### ISSUE TITLE
Styling tooltips on surveyjs questions

### ISSUE THREAD

**Issue by ashygk** [surveyjs/survey-library#1001]
### Are you requesting a feature, reporting a bug or ask a question?

Question/ feature request

### What is the current behavior?

Tooltips achieved on survey questions using onAfterRenderQuestion event.

### What is the expected behavior?

How to create styles to those tooltips on survey questions
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@ashygk What do you mean? It is a custom html code, just put any css or change as you wish for you app.

Thank you,
Andrew

**Comment by ashygk** [comment]
i do not see any demo for tooltips using custom html code

**Comment by dmitrykurmanov** [comment]
Here the working example: https://plnkr.co/edit/0vXbRM?p=preview based on this example: https://surveyjs.io/Examples/Library/?id=survey-afterrender&platform=jQuery&theme=default
