### ISSUE TITLE
Difference in output HasOther item between SurveyJS Editor & Library

### ISSUE THREAD

**Issue by Lynn42** [surveyjs/survey-library#1019]
### Are you requesting a feature, reporting a bug or ask a question?

Possibly reporting a bug

### What is the current behavior?

There seems to be a difference in result string passed back by the library and the result string passed back by the surveyjs editor, when it comes to the 'has other item'. See example below.

### What is the expected behavior?

I would expect the result string of the library to be the same as the one the surveyjs editor produces. 
The result string of the surveyjs editor is correct.

### How would you reproduce the current behavior (if this is a bug)?

1. Use this Survey Structure

`{
"clearInvisibleValues": "onHidden",
"completeText": "Verzenden",
"completedHtml": "<div class=\"jumbotron\"><h3>Bedankt voor het invullen van het formulier.</h3><h4>Uw informatie is succesvol opgeslagen.</h4></div>",
"locale": "nl",
"pages": [
  {
   "elements": [
    {
     "type": "checkbox",
     "name": "Sporten",
     "title": {
      "nl": "Welke sporten vind je leuk?"
     },
     "hasOther": true,
     "choices": [
      "Handbal",
      "Voetbal",
      "Softbal"
     ]
    }
   ],
   "name": "page1"
  }
],
"requiredText": "",
"showQuestionNumbers": "off"
}
`
2. Choose answer ‘Other’ for ‘Welke sporten vind je leuk?’ and enter a comment value, eg ‘Tennis’. 
3. Change the answer to ‘Handbal’, deselecting the answer ‘Other’ (the box for the comment value now disappears)
4. Complete the survey.

When doing this when testing the survey in the SurveyJS Editor, you get the expected result string back:
“{"Sporten":["Handbal"]}”

However, when doing this using the SurveyJS library, you still also get the other item back (though that was no longer selected): 
"{"Sporten":["Handbal"],"Sporten-Comment":"Tennis"}"

### Specify your surveyjs version:
Version SurveyJs library: 1.0.0
Version SurveyJs Editor: 1.0.0

**Comment by andrewtelnov** [comment]
@Lynn42 What SurveyJS Library and platform do you use?
Here is [the example](https://plnkr.co/edit/NubzetvYr00Eq0H4pnto?p=preview) with the latest version of SurveyJS and jQuery.
If you are talking about v1.0.0 then we very likely fixed the issue. We were building jQuery version using our react code and pReact library - it gives us different small problems.
We are building jQuery based on knockout version and we have less issues.

Thank you,
Andrew

**Comment by Lynn42** [comment]
We will try to update first then and see if that solves things. Thank you! Do you know when the next maintenance update is planned? We are waiting on that for updating because then we can take along the fix of https://github.com/surveyjs/surveyjs/issues/999

**Comment by Lynn42** [comment]
We updated to the new version and now understand why it works differently for us (and how to possibly fix this). 

I do have another question based on your example on Plunker. When ClearInvisibleValues is set to OnHidden (as it is in the example, right?), I would expect the text filled out in the comment to be cleared immediately when 'other' is un-checked, and not only after completing the survey.

So in the example, I mean the following scenario:
- Click 'Andere'
- Enter value 'Tennis'
- Unclick 'Andere'
- Then click 'Andere' again --> Tennis is still there,

I had understood OnHidden to mean that in a situation as this, 'Tennis' would be cleared as soon as it becomes invisible (i.e. is hidden). And when ClearInvisibleValues is set to 'OnComplete', it will leave it there (just as it does now), and only clears it when you complete the survey. But maybe I just don't understand how the functionality is supposed to work?

**Comment by andrewtelnov** [comment]
@Lynn42 onHidden, it means that the value clears when the question is hidden.
In fact, the value, after you have unclicked "Andere" is null - "Tennis" is cached into text box input. We may, of course, clear it, but I do not think the current behavior is a bug.
A user, enteter the "Tennis" then decided to unclick "Andere" then click it again, he may expect to see "Tennis" there.
What do you think?

Thank you,
Andrew

**Comment by Lynn42** [comment]
Hmm I see your point about the user perspective. However, this makes the distinction between onHidden & onComplete a bit fuzzy. 

For example, when you use this survey structure:
`{
 "locale": "nl",
 "completedHtml": "<div class=\"jumbotron\"><h3>Bedankt voor het invullen van het formulier.</h3><h4>Uw informatie is succesvol opgeslagen.</h4></div>",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "checkbox",
     "name": "Sporten",
     "title": {
      "nl": "Welke sporten vind je leuk?"
     },
     "hasOther": true,
     "choices": [
      "Handbal",
      "Voetbal",
      "Softbal"
     ]
    },
    {
     "type": "radiogroup",
     "name": "question1",
     "visibleIf": "{Sporten} contain Handbal",
     "choices": [
      "item1",
      "item2",
      "item3"
     ]
    }
   ]
  }
 ],
 "showQuestionNumbers": "off",
 "clearInvisibleValues": "onHidden",
 "completeText": "Verzenden",
 "requiredText": ""
}`

The 'has other' item works like you describe --> 'Tennis' isn't cleared when you unclick the hasOther option. However, the answer to question1 in the structure above, which is only visible if you select 'Handbal' in the first question, _is_ cleared when 'Handbal' is unselected. I think it would be easier to use the same logic everywhere: when onHidden is selected, unchecking an answer which results in another question disappearing, will clear that value (including on the front-end).

But I agree with you that it is not necessarily a bug, but more a consistency thing.

**Comment by andrewtelnov** [comment]
@Lynn42 We will keep it in mind, but to be honest I don't know what is better, leave as it is or clear other values. I think I will keep the current behavior, since we do not need to do anything, and if you are not sure, that your changes improve the product, then it is better do nothing :)

Thank you,
Andrew

**Comment by Lynn42** [comment]
I agree that is the best decision to make right now!
