### ISSUE TITLE
Render Custom Inputs

### ISSUE THREAD

**Issue by tximpa91** [surveyjs/survey-library#1024]
### Are you requesting a feature, reporting a bug or ask a question?
I am asking a question

### What is the current behavior?

I dont know
### What is the expected behavior?

Can override the render method (if exists) ? for adding  custom inputs. Like if a want to put another Range input or select.

If this is already implemented i would like to know how to  do it . I think that i can do it afterRender events  but i would be nice if can be done  before render 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version: Versión 65.0.3325.181 (Build oficial) (64 bits)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version:1.0.14

**Comment by andrewtelnov** [comment]
@tximpa91 I am not sure I got you completely.
You may change the rendering by using onAfterRender event, here is [the demo](https://surveyjs.io/Examples/Library/?id=survey-afterrender)
Another way is to create a custom widget. Please go to [this repo](https://github.com/surveyjs/widgets), section **4. Add your own custom widget** and see the plunker examples.

Thank you,
Andrew
