### ISSUE TITLE
Show CompletedHtml after survey has saved successfully?

### ISSUE THREAD

**Issue by michaelh15** [surveyjs/survey-library#1028]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
The completedHtml is shown before the onComplete event is fired

### What is the expected behavior?
I would expect the completedHtml to be shown after the event is complete or is there another completedHtml property to use. E.g. afterCompletedHtml? 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@michaelh15 survey.onComplete event has options parameters. You may use them. Here is [the example](https://plnkr.co/edit/75nXj6?p=preview)

Thank you,
Andrew

**Comment by michaelh15** [comment]
Thanks for the quick reply Andrew ... I am aware of those options, but they don't quite fulfill my use-case. Is there no way to hide the completedHtml in the initial configuration and then to show it in the onComplete event?

**Comment by andrewtelnov** [comment]
@michaelh15 You may completely hide the survey div on complete and show your own text or whatever you want. 

Thank you,
Andrew
