### ISSUE TITLE
Responsive mandatory question

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/survey-library#1062]
### Are you requesting a feature, reporting a bug or ask a question?
Ask a question

### What is the current behavior?
When mandatory question is not answered before submit survey, user come back to that question, answer question, warning message still appear on the question. warning message only disappear when user submit survey.

### What is the expected behavior?
When mandatory question is not answered before submit survey, user come back to that question, answer question, warning message disappear on the question responsively, not on submit survey. 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
https://plnkr.co/edit/?p=preview

**Comment by tsv2013** [comment]
Current behaviour doesn't allow user to leave the page or submit survey while mandatory questions are not answered. And one showld answer the questions before will be able to go to next page or complete survey. You can check this example - https://surveyjs.io/Examples/Library/?id=validators-standard&platform=jQuery&theme=default

Are you talking about immediate validation - immediately after question value has been changed? THis was discussed in this thread - https://github.com/surveyjs/surveyjs/issues/668

**Comment by xiuzhen1103** [comment]
@tsv2013  Sorry I didn't explain well. My question is if you could do real-time update for mandatory question? If user submit question, mandatory question is not answer, do not able to submit survey, red error appears, user answer mandatory question, error automatically disppear on this question

**Comment by xiuzhen1103** [comment]
hi @tsv2013  thanks for referencing the issue,  is it possible if immediate validation happens after first submit survey, please?

**Comment by xiuzhen1103** [comment]
hi @andrewtelnov Thanks, this is immediate update, my question is immediate update only happens after first time click submit button?

**Comment by andrewtelnov** [comment]
@xiuzhen1103 I am sorry, I do not understand what do you mean under "immediate update"
There is onValueChanged event. It fires on value changed. On this event, in this example, we check if the value can pass the validation, if not then show the errors.

If you want to disable the next button, then you have to implement your own nativation: https://surveyjs.io/Examples/Library/?id=survey-customnavigation
Finally, initially, you may onCurrentPageChanged event, you may call surve.currentPage.hasErrors(false, false), if it returns true, it means there is at list one error.
hasErrors(false, false); the first parameter show errors if true,  and second parameter - focus on the first input with error if true.

Thank you,
Andrew

**Comment by xiuzhen1103** [comment]
sorry, I didn't explain well, 
In this plunk, onValueChange enabled without submit survey, it there any chance that onValueChange enabled after I click submit button? nothing to do with next page.

**Comment by andrewtelnov** [comment]
@xiuzhen1103 You can have validator for any question. We have recently added the expression validator, where you can put any boolean expression and it will raise the error if the expression returns false.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
We have survey.checkErrorsMode property now. ``survey.checkErrorsMode = "onValueChanged"`` will do what you need.

Thank you,
Andrew
