### ISSUE TITLE
Change text timerInfoText in Quiz

### ISSUE THREAD

**Issue by mflash123** [surveyjs/survey-library#1110]
In Quiz I have default text which shows how mane seconds spend and left in Quiz. I want change default text.

**Tested page URL:**
https://surveyjs.io/Examples/Library/?id=survey-quiz

**When u start quiz, u can see that message:**

Html:
`<div data-bind="text:koTimerInfoText">You have spent..</div>`
So, I want change text in that div selector.

**Comment by andrewtelnov** [comment]
@mflash123 Sure here is all localizable quiz strings in English:
```
  timerMin: "min",
  timerSec: "sec",
  timerSpentAll: "You have spent {0} on this page and {1} in total.",
  timerSpentPage: "You have spent {0} on this page.",
  timerSpentSurvey: "You have spent {0} in total.",
  timerLimitAll:
    "You have spent {0} of {1} on this page and {2} of {3} in total.",
  timerLimitPage: "You have spent {0} of {1} on this page.",
  timerLimitSurvey: "You have spent {0} of {1} in total.",
```
You may change any of them as [described here](https://surveyjs.io/Documentation/Library/#localization)

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@mflash123 You may always make a progress bar outside the survey div. You have all needed properties and events.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
You can use [survey.onTimerPanelInfoText](https://surveyjs.io/Documentation/Library?id=surveymodel#onTimerPanelInfoText) event.

Thank you,
Andrew
