### ISSUE TITLE
Using iCheck in react app, how to integrate?

### ISSUE THREAD

**Issue by cliewdevelop** [surveyjs/survey-library#1159]
### Are you requesting a feature, reporting a bug or ask a question?
Ask a question.
Hello,

May I ask how I can implement the following:
https://plnkr.co/edit/BUTWvvDYmqME5UFlShbe?p=preview
without using JQuery? 

I have a react application that does not use JQuery. Basically above seems to just be appending css classes to certain elements, and handling some of the checked/unchecked behaviours, so I think it definitely can be done with just standard JavaScript.

Thank you!

In all the examples that I've found, so far its all JQuery, including the official example.
https://surveyjs.io/Examples/Library/?id=custom-widget-icheck&platform=Reactjs

Thank you!

### Specify your

* browser: Chrome 
* browser version: 66.0.3359.181
* surveyjs platform: React with no JQuery
* surveyjs version: 1.0.10

**Comment by andrewtelnov** [comment]
@cliewdevelop You have to find the widget that does what you need and doesn't require jQuery library. 
Here is [the example of integrating a widget](https://plnkr.co/edit/HdnYE5?p=preview) with comments.

Thank you,
Andrew
