### ISSUE TITLE
Single Question Custom CSS Class (Vuejs)

### ISSUE THREAD

**Issue by timaronan** [surveyjs/survey-library#1179]
### Are you requesting a feature, reporting a bug or ask a question?
Requesting a feature.

### What is the current behavior?
You can customize classes by component type.

### What is the expected behavior?
Add custom CSS class to a single question.

#### Provide the test code and the tested page URL (if applicable)
```
{
	customClass : "custom_class_style",
	defaultValue : "This is a name",
	indent : 0,
	isRequired : true,
	name : "first_name",
	title : "First Name",
	type : "text",
}
```

* surveyjs platform : Vue
* surveyjs version : "survey-vue": "^1.0.26"

**Comment by tsv2013** [comment]
You can use the [onUpdateQuestionCssClasses](https://surveyjs.io/Documentation/Library/?id=surveymodel#onUpdateQuestionCssClasses) event. Here is the sample - https://surveyjs.io/Examples/Library/?id=survey-cssclasses&platform=jQuery&theme=default
