### ISSUE TITLE
Statistics for each question

### ISSUE THREAD

**Issue by mkgn** [surveyjs/survey-library#1191]
This is more of a question, but can be suggestion as well

* surveyjs platform latest angular version

In google forms, it shows real time charts for each question based on the responses.

Can anyone direct me on how i might be able to do similar thing? I might try to do a plugin for this.

**Comment by tsv2013** [comment]
Take a look at this sample - http://localhost:62946/Examples/Library/?id=service-result&platform=jQuery&theme=default
It draws chart with all survey results after survey completed

**Comment by tsv2013** [comment]
@qublibjohnny Too much results. If you complete survey and wait a bit, you'll see the chart. We need either  to cut results or improve sample backend performance :-)

**Comment by qublibjohnny** [comment]
Thanks :)

**Comment by YuanZhencai** [comment]
i also want this feature

**Comment by errazki1995** [comment]
may i know what should i load as an input , to get the results , the result of that survey clicked or all surveys?

**Comment by errazki1995** [comment]
i didn't quite get this function behavior is it just to Post an answer? 
var surveySendResult = function (s, options) {
    var key = Object.keys(options);
    alert(key);
    if (options.success) {
        s.getResult('a15eee7a-9418-4eb4-9671-2009c8ff6b24', 'langs');
    }
};

**Comment by andrewtelnov** [comment]
We have released [Analytics](https://surveyjs.io/Overview/Analytics) library.
