### ISSUE TITLE
Save multiple surveys with one SAVE button

### ISSUE THREAD

**Issue by ashygk** [surveyjs/survey-library#1192]
### Are you requesting a feature, reporting a bug or asking a question?

Question / Request a feature

### What is the current behavior?

Saving a survey individually is fine and working

### What is the expected behavior?

Is there a possibility to save multiple surveys with a single save button? 

### How would you reproduce the current behavior (if this is a bug)?
We have a single survey each in multiple expansion panels. (Angular material is used for expansion panels).
we have to implement, Page level saving, i.e., surveys from all expansion panels needs to be saved with a single save button which is at the end of the page.

![capture](https://user-images.githubusercontent.com/36975459/41791016-1067d39e-761a-11e8-8420-9b28cd06356a.PNG)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):  angular 5
* surveyjs version: 1.0.25

**Comment by tsv2013** [comment]
If you create multiple expansion panels, you can collect links to each SurveyJS editor instance.
So you can iterate through the editor instances and call `editor.saveButtonClick()` function.

**Comment by ashygk** [comment]
We don't have surveyjs editor within our application. We create surveys using online survey builder and copy the json in our local db

**Comment by andrewtelnov** [comment]
@ashygk Do you want do save all surveys?
every survey has the data property JSON format, survey.data. You may get the data from the current page as: survey.currentPage.getValue() - it will return values in JSON format all visibles questions on the current page.
Please read this [help topic](https://surveyjs.io/Documentation/Library/#data) for more information.

Thank you,
Andrew

**Comment by ashygk** [comment]
Hi, I have question related to diff issue. Could you please check my question there
[https://github.com/surveyjs/surveyjs/issues/384](url)
