### ISSUE TITLE
[Question] How to add option to select field of Matrix Multi Choice

### ISSUE THREAD

**Issue by nguyencuonginfo** [surveyjs/survey-library#1198]
I have 2 questions in a survey.
-Question1: Matrix (Dymanic Rows) have a simple text input field.

Qutestion2: Matrix (Multi Choice) have a Dropdown field.

So, how can i update Dropdown field of question2 based on the value i added in question 1?

Example: question1 i added 2 lines: Eng, US
So in dropdown of question2, i'll have 2 options: Eng and US.

Thanks.

**Comment by andrewtelnov** [comment]
@nguyencuonginfo You may implement this functionality [onValueChanged event](https://surveyjs.io/Documentation/Library/?id=surveymodel#onValueChanged)

Thank you,
Andrew

**Comment by nguyencuonginfo** [comment]
@andrewtelnov thanks for your support.
I did it before, but the value dosn't take change to the dropdown of matrix (multi choice)

**Comment by andrewtelnov** [comment]
@nguyencuonginfo I am not sure I got you completely. Could you please create a small plunker example with your two matrixes and tell exactly what do you want to do?
We will fork your plunker and correct it to make it work.

Thank you,
Andrew

**Comment by nguyencuonginfo** [comment]
hi @andrewtelnov 
Here is my example on plunker: 
https://plnkr.co/edit/KGGC8ByyEvb1H8GEZnPp?p=preview

In that example you can see, i have 2 fields:
CAND_COURSES is a Matrix (dynamic rows) and
STRATEGY_VALUES  is a Matrix (multi choices)
What i want to do here is: when i enter value and add new rows in CAND_COURSES, so the options of dropdown of  STRATEGY_VALUES   will be changed based values i entered in CAND_COURSES.
![image](https://user-images.githubusercontent.com/5045469/41879598-83408d60-7904-11e8-8b52-94d0fcf3b3b4.png)
In above example, options of "Column 2" will be "1 this is one" and "2 this is two".

Thanks for your help.
Regards,
Cuong Nguyen

**Comment by andrewtelnov** [comment]
@nguyencuonginfo Here is the [fork version](https://plnkr.co/edit/HzUtiviw6Lshnrc0H9Kd?p=preview) of your plunker

Thank you,
Andrew

**Comment by nguyencuonginfo** [comment]
Thank  you very much, @andrewtelnov 
It's exactly what i need.

Thank you.
Cuong Nguyen
