### ISSUE TITLE
Result Analysis

### ISSUE THREAD

**Issue by sitzvino** [surveyjs/survey-library#1213]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a Question?
Scenario is the Result Jason is stored in the local database.
Question is How do we parse the Jason.I understand you provide the SurveryJS services which is for your hosted database, 
1) how do we analyse the Jason which is stored locally.Do you provide any Javascript Api to group the answers for a question, how to do various type of analysis.
2) Is there a tool to parse Jason and put it into DB based on the Jason provided.
3) what are the various options currently provided for own db.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@sitzvino Please review our examples for PHP, ASP.Net and NodeJS: https://surveyjs.io/Examples/Service/

Thank you,
Andrew
