### ISSUE TITLE
Remove button text is defaulting to "Remove"

### ISSUE THREAD

**Issue by ashygk** [surveyjs/survey-library#1219]
### Are you requesting a feature, reporting a bug or asking a question?
bug/question

### What is the current behavior?
In a matrix dynamic/dynamic panels, when removebuttontext property is set to empty string "", it is defaulting  to Remove

### What is the expected behavior?

when removebuttontext property is set to empty string "", the button should have no text

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version: 
* surveyjs platform (angular or react or jquery or knockout or vue): angular 5
* surveyjs version: 1.0.30

**Comment by ashygk** [comment]
Tried the below snippet, but doesn't work.
`    surveyModel.onMatrixRowAdded.add((survey, options) => {
      let str = "";
      options.question.removeRowText = str;
    })`

**Comment by andrewtelnov** [comment]
@ashygk You may use a white space. Adding an empty string, means that you want to have the default value.

Thank you,
Andrew

**Comment by ashygk** [comment]
We are displaying an image (trash can) instead of remove button.
If I use a white space, there is going to be some space after the trash can which is visible when clicked because of border its border.
![capture](https://user-images.githubusercontent.com/36975459/42400728-5a6f773e-8138-11e8-8ba5-acce3939775c.PNG)

**Comment by andrewtelnov** [comment]
@ashygk You may set empty string to "removeRow" in the localization as well. In this case, by default all remove button will have empty string. I guess, this is what you want.
Please read [this topic](https://surveyjs.io/Documentation/Library/#localization) to see how to change the default strings.

Thank you,
Andrew

**Comment by ashygk** [comment]
Tried the above, setting my locale to en and added default property to "" and en property to "" for remove text. It is still taking the default property and Remove is being displayed as remove text. Same result if the default property is removed and just kept en: ""
