### ISSUE TITLE
Follow up options set similar to follow up questions based on visibility

### ISSUE THREAD

**Issue by ashygk** [surveyjs/survey-library#1221]
### Are you requesting a feature, reporting a bug or asking a question?

question/feature

### What is the current behavior?

Currently, we have the ability to have follow up questions to be displayed based on visibility conditions.

### What is the expected behavior?

Is there a possibility to have MULTIPLE options set for a single question? (ex. for a dropdown). If I have a dropdown I need to have multiple 'choice sets' for the same question 
And each set should be visible based on the choices selected in previous options sets/ previous questions.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular 5
* surveyjs version: 1.0.30

**Comment by andrewtelnov** [comment]
@ashygk Are you looking for [filtering choices functionality](https://surveyjs.io/Documentation/Library/#itemvaluesfiltering)?

Thank you,
Andrew

**Comment by ashygk** [comment]
No..Lets take an example of dropdown.
Question: Please select all the alphabets from your name. (Ex: my name is AMY)
There should be 3 dropdown sets available for single question with choices like [A,B,C,D]  [L,M,N,O] [W,X,Y,Z]. And choices set should be visible based on the option selected from each set

**Comment by andrewtelnov** [comment]
@ashygk There are two options:
1) create several questions with different names, visibleIf and choices properties, but with the same valueName
2) Names all letters from alphabets and create choicesVisibleIf with custom function: 
isLetterUse({name}, {item}), where name is AMY and {item} is the current item in choices, a current letter, from A to Z.

Thank you,
Andrew

**Comment by ashygk** [comment]
Can you elaborate option 2.. i do not understand properly

**Comment by andrewtelnov** [comment]
@ashygk Here is [the example](https://plnkr.co/edit/tbSBFXiunLq8d5n18SVP?p=preview)

Thank you,
Andrew

**Comment by ashygk** [comment]
That is not how it should work. Please see the below. I'm looking for something like this. It should be under same question
![webp net-gifmaker](https://user-images.githubusercontent.com/36975459/42591546-9f6e3d70-850c-11e8-8010-73192cbbddcb.gif)

**Comment by andrewtelnov** [comment]
@ashygk Sorry, I could not understand the task. Could you please more specific then. You are choosing 'a' and you are getting 'b', you are choocing  'x' and you are getting 'y' and/or 'z'.

Thank you,
Andrew

**Comment by ashygk** [comment]
Amb Assistance is a dropdown question(in a matrix dynamic). When an option is selected from the dropdown, another dropdown with different options(In this case, x2) is displayed.

**Comment by andrewtelnov** [comment]
@ashygk What is the rule of showing options in the second dropdown? I do not understand your task.

Thank you,
Andrew

**Comment by ashygk** [comment]
Second dropdown is visible only when few options are selected from first dropdown. (Options like MIN A, which is selected in the GIF above)

**Comment by andrewtelnov** [comment]
You may use visibleIf property of the column like:
`yourSecondColumn.visibleIf = "{row.youFirstColumnName} = 'MinA'"`

Thank you,
Andrew

**Comment by ashygk** [comment]
Yes, we use that if there is a different column. But my requirement here is, for the same column, we should have two dropdowns

**Comment by andrewtelnov** [comment]
@ashygk I am lost. Does it mean that the first dropdown is hidden and the second is shown?
You may set the criteria for every choice item as:
```
choices: [
{value: "My Value1", visibleIf: "{youQuestionName} = 'MainA'"},
{value: "My Value2", visibleIf: "{youQuestionName} <> 'MainA'"},
...
]
```

Thank you,
Andrew

**Comment by ashygk** [comment]
Yes, one dropdown is shown at the beginning and second is hidden. Based on the choice selected in first dropdown, second is shown.
NOTE: these two dropdowns belong to same column.

**Comment by ashygk** [comment]
`choices: [
{value: "My Value1", visibleIf: "{youQuestionName} = 'MainA'"},
{value: "My Value2", visibleIf: "{youQuestionName} <> 'MainA'"},
...
]` 

In this snippet we are having all choices in single dropdown. isn't it?

**Comment by andrewtelnov** [comment]
We do not have this functionality. Why can't you have the dropdown in another column?
Right now in one cell you may have only one editor. 
You may implement something using our matrix events, but you would have to write, I am afraid a lot of, code.

Thank you,
Andrew

**Comment by ashygk** [comment]
We needed that functionality because all the dropdown answers should belong in a single set(for that column)

**Comment by ashygk** [comment]
Ok. the problem I have with having two columns is, I donot want to display the header of second column. If I have visible if condition for second dropdown, the header of second column is still being displayed.

**Comment by andrewtelnov** [comment]
@ashygk You may create the second column on onMatrixCellValueChanged if it doesn't exist yet.
Another option is to render a text or something onMatrixAfterCellRender event in the second column if cell question is invisible.

Thank you,
Andrew

**Comment by ashygk** [comment]
@andrewtelnov Could you please create an example using the onmatrixcellvaluechanged for this scenario?
