### ISSUE TITLE
Total survey time tracking without timer on the screen

### ISSUE THREAD

**Issue by vihansri** [surveyjs/survey-library#1224]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question

### What is the current behavior?

Cannot track the total time of a survey, without displaying a timer on the screen. 

### What is the expected behavior?

Would like to know how long a survey takes without showing it on the screen as a timer. 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
Survey model has the [timeSpent](https://surveyjs.io/Documentation/Library/?id=surveymodel#timeSpent) property - the time in seconds end-user spends on the survey. Does it fit your needs?

**Comment by vihansri** [comment]
@tsv2013  for some reason the timeSpent always returns 0 for me.

**Comment by andrewtelnov** [comment]
@vihansri Do you call [survey.startTimer()](https://surveyjs.io/Documentation/Library/?id=surveymodel#startTimer)?
You should call it and onComplete call [survey.stopTimer()](https://surveyjs.io/Documentation/Library/?id=surveymodel#stopTimer) manually.

Thank you,
Andrew
