### ISSUE TITLE
Render Angular Components in HTML block

### ISSUE THREAD

**Issue by wollerman** [surveyjs/survey-library#1227]
### Are you requesting a feature, reporting a bug or asking a question?

feature

### What is the current behavior?

Currently placing a custom Angular component inside of an HTML block does not render. For example:
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "html",
     "name": "question1",
     "html": "<my-custom-component [message]=\"'My Message.'\"></my-custom-component>"
    }
   ]
  }
 ]
}
```

The `<my-custom-component>` will not be picked up by the Angular rendering.

### What is the expected behavior?

To see the custom component correctly.

**Comment by tsv2013** [comment]
It isn't possible with the current implementation of the survey-angular library: survey-angular library is a single angular survey component which inner content is rendered via survey-knockout library.
One our customer was rendering angular components inside a custom widget, but he created a new ng-app instance for every inner angular component.
This probably can be overcame if survey-angular library will be rewritten in native angular components, but it will require time and resources.
JFYI - @andrewtelnov @dmitrykurmanov
