### ISSUE TITLE
How to customize progress.html template?

### ISSUE THREAD

**Issue by mflash123** [surveyjs/survey-library#1230]
I am asking a question

I want make custom html code which i find here: https://github.com/surveyjs/surveyjs/blob/master/src/knockout/templates/progress.html

I cant understand, how can I apply my custom progress.html ?

**Comment by tsv2013** [comment]
I think you are looking for this sample - https://surveyjs.io/Examples/Library/?id=survey-customnavigation&platform=jQuery&theme=default
