### ISSUE TITLE
OnModified Not called with undo redo buttons

### ISSUE THREAD

**Issue by rabberbock** [surveyjs/survey-library#1231]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the current behavior?
When using the SurveyJs builder, I am able to auto-save the survey when the user interact with the builder because the onModified callback is called. However, when the user uses undo/redo buttons, the onModified callback is not called. 

### What is the expected behavior?
Is this the expected behavior? If so, how can I auto-save (to a backend) when using undo/redo?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: 
* browser version:
* surveyjs platform - react
* surveyjs version: 1.0.32

**Comment by andrewtelnov** [comment]
@rabberbock You are right. We should call setModified function on undo/redo operations.

Thank you,
Andrew

**Comment by tsv2013** [comment]
@rabberbock Could you please create issues on the editor in the corresponding repo - https://github.com/surveyjs/editor/issues ?

**Comment by andrewtelnov** [comment]
@rabberbock After some investigation, I find out that it is a correct behavior.
You should use `editor.saveSurveyFunc` for saving the survey.
Please read the following [topic in the documentation](https://surveyjs.io/Documentation/Builder/#loadsavesurvey)

Thank you,
Andrew

**Comment by rabberbock** [comment]
@andrewtelnov Okay, great. Thanks! Will try that out
