### ISSUE TITLE
Not able to add maxLength to comment column in a matrix dynamic

### ISSUE THREAD

**Issue by ashygk** [surveyjs/survey-library#1233]
### Are you requesting a feature, reporting a bug or asking a question?

bug/question

### What is the current behavior?

maxLength property works for a question type Comment

### What is the expected behavior?

maxLength property should work the same way if a Comment is included as a column in Matrixdynamic

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular 5
* surveyjs version: 1.0.31

**Comment by tsv2013** [comment]
I've fixed it. Fix will be available in the nearest update, most likely tomorrow

**Comment by ashygk** [comment]
From your commit above, it looks like you have added maxLength property to text field, not comment field

**Comment by ashygk** [comment]
@tsv2013

**Comment by tsv2013** [comment]
Sorry. My bad. Inserted in wrong place :-)

**Comment by tsv2013** [comment]
I've check it locally for both column types.

**Comment by ashygk** [comment]
Thanks. I created a duplicate ticket because I didnt have the option of reopening the ticket.
Kindly, guide me through how to re open

**Comment by tsv2013** [comment]
Sure. This button is in the bottom of the new comment input area. Please check the attached screenshot;
![image](https://user-images.githubusercontent.com/3013415/42928390-d2b236f8-8b3f-11e8-8fbb-7e0a7d2fa762.png)

**Comment by ashygk** [comment]
I think we donot have the option of re-openig the ticket. Only the owners of repository might have, which is why I had to open a new ticket.

![capture](https://user-images.githubusercontent.com/36975459/42950569-f495c722-8b39-11e8-9f44-4d7c16fc5281.PNG)

**Comment by tsv2013** [comment]
Can you try it with the issue where you are owner?

**Comment by ashygk** [comment]
Its the same. the above screenshot is of issue which I openend.

**Comment by tsv2013** [comment]
Not good. I was thinking one can reopen the issue at any time. Ok, I'll keep'em open.
