### ISSUE TITLE
update Height of Comment Question with Pre-populated data

### ISSUE THREAD

**Issue by wollerman** [surveyjs/survey-library#1235]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question.

### What is the current behavior?

If I set the value of a comment question with `survey.data` and the number of lines is bigger than the default, the text is cut off. Is there a way to expand the comment question height to show the full content?

[Looking at the API](https://surveyjs.io/Documentation/Library/?id=QuestionBase), I see a `setWidth()` but nothing for `height`.

### Example:
Place the below block into something like the builder:

```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "comment",
     "name": "question1",
     "defaultValue": "test1,\ntest2,\ntest3,\ntest4,\ntest5,\ntest6",
     "placeHolder": "Medication 1,\nMedication 2, \nMedication 3"
    }
   ]
  }
 ]
}
```

And it will look like:
![image](https://user-images.githubusercontent.com/1610241/42772123-4c16c798-88de-11e8-9ad6-a63a16511166.png)

**Comment by andrewtelnov** [comment]
@wollerman Please set [rows](https://surveyjs.io/Documentation/Library/?id=questioncommentmodel#rows) property to 7 or any other value.

Thank you,
Andrew
