### ISSUE TITLE
add allowChanging options into onCurrentPageChanging event

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#1240]
By setting options.allowChanging to false (true is default) the page would not be changed.
```
survey.onCurrentPageChanging.add(function (sender, options){
 //do some checks based on options.oldCurrentPage and options.newCurrentPage
  options.allowChanging = false; //disable the current page changing
});
```

**Comment by jjzjx118** [comment]
this option is not work in my demo : https://stackblitz.com/edit/react-surveyjs-29dj . can you take a look at this?

**Comment by tsv2013** [comment]
You need to use the https://www.surveyjs.io/Documentation/Library?id=surveymodel#onCurrentPageChanging event.

Here is the working sample - https://plnkr.co/edit/m46drJFIfi2tdlvXM4ZE?p=preview
