### ISSUE TITLE
Can we have nested matrix dynamic?

### ISSUE THREAD

**Issue by ashygk** [surveyjs/survey-library#1245]
### Are you requesting a feature, reporting a bug or asking a question?

question/feature

### What is the current behavior?

Mtrix dynamic works fine

### What is the expected behavior?

Can we have a feature where we have a matrix dynamic within another matrix dynamic? (like nested?)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular 5
* surveyjs version: 1.0.33

**Comment by andrewtelnov** [comment]
@ashygk I would suggest to use matrix dynamic inside the panel dynamic.
You may read more about it [here](https://hackernoon.com/surveyjs-an-open-source-javascript-survey-library-with-versions-for-angular-2-react-vue-2086d988b974), section Dynamic Panel: Dealing with List Data.

Thank you,
Andrew
