### ISSUE TITLE
Is it possible to add buttons as a columns within matrix dynamic 

### ISSUE THREAD

**Issue by ashygk** [surveyjs/survey-library#1247]
### Are you requesting a feature, reporting a bug or asking a question?

question/feature

### What is the current behavior?

Right now, we have text/comment/dropdown/checkbox.. as columns in matrix dynamic

### What is the expected behavior?

Can we have a celltype as html for matrixdynamic

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular 5
* surveyjs version: 1.0.33

**Comment by andrewtelnov** [comment]
@ashygk What are you going to do with on clicking this button?
You may use [onMatrixAfterCellRender](https://surveyjs.io/Documentation/Library/?id=surveymodel#onMatrixAfterCellRender) event to render a button.

Thank you,
Andrew

**Comment by ashygk** [comment]
The thing is we need to have an archive button beside remove button for each row in a matrix dynamic. And add some functionality to it when archive button is clicked.

**Comment by ashygk** [comment]
How do I manually make a matrix dynamic row to be deleted?

**Comment by andrewtelnov** [comment]
@ashygk You may call functions [removeRow](https://surveyjs.io/Documentation/Library/?id=questionmatrixdynamicmodel#removeRow) or [removeRowUI](https://surveyjs.io/Documentation/Library/?id=questionmatrixdynamicmodel#removeRowUI)

What is wrong with the default remove row functionality?

Thank you,
Andrew

**Comment by ashygk** [comment]
@andrewtelnov  we need both archive and remove buttons displayed for each row.
Could you please update your plunkr example using the removerow. I have used removerow method and it just clears the text in the rows but doesnt actually delete the row.

**Comment by andrewtelnov** [comment]
@ashygk Sure, It is updated.

Thank you,
Andrew

**Comment by ashygk** [comment]
Question: If I have a confirm delete text property set and click the new button(supposedly to archive, but soft delete) I have set an alert for that button saying "do you want to archive?". But when clicking, i'm getting two alert boxes.
 one to archive and one is asking whether to delete

**Comment by andrewtelnov** [comment]
@ashygk Please change removeRowUI function to removeRow. It would not show the confirm modal window.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@ashygk Sounds as a bug to me. Could you please create another issue?

Thank you,
Andrew

**Comment by ashygk** [comment]
Created #1249
