### ISSUE TITLE
dynamically set default value

### ISSUE THREAD

**Issue by rjbks** [surveyjs/survey-library#1248]
### Are you requesting a feature, reporting a bug or asking a question?
feature/question

### What is the current behavior?
`defaultValue` is static

### What is the expected behavior?
dynamically fill in the default value based on other form elements

Is there a way to dynamically set the default value for a question? 

For example: The user adds several panels, one of the questions in the panels is "What order should this panel be presented in?" 
I would like the default value to be the number of sibling panels + 1, I would ideally like the dropdown menu items to be set dynamically so that adding and deleting questions will update the menu items for every question that includes the Order question. The docs and issues section here specify using the `survey.onValueChange` function to accomplish this (assuming I understood the docs correctly) but using an expression/function in the `defaultValue` field seems like a much more direct approach.

Thoughts?

**Comment by andrewtelnov** [comment]
@rjbks Are you talking about panel dynamic and matrix dynamic questions?
They have defaultPanelValue and defaultRowValue, I was thinking about adding a new bolean properties: defaultLastPanelValue/defaultLastRowValue.
If it is true, then a new row/panel value will be a merge: set defaultPanelValue and then override with none empty values in the last panel values.
Is it what you mean?

Thank you,
Andrew
