### ISSUE TITLE
onselect image imagepicker

### ISSUE THREAD

**Issue by kopsinnovaties** [surveyjs/survey-library#1254]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
Cant seem to find trigger onchange value imagepicker.
I want my script to do something when a user selects an image (imagepicker).
How to do this?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version:

**Comment by tsv2013** [comment]
You can use the [onValueChanged](https://surveyjs.io/Documentation/Library/?id=surveymodel#onValueChanged) event:

```JS
survey.onValueChanged.add(function(sender, options) {
 // handler code
});
```
