### ISSUE TITLE
Dates in matrix rows should be able to re-order

### ISSUE THREAD

**Issue by ashygk** [surveyjs/survey-library#1256]
### Are you requesting a feature, reporting a bug or asking a question?

question/feature

### What is the current behavior?

Date fields(custom datepicker) can be added to a matrix dynamic

### What is the expected behavior?

Rows in matrix dynamic should be able to re-order based on latest date being at the top/bottom

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
`{
            pages: [
                {
                    name: "page1",
                    elements: [
                        {
                            type: "matrixdynamic",
                            name: "ComplexMedicalNeeds",
                            titleLocation: "hidden",
                            columns: [
                                {
                                    name: "Date",
                                    cellType: "datepicker",
                                    dateFormat: "mm/dd/yy",
                                    config: {
                                        showOn: "button",
                                        buttonImage:
                                        "assets/icons/date.svg",
                                        buttonImageOnly: true,
                                        buttonText: "Select date",
                                        maxDate: "+0D"
                                    },
                                    inputType: "date"
                                },
                                {
                                    name: "Narrative",
                                    cellType: "comment",
                                    maxLength: 2000,
                                    validators: [
                                        {
                                            type: "text",
                                            allowDigits: true,
                                            minLength: 0,
                                            maxLength: 2000
                                        }
                                    ]
                                },
                                {
                                    name: "Actions",
                                    visibleIf: "1 = 2"
                                }
                            ],
                            cellType: "text",
                            rowCount: 0,
                            addRowLocation: "top",
                            addRowText: "ADD COMPLEX NEED  +",
                            removeRowText: " ",
                            confirmDelete: true,
                            confirmDeleteText: "Are you sure you want to delete medical/nursing needs record?"
                        }
                    ]
                }
            ],
            showTitle: false,
            showQuestionNumbers: "off",
            questionErrorLocation: "bottom"
        }`
```
your_code_here

```

### Specify your

* browser: chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular 5
* surveyjs version: 1.0.35

**Comment by tsv2013** [comment]
Could you please share your use case? It doesn't seem for me as a survey must have functionality. It looks like you need integrate a grid control (e.g. https://datatables.net/) as a custom widget.

**Comment by ashygk** [comment]
Our use case is that we should be able to add dynamic rows (which has one of the column as datepicker).
Once the survey is saved and come back again, the date should be re-order based on chronological order of the dates.

**Comment by tsv2013** [comment]
You can reorder survey data on your side before assigning to the `survey.data`
