### ISSUE TITLE
Radiogroup generates string output instead of numerical

### ISSUE THREAD

**Issue by ogero** [surveyjs/survey-library#1261]
When using radiogroup with numbers as values for its options:
```
"choices": [
	{"value": 0, "text": "Zero"},
	{"value": 1, "text": "Onw"},
	{"value": 2, "text": "Two"}
]
```
The resulting survey data for radiogroups picked values are strings:  
`{"number_picked_radiogroup":"2","number_picked_dropdown":2}`  
Instead of the expected "numerical" type:  
`{"number_picked_radiogroup":2,"number_picked_dropdown":2}`  

This behaviour seems not to be affecting "dropdown".

[Example "radiogroup sends numerical values as string"](https://next.plnkr.co/edit/Pv0BpRAo5UTTvoIK)

```
{
 "pages": [
  {
   "name": "form",
   "elements": [
    {
     "type": "radiogroup",
     "name": "number_picked_radiogroup",
     "title": "Select a number",
     "isRequired": true,
     "choices": [
      {
       "value": 0,
       "text": "Zero"
      },
      {
       "value": 1,
       "text": "One"
      },
      {
       "value": 2,
       "text": "Two"
      }
     ],
     "colCount": 3
    },
    {
     "type": "dropdown",
     "name": "number_picked_dropdown",
     "title": "Select a number again",
     "choices":  [
      {
       "value": 0,
       "text": "Zero"
      },
      {
       "value": 1,
       "text": "One"
      },
      {
       "value": 2,
       "text": "Two"
      }
     ]
    }
   ]
  }
 ]
}
```

**Comment by tsv2013** [comment]
The choices of radiogroup items are bound to html input radio elements. It's value attribute is a DOMString (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/radio#The_value_attribute). When you are choosing a radio button, it's value is taken as a result value. Thus the result value is a string.
It's not good. Ideally we should take the value from the corresponding choice item model. I marked this question as an enchancement and we'll discuss it with the team.

**Comment by ogero** [comment]
This enhacement could be very handy, as for now, the only workaround in my knowledge is to change radiogroups for dropdown (not the best experience in some cases).
Thanks @tsv2013

**Comment by andrewtelnov** [comment]
@ogero We have fixed this issue some times ago. The question stores the numeric now if numeric in the value.

Thank you,
Andrew
