### ISSUE TITLE
It's impossible to add custom widget via the question factory

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-library#1266]
### Are you requesting a feature, reporting a bug or asking a question?
Bug, see https://surveyjs.answerdesk.io/ticket/details/T938 for more details

### How would you reproduce the current behavior (if this is a bug)?
survey.getPageByName("page1").addNewQuestion("sortablelist", "Title");

#### Provide the test code and the tested page URL (if applicable)
Tested page URL:
https://plnkr.co/edit/9B3geIS5rxLfDD9jDb5w?p=preview

Test code
survey.getPageByName("page1").addNewQuestion("sortablelist", "NewQuestion");

**Comment by gologames** [comment]
Seems fixed in latest version
![image](https://user-images.githubusercontent.com/30930391/86912206-4099e680-c125-11ea-8cb1-2c9c1aaa7190.png)
