### ISSUE TITLE
how to place a button in the survey?

### ISSUE THREAD

**Issue by moldoe** [surveyjs/survey-library#1268]
In the screenshot below I'm using a HTML question to render the button and some hacky styling to aling it. 
Is there a better way to add a button and a click handler where I can have access to the survey instance in which the button is placed.
Thanks again for the great work!

![image](https://user-images.githubusercontent.com/23000474/43782293-0404eca4-9a2d-11e8-875b-8446a0dc3548.png)

**Comment by moldoe** [comment]
I appreciate your time. Your example is exactly what I did. But sometimes developers wrap your Survey component in other components like in our case an EXTJS panel or window. In this case ideally you don't want to store references of survey instances in the global context(e.g. window) and then accessing them from there. 
If your framework would have an actual Question of type 'button', maybe the Survey instance and Question can be passed down as parameters to the click event handler. This is especially useful when your page may have multiple surveys instantiated(I know, were pushing the limits here :) ). Maybe this is something you want to consider for the future. 
Thank you!

**Comment by andrewtelnov** [comment]
@moldoe You may implement a custom widget with base class questionbase.
In this case you may get the access to survey inside the custom widget code.
Here is the [repo](https://github.com/surveyjs/widgets) where you can find more information and an example.

Thank you,
Andrew

**Comment by moldoe** [comment]
That makes sense. Thanks for the suggestion!

**Comment by BabuBahir** [comment]
This gets the jobs done 

https://surveyjs.io/Examples/Library/?id=survey-afterrender&platform=jQuery&theme=default#
