### ISSUE TITLE
cssClasses Documentation

### ISSUE THREAD

**Issue by CalvinRodo** [surveyjs/survey-library#1277]
### Are you requesting a feature, reporting a bug or asking a question?
Requesting documentation

I'm unable to find any documentation for the options parameter in the `onUpdateQuestionCssClasses`. 

It would be nice to have some documentation or even a link to the where it is defined in source code so that I can properly set the options.

**Comment by CalvinRodo** [comment]
I found the solution here; 
https://surveyjs.io/Examples/Library/?id=survey-customcss&platform=jQuery&theme=default

In the documentation tab. 

Wasn't super obvious for me.

**Comment by dmitrykurmanov** [comment]
@CalvinRodo @andrewtelnov @tsv2013 may be we need to add this info to the [overview](https://surveyjs.io/Documentation/Library/). What do you think?

**Comment by JaneSjs** [comment]
Hello,
Please refer to the following guide for more information on how to customize survey styling: [Themes and Styles](https://surveyjs.io/form-library/documentation/manage-default-themes-and-styles).
