### ISSUE TITLE
Add more built in basic math expressions

### ISSUE THREAD

**Issue by MackAttack26** [surveyjs/survey-library#1281]
### Are you requesting a feature, reporting a bug or asking a question?
Requesting a feature

### What is the current behavior?
None

### What is the expected behavior?
Count the number of rows in a matrix, 
Count the number of non blank values in a matrix
Average a matrix column
Average all non-blank values matrix column

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here
Generic
```

### Specify your

* browser: Chrome/Firefox
* browser version: Latest version
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: Latest

**Comment by tsv2013** [comment]
Thank you for the suggestion.
At the moment you can write and register your own custom function as described here - https://surveyjs.io/Documentation/Library/#visibility
