### ISSUE TITLE
OnPartialSend for single page surveys?

### ISSUE THREAD

**Issue by bvolkmann** [surveyjs/survey-library#1283]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question / Eventually requesting a feature

### Description

Hi,
is it possible to save incomplete, single-page surveys for a later editing?
I only saw the "onPartialSend" event for multiple-page surveys, that will be triggered,
when "sendResultOnPageNext" is enabled and the page is changed.

The use-case i'm speaking of is, when the user began to edit the survey, 
but had to interrupt it, i would like to save the progress for when the user returns. 

For multiple-page surveys, this is already possible, 
but i just would like to know if that is working independent from the amount of designed pages.

**Comment by andrewtelnov** [comment]
@bvolkmann Sure, it is possible. In this case you have to save the data on every survey.onValueChanged event. survey.onCurrentPageChanged event will not be fired and onComplete is too late.

Thank you,
Andrew
