### ISSUE TITLE
How to add elements in the title attribute

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/survey-library#1287]
How to add elements to the title attribute, such as buttons

**Comment by tsv2013** [comment]
You can use the [onAfterRenderQuestion](https://surveyjs.io/Documentation/Library/?id=surveymodel#onAfterRenderQuestion) event as shown in this example - https://surveyjs.io/Examples/Library/?id=survey-afterrender&platform=jQuery&theme=default

**Comment by fengzhihenxs** [comment]
Thank you. This is what I need.

**Comment by fengzhihenxs** [comment]
There is another question to ask. In surveyjs, if you set the hasComment of a problem to ture, can the input tag that appears be set to textarea

![image](https://user-images.githubusercontent.com/37610470/44506666-07dff800-a6da-11e8-989d-47d0adbab44c.png)

![image](https://user-images.githubusercontent.com/37610470/44506712-2e9e2e80-a6da-11e8-9457-376ba2f1ef5f.png)

**Comment by andrewtelnov** [comment]
@fengzhihenxs Unfortunately, there is not easy way to convert comment text input into textarea right now.
I have added this request into our TODO list. However, I could not promise that we will implement it immediately.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@fengzhihenxs We are using textarea since several versions now.

Thank you,
Andrew
