### ISSUE TITLE
Get the result of the page

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/survey-library#1296]
If there are multiple pages, how can we get the result of the current page? For example, when you click the next page, get the result of the previous page.

**Comment by andrewtelnov** [comment]
@fengzhihenxs You may use page.getValue() function that returns values of questions of the page and survey.onCurrentPageChanging event as:
```
survey.onCurrentPageChanging.add(function(sender, options) {
  if(!!options.oldCurrentPage) alert(JSON.stringify(options.oldCurrentPage.getValue()));
});
```

Thank you,
Andrew
