### ISSUE TITLE
Support multiple other options

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#1297]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
Currently `hasOther` is a `boolean` option. This means we can enable or disable it.

### Proposed behavior
It would be nice if we have `choices` and `otherChoices`, where `otherChoices` can also contain multiple elements which, when selected, show a text box.

**Comment by andrewtelnov** [comment]
@SamMousa We have the request about this functionality in our TODO list. Unfortunately we have not implemented it yet.
The current solution is not use the Matrix Dynamic question with one text column, next to the question, where a user may add/remove rows.

Thank you,
Andrew

**Comment by SamMousa** [comment]
Closing this in favor of https://github.com/surveyjs/survey-library/issues/4764
