### ISSUE TITLE
SurveyJS Builder -> Names aren't being loaded 

### ISSUE THREAD

**Issue by MarissaBez** [surveyjs/survey-library#1298]
### Are you requesting a feature, reporting a bug or asking a question?
It's probably a bug as it's pretty inconsistent among different question-types (but might be a bit more of a question too)

### What is the current behavior?
We set our builder up with a mix of preset and default question (as in preset dropdowns and custom dropdowns). Our preset dropdowns have been set to a certain name (as example "dropdown1" instead of "question1"). When we drag the preset dropdown to the survey - it keeps it preset name. When we click the preset dropdown, it also appears in the survey, but is named "question1" instead.

When disabling the option to change the name both clicking and dragging will result in the dropdown being made with name "question1".

### What is the expected behavior?

We would expect, in all cases, that the name from the question gets inherited from the presets.

### How would you reproduce the current behavior (if this is a bug)?

Create a question, any question of the above types (checkbox has the same behaviour as the comments) with a preset name and try dragging/clicking the checkbox to add it to the survey. It won't have the name car, but instead go back to the default "question1".

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
Not available (running locally).

Test code

```
var editorOptions = {questionTypes : [""], showJSONEditorTab: false, showTestSurveyTab: false};
var editor = new SurveyEditor.SurveyEditor("editorElement", editorOptions);

  editor
            .toolbox 
              .addItem({
                    name: "checkbox",
                    isCopied: true,
                    iconName: "checkboxico",
                    title: "Checkbox",
                    json: {
                        "type": "checkbox",
                        "name": "Car",
                        "title": "This is a checkbox",
                    }
                })

editor
                .onCanShowProperty
                .add(function (sender, options) {
                    if (options.obj.getType() == "checkbox") {
                        options.canShow = 
                            options.property.name == "title";
                    }
                });
```

### Specify your

* browser:  (tested in) Chrome, Microsogt Edge and Mozilla Firefox
* browser version: latest updates for each
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.39

**Comment by andrewtelnov** [comment]
@MarissaBez the question.name should be overridden to be unique. You may use editor.onQuestionAdded event to set your own question name.
Here is [the example](https://surveyjs.io/Examples/Builder/?id=oncreatequestion) of using this event to set the custom question name.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@MarissaBez Please, use this [repo](https://github.com/surveyjs/editor/issues) for SurveyJS Builder(Editor).

Thank you,
Andrew
