### ISSUE TITLE
set InputType date textbox default value to current date instead of mm/dd/yyyy

### ISSUE THREAD

**Issue by SaharDastitash** [surveyjs/survey-library#1299]
### Are you requesting a feature, reporting a bug or asking a question?

How can I show default input value as current local date instead of mm/dd/yyyy in the textbox of an dateType input?

### What is the current behavior?

Testing Date(mm/dd/yyyy): mm/dd/yyyy

### What is the expected behavior?

Testing Date(mm/dd/yyyy): 08/28/2018

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

questions: [
          {
              type: "multipletext", name: "SiteInfo",
              title: "Please enter the Tesing Date in the box below.",
              items: [{ inputType: "date", name: "TestingDate", title: "Testing Date(mm/dd/yyyy)"}
              ]
          }

or 

 {
                type: "text",
                name: "RapidTest1BeginDate",
                title: "Begin Date:",
                inputType: "date"
            },
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
I've created a sample for you - https://plnkr.co/edit/ppWxnDdTTyLAxohBcb4r?p=preview

**Comment by SaharDastitash** [comment]
@tsv2013  Thank you so much, It was great!

**Comment by andrewtelnov** [comment]
The solution for v1.8.1+ is to use defaultValue with function.
```js
{
type: "text",
name: "RapidTest1BeginDate",
title: "Begin Date:",
inputType: "date",
defaultValue: "=today()"
},
```

Thank you,
Andrew
