### ISSUE TITLE
Surveyjs uses third party plug-ins

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/survey-library#1300]
How to use third party plug-ins. For example, when the default date and time are not satisfied, use Bootstrap Datepicker.

**Comment by andrewtelnov** [comment]
@fengzhihenxs Sure, you can do this.
Here is [the example of bootstrap time picker](https://plnkr.co/edit/9Tc9woNcdYmwOiFxB15y?p=preview), in timepicker_widget.js. You may try it by draging the last item in the toolbox.
More information about integration third-party widgets you may find in [this repo](https://github.com/surveyjs/widgets)
Here are [online examples](https://surveyjs.io/Examples/Library/?id=custom-widget-select2-tagbox) of custom widgets.

Thank you,
Andrew

**Comment by fengzhihenxs** [comment]
Thank you. If you use Bootstrap Datepicker, how do you write the attributes of question?

For example, use bootstrap-datetimepicker.js
 questions: [
      {
        "name": "date",
        "type": "datetimepicker",
        "inputType": "date",
        "title": "Your favorite date:",
        "dateFormat": "mm/dd/yy",
        "isRequired": true
      }]

**Comment by andrewtelnov** [comment]
@fengzhihenxs That is depends on the widget integration. There are following functions:
```
    //Required libraries are availalble
    widgetIsLoaded: function() {
      return !!$ && !!$.fn.timepicker;
    },
    //Return true to use this custom widget instead of the standard
    isFit: function(question) {
      return question.getType() === "timepicker";
    },
```
You may write isFit function as you need. For example:
```
    isFit: function(question) {
      return question.getType() === "text" and question.inputType === "date";
    },
```
or just
```
    isFit: function(question) {
      return question.inputType === "date";
    },
```
The library check for every question, if there is a custom widget that is loaded (all needed scripts are here) and isFit returns true, then use this widget instead of standard rendering.
How you will use third-party widget integration is totally up to you and depends on your tasks.
I hope it makes sense to you :)

Thank you,
Andrew

**Comment by fengzhihenxs** [comment]
Sorry. I don't quite understand.

**Comment by andrewtelnov** [comment]
@fengzhihenxs  Do you want to create a new question type or do you want to change the behavior/rendering of the current questions?
You may show bootstrap date/time picker for text question with inputType equals to "date" and "time".
Another alternative, to have a new question types: "date" and "time".

What is your goal?

Thank you,
Andrew

**Comment by fengzhihenxs** [comment]
I think both date and time will meet simultaneously.
![image](https://user-images.githubusercontent.com/37610470/44777262-bf7a7b80-abac-11e8-9ec4-c44c765e78b6.png)

**Comment by andrewtelnov** [comment]
@fengzhihenxs I do not know this widget, but you may set your isFit function as:
```
 isFit: function(question) {
      return question.inputType === "datetime" || question.inputType === "datetime-local";
    }
```
You may use [the example with bootstrap time picker](https://plnkr.co/edit/9Tc9woNcdYmwOiFxB15y?p=preview) I gave you  to integrate this widget or use [this example](https://plnkr.co/edit/HdnYE5?p=preview)

Thank you,
Andrew

**Comment by fengzhihenxs** [comment]
Hello, I use the bootstrap datetimepicker custom widget, can display normally, but when I click on the completion of the value is not obtained, why?
 
![image](https://user-images.githubusercontent.com/37610470/44827129-521a2980-ac44-11e8-9d04-446f8faa39ed.png)


The following is custom widget code：
function init(Survey) { 
  var widget = {
    name: "datetimepicker",
    title: "Date time picker",
    iconName: "",
    widgetIsLoaded: function () {
      return !!$ && !!$.fn.datetimepicker;
    },
    isFit: function (question) {
      return question.getType() === "datetimepicker";
    },
    htmlTemplate:"<input class='form-control widget-datetimepicker' type='text' style='width: 100%;'>",
    activatedByChanged: function (activatedBy) {
      Survey.JsonObject.metaData.addClass(
        "datetimepicker",
        [
          { name: "inputType", visible: false },
          { name: "inputFormat", visible: false },
          { name: "inputMask", visible: false }
        ],
        null,
        "text"
      );
      Survey.JsonObject.metaData.addProperty("datetimepicker", {
        name: "dateFormat"
      });
    },
    afterRender: function (question, el) {
      var $el = $(el).is(".widget-datetimepicker")
        ? $(el)
        : $(el).find(".widget-datetimepicker");

      var pickerWidget = $(".widget-datetimepicker").datetimepicker({
        // enableOnReadonly: false,
        format: question.inputFormat,
        startView:question.inputMask,
        showMeridian: true,
        todayHighlight:true,
        autoclose: true,
        todayBtn: true
      })
        // .on("changeDate", function (e) {
        //   question.value = moment(e.date).format("DD/MM/YYYY");
        //   // `e` here contains the extra attributes
        // });

      question.valueChangedCallback = function() {
        $(".widget-datetimepicker").datetimepicker({format: question.inputFormat});
      }
      question.valueChangedCallback();
      question.readOnlyChangedCallback = function() {
        if(question.isReadOnly) {
          $el.prop('readonly', true);
        }
        else {
          $el.removeAttr('readonly');
        }
      }
      question.readOnlyChangedCallback();

    },
    willUnmount: function (question, el) {
      var $el = $(el).is(".widget-datetimepicker")
        ? $(el)
        : $(el).find(".widget-datetimepicker");
      $el.datepicker("destroy");
      question.readOnlyChangedCallback = undefined;
      question.valueChangedCallback = undefined;
    }
  };

  Survey.CustomWidgetCollection.Instance.addCustomWidget(widget, "customtype");
}

if (typeof Survey !== "undefined") {
  init(Survey, window.$);
}

**Comment by fengzhihenxs** [comment]
questions: [
      {
        name: "datetime",
        type: "datetimepicker", 
        title: "Your  datetime:",
        inputFormat: "dd/mm/yyyy HH:ii P", 
        inputMask: 2,
        isRequired: true
      }]

**Comment by fengzhihenxs** [comment]
Thank you. I know why.

**Comment by andrewtelnov** [comment]
Yes, the code that set question.value on change date event was commented.

Thank you,
Andrew

**Comment by fengzhihenxs** [comment]
Hello, can you change the template of htmlTemplate dynamically according to the properties of question when custom widgets are changed?

For example, the inputType attribute of a question has different HTML Template values <span class="input-group-addon"> <span class="glyphicon-time"> </span> or <span class="input-group-addon"> < span class="glyphicon-calendar"> </span>

**Comment by dmitrykurmanov** [comment]
Our `htmlTemplate` is static string and can not be changed dynamically. But you can set something like:
`htmlTemplate: "<div></div>",` and generate it content dynamically in the `afterRender` question.

**Comment by fengzhihenxs** [comment]
OK，Thank you
