### ISSUE TITLE
Add the corresponding comments for each selected option.

### ISSUE THREAD

**Issue by ShuQingGit** [surveyjs/survey-library#1303]
### Are you requesting a feature, reporting a bug or asking a question?

Ask a question

### What is the current behavior?
The current function is to add comments to the entire problem by adding the hasComment attribute.

### What is the expected behavior?
So how do you implement a question like dropdown, radiogroup, and checkbox where each answer is selected to add a comment? Thank you

### How would you reproduce the current behavior (if this is a bug)?
I want to do this by adding hasComment attributes to the choices attribute, but it doesn't work at this point.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```

      {
            type: "radiogroup",

            choices: [
              { value: "Yes", hasComment:true},
              { value: "No", hasComment:"false"}
            ],
            isRequired: false,
            name: "1000007",
            popupdescription: "Select the operating system you are currently using.",
            title: "Do you use any front-end framework like Bootstrap?",
            page: "page2"
          },
```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@ShuQingGit It would be hard to imlement. In fact, you would have to create your own custom widget. You may look at [this repo](https://github.com/surveyjs/widgets) for more information.
Another solution is to use the [matrix dropdown question](https://surveyjs.io/Examples/Library/?id=questiontype-matrixdropdown) with two columns, where the first column will be checkobx and the second column is a comment, the comment can be visible/invisible by some rules.

Thank you,
Andrew
