### ISSUE TITLE
Surveyjs.io is down as of 2:08PM 4Sept(GMT+3)

### ISSUE THREAD

**Issue by omkardusane** [surveyjs/survey-library#1307]
The site is unreachable.
![image](https://user-images.githubusercontent.com/12975569/45027986-d1eb2e00-b060-11e8-95de-77d7cbe2c210.png)

**Comment by HarunKARATAS** [comment]
![image](https://user-images.githubusercontent.com/7129948/45028830-32716f80-b04f-11e8-95e5-4dc9d1f66940.png)

**Comment by tsv2013** [comment]
Our Azure hosting experiences some troubles:

Please track the
https://azure.microsoft.com/en-us/status/

Multiple Services - South Central US - Investigating

Starting at 09:29 UTC on 04 Sep 2018 a subset of customers in South Central US may experience difficulties connecting to resources hosted in this region. At this time Engineers are investigating an issue with cooling in one part of the data center which caused a localized spike in temperature. Automated data center procedures to ensure data and hardware integrity went into effect when temperatures hit a specified threshold and critical hardware entered a structured power down process. The impact to the cooling system has been isolated and engineers are actively working to restore services. The next update will be provided as events warrant.

**Comment by anushasipl** [comment]
Could you please let me know how much time it will take :(

**Comment by andrewtelnov** [comment]
@anushasipl Unfortunately it doesn't depend on us right now :( We did not expect that Azure will fail. As soon as it come back, we will enable "Cross-regional replication for Azure Storage" to be safe in the future.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Some for information about [issues with Azure](https://www.theregister.co.uk/2018/09/04/azure_its_getting_hot_in_here/)

**Comment by ishuen** [comment]
I wonder if the database servers are still working. Currently my surveys are still in progress but I'm not sure if it still can collect data.

**Comment by andrewtelnov** [comment]
@ishuen The site comes back.
To all: We will work on Azure cross-region replication to avoid such problems in the future. This time we get "lucky" that exactly our "South Central US" experienced problems.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@omkardusane Unfortunately the issue is not resolved completely. We can't update our website. Additionally, we want to create a secondary instance of our web application and replicated database in Europe, to avoid this type of issues in the future.

Thank you,
Andrew

**Comment by Dev-Dipesh** [comment]
The site is down again, but your status page says that's it's "Active".

**Comment by Dev-Dipesh** [comment]
Is there any other place for the documentation?

**Comment by andrewtelnov** [comment]
@Dev-Dipesh @omkardusane I hope we found the issue. We are contacting Azure support. Internal routing in Azure cloud doesn't work correctly for our segment/website.

Thank you,
Andrew
