### ISSUE TITLE
Width of question type

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/survey-library#1310]
Is there any way to control the width of input in question? Can width attribute only control the width of a problem? If the title attribute has more content, the width attribute will not work.

![image](https://user-images.githubusercontent.com/37610470/45069686-5e006280-b100-11e8-863a-8486b4ac6807.png)
  

json：{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "text",
     name: "question1",
     width: "50",
     title: "Test1 Do you use any front-end framework like Bootstrap?"
    },
    {
     type: "dropdown",
     name: "question3",
     width: "20",
     title: "Test2 Do you use any front-end framework like Bootstrap?",
     hasComment: true,
     choices: [
      "item1",
      "item2",
      "item3"
     ]
    },
    {
     type: "radiogroup",
     name: "question2",
     width: "15",
     choices: [
      "item1",
      "item2",
      "item3"
     ]
    }
   ]
  }
 ]
}

**Comment by dmitrykurmanov** [comment]
@fengzhihenxs hello! I think that you can set different width for the title and input via the css. What do you think about this way?

**Comment by fengzhihenxs** [comment]
Also, what is the role of the width attribute?

**Comment by dmitrykurmanov** [comment]
@fengzhihenxs may be I've miss something. I've created an example with `width` config : https://plnkr.co/edit/uadg11D36RJrDwRUhasQ?p=preview and it looks ok
