### ISSUE TITLE
How to get the value of the current page

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/survey-library#1311]
The survey. currentPage. getValue () method can only get the value of questions in the current page. If the hasComment property in the problem is true, the value in the comment cannot be obtained.
   Is there a way to get the values of questions, comment and other of the current page?

such as：
![image](https://user-images.githubusercontent.com/37610470/45073154-a9bb0800-b110-11e8-8b20-6310ae169e42.png)

![image](https://user-images.githubusercontent.com/37610470/45073171-be979b80-b110-11e8-8edc-88eccb3c1517.png)

![image](https://user-images.githubusercontent.com/37610470/45073182-cce5b780-b110-11e8-92a2-af521191f972.png)

**Comment by andrewtelnov** [comment]
@fengzhihenxs I have added getComments function. It will be available in the next update. Meanwhile you may use the following code:
```
  public getComments(page) {
    var comments = {};
    var questions = page.questions;
    for (var i = 0; i < questions.length; i++) {
      var q = questions[i];
      var comment = page.data.getComment(q.getValueName());
      if (!!comment) {
        comments[q.getValueName()] = comment;
      }
    }
    return comments;
  }
```

Thank you,
Andrew
