### ISSUE TITLE
How to jump to a question on the specified page?

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/survey-library#1316]
If you have a button outside, click the button to jump to a certain question on the specified page, how do you implement it?

**Comment by dmitrykurmanov** [comment]
@fengzhihenxs please check the code: 

```js
survey.currentPageNo = 2 // change current page to 3
survey.currentPage.questions[4].focus() // focus specified question
```

also check: https://surveyjs.io/Documentation/Library/?id=QuestionSelectBase#focus
https://surveyjs.io/Documentation/Library/?id=surveymodel#currentPageNo

**Comment by fengzhihenxs** [comment]
OK, thank you. I realized it in another way.

**Comment by dmitrykurmanov** [comment]
@fengzhihenxs cool! It would be great if you share your realization here for another users

**Comment by fengzhihenxs** [comment]
My train of thought is to find the parent element of question and then use scrollTop.
