### ISSUE TITLE
How to verify all the problems on the current page

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/survey-library#1321]
1.How does SurveyJS trigger built-in validation to verify whether there are errors in the current page problem?

2.How to get the value of the current page after verification (including required).

**Comment by dmitrykurmanov** [comment]
1. try `survey.currentPage.hasErrors()` https://surveyjs.io/Documentation/Library/?id=pagemodel#hasErrors 

    PS @tsv2013 @andrewtelnov  I think that we need to rename this method to something like `validate`

2. `survey.currentPage.getValue()` @fengzhihenxs I  don't understand what do you mean by "including required" could you please clarify it?
 
please also check `checkErrorsMode` property https://surveyjs.io/Documentation/Library/?id=surveymodel#checkErrorsMode

**Comment by fengzhihenxs** [comment]
The first problem I use is isCurrentPageHasErrors.

The second question is wrong.

**Comment by fengzhihenxs** [comment]
In addition, I want to know if there is any way to judge whether the result of the page has changed. For example, a survey restores questions based on the last answer, and if the question on the page is modified, it saves; if it is not, a message prompt pops up
