### ISSUE TITLE
How to get the questionsof the current page?

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/survey-library#1322]
I have a request to click the button to get all the changes, how to do it?

**Comment by dmitrykurmanov** [comment]
@fengzhihenxs please try this:

```js 
survey.currentPage.getValue(); // for the current page
survey.data; // for all survey
```

**Comment by fengzhihenxs** [comment]
I mean, there are modified and unmodified questions in the page, get the modified questions, how do you get them?

**Comment by andrewtelnov** [comment]
@fengzhihenxs You would have to do the following. You have to store the survey.currentPage.getValue() json data to a variable on first survey showing and [onCurrentPageChanged event](https://surveyjs.io/Documentation/Library/?id=surveymodel#onCurrentPageChanged) and then compare with the current page values.
If you need to get the difference, here is the [stackoveflow topic](https://stackoverflow.com/questions/8431651/getting-a-diff-of-two-json-objects) that may be usefull for you.

Thank you,
Andrew
