### ISSUE TITLE
Renderings of survey again

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/survey-library#1324]
I have a need to click the question to set its hasComment attribute to true, showing the comments. DOM that needs to be rendered again. I saw a survey.render () method that rendered the whole survey, and whether there was a way to render the problem again.

**Comment by fengzhihenxs** [comment]
Now I'm going to update the query settings and use "survey. render ()" and the scrollTop of the page goes back to the top. I don't know what's affecting it.

**Comment by fengzhihenxs** [comment]
The problem was that the surveyjs-widgets.js file affected the use of third-party plug-ins that had to refer to surveyjs-widgets.js. What should I do?

**Comment by fengzhihenxs** [comment]
This is an example, but I put it in Angular 5 and when I click the button, the scrollbar goes back to the top. Why?https://plnkr.co/edit/tuzfFFZeQChlgL60hVW2?p=preview

**Comment by fengzhihenxs** [comment]
How to write this function format in angular component?

**Comment by dmitrykurmanov** [comment]
@fengzhihenxs we've checked your example and we need more clarifications.

- about scroll to top: your plnkr example looks ok and don't have the scroll to top. Could you please provide an example to reproduce the problem?

- about comment: you also can add `comment` question (https://surveyjs.io/Examples/Library/?id=questiontype-comment&platform=jQuery&theme=default) and make it visible by the proper condition (https://surveyjs.io/Examples/Library/?id=condition-kids&platform=jQuery&theme=default)

- about custom-widgets: sorry I don't undertand your question. Could you please clarify it?

**Comment by fengzhihenxs** [comment]
This is the angular5 project. When you click the "more info" button, scroll to the top. This is not what I want. I don't know why this problem arises.
[surveyjs_angular5.zip](https://github.com/surveyjs/surveyjs/files/2370108/surveyjs_angular5.zip)

**Comment by dmitrykurmanov** [comment]
after debugging:

```js
window.onscroll = function() {
  debugger
}
```
I've found the problem:
![image](https://user-images.githubusercontent.com/22315929/45365707-cc07c680-b5e5-11e8-902c-6c016af8e14b.png)

So the problem in the bootstrap-slider. 

@fengzhihenxs do you use it in your project? If no, you can just exclude this widget. 

Anyway we will investigate how to solve this problem.

**Comment by fengzhihenxs** [comment]
This is a temporary demo, and I'm not using bootstrap-slider, but the real project needs to use inputmask. js, which also affects scroll, and that's the problem. I use the same JS file, there is no problem in jQuery, but there is a problem in angular. I don't understand why.

**Comment by fengzhihenxs** [comment]
Hello, bootstrap-datetimepicker will also affect the scroll bar. Is there any way to solve it?

**Comment by tsv2013** [comment]
@fengzhihenxs We're still working on the solution.
