### ISSUE TITLE
Add description location property

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1328]
Is it possible to move description below the input field to avoid this misalignment:

![screen shot 2018-09-11 at 15 57 28](https://user-images.githubusercontent.com/454321/45364864-7a5a3e80-b5db-11e8-8dc6-cf5a27ed686f.png)

thank you

**Comment by andrewtelnov** [comment]
@masciugo You may set survey.questionDescriptionLocation property to "underInput" (default is "underTitle") or question.descriptionLocation to "underInput" (default is "default").
It will work from next minor version that we will release on next week.

Thank you,
Andrew
