### ISSUE TITLE
runexpression trigger called before valueChanged event

### ISSUE THREAD

**Issue by moldoe** [surveyjs/survey-library#1330]
As it seems, from my testing, when a question changes it's value, the "runexpression" triggers are called before the "onValueChanged" event. To me it feels like it should be the other way around.
Let me know if this makes sense to you or if I should explain in more details what I'm trying to do.
Thanks,
Daniel

**Comment by tsv2013** [comment]
You are absolutlely right. We need more details description on your scenario to realize how we can improve the current behaviour.

**Comment by moldoe** [comment]
I'm using the library to implement questionnaires for Tier 1 support teams in the telecom industry. We basically implement a multitude of question flows which support users have to go through when a subscriber calls with an issue. The flows can be quite long and complex and most of the times the answer to one question determines the rest of the flow(the visibility for the next question(s)). I'm also using "runexpression" triggers to detect certain situations in the flow and display certain messages. The messages are added dynamically to the survey as html questions from a call back function set using the "runExpression" property.

`{
    "type": "runexpression",
    "expression": "{expression}",
    "runExpression": "setProbableCause('cause')"
}
`
At this point if the user goes back in the survey and changes any value to any question, I need to remove(hide) the html question that was displayed by the trigger. So I'm using the "survey.onValueChanged" event, where I call "setProbableCause(null)" to hide the html question.

But the handling of the "valueChanged" event will now conflict with my triggers, because, when a value changes in the survey, the triggers are executed first, they will briefly display the html question if the conditions are met, but then when "survey.onValueChanged" is called immediately after, the html question will become hidden.

Thus, in this scenario, having "survey.onValueChanged" called first, will reset(hide) the html question and then when triggers are executed next they will decide if any html message needs to be displayed.

**Comment by andrewtelnov** [comment]
@moldoe I have added [survey.onValueChanging event](https://github.com/surveyjs/surveyjs/issues/1331). Let me know if it solves your issue.
It will be available in the next minor update on the next week.

Thank you,
Andrew

**Comment by moldoe** [comment]
As long as this event is called before "runexpression" triggers it should help. Looking forward for the minor release.
Thank you!
Daniel

**Comment by andrewtelnov** [comment]
@moldoe It calls before setting the value. You may change the value on this event. You may look at my commit to see the code changes and a new unit test.

Thank you,
Andrew
