### ISSUE TITLE
Trouble with onSetValue attribute on custom property

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-library#1334]
Hi @andrewtelnov ,

Is the onSetValue attribute working as expected? When exactly would this attributes function be invoked? I thought it might be when you click 'Ok' on the question edit modal but I am unable to see anything get executed. Here's how i'm adding this to a custom property to questionbase.

SurveyKo.JsonObject.metaData.addProperty('questionbase', {
name: 'customName',
default: '',
isRequired: true,
onSetValue: (obj, value, jsonConverter) => {
console.log('onSetValue', obj);
}
});

Thank you.

**Comment by tsv2013** [comment]
The `onSetValue` function is being called in the `setValue` function See https://github.com/surveyjs/surveyjs/blob/master/src/jsonobject.ts#L74-L76

I think it's related to the value of the question, not to the question attributes.
But I can mistake. @andrewtelnov What do you say?

**Comment by leksinteractive** [comment]
To give you more info I found out about this via the documentation in the builder:
https://surveyjs.io/Documentation/Builder/ (the section "Add properties into SurveyJS Elements")

**Comment by tsv2013** [comment]
The code part I've posted is a method of the `JsonObjectProperty` class. So if the property value is set via the `JsonObjectProperty` class, than this method will be called. Otherwise, if you assigning the property directly, this method will not be called. I know some places in the builder where we assign object properties directly: "question[propertyName] = somePropertyValue". Probably this is wrong.

**Comment by leksinteractive** [comment]
I see - I was hoping to be able to hook into this method when the user clicks 'Ok' on the question edit modal in the builder, and do some logic there.  For now I'm able to achieve the same by using the `onModified` event and checking for the `QUESTION_CHANGED_BY_EDITOR` type.

Thank you.
