### ISSUE TITLE
Trigger to go to a page that is not the next one

### ISSUE THREAD

**Issue by f80** [surveyjs/survey-library#1335]
### Are you requesting a feature, reporting a bug or asking a question?
I am asking a question / requesting a feature.

Is there a way to set up a trigger that will lead me (after clicking on next) to a page that is not the next one but several pages later. What I'm currently doing is making every pages not visible and make them visible with a trigger.
For instance : I have a form with 5 pages. The first one has the only question "Are you John Doe? (Yes/No)" If not, I want to go to the last page by clicking on "Next". Right now, I'm just making the pages visible when choosing "Yes". This is quite a simple example but this operation can be really hard to maintain with more complex scenario.

Thanks for your help.
Florent

**Comment by tsv2013** [comment]
You can make page conditionaly visible.
This controlled by the [visibleIf](https://surveyjs.io/Documentation/Library/?id=pagemodel#visibleIf) property.

Here is the JSON sample - page2 is visible only in case of `item1` of the  `question1` was selected:

```JSON
{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "checkbox",
     name: "question1",
     choices: [
      "item1",
      "item2",
      "item3"
     ]
    }
   ]
  },
  {
   name: "page2",
   elements: [
    {
     type: "radiogroup",
     name: "question2",
     choices: [
      "item1",
      "item2",
      "item3"
     ]
    }
   ],
   visibleIf: "{question1} = [\"item1\"]"
  },
  {
   name: "page3",
   elements: [
    {
     type: "comment",
     name: "question3"
    }
   ]
  }
 ]
}
```

**Comment by andrewtelnov** [comment]
@f80 We have skip to question trigger now. You may use it.

Thank you,
Andrew
