### ISSUE TITLE
Set current date as max date for Date question

### ISSUE THREAD

**Issue by ashygk** [surveyjs/survey-library#1337]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

Date control works fine

### What is the expected behavior?
How do I set the current date as max date? In order to not allow the users to select future dates?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular 5
* surveyjs version: 1.0.38

**Comment by andrewtelnov** [comment]
@ashygk Here is [the example](https://next.plnkr.co/edit/qi2tkCFqR4IeB6o3)

Thank you,
Andrew

**Comment by ashygk** [comment]
@andrewtelnov Thanks for the example. I don't want the validators to validate the date. I want the future dates to be disabled/non-selectable.

**Comment by andrewtelnov** [comment]
@ashygk You may set max attribute onAfterRenderQuestion event. Here is [the example](https://surveyjs.io/Examples/Library/?id=survey-afterrender)

Thank you,
Andrew

**Comment by ashygk** [comment]
@andrewtelnov I used the below implementation to set max date.

**Comment by ashygk** [comment]
@andrewtelnov  I have used the below for my matrix dynamic and it works perfectly fine.
`  private onMatrixAfterCellRender(survey, options) {
    if (options.cellQuestion.name.startsWith('Date') || options.cellQuestion.name.endsWith('Date')) {
      var date = document.getElementById(options.cellQuestion.id + 'i');
      date.setAttribute('max', this.getDate());
      }
  }
  private getDate() {
    var now = new Date();
    var day = ("0" + now.getDate()).slice(-2);
    var month = ("0" + (now.getMonth() + 1)).slice(-2);
    var today = now.getFullYear() + "-" + (month) + "-" + (day);
    return today;
  }`

The problem here is, when a matrix dynamic's column layout is vertical, this max attribute is removed dynamically.

**Comment by ashygk** [comment]
I have created a plunker example. Try to remove the column layout property and it works! But i want my matrix columns layout to be vertical
https://plnkr.co/edit/u6vK4XwgU0IOL0AdwRpq?p=preview

**Comment by andrewtelnov** [comment]
@ashygk Here is the [corrected example](https://next.plnkr.co/edit/LFTxJ8aNaHAgmBEk)

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@ashygk The default input doesn't have this functionality. You may use [jQuery datepicker, for example](https://surveyjs.io/Examples/Library/?id=custom-widget-datepicker)

Thank you,
Andrew

**Comment by ashygk** [comment]
We used to have jquery datepicker previously, but we reverted back to the default input as we were having lot many issues with that  custom widget. Is there any possible workaround to stop the user from manually entering future dates using the default input?

**Comment by andrewtelnov** [comment]
The current solution is to use the min property as: ``min: "=today()"``, from v1.8.1+

Thank you,
Andrew
