### ISSUE TITLE
Panel Dynamic - Custom Navigation Between Panels

### ISSUE THREAD

**Issue by perlav** [surveyjs/survey-library#1339]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question. 

### What is the current behavior?
I'm interested in using the Panel Dynamic in a similar way to the `renderMode = progressTop`. 

### What is the expected behavior?
I am curious on if there's a way of changing the progress and navigation elements. I'm aiming for something more like a dropdown or radio button with options that would identify each panel. 

### Specify your

* browser: Chrome
* browser version: 69.0.3497.92 
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.0.38

**Comment by tsv2013** [comment]
I think you can use the [onAfterRenderPanel](https://surveyjs.io/Documentation/Library/?id=surveymodel#onAfterRenderPanel) event to customize the panel dynamic header in a way similar shown in this example - https://surveyjs.io/Examples/Library/?id=survey-afterrender&platform=jQuery&theme=default
