### ISSUE TITLE
Confirmation popup before changing answer of dependent questions answered already

### ISSUE THREAD

**Issue by abdul-qadir** [surveyjs/survey-library#1341]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?

Whenever any questions's answer is changed and that has some dependent questions which were already answered, we are not able to first confirm from user whether one wants to proceed or not. 

### What is the expected behavior?

When there are too many questions which were answered already and user come back to any question which can change visibility of such already answered questions then it would be required to first confirm with some popup for confirmation before doing that.

**Comment by tsv2013** [comment]
You can use "survey.onValueChanging" event to ask confirmation and change a new value or reset it:
```JS
  /**
   * The event is fired before the question value is changed. It can be done via UI by a user or programmatically on calling setValue method.
   * <br/> sender the survey object that fires the event
   * <br/> options.name the value name that has being changed
   * <br/> options.question a question which question.name equals to the value name. If there are several questions with the same name, the first question is taken. If there is no such questions, the options.question is null.
   * <br/> options.value a new value. You may change it
   * @see setValue
   * @see onValueChanged
   */
  public onValueChanging: Event<
    (sender: SurveyModel, options: any) => any,
    any
  > = new Event<(sender: SurveyModel, options: any) => any, any>();
```

**Comment by abdul-qadir** [comment]
I think it will be fired for all dependent questions. Is there any event which is superset and fired to check if we want to proceed with all dependent question changes or not want to proceed further and stay with same dependent questions and filled up answers without using setValue etc.?

**Comment by tsv2013** [comment]
What do you mean under "dependent questions"?

**Comment by abdul-qadir** [comment]
visibleif questions which depend on selected options of parent question's answer.

**Comment by tsv2013** [comment]
SurveyJS doesn't track dependencies for visibleIf expressions. They are updated on the current page on each value changed event.
