### ISSUE TITLE
Event on validation of page?

### ISSUE THREAD

**Issue by kaphert** [surveyjs/survey-library#1342]
### Are you requesting a feature, reporting a bug or asking a question?
Question / Feature?

### What is the current behavior?
I am looking for a way to collect all errors on a page. Or an event that is fired when there are errors on the page. I am unable to find it and unable to add my own event with all the events there are like `onValidateQuestion`, `onCurrentPageChanged`, `onCurrentPageChanging` because all of these events are not fired if there is an error on the page (question not filled in) 

### What is the expected behavior?
I have a multi page form with some custom widgets. When I press "next" to go to the next page I would like to be able to collect all errors on that page. But actually every time validation is failed I would like to know. By preference with an event like: `onPageValidationFailed` or `onPageValidation(sender, options)` where options contains: 
```
{
   name: 'page_name',
   passed: false,
   errors: {
       question_1: ['Error 1', 'Error 2']
       question_2: ['Error A', 'Error B']
   }
}
``` 

Or maybe easier to implement an event per question that indicates that the validation is passed or failed. 

### Use cases
An event like this would be helpful if you want to show all errors on a page summarized at the top. Or add an indicator below the 'next/prev' button that there are errors on a page. 

Is something like this already available and I am just unable to find it?

**Comment by tsv2013** [comment]
You can use the [hasErrors](https://surveyjs.io/Documentation/Library/?id=pagemodel#hasErrors) method of the page:
```JS
survey.currentPage.hasErrors();
```
Validation in SurveyJS is triggered by any value changes and durring attempt to change the current page.

So you can check that page has errors in the [onValueChanged](https://surveyjs.io/Documentation/Library/?id=surveymodel#onValueChanged) event handler. And then iterate through all questions on the page to collect all errors via the [getAllErrors](https://surveyjs.io/Documentation/Library/?id=QuestionBase#getAllErrors) method of each question..

**Comment by kaphert** [comment]
Hi @tsv2013, thanks for your reply. I am aware of those methods. But what if none of the questions are changed? Imagine a page with 1 required question. A person enters that page and presses 'next' immediately. The event `onValueChanged` won't be fired in this case. A way around this would be to also check on errors before `nextPage` is called. But this feels not like a solid solution but I suppose the only solution at this moment. 

I think it would be a nice add on to have an event that is fired when an error is raised for a question or for a page.

**Comment by tsv2013** [comment]
Questions validation will be called during nextPage attempt and customer will be informed about the errors in case of any. So you can just update your global errors panel on this event.

**Comment by kaphert** [comment]
> So you can just update your global errors panel on this event.

What event is fired when I press 'next' and there are errors on the page? I am unable to track down which one it is. Because the `onCurrentPageChanged` and `onCurrentPageChanging` are not yet fired at this moment.

**Comment by tsv2013** [comment]
You can use the [onServerValidateQuestions](https://surveyjs.io/Documentation/Library/?id=surveymodel#onServerValidateQuestions) callback to validate questions before next page transition

**Comment by kaphert** [comment]
The survey doesn't reach that callback if there is a question on the page that fails the regular validation (field is required for example). So I am unable to use that callback in this case.

**Comment by kaphert** [comment]
I've managed to get what I want with some custom events that I fire before I move to a next page and other moments I need it. 

@tsv2013 it's up to you if you want to close this ticket. I think firing an event if `isCurrentPageHasErrors` is called an fails would be a nice addition.
