### ISSUE TITLE
Need help passing in custom data

### ISSUE THREAD

**Issue by rachel-flux** [surveyjs/survey-library#1344]
### Are you requesting a feature, reporting a bug or asking a question?

I have a question about accessing additional elements included in the JSON survey object.

### What is the current behavior?

We use the SurveyJS Builder tool online to generate surveys and store the JSON in our database.  Our VueJS app makes API calls to get this JSON and generate the survey model in our web app.  This setup is working correctly.

Now we would like to programmatically add some custom elements into the JSON survey object in our backend before returning our API call.  For example, our API now returns the following JSON which includes storeName and shoppingTripId at the page level:

```
{
    "showQuestionNumbers": "off",
    "sendResultOnPageNext": true,
    "completeText": "Next Section",
    "showCompletedPage": false,
    "showPrevButton": false,
    "pages": [
        {
            "name": "page1",
            "elements": [
                {
                    "type": "radiogroup",
                    "name": "questionId-1",
                    "isRequired": true,
                    "title": "How many items did you purchase at the grocery store today?",
                    "choices": [
                        "1-5",
                        "6-10",
                        "11-20",
                        "20+"
                    ]
                }
            ],
            "storeName": "Safeway",
            "shoppingTripId": "1234567"
        }
    ]
}
```

I have seen some SurveyJS examples of how to customize the answer data object before sending the results on survey complete.  I would like to include storeName and shoppingTripId in my survey results, but I can't figure out how to access the custom data.

### What is the expected behavior?

When the onComplete event is called, I had expected that storeName and shoppingTripId would be included in the sender/survey object.  But the custom items are stripped from the JSON.

```
const s = new SurveyVue.Model(surveyJSON);
s.onComplete.add(sendDataToServer);
sendDataToServer(survey) {
    console.log(JSON.stringify(survey));
}
```

Console log:
```
{
    "pages": [
        {
            "name": "page1",
            "elements": [
                {
                    "type": "radiogroup",
                    "name": "questionId-1",
                    "isRequired": true,
                    "title": "How many items did you purchase at the grocery store?",
                    "choices": [
                        "1-5",
                        "6-10",
                        "11-20",
                        "20+"
                    ]
                }
            ]
        }
    ]
}
```

Is there any way to access the custom JSON data values we included when generating the survey model?

Each survey has approx 5 pages and each page has one question.  Each page/question combination will likely have different custom data associated within the survey.  Therefore I am open to having page level custom data or question/element level custom data if that is easier.  I'm just not sure how to access the custom data after the survey model is created.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: survey-vue version 1.0.38

**Comment by andrewtelnov** [comment]
@rachel-flux You have to customize the data onComplete event. Here is [the example](https://next.plnkr.co/edit/HGjNTeM2qr7tIL3e)

Thank you,
Andrew

**Comment by shashikant-lokare** [comment]
This is example for setting and getting customized data for 'pages'. Similarly, can we set and get the customized data to and from question? Such as setting attribute 'visibility' : 'show/ hide' to the radio button 'questionId-1'. Something like below code

 elements: [
                {
                    type: 'radiogroup',
                    name: 'questionId-1',
                    isRequired: true,
                    title:
                        'How many items did you purchase at the grocery store today?',
                    choices: ['1-5', '6-10', '11-20', '20+'],
                    visibility: 'show'
                },
            ],
