### ISSUE TITLE
functionality to add subtitle/description to questions. (question)

### ISSUE THREAD

**Issue by jasan-s** [surveyjs/survey-library#1349]
This may be a feature request if it doesn't already exist.  i.e 
<img width="822" alt="screen shot 2018-09-20 at 12 50 56 pm" src="https://user-images.githubusercontent.com/13863953/45843219-dc99fa00-bcd3-11e8-8382-9bddcd810919.png">

**Comment by tsv2013** [comment]
Survey model has the [onAfterRenderQuestion](https://surveyjs.io/Documentation/Library/?id=surveymodel#onAfterRenderQuestion) event, that can be used for questions customization as shown in this example - https://surveyjs.io/Examples/Library/?id=survey-afterrender&platform=jQuery&theme=default

**Comment by andrewtelnov** [comment]
@jasan-s We have a description property in the question. Probably you just need just this. Here is [the example](https://next.plnkr.co/edit/4ntCFBwvuDBaCA2v)

Thank you,
Andrew
