### ISSUE TITLE
Can I style SurveyRow dynamically

### ISSUE THREAD

**Issue by juliankrispel** [surveyjs/survey-library#1355]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the current behavior?
Currently I can see one way of applying dynamic styling to questions, via `onUpdateQuestionCssClasses`, it lets me modify the `className` of the question, but how can I configure the `className` of the row? That's what I need really :/

**Comment by juliankrispel** [comment]
@tsv2013 What I'm asking in my question is can I style it dynamically, as in idividual styles per row

**Comment by tsv2013** [comment]
SurveyJS hasn't have such an event. Probably you can use the "after render" events - https://surveyjs.io/Examples/Library/?id=survey-afterrender&platform=jQuery&theme=default
