### ISSUE TITLE
Make property editor work the same for itemvalue properties as for question properties

### ISSUE THREAD

**Issue by lady3bean** [surveyjs/survey-library#1358]
### Are you requesting a feature, reporting a bug or asking a question?
Bug/requesting a feature to make the API consistent. There also seems to be no workaround to do what I want given the API, so I'm looking for suggestions.

### What is the current behavior?
This example shows how to populate the property editor of a question property with choices based on a previous question's selected property value: https://embed.plnkr.co/l01zarPdpBWRiqPW4Kat/. 
This results in the a dropdown property editor being rendered along with the choices based off of the selected value, like so: <img width="881" alt="screen shot 2018-09-25 at 3 28 03 pm" src="https://user-images.githubusercontent.com/10011287/46090311-76532280-c17e-11e8-9301-935b4859cd4f.png">

However, when I add an "itemvalue" property and seek to do the same, the dropdown property editor renders renders but does not include the choices. Here is the HTML: 
![screen shot 2018-09-26 at 11 20 27 am](https://user-images.githubusercontent.com/10011287/46090508-d77af600-c17e-11e8-8d72-0d56bb031d22.png)

It is almost the same, but the options do not come through.

### What is the expected behavior?
I'd expect that
```
Survey.JsonObject.metaData.addProperty("question", {name: "targetEntity", choices: ["","Account", "Developement"]});
Survey.JsonObject.metaData.addProperty("question", {name: "targetField", choices: []});
```
would work the same as:
```
Survey.JsonObject.metaData.addProperty("question", {name: "targetEntity", choices: ["","Account", "Developement"]});
Survey.JsonObject.metaData.addProperty("itemvalue", {name: "targetField", choices: []});
```
if implementing the rest of the code in the Plunker in the same way. Since the property editor renders in the same way but just without the choices, this seems like a bug.

Ultimately, I want to be able to populate the choices of a custom itemvalue property with values based off the value of a question property when selected, updating the choices dynamically if the question property value changes.

I tried using `onPropertyValueChanging` to do this, but as far as I can tell, there is no way to then assign values to choices on an existing itemvalue. If my property is set up like so: `Survey.JsonObject.metaData.addProperty("itemvalue", {name: "targetField", choices: []});` - I don't see a way in the API to access and thereby reassign the 'choices' attribute a custom property. If there is a way to do this, please let me know, because this would provide a workaround to get the functionality I need. (Note that removing and then re-adding itemvalues onPropertyValueChanging is not an option because multiple questions will be using the property.)

### How would you reproduce the current behavior (if this is a bug)?

Change "question" to "itemvalue" in line 5 of the Plunkr and remove line 8.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@lady3bean Yes, we will try to come with a solution.
I do not like the code you have for question extension. It should be clear.
I will come back to this issue.

PS: Please create issues for Editor in [this repo](https://github.com/surveyjs/editor/issues)

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@lady3bean I have created [an issue](https://github.com/surveyjs/editor/issues/418). We will work on it. 

Thank you,
Andrew
