### ISSUE TITLE
Can you have dropdown options populate from an answer in a single input

### ISSUE THREAD

**Issue by blumedoom1** [surveyjs/survey-library#1359]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question

### What is the current behavior?

Right now I have a question with text boxes where our customers can list the locations they need service at. Later in the survey I want them to indicate their primary location from the the list they provided earlier, probably in a dropdown. For now the best solution I could come up with is asking them to list that location again. I'm not trying to confuse my customers or give them busy work. I hope that makes sense.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version: 69.0.3497.100
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: 1.0.46

**Comment by andrewtelnov** [comment]
@blumedoom1 Here is [the example](https://next.plnkr.co/edit/alaByJhNfQM9jdH4) by using onValueChanged event.

Thank you,
Andrew

**Comment by blumedoom1** [comment]
I appreciate you getting back to me on this, thank you.

Claire Blume
*Executive Assistant*

*Cypient Black LLC*
8070 Georgia Ave. Ste. 407
Silver Spring, MD 20910
(301) 358-3819
