### ISSUE TITLE
Support tree shaking

### ISSUE THREAD

**Issue by mikecousins** [surveyjs/survey-library#1362]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
We have to bring in the entire library and it's enormous.

### What is the expected behavior?
We should be able to bring in the parts we need so that we don't kill our performance.

* surveyjs platform: React
* surveyjs version: Latest

![image](https://user-images.githubusercontent.com/725614/46167684-b2a48280-c253-11e8-9140-b5b399582495.png)

The Javascript library for React comes in at 98.3KB when gzipped. This is pretty unacceptable and is the single biggest library that we use. Is there any chance that we can get this written so that we can bring in chunks of the library instead to bring this down if we aren't using all of the features?

**Comment by andrewtelnov** [comment]
@mikecousins You may fork the library, remove unneeded files from https://github.com/surveyjs/surveyjs/blob/master/src/entries/react.ts
https://github.com/surveyjs/surveyjs/blob/master/src/entries/chunks/model.ts
https://github.com/surveyjs/surveyjs/blob/master/src/entries/chunks/localization.ts

You may do not need matrixes questions or some others. The most questions are done as plug-ins you may remove them and build the library.

Moving from webpack into another solution may reduce the size as well.

Thank you,
Andrew

**Comment by chrismclarke** [comment]
+1 for this feature, stands at 650KB for survey-angular
![image](https://user-images.githubusercontent.com/10515065/58905179-10516e80-8701-11e9-8394-736abccb5ef7.png)

**Comment by dactechie** [comment]
I see that my minified version has many parts of the library which i don't use e.g. the signature pad.
Any update on the question about treeshaking ?

**Comment by tsv2013** [comment]
@dactechie At this moment library is built into a single package. If you want, you can create your custom build via removing unused elements from the https://github.com/surveyjs/survey-library/blob/master/src/entries/chunks/model.ts file and other entry point files.

**Comment by dirq** [comment]
+1.  Vue version is about 900k!!

**Comment by stevebering** [comment]
I would be very interested in tree-shaking capability. The survey-vue package makes up almost half of our vendor bundle. We don't need language packs, etc. So tree-shaking them out would help us quite bit. Removing unused components would be great as well.

**Comment by tsv2013** [comment]
Locked since the workaround suggested: https://github.com/surveyjs/survey-library/issues/1362#issuecomment-425204688
