### ISSUE TITLE
How to use surveyjs within a Vuejs single file component

### ISSUE THREAD

**Issue by fcam77** [surveyjs/survey-library#1368]
### Are you requesting a feature, reporting a bug or asking a question?

Do you have an example of using surveyjs embedded within a Vuejs single file component (.vue)?
Thank you.

**Comment by andrewtelnov** [comment]
@fcam77 Have you seen our [Vue quick start repo](https://github.com/surveyjs/surveyjs_vue_quickstart)?

Thank you,
Andrew

**Comment by fcam77** [comment]
Thank you Andrew - yes I have but encountered errors in adapting it to my project. I was hoping there was a simpler example but perhaps I'm just new to Vue.

Fred

**Comment by dmitrykurmanov** [comment]
@fcam77 you can create a repo and post it here, so we can check it.
