### ISSUE TITLE
How to change the class on element on value change. 

### ISSUE THREAD

**Issue by gajayreddy9** [surveyjs/survey-library#1370]
### Are you requesting a feature, reporting a bug or asking a question?

Question.

### What is the expected behavior?

I am trying to add a css class(colored border etc) to the elements when the value is empty in a text box or when the radio buttons are not selected etc and remove the css class when the value is entered/selected . Is there a way that we could use onChange event or OnBlur like we use in jQuery or how do we achieve this using surveyjs. Please suggest.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: 
* browser version: 
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version:

**Comment by dmitrykurmanov** [comment]
@gajayreddy9 sorry for the late response. I am going to add "is-empty" class for questions.
