### ISSUE TITLE
Collapse/expand all panels

### ISSUE THREAD

**Issue by kholibri3** [surveyjs/survey-library#1374]
### Are you requesting a feature, reporting a bug or asking a question?

Question.

### What is the current behavior?

Each panel has the state property which can be set to collapsed, expanded, or default.

### What is the expected behavior?

I'm curious if there's a way to collapse/expand all the panels in the survey. I would like to have a button on the same page as the survey that will serve to control this collapse/expand all functionality. Any suggestions of functions or properties that are exposed for this?

**Comment by tsv2013** [comment]
You con control the state of a panel by the [state](https://surveyjs.io/Documentation/Library/?id=panelmodel#state) property of a panel.
You can get the panels via the [getAllPanels](https://surveyjs.io/Documentation/Library/?id=surveymodel#getAllPanels) method of the survey.
This can be done before survey rendered, or you can update survey via the `survey.render()` method call.
