### ISSUE TITLE
Adding isRequired for a complex custom question

### ISSUE THREAD

**Issue by uzair-rm** [surveyjs/survey-library#1381]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question.
Have added a GeoLocation custom question, with two buttons, One to open a map, select co-ordinates from map, and update lat and long in two text fields, and one more button to get current location details. Everything works fine. But I wish to make it mandatory, when I add isRequired : true for normal questions, it works:

    function init() {
    var json = {
        title: "Survey Example", showProgressBar: "top", pages: [
            {
                questions: [
                    {  isRequired: true, type: "someQuestion", name: "someQuestion", title: "someQuestionStatus?" },
                    {  isRequired: true,  type: "geoLocation", name: "locationDetails", title: "Get location details" }
The first question, being simple works fine, the second one, whose html has two buttons, map, two text boxes, does not take isRequired, and on clicking 'Complete' button, completes form, instead of giving error, 'Please answer the question. '. And I'm using knockout to create custom question.

### What is the current behavior?
SurveyJs, isRequired is not handled for complex custom questions. For a simple custom question, adding 'isRequired: true', works fine, but not for complex question wherein there are more than one field (eg; could be a text box or a select).

### What is the expected behavior?
If a custom question, having multiple text boxes is made, and if it is made 'isRequired:true', it should make the entire custom question mandatory.

### How would you reproduce the current behavior (if this is a bug)?
Add a custom question, having multiple text boxes, then in schema make it 'isRequired : true', even thought the title shows that it is mandatory with a star at the top of title, but it still lets you complete without prompting error  'Please answer the question.'.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
function init() {
    var json = {
        title: "Survey Example", showProgressBar: "top", pages: [
            {
                questions: [
                    {  isRequired: true, type: "someQuestion", name: "someQuestion", title: "someQuestionStatus?" },
                    {  isRequired: true,  type: "geoLocation", name: "locationDetails", title: "Get location details" }
```
your_code_here

CustomQuestion.html---
<input type="button" data-bind="attr: { 'disabled': question.koIsReadOnly() },click: question.koToggle" value="Choose location from map" />
    <input type="button" data-bind="attr: { 'disabled': question.koIsReadOnly() },click: question.koGetDetails" value="Get details" />
<select data-bind="attr: { 'disabled': question.koIsReadOnly() }, options: question.koValues, value: question.selectedVal,"></select>
Latitude: <input type="text" data-bind="attr: { id: question.id + '_lat', 'readonly': question.koIsReadOnly() }, value: question.koLat" />
Longitude: <input type="text" data-bind="attr: { id: question.id + '_lon', 'readonly': question.koIsReadOnly() }, value: question.koLong" />
```

### Specify your

* browser: Chrome
* browser version: 69
* surveyjs platform (angular or react or jquery or knockout or vue): Knockout
* surveyjs version:

**Comment by andrewtelnov** [comment]
@uzair-rm I would suggest you to use the approach in creating custom widget that we are suggesting.
Here is the example of [custom widget and isRequired](https://plnkr.co/edit/YlTX09MC36l0WUDFKlnr?p=preview)

Additionally, in the next minor that we may release today, there is no koIsReadOnly() property anymore. isReadOnly property becomes observable, due working on [this issue](https://github.com/surveyjs/surveyjs/issues/1361)

Thank you,
Andrew

**Comment by uzair-rm** [comment]
> @uzair-rm I would suggest you to use the approach in creating custom widget that we are suggesting.
> Here is the example of [custom widget and isRequired](https://plnkr.co/edit/YlTX09MC36l0WUDFKlnr?p=preview)
> 
> Additionally, in the next minor that we may release today, there is no koIsReadOnly() property anymore. isReadOnly property becomes observable, due working on [this issue](https://github.com/surveyjs/surveyjs/issues/1361)
> 
> Thank you,
> Andrew

Hi Andrew, isRequired works fine for simple custom question type as shown in the plunker, in my case there are multiple fields in the question, 2 fields to be exact, and I pass 'isRequired' exactly the same way you have done in elements array, I also can see the isRequired value to be true in my js file 'koquestion_myCustomQuestion', I can also see the "*" on my title, but when I do complete, it completes.
Whereas when I put 'isRequired: true' from simple question as shown in plunker, with one field only and when it is empty, and I click complete, it gives error "Please answer the question."

**Comment by andrewtelnov** [comment]
I believe the current solution is [component questions](https://surveyjs.io/Documentation/Survey-Creator?id=Build-Component-Questions).

Thank you,
Andrew
