### ISSUE TITLE
Wrong text question's visibility when setting visibleIf

### ISSUE THREAD

**Issue by Jojo109** [surveyjs/survey-library#1382]
### Are you requesting a feature, reporting a bug or asking a question?
A question

### What is the current behavior?
There is unexpected visibility of a question. 

### What is the expected behavior?
The value of visibility should be calculated from expression of visibleIf

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
[https://next.plnkr.co/edit/Su2aW357QKVruGDK]

![survey3](https://user-images.githubusercontent.com/39783820/46650378-d316fa00-cbce-11e8-9fad-118e8f33cb8f.gif)

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: 1.0.48

**Comment by andrewtelnov** [comment]
@Jojo109 Here is the [corrected example](https://next.plnkr.co/edit/mluVY6t3IvwOgB8d?preview)

Thank you,
Andrew
