### ISSUE TITLE
Transition collapse/expand panel with animation

### ISSUE THREAD

**Issue by kholibri3** [surveyjs/survey-library#1385]
### Are you requesting a feature, reporting a bug or asking a question?

Question.

### What is the current behavior?

The state property of each panel in our survey is set to expanded when the page loads. 

When the panel is collapsed, the `<div>` within the `<h4 class="sv_p_title sv_p_title_expandable">` gets `"display: none"`. It appears that the styles on the `<h4>` trigger the collapse/expand functionality (`display: block` --> `display: none`) on the `<div>` .

### What is the expected behavior?

Is there a way to animate the collapse/expand functionality? I'm looking for a way to transition this functionality instead of the panel abruptly closing/opening.

**Comment by andrewtelnov** [comment]
@kholibri3 We may add onPanelStateChanging and onPanelStateChanged events and try to make something like in [this example](https://surveyjs.io/Examples/Library/?id=survey-animation)
However, I am not sure we will be able to make it work well. We have to try.
I will add it as a suggestion for now.

Thank you,
Andrew

**Comment by tsv2013** [comment]
We're working on animations and plan to release this feature in a month or two.
