### ISSUE TITLE
Dynamic Panel Button tags and attributes

### ISSUE THREAD

**Issue by wandecleya** [surveyjs/survey-library#1388]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting bug

### What is the current behavior?

When a dynamic panel is added two buttons automatically created:

```<input class=" " type="button" value="Add example" style="margin-top: 5px;">```

The absence of a class name makes hard to style the buttons.

The fact that the button is modelled as an input tag makes hard to use things like using a before pseudo-tag to add an icon to the button, which isnt applicable to an input.

Another thing that makes hard to customize it is the fact that the margin was added as an inline style, not possible to override by a separate css.

### What is the expected behavior?

```<button class="add_button" value="Add example" >```

### How would you reproduce the current behavior (if this is a bug)?
Add a dynamic panel and look at the html of the buttons

### Specify your

* browser: Chrome
* browser version: Version 69.0.3497.100 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.0.46

**Comment by tsv2013** [comment]
You can set custom CSS classes as shown in this example - https://surveyjs.io/Examples/Library/?id=survey-customcss&platform=jQuery&theme=default

Here is the working sample - https://next.plnkr.co/edit/HvzL8HhwWjQlewgQ?preview
