### ISSUE TITLE
Japanese locale 

### ISSUE THREAD

**Issue by munec** [surveyjs/survey-library#1389]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

There is no Japanese locale.

### What is the expected behavior?

Able to use Japanese locale.

### How would you reproduce the current behavior (if this is a bug)?

```
  survey.locale = "ja";
  survey.render();
```
Hi, may I create a pull request and share it if I create Japanese locale?

**Comment by andrewtelnov** [comment]
@munec Of course, it would be great if you make a pull request with Japanese translation. We definately miss it.

Thank you,
Andrew

**Comment by doongle** [comment]
The word 'Japanese' (日本人の) is wrong.
Correct value: "日本語"

**Comment by andrewtelnov** [comment]
@doongle I have corrected it in the commit above.
There are many untranslated strings in japanese file. It would be great if you share with others the translation.

Thank you,
Andrew
