### ISSUE TITLE
Matrix dynamic column data getting disabled on render

### ISSUE THREAD

**Issue by ashygk** [surveyjs/survey-library#1399]
### Are you requesting a feature, reporting a bug or asking a question?

question / bug

### What is the current behavior?
Our application has a feature where we pre-populate saved data(if any) whenever a survey renders.
I have a matrix dynamic survey where few columns are related which decides if they should be enabled/disabled.
I save my data and come back, all the related columns are disabled.

### What is the expected behavior?
Only columns that are disabled in my survey data should render as disabled.

### How would you reproduce the current behavior (if this is a bug)?

survey definition: `{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "text",
     name: "date",
     title: "Date",
     isRequired: true,
     requiredErrorText: "Please enter date.",
     inputType: "date"
    },
    {
     type: "comment",
     name: "Comment",
     startWithNewLine: false,
     title: "Comments",
     isRequired: true,
     requiredErrorText: "Please narrate.",
     maxLength: 2000,
     rows: 1
    },
    {
     type: "matrixdynamic",
     name: "MDynamic",
     titleLocation: "hidden",
     columns: [
      {
       name: "Name",
       cellType: "comment",
       isRequired: true,
       requiredErrorText: "Please enter name.",
       rows: 1,
       maxLength: 2000
      },
      {
       name: "Address",
       title: "Address",
       cellType: "comment",
       rows: 1,
       maxLength: 2000
      },
      {
       name: "TicketReceivedDate",
       title: "Ticket Received Date",
       cellType: "text",
       enableIf: "{row.TicketNotReceived} = false and {row.Reason NotReceived} empty",
       inputType: "date"
      },
      {
       name: "TicketNotReceived",
       title: "TicketUnReceived?",
       cellType: "boolean",
       colCount: 0,
       isRequired: true,
       enableIf: "{row.TicketReceivedDate} empty",
       defaultValue: "false"
      },
      {
       name: "Reason NotReceived",
       title: "Reason NotReceived?",
       cellType: "comment",
       isRequired: true,
       requiredErrorText: "Please enter reason not received.",
       enableIf: "({row.TicketNotReceived} = true and {row.TicketReceivedDate} empty) or ({row.TicketNotReceived} = false and {row.TicketReceivedDate} empty)",
       rows: 1,
       maxLength: 2000
      }
     ],
     choices: [
      1,
      2,
      3,
      4,
      5
     ],
     cellType: "text",
     rowCount: 0,
     defaultRowValue: {
      TicketNotReceived: false
     },
     addRowLocation: "top",
     addRowText: "ADD TICKET +"
    }
   ]
  }
 ],
 showTitle: false,
 showQuestionNumbers: "off",
 questionErrorLocation: "bottom"
}`

survey data: `{"MDynamic":[{"TicketNotReceived":true,"Name":"Scooby","Address":"illinois","Reason NotReceived":"No reason"},{"TicketNotReceived":false,"Name":"Akki","Address":"Georgia","TicketReceivedDate":"2018-10-09"}],"date":"2018-10-17","Comment":"no comments"}`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular 5
* surveyjs version: 1.0.52

**Comment by ashygk** [comment]
Please see the screenshot below, this data is pre-populated when the survey rendered and if you notice the second row, the check box is checked and the textbox next to it is filled, but yet, it is disabled.
![capture](https://user-images.githubusercontent.com/36975459/47452993-2cffee00-d791-11e8-8d44-79ac35478d7d.PNG)

**Comment by andrewtelnov** [comment]
@ashygk I have created the [example](https://plnkr.co/edit/WFMy1AcpqTMek0dmofJi?p=preview) and checked all 3 columns with enabledIf. They enabled and disabled exactly as you have asked them to be.
Could you point us, what do you think is wrong?

Thank you,
Andrew

**Comment by ashygk** [comment]
It works in the example you have give above. 
In our case, we are pre-filling the form by getting the saved answers from the database before the survey renders.

When the Survey.render method is called, while rendering the survey with pre-filled answers, it is having those fields disabled. Please see below at the second row.
![capture](https://user-images.githubusercontent.com/36975459/47514053-1e730e80-d845-11e8-8373-7175c1e339be.PNG)

**Comment by ashygk** [comment]
I entered the fields here and am ready to save it.
![1](https://user-images.githubusercontent.com/36975459/47519681-b24bd700-d853-11e8-8ee0-9505e276a6f1.PNG)

I have saved my form and this is how it is pre-populated

![2](https://user-images.githubusercontent.com/36975459/47519688-b7a92180-d853-11e8-999e-1fb1c80e6915.PNG)

**Comment by andrewtelnov** [comment]
@ashygk I have created the example based on your json and predefined data you gave us. Could you please fork my example and modify it so it stops working? In this case we will be able to see the issue and can work on the fix.

Thank you,
Andrew

**Comment by ashygk** [comment]
Could you please modify the example to use survey-angular rather than react..i modified the example to see how we are assigning the data and still couldn't reproduce the issue. Just curious it might be how it is rendering with angular.

**Comment by ashygk** [comment]
https://plnkr.co/edit/CrkWZIyuv1kJIobHlZwc?p=preview

**Comment by andrewtelnov** [comment]
@ashygk Sure, here is [the example on Angular](https://plnkr.co/edit/wKBUn9wmUBXp94pyCTyx?p=preview)
Probably you are using old version. Could you check it?

Thank you,
Andrew

**Comment by ashygk** [comment]
We are using Angular 5

**Comment by andrewtelnov** [comment]
@ashygk The executed code will be the same. The library is the same.

Thank you,
Andrew
