### ISSUE TITLE
requiredIf property for matrix dynamic?

### ISSUE THREAD

**Issue by ashygk** [surveyjs/survey-library#1401]
### Are you requesting a feature, reporting a bug or asking a question?

question / feature

### What is the current behavior?

I have a scenario where in a matrix dynamic, I need a column to be required if another column is checked(boolean). 
Right now I add an extra field and make it visible and required  when the boolean value is checked. the problem here is I now see two headers. Is there a possibility to just show one header or have a requiredIf property for matrix dynamic?

### What is the expected behavior?

I expect to not show the header of invisible column or have a requiredIf property implemented

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular5
* surveyjs version: 1.0.52

**Comment by andrewtelnov** [comment]
@ashygk We have several requests on adding requiredIf condition into question.
I think we will finally add it and to matrix column too. Please ping me on the next week.

Thank you,
Andrew

**Comment by ashygk** [comment]
Thanks. We have our application going to production next week. Is there a workaround you can provide until this feature is implemented?

**Comment by andrewtelnov** [comment]
@ashygk Sure, here is the [example](https://plnkr.co/edit/3qlYnc8v4gqUIdCefJK3?p=preview)

Thank you,
Andrew

**Comment by ashygk** [comment]
Can I have an example where atleast two fields (of suppose, 10 columns) are required in a matrix dynamic. can be any two

**Comment by andrewtelnov** [comment]
@ashygk I am not sure why do you need it, but ok :-) Here is [the fork version of initial example](https://plnkr.co/edit/GKQXHeDYKHydlpADLeSS?p=preview)

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@ashygk Sorry, what should I do? I have added three rows and got this result:
`result: {"cars":[{"driveCar":true,"cars":"Audi","text2":"weqw","text4":"qweqwewq","text5":"qweqwewqe"},{"driveCar":true,"cars":"Mercedes-Benz","text2":"qwewqe","text4":"qwewqewq","text7":"qwewqe"},{"driveCar":false,"text2":"qweqwe","text5":"wqewewqe"}]}`
It works fine to me.

Thank you,
Andrew

**Comment by ashygk** [comment]
Im sorry if I wasn't clear. Let me explain.
I have a matrix dynamic with suppose 10 columns.
When a user adds a row, I want him/her to add atleast three columns in each row. Those three columns could be any. I do not want to pose a restriction that a specific column should be filled.
Do you get me now?
