### ISSUE TITLE
The blank delay of the list when dropping the list.

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/survey-library#1409]
Hello, my angular project needs to use the jquery. nicescroll plug-in, but after using it, if the problem type is a drop-down list, when you click on the drop-down list, there will be a 1-2 second blank delay in the list before the option appears. Why?

![1](https://user-images.githubusercontent.com/37610470/47704938-1d384c00-dc60-11e8-82d2-81bb2b4c3488.jpg)
![2](https://user-images.githubusercontent.com/37610470/47704945-232e2d00-dc60-11e8-8885-2b00ed96a089.jpg)

**Comment by dmitrykurmanov** [comment]
@fengzhihenxs hello! It is hard to understand what's going wrong in your project. Could you please create a small example (you can fork plnkr example https://plnkr.co/edit/F0m2d1HidMZ5TYOeBVAw?p=preview) and we will try to help you.
