### ISSUE TITLE
How I can convert all pages to panels

### ISSUE THREAD

**Issue by NafanyaVictorovna** [surveyjs/survey-library#1410]
Question

If I want to show many page survey like one page and I want to show pages like a panels on new one page how I can do it?

Can not find any opportunities on documentation for page (convert to panel) or for survey. 

Tested page URL:
https://plnkr.co/edit/n9AFLy?p=preview

### Specify your

* browser: Chrome
* surveyjs version: surveyjs 1.0.52

**Comment by tsv2013** [comment]
You can use this setting - https://surveyjs.io/Documentation/Library/?id=surveymodel#isSinglePage

**Comment by NafanyaVictorovna** [comment]
@tsv2013 The question is how I can get all pages, and show them like panel and restyle them?

**Comment by tsv2013** [comment]
Here is the updated plunk - https://plnkr.co/edit/HTxlxnzfdzVnpiT1Mp3o?p=preview
Does it fit your needs?

**Comment by dmitrykurmanov** [comment]
@NafanyaVictorovna it would be great if you could share your decision here for other people

**Comment by NafanyaVictorovna** [comment]
@dmitrykurmanov no problem, will add plunker later.
What about my question?

**Comment by dmitrykurmanov** [comment]
@NafanyaVictorovna sorry I've missed it. We have `expand` and `collapse` methods for programmatically use. https://surveyjs.io/Documentation/Library/?id=panelmodel#expand and https://surveyjs.io/Documentation/Library/?id=panelmodel#collapse.

**Comment by NafanyaVictorovna** [comment]
@dmitrykurmanov Yea, thanks, I know, but how I can prevent to collapse panel, make it state like 'default' - always expanded?

**Comment by dmitrykurmanov** [comment]
@NafanyaVictorovna also please check this properties:

https://surveyjs.io/Documentation/Library/?id=panelmodel#state
https://surveyjs.io/Documentation/Library/?id=questionpaneldynamicmodel#panelsState
