### ISSUE TITLE
Add CustomError to question in dynamic panel 

### ISSUE THREAD

**Issue by Jojo109** [surveyjs/survey-library#1415]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
It can still go to next page when there is an error in question.

### What is the expected behavior?
It should not proceed to next page when there is an error. 

### How would you reproduce the current behavior (if this is a bug)?
![survey4](https://user-images.githubusercontent.com/39783820/47910377-a4d6c280-decd-11e8-827b-245a266a8d6f.gif)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

https://next.plnkr.co/edit/pB0r2OMJDd4Zmako

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: 1.0.47

**Comment by tsv2013** [comment]
You should use the [onValidateQuestion](https://surveyjs.io/Documentation/Library/?id=surveymodel#onValidateQuestion) event as shown in this example - https://surveyjs.io/Examples/Library/?id=validators-event&platform=jQuery&theme=default

I've modified your plunk to demonstrate how it works:
https://next.plnkr.co/edit/G7Q4bMjpeuL4Umbn

**Comment by Jojo109** [comment]
@tsv2013  Thanks. However I change the code in this example.
https://next.plnkr.co/edit/LoMY7oPh7875iTJ0

![survey5](https://user-images.githubusercontent.com/39783820/47918190-c2645600-dee6-11e8-9f55-e0aeb81745c0.gif)

No error display, when I set the value for option.error

**Comment by tsv2013** [comment]
@Jojo109 Why do you comment the working code? The `onValidatePanel` is not suitable event for questions.

**Comment by Jojo109** [comment]
@tsv2013 Would you mind to explain more about usage of options.error in onValidatePanel  for survey? So I can use the onValidatePanel  event properly

**Comment by tsv2013** [comment]
@Jojo109 My apologies for the late answer. The [onValidatePanel](https://surveyjs.io/Documentation/Library/?id=surveymodel#onValidatePanel) event is for the panel element, not for inner questions.

Use this event to modify the html before rendering. Options: 
- sender the survey object that fires the event 
- options.html an html that you may change before text processing and then rendering. The event is fired on validating a panel. Set your error to options.error and survey will show the error for the panel and block completing the survey or going to the next page. 
- options.name a panel name 
- options.error an error string. It is empty by default.

**Comment by Jojo109** [comment]
@tsv2013 Thanks
