### ISSUE TITLE
Survey displays a current date instead of a custom date.

### ISSUE THREAD

**Issue by stsiushkevich** [surveyjs/survey-library#1416]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

Survey displays a current date instead of a custom date.

![1](https://user-images.githubusercontent.com/12151060/47911453-83161500-dea6-11e8-8841-11552a209e03.png)
![3](https://user-images.githubusercontent.com/12151060/47911714-3e3eae00-dea7-11e8-991b-32548518a9e7.png)

**Comment by tsv2013** [comment]
I can't check the issue on our side.
It's hard to reproduce the issue on our side without exact steps.
Could you please provide us with ones.

**Comment by dmitrykurmanov** [comment]
@stsiushkevich hello! We've used native browser datepicker. I've created an example in plnkr: https://plnkr.co/edit/67zb3WtFI5S0hGC22ypC?p=preview with the datepicker. Could you please modify it to reproduce the bug?
