### ISSUE TITLE
Hide matrix dynamic rows based on column value

### ISSUE THREAD

**Issue by ashygk** [surveyjs/survey-library#1419]
### Are you requesting a feature, reporting a bug or asking a question?
question

### What is the current behavior?

hides rows based on questions, Reference #918

### What is the expected behavior?

should be able to hide rows based on column values of that respective row?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular 5
* surveyjs version: 1.0.53

**Comment by andrewtelnov** [comment]
@ashygk Do you want to hide the row based on colum value in the same row?
Then you should use the following expression: "{row.columnName} = 'yourValue'"
{row.ColumnName} - you will get the value of the cell value in the same row.

Thank you,
Andrew

**Comment by ashygk** [comment]
I tried the same but it didn't work

**Comment by andrewtelnov** [comment]
@ashygk Yes, you are right, rowsVisibleIf doesn't see "row." context. By the way, do you really need it? From UI point of you it would be strange if by changing a cell value in a row, the row would be disappeared and end-user could not show it again.
We have matrix dynamic, where the user may add/delete the row. 
What are you trying to implement?

Thank you,
Andrew

**Comment by ashygk** [comment]
@andrewtelnov  One of the columns we have customized to have an archive button. When the user clicks the archive button, that respective row should be hidden

**Comment by andrewtelnov** [comment]
@ashygk The functionality you are looking for is pretty close to matrix dynamic. You may rename the "Remove" button to "Archive" and you are done. What is the reason you want to use matrix dropdown instead?

Thank you,
Andrew

**Comment by ashygk** [comment]
I am using matrix dynamic.. See the subject? I need both remove and archive in this case.

**Comment by andrewtelnov** [comment]
@ashygk We will take a look at this isssue later. I am not sure right now, how it will be hard to add the "row." context here.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@ashygk I was trying to implement this functionality and unfortunately, I do not see any easy way, without many changes and probably breaking changes, to implement it. Considering that it is not commen scenario, it is better do not work on it. I will hide rowsVisibleIf for matrix dynamic. It works for matrix dropdown only.

I think that you may go in a different way. You may delete a row on your button click, but before deleting, store the row value (row.value) in an array, then onComplete event you may modify result data json, by adding a new varible or by modifying the matrix question value using the array where you have stored the deleted rows values.
It is several lines of code that would work perfectly for you scenario.

Thank you,
Andrew
