### ISSUE TITLE
"Complete" button does not immediately update to "next" on conditional page

### ISSUE THREAD

**Issue by flxwu** [surveyjs/survey-library#1420]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### Reproducing

Given the JSON below, select the second Checkbox in Question 2.

#### Expected behaviour:
* Question 3 is shown
* The submit button becomes a "Next"-button immediately (to advance to page2)

#### Actual behaviour:
* Question 3 is shown
* The submit button is not changed and still displays "Complete"
* When clicking on "Complete", it changes to "Next"

```json
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "question1"
    },
    {
     "type": "checkbox",
     "name": "question2",
     "choices": [
      "item1",
      "item2",
      "item3"
     ]
    },
    {
     "type": "dropdown",
     "name": "question3",
     "visibleIf": "{question2} = [\"item2\"]",
     "title": "frage",
     "choices": [
      "item1",
      "item2",
      "item3"
     ]
    }
   ]
  },
  {
   "name": "page2",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question4",
     "choices": [
      "item1",
      "item2",
      "item3"
     ]
    }
   ],
   "visibleIf": "{question2} = [\"item2\"]"
  }
 ]
}
```

### Specify your

* browser: Chrome
* browser version: 70
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.0.32

**Comment by andrewtelnov** [comment]
@flxwu I have tried it with the latest version (1.0.53) and it works fine to me. Here is [the example](https://plnkr.co/edit/oFp8GYUxoAbB8yFPYrxg?p=preview)

Thank you,
Andrew
