### ISSUE TITLE
Empty data prop prevents defaultValue from being populated

### ISSUE THREAD

**Issue by cameronmarlow** [surveyjs/survey-library#1429]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

If you provide a falsey data prop, default values do not get populated

### What is the expected behavior?

The data prop should be evaluated to test for falsey/empty values and populate defaults if so

### How would you reproduce the current behavior (if this is a bug)?

1. Create a survey with a default value
1. Create a react component 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://embed.plnkr.co/8CLsAfDxUJiAeS1pK87M/

Test code

```
var json = {
    questions: [
        {
            name: "name",
            type: "text",
            title: "Please enter your name:",
            defaultValue: "Jon Snow",
            isRequired: true
        }, {
            name: "color",
            type: "text",
            inputType: "color",
            defaultValue: "#FF0000",
            title: "Your favorite color:"
        }
    ]
};

export default class App extends React.Component {
  
  render() {
    return (
      <div>
        <h1>Survey with empty data prop</h1>
        <Survey
          json={json}
          data={undefined}
        />
        <h1>Survey without data prop</h1>
        <Survey
          json={json}
        />
      </div>
    );
  }
}
```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.0.53

**Comment by andrewtelnov** [comment]
@cameronmarlow Setting data to undefined, null or empty ({}) clearing the survey values. Here is what happens. you are setting a json, not a survey model, so the model is created in react component, then the survey model load its definition from the json, including setting the initial question values from default values, and then you are setting survey data to null, by clearing it completely.
I guess, you want to merge the data and do not to set it. In this case your code should be the following:
```
export default class App extends React.Component {
  
  render() {
    let survey =  new Survey.Model(json);
    for(var key in yourData) {
      survey.setValue(key, yourData[key];
    }
    return (
      <div>
        <h1>Survey with empty data prop</h1>
        <Survey
            model={survey}
        />
        <h1>Survey without data prop</h1>
        <Survey
          json={json}
        />
      </div>
    );
  }
}
```

Thank you,
Andrew
