### ISSUE TITLE
Add unit to single line text question

### ISSUE THREAD

**Issue by Evertude** [surveyjs/survey-library#1441]
### Are you requesting a feature, reporting a bug or asking a question?
Requesting a feature

### What is the current behavior?
I can have Single Line Text Questions with different input types

### What is the expected behavior?
I would like to add the unit of the input next to the answer, something like the following:
![image](https://user-images.githubusercontent.com/7377709/48714391-ef1cab00-ec12-11e8-960f-59f33c0b8104.png)

If it's possible, I would love to specify some kind of template for the value like in this case "{value}{unit}"
Additionally, it would be nice if the user could choose his unit (e.g. cm/inch or €/$)

**Comment by tsv2013** [comment]
Thank you for the suggestion. We'll keep it in mind.

You can change the question's markup in the [onAfterRenderQuestion](https://surveyjs.io/Documentation/Library/?id=surveymodel#onAfterRenderQuestion) event handler as shown in this example - https://surveyjs.io/Examples/Library/?id=survey-afterrender&platform=jQuery&theme=default.

**Comment by andrewtelnov** [comment]
@Evertude Another solution is to add a custom widget.
Here is the [custom widgets repository](https://github.com/surveyjs/widgets)
and here is the example of [a custom widget](https://plnkr.co/edit/HdnYE5?p=preview)

Thank you,
Andrew
