### ISSUE TITLE
How Add client name label to the same survey but  is aimed at diferent people 

### ISSUE THREAD

**Issue by ReneI** [surveyjs/survey-library#1443]
idclientename to json and the name label in html

**Comment by andrewtelnov** [comment]
@ReneI You may find [this example](https://surveyjs.io/Examples/Library/?id=survey-processtext) is useful as well.
To add any value into survey result json, please use the following code:
`survey.setValue("youValueName", youValue);`
Please read more about survey data functions [here](https://surveyjs.io/Documentation/Library/#data)

Thank you,
Andrew
