### ISSUE TITLE
Bug: survey.onAfterRenderSurvey() is called twice

### ISSUE THREAD

**Issue by cphamlet** [surveyjs/survey-library#1448]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
The event survey.onAfterRenderSurvey appears to be firing twice in 1.0.56. Unless I am doing something dumb (quite possible)

### What is the expected behavior?
The survey should be rendered once, unless manually rendered again.

### How would you reproduce the current behavior (if this is a bug)?
Quite possible I am doing something dumb here but I am at a loss. I have an init function which is listed below, called once. However, the survey is being rendered twice. I do not change the survey data, nor do I attempt to re-render the survey. Is it perhaps the survey being rendered in the library code twice?

#### Provide the test code and the tested page URL (if applicable)

This is my code: 

```javascript
function init() {
  Survey.dxSurveyService.serviceUrl = "/surveypanel";
  var css = {
    root: "sv_main sv_frame sv_default_css"
  };

  var model = new Survey.Model({ surveyId: somesurveyId, 
                          surveyPostId: somesurveyId, 
                          clientId:someclientId, sendResultOnPageNext:true});
  
  model.css = css;
  window.survey = model;
  console.log("This statement prints out once.")
  survey.onAfterRenderSurvey.add(function(survey){
    console.log("This statment prints out twice.");
  })

  model.render("surveyElement");
//Commenting the above render statement, prevents the survey from being re-renderd
}
```

### Browser Information

* browser: Chrome 
* browser version:  69.0.3497.81
* surveyjs platform (angular or react or jquery or knockout or vue): Knockout.js
* surveyjs version: 1.0.56

**Comment by cphamlet** [comment]
Update: I determined the exact problem with this. 

If I execute this code:

`  survey.onAfterRenderSurvey.add(function(survey){
    console.log("This statment prints out twice.");
  });

  survey.render("surveyElement");`

The statement prints out twice. For what reason, I am not sure. 

If I swap the two:

`  survey.onAfterRenderSurvey.add(function(survey){
    console.log("This statment prints out twice.");
  })`

**Comment by andrewtelnov** [comment]
@cphamlet I could not reproduce it, Could you please help me with it? Here is [the example](https://next.plnkr.co/edit/EAp5DasLEf6T7ds2)

This code is correct:
```
survey.onAfterRenderSurvey.add(function(survey){
   console.log("This statment prints out twice.");
 });
 survey.render("surveyElement");
```
and it should render only one time.

PS: Spread the good news about the product :) and thank you for using it!

Thank you,
Andrew

**Comment by cphamlet** [comment]
Amazing... I will look into this in greater detail. Thank you so much for keeping in contact.
