### ISSUE TITLE
Styling of input box changed unexpectedly after update from 1.0.41 to 1.0.53

### ISSUE THREAD

**Issue by omkardusane** [surveyjs/survey-library#1449]
Scenario: I have a survey with 2 of its questions in read-only mode, in 1.0.41 they looked like this:
![image](https://user-images.githubusercontent.com/12975569/49142430-c38a7680-f31e-11e8-8d11-d1bb7385a636.png)

and in 1.0.53 they look like:

![image](https://user-images.githubusercontent.com/12975569/49142537-01879a80-f31f-11e8-9ef1-a8a83432f5c5.png)

please note that I did not update survey.css from 0.1.x version because we have some custom styles.

Question.
Can you suggest a way to make it look like earlier, without downgrading

**Comment by dmitrykurmanov** [comment]
@omkardusane hello! 

What browser do you use? The problem in `word-break` css property and different browsers behaviour. Could you please check the commit: https://github.com/surveyjs/surveyjs/commit/a52d0bd41a64ad8886e5d4073b7a19a7a8c2b977.
The fix will be available in the next minor update 1.0.59.

As a workaround you can use the following code via the css:
```css 
.your-surveyjs-container -selector .sv_main span {
    word-break: break-word;
}
```
Thank you.

**Comment by omkardusane** [comment]
Hi @dmitrykurmanov , 

Thanks for the prompt response and suggession, 
applying this style did not work
``
.sv_main span {
    word-break: break-word !important;
}
``

browser is chrome latest, the pointer you gave to a commit: a52d0bd does not seem to help me
here are my understandings:

scenario 1 1.0.53 is rendered as ``<input>`` :
![image](https://user-images.githubusercontent.com/12975569/49144322-1c5c0e00-f323-11e8-9300-5a6e2d7017e7.png)

scenario 2 1.0.41 is rendered as ``<div>`` : 
![image](https://user-images.githubusercontent.com/12975569/49144278-02223000-f323-11e8-9663-466d5a54fa9e.png)



Thanks,

**Comment by dmitrykurmanov** [comment]
@omkardusane I understand your problem now. Unfortunately, this is braking change we've done.

But I think that now you can use onAfterRender event for your needs. Please check the example: https://plnkr.co/edit/qPw6vHCToe5cO1zXFTTS?p=preview

**Comment by omkardusane** [comment]
hi @tsv2013 , thanks, I shall try and update the css and see if this issue is fixed and if any other issues are arised

**Comment by omkardusane** [comment]
@tsv2013 , can you help me understand this `input` vs `div` situation, Can we expect to go to normal or shall we find a workaround?

**Comment by omkardusane** [comment]
Yes, at few of the places I can use comment, I will see if it renders a `div`, 
Thanks @tsv2013 , I appriciate the help

**Comment by tsv2013** [comment]
@omkardusane I've checked our code - comment question is rendered as an readonly textarea.
