### ISSUE TITLE
Custom errors : add and remove

### ISSUE THREAD

**Issue by dhwanivora** [surveyjs/survey-library#1453]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

Not sure

### What is the expected behavior?

Is there a way to add or remove custom errors?

I see addError() method but I don't see anything for resolving or removing errors

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@dhwanivora You may call `question.hasErrors(fireCallback: boolean = true): boolean;` It returns true if there is an error, create new errors if there are and clear errors if there is no any error.
Set fireCallback to true (default value) to show errors in UI.
Could you please describe your scenario? Why do you need to remove an error manually?

Thank you,
Andrew

**Comment by dhwanivora** [comment]
@andrewtelnov There is a file upload question that I am putting in my survey. The allowed formats are .yaml and .zip. I need to read the .zip file and extract all the .yaml files. If the .zip does not contain any .yaml files then I want to show an error message to user to upload the correct .zip file.
