### ISSUE TITLE
Minimum time timer

### ISSUE THREAD

**Issue by schoolmeister** [surveyjs/survey-library#1455]
### Are you requesting a feature, reporting a bug or asking a question?
Requesting a feature, but also asking a question

### What is the current behaviour?
Currently it's possible to set a timer per page that sets a limit on how much time a user can spend on a page. This timer counts from 0 up to X.

### What is the requested feature?
For our research we need to set a timer the other way, namely how much time a user should *at least* spend on a page. This timer counts from X down to 0. Before 0 a user should not be able to go to the next page. 

### Why?
In our research a user needs to complete some tasks and afterwards reflect upon their actions. We need a way to prove that users have spent at least X amount of time reflecting upon their actions. I'm not exactly sure whether this is a common use case, so I understand if you have more important features to implement right now.

### How to implement this myself?
 -- this question might be better suited for your editor repo -- 
Independent of whether you find it's worth implementing this feature, is it possible to implement this myself without touching your source code? (even though I'd like to make a pull request, there's little time left to learn the code base). Creating a new "Timer" widget that users of the editor can use probably works, but ideally I'd like it to just be a property of a page rather than a tool in the toolbox.

**Comment by andrewtelnov** [comment]
@schoolmeister I see the issue. Unfortunately, we do not have this functionality out of the box. You may implement it by using survey.onCurrentPageChanged event and survey.doComplete() function.
Let us know if you need a help.

Thank you,
Andrew
