### ISSUE TITLE
reassign data make dynamic panel still show old removed panels

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1458]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

after assigning new data with less panels removed panels are just emptied not removed from the UI

### What is the expected behavior?

remove empty panels

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/KlxzGVOZbrOS4OjnjwJJ?p=preview

maybe linked to #1083

**Comment by andrewtelnov** [comment]
@masciugo We do not reduce the panelCount property on setting the data. Since there are some scenarios, when it is not an expected behavior.
Could you set the panelCount as well. What is your scenario?

Thank you,
Andrew

**Comment by masciugo** [comment]
mmmm in my opinion the UI should always reflect the actual data but maybe I miss some obscure use cases. However in mine I need to compare different version of the same survey so I have an external dropdown to choose the version and on its change I reset the data with the saved ones related to the selected version

thanks anyway
