### ISSUE TITLE
Set all elements as visible in display mode

### ISSUE THREAD

**Issue by budupaul** [surveyjs/survey-library#1463]
### Are you requesting a feature, reporting a bug or asking a question?

Feature/Question

### What is the current behavior?

When survey is set as readOnly, elements that have a visibleIf property don't show

### What is the expected behavior?

I should have an option to make all elements visible on readOnly display mode

### How would you reproduce the current behavior (if this is a bug)?

Hide questions on a survey and put the survey mode on "display"

**Comment by andrewtelnov** [comment]
@budupaul Have you tried `survey.showInvisibleElements = true;` ?

Thank you,
Andrew

**Comment by budupaul** [comment]
@andrewtelnov This works. Where is it documented because I wasn't able to see it in the Docs?

**Comment by andrewtelnov** [comment]
@budupaul just added. I did not beleive somebody will need it. We use it in our SurveyJS Builder to allow end-users see all elements.

Thank you,
Andrew
