### ISSUE TITLE
progressbar without progressText (only visual indicator)

### ISSUE THREAD

**Issue by b166er** [surveyjs/survey-library#1464]
### Are you requesting a feature, reporting a bug or asking a question?
question, if not possible, then feature

### What is the current behavior?
i trying to hide the "Page X of X"-Text in progressbar to have just only visual indicator, but with my trying code, 
```
.sv_progress_bar span {display: none;}
```
i only see a grey-bar
![49535027-6e70d680-f8c3-11e8-83d9-85de297d7772](https://user-images.githubusercontent.com/679114/49547295-9885c100-f8e2-11e8-9409-87e586b7301b.png)

### What is the expected behavior?

this is my final wish result 
![49535070-87798780-f8c3-11e8-86e6-ca3e4e8766f0](https://user-images.githubusercontent.com/679114/49547313-a63b4680-f8e2-11e8-84ff-d9bbbcb7b6e4.jpg)
i need a progressbar without "Page X of X"-Text, only visual indicator, 
maybe with survey.progressText = ''; // but this is only read-only var.

### How would you reproduce the current behavior (if this is a bug)?
it's not a bug, see screenshot

#### Provide the test code and the tested page URL (if applicable)

Test code
app.js
```
Survey.StylesManager.applyTheme("bootstrap");
var json = {
	pages: [
		{
			title: { en: "What car are you driving?"},
			questions: [
				{
					type: "radiogroup",
					name: "qLiable",
					isRequired: true,
					choices: [
					    "None",
					    "Ford",
					    "Nissan",
					    "Audi",
					    "Peugeot"
				       ]
				}
			]
		}


window.survey = new Survey.Model(json);

survey
    .onComplete
    .add(function (result) {
        document
            .querySelector('#surveyResult')
            .innerHTML = "result: " + JSON.stringify(result.data);
    });

survey.showProgressBar = 'bottom';
survey.showPageNumbers = true;
survey.showQuestionNumbers = 'off';
survey.showPrevButton = true;
survey.showTitle = false;
survey.pagePrevText = '<';
survey.pageNextText = '>';
survey.completeText = '';
survey.questionTitleTemplate = ' ';
//survey.progressText = ''; // cannot set, read only

ReactDOM.render(<Survey.Survey model={survey} />, document.getElementById("surveyElement"));
```

index.html-file
```
<!DOCTYPE html>
<html>
    <head>
        <title>test</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script type="text/javascript" src="js/react.js" charset="utf-8"></script>
        <script type="text/javascript" src="js/react-dom.js" charset="utf-8"></script>
        <script type="text/javascript" src="js/browser.js" charset="utf-8"></script>
        <script type="text/javascript" src="js/survey.react.js" charset="utf-8"></script>
        <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="css/app.css">

    </head>
    <body id="content">
        <div id="surveyElement"></div>
        <div id="surveyResult"></div>
        <script type="text/babel" src="js/app.js" charset="utf-8"></script>
    </body>
</html>
```

app.css-file
```
.sv_progress {
	height: 10px;
	width: 420px;
	position: absolute;
	bottom: 25px;
	left: 55px;
}

.sv_progress_bar span { 
	display: none;
}
```

### Specify your

* browser: Google Chrome 
* browser version: v70
* surveyjs platform: react v16.6.1
* surveyjs version: v1.0.58

**Comment by tsv2013** [comment]
I've created a live sample for you - https://next.plnkr.co/edit/ImB7kE5taBcygIug
Text is hidden via CSS rule
Does it fit your needs?

**Comment by b166er** [comment]
> I've created a live sample for you - https://next.plnkr.co/edit/ImB7kE5taBcygIug
> Text is hidden via CSS rule
> Does it fit your needs?

Yes, Thank you!

**Comment by kelvin-homann** [comment]
For future Googlers stumbling upon this thread:
With the SurveyJS version 1.1.17 this CSS rule works: 

```css 
.sv_main .sv_container .sv_body div.sv_progress > span {
  display: none;
}
```

**Comment by PeterHassaballah** [comment]
How can I use the progressText Else where in my code ?
I am using React v:16^
Survey js v:1.1.25
