### ISSUE TITLE
separate style-class for question number in page

### ISSUE THREAD

**Issue by b166er** [surveyjs/survey-library#1467]
### Are you requesting a feature, reporting a bug or asking a question?
feature

### What is the current behavior?
i need to style the question number extra from title, currently it's not possible (or rather i simple don't found a solution, any hints are welcome). i tried with "::first-letter" but with a higher question number (over 10) i cannot style the second number.
first-page:
![1](https://user-images.githubusercontent.com/679114/49652363-2e7c3180-fa32-11e8-8841-d836b5845b50.png)
last-page:
![2](https://user-images.githubusercontent.com/679114/49652373-3340e580-fa32-11e8-87e3-365af5b3addc.png)

### What is the expected behavior?
the simplest solution i would like to see, is the page-number in a separate span/div-tag with own css-class, like: 
```
<div class="sv_p_root" data-rendered="r">
  <h4 class="sv_page_title">
    <span class="sv_page_title_numpage">1.</span>
    <span> Question-Text</span>
  </h4>
</div>
```
expected result: 
![3](https://user-images.githubusercontent.com/679114/49652382-3a67f380-fa32-11e8-9011-b5e9378baffa.png)

### How would you reproduce the current behavior (if this is a bug)?
see the code below

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/ANQujBliB3HZQo69NZE4?p=preview

index.css
```
.sv_page_title span {
	font-size: 1.2em;
	color: #31465b;
	line-height: 120%;
}
.sv_page_title::first-letter { 
	color: #fff;
	border-radius: 50%;	
	background-color: #A0C0A0;
	padding: 3px 6px 3px 9px;	
}
```

### Specify your

* browser: Google Chrome
* browser version: v71
* surveyjs platform: react v16.6.1
* surveyjs version: v1.0.59

**Comment by tsv2013** [comment]
This can be achieved via custom page title rendering
Here is the sample - https://next.plnkr.co/edit/btiqZFUZ28BIm5uf?preview
Does it fit your needs?

**Comment by b166er** [comment]
yes thank you for help! it's little bit more complex than I imagined, but whatever, it works for me and i'm happy!

**Comment by b166er** [comment]
sorry, but this code doesn't work with multi-language. if i change the language, only answers will changing but the title doesn't. do i need to clear values or re-initialize some models in .onAfterRenderPage() ?

**Comment by tsv2013** [comment]
@b166er Your plunk gives the "Uncaught SyntaxError: Unexpected token <" error in console.

I've fized my original plunk - https://next.plnkr.co/edit/btiqZFUZ28BIm5uf

instead of "title" you chould use "locTitle.renderedHtml"

**Comment by tsv2013** [comment]
We've add a card in our TODO list to implement separate rendering for number/required/title for all titles

**Comment by b166er** [comment]
> We've add a card in our TODO list to implement separate rendering for number/required/title for all titles - gor pages and questions

thats good news! 
i've fixed now my code in plunker, here a sample of non-translated page-title: https://plnkr.co/edit/mVVfmODLt2bYdkpH5gTe?p=preview 
you just need to click the button, show the title (in selected language), then close the popup (click to backgroud or to "X"), and click the other button, the page-title will stay the same language. still not work with "options.page.locTitle.renderedHtml"

**Comment by tsv2013** [comment]
@b166er It looks like you need to destroy previously rendered survey

**Comment by tsv2013** [comment]
We heed to put the required question mark (*) at the end of a question. See https://surveyjs.answerdesk.io/ticket/details/T1626 for more details.
