### ISSUE TITLE
Maximum input length doesn't matter if inputType is number

### ISSUE THREAD

**Issue by schoolmeister** [surveyjs/survey-library#1468]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
When using a single input with inputType set to "number" and maximum length set to anything, the input is always accepted, even if the number is longer than the maximum length.

### What is the expected behavior?
When setting maximum length to e.g. "2" you'd expect that "100" isn't accepted. 
Ideally, we'd be able to set a range of accepted numbers (e.g. 18 to 99).

#### Provide the test code and the tested page URL (if applicable)
Small plunker example: https://plnkr.co/edit/sECXrZ0H7xfvXVD7bSXc?p=preview

### Specify your

* browser: Chrome 
* browser version: 70.0.3538.110 (Official Build) (64-bit)
* surveyjs version: latest

**Comment by dmitrykurmanov** [comment]
Hello! According to the [doc](https://developer.mozilla.org/ru/docs/Web/HTML/Element/Input): 

> maxlength
If the value of the type attribute is text, email, search, password, tel, or url, this attribute specifies the maximum number of characters...

So this property is not for input with the type "number"

We need to use `max` and `min` props for that. And I thinks this is enhancement.

**Comment by andrewtelnov** [comment]
We have min and max properties for text question now.

Thank you,
Andrew
