### ISSUE TITLE
How to render React Component instead of html in completedHtml?

### ISSUE THREAD

**Issue by xAlstrat** [surveyjs/survey-library#1471]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

completedHtml only accepts an html string. I'd like to render a custom component using the quiz result data.

### What is the expected behavior?

There is another parameter that accepts a React Component to render at quiz completion?

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.0.58

**Comment by andrewtelnov** [comment]
@xAlstrat Hello, Here is [the example](https://codesandbox.io/s/ymmzn7l1q1)

Thank you,
Andrew

**Comment by xAlstrat** [comment]
I wanted to keep the Survey drawn but I think is better to unmount that component drawing a new one instead, just like your example. Thanks you so much !

**Comment by awlayton** [comment]
Sorry if this is the wrong place to ask, but is there a good way to use react components in place of html for other aspects? For example I have this code which I am not fond of for using React components in my `onAfterRenderQuestion` callback:

```javascript
// prop of my Survey conponent
onAfterRenderQuestion={
    (survey, {question, htmlElement}) => {
        if (!question.cerebralbutton) {
             return;
        }

        let seq = get(sequences`${question.cerebralbutton}`);
        ReactDOM.render(
        <Button onClick={() => seq()}>
            {question.title}
        </Button>
        , htmlElement);
    }
}
````

If this is just me not doing React right, you can just say so and I'll go away as I am new to this front-end stuff :expressionless:

**Comment by andrewtelnov** [comment]
@awlayton You may turn-off the complete page (`survey.showCompletedPage = false;`) and show your own component onComplete event.

Thank you,
Andrew

**Comment by awlayton** [comment]
The survey isn't complete yet in my example. I am trying to add a react component to one of the questions using the `onAfterRenderQuestion`.

**Comment by andrewtelnov** [comment]
@awlayton Yep, sorry, I did not read it carefully.
Well, I am afraid we don't have a good solution right now. We do have a general solution with onAfterRender, but it is something you may not want for react.

@tsv2013 I beleive there is a way to change a question rendering. I am not sure, is it possible to call the previous render function?

Thank you,
Andrew

**Comment by tsv2013** [comment]
@andrewtelnov As far as I understand we can't re-call the previous render function.

@awlayton  We can implement an event that pass you question render function result as an option. You can modify the render result and we'll return it as a question render result. To be honest I doubt this will be useful, because you will need to modify the JSX component structure.

@awlayton Could you share your business case - do you want to render the whole question by yourself, or you need to patch/change a part of a question inner structure?

**Comment by awlayton** [comment]
Rendering the whole question myself would be fine I suppose. In this particular instance I just want to add a button to the question.

**Comment by awlayton** [comment]
Is there any intention of supporting customizing the rendering of questions in react? My above hack is causing React to break eventually. I would be ok with having to render the entire question myself.

**Comment by andrewtelnov** [comment]
@xAlstrat You may not to show complete page at all [survey.showCompletedPage = false](https://surveyjs.io/Documentation/Library/?id=surveymodel#showCompletedPage) and onComplete event show your react component. It would be the easiest solution.

Thank you,
Andrew
