### ISSUE TITLE
Unable to use the survey constructor

### ISSUE THREAD

**Issue by Weedoze** [surveyjs/survey-library#1477]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
I am unable to use the survey constructor as described in the documentation : 

```
var json = {
    pages: [
        {
            name: "page1", 
            elements: [
                 { type: "text", name: "question1" }
            ]
        }]
}
var survey = new Survey.Survey(json);
```

### What is the expected behavior?
A survey object should be created to access its methods/properties.
For example, I have to access all the questions 
```
var survey = new Survey.Survey(json);
var questions = survey.getAllQuestions();
```

### How would you reproduce the current behavior (if this is a bug)?
I created a [JSFiddle](https://jsfiddle.net/nfyrq8kc/) to demonstrate the problem

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version: 70.0.3538.110
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.0.60

**Comment by andrewtelnov** [comment]
@Weedoze Please use the following code for react:
const survey = new Survey.Model(json);

Thank you,
Andrew
SurveyJS Team

**Comment by tsv2013** [comment]
@Weedoze  I've updated your fiddle - https://jsfiddle.net/nfyrq8kc/1/
