### ISSUE TITLE
Textarea field with no maxlength disaligns other elements in matrix dynamic

### ISSUE THREAD

**Issue by ashygk** [surveyjs/survey-library#1484]
### Are you requesting a feature, reporting a bug or asking a question?

question/bug

### What is the current behavior?

Text area field disaligns other fields in a matrix dynamic. Difficult when there is no max length property set. K will have to scroll up and down to see other fields data.

### What is the expected behavior?

Other fields should stay on top irrespective of the length of textarea.

### How would you reproduce the current behavior (if this is a bug)?

![image](https://user-images.githubusercontent.com/36975459/50100421-1e104780-01e6-11e9-96a9-5b55ccf0d7f3.png)

Had to scroll further down 

![image](https://user-images.githubusercontent.com/36975459/50100481-3d0ed980-01e6-11e9-9ebf-6b06ddcb7d80.png)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version: 
* surveyjs platform (angular or react or jquery or knockout or vue):  angular 5
* surveyjs version: 1.0.60

**Comment by dmitrykurmanov** [comment]
@ashygk  hello! I've created an example for you : https://plnkr.co/edit/LPrpbhG45v29E9FKTZKW?p=preview and it looks ok.

Could you please modify it to reproduce the issue?
