### ISSUE TITLE
matrix unanswered questions

### ISSUE THREAD

**Issue by DCToddM** [surveyjs/survey-library#1485]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question

### What is the current behavior?

Is there a way to find unanswered questions in a matrix.  I can do it for simple objects like textbox following this advice https://github.com/surveyjs/surveyjs/issues/1053 but I haven't been able to do it for any type of matrix control.

### What is the expected behavior?
I"d like to enter "unanswered" in the question not answered and have it included in my result set

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@DCToddM Here is [the example](https://plnkr.co/edit/GPMO4cyI9i2P4zsBrbCl?p=preview)

Thank you,
Andrew
