### ISSUE TITLE
Unpkg problem

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/survey-library#1487]
Here is a problem with unpkg: https://github.com/unpkg/unpkg.com/issues/156

So for example [https://unpkg.com/survey-knockout](https://unpkg.com/survey-knockout) doesn't work a while. Please use something like that: 

[https://unpkg.com/survey-knockout/survey.ko.js](https://unpkg.com/survey-knockout/survey.ko.js)

**Comment by Miletes** [comment]
Thank you very much for your fast reply. Is it fine to use that reference, or should i go back to the previous one when its fixed?
