### ISSUE TITLE
Custom navigation survey can be submitted with empty required questions

### ISSUE THREAD

**Issue by budupaul** [surveyjs/survey-library#1490]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

When implementing this -> https://surveyjs.io/Examples/Library/?id=survey-customnavigation&platform=jQuery# type of navigation, the user can go to the last page and submit the survey without answering the required questions on the other pages.

### What is the expected behavior?

Some kind of validation message should be shown because there are required questions that haven't 
 been answered and the survey should not be submitted.

### How would you reproduce the current behavior (if this is a bug)?

In the link above, go to the last page and submit the survey and this works, when it shouldn't as there are required questions in the first page.

**Comment by tsv2013** [comment]
I've just checked this sample and it works ok for me - user is not allowed to go to next page if he hasn't answered required questions on the current page. So user can achieve the last page in case he's aswered all required questions.
Please correct me if I'm missing something.

**Comment by budupaul** [comment]
> I've just checked this sample and it works ok for me - user is not allowed to go to next page if he hasn't answered required questions on the current page. So user can achieve the last page in case he's aswered all required questions.
> Please correct me if I'm missing something.
If you go on the link, in the upper left corner there is an option "Get/set the current page No:..". If you click here on 2 ( go to the last page ), and press the complete button, the survey will be completed, saying "Thank you for completing the survey!" even though the question on the first page ( "1. * OS" ) hasn't been answered

**Comment by tsv2013** [comment]
Ok. I see.

On the right panel you can see a list of properties related to the navigation functionality. In the ordinary mode you should use the [nextPage](https://surveyjs.io/Documentation/Library/?id=surveymodel#nextPage) and [prevPage](https://surveyjs.io/Documentation/Library/?id=surveymodel#prevPage) methods. 

You can force change current page. But if you want to check errors before, you can check the [isCurrentPageHasErrors](https://surveyjs.io/Documentation/Library/?id=surveymodel#isCurrentPageHasErrors) property of the `survey` object.

**Comment by budupaul** [comment]
Any update on this?

**Comment by tsv2013** [comment]
This sample - https://surveyjs.io/Examples/Library/?id=survey-customnavigation&platform=jQuery#
Demonstrates how to implement a custom navigation for SurveyJS library. So you can take this sample as a basis and write your own code to implement desired behavior.

You can pragrammatically iterate throgh all the questions (`survey.getAllQuestions()` and check the [question.isEmpty()](https://surveyjs.io/Documentation/Library/?id=questioncheckboxmodel#isEmpty) for all questions with [question.isRequired](https://surveyjs.io/Documentation/Library/?id=questioncheckboxmodel#isRequired) ).

Could you please specify - what certain code you've tried and what exact issues have you faced?

**Comment by andrewtelnov** [comment]
We do not make any checks when developer change the current page in the code. The developer should check the current page on errors, ``survey.currentPage.hasErrors()`` and then decide go on another page or not.

Thank you,
Andrew
