### ISSUE TITLE
display survey in 2 columns

### ISSUE THREAD

**Issue by MugiwaraNoMehdi** [surveyjs/survey-library#1493]
### Are you requesting a feature, reporting a bug or asking a question?
requesting a feature / asking a  question

### What is the current behavior?

the survey is displaying in full width, and depending on the screen it makes input text of more than 1000px

### What is the expected behavior?

just wanted to know if there is a template or something that can display two columns of questions in the same page like if I have : 

question 1 : 
input text 1

question 2 : 
input text 2

question 3 : 
input text 3

question 4 : 
input text 4

I wanted something like : 

question 1 :                                                          |        question 3 : 
input text 1                                                          |         input text 3
question 2 :                                                          |        question 4 : 
input text 2                                                          |         input text 4

**Comment by tsv2013** [comment]
Thank you for the suggestion.

Now you can create two panels side-by-side as shown in the JSON below:

```JSON
{
 locale: "de",
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "panel",
     name: "panel2",
     elements: [
      {
       type: "radiogroup",
       name: "question5",
       choices: [
        "item1",
        "item2",
        "item3"
       ]
      },
      {
       type: "dropdown",
       name: "question4",
       choices: [
        "item1",
        "item2",
        "item3"
       ]
      }
     ]
    },
    {
     type: "panel",
     name: "panel1",
     elements: [
      {
       type: "comment",
       name: "question3"
      },
      {
       type: "rating",
       name: "question2"
      }
     ],
     startWithNewLine: false
    }
   ]
  }
 ]
}
```

**Comment by MugiwaraNoMehdi** [comment]
Thank you for the answer, and for the great work 
and best wishes for the new year

**Comment by vsaiprakash** [comment]
Is it possible to keep more than 2 panels side by side? 

When I try to add more than 2 panels, the 3rd panel is always taking a new row.

**Comment by vsaiprakash** [comment]
> Thank you for the suggestion.
> 
> Now you can create two panels side-by-side as shown in the JSON below:
> 
> ```json
> {
>  locale: "de",
>  pages: [
>   {
>    name: "page1",
>    elements: [
>     {
>      type: "panel",
>      name: "panel2",
>      elements: [
>       {
>        type: "radiogroup",
>        name: "question5",
>        choices: [
>         "item1",
>         "item2",
>         "item3"
>        ]
>       },
>       {
>        type: "dropdown",
>        name: "question4",
>        choices: [
>         "item1",
>         "item2",
>         "item3"
>        ]
>       }
>      ]
>     },
>     {
>      type: "panel",
>      name: "panel1",
>      elements: [
>       {
>        type: "comment",
>        name: "question3"
>       },
>       {
>        type: "rating",
>        name: "question2"
>       }
>      ],
>      startWithNewLine: false
>     }
>    ]
>   }
>  ]
> }
> ```
Is it possible to keep more than 2 panels side by side?

When I try to add more than 2 panels, the 3rd panel is always taking a new row.

**Comment by dmitrykurmanov** [comment]
I think you could try to set minWidth, maxWitdth or width properties: https://surveyjs.io/Documentation/Library?id=panelmodel#minWidth
