### ISSUE TITLE
cannot access your website

### ISSUE THREAD

**Issue by healkar01** [surveyjs/survey-library#1494]
I cannot access https://surveyjs.io/

Last week I could, and ONCE this morning I got through.  The rest of the time, it times out.

Please advise.

Thank you,

Karen Healey

**Comment by tsv2013** [comment]
Unfortunately I've not managed to reproduce the issue. The site is openening ok for me,

**Comment by healkar01** [comment]
The site is opening OK for me now as well... very strange.  It didn't work yesterday at all, then it worked once this AM, then stopped working.  Now working again.  You might want to bring it to the attention of whomever supports your website that there are/were connectivity issues.

Thanks!

**Comment by andrewtelnov** [comment]
@MugiwaraNoMehdi @healkar01 I hope we fixed the issue completely. It was a DNS issue.

Thank you,
Andrew
