### ISSUE TITLE
Custom validator

### ISSUE THREAD

**Issue by AnnemiekeNL** [surveyjs/survey-library#1497]
Hi guys,

I am creating a custom validator, and as a test I copied the example (https://surveyjs.io/Examples/Library/?id=validators-custom&platform=Vue) in my project. This gives the following error: TypeError: Survey.__extends is not a function.

Is this a bug?

Tested page URL: https://surveyjs.io/Examples/Library/?id=validators-custom&platform=Vue

* browser: Chrome
* surveyjs platform: Vue
* surveyjs version: 1.0.63

**Comment by andrewtelnov** [comment]
@AnnemiekeNL It works fine to me.
By the way, have you seen [this example](https://surveyjs.io/Examples/Library/?id=validators-expression)? It covers the most scenarios without need to create a custom validator.

Thank you,
Andrew

**Comment by AnnemiekeNL** [comment]
I fixed it with the other example. But I have to use it muliple times, so it would be easier to create a custom one. Did I miss something here?

```
<script>
import * as SurveyVue from 'survey-vue'
let Survey = SurveyVue.Survey

var MyTextValidator = (function (_super) {
    Survey.__extends(MyTextValidator, _super);
    function MyTextValidator() {
        _super.call(this);
    }
    MyTextValidator.prototype.getType = function () {
        return "mytextvalidator";
    };
    MyTextValidator.prototype.validate = function (value, name) {
        if (value.indexOf("survey") < 0) {
            //report an error
            return new Survey.ValidatorResult(null, new Survey.CustomError(this.getErrorText(name)));
        }
        //return Survey.ValidatorResult object if you want to correct the entered value
        // return new Survey.ValidatorResult(youCorrectedValue);
        //return nothing if there is no any error.
        return null;
    };
    //the default error text. It shows if user do not set the 'text' property
    MyTextValidator.prototype.getDefaultErrorText = function (name) {
        return "You text should contains 'survey' word.";
    }
    return MyTextValidator;
})(Survey.SurveyValidator);
Survey.MyTextValidator = MyTextValidator;
//add into survey Json metaData
Survey
    .JsonObject
    .metaData
    .addClass("mytextvalidator", [], function () {
        return new MyTextValidator();
    }, "surveyvalidator");

export default {
  components: {
    Survey
  },
    data () {
        var vm = this
        
        const form = {
          locale: "nl",
          pages: [
            {
              name: "page1",
              elements: [
                {
                  type: "text",
                  name: "voornaam",
                  title: {
                    nl: "Hoe heet je? (voornaam)"
                  },
                  isRequired: true,
                  validators: [
                    {
                    type: "mytextvalidator"
                    }
                  ]
                }
            ]}
        ]}
    }
const model = new SurveyVue.Model(form)
model
      .onComplete
      .add(function (sender, options) {
        vm.onSubmit(sender.data)
    })
}
</script>
```

**Comment by MugiwaraNoMehdi** [comment]
the problem is when you are adding your validator.
replace 
`Survey.MyTextValidator = MyTextValidator;`
by
`Survey.JsonObject.metaData.addClass("mytextvalidator", [], function () {
        return new MyTextValidator();
    }, "surveyvalidator");`
and it will work... 
see the example here https://plnkr.co/edit/qRtgOrAda6QvZ0COu1yU?p=preview

**Comment by AnnemiekeNL** [comment]
Really strange, I get the same error (Survey.__extends is not a function)

**Comment by MugiwaraNoMehdi** [comment]
the example did not work for you ?

**Comment by AnnemiekeNL** [comment]
Nope

**Comment by AnnemiekeNL** [comment]
console.log(Survey) gives:

`ƒ VueComponent (options) {
      this._init(options);
    }`

Clicking on this gives:
`var Sub = function VueComponent (options) {
      this._init(options);
    };
    Sub.prototype = Object.create(Super.prototype);
    Sub.prototype.constructor = Sub;
    Sub.cid = cid++;
    Sub.options = mergeOptions(
      Super.options,
      extendOptions
    );
    Sub['super'] = Super;`

I'm lost here, so I hope you can make something out of this :-)

**Comment by MugiwaraNoMehdi** [comment]
can you retry to access https://plnkr.co/edit/qRtgOrAda6QvZ0COu1yU?p=preview open console and post what you get from console.log(Survey)... because it is a working example in plunker, if it works for me, it's that it works for you too... :s

**Comment by AnnemiekeNL** [comment]
Sorry, I was not clear. The plnkr is working for me, only a copy of the code in my project is still not working.
