### ISSUE TITLE
Restart quiz with incorrect (visible) answers only

### ISSUE THREAD

**Issue by craigsands** [surveyjs/survey-library#1507]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

1. Skips next question if correct.
2. Sends user back to the first page (with directions, not first question).

### What is the expected behavior?

Implement a 'retake incorrect' quiz. Each page has 1 question (this is important). Questions should be hidden after they are answered correct, and the OnCompleting function restarts (loops) the quiz with only the incorrect (visible) questions, unless every question is hidden (meaning the user finally answered them all correct).

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```javascript
survey
    .onValidateQuestion
    .add(function (sender, options) {
      if (options.value == options.question.correctAnswer) {
        options.question.visible = false;
      }
    });

survey
    .onCompleting  // does not work with onComplete either
    .add(function (sender, options) {
      if (sender.visiblePageCount == 0) {
        options.allowComplete = true;
      } else {
        options.allowComplete = false;
        survey.clear(false, true);
      }
    });
```

### Specify your

* browser: Firefox
* browser version: 64.0
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.49

**Comment by PeterHassaballah** [comment]
I have a similar issue I tried this but It does not do the trick yet.
I am using react.js
```

    onCompleteComponent = (survey, options) => {
        let mySurvey=survey;
        //this is the state used for the showCompletePage prop 
        this.setState({isComplete:false});
        mySurvey.currentPage = this.state.progress;
        //or try using this but both dont work 
        mySurvey.prevPage();
    }
```
When I console.log onCurrentPageChanged function I see the prevpage or the current page index changing but the view remains on the completedHtml view.

**Comment by andrewtelnov** [comment]
@craigsands @PeterHassaballah Here is the code that you can use and [example](https://plnkr.co/edit/Qjf8wcVgSmJadCbH).:
```js
survey.onComplete.add(function (sender) {
    survey.clearInvisibleValues = 'none';
    let hasIncorrected = false;
    const questions = survey.getAllQuestions();
    for (var i = 0; i < questions.length; i++) {
        const q = questions[i];
        if (q.correctAnswer === undefined || !q.isVisible) continue;
        if (q.isAnswerCorrect()) {
            q.visible = false;
        } else {
            hasIncorrected = true;
        }
    }
    if (hasIncorrected) {
        survey.getQuestionByName('intro').html =
            'You have made mistake(s), plase correct it(them).';
        survey.startSurveyText = 'Correct mistakes';
        survey.clear(false, true);
    }
});
```
Thank you,
Andrew
