### ISSUE TITLE
title to right input column

### ISSUE THREAD

**Issue by dafinoer** [surveyjs/survey-library#1510]
i want to show title to right input column in multipletext like this;

expectation;
input_column1 | title
input_column2 | title

**Comment by dmitrykurmanov** [comment]
Hello! Thanks for the question. We don't have that functionality. So I've added it to our todo list. As a workaround you can use the `onAfterRenderQuestion` event. Something like that: 
https://plnkr.co/edit/zOWW9QA9bD7wndv5ohu3?p=preview

Does it cover your needs?

Thanks.

**Comment by MugiwaraNoMehdi** [comment]
you can do this with css, take a look at https://stackoverflow.com/questions/17955983/flip-horizontally-html-and-css

**Comment by dafinoer** [comment]
Nice @dmitrykobets  :+1:
