### ISSUE TITLE
Checkbox "Other" input size

### ISSUE THREAD

**Issue by flowt-au** [surveyjs/survey-library#1519]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
Checkbox and Radio group questions have an "Other" text input box. The size (width) is quite narrow and if the user wants to write more than a few words it is not a great experience.

### What is the expected behavior?
I used the following css to make it 100% of the window. It seems to work for all my current surveys without breaking things but obviously needs more testing.

	.form-group {
		min-width: 100%;
	}
	.sv_q_checkbox_other {
		width:100% !important;
	}

Further to that, it would be great to be able to choose between a "textarea" or "text" to use as the "other" input option. In many of my surveys the checkbox options are sentences so the "other" option will generally require a lengthy response. I have resorted to a separate comment question using visibleIf but it would be better to roll all that into the checkbox question itself.

Thanks!
Murray

**Comment by dmitrykurmanov** [comment]
@flowt-au  Hello! I've created an example with your css and don't see any changes https://plnkr.co/edit/UA2O2b3elMjryy48S2PQ?p=preview may be I've missed something.

Also we have `hasComment` option: https://www.surveyjs.io/Documentation/Library/?id=questionradiogroupmodel#hasComment
May be `hasComment` is what you need: https://plnkr.co/edit/7uFlpuLBGYv1synXzyYK?p=preview

**Comment by flowt-au** [comment]
@dmitrykurmanov Thanks Dmitry. It seems the issue is the bootstrap theme. Yes, it works as expected without the css for the 'default' theme but it needs the extra css for the 'bootstrap' theme. I hadn't checked the theme before. Sorry. 

Also, to fix for both checkboxes and radiogroups it needs:

	.form-group {
		min-width: 100%;
	}
	.sv_q_checkbox_other {
		width:100%;
	}
	.sv_q_radiogroup_other {
		width:100%;
	}

Thanks for having a look.
Murray
