### ISSUE TITLE
Survey stops working after call to setState

### ISSUE THREAD

**Issue by dennisfischer** [surveyjs/survey-library#1524]
### Are you requesting a feature, reporting a bug or asking a question?
Bug report, example is attached.

### What is the current behavior?
https://next.plnkr.co/edit/ZzdpwCcEQNOQIMjY

If item2 in question2 is selected, then the navigation does not change and question3 stays hidden. This occurs after the call to `setState` in `componentDidMount`

### What is the expected behavior?
https://next.plnkr.co/edit/jkXmKgYyTJ8HVon5

After selecting item2 in question2 the survey should reveal question3 and the navigation should show the next page.

### How would you reproduce the current behavior (if this is a bug)?
With `setState`: https://next.plnkr.co/edit/ZzdpwCcEQNOQIMjY
Without `setState`: https://next.plnkr.co/edit/jkXmKgYyTJ8HVon5

### Specify your

* browser: Chromium
* browser version: 71
* surveyjs platform: react
* surveyjs version: 1.0.32 - 1.0.65

**Comment by andrewtelnov** [comment]
@dennisfischer We will take a look.

Thank you,
Andrew

**Comment by dennisfischer** [comment]
@andrewtelnov I found a "workaround", which outlines another or related problem. 

https://next.plnkr.co/edit/5q3MP9eY4HDz4ZFI 

This forces the child element (i.e., the survey) to reinitialize. Then, the navigation works. However, now the unmounted survey is still alive as we can see in the console (setState is called on an unmounted component).

**Comment by tsv2013** [comment]
You re-create the survey model in each render. That's why survey is always rendering again in it's initial state with hidden 3rd question.

Survey model has it's own state (current page, survey data, dynamic matrixes rows, dynamic panels and so on) and can't be "simply re-created".

I've updated your plunk to make it work - create survey model ones in the constructor. Does it fit your needs? - https://next.plnkr.co/edit/t0N1PPrvm7iqUSuo

**Comment by dennisfischer** [comment]
@tsv2013 I don't agree. Your solution seems to be a better workaround than mine but it does not fix the bug I reported. Let's have a look at the failing code:

```javascript
class Child extends React.Component {
    componentDidMount() {
        // This causes a problem
        this.setState({
            counter: 1
        });
    }

    render() {
        var survey = new Survey.Model(json);
        return (<Survey.Survey model={survey}/>)
    }
}

ReactDOM.render(<Child />, document.getElementById("surveyElement"));
```

This renders exactly twice: 1) before, and 2) after the call to `setState`. Afterwards, only the `Survey.Survey` component re-renders on changes. The `Child` component stays the same. However, the `Survey.Survey` component is broken now.

**Comment by tsv2013** [comment]
@dennisfischer The initial problem IMO was that survey model (not Survey.Survey component) is re-created on each render call. In this case it is needed to apply current survey model state each time.

Let me explain.

When used selects checkbox, the state of the survey model is being changed - surevy.data contains let's say `{ question2: ["item2"] }` . If the survey model re-created in this point, then it loses it's state and as a result - user doesn't see the third question.

Please correct me if I miss something or haven't got you right.

**Comment by dennisfischer** [comment]
@tsv2013 The initial problem is not that the survey model is re-created. Maybe https://next.plnkr.co/edit/ZSOOtvwJBW3iGALx makes it more obvious, no? Have a look at the console. It renders twice, and if you change the questions it will correctly recognize that the value changes. 

If for some reason the `Survey.Survey` component re-renders on every change, then this is clearly a bug in the library.

The assumption you make is that we're losing state because we re-create the survey model. But this is not the case. If you take a look at the submit event then you can see that question2 is checked - and in between we did not see any re-rendering!

Console log:
```
rendered
rendered
changed
{question2: Array(1)}
question2: ["item2"]
....
}
```

From that I conclude: 

1. The Survey is re-rendered once. A new survey model is created. After the re-render the survey stops functioning correctly.
2. The Survey model keeps track of the changes, but somehow the React Component does not update its state.
3. The workarounds can be an option until the root cause is patched. However, the workarounds trigger errors in the console (setState on unmounted component is a noop).

**Comment by tsv2013** [comment]
@dennisfischer  Could you please check the latest version of SurveyJS Library which is 1.0.65?

**Comment by dennisfischer** [comment]
@tsv2013 indeed, with 1.0.65 it looks to work better in the minimal provided example. However, I'm fairly certain that we have observed this bug in 1.0.65. I will check that and update the issue once I have a new minimal working example.

**Comment by andrewtelnov** [comment]
@dennisfischer I have looked at your example. Here is the [forked version](https://next.plnkr.co/edit/kipmTdAmdMnoAzjF)
react calls render, then didMount, since are you changing state on didMount it decides to call render one more time again.
Why do you create survey on render? You may create it in constructor, so it would not recreate itself on every render.

Thank you,
Andrew

**Comment by shehrozsheikh** [comment]
I am still getting this issue while calling any of the React Hook setters.
