### ISSUE TITLE
setValue(<String>) on a rating field

### ISSUE THREAD

**Issue by amit777** [surveyjs/survey-library#1551]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the current behavior?
setValue('3') does not set the value on a ratings field
setValue(3) does work

### What is the expected behavior?
setValue('3') should detect the numeric value of the string for a ratings field and set correctly.

### Specify your

* browser: Chrome
* browser version: 72
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.69

**Comment by dmitrykurmanov** [comment]
@amit777 Hello! Thank you for the interest! I think that you could do something like this:

```js
survey.getQuestionByName("myrating") = +"2";
```

**Comment by amit777** [comment]
hi, yes, I've done a work around with something like this:
(assume query string params are stored in queryObj)
Object.keys.forEach(function(q){
survey.setValue(q, parseInt(queryObj[q]) || queryObj[q]);
})
