### ISSUE TITLE
Bugging radiogroup: selection not visible

### ISSUE THREAD

**Issue by StephanMeijer** [surveyjs/survey-library#1553]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

![value-changes-but-not-visible](https://user-images.githubusercontent.com/3169264/53025575-6c013000-3461-11e9-9dae-ae69bb4942a2.gif)

### What is the expected behavior?

It should just work ™️ 

### How would you reproduce the current behavior (if this is a bug)?

???

#### Provide the test code and the tested page URL (if applicable)

```
      {
        title: {
          en: "Do you have anyone who depend on you financially?",
          ar: "هل لديك أي شخص يعتمد عليك مالياً؟"
        },
        description: {
          en: "For example aunts, parents, cousins, friends.",
          ar: "مثلا والديك، أوعماتك، أو أبناء عمك أو أصدقائك"
        },
        name: "dependence",
        type: "radiogroup",
        visibleIf: "{children} == 'no",
        isRequired: required,
        choices: [{value: 'yes', text: {en: "Yes", ar: "نعم"}}, {value: 'no', text: {en: "No", ar: "لا"}},]
      },

```

### Specify your

* browser: Chrome (Mac)
* browser version: `Version 72.0.3626.109 (Official Build) (64-bit)`
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: `1.0.71`

**Comment by tsv2013** [comment]
Unfortunately I've not managed to reproduce the issue in our demos. Please provide a small sample illestrating the issue to reproduce it on our side.

**Comment by StephanMeijer** [comment]
I'm on it.
