### ISSUE TITLE
Reset current choosed value when pressing "back" button

### ISSUE THREAD

**Issue by tadas117** [surveyjs/survey-library#1554]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

selecting:
question1 - any value
question2 - any value
question3 - any value

after going back to question1 and going forward:
question2 - value selected
question3 - value selected

### What is the expected behavior?

selecting:
question1 - any value
question2 - any value
question3 - any value

after going back to question1 and going forward:
question2 - value should be empty, user need to select again, because it will change visibility of further questions
question3 - value should be empty, user need to select again, because it will change visibility of further questions

### How would you reproduce the current behavior (if this is a bug)?

When scrolling and selecting in: question1 -> question2 -> question3....... , then going back to question1, selecting value and then after going to question2 or any other further - the value of question2 is already selected and not cleared. In this way, it shows questions that shouldn't be visible because there are visibleif statements.

#### Provide the test code and the tested page URL (if applicable)

I will provide my survey URL only for admin.

### Specify your

* browser: Chrome
* browser version: up to date
* surveyjs platform (angular or react or jquery or knockout or vue): Jquery
* surveyjs version: 1.0.71

**Comment by dmitrykurmanov** [comment]
Hello. Thank you for the interest. Could you please provide an example or json to reproduce the problem. And please specify your:
* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

Here an example and it looks ok for me https://plnkr.co/edit/WKWwV2rd5PvZzo9lX2gA?p=preview

**Comment by tadas117** [comment]
@dmitrykurmanov hi, I already edited my problem description. Check it now.

**Comment by tadas117** [comment]
@dmitrykurmanov your example is when question is in same and single page. I have 32 pages with 1-2 questions for each page.

**Comment by tadas117** [comment]
@dmitrykurmanov my JSON is here:

https://plnkr.co/edit/iAyvVT51cUEFGUcKrslX?p=preview

**Comment by dmitrykurmanov** [comment]
@tadas117 if I understand you correctly you need to clean all selected values of the page when user go pack from that page, isn't it? 

If yes you can use this code: 

```js
survey.	onCurrentPageChanging.add(function(survey, options) {
  var oldPage = options.oldCurrentPage;
  var newPage = options.newCurrentPage;
  
  if (newPage.visibleIndex < oldPage.visibleIndex ) {
    oldPage.questions.forEach(function(q) {q.value = null})
  }
});

```

Here an updated plunk https://plnkr.co/edit/z7jWilKHUlZdcuXCyWxJ?p=preview

**Comment by tadas117** [comment]
@dmitrykurmanov thank you! That was exactly what I needed! Could you also help with another issue regarding visibleIF functionality:

when i select qst-16 value item1 then qst-26-D is displayed later, however, than 26.E is also display but only 26.D should be visible. I managed to do all visibleIF statements but im stuck with this one. Also same problem for 27D and 27E

**Comment by dmitrykurmanov** [comment]
@tadas117 maybe you need to add additional check for `{qst-16} notempty` please check the small example https://plnkr.co/edit/jWDeQQoj5mZCp51SPjyX?p=preview

**Comment by tadas117** [comment]
@dmitrykurmanov that also fixed my problem but now, when I'm at:

qst-15 - answers - YES | NO
it shows complete button instead of next. I want still to show button name as "Next"
qst-16 has visibleif: qst-15 = "item1"

**Comment by dmitrykurmanov** [comment]
@tadas117 please create a small example to reproduce the problem

**Comment by tadas117** [comment]
Here, at 15 question when nothing is pressed

Plunker:
https://plnkr.co/edit/iAyvVT51cUEFGUcKrslX?p=preview

Image:
![image](https://user-images.githubusercontent.com/22645714/53178249-2a57bd00-35fa-11e9-8060-a6604baff996.png)

**Comment by dmitrykurmanov** [comment]
@tadas117 unfortunately I can't reproduce it. On my side I see "Next" button:

![image](https://user-images.githubusercontent.com/22315929/53179108-26c93380-3604-11e9-8be1-a3b58d7feb34.png)
 

Do I need to do something else to reproduce it?

**Comment by dmitrykurmanov** [comment]
@tadas117 it looks like in your case qst-15 is the last question (probable because of visibleIf's)

**Comment by tadas117** [comment]
@dmitrykurmanov check again. I updated JSON. How about to hardcode 15 question button with Jquery from "Complete" to "Next" ?

**Comment by dmitrykurmanov** [comment]
@tadas117  hardcode is bad practice. I would not recommend to use it. Sorry but I can't reproduce the problem. I've just tap `next` button until arrive 15 question and I see "next" button.

**Comment by tadas117** [comment]
@dmitrykurmanov i managed to do it with this code:

survey.onCurrentPageChanged.add(function(){
  if (survey.currentPageNo >= 13 && survey.currentPageNo <= 15) {
      $(".sv_next_btn").css('display','');
      $(".sv_complete_btn").css('display','none','important');
  }

  else {

  }
});

If you know better one - please let me now. I just force not to appear "Complete" button too early.

**Comment by dmitrykurmanov** [comment]
I am sorry but it would be great to reproduce the problem. SurveyJS shows `complete` button then there are no more questions in the survey. And changing button to `next` programmatically should not help. 

Could you please provide  exact steps to reproduce the problem in this plunker https://plnkr.co/edit/iAyvVT51cUEFGUcKrslX?p=preview ? We should ensure that we're testing the same code.

If I just tap "next next next" until go to the 15 question then I should see complete button, am I right?

**Comment by tadas117** [comment]
@dmitrykurmanov 

https://plnkr.co/edit/jRLbyLn6VAoXfIrNFdjX?p=preview

Use this plunker, because yours cant be edited due permissions. 

Also, now i have multiple problem: on 15 question - NEXT and COMPLETE buttons, they both are visible.

**Comment by tadas117** [comment]
@dmitrykurmanov 
![image](https://user-images.githubusercontent.com/22645714/53302991-d7863b80-386d-11e9-9e43-634666d4ab24.png)

**Comment by dmitrykurmanov** [comment]
@tadas117 thank you for the example. I will check it.

**Comment by tadas117** [comment]
@dmitrykurmanov if 26E has {qst-15} notempty and {qst-16} != "item1" and {qst-16} != "item2" then button  COMPLETE appears at 15 question

If 26E has {qst-15} notempty and {qst-16} != "item1" or {qst-16} != "item2" then there is no COMPLETE button, everything is fine until i pick question 15 value as "Yes", question 16 as "Delay", go till question 26D and then after next i see question 26E which should be invisible.

**Comment by dmitrykurmanov** [comment]
@tadas117 I've found the problem:

`complete` button appears because of you don't have any visible questions in the survey until you answered on `qst-15` so you can do the following:

```js
 ...
{
    "name": "page19",
    "elements": [{
      "isRequired": true,  // <=============
      "name": "qst-15",
      "title": "15. Have you ever experienced a flight disruption?",
      ...
    }, {
    "name": "page20",
    "elements": [{
      ...
      "visibleIf": "{qst-15} empty or {qst-15} = \"item1\"",   // <============= {qst-15} empty  or
      "title": "16. What kind of disruption did you experience?",
    }
 ...
```

here an updated plunk https://plnkr.co/edit/dTfgojBmg2vDZRjYokMS?p=preview
