### ISSUE TITLE
Unable to process binding "template: function (){return { name:'survey-content',afterRender:koEventAfterRender} }"

### ISSUE THREAD

**Issue by KhanUzair01** [surveyjs/survey-library#1562]
Created a custom question, with its custom properties, which now is throwing the below error.

### Are you requesting a feature, reporting a bug or asking a question?
Probably a bug.
Uncaught Error: Unable to process binding "template: function(){return { name:'objecteditorproperty',afterRender:$parent.koAfterRender} }"
Message: Unable to process binding "template: function(){return { name:'propertyeditor-'+ editorTypeTemplate,data:$data.editor} }"
Message: Unable to process binding "template: function(){return { name:'propertyeditor-modal',data:$data} }"
Message: Unable to process binding "template: function(){return { name:'propertyeditor-modalcontent',data:$data} }"
Message: Unable to process binding "template: function(){return { name:'propertyeditorcontent-'+ editorTypeTemplate,data:$data,afterRender:$data.koAfterRender} }"
Message: Unable to process binding "foreach: function(){return { data:koItems,as:'item'} }"
Message: Unable to parse bindings.
Bindings value: style:{display: 'inline-block'
Message: Unbalanced parentheses, braces, or brackets

### What is the current behavior?
The properties of a question are not showing up on the right, properties panel.

### How would you reproduce the current behavior (if this is a bug)?
Uncaught Error: Unable to process binding "template: function(){return { name:'objecteditorproperty',afterRender:$parent.koAfterRender} }"
Message: Unable to process binding "template: function(){return { name:'propertyeditor-'+ editorTypeTemplate,data:$data.editor} }"
Message: Unable to process binding "template: function(){return { name:'propertyeditor-modal',data:$data} }"
Message: Unable to process binding "template: function(){return { name:'propertyeditor-modalcontent',data:$data} }"
Message: Unable to process binding "template: function(){return { name:'propertyeditorcontent-'+ editorTypeTemplate,data:$data,afterRender:$data.koAfterRender} }"
Message: Unable to process binding "foreach: function(){return { data:koItems,as:'item'} }"
Message: Unable to parse bindings.
Bindings value: style:{display: 'inline-block'
Message: Unbalanced parentheses, braces, or brackets

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```
I have mailed the code at surveyjs.org@gmail.com
### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@KhanUzair01 It works fine in our tests and [examples](https://surveyjs.io/Examples/Builder/?id=customwidgets)

Thank you,
Andrew
