### ISSUE TITLE
matrix dynamic maxRowCount over 100 doesn't work

### ISSUE THREAD

**Issue by grooveslap** [surveyjs/survey-library#1589]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
With Matrix Dynamic, I cannot set the property "maxRowCount" to over 100 like 102 or 200. If I do and then save my survey, get back to the survey, the property has reverted back to 100.

If I set it lower than 100, it works OK. 

### What is the expected behavior?

The property "maxRowCount" stay as I set, not getting back to default value which is 100.

### How would you reproduce the current behavior (if this is a bug)?

1. add matrix dynamic to your survey
2. click the matrix dynamic you just added and set the property 'maxRowCount' to 101
3. save the survey 
4. click other area within the survey 
5. click again the matrix dynamic, then you can see the value of the property 'maxRowCount' is 100 not 101!

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version: 72
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.0.69

**Comment by andrewtelnov** [comment]
@grooveslap Please call the following code:
`QuestionMatrixDynamicModel.MaxRowCount = 200;` (it is 100) by default.

Thank you,
Andrew

**Comment by grooveslap** [comment]
@andrewtelnov 

Thanks you for your answer. 

I still have some questions regarding your answer as follows:

1) From surveyjs documentation, the property starts with lower case, which is 'maxRowCount'. So which one is correct? Or are they different?

https://surveyjs.io/Documentation/Library/?id=QuestionMatrixDynamicModel#maxRowCount

2) The way I call the API was (in coffeescript) like this but didn't work. 
`            
question = model.getQuestionByName('dynamicMatrix');

console.log 'question max row: ', question.maxRowCount

if question.maxRowCount is 100              
    question.maxRowCount = 500

console.log 'question max row: ', question.maxRowCount
`

The result message were 100
100  

not 

100 
500.

**Comment by andrewtelnov** [comment]
@grooveslap Here is the [example](https://plnkr.co/edit/PyK2GJhmRPM59ClTS977?p=preview)

Thank you,
Andrew
