### ISSUE TITLE
Problem with RadioGroup

### ISSUE THREAD

**Issue by Lucasflvsurvey** [surveyjs/survey-library#1590]
Good afternoon, 
I´m new here and i don´t have any experience in using json. I began recently using this language and i can´t solve a problem. 
I implemented  a radiogroup in my survey and each option opens a different question, but when I switch options, the old questions remain.
For example: when i have a choice with Yes or No, and each choice take to a different question. If I mark Yes, the next question will appear, and the next one. When I change to No, the old questions remain visible

**Comment by andrewtelnov** [comment]
@Lucasflvsurvey Sorry, it is hard to understand the issue without example or without survey json and steps to reproduce the issue.

Thank you,
Andrew

**Comment by Lucasflvsurvey** [comment]
Sorry for that. I will post the json and see if helps to understand my problem. I appreciate the attention

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by MugiwaraNoMehdi** [comment]
https://next.plnkr.co/edit/cT9jP4SIPbj63vgW
