### ISSUE TITLE
Adding both Rows and Columns in dynamic matrix

### ISSUE THREAD

**Issue by SpookyBoogy2016** [surveyjs/survey-library#1593]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
Dynamic matrix can only be added in one direction.

### What is the expected behavior?
Will this functionality be upgraded so that the survey takers can add row and/or columns?

**Comment by andrewtelnov** [comment]
@SpookyBoogy2016 when you are adding a matrix dynamic row, you are create a new row using a predefined template, a row with a number of cells with predefined cell types and properties.
If you are adding a new column, the end user or you (a developer) should set some additional properties: column name, column title, column cell type and likely some properties.
If you describe your scenario, why do you need it and what you are trying to achieve, we may find a solution for you.
SurveyJS is a library, that can be easily extended for many user cases that are not currently out of the box.

Thank you,
Andrew

**Comment by tino-liu** [comment]
Since January 2024, I have changed my GitHub account name to @tino-liu
