### ISSUE TITLE
Survey Results Information

### ISSUE THREAD

**Issue by clgerhardt** [surveyjs/survey-library#1602]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### Question:
From what I've noticed, survey.data is a key value pair of question and answer. Is there a way to get more information regarding survey data, such as question type or even more robust survey data ? or is it only/always a key value pair of question and answer ?  

* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.0.74

**Comment by tsv2013** [comment]
You can use  the `survey.getPlainData()` method

**Comment by clgerhardt** [comment]
@tsv2013 Thank you for that feedback. It does give a little more information which is always helpful!

**Comment by tsv2013** [comment]
@clgerhardt In any case the keys of the `survey.data` object are the question names. And you can use the `survey.getQuestionByName(<question namr>)` function to get as many information as you want ;-)

**Comment by clgerhardt** [comment]
@tsv2013 OH! I see what you're saying. This is very informative. Thank you 😄

**Comment by kc-nxtbig** [comment]
A question related to this (as I understand)
1. `survey.getPlainData()` method gives access to question names, titles, values, and diplayvalues
2. `survey.getAllQuestions` , `getQuestionByName`, `getQuestionByValueName` and `getQuestionsByNames` methods also provide access to questions and their data.
3. `survey.data` property is providing access to user  _(only responses only),_ values setToNames of triggers and calculatedValues (?). It excludes hidden/ unanswered questions from the list

Is there a way one can get access to all - questions (answered, hidden, unanswered) + setToName (names and values)  triggers and calculated values?

Thanks
--

**Comment by andrewtelnov** [comment]
@kc-nxtbig I am not sure what is your task. calculatedValues has a boolean property `includeIntoResult`, `false` by default. Triggers do not contain values, they just executed when expression becomes true. survey.getAllQuestions() will return all questions. I believe `survey.getAllQuestions()` and `survey.calculatedValues` and what you need.

Thank you,
Andrew

**Comment by kc-nxtbig** [comment]
Thank you @andrewtelnov , 
That helped.
