### ISSUE TITLE
Remove Uploaded file

### ISSUE THREAD

**Issue by sanjayksuthar** [surveyjs/survey-library#1607]
Hi @andrewtelnov ,

I'm using surveyjs with matrixdropdown question type and in one column provide a option to upload file.
file uploading working fine and stored in server but it can't clear file after click on clear button.

can you please help me in this

Thanks

**Comment by andrewtelnov** [comment]
@sanjayksuthar Do you mean, you can't clear it on server?

Thank you,
Andrew

**Comment by tsv2013** [comment]
@sanjayksuthar You can use the [onClearFiles](https://surveyjs.io/Documentation/Library/?id=surveymodel#onClearFiles) event as shown in this sample - https://next.plnkr.co/edit/sbvUCoQeRUeESbrL
