### ISSUE TITLE
Choices don't get passed through to tagboxes or custom controls in a matrix dynamic

### ISSUE THREAD

**Issue by dogwith1eye** [surveyjs/survey-library#1612]
A tagbox, or a custom control, that relies on choices, does not get choices passed through to it when set as an element of a dynamic matrix.

Here is a plunk showing the issue

https://embed.plnkr.co/yvSAjwCJXjdCYgag8BoR/

thanks
matt

**Comment by andrewtelnov** [comment]
@dogwith1eye Please add the following code into activatedByChanged function
```
      Survey.matrixDropdownColumnTypes.tagbox = {
        properties: [
          'choices',
          'choicesOrder',
          'choicesByUrl',
          'optionsCaption',
          'otherText',
          'choicesVisibleIf',
        ]
      };
```
It will allow matrix to know about your new widget. 
We do not have documentation for it yet, it is in our TODO list.
Here is [the example in our source code](https://github.com/surveyjs/surveyjs/blob/master/src/question_matrixdropdownbase.ts#L80).

Thank you,
Andrew

**Comment by dogwith1eye** [comment]
That fixes the issue with our custom widgets. I think it will need to be updated in the surveyjs custom widget project as well. 

https://github.com/surveyjs/widgets/blob/master/src/select2-tagbox.js

**Comment by andrewtelnov** [comment]
@dogwith1eye Yes. you are right. I have added it.

Thank you,
Andrew
