### ISSUE TITLE
Change font family 

### ISSUE THREAD

**Issue by sarn3792** [surveyjs/survey-library#1613]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the current behavior?
I can't change font family

### What is the expected behavior?
I would like to specify font family to survey text

#### Provide the test code and the tested page URL (if applicable)
![image](https://user-images.githubusercontent.com/9375416/55041873-b774a400-4ff4-11e9-9617-f151c81a4fd4.png)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): Angular6
* surveyjs version: 1.0.75

**Comment by sarn3792** [comment]
Additionally I want to change page title style. Center it, bigger font size, etc.
I attach an image where you can find the specific field.
Thanks!!

![image](https://user-images.githubusercontent.com/9375416/55042308-839a7e00-4ff6-11e9-9052-5f4507be6f75.png)

**Comment by tsv2013** [comment]
You can use the ordinary CSS rules:
```CSS
.sv_main {
  font-family: Thimes;
}

.sv_main .sv_container .sv_body .sv_p_root .sv_page_title {
    font-size: 2em;
}
```

Here is the working plunker - https://plnkr.co/edit/cZKD9DTYeB7T6eMxKLJl?p=preview
