### ISSUE TITLE
Display the columns again after a certain number of rows in Matrix(single choice)

### ISSUE THREAD

**Issue by SpikePiegal** [surveyjs/survey-library#1614]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

Column on displays at the top 

### What is the expected behavior?

Want columns to display after a certain number of rows so that user doesn't have to scroll up to see columns.  

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@SpikePiegal Unfortunately, we do not have this functionality. However, you may use the following trick.

Create a second question, remove its title, set the property titleLocation to "none" and set the same valueName to the your first and second matrix (you may have the third and forth and so on matrix).

Here is [the example](https://plnkr.co/edit/5X4HfLPSL5wYlxWpC3MN?p=preview).

Let us know if it works for you.

Thank you,
Andrew
