### ISSUE TITLE
How to wait for asynchronous validator expressresion?

### ISSUE THREAD

**Issue by csgchristian** [surveyjs/survey-library#1615]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the current behavior?
The validator function gets read as `undefined` before the asynchronous operation finishes.

### What is the expected behavior?
That validator function displays errors only if the asynchronous operation returns an invalid number.

### How would you reproduce the current behavior (if this is a bug)?
See code below for example.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: N/A

Test code

```
Survey.FunctionFactory
      .Instance
      .register("isValidNumber", function(params) {
        _this.isValidNumber(params).subscribe((num: number) => {
          return num; // Asynchronous return
        });

        // (validator instead receives 'undefined' while promise is resolving)
      });
```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version:

**Comment by andrewtelnov** [comment]
@csgchristian I would recomment to use our [survey.onServerValidateQuestions] event. It does all needed. Here is [the example](https://surveyjs.io/Examples/Library/?id=validators-server).

Thank you,
Andrew

**Comment by csgchristian** [comment]
@andrewtelnov I saw this when I was first implementing this system, the issue with [survey.onServerValidateQuestions] is I need to write new javascript for each new question validator. With the expression syntax on validators, I can modify a surveys rules without touching the javascript at all. For example, with the expression syntax I could put

'CallAPI('surveyTest/getMinimum', {question1}) > 5' as an expression in the survey, and as long as I've properly implemented 'CallAPI()', I wouldn't need to update any javascript to add additional validators.

**Comment by andrewtelnov** [comment]
@csgchristian We had several requests about making our validation async. I have added it into our TODO list. I can't promise we will include this task immediately, but we will definitely discuss about possibility to implement it every second week.

Thank you,
Andrew

**Comment by jeffbcsg** [comment]
Any progress on asynchronous validators?

**Comment by andrewtelnov** [comment]
@jeffbcsg I was thinking about posible API and could not come with something generic. We may dicuss it here.
So you don't want to have anyc/await function inside the SurveyJS registered custom function. Let's say we decided to registered the custom function that will go and check if the value is fine in the question is fine.
The standard function returns:
```js
function asyncFunction(params) {
  if (!params && params.length < 1) return -1;
          var xhr = new XMLHttpRequest();
          var url ="SomeURL" + params[0];
          xhr.open("GET", url);
          xhr.setRequestHeader(
            "Content-Type",
            "application/x-www-form-urlencoded"
          );
          xhr.onload = function() {
            if (xhr.status === 200) {
            }
          };
          xhr.send();
  //What should we return here? To tell SurveyJS wait. 
}
// Register the function for use in SurveyJS expressions
Survey.FunctionFactory.Instance.register("asyncFunction", asyncFunction);
//Question validators
"validators": [ { "type": "expression",  "expression": "asyncFunction({question1}) > 10", "You parameter is incorrect"  } ]
```
Everything that comes me in mind is more complicated than async/wait construction. What do you think? Probably we should make an example with async/wait and see how it goes...

Thank you,
Andrew

**Comment by csgchristian** [comment]
Is it possible the expression syntax could be updated to support an `await` operator?

```
"validators": [
    { "type": "expression",  
     "expression": "await asyncFunction({question1}) > 10", 
     "Your value is incorrect"  } ]
```

```
function asyncFunction(params) {
  if (!params && params.length < 1) return -1;
          var xhr = new XMLHttpRequest();
          var url ="SomeURL" + params[0];
          xhr.open("GET", url);
          xhr.setRequestHeader(
            "Content-Type",
            "application/x-www-form-urlencoded"
          );
          xhr.onload = function() {
            if (xhr.status === 200) {
              return 11; // Success
            }
            return 9; // Failure
          };
          xhr.send();
}
```

**Comment by andrewtelnov** [comment]
@csgchristian Nope, we need a built-in support for async in validators. We will think how to implement it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@csgchristian @jeffbcsg I have started to work on this functionality. Here is the [related issue](https://github.com/surveyjs/survey-library/issues/1806) to view the progress.
It will require a lot of code since if something is async then all related functionalities become async too.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@csgchristian @jeffbcsg The support for async expression is here. Here is pthe example](https://surveyjs.io/Examples/Library/?id=validators-async-expression) for async function in validator expression.

Thank you,
Andrew
