### ISSUE TITLE
Multiple answers in Quiz

### ISSUE THREAD

**Issue by mflash123** [surveyjs/survey-library#1617]
I find that for multiple answers author recommend use onIsAnswerCorrect event.
But I have no idea how integrate it. Can somebody make sinple example with simple Quiz with multiple answers, based in this example https://surveyjs.io/Examples/Library/?id=survey-quiz ?

**Comment by tsv2013** [comment]
Sorry for late response.

I'm not sure I've understood you right. Could you plase explain in greater details - what do you mean under the "multiple answers"? Probably you can share a survey JSON example&

**Comment by mflash123** [comment]
Multiple answers means that user can check 2 or more correct answers in 1
question.
I already find solution - onIsAnswerCorrect method

ср, 3 апр. 2019 г. в 10:38, tsv2013 <notifications@github.com>:
