### ISSUE TITLE
clearInvisibleValues is not working  when visibleIf is applied to a full page

### ISSUE THREAD

**Issue by qav-gabriela-castro** [surveyjs/survey-library#1626]
### Are you requesting a feature, reporting a bug or asking a question?

a bug

The example on plunker shows a survey example where 'page2' doesn't clear its values .

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  https://next.plnkr.co/edit/ojSXCF3TmmpqqdTE

**Comment by andrewtelnov** [comment]
@qav-gabriela-castro I have modified [your example](https://next.plnkr.co/edit/o09kbNfo41yXBTtE?preview) by showing the survey.data on every question value change. I do not see any issue, survey clears values of questions on page2 when it becomes invisible.

Thank you,
Andrew
