### ISSUE TITLE
Use Display Values In Title

### ISSUE THREAD

**Issue by muratsaglik** [surveyjs/survey-library#1629]
### Are you requesting a feature, reporting a bug or asking a question?

I have a question

### What is the current behavior?

entering individual values. ( Value - Title )

### What is the expected behavior?

I disabled value. I use display values in title

**Comment by andrewtelnov** [comment]
@muratsaglik Sorry, could you be please more specific? I did not understand the issue/question.

Thank you,
Andrew

**Comment by muratsaglik** [comment]
@andrewtelnov Iwould like to use title and value information just as a title. I mean title and value will be automatically the same.

**Comment by andrewtelnov** [comment]
@muratsaglik Do you mean in choices? Then just use value and title left empty.

Thank you,
Andrew

**Comment by muratsaglik** [comment]
@andrewtelnov Yes. How do I leave the value of selections blank by default?

**Comment by andrewtelnov** [comment]
@muratsaglik You can't leave the value blank. The value assign to an UI element. You may leave title blank and it will be the same as title.
Are you talking about SurveyJS Builder or SurveyJS Library - JSON/code?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@muratsaglik Could you describe your scenario? We may probably be able to suggest something.

Thank you,
Andrew

**Comment by muratsaglik** [comment]
I use SurveyJS Builder. I use choices. When I add an item I want it to get the same value with text. I don't want to change the value from the edit section.

**Comment by andrewtelnov** [comment]
@muratsaglik You post the question to the wrong repo, that is why it confused me.
Here is the [correct repo](https://github.com/surveyjs/editor).

And here is [the example](https://plnkr.co/edit/szqOhqW0V35uBVoTIFhM?p=preview).

Thank you,
Andrew

**Comment by muratsaglik** [comment]
@andrewtelnov Oh sorry. the same thing I want to do. https://github.com/surveyjs/editor/issues/14.

**Comment by andrewtelnov** [comment]
@muratsaglik OK, great!
