### ISSUE TITLE
custom-widget.tsx create a wrapper

### ISSUE THREAD

**Issue by marc0n3** [surveyjs/survey-library#1630]
### Are you requesting a feature, reporting a bug or asking a question?
Requesting a feature/asking a question

### What is the current behavior?
What i need is a custom widget that enable itself when some props are selected and renders a wrapper (collapsible) on some questions when checked.

### What is the expected behavior?
inside the render function, to have a second parameter : creator, to pass it down to my custom wrapper that basically do 

```
const comp = ReactQuestionFactory.Instance.createQuestion(element.getTemplate(), {
		question: element,
		isDisplayMode: element.isReadOnly,
creator:????
	});
	return <div ref={elRef} className={"blu-question"}>
		{!element.preCheckHideCheckbox && elRef.current && ReactDOM.createPortal(<CheckBox value={open}
		                                                                                   className={className}/>, $(elRef.current).parents(".question").find(".sv_q_title .num")[0])}
		<Collapse in={!!collapseOpen}>
			<div className={className}>{comp}</div>
		</Collapse>
	</div>
```
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
export const SurveyCheckboxWidget = {
	name: "confirmWidget",
	
	render: function (element) {

		return <SurveyCheckboxQuestion element={element}></SurveyCheckboxQuestion>
	},
	
	isFit: function (question) {
		return question.preCheckDisable ||
				question.preCheckHideCheckbox ||
				question.preCheckCollapse;
	},
	widgetIsLoaded: function () {
	
		return true; //we do not require anything so we just return true.
	},
};

```

Thanks in advance

**Comment by tsv2013** [comment]
Creator is an instance of react Survey class. Every survey question has a `creator` property and it would be available via `question.creator` property if it was `public`. But at this moment it has the `private` modificator. If me make it public, will it solve your problem?

**Comment by marc0n3** [comment]
Hi, this is my widget:
```
export const SurveyCheckboxWidget = (JsonObject) => ({
	name: "confirmWidget",
	//the widget title. It is how it will appear on the toolbox of the SurveyJS Editor/Builder
	title: "Text with button",
	//the name of the icon on the toolbox. We will leave it empty to use the standard one
	iconName: "",
	
	render: function (element,creator) {
		const comp = ReactQuestionFactory.Instance.createQuestion(element.getTemplate(), {
			question: element,
			isDisplayMode: element.isReadOnly,
			creator
		});
		return <SurveyCheckboxQuestion element={element}>{comp}</SurveyCheckboxQuestion>
	},
	activatedByChanged: function (activatedBy) {
		JsonObject.metaData.addClass("confirmWidget", [], null, "text");
		
	},
	isFit: function (question) {
		return question.preCheckDisable ||
				question.preCheckHideCheckbox ||
				question.preCheckCollapse;
	},
	widgetIsLoaded: function () {
		return true; 
});
```
do you suggest something like:
```
const comp = ReactQuestionFactory.Instance.createQuestion(element.getTemplate(), {
			question: element,
			isDisplayMode: element.isReadOnly,
			creator:element.creator
		});
```

in the render method?

If so this solves my poroblem

**Comment by tsv2013** [comment]
Yes, somthing like this, if the `element` is a survey `question`.

**Comment by marc0n3** [comment]
Thanks, I'll remove the pull request and close tha bug as soon as It's done.

**Comment by tsv2013** [comment]
I've made the `creator` public via the commit above

**Comment by marc0n3** [comment]
@tsv2013 
Actually this does not solve my issue.
You have added creator inside each element, but all I got inside the render method of the custom-widget is the model.

How can I do?
Thanks

**Comment by tsv2013** [comment]
Can you provide me with a plunker or other live code sandbox sample with your widget?

**Comment by marc0n3** [comment]
https://codepen.io/marcone/pen/JVXqYb

**Comment by carllau999** [comment]
@marc0n3 

Not sure why but sometimes your solution gives me a Maximum call stack size exceeded error
