### ISSUE TITLE
Hide question number in first page

### ISSUE THREAD

**Issue by sarn3792** [surveyjs/survey-library#1631]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the current behavior?
I can't hide question numbers in the first survey page

### What is the expected behavior?
![image](https://user-images.githubusercontent.com/9375416/55579877-83753f00-56d6-11e9-958d-ad8ca14fdbad.png)
In the survey it's first page in only customer information therebofe it should not show question number. I would like to show question number until the second page. Is there any way to do this?
Thanks!

### How would you reproduce the current behavior (if this is a bug)?
Not

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: all
* browser version: all
* surveyjs platform (angular or react or jquery or knockout or vue): angular2+
* surveyjs version:

**Comment by andrewtelnov** [comment]
@sarn3792 Please set questionTitleLocation property to "hidden" for your first page.

Thank you,
Andrew

**Comment by sarn3792** [comment]
> @sarn3792 Please set questionTitleLocation property to "hidden" for your first page.
> 
> Thank you,
> Andrew

Thanks! It works!

What about if I want to page numer start counting until page two? Is it possible?
![image](https://user-images.githubusercontent.com/9375416/55996476-1258fd00-5c7d-11e9-9116-67ae780c1685.png)

As you can see the first page is only about information therefore it must not be part of survey progress bar.
Thanks!
