### ISSUE TITLE
VisibleIf doesn't work with function

### ISSUE THREAD

**Issue by akovalyov** [surveyjs/survey-library#1632]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a possible bug

### What is the current behavior?

Function is not called thus container with text is not shown.

### What is the expected behavior?

Based on https://surveyjs.io/Documentation/Library/#visibility it's possible to register a custom function, which will be called and its result will be taken into account when calculation expression.

#### Provide the test code and the tested page URL (if applicable)

Just a very foolish  example -- let's say there is a form where you need to enter your height in meters, youw weight in kg and if [your BMI](https://en.wikipedia.org/wiki/Body_mass_index) is more than 25, you need to consider your diet. The key is the function, which will return any result.

Tested page URL: https://codepen.io/anon/pen/oOxwaK

### Specify your
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.78

**Comment by tsv2013** [comment]
Functions use another way of how parameters being passed:
```JS
function bmi(params) {
  var height = params[0];
  var weight = params[1];
  return height/ (weight*weight);
}
```

Here is the modified sample - https://codepen.io/anon/pen/NmNeLB

You can check this article for more details - https://surveyjs.io/Documentation/Library/#visibility
