### ISSUE TITLE
How can I change input to textarea in other radiobutton?

### ISSUE THREAD

**Issue by StanislavkoP** [surveyjs/survey-library#1634]
Hello, please tell me. How can I change input to textarea in "Other"radiobutton?

**Comment by StanislavkoP** [comment]
> Hello, please tell me. How can I change input to textarea in "Other"radiobutton?

**Comment by andrewtelnov** [comment]
@StanislavkoP Unfortunately, there is no way to do it at the current version.
I have added this request. I think we will implement it shortly, as well as we will change to textarea for question.comment 

Thank you,
Andrew
