### ISSUE TITLE
SurveyJS.io log in with github

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#1636]
I just tried creating an account on surveyjs.io; I tried to login via github:

![image](https://user-images.githubusercontent.com/547021/55728040-9a3bce80-5a13-11e9-80f2-d0bd36c465fa.png)

I don't think write access is / should be needed for login.

**Comment by andrewtelnov** [comment]
@tsv2013 Sergey, could you please take a look at it?

Thank you,
Andrew

**Comment by tsv2013** [comment]
@andrewtelnov Sure

**Comment by andrewtelnov** [comment]
@SamMousa The issue has been fixed some times ago.

**Comment by SamMousa** [comment]
When going through the flow of adding my github account it gives me an error though:
![image](https://user-images.githubusercontent.com/547021/65505410-6ec97500-dec9-11e9-8f45-b951ee4949b1.png)


I do get an email from github saying the the app was added.

Logging in does not work.

**Comment by tsv2013** [comment]
@SamMousa We've changed our github asdapter. Could you try to remove all cookies for the "surveyjs.io" site in your browser? Or try login form another browser or incognito mode?

**Comment by tsv2013** [comment]
OK. Thank you. We'll check it.

**Comment by tsv2013** [comment]
@SamMousa I've fixed the GitHub OAuth adapter. Could you check it?

**Comment by SamMousa** [comment]
Works!
