### ISSUE TITLE
Support for conjoint style questions - populating data from JS array

### ISSUE THREAD

**Issue by JedStephens** [surveyjs/survey-library#1637]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### Support table generation from a JavaScript array.
In conjoint analysis the options which populate a vignette table are sometimes (as in my case) randomly generated. The table then displays the (randomly generated) values which are housed in a javascript array.
This array is generated before the survey procedure. 

Is it possible to customize one of the questions so that I may achieve some output like the example below: (Example drawn from Hainmueller J, Hopkins D, Yamamoto T (2014). cjoint: Causal Inference in Conjoint Analysis: Understanding Multi-Dimensional Choices via Stated Preference Experiments, volume 22 number 1.)
![image](https://user-images.githubusercontent.com/26483444/55784333-9f9b2680-5ab0-11e9-9f47-b4c92c279654.png)

Where my randomly generated values (from the array) are the contents of the table. (The top row and left-hand column are fixed and can be populated ahead of time.)

I appreciate your assistance with this great package. 

### Specify your
* browser: Chrome
* browser version: current
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: current

**Comment by tsv2013** [comment]
Does matrix rubric fit your needs? Here is the demo - https://surveyjs.io/Examples/Library/?id=questiontype-matrix-rubric&platform=jQuery&theme=default

It looks very similar for me.
You can fill the `columns` and `rows` properties with your rendom data.
