### ISSUE TITLE
Add Survey To Website

### ISSUE THREAD

**Issue by SpikePiegal** [surveyjs/survey-library#1640]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

Survey doesn't load in HTML

Not sure where to put the code at from step 3 and step 4/ the JSON and the var code. 

### What is the expected behavior?

Survey to load and display on browser

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: http://highdemanddesigns.com/arc3s/survey

Test code

```
Using code from example 
https://surveyjs.io/Documentation/Library/?id=Add-Survey-into-your-Web-Page

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): jquery 
* surveyjs version:

**Comment by andrewtelnov** [comment]
@SpikePiegal I do not see any JavaScript code on your page, there is no json definition, creating model and rendering.  Steps 3, 4, 5 are missed.

Thank you,
Andrew

**Comment by SpikePiegal** [comment]
Do I embed part 3 and 4 inside of the html?

**Comment by andrewtelnov** [comment]
@SpikePiegal It should be in your javascript code as written in instruction. I did not find this code on your page.

Thank you,
Andrew

**Comment by SpikePiegal** [comment]
Okay, do I need to add this code to a superset js file or link it directly inside of the html.

Thanks,

David

**Comment by SpikePiegal** [comment]
Solved! Here's what I did, I added the code from step 3 and step 4 into a js file, linked it to the html page that I wanted to survey to appear on and it is there. Thank you @andrewtelnov !
