### ISSUE TITLE
Access panelIndex in callbacks?

### ISSUE THREAD

**Issue by awlayton** [surveyjs/survey-library#1641]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question.

Many of the callbacks receive the name and value for the relevant question. For example the `onValueChanged` callback passes them in the second parameter. However, if the question is in a dynamic panel these are not enough to uniquely identify it. Is there any way in this scenario to determine the `panelIndex` for the question which caused the callback?

### What is the current behavior?
```javascript
onValueChanged={(survey, {name, value, question}) => {
}}
```

### What is the expected behavior?
Is it possible to get it as a parameter on options?
```javascript
onValueChanged={(survey, {name, value, panelIndex, question}) => {
}}
```
Or is there some way to figure it out from the question parameter?
```javascript
onValueChanged={(survey, {name, value, panelIndex, question}) => {
    panelIndex = question.something;
}}
```

**Comment by andrewtelnov** [comment]
We missed this one. We have an event for this: [survey.onDynamicPanelItemValueChanged](https://surveyjs.io/Documentation/Library?id=surveymodel#onDynamicPanelItemValueChanged).

Thank you,
Andrew
