### ISSUE TITLE
Include Server-Side Rendering

### ISSUE THREAD

**Issue by derchirurg** [surveyjs/survey-library#1642]
### Are you requesting a feature, reporting a bug or asking a question?
feature

### What is the current behavior?
Server-side rendering is currently not possible.

### What is the expected behavior?
SurveyJS should be able to be used with server-side rendering. I would like to use it with angular-universal.

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular / angular-universal
* surveyjs version:

**Comment by andrewtelnov** [comment]
We are considering to implement React Native. Did not think about angular-universal yet.

Thank you,
Andrew
