### ISSUE TITLE
Random combinations of answers for radio question

### ISSUE THREAD

**Issue by kim66003** [surveyjs/survey-library#1643]
### Are you requesting a feature, reporting a bug or asking a question?

Is it possible to make random combinations of answers for a radio question, every time a new survey is started? The reason I want to do this is because the survey results will be biased if we provide the same combination of answers every time somebody fills in the survey. 

I have one page with 12 radio questions. Each question has two statements and the person filling in the survey can either agree with the first or second statement. All the statements can be categorized in one of 4 categories. Now I'd like to randomly combine questions from different categories. I have already written a code for this in python that combines two statements from these 4 categories randomly.

Now my question is: how do I use this function to randomly assign answers to these 12 questions, every time the survey is loaded again?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

Here is a part of my javascript code. I didn't include all 12 radio questions because the code gets really long.

{
        "name": "page4",
        "elements": [{
            "type": "panel",
            "name": "panel4",
            elements: [{
                type: "html",
                name: "question8",
                html: "<p>Je krijgt nu telkens twee stellingen te zien die gaan over redenen om culturele diversiteit na te streven. Kies telkens de stelling waar je het het meest mee eens bent.</p>"
            }, {
                type: "radiogroup",
                name: "question9",
                title: "Ik steun culturele diversiteit in onze organisatie...",
                isRequired: true,
                choices: [{
                    value: "1",
                    text: "...omdat het onze sociale verantwoordelijkheid is om een afspiegeling te zijn van de maatschappij",
                    score: 1,
                }, {
                    value: "2",
                    text: "...als kwaliteitsdoelen maar eerst gewaarborgd zijn",
                    score: 2,
                }]
            }, {
                type: "radiogroup",
                name: "question10",
                title: "Ik steun culturele diversiteit in onze organisatie...",
                isRequired: true,
                choices: [{
                    value: "1",
                    text: "...omdat teamleden met verschillende culturele achtergronden elkaar versterken",
                    score: 3,
                }, {
                    value: "2",
                    text: "...omdat wij als organisatie moeten inspelen op het diverser worden van de markt",
                    score: 4,
                }]
            }
            }],
            "title": "Onderdeel 1: Vragenlijst"
        }]
    }

### Specify your

* browser:
* browser version: chrome
* surveyjs platform (angular or react or jquery or knockout or vue): I use jquery: jquery-3.3.1.slim.min.js
* surveyjs version: 1.0.75

**Comment by andrewtelnov** [comment]
@kim66003 Would `radiogroupquetion.choicesOrder = "random"` work for you?
Please check [this example](https://surveyjs.io/Examples/Library/?id=questiontype-radiogroup) and change the **Choices order** property.

Thank you,
Andrew

**Comment by kim66003** [comment]
@andrewtelnov Thanks for your quick response. However, I don't think this would work as I have 12 different radio questions and I need the answers of all those 12 questions to be in a random order without duplicate answers. It would be great if could use a function in the "text" property to return a value (i.e. the answer).

For example: 

type: "radiogroup",
name: "question10",
title: "Ik steun culturele diversiteit in onze organisatie...",
isRequired: true,
choices: [{
value: "1",
text: "functionRandomAnswer()",
score: 3,
}, {
value: "2",
text: "functionRandomAnswer()",
score: 4,
}]

functionRandomAnswer() would then return a text (random answer) and hopefully this function would be called everytime the survey loads. However I don't know if this is possible and if it works like that. I thought about making my own property that accepts functions to return a string, but how would I go about doing that?

**Comment by kim66003** [comment]
Is it possible to call this function once (every time the survey is loaded) and then I would make a list of all these answers and just assign the answers like so:

functionRandomAnswer() // returns list
answers_list = [answer1, answer2, answer3, answer4, .....] // list of 24 answers for 12 questions

type: "radiogroup",
name: "question10",
title: "Ik steun culturele diversiteit in onze organisatie...",
isRequired: true,
choices: [{
value: "1",
text: "answer_list[0]",
score: 3,
}, {
value: "2",
text: "answer_list[1]",
score: 4,
}] etc. etc.

**Comment by andrewtelnov** [comment]
@kim66003  I just look at the code. The function of sorting choices is called on every choices change or filtering them.

However, to be honest, I do not understand your scenario completely. By anyway, you should be fine.

Thank you,
Andrew
