### ISSUE TITLE
VisibleIf for matrix(row) not working when we set the data of survey and do complete

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-library#1644]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
When I fill previously a survey with data, and complete the survey without changing the survey , just clicking on next button , and complete , the visibleIf for rows(Matrix Question) dont work

### What is the expected behavior?
When i complete the survey must remove extra data if the condition of visibleIf is false, with clearInvisibleValues

### How would you reproduce the current behavior (if this is a bug)?

Fill a survey with data(add extra data of course)
You must have a matrix with a visibleIf on one row with condition in false
Do a complete of survey

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://next.plnkr.co/edit/8Hs7c1bdkB3GuMtK
#### Extra
Works if the user change the parent question(in a answer that trigger false on child question)
and before complete its already clean, but in my case i fill the survey and without changing survey i do complete

### Specify your
* browser: Chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.79

**Comment by andrewtelnov** [comment]
@jmar1998 Sorry, it works fine to me. What is exactly wrong?

Thank you,
Andrew

**Comment by jmar1998** [comment]
@andrewtelnov when i do complete without changing the survey , only clicking next, and complete i get this
result:
 {
"satisfaction":4,
 "Quality":
        {
             "affordable":"3",
              "does what it claims":"3",
               "better then others":"3",
                "easy to use":"3"
         },
"recommend friends":4,
 "suggestions":"ASDASD","price to competitors":"Less expensive","price":"low","pricelimit":{"mostamount":"ASDASDA","leastamount":"ASDASD"},"email":"ADASDAS"}

The expected behavior on this case is the first one be removed on complete because the visible if of that row is 
VisibleIf:"{satisfaction} contains '3'"

thanks :)

**Comment by andrewtelnov** [comment]
@jmar1998 I see the issue now.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@jmar1998 I have fixed this bug for matrix and matrixdropdown. New unit tests are added.
We will release a new minor version on the next week. It will include the fix.

Thank you,
Andrew

**Comment by jmar1998** [comment]
@andrewtelnov thanks alot , very nice work with surveyjs 👍

**Comment by jmar1998** [comment]
@andrewtelnov extra on this problem, seems not working on every type question that have a visibleIf inside on a choice/row/option, i test this on radiogroup and i get the same behavior.
Thanks

**Comment by andrewtelnov** [comment]
@jmar1998 Indeed, I have added a new unit test and fixed it.
I had to change my yesterday fix as well. It should be total fine now.

Thank you,
Andrew
