### ISSUE TITLE
An event after survey validate the questions on the current page is missed

### ISSUE THREAD

**Issue by zhihil** [surveyjs/survey-library#1646]
### Are you requesting a feature, reporting a bug or asking a question?
I'm reporting a bug.

### What is the current behavior?
Accessing `surveyModel.isCurrentPageHasErrors` will cause `onErrorCustomText` events to be fired for each error on the page.

### What is the expected behavior?
The documentation says that `isCurrentPageHasErrors` is a readonly property. I would expect that accessing a property doesn't fire events, potentially triggering side-effects that I've added to these events.

### How would you reproduce the current behavior (if this is a bug)?
Add a `console.log` to `onErrorCustomText` and then access `isCurrentPageHasErrors` from any event such as `onAfterRenderSurvey`.

#### Provide the test code and the tested page URL (if applicable)

Run the below code and open the console.

If there are two questions on the first page of the survey, `onErrorCustomText` will fire twice.

Test code

```jsx
import React from 'react';
import { Model, Survey } from 'survey-react';
import { mockData } from '../lib/mockData';

export class SurveyTest extends React.Component {
    public render() {
        return <Survey 
            json={mockData} 
            onErrorCustomText={this.onErrorCustomText} 
            onAfterRenderSurvey={this.onAfterRenderSurvey}
        />
    }

    private onErrorCustomText = () => {
        console.log('onErrorCustomText');
    };

    private onAfterRenderSurvey = (s: typeof Model) => {
        s.isCurrentPageHasErrors;
    }
}

```

### Specify your

* browser: Chrome 
* browser version: 73.0.3683.103 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.0.78

**Comment by zhihil** [comment]
If this not a bug, and in fact, intended behaviour, I'd interested in an event or property that lets me determine when errors have appeared on SurveyJS.

For a project, I need to display an additional error message that links to the SurveyJS errors. I need to know when the SurveyJS errors are available to get their ids.

**Comment by andrewtelnov** [comment]
@zhihil The only solution that I may offer right now, is to use your own navigation: Previous, Next, Complete buttons. Here is [the example](https://surveyjs.io/Examples/Library/?id=survey-customnavigation). On next page and on complete, you may call survey.isCurrentPageHasErrors, clear your old external errors and create a new list. You may get all questions on the current page:
survey.currentPage.questions and then every question has question.errors.

If there is no errors, then call survey.nextPage() or survey.completeLastPage() functions.

Thank you,
Andrew

**Comment by zhihil** [comment]
@andrewtelnov Thanks for the response. I will try this solution.

Could you clarify if this is a bug or intended behaviour? My team will probably use SurveyJS in the future and I'm curious to know if this will get fixed. Otherwise, could this behaviour be listed somewhere in SurveyJS's documentation? This kind of behaviour seems unusual from my perspective, and it might trip people up.

**Comment by andrewtelnov** [comment]
@zhihil It is not a bug. In fact, you are the first one who have this scenario,
As I understand you need to get the access to all errors on the current page. You may easily can access them. Unfortunately, there are not events that would tell you: we are going to check for errors and we have finished checking for errors. Basically, you are looking for this functionality, if I do understand you properly. Am I right?

Thank you,
Andrew

**Comment by zhihil** [comment]
@andrewtelnov 

Well, our client has requested an external error message be placed above the survey. This external message contains a list of <a> links associated with each SurveyJS error. Clicking the link scrolls the screen to the corresponding SurveyJS error.

Essentially, we require functionality that is identical to `onAfterRenderSurvey` but for error messages. We need an event that fires after the SurveyJS errors appear on the DOM. 

This kind of event tells we should search the DOM and add the links to our external error message. We need to do this because the specific errors that appear might change, so it affects how far the browser needs to scroll.

**Comment by andrewtelnov** [comment]
@zhihil I think, we may create an example for this scenario.
Do you need to show errors for the current page only?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@zhihil I have a new event, onValidatedErrorsOnCurrentPage. It fires after question validation on the current page.
You may look at my [unit test](https://github.com/surveyjs/survey-library/commit/70c89ff79dacc9b3541d9a2ac9aba17f7936f36f#diff-180e6643e1a1547808dfe32bcce7822dR6743) to find out how it works.

It will be available in the next minor update, that we will release on the next week. You may build the library from source. The instruction for building library from source in the Readme file.

Let me know if it works.

Thank you,
Andrew

**Comment by zhihil** [comment]
@andrewtelnov The new event is working quite well, we aren't seeing duplicated effects like with `onErrorCustomText`. This has resolved the original problem listed by the ticket.

**Comment by andrewtelnov** [comment]
Great!
