### ISSUE TITLE
No currency for South Korea

### ISSUE THREAD

**Issue by grooveslap** [surveyjs/survey-library#1647]
### Are you requesting a feature, reporting a bug or asking a question?

Requesting a feature

### What is the current behavior?

No currency for KRW (South Korea Won) when using an expression with currency display type. 

As you might know, there are two Koreas: South and North. The thing is you can only set North Korean currency, which is KPW, whereas not South Korean currency, KRW. 

This is weird because North Korean currency is the least accepted in the world at the moment due to nuclear weapons issues and the sanctions by US government, etc.

While South Korea, a country of Samsung, LG, and Hyundai, must be an option for currency selection.

Or please let me know if there's a way to add a custom currency to the Expression.

### What is the expected behavior?

South Korea currency KRW should be an option for an expression with currency display type.

KRW typically appears with a symbol '₩' without any decimal point. 
Example: ₩200,000 

https://en.wikipedia.org/wiki/South_Korean_won

### How would you reproduce the current behavior (if this is a bug)?

1. Add an expression question
2. Set displayType to 'currency'
3. There no 'KRW' option

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version: 73
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.0.61

**Comment by tsv2013** [comment]
Could you specify - what exact survey question type are you using?

**Comment by andrewtelnov** [comment]
@grooveslap I have added "KRW" currency code. I am really sorry for this mistake. Probably we have copied currency codes from a wrong place.

Thank you,
Andrew
