### ISSUE TITLE
Connecting with mySQL

### ISSUE THREAD

**Issue by SpikePiegal** [surveyjs/survey-library#1650]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

Not able to send data to database

### What is the expected behavior?

connect database to MySQL

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: http://highdemanddesigns.com/arc3s/

Test code
Not sure where to get the JSON_URL from
```

survey.onComplete.add(function (sender, options) {
      var xhr = new XMLHttpRequest();
      xhr.open("POST", "YourServiceForStoringSurveyResultsAsJSON_URL");
      xhr.setRequestHeader("Content-Type", "application/json; charset=utf-8");
      xhr.send(JSON.stringify(sender.data));
});

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@SpikePiegal You should create your own service for storaging json data or use our (it is free).
You should create an account on surveyjs.io and create a survey (it can be empty) then follow [the instruction](https://surveyjs.io/Documentation/Library/?id=Add-Survey-into-your-Web-Page) on the Step 5.
```
//You should get the Guid for storing survey data in surveyjs.io service storage
survey.surveyPostId = 'e544a02f-7fff-4ffb-b62d-6a9aa16efd7c';
//You may call survey.sendResult function as another option.
function sendDataToServer(survey) {
  survey.sendResult('e544a02f-7fff-4ffb-b62d-6a9aa16efd7c');
}
```

Thank you,
Andrew

**Comment by SpikePiegal** [comment]
Hey Andrew, we would like to have the results hosted on our own servers! 

Currently I have added this to the js file
 `survey.onComplete.add(function (sender, options) {
      var xhr = new XMLHttpRequest();
      xhr.open("POST", "connect.php");  <---- Connects to php file
      xhr.setRequestHeader("Content-Type", "application/json; charset=utf-8");
      xhr.send(JSON.stringify(sender.data));
});
`
Then so far in my php file I have 
`<?php
    //connect and select the database
     $connect = mysql_connect("localhost","root","") or die('Database Not Connected. Please Fix the Issue! ' . mysql_error());

    
     // get the contents of the JSON file 
$results = $_POST['sender'];
 
//Decode the JSON string and convert it into a PHP associative array.
$decoded = json_decode($results, true);
    

    //Insert the fetched Data into Database
    $query = "INSERT INTO 
    VALUES
    
     if(!mysql_query($query,$connect))
    {
        die('Error : Query Not Executed. Please Fix the Issue!  ' . mysql_error());
    }
     else{
            echo "Data Inserted Successully!!!";
     }
?> 

`

My question now is when I am using $POST in the php file is it correctly pulling  this file xhr.send(JSON.stringify(sender.data)); 

xhr.open("POST", "connect.php");  <---- Connects to php file

**Comment by SpikePiegal** [comment]
Hey Andrew, we would like to have the results hosted on our own servers!

Currently I have added this to the js file
`
survey.onComplete.add(function (sender, options) { var xhr = new XMLHttpRequest(); xhr.open("POST", "connect.php"); <---- Connects to php file xhr.setRequestHeader("Content-Type", "application/json; charset=utf-8"); xhr.send(JSON.stringify(sender.data)); }); 

`
Then so far in my php file I have
`
<?php
//connect and select the database
$connect = mysql_connect("localhost","root","") or die('Database Not Connected. Please Fix the Issue! ' . mysql_error());

 // get the contents of the JSON file 
$results = $_POST['sender'];

//Decode the JSON string and convert it into a PHP associative array.
$decoded = json_decode($results, true);

//Insert the fetched Data into Database
$query = "INSERT INTO 
VALUES

 if(!mysql_query($query,$connect))
{
    die('Error : Query Not Executed. Please Fix the Issue!  ' . mysql_error());
}
 else{
        echo "Data Inserted Successully!!!";
 }
?>

`

My question now is when I am using $POST in the php file is it correctly pulling this file xhr.send(JSON.stringify(sender.data));

xhr.open("POST", "connect.php"); <---- Connects to php file

**Comment by andrewtelnov** [comment]
@SpikePiegal Unfortunately, we can't support all numerous server platform and database. We just give the ability to implement this for developers. [Here is the answer](https://stackoverflow.com/questions/4834917/how-would-i-save-my-javascript-objects-with-json-php-mysql-to-re-load-them-upon) to your question on stackoverlow.
You may just google: how to store json from client php mysql

Thank you,
Andrew

**Comment by SpikePiegal** [comment]
Thanks I understand thanks for pointing me in the right direction, but when the survey is completed and we receive the Json file.
In your version of the database do you store the data by name of the question and the answer, does the json file we receive only have the answers and name of questions.

Thanks.

**Comment by andrewtelnov** [comment]
@SpikePiegal survey.data contains only question.name: question.value. You may call [survey.getPlainData()](https://surveyjs.io/Documentation/Library/?id=surveymodel#getPlainData) function to get the survey results in another format.

Thank you,
Andrew

**Comment by SpikePiegal** [comment]
Hey @andrewtelnov you mentioned survey.data contains the question.name and question.value but in the code I have it shows sender.data and this isn't able to be pushed in a POST. Should I change that to survey.data?

`survey.onComplete.add(function (sender, options) {
    
      var xhr = new XMLHttpRequest();
    
      xhr.open("POST", "connect.php", true);
    
      xhr.setRequestHeader("Content-Type", "application/json; charset=utf-8");
    
      xhr.send(JSON.stringify(sender.data));
});
`

**Comment by andrewtelnov** [comment]
@SpikePiegal The client code looks good to me. I beleive the problem in your connect.php file. However, I may be mistaken.
I would suggest to ask a question on stackoverflow.com, about saving json in mysql using php.

Thank you,
Andrew

**Comment by SpikePiegal** [comment]
Connected and everything is working smoothly. 

Thanks

**Comment by jemorape** [comment]
@SpikePiegal do you resolved how you put the survey data on your database? I have the same problem.
