### ISSUE TITLE
Others required

### ISSUE THREAD

**Issue by kouhunzhe** [surveyjs/survey-library#1651]
### Are you requesting a feature, reporting a bug or asking a question?

asking a question

### What is the current behavior?
Other commentText are required

### What is the expected behavior?
Other remarks do not wish to be required

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@kouhunzhe Do you mean [question.otherText](https://surveyjs.io/Documentation/Library/?id=questionradiogroupmodel#otherText) property?

Thank you,
Andrew
