### ISSUE TITLE
file question

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1653]
### Are you requesting a feature, reporting a bug or asking a question?

question/feature/bug I don't know exactly

### What is the current behavior?

cannot prepopulate survey showing ONLY filename with link when storeDataAsText is enabled. 

### What is the expected behavior?

I'd like to simply show attached file showing ONLY filename as a data:uri download link 

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/BIOZnfoPpJXiLb1cBdbK?p=preview

other related issues and docs https://surveyjs.io/Documentation/Library/?id=QuestionFileModel#showPreview did not help

**Comment by tsv2013** [comment]
We've not such an option yet. I;ll take look what we can do.

**Comment by tsv2013** [comment]
I've added the `allowImagesPreview` option

Since 1.0.82 you can use the following JSON:
```JSON
{
                        type: "file",
                        title: "Please upload your photo",
                        name: "image",
                        storeDataAsText: true,
                        allowImagesPreview: false,
                        //showPreview: false,
                        maxSize: 102400
                    }
```
