### ISSUE TITLE
Add image for each page and/or question

### ISSUE THREAD

**Issue by laurabennett** [surveyjs/survey-library#1654]
Feature Request

I am creating a quiz with one question per page and would like the ability to specify an image in the json object to use as the background. I'm generating the list of questions dynamically so including the background as part of the css isn't feasible.

**Comment by tsv2013** [comment]
You can add a custom property, let's say called `background` to page and question as shwon in this example - https://surveyjs.io/Examples/Survey-Creator/?id=addproperties&theme=bootstrap and then patch markup of a page/question usging the `onAfterRender...` event as shown in this example - https://surveyjs.io/Examples/Library/?id=survey-afterrender&platform=jQuery&theme=default

**Comment by laurabennett** [comment]
Excellent, thanks!
