### ISSUE TITLE
Is there a method to clear error message?

### ISSUE THREAD

**Issue by Fengzhen8023** [surveyjs/survey-library#1655]
### Test step

1. There is some required question in page1 of the survey
2. click a button to use  `survey.isCurrentPageHasErrors`
3. There is some error message

### Expectation
1. click a custom button such as  **Clear Error** button
2.  the error message is cleared

**Comment by andrewtelnov** [comment]
@Fengzhen8023 Sure, here is [the example](https://plnkr.co/edit/iQ5sgd67SOIeJHkvputp?p=preview) and the code:
```
function clearErrors() {
  if(!survey || !survey.currentPage) return;
  var questions = survey.currentPage.questions;
  for(var i = 0; i < questions.length; i ++) {
    questions[i].errors = [];
  }
}
```

Thank you,
Andrew

**Comment by JiangFei** [comment]
if the question in panel dynamic or panel, how can I clear the question errors?
thanks

**Comment by andrewtelnov** [comment]
@JiangFei I guess, we will need to add page/panel/question clearErrors function.
It will be a lot of code here, for matrices and dynamic panel. It is better to add it on library level. I am adding it into our TODO.

**Comment by andrewtelnov** [comment]
@Fengzhen8023 @JiangFei The next minor update v1.0.82 that we are going to release today will have page(panel/question).clearErrors() function.

Here is [the related Unit Test](https://github.com/surveyjs/survey-library/commit/cc2196227bd7e249564d145f3df6187b0f997ffe#diff-180e6643e1a1547808dfe32bcce7822dR6882) for this functionality.

Thank you,
Andrew
