### ISSUE TITLE
Set surveyjs current page to targeted page, but check previous question with attribute 'required' is answered, if not answered yet then set currentPage to the required question

### ISSUE THREAD

**Issue by michaelchandrag** [surveyjs/survey-library#1657]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?
i am currently creating a survey based on surveyjs with a feature like 1 survey (4 sections of question step). Using a custom navigation bar (to targeted pages: button 1 -> page 3, button  -> page 6) and following the example at this docs https://surveyjs.io/Examples/Library/?id=survey-customnavigation&platform=jQuery&theme=default, i am able to change the current page using this syntax `survey.currentPageNo = yourValue;`, but if there is an question with 'required' attribute that didnt answered it was bypassed (example i click navigation to page 3 but question at page 1 is not answered yet)

### What is the expected behavior?

After clicking the navigation button with function to set `survey.currentPageNo = yourValue;` . Checking and validating the previous page question with 'required' attribute if it is answered, it will be redirected to the target page, if not it will be redirected to the page with question unanswered

### How would you reproduce the current behavior (if this is a bug)?

create a 4 different survey

#### Provide the test code and the tested page URL (if applicable)
i just use the example docs for custom navigation at this link and edit it https://surveyjs.io/Examples/Library/?id=survey-customnavigation&platform=jQuery&theme=default
Tested page URL: https://plnkr.co/edit/XuVrtpvk9Qcnap0ZjArH?p=preview

Test code

```
your_code_here

```

### Specify your

* browser: Google Chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): currently using vue, but it is ok if u answered in jquery
* surveyjs version: latest version

**Comment by andrewtelnov** [comment]
@michaelchandrag You may use the following code:
```
if(!survey.isCurrentPageHasErrors) { //if there is no errors on the current page, then
  survey.currentPageNo = yourValue;
}
```

Thank you,
Andrew
