### ISSUE TITLE
ClearInvisibleValues onhidden not working when the condition question is on other page

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-library#1659]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting Bug

### What is the current behavior?
1)Filling survey and trigger the value of visibleIf with the answer : 
-"Product is affordable" -> agree
2)Go to next page and fill the answers
3)Go back to the first value and trigger the change of question "Product is affordable"
4) go to next page and is still the answered question on answers json

### What is the expected behavior?
1)Filling survey and trigger the value of visibleIf with the answer : 
-"Product is affordable" -> agree
2)Go to next page and fill the answers
3)Go back to the first value and trigger the change of question "Product is affordable"
4) go to next page and the question with the visibleIf that depends of this question Product is affordable is deleted

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/3G8NyjxsZPqke2z76fij?p=preview

### Specify your

* browser: chrome/firefox
* browser version:...
* surveyjs platform (angular or react or jquery or knockout or vue) :jquery
* surveyjs version: 1.0.81
PD: complete is cleaning the values correctly

**Comment by andrewtelnov** [comment]
@jmar1998 I have forgotten to set clearInvisibleValues to "onHidden". It is onComplete by default.
Here is [the corrected example](https://plnkr.co/edit/l6hbNUwm6GrXsgllT2KD?p=preview)

Thank you,
Andrew

**Comment by jmar1998** [comment]
@andrewtelnov thanks you i forget it sorry , one more question , its possible have 2 types of clearInvisibleValues? , i mean something like clearInvisibleValues = {'onComplete', 'onHidden'} ??

**Comment by andrewtelnov** [comment]
@jmar1998 Unfortunately, we have this property (behavior) on survey level only.

Thank you,
Andrew
