### ISSUE TITLE
Make questions inside Matrix single choice required (questions are in the rows)

### ISSUE THREAD

**Issue by SpikePiegal** [surveyjs/survey-library#1660]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

The matrix only requires to answer one row, but want it for all rows. 

### What is the expected behavior?

User must answer all rows of questions

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: 

Test codehttp://highdemanddesigns.com/arc3s/survey (question 8)

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@SpikePiegal We will need to add one more property: `column.isAllRowsRequired`. We do not have it yet.

Thank you,
Andrew

**Comment by SpikePiegal** [comment]
@andrewtelnov When you say you do not have it yet, do you mean it is something you are working on implementing? If so, do you have any idea on the timeframe of this update or is there any work around that I can use now? Thanks.

**Comment by andrewtelnov** [comment]
@SpikePiegal Could you ping me in a week? We will try to implement it for the next minor release if we do not see any unpredictable problems.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@SpikePiegal I have just realized that you are talking about Matrix (single choice). It has already here: matrix.isAllRowRequired = true. Here is [the example](https://plnkr.co/edit/43saXL4fcYmA9nIrthuP?p=preview).

Thank you,
Andrew

**Comment by SpikePiegal** [comment]
Thank you, this worked exactly how I needed it to.

**Comment by benirose** [comment]
I was about to open this same ticket, but I found this old one. Where is the `isAllRowRequired` property presented in the survey editing interface?

**Comment by andrewtelnov** [comment]
@benirose Right now you may change it from the Property Grid only. 
I have added the property into Matrix Editor via [this commit](https://github.com/surveyjs/survey-creator/commit/d33166d9c15e32fddb37b0c00bba191e68486e55). We will release a new version today and it will be there.

Thank you,
Andrew
