### ISSUE TITLE
Implementing startTimer and stopTimer for each page

### ISSUE THREAD

**Issue by SpikePiegal** [surveyjs/survey-library#1661]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the expected behavior?

Is it possible to add the start and stop timers inside the functions to keep track of how much time users spend on each page, add the functions inside the JSON file?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```


```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
You can use the https://surveyjs.io/Documentation/Library/?id=surveymodel#onCurrentPageChanged event, the https://surveyjs.io/Documentation/Library/?id=surveymodel#startTimer and https://surveyjs.io/Documentation/Library/?id=surveymodel#stopTimer methods with the https://surveyjs.io/Documentation/Library/?id=surveymodel#timeSpent property

Here is the working sample - https://plnkr.co/edit/lrJ6DtxuPjHNOUf1TLxc?p=preview
