### ISSUE TITLE
[React] Custom radiogroup widget can't select items

### ISSUE THREAD

**Issue by andreihabalau** [surveyjs/survey-library#1662]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

If you extend the radiogroup question in a custom widget, the select functionality doesn't work any more for that custom question type in the react render.

### What is the expected behavior?

You should be able to select an option, and the checked class should be assigned to the correct div.

### How would you reproduce the current behavior (if this is a bug)?

Extend the radiogroup question in a custom widget, and use isDefaultRender: true on that widget.
Then just add the custom type in a survey.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://plnkr.co/edit/kqBcl15Tv5RjssoZbmuU?p=preview

### Specify your

* browser: Google Chrome
* browser version: 73.0.3683.103
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.0.82

**Comment by tsv2013** [comment]
I'm not sure whether it is a bug. The `isDefaultRender` option is responsible for the default rendering - provides programmer with a raw markup. Further the programmer is responsible for the bindings.
We need to check it and discuss internally with @andrewtelnov  and @dmitrykurmanov

**Comment by tsv2013** [comment]
We've discussed this behaviour with the team and desided that we need to fix this inconsistence. We'll try to kame default rendered widgets to work

**Comment by tsv2013** [comment]
I've fixed the issue. Fix will be available in the nearest update, most likely tomorrow.
