### ISSUE TITLE
VisibleIf notempty not triggered when value is 0

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-library#1663]
Missing comment question
![image](https://user-images.githubusercontent.com/30930391/56671814-f2362e80-66bd-11e9-92e3-bc0b56982a98.png)
visibleIf: notempty
![image](https://user-images.githubusercontent.com/30930391/56671876-16920b00-66be-11e9-879d-e586768ed8e1.png)

**Comment by andrewtelnov** [comment]
@gologames I have added a [new unit test](https://github.com/surveyjs/survey-library/commit/1ef92d77aa6f06b3916cb69376ac18f573be0eac#diff-144ca1a9817acf1e3c4579944397a140R957) and fixed it.

Thank you,
Andrew

**Comment by gologames** [comment]
Cool!

**Comment by rer145** [comment]
I hate to be that guy that comments and tries to reopen a 4 month old issue, but this does not appear to be fixed. Here is a link to a snippet for a radiogroup question that should show a comment box if something is selected.  When choosing "Not at all", which has a value of 0, the comment box does not appear.

https://plnkr.co/edit/sSfpf1VqWfZGm0fPklln?p=preview
