### ISSUE TITLE
Preprocessing text should return the text in chosen language

### ISSUE THREAD

**Issue by ajien** [surveyjs/survey-library#1666]
### Are you requesting a feature, reporting a bug or asking a question?

Requesting a feature

### What is the current behavior?

Preprocessing text returns the value of the field instead of the text (or label) in the currently active language. For example, if I use {community}, I will get either 'Aesthetics' or 'Noise Levels' even when the chosen language is French, when I should be getting either 'Esthétique' or 'Niveaux de bruit'.

`            {
              type: "checkbox",
              name: "community",
              title: {
                default: "Community",
                fr: "Communauté"
              },
              choices: [
                {
                  value: "Aesthetics",
                  text: {
                    default: "Aesthetics",
                    fr: "Esthétique"
                  }
                },
                {
                  value: "Noise levels",
                  text: {
                    default: "Noise levels",
                    fr: "Niveaux de bruit"
                  }
                },
             ]
           }`

* browser: Chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: v1.0.60

**Comment by andrewtelnov** [comment]
@ajien It works fine with the latest version 1.0.82.
Here is [the exampple](https://plnkr.co/edit/mfoJy69uYDR8gsjMa40g?p=preview)

Thank you,
Andrew

**Comment by ajien** [comment]
I have tried updating to the latest version and it is still not working for
me. My implementation is different from the example, since I am using panel
dynamic that are created as a result of the options selected.

**Comment by andrewtelnov** [comment]
@ajien Could you reproduce the issue in a small examples?
We will be able to fix it in this case.

Thank you,
Andrew

**Comment by ajien** [comment]
[Here it is.](https://plnkr.co/edit/HzqzHg2kkNy8Ug93DyWf)

**Comment by andrewtelnov** [comment]
@ajien You {panel.community} in riskDetails question doesn't have any binding  to 'risks' question and as result, it could not find the requried displayText. That is why it shows value only.
I would suggest to make the first page with two typical questions, then create an array for risk_detail, based on two questions and add into risk_detail two values (value and displayName), 
question.displayValue property.
It should work and I believe, you will have less code.

Thank you,
Andrew

**Comment by ajien** [comment]
I don't understand, I am sorry. Do you mean that I should not use
panelDynamic in the first page? Would you be kind enough to show me an
example of the solution that you are proposing? Thank you and I really
appreciate your help on this one.

**Comment by andrewtelnov** [comment]
@ajien Unfortunately, I did not get the logic of creating the dynamic panel. Here is [my example](https://plnkr.co/edit/n1SrHu7BEF7yLoLtzNdv?p=preview). I'm afraid it doesn't work correctly, but you have to understand the idea.

Thank you,
Andrew

**Comment by ajien** [comment]
Thanks! I've made a few changes to what you did and it seems to be working
now. See it here <https://plnkr.co/edit/kWlUr2WuA2kK1bB1Oaku>.
