### ISSUE TITLE
Is there a method to get element by name (getElementByName)?

### ISSUE THREAD

**Issue by ajien** [surveyjs/survey-library#1668]
### Are you requesting a feature, reporting a bug or asking a question?
Question

Is there a method similar to getQuestionByName, but one that works for elements of a dynamic panel? 

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version:

**Comment by andrewtelnov** [comment]
@ajien Dynamic panel has the list of panels with the same question names. You may use getQuestionByName as: `paneldynamicquestion.panels[myIndex].getQuestionByName("myQuestionName")`

Thank you,
Andrew
