### ISSUE TITLE
ClearInvisibleValues not work on 2nd level question and possible more levels (VisibleIf)

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-library#1669]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

I load a survey with answers to test (The child question depends of parent question and second level depends of child-question), and when i click on complete , the 2nd level answer is still on json(i delete the parent answer), only the child answer was removed
-window.survey.data = {
    "Quality": {
        "affordable": "4" <- parent question
    },
    "price": "correct", (this question depends of another)<- child-question
    "pricelimit": { <- second level question
        "mostamount": "LOREM IPSUM",
        "leastamount": "LOREM IPSUM"
    }
};
### What is the expected behavior?
When i click on update the child-question, second-level and possible more levels should be removed

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/oYvu9fQ1LRDkUlxckdhY?p=preview

### Specify your

* browser: chrome, firefox
* browser version: ...
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: last

**Comment by andrewtelnov** [comment]
@jmar1998 I am not sure I am follow you.
question.value becomes empty if the question is invisible. We do not create any dependencies.

Thank you,
Andrew

**Comment by jmar1998** [comment]
@andrewtelnov ok let me explain you, right now i have questions, that depends of another questions, and there are levels of dependecy, like i was explain you, in my system i could have 2 levels or more of visibleIf dependency , so my question is the following, clearInvisibleValues works only if we refer directly the question(visibleIf) or we can use levels of visibleIf(so this is a possible bug)
Example about the levels:
Question1
Question 2 visibleIf(question1 Is notempty)
Question 3 visibleIf(question2 is notempty)
So if for any reason question1 is empty and question2 and question3 is on answers, the complete will not clear the question3

**Comment by andrewtelnov** [comment]
@jmar1998 I got it now. The easiest solution is to set clearInvisibleValues to “onHidden”, or for Question3 have question1 isnotempty and question2 isnotempty

We do not change elements visibility when survey is completed.

Thank you,
Andrew
