### ISSUE TITLE
How to track changed on textarea

### ISSUE THREAD

**Issue by naspredam** [surveyjs/survey-library#1670]
### Are you requesting a feature, reporting a bug or asking a question?
Asking question.

### What is the current behavior?
We are using the survey-js with reactjs. We are tracking any change of the textarea by keyup, but we are seeing the ReactSurveyModel.data is not being updated, just in case we have some inputs triggering onChangeValue.

### What is the expected behavior?
When we keyup/keydown/... the ReactSurveyModel.data.`question_id_with_textarea` should be updated, in order to be able to get the latest text.

### How would you reproduce the current behavior (if this is a bug)?
Create a survey with textarea.
Track via rxjs event via keyup
Change the content of the textarea
ReactSurveyModel.data is never changing, just if I do onblur.

* surveyjs platform: react
* surveyjs version: 1.0.38

**Comment by tsv2013** [comment]
Yes this is designed behavior of SurveyJS library. You can use the https://surveyjs.io/Documentation/Library/?id=surveymodel#onAfterRenderQuestion event to access the textarea, subscribe the textarea events and update survey model.

The sample of how to use this event can be found here - https://surveyjs.io/Examples/Library/?id=survey-afterrender&platform=Reactjs&theme=default
