### ISSUE TITLE
Is it possible to use a static css file instead of dynamic <style> element

### ISSUE THREAD

**Issue by socialsuiteDan** [surveyjs/survey-library#1671]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the current behavior?
We are hoping to implement surveyJS within a very restrictive environment which limits access to a number of standard DOM elements and browser APIs. We don't have control over the outer elements of the page like <head>, we're only able to provide a component which will be rendered within a specific page region. In our initial testing we have run into an issue with the way that StylesManager works, with style elements constructed dynamically and appended to the <head> element. Our component is not able to to append the style to document.head, and the environment we are working in does not permit inline style tags anyway, so the subsequent calls to populate it with rules are failing and the survey isn't rendered.

### What is the expected behavior?
The only supported approach for handling styles within the environment we're working in is a static css file provided alongside our component, so we are wondering if it would be feasible to provide an option to disable the dynamic theming in StylesManager so that we can include a static theme css file instead? We'd lose the ability to switch themes of course, but that's a fairly low priority for us. 
We're happy to put together a PR for that if you think it would be possible, i'm just wondering if there are any other parts of the library that would also be impacted by our limitations around adding/changing the style element on the fly? We've only just started working with surveyJS so we're not too familiar with the architecture yet.

### Specify your

* browser: any
* browser version: any
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.0.82

**Comment by tsv2013** [comment]
The `StylesManager` class is used to customize and update color scheme of SurveyJS Library on-the-fly. The `survey.css` static file from the NPM package can be used instead. Have you tried to load it?

**Comment by socialsuiteDan** [comment]
Yes, the issue we have is that StylesManager throws an exception so the survey still can't render. Is StylesManager supposed to detect the use of the static file somehow, or is there some other way to stop StylesManager from attempting to initialize the styles dynamically?

The specific exception we get is from the sheet.insertRule() in initializeStyles, since the createSheet function returns null in our case.

**Comment by tsv2013** [comment]
Can you tell me - what exact errors have you faced and I'll try to fix our code

**Comment by socialsuiteDan** [comment]
The exception message is 'TypeError: Cannot read property 'insertRule' of undefined', if you add in a check that the sheet exists before calling insertRule that would probably be enough.

**Comment by tsv2013** [comment]
I've added the `Survey.StylesManager.Enabled` static flag that you can set to `false` in order to disable it:
```JS
Survey.StylesManager.Enabled = false;
```

This feature will be available in the nearest update, most likely tomorrow

**Comment by socialsuiteDan** [comment]
Thanks so much for the quick response, that's great.
