### ISSUE TITLE
Validate that single checkbox (boolean) is checked

### ISSUE THREAD

**Issue by kaphert** [surveyjs/survey-library#1674]
### Are you requesting a feature, reporting a bug or asking a question?
Bug?

### What is the current behavior?
I have a checkbox at the end of the form that says: "I agree that..." etc. I want to validate this in the frontend that it is checked. But I'm unable to figure out how to do this. 

### What is the expected behavior?
Setting `correctAnswer` to 'true' and unchecking the checkbox should show an error when you try to submit the form.  

### How would you reproduce the current behavior (if this is a bug)?
This is a JSON tested on the latest version in the online builder (v1.0.83)
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "boolean",
     "name": "checkbox_question",
     "title": "Please Confirm",
     "defaultValue": "false",
     "correctAnswer": true,
     "isRequired": true,
     "titleLocation": "left",
     "label": "Yes I agree that....",
     "showTitle": true
    }
   ]
  }
 ]
}
```

**Comment by tsv2013** [comment]
You can use the expression validator:
```JSON
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "boolean",
     "name": "checkbox_question",
     "title": "Please Confirm",
     "defaultValue": "false",
     "validators": [
      {
       "type": "expression",
       "text": "You need to check this",
       "expression": "{checkbox_question} = true"
      }
     ],
     "titleLocation": "left",
     "label": "Yes I agree that....",
     "showTitle": true
    }
   ]
  }
 ]
}
```

**Comment by kaphert** [comment]
@tsv2013 ah thanks that does the trick indeed. Thanks!
