### ISSUE TITLE
group questions at data level too

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1676]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

if I use panel to group questions, those questions in the survey result are not grouped but splatted

### What is the expected behavior?

I'd like to see panel question answers grouped under the panel name like

```
{
  question_name_1: 'a', 
  panel_name: { 
    panel_question_name_1: 'b', 
    panel_question_name_2: 'c',
  }
} 
```

**Comment by tsv2013** [comment]
I've marked it as an enchancement. I can't give you any estimations.
As a workaround you can group results according your custom requirements in the https://surveyjs.io/Documentation/Library/?id=surveymodel#onComplete event hendler using survey structure.

**Comment by masciugo** [comment]
ok thanks

I would just add a boolean property to panel question. Something like:

nestData: true/false
