### ISSUE TITLE
'renderAs' not a valid property on type 'dropdown' in survey-angular@1.0.84

### ISSUE THREAD

**Issue by csgchristian** [surveyjs/survey-library#1678]
`renderAs` appears to be unimplemented in the angular version of surveyjs, is this intentional?

**Comment by csgchristian** [comment]
Thanks for this, this was not clear in the angular example for implementing the `renderAs` property.

There are no longer any errors, but the dropdown appears blank and flashes when I click it now, do I need to import more than

```
 "../node_modules/jquery/dist/jquery.js",
 "../node_modules/select2/dist/js/select2.js"
```?

**Comment by tsv2013** [comment]
Probably you need to add CSS styles also:
```JSON
      "styles": [
        "../node_modules/select2/dist/css/select2.css",
```

**Comment by csgchristian** [comment]
That was correct, now there appears to be two blank entries at the bottom of the select when the dropdown has no selected value initially, is there an easy way to display 'Choose...' or some other value by default for any dropdown?

**Comment by tsv2013** [comment]
You need to use the `select2Config` as shown in this live sample - https://plnkr.co/edit/FgNuRbkHZiV91aU0o7dc?p=preview
