### ISSUE TITLE
bootstrap 4 and material design

### ISSUE THREAD

**Issue by comur** [surveyjs/survey-library#1679]
Hello,
I'm using last version of all libraries and developing with react.

I need to use last version of bootstrap (4) and material design but in examples I see that you use bootstrap 3 and materal design 0.5.10 : https://surveyjs.io/Examples/Library/?id=bootstrap-material-theme&platform=Reactjs&theme=default

How can I achieve this ? And how can I customize (colors and other visual stuff) as I can do with bootstrap in the example: https://surveyjs.io/Examples/Library/?id=custom-theme&platform=Reactjs&theme=default:

Thanks !

**Comment by comur** [comment]
someone ? I realy need this to be able to use this library efficiently.
Thanks !

**Comment by dmitrykurmanov** [comment]
@comur Hello! Thank you for the question. We support bootstrap 4. Concerning material design support - what exact material design library do you mean?

**Comment by comur** [comment]
Hello @dmitrykurmanov 
If I understand well, it's compatible with bootstrap-material-design package https://fezvrasta.github.io/bootstrap-material-design/
I tried this one but impossible to have the new `$('body').bootstrapMaterialDesign()` function working. I don't know if it can work well without calling this function. Actually I use it like this without calling the function but I have lot of errors especially with checkbox and radios (they are not visible at all and I needed to add a css patch to get them visible). I would prefer having beautiful bootstra-material-design checkboxes / radios but actually I have ugly classic ones.
In your examples you always use Bootstrap 3 with material-design 0.5 so I need to find a way to get it working with v4.

Other problem that I have is with the survey-creator but I guess you prefer me to put it on dedicated repository ?
I guess it's the same problem (with 4.x bootstrap-material-design).

Do you have an example (react if possible) working with bootstrap-material-design ? And can you tell me if I can use all of their scss variables in style manager or how can I have the list of available variables ?

Thanks again for your help !

**Comment by tsv2013** [comment]
@comur  Unfortunately or fortunately there are a lot of CSS frameworks and meterial design libraries: https://getbootstrap.com/ , https://foundation.zurb.com/ , https://fezvrasta.github.io/bootstrap-material-design/ , https://mdbootstrap.com/ , https://www.creative-tim.com/product/material-kit and so on.
It's hard to support all of them.

Over the year ago we introduced bootstrap v3 material design support from https://github.com/FezVrasta/bootstrap-material-design . It was most popular repo at that time. We've spent rather large efforts to implement it. But today I see that last commit in the bootstrap-material-design was over 10 months ago - that means this project is almost dead.

Thus we today need to support another material design library for BS4. I'm not sure we need to support it (yet another material theme) in favour of a little amount of user requests. I think we need more user requests to implement this feature. And I beleive all UI customizations can be done via CSS styling of SurveyJS Library.
