### ISSUE TITLE
Surveyjs not rendered in modal

### ISSUE THREAD

**Issue by marianpavel** [surveyjs/survey-library#1680]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
SurveyJs not working on modal but outside it works

### What is the expected behavior?
It should show the survey when the modal is opened

### How would you reproduce the current behavior (if this is a bug)?
I would create a simple bootstrap modal & render with the angular version of the library the div inside the modal.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
 const surveyJSON = {
                pages: [
                    {
                        name: 'page1',
                        elements: [
                            {
                                type: 'text',
                                name: 'question1',
                                title: 'Test question?',
                            },
                        ],
                    },
                ],
            };

            Survey.StylesManager.applyTheme('bootstrap');

            const surveyModel = new Survey.Model(surveyJSON);

            surveyModel.onValidateQuestion.add((sender: any, options: any) => {

            });

            surveyModel.onComplete.add((result: any) => {
                this.sendDataToServer(result);
                result.clear(true);
            });

            surveyModel.completeText = 'End questionnnaire';

            Survey.SurveyNG.render('surveyElement', {
                model: surveyModel, isExpanded: true,
            });
```

### Specify your

* chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version:    "survey-angular": "^1.0.83",

The div is there but, if I move the div and the typescript code to another page that doesn't contain the modal, everything works as expected.

**Comment by andrewtelnov** [comment]
@marianpavel Please review [this working example](https://surveyjs.io/Examples/Library/?id=survey-window&platform=Angular2)?

Thank you,
Andrew

**Comment by marianpavel** [comment]
It can be closed. The solution was to add a timeout of 0 so the render gets added to the tail and done it after all the asynchronous things

**Comment by jjsafety** [comment]
Any chance you can post your timeout example? I think I'm running into something similar. I've got some kind of race condition where I'm seeing the survey data loaded from the server, but when I do the render ala: Survey.SurveyNG.render("surveyContainer", {model:this.survey}) I'm not seeing anything rendered in Chrome with Angular. Thanks!!!
