### ISSUE TITLE
How to slide to next page after some time

### ISSUE THREAD

**Issue by saksham7** [surveyjs/survey-library#1683]
### Are you requesting a feature, reporting a bug or asking a question?
This is a question.

### What is the expected behaviour?
My first 3 pages contain HTML which I wanted to slide after some seconds like in the below sample site using SurveyJS
https://www.vivewellness.com/consultation/
In this, after you enter the name, 3-4 pages slide without pressing continue button and I want to reproduce this in my site.

### Specify your

* browser: Chrome
* browser version: Version 74.0.3729.131
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: 1.0.84

**Comment by tsv2013** [comment]
You can check this thread - https://surveyjs.answerdesk.io/ticket/details/t894/animations-while-changing-page and this sample - https://surveyjs.io/Examples/Library/?id=survey-animation&platform=jQuery&theme=default

**Comment by saksham7** [comment]
This shows how to add animation while changing page, I have 3 pages which contain html, I want them to automatically move to next pages after 2 seconds without pressing continue button.

**Comment by andrewtelnov** [comment]
@saksham7 You have to write the following code:
```
//Set the max time to finish the page to two seconds
survey.maxTimeToFinishPage = 2;
//start the timer
survey.startTimer();
```
Please find out more in [this example](https://surveyjs.io/Examples/Library/?id=survey-quiz).

Thank you,
Andrew

**Comment by saksham7** [comment]
thanks for this, also "colCount":4 not working for radio button in my case...
![Consultation - Vive Wellness - Google Chrome 5_20_2019 4_07_48 PM](https://user-images.githubusercontent.com/24752275/58015861-ecdfce80-7b19-11e9-95f9-6d932ff3406a.png)
