### ISSUE TITLE
onValueChanged not always invoked when changing a matrixdynamic

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1687]
### Are you requesting a feature, reporting a bug or asking a question?

question/bug

### What is the current behavior?

when you add/remove empty rows in matrixdynamic onValueChanged is not invoked. But the empty object are tracked behind the scenes because if you start populating just a row then if start playing again with empty rows onValueChanged get called only on remove action but not on add action

### What is the expected behavior?

I expect a coherent behaviour having onValueChanged called on any action regarding empty rows or not

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/H5fcrVCjDefanFURq9oY?p=preview

**Comment by tsv2013** [comment]
The "add row" actually doesn't change the value, due to the new now is empty. I think you can use the https://surveyjs.io/Documentation/Library/?id=surveymodel#onMatrixRowAdded event.

**Comment by masciugo** [comment]
> The "add row" actually doesn't change the value

it does change the value pushing empty object in the survey data. Submit to see

and also removing an empty row changes the data. But, I noticed that removing empty row trigger onValueChanged only when there is at least an other nonempty row. 

Maybe it is expected or not important. This is just a warning. Thank you
