### ISSUE TITLE
same valueName

### ISSUE THREAD

**Issue by kouhunzhe** [surveyjs/survey-library#1688]
### Are you requesting a feature, reporting a bug or asking a question?

asking a question

### What is the current behavior?
same valueName

### What is the expected behavior?
I want the valueName not to be repeated, and the Shared value I can set with the trigger

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
Each survey question has a name and a valueName (by default valueName = name). The `valueName` is a key for survey question values dictionary. If you want to set values of different question via trigger, you can use personal trigger for each question.
