### ISSUE TITLE
Inconsistent JSON formatting for value text

### ISSUE THREAD

**Issue by garethbc** [surveyjs/survey-library#1692]
### Are you requesting a feature, reporting a bug or asking a question?
Can this be made consistent as it makes it much easier to work with the JSON in SQL Server?

### What is the current behavior?

If the value and text properties of items are identical they are saved in JSON as a single string value. 

{
"Team Member",
"Director"
}`
If they are different they are saved as:

` {
         "value": "TeamMember",
         "text": "TeamMember"
        },
{
         "value": "valDirector",
         "text": "Director"
        },

### What is the expected behavior?
In both events the rows should be saved with value and text properties.

In addition, editing the value should not auto populate the text in the creator, or there should be an option to disable this.

### How would you reproduce the current behavior (if this is a bug)?

Add a row to a matrix, view the JSON

**Comment by tsv2013** [comment]
Hello

You can use the follwoing code:
```JS
Survey.ItemValue.prototype.getData = function() {
  return this.toJSON(); // Here you can change how ItemValue will be serialized
};
```

Here is the live sample with SurveyJS Creator - https://plnkr.co/edit/hpzb9QKDYrWkLOe9FfqS?p=preview

If you have additional questions regarding SurveyJS Creator, please ask them in the corresponding repo - https://github.com/surveyjs/survey-creator/issues

**Comment by garethbc** [comment]
Can you expand on this?
Will SurveyJs deserialize this correctly?

**Comment by tsv2013** [comment]
If you return a single string, it will be deserialized as the same value and text.
