### ISSUE TITLE
Data not sent in result when checkbox with prettycheckbox 

### ISSUE THREAD

**Issue by comur** [surveyjs/survey-library#1696]
Hi all,

### Are you requesting a feature, reporting a bug or asking a question?

Bug / compatibility problem

### What is the current behavior?

When using prettycheckbox, checkbox data is not sent in result

### What is the expected behavior?

We need to have selected checkboxes values

### How would you reproduce the current behavior (if this is a bug)?

You can reproduce it on : https://surveyjs.io/Examples/Library/?id=custom-widget-pretty-checkbox&platform=Reactjs

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

https://surveyjs.io/Examples/Library/?id=custom-widget-pretty-checkbox&platform=Reactjs

* browser: Chrome
* surveyjs platform : React
* surveyjs version: 1.0.87

This bug is introduced in 1.0.78 (tested with 1.0.77 it works as expected). Here is the diff:

https://github.com/surveyjs/survey-library/compare/v1.0.77...v1.0.78

I also opened an issue on surveyjs/widgets#122 so you can close one of them if it concerns the other repo :)

Anyway, thx for this lib !

**Comment by andrewtelnov** [comment]
[Duplicated](https://github.com/surveyjs/widgets/issues/122)
Fixed-
