### ISSUE TITLE
Min / max on numerical and date inputs

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#1697]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
Currently we can select the html input type, but not set additional attributes.
Attributes that only apply to the `text` input type however are always configurable, even when not relevant.
For `text` we have `maxlength`, `minlength` and `pattern` amongst others.
For `date` attributes that apply (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#Additional_attributes)
 are: `max`, `min` and `step`.

### What is the expected behavior?
There should be some way to specify these attributes (without coding for every possible combination).

### Proposed solution 1
Add a key value property that allows us to specify custom input attributes for this question type.

### Proposed solution 2
Create a custom question type for each html input type. This is the best solution, but also requires a lot more work.

**Comment by SamMousa** [comment]
> Hello Sam,
It is easy to add these properties into text question. The main issue that they are depending from inputType property. It would be logically to hide unneeded properties based on inputType.
Unfortunately, we do not have this functionality in our SurveyCreator yet and to implement it we have to do some refactoring.
However, we believe it worth to implement, since the code will be cleaner after the changes we want to make and implementing logical visibility into property will be easy after refactoring.
So, we will keep this ticket open and we will come back to it as soon as we have something.
> Thank you,
> Andrew
> SurveyJS Team
>

**Comment by SamMousa** [comment]
The solution you propose is indeed best, but it still doesn't cover all cases.
What about starting off with adding a simple key value editor for input attributes, this will also allow for easier customization via custom attributes.

For example I could have something like this:
```html
<input type="text" x-expandable-tooltip="cool">
```
And then have some JS code that does something with it.

By adding a key value property to single input question type you can easily and quickly provide these basic features and workarounds for all the different input types. 
Then you can take the time to do a more UX friendly editor for the specific properties.
Advantage also is that the friendly UX would be creator only, since the creator can then fill the actual attributes and the library won't need changing for it.

**Comment by tsv2013** [comment]
I've partially implemeted it: min/max/step properties
