### ISSUE TITLE
Expession doesn't work if a question name contains apostrophes. It works in previous versions.

### ISSUE THREAD

**Issue by edwardstamps** [surveyjs/survey-library#1700]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
All pages on a multipage survey with pages conditional ("visibileIf") based upon a checkbox option selected on an earlier pages question are visible.

### What is the expected behavior?
On a multipage survey with pages conditional ("visibileIf") upon a checkbox option selected on a page 1 question those pages should only be visible if question 1 contains the relevant option.

### How would you reproduce the current behavior (if this is a bug)?
Build a multipage survey with a checkbox question as page 1. Then on following pages add a visible if question 1 contains x option.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: It appears to have been introduced in 1.0.86

**Comment by andrewtelnov** [comment]
@edwardstamps Could you please fork and modify [the example](https://next.plnkr.co/edit/GR6Fj5gArmz18mG6ZBEx?p=preview&utm_source=legacy&utm_medium=worker&utm_campaign=next&preview) so we can see the issue.

Thank you,
Andrew

**Comment by edwardstamps** [comment]
@andrewtelnov I was unable to replicate in the browser but my team is using survey-react and rendering on a mobile device so that may help isolate the issue

**Comment by andrewtelnov** [comment]
@edwardstamps Then we need your JSON (if you keep it as less as possible it would be great) and enviroment: OS (name, version) + Browser (name, version),  where it doesn't work.
PS: I assume that you are using the latest version of the library.

Thank you,
Andrew

**Comment by edwardstamps** [comment]
@andrewtelnov I've finally isolated it to when a question name contains a {'} character ex: "Question's" that the visibleif conditional does not work correctly: https://next.plnkr.co/edit/xfJeA0P6cXiUXTjX. In general I would also recommend renaming "name" to "key" as its very confusing to users who don't understand the difference between "name" and "title". This has also caused quite a bit of issues for our users as when the data is exported you drop characters that would fail which makes hashing difficult. My work around for the time being has been to hide the "name" field and prevent users from editing it.

**Comment by andrewtelnov** [comment]
@edwardstamps I am going to do the following.
1) Exlude apostrophes on setting the name and brackets [] and {}. Right now we are removing dots only
2) We may change the name title in the Question Editor Modal Window, from "Name" to something like, "The element key", for example.
If you are running SurveyCreator in your web app, then you may change it as you want.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@edwardstamps In the commit above I have added the support for apostrophes in value names. In fact we had it before, but we lost it after we remove our own expression code and start to use [pegjs grammar library](https://pegjs.org).
I have added the unit test and fix the grammatic.

Thank you,
Andrew

**Comment by edwardstamps** [comment]
Thanks for looking into this @andrewtelnov !
