### ISSUE TITLE
I needded get value from question if is are marked "other"

### ISSUE THREAD

**Issue by victorfernandesraton** [surveyjs/survey-library#1702]
Hey guyss, i neede for u's.

I maked this surley.js test example for demonstrate this tool .

I needed get value of "Other" option if respondent markl this in Banco question

this is my code. i inserted this in a demo's place.

Hey guyss, i neede for u's.

I maked this surley.js test example for demonstrate this tool .

I needed get value of "Other" option if respondent markl this in Banco question

this is my code. i inserted this in a demo's place  
``
var surveys =
{
  "Bancos": {
  "completedHtmlOnCondition": [
    {
      "expression": "{question1} = [\"other\"] and {question1} = {question1.other}"
    }
  ],
    "pages": [
      {
        "name": "Bancos",
        "elements": [
          {
            "type": "checkbox",
            "name": "question1",
            "indent": 2,
            "title": "Banco",
            "isRequired": true,
            "hasOther": true,
            "choices": [
              "Bradesco",
              "BB",
              "Itaú"
            ]
          }
        ],
        "title": "Todos os bancos",
        "description": "Mostra todos os bancos disponíveis"
      },
      {
        "name": "Banco favorito",
        "elements": [
          {
            "type": "radiogroup",
            "name": "question2",
            "title": "Selecione seu banco Favorito",
            "choices": [
              "Bradesco",
              "BB",
              "Itaú",
              {
                "value": "{question1.other}",
                "text": "{question1}",
                "visibleIf": "{question1}  and {question1} anyof [\"other\"]"
              }
            ],
            "choicesVisibleIf": "{question1} contains {item}"
          }
        ],
        "title": "Banco favorito",
        "description": "Escolha seu banco favorito"
      },
      {
        "name": "BnacoFavorito",
        "elements": [
          {
            "type": "rating",
            "name": "question3",
            "title": "Avalie o saaeu banco favorito <script></script>",
            "correctAnswer": 4,
            "isRequired": true,
            "rateValues": [
              1,
              3,
              4,
              5
            ]
          }
        ],
        "title": "Banco favorito"
      }
    ],
    "sendResultOnPageNext": true,
    "showPageNumbers": true
  }
}
// pegando um eleemento qualquer
console.log(surveys["Bancos"].pages[0].);

var results = {
  "Bancos": [
    '{"Bancos":{"question1"}}',
  ],
};

module.exports = {
  surveys: surveys,
  results: results
};
``

**Comment by andrewtelnov** [comment]
@victorfernandesraton Sorry, we missed this one.
set property [survey.storeOthersAsComment](https://surveyjs.io/Documentation/Library/?id=surveymodel#storeOthersAsComment) to false or question.storeOthersAsComment and then you may have expression as:
`"expression": "{question1} = 'yourOtherText'"`
If you need to store others as comments, then please reply here. We will add this functionality.

Thank you,
Andrew
