### ISSUE TITLE
RegExp Syntax Example

### ISSUE THREAD

**Issue by RA-Work-A** [surveyjs/survey-library#1707]
### Are you requesting a feature, reporting a bug or asking a question?

**question**

### What is the current behavior?

unsure

### What is the expected behavior?

I'm looking for information on the syntax for regexp for validators. 

If found this -->

```
public validate(value: any, name: string = null): ValidatorResult {
    if (!this.regex || !value) return null;
    var re = new RegExp(this.regex);
    if (Array.isArray(value)) {
      for (var i = 0; i < value.length; i++) {
        var res = this.hasError(re, value[i], name);
        if (res) return res;
      }
    }
    return this.hasError(re, value, name);
  }
```

### How would you reproduce the current behavior (if this is a bug)?

n/a

#### Provide the test code and the tested page URL (if applicable)
n/a
Tested page URL:

Test code

```
your_code_here

I'm using this: 

"type": "multipletext",
                        "items": [
                            {
                                "title": "First Name",
                                "name": "Your_First_Name",
                                "inputType": "text",
                                "placeHolder": "What does your mom call you?",
                                "isRequired": true,
                                "validators": [{
                                    "type": "text",
                                    "text": "Invalid Input Entered",
                                    "maxLength": 100,
                                    "validate": "/\w/g",
                                    "allowDigits": false
                                }]
                            },

Is this the correct way to do this?

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: 1.0.85

**Comment by tsv2013** [comment]
RegexValidator works the following way:
```JS
var re = new RegExp(this.regex);
if (re.test(value)) return null /* no error */;
```

You can use any valid JavaScript regular expressions. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions for more details

**Comment by RA-Work-A** [comment]
Hmm?!
Let me clarify, do I need to call a .js function to get this to work? Or should SurveyJs interpret my regex via the :

`"validators": [{
                                    "type": "text",
                                    "text": "Invalid Input Entered",
                                    "maxLength": 100,
                                    "validate": "/\w/g",
                                    "allowDigits": false
                                }]`

**Comment by andrewtelnov** [comment]
@RA-Work-A You are using incorrect validator syntaxes trying to combine several validators in one. You can have two or more validators. For example:

```
"validators": [
      {
       "type": "text",
       "text": "Invalid Input Entered. The text should be less then 100 symbols",
       "minLength": 0,
       "maxLength": 100,
       "allowDigits": true
      },
      {
       "type": "regex",
       "text": "Invalid Input Entered. We do not except digits here.",
       "regex": "/\\w/g"
      }
     ]
```

Thank you,
Andrew
