### ISSUE TITLE
multipletext

### ISSUE THREAD

**Issue by RA-Work-A** [surveyjs/survey-library#1708]
### Are you requesting a feature, reporting a bug or asking a question?

**feature**

### What is the current behavior?
multipletext only allows for the entry of "text". however I would like the ability to use other input types as well. My business case is as follows:

I have one question. This question houses FName and LName, and Suffix. I would like Suffix to be a select list (dropdown list). 

### What is the expected behavior?
I would expect to be able to add "choices" to an item, in order to allow me to use (in this case) a select list containing the options of (.jr , .sr. etc.).

### How would you reproduce the current behavior (if this is a bug)?

n/a

#### Provide the test code and the tested page URL (if applicable)
plunkr -- >https://plnkr.co/edit/hOGTcFR8mxS3DpJCbXZT?p=preview

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: 1.0.85

**Comment by tsv2013** [comment]
I've added this suggestion into our plans, but I can't promise you any estimations.

**Comment by andrewtelnov** [comment]
@RA-Work-A Why could not you use Panel? Here is [the example](https://next.plnkr.co/edit/kkfowpz6QQVs23Y3).

Thank you,
Andrew

**Comment by RA-Work-A** [comment]
I ended up using the DynamicMatrix, though that has other issues.
