### ISSUE TITLE
Show next question when all rows of matrix answered with onvaluechanged

### ISSUE THREAD

**Issue by kim66003** [surveyjs/survey-library#1709]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the current behavior?
I have a page in my survey where I have a matrix question with two rows. I want the next question (radiogroup) to show up when both rows of the matrix are filled in. I am now using:
visibleIf: "{matrix1} notempty". However when I use this code, the next question is already shown when only one row of the matrix is answered.

This is my code:

{
          type: "matrix",
          name: "matrix1",
          title: "Ik steun culturele diversiteit in onze organisatie...",
          // isRequired: true,
          columns: [{
            value: 1,
            text: "Helemaal oneens"
          }, {
            value: 2,
            text: "Oneens"
          }, {
            value: 3,
            text: "Neutraal"
          }, {
            value: 4,
            text: "Eens"
          }, {
            value: 5,
            text: "Helemaal eens"
          }],
          rows: [{
            value: answers[0][0].number,
            text: answers[0][0].text,
            score: answers[0][0].value
          }, {
            value: answers[0][1].number,
            text: answers[0][1].text,
            score: answers[0][1].value
          }]
        }, {
          type: "radiogroup",
          name: "radio1",
          title: "Ik steun culturele diversiteit in onze organisatie...",
          // isRequired: true,
          "visibleIf": "{matrix1} notempty",
          choices: [{
            value: answers[0][0].number,
            text: answers[0][0].text,
            score: answers[0][0].value,
          }, {
            value: answers[0][1].number,
            text: answers[0][1].text,
            score: answers[0][1].value,
          }]
        }

I read that you can use OnValueChanged to do this but how do you change the visibility of a question within OnValueChanged code? Here's my code:

survey.onValueChanged.add(function(survey, options) {
  if (options.name === "matrix1") {
    var values = Object.values(options.value)
    if (values.length > 1) {
      // here I want to show the next question (radio1)
     // but only when both rows of the matrix 1 question are filled in
    }
  }
});

### Specify your

* browser: Chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.75

**Comment by andrewtelnov** [comment]
@kim66003 I would suggest to use the [custom function functionality](https://surveyjs.io/Documentation/Library/#visibility-functions).
You may registered a function where you will pass the matrix value, it will return true if all two rows are filled. 

Thank you,
Andrew
