### ISSUE TITLE
Dynamic panel elements validation

### ISSUE THREAD

**Issue by marianpavel** [surveyjs/survey-library#1710]
### Are you requesting a feature, reporting a bug or asking a question?
question

### What is the current behavior?
I cannot validate the current templateElement value with other fields.

### What is the expected behavior?
I should be able to validate the template elements with value from other fields.

#### Provide the test code and the tested page URL (if applicable)

Hi, I have a dynamic panel a templateelements that is a text. I am able to add or delete those elements as much as I want but the problem is on validation that I cannot get the current value of the element I want to validate. Is there a way how I can achieve that? I also tried with listeners inside typescript but I think dynamic panel don't trigger the listener.

**Comment by andrewtelnov** [comment]
@marianpavel You may validate questions inside the dynamic panel.
Could you provide an example of what you are trying to achieve?

Thank you,
Andrew

**Comment by marianpavel** [comment]
thank you for answering so fast.

Here is a json example of my problem.

`{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "registrationDate",
     "title": "Registration date:",
     "requiredIf": "{completionCause} notempty",
     "inputType": "date"
    },
    {
     "type": "text",
     "name": "completionDate",
     "title": "Completion date:",
     "requiredIf": "{completionCause} notempty",
     "inputType": "date"
    },
    {
     "type": "paneldynamic",
     "name": "conGroup",
     "title": "Something:",
     "isRequired": true,
     "requiredErrorText": "At last one date must be completed.",
     "templateElements": [
      {
       "type": "text",
       "name": "conGroup_sub",
       "title": "Date:",
       "validators": [
        {
         "type": "expression",
         "text": "Date must be after registration date.",
         "expression": "{conGroup_sub} >= {registrationDate}"
        },
        {
         "type": "expression",
         "text": "Date must be before completion date.",
         "expression": "{conGroup_sub} <= {completionDate}"
        }
       ],
       "inputType": "date"
      }
     ]
    }
   ]
  }
 ]
}`

**Comment by andrewtelnov** [comment]
@marianpavel You should use "panel." prefix. Here is the correct validators:
```
       "validators": [
        {
         "type": "expression",
         "text": "Date must be after registration date.",
         "expression": "{panel.conGroup_sub} >= {registrationDate}"
        },
        {
         "type": "expression",
         "text": "Date must be before completion date.",
         "expression": "{panel.conGroup_sub} <= {completionDate}"
        }
       ]
```

Thank you,
Andrew

**Comment by marianpavel** [comment]
Doesn't work, I tried your example and also tried to replace with the dynamic panel name.

`        {
         "type": "expression",
         "text": "Date must be after registration date.",
         "expression": "{conGroup.conGroup_sub} >= {registrationDate}"
        },
        {
         "type": "expression",
         "text": "Date must be before completion date.",
         "expression": "{conGroup.conGroup_sub} <= {completionDate}"
        }`

When you say "panel" your refer to dynamic panel name or to word "panel"?

**Comment by andrewtelnov** [comment]
@marianpavel It doesn't work indeed. I check it out and comeback.
Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@marianpavel I have fixed the issue with dynamic panel validators by adding a new unit test.
I have added getDate function that converts string into datetime. Otherwise you are comparing two strings and it is not what you are expecting.
Here is the JSON that works on developer build.
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "registrationDate",
     "title": "Registration date:",
     "requiredIf": "{completionCause} notempty",
     "inputType": "date"
    },
    {
     "type": "text",
     "name": "completionDate",
     "title": "Completion date:",
     "requiredIf": "{completionCause} notempty",
     "inputType": "date"
    },
    {
     "type": "paneldynamic",
     "name": "conGroup",
     "title": "Something:",
     "isRequired": true,
     "requiredErrorText": "At last one date must be completed.",
     "templateElements": [
      {
       "type": "text",
       "name": "conGroup_sub",
       "title": "Date:",
       "validators": [
        {
         "type": "expression",
         "text": "Date must be after registration date.",
         "expression": "getDate({panel.conGroup_sub}) >= getDate({registrationDate})"
        },
        {
         "type": "expression",
         "text": "Date must be before completion date.",
         "expression": "getDate({panel.conGroup_sub}) <= getDate({completionDate})"
        }
       ],
       "inputType": "date"
      }
     ]
    }
   ]
  }
 ]
}
```
We are releasing a new minor build every week, typically on Tuesday.
You may build the library from sources as described in the Readme file.

Thank you,
Andrew
