### ISSUE TITLE
Is it possible to switch columns and rows in a `matrix` question?

### ISSUE THREAD

**Issue by csgchristian** [surveyjs/survey-library#1711]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

I'm aware that `matrixdynamic` has the property `columnLayout`, but the same property does not seem to exist on the `matrix` type of question. I have a question where I would like each column to only support one answer, while currently the `matrix` question causes each row to only support one answer. Is this possible?

**Comment by andrewtelnov** [comment]
@csgchristian You may just change the rows and columns. They are the same type. This code should work:
```
var rows = matrix.rows;
matrix.rows = matrix.columns;
matrix.columns = rows;
```

Thank you,
Andrew
SurveyJS Team

**Comment by csgchristian** [comment]
Are you sure?

I tried that https://plnkr.co/edit/i0MxhgYozKP0kw69ZOM7?p=preview

Not only did the rows and columns remain unchanged, but I was still able to select multiple values in a single column.

**Comment by csgchristian** [comment]
Woops, there was a typo in my plunker code, you are correct that I can flip the rows and columns.

However, the UI still allows me to select more than one value per column! This is not the desired behavior. I also want to flip this.

**Comment by andrewtelnov** [comment]
@csgchristian Unfortunately, we do not have this functionality since I beleive you are the first who is asking for this.
What is the reason of doing this?

Thank you,
Andrew

**Comment by csgchristian** [comment]
We have a paper form, which we would like to convert into an electronic form.

The user expects to see this form online the same way they have seen it before on paper, with vertical column choices.

Functionally it makes no difference, we are just trying to make the transition as smooth as possible.

**Comment by andrewtelnov** [comment]
@csgchristian I have adeded this into our TODO list. We will implement it if see more requests for this functionality.
However, to be honest, I do not think it is a standard behavior for screen UI. People used to have radio groups in horizontal line and not in vertical line. 
This UI would make sense if there are many columns and just few rows to keep everything on one screen.

Thank you,
Andrew

**Comment by csgchristian** [comment]
To clarify, this form does not use radio buttons, it uses the `cells` property of the `matrix` question type. But yes, you are right, the standard is to group selections in a horizontal line.

**Comment by JaneSjs** [comment]
To ensure a single option per a column use a Multi-Select Matrix. Enable a Radiogroup column, check its `` option and transpose a matrix. Consider the following survey definition:
```
{
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "matrixdropdown",
          "name": "question1",
          "columns": [
            {
              "name": "Column 1",
              "cellType": "radiogroup",
              "showInMultipleColumns": true
            }
          ],
          "transposeData": true,
          "choices": [
            1,
            2,
            3,
            4,
            5
          ],
          "rows": [
            "Row 1",
            "Row 2",
            "Row 3",
            "Row 4"
          ]
        }
      ]
    }
  ]
}
```
Now, as rows appear as columns, respondents will be able to select a single option per a column:
![image](https://github.com/user-attachments/assets/d25c3307-000c-441a-b7cb-d8c3b221c4da)
