### ISSUE TITLE
[Question] Is it possible to has checkbox type's hasOther option in 'matrix single choice' type?

### ISSUE THREAD

**Issue by doongle** [surveyjs/survey-library#1712]
### Question
How do I add checkbox type's Other(describe)/hasOther:true in Matrix Single Choice type?

### Are you requesting a feature?
Yes, in Matrix Single Choice type, I'd like to have checkbox's hasOther option.

**Comment by andrewtelnov** [comment]
@doongle Unfortunately, we do not have this functionality yet.
You may drop a panel and then several radiogroup questions.

Thank you,
Andrew
