### ISSUE TITLE
question.name property is stripped of periods in survey data

### ISSUE THREAD

**Issue by lady3bean** [surveyjs/survey-library#1715]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

The question.name property is being stripped of periods in the survey.data (but not the script model).

I am aware that, on purpose, the `valueName` property of a question is stripped of any periods for use with visibleIfs, per https://github.com/surveyjs/survey-library/issues/1220. However, the question.name property is also being stripped of periods in the survey.data (as well as in options.questionName), and that's problem because then you can't associate question names from the survey data with those of the script model, where the question.name property is not stripped of periods.

### What is the expected behavior?
Question names would persist as written, including periods.

Alternatively, if periods (and/or other characters) truly cannot be in question names, there should be a front end validation that prevents users from including them in the first place.

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/t5378JE0di2DPHUapi0h?p=preview

I added a console.log of the results, and a period to the first question name. You can see that it's being stripped of the period in the survey.data.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@lady3bean Yes, we do not allow to have period in our question and column names.
Lets keep this issue open for a while with a bug status, so we do not forgot about it. We may remove this limitation. However, I could not promise anything. If a trick that I try to apply on this/next week doesn't work, then it continue to work this way.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@lady3bean Here is how it works now.
If there is a symbol, like period, in the question name, then we keep name as it is, since many users use it as a question title in rendering, and set question.valueName property without period.
If 'valueName' property is set then it is used intead of 'name' property to work with survey.data and expression.

Thank you,
Andrew

**Comment by lady3bean** [comment]
> If 'valueName' property is set then it is used instead of 'name' property to work with survey.data and expression.

But then the valueName property will always be set if there's a symbol in the question name, which means it will always overwrite question.name. You're effectively setting question.name to be question.valueName, which is what I thought was the bug.

Even though this might have been the intention, this feels like a bug because it's unexpected behavior and it breaks reasonable assumptions about what the question properties are. If question.name is always overwritten by question.valueName when valueName is set, we'll never be able to recover the original name in the survey.data. I am having trouble working with the survey.data precisely because the question names are being changed. The property called question.name is no longer the question name. I'd expect that the only property that would be changed and stripped of symbols is the valueName property, and that nothing else would change.

Can you please consider changing this so question.name will persist unchanged? If the visibleIf issue I linked to is why this was done in the first place, one idea would be making the visibleIf's default to the question.valueName while the question.name remains as is.

**Comment by andrewtelnov** [comment]
@lady3bean I understand that we want the perfect solution. However, it is not easy technically recognize in abstract case what is 'a.b.c': 
it can be: {"a.b.c": 1} or {"a.b": {c: 2}} or {a : {b: {c: 3}}}.
