### ISSUE TITLE
How it woks counter responses

### ISSUE THREAD

**Issue by victorfernandesraton** [surveyjs/survey-library#1716]
Hey everybody.

Ineeded get the value of number chopces are marked in a checkbox question. It's possible? do it works?

**Comment by andrewtelnov** [comment]
@victorfernandesraton It is as simple as this: `question.choices.length` if you have choices filtering or getting choices from the web service then it is better to use this code:
`question.visibleChoices.length`

Thank you,
Andrew

**Comment by kfarkasHU** [comment]
@victorfernandesraton as @andrewtelnov told, you can get all available answers by 
```
question.visibleChoices.length
```

to get the marked chocies number, try the following snippet:

```
const questionName = 'question1';
const question = survey.getQuestionByName(questionName);
const availableCohices = question.visibleChoices.length;
const markedQuestion= question.value;
const markedQuestionsLength = markedQuestion.length;

console.log(`There are ${markedQuestionsLength} marked question in question ${questionName}`);
```

hope, it helps

**Comment by victorfernandesraton** [comment]
thanks
