### ISSUE TITLE
ConfirmDelete in matrix dynamic shouldn't confirm deleting a row which hasn't received any data yet

### ISSUE THREAD

**Issue by csgchristian** [surveyjs/survey-library#1718]
### Are you requesting a feature, reporting a bug or asking a question?
Requesting a feature

### What is the current behavior?
If ConfirmDelete is set to true, it will always confirm deletion.

### What is the requested behavior?
I'd like there to be an option to not prompt for confirmation, only if the row hasn't been altered from its' original state.

**Comment by andrewtelnov** [comment]
@csgchristian Do you mean, if there is no value in any cell in the row, then just delete it without confirmation?

Thank you,
Andrew

**Comment by csgchristian** [comment]
Yes, this is what I mean. I think that makes sense.

**Comment by andrewtelnov** [comment]
@csgchristian I think we just stop showing the Confirm Delete dialog if there is no value in the row.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@csgchristian This functionality will be available in the next minor. We will release it on next week.

Thank you,
Andrew

**Comment by csgchristian** [comment]
Thanks!
