### ISSUE TITLE
visible if panel

### ISSUE THREAD

**Issue by NHENeil** [surveyjs/survey-library#1720]
### Are you requesting a feature, reporting a bug or asking a question?
bug

### What is the current behavior?
With a page that has the below JSON, built with survey-creator,  the JSON correctly hides and shows the panel1 when in creator and clicking Test Survey however in the upper part of the screen when the <servey> tag is used to show the survey the panel1 never gets shown.

### What is the expected behavior?
panel1 should hide and show in <survey> not just in test.

### How would you reproduce the current behavior (if this is a bug)?
minimal angular-cli project with the following JSON
`json2 ={
 "title": "BYOD",
 "pages": [
  {
   "name": "BYOD",
   "elements": [
    {
     "type": "dropdown",
     "name": "Manufacturer",
     "title": "Make",
     "choices": [
      {
       "value": "Apple",
       "text": "Apple"
      }
     ]
    },
    {
     "type": "panel",
     "name": "panel1",
     "elements": [
      {
       "type": "text",
       "name": "question2",
       "title": "Model"
      },
      {
       "type": "text",
       "name": "question3",
       "title": "WiFi MAC"
      }
     ],
     "visibleIf": "{Manufacturer} notempty",
     "title": "Details"
    },
    {
     "type": "boolean",
     "name": "question4"
    }
   ],
   "title": "BYOD"
  }
 ],
 "showProgressBar": "top"
}`

The html for app.component is as below

#### Provide the test code and the tested page URL (if applicable)
The html for app.component is as below

Test code

```
<h1>
  {{ title }}
</h1>

<h1>Survey</h1>
<survey [json]="json2" (submitSurvey)="sendData($event)"></survey>

<h1>Survey JS Creator</h1>
<survey-creator
  [json]="json2"
  (surveySaved)="onSurveySaved($event)"
></survey-creator>

```

### Specify your

* browser:  chrome

* browser version:  Version 74.0.3729.169 (Official Build) (64-bit)

* surveyjs platform (angular or react or jquery or knockout or vue):
Angular CLI

* surveyjs version:
    "survey-knockout": "latest",
    "survey-angular": "latest",
    "survey-creator": "latest",
    "surveyjs-widgets": "latest",

**Comment by NHENeil** [comment]
Issue is caused by having both the <survey> and <survey-creator> tags in the same app-component.

**Comment by andrewtelnov** [comment]
@NHENeil Yes, indeed. Something strange happens. We will take a look.

Thank you,
Andrew

**Comment by tsv2013** [comment]
Fix will be available in the nearest update, most likely tomorrow
