### ISSUE TITLE
dot and whitespace in question name

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1721]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

when using expression you can link question value by a dot notation like {matrix1.question1}. It seems also possible to use whitespaces or dot in question name (i.e: "question one"). In this case how would you point to the question value?

### What is the expected behavior?

I would expect surveyJS prevent raise an exception when using invalid or risky chars in name property? I would expect more rigidity. Alternatively is there any guide lines on this?

**Comment by andrewtelnov** [comment]
@masciugo I have just implemented the code that allows to have dot in question and column names.
white-space never was not an issue.
Please refer to [this GitHub issue](https://github.com/surveyjs/survey-library/issues/1715).

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@masciugo We will release new version with this fix on next week.

Thank you,
Andrew
