### ISSUE TITLE
showQuestionNumbers property without quoting in json giving exception

### ISSUE THREAD

**Issue by dk981234** [surveyjs/survey-library#1724]
var json = {
	showQuestionNumbers: false,
	questions: [
		{
			type: 'text',
			name: 'example',
			title: 'example'
		}
	]
};
Getting  exception while showQuestionNumbers field is not quoted

**Comment by tsv2013** [comment]
According the [documentation](https://surveyjs.io/Documentation/Library/):

> For a question title, there are additional properties that many people find useful. At first, you may control the question numbering. By default, all questions titles show question number, from 1 till the visible question number in the survey. You may turn it off by setting survey showQuestionNumbers property to "off", or start the numbering from the beginning on each page, by setting this property to "onPage".

**Comment by tsv2013** [comment]
Probably these values are not so intuitive as we wanted to
