### ISSUE TITLE
Rating rateMin not applied from JSON

### ISSUE THREAD

**Issue by marc0n3** [surveyjs/survey-library#1728]
https://plnkr.co/edit/tjhHd3RPsfYiTYxDp0fg?p=preview

### Are you requesting a feature, reporting a bug or asking a question?

reporting a bug

### What is the current behavior?

Actually, setting Min to 50 Max to 100 and step to 10 you get the default for Min

### What is the expected behavior?

a range from 50 to 100 with a step of 10

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://plnkr.co/edit/tjhHd3RPsfYiTYxDp0fg?p=preview

### Specify your

* browser: Chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): tested in react and knockout
* surveyjs version: 1.0.92

**Comment by marc0n3** [comment]
actually, if condition in property set are triggering because rateMin is the first to be setted and the others are still unset and get default values

**Comment by andrewtelnov** [comment]
I have fixed the issue. We will included the fix into the next minor version that we will release shortly.

Thank you,
Andrew
SurveyJS Team
