### ISSUE TITLE
[Question] syntax of getValue, setValue for Matrix single choice

### ISSUE THREAD

**Issue by doongle** [surveyjs/survey-library#1730]
### QUESTION

What is syntax to getValue, setValue for Matrix single choice?
For single question, I can do survey.getValue('question1') and survey.setValue('question1', 'newValue').
But how do I get/set for question2:row1 value? What's the syntax?

**Comment by doongle** [comment]
I think I got it for setValue()
survey.setValue('question1', {row1: "2", row2: "3"}) with quotes.
But I'm still struggling to get getValue() syntax correctly.

**Comment by doongle** [comment]
I've got what I want, but is it correct way to get value?
survey.getValue('qestion01').row1

**Comment by doongle** [comment]
I have more than 10 rows in matrix single choice.
If I do survey.setValue('question1', {row1: "2"}), it will update row1 correctly, but will reset rest of them.
Is there a way to update specific rows without specifying them all?

**Comment by andrewtelnov** [comment]
@doongle You may merge the value:
```js
let question1Value = survey.getValue("question1);
question1Value.row1 = "2";
survey.getValue("question1, question1Value);
```

Thank you,
Andrew
