### ISSUE TITLE
Theme website broken

### ISSUE THREAD

**Issue by glumb** [surveyjs/survey-library#1731]
The website https://surveyjs.io/Examples/Library/?id=orange-theme linked on your overview page is broken and displays

```
Error.
An error occurred while processing your request.
```

**Comment by andrewtelnov** [comment]
@glumb We have removed this example. We have to show a better text for this error. You may change the theme almost for all our examples now. For example, here is [an example](https://surveyjs.io/Examples/Library?id=survey-options&platform=jQuery&theme=orange) in orange theme.

Thank you,
Andrew

**Comment by glumb** [comment]
Thanks 🙂

**Comment by andrewtelnov** [comment]
@glumb and we are showing now the better error explanation on navigating to the wrong example.

Thank you,
Andrew

**Comment by glumb** [comment]
I found the broken link here on the overview page. 
![8D2A5F65-76EF-4217-832F-E96B6266546E](https://user-images.githubusercontent.com/3062564/60029315-34212800-96a1-11e9-85e1-0ea612b1ab14.jpeg)

**Comment by tsv2013** [comment]
@glumb Thank you for the report, I've fixed the link
