### ISSUE TITLE
Unable to update a different column in the same row inside a matrixdynamic in onValueChanged?

### ISSUE THREAD

**Issue by bstalzer** [surveyjs/survey-library#1733]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question, possibly a bug?
I could be mistaken, but it appears that with the row that was the source of the onValueChanged, its isRowChanging flag is still true when I am trying to update the other column, so the update doesn't make it quite all the way through the setValue process.

### What is the current behavior?
When I add a handler for onValueChanged on a matrixdynamic, I am unable to update a different column in the same row when a value is changed.

When I click the "Don't know" checkbox, values in other questions/rows of matrixdynamic are updated, but the text column value of the row in which I'm editing is not updated/cleared.

My current workaround is to use setTimeout and fire after I estimate the isRowChanging flag will be false again.

### What is the expected behavior?
I'd like to be able to have a change in state of a checkbox alter the value of a text input in the same row.
When I mark the "Don't know" checkbox, I'd like to empty (or set to a special value) the textbox within the same row as the checkbox. I believe disable and hide work a treat as things are.

### How would you reproduce the current behavior (if this is a bug)?
Please see the code/splunk

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/UMTedDnE2aQkd7cLWpkJ?p=preview (version 2)

Test code
```
Survey
    .StylesManager
    .applyTheme("default");

var json = {
    questions: [
       {
         type: "text",
         name: "testField",
         title: "Test field"
       },
        {
            type: "matrixdynamic",
            name: "twoPlusTwo",
            title: "What is 2 + 2?",
            cellType: "text",
            maxRowCount: 1,
            minRowCount: 1,
            columns: [
                {
                    name: "twoPlusTwoAnswer",
                    title: "Answer",
                    cellType: "text",
                    inputType: "number"
                },
                {
                    name: "twoPlusTwoDK",
                    title: "Don't know",
                    cellType: "boolean",
                    defaultValue: false
                }
            ],
            rowCount: 1
        },
        {
            type: "matrixdynamic",
            name: "fourPlusFour",
            title: "What is 4 + 4?",
            cellType: "text",
            maxRowCount: 1,
            minRowCount: 1,
            columns: [
                {
                    name: "fourPlusFourAnswer",
                    title: "Answer",
                    cellType: "text",
                    inputType: "number"
                },
                {
                    name: "fourPlusFourDK",
                    title: "Don't know",
                    cellType: "boolean",
                    defaultValue: false
                }
            ],
            rowCount: 1
        }
    ]
};

var survey = new Survey.Model(json);

survey.setValue("testField", "Initial value");
survey.setValue("twoPlusTwo", [  
      {  
         "twoPlusTwoAnswer": 4,
         "twoPlusTwoDK": true
      }
   ]);

let onValueChanged = (sender,options) => {
  switch(options.name){
    case "twoPlusTwo" :
      sender.setValue("testField","twoPlusTwo: " + options.name + ":" + options.value[0].twoPlusTwoDK);
      if(options.value[0].twoPlusTwoDK === true){
        sender.setValue("twoPlusTwo",[{twoPlusTwoAnswer: null, twoPlusTwoDK: false}]);
        
        sender.setValue("fourPlusFour",[{fourPlusFourAnswer: null, fourPlusFourDK: true}]);
        
        sender.setValue("testField","This happened");
      }
      break;
    case "testField":
      break;
    default:
      sender.setValue("testField","default case: " + options.name);
      break;
  }
};

survey
    .onComplete
    .add(function (result) {
        document
            .querySelector('#surveyResult')
            .innerHTML = "result: " + JSON.stringify(result.data);
    });

$("#surveyElement").Survey({model: survey, onValueChanged: onValueChanged});
```

### Specify your

* browser: Chrome, IE
* browser version: updated/latest
* surveyjs platform (angular or react or jquery or knockout or vue): react, jquery
* surveyjs version: 1.0.94

**Comment by andrewtelnov** [comment]
@bstalzer Please use [onMatrixCellValueChanged](https://surveyjs.io/Documentation/Library/?id=surveymodel#onMatrixCellValueChanged) event.
Here is the example:
```js
survey.onMatrixCellValueChanged.add(function(sender, options) {
  if(options.columName == "My Column") {
    options.getCellQuestion("Another Column Name").value = options.value  + " add some text";
  }
});
```

And you may want to use the expression cell type. In this case you do not need to write any code. Here is [the example](https://surveyjs.io/Examples/Library/?id=questiontype-matrixdynamic-totals).

Thank you,
Andrew

**Comment by bstalzer** [comment]
This event handling definitely works without timing issues. Perfect and thanks!

I'm not sure I follow with the expression type for the cell in my example.
I think of expressions as one-way calculated fields. I'm editing, upon change on the checkbox, a participant-editable field that happens to have number for inputType.

Say, the user enters an answer like 3 for the 2+2 question, but then sees Don't Know and they know they don't know. So then I clear their answer or set to a different value: 99 which the data analyst prefers to see in the number question response when Don't Know is checked.

But then, if the participant thinks, "Wait, I know 2+2." and unchecks Don't Know, then I either clear the value or maybe I held onto their previous answer of 3 and make that re-appear.

A no-code way to do that would be powerful, but I think I'm in a different type of situation?

**Comment by andrewtelnov** [comment]
@bstalzer Yes, expression is readonly and in your case, it is better to use onMatricCellValueChanged event.

Thank you,
Andrew

**Comment by bstalzer** [comment]
Thanks for your quick support and ongoing maintenance of this powerful tool!
