### ISSUE TITLE
[Question] Display comment box and select all option for Matrix question

### ISSUE THREAD

**Issue by karthickvkumar** [surveyjs/survey-library#1734]
Hi @andrewtelnov @tsv2013 
I'm new to SurveyJS, I  just trying to create a survey based on the below mentioned image
![surveyjs](https://user-images.githubusercontent.com/11032434/60076042-37b9bb00-9744-11e9-8935-7d15e901e082.png)

I tried by using Matrix and Matrixdropdown but couldn't achieve the result. It would be helpful if you provide any suggestion to create a form as mentioned in image.

Thanks in Advance

**Comment by andrewtelnov** [comment]
@karthickvkumar You can use matrix dropdown. Here is [the example](https://surveyjs.io/Examples/Library/?id=questiontype-matrixdropdown). Howefver, choice1, choice2 and choices 3, will be in one column.

Thank you,
Andrew

**Comment by karthickvkumar** [comment]
@andrewtelnov Thanks you so much! Is there any way to customize the matrix dropdown as per my requirement.  And also I want to implement  Select ALL for choices in horizontal mode and hide one comment box by default

**Comment by andrewtelnov** [comment]
@karthickvkumar You may use "Select All" for checkbox column. Here is [the example](https://surveyjs.io/Examples/Library/?id=questiontype-checkbox) for checkbox.
Here is [the example](https://surveyjs.io/Examples/Library/?id=condition-dynamic) of using column.visibleIf expression in a matrix.

Thank you,
Andrew

**Comment by karthickvkumar** [comment]
@andrewtelnov  Thanks a ton! Is it possible to customize the Matrix dropdown choices to be list out in horizontal way ( eg., Matrix question)

**Comment by andrewtelnov** [comment]
@karthickvkumar Unfortunately we do not have it out of the box. You may have a boolean cell type. You will have one check in the cell.

Thank you,
Andrew

**Comment by karthickvkumar** [comment]
Thanks you so much @andrewtelnov
