### ISSUE TITLE
Maximum call stack size exceeded with questionsOrder option

### ISSUE THREAD

**Issue by elchiconube** [surveyjs/survey-library#1736]
I'm trying to populate the JSON and I have a `Maximum call stack size exceeded` error when I put the `questionsOrder` to `random`

Any idea why? 

Thanks

* browser: 75.0.3770.100
* browser version: Chrome
* surveyjs platform (angular or react or jquery or knockout or vue):jquery
* surveyjs version:1.0.50

**Comment by andrewtelnov** [comment]
@elchiconube Could you please try the current version: v1.0.95

Thank you,
Andrew

**Comment by elchiconube** [comment]
Solved! Thanks @andrewtelnov
