### ISSUE TITLE
custom function in choicesByUrl

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1738]
Is it possible to use custom function (like age())in choicesByUrl string as it was an expression? The only way I found to do that is a2-steps solution: adding an expression field and use it in choicesByUrl. More generally in which properties I can use custom functions? 

- expression
- visibleIf
- ...

**Comment by andrewtelnov** [comment]
@masciugo Unfortunately, we do not have this functionality right now. However, you do the following workaround:
Add an expression question on a page and set its visible property to false, set its expression property (you may use a custom function here) and then use the expression question name in choicesByUrl property as {yourExpressionQuestionName}. 

Thank you,
Andrew

**Comment by masciugo** [comment]
yes that what I did. Problem is that my app users build their own survey by inserting the json syrvey model. So this way I had to teach them extra DSL. That's why hoped in something native. thank you anyway

**Comment by andrewtelnov** [comment]
@masciugo We have introduced calculatedValues in the latest release. You may add a new calculated value, set an expression for it and then use it choicesByUrl.
[Here](https://surveyjs.io/Examples/Library/?id=survey-calculatedvalues) is the example of calculated value. It doesn't do exactly what you need, but you have to get the idea.

Thank you,
Andrew
