### ISSUE TITLE
[Question] document on dragDrop

### ISSUE THREAD

**Issue by swuecho** [surveyjs/survey-library#1739]
I am confused on dragDrop.

from the code: 

```
(method) PageModel.dragDropStart(src: IElement, target: IElement, nestedPanelDepth?: number): void
```

in the dragdrop test:
```
 var survey = new SurveyModel();
  var page = survey.addNewPage("p1");
  var q1 = page.addNewQuestion("text", "q1");
  var q2 = page.addNewQuestion("text", "q2");
  var target = new QuestionTextModel("qt");
  page.dragDropStart(null, target); 
  assert.equal(page.rows.length, 2, "Two elements initially");

  assert.equal(page.dragDropMoveTo(q1, false), true, "It can be done: 1"); 
  assert.equal(page.rows.length, 3, "Move 1");
  assert.equal(page.rows[0].elements[0].name, "qt", "Move 1")
```
hard to understand the test .  I guess the result is, move qt to the row above q1 . If so, 'qt' should be the source? 

If I want to move q1 below q2, what shoud i do?

I thought it should be like this.
```
page.dragDropStart(q1)
page.dragDropMoveTo(q2, true)
```
obviously, not correct.

ideally, 
```
page.dragDrop(q1, q2, true) // no possible now. 
```
Thanks!

**Comment by andrewtelnov** [comment]
@swuecho What task do you want to solve?
Do you want to move an element from one position to another?
In this case you have to write the following code:

```js
page.removeElement(q1);
var index = page.indexOf(q2);
page.addQuestion(q1, index);
```
Where page can be any container, for example a panel.
or more general code:
```js
var newParent = q2.parent;
if(!newParent) return;
if(!!q1.parent) {
  q1.parent.removeElement(q1);
}
var index = newParent.indexOf(q2);
newParent.addQuestion(q1, index);
```
I would offer the following API:
```js
element.moveTo(container, questionInsertBefore);
```
If questionInsertBefore is null then add into the end of the list. In fact, since we are in JavaScript world, we may have 
```js
element.moveTo(container, insertBefore);
```
Where insertBefore maybe an index or an element from the list. 

Thank you,
Andrew

**Comment by swuecho** [comment]
@andrewtelnov Yes. I want to move question postion. the solution you provide works great, except the `page.elements.indexOf` should be used to get the index. Thanks.

```
element.moveTo(container, insertBefore);
```
will be very handy.  

should be better if split into `element.moveBefore(container, indertBefore)` and `element.moveAfter(container, indertAfter)`.  However,  this is not crucial since it is easy to implement use `element.MoveTo`.

**Comment by andrewtelnov** [comment]
@swuecho Implemented. It will included into the next minor udate that we will release in several days, likely on Tuesday.

Thank you,
Andrew
