### ISSUE TITLE
Is it possible to make matching and order quiz?

### ISSUE THREAD

**Issue by mflash123** [surveyjs/survey-library#1740]
Is it possible to make matching test(quiz)?
Example:
![p3](https://user-images.githubusercontent.com/1176181/60504918-3f8cd880-9ccb-11e9-8c5f-380bebfffa65.gif)

**Comment by tsv2013** [comment]
Please describe your scenario in greater details.

**Comment by mflash123** [comment]
> Please describe your scenario in greater details.

I need to do matching tests. For example, I need find match for **Fruit** find from **monitor,apple,red** words.
Then for **device** find matches and etc...
I think it is difficult to explain in words, so I attached gif
![p3 (1)](https://user-images.githubusercontent.com/1176181/60515415-3d834380-9ce4-11e9-935a-7212f1d11038.gif)

**Comment by tsv2013** [comment]
Thank you for the clarification. I see now.

We don't have such built-in functionality, but you can try to use a set of SortableJS custom widgets. Here is the live sample - https://surveyjs.io/Examples/Library/?id=custom-widget-sortablejs&platform=jQuery&theme=default
