### ISSUE TITLE
Delete hidden values not working

### ISSUE THREAD

**Issue by Nils-DE** [surveyjs/survey-library#1742]
First of all, I am not a professional developer, just a guy of the "business side" trying to improve his coding skills. Additionally, this is my first posting here on GitHub, hoping that anybody had a related issue and is able to help. Big thanks in advance!

### Are you requesting a feature, reporting a bug or asking a question?
I implemented the surveyjs OS Editor into my ASP.Net Tool. 
As the tool and the JSON include confidential data, I am not able to share the code here. Sorry for that!

### What is the current behavior?
My survey is splitt up in different pages and the user can predefine answer in the tool. In the end of the tool there is a page for "Success" and "Not successful" depending on given answers.
Now I got a problem similar to this issue #299 . Through the predefined question the user opens up a fully answered surveyResult, e.g. leading to "Success". If the user changes the first question to "No" which would lead to the result "Not Successful" only the hidden answer ON THIS ONE PAGE are deleted but the answers on the following are still saved. The result is that I always reach the "Success" page in the end, as the answer which are hidden correctly leading to this page.
In surveyjs.io (where I built up the surveys) I set "Delete hidden values" to "OnHidden"

### What is the expected behavior?
Expected behaviour is, that ALL hidden answers are cleared when the user backtracks an answer and not only the ones on the page the reference question is changed. 

### How would you reproduce the current behavior (if this is a bug)?
1) Answer all pages of the survey
2) Save
3) Change first answer so the next pages are not visible anymore
4) Track if the hidden answers are still saved in the result

### Specify your

* browser: Chrome
* browser version: 75.0
* surveyjs platform (angular or react or jquery or knockout or vue): Surveyjs.io
* surveyjs version: 1.0.96

**Comment by tsv2013** [comment]
Hello, I've created a small live sample for you - https://plnkr.co/edit/cQgArWXFcTzD9kl7ew0T?p=preview
Initial data contains values for all questions. Then if you change question1 value, question3 and question4 became hidden and their values are cleared on survey complete as you can see from the survey result.

Do I miss something? Please feel free to update this sample according your actual scenario.

**Comment by Nils-DE** [comment]
Hello tsv2013,

thank you very much for this example. Fits pretty good to my situation.
My problem is, that only the results of the questions on the page of the changes questions are cleared and not the other pages.
