### ISSUE TITLE
How do I style my custom question to look different from other questions. 

### ISSUE THREAD

**Issue by napakorn-sricomnerd** [surveyjs/survey-library#1743]
### Are you requesting a feature, reporting a bug or ask a question?
Question
### What is the current behavior?
Now all questions in SurveyEditor have same styling (e.g color and background).
How do I style my custom question to look different from other questions. 

### What is the expected behavior?
I want to customise my custom question style.

I updated the onQuestionAdded event and add isGlobal property to this and would like this to display differently, at least background or border colour.

```
{
	"type": "comment",
	"name": "customQuestion",
	"title": "My Custom Question Title",
	"displayName": "My Custom Question Display Name",
	"isGlobal": false
}

```
Thank you,
Napakorn

### Specify your

* browser:
* editor version: v1.0.53

**Comment by tsv2013** [comment]
I've moved this question to the corresponding repository

**Comment by napakorn-sricomnerd** [comment]
Hi @tsv2013 

Thanks for your reply. However, I want something like 
`survey
    .onUpdateQuestionCssClasses
    .add(function (survey, options) {
        var classes = options.cssClasses

        classes.root = "sq-root";
        classes.title = "sq-title";
        classes.item = "sq-item";
        classes.label = "sq-label";

        if (options.question.isRequired) {
            classes.title = "sq-title sq-title-required";
            classes.root = "sq-root sq-root-required";
        }

        if (options.question.getType() === "checkbox") {
            classes.root = "sq-root sq-root-cb";
        }
    });
`
but in Survey Editor/Creater side

Thanks,
Napakorn

**Comment by tsv2013** [comment]
The survey creator uses the survey-knockout library. You can access inner survey object via the `creator.survey` property of in the https://surveyjs.io/Documentation/Survey-Creator/?id=surveycreator#onSurveyInstanceCreated event handler.
