### ISSUE TITLE
Error using onIsAnswerCorrect method 

### ISSUE THREAD

**Issue by elchiconube** [surveyjs/survey-library#1744]
When I use the `onIsAnswerCorrect` method the questions are double. Any idea?
I only have two questions but If I make a `console.log` I see four questions results
I expected only two questions

Code
```
survey.onIsAnswerCorrect.add(function (sender, options) {
  console.log('onIsAnswerCorrect fired')
  console.log('onIsAnswerCorrect - sender', sender)
  console.log('onIsAnswerCorrect - options', options.question.title)
  console.log('onIsAnswerCorrect - options', options.question.value)
  console.log('onIsAnswerCorrect - options', options.result)
})

```

* browser: Chrome
* browser version: 75.0.3770.100
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.95

**Comment by dk981234** [comment]
Hello,
Could you provide your sample in planker for example?
Thank you
Dmitry
SurveyJS Team
