### ISSUE TITLE
jquery date picker issue

### ISSUE THREAD

**Issue by KhanUzair01** [surveyjs/survey-library#1746]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Text question with type 'date', does not work in internet explorer. So tried adding 'jquery date question'. If you can solve text with 'date' type that would be wonderful. But since <input type='date'> is not supported in IE and I have to use jquery option I am opening this issue.

I added custom jquery date question, which works fine in surveyjs package. And I got the date picker too. Followed the steps explained in plugins/README.
Then I installed SurveyJs package in Survey Editor, I dragged the date question and got the date properties on the right side. But when I tried to see result, it throws an error. Debugged to see where it does, it throws error at this point SurveyEditor.tsx => onPreview () => this.editor.showTestSurvey();

### What is the expected behavior?
Once the question is dragged and date question's properties are visible, if result is rendered it should work and date picker calendar should open, (both in chrome and IE)

### How would you reproduce the current behavior (if this is a bug)?
For 'text date type', just drag text input and change input type to date, result is that date picker opens in chrome but not in IE.
For jquery date question issue, follow steps in 'plugins/README' to custom add jquery date question, build and then install package in survey creator. Drag the new date question, questions comes and its related properties come on right, see the dragged question in preview mode. It throws error.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: 
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@KhanUzair01 Do you mean [this example](https://surveyjs.io/Examples/Library/?id=custom-widget-datepicker)?
I have just tried it in IE11 and it works fine.

Thank you,
Andrew

**Comment by zenithA** [comment]
In relation to the example above, how is the widget to be used? What is that should be done extra, other than adding something like
`  {
            "name": "date",
            "type": "datepicker",
            "inputType": "date",
            "title": "Your favorite date:",
            "dateFormat": "mm/dd/yy",
            "isRequired": true
        }` to our json, in order to get a functional datepicker on Chrome that works also on IE11?
