### ISSUE TITLE
set comment value does not work in react

### ISSUE THREAD

**Issue by marc0n3** [surveyjs/survey-library#1747]
It seems that setting comment value after model first rendering, in REACT version, does not affect the model nor the rendering

https://codepen.io/marcone/pen/ydqroR

**Comment by andrewtelnov** [comment]
@marc0n3 It works as it should to work. What is wrong?
I have changed hasComment to hasOther. Here is [the forked version](https://codepen.io/anon/pen/rEZyZb). Probably you was looking for this.

Thank you,
Andrew

**Comment by marc0n3** [comment]
radiogroup 1 value is changing as expected after 2 seconds.

"radiogroup1-Comment": "this is a test" is not changing and remains initial value

**Comment by andrewtelnov** [comment]
@marc0n3  We will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@marc0n3 I have fixed the issue by the commit above.

Thank you,
Andrew
