### ISSUE TITLE
Dynamic Matrix Default Dropdown Selection Doesn't Fire Validation

### ISSUE THREAD

**Issue by RA-Work-A** [surveyjs/survey-library#1749]
### Are you requesting a feature, reporting a bug or asking a question?

Question 

### What is the current behavior?

When using the dynamic matrix panel, and when selecting the default choice, eg. 'choose'. There is no way to change the default message of "Please fill in at least x rows. 

### What is the expected behavior?

See : https://surveyjs.io/Examples/Library/?id=condition-dynamic&platform=jQuery&theme=default

I would like to be able to change the "Please answers the question" error message. The issue here is that surveyValidateQuestion(s, options) is not called when the default selection is made. eg, if I have 2 choices (mom, dad), but my default option is "Choose a parent". If I select Choose a parent, the survey validate method is not called, some other validator is called. 

I tried to override the default message here --> survey.getQuestionByName('YourFavoritePerson').errors[0].locTextValue.values.default but that doesn't appear to have any effect. 

### How would you reproduce the current behavior (if this is a bug)?

https://next.plnkr.co/edit/hgUNdWgaSDlXIdBT?open=lib%2Fscript.js

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version: 75.0.3770.100 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.96

**Comment by dk981234** [comment]
Hello,
"Please fill in at least x rows" is not validate error text. It is printed by minRowCount error. So you can redefine your validate text and text for this error.
Here is the [sample](https://next.plnkr.co/edit/CKPCINswRA8bcTw9?open=lib%2Fscript.js)
Thanks
Dmitry
SurveyJS Team
