### ISSUE TITLE
Dynamic Matrix SetValue Doesn't trigger based on checkbox

### ISSUE THREAD

**Issue by RA-Work-A** [surveyjs/survey-library#1750]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

Be me. 
Have a Dynamic Matrix. 
The Dynamic Matrix has a radio button that calls setvalue. When setvalue is called, I am pulling values from another dynamic matrix. When setvalue is called, the values need to be set, don't technically exist yet. However, calling setvalue does set the values. What it doesn't do, is update the view on the screen. 
eg. 

Dynamic Matrix (A)
A.FirstName
A.LastName

DynamitMatrix(B)
B.IsYourNameTheSameAsAbove?
B.FirstName
B.LastName

If B.IsYourNameTheSameAsAbove is "yes". Then setvalue("B", [{FirstName: A.FirstName, LastName: A.LastName}].

This **does** update the data, however the view doesn't change. 

If I do this via the browser console, the view updates just fine. 

### What is the expected behavior?

I expect the view (the browser window content), to update when setvalue is called. 

### How would you reproduce the current behavior (if this is a bug)?

https://next.plnkr.co/edit/eyHIDx10jc3zwnwY?preview

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version: Version 75.0.3770.100 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.96

**Comment by dk981234** [comment]
Hello, 
The trigger you've written is setting value for the same question, as the event triggered this and it's conflicting. So you can create separate question for your checkbox, and set trigger for it.
Here is your [sample](https://next.plnkr.co/edit/lIGXIBthzYn0GKYS?preview)
Thanks
Dmitry
SurveyJs Team
