### ISSUE TITLE
Reuired style from question cssstandard overriden when element have specific style options

### ISSUE THREAD

**Issue by themobius85** [surveyjs/survey-library#1752]
### Are you requesting a feature, reporting a bug or asking a question?
Possible bug

### What is the current behavior?
In the questions.ts/updateCssClasses the required css class is copied into the question root but a few lines later it gets overriden by the element style if it is a string or if the root is defined. Meaning it dosent't matter what you fill in the custom css question.required field as long as the element have another entry in the default css mapping or you custom css. For example "text" has an entry in the cssstandard.ts so the value in the root gets overriden by whatever is in the text entry.
Also the current code would set the question.root to "undefined [question.required]" when root is not defined wich by defult is not defined if it would not override the root css.

### What is the expected behavior?
Requierd custom css field works.

### How would you reproduce the current behavior (if this is a bug)?
- Add a text field to your form. 
- Make the field required
- Either edit the cssstanard.ts file and set question.required : "classWithSomeCss" or set the custom css with the follwing object: {question: {required: "classWithSomeCss"}.
- Make sure that the "classWithSomeCss" is actually exist in your style sheet.
- The style is not applied since the question.root will be whatever is the 'text' element in the css mapping (cssstandrd.ts).

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here
  protected updateCssClasses(res: any, surveyCss: any) {
    if (this.isRequired) {
      if (surveyCss.question.required) {
        //CAN PRODUCE undefined someCssClass
        res.root += " " + surveyCss.question.required;
      }
      if (surveyCss.question.titleRequired) {
        res.title += " " + surveyCss.question.titleRequired;
      }
    }
    var objCss = surveyCss[this.getType()];
    if (objCss === undefined || objCss === null) return;
    if (typeof objCss === "string" || objCss instanceof String) {
      //OVERRIDES ROOT  CLEARING THE STYLE SET A FEW LINES ABOVE
      res.root = objCss;
    } else {
      for (var key in objCss) {
        //OVERRIDES ROOT  CLEARING THE STYLE SET A FEW LINES ABOVE IF ROOT IS SET
        res[key] = objCss[key];
      }
    }
  }

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by dk981234** [comment]
Hello
Thank you for your reply.
We' ll fix it. Changes will be available in the next release.
Thanks
Dmitry
SurveyJS Team
