### ISSUE TITLE
Disable SurveyJS preprocessing / mangling texts

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#1753]
### Are you requesting a feature, reporting a bug or asking a question?
Feature.

I'm looking into integrating support for another template language into SurveyJS.
For example, I'd like to use TwigJS or HandleBars.

There are several hooks to aid with this:
- `onProcessHtml`
- `onProcessTextValue`
- `onTextMarkDown`

However it seems that SurveyJS does some processing before the text(s) are passed to these callbacks.

For example, using a question text like this:
```
{{ a|b }}
```
Will be passed to `onTextMarkDown` as `{{ a||b }}`

Is there anyway to remove this behavior.

## Side note
In general, what is your opinion on including an external rendering engine instead of (re-)inventing your own? Currently SurveyJS supports very simple replacements of values, but more advanced stuff is hard or impossible, or requires JS.

An easy to implement solution would be to just hand this over to a different library.

**Comment by dk981234** [comment]
Hello,
There is  [sample](https://surveyjs.io/Examples/Library/?id=questiontype-matrix-rubric&platform=jQuery&theme=default). It shows how you can integrate support for another template language.
SurveyJS doesn't change text before these callbacks. You can see it  [here](https://plnkr.co/edit/904vySKc8UMlUvCGDV8a?p=preview)
Thanks
Dmitry
SurveyJS Team

**Comment by SamMousa** [comment]
Hmm, saw your reply and can't reproduce on another PC... will check again in the office and close if I can't reproduce it then.

**Comment by SamMousa** [comment]
Hmm, can't reproduce it, apologies.
