### ISSUE TITLE
When using a matrix with rowsOrder:"random" in React, the randomization is triggered after each click

### ISSUE THREAD

**Issue by aad4** [surveyjs/survey-library#1754]
```
{
    "pages": [
        {
            "title": "Some questions",
            "questions": [
                {
                    "type": "matrix",
                    "name": "opinions",
                    "title": "Please indicate if you agree or disagree with the following statements",
                    "isAllRowRequired": true,
                    "columns": [
                        {
                            "value": 1,
                            "text": "Completely disagree"
                        }, {
                            "value": 2,
                            "text": "Disagree"
                        }, {
                            "value": 3,
                            "text": "Agree"
                        }, {
                            "value": 4,
                            "text": "Completely agree"
                        }
                    ],
                    "rows": [
                        {
                            "value": "q1",
                            "text": "Hypothesis 1",
                            "isRequired": true
                        },
                        {
                            "value": "q2",
                            "text": "Hypothesis 2",
                            "isRequired": true
                        },
                        {
                            "value": "q3",
                            "text": "Hypothesis 3",
                            "isRequired": true
                        }
                    ],
                    "rowsOrder": "random"
                }
            ]
        }
    ]    
}
```

### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
When using a matrix with the option "rowsOrder":"random" in combination with the React wrapper, the randomization is triggered after every clicked radiobutton.

Funny thing is: this issue DOES occur when using React+SurveyJS, but it does NOT occur with the plunker that is referred to in the [NPS survey example](https://surveyjs.io/Examples/Library/?id=real-nps&platform=jQuery&theme=default), where I replaced the json by the one above.

### What is the expected behavior?
The randomization should only be triggered when displaying the page for the first time. So, when the page is filled in, and then the user navigates back and forth to other pages, and the comes back to the page, it should not randomize it again.

### How would you reproduce the current behavior (if this is a bug)?
Open the provided example and click on any of the radio buttons for the questions. After each click, the randomization is triggered again.

### Code
```
import React from 'react';
import {Survey, Model} from 'survey-react';
import 'survey-react/survey.css';
import json from './Test.json';
const Test = (props) => {
    const model = new Model(json);
    return (
        <Survey model={model} onComplete={onComplete}/>
    );
};
function onComplete(survey, options) {
    console.log(JSON.stringify(survey.data));
}
export default Test;
```

### Specify your
* browser: Chrome
* browser version: 75.0.3770.100
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.0.96

**Comment by tsv2013** [comment]
Fix will be available in the nearest update, most likely in a couple of days.
