### ISSUE TITLE
Difference between onIsAnswerCorrect and onValidateQuestion

### ISSUE THREAD

**Issue by elchiconube** [surveyjs/survey-library#1755]
Hi! Anyone can explain to me the difference between `onIsAnswerCorrect` and `onValidateQuestion`? I'm not sure what's the difference and when they are triggered.

Thanks!

* surveyjs platform: jQuery 
* surveyjs version: 1.0.96

**Comment by andrewtelnov** [comment]
@elchiconube Sure. onIsAnswerCorrect this event is mostly for Quiz, if the correct answeres to the question is stored/calculated on the server, for example. If a user answers incorrectly, SurveyJS will score the answer as incorrect and allow to move further. A user will not see any error.

onValidateQuestion - allows you to check in the code, if a user made an acceptable answer to the question. If you return an error, a user could not go to the next page or complete the error, untill he fixed the answer. Here is [the example](https://surveyjs.io/Examples/Library/?id=validators-event).

Thank you,
Andrew
