### ISSUE TITLE
visibleIf evaluated too early

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#1756]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
The first survey page is decided before the survey is rendered.

### What is the expected behavior?
It should be decided when rendering, unless explicitly set via methods like `nextPage()`.

### How would you reproduce the current behavior (if this is a bug)?
1. Create a survey with 1 question on the first page and another page with a question.
2. Add a `visibleIf` condition to that first question that depends on the data.
3. Instantiate the model: `survey = new Survey.Model(json);`
4. Set data `survey.data = { "q1": "abc" }`
5. Render the survey `survey.render(id)`.

This will show the survey on the second page, after the instantiation in step 3 the `survey.currentPage` is already page 2. Setting the data in 4 does not change it.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://next.plnkr.co/edit/95YgdLqGZDtTKJ41

## Solution
A solution would be to allow the data to be passed in the initial configuration, this would be most efficient.
Alternatively when setting data we must manually call `prevPage()` until it returns `false`.

**Comment by andrewtelnov** [comment]
@SamMousa It is not a bug. Here is what happend. You have created the survey using JSON. There is one visible page and the current page is "Page2"  then set the data and make the "Page1" visible.
The survey should not change the current page on setting the data, it can be unexpected behavior. You perform `survey.data = someData;` right after survey creation, however you may call this operator at any time.
The correct solution is:
```js
survey,data = someData;
survey.currentPageNo = 0;
```
Here is the [fixed example](https://next.plnkr.co/edit/ZR2h1go9lm2jz8Be?preview).

Thank you,
Andrew
SurveyJS Team

**Comment by SamMousa** [comment]
Is there a reason we cannot pass data into the constructor? That way we can avoid the overhead of navigating forward initially and then resetting it

**Comment by andrewtelnov** [comment]
@SamMousa It is easy to add into the Model and knockout (jQuery/Angular). However, we have to check how it will work in react and vue. What platform do you use?

Thank you,
Andrew

**Comment by SamMousa** [comment]
Vanilla JS; which means I'm forced to use Knockout ;-)

Might be good to update the current behavior in this example:
https://surveyjs.io/Examples/Library/?id=survey-data&platform=Knockoutjs&theme=default

The docs for `data`: https://surveyjs.io/Documentation/Library/?id=surveymodel#data should also mention that when using this at survey initialization time one probably wants to call `.currentPageNo=0` after.

A possible solution that is a bit more magic, could be to set `currentPageNo` to `0` whenever `data` is set **and** the survey has not been rendered yet. But that's totally up to you, current behavior is fine with me just needs to be better documented.

**Comment by andrewtelnov** [comment]
@SamMousa Added into description. The documentation on the website will be updated automatically later.

Thank you,
Andrew
