### ISSUE TITLE
show errors onValueChanged

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1759]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

I cannot well understand when the errors are calculated and when they are showed in the survey.

I expected to see all errors when something change with the option checkErrorsMode="onValueChanged" but it does not seem so:

or maybe it is supposed to check errors but not to show them

https://plnkr.co/edit/4GlgnYk9Xh5Dv0pqIlJk?p=info

to obtain what I mean I need to write code in the onValueChanged callbacks like this:
https://plnkr.co/edit/896pgsICMVYH2H2QVyGF?p=preview

but the hasErrors() method is not even mentioned in the docs.

Whats the correct way to run all validations and show errors manually and why the checkErrorsMode seems not to work when I want to do the same manually?

thanks

**Comment by andrewtelnov** [comment]
@masciugo onValueChanged shows only errors in the question that has been just changed. It would be strange to show an error for a question that user has not even touch yet.

Thank you,
Andrew

**Comment by masciugo** [comment]
Ok, fine. 

But is it possible to run all validations and show errors manually? Is there any official method to do that for every page at once? The best I could do was calling multiple times methods like  _hasErrors_ or _checkIsCurrentPageHasErrors_  on any page in callbacks attached to the onComplete event. I would expect something like:

checkErrorsMode="onComplete"

**Comment by andrewtelnov** [comment]
@masciugo the page (actually a container, the panel class as well) has the function:
`page.hasErrors(fireCallback: boolean = true,  focuseOnFirstError: boolean = false) : boolean`
where fireCallback - it shows errors visually.
`survey.currentPage.hasErrors();` will work

Thank you,
Andrew

**Comment by masciugo** [comment]
ok I will check page by page

thank you
