### ISSUE TITLE
[Question] How can I manually trigger surveyJS 'checkErrors'?

### ISSUE THREAD

**Issue by csgchristian** [surveyjs/survey-library#1761]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

When I initially load a survey for the user, I would like to display all errors immediately, so they see which fields require attention.

Currently I am using: `survey.checkErrorsMode = "onValueChanged";`, but this does not display the error until the user touches the survey question. I would like to display the error the moment the survey is loaded.

**Comment by andrewtelnov** [comment]
@csgchristian we have this function on page level: `page.hasErrors();`
For the current page: `survey.currentPage.hasErrors();`
For all pages:
`for(var i = 0; i < survey.pages.length; i ++) survey.pages[i].hasErrors();`

Thank you,
Andrew

**Comment by csgchristian** [comment]
Exactly what I needed, thanks!
