### ISSUE TITLE
Randomize questions inside panel

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#1764]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
Currently questions can be randomized only per page (but the configuration can be set at a survey level as a default for each page).

### What is the expected behavior?
I'd love to be able to randomize questions inside a panel.

**Comment by andrewtelnov** [comment]
@SamMousa It goes into our TODO list. It is not hard to move the functionality into PanelBase class (the parent for containers: Page and Panel). However, there is a code that tells that Page has been already shown and there is no need for another randomization. We would have to change it. We will keep this functionality in mind.

Thank you,
Andrew

**Comment by flowni** [comment]
This is exactly what I am also looking for, are there any updates on this yet?

**Comment by dmitrykurmanov** [comment]
implemented via the https://github.com/surveyjs/survey-library/commit/908e07621fa62a5c1bbd6f52526b547090d1c1c3

**Comment by SamMousa** [comment]
This has been implemented and is already working for a while now!
