### ISSUE TITLE
set rowCount and canAddRow not working with using values from question for matrixdynamic

### ISSUE THREAD

**Issue by michaelchandrag** [surveyjs/survey-library#1769]
### Are you requesting a feature, reporting a bug or asking a question?
question

### What is the current behavior?
1. set rowCount on matrixDynamic by another question's value not working
2. set canRowAdd on matrixDynamic to false not working

### What is the expected behavior?
1. Create a matrixdynamic with row length determined by another question's value
2. User cant add rows on matrix dynamic

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/cFiNuGmKE8n1zqrgyIpS?p=preview

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.1.0

**Comment by andrewtelnov** [comment]
@michaelchandrag Unfortunately we do not support this type of binding. You have to use onValueChanged event to handle it. canAddRow is not a property.
Here is your [updated example](https://plnkr.co/edit/iNDil4I0g5qxuhcTrjtR?p=preview).

Thank you,
Andrew

**Comment by michaelchandrag** [comment]
hey andrew thanks for the advice
using onValueChanged helps my issue
however, if there are a question with 'comment' type
the onValueChanged triggered like a keyup function, difference with other question's type like text and dropdown
can u investigate?
thanks

**Comment by andrewtelnov** [comment]
@michaelchandrag Do you use vue?

Thank you,
Andrew

**Comment by michaelchandrag** [comment]
yes i am
