### ISSUE TITLE
Regex validator doesn't work correctly with 0

### ISSUE THREAD

**Issue by kouhunzhe** [surveyjs/survey-library#1775]
### Are you requesting a feature, reporting a bug or asking a question?
 reporting a bug

### What is the current behavior?

Validation error when input type is modified to number

### What is the expected behavior?
Validation can be performed when the user enters a 0

### How would you reproduce the current behavior (if this is a bug)?
All Versions

Test code
When the input type is modified to number, the validate function is buggy in the validator.ts file
if (!this.regex || !(value)) return null;
In this sentence-------! (value)
value can be number type, take an anti-logic error
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by kouhunzhe** [comment]
**My solution is**
    if (!this.regex ) return null;
    if (value==undefined || value===null) return null;

**Comment by andrewtelnov** [comment]
@kouhunzhe New unit test is added and fixed.

Thank you,
Andrew
