### ISSUE TITLE
MatrixDynamic columns and visibleIf: Make column invisible if all its editors are invisible

### ISSUE THREAD

**Issue by yoon** [surveyjs/survey-library#1777]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

MatrixDynamic columns with visibleIf still show their headers even if the visibleIf condition isn't met.

### What is the expected behavior?

I'd expect the entire column to disappear.

### How would you reproduce the current behavior (if this is a bug)?

```
{
  "pages": [{
    "name": "page1",
    "elements": [{
      "type": "checkbox",
      "name": "years",
      "title": "Years",
      "choices": [{
        "value": "2018 actual",
        "text": "2018 actual"
      }, {
        "value": "2019 projected",
        "text": "2019 projected"
      }]
    }, {
      "type": "matrixdynamic",
      "name": "question1",
      "columns": [{
        "name": "Resource",
        "cellType": "text"
      }, {
        "name": "2018 actual",
        "cellType": "text",
        "visibleIf": "{years} contains '2018 actual'"
      }, {
        "name": "2019 projected",
        "cellType": "text",
        "visibleIf": "{years} contains '2019 projected'"
      }]
    }],
    "title": "Utility costs"
  }]
}
```

The 2018 actual and 2019 projects column headers still show even if they're unchecked in the previous question.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome on OSX
* browser version: Version 75.0.3770.142 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.1.1

**Comment by andrewtelnov** [comment]
@yoon Yep, it does look like a bug, however it is actually not :-)
column.visibleIf apply to cell.editor.visibleIf property, not to a column itself. You may use there the code as: `"{row.columnNameA} = 'showMeColumn.B'"`, where row.columnNameA is the cell editor value of ColumnNameA on the same row.
Many people use it in this way.
Of course we can go further and hide the column completely if all its editors are invisible. From UI point of view, it is a logical thing to do.
I made the ticket as an usability issue and we wil think about the fix.

Thank you,
Andrew

**Comment by yoon** [comment]
@andrewtelnov thanks for the response! I'd be happy to create a PR - could use a little direction though. E.g. what code hides rows in matrixdropdown questions (and thus columns when `columnLayout` is vertical) with visibleIf?

**Comment by andrewtelnov** [comment]
@yoon There are several levels of abstraction here:
Question Model (QuestionMatrixDropdownBase->QuestionMatrixDynamic) then rendered (View) classes (QuestionMatrixDropdownRendered* classes) that convert columns to rows and for different layout and at last plaform depended code for knockout, react and vue.
I will take a look at this functionality on this week, since I feel it is logical to have it and comeback.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@yoon You may try the current code in react. It should work fine now.

Thank you,
Andrew

**Comment by yoon** [comment]
Many thanks! 👏
