### ISSUE TITLE
visibleIf in matrixdropdown doesn't run after a component re-renders

### ISSUE THREAD

**Issue by yoon** [surveyjs/survey-library#1778]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

On a survey component re-render, visibleIf triggers no longer work

### What is the expected behavior?

visibleIf should continue to work

### How would you reproduce the current behavior (if this is a bug)?

The plnkr code below loads the survey, sets the state (which causes a re-render), and the checkboxes no longer trigger showing / hiding rows.

Note: on re-render `visibleRowsChangedCallback` is undefined.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://embed.plnkr.co/plunk/83NklNG699CV6b7K (kudos @als753)

### Specify your

browser: Chrome on OSX
browser version: Version 75.0.3770.142 (Official Build) (64-bit)
surveyjs platform (angular or react or jquery or knockout or vue): react
surveyjs version: 1.1.1

**Comment by dk981234** [comment]
Hello, 
Fix for this bug is available in 1.1.2 version.
Thanks 
Dmitry

**Comment by andrewtelnov** [comment]
@yoon ping about fixing the issue in v1.1.2

**Comment by yoon** [comment]
@dk981234 and @andrewtelnov Many thanks! 👏
