### ISSUE TITLE
Checkbox | character

### ISSUE THREAD

**Issue by carl2g** [surveyjs/survey-library#1780]
Hi, I want to include the character  |  in a checkbox element value. But it seems the library is interpreting and splitting the value on |, even if the text filed is already set.

Can the library not interpret the value if both text and value fields are set ?
Is there an other way to include | in the value ?

Here is an exemple:

```
var json = {
    questions: [
        {
            type: "checkbox",
            name: "car",
            title: "What car are you driving?",
            isRequired: true,
            hasNone: true,
            colCount: 4,
            choices: [
                { value: "Renault | Ford", text: "Renault | Ford" }
            ]
        }
    ]
};
```
Thanks for your time.

**Comment by gologames** [comment]
Hello,

You can to set another `Survey.settings.itemValueSeparator` to solve this problem. Here is [live sample](https://plnkr.co/edit/iYI5LigJR1qo0sHmRvFQ?p=preview) in plunker

Thanks, Alex
SurveyJS Team

**Comment by carl2g** [comment]
Thanks a lot !
Have a nice day
