### ISSUE TITLE
Can you add indicator whether user changed survey or value was updated in 'onValueChanged'?

### ISSUE THREAD

**Issue by als753** [surveyjs/survey-library#1782]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
Currently I am trying to save a question every time the onValueChanged occurs. 
However, when I am loading data into the survey, or refreshing the questions from my backend, the onValueChanged are being called. 

### What is the expected behavior?
I want a flag or a seperate method to watch so that I only call save when the user has updated a questions, and not when the question value was updated through props. 

### Specify your

* browser: Chrome on OSX
* browser version: Version 75.0.3770.142 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.1.1

**Comment by gologames** [comment]
Hello,

You can set the survey.data property in format `question_name: question_value`. Here is [live sample](https://plnkr.co/edit/7sFceQOHrlSKpCPqsJQM?p=preview) in plunker. In this case `onValueChanged` event not fired

Thanks, Alex
SurveyJS Team
