### ISSUE TITLE
How to insert the complete button on all pages?

### ISSUE THREAD

**Issue by alfredodelfabro** [surveyjs/survey-library#1783]
Hello, I would like to know how to insert the complete button on all survey pages so that the user can close the survey at any time. I know there is this option (https://www.surveyjs.io/Examples/Library/?id=trigger-complete&platform=jQuery), but I need to put a button.

Thank you in advance.

**Comment by gologames** [comment]
Hello

You may use `survey.doComplete()` method to complete the survey manually in any time as you want. Here is simple [live sample with complete button](https://plnkr.co/edit/QcRFhm1B84LK0YD2pPGa?p=preview) on every survey page. Also here is more complex example with [survey custom navigation](https://surveyjs.io/Examples/Library/?id=survey-customnavigation&platform=jQuery&theme=default#)

Thanks, Alex
SurveyJS Team
