### ISSUE TITLE
Add question/panel/page delete function

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#1785]
question.delete(), panel.delete() and page.delete() it is more obvious way to delete the element instead of writing 3 lines of code.

**Comment by miranaitamara** [comment]
Hello @andrewtelnov
And then I have an example on plunker especially for the function add question.

Best Regards

**Comment by andrewtelnov** [comment]
@miranaitamara Please look at [this documentation](https://surveyjs.io/Documentation/Library/#objects).

Thank you,
Andrew

**Comment by miranaitamara** [comment]
Hi @andrewtelnov 

And to edit the add question, can we do it without using the editor, for example here to edit the title of a question (https://jsfiddle.net/mpnatLeg/12/)
I need to edit the items for a radiogroup, checkbox ..., and add imagepicker..

Best Regards
Ryma

**Comment by andrewtelnov** [comment]
@miranaitamara Here is the [updated example](https://jsfiddle.net/Lk0amh5r/1/)
`toadd.choices = ["My Item 1", {value: 1, text: "My Item 2"}];`

Thank you,
Andrew
