### ISSUE TITLE
Question: Hide page for certain users

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#1786]
Hi there!

I wonder if there is a feature for hiding pages for certain users. I would like to have an admin first page and then more pages for a normal user to fill in. This first admin page has questions that questions on later pages are dependent on via visibleIf. I would like to hide the admin page for normal users and show the admin page for admin users. Is this already possible? It would need a call to a function to hide a page when initializing the survey in jQuery. I use Django, so I can have the user in the context of my template to decide whether to call the hide page function or not.

* browser: Firefox
* browser version: 68.0.1
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: v1.1.1

**Comment by tsv2013** [comment]
You can remove some pages from survey JSON or survey model before it will be shown.

E.g. `survey.pages.splice(1, 3);` as shown in this example - https://plnkr.co/edit/0PnfE0LgoVKPRlooQxC6?p=preview

Or you can return cut JSON from your server.

**Comment by Lionqueen94** [comment]
Thanks a lot for your answer! The splicing works well. I do have one more question, since the page numbers change when you splice pages (cut off the first page and all the page numbers change with it, is it possible to request the page ID or name instead of currentPageNo?

**Comment by tsv2013** [comment]
Unfortunately deleting pages in runtime is an untypical scenario for SurveyJS and you can implement it by index or by passing the page instance to the `survey.removePage` method.

**Comment by andrewtelnov** [comment]
@Lionqueen94 You may use the following code:
`survey.currentPage = survey.getPageByName("yourPageName");`

Thank you,
Andrew

**Comment by Lionqueen94** [comment]
Thanks again, I got it all working.
I do have another question, is it possible to add multiple errors to a single question? Using AddError on the question gives me an error in the console (ReferenceError: koHasHtml is not defined) and setting an Array of errors to options.errors[question] gives me an empty error section under the question. I can't for the life of me figure out how to show multiple errors aside from joining them together in one with spaces in between... (I cannot get a newline working either). Sorry if I sound very vague, please let me know what to be more clear on.
