### ISSUE TITLE
Breaking on compile Angular

### ISSUE THREAD

**Issue by martingenchev** [surveyjs/survey-library#1787]
### Are you requesting a feature, reporting a bug or asking a question?
I am having error when i want compile the angular project.  I am using version  "^1.0.52"

### What is the current behavior?
 
ERROR in node_modules/knockout/build/types/knockout.d.ts(17,21): error TS1005: ';' expected.
node_modules/knockout/build/types/knockout.d.ts(17,41): error TS1005: ';' expected.
node_modules/knockout/build/types/knockout.d.ts(17,44): error TS1109: Expression expected.

**Comment by dmitrykurmanov** [comment]
Hello! We have the example with Angilar and SurveyJS https://github.com/surveyjs/surveyjs_angular_cli
Could you please check it?
