### ISSUE TITLE
Markdown italics not working.

### ISSUE THREAD

**Issue by Chatzimina** [surveyjs/survey-library#1789]
Hello, I am trying to add italics in the title of a radiogroup. I have added 
```
      <script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.6.4/showdown.min.js"></script>
```
but nothing is happening in . I tried like this:   * this is italic*  and like this \_this is italics\_.

Thank you

* browser: Chrome, Firefox or internet explorer
* browser version: latest versions
* surveyjs platform (angular or react or jquery or knockout or vue): survey.jquery.js
* surveyjs version:1.0.73

**Comment by tsv2013** [comment]
You need to add a markdown converter as shown in this live example on our site - https://surveyjs.io/Examples/Library?id=survey-markdown-radiogroup&platform=jQuery&theme=default

**Comment by Chatzimina** [comment]
It worked!
 thank you
