### ISSUE TITLE
js minor coding error

### ISSUE THREAD

**Issue by dszryan** [surveyjs/survey-library#1791]
Survey.prototype.koEventAfterRender = function (element, survey) {
        survey.onRendered.fire(self, {});
        survey.afterRenderSurvey(element);
    };

should be...

    Survey.prototype.koEventAfterRender = function (element, survey) {
        survey.onRendered.fire(this, {});
        survey.afterRenderSurvey(element);
    };

(self is not known on the ko callback?)

**Comment by andrewtelnov** [comment]
@dszryan Yes, you are right. I have corrected the code.

Thank you,
Andrew

**Comment by dszryan** [comment]
thanks for the quick response - normally I usually submit a pull request - but just didn't have the time
