### ISSUE TITLE
VisibleIf notempty doesn't work when radiogroup value is 0 (v1.1.3)

### ISSUE THREAD

**Issue by rer145** [surveyjs/survey-library#1792]
Issue #1663 doesn't appear to be fixed ("VisibleIf notempty not triggered when value is 0"). 

Here is a link to a snippet for a radiogroup question that should show a comment box if something is selected.  When choosing "Not at all", which has a value of 0, the comment box does not appear.

https://plnkr.co/edit/sSfpf1VqWfZGm0fPklln?p=preview

**Comment by andrewtelnov** [comment]
@rer145 It was fixed, but we moved to completely another expression engine, from our own to [pegjs](https://pegjs.org/) and for some reason lost required unit tests or they were not enough.
I have added new unit tests and fix the issue.

Thank you,
Andrew

**Comment by rer145** [comment]
Thanks Andrew. I just tested v1.1.5 on my example and it works perfect. Thanks for the quick fix and response!
