### ISSUE TITLE
Question: How to check for isVisible property if a question is part of a dynamic panel?

### ISSUE THREAD

**Issue by ramalveyra** [surveyjs/survey-library#1793]
### Are you requesting a feature, reporting a bug or asking a question?

I'm currently tracking whether a question is hidden (visibleIf not triggered) or user didn't answer. This is easily covered by `isVisible` property however, this doesn't work if the question is part of a dynamic panel. Is there a way to check isVisible property if a question is part of a dynamic panel?

**Comment by andrewtelnov** [comment]
@ramalveyra There are two types of questions in dynamic panel. The template question that is not rendered and used as a template for creating questions in panels. The run-time, "actual', question that were created based on template. You may have several panels in dynamic panel and you their isVisible property maybe different, if the template question has visibleIf property set as: `{panel.anotherQuestionInAPanel} notempty`. 
So you have to check question isVisible property as: 
`dynamicPanelQuestion.panels[index].questionInPanel.isVisible`

Thank you,
Andrew

**Comment by ramalveyra** [comment]
Cool. This works perfectly! Cheers @andrewtelnov.
