### ISSUE TITLE
Has none Item with multiple columns ordering issue

### ISSUE THREAD

**Issue by stevaniestevanie** [surveyjs/survey-library#1794]
There was a 2 columns layout with checkboxes, the responsiveness working great but the `None of the above` question seems to be ordered wrongly. It would be great if we can resolve this issue quickly, thanks
![image](https://user-images.githubusercontent.com/45781436/62997300-5dd51f00-be9a-11e9-8e58-11ceebcb78f8.png)

**Comment by tsv2013** [comment]
I've checked the described issue in the current version, but have not managed to reproduce it. The `None` item is always the last one. Could you provide us with the steps to reproduce?

**Comment by andrewtelnov** [comment]
@stevaniestevanie I see the problem. Unfortunately I have no idea how to fix it at the current moment. We have two columns, two divs. "None of the above" goes into the first column 10 items, two columns by 5 items + "None of the above" that goes into the first column.
We use css rules to support responsilbility. As resut the second colum, the second div goes under the first one.
We will think about putting "None of the above" always into the last column.

Thank you,
Andrew

**Comment by JaneSjs** [comment]
The issue no longer occurs in the current SurveyJS Form Library version (v1.9.116).
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "checkbox",
     "name": "question1",
     "choices": [
      "Item 1",
      "Item 2",
      "Item 3",
      "Item 4",
      "Item 5",
      "Item 6"
     ],
     "showNoneItem": true,
     "colCount": 2
    }
   ]
  }
 ]
}
```
![image](https://github.com/surveyjs/survey-library/assets/22372972/385fa68e-eb4f-4249-a045-b4aa818bc0ae)
