### ISSUE TITLE
Convert the data to the surveyjs format

### ISSUE THREAD

**Issue by Khan-Uzair** [surveyjs/survey-library#1800]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
In case of dropdown/ checkbox/ radio, wherein I add FastEntry values I had to save the data in a modified format, so I modified as explained in the docs : https://surveyjs.io/Documentation/Library/#modifysurveyresults

Eg: {field1: [{text: 'item1', value: 'vv' }, {text: 'item2', 'werq'}] }  /// for checkbox
or {field1: {text: 'item1', value: 'someValue'} }  /// for checkbox
Since, data is saved in a different format now, on render dropdown/ checkbox/ radio do not work, because the expected format for them is different.

### What is the expected behavior?
I want the inverse of steps showed in https://surveyjs.io/Documentation/Library/#modifysurveyresults, so once I have the schema retrieved, I can render the form. Meaning to convert this 
{field1: [{text: 'item1', value: 'vv' }, {text: 'item2', 'werq'}] } ==> {field1: ['vv', 'werq'] } 

### How would you reproduce the current behavior (if this is a bug)?
Change the format of the data before storing for dropdown/ checkbox/ radio, and since the format is changed dropdown/ checkbox/ radio will not show the saved values when rendered.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here
Data modifications before saving on 'onComplete()'
  const dataKeys = Object.keys(this.model.data);
    dataKeys.forEach((key) => {
      const question = this.model.getQuestionByValueName(key);
      if (question) {
        if (question.getType() === 'dropdown' || question.getType() === 'radiogroup') {
          question.value = {
            text: question.displayValue,
            value: question.value,
          };
        }
        if (question.getType() === 'checkbox') {
          const checkboxKeys = question.displayValue.split(',');
          question.value = checkboxKeys.map((ele, index) => ({
            text: ele.trim(),
            value: question.value[index],
          }));
        }
      }
    });
```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
Do I understand you right that you want to assign some initial data to a survey? It is described in this sample on our site - https://surveyjs.io/Examples/Library/?id=survey-data&platform=jQuery&theme=default
_Note: The checkbox named `car` is shown in this sample_
