### ISSUE TITLE
 Chinese title export pdf is not work

### ISSUE THREAD

**Issue by YuanZhencai** [surveyjs/survey-library#1803]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?
survey json

```json
{
 "title": "评估行 PCI 治疗的中国急性冠脉综合征患者出血风险的非干预性临床研究",
 "pages": [
  {
   "name": "基本信息",
   "elements": [
    {
     "type": "radiogroup",
     "name": "本次随访方式",
     "choices": [
      "门诊随访",
      "电话随访"
     ]
    },
    {
     "type": "panel",
     "name": "体格检查",
     "elements": [
      {
       "type": "radiogroup",
       "name": "是否检查",
       "title": "是否检查",
       "choices": [
        "检查",
        "未查"
       ]
      }
     ],
     "title": "体格检查"
    }
   ],
   "title": "基本信息"
  },
  {
   "name": "实验室检查",
   "elements": [
    {
     "type": "panel",
     "name": "血常规",
     "elements": [
      {
       "type": "text",
       "name": "采样时间",
       "title": "采样时间"
      }
     ],
     "title": "血常规"
    }
   ],
   "title": "实验室检查"
  }
 ]
}
```

pdf 

![image](https://user-images.githubusercontent.com/4961592/63827595-4e73cc80-c996-11e9-9dfd-4a682549e5b2.png)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by gologames** [comment]
Hello Yuan,

To support custom fonts in SurveyPDF (some Chinese font, for example) you need to pass base64 encoded .ttf font to SurveyPDF options. Here is [live sample](https://plnkr.co/edit/A83vsFYg5I8KF5YW9tB9?p=preview) in plunker with Japanese Hiragana (without Kanji). Unfortunately, Chinese fonts have about ~10MB size and we don't able to show online example with it.  You may use [this tool](https://rawgit.com/MrRio/jsPDF/master/fontconverter/fontconverter.html) to convert any .ttf font to base64. We will create an example on our surveyjs.io site in SurveyPDF examples section with more details

Thanks, Alex
SurveyJS Team
