### ISSUE TITLE
Add sums in matrix when using input masks

### ISSUE THREAD

**Issue by als753** [surveyjs/survey-library#1805]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Currently the matrix can only sum currency by concatenating strings, not by actual numeric sums. 
This is with using the currency input mask. 

### What is the expected behavior?
I would expect that the currency can be summed into a currency at the bottom of the matrix

### How would you reproduce the current behavior (if this is a bug)?
https://embed.plnkr.co/plunk/8amEgbsRhsk8bXxA

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:Chrome on OSX
* browser version:Version 75.0.3770.142 (Official Build) (64-bit)
* surveyjs platform : React
* surveyjs version: 1.1.7

**Comment by gologames** [comment]
Hello,

Indeed is our code architecture mistake. We are fixed it via [this commit](https://github.com/surveyjs/survey-library/commit/b459615834c39e656bdcff1563800fbefc90f0cf). As a workaround you may paste code below on the very top of js file of your plunker example and set `totalType` to `sumnum` in survey JSON

```javascript
function getInArrayParams(params) {
  if (params.length != 2) return null;
  var arr = params[0];
  if (!arr) return null;
  if (!Array.isArray(arr) && !Array.isArray(Object.keys(arr))) return null;
  var name = params[1];
  if (typeof name !== "string" && !(name instanceof String)) return null;
  return { data: arr, name: name };
}

function calcInArray(
  params,
  func
) {
  var v = getInArrayParams(params);
  if (!v) return undefined;
  var res = undefined;
  if (Array.isArray(v.data)) {
    for (var i = 0; i < v.data.length; i++) {
      var item = v.data[i];
      if (!!item && item[v.name]) {
        res = func(res, item[v.name]);
      }
    }
  } else {
    for (var key in v.data) {
      var item = v.data[key];
      if (!!item && item[v.name]) {
        res = func(res, item[v.name]);
      }
    }
  }
  return res;
}

function sumnum(params) {
  var res = calcInArray(params, function(res, val) {
    if (res == undefined) res = 0;
    return +res + +val;
  });
  return res !== undefined ? res : 0;
}
Survey
    .FunctionFactory
    .Instance
    .register("sumnumInArray", sumnum);
```
Thanks, Alex
SurveyJS Team

**Comment by als753** [comment]
Thank you so much!!!!
