### ISSUE TITLE
SumInArray with Checkbox

### ISSUE THREAD

**Issue by neilhosey** [surveyjs/survey-library#1808]
**Are you requesting a feature, reporting a bug or asking a question?**
I have what I think might be a bug, but actually hoping i am doing something wrong instead :)

**What is the current behavior?**
Currently the matrix can only sum currency by concatenating strings, not by actual numeric sums.

For question1, I have a checkbox with 6 items, each has a value of 0, 1 or 2.. so below is the tablet of values for each checkbox item:

0 item1
1 item2
1.0 item3 (I cant use 1 for all checkbox values as it checks all of them when i click any one of the 1s)
1.00 item4 
1.000 item5
2 item6

Then I have an expression, where I want to sum the values of all items selected in question1... so i set the expression to this:

sumInArray({question1})
this does not seem to work, either does:
sum({question1})

both just stay blank.  
EDIT:  i also tried this: sumInArray({question1}, 'choices')  .

**What is the expected behavior?**
I would expect it to return the sum of the values of the items selected in the checkbox.
How would you reproduce the current behavior (if this is a bug)?

**Specify your**
browser:Chrome on Windows
browser version:Version 76
surveyjs platform : React
surveyjs version: 1.1.7

**Comment by andrewtelnov** [comment]
@neilhosey To my surprice we do not handle the simple array correctly in sum function. I have added a unit test and fix the issue.
`sum({question1})` will work from the next minor v1.1.8. Commonly we release every Tuesday.
You may build the library from source. The instruction is in readme file of this repo.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@neilhosey As workaround you may register your own custom function: "mysum". Here is [the example](https://plnkr.co/edit/eiMulEweajweuSmYg0Iq?p=preview).

Thank you,
Andrew

**Comment by neilhosey** [comment]
Thanks guys!!

Also did you notice the other bug, where if you have the same value for multiple items on a checkbox, when you select one, it selects all with the same value?

**Comment by andrewtelnov** [comment]
@neilhosey item.value should be unique. Based on this value we can find out if the value is selected or not. It is the basic functionality of the html checkbox. If item.value is not unique then it works in the value your have described by design.
[Here is the solution for your task](https://plnkr.co/edit/AvKnIiEjL5hS8KGezDBb?p=preview).
You need to add a custom property into itemvalue object and then create your own custom function as in this example.

Thank you,
Andrew

**Comment by neilhosey** [comment]
Again, thank you Andrew!!

**Comment by CodeCurosity** [comment]
this still doesn't work in 2023?
