### ISSUE TITLE
special characters, > * and #, rendering issue

### ISSUE THREAD

**Issue by HypertinIsBehindYou** [surveyjs/survey-library#1813]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

special characters, > * # is rendering weird format for question title, and survey title 

### What is the expected behavior?

It should be rendering as it 

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/CoIPCWN5zCZyWlIyFiav?p=preview

In the live example, 
1. on the right, drag a single input question type into the box 
2. on the question title, change it to start with special characters 
  2.1  # hash tag became  id="hashtag">hash tag<
  2.2. * star became > list item star < 
  2.3.  >close bracket became ockquote>>close bracket

### Specify your 

* browser: chrome
* browser version:  76.0.3809.132 
* surveyjs platform (angular or react or jquery or knockout or vue): as shown in the https://plnkr.co/edit/CoIPCWN5zCZyWlIyFiav?p=preview
* surveyjs version: 1.1.3

**Comment by andrewtelnov** [comment]
@HypertinIsBehindYou Answering [here](https://surveyjs.answerdesk.io/ticket/details/T2614).

Thank you,
Andrew
