### ISSUE TITLE
Error when adding   import * as SurveyAnalytics from 'survey-analytics';

### ISSUE THREAD

**Issue by aelhadi** [surveyjs/survey-library#1815]
I only add import * as SurveyAnalytics from 'survey-analytics'; to my component in a Angular project.

npm start

#Error

ERROR in node_modules/survey-analytics/survey.analytics.d.ts:9:10 - error TS2300: Duplicate identifier 'Question'.

9 import { Question } from "survey-core";
           ~~~~~~~~
node_modules/survey-analytics/survey.analytics.d.ts:11:8 - error TS1192: Module '"/home/MyProject/node_modules/@types/chart.js/index"' has no default export.

11 import Chart from "chart.js";
          ~~~~~
node_modules/survey-analytics/survey.analytics.d.ts:12:10 - error TS2300: Duplicate identifier 'Question'.

12 import { Question, ItemValue } from "survey-core";
            ~~~~~~~~
node_modules/survey-analytics/survey.analytics.d.ts:94:35 - error TS2702: 'DataTables' only refers to a type, but is being used as a namespace here.

94     buttons: boolean | string[] | DataTables.ButtonsSettings | DataTables.ButtonSettings[];
                                     ~~~~~~~~~~
node_modules/survey-analytics/survey.analytics.d.ts:94:64 - error TS2702: 'DataTables' only refers to a type, but is being used as a namespace here.

94     buttons: boolean | string[] | DataTables.ButtonsSettings | DataTables.ButtonSettings[];
                                                                  ~~~~~~~~~~
node_modules/survey-analytics/survey.analytics.d.ts:97:25 - error TS2702: 'DataTables' only refers to a type, but is being used as a namespace here.

97     rowGroup: boolean | DataTables.RowGroupSettings;
                           ~~~~~~~~~~
node_modules/survey-analytics/survey.analytics.d.ts:98:21 - error TS2702: 'DataTables' only refers to a type, but is being used as a namespace here.

98     headerCallback: DataTables.FunctionHeaderCallback;
                       ~~~~~~~~~~
node_modules/survey-analytics/survey.analytics.d.ts:104:40 - error TS2702: 'DataTables' only refers to a type, but is being used as a namespace here.

104     createSelectButton: (datatableApi: DataTables.Api, colIdx: number, columnName: string) => HTMLButtonElement;
                                           ~~~~~~~~~~
node_modules/survey-analytics/survey.analytics.d.ts:105:42 - error TS2702: 'DataTables' only refers to a type, but is being used as a namespace here.

105     createGroupingButton: (datatableApi: DataTables.Api, columnName: string) => HTMLButtonElement

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):Angular
* surveyjs version:1.1.8

**Comment by aelhadi** [comment]
Any solution?

**Comment by dmitrykurmanov** [comment]
Hello! I am beginning to investigate it.

**Comment by dmitrykurmanov** [comment]
Hello! Could you please check our angular example. It looks ok for me. Maybe the problem in the tsconfig.json. 

Here the repo: [https://github.com/surveyjs/surveyjs_angular_cli](https://github.com/surveyjs/surveyjs_angular_cli)

and the component: [https://github.com/surveyjs/surveyjs_angular_cli/blob/master/src/app/survey.analytics.component.ts](https://github.com/surveyjs/surveyjs_angular_cli/blob/master/src/app/survey.analytics.component.ts)


And also you could provide a sample to reproduce the problem and we'll check it.

**Comment by aelhadi** [comment]
Error is occured when using :+1: 

{
    "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": "./src",
        "outDir": "./dist/out-tsc",
        "sourceMap": true,
        "declaration": false,
        "downlevelIteration": true,
        "experimentalDecorators": true,
        "module": "esnext", // es2015
        "moduleResolution": "node",
        "importHelpers": true,
        "target": "es2015", // es5
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2018", // es2016
            "dom"
        ],
        "paths": {
            "@fuse": [
                "@fuse/"
            ]
        }
    },
    "angularCompilerOptions": {
        "fullTemplateTypeCheck": false,
        "strictInjectionParameters": false
    }
}

tsconfig.json

**Comment by aelhadi** [comment]
No Error with v 1.1.9
