### ISSUE TITLE
disable alert when restful dropdown returns empty set

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1816]
### Are you requesting a feature, reporting a bug or asking a question?

question

when my restful dropdown returns an empty set I see this alert:

![image](https://user-images.githubusercontent.com/454321/64352773-e314a500-cffc-11e9-9c0b-860aa539f572.png)

Is there a way to disable it?

thanks

**Comment by andrewtelnov** [comment]
@masciugo You may hide the question if the choices are empty by using **hideIfChoicesEmpty** property.

Thank you,
Andrew

**Comment by masciugo** [comment]
thank you andrew

It seems not working in matrixdynamic

https://plnkr.co/edit/TFhVfwVezDdD7EzugNuB?p=preview

**Comment by andrewtelnov** [comment]
@masciugo You need to add this line:
`Survey.matrixDropdownColumnTypes.dropdown.properties.push("hideIfChoicesEmpty");`
to add this property into column and bind it with question in cells.
[Here](https://plnkr.co/edit/2MhtM0vJHxCrCzAoZFxz?p=preview) is the updated example.

Thank you,
Andrew

**Comment by masciugo** [comment]
Ok but that hides the dropdown not the alert. I updated [my plunk](https://plnkr.co/edit/TFhVfwVezDdD7EzugNuB?p=preview) to show that when the request return an empty list the alert is still visible with hideIfChoicesEmpty set. More over I am not sure that en empty list as response should be raise an alert but that's my personal opinion related to my usage

**Comment by andrewtelnov** [comment]
@masciugo It doesn't work correctly for react and vue. I have fixed the rendering.

Thank you,
Andrew
