### ISSUE TITLE
keyName property in dynamic panel is not working

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1820]
### Are you requesting a feature, reporting a bug or asking a question?

bug (maybe)

### What is the current behavior?

it lets me submit same key question in different panels

https://plnkr.co/edit/4g5OZSFnv14ldVZHhrdk?p=preview

**Comment by andrewtelnov** [comment]
@masciugo Yes, it is fine. You may name valueName as non-unuque. The idea of introducing valueName property is the ability to have the same valueName for several questions, while keep their names are unique.

Thank you,
Andrew

**Comment by masciugo** [comment]
I borrowed that example (born to show the usage of valueName prop) just for convenience. In fact I edited it and I don't use valueName in it, I am interested in the usage of **keyName** property in order not to have duplicate panels. In my plunk you can select _father_ twice as relativeType without  getting any error.

**Comment by andrewtelnov** [comment]
@masciugo I did not get you from the beginning. keyName doesn't work indeed here. I will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@masciugo I have fixed the issue.
