### ISSUE TITLE
valueChanging emit while user interacting with element?

### ISSUE THREAD

**Issue by wollerman** [surveyjs/survey-library#1822]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

Is there some way to subscribe to user inputs while they're typing? Specifically, when using angular forms it's possible to do something like:

```
this.myControl.valueChanges.subscribe(x => console.log(x));
```

I was expecting `valueChanging` to act this way, but it seems that `valueChanging` only fires after user focus leaves the element. 

e.g. typing in a textbox and then clicking away fires `valueChanging`, but while the user is typing it does not fire.

### What is the expected behavior?

`valueChanging` emits while user is still interacting with element just like `valueChanges` when subscribing to an Angular FormControl. Or some way to receive values before the user navigates away from an element.

### Specify your

* browser: Chrome
* browser version:  76.0.3809.100
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: `"survey-angular": "1.1.7",`

**Comment by andrewtelnov** [comment]
@wollerman Unfortunately we do not have it out of the box. You may use onAfterRenderQuestion event and set the event for html input of course.
Why do you need this functionality?

Thank you,
Andrew

**Comment by wollerman** [comment]
@andrewtelnov we were looking at managing surveys that have long text areas and wanted to provide incremental auto-saves. 

And that makes sense, I will look into using the onAfterRenderQuestion to attach my own event handlers. Thanks!
