### ISSUE TITLE
List of all build in expression

### ISSUE THREAD

**Issue by benirose** [surveyjs/survey-library#1823]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

Is there a list of all available expressions for use in expression questions and display logic? Even if there's a file or two in the source code I can look at it would be helpful.

**Comment by andrewtelnov** [comment]
@benirose We do not have this functionality in Survey Library. However, we do have it in Survey Creator. You may get the list of expressions via code or if you need to list them, go to our [survey creator page](https://surveyjs.io/create-survey/), insert your JSON into JSON editor and then go to "Logic Tab".
In code you may get it as: `creator.logic.items`

Thank you,
Andrew
