### ISSUE TITLE
panel folding icon disappeared after upgrading to 1.1.10 

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1825]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

After upgrading to 1.1.10 I cannot see the panel folding icon on the right of the title and the also the font seems messed up

### How would you reproduce the current behavior (if this is a bug)?

change the the version from 1.1.8 to 1.1.10 and vice-versa to see the difference

https://plnkr.co/edit/J9stHRp0BXCqZZKmyFAA?p=preview

**Comment by andrewtelnov** [comment]
@masciugo Yes, I can see the issue. We will work on the fix.

Thank you,
Andrew
