### ISSUE TITLE
onMatrixCellValidate missing .getCellQuestion(columnName) function

### ISSUE THREAD

**Issue by dmcc0987** [surveyjs/survey-library#1826]
### Are you requesting a feature, reporting a bug or asking a question?
This is a bug.

### What is the current behavior?
When utilizing the onMatrixCellValidate function, the documentation states that we should have access to the options.getCellQuestion(columnName) function (much like we do when using 'onMatrixCellValueChanged'.  It's currently unavailable (as of 1.1.8 and 1.1.11).

### What is the expected behavior?
We should have access to this function.

### How would you reproduce the current behavior (if this is a bug)?
Utilize the onMatrixCellValidate function, and attempt to use options.getCellQuestion(columnName).

#### Provide the test code and the tested page URL (if applicable)
My code:

```
survey.onMatrixCellValidate.add(function (survey, options) {
// This should get the question for the cell:
var cq = options.getCellQuestion(options.columnName);
});
```

### Specify your
* browser: Chrome
* browser version: 77
* surveyjs platform jQuery
* surveyjs version: 1.1.11

**Comment by tsv2013** [comment]
I've added this method. The functionality will be available in the nearest update. most likely tomorrow.

**Comment by dmcc0987** [comment]
Thank you!  Looking forward to it.  Take care!
