### ISSUE TITLE
Surveys Results in admin page 

### ISSUE THREAD

**Issue by ManuchekhrT** [surveyjs/survey-library#1827]
Why when I use survey-js in vuejs2, i can't see results in admin page ?

**Comment by tsv2013** [comment]
Sorry but I don't understand - what do you mean under the SurveyJS admin page for VueJS 2.0. Our repos don't contain such a code.

Could you provide a minimal sample with exact steps to reproduce the issue on our side?

**Comment by ManuchekhrT** [comment]
I meant I use survey in vuejs web app, i can;t follow statistics in admin page of the surveyjs.io, like how many people answered certain question and etc

**Comment by tsv2013** [comment]
Have you set the https://surveyjs.io/Documentation/Library/?id=surveymodel#surveyPostId property as shown in this example - https://surveyjs.io/Examples/Library/?id=service-send&platform=jQuery&theme=default ?
