### ISSUE TITLE
Store survey.js checkbox text in Survey JSON result alongside the value selected.

### ISSUE THREAD

**Issue by neilhosey** [surveyjs/survey-library#1829]
### Are you requesting a feature, reporting a bug or asking a question?
Question or a Feature (not sure)

### What is the current behavior?
Checkbox item "value" is stored in survey json result.  ie item1

### What is the expected behavior?
Want both item "value" and "text" stored in survey json result.  ie {value: "item1", text: " Sample Text"}

**Comment by andrewtelnov** [comment]
@neilhosey You can use [survey.getPlainData()](https://surveyjs.io/Documentation/Library/?id=surveymodel#getPlainData) function It does what you need.

Thank you,
Andrew
