### ISSUE TITLE
Possibility to add validators only for IE11

### ISSUE THREAD

**Issue by zenithA** [surveyjs/survey-library#1831]
Is there any way to add a custom validator in the Json that should be considered only for IE11 but not for the other browsers?

I intent to add a custom validation on date on IE, that (I am not sure about the reason why this happens, as the validator works correctly) seems to be incompatible with Chrome.
The fastest fix for that seems to be to run the validator only on IE11, not on chrome also

eg: 
`{ 
 "title": "Dato",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "date",
     "title": "Date :",
     "validators": [
      {
       "type": "regex",
       "text": "Date should be in format: mm/dd/yyyy",
       "regex": "^(0[2-9]|1[0-2])/(0[1-9]|1[0-9]|2[0-9]|3[01])/(([1]{1}[9]{1}[9]{1}[0-9]{1})|([2-9]{1}[0-9]{3}))$"
      }
     ],
     "inputType": "date"
    }
   ]
  }
 ]
}`

**Comment by tsv2013** [comment]
Sorry for the late response.
You can create a custom validator as shown in this example - https://surveyjs.io/Examples/Library/?id=validators-custom&platform=Angular2&theme=default

**Comment by andrewtelnov** [comment]
@zenithA @tsv2013 We have now an expression validator. Here is [the example](https://surveyjs.io/Examples/Library/?id=validators-expression). You may register a custom function, where you can run your regular expression for IE only. Here is [the example](https://surveyjs.io/Documentation/Library/?id=LibraryOverview#visibility-functions) of adding a custom funciton.

Thank you,
Andrew
