### ISSUE TITLE
component survey is already registered

### ISSUE THREAD

**Issue by dannissim** [surveyjs/survey-library#1833]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug.

### What is the current behavior?
I am trying to use the react quickstart boilerplate code, but to build survey-creator and survey-library from source. What I have done is forked the two repos, I haven't changed them, and I haven't changed the quickstart code either, I just added a prepare script in each package.json which runs the build scripts.
So in the quickstart package.json dependencies instead of depending on the prebuilt code, it depends on the forked repos.
When I do this with survey creator everything works as usual. However when I do it with survey library as well, I receive: "Error: Component survey is already registered". I have been stuck trying to fix this for a couple of days now, what is the fix?
Thanks alot.
Dan

![Screenshot from 2019-09-18 15-08-19](https://user-images.githubusercontent.com/28741558/65147150-32f46280-da26-11e9-8118-09509bb745d2.png)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: latest

**Comment by tsv2013** [comment]
You've loaded survey-knockout on a web page twice

**Comment by e-hop** [comment]
Happening on react's example
[Link](https://codesandbox.io/s/hj6i4?file=/src/SurveyCreatorComponent.jsx)

**Comment by dmitrykurmanov** [comment]
Hello,

I've opened the link and didn't see such an error message in the developer console or somewhere else. It looks ok to me. Could you please specify your problems in greater detail?

Thanks,
Dmitry
SurveyJS Team
