### ISSUE TITLE
[feature request] auto scroll when user take the survey?

### ISSUE THREAD

**Issue by swuecho** [surveyjs/survey-library#1836]
### Are you requesting a feature, reporting a bug or asking a question?

feature request

### What is the current behavior?

no auto scroll at all.

### What is the expected behavior?

auto scroll, i.e move the next question to center of view when current question is done.

I have the code below, which works fine when there is only one page. 

However, if there are multiple page in the survey. when click 'next page', it will jump right into the center of next page instead of the top. Probably, I could twist my code to make it work. 
Is it possible for surveyjs to support this feature directly?

```
     var current_input_name = "";
     $(':input').focus(function () {
         var name = $(this).attr('name')
         // only scroll when input name changed, i.e question chanaged
         if (current_input_name != name) {
             var center = $(window).height() / 2;
             var top = $(this).offset().top;
             var amount = top - center;
             if (amount > 10) {
                 $('html, body').animate({ scrollTop: amount}, 'fast');
             }
             current_input_name = name;
         }
     });
```

**Comment by tsv2013** [comment]
Thank you for the feedback. We'll take it in account if the suggestion will be requested by community.

**Comment by swuecho** [comment]
Thanks!
