### ISSUE TITLE
OnValueChanged Does not fire when expected for text inputs

### ISSUE THREAD

**Issue by tonikaplan-pear** [surveyjs/survey-library#1838]
The functionality/call time of onValueChanged is ambiguous based on the [docs](https://surveyjs.io/Documentation/Library/?id=SurveyModel#onValueChanged).

### Are you requesting a feature, reporting a bug or asking a question?
Asking a question, requesting a feature if it is not implemented.

### What is the current behavior?
When using a text input, onValueChanged is called when you click outside of the text input, not when the value inside of the textInput is actually changed (e.g. the moment a new letter is typed). You can see this happening [here](https://plnkr.co/edit/ZNJ6TfOvHxLsquIXfmpY?p=preview) but not [here](https://plnkr.co/edit/rG2sMXQsMwD61eDxj5wr?p=preview) so I'm not sure what the intended functionality is suppposed to be.

### What is the expected behavior?
onValueChanged should be called when the value inside the text input is changed, similar to the html input event: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event

Questions:
- Is this the intended functionality? 
- If so, is there another function / setting that I can configure to do something like this? (**I am trying to enable the "Next" button as soon as the user has valid input, even before they click outside of the text field**)
- If not, I can give more information about my setup to help pinpoint the bug.

**Comment by tsv2013** [comment]
As said in our documentation (mentioned above)

> The event is fired when the question value is changed. It can be done via UI by a user or programmatically on calling setValue method.

Set value method for text fields are called in SurveyJS then input control lost focus.

**Comment by andrewtelnov** [comment]
It can be done by using this code ``survey.textUpdateMode = "onTyping";`` with the latest versions.

Thank you,
Andrew

**Comment by fefefefta** [comment]
'survey.textUpdateMode = "onTyping";' is not working in case of using input type=range.
