### ISSUE TITLE
Changing dropdown value in forms causes old values to appear in the response (React)

### ISSUE THREAD

**Issue by andreqko69** [surveyjs/survey-library#1840]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
After playing with options I chose the following items: { Field1: "item1", Field2: "item1" }
Response data is: {Field1: "item1", Field2: "item1", Field4: "item3"}
### What is the expected behavior?
After playing with options I chose the following items: { Field1: "item1", Field2: "item1" }
Response data is: { Field1: "item1", Field2: "item1" }

### How would you reproduce the current behavior (if this is a bug)?
Play with options from different dropdowns. Then submit the form.
1) Select Item1 from Field1
2) Select Item1 from Item1Choice
3) Change Field1 to Item2
4) Select Item2 from Item2Choice
5) Submit

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
`const params = {
  pages: [
    {
      name: 'page1',
      elements: [
        {
          type: 'dropdown',
          name: 'Field1',
          choices: ['item1', 'item2', 'item3'],
        },
        {
          type: 'dropdown',
          name: 'Field2',
          visible: false,
          visibleIf: '{Field1} = "item1"',
          title: 'Item1 Choice',
          isRequired: true,
          choices: ['item1', 'item2', 'item3'],
          customField: true,
        },
        {
          type: 'dropdown',
          name: 'Field3',
          visibleIf: '{Field1} = "item2"',
          title: 'Item2 Choice',
          enableIf: '{Field1} = "item2"',
          choices: ['item1', 'item2', 'item3'],
          customField: true,
        },
        {
          type: 'dropdown',
          name: 'Field4',
          visible: false,
          visibleIf: '{Field1} = "item3"',
          enableIf: '{Field1} = "item3"',
          choices: ['item1', 'item2', 'item3'],
          customField: true,     
        },
      ],
    },
  ],
};`

```

### Specify your

* browser: Chrome
* browser version: Version 77.0.3865.90 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.0.91

**Comment by andrewtelnov** [comment]
@stepanov-apiko I just tried it with the latest version and could not find an issue. Here is [the example](https://next.plnkr.co/edit/ZsYWGxzCMlUaDOwb).

Thank you,
Andrew
