### ISSUE TITLE
matrixdynamic does not fire onValueChanged callback on adding new row when column of type expression changes

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1845]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

https://plnkr.co/edit/XTdwGL4LmeQTz9f1ARZM?p=preview

onValueChanged callback is not called when you simply add a row which is actually not empty because the expression is calculated and its result showed

### What is the expected behavior?

catch the survey data changed event

**Comment by andrewtelnov** [comment]
@masciugo I have fixed the bug. We are going to release v1.1.14 tomorrow. The fix will be there.

Thank you,
Andrew
