### ISSUE TITLE
Update survey-react to prevent deprecation warnings

### ISSUE THREAD

**Issue by xxxKOTxxx** [surveyjs/survey-library#1846]
### Are you requesting a feature, reporting a bug or asking a question?
reporting a bug

### What is the current behavior?
Multiple console deprecation warnings

### What is the expected behavior?
No warnings in console

### How would you reproduce the current behavior (if this is a bug)?
Use with React at least v16.8.6 and open console

### Specify your

* browser: Chrome
* browser version: Version 77.0.3865.90 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: "survey-react": "^1.0.96",

**Comment by andrewtelnov** [comment]
@xxxKOTxxx We used componentWillMount and componentWillReceiveProps. I have refactored code so we no longer use it, so it works for v15+.
@tsv2013 We need more functional tests on react. I have found couple bugs after my changes, however functional tests ran successfull.

Thank you,
Andrew

**Comment by xxxKOTxxx** [comment]
Thank You for fast fix! 
I updated project to:

>  "survey-react": "^1.1.13",

and still get

> Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> Please update the following components: Survey
Please update the following components: SurveyPage, SurveyPanel, SurveyQuestion, SurveyRow


> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> Please update the following components: Survey
Please update the following components: SurveyElementErrors, SurveyLocString, SurveyNavigation, SurveyPage, SurveyPanel, SurveyProgress, SurveyQuestion, SurveyQuestionFile, SurveyQuestionHtml, SurveyRow

I'm sorry but looks like this fixes is not enough

**Comment by andrewtelnov** [comment]
@xxxKOTxxx The fix will be available in v1.1.14. We are going to release it today.

Thank you,
Andrew

**Comment by xxxKOTxxx** [comment]
Oh, sorry!
I'll wait for release!
Thank You!

**Comment by xxxKOTxxx** [comment]
Ok, no warnings in console.
But "There is no visible page or question in the survey." in all surveys.
Possibly need to update my code...

**Comment by andolojm** [comment]
Testing with versions v1.1.26 and v1.5.3, I am seeing a few similar errors (With react and react-dom v16.12.0). The following is an example.

> react-dom.development.js:12357 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: SurveyQuestionText

browser: Chrome
browser version: Version 79.0.3945.130 (Official Build) (64-bit)
surveyjs platform (angular or react or jquery or knockout or vue): react
surveyjs version: Survey-React v1.1.26, v1.5.3

------

Would this line be the culprit?
https://github.com/surveyjs/survey-library/blob/6e1caa5a0f09aa1653090c3ced195c092b2eabce/src/react/reactquestionelement.tsx#L151

**Comment by tsv2013** [comment]
@andolojm Thank you for the report. I've fixed the issue but this causes some scenarios work with react >16.5.0.

**Comment by andolojm** [comment]
Looks like version 1.5.4 removes the warning. Thanks for the quick response!
