### ISSUE TITLE
Has erros for dynamic panel issue

### ISSUE THREAD

**Issue by dk981234** [surveyjs/survey-library#1847]
hasErrors for dynamic panel returns true, but it doesn't have errors, when it is called from checkIsCurrentPageHasErrors
  var json = {
    questions: [
      {
        name: "name",
        type: "text",
        isRequired: true
      },
      {
        type: "paneldynamic",
        name: "relatives",
        templateElements: [
          {
            name: "relativeType",
            type: "dropdown",
            choices: [
              "father",
            ],
            isRequired: true
          }
        ],
        panelCount: 1
      }
    ]
  };

**Comment by andrewtelnov** [comment]
@dk981234 @dmitrykurmanov To fix the issue, I have added containsError property. It is observalbe for knockout and reactive for react.
Please use it to find out if the question/panel/page or their chidren have errors or not.

Thank you,
Andrew
