### ISSUE TITLE
Expand/collapse panels on button click

### ISSUE THREAD

**Issue by tharun777** [surveyjs/survey-library#1848]
I want a custom button where I can expand and collapse panels in Survey

### What is the expected behavior?
On click of custom button panels should be expand or collapse

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@tharun777 panel has [collapse](https://surveyjs.io/Documentation/Library/?id=panelmodel#collapse) and [expand](https://surveyjs.io/Documentation/Library/?id=panelmodel#collapse) functions. You may find [isExpanded](https://surveyjs.io/Documentation/Library/?id=panelmodel#isExpanded) function is usefull as well.

Thank you,
Andrew
