### ISSUE TITLE
onUpdatePanelCssClasses not applying classes for React

### ISSUE THREAD

**Issue by ChuckByram** [surveyjs/survey-library#1850]
### Are you requesting a feature, reporting a bug or asking a question? 
Bug

### What is the current behavior?
When handling the onUpdatePanelCssClasses event for React Survey.Survey component, version 1.1.13, the css classes are not getting applied to the rendered panel. Note that when handling onUpdateQuestionCssClasses, the question version succeeds.

### What is the expected behavior?
The css classes added in onUpdatePanelCssClasses (options.cssClasses.panel.container, for example) should be applied to the rendered element.

### How would you reproduce the current behavior (if this is a bug)?
Create a React component that uses the Survey.Survey component, handle the onUpdatePanelCssClasses event, and add a classname to the panel.

Please see this plunker: https://plnkr.co/edit/QU3Tm1jP3AZHZ2iGCIED?p=preview
The panel should have a blue border and 2px padding (it doesn't) and the question should have red border and 2px padding (it does).

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://plnkr.co/edit/QU3Tm1jP3AZHZ2iGCIED?p=preview

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version: 77.0.3865.90 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.1.13

**Comment by marvoh** [comment]
I have this bug on the jquery version, object updates but class not applied resulting html

**Comment by gologames** [comment]
Hello, @marvoh could you, please, share us a live sample with the issue?

Thanks, Alex
SurveyJS Team

**Comment by marvoh** [comment]
Here you go: http://plnkr.co/edit/zfdkQnYoC7yiTRZx

**Comment by marvoh** [comment]
My bad, the intention was to change the panel.cssClasses.row class of the panel's row and not those of the panel's children. How can I achieve this?

**Comment by marvoh** [comment]
My bad, my intention was to change the class of the parent survey and not children as is the case. Apologies for false alarm

**Comment by marvoh** [comment]
Okay, it's still a bug. Let me open a new issue

**Comment by gologames** [comment]
Hello @marvoh,

Thank for link provided, we will investigate it and write back to this thread

Thanks, Alex

**Comment by gologames** [comment]
Hello,

We checked your live sample. All works fine as you can see on screenshot below. Here is [updated live sample](http://plnkr.co/edit/51DZ6Civ1kpBoL4N)

![image](https://user-images.githubusercontent.com/30930391/112987503-78413680-916b-11eb-87b8-cdfca71e559c.png)


Thanks, Alex
SurveyJS Team
