### ISSUE TITLE
How to get current index of panel based on question

### ISSUE THREAD

**Issue by ramalveyra** [surveyjs/survey-library#1851]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question.

I am using a dynamic panel where questions uses a custom widget to display a "question already answered" component whenever the user revisits the survey.

If there are three dynamic panels with a text question for example and the user only answered the first, I want the first question to render the answered custom widget.

Currently I am using the `isFit` callback but is there a way to get the index of the panel for the current question?
Ie:
```
isFit: (question) => {
if (question.parent && question.parent.getType() === 'panel') {
// If this question in Panel 1 was already answered, display "answered" widget
// else this question in Panel 2 was not yet answered so display the default component
...
}
```

**Comment by tsv2013** [comment]
If you want to know whether the question has been answered or not, you can check  the [isEmpty](https://surveyjs.io/Documentation/Library/?id=questiondropdownmodel#isEmpty) method of a question.

**Comment by ramalveyra** [comment]
The check actually happens on survey load where the service returns a list of question names that has been answered (but not actual answers) and the panel index. So to check whether to render a  custom widget, it has to compare it to this data and not answer ie: `isFit: question => question.name === fromApi.questionName && currentIndexOfPanelForQuestion === fromApi.panelIndex`
