### ISSUE TITLE
Strings with 0x in it won't work with as custom validation params

### ISSUE THREAD

**Issue by MarissaHudson** [surveyjs/survey-library#1852]
### Are you requesting a feature, reporting a bug or asking a question?

reporting a bug

### What is the current behavior?

You create a survey with an input and custom validator for that input. 
You put in a string with 0x in the survey input (for example an ethereum address). 
The paramater that goes into the custom validator is not what was in the input. It appears as if it is put in hexadecimal form.

### What is the expected behavior?

You create a survey with an input and custom validator for that input. 
You put in a string with 0x in the survey input (for example an ethereum address). 
The paramater that goes into the custom validator should be exactly what was typed in the input. 

### How would you reproduce the current behavior (if this is a bug)?

Create a new survey with a custom validator and log the paramaters. 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://jsfiddle.net/vdk93zL8/

Test code

```
try inputing 0xbe0eb53f46cd790cd13851d5eff43d12404d33e8

<div id="surveyContainer"></div>
debugger;

Survey.StylesManager.applyTheme("bootstrap");

var surveyJSON = {"pages":[{"name":"page1","elements":[{"type":"text","name":"question1","title":"What's your ethereum address?","validators":[{"type":"expression","expression":"validate({question1})"}]}]}]}

function sendDataToServer(survey) {
    survey.sendResult('7944a1fa-e257-46a5-9c71-6522827ff3c9');
}

var survey = new Survey.Model(surveyJSON);
$("#surveyContainer").Survey({
    model: survey,
    onComplete: sendDataToServer
});

function validate(params) {
	alert(params[0]);
	return true;
}
Survey.FunctionFactory.Instance.register("validate", validate);

```

### Specify your

* browser: chrome
* browser version: 77.0.3865.90 
* surveyjs platform (angular or react or jquery or knockout or vue): jqury
* surveyjs version: 1.1.13

**Comment by andrewtelnov** [comment]
@MarissaHudson The problem, that your string is number. We try to convert string to number automatically.
We are using the following code by trying to convert the string into number:
```
  private isNumber(value: any): boolean {
    return !isNaN(parseFloat(value)) && isFinite(value);
  }
```
It returns true for this string and it is correct.
Here is [the example](https://jsfiddle.net/surveyjs/jpokq0cr/7/).
What problem do you have with this behavior?

Thank you,
Andrew

**Comment by MarissaHudson** [comment]
Is there any way to mark that it is a string and not to try and format is a number? This is an ethereum address ("0xbe0eb53f46cd790cd13851d5eff43d12404d33e8") not a number. I'd like to write a function to check that it is a valid ethereum address. This would require performing regex on the characters which can't be done since it keeps returning hexadecimal

**Comment by andrewtelnov** [comment]
@MarissaHudson I will try to do something. I'll be back tomorrow.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@MarissaHudson I made the fix. I did not happy with the work-around, but I could not came with something better.
We are going to release new minor version today. The fix will be there.

Thank you,
Andrew

**Comment by MarissaHudson** [comment]
It seems like this didn't work. I can see that the changes were made on the [dev branch](https://github.com/surveyjs/builds/tree/master/dev) but the result is still the same: 
https://jsfiddle.net/0oaj1uns/

**Comment by andrewtelnov** [comment]
@MarissaHudson Yes, indeed. I forgot to use my new function in expression engine. I have added a new unit test and fix it. It will work fine from v1.1.15 that we will likely release next Tuesday.
Sorry about that.

Thank you,
Andrew
