### ISSUE TITLE
Audio Recorder in quiz

### ISSUE THREAD

**Issue by syedmuhammadwaqas** [surveyjs/survey-library#1853]
How I can add an option where user can record his audio and its recorded file show in result ?

**Comment by tsv2013** [comment]
You can use the https://github.com/surveyjs/widgets/blob/master/src/microphone.js custom widget
It's dependencies can be found in the widgets repo home page - https://github.com/surveyjs/widgets

**Comment by syedmuhammadwaqas** [comment]
Got it Thanks.
