### ISSUE TITLE
Error box doesn't disappear when other value is entered

### ISSUE THREAD

**Issue by dk981234** [surveyjs/survey-library#1854]
var json = {
    checkErrorsMode: "onValueChanged",
    questions: [
        {
            type: "dropdown",
            name: "car",
            title: "What car are you driving?",
            isRequired: true,
            hasOther: true,
            choices: [
               "Citroen"
            ]
        }
    ]
};
1. Select other
2. Enter other value -> error box will be still visible

**Comment by dmitrykurmanov** [comment]
https://github.com/surveyjs/survey-library/commit/195ba5fa0c4e8b29e634660b8cf2a386f0b27b98
