### ISSUE TITLE
Is it possible to add a complete button on all pages in run survey gui

### ISSUE THREAD

**Issue by hekin1** [surveyjs/survey-library#1856]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

### What is the current behavior?
When having a survey with a lot of pages (lets say 100), and the user answers some questions on the first page only- then the user has to navigate to the last page to be able to save the survey result with the complete button. This is because the complete button is located only on the last page.

### What is the expected behavior?
Users would like a complete button on every page in the survey

### Specify your

* browser: All modern
* editor version: 1.0.74

**Comment by tsv2013** [comment]
You can implement custom navigation as shown in this live sample on our site - https://surveyjs.io/Examples/Library/?id=survey-customnavigation&platform=jQuery&theme=default
