### ISSUE TITLE
matrixdynamic removes wrong row (only in UI) when using dropdown column

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1857]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/MLO0zGKwQLNYzUiVDSYd?p=preview

if you try to add rows giving a sequential value (1,2,3...) to the dropdown column and the remove any except the last one you'll see the problem: it seem that always the last one is removed. Actually this happen only at UI level, the data seems coherent

**Comment by tsv2013** [comment]
Reproduced. We'll fix it ASAP
