### ISSUE TITLE
ImagePicker doesn't support boolean values as options

### ISSUE THREAD

**Issue by jamesrwaugh** [surveyjs/survey-library#1858]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

When I add **true** and **false** as the value for the image picker, I can't select the images and no value is reported when the survey finishes

What's more interesting is that _visibleIf_ expressions on the image value being true/value work correctly, but the true/false value does not appear on the survey results.

### What is the expected behavior?

I expect to see something like the following result when I complete the survey:

```
{
    "question1": true
}
```

### How would you reproduce the current behavior (if this is a bug)?

Paste the above below JSON into the online SurveyJS editor and observe the described behavior.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "imagepicker",
     "name": "question1",
     "choices": [
      {
       "value": true,
       "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/lion.jpg"
      },
      {
       "value": false,
       "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/giraffe.jpg"
      }
     ]
    },
    {
     "type": "text",
     "name": "question2",
     "visibleIf": "{question1} = true"
    }
   ]
  }
 ]
}
```

### Specify your

* browser: Chrome
* browser version: 77.0.3865.90
* surveyjs platform (angular or react or jquery or knockout or vue): React / Online
* surveyjs version: 1.1.12

**Comment by tsv2013** [comment]
For selecting the items the value attribute is assigned to the corresponding value attribute of the HTML input tag. According the documentation (https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement) tha value is a string. Thus boolean constants become the "true" and "" value attributes.

In any case, we'll need to transform values to strings and backward during user input. To be honest I wouldn't like to add this processing logic to the question.
As a workaround I can recommend you to use strings "true" and "false" and they will work ok.

**Comment by jamesrwaugh** [comment]
I'm currently using the workaround of "true" and "false" and it's good, but it a bit tedious. This isn't a huge deal except that we need to update some models to be strings instead of boolean which is unfortunate. 

Would the SurveyJS fix be a lot of effort? I do find this strangeness on other types other than the image picker which I'm assuming is the same issue.

**Comment by jamesrwaugh** [comment]
Closing this -- for the time being I'm fine with the workaround, thanks!
