### ISSUE TITLE
Add "date" choice into displayStyle in expression question

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1862]
### Are you requesting a feature, reporting a bug or asking a question?

question/feature

### What is the current behavior?

question type expression produces simple DIV html tag

### What is the expected behavior?

use INPUT tag like all other questions **but disabled**. In my specific case, in order to have the correct formatting, I would like to specify that the result of the expression will be a date and I would do that by the inputType property which is of course ignored. 

![image](https://user-images.githubusercontent.com/454321/67013731-ddc67200-f0f3-11e9-84cf-6669365b5b6b.png)

**Comment by andrewtelnov** [comment]
@masciugo We do not have inputType for "expression" question type. This question is always readonly. It has format property that you may use.

Thank you,
Andrew

**Comment by masciugo** [comment]
Please Andrew could you update the plunk to show me how? Thank you

https://plnkr.co/edit/QwBoUors7BH2GRJr4LsQ?p=preview

**Comment by andrewtelnov** [comment]
@masciugo You will have to set expressionQuestion.displayStyle = "date". In this case the value will be displayed as dateValue.toLocaleDateString()

Thank you,
Andrew
