### ISSUE TITLE
Change survey mode to display after submit

### ISSUE THREAD

**Issue by samuelwx** [surveyjs/survey-library#1868]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
On submit, completedPage is displayed after submit. With `survey.showCompletedPage = false`, blank page is displayed.

### What is the expected behavior?
What I want is for the completed page not to be displayed after the user submits. Instead the questions should remain displayed with the user's answers but the survey become uneditable.

I have tried

```
survey.showCompletedPage = false;
survey.onComplete.add(function (result) {
        survey.mode = "display";
});
```
but that displays a blank page

**Comment by andrewtelnov** [comment]
@samuelwx Here is the correct code:
```js
survey.onComplete.add(function (sender, options) {
  survey.mode = "display";
  survey.clear(false);
});
```

Thank you,
Andrew

**Comment by samuelwx** [comment]
Thanks!
