### ISSUE TITLE
matrixdynamic does not show duplicate keys error on alert

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1869]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

matrixdynamic does not show duplicate keys error on alert. it just focus the field

### What is the expected behavior?

it should like panel dynamic does

### How would you reproduce the current behavior (if this is a bug)?

try to add new rows with the same key and submit

https://plnkr.co/edit/N3S9DcGghS2oeRFB0PAC?p=preview

**Comment by andrewtelnov** [comment]
@masciugo I have added two new asserts into the existing unit test to reproduce the issue and fix it.
The fix should be available in today minor update.

Thank you,
Andrew
