### ISSUE TITLE
Bugs in SurveyJS 1.1.16 layout/workings

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#1870]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting bugs

### What is the current behavior?
1) Description underInput does not get the class='small' making it the same size as the titles. Description underTitle does get the class and looks like it should.

2) The layout in version 1.1.15 and 1.1.14 is bodged, there is no spacing between the questions, in version 1.1.14 the layout looks fine.

3) Adding a function to onComplete does not work properly. When adding a function with a window.location.href redirect there, it shortly shows the standard "Thank you for completing the survey" text before actually redirecting. I now redirect on successful onServerValidateQuestions and refrain from using onComplete.

### What is the expected behavior?
1) Add the class='small' to the div around the description span for underInput like you do for underTitle descriptions: 
<div data-bind="visible: question.hasDescriptionUnderTitle, css: koCss().description" class="small">

2) I don't know if this is only a problem on my way of using SurveyJS, but I expect the same layout spacing in subsequent versions.

3) onComplete should completely override the standard onComplete showing the text "Thank you for completing the survey"

### How would you reproduce the current behavior (if this is a bug)?
1) Create a question with an underTitle description and one with an UnderInput description and see the difference. On the survey creator it looks fine, but on an implemented survey it does not (for me).

2) Look at an implemented survey on version 1.1.14 vs version 1.1.15 and 1.1.16.

3) Add a redirect to onComplete and see that it doesn't redirect without showing the standard text onder or in place of the survey.

#### Provide the test code and the tested page URL (if applicable)
3) `function onComplete(result) {
  window.onbeforeunload = null;
  window.location.href = "{{ url }}";
}`

I will try to make some screenshots of the layout problem if needed, please let me know (it will take me some effort to switch versions and show the problem).

### Specify your

* browser: Chrome
* browser version: Version 77.0.3865.120
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.1.14

**Comment by dk981234** [comment]
Hello, 
According to the documentation you can use showCompletedPage: false  to hide the "Thank you" page.
Fix for description under input will be available in the next minor update.
Thanks 
Dmitry
SurveyJS Team

**Comment by Lionqueen94** [comment]
@dk981234  Thanks for the fix, however the layout problem is not addressed. Here are some screenshots:
1.1.14:
![working-1 1 14](https://user-images.githubusercontent.com/2974080/67286110-16da5a00-f4d9-11e9-9ac7-891a92d00d38.png)
1.1.16
![not-working-1 1 16](https://user-images.githubusercontent.com/2974080/67286121-1f329500-f4d9-11e9-97da-b3bef1c787ab.png)

The progress bar also acts and looks different between the versions.
1.1.14:
![original-bar1](https://user-images.githubusercontent.com/2974080/67286479-c0215000-f4d9-11e9-8f0f-b47b0a432bba.png)
![original-bar2](https://user-images.githubusercontent.com/2974080/67286481-c0215000-f4d9-11e9-8637-2ac279a14129.png)

1.1.16:
![new-bar1](https://user-images.githubusercontent.com/2974080/67286477-bf88b980-f4d9-11e9-96b1-007953f1e701.png)
![new-bar2](https://user-images.githubusercontent.com/2974080/67286478-bf88b980-f4d9-11e9-8e2d-4e7cb55457a1.png)

It would be nice if there was a changelog with all the changes in each new version. Can you tell me if there were any layout/spacing/styling changes in version 1.1.15? Since the layout in the newest versions are not working for me, I cannot retrieve the description fix either.

EDIT: 
I figured out the spacing problem. I add my own css to the form:
`    var myCss = {
      question: {
        title: 'col-form-label',
      },
      footer: 'box-footer',
      navigationButton: 'btn btn-primary'
    };`
But class='col-form-label' is no longer added to each question title label from 1.1.15 upwards, can you tell me if the css declaration has changed or if this is a bug in the code?

Please let me know if the bar layout is supposed to be like the new one or if that is a bug.

**Comment by dk981234** [comment]
Hello,
Could you provide sample in plunker for example?  We can't reproduce the problem with margins.
Thanks
Dmitry
SurveyJS Team

**Comment by Lionqueen94** [comment]
@dk981234 I'm trying to get a Plunker to work, but it's not working so far. 
I'm using Survey.Survey.cssType = "bootstrap"; btw

**Comment by dk981234** [comment]
You can modify the working [plunker ](https://plnkr.co/edit/1H1cEvKxBwYmHLhOmAlR?p=preview).
Thanks
Dmitry
SurveyJS Team

**Comment by Lionqueen94** [comment]
Here is a working Plunker. https://plnkr.co/edit/ioDtjYm5FYHPPzrUlGry?p=preview
I do some tweaking on the titles and in 1.1.14:
`let questionTitle = options.htmlElement.getElementsByTagName('h5')[0];
class="${questionTitle.className}"`
exists, but in 1.1.15/16 it doesn't anymore. (edit the script import from 1.1.16 to 1.1.14)

I will try to replicate the progress bar problem in plunker as well.

**Comment by dk981234** [comment]
Yes, it's definitely bug, that your styles for question title are not updating, we'll fix it to the next minor update.
Thanks
Dmitry
SurveyJS Team

**Comment by Lionqueen94** [comment]
@dk981234 Thanks a lot! Will you also fix the progress bar bug?
> This plunker shows the difference in progress bar (again, edit the script import from 1.1.16 to 1.1.14)
> https://plnkr.co/edit/nQhMi6LTGr2B3YmETbaI?p=preview

**Comment by dk981234** [comment]
Hello,
We've fixed question's title class updating in knockout via this [commit](https://github.com/surveyjs/survey-library/commit/0b2e6e6f64866bd6e61e1f530acf3ab06456db7d) and progress bar in bootstrap via this  [commit](https://github.com/surveyjs/survey-library/commit/86ef321e725ace66ad63729433da0bf253f863d9).
Fixes will be available with next minor update.
Thanks
Dmitry
SurveyJS Team

**Comment by Lionqueen94** [comment]
> Hello,
> We've fixed question's title class updating in knockout via this [commit](https://github.com/surveyjs/survey-library/commit/0b2e6e6f64866bd6e61e1f530acf3ab06456db7d) and progress bar in bootstrap via this [commit](https://github.com/surveyjs/survey-library/commit/86ef321e725ace66ad63729433da0bf253f863d9).
> Fixes will be available with next minor update.
> Thanks
> Dmitry
> SurveyJS Team
@dk981234 The class updating issue is in the jquery-surveyjs version, or is that fixed when you fix it in knockout as well? Thanks for putting in the work to fix the bugs, I look forward to the updated version!

**Comment by dk981234** [comment]
Hello,
Yes, class updating issue fixed in knockout and jquery.
Thanks
Dmitry
SurveyJS Team

**Comment by nikhilwegile** [comment]
@dk981234 

Description under input is not working.
Please refer to below link from the documentation under descriptionLocation.

https://surveyjs.io/Documentation/Library/?id=questiontextmodel#descriptionLocation

Can you please suggest something

Thanks
Nikhil Singh

**Comment by dk981234** [comment]
Hello,
I can't reproduce the issue. Here is an [example](https://plnkr.co/edit/?p=preview&preview) and it works fine.
Could you please provide us more information about your case, it would be great if you gave us json or plunker.
Thanks 
Dmitry
SurveyJS Team

**Comment by nikhilwegile** [comment]
@dk981234 


Here is the json.

{
  "title": "test",
  "pages": [
    {
      "name": "test survey",
      "elements": [
        {
          "type": "text",
          "name": "Question1",
          "title": "what your name",
          "description": "eg. Piyush",
          "descriptionLocation": "underInput",
          "isRequired": true
        }
      ]
    },
  ],
  "clearInvisibleValues": "onHidden",
  "questionTitleLocation": "top",
  "questionErrorLocation": "bottom"
}



Angular: 5.2.11
"survey-angular": "1.0.18"

**Comment by dk981234** [comment]
You are using an old version of survey-library.
The feature has been available since v1.1.12.
Thanks
Dmitry
SurveyJS Team

**Comment by nikhilwegile** [comment]
@dk981234 

Its not working for v1.1.12 and also not working for v1.5.19.

**Comment by dk981234** [comment]
Here is [example](https://plnkr.co/edit/u6JzUf16uyzWFLvn) with your json and it works fine.
Thanks
Dmitry
SurveyJS Team

**Comment by nikhilwegile** [comment]
@dk981234 
Yes!!! It is working now. 
Thanks
Nikhil Singh
