### ISSUE TITLE
Triggers to only fire when Next button is clicked

### ISSUE THREAD

**Issue by thomlawton** [surveyjs/survey-library#1872]
Are you requesting a feature, reporting a bug or asking a question?
question

Is there a way to make the triggers only fire when the "Next" button is clicked? I have a survey with multiple pages, each with a single Yes or No question. Depending on response to the each question, I want to skip to a different page.

Current behavior:
I've set this up using triggers - eg. if question1 = 'yes' skip to question10, if question1 = 'no' skip to question5, but I don't want the skip to happen when the radio button is checked. I want the user to have to click 'Next' before the next page shows. This is in case they select the wrong answer or are using keyboard navigation.

The survey isn't linear and some questions will skip back to a previous page, so it isn't feasible to use the visibleIf feature.

**Comment by tsv2013** [comment]
Unfortunately no. Triggers are fired then question value has been changed. You mendioned additional condition - "but I don't want the skip to happen when the radio button is checked" - in this case you can just add this condition to the trigger of register a custom function for complex scenarios.

Custom functions are described in this article - https://surveyjs.io/Documentation/Library/#conditions-functions

Probably you can write your custom logic in code and call this logic in the https://surveyjs.io/Documentation/Library/?id=surveymodel#onCurrentPageChanging event handler or in the https://surveyjs.io/Documentation/Library/?id=surveymodel#onCurrentPageChanged event handler.

**Comment by andrewtelnov** [comment]
From v1.8.2 that we will release on next week (14-18 Sep, 2020), this can be possible after executing the following code:
``Survey.settings.executeSkipTriggerOnValueChanged = false;`` 
Here is [the related issue](https://github.com/surveyjs/survey-library/issues/2380).

Thank you,
Andrew
