### ISSUE TITLE
Loading data into already initialized survey

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#1873]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the current behavior?
So I have a multiple page survey and on page 4 I need to reinitialize my survey to get new data from the server. This data is generated in the backend so I do an Ajax request to get the survey data with a callback to my initializeSurvey function. The problem is that from this page onward, I seem to have 2 surveys and every call happens twice, causing my survey to glitch, skip pages, etc.
My question is, is there a way to load in data when a survey is already initialized? The data I want to load is based on the user input, so I cannot load it up front.

### Specify your
* browser: Chrome
* browser version: 78
* surveyjs platform (angular or react or jquery or knockout or vue): JQuery
* surveyjs version: 1.1.14

Thanks in advance!

**Comment by tsv2013** [comment]
You can get survey data at any time, change it and assign back to survey:
```JS
var data = survey.data;
data["someQuestionName"] = "New value";
survey.data = data;
```
or modify any quesion velue or setting directly:
```JS
survey.getQuestionByName("someQuestionName").value = "New value";
```

**Comment by Lionqueen94** [comment]
Thanks! I was able to fix the issue by just calling the right functions in the right order and not initializing the survey again. I somehow thought that setting the new data would not load properly but it does :+1:
