### ISSUE TITLE
 Validation at the end of the survey

### ISSUE THREAD

**Issue by Moeedtkxel** [surveyjs/survey-library#1874]
Is there any way that my form gets validated after the user has pressed the complete button? Currently the behavior is that the form gets validated on every single page, i.e. when i press the next page button. It does not let me move on if that page is not validated. Is there any way for me to check all the validations & isRequired' on pressing the complete button?

**Comment by andrewtelnov** [comment]
@Moeedtkxel I have created [the example](https://plnkr.co/edit/RK10XmLMpGtjNmLThdKT?p=preview) several days ago, that does exactly that you need.

Thank you,
Andrew

**Comment by Moeedtkxel** [comment]
> @Moeedtkxel I have created [the example](https://plnkr.co/edit/RK10XmLMpGtjNmLThdKT?p=preview) several days ago, that does exactly that you need.
> 
> Thank you,
> Andrew

My boy Andrew here is an absolute life saver, Thanks a lot buddy.
Cheers.
