### ISSUE TITLE
React - Validate all surveys that are separate js files in tabs

### ISSUE THREAD

**Issue by tazmanrising** [surveyjs/survey-library#1877]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

Complete buttons on every survey page that calls validation, however I have entire survey split into separate JS files and using local storage.   e.g.  SectionA.js , SectionB.js    I have a Save button at the top of the parent page.  But with my React , I'm using Tabs and each Section loads data from local storage and when I click Save , it doesn't know about all the children survey pages to validation.

### What is the expected behavior?

I wish to click click Save on Parent page and need it to validate all the child page 

### How would you reproduce the current behavior (if this is a bug)?

 <Tab eventKey={2} title="CORE SEC B."><SectionB /></Tab>

handleSelect(selectedTab) {
if(selectedTab==2){
            var obj=new SectionB();
            obj.refreshLoadData();
      } 
}
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
    
Test code

```
your_code_here
survey.onComplete.add(function(survey, options){  ... } 
```

### Specify your

* browser:  chrome
* browser version: current
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: current

**Comment by tazmanrising** [comment]
I added a stackoverflow question as well .  take a look    https://stackoverflow.com/questions/58599869/react-parent-page-needs-to-call-up-each-method-on-its-children-page

**Comment by tazmanrising** [comment]
Ok, I did get further, and I created a 2nd question   https://stackoverflow.com/questions/58617073/react-js-parent-to-call-functions-of-multiple-children-with-one-button-click

**Comment by andrewtelnov** [comment]
@tazmanrising You have to complete the survey and call the validation before then call ``survey.completeLastPage()`` function. It returns true if there is no errors on validation. You should do it for all your surveys. 
If have just one page in your surveys then you may call the following function for each survey:
``survey.currentPage.hasErrors(true, true);`` It returns true if there is an error.
To check errors on all pages you may use the following code:
```js
function hasErrorsInSurvey(survey) {
    for (var i = 0; i < survey.visiblePages.length; i++) {
        if (survey.visiblePages[i].hasErrors(true, true)) {
            survey.currentPageNo = i;
            //Show errors and focus the first question with error
            survey.currentPage.hasErrors(true, true);
            return true;
        }
    }
    return false;
}
```
Thank you,
Andrew

**Comment by tazmanrising** [comment]
@andrewtelnov  - thanks so much for responding.  I will try this out.
