### ISSUE TITLE
Support to image based questions

### ISSUE THREAD

**Issue by lhsvobodaj** [surveyjs/survey-library#1878]
I would like to have a question in my survey that is completely based on images (no text at all). Below is an example:

<img width="747" alt="Screen Shot 2019-10-29 at 2 41 28 PM" src="https://user-images.githubusercontent.com/5245736/67760477-d770b800-fa5a-11e9-9235-489654bce72f.png">

I spend some time playing with the HTML question until I found a comment on issue https://github.com/surveyjs/survey-library/issues/624#issuecomment-326974719 saying that this component should be used only to display information.

In this case, is there any other question type that can be used to support this type of question?

**Comment by gologames** [comment]
Hello,

You may use [imagepicker question](https://surveyjs.io/Examples/Library/?id=questiontype-imagepicker&platform=jQuery&theme=default) with [image in description](https://surveyjs.io/Examples/Library/?id=survey-markdown-radiogroup&platform=jQuery&theme=default). Here is live [sample in plunker](https://next.plnkr.co/edit/mXfyRwPjCtshgle1?preview)

Thanks, Alex
SurveyJS Team
