### ISSUE TITLE
survey.jquery 1.1.18 with Bootstrap theme has bugs in layout

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#1880]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting bugs

### What is the current behavior?
1) The div around the 
`<div role="alert" data-bind="visible: errors.length > 0, foreach: { data: errors, as: 'error'}, css: question.koCss().error.root" style="display: none;" class="alert alert-danger"></div>`
on fields now looks like this:
`<div data-bind="visible: errors.length > 0, css: !isPanel ? koErrorClass() : 'panel-error-root'" style="display: none;" class="alert alert-dangersv_qstn_error_bottom">`
This is wrong and causes the alert to be indented when displayed, also the space reserved for the alert is not shown when there is no error.
Without error:
![Screenshot from 2019-10-30 15-45-19](https://user-images.githubusercontent.com/2974080/67868631-86c98f80-fb2c-11e9-83b3-c765fb8851a7.png)
With error:
![Screenshot from 2019-10-30 15-45-37](https://user-images.githubusercontent.com/2974080/67868642-89c48000-fb2c-11e9-893a-067438ef5594.png)

2) 'has-error' does not get added to the question div anymore in case of an error on the question:
`<div data-bind="css: question.koRootClass(), style: { paddingLeft: question.paddingLeft, paddingRight: question.paddingRight, width: question.renderWidth }, attr: {id: question.id, name: question.name}" style="width: 100%;" id="sq_102" name="project_name" class="sv_qstn form-group">`
### What is the expected behavior?
1) The div around the alert div should look like this:
`<div data-bind="visible: errors.length > 0, css: !isPanel ? koErrorClass() : 'panel-error-root'" class="sv_qstn_error_bottom">`
So remove the style="display:none" and the classes that are copied from the inner div role=alert.

2) 'has-error' should be added to the class of the outer div for each question in case of an error on the question:
`<div data-bind="css: question.koRootClass(), style: { paddingLeft: question.paddingLeft, paddingRight: question.paddingRight, width: question.renderWidth }, attr: {id: question.id, name: question.name}" style="width: 100%;" id="sq_102" name="project_name" class="sv_qstn form-group has-error">`

Causing the layout to go back to before 1.1.18 version:
Without error:
![Screenshot from 2019-10-30 16-00-32](https://user-images.githubusercontent.com/2974080/67870100-a366c700-fb2e-11e9-8c83-9399bdfecd46.png)
With error:
![Screenshot from 2019-10-30 15-51-56](https://user-images.githubusercontent.com/2974080/67869165-58987f80-fb2d-11e9-9638-74772be7ad37.png)

### How would you reproduce the current behavior (if this is a bug)?
Compare a previous version of survey.jquery.js with the 1.1.18 version.
with Survey.StylesManager.applyTheme("bootstrap");

### Specify your
* browser: Chrome and Firefox
* browser version: most recent versions
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.1.18

**Comment by dk981234** [comment]
Hello, it is definitely a bug. Thank you for your reply.
We'll fix it.
Thanks, Dmitry
SurveyJS Team

**Comment by dk981234** [comment]
Hello
We've fixed the issue. Fix will be available with the next minor update.
Thanks
Dmitry
SurveyJS Team
