### ISSUE TITLE
File : Confirm file removal

### ISSUE THREAD

**Issue by olimjonbakirov** [surveyjs/survey-library#1881]
### Are you requesting a feature, reporting a bug or asking a question?
Feature request

### What is the current behavior?
When pressed on 'Remove this file', the file gets deleted immediately without confirmation. 

### What is the expected behavior?
Confirmation should be shown to prevent accidental deletion.

### How would you reproduce the current behavior (if this is a bug)?
Upload a file on File question and click on 'Remove this file'

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
This feature has been implemented via referenced commit
