### ISSUE TITLE
Read-Only fields are not validated

### ISSUE THREAD

**Issue by dArignac** [surveyjs/survey-library#1887]
### Are you requesting a feature, reporting a bug or asking a question?
Ask a question

### What is the current behavior?
Read-Only questions with validation rules are not validated.

### What is the expected behavior?
Read-Only questions with validation rules are validated.

### How would you reproduce the current behavior (if this is a bug)?
Create a survey with the structure below. Fill it out, in fact only the first question is editable, and send it. One can send the survey without any issue. Anyhow, the second question has a validation that is not fulfilled, but as it is read only, it is not validated.

Assume the following scenario:
* use a survey with a read only question with a validator
* a user fills out the survey and submits it
* the frontend application sends the data to a backend system to store the results in a database
* the backend system validates the sent data also with survey.js

If a attacker manipulates the sent data for the read only question, this value will be able to get persisted in the database and bypasses any validation.

I know that this only applies when survey.js is also used for validation in the backend. If one would implement the backend side on its own, the problem would probably be solved. To save implementation time and duplication of the survey structure, I think it is quite a reasonable approach to also use survey.js on the backend side and don't do the implementation on your own.

I'd like to hear your opinion on that and if the missing validation for read only questions could be an issue. For me it is, but maybe we just have a edge case here. Please advise!

#### Provide the test code and the tested page URL (if applicable)
Survey structure:

```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "boolean",
     "name": "question1",
     "labelTrue": "Yes",
     "labelFalse": "No"
    },
    {
     "type": "text",
     "name": "question2",
     "enableIf": "{question1} = true",
     "readOnly": true,
     "validators": [
      {
       "type": "text",
       "minLength": 0,
       "maxLength": 3,
       "allowDigits": true
      }
     ]
    }
   ]
  }
 ]
}
```

### Specify your

* browser: Firefox
* browser version:  70
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.1.18

**Comment by tsv2013** [comment]
Read only fields are not validated, beacuse validation means "user input validation" - in case of read only fields user cann't change anything, thus validation massage loses its meaning.

**Comment by andrewtelnov** [comment]
@dArignac There are unit tests, for example like [this one, "Do not show required error for readOnly questions"](https://github.com/surveyjs/survey-library/blob/master/tests/surveytests.ts#L257).
End-user can't fix the error, since there is no input. If we show error and require to fix it, then the survey/form could not be filled.

Thank you,
Andrew

**Comment by dArignac** [comment]
Alright, understood. Thanks a lot for the clarification!

**Comment by dArignac** [comment]
Still found a possible issue, please consider this case:



```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "boolean",
     "name": "question1",
     "labelTrue": "Yes",
     "labelFalse": "No"
    },
    {
     "type": "text",
     "name": "question2",
     "enableIf": "{question1} = true",
     "readOnly": true,
     "validators": [
      {
       "type": "text",
       "minLength": 0,
       "maxLength": 3,
       "allowDigits": true
      }
     ]
    }
   ]
  }
 ]
}
```

The second question has a validation but is only enabled if the first question is set to true.

If I set the  first question to true and enter an invalid value to the second question, the validation properly shows an error. If I then set the first question to false, implicitly setting the second question to read only, I can send the survey. It also sends the wrong value for the second question. In this case, survey.js should not send the value of the second question, should it?

**Comment by gologames** [comment]
Hello,

In this case you send data with `question1=false`, so that means you should not process data of question2 according to your bushiness logic. Therefore question2 don't need any validation in this situation. However you may add another expression question with validation like, `if question1=false then question2 value should be empty`

Thanks, Alex
SurveyJS Team

**Comment by dArignac** [comment]
Ok, understood, thanks a lot!
