### ISSUE TITLE
Is it possible to have an icon on the add/remove row buttons in matrixdynamic?

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#1888]
### Asking a question
Is it possible to have an icon on the add/delete row buttons in matrixdynamic?

There are the 'add row button text' and 'remove row button text' properties, is it possible to put HTML icons in them? If not, I would love to request this as a feature.
For example, I am requested to add a trash icon to the remove row button.

**Comment by dmitrykurmanov** [comment]
Hello, could you please check this example: https://plnkr.co/edit/Rnc4PuOALM1dg7grsB2n?p=preview Is it ok for you?


the same issue: https://github.com/surveyjs/survey-library/issues/550

**Comment by Lionqueen94** [comment]
@dmitrykurmanov Thanks for your answer! I had to manually edit this in my surveyJSON in my js file, because the Survey Designer does not want to save a space in addRowText and removeRowText fields causing the buttons to show the default text... It would be nice if this can be fixed :)
