### ISSUE TITLE
Is it possible to set visible if/required if any one of the questions in paneldynamic contains a certain answer?

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#1889]
### Asking a question?
Is it possible to set visible if/required if any one of the questions in paneldynamic contains a certain answer?

I have a matrixdynamic and a paneldynamic linked to it. This means my questions in the panel multiply according to the amount of rows the user filled in in the matrix. I want to make another question dependent on if any of the answers to the questions in paneldynamic is a certain value (Yes). Is this possible? If yes, can you give me an example, I can now only select the first occurrence of the questions, but I want to look at all of the questions.

_As an example_
Matrixdynamic:
Row 1
Row 2
Row 3

Paneldynamic:
Panel 1 question1 answer Yes
Panel 2 question1 answer No
Panel 3 question1 answer No

If any instance of question1 equals Yes, show Question 2

**Comment by Lionqueen94** [comment]
Hi there, is this currently possible or not? Or is there a workaround possible somehow with runexpression?

**Comment by andrewtelnov** [comment]
@Lionqueen94 Sorry, we have missed this question. You can implement it by registered a custom function that check if there is a colum/question in the array with the requried value. Let us know if you need an example. It is easy to write.

Thank you,
Andrew
