### ISSUE TITLE
It's impossible to set all questions as invisible using "visible" prop

### ISSUE THREAD

**Issue by stsiushkevich** [surveyjs/survey-library#1890]
Hello! I cannot change visibility all of my questions using "visible" prop. Here is an example:

https://repl.it/@SimplyConnect/visible-property

1) Expand panel and check some questions (radiobuttons)
2) Click "Review"

I'm trying to use the following code for change visibility of some questins (all - is only for example):

```javascript
each(questions, (question, i) => {
      question.visible = false
})
```

What I do incorrectly?

Thanks!

**Comment by gologames** [comment]
Hello,

Unfortunately SurveyJS React library don't support live replacement of model as you do in this line `model={isReviewMode ? surveyReviewModel : surveyModel}` at this moment. But why are you trying to show new survey in which all the questions are invisible?

Thanks, Alex
SurveyJS Team

**Comment by stsiushkevich** [comment]
> Hello,
> 
> Unfortunately SurveyJS React library don't support live replacement of model as you do in this line `model={isReviewMode ? surveyReviewModel : surveyModel}` at this moment. But why are you trying to show new survey in which all the questions are invisible?
> 
> Thanks, Alex
> SurveyJS Team

Hello! I don't try to hide all questions - it's only for an example! My target is showing all questions that have checked "Priority" checkbox but without these checkboxes. So I hide all the questions and then show only required.

**Comment by stsiushkevich** [comment]
Which is a correct way to totally rebuild <Survey> with  surveyReviewModel or using additional?

Can I do something like this?

```javascript
<Survey key="usual" /> 
<Survey key="review"/>
```

**Comment by gologames** [comment]
Hello,

Here is [live sample](https://codesandbox.io/s/lucid-cerf-lmofu) how to hide question in SurveyJS React

Thanks, Alex
SurveyJS Team

**Comment by stsiushkevich** [comment]
> Hello,
> 
> Here is [live sample](https://codesandbox.io/s/lucid-cerf-lmofu) how to hide question in SurveyJS React
> 
> Thanks, Alex
> SurveyJS Team

Ok. I prepared a new example: https://codesandbox.io/s/survey-hiding-questions-5jztb?fontsize=14

The first issue:

1) In first expanded panel choose two first questions as "YES"
2) Click "Review" button

AR: U see some unhidden questions

The second issue:

1) Click "Review" button
2) Click "Cancel Review" button

AR: U must click twice to show all questions back
