### ISSUE TITLE
React trying to add a custom button click

### ISSUE THREAD

**Issue by tazmanrising** [surveyjs/survey-library#1893]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

button i add is not working

### What is the expected behavior?

If I click on button, it should fire event 

### How would you reproduce the current behavior (if this is a bug)?

i can show the code 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

In the surveyjs html i added, the json shows 
"name": "SectionE",
   "elements": [
    {
     "type": "html",
     "name": "Additonal Instructions1",
     "html": "<b>1. Important People In The Individual's Life<b> <button type=\"button\" icon=\"pi pi-external-link\" onClick={this.onClick} className=\"btn btn-primary\" id=\"btnImportant\">Add Important People</button>"
    },

The button click is not calling my event 

I wa looking at the custom widgets and if I try to import a custom widget like  customWidget.js,  it complains about several functions like   'onValueChangedCallback' is not defined  
I tried import Survey,.. and npm install custom survey widgets ... but i end up not being able to do the following in ReactJS  https://embed.plnkr.co/plunk/HdnYE5

End goal is to have that element with  onClick={this.onClick} just be able to fire...

In my React code i have : 
this.onClick = this.onClick.bind(this);
then
onClick() {
        this.setState({visible: true});
}

(normally apart from surveyjs code,  I can simply have this
<button type="button" icon="pi pi-external-link" onClick={this.onClick} className="btn btn-primary" id="btnImportant">Add Important People</button>   
That works fine as expected.

What is the simplest way to achieve just having a button click added to a survey and being able to have it fire off so i can do some event/action ?



```

### Specify your

* browser: chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: latest

**Comment by tsv2013** [comment]
The `onClick={this.onClick}` is not expected to work due to it rendered as a plain HTML

Ordinary HTML/JS syntax should work - https://www.w3schools.com/jsref/event_onclick.asp

The recommended way of customizations is to use the onAfterRernderQuestion event like in this sample - https://surveyjs.io/Examples/Library/?id=survey-afterrender&platform=Reactjs&theme=default

**Comment by tazmanrising** [comment]
Thanks.   Trying to get it to work 

Error:

Failed to compile.

./src/JSON-SecA-B-C-D.json
Module parse failed: Unexpected token p in JSON at position 85488 while parsing near '...Individual's Life", popupdescription: "A...'
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token p in JSON at position 85488 while parsing near '...Individual's Life", popupdescription: "A...'
    at JSON.parse (<anonymous>)

JSON 

"name": "SectionE",
   "elements": [
    {
     "type": "html",
     "name": "Additonal Instructions1",
     "html": "1. Important People In The Individual's Life", popupdescription: "Add Important People"
    },

**Comment by tazmanrising** [comment]
trying a lot of things.   Not sure how to use  , popupdescription:   that blows up with parsing error

**Comment by tazmanrising** [comment]
"html": "1. Important People In The Individual's Life", popupdescription: "Add Important People"
gives me an error as soon as it sees popupdescription with quotes , but then i add quotes and i never end up seeing the button  , with the onAfterRenderQuestion    I have to comment out the appendChild 
  //header.appendChild(span);
    //header.appendChild(btn);

I have all the functions, the jquery modal and everything just to minimize any chances of errors...  still not working.
