### ISSUE TITLE
SurveyQuestionText value value is not reset when clear is executed with survey-react

### ISSUE THREAD

**Issue by MasafumiTokiwa** [surveyjs/survey-library#1895]
Hello!
In v1.1.14 or later, even if survey-react `survey.clear` is executed, the input value of SurveyQuestionText input element is not reset.
SurveyQuestionText state value appears to be cleared.

Works as expected under v1.1.13.

https://plnkr.co/edit/gYj5nESJSdPd5LJWYBs2?p=preview

**Comment by tsv2013** [comment]
We've reproduced the issue. https://next.plnkr.co/edit/btRCCKGJOAwS8j4c?preview
We'll work on the fix.

**Comment by MasafumiTokiwa** [comment]
Thanks a lot!
I confirmed that the bug was fixed in v1.1.20.
