### ISSUE TITLE
React: currentPageNo won't accept new values

### ISSUE THREAD

**Issue by DaveSweeton** [surveyjs/survey-library#1896]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
I'm creating my component like so: 
```
<Survey
     /*other props omitted*/
    currentPageNo={this.state.PageIndex}
    onCurrentPageChanging={() => this.onPageChanging()} />
```

Then in my event handler:

```
onPageChanging(sender, options){
        options.allowChanging = false; //block the page change until we finish custom processing, then our state change will set the new page index.
        //Do my stuff then:
        this.setState({PageIndex: options.newCurrentPage.visibleIndex});
    };
```

### What is the expected behavior?
The survey should move to the new page after the state variable changes.

This used to work in 1.1.7.

It appears that I can set currentPageNo on first render only. After the prop has been set, changes are ignored.

### How would you reproduce the current behavior (if this is a bug)?
Create a multi page survey, use the event handler above, see if the page changes with next.

### Specify your

* browser: FireFox Developer
* browser version: 71.0b7
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.1.19

**Comment by andrewtelnov** [comment]
@DaveSweeton Yes, we changed the way we are working with react state due react make several functions obsolete in the latest versions. 
 Please use the following code:
```js
// Old code
// this.setState({PageIndex: options.newCurrentPage.visibleIndex});
//New code, that would work in all SurveyJS versions:
//sender is survey model
sender.currentPageNo = options.newCurrentPage.visibleIndex;
```
Thank you,
Andrew

**Comment by DaveSweeton** [comment]
@andrewtelnov Thanks, I'll try that out. Are there other breaking changes I should be aware of? Is there a post with info?

**Comment by andrewtelnov** [comment]
@DaveSweeton We used to cache survey model properties in react states. There was not need to do it any more, since we made them reactive many versions ago. We have removed this duplication. In fact we could not support it any more since some functions we rely on react team simply removed.

Thank you,
Andrew

**Comment by DaveSweeton** [comment]
@andrewtelnov I've updated my code to use the new approach, and it's working as desired, and is much simpler now. Thanks!

One suggestion I have is release notes would be helpful for breaking changes like this. I was making a big jump from 1.1.7 to 1.1.19, but I couldn't find release notes, and figured if you were using semantic versioning nothing should've broken. My fault for assuming semantic versioning.
