### ISSUE TITLE
How to add an error to an upload question (for example if server returns a BadRequest with an error message)

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#1897]
### Asking a question?
How to add an error to an upload question (for example if server returns a BadRequest with an error message)?

I perform a request to my server onUploadFiles. It is possible that my fileSerializer denies the file because the validator is not happy (for example when the filename is too long). I then get an xhr.status === 400. On handling this, I want to add the error to the question (as I do in onServerValidateQuestions). I try to add the error(s) like this:
`questionObject = survey.getQuestionByName(question);
questionObject.errors.push(questionErrors.join("\n"));`

I have also tried:
`questionObject = survey.getQuestionByName(question);
questionObject.addError(questionErrors.join("\n"));`

Both result in a Javascript error:
`survey.jquery-1.1.19.min.js:11 Uncaught ReferenceError: Unable to process binding "template: function(){return { name:'survey-string',data:error.locText} }"
Message: Unable to process binding "ifnot: function(){return koHasHtml }"
Message: koHasHtml is not defined`

Is this a bug or is there another way to add an error to the file upload question in OnUploadFiles?

* browser: Chrome/Firefox
* browser version: latest versions
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.1.19

**Comment by tsv2013** [comment]
You need to pass a SuveyError object:
```JS
questionObject.addError(new Survey.SurveyError(questionErrors.join("\n")));
```

**Comment by Lionqueen94** [comment]
Thanks a lot, I now see that the docs say type: SurveyError as parameter for addError, my bad for not recognising this before. Again, awesome quick responses from you guys :)
