### ISSUE TITLE
How to disable onComplete on last page when goNextPageAutomatic is true?

### ISSUE THREAD

**Issue by alfredodelfabro** [surveyjs/survey-library#1899]
In a survey with the attribute goNextPageAutomatic equals to true, is there a way to not complete the survey when click in options on last question? I need the user himself to click the finish button on the last question.

Thanks.

**Comment by tsv2013** [comment]
You can set the [allowCompleteSurveyAutomatic](https://surveyjs.io/Documentation/Library/?id=surveymodel#allowCompleteSurveyAutomatic) property of a survey to `false`

**Comment by alfredodelfabro** [comment]
Thanks! I ended up seeing this later. It had version 1.1.1, which did not have this property. Now it worked.
