### ISSUE TITLE
Bug: React RadioGroups have editable comment box if mode = display

### ISSUE THREAD

**Issue by zech** [surveyjs/survey-library#1900]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Radiogroups with "Has Comment" enabled comment boxes are still editable in display mode.

### What is the expected behavior?
Comment field should be disabled.

### How would you reproduce the current behavior (if this is a bug)?

1. Create a survey.
2. Insert a Radio Group question.
3. Set mode of the survey to display
4. Note that you can still edit text within the comment box

#### Provide the test code and the tested page URL (if applicable)

I think the issue is related to this part of the code:

https://github.com/surveyjs/survey-library/blob/74e15eb7f1f54179ee86a37c56f18ea103b2f66a/src/react/reactquestioncomment.tsx#L60-L63

as `this.isDisplayMode` returns false returning from this getter here: 

https://github.com/surveyjs/survey-library/blob/74e15eb7f1f54179ee86a37c56f18ea103b2f66a/src/react/reactquestionelement.tsx#L58-L60

and as i've found the base classes `ReactSurveyElement` and `SurveyElementBase` are already missing the prop `isDisplayMode` so it is defaulting to false.

As I've seen on further debugging is that it is rendered from `SurveyQuestion` here:

https://github.com/surveyjs/survey-library/blob/d49cec3eb1cfd126bf6c9e09c70411d1083cd5d7/src/react/reactquestion.tsx#L188-L203

and as opposed to the property `hasOther` in the Radio Group it is missing the `isDiplayMode` property. Compare with: https://github.com/surveyjs/survey-library/blob/74e15eb7f1f54179ee86a37c56f18ea103b2f66a/src/react/reactquestionradiogroup.tsx#L197-L208

I hope that helps. You can test the behavior in this plunkr here: https://next.plnkr.co/edit/u0BCEUCzscGkqdFp

This is the config i'm using:

```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question6",
     "title": "Radio Group",
     "hasComment": true,
     "choices": [
      "item1",
      "item2",
      "item3"
     ]
    }
   ]
  }
 ],
 "progressBarType": "questions",
 "isSinglePage": true,
 "mode": "display"
}
```

### Specify your

* browser: Chome 
* browser version: Latest dev and Lates stable
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.1.19

**Comment by dmitrykurmanov** [comment]
Thanks for the reporting. Fix will be available in the next minor release.

**Comment by zech** [comment]
Thanks a lot!
