### ISSUE TITLE
Expressions in Matrix Dropdown not calculating

### ISSUE THREAD

**Issue by als753** [surveyjs/survey-library#1902]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

When passing in state for expressions in a dropdown matrix, the expression stops calculating. 

### What is the expected behavior?

The expression should continue to perform calculations, and update the state. 

### How would you reproduce the current behavior (if this is a bug)?
When I change a value more than once in the example: 
https://next.plnkr.co/plunk/fsQRSrgBtPFZLPYt7wnC

### Specify your

* browser:Chrome on OSX
* browser version:Version 75.0.3770.142 (Official Build) (64-bit)
* surveyjs platform : React
* surveyjs version: 1.1.19

**Comment by tsv2013** [comment]
Your code has an error:
```JS
  onValueChanged(result, options) {
    console.log("changing")
    console.log({data: { [options.name]: options.question.value }})
    // I've commented this line
    //this.setState({data: { [options.name]: options.question.value }}) // Impossible to call the setState function here - you are not in the context of a react component here
  }
```

I've updated your plunker and it works ok for me - https://next.plnkr.co/edit/Pm78dZhZAxEj9OWE?preview
