### ISSUE TITLE
[survey-vue v1.1.20] : Cannot redeclare exported variable surveyStrings

### ISSUE THREAD

**Issue by Akash-M** [surveyjs/survey-library#1903]
Survey-vue v 1.1.20 has duplicate exported variable `surveyStrings` in `index.d.ts` resulting in error during compilation using tsc.  

### Are you requesting a feature, reporting a bug or asking a question?
Reporting possible bug. 

### What is the current behavior?
Running `tsc` results in the following error: `Cannot redeclare exported variable 'surveyStrings'.`

<img width="721" alt="image" src="https://user-images.githubusercontent.com/5843438/68752982-85a46200-0604-11ea-9e2c-45085b952828.png">

### What is the expected behavior?
The compilation should not throw the error. 

### How would you reproduce the current behavior (if this is a bug)?
- Install `survey-vue` in a vue.js project with typescript support enabled
- Override default `surveyStrings`
- Compile using tsc

#### Provide the test code and the tested page URL (if applicable)
- Error is in private repository. 
- Error in `index.d.ts` is as follows: 

![image](https://user-images.githubusercontent.com/5843438/68753228-f2b7f780-0604-11ea-95d9-058ab76368a7.png)

![image](https://user-images.githubusercontent.com/5843438/68753266-02374080-0605-11ea-8657-16bb3ed95f58.png)

### Specify your

* browser: Firefox, Chrome 
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.1.20

**Comment by tsv2013** [comment]
We've fixed the issue via the https://github.com/surveyjs/survey-library/commit/2c4da6c741061f1bd7fb1a9fd7145ea6363b8f1f commit.
Fix will be available in the nearest update, most likely next tuesday.
