### ISSUE TITLE
Is possible change matrixdropdown readOnly property on specific row and column

### ISSUE THREAD

**Issue by zulmi** [surveyjs/survey-library#1904]
I have matrixdropdown with 6 rows and 5 columns, and each columns with cellType 'text'
How can I change specific columns (e.g. rows 0 and columns 3) to readOnly?
maybe like q.rows[0].columns[3].readOnly =true

here is my code:
`survey.onAfterRenderSurvey.add(function(handler){
	handler.getAllQuestions().forEach(q => {
    if (q.getType() === 'matrixdropdown') {
	q.rows[i].locOwner.columns[3].readOnly = true;
    }
  });
});`

and the result is all columns index no 3 is readonly, actually I just want question rows index number 0 and column index no 3 to set as readonly

**Comment by tsv2013** [comment]
You can set row readOnly option in the https://surveyjs.io/Documentation/Library/?id=surveymodel#onMatrixCellCreated event hadler:
```JS
survey.onMatrixCellCreated.add(function(sender, options) {
    if(options.row.name === "angularv2" || options.column.name === "strength") {
        options.cellQuestion.readOnly = true;
    }
});
```

Here is the working sample - https://next.plnkr.co/edit/FKtEZvfpMi0VUw3Y

**Comment by zulmi** [comment]
Hi tsv2013,
Thanks for the response, on the sample https://next.plnkr.co/edit/FKtEZvfpMi0VUw3Y , all columns in row.name "angularv2" is readOnly.

I found better code, and it work for me.
`survey.onAfterRenderSurvey.add(function(handler){
	handler.getAllQuestions().forEach(q => {
    if (q.getType() === 'matrixdropdown') {
	q.visibleRows[0].getQuestionByColumnName("strength").readOnly=false;
    }
  });
});`
