### ISSUE TITLE
It's impossible to set all questions as invisible

### ISSUE THREAD

**Issue by stsiushkevich** [surveyjs/survey-library#1905]
I prepared an example: https://codesandbox.io/s/survey-hiding-questions-5jztb?fontsize=14

The first issue:

1) In first expanded panel choose two first questions as "YES"
2) Click "Review" button

AR: U see some unhidden questions

The second issue:

1) Click "Review" button
2) Click "Cancel Review" button

AR: U must click twice to show all questions back

**Comment by tsv2013** [comment]
Then you make all the questions from some page invisible, this page becomes invisible too because it is empty. Then all pages are empty, survey indicates that "There is no visible page or question in the survey." This is the designed behaviour.

Could you explain what do you want to achieve in greater details?

**Comment by stsiushkevich** [comment]
> Then you make all the questions from some page invisible, this page becomes invisible too because it is empty. Then all pages are empty, survey indicates that "There is no visible page or question in the survey." This is the designed behaviour.
> 
> Could you explain what do you want to achieve in greater details?

I have some survey.  Some questions of this survey have boolean "priority" flag. Also there is a "Review mode".  Requirements: "The app shall display the fields with enabled "Priority" checkbox on a separate page shown by clicking on the "Review" button".

![image](https://user-images.githubusercontent.com/12151060/71072818-4c758980-2190-11ea-9655-27a417f41b62.png)

![image](https://user-images.githubusercontent.com/12151060/71072828-50a1a700-2190-11ea-9e09-fa9eb777704b.png)

To enable a Review mode in the editor I need to hide all questions and then show only those of them that have "Priority" checkbox with "true" value.

**Comment by stsiushkevich** [comment]
The issue is not resolved! I'll reopen it.
