### ISSUE TITLE
A way to opt out of the automatic scroll to first question.

### ISSUE THREAD

**Issue by als753** [surveyjs/survey-library#1907]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
When a page change occurs, we want to focus the user on a specific part of the survey. However, the scrolling is now scrolling to the beginning again. 

https://github.com/surveyjs/survey-library/blob/f9aeaf820710cad2894c2c81635b4ac2634ed127/src/survey.ts#L1775

### What is the expected behavior?
I would like an option so that we can opt out of this scroll.
Similar to how we have "focusFirstQuestionAutomatic" I would like something like "scrollFirstQuestionAutomatic" to set at the survey level. 

browser:Chrome on OSX
browser version:Version 75.0.3770.142 (Official Build) (64-bit)
surveyjs platform : React
surveyjs version: 1.1.19

**Comment by tsv2013** [comment]
You can try the following code:
```
Survey.SurveyModel.prototype.scrollToTopOnPageChange = function() {}
```

**Comment by als753** [comment]
Thank you!
