### ISSUE TITLE
Are matrix questions responsive with Bootstrap?

### ISSUE THREAD

**Issue by justinkauai** [surveyjs/survey-library#1908]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question

### What is the current behavior?

Matrix questions with bootstrap are not responsive on small screens in any version past 1.1.9

### What is the expected behavior?

Resize Matrix like the default non bootstrap theme does

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/UhHfRcZ2XKL35QijF1FF?p=preview

I like how the default theme handles matrix resizing, is this available if I use bootstrap?

**Comment by dk981234** [comment]
Hello,
It is definitely a bug.  We've fixed it with this [commit](https://github.com/surveyjs/survey-library/commit/faf97a336cd6e6c0aca68a0bb3317c9b9c7acd03) . The fix will be available with the next minor update.
Thanks
Dmitry
SurveyJS Team
