### ISSUE TITLE
Package Structure

### ISSUE THREAD

**Issue by johannesschobel** [surveyjs/survey-library#1909]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
Currently, there is a `survey-angular`, `survey-vue`, `survey-jquery`, `survey-react`, `survey-whatever` package, that all contain the structure / models from `survey-core`. Wouldn't it be better to make them include the `survey-core` as dependency?

### What is the expected behavior?
I would expect to have the `survey-angular`, `survey-vue`, `survey-whatever` to include the `survey-core` as a main dependency. This would reduce the code in these libs dramatically, as this code can simply be referenced.

For example, in my application scenario, i need a `vue` and `angular` application. So i would require both the `survey-angular` and `angular-vue` package - and hence, would download / include the `core` code 2 times.. :(

All the best

**Comment by tsv2013** [comment]
Do you need the survey-angular and angular-vue packages to be bundled in the same app simultaneously? Usually there are two different application bundles.

**Comment by johannesschobel** [comment]
i use a monorepository, i.e., i only have one huge `package.json` file!

**Comment by tsv2013** [comment]
Do you have different applications - angular and vue?

**Comment by johannesschobel** [comment]
yeah, but all are located within one mono-repository. so these packages **do not** have their own `package.json` file, but rather one large file within the repository. however, there are sophisticated build scripts that creates different applications based on the structure of this repository..

**Comment by tsv2013** [comment]
If you create different applications, let's say
A - angular app
V - vue app

At this moment:
When you build app A, your build scripts include `survey-angular` package inside it
When you build app V, your build scripts include `survey-vue` package inside it

If `survey-core` package will be separated,
When you build app A, your build scripts include `survey-core` and `survey-angular` packages inside it
When you build app V, your build scripts include `survey-core` and `survey-vue` packages inside it

The size of the resulting bundle will be the same. What's the profit?

**Comment by tsv2013** [comment]
From the other hand, `survey-angular` and `survey-vue` packages don't have other dependencies except Angular and Vue and packages structure redesign will be a breaking change for our users. I believe we should not do such breaking changes

**Comment by johannesschobel** [comment]
Dear @tsv2013 ,

thanks again for answering me. The issue is, that i also have a backend application (i.e., nodeJS). This application, in turn, needs to verify respective data sent from my clients, and offer typings for responses sent to the clients. I.e., i would like to use the models defined and offered by the `survey-core` library.

In the case of the api, it is completely wrong to use either of the `survey-angular` and `survey-vue` library, but to use the `survey-core` library.. In this case, i would have the `core` code 3 times in my `node_modules`. I am aware, that the bundled (and minified) code that is delivered does not contain the code 3 times - however, it is a structural and architectural issue.

Please note that this change **is not breaking**, if the `survey-core` library is added as a `dependency` in respective `survey-xyz` libraries! The best solution, however, would be to let the developer add both (`core` and `framework-specific`) library. This would, however as you pointed out, be a breaking change!

All the best

**Comment by tsv2013** [comment]
For the backend app you can refer to the `survey-core` package. And you can import `survey-core` in this case in your node js backend app.

As for breaking changes, some of our users don't use packaging systems and simply include our scripts on their pages via the `script` tag. For these users, such a decomposition certainly will be a breaking change.

**Comment by johannesschobel** [comment]
i totally agree for the `<script>` include!
However, would you consider a better packaging strategy for real web applications built with npm / yarn or whatever? Or do you stick with the current approach?

**Comment by tsv2013** [comment]
@johannesschobel  Thank you for the feedback. We appreciate it. We will keep in mind your suggestion for future packaging structure improvements.

**Comment by johannesschobel** [comment]
thanks a lot
