### ISSUE TITLE
Optionally update survey.data (values) on typing text in input

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#1910]
Add survey.textUpdateMode. It has two choices "onBlue" and "onTyping". The defualt is "onBlue". The value is updating on losing focus of the text input (text and comment questions + question comment and others input).

**Comment by ChuckByram** [comment]
@andrewtelnov, this comment and the 1.1.24 code/docs reference "onBlue" but it should be "onBlur".

**Comment by andrewtelnov** [comment]
@ChuckByram Right, Fixed the typo.

Thank you,
Andrew
