### ISSUE TITLE
runExpression casts string to number

### ISSUE THREAD

**Issue by akuzmenkocarmoney** [surveyjs/survey-library#1913]
### Are you requesting a feature, reporting a bug or asking a question?
 reporting a bug 

### What is the current behavior?
runExpression ignores the type of question, casting "string" to "number"

### What is the expected behavior?
runExpression respects the type of question. If type is "text" it must not cast it to a number

### How would you reproduce the current behavior (if this is a bug)?
Click the "Complete" button. The alert shows "1" instead of "00001"
https://plnkr.co/edit/eiwV0EVLHfgjRNC98HJZ?p=preview
* browser:
Google Chrome
* browser version:
 78.0.3904.108
* surveyjs platform (angular or react or jquery or knockout or vue):
jquery 
* surveyjs version:
1.1.17

**Comment by andrewtelnov** [comment]
@akuzmenkocarmoney Yes, it does, since the most of our customers requires numbers in expressions, but they store strings. If we can convert a string to number, we do.
What is your scenario?

Thank you,
Andrew

**Comment by akuzmenkocarmoney** [comment]
@andrewtelnov We have a question that stores passport number. runExpression is used to process additional logic. When passport number contains leading zeros it leads to wrong results

**Comment by andrewtelnov** [comment]
@akuzmenkocarmoney Could you please share the part of your JSON to show the problem? It would be easy for us to come with a solution.

Thank you,
Andrew

**Comment by akuzmenkocarmoney** [comment]
@andrewtelnov Unfortunately I cannot share my code/JSON (company rules). The simple example of using runExpression is validation.

**Comment by andrewtelnov** [comment]
@akuzmenkocarmoney Please share us here your validator.

Thank you,
Andrew

**Comment by saschanos** [comment]
I ran into the same issue. We want to use the library for a german project. In germany, decimals are shown with a comma; the thousand steps are shown with dots.

It looks like the library is automatically casting the values when using validators. So when a user enters "1.000", it is automatically casted to "1"; but in german this means "thousand". There should be a possibility to output the original value instead of the casted one to the validators.

For now, I used the onValidateQuestion functionality. Here the value is always outputted as a string.

**Comment by tsv2013** [comment]
@saschanos if you set inputType to "number", the entered value will be "1000" and all checks should be ok

**Comment by saschanos** [comment]
That's right – but in this case (using inputType "number") an entered value like "8.000" (which means "8 thousand") is automatically replaced by 8.

**Comment by tsv2013** [comment]
You can also use the inputmask custom widget - https://surveyjs.io/Examples/Library?id=custom-widget-inputmask&platform=jQuery&theme=modern
It will show thousands separator, but clear in then put to survey data

**Comment by andrewtelnov** [comment]
@akuzmenkocarmoney @saschanos From the next week with releasing v1.8.2 you will be able to use:
``survey.runExpression('{#textField}')`` to avoid the conversion. 
Here is [the related issue](https://github.com/surveyjs/survey-library/issues/2376).

Thank you,
Andrew
