### ISSUE TITLE
 "showPageTitles": false does not work when survey.isSinglePage = true

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#1914]
# Reporting a bug
"showPageTitles": false does not work on mode="display" surveys.
The page titles are changed into panel titles and they do not get hidden.
I think the page titles need to be hidden before turning into panel titles.

### Specify your
* browser: Firefox and Chrome
* browser version: latest versions
* surveyjs platform (angular or react or jquery or knockout or vue): JQuery
* surveyjs version: 1.1.21

**Comment by andrewtelnov** [comment]
@Lionqueen94 display model should not convert pages into panel titles.
Are you talking about survey.isSinglePage property? If this property is true, then we convert pages into panels.

Thank you,
Andrew

**Comment by Lionqueen94** [comment]
@andrewtelnov Ah yes I mean isSinglePage=true. Is it possible to hide the page titles with that setting on true and showPageTitles=false?

**Comment by andrewtelnov** [comment]
@Lionqueen94 Added a new unit test and fixed it in the commit above.
You may build a new version as described in readme file or wait until we add a new version into npm on next Tuesday/Wednesday.
Thank you,
Andrew

**Comment by Lionqueen94** [comment]
Thanks a lot, I'll wait for the next release :)
