### ISSUE TITLE
Possibility to show questions in a matrix based on selection in tagbox2

### ISSUE THREAD

**Issue by jeloneal** [surveyjs/survey-library#1919]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the expected behavior?
I have at survey with a tagbox2 widget. It offers a list of websites, the user can choose from. Based on the choices the user makes there I want a Matrixquestion that asks an additional boolean question for each selected item (e.g. "Is the website encrypted?")

How can I configure that second question to show only the entries selected in the first one?

**Comment by tsv2013** [comment]
Yes, you can check this demo on our site - https://surveyjs.io/Examples/Library/?id=condition-matrixVisibleIf&platform=jQuery&theme=modern

**Comment by jeloneal** [comment]
Thanks a lot. That did the trick!
