### ISSUE TITLE
Order of progress bar and navigation buttons

### ISSUE THREAD

**Issue by harrisbaitalrayan** [surveyjs/survey-library#1920]
Dear Team,
I want to show the navigation buttons ( Prev, Next and Complete ) above the progress bar. My requirement is to show the question body and Navigation buttons as a single background and show the progress bar outside this block at the most bottom.

![Screen Shot 2019-11-26 at 5 23 17 PM](https://user-images.githubusercontent.com/13076524/69637116-70eab400-1071-11ea-9fec-7e2d58047a8c.png)

Currently order of divs is question body, then progress bar and at bottom the navigation bar which is preventing me to make my design . Also is it possible to wrap question body div and navigation bar div in a single div to apply this design. Any help will be highly appreciated.

**Comment by tsv2013** [comment]
You can create custom navigation. Here is the sample - https://surveyjs.io/Examples/Library/?id=survey-customnavigation&platform=jQuery&theme=modern

**Comment by harrisbaitalrayan** [comment]
You mean hide the default progress bar and make a custom navigation. Brilliant !
Thank you tsv2013 :-) . Appreciate the quick response and keep up the good work.
