### ISSUE TITLE
Is there a way to add a custom sum display style?

### ISSUE THREAD

**Issue by als753** [surveyjs/survey-library#1921]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question/feature

### What is the current behavior?
Currently when I set a sum field to display as percent, the number gets multiplied by 100 and then displayed with a percent sign. 

### What is the expected behavior?
I would like to keep the same number, and just display the sum with a percent sign. 
I would love to be able to define my own display style for a sum, or possibly override the current display functionality for percent. 

### How would you reproduce the current behavior (if this is a bug)?
https://next.plnkr.co/plunk/3AU3bWSyNUoRpA0L

### Specify your

* browser:Chrome
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.1.21

**Comment by andrewtelnov** [comment]
@als753 Sure use totalFormat: "{0} %" instead. Here is the [example](https://next.plnkr.co/edit/ktaJyfZe9FUJWc1i)

Thank you,
Andrew
