### ISSUE TITLE
How can i add the third param to the save request?

### ISSUE THREAD

**Issue by virajsonagra** [surveyjs/survey-library#1925]
I want to pass custom parameter to surveyjs result data while saving the data. Currently 2 param available postId and SurveyResult, I wants to pass the third one is it possible? How can i do that?

![image](https://user-images.githubusercontent.com/3530596/70031290-e81fcb00-15d0-11ea-99b4-2687e27656b4.png)

**Comment by tsv2013** [comment]
You need to write your own send result function

**Comment by virajsonagra** [comment]
It this right one code?

`model.onSendResult.add(function(sender, options){
     alert(sender);
      return false;
});`


Not working.

**Comment by virajsonagra** [comment]
I also tried this function as well.


`
model.sendResult(function(postid, clientid, isPartialCompleted){
                    console.log(postid);
                });`

But not working.

**Comment by tsv2013** [comment]
The `survey.sendResult` sends result to `surveyjs.io` service and the `survey.onSendResult` is the event that fires then result has been sent to our service.
This request is processed by the `surveyjs.io` service and it doesn't allow to send additional paramaters.

If you want to store additional values in survey result JSON you can add your custom field to survey result data and it will be sent.

**Comment by virajsonagra** [comment]
Okay Thank You. :)
