### ISSUE TITLE
Having more than one "none" choice in checkbox widget / setValue trigger for arrays

### ISSUE THREAD

**Issue by jeloneal** [surveyjs/survey-library#1926]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
Right now, there is only one "none" value in checkbox widget. I want to add more choices that act like the native "none" choice. That means, if I check the box for that choice, all other boxes should get unchecked in the same turn. How can I achieve this?

I tried with triggers. That way I was able to remove the other checks, but then no box is checked.
Is it possible with setValue trigger to set the checkbox array to a certain state?

**Comment by jeloneal** [comment]
```
"triggers": [
  {
   "type": "setvalue",
   "expression": "{action_choice} contains \"stopped\"",
   "setToName": "action_choice",
   "setValue": [
    "stopped"
   ]
  }
 ],
```
I guess the "contains" is to blame for this behaviour.

**Comment by tsv2013** [comment]
I think you can subscribe the https://surveyjs.io/Documentation/Library/?id=surveymodel#onValueChanged or the https://surveyjs.io/Documentation/Library/?id=surveymodel#onValueChanging event and implement desired behavior via JavaScript code in the event handler
