### ISSUE TITLE
Translate/Localization of type html

### ISSUE THREAD

**Issue by gdet** [surveyjs/survey-library#1928]
Is it possible to translate the type Html? 
        {
        "type": "html",
          "name": "question1",
           "html": "text to be translated."
                }

thank you

**Comment by tsv2013** [comment]
Yes. Here is the sample JSON:

```JS
{
 "locale": "de",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "html",
     "name": "question1",
     "html": {
      "default": "English text",
      "de": "Deutsch text"
     }
    }
   ]
  }
 ]
}
```

You can check it in our online survey creator - https://surveyjs.io/create-survey/

**Comment by gdet** [comment]
Ok thank you!
