### ISSUE TITLE
How to change enable checkbox inside the dynamicMatrix via onMatrixCellValueChanged event or other ways?

### ISSUE THREAD

**Issue by XingXie** [surveyjs/survey-library#1929]
I am big fan of the survey report and doing a lot of practices. Basically I would love to have a feature: checkbox can have multiple "other" which I can input multiple texts.

I am trying to implement it by adding a checkbox and text field in the dynamic matrix. 
However, I cannot do the enable/disable checkbox column inside a dynamic matrix. Any suggestions are welcomed. 
Method 1: try to have enableIf inside the checkbox column, it does not reflect the changes.
```
{
            "type": "matrixdynamic",
            "maxRowCount": 3,
            "rowCount": 1,
            "name": "other-cities",
            "title": " ",
            "titleLocation": "hidden",
            "addRowText": "Add another city",
            "columns": [
              {
                "name": "no",
                "title": "Number",
                "cellType": "expression",
                "expression": "{rowIndex}"
              },
              {
                "name": "fillinCity",
                "title": "Your Choice",
                "cellType": "checkbox",
                "choices": [
                  {
                    "value": "fillin",
                    "text": "fill-in",
                    "enableIf": "1 < 0"
                  }
                ]
              },
              {
                "value": "text",
                "name": "text",
                "cellType": "text",
                "title": " "
              }
            ]
      }
```
Method 2: Try to disable the first row checknbox onMatrixCellValueChanged, and it does not work either.
```
survey.onMatrixCellValueChanged.add(function(model, options) {
      if (options.columnName.startsWith("fillinCity")) {
        var dynamicMatrixResult = model.getQuestionByName("other-cities").value;
         
          if (options.value == undefined) {
            // does not work
            options.row.cells[1].questionValue.choices[0].setIsEnabled(false);
            // model
            //   .getQuestionByName("other-cities")
            //   .getColumnByName("cityc")
            //   .templateQuestion.choices[0].setIsEnabled(false);
          }
      }
    });
```
### Are you requesting a feature, reporting a bug or asking a question?
I am asking the question since it does not work. Can be a bug or new feature.

### What is the expected behavior?
The enableIf should be reflected in checkbox inside the dynamic matrix if implementing in the model or onMatrixCellValueChanged event

### Specify your

* browser: Chrome
* surveyjs version: 1.23

**Comment by tsv2013** [comment]
Yes, you can use the `enableIf` for the column. Here is the sample JSON:
```JS
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "matrixdynamic",
     "name": "other-cities",
     "titleLocation": "hidden",
     "columns": [
      {
       "name": "no",
       "title": "Number",
       "cellType": "expression",
       "expression": "{rowIndex}"
      },
      {
       "name": "fillinCity",
       "title": "Your Choice",
       "cellType": "checkbox",
       "choices": [
        {
         "value": "fillin",
         "text": "fill-in",
         "enableIf": "1 < 0"
        }
       ]
      },
      {
       "name": "text",
       "cellType": "text",
       "enableIf": "{row.fillinCity} contains 'fillin'"
      }
     ],
     "rowCount": 1,
     "maxRowCount": 3,
     "addRowText": "Add another city"
    }
   ]
  }
 ]
}
```

**Comment by XingXie** [comment]
Thank you for the response. However my original question is checkbox column cannot reflect the     **"enableIf": "1 < 0"** even I put a false expression there.  
```
"choices": [
        {
         "value": "fillin",
         "text": "fill-in",
         "enableIf": "1 < 0"
        }
       ]
```
And I tried choicesEnableIf in the checkbox question (inside the dynamic matrix column), it does not work as well.
```
{
       "name": "fillinCity",
       "title": "Your Choice",
       "cellType": "checkbox",
        "choicesEnableIf": "1 < 0",
       "choices": [
        {
         "value": "fillin",
         "text": "fill-in"
        }
       ]
      },
```

If not using checkbox inside the dynamic matrix, those enable options work great in other places of my project. How to make it work inside the dynamic matrix column? Any suggestions would be appreciated, thank you very much for the concern!

**Comment by andrewtelnov** [comment]
@XingXie I tried      "choicesEnableIf": "1 < 0" with the latest version (1.8.0) and this property works in the column as well.

Thank you,
Andrew
