### ISSUE TITLE
matrix default value lost when data is controlled 

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1932]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

in my use case survey data is provided by outer component (I am using react flavour). So when I render survey with some data defaultValue prop in matrix input results ineffective even when matrix input is blank

### What is the expected behavior?

I would like to have all input set with their defaults coming either from data or, if blank, from defaultValue prop 

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/tFvM6eyTL51GDM8Gfe5w?p=preview

**Comment by cinziasala** [comment]
Also in my case 

https://next.plnkr.co/edit/W1WlqGDLxDzFpSIv

I would like to use birthdate defaultValue even when some other inputs (name) are already set by preloaded survey data

**Comment by andrewtelnov** [comment]
@cinziasala @masciugo Data are not lost. You have override them. There is no way to know do you want to override default value or keep them.
Anyway, it is several lines of code to keep your defaultValues. Here is [the example](https://next.plnkr.co/edit/s6Fa6w0sQIhE1Orv)

Thank you,
Andrew
