### ISSUE TITLE
`clearInvisibleValues` 'onHidden' option still clears values on submit

### ISSUE THREAD

**Issue by mcgrogan91** [surveyjs/survey-library#1933]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
Given a survey with `clearInvisibleValues` set to 'onHidden', a hidden expression is not included in the final survey submission - it's being cleared as though it was set to 'onComplete'.

### What is the expected behavior?
The documentation for `clearInvisibleValues` says to: Set it to 'onHidden' to clear the question value when it becomes invisible.

Since the expression began the survey invisible, it never became invisible - it always was.  It shouldn't be cleared from the result.

### How would you reproduce the current behavior (if this is a bug)?
Set up a survey with a field and an expression based on it, then set the survey to have its `clearInvisibleValues` property to 'onHidden'.  Enter a value in the visible field and submit, verify that the expression was stripped from the result despite not changing state to hidden (always having been so)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/NLWa8LBGOM9ChYtOE9y4?p=preview

### Specify your

* browser: Google Chrome
* browser version: 78.0.3904.108 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version:

**Comment by tsv2013** [comment]
The `clearInvisibleValues` option with the 'onHidden' value force survey to clear question value immediately after it becomes hidden.

If you want to keep invisible values you need to set the https://surveyjs.io/Documentation/Library/?id=surveymodel#clearInvisibleValues to the `none` value.

**Comment by andrewtelnov** [comment]
@mcgrogan91 I understand where you come from. The question doesn't change it's visibility state and as result it should not change it's value. In fact, we are clearing values for all invisible questions on complete survey unless the ```clearUnvisibleValue``` is 'none'. Do you have any real scenario or we just need to change our docs to make the help topic more accurate?

Thank you,
Andrew

**Comment by mcgrogan91** [comment]
Hi Andrew,

I think what I was trying to do with them is better served by using a calculated value that is included in the result, but it might be worth it to clarify the behavior of 'onHidden' a bit in the documentation as well.

Thanks,
Kyle

**Comment by andrewtelnov** [comment]
@mcgrogan91 Got it and updated the doc for this property.

Thank you,
Andrew
