### ISSUE TITLE
Calculate same expression using async functions for two different questions

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1935]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

I followed the example [here](https://surveyjs.io/Examples/Library/?id=questiontype-expression-async&platform=Reactjs) slightly change the code in order to fetch remote object property. The problem raise when I try to use the custom async function for 2 different questions. They work as expected when used separately but not when data is preloaded

https://plnkr.co/edit/mF8H59MoYMpDgPHgMwBz?p=preview

### What is the expected behavior?

every question should get updated coherently. It seem instead that there is some conflict. I tried by attach the list of listeners to something related to the questions but I was not able to find anything related to the _current_ question into `this` at line 83

How can I do it? 
thanks

**Comment by masciugo** [comment]
I find a solution but is very ugly. The idea is to build question specific list of listeners. The problem is that I cannot find a better way to provide the name of the list except doing that at DSL level in the question definition:

https://plnkr.co/edit/tUXRZofek16By1QuPNfd?p=preview

I think that context provided to the function should include the question using the function

**Comment by masciugo** [comment]
the previous ugly workaround does not work in paneldynamic:

https://plnkr.co/edit/cdfXhHwpRmeylOcMNoM1?p=preview

**Comment by andrewtelnov** [comment]
@masciugo I have added question into function context. You may use it now. I hope it solves your issue.
Please review the commit above.

Thank you,
Andrew

**Comment by masciugo** [comment]
ok thanks I'll let you know

**Comment by masciugo** [comment]
@andrewtelnov I tried. I made a build from master with your update. 

https://plnkr.co/edit/MCsYuZywNsFIpA6JppjI?p=preview

As you can see preloaded data are showed regularly but when I try to play with them for example editing a country nothing things go bad. To be honest I was not able to debug it. Could you have a look to it please?

**Comment by masciugo** [comment]
Actually something weird happens silently without interaction. If you look at the console in the following plunker it seems that the last panel get updated different times with values belonging to the other panels and every time it change back to the right value

https://plnkr.co/edit/rTkOnwQ91vL3LwPiurVS?p=preview

it seems that _returnResult()_ function is applied to the wrong question

**Comment by andrewtelnov** [comment]
@masciugo I wanted to make an example with dynamic panel based on [this example](https://surveyjs.io/Examples/Library/?id=questiontype-expression-async) and I failed.
I will take a look.

Thank you,
Andrew

**Comment by masciugo** [comment]
thank you Andrew. Hope it will be a quick and easy fix

**Comment by andrewtelnov** [comment]
@masciugo I spent several hours today on this issue and it is definately in our code. I found and fix one problem, but now the bug with panel dynamic. Unfortunately, I can't promise a quick fix, but I will continue to work on it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@masciugo Finally found the main issue. We cached the expression parsing and keep the same condition tree to speed up the expression perfomance significantly. It uses the same tree for same expression but with different values&properties.
However, it stops working with async functions. As a solution - do not cache the expression if there is an async function inside it.
You do not need a question property inside the context. Another fix inside ```evaluateAsync(processValue: ProcessValue)``` makes it working out of the box.

Unfortunately this fix will not be included into v1.1.25. You will have to build the library itself or wait for v1.1.26.

Thank you,
Andrew

**Comment by masciugo** [comment]
Hi Andrew, many thanks for your effort. 

I started testing the fix today. The [old plunk](https://surveyjs.io/Examples/Library/?id=questiontype-expression-async) works. It was created to help you isolate the bug. But, I created other two which are more closer to our real scenario.

**The first one is without using the question property inside the context**
https://plnkr.co/edit/pHqCQtcgqSJEdVANs0xQ?p=preview

Eventually all questions are correctly populated but if you see the whole process in slow motion (looking at the console) you'll see that still wrong question values are wrongly set before finish. Moreover, even if I was not able to reproduce it in a deterministic way, sometimes while rerunning the plunker more times, the end result is wrong: all capitals bacame the same. Try reloading to see if it happens

**In the second I used the question property inside the context**
https://plnkr.co/edit/2GTvQWRgWFD1gZbjLuHu?p=preview

Here it seems that no wrong question values are set before finish. the whole process seems more coherent to me. The problem here is that if you try to change the last panel the capital question does not change. I noticed this happens when trying to change a prepopulated panel with a country already used in a previous panel 

I understand the complexity of this issue and I am trying to do my best to help you. Sorry for the bad news

**Comment by andrewtelnov** [comment]
@masciugo I will take a look at them. Thank you for new examples. 
There is nothing to sorry about :) If there is an issue, it has to be fixed. I am not sure I will be able to work on it tomorrow/aftertomorrow. However, I will definately play with the issue this week. I will keep inform you about the progress.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@masciugo I have played with the first example, could not sleep without reproducing the issue :-) and found that the issue is not in the library, but in the example code. Could you please replace the getRemoteObjectAjax function with the simpler version and check it out?
```js
      var remoteObjects = {};
      function getRemoteObjectAjax(url, isReadyCallback) {
        if (!url) {
          isReadyCallback({
            isFound: false
          });
          return null;
        }
        let result = remoteObjects[url.pathname];
        if (!!result) {
          isReadyCallback(result);
          return result;
        }
        $.ajax({
          url: url,
          type: "GET",
          success: function(data) {
            if (!data) {
              isReadyCallback({
                isFound: false
              });
              return;
            }
            var newRes = {
              status: "completed",
              isFound: true,
              data: data
            };
            remoteObjects[url.pathname] = newRes;
            isReadyCallback(newRes);
          },
          error: function(xhr, ajaxOptions, thrownError) {
            isReadyCallback({
              isFound: false
            });
            return;
          }
        });
        return null;
      }
```

And here is the code for fast country changing:
```js
function setCountriesRandomly() {
  var question = survey.getQuestionByName("foo");
  for (var i = 0; i < question.panels.length; i++) {
    var countryQuestion = question.panels[i].questions[0];
    choices = countryQuestion.visibleChoices;
    var value = choices[Math.floor(Math.random() * choices.length)].value;
    countryQuestion.value = value;
  }
}

```
Thank you,
Andrew

**Comment by masciugo** [comment]
wow.. I feared this. I did not get the fix would even simplify the custom function code. 

THANKS Andrew!
