### ISSUE TITLE
Replace property isSinglePage with questionsOnPageMode

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#1938]
## UPDATE by @andrewtelnov:
New property questionsOnPageMode is added with default value "standard". Addtional possible values are:
"singlePage" - all elements on one page
"questionPerPage" - every element is on a separate page.

### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
Currently the survey displays as programmed, or all in one single page if `isSinglePage` is `true`.

I propose replacing `isSinglePage` with `executionMode` with value: `singlepage|standard|singlequestion`.

The single question mode would then duplicate each page that has more than 1 question so that it has 1 question per page. (Panels are interpreted as single questions).

### What is the expected behavior?
Allows more effective creation of surveys that need to show just 1 question per page.

**Comment by tsv2013** [comment]
Thank you for the suggestion. We'll keep it in mind during future releases planning.

**Comment by SamMousa** [comment]
We could call it `presentationMode` or `surveyFormat`

**Comment by andrewtelnov** [comment]
@SamMousa I would love to have a "page" word here.

Thank you,
Andrew

**Comment by SamMousa** [comment]
But it is not related to page; 
`presentationMode` with options `singlepage|standard|singlequestion` would be more descriptive then using something like `pageFormat` with a value of `singlequestion`.
If you prefer `pageFormat` because it contains `page` then that's fine as well ;-)

**Comment by andrewtelnov** [comment]
@SamMousa `questionsOnPageMode: standard|singlePage|questionPerPage` ?

**Comment by SamMousa** [comment]
Sure :smile:

**Comment by andrewtelnov** [comment]
@SamMousa Implemented.
