### ISSUE TITLE
How to create a conditional string expression?

### ISSUE THREAD

**Issue by starg09** [surveyjs/survey-library#1941]
Hello! Been trying the library, and porting over a reporting survey from an alternative system. There's two main things I did on said previous system, and that I ended up doing here in a similar way:

1. I ask them (optionally) for a contact username. While testing the available features on surveyjs, I wanted to place a regex restriction depending on what option they chose: If they chose Discord, they'd have to be "username#9999", and if they chose reddit they'd use "/u/username".
2. I make a good amount of logic jumps, giving different questions and options depending on previously selected options. I think this could be optimized, but right now it doesn't really change the issue that much.

Which brings my current question: I'd like to include a confirmation page before the user completes the submission, [something like this](https://i.imgur.com/kdtUFPO.png). But so far I can't seem to find a way to process the answers inside the survey itself. I can get specific answers to display, but what I'd be looking for is something combining many of them, and using some only if a certain condition is met... What I wonder is, is there some way to, as examples:

* Print "{username_discord}" here only if {contact_info_choice} = "discord"
  - Alternative to this: Set {username} ("Expression (read-only)" block) depending on the value of {contact_info_choice}. Then just print {username}.
* Print `{quest_type} + ( ("[" + <name conditional> + "]") if {quest_type} = "MSS") + ( {ch_number} if ({quest_type} != "D" && {quest_type} != "MSS") ) + <more similar conditions>`

### [Here's a gist of my current survey json](https://gist.github.com/starg09/69de8ef1daa0cbf9e59dab9a8a0c6e72)

I've been looking around the site and customer portal for hours, solved many other questions I had but just can't find a solution to this. I'd really appreciate if you could help me, thank you for reading.

**Comment by andrewtelnov** [comment]
@starg09 I assume that you are posting the data into your own database. It means that you may post the data at any moment you want. You don't need to do it onComplete event.
onComplete event you may show the alternative smaller survey in [display mode](https://surveyjs.io/Examples/Library/?id=survey-displaymode) and use  and with two buttons outside this survey: "Edit Survey" and "Post the Data".
"Edit Survey" will show the previous survey with the current data and "Post the Data" will post the actual data.
In the second survey you may use different visbileIf expressions to show the data you want.
This code will share the data between surveys ```smallSurvey.data = survey.data;```

It is as an idea.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@starg09 About go to another question logic. We have a trigger concepts, survey.triggers. When an expression becomes True the certain actions are performed. There are [complete](https://surveyjs.io/Examples/Library/?id=trigger-complete) and go to question triggers. You may use them.

**Comment by andrewtelnov** [comment]
By the way, just curious, from what platform are you migrating from? and what is the reason?
We have plans, not immediately so, to work on imports from popular survey platforms.
Do you feel we missed something?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Oh yea, regarding conditional regular expression. You may use [expression validator](https://surveyjs.io/Examples/Library/?id=validators-expression). You may use their a [custom function](https://surveyjs.io/Documentation/Library/#conditions-functions).

Thank you,
Andrew

**Comment by starg09** [comment]
Oh! Wasn't aware of those custom functions, not sure how I missed those... That works perfectly for what I was looking for, haha!

Thanks for the quick reply!

> By the way, just curious, from what platform are you migrating from? and what is the reason?
> We have plans, not immediately so, to work on imports from popular survey platforms.
> Do you feel we missed something?

Well, I've been trying some different open source alternatives as to replace an old Google Form for a "game farming report" spreadsheet. For the last couple months I'd been trying [Tripetto](https://tripetto.com/studio/), which is pretty nice but still missing a couple small features. While trying to understand their custom blocks SDK I stumbled upon survey.js and decided to give it a shot as well, and I feel it might work pretty well for some stuff I missed having over there :)

**Comment by andrewtelnov** [comment]
@starg09 Got it! Thank you for good explanation.

Andrew
