### ISSUE TITLE
Is there any way to bypass minRowCount validation when the question is not mandatory in matrixdynamic?

### ISSUE THREAD

**Issue by KLC215** [surveyjs/survey-library#1944]
Hi,

Is there any way to bypass `minRowCount` validation when the question **is not mandatory** in matrixdynamic?

```json
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "matrixdynamic",
     "name": "question1",
     "columns": [
      {
       "name": "Column 1"
      },
      {
       "name": "Column 2"
      },
      {
       "name": "Column 3"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "isRequired": false,
     "rowCount": 1,
     "minRowCount": 1,
     "maxRowCount": 5
    }
   ]
  }
 ]
}
```

For above json, My client wants to hide the `Remove` button when the `rowCount: 1`.
I found `minRowCount: 1` can do the trick, but it still prompt an error message when I validate the form.

Thanks.

* browser: Chrome
* browser version: 79.0.3945.79
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.1.25

**Comment by tsv2013** [comment]
At this moment there no way to bypass `minRowCount` validation except updating the `minRowCount` option at runtime. You can set the `minRowCount` to 0 or 1 if you want.

Could you describe your business case in greater details?

**Comment by KLC215** [comment]
For the `matrixdynamic` question, my client expects:

#### 1. Display a single row _without_ `Remove` button

I set `minRowCount: 1` to the question

#### 2. The question is not mandatory

I set `isRequired: false` to the question

#### 3. Should not prompt the `Please fill in at least 1 rows.` error message because the question and rows are not mandatory.

I tried some approaches on `onSettingQuestionErrors` with `onValidateQuestion` event:

1. Set an empty message
2. Set `visible` to false
3. Remove the `MinRowCountError`

but they didn't work as expected. 
Also, it seems that `minRowCount` will not trigger the `onValidateQuestion` event.

I also tried `onMatrixAllowRemoveRow` to display/hide `Remove` button, but I couldn't find the property to enable back the `Remove` button on the first row.

Here is the plunker that shows my implementation: [https://next.plnkr.co/edit/haOE1oMb6FnujtZi](https://next.plnkr.co/edit/haOE1oMb6FnujtZi)

I think the question should not do any validation if `isRequired: false` and `minRowCount: 1` exist,

Please correct me if I have any misunderstanding about the usage of event/property.

Thanks :)

**Comment by andrewtelnov** [comment]
@KLC215 Reread the message several times and I could not understand the issue.
minRowCount is 1 and isRequried is false (the default value). In your example, the question shows one row and on complete do show any error. What is wrong?

Thank you,
Andrew

**Comment by KLC215** [comment]
Apologize for my explanation :(

For now, I found that `minRowCount` will affect the question UI change (hide `Remove` button in the first row) and validation (`MinRowCountError`).

Can `minRowCount` adopt the UI change only and without the `MinRowCountError`?

My goals are

1. Hide `Remove` button in the first row --> *which `minRowCount: 1` did for the question*
2. No validation for the question because it is not required.

Thanks :) and Sorry for annoying you guys.

**Comment by andrewtelnov** [comment]
@KLC215 In your example there is no any validation. It works out of the box. Unless I missed something.

Thank you,
Andrew

**Comment by KLC215** [comment]
Let's check this simple plunker.
[https://next.plnkr.co/edit/dbrs99NbzM86NU2P](https://next.plnkr.co/edit/dbrs99NbzM86NU2P)

So, what I expect is to 

 * display 1 row and hide `Remove` button in the first row, when the second row is added. All rows should allow to remove.
 * no error message (MinRowCountError) will be prompted.

on `matrixdynamic`.

I added `minRowCount: 1` to do the `first point of the above` and it **works well**.

But, it will prompt the `MinRowCountError` when I submit the form.
That's not my expectation because what I think is
> the question **is not required**, so all errors *(except the input format)* should be ignored/gone.

So my question is
#### Is there any way to ignore all errors to this question?

**Comment by andrewtelnov** [comment]
@KLC215 Sorry, for misunderstanding. Finally I can see the issue. Got it.
You can use survey.onSettingQuestionErrors event to modify question errors. Here is the code
```js
survey.onSettingQuestionErrors.add(function(sender, options) {
    for (var i = options.errors.length - 1; i >= 0; i--) {
        if (options.errors[i].getErrorType() === 'minrowcounterror') {
            options.errors.splice(i, 1);
        }
    }
});
```
And here is [the example](https://next.plnkr.co/edit/IyWeSWErDEhpjxQJ).

Thank you,
Andrew

**Comment by KLC215** [comment]
@andrewtelnov No, it's my poor explanations. Thanks for saving my life~~~~~It works well :)
