### ISSUE TITLE
how to send json data to a php and then upload to mysql?

### ISSUE THREAD

**Issue by Moriand** [surveyjs/survey-library#1945]
### Are you requesting a feature, reporting a bug or asking a question?
Hello, I am new using this excellent library and well, I do not understand very well how is the handling. And here is my question.
How can I receive json data to a php and then save it to a database?
### What is the current behavior?
the data is not sent to the php
### What is the expected behavior?
when you finish the survey, send the json data to a php
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

 >**Code index.html**

```html
<!DOCTYPE html>
<html lang="es">
	<head>
        <title>Test Survey</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="utf-8" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
		<!-- Your platform (jquery) scripts. --> 
		<script src="https://unpkg.com/jquery"></script>
        <link href="https://surveyjs.azureedge.net/1.1.26/survey.css" type="text/css" rel="stylesheet" />
        <script src="https://surveyjs.azureedge.net/1.1.26/survey.jquery.min.js"></script>
		<script src="https://surveyjs.azureedge.net/1.1.26/survey.jquery.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.0/knockout-min.js"></script>
        <script src="https://surveyjs.azureedge.net/1.1.26/survey.ko.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.0/ace.min.js" type="text/javascript" charset="utf-8"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.0/ext-language_tools.js" type="text/javascript" charset="utf-8"></script>  
        <link href="https://surveyjs.azureedge.net/1.1.26/modern.css" type="text/css" rel="stylesheet"/>
        <script src="https://surveyjs.azureedge.net/1.1.26/survey-creator.js"></script>
        <link rel="stylesheet" href="estilo/style.css">
    </head>
<body>
<div id="surveyContainer"></div>
<div id="surveyElement"></div>
<script type="text/javascript" src="index.js"></script>
</body>
</html>
```
  >file **index.js**
```js
Survey.StylesManager.applyTheme("bootstrap");

var surveyJSON = {"pages":[{"name":"page1","elements":[{"type":"text","name":"qt1","title":"Whats your name?"},{"type":"radiogroup","name":"qt2","title":"What is your gender?","choices":[{"value":"1","text":"Male"},{"value":"2","text":"Female"}]}]}]}

window.survey = new Survey.Model(surveyJSON);

survey
    .onComplete
    .add(function (result) {
        document
            .querySelector('#surveyResult')
            .textContent = JSON.stringify(result.data, null, 3);
    });
survey.onComplete.add(function (sender, options) { 
	var xhr = new XMLHttpRequest();
	xhr.open("POST", "send/datos.php", true);
	xhr.setRequestHeader("Content-Type", "application/json; charset=utf-8"); 
	xhr.send(JSON.stringify(sender.data)); 
	});
	
$("#surveyElement").Survey({model: survey});
```

and end file  
 > **datos.php**
```php
<?php
$datos = _POST['sender'];
$decoded = json_decode($datos, true);
echo $decoded;
?>
```
### Specify your

* browser: mozilla
* browser version: ultimate
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: 1.1.26

**Comment by andrewtelnov** [comment]
@Moriand Please review our [php example](https://surveyjs-php.herokuapp.com/index.html), click on right top corner to go to its GitHub repo.
In general this question is better to ask in php / MySQL (or any your database) forums. We provide survey.onComplete event where you may post the result JSON into your database. Based on your server platform and your service/database you should write different code

Thank you,
Andrew

**Comment by Moriand** [comment]
**@andrewtelnov** Thanks for answering, my question is related to how to embed the json with php. That is, `survey.onComplete` make it **redirect to a php page where json data is displayed**

**Comment by tsv2013** [comment]
This is a common JavaScript question not related to SurveyJS Library functionality. Please check the https://www.google.com/search?q=how+to+redirect+from+javascript search, e.g. https://www.w3schools.com/howto/howto_js_redirect_webpage.asp

**Comment by Moriand** [comment]
@tsv2013 as I also include sending the js data

**Comment by tsv2013** [comment]
Sure. Here it is - https://www.google.com/search?q=javascript+how+to+send+json+to+php+server
E.g. https://stackoverflow.com/questions/23750661/send-json-object-from-javascript-to-php/23750707

There are two different actions - send JSON to server and redirect to other page. And several scenarios can be implemented:

(1)
- send JSON to server
- get response that JSON saved ok
- redirect from client to another page

(2) - Long story short: no, it's not possibile using PHP:
- send JSON to server
- make redirect from the server side
Here you need to make another search - https://www.google.com/search?q=how+to+redirect+in+php+code+on+post+data
https://stackoverflow.com/questions/32387631/is-it-possible-to-send-post-data-with-a-php-redirect
