### ISSUE TITLE
react-survey does not unmount styles properly

### ISSUE THREAD

**Issue by Taskle** [surveyjs/survey-library#1947]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

When implementing a React app with react-survey within it, the styles applied when interacting with the survey are never removed when you leave the survey to other parts of your app, so as a result, that styling can sometimes conflict (e.g. progressbar margins and other subtleties). Note that this occurred for me using the bootstrap theme, but based on the code I inspected, I suspect it applies to all themes.

This is illustrated by added style blocks to <head> that are never removed. Specifically, in my case, they are 2 style blocks with the following ids that get added but never removed: "bootstrap.sv_main" and "surveyjs"

### What is the expected behavior?

When unmounting surveyjs, these style blocks should be removed.

### How would you reproduce the current behavior (if this is a bug)?

Run the following code:
        Survey.StylesManager.applyTheme("bootstrap");
        Survey.Survey.cssType = "bootstrap";
and render a survey as normal.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
...
// configure SurveyJS elements and dependencies
Survey.StylesManager.applyTheme("bootstrap");
Survey.Survey.cssType = "bootstrap";
Survey.defaultBootstrapCss.navigationButton = "btn btn-green";
...
```

NOTE: for those that encounter this issue, there is a hack workaround you can use. Here is the workaround using React functional components where surveyModel is set only once in your app:

```
useEffect(() => {

    if (surveyModel) {

      // for unmount
      return () => {

        // opposite of https://github.com/surveyjs/survey-library/blob/master/src/stylesmanager.ts -
        // HACK needed to workaround issue that the style hangs around after leaving this page
        // which has weird visual artifacts (e.g. on dossier page, spacing for things is weird)
        let style1 = document.getElementById("bootstrap.sv_main");
        style1.parentNode.removeChild(style1);
        let style2 = document.getElementById("surveyjs");
        style2.parentNode.removeChild(style2);
      };
    }

  }, [surveyModel]);
```

### Specify your

* browser: Chrome
* browser version: Latest
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: survey-react v1.1.29

**Comment by tsv2013** [comment]
I think I understand what are you talking about. Now SurveyJS styles are scoped for bootstrap with the `sv_bootstrap_css` CSS class and shuldn't affect other elements outside the survey.

If you share what exact styles are not scoped we'll definitely fix it.

**Comment by Taskle** [comment]
Thanks for the reply!

So there are 2 style blocks that I observe get included by react-survey:
- bootstrap.sv_main
- surveyjs

![css](https://user-images.githubusercontent.com/1445636/71647288-54155200-2ca9-11ea-8c87-ee8891443d9e.png)

The latter (surveyjs) appears to be the one that is affecting style outside the survey components. While I imagine there's more than one example, the one that caused me to notice the problem was progress bars. For example, I had this in my code on a separate prat of my app (unrelated to surveyjs):
```
<div class="progress-bar bg-secondary" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;"></div>
```
and that div gets the following 2 css classes applied:
```
.progress-bar {
    width: auto;
    margin-left: 2px;
    margin-right: 2px;
}
.progress {
    width: 60%;
}
```
which, when looking at the inspector, these originate from the surveyjs style element injected above.

When I manually remove the style component after unmounting the survey, it resolves the issue. Namespacing it would help, so if you'd like to do that, that would be wonderful. That said, unmounting the injected style blocks in addition feels like it would be the cleanest solution, IMHO. :)

Cheers,
Dave

**Comment by dk981234** [comment]
Hello,
We fixed the issue via this [commit](https://github.com/surveyjs/survey-library/commit/02be7bd9b7fa18da61baa0cb223b8b7061c2b3e3). 
Thanks
Dmitry
SurveyJS Team
