### ISSUE TITLE
Add ability to navigate on a url on completing survey

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#1949]
Add navigateToUrl, navigateToUrlOnCondition properties and onNavigateUrl event.
```js
/**
 * Set this property to a url you want to navigate after a user completing the survey
*/
public navigateToUrl: string 
/**
* The list of url condition items. If the expression of this item returns true, then survey will navigate to item url
* @see UrlConditionItem
* @see navigateToUrl
*/
public navigateToUrlOnCondition: Array<UrlConditionItem>

```

**Comment by andrewtelnov** [comment]
Functionality is implemented in the library. We have implemented it in Survey Creator as well, but in a newpropertygrid branch. We will merge it in one-two weeks and after that we can close the issue.

Andrew

**Comment by SamMousa** [comment]
How will this interact with `onComplete`?

Will it only be used after `showDataSavingSuccess()` is called from the / all handlers?

**Comment by andrewtelnov** [comment]
@SamMousa In the current implementation, it doesn't wait for showDataSavingSuccess callback and navigates to the url write after calling onComplete event.

Theoratically, I can wait till showDataSavingSuccess callback if showDataSaving callback has been called.

Thank you,
Andrew

**Comment by SamMousa** [comment]
Well I don't care either way, but it should at least be documented.
For our use case I'll probably remove this property since it could interfere with our logic.
Personally I'd say you have to wait until the `onComplete` event has been fully handled, meaning that all event handlers have resolved into either success or error, even if `showDataSaving` has not been called.

**Comment by andrewtelnov** [comment]
We could not know if the data has been saved or not if showDataSaving / showDataSavingSuccess was not called.
I would agree that It would be logical to go to another url immediately after calling onComplete or, in case using showDataSaving callback, navigate after showDataSavingSuccess callback.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@SamMousa Implemented via commit above.

Thank you,
Andrew
