### ISSUE TITLE
Please fix T3104 also for radio buttons, not only checkboxes

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#1954]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
[DOM] Found 2 elements with non-unique id warning on multi column radio buttons (radiogroup).
I saw this was fixed for checkboxes, which works, but it also needs to be fixed for radio buttons.

### What is the expected behavior?
No warnings on multi column radio buttons but unique id's for each button.

### How would you reproduce the current behavior (if this is a bug)?
Make a multi column radiogroup and look at the console.

#### Provide the test code and the tested page URL (if applicable)
https://plnkr.co/edit/r5FxlyAF7CevgcapCcS4?p=preview

### Specify your

* browser: Chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: 1.1.29 and below

**Comment by tsv2013** [comment]
Thank you for the report. We'll fix it.
