### ISSUE TITLE
Trying to implement different quiz timer options

### ISSUE THREAD

**Issue by MbL93** [surveyjs/survey-library#1955]
I am currently using the following template to create a quiz:
https://surveyjs.io/Examples/Library/?id=survey-quiz&platform=jQuery&theme=modern

I set a different maxTimeToFinish for each page.
I would like to achieve that page N+1 won't show until the time for page N has run up. Is that possible?

Furthermore, i'd like to start the timer by clicking on the "Start Quiz" button, but without showing the timer to the user.

I havn't found any solutions to this yet and dont know where to begin with, are there any suggestions?
cheers

**Comment by andrewtelnov** [comment]
@MbL93 You may disable our page navigation and implement your own. Here is [the example](https://surveyjs.io/Examples/Library/?id=survey-customnavigation).

Thank you,
Andrew

**Comment by MbL93** [comment]
Thanks a lot Andrew, that helped me a lot.
I got one more question tho: Is there a way to hide a page? I want to put a text that goes like "The next question will appear shortly" and hide the question in the meantime.

**Comment by andrewtelnov** [comment]
@MbL93 There is ``survey.onStarted`` event.

Thank you,
Andrew
