### ISSUE TITLE
readOnly in dropdown causes crash when survey data is set programmatically 

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1959]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

readOnly in dropdown causes crash when survey data is set programmatically

### What is the expected behavior?

should not crash

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/tzJQdH0xFqV974dgNcTb?p=preview

**Comment by andrewtelnov** [comment]
@masciugo We will take a look as well.

Thank you,
Andrew

**Comment by tsv2013** [comment]
Fix will be available in the nearest update most likely next tuesday
