### ISSUE TITLE
date format in templateTitle

### ISSUE THREAD

**Issue by cinziasala** [surveyjs/survey-library#1960]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

templateTitle property shows date question value not formatted

### What is the expected behavior?

I'd like to have a way to show dates in template title with the correct format. Is there any workaround to do that?

Thank you
Cinzia

![image](https://user-images.githubusercontent.com/4437896/72149691-fc12d580-33a3-11ea-9e9b-27d89f347fd8.png)

**Comment by tsv2013** [comment]
Unfortunately SurveyJS doesn't have such a feature at this moment. In case of the format is fixed you can just write a constant in the appropriate format.

**Comment by masciugo** [comment]
@tsv2013  would you please clarify? 

here's a plunk if you need it
https://plnkr.co/edit/GiiMOdgU1hGmIJ8vK71W?p=preview

**Comment by tsv2013** [comment]
I was talking about the string constant :-)

But I've added a calculated field and a custom function in your plunk and - https://next.plnkr.co/edit/mgPxdeuQLj1LlQS1

And looks like it is what you need

**Comment by masciugo** [comment]
wow! I had missed calculatedValues feature. Thanks!

**Comment by cinziasala** [comment]
Thank you so much for letting me know this feature.
