### ISSUE TITLE
Custom Widget onAfterRender attaching listeners/firing twice after hiding and showing again

### ISSUE THREAD

**Issue by brandonduganse** [surveyjs/survey-library#1964]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question about an issue I'm having.

### What is the current behavior?
When my custom widget reloads it seems to stack it's functionality on top of it's self again.  For example, when the widget is hidden, after it has been initially loaded, and then the widget is shown again, the functionality of the widget happens twice instead of just once. The widget itself appears only once.

### What is the expected behavior?
The widgets functionality should "fire" or attach listeners only once.

### How would you reproduce the current behavior (if this is a bug)?
hide my custom widget and then show it again in the survey

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here
Here is the relevant onAfterRender code:

function onClose() {
            hdnInput.value = "true";
        }

        function scrollBottom() {
            var y = this.scrollTop;
            var z = this.clientHeight;
            var height = this.scrollHeight;
            console.log("scrolled");
            if (y + z >= height) {
                hdnInput.value = "true";
                question.value = "true";
            }
        }

        btn.onclick = btn.onclick || function () {
            var myWindow = $("#electronic-disclosure-window");
            myWindow.kendoWindow({
                width: (clientWidth * .70) + "px",
                height: (clientHeight * .8) + "px",
                title: "Electronic Disclosure",
                visible: true,
                actions: [
                    "Pin",
                    "Minimize",
                    "Maximize",
                    "Close"
                ],
                close: onClose
            }).data("kendoWindow").center().open();

            document.getElementById("electronic-disclosure-window").removeEventListener("scroll", scrollBottom);
            document.getElementById("electronic-disclosure-window").addEventListener("scroll", scrollBottom);
        }

            var onValueChangedCallback = function () {
            hdnInput.value = question.value ? question.value : "false";
            var reviewedIcon = $(el).find(".green-icon");
            var notReviewedIcon = $(el).find(".red-icon");

            if (hdnInput.value === "true") {
                console.log("Works.");
                reviewedIcon.show();
                notReviewedIcon.hide();
                LogReviewedForm(SCR.FormTypes.ElectronicDisclosure);
            } else {
                notReviewedIcon.show();
                reviewedIcon.hide();
            }
        }
        var onReadOnlyChangedCallback = function () {
            // will never be readonly
        };
        question.readOnlyChangedCallback = onReadOnlyChangedCallback;
        question.valueChangedCallback = onValueChangedCallback;
        //onValueChangedCallback();
```

### Specify your

* browser:
Chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
jquery
* surveyjs version:
surveyjs - Survey JavaScript library v1.0.85

**Comment by tsv2013** [comment]
If I correctly understand your scenario, then all is ok.

If the widget was visible, it was rendered - afterRender was called. If you hide the question - it was removed from DOM. The willUnmount function of the widget should be called. Then widget became visible again - the question has been rendered and the afterRender has been called again.

**Comment by brandonduganse** [comment]
The problem is the afterRender is being called twice, or at least some of the functionality within the afterRender is happening twice.

Also, if the widget is hidden and show again, a second time, the functionality happens even more times.  More and more duplication as the widget is shown and hidden.

**Comment by tsv2013** [comment]
Can you provide us with a sample?

Here is the slightly modified live sample from our custom widgets repo - https://next.plnkr.co/edit/Lk1Es1wR0bpTUKgO
If you check it you can see that "after render" is called once.
