### ISSUE TITLE
Reading custom properties in onComplete Event

### ISSUE THREAD

**Issue by kelvin-homann** [surveyjs/survey-library#1965]
### Are you requesting a feature, reporting a bug or asking a question?

Probably a bug, looking at this example it should work: https://surveyjs.answerdesk.io/ticket/details/t843/getting-and-setting-value-of-a-custom-property

### What is the current behavior?

Accessing a custom property on the Question Object is undefined. Apparently custom properties are already lost as soon as the Survey Model is created. 

### What is the expected behavior?

I can access a custom property in the Question Object. 

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/7hdGj4YQpuXvUflphO51?p=preview

### Specify your

* browser: Any
* browser version: Any
* surveyjs platform: React
* surveyjs version: 1.1.32

**Comment by tsv2013** [comment]
You forgot to add the property:
```JS
Survey.Serializer.addProperty("question", "koquestion");
```

Here is the fixed plunk - https://next.plnkr.co/edit/9WlhZyBR8JB1P0qC

**Comment by kelvin-homann** [comment]
Ah gotcha, thought this was only relevant for the Creator Tool. This fixed it, thank you!
