### ISSUE TITLE
It's impossible to set all questions as invisible

### ISSUE THREAD

**Issue by stsiushkevich** [surveyjs/survey-library#1969]
I prepared an example: https://codesandbox.io/s/survey-hiding-questions-5jztb?fontsize=14

The first issue:

In first expanded panel choose two first questions as "YES"
Click "Review" button
AR: U see some unhidden questions

The second issue:

Click "Review" button
Click "Cancel Review" button
AR: U must click twice to show all questions back

Description of the case:

I have some survey. Some questions of this survey have boolean "priority" flag. Also there is a "Review mode". Requirements: "The app shall display the fields with enabled "Priority" checkbox on a separate page shown by clicking on the "Review" button".

![71072818-4c758980-2190-11ea-9655-27a417f41b62](https://user-images.githubusercontent.com/12151060/73153768-25429e00-40e6-11ea-8e38-bfdeb4a32cc9.png)

![71072828-50a1a700-2190-11ea-9e09-fa9eb777704b](https://user-images.githubusercontent.com/12151060/73153783-28d62500-40e6-11ea-9925-614860ecf377.png)

To enable a Review mode in the editor I need to hide all questions and then show only those of them that have "Priority" checkbox with "true" value.

**Comment by gologames** [comment]
Hello,

Indeed, this is a bug, but it isn't expected that somebody will set `isSInglePage` option via component's props. We have find a workaround for you. You can set the `isSinglePage` manually like `this.state.surveyModel.isSinglePage = false;` instead `this.setState({ isReviewMode: false });`. [Here is updated codesandbox](https://codesandbox.io/s/survey-hiding-questions-my8gm) project. We will discuss with team whether we will fix this issue and write back immediately 

Thanks, Alex
SurveyJS Team

**Comment by tsv2013** [comment]
We've discussed this rather rare scenario and desided not to support it directly, but implement as woraround suggested above.
