### ISSUE TITLE
Remove Button does not appear when panels are set to collapsed

### ISSUE THREAD

**Issue by dogwith1eye** [surveyjs/survey-library#1972]
A couple of bugs to report with this plunk

https://plnkr.co/edit/Qp5oH4wi1pCSarmWEt72

When panel status is set "panelsState": "collapsed", then the new panels do not get added with a remove button. If you remove the panelsState attribute then things work as expected.

When you remove all the panels then they all get added back. So the plunk starts with three, if you remove the third then there are two, if you remove the second then there is one, if your remove this one then they all appear back.

**Comment by andrewtelnov** [comment]
@dogwith1eye I have fixed the issue with "Remove" button. This bug is vue specific. The second bug is related to modal, platform independent code. I will work on the fix as well.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@dogwith1eye New unit test has been added and fixed.
We do not reset panelCount to origional value after removing the last panel. We will release v1.5.3 on this week and it will include the fixes.

Thank you,
Andrew

**Comment by dogwith1eye** [comment]
Terrific! Thanks for all your hard work!

**Comment by andrewtelnov** [comment]
@dogwith1eye You are welcome! We release new version that contains the fix, v1.5.3

Thank you,
Andrew
