### ISSUE TITLE
Calculated values not working in js version opening survey with saved data

### ISSUE THREAD

**Issue by care46** [surveyjs/survey-library#1973]
Hi
i have this simple example

https://next.plnkr.co/edit/qTLwuBLBmTQRWU8v?open=lib%2Fscript.js

the problem is that if i open the survey without saved data, the survey work fine, but if i open the survey with this parameter

window.survey.data = {"question1": 7, "question2": 7, "question5": 12, "question3": 5, "question4": 5 }

the survey don't work correctly and the value in question 5 was not calculated well

It's possible to solve this?

**Comment by andrewtelnov** [comment]
@care46 I have fixed the bug by the commit above. We will release new minor version with this fix available on this week.

Thank you,
Andrew

**Comment by care46** [comment]
Thanks! it's possible to have a survey.jquery.min.js for testing?

**Comment by andrewtelnov** [comment]
@care46 You can build it. Follow the description in the Readme file of this repo.

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov can you build it for me? i havn't git working... and i can't build it....

**Comment by andrewtelnov** [comment]
@care46 We will release v1.5.2 today.

**Comment by care46** [comment]
@andrewtelnov ok thanks! then i can download the survey.jquery.min.js right?

**Comment by andrewtelnov** [comment]
@care46 We will not add this version into our builds cdn, since we are not releasing Survey Creator v1.5.2, we are going to release v1.5.3 this week as well and we will add it into our builds and so on.
You may install our [jquery npm package](https://www.npmjs.com/package/survey-jquery), 
```npm install survey-jquery``` and get that your jquery.min file.

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov yes i do this and work fine! thanks
