### ISSUE TITLE
[Question] set limit on question choices

### ISSUE THREAD

**Issue by swuecho** [surveyjs/survey-library#1974]
a question use choices selected in previous question, but I only want to show certain number of them.

e.g. ask user which brand they like in a question, and then ask user to review 4 of the selected in next question.

I did not find an example or approach to make this work, thanks.

**Comment by gologames** [comment]
Hello,

You can find needed questions via `getQuestionByName` or `getAllQuestions` methods of SurveyModel. To detect user's click question use `onValueChange` event. In this event you can set `choices` property of checkbox/radiogroup/etc question as you want

Thanks, Alex
SurveyJS Team

**Comment by andrewtelnov** [comment]
@swuecho You can filter choices as we do in [this example](https://surveyjs.io/Examples/Library/?id=condition-choicesVisibleIf) and you can limit the number of selected items using answercount validator, here is [the example](https://plnkr.co/edit/oqrcjxlQ1xDodtgpMLVR?p=preview).

Thank you,
Andrew

**Comment by swuecho** [comment]
@andrewtelnov  Thanks. I am aware of choicesVisibleIf. I did not find a way to solve the problem still.

probably I did not describe my question clear enough. 

use the choicesVisibleIf example, https://surveyjs.io/Examples/Library/?id=condition-choicesVisibleIf.

when user click the first checkbox question (1 .  What cars have you being drived?), the user can select any number of the choices. My goal is to show only the first 4 selected on the second question.

I was expecting something like`choicesMaxCount: 4` . ( an extra filter on choices after choicesVisibleIf)

all the information required  is available, so I do not want to write code to make it work.  the solution from @gologames  should be able to get the job done, but JS code is required.

**Comment by andrewtelnov** [comment]
@swuecho It sounds like a new functionality to me: QuestionCheckbox.maximumAnswers, default is 0 that means unlimited number of answers.
The question is, what should we do after an end-user exceed the number of answers, maximumAnswers equals 4, he/she has selected 4 choices and he/she is going to selected one more. Should we unselect the first one?

Thank you,
Andrew

**Comment by swuecho** [comment]
@andrewtelnov  it is not about the number of selection on first question. it is about how many choices are displayed in the next question, which depend on the first question.

use the choicesVisibleIf example, https://surveyjs.io/Examples/Library/?id=condition-choicesVisibleIf.

when user click the first checkbox question (1 . What cars have you being derived?), the user can select *any number of the choices*. My goal is to show only the first 4 selected on the *second* question.

in general, the derived choices are from several questions above, but only show a certain number of them to user. (ChoicesMaxDisplayCount or similar should be the full name)

**Comment by swuecho** [comment]
> @swuecho It sounds like a new functionality to me: QuestionCheckbox.maximumAnswers, default is 0 that means unlimited number of answers.
> The question is, what should we do after an end-user exceed the number of answers, maximumAnswers equals 4, he/she has selected 4 choices and he/she is going to selected one more. Should we unselect the first one?
> 
> Thank you,
> Andrew

this feature can also be useful. if maxinumAnswers is 4, when user select the 5th, give a warning msg "you can only select maximium 4", so user have to de-select one selected answer before another selection. (answer count validator works, but seems only triggered on page complete)

**Comment by andrewtelnov** [comment]
@swuecho You may use the custom function in your case. Here is [the example](https://plnkr.co/edit/oqrcjxlQ1xDodtgpMLVR?p=preview).

Thank you,
Andrew

**Comment by swuecho** [comment]
> the example

wow! That is exactly what i need. Thanks.

**Comment by andrewtelnov** [comment]
You are welcome!

Thank you,
Andrew
