### ISSUE TITLE
isRequired option not working on start page

### ISSUE THREAD

**Issue by jakobjh** [surveyjs/survey-library#1976]
### Are you requesting a feature, reporting a bug or asking a question?

Bug ?

### What is the current behavior?

The field Name on the first page should be mandatory with isRequired set to true. But it is not. You can start quiz without entering your name.

### What is the expected behavior?

The field should be mandatory.

### How would you reproduce the current behavior (if this is a bug)?

Just run the above Json code.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
var json = {
    title: "American History",
    showProgressBar: "bottom",
    showTimerPanel: "top",
    maxTimeToFinishPage: 10,
    maxTimeToFinish: 25,
    firstPageIsStarted: true,
    startSurveyText: "Start Quiz",
    pages: [
        {
            questions: [
                {
                    type: "html",
                    html: "You are about to start quiz by history. <br/>You have 10 seconds for every page and 25 seconds for the whole survey of 3 questions.<br/>Please click on <b>'Start Quiz'</b> button when you are ready."
                },
                {
                  type: "text",
                  name: "Name",
                  title: "Please enter your name",
                  isRequired: true
                }
            ]
        }, {
            questions: [
                {
                    type: "radiogroup",
                    name: "civilwar",
                    title: "When was the Civil War?",
                    choices: [
                        "1750-1800", "1800-1850", "1850-1900", "1900-1950", "after 1950"
                    ],
                    correctAnswer: "1850-1900"
                }
            ]
        }, 
            ]
        }
    ],
    completedHtml: "<h4>You have answered correctly <b>{correctedAnswers}</b> questions from <b>{questionCount}</b>.</h4>"
};

```

### Specify your

* browser: Chrome 
* browser version: 79.0.3945.117
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.1.32

**Comment by tsv2013** [comment]
The thing is that you've set the `firstPageIsStarted: true,` This tells survey that the first page is just a "banner".

**Comment by jakobjh** [comment]
Okay. So in other words you can't have a question AND the Start Quiz button on same page? That's what I was hoping for.

**Comment by andrewtelnov** [comment]
@jakobjh You scenario has perfect sense. We will take a look.

Thank you,
Andrew

**Comment by jakobjh** [comment]
Thanks very much!

**Comment by andrewtelnov** [comment]
@jakobjh I have added a new unit tests and check that it works on your JSON.
We will include the fix into the next release, that we will release on next week.

Thank you,
Andrew

**Comment by jakobjh** [comment]
very nice! :)
