### ISSUE TITLE
clean up remote files using nested panel with file questions

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1980]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

when using nested panel with file questions and removing an outer panel, _onClearFiles_ event callback is only called for the removed panel (outer) so only its direct files can be managed for deletion on remote server. Inner panel files will remain orphan on the server

### What is the expected behavior?

when removing outer panel all files inside it (not only direct ones) should be have chance to be removed 

### How would you reproduce the current behavior (if this is a bug)?

https://next.plnkr.co/edit/9GBNUCmVvx6sYHB7

**Comment by gologames** [comment]
Hello,

We fixed it via [this commit](https://github.com/surveyjs/survey-library/commit/73eaaed8a2aa30c7cf94897ee0b799ee8245b3b3). It will available with next minor update

Thanks, Alex
SurveyJS Team
