### ISSUE TITLE
How to revert the complete state when saving results to backend fails?

### ISSUE THREAD

**Issue by xraywu** [surveyjs/survey-library#1981]
We save the survey answers to our backend in the `onComplete` event. However, due to multiple reasons it could fail (which could be captured) and we would want to "revert" survey's status to incomplete in those scenarios (say goes back to the last page of the survey with all answers intact). Is it possible to do so?

**Comment by tsv2013** [comment]
You can use the https://surveyjs.io/Documentation/Library/?id=surveymodel#clear method.

Here is the working sample - https://plnkr.co/edit/qfO1hIIrBfHIAzbMRmzR?p=preview
