### ISSUE TITLE
[feature] display choices in rows in matrix

### ISSUE THREAD

**Issue by swuecho** [surveyjs/survey-library#1982]
### Are you requesting a feature, reporting a bug or asking a question?

feature

### What is the current behavior?

https://surveyjs.io/Examples/Library/?id=questiontype-matrix&platform=Vue&theme=modern

this works well, if you number of rows is more than columns(choices).

However, when number of rows is significantly less than the number of columns(choices), display the choices in the rows make more sense.  https://plnkr.co/edit/y7FrBNXgYF7VKeWSBybL?p=preview (10 choices can not fit into one medium or small display.)

### What is the expected behavior?

have an option to display choices in rows.

**Comment by swuecho** [comment]
duplication of https://github.com/surveyjs/survey-library/issues/1711

I believe the rational here is also valid.

**Comment by tsv2013** [comment]
Thank you for the suggestion. We'll keep it in mind during future releases planning.

**Comment by swuecho** [comment]
get basic matrix 'vertical' mode work. (not a final solution)

https://github.com/swuecho/survey-library/blob/1ab3c58c1a124f3a4c47eb68ccf1d3b0ecdd7940/src/vue/matrix.vue

**Comment by swuecho** [comment]
@tsv2013  Can I count on that media query `max-width: 600` is fixed? or Can I access the width from vue?
