### ISSUE TITLE
Required Text Not Showing in Item title of MultipleText question

### ISSUE THREAD

**Issue by rsiasat00** [surveyjs/survey-library#1983]
I have a multi-page survey that has a few required fields but it's not showing on the latest version of survey-jquery (^1.5.5)

isRequired: true is set on the first name based on the screenshot below:

![image](https://user-images.githubusercontent.com/31335778/73816626-15ccfe80-4824-11ea-89b9-22a97af43fa6.png)

But when viewed via Test Survey it does not show the required text:

![image](https://user-images.githubusercontent.com/31335778/73816666-2bdabf00-4824-11ea-8bf8-93e98ed94fad.png)

Is there anything that needs to be updated on the JSON file so that it properly reflects the required text? or is this a bug on the latest version?

Any help would be appreciated. Thanks!

**Comment by andrewtelnov** [comment]
@rsiasat00 I have fixed the bug. We will include the fix into v1.5.6 that we will release on this week.

Thank you,
Andrew
