### ISSUE TITLE
createPagesForEveryQuestion should inherit from the original page

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#1985]
When creating pages for every question (`questionsOnPageMode == 'questionperpage') the newly created pages should inherit most (all?) properties from the original page.

Furthermore, if the original page has randomization enabled, the questions should be randomized before the new pages are created.

Most predictable would be to have all properties of the original page be copied to the new page.

**Comment by andrewtelnov** [comment]
@SamMousa I have added the unit test. Your code is perfect, I made the change in deserialization. We have the functionality to deserialize in json all properties except "elements", light serialization. We need it for SurveyJS Creator.

Thank you,
Andrew

**Comment by SamMousa** [comment]
Thanks, wasn't sure about that part. Same for tests!

**Comment by andrewtelnov** [comment]
You are very welcome!

Andrew
