### ISSUE TITLE
Access checkbox choice text in expressions rather than checkbox choice value

### ISSUE THREAD

**Issue by justinkauai** [surveyjs/survey-library#1987]
I would like to use the selected text from a checkbox question in another question name.

I have followed this example this example but params only contains the values and not the text
https://embed.plnkr.co/GXPkeVaYrQAGYIONrjui/

Any way i could pass the choice text instead?

Thanks!

**Comment by andrewtelnov** [comment]
@justinkauai You can do it using calculatedValues functionality and custom function. It is hard to suggest something without seeing the real scenario.
survey.calculatedValues is an array of objects with name and expression. You may refer to a calculated value by it's name: {calculated_value_name} and it will insert the result of expression.

Than you,
Andrew

**Comment by justinkauai** [comment]
In the example above params is a array of values, i would like to access the text of the selected values

**Comment by justinkauai** [comment]
https://plnkr.co/edit/Op5gFat9rXeQRAGj2OeY?p=info

In the example above I need params to contain "text 1","text 2","text 3",etc
Rather than 
"1","2","3",etc

**Comment by gologames** [comment]
Hello,

You can use hidden expression question with custom function to format any string in title as you want. [Here is live sample](https://plnkr.co/edit/iITau7COC1lB2sirisH0?p=preview) how to display choices text from one question in another question's title

Thanks, Alex
SurveyJS Team

**Comment by justinkauai** [comment]
Thank you @gologames and @andrewtelnov.
This works perfectly.
Great library and even better support!

**Comment by JaneSjs** [comment]
With v1.9.108 and newer, a SurveyJS Form Library introduces a new [displayValue](https://surveyjs.io/form-library/documentation/design-survey/conditional-logic#displayvalue) function. To use a title name in expressions, use the [displayValue](https://surveyjs.io/form-library/documentation/design-survey/conditional-logic#displayvalue) function in survey expressions.
