### ISSUE TITLE
[question]matrix column ordering

### ISSUE THREAD

**Issue by swuecho** [surveyjs/survey-library#1990]
### Are you requesting a feature, reporting a bug or asking a question?

quesiton

### What is the current behavior?

rowsOrder exists, but no columnsOrder

https://surveyjs.io/Documentation/Library/?id=questionmatrixmodel#rowsOrder

**Comment by tsv2013** [comment]
At this moment SurveyJS martix question doesn't have this option (`columnsOrder`). But I believe you can reorder columns via JavaScript code after survey object is created.

**Comment by swuecho** [comment]
```
import { randomizeArray } from "@/util.js"

export function setMatrixColumnsOrder(matrix) {
    if (matrix.columnsOrder === undefined) return;
    if (matrix.columnsOrder === 'random') {
      matrix.columns =  randomizeArray(matrix.columns)
    }
}
```

```
var matrixs= this.survey.getAllQuestions();
matrixs.forEach(m => {setMatrixColumnsOrder(m)});
```

get the job done if anyone is interested.
