### ISSUE TITLE
Question: Is it possible to set a boolean to false depending on the amount of rows in a dynamic panel?

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#1992]
### Asking a question
Is it possible to set a boolean to false when it's hidden?

### What is the current behavior?
So I have 2 dynamic panels and a boolean yes/no.
The 2nd panel only has to be filled in if there are 2 or more rows in the 1st panel or if the boolean is set to no.
```
{
     "type": "boolean",
     "name": "is_technical_contact_person_report_recipient",
     "visibleIf": "{technical_contact_person[1]} empty",
     "title": "Is the technical contact person also the recipient of the report?",
     "defaultValue": "false",
     "labelTrue": "Yes",
     "labelFalse": "No",
     "valueTrue": "yes",
     "valueFalse": "no"
},
```
This is how I have defined the boolean. But I'm wondering if it's possible to set the value to no (false) when the boolean gets hidden/when there are 2 or more rows in the 1st panel?
Now it is possible that the boolean is on yes (true) when there are 2 rows in the first dynamic panel and the second dynamic panel is visible and should be filled in also.

### Specify your

* browser: Firefox/Chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.5.6

**Comment by andrewtelnov** [comment]
@Lionqueen94 
You may try to use "setvalue" or "runexpression" trigger. 
```
 "triggers": [
  {
   "type": "setvalue",
   "expression": "{technical_contact_person[1]} notempty",
   "setToName": "yourfullquestionname",
   "setValue": false
  }
 ]

```

**Comment by Lionqueen94** [comment]
@andrewtelnov I had no idea this existed! Thanks for the information!
One more question, is it possible to copy data from a field in a panel to a field in another panel using those triggers? I know it's possible to write strings to it according to this example: https://surveyjs.io/Examples/Library/?id=trigger-setvalue&platform=jQuery&theme=default
But I seem to be unable to use `"setValue": "{technical_contact_person[0].name}"` for example, because it is interpreted as a string. Or what I would rather want is to just copy the contents of one panel into another panel entirely, not field by field.

**Comment by andrewtelnov** [comment]
@Lionqueen94 We have functionality like: valueName. If two dynamic panels/dynamic matrix will have the same valueName, then they will share same data (get/set) from the same array.
Here is [the example](https://surveyjs.io/Examples/Library/?id=survey-shareddata).

Thank you,
Andrew

**Comment by Lionqueen94** [comment]
@andrewtelnov I know about valueName and am using it already and it's awesome. But in this case i only want to copy data in a trigger. If the boolean is true, copy from panel 1 into panel 2. For now I just look in my first panel for the data if the boolean is true, so that also works, but it would make my code easier if I can just look in the data of the second panel to get my information.

**Comment by andrewtelnov** [comment]
@Lionqueen94 In this case you may use "runexpression" trigger with custom function.
You may create a function where you may pass question name(s). Inside the function, this.survey will give you access to the survey instance. ``survey.getQuestionByName(questionName)`` will give you your question, and so on.
[Here is the example](https://surveyjs.io/Examples/Library?id=condition-customfunctions) of using custom function.

Thank you,
Andrew
