### ISSUE TITLE
Radiogroup Other value doesn't load

### ISSUE THREAD

**Issue by WzlMichael** [surveyjs/survey-library#1995]
### Are you requesting a feature, reporting a bug or asking a question?
when i use radiogroup Question, I save survey submited data in database. Then I load that data to show survey. other value comment value doesn't load

example : I design survey : 
{
 "pages": [
  {
   "name": "页面1",
   "elements": [
    {
     "type": "radiogroup",
     "name": "Q1",
     "title": "Q1 Test",
     "hasOther": true,
     "choices": [
      "item1"
     ]
    }
   ]
  }
 ]
}

I  submit Data
{"Q1":"other","Q1-Comment":"Test"}

I update the code file survey.js from https://github.com/surveyjs/surveyjs-aspnet-mvc

The code I load Survey :
 var model = new Survey.Model({ surveyId: surveyId, surveyPostId: surveyId});
    model.css = css;
    model.data = defautlValue;
    window.survey = model;
    model.render("surveyElement");

### What is the current behavior?
When survey show submited Data I set , "Q1-Comment" is not loaded.

### What is the expected behavior?
"Q1-Comment" shwo in page 

 

### Specify your
I use survey.ko.js  ,version: 1.5.5

**Comment by WzlMichael** [comment]
I use survey.ko.js

**Comment by tsv2013** [comment]
Your code works ok for me.
Here is the working plunker - https://plnkr.co/edit/m1ttrXjqb1vJlyXf2HCx?p=preview

**Comment by WzlMichael** [comment]
> orking plunker
Thank you for your code . 
Try to get Survey Data From server .

**Comment by WzlMichael** [comment]
[surveyjs-aspnet-mvc-master.zip](https://github.com/surveyjs/survey-library/files/4199586/surveyjs-aspnet-mvc-master.zip)

try this code , I add  a Survey named "Radiogroup" in SessionStorage. in survey.js  , I add code :
//to load default value
    if (surveyId == "Radiogroup") {
        model.data = { "Q1": "other", "Q1-Comment": "Test" };
    }

**Comment by tsv2013** [comment]
SurveyJS is a client side JavaScript library. If the issue is in the SurveyJS code, you will be able to modify the plunker above to illustrate the issue.

First of all I'd check the data you received and case of the properties. Probably it should be the lower case: ` { "q1": "other", "q1-comment": "Test" };`
