### ISSUE TITLE
Do not show placeholders in display mode or when question is read-only

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#1996]
### Are you asking a question?
Is it possible to turn off/remove placeholders in display mode?

### What is the current behavior?
I have some placeholders in optional fields. When nothing is filled in, they look like they have input because of the placeholders when you're looking at the survey in display mode.

### What is the expected behavior?
I would like an option to have the placeholders (any placeholder) removed/invisible in display mode of know how to do it if it already exists. Thanks a lot!

### Specify your

* browser: Chrome/Firefox
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: 1.5.9

**Comment by andrewtelnov** [comment]
@Lionqueen94 Yes, it makes perfect sense.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@Lionqueen94 It will be a default behavior from v1.5.11. We are going to release it on the next week.

Thank you,
Andrew
