### ISSUE TITLE
Compare strings without converting to number, "77" not equals to "077"

### ISSUE THREAD

**Issue by xxxKOTxxx** [surveyjs/survey-library#2000]
I have a problem with text field updating. I found this issue while tesing zip code field.

### How would you reproduce the current behavior (if this is a bug)?

To reproduce bug need to enter numeric string with leading zeros f.e. "0077" and store survey data (go to next page). 

Then if we return to previous page and change input value to "77" or "077" and try to update survey result no changes will be stored. 

### What is the current behavior?
If we return we'll see "0077" in this input. 

### What is the expected behavior?
Value must be changed

### Possible reason
I think the problem is in unstrict comparing in change detection. 
"0077" == 77 but "0077" !== 77.
If number from string value  changing everything works as expected.

Please check it.

Best regards,
Boris

### Specify your

* browser: Chrome
* browser version: Version 80.0.3987.106 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.5.9

**Comment by tsv2013** [comment]
I've created a live sample - https://next.plnkr.co/edit/X9ITVFDWjaefEwHN
It works ok for me? Do I miss something?

**Comment by xxxKOTxxx** [comment]
I'll try to illustrate in this fork - https://next.plnkr.co/edit/JWeYKRAmb6fMjw1A?preview

Please, take attention to onValueChanged callback fireing.

I'm using backend storageand synchronize data on page changing.

**Comment by xxxKOTxxx** [comment]
Interesting, that onValueChanging working as expected, but onValueChanged - no.

**Comment by andrewtelnov** [comment]
@xxxKOTxxx You should not use ```question.setValueCore``` function. In fact, it is protected and as result it doesn't exists in minimized version.
What you are trying to do?

Thank you,
Andrew

**Comment by xxxKOTxxx** [comment]
> @xxxKOTxxx You should not use `question.setValueCore` function. In fact, it is protected and as result it doesn't exists in minimized version of the library.
> What you are trying to do?

I apologize - I inadvertently saved this.
Returned to the previous state.
The idea was, as a temporary measure, to check for erroneous behavior and manually set the value.

Thank you for your comment

**Comment by andrewtelnov** [comment]
@xxxKOTxxx What is wrong with your plunker? I added debugger; into onValueChanged event. The debugger stopped two times as well as in onValueChanging. Everything works as expected.

PS: We have several unit tests on this functionality. It is unlikely that it is broken.

Thank you,
Andrew

**Comment by xxxKOTxxx** [comment]
@andrewtelnov, sorry - had no time to create more clear plunker.

Try this https://next.plnkr.co/edit/0BdxsoQx5DqwJPiG

I added normal output and steps to reproduce.

I hope it's enough to understand what is wrong. Maybe I don't understand something - if so, I'll be glad if You point out my error.

**Comment by andrewtelnov** [comment]
@xxxKOTxxx I think I finally got you!
You mean that SurveyJS consider "10" equals "010". Am I correct?
I guess we can fix it.

Thank you,
Andrew

**Comment by xxxKOTxxx** [comment]
> You mean that SurveyJS consider "10" equals "010". Am I correct?

Yes! I'll be very glad if You fix it.

Thank You!

**Comment by andrewtelnov** [comment]
@xxxKOTxxx The bug is fixed via commit above.

Thank you,
Andrew

**Comment by xxxKOTxxx** [comment]
@andrewtelnov Thank You!

As I understand we can get this fix in  v1.5.13?

When do You planning to release it?

**Comment by andrewtelnov** [comment]
@xxxKOTxxx We will release v1.5.13 hopefully tomorrow, but definately on this week.

Thank you,
Andrew
