### ISSUE TITLE
Validatation on server

### ISSUE THREAD

**Issue by majkinetor** [surveyjs/survey-library#2001]
Do you have any tips on how to achieve server side check on validation ? 

Lets say I keep various json forms in the db table and have an web app that gets a form, renders it, validats it on client according to schema and posts data back. Now, I can't know if post is crafted/changed after the validation or sent directly to the backend without using interface (backend can't rely on client validation in anyway). So now I need to recheck data on server.

So, I need to use the same schema to test received data object to check for request hacking. If surveyjs was using legit json schema, I would be able to do that in basically [any language](https://json-schema.org/implementations.html#validators).

While this is available on JS side:

```
survey.onComplete.add(function (s) {
    var questions = s.getAllQuestions();
    for (var i = 0; i < questions.length; i++) {
        s.validateQuestion(questions[i].name);
    }
}
```

how would I do it for example in C# backend ?

Any tips are appreciated. The #129 might be related.

**Comment by andrewtelnov** [comment]
@majkinetor Here is the example for [server validation](https://surveyjs.io/Examples/Library?id=validators-server).
Another example, is to use async custom function during validation, where you can make an ajax request, here is [the example](https://surveyjs.io/Examples/Library?id=validators-async-expression).

Thank you,
Andrew

**Comment by majkinetor** [comment]
That is not what I asked. I know about server callbacks and ajax calls.  What I want is something different, for which JS part doesn't play any role. 

So, survey generates some object. I need to check this object later for validity in case it is changed in transport. Imagine I generated a form and you sent it to me via gist. Now I need to validate it without using JS but anything my app using that data is written in (java, C#, ruby, whatever). So there is nothing to callback to, or ajax to. There is offline object and schema. That should be enough. 

Now, I could instantiate some javascript engine within my app that will use survey JS API but that is TOTAL OVERKILL for something that trivial.

**Comment by SamMousa** [comment]
Alternative is to parse the JSON structure of the survey and create validation scripts in the language of your choice.
But you are then essentially rewriting (part of) the survey engine; it might make more sense to run a node process. While you claim it's overkill to do that it is a lot more work to re-implement it in a different language, especially since every new feature will require more work from your side.

**Comment by majkinetor** [comment]
>  While you claim it's overkill to do that it is a lot more work to re-implement it in a different language, especially since every new feature will require more work from your side.

Yeah, that is easier then implementing my language, but really ? I need to host JS engine so I can validate form ? That is a last resort really, and I would actually rather implement my own parser then leting something THAT UGLY slip into the codebase.

The whole point of jscon-shema was to allow stuff like this. While I don't think that such standard is optimal for forms, it has that extra ability to work everywhere and in any context which is lost here.

**Comment by SamMousa** [comment]
Isn't this what microservices are about?

Anyway, if you implement your own parser I'm sure it will make other c# users really happy :grinning:

While a formal spec has benefits it also has drawbacks. Adding custom widgets which have custom validation might not be supported by the spec and would then require custom coding in every validation engine.
