### ISSUE TITLE
Choices from web doesn't load in Dynamic Panels

### ISSUE THREAD

**Issue by Robby123456** [surveyjs/survey-library#2002]
Choices from web doesn't load in Dynamic Panels for dropdowns that rely on values from another dropdown.

### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
Choices from web are not loading in country2 when a value is selected for region2

### What is the expected behavior?
Load the choices from web for country2 when a value is selected for region1

### How would you reproduce the current behavior (if this is a bug)?
Add a row to the panel question, select a region from region2

#### Provide the test code and the tested page URL (if applicable)
Tested page URL: https://plnkr.co/edit/OTcNbH07Ilcbgd3woxvG?p=preview

Test code

```
Survey
  .StylesManager
  .applyTheme("modern");

var json = {
  "pages": [{
    "name": "page1",
    "elements": [{
      "type": "dropdown",
      "name": "region1",
      "title": "region1",
      "choices": [
        "Africa",
        "Americas",
        "Asia",
        "Europe",
        "Oceania"
      ]
    }, {
      "type": "dropdown",
      "name": "country1",
      "title": "country1",
      "choicesByUrl": {
        "url": "https://restcountries.eu/rest/v2/region/{region1}",
        "valueName": "name"
      }
    }, {
      "type": "paneldynamic",
      "name": "question1",
      "title": "panel question",
      "templateElements": [{
        "type": "dropdown",
        "name": "region2",
        "title": "region2",
        "choices": [
          "Africa",
          "Americas",
          "Asia",
          "Europe",
          "Oceania"
        ]
      }, {
        "type": "dropdown",
        "name": "country2",
        "title": "country2",
        "choicesByUrl": {
          "url": "https://restcountries.eu/rest/v2/region/{region2}",
          "valueName": "name"
        }
      }]
    }]
  }]
};

window.survey = new Survey.Model(json);

survey
  .onComplete
  .add(function(result) {
    document
      .querySelector('#surveyResult')
      .textContent = "Result JSON:\n" + JSON.stringify(result.data, null, 3);
  });

$("#surveyElement").Survey({
  model: survey
});
```

### Specify your

* browser: Chrome
* browser version: 80.0.3987.116 (Official Build) (64-bit)
* surveyjs platform: jquery
* surveyjs version: 1.5.10

**Comment by andrewtelnov** [comment]
@Robby123456 You have to use prefix "panel.", {panel.region2}, to get the value from a question in the same panel. Here is [the updated example](https://plnkr.co/edit/r5VFllfQUkgzhLkeE1uk?p=preview).

Thank you,
Andrew

**Comment by Robby123456** [comment]
@andrewtelnov thank you thank you thank you!

Is that documented somewhere?

**Comment by andrewtelnov** [comment]
@Robby123456 We do have examples, but I could not find it in docs. We should add it.

Thank you,
Andrew
