### ISSUE TITLE
Incorrect ISO-639-1 code for Czech language

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#2004]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
The language code used for Czech is `cz`, but according to ISO63901 it should be `cs`.

### What is the expected behavior?
Localization should use language codes not country codes.

**Comment by andrewtelnov** [comment]
@SamMousa We will think how to fix it without producing breaking change for our users who is using ``cz`` tranlsation. Right now I do not see any good solution.

Thank you,
Andrew

**Comment by SamMousa** [comment]
I propose:

- Change languages to use correct code
- Add aliases for the old ones so they can still be used
- Add a warning to the JS console that an old / deprecated code is used.

That gives you a path forward without being stuck to these changes; then all that's needed is to not forget to remove the aliases in the next release that is a breaking change (2.0?)

**Comment by andrewtelnov** [comment]
@SamMousa I do not like the fix, but anyway, unit test is added and fixed.

Thank you,
Andrew

**Comment by SamMousa** [comment]
Why don't you like it? (And why implement it if you don't agree? :D)

**Comment by andrewtelnov** [comment]
@SamMousa There is no any way to fix it. Anyway, since we have unit test, then it should not be a big deal :)

Thank you,
Andrew
