### ISSUE TITLE
indexing and logic inside a dynamic panel

### ISSUE THREAD

**Issue by tkon3** [surveyjs/survey-library#2008]
### Are you requesting a feature, reporting a bug or asking a question?

Questions
I'm using a dynamic panel with 3 widgets inside. 
I want the user to fill these widgets one by one in a fixed order so I want to hide them first. 
As each tab is independent, I need to retrieve the tab index each time.

How can I get the current panel tab index to write the logic? 
Can this be done directly in the survey editor? 
Can we also add some logic to the "add new" button so it is disabled until we ask all questions in the current tab?

Example: 
{mypanel[currentIndex].question1} notempty -> mypanel[currentIndex].question2 visible

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: 
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: 1.15.1

Thanks

**Comment by andrewtelnov** [comment]
@tkon3 It should be: "{panel.question1} notempty".
Here is [the example](https://plnkr.co/edit/31acDpNlPoZsTF71KN9v?p=preview).

Thank you,
Andrew

**Comment by tkon3** [comment]
Thank you it is working inside the panel.
If I have a widget outside the panel, is there a way to access the index of the last panel tab and its specific questions?

**Comment by andrewtelnov** [comment]
@tkon3 That is question about using outside dynamic panel and not inside :) So it is another issue.
Here is [the example](https://plnkr.co/edit/kkk0msrSEYxVeTNNwtoc?p=preview).

Thank you,
Andrew

**Comment by tkon3** [comment]
Perfect this is what I was looking for.

Thank you.

**Comment by tam-carre** [comment]
For anyone stuck on this issue, I was struggling for a while because of an ambiguity in @andrewtelnov  linked example:

```js
var json = {
   "textUpdateMode": "onTyping",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "paneldynamic",
     "name": "panel",
     "panelCount": 1,
     "templateElements": [
      {
       "type": "text",
       "name": "question1"
      },
      {
       "type": "text",
       "name": "question2",
       "visibleIf": "{panel.question1} notempty"
      },
      {
       "type": "text",
       "name": "question3",
       "visibleIf": "{panel.question1} notempty and {panel.question2} notempty"
      }
     ]
    }
   ]
  }
 ]
};
```

Because the dynamic panel happens to be named `"panel"`, it looks like the logic must be written as `{${panelName}.${questionName}}`, when in fact `panel` is a keyword in the logic expression for `the current dynamic panel's instance`. In other words, even if your dynamic panel is named `opinions`, the logic will be `panel.question1` and not `opinions.question1`.
