### ISSUE TITLE
react survey does not get populated with preloaded data in dropdown question with restful options

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#2009]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?
survey does not get populated with preloaded data in dropdown question with restful options. It seems that the last working version was 1.5.3

### What is the expected behavior?

work as it used to till 1.5.3

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/TvZ5VtJh6nYIo7yaNoOf?p=preview

**Comment by andrewtelnov** [comment]
@masciugo Thank you, we will take a look.

Andrew
