### ISSUE TITLE
Copy content of a read only widget

### ISSUE THREAD

**Issue by tkon3** [surveyjs/survey-library#2010]
### Are you requesting a feature, reporting a bug or asking a question?

Question.
Is there a way to allow the user to copy some content (text) from a readonly comment widget with a predefined value?
Thank you.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: 1.5.12

**Comment by andrewtelnov** [comment]
@tkon3 You can do it right now. Please look at [read-only example](https://surveyjs.io/Examples/Library?id=survey-displaymode).

Thank you,
Andrew

**Comment by tkon3** [comment]
Thank you.
I think I was not clear about my question.
Can a user manually select and copy the content (or a part) from the read only comment widget? 
It is disabled in the example.

**Comment by andrewtelnov** [comment]
@tkon3  Yes, it can. You can try it by yourself.

Thank you,
Andrew

**Comment by tkon3** [comment]
@andrewtelnov Just rechecked
It's actually working on Chrome but not on Firefox in my case. 

Thank you.

**Comment by andrewtelnov** [comment]
@tkon3 I would leave this issue since it depends how browsers implements this functionality.

Thank you,
Andrew
