### ISSUE TITLE
Automatic navigation to next page - other option in dropdown shows error

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#2014]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?

![ezgif-5-210d12c2c814](https://user-images.githubusercontent.com/547021/75779109-581d2900-5d59-11ea-867c-316e1d315223.gif)

### What is the expected behavior?

SurveyJS should know that selecting other means we're not done yet; now the user is greeted with a big error that is very unexpected.

### How would you reproduce the current behavior (if this is a bug)?
Enable `automatically go to next page` behavior create a question that has an `other` option.

### Specify your

* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: *.12

**Comment by andrewtelnov** [comment]
@SamMousa What do you think? Should we disable the ability to go to next page if an end-user select other?

Thank you,
Andrew

**Comment by SamMousa** [comment]
I think this should be done more abstract, this way we can support custom question types as well.

What about validating the question silently and only attempting navigation if it succeeds?

**Comment by SamMousa** [comment]
Silently meaning don't show markup for failed or successful validation

**Comment by SamMousa** [comment]
I guess the core library could offer this via events, so that a question can fire something when it is complete?

**Comment by andrewtelnov** [comment]
@SamMousa We have public supportGoNextPageAutomatic(); that some questions overrides, it returns false by default. We check for errors silently as well, probably there is a bug, I have to check.
Here is [the link to the code](https://github.com/surveyjs/survey-library/blob/master/src/survey.ts#L3843).
Here is my question:
Should we disable this functionality for radio group/dropdown when the other is choosen or go to the next page, when the other/comment field is filled? What do you think?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@SamMousa I decided to go to the next page on setting value to other comment. The issue is fixed. The fix will be available in the next minor update that we will relese on this week.

Thank you,
Andrew
