### ISSUE TITLE
Tagbox + choises by url + numeric id = not updating + duplicate values

### ISSUE THREAD

**Issue by xxxKOTxxx** [surveyjs/survey-library#2016]
AFAIK it caused by limitation of Select2 dependency:

> Because the value attribute on a `<select>` tag must be a string, and Select2 generates the value attribute from the id property of the data objects, the id property on each data object must also be a string.     
Select2 will attempt to convert anything that is not a string to a string, which will work for most situations, but it is recommended to explicitly convert your ids to strings ahead of time.

But parsing of my backend data is incapsulated by surveyJs.

As temporary workaround I using onLoadChoicesFromServer callbaсk with manual id converting.

I think it will be better to parse select choices value as text inside surveyJs by default.

I hope my description is clear enough? 

Do You agree with this idea?

**Comment by tsv2013** [comment]
The `onLoadChoicesFromServer` callback was introduced to solve such tasks

**Comment by xxxKOTxxx** [comment]
> The `onLoadChoicesFromServer` callback was introduced to solve such tasks

It looks some "hacky". 

Have you any cases to get choisesByUrl with numeric id?

It'll be much usable to add congiguration option instead fix this issue using hooks.
