### ISSUE TITLE
Validating results on a server for a given survey schema.

### ISSUE THREAD

**Issue by nathan-at-jisc** [surveyjs/survey-library#2021]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question.

So the React SurveyJS component validates values whilst on the Client, which is great.

Let's say I wanted to send my survey response to my API and store it in a DB and wanted to validate, how would I validate on the server (with a given Survey Schema).

### What is the current behavior?

Currently I can send the responses to my API and store this in the DB.

Let's say I had 2 questions:

1. Do you have children? (name: child_1)

2. How many children do you have? (name: child_2)

The second question is only displayed if the user inputs yes. 

So the survey results may look like:

```
{
  child_1: "yes",
  child_2: 2
}
```

This is fine. However if I was sending this to my API, a user may edit it/send a request manually and put:

```
{
  child_1: "no",
  child_2: 2
}
```

Is there any way for me to validate on the server?

**Comment by andrewtelnov** [comment]
@nathan-at-jisc Transfered to the correct repo.

Thank you,
Andrew

**Comment by nathan-at-jisc** [comment]
@andrewtelnov Many thanks for the quick response, this looks like a good way to do it (as we are using a Node backend). Appreciate the help, if I have any further questions I'll post them in the correct repo.

Cheers,
Nathan
