### ISSUE TITLE
Very weird behaviour when using react dev tool 

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#2024]
### Are you requesting a feature, reporting a bug or asking a question?

I don't know exactly

### What is the current behavior?

It seems that chrome react dev tool interferences with survey-react

### How would you reproduce the current behavior (if this is a bug)?

1. open an official example like https://surveyjs.io/Examples/Library?id=questiontype-text&platform=Reactjs&theme=modern#
2. pop it up in a separate window
3. open the inspector 
4. go to components tabs
5. as soon as click the survey component survey-react runs the hasErrors function!

![Mar-10-2020 18-40-00](https://user-images.githubusercontent.com/454321/76342736-5924fc00-62ff-11ea-9a08-cd1f84a795dc.gif)

I could never imagine this. It was really hard to find the reason hasErrors run. Being forced to close the react dev tool while trying to debug react code should not be an option

**Comment by tsv2013** [comment]
Your gif is too small. What exact react-dev-tool are you using?

**Comment by masciugo** [comment]
Sorry for the gif but there's not so much to see actually. When you inspect the Survey component in the tool tab, clicking on it, errors in the survey appears. 

The tool is https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi.

thank you
