### ISSUE TITLE
Date validation doens't work in matrixdynamic 

### ISSUE THREAD

**Issue by rocker8942** [surveyjs/survey-library#2025]
### Are you requesting a feature, reporting a bug or asking a question?

This is a bug. 

### What is the current behavior?

A date validation doesn't work. When it's set to validate if the date is larger than 2014-04-16

### What is the expected behavior?

When 01/01/2015 entered, it should pass. But the date validation failed with the message, The expression: 2015-10-01 >= '2014-06-16' should return 'true'. 

### How would you reproduce the current behavior (if this is a bug)?

Please see the plnkr, I created. This will reproduce the bug. 
https://plnkr.co/edit/B69CExZMWjlirBTg

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/B69CExZMWjlirBTg

The code is in the link above. 

### Specify your

* browser: Google Chrome
* browser version: Version 80.0.3987.132 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jqeury
* surveyjs version: 1.5.13

**Comment by tsv2013** [comment]
If you start debug your sample you will see that you are comparing two dates.

You need to imlement a custom functions to compare dates. Here is the live sample - https://plnkr.co/edit/vMl2EGm59EKXyl07

Here is the documentation link - https://surveyjs.io/Documentation/Library#conditions see the "Using functions in expressions" section

**Comment by rocker8942** [comment]
Thanks @tsv2013 , 
That's a great tip. Appreciate it. 
However, the expression that I've written is auto-generated when used survey creator. Oh, is that then need to raise in the creator project than here?
