### ISSUE TITLE
Trigger from MatrixDynamic to setValue in the same MatrixDynamic

### ISSUE THREAD

**Issue by VGamezz19** [surveyjs/survey-library#2026]
Hello, we are facing a problem trying to manage a trigger event inside a MatrixDynamic.

### What is the current behavior?

Currently, on changing the field in MatrixDynamic, we have a trigger who have the responsavilitie to sett the other fields from the same MatrixDynamic (the same row). The fact is, the trigger works as expected, and capture the runexpression trigger, but the setValue() dosen't fill target fields. 

### What is the expected behavior?

The expected behavior should update the other fields from a fieldName dynamicMatrix trigger

```
// products is the DynamicMatrix name
// This code is executed insed the same dynamicMatrix trigger

surveyModel.setValue('products', [
       {productName:'prod 01'} // thats just  a test, it dosen't update anything
]);
```

**Comment by andrewtelnov** [comment]
@VGamezz19 I am afraid it is not possible to do it via trigger mechanism right now.
If you host SurveyJS Library on your own page, then you can handle [survey.onMatrixCellValueChanged](https://surveyjs.io/Documentation/Library?id=surveymodel#onMatrixCellValueChanged) event and do what you need.
I did not check the code, but it should work
```js
survey.onMatrixCellValueChanged.add(function(sender, options) {
  if(options.question.name != "yourMatrixQuestionName") return;
  if(options.columnName != "yourCopyFromColumnName") return;
  options.getCellQuestion("yourCopyToColumnName") = options.value;
});
```

Thank you,
Andrew

**Comment by VGamezz19** [comment]
Grate, it works as we expected! ty @andrewtelnov

**Comment by VGamezz19** [comment]
Hello, I will re-open this issue, just for a question @andrewtelnov.

We are get inizalizating this MatrixDynamic with data:

```
 const surveyResults = await // service call
 surveyModel.data = surveyResults.value;
 surveyModel.currentPageNo = 0;
```

It render all data in MatrixDynamic (work as expected), but then the trigger from it will execute, and this is not the expected behaviour. I understand that the trigger its executing cause the new value from MatrixDynamic, becouse at the begining, it start as empty, and then, fill with all data.

There is any way, to restrict trigger executions, or knowing if survey just finish on render, etc.

**Comment by andrewtelnov** [comment]
@VGamezz19 As a work-around, you may add a variable to your trigger expressions.
```js
 const surveyResults = await // service call
surveyModel.setVariable("runTriggers", false);
 surveyModel.data = surveyResults.value;
 surveyModel.currentPageNo = 0;
surveyModel.setVariable("runTriggers", true);
```
And you expressions in triggers, `expression: "YourCurrentExpression and runTriggers"`.

Thank you,
Andrew

**Comment by VGamezz19** [comment]
@andrewtelnov thanks you so much for answering the issue asap.
The fact is, that we are executing the "trigger" with Matrix CellValueChanged event.
Its is possible to disable the event in a particular time?

```
surveyModel.onMatrixCellValueChanged.add((sender: any, options: any) =>
          onValueChangeTrigger.dynamicMatrix(sender, options)
        );
```

**Comment by VGamezz19** [comment]
Hello @andrewtelnov  we identify a method named `onAfterRenderPage` where we can manage when survey already finish on its render. The fact is, in our MatrixDynamic we have a dropdown fill it with an URL (async way), so, it will trigger the event "onMatrixCellValueChanged" although we manage render on survey.

There any way to manage when survey already finish to render ALL data, including HTML, json data and Ajax data? like `survey.onFinishLoad()` or some like that

**Comment by andrewtelnov** [comment]
@VGamezz19 Probably ``onAfterRender`` is not the best event for this.
Could you explain your flow in greater detail?
You are getting your JSON from your service, create survey, set data from your service, set them.
Probably ``onMatrixCellValueChanged`` event should not be called and this is the bug. Please tell us more about your scenario.

Thank you,
Andrew

**Comment by VGamezz19** [comment]
@andrewtelnov  we got it! we manage the dropdown load inside the trigger method of the `onMatrixCellValueChanged`  by `isChoiseLoaded`

```
    if (!options.getCellQuestion(options.columnName).isChoicesLoaded) {
      return;
    }
```
thanks you so much for your time, i'll close issue
