### ISSUE TITLE
Use survey responses in text fields

### ISSUE THREAD

**Issue by nedakhan** [surveyjs/survey-library#2027]
### Are you requesting a feature, reporting a bug or asking a question?

Requesting a feature

### What is the current behavior?

You can only use survey responses in question text but not having it show up in survey responses.

### What is the expected behavior?

You can include response variables in the survey text field so you can combine responses and have it be editable to someone filling out the survey.

### How would you reproduce the current behavior (if this is a bug)?

N/A

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@nedakhan Sorry, could you please describe your question in more details? I can't understand it.
Are you looking for [this functinality](https://surveyjs.io/Examples/Library?id=survey-data)?

Thank you,
Andrew

**Comment by nedakhan** [comment]
Hi, yes sorry. We want to basically ask a few free text questions and then at the end of the survey, take those responses and combine them into one and present that combined response to the person filling out the form so that they can edit it. Does that make more sense?

**Comment by nedakhan** [comment]
Hi, just checking in. Do you need any more clarification?

**Comment by andrewtelnov** [comment]
@nedakhan Sorry for missing your comment. I am afraid I am not, since I still believe that you are looking for functionality of setting pre-defined data and I sent you the link on the example in my previous answer.

Thank you,
Andrew

**Comment by nedakhan** [comment]
![Screen Shot 2020-03-16 at 2 57 31 PM](https://user-images.githubusercontent.com/40066632/76791099-86a5f580-6796-11ea-803f-0583eab031a3.png)

Maybe the screenshot will help. We have survey that asks several free text questions to build a story/prompt. At the end, we combine their responses to show them their final prompt but we want to make that final prompt editable. How do I go about doing that?

**Comment by andrewtelnov** [comment]
@nedakhan Are you looking for [text processing functionality](https://surveyjs.io/Examples/Library?id=survey-processtext)?

Thank you,
Andrew

**Comment by nedakhan** [comment]
No I'm not looking to process it. I'm just looking to combine responses and display it to the person filling it out in an editable field.
