### ISSUE TITLE
Server side Validation for all pages in single click

### ISSUE THREAD

**Issue by mkoteswararao08** [surveyjs/survey-library#2029]
### Are you requesting a feature, reporting a bug or asking a question?

 feature

### What is the current behavior?

Server side Validation is happening each page separately.

### What is the expected behavior?

we want server side validation should happen for all the pages in single click.

### How would you reproduce the current behavior (if this is a bug)?
Have a form with two or more pages and do server side validation. currently for each page it is calling validation and moving to next page. In my scenario we want validation should happen for all pages in single click and with out moving to next page.
 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version:

**Comment by andrewtelnov** [comment]
@mkoteswararao08 Sorry, we missed this question.
The solution is pretty simple. You can still use ``survey.onServerValidateQuestions`` event, as shows in [this example](https://surveyjs.io/Examples/Library?id=validators-server). However, you can do nothing if ``survey.isLastPage`` returns false.
When it is the last page, then you can do the validation. You can pass survey.data to your server, validate them. If there is an error on previous page then you should run the code that looks like this:
```js
//get the first question with error
var erroredQuestion = survey.getQuestionByValueName(yourErroredQuestionKey);
//Go to the page where the question is located
survey.currentPage = erroredQuestion.page; 
//Show the error
erroredQuestion.addError(new Survey.SurveyError(YourErrorText);
```

Thank you,
Andrew
