### ISSUE TITLE
Corrected Spanish translation for "Complete" button

### ISSUE THREAD

**Issue by agrippa** [surveyjs/survey-library#2031]
The current Spanish translation of "Complete" in spanish.ts is "Completo". According to native Spanish speaking members of my team, this translates most directly into "Completed" (adjective), whereas I think a more accurate translation would be to a verb. Our team would like to suggest that the Spanish word used be changed to "Completar" (verb).

This text is defined here:

https://github.com/surveyjs/survey-library/blob/f25840cef04fb788ac265f6c545332048252bc24/src/localization/spanish.ts#L6

### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

Complete (verb) is translated to Completo (adjective).

### What is the expected behavior?

Completed (verb), as in to complete the survey by clicking this button, should be translated to another verb (Completar, in this case, for Spanish).

### How would you reproduce the current behavior (if this is a bug)?

View the last page of any survey with your browser configured in the Spanish language.

**Comment by agrippa** [comment]
If there aren't any objections to this change, I'm happy to submit a pull request against this issue.

**Comment by andrewtelnov** [comment]
@agrippa Unfortunately, I am not an expert in Spanish. The initial translation was done by @SlowburnAZ and then some correction was done by @marti1125.
If your Spanish native speakers agree that it would be better then I do not have any objection.
You may want to add some missing strings into Spanish translation as well. You can compare with [english file](https://github.com/surveyjs/survey-library/blob/master/src/localization/english.ts) which is twice as big.

Thank you,
Andrew

**Comment by marti1125** [comment]
I agree with @agrippa "Completar" or "Finalizar" yep is correct for `completeText: "Completo",`

**Comment by andrewtelnov** [comment]
@agrippa @marti1125 I have change the string by the commit above.
If you have time to translate and share some missing spanish localized strings, it would be great!

Thank you,
Andrew
