### ISSUE TITLE
Incorrect radiogroup option selected on click

### ISSUE THREAD

**Issue by PranavSakthivel** [surveyjs/survey-library#2033]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
3rd page of the survey, I have to click twice to select a radiogroup option. The first click selects a random radiogroup option on the survey.

### What is the expected behavior?
Clicking the radiogroup choice should select the option the user clicks on.

### How would you reproduce the current behavior (if this is a bug)?
Not sure, as the first 2 pages work fine. 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: Survey Creator and ReactJS
Tested on Survey Creator:
![github](https://user-images.githubusercontent.com/33013003/76806404-8ad61100-679e-11ea-8f15-f633ff896611.gif)

### Specify your

* browser: Firefox, Chrome
* browser version: 74.0, 80
* surveyjs platform (angular or react or jquery or knockout or vue): ReactJS and Survey Creator
* surveyjs version: 1.5.15 (latest as of 3/16/20)

**Comment by andrewtelnov** [comment]
@PranavSakthivel Please provide your JSON, so we can investigate it. However, I believe you have the same un-unique values in your choices.

Thank you,
Andrew

**Comment by PranavSakthivel** [comment]
Hi Andrew, thanks for the response. Some of the answers do have the same un-unique values, as I want to use the values of each answer to calculate a score at the end of the survey. Some of the JSON is company property so I can offer the JSON of the page that is having issues (the questions in the screenshot). 

`{
            name: "page3",
            elements: [
                {
                    type: "radiogroup",
                    name: "approximateAge",
                    title: "Please indicate your approximate age:",
                    isRequired: true,
                    choices: [
                        {
                            value: "4",
                            text: "Below 40"
                        },
                        {
                            value: "12",
                            text: "40-50"
                        },
                        {
                            value: "24",
                            text: "50-60"
                        },
                        {
                            value: "24",
                            text: "60-70"
                        },
                        {
                            value: "12",
                            text: "70-80"
                        },
                        {
                            value: "4",
                            text: "Above 80"
                        }
                    ]
                },
                {
                    type: "radiogroup",
                    name: "describeYourself",
                    title: "How would you describe yourself?",
                    isRequired: true,
                    choices: [
                        {
                            value: "0",
                            text: "Very Active"
                        },
                        {
                            value: "0",
                            text: "Want to be more active"
                        },
                        {
                            value: "0",
                            text: "Somewhat Active"
                        },
                        {
                            value: "0",
                            text: "Inactive"
                        }
                    ]
                }
            ]
        }`

**Comment by andrewtelnov** [comment]
@PranavSakthivel The value should be unique. This is the requirement. If you write html, you would have to set unique values into html elements as well. It can't work otherwise.

For your scenario, you can add a custom property into "itemvalue", choice, object. Please look at [this example](https://surveyjs.io/Examples/Library?id=questiontype-matrixdynamic-totals&platform=jQuery).

Thank you,
Andrew
