### ISSUE TITLE
Cannot change Boolean value after first click

### ISSUE THREAD

**Issue by tDuy** [surveyjs/survey-library#2034]
I'm reporting a bug

### What is the current behavior?
At the default value, Boolean does not update to Yes unless I double click on it.
This occurs in IE and Edge only. It works fine in Chrome and Firefox.

### What is the expected behavior?
The switch should change to Yes after a click.

#### Provide the test code and the tested page URL (if applicable)
Tested page URL:
https://surveyjs.io/Examples/Library/?id=questiontype-boolean&platform=Reactjs&theme=default#content-result

### Specify your
* browser: IE, Edge
* browser version: IE 11.719.18362.0, Edge 44.18362.449.0
* surveyjs platform: react
* surveyjs version: 1.1.31

**Comment by dk981234** [comment]
Hello,

We've fixed the bug via the attached commit. The fix will be available with the next minor update.

Thanks
Dmitry
SurveyJS Team
