### ISSUE TITLE
markdown and questionTitleTemplate

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#2035]
### Are you requesting a feature, reporting a bug or asking a question?

question/bug

### What is the current behavior?

when using questionTitleTemplate, markdown text is not correctly escaped

### What is the expected behavior?

In my specific usecase I'd like to swap required symbol and title order, so I used `questionTitleTemplate: '{require} {title}'`. 
I can partially fix whats rendered changing the required text from `requiredText: "* "` to `requiredText: "&#42;"` but markdown text is not correctly escaped

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/5GVv4X9gS7NqYw45

**Comment by andrewtelnov** [comment]
@masciugo We wanted to change text processing for our titles. Right now, here is the updated code for event:
```js
survey.onTextMarkdown.add(function(survey, options) {
    //convert the mardown text to html
    var prefix = "";
    if(options.text.indexOf("* ") == 0) {
        prefix =  "* ";
        options.text = options.text.substring(2);
    }
    var str = converter.makeHtml(options.text);
    //remove root paragraphs <p></p>
    str = str.substring(3);
    str = str.substring(0, str.length - 4);
    //set html
    options.html = prefix + str;
});

```

**Comment by masciugo** [comment]
Thank you. Does the above code will not be need or, worse, may be incompatible with new text processing?

**Comment by andrewtelnov** [comment]
@masciugo According to [this change](https://github.com/surveyjs/survey-library/issues/2040), You will need to set ``survey.questionTitlePattern`` to "numRequireTitle" or to "requireNumTitle" and that is all. onTextMarkdown should work for title part only only,

Thank you,
Andrew

**Comment by masciugo** [comment]
ok, I'll follow #2040 then. thanks
