### ISSUE TITLE
[Question]: Checkbox - `hasNone` disables other choices

### ISSUE THREAD

**Issue by jeffbirkholz** [surveyjs/survey-library#2036]
### Are you requesting a feature, reporting a bug or asking a question?

Question, potentially feature.

### What is the current behavior?

Currently for a checkbox `hasNone` will clear the other selections and vice versa.

Is there a way to disable the other selections when `None` is selected? I thought I could use `triggers` however I have many checkboxes so that would get tedious to handle all of them. 

It could be handy if it was just a flag to pass in with the object. Something like this: `disableOptions: {choice} = 'none'` 

### What is the expected behavior?
N/A

### How would you reproduce the current behavior (if this is a bug)?
N/A

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: N/A

Test code

```
        {
          name: 'choice',
          type: 'checkbox',
          title: 'Which choice is best?',
          isRequired: true,
          colCount: 1,
          hasNone: true,
          noneText: 'None / NA',
          choices: [
            'choice 1',
            'choice 2',
            'choice 3',
          ],
        },

```

**Comment by andrewtelnov** [comment]
@jeffbirkholz Here is [the example](https://plnkr.co/edit/ZKDWNy2NNjMR0NI5).
You have to add the follwing code: ``choicesEnableIf: "{item} == 'none' or {choice} != ['none']"``

Thank you,
Andrew

**Comment by jeffbirkholz** [comment]
Awesome! Thanks so much for the fast response.
