### ISSUE TITLE
Validation with scrollIntoView with a fixed position header

### ISSUE THREAD

**Issue by koyan** [surveyjs/survey-library#2044]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
When a field is validated, if it is wrong, the page scrolls to make it visible. This happens using scrollIntoView. When a fixed position header exists in the page though, the field and the validation message are bellow the fixed position header. 

### What is the expected behavior?
One of the following: 
-  a different method is used for scroll, 
- an field for scrollIntoView offset is provided (and applied with the solution at: https://stackoverflow.com/questions/13614112/using-scrollintoview-with-a-fixed-position-header ) 
- 

### How would you reproduce the current behavior (if this is a bug)?
Create a fixed height header. Make the survey go behind it. Fill in the survey, make an error, let it validate/scroll to the issue with the error

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://plnkr.co/edit/eU6IJGK5TrUtQgYS

### Specify your

* browser:
Chrome
* editor version:
80.0.3987.149

**Comment by andrewtelnov** [comment]
@koyan I am afraid there is no way to get the height of a fixed header height for a general case. I guess, the only solution is to raise a question where you can correct the scolling.
What do you think?

Thank you,
Andrew

**Comment by koyan** [comment]
> I guess, the only solution is to raise a question where you can correct the scolling.
> What do you think?
I am not sure what you mean by "raise a question where you can correct the scrolling". 
Do you mean a setting, or a config value? (If yes, that would be perfect).

**Comment by andrewtelnov** [comment]
@koyan Oh, my bad :) raise an event of course. Do you have a height on that you need to correct the scrolling?

Thank you,
Andrew

**Comment by koyan** [comment]
Oh, if you raise an event, then I can correct the height on my own! That would be great.

**Comment by andrewtelnov** [comment]
@koyan I have added a new event into survey object. It will come with v1.5.18 that we are going to release on the next week. You will have to add the following code:
```js
      survey.onScrollingElementToTop.add(function(sender, options) {
        options.cancel = true;
        //Your code to scroll to DOM element where it's id equals to options.elementId 
      });

```
Here is the [related GitHub issue](https://github.com/surveyjs/survey-library/issues/2047).

Thank you,
Andrew

**Comment by koyan** [comment]
Thank you very much!!!!!!
