### ISSUE TITLE
Single boolean question vs. going to the next page automatically

### ISSUE THREAD

**Issue by msbt** [surveyjs/survey-library#2048]
### Are you requesting a feature, reporting a bug or asking a question?
A logic bug, or maybe I'm missing something

### What is the current behavior?
I'm trying to build a one-question-per page questionnaire with 6-7 questions in total. To reuse an example of a solved issue, lets assume this scenario:

Question 1 is "Do you have a car?" with a boolean question yes/no. I want the form to continue to the next question via the setting "On answering all questions, go to the next page automatically". If people say no/false, there should be a follow-up boolean with "Do you want to buy one?" (on a new page or directly afterwards, doesn't matter where) which follows the logic "enable and visible if  `{car} = false`". So far so good, but no matter where I click on the boolean item, its behaviour always goes to true first before I can switch it to false. In this scenario, you can only answer yes and proceed to the next question immediately without being able to answer no and get to see the other question, does that make sense?

### What is the expected behavior?
If I click on the left side of the boolean button, it should go to the left/false and if I click on the right side, it should go to right/true.

### How would you reproduce the current behavior (if this is a bug)?
As stated above.

### Specify your

* browser: Firefox/Chrome
* browser version: Latest

**Comment by andrewtelnov** [comment]
@msbt Yes, it sounds like a bug to me. I make [an example](https://plnkr.co/edit/g1cAf105LuEh1Kp4) and it is clear doesn't work correctly.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@msbt There are actually two separate issues.

At first I think that boolean question should not support GoToNextPageAutomatic functionality. I have removed this support by the commit above. Now on changing boolean question value survey will not go on the next page.

Second issue, when the boolean value is undefined boolean value becomes true first and on the second click false. It works fine for checkbox style boolean question, but it looks strange for toggle style. We will try to determinate the toggle element area and based on that set true or false value. 

Thank you,
Andrew

**Comment by msbt** [comment]
@andrewtelnov Sounds great, thanks!
