### ISSUE TITLE
inputType date saved format

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#2049]
### Are you requesting a feature, reporting a bug or asking a question?

question/feature

### What is the current behavior?

When using date input there is no way to force date format. Users may not use datepicker and type incomplete dates. Moreover if they use safari browser for example, datepicker does not even pop up and they can type any string. Just try https://surveyjs.io/Examples/Library?id=questiontype-text&platform=Reactjs&theme=modern

### What is the expected behavior?

I would like surveyJS take care of date format someway. Maybe setting _placeholder_ html5 attribute may solve (https://stackoverflow.com/questions/35682138/html5-date-picker-doesnt-show-on-safari#answer-35682391). I need to force format even when browser localization settings try to apply default formats. 

Maybe using a custom widget like Bootstrap Datepicker will let me force date format but I'd like a browser native solution if any

thank you

**Comment by andrewtelnov** [comment]
@masciugo Yes, I believe we can calculate the current date format on the client machine and display it in the place holder.

Thank you,
Andrew

**Comment by Evertude** [comment]
Would also be great if it adapts to the survey locale (e.g. dd.mm.yyy for de vs. mm/dd/yyyy for en)

**Comment by masciugo** [comment]
in the meantime I had to use bootstrap datepicker which not only let you specify date format but also distinguish between the one used to show the date in the input field and the one used to store data
