### ISSUE TITLE
Survey translation don't work

### ISSUE THREAD

**Issue by benouaghremhamza** [surveyjs/survey-library#2065]
`pages: [
  {
   name: "pre_adult_yes_no",
   elements: [
    {
     type: "radiogroup",
     name: "adult",
     title: {
      default: "0avez plus de 18 ans ?",
      en: "Are you over 18?"
     },
     isRequired: true,
     choices: [
      {
       value: "yes",
       text: {
        en: "B",
        default: "Oui"
       }`

I Added english translation to a french survey , but switching survey locale changes only survey error messages , previous and next button , but do not switch values like questions title and choices

**Comment by andrewtelnov** [comment]
@benouaghremhamza You set the default location "fr". I guess you did it in Survey Creator. In this case you should tell survey that the default location is "fr" and not "en" now.
``Survey.surveyLocalization.defaultLocale = "fr";``

Here is the [working example](https://plnkr.co/edit/NlPBBMcMLhF3ARiE).

Thank you,
Andrew

**Comment by benouaghremhamza** [comment]
Thank you 👍
