### ISSUE TITLE
Dropdown - Vue - injected data is not displaying well

### ISSUE THREAD

**Issue by aloiseau17** [surveyjs/survey-library#2066]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting bug on vue platform with dropdown component

### What is the current behavior?
When data is injected on display mode
```js
survey.data = {
    car: ['Ford']
};
survey.mode = 'display';
```

Dropdown is displaying like this :
![image](https://user-images.githubusercontent.com/19550407/78349667-3d321480-75a4-11ea-8fab-d22520f0c3c2.png)

### What is the expected behavior?
I expect only first array item is displaying, not surrouding with '[ ]'.
It's correctly displayed with jQuery implementation for example: https://plnkr.co/edit/qNKNiYVO6OBwfdXp

### How would you reproduce the current behavior (if this is a bug)?
Create a form with a dropdown question and display mode then inject data inside.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/EocuocRDUdWPJfUR

Test code

```js
Survey
    .StylesManager
    .applyTheme("modern");

var json = {
    questions: [
        {
            type: "dropdown",
            name: "car",
            title: "What car are you driving?",
            isRequired: true,
            colCount: 4,
            choices: [
                "None",
                "Ford",
                "Vauxhall",
            ]
        }
    ]
};

window.survey = new Survey.Model(json);

survey.data = {
    car: ['Ford']
};
survey.mode = 'display';

var app = new Vue({
    el: '#surveyElement',
    data: {
        survey: survey
    }
});


```

### Specify your

* browser: chrome
* browser version: Version 80.0.3987.149
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.5.18

**Comment by tsv2013** [comment]
You needn't to use square brackets in data:
```JS
survey.data = {
    car: 'Ford'
};
```
Here is the updated plunker - https://plnkr.co/edit/ga5NENkzlyhpcj7g

**Comment by aloiseau17** [comment]
Thank you for your response but I receive data in this format for dropdown.

What you suggest is to parse data and replace array with string. Lots of work I think, especially after I try the same rendering with jQuery instead of Vue.
If you check the example sent above with jQuery, it works well.

Here is the link back [https://plnkr.co/edit/qNKNiYVO6OBwfdXp?preview](https://plnkr.co/edit/qNKNiYVO6OBwfdXp?preview)

**Comment by andrewtelnov** [comment]
@aloiseau17 That is not a good idea to do what you do. You are modifying DOM and if SurveyJS Library decided to re-render the question, html element will be updated and comeback to the origional version.
We gave you the right approach, you can do what ever you want of course, but your approach can lead to non-stable code. 

Your code doesn't work, because in your case, question.name is "car" and you do not have an option with "car" value.
```js
   var el = document.getElementById(options.name); //options.name equals to car
    if (el) {
        el.value = options.value;
    }
```

Thank you,
Andrew

**Comment by aloiseau17** [comment]
Sorry but I think there is misunderstanding. Sorry for my bad english.

I'll try to reword my question.

I did two plunker demo: 
- one with VueJS platform : https://plnkr.co/edit/EocuocRDUdWPJfUR
- the other with jQuery platform : https://plnkr.co/edit/qNKNiYVO6OBwfdXp?preview

I do exactly the same: 
```
survey.data = {
    car: ['Ford']
};
```
**But result is different. Why ?**

For me right behavior is jQuery rendering.

**Comment by aloiseau17** [comment]
Does my question more understandable or not ?

**Comment by tsv2013** [comment]
Your code with array is wrong. The dropdown question doesn't accept array as value. The data should be a single value, not an array:
```JS
survey.data = {
    car: 'Ford'
};
```
for all framaworks - jQuery/Vue/Angular and so on

**Comment by aloiseau17** [comment]
Ok fine, so there is effectively a problem with jQuery platform. That's right ?

**Comment by tsv2013** [comment]
No. The code from my previous post should work for the dropdown question for all platforms.

Unless I misunderstand your question....

**Comment by aloiseau17** [comment]
Yes it works :) but I'm talking about the two demo plunker. Behaviors are different. 

With [demo jQuery](https://plnkr.co/edit/qNKNiYVO6OBwfdXp?preview): **wrong code with bracket, is working.**

```js

survey.data = {
    car: ['Ford']
};
```

**Comment by tsv2013** [comment]
It's an unexpected side-effect.
