### ISSUE TITLE
survey.vue.d.ts => Module not found import("../question") &  import("../panel")

### ISSUE THREAD

**Issue by a599155162** [surveyjs/survey-library#2074]
`Version: "survey-vue": "^1.5.19"` 

![image](https://user-images.githubusercontent.com/28429119/78863668-be8a1b00-7a6c-11ea-8cd7-78cc285089ab.png)

thx~

**Comment by andrewtelnov** [comment]
We missed this issue. Please look at our [vue qick start repository](https://github.com/surveyjs/surveyjs_vue_quickstart).
