### ISSUE TITLE
Adding Pages Dynamically

### ISSUE THREAD

**Issue by kc-nxtbig** [surveyjs/survey-library#2078]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a Question / Feature Request

### What is the current behavior?

1. Say we have a very long Page with nested multiple panels/ panelDynamics/ mtarixDynamics. 
2. To avoid form fatigue, we are using '"questionsOnPageMode": "questionPerPage" so that only a question or a panel is presented to the user.
3. In case we need to **add one more page at (1)** above, if a user chooses to **add more** inputs of all of the above, one way to do that could be to wrap all the elements in the page in a panelDynamic and load one more set of the questions, panels/ panelDynamic and use 'add more' of this panel. 
4. But in this case, since the '"questionsOnPageMode": "questionPerPage" property renders the entire panel, the form becomes too long. The problem gets compounded if there are multiples of such pages to be added.
5. On the other hand, if we programmatically choose to 'add page', if the user wants pause and to resume filling a survey after some time, and reopens the survey - we couldn't figure out a way to get the user started from the previous point as the original JSON will not have this state info.

### What is the expected behavior?

It would be a nice feature, if we can add pages dynamically on similar lines as panelDynamic or matrixDynamic (say, **pageDynamic**).

Or alternately, is there some feature in surveyJS that facilitates adding any number of pages with nested components, that allows us to pause and resume survey from the same point where we left it at earlier - i.e., midway from a page added programmatically - say the fifth such page added?

### How would you reproduce the current behavior (if this is a bug)?

It is not a bug. Falls under the category of a feature request or a query.

#### Provide the test code and the tested page URL (if applicable)

A sample JSON (txt form) is attached

[sample.txt](https://github.com/surveyjs/survey-library/files/4456951/sample.txt)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version: Version 80.0.3987.163 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.5.19

**Comment by andrewtelnov** [comment]
@kc-nxtbig You can always call ``survey.toJSON()`` function to get the current survey json. You can load this json next time a user came to your page.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@kc-nxtbig all our objects has functions:
``public toJSON(): any;``
``public fromJSON(json: any);``

**Comment by kc-nxtbig** [comment]
thank you very much  @andrewtelnov.
shall check this out.
