### ISSUE TITLE
Field inputType Date allows text to be entered in Mac OS Catalina

### ISSUE THREAD

**Issue by twentytwokhz** [surveyjs/survey-library#2091]
### Are you requesting a feature, reporting a bug or asking a question?
Bug report

### What is the current behavior?
User can enter text in a Date inputType field on Mac OS Catalina 10.15.2

### What is the expected behavior?
User should be able to only enter dates in a Date field.

### How would you reproduce the current behavior (if this is a bug)?
You can reproduce it by opening the 
Open this page on Mac OS Catalina (10.15.2 if possible) - it does not reproduce on **Mojave 10.14.6**!
https://surveyjs.io/Examples/Library?id=questiontype-text&platform=jQuery&theme=winterstone

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://surveyjs.io/Examples/Library?id=questiontype-text&platform=jQuery&theme=winterstone

Test code
None
```
your_code_here

```

### Specify your

* browser: Safari
* browser version: default
* surveyjs platform (angular or react or jquery or knockout or vue): check the examples above
* surveyjs version: latest

**Comment by tsv2013** [comment]
SurveyJS is using native browser control to create a date input. Unfortunately in Safari it allows to enter text.

To overcome it you can use 3rd party components, that integrated in SarveyJS as "custom widgets". You can use date picker. Here is the live sample on our site - https://surveyjs.io/Examples/Library?id=custom-widget-datepicker&platform=jQuery&theme=modern

**Comment by twentytwokhz** [comment]
Ok, I assumed this was a library issue. Since I can use the custom widgets, I will close this issue 👍

**Comment by twentytwokhz** [comment]
I forgot to mention this also happens on the inputType Time picker...there is no custom widget for that one. Any ideas? 😕

**Comment by tsv2013** [comment]
Nobody asked a time picker before. You can implement your own one ad a custom widget, taking datepicker as a starting point.
