### ISSUE TITLE
Datepicker textbox question's input field width doesn't equals to other textbox questions 

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-library#2094]
In modern theme datepicker textbox question's input field width doesn't equals to other textbox questions 

![image](https://user-images.githubusercontent.com/30930391/79431825-a158cd80-7fd3-11ea-8357-9856c383dab9.png)

**Comment by tsv2013** [comment]
Can't reproduce if remove width from the question
Working sample - https://plnkr.co/edit/yWgrmGhJ4ereLw9V
