### ISSUE TITLE
Space between questions in panel not wide enough in modern theme

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-library#2095]
Space between questions in panel not wide enough in modern theme (in comparison to space between question not inside panel)

![image](https://user-images.githubusercontent.com/30930391/79432092-057b9180-7fd4-11ea-81fb-3dc643daf287.png)

**Comment by tsv2013** [comment]
Are you sure it should be more? In panel we have smaller font and smaller spaces...

**Comment by tsv2013** [comment]
Fix is straight and quick. But what's the opinion of our designer?

**Comment by gologames** [comment]
We discussed space between questions in panel again. There some problem that space between title and bottom border of unfilled text field is bigger than space between bottom border and next title
![image](https://user-images.githubusercontent.com/30930391/80087174-6de1ea00-8563-11ea-82a2-6ce76514474b.png)

But there no win-win solution for this problem and we decided to stay it as is
