### ISSUE TITLE
`goNextPageAutomatic` on the page level

### ISSUE THREAD

**Issue by jeffbirkholz** [surveyjs/survey-library#2100]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the current behavior?
I have some pages that are simple with one question and others that have multiple questions. If a user navigates back to a pervious page changes an answer on a page with multiple questions, then the survey navigates to the next page. It's a bad experience if the user wants to change multiple answers on that page. 

Is there a way to set `goNextPageAutomatic` at the page level? 

Alternatively, is there a way to block `goNextPageAutomatic` for certain pages?

I've looked through old issues and found: https://github.com/surveyjs/survey-library/issues/206 however it doesn't quite fit my use case.

**Comment by tsv2013** [comment]
You can subscribe the https://surveyjs.io/Documentation/Library?id=surveymodel#onValueChanged event and write your own method that will `tryGoNextPageAutomatic`. Here you can implement any strategy according your needs. Below is our implementation that you can take as a basis.

```JS
  protected tryGoNextPageAutomatic(name: string) {
    if (
      !!this.isEndLoadingFromJson ||
      !this.goNextPageAutomatic ||
      !this.currentPage
    )
      return;
    var question = <Question>this.getQuestionByValueName(name);
    if (
      !question ||
      (!!question &&
        (!question.visible || !question.supportGoNextPageAutomatic()))
    )
      return;
    if (question.hasErrors(false)) return;
    var questions = this.getCurrentPageQuestions();
    if (questions.indexOf(question) < 0) return;
    for (var i = 0; i < questions.length; i++) {
      if (questions[i].hasInput && questions[i].isEmpty()) return;
    }
    if (!this.checkIsCurrentPageHasErrors(false)) {
      if (!this.isLastPage) {
        this.nextPage();
      } else {
        if (
          this.goNextPageAutomatic === true &&
          this.allowCompleteSurveyAutomatic
        ) {
          this.completeLastPage();
        }
      }
    }
  }

```

**Comment by jeffbirkholz** [comment]
@tsv2013 thanks for the info. I think I can make something work out of this for my use case. Appreciate the quick response!
