### ISSUE TITLE
Not able to translate the complete json 

### ISSUE THREAD

**Issue by karishmasahu** [surveyjs/survey-library#2103]
I have a json as: 
json:Object = {
      "title": "Techinal Expertise Feedback Survey Example",
      "pages": [
       {
        "name": "page1",
        "elements": [
         {
          "type": "radiogroup",
          "name": "question5",
          "title": "Work location",
          "isRequired": true,
          "hasOther": true,
          "choices": [
           {
            "value": "item1",
            "text": "Bangalore"
           },
           {
            "value": "item2",
            "text": "Hyderabad"
           }
          ]
         }
]}]}
And I am using:
this.surveyModel = new Survey.Model(this.json);
this.surveyModel.locale = "de";

Then I am not able to localize the complete json. only few properties like complete button, page name are only translated.
Not the json. Any idea what I'm missing.
Thanks in advance.

**Comment by tsv2013** [comment]
Could you please specify - what do you mean under the "complete json"?

**Comment by karishmasahu** [comment]
when i use 
this.surveyModel = new Survey.Model(this.json);
this.surveyModel.locale = "de";

Translation happens only for the previous,next,complete buttons of surveyjs. not on the json data provided.
![image](https://user-images.githubusercontent.com/33975459/79581059-84152380-80e7-11ea-9d16-be16c3048d5f.PNG)

**Comment by tsv2013** [comment]
Your survey JSON is not multi-language. Please check this sample - https://surveyjs.io/Examples/Library?id=survey-multilanguages&platform=jQuery&theme=modern

**Comment by karishmasahu** [comment]
Okay got it, Thanks :)

**Comment by karishmasahu** [comment]
Issue is solved, hence closing the ticket
