### ISSUE TITLE
Partial data saving not working

### ISSUE THREAD

**Issue by karishmasahu** [surveyjs/survey-library#2104]
If a user filling the form and then moves to the next tab, and upon return to the form wants to get the data that is already filled and continue filling from were he has left.
So if there any way to retain the half filled data?

**Comment by tsv2013** [comment]
Yes. You need to store "survey.data" to a variable and then assign it again. Here is the live sample on our site - https://surveyjs.io/Examples/Library?id=survey-editprevious&platform=jQuery&theme=modern

**Comment by karishmasahu** [comment]
Its not working for me, maybe I am missing something.
 I have added this in my onInit() of angular : 
     this.timerId = window.setInterval(() => {
      this.saveState(this.surveyModel);
  }, 10000);
 saveState(survey){
     this.res = {
      currentPageNo: survey.currentPageNo,
      data: survey.data
  };
    window.localStorage.setItem(this.storageName, JSON.stringify(this.res));
  }

The changes made in the form are getting stored in localstorage but once i switch between the tabs, it local storage data getting fluctuate no of times.

**Comment by tsv2013** [comment]
Can you share a minimal live sample illustrating the issue?

**Comment by karishmasahu** [comment]
It was because of my code issue, resolved it. Thanks for the link, helped it!!
