### ISSUE TITLE
"textUpdateMode": "onTyping" prevents most placeHolders from showing

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#2112]
### Reporting a bug?
"textUpdateMode": "onTyping" prevents most placeHolders from showing

### What is the current behavior?
With "textUpdateMode": "onTyping" specified almost all placeholders do not show.
Some placeholders do still show, weirdly enough, for example the first placeholder in a dynamic matrix does show and the second and third placeholders show in a panel with 3 textfields, but most placeholders don't show at all.

### What is the expected behavior?
With "textUpdateMode": "onTyping" the placeholders still need to show, just like with the default setting of textUpdateMode.

### How would you reproduce the current behavior (if this is a bug)?
Create some fields with placeholders and add "textUpdateMode": "onTyping" to see the placeholders disappear.

#### Provide the test code and the tested page URL (if applicable)
https://plnkr.co/edit/pdSfMAuswxPw7Rei

### Specify your

* browser: Chrome & Firefox
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): JQuery
* surveyjs version: 1.5.18 through 1.7.2 for sure

**Comment by andrewtelnov** [comment]
@Lionqueen94 It was fixed via commit above.

Thank you,
Andrew
