### ISSUE TITLE
Categorize list of questions based on section

### ISSUE THREAD

**Issue by karishmasahu** [surveyjs/survey-library#2113]
Is there a way to list out a few questions under one section and rest questions in another section?
Pls refer the screenshot for better clarification.

![image](https://user-images.githubusercontent.com/33975459/79862744-30128380-83f4-11ea-8431-21fffe3d5545.png)

Here as per the screenshot, under "Environment" section, there are few questions. Under "Labor & Human rights" section there are few questions. So can we achieved this kind of layout?

**Comment by andrewtelnov** [comment]
@karishmasahu You can use two panels with property showQuestionNumber = "onpanel". Here is the [example](https://plnkr.co/edit/DpTI0jsF4JwIYn0I).

Thank you,
Andrew

**Comment by karishmasahu** [comment]
Yes thanks for the info. I got it :)
