### ISSUE TITLE
Is it possible to use this without jquery (vanilla js)

### ISSUE THREAD

**Issue by morenoh149** [surveyjs/survey-library#2116]
### Are you requesting a feature, reporting a bug or asking a question?
question

I would like to use this library in a traditional django app. I do not use webpack yet. I use <script> tags to import all my dependencies. 

What files do I need from https://github.com/surveyjs/builds/tree/master/1.7.3 ?

Studying https://surveyjs.io/Examples/Library?id=real-product-fit-market&platform=jQuery&theme=default#

looks like I want

* survey.min.css
* survey.jquery.min.css
* jquery

is it possible to use `survey.core.min.js` and omit jquery?

**Comment by tsv2013** [comment]
The survey-core library contains model only and doesn't have rendering code.

Every our example has  the "Edit in Plunker" button.

Here is the mentioned above example in plunker - https://plnkr.co/edit/U6aGlsqkS02Dzc9q

You can copy/paste it content on your web page.

You can also read this document - https://surveyjs.io/Documentation/Library?id=Add-Survey-into-your-Web-Page

**Comment by morenoh149** [comment]
yes your example uses jquery. Can I use surveyjs without jquery?

**Comment by andrewtelnov** [comment]
@morenoh149 We have framework independed code, SurveyJS Model, then code that uses any of these three frameworks: knockout, react or vue. jQuery and Angular, in fact, using knockout version.

Thank you,
Andrew

**Comment by morenoh149** [comment]
would you accept a PR to bridge the core to vanilla js? it could be as easy as replacing the jQuery calls with the equivalent dom/js apis.

**Comment by andrewtelnov** [comment]
@morenoh149 Why do you want to do it? I believe you want to wrap the knockout version. Why do not use knockout version directly?

Thank you,
Andrew

**Comment by morenoh149** [comment]
I guess I could use the knockout version. But you can see how that is not the obvious package to use for someone new to this library right?

You could clone the knockout version call it vanilla and you would not see these questions come up again :)

**Comment by andrewtelnov** [comment]
@morenoh149 Let us discuss it in the team tomorrow.

Thank you,
Andrew

**Comment by morenoh149** [comment]
To clarify this sounds like a usability issue. It is not clear as someone building a vanillajs project that they should use the selfcontained knockout version. The solution could be to clarify this usecase in the quick start.

As someone unfamiliar with your project I see knockout and I think "I dont want to use any framework. Where is the survey.min.js?"

**Comment by flowt-au** [comment]
+1 for that clarification. I am using the jQuery version thinking that _was_ the "minimal" version. My ignorance, I know, but a clarification in the Getting Started might help if it is not there already. I started using surveyJS a few years ago and have not checked the Getting Started since! ;-) 
Love the product, by the way. :-)

**Comment by andrewtelnov** [comment]
@morenoh149 @flowt-au We have decided to update our docs for now.
[Add Survey into your page](https://github.com/surveyjs/survey-library/blob/master/docs/Add-Survey-into-your-Web-Page.md) and [Library Overview](https://github.com/surveyjs/survey-library/blob/master/docs/LibraryOverview.md#platforms).

Thank you,
Andrew

**Comment by sovetski** [comment]
Any idea if we can use surveyjs without any library like jQuery, React etc.? just vanilla js?

**Comment by andrewtelnov** [comment]
@sovetski Please use the knockout version. [knockoutjs](https://knockoutjs.com/) is a tiny MVVM framework (25K min+gz).
If we would not use knockout, we would have to invent our own anyway.
knockout works with any other framework perfectly.

Thank you,
Andrew

**Comment by ericraider33** [comment]
I downloaded the version specified in the documentation, and found:

JQuery:
survey.jquery.min.js - 1915kb
jquery.min.js - 88kb
2,003kb - total

vs.

KnockOut:
knockout-latest.js - 67kb
survey.core.min.js - 1303kb
survey-knockout-ui.min.js - 209kb
1,579kb - total

So, not exactly 25kb, but still substantially smaller than the JQuery version. 

On a separate note, I'd love to see a version written against VanJS, which is only a couple of kb, without having to reinvite the wheel. KO is a long dead project.
