### ISSUE TITLE
Survey title and description should be responsive

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-library#2118]
Survey title and description are cut on small screens:

![image](https://user-images.githubusercontent.com/3013415/79979354-129ff100-84aa-11ea-86eb-45894f0c8ea9.png)

**Comment by nico-hernandez** [comment]
After struggling I realized this line was missing in my HTML code 
`<meta name="viewport" content="width=device-width"/>`
That's all, now is responsive, thanks @JaneSjs .
