### ISSUE TITLE
Feature Request for Error Validation onBlur

### ISSUE THREAD

**Issue by shekharkc** [surveyjs/survey-library#2120]
### Are you requesting a feature, reporting a bug or asking a question?

Feature request.

### What is the current behavior?

checkErrorsMode has three options - onNextPage, onValueChanged and onComplete.

### What is the expected behavior?

One of the most common options to validate is onBlur. onValueChaged works quite fine for most cases but triggers validation prematurely occasionally. E.g upon partial entry in a Date field. 

It would be nice to have one more option to trigger validation when the user focuses away after an input (onBlur event). Alternately, limit trigger to occur after the user enters a minimum number of characters.

### How would you reproduce the current behavior (if this is a bug)?
Feature request.

#### Provide the test code and the tested page URL (if applicable) 
Not applicable

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version:Version 81.0.4044.122 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: latest

**Comment by tsv2013** [comment]
Sorry but I don't understand how it helps with the "partial entry in a Date field"

**Comment by shekharkc** [comment]
@tsv2013 ,

The suggestion I was making is to give an option to do the validation after the user finishes his input entry and/or focuses away from the input field. Else, quite often the 'Error' message is being triggered even before the entry is completed.

On the other hand, there is this additional related issue of the _user being navigated away from the current question even before completing the entry & next question being displayed_  - when the 'QuestionsOnPageMode' is set to 'questionPerPage'  & navigate 'auto' on answering questions. 

Thought I will bring this issue to notice separately.

**Comment by tsv2013** [comment]
If the https://surveyjs.io/Documentation/Library?id=surveymodel#textUpdateMode is set to `onBlur` and the https://surveyjs.io/Documentation/Library?id=surveymodel#checkErrorsMode is set to `onValueChanged` you should get the behavior you are requesting for.

In this case value will be updated `onBlur` and after that validation will be performed. This looks like exactly your scenario. Isn't it? Doesn't is work in some cases?

Could you describe exactly your use case?

**Comment by shekharkc** [comment]
Hi,

There are two issues here that I referred to.

You've described the first use-case correctly. What you suggested seemed like an option that should work. But, it surprisingly didn't.

1.  **Allowing a setting for Error Validation to be Done After user Focuses Away (onBlur) from the Input Box**  As a good UX, some recommend error validation to be done after a user completes input (onBlur) - immediate enough, but not too early.

I would have imagined it to work with the settings you suggested, i.e _value will be updated onBlur and after that validation will be performed. 

` "checkErrorsMode": "onValueChanged",
 "textUpdateMode":"onBlur"`

However, even with the above settings, the validation is still being done before the onBlur event.  
PFA the screenshot.

![Slide2](https://user-images.githubusercontent.com/32909897/80104755-3c821200-8595-11ea-867e-17f8021beb85.JPG)


However, this is just a minor issue one can live with.


2. **Second Issue of Premature Navigation Away -  Results in Bad UX**

With the following settings:
`"goNextPageAutomatic": true,
 "checkErrorsMode": "onValueChanged",
 "questionsOnPageMode": "questionPerPage"
 "textUpdateMode":"onBlur"
`
The user is being navigated away from the current question even before completing the entry, especially with a date field & next question being displayed. Please see the linked jumpshare video to understand.

https://jmp.sh/ls9GEN6

 Here the user **could not enter the Date of Birth even after three attempts**, as the user is being navigated away prematurely.

Is this a known issue? Any suggestions on how to address this?

Thanks

**Comment by tsv2013** [comment]
If first dosen't work for the date field only - it's a bug. We'll check it and fix.

**Comment by tsv2013** [comment]
Can you share s survey JSON to reproduce it?

**Comment by Tri125** [comment]
This feature request could help with the error validation firing prematurely for matrix questions.

With checkErrorsMode set to 'onValueChanged' with a matrix question where both the question is required and answer for all rows is required, the validation is fired prematurely as soon as the first row is answered.

**Comment by shekharkc** [comment]
> Can you share s survey JSON to reproduce it?

@tsv2013 

Here are two .txt files with the JSONs.

1. First JSON - The error validation kicks in even before 'onBlur' event, even though the  Text Update Mode has been set to 'onBlur'. It's happening only with date type input - as far I noticed. Would be nice to have an option of doing error validation 'onBlur' explicitly.

2. Second JSON - Same as the first JSON, but with additional `"goNextPageAutomatic": true, "questionsOnPageMode": "questionPerPage"` .  You would notice that the user is navigated away from the second question (DOB) even before the entry is completed.
[sample1-personalInfo.txt](https://github.com/surveyjs/survey-library/files/4526891/sample1-personalInfo.txt)
[sample2-personalInfo.txt](https://github.com/surveyjs/survey-library/files/4526892/sample2-personalInfo.txt)

Thanks

**Comment by tsv2013** [comment]
I've created two plunker samples for each case you mentioned. Both examples work ok for me - allow to enter value via chooser or keyboard and show error on blur only.

1. https://plnkr.co/edit/pi3MSai2MGRYJOPe?preview

2. https://plnkr.co/edit/ztwSRLGIV7mMrLtX

Can you check them and tell me - what am I doing wrong?

**Comment by andrewtelnov** [comment]
@shekharkc We decided to do it differently. We do not check isRequired error on value changed event any more. We check it on next page or on complete survey events.
Here is the related GitHub issue: [Do not show isRequried error on value changed](https://github.com/surveyjs/survey-library/issues/2126).

Thank you,
Andrew

**Comment by shekharkc** [comment]
> I've created two plunker samples for each case you mentioned. Both examples work ok for me - allow to enter value via chooser or keyboard and show error on blur only.
> 
> 1. https://plnkr.co/edit/pi3MSai2MGRYJOPe?preview
> 2. https://plnkr.co/edit/ztwSRLGIV7mMrLtX
> 
> Can you check them and tell me - what am I doing wrong?

@tsv2013 
Seen both the examples. They are working perfectly as expected in plunker.

However, when I have tried the same JSON on survey-creator (https://surveyjs.io/create-survey), the problems I highlighted are still there.

Noticed that you are using react version of survey JS.
Could it be due to some library or version issue?

Thanks for your time

**Comment by tsv2013** [comment]
@shekharkc How these scenarios are related to survey-creator?

In survey-creator on our site you cann't register a custom function that compare dates:
```JS
function dateLessThen(params) {
  if (!params && params.length < 2) return -1;
  var birthDay = new Date(params[0]);
  var dateCompare = new Date(params[1]);
  return birthDay < dateCompare;
}
Survey.FunctionFactory.Instance.register("dateLessThen", dateLessThen);
```
It is used in validator.

**Comment by shekharkc** [comment]
Ok. 
Checked the JSON that I shared on plunker. With the settings that you shared.
`title: "Survey Validation Test",
    description: "Try enter month only and leave the input",
    checkErrorsMode: "onValueChanged",
    textUpdateMode: "onBlur",
    "goNextPageAutomatic": true,
    "questionsOnPageMode": "questionPerPage",
`
Works just fine.

When I tried the same on survey-creator (the JSON that I shared - with above settings) - result is the same as before. **User has been navigated away prematurely**

Have only two observations.

1. The JSON Editor in survey-creator is automatically  stripping of this
`textUpdateMode: "onBlur",` 

The settings remaining after a Test survey are only these:
` "goNextPageAutomatic": true,
 "checkErrorsMode": "onValueChanged",
 "questionsOnPageMode": "questionPerPage"`

2. The survey library in survey-creator is knockout version unlike the react version you used in the example.

Could the issue be related to JSON editor parsing? or due to differences in library versions?

Thanks

**Comment by shekharkc** [comment]
Btw, I used this inbuilt validator in survey-creator, and not the function you used _function dateLessThen(params)_

`{
          "type": "expression",
          "text": "Date of birth has to be before 01 Jan 2002",
          "expression": "{dob} < '2002-01-01'"
         }`

Hope that clarifies things a bit more

**Comment by andrewtelnov** [comment]
@shekharkc Could you please send us the minimum JSON that doesn't work incorrectly, so we do not guess what is wrong?

Thank you,
Andrew

**Comment by shekharkc** [comment]
@andrewtelnov ,

Shared a couple of samples earlier.

Here is one more - taken from @tsv2013 's example.
[sample1-personalInfo.txt](https://github.com/surveyjs/survey-library/files/4556439/sample1-personalInfo.txt)


Thank you

**Comment by shekharkc** [comment]
@tsv2013 ,

I tried it on survey-creator without the function used in your code, but using the inbuilt expression validator in surveyJS.

> Btw, I used this inbuilt validator in survey-creator, and not the function you used _function dateLessThen(params)_
> 
> `{ "type": "expression", "text": "Date of birth has to be before 01 Jan 2002", "expression": "{dob} < '2002-01-01'" }`
> 
> Hope that clarifies things a bit more

A sample of the JSON I used in survey-creator is in the comment above your comment. With that JSON pasted in survey-creator JSON editor - we still have the issue of premature navigation before the date entry is completed by the user. 

Not sure of the reason why it should be so. 

Pointed out what my observations were wrt the library version or the JSON editor above if that helps in any manner.

Thanks

**Comment by andrewtelnov** [comment]
@shekharkc There are two issues. At first your validator should be the following:
```js
validators: [
  {
    type: "expression",
    expression: "getDate({birthdate}) < getDate('2020-01-01')",
  },
],
```
You have to convert the strings to Date to compare the values correctly.
At second, we should not check validators for "date" inputType on value changed, because it raises several times while end-user enters a date.
I have changed it. Here is [the related issue](https://github.com/surveyjs/survey-library/issues/2141). It should work fine from [v1.7.5](https://surveyjs.io/WhatsNew#v1.7.5)

Thank you,
Andrew

**Comment by shekharkc** [comment]
@andrewtelnov ,

Thank you very much.

Two related issues/ queries:

1. I used `"inputType": "date",` . Wouldn't the string to the date conversion be handled by the library?

2.  `"expression": "{birthdate} < '2020-01-01'"`  is the expression built by the Expression Builder (GUI) in survey-creator. If this is not an acceptable format, possibly the Expression Builder needs a look.

Thank you very much

**Comment by andrewtelnov** [comment]
@shekharkc Ideally, our condition property editor should generate ``getDate({birthdate}) < getDate('2020-01-01")`` instead of ``{birthdate} < '2020-01-01"``. 
Unfortunately, it is relatively a large task. It is definitely not a dozen lines of code.
Anyway, I will add it to our TODO list, since this suggestion makes sense and we will discuss it during our weekly planning.

Thank you,
Andrew

**Comment by shekharkc** [comment]
Thank you @andrewtelnov
