### ISSUE TITLE
Some custom CSS not working since v1.7.1

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#2122]
### Reporting a bug?
Some custom CSS is not working since v1.7.1.

### What is the current behavior?
Some custom CSS does not get applied.

### What is the expected behavior?
All custom CSS should be applied.

### How would you reproduce the current behavior (if this is a bug)?
Set the version to 1.7.1 or higher and see the custom css for the question titles disappear.
I'm not sure if this happens for more css classes, I have noticed it for my question classes.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/2RN0QXZ5sIJGkSQt

### Specify your

* browser: Chrome and Firefox
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.7.1 onwards

**Comment by tsv2013** [comment]
It's a bug. We'll fork on the fix.

**Comment by tsv2013** [comment]
I've fixed the issue via the referenced commit. Fix will be available in the nearest update.

**Comment by tsv2013** [comment]
@Lionqueen94 I'll check questions in panels.

**Comment by tsv2013** [comment]
@Lionqueen94 I've put question inside a palel. It works ok for me. Here is the plunker with 1.7.4 - https://plnkr.co/edit/iiItoFK1wVOPgYtZ

**Comment by tsv2013** [comment]
@Lionqueen94  I've copied your comment here, in the  original thread,

@tsv2013 I have tested it, and the css for question titles it not applied within dynamic panels. See this Plunker: https://plnkr.co/edit/1d4W8wAwIeNNMSAD
Change the SurveyJS version between 1.5.19 and 1.7.4

**Comment by tsv2013** [comment]
I've reproduced the issue with paneldynamic in this plunker - https://plnkr.co/edit/iiItoFK1wVOPgYtZ

**Comment by tsv2013** [comment]
I've fixed the issue with inner quesitons in a dynamic panel. Fix will be available in 1.7.5.

**Comment by Lionqueen94** [comment]
Thanks! I'm looking forward to the new version!
