### ISSUE TITLE
Adding a custom Object as a Property to a Question

### ISSUE THREAD

**Issue by shekharkc** [surveyjs/survey-library#2127]
### Are you requesting a feature, reporting a bug or ask a question?

Question.

### What is the current behavior?

Did not see a way to add a custom object array as a Property to a question. 
Is adding a property (an dynamic object array) such as the following possible? If yes, how? Alternately, any work around? :

"infoBox": [{
                        "position": "one of ['top', 'in-between', 'bottom']",
                        "type": "one of ['info', 'help', 'caution', 'tip', 'example']",
                        "state":  "one of [default= 'open', 'closed']" ,
                        "content": "some HTML content",
                      },
                   {
                        "position": "one of ['top', 'in-between', 'bottom']",
                        "type": "one of ['info', 'help', 'caution', 'tip', 'example']",
                        "state":  "one of [default= 'open', 'closed']" ,
                        "content": "some HTML content",
                      },
                  {
                        "position": "one of ['top', 'in-between', 'bottom']",
                        "type": "one of ['info', 'help', 'caution', 'tip', 'example']",
                        "state":  "one of [default= 'open', 'closed']" ,
                        "content": "some HTML content",
                      },
                  {
                   }, ...
         ]

### What is the expected behaviour?

Not applicable

### How would you reproduce the current behavior (if this is a bug)?
Not applicable

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* editor version: latest

Thanks

**Comment by tsv2013** [comment]
At this moment there are no means in SurveyJS Library to add a property of object type to survey element in a declarative way.

You can split your object into a set of properties and declare each property separately.

Another approach could be is to introduce new object as descendant of a Base class, override a question with definition of your custom property and override serialization functions. It's a long way.

**Comment by shekharkc** [comment]
Thanks a lot, @tsv2013
