### ISSUE TITLE
Panel with a checkbox

### ISSUE THREAD

**Issue by karishmasahu** [surveyjs/survey-library#2128]
I want to implement something like a panel heading having a single checkbox. If the checkbox is checked then only it will display the questions inside the panel.
So is there a way to achieve this?

**Comment by tsv2013** [comment]
I believe you can customizer a panel rendering the https://surveyjs.io/Documentation/Library?id=surveymodel#onAfterRenderPanel event handler.

Here is the live sample how to use similar examples
