### ISSUE TITLE
Memory leaks is SurveyJS Library

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-library#2131]
If you render Survey multiple times without refresh the page, the memory consumption keep increasing when Survey is re-created.

See this thread for more details: https://surveyjs.answerdesk.io/ticket/details/t3896/memory-issue-on-ie11

I've reproduced the issue in Chrome also.

We'll introduce the `dispose` method for survey model. It should dispose all inner elements and subscriptions.

**Comment by hhendrycks** [comment]
Do you know if this was resolved for React? I'm using a live-reload for node and am getting heap memory errors, causing the app to crash.

**Comment by tsv2013** [comment]
Yes, it's marked as fixed.
