### ISSUE TITLE
Calculated values not updated in survey.data

### ISSUE THREAD

**Issue by mloar** [surveyjs/survey-library#2133]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
If a survey is loaded with data which contains a value with the same name as a calculated value with includeIntoResult = true, that value will be returned by all future gets of survey.data, even if the calculated value changes.

### What is the expected behavior?
survey.data should return the current value of the calculated value.

### How would you reproduce the current behavior (if this is a bug)?
Survey JSON:
```
{
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "text",
          "name": "fruit",
          "title": "Enter a fruit"
        }
      ]
    }
  ],
  "calculatedValues": [
    {
      "name": "finalAnswer",
      "expression": "{fruit}",
      "includeIntoResult": true
    }
  ]
}
```  

Set data to:
```
{"fruit": "apple", "finalAnswer": "apple"}
```

Change "apple" to "orange" in the first question. survey.data returns:
```
{"fruit": "orange", "finalAnswer": "apple"}
```

### Specify your

* browser: Edge
* browser version: 81.0.416.64
* surveyjs platform: react
* surveyjs version: 1.7.3

**Comment by andrewtelnov** [comment]
@mloar Thank your for reporting the issue and for the fix.
I have just added a unit test based in your case.

Thank you,
Andrew
