### ISSUE TITLE
Question title custom css class is applied only after question value is set

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#2136]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

question title custom css class is applied only after question value is set

### What is the expected behavior?

question title custom css class should by applied after survey rendering 

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/4kZLfX1A9Zw4ZZyO

**Comment by masciugo** [comment]
maybe related to #2122

**Comment by masciugo** [comment]
still persisting in 1.7.4
https://plnkr.co/edit/4kZLfX1A9Zw4ZZyO

**Comment by Lionqueen94** [comment]
@masciugo #2122 is indeed still the case, I hope you can find the issue. For now I'll keep using 1.5.19 since placeholders and custom css were both still working in that version.

**Comment by tsv2013** [comment]
I've fixed the issue. Fix will be available in the nearest update.

@Lionqueen94 Have you checked the 1.7.4 ?

**Comment by Lionqueen94** [comment]
@tsv2013 I have indeed tested it, and as I said, for me all questions are rendered with custom css except the questions in panels. So I think you are skipping the css there?

**Comment by Lionqueen94** [comment]
@tsv2013 I have tested it, and the css for question titles it not applied within **dynamic panels**. See this Plunker: https://plnkr.co/edit/1d4W8wAwIeNNMSAD
Change the SurveyJS version between 1.5.19 and 1.7.4

**Comment by tsv2013** [comment]
@Lionqueen94 I've put question inside a palel. It works ok for me. Here is the plunker with 1.7.4 - https://plnkr.co/edit/iiItoFK1wVOPgYtZ. If you will answer please do it in the original thread.
