### ISSUE TITLE
Scroll to go back/ forward along with Forward and Next Buttons

### ISSUE THREAD

**Issue by shekharkc** [surveyjs/survey-library#2139]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

1. With the 'questionsOnPageMode' in the 'standard' mode & "goNextPageAutomatic": true, the survey is _scrollable_ for going back or forward. **Next** and **Back** buttons are available if there are more pages. However:
- the questions in a page are all displayed at once _(not one question at a time)_
- There is no way to go _back/ forward_ to _Previous or Next_ **question** using Buttons _as the buttons are for a Page-level navigation_

2. With the 'questionsOnPageMode' in the 'questionPerPage' mode, and "goNextPageAutomatic": true, a page with a number of questions is automatically divided to multiple pages, and questions are displayed one after another, progressively - _which is what a survey creator would usually prefer in a long survey_ to avoid the question fatigue. However, 
- We have only the 'Back' and 'Next' buttons for navigation now.
- and **not** the scroll action to move forward and back.

### What is the expected behavior?

3. One of the desired ways would be to have a combination of 

- both Scroll action for Navigation _(Especially for mobile devices && if the survey is long)_  
- and Back and Next buttons for going back to the previous or Next **questions**  (_at a question-level too in addition to navigation at a Page level_)  
- and _questions being displayed one at a time if desired so_
- Navigation control at a _Question Level_ in addition to the one at a _Page Level_

4. Some of the popular survey software has this feature. As an example,

https://www.typeform.com/templates/t/lead-generation/

allows a **scroll**, **up/down arrow based navigation**,  and **next & back buttons** for navigating forward and back **at a question level**

5. **My question(s)**:

- Is there a way we can achieve this in surveyJS with some changes in settings?
- If not, is it in the _roadmap_ or can it be taken up as an enhancement request, if deemed fit?
- Is there a workaround?
    - The only workaround, I could think of is to break the survey into multiple pages, in smaller chunks as one would want to display and have the settings set to 'questionsOnPageMode' in the 'standard' mode & "goNextPageAutomatic".

### How would you reproduce the current behavior (if this is a bug)?

Not a bug

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version: Latest
* surveyjs platform (angular or react or jquery or knockout or vue): Knockout
* surveyjs version: Latest

**Comment by tsv2013** [comment]
Answering your questions:
There is no built-in options in SurveyJS now to setup such a behavior.
It's not in the roadmap. But we definitely will take it in account during planning future releases.
I think there is no easy workaround here: if you want to have to scroll from one question to another it requires dramatic changes in survey/page rendering algorithm. Viewport can fit more than one question at once and it requires to calculate what questions are visible and what nearest questions can be smoothly scrolled to. In other words we need to implement a progressive rendering here otherwise it will be time and memory consuming survey UI.

But this is an interesting enhancement indeed. We appreciate your feedback.

**Comment by shekharkc** [comment]
Thanks a lot for your feedback.
Much appreciated.
