### ISSUE TITLE
Ability to autoset the cursor to the leftmost position after a row is added in Dynamic Matrix

### ISSUE THREAD

**Issue by mahajanrevant** [surveyjs/survey-library#2144]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question, possibly a feature request

### What is the current behavior?

In the dynamic matrix element, when the user adds a row, the horizontal scroll stays at the same horizontal position as it was before pressing the button

### What is the expected behaviour?

Is there a way to move to make the horizontal scroll to the leftmost position so it shows the first column whenever the add rows button is pressed.
This makes sense to me from a UI perspective. You always want the user to answer questions from the left to right order and to force that behaviour would be a nice addition

### How would you reproduce the current behavior (if this is a bug)?

Not a bug

#### Provide the test code and the tested page URL (if applicable)
NA
Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Google Chrome
* browser version: 81.0.4044.122 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): Angular 2
* surveyjs version: v1.7.4

**Comment by andrewtelnov** [comment]
@mahajanrevant Here is [the example](https://plnkr.co/edit/Ku6G4os5CwWp6E8m) that does what you need.
Here is the code:
``js
survey.onMatrixRowAdded.add(function(sender, options){
   //The first cell is readOnly
    var question = options.row.cells[1].question; 
    setTimeout(function() {
        question.focus()
    }, 300);
});
``
We need to call question focus method in another thread.

Thank you,
Andrew
