### ISSUE TITLE
Populate coded values via code only (ignoring text)

### ISSUE THREAD

**Issue by TonisOrmisson** [surveyjs/survey-library#2148]
A proposal / question

It would be great if the logic of the surveys would be able to operate on coded choices only (if coded) and ignore the text labels. 

### What is the current behavior?

I'm not sure (yet how the filtering & conditions work), but for populating/ setting data, it only works if both code and text match.

A simple example of what I mean.  
let's say I have a question like :
```
{
    type: "radiogroup",
    name: "car",
    title: "What car are you driving?",
    isRequired: true,
    choices: [
        {'code':1, "text":"Ford"},
        {'code':2, "text":"BMW"},
        {'code':3, "text":"Ziguli"}
    ]
}
```
right now, in order to set the value, one would need to have it like:
```
survey.data = {car: {code:1,text:'Ford'}};
```

### What is the expected behavior?
I  think it would be logical if only this would be enough:

```
survey.data = {car:1};
```

If the choices are coded, using codes will resolve numerous issues like
 - simplicity
 - translation issues (having texts in various languages needs separate attention & a layer of management)
 - Changeability. Mostly you need to change the label / text only. What if you change the form coded text and you have some values stored with a different text?
 - less data to store. Storing `{car:1}` takes much less space than `{car: {code:1,text:'Ford'}}` Imagine if you would have some code in the text labels (eg html).

Thank you for a cool library!

**Comment by TonisOrmisson** [comment]
also similarly to setting, the conditions would need to work then like: 
`visibleIf:"{car}=1"` which does not seem to work for now.

BTW how would you set such a condition that would work currently having the choices coded?

**Comment by TonisOrmisson** [comment]
The real world example of such a question (from examples)
```
{
            type: "dropdown",
            name: "kids",
            title: "How many kids do you have",
            enableIf: "{haveKids}='Yes'",
            isRequired: true,
            choices: [1, 2, 3, 4, 5]
 },
```

would need to go like:
```
{
            type: "dropdown",
            name: "kids",
            title: "How many kids do you have",
            enableIf: "{haveKids}='Yes'",
            isRequired: true,
            choices: [
               {code:1, text:1},
               {code:2, text:2},
               {code:3, text:3},
               {code:4, text:4},
               {code:5, text:'5 or more'},
            ]
 },
```
and for the coded version one currently can not do `enableIf: "{kids} >= 2"`

**Comment by andrewtelnov** [comment]
@TonisOrmisson We have value and text in choice item (ItemValue class).
It can be as:
```js
{
            type: "dropdown",
            name: "kids",
            title: "How many kids do you have",
            enableIf: "{haveKids}='Yes'",
            isRequired: true,
            choices: [ 1, 2, 3, 4, {value:5, text:'5 or more'}]
 }
```

Thank you,
Andrew

**Comment by TonisOrmisson** [comment]
@andrewtelnov thanks, good to know!

But how you set an `enableIf` for `value=5`? `{haveKids}=5` would not work any more right?
Adding a label to a choice would also mean rewriting any of the logic using the `{haveKids}=5`?

What would seem reasonable, is IF the `value` property is defined for the choices, the value would always be used without the need to additionally refer to the text regarding any logical operations as well as setting and/or getting the data.

**Comment by andrewtelnov** [comment]
@TonisOrmisson You should use value in expressions and it means that ``{haveKids}=5`` works perfectly.
``choices : [1, 2]`` is the same as ``choices : [{value: 1}, {value: 2}]`` and text is optional and surveyjs uses it for displaying in UI only. Adding text as: ``choices : [{value: 1, text: "first year"}, {value: 2, text: "second year"}]`` doesn't change the way it works in expression.

Thank you,
Andrew

**Comment by TonisOrmisson** [comment]
@andrewtelnov thank you!

You are completely right. And seems the setting also works perfectly.
It seems that my mistake was wrongly using `code` instead of `value`. 
:man_facepalming:

excellent work guys
