### ISSUE TITLE
signaturepad is not a function

### ISSUE THREAD

**Issue by RixBai** [surveyjs/survey-library#2149]
### What is the current behavior?
![image](https://user-images.githubusercontent.com/43899212/81132946-21f95280-8f1e-11ea-9566-72c1d3473621.png)

### Code base
```
import * as widgets from 'surveyjs-widgets';
import * as SurveyJS from 'survey-react';

widgets.prettycheckbox(SurveyJS);
widgets.inputmask(SurveyJS);
widgets.jquerybarrating(SurveyJS, $);
widgets.jqueryuidatepicker(SurveyJS, $);
widgets.nouislider(SurveyJS);
widgets.select2tagbox(SurveyJS, $);
widgets.signaturepad(SurveyJS);
widgets.sortablejs(SurveyJS);
widgets.ckeditor(SurveyJS);
widgets.autocomplete(SurveyJS, $);
widgets.bootstrapslider(SurveyJS);
```

### IDE
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.7.4

**Comment by andrewtelnov** [comment]
@RixBai Please make sure that you have loaded the modern.css file on your page.

Thank you,
Andrew

**Comment by RixBai** [comment]
What do you mean by modern.css file @andrewtelnov ?

**Comment by andrewtelnov** [comment]
@RixBai Hm, I believe there was another subject: "Cannot update matrix selection" and image. My answer was about that question.
Regarding signuturepad. Please remove this line:
``widgets.signaturepad(SurveyJS);``
SignaturePad is now a part of a SurveyJS Library. We have this question out of the box now, due many requests for this widget.

Thank you,
Andrew

**Comment by RixBai** [comment]
Great!
It's working!
Thank you, @andrewtelnov
