### ISSUE TITLE
i want to hidden the category like  navigation/ logic etc.

### ISSUE THREAD

**Issue by zzq0826** [surveyjs/survey-library#2150]
### Are you requesting a feature, reporting a bug or asking a question?
 asking a question
![image](https://user-images.githubusercontent.com/12936800/81131742-bbf0e780-8f7e-11ea-8f1d-c2f2e8471424.png)

### What is the current behavior?
nothing

### What is the expected behavior?

i want to hidden the category like  navigation/ logic etc.

### How would you reproduce the current behavior (if this is a bug)?

i use 
SurveyKo
    .Serializer
    .removeProperty("survey", "navigation");
but it does not work.    thanks for your help.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@zzq0826 You can't remove a tab. You have to remove all properties in this tab ans the tab will be hidden. We do not display a tab without properties.

Thank you,
Andrew

**Comment by neo1afshin** [comment]
use css:
.svd-accordion-tab-header[data-title="Layout"],
.svd-accordion-tab-header[data-title="Data"],
.svd-accordion-tab-header[data-title="Others"] {
  display: none;
}
