### ISSUE TITLE
Panel indentation

### ISSUE THREAD

**Issue by jbouchard24** [surveyjs/survey-library#2154]
### Are you requesting a feature, reporting a bug or ask a question?

Ask a question

### What is the current behavior?

I'm adding a panel and inserting questions in it. In the panel property editor, layout section, there are two indentation values ("Indent" and "Inner indent"). When I set an inner indent, I see that the questions of the panel are moving to the right, which is what I expect (see screenshot below). 

![image](https://user-images.githubusercontent.com/54321952/81192202-edba7c00-8f87-11ea-8c83-a9d1b619bfaf.png)

However, when I change the "Indent" value, which is 20 in the screenshot, nothing seems to happen. What would be the expected behavior for this?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: [https://surveyjs.io/create-survey](https://surveyjs.io/create-survey)

### Specify your

* browser: Chrome 81
* editor version: 1.7.4

**Comment by tsv2013** [comment]
Transferred to the corresponding repo

**Comment by tsv2013** [comment]
I've checked our code - it looks like this property is not used in markup. We need to discuss it with the team - whether we forgot to remove it or needed to implement it.

**Comment by tsv2013** [comment]
We discussed it and decied to implement for panels and questions.

**Comment by jbouchard24** [comment]
Alright, thank you for your answer.
