### ISSUE TITLE
Add rowTitleWidth property for Matrix Dropdown

### ISSUE THREAD

**Issue by TonisOrmisson** [surveyjs/survey-library#2158]
## Are you requesting a feature, reporting a bug or asking a question?

Im not 100% its a feature request or a question. Did not find this option in the docs, anyway.

### What is the current behavior?
Currently one can set the widths for defined columns in the matrix. But does not seem to be possible to set the desired width for the first column containing the sub-question text.
I understand it can be done via css, but it should be able to define this per question. 
Some matrixes have longer texts in rows, and some free space can be allocated there from columns.

so as an example. Lets say I have this:
![Screenshot from 2020-05-07 18-49-39](https://user-images.githubusercontent.com/6357451/81317707-d964a500-9095-11ea-8924-c2b47ab1ba64.png)

### What is the expected behavior?
But I want is to look like this:
![Screenshot from 2020-05-07 18-50-52](https://user-images.githubusercontent.com/6357451/81317746-e8e3ee00-9095-11ea-8330-5d4e38c0a8f8.png)

**Comment by andrewtelnov** [comment]
@TonisOrmisson We do not have this functionality yet. It makes sense and it should be easy to add. We will need ``rowColumnWidth`` or I do ``rowTitleWidth``. I am not sure about the name.

Thank you,
Andrew

**Comment by TonisOrmisson** [comment]
Awesome!
`rowTitleWidth` seems more logical to me.

**Comment by andrewtelnov** [comment]
@TonisOrmisson I have added the property. It will be available in [v1.7.6](https://surveyjs.io/WhatsNew#v1.7.6).
In property grid it will be located in "Layout" tab.

Thank you,
Andrew
