### ISSUE TITLE
Title not highlighted when data set

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-library#2159]
1) Create survey
2) Set `survey.data`
3) ???
4) Titles not highlighted

Example in plunker: https://plnkr.co/edit/fFp3wS1lKpbDYWm0

![image](https://user-images.githubusercontent.com/30930391/81321144-e5069a80-909a-11ea-91ff-6a4e4007bc30.png)

**Comment by dmitrykurmanov** [comment]
It seem that the bug is already fixed.
