### ISSUE TITLE
Is there a way to set question input box size and prompt size independent of each other?

### ISSUE THREAD

**Issue by zman13** [surveyjs/survey-library#2163]
I was hoping to be able to set the input box to one size programitically, and  the prompt to a different size.  Is there a way to do this currently?

This demonstrates the description text being longer than the desired size of the input box
https://plnkr.co/edit/KSbrsqMHbshO8hTs?preview

and here the opposite problem
https://plnkr.co/edit/UKe511DhYPPVlixZ

I was hoping to be able to address the 2 sizes independently so it could lay out neatly.

BTW I LOVE Survey.js. 

### Are you requesting a feature, reporting a bug or asking a question?
This is either a question or a feature request depending on the answer ;)

Thanks,
Marc

**Comment by andrewtelnov** [comment]
@zman13 You can define a new property, for example inputWidth and then use it survey.onAfterRenderQuestionInput event.
Here is [the example](https://plnkr.co/edit/imtF5hNi8Rf4ezvN).
Please note, I am using the latest version of SurveyJS Library [v.1.7.5](https://surveyjs.io/WhatsNew).

Thank you,
Andrew

**Comment by zman13** [comment]
@andrewtelnov Thank you! You rock!
