### ISSUE TITLE
How does i fire custom vue events from inside the survey?

### ISSUE THREAD

**Issue by tomaserlebach** [surveyjs/survey-library#2164]
Is there a way to fire a custom vue event from inside the survey?

For example i have the following element:
```
       {
        "type": "html",
        "name": "question5",
        "html": "<button type=\"button\" @click=\"$emit('ggg')\">Test</button>"
       }
```
No Vue Events are triggered. I am propably out of scope...but i have no clue how to fix this.

I am tracking the events with the vue browser addon.

Thanks a lot!

**Comment by tsv2013** [comment]
The HTML markup is rendered via the following template:
```HTML
<div :class="question.cssClasses.root" v-html="question.locHtml.renderedHtml"></div>
```
(the renderedHtml is processed html value: substituted question values)

Thus it doesn't have bindings to the model. It's just a plain markup not bound to VueJS context.
