### ISSUE TITLE
Do we have checkbox & textfield combination?

### ISSUE THREAD

**Issue by sem1colon** [surveyjs/survey-library#2165]
I want to display a question which consists of checkboxes with the other option, on which user can enter some text to _other_ option. Something like this:

What programming languages do you know?

- [ ] Java

- [ ] JavaScript

- [ ] Typescript

- [ ] Others - `Please enter your language name.`

**Comment by tsv2013** [comment]
The "checkbox" question has the 'hasOther' property. You can set it to true and I believe you will exactly your case implemented.

**Comment by sem1colon** [comment]
Great, That worked!
![image](https://user-images.githubusercontent.com/26898798/81656457-aa16b500-9454-11ea-9ff1-f6870dc0a0f7.png)
However, I want to remove `(describe)` here, is there a way to do that?

**Comment by tsv2013** [comment]
You can set the https://surveyjs.io/Documentation/Library?id=questioncheckboxmodel#otherText property to change this text

**Comment by sem1colon** [comment]
I must say, it's a great library. Cheers mate! Thank you for your support and great work.
