### ISSUE TITLE
Cuelang Schema for SurveyJS

### ISSUE THREAD

**Issue by wroge** [surveyjs/survey-library#2166]
Hello everybody,
I think I'm not the only one who wants a scheme for SurveyJS. A JSON schema is included in this [gist](https://gist.github.com/Goxiaoy/6c6383439dc75fb5b96085c23edb908e), but an official and regularly updated schema would make it much easier to develop tools yourself.
[Cuelang](https://cuelang.org) is a data constraint language that can define and validate text-based data. Therefore, it can ideally be used to define our Survey JSON. It would also be possible to use a Cuelang definition file as documentation.

This is an example to show the possibilities: [schema.cue](https://gist.github.com/wroge/7cabe0d7e4b5f09be75453950aadf860)

`cue vet schema.cue example.json`

**Comment by tsv2013** [comment]
@wroge  Thank you for your efforts. I hope it helps other members of the community.

**Comment by wroge** [comment]
Thank you for your answer.
It would be great if someone could check whether the Cuelang definition fits the current survey model. Are there any surveys to test all edge cases?

**Comment by tsv2013** [comment]
I'm afraid there are no such term as "edge cases" here. There is no some exact static schema of SurveyJS. SurveyJS metadata is very flexible and you can unregister some question types, add your own question types, hide or remove properties, change defaults and add custom properties. In the client side code validation is produced during survey deserialization: all unknown properties are ignored to be loaded.

The question about SurveyJS schema for server side applications was set before - e.g. here https://github.com/surveyjs/survey-library/issues/129 and here https://github.com/surveyjs/survey-library/issues/2001

SurveyJS team does understand your needs. But on the other hand we're working on the JavaScript cilent side products. Rather small team supports SurveyJS Library, SurveyJS Creator, SurveyJS Widgets, SurveyJS PDF and SurveyJS Analytics as well as out site https://surveyjs.io/ and service infrastructure.

Right now we don't have resources to work on schema and server-side validation scripts and it would be great if community members share thier experiences here.

**Comment by wroge** [comment]
It is possible to generate OpenAPI specification from Cue: [surveyjs.yaml](https://gist.github.com/wroge/3b27b875976c9d57dd2580196208779e)
