### ISSUE TITLE
pass title to Survey.RegexValidator 

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#2167]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

Docs says I can add validators this way

```
afterRender: function (question, el) {
   question.validators.push(new Survey.RegexValidator(/^(\d\d\d\d-\d\d-\d\d)?$/))
....
```
But how can I pass the title/text for the error message? I am building a custom widget so I cannot use the json model way. Can I?

thank you

**Comment by tsv2013** [comment]
I think you can do the following:
```JS
var validator = new Survey.RegexValidator(/^(\d\d\d\d-\d\d-\d\d)?$/);
validator.text = "My validation message";
```

**Comment by masciugo** [comment]
great. thank you
