### ISSUE TITLE
Radio group selection continues on next page

### ISSUE THREAD

**Issue by PeterHassaballah** [surveyjs/survey-library#2173]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Answer selection in radio group is same across all pages

### What is the expected behavior?
I have multiple pages with 5 radio group questions on each.
with 5 answers each
If for example, I choose for question 1 the third answer all questions in the next pages that are at the top of the page has the 3rd answer selected as well

### How would you reproduce the current behavior (if this is a bug)?
I am using the example code from the docs

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
var question = {
    "pages": [
        {
            "name": "page1",
            "title": "The question text",
            "elements": [
                {
                    "type": "radiogroup",
                    "name": "The answer text",
                    "descriptionLocation": "underInput",
                    "titleLocation": "top",
                    "choices": [
                        {
                            value: 20,
                            text: "Extremly does not resonate for me"
                          }, {
                            value: 40,
                            text: "Does not resonate for me"
                          }, {
                            value: 60,
                            text: "Neutral"
                          }, {
                            value: 80,
                            text: "Resonate for me"
                          }, {
                            value: 100,
                            text: "Highly resonate for me"
                          }
                    ],
                    "colCount": 5
                }
            ],
            "questionTitleLocation": "top",
            "questionsOrder": "initial"
        },
       
    ],
    "questionErrorLocation": "bottom",
    "showProgressBar": "top",
    "progressBarType": "questions",
    "goNextPageAutomatic": true,
    "questionsOnPageMode": "singlePage"
}

```

### Specify your

* browser: Chrome
* browser version:Version 81.0.4044.138 
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version:1.1.25
*OS: Windows 10

**Comment by tsv2013** [comment]
Do the questions on all pages have the same name?

**Comment by PeterHassaballah** [comment]
Yeah I found out it is populated without changing the name thanks a million
