### ISSUE TITLE
[question] list of all survey variable

### ISSUE THREAD

**Issue by swuecho** [surveyjs/survey-library#2176]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

in  quiz, https://surveyjs.io/Examples/Library/?id=survey-quiz&platform=Vue&theme=modern#content-js

completedHtml: `"<h4>You have answered correctly <b>{correctedAnswers}</b> questions from <b>{questionCount}</b>.</h4>"
`

there are two variable, {correctedAnswers} and {questionCount}.  I wonder if there is a list of all variable?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
You can iterate through all the questions getting them using the `survey.getAllQuestions();` function.

Right now we're working on the "preview answers" feature. Here is the related issue - https://github.com/surveyjs/survey-library/issues/2170

Please feel to post your suggestions here if you find this feature useful for you
