### ISSUE TITLE
Store Survey Results in a local JSON file

### ISSUE THREAD

**Issue by Arianagra** [surveyjs/survey-library#2178]
Hello,

So I wanted to use the onComplete event to store Survey Results in my Own Database as explained in the Documentation of SurveyJS:

survey.onComplete.add(function (sender, options) {
    var xhr = new XMLHttpRequest();
    xhr.open("POST", "file:///C:/Users/Name/Desktop/Test.json");
    xhr.setRequestHeader("Content-Type", "application/json; charset=utf-8");
    xhr.send(JSON.stringify(sender.data));
});

Unfortunately after completing my survey on the local website, the empty JSON file i created won't be filled. What do i have to change in the code to send the results to a local file instead of to a URL?

Thank you very much!

**Comment by tsv2013** [comment]
This question is not related to SurveyJS functionality. Please check the follwoing threads:

https://stackoverflow.com/questions/28464449/how-to-save-json-data-locally-on-the-machine

https://stackoverflow.com/questions/34156282/how-do-i-save-json-to-local-text-file
