### ISSUE TITLE
Survey-knockout upgrade issue 

### ISSUE THREAD

**Issue by jeffcann** [surveyjs/survey-library#2179]
### Are you requesting a feature, reporting a bug or asking a question?
Not sure? Maybe bug, or something to investigate, or useful information for anyone else who come across this.

When I'm using the following dependencies, all is good.
```
    "survey-knockout": "1.1.26",
    "survey-vue": "1.1.27",
    "surveyjs-editor": "1.1.25",
    "surveyjs-widgets": "1.1.27",
```

When I change survey-knockout to 1.1.27 (all other packages remain the same), I get the following error:
```
knockout-latest.js?68fb:16 Uncaught TypeError: Unable to process binding "if: function(){return $data.survey }"
Message: Unable to process binding "template: function(){return { name:'survey-content',data:survey,afterRender:$parent.koEventAfterRender} }"
Message: Cannot read property 'fire' of undefined
    at SurveyLiveTester.koEventAfterRender (surveyeditor.js?e0b3:15182)
    at Object.G (knockout-latest.js?68fb:41)
    at e (knockout-latest.js?68fb:126)
    at a.$.Sa (knockout-latest.js?68fb:127)
    at Function.yd (knockout-latest.js?68fb:55)
    at Function.zd (knockout-latest.js?68fb:55)
    at Function.ha (knockout-latest.js?68fb:54)
    at Object.a.o.a.$ (knockout-latest.js?68fb:52)
    at Object.a.dc (knockout-latest.js?68fb:127)
    at update (knockout-latest.js?68fb:131)
```

### What is the current behavior?
When survey editor is instantiated I see the above error. 
Survey editor is unusable.

### What is the expected behavior?
No errors, survey editor is usable.

### How would you reproduce the current behavior (if this is a bug)?
Rollback to survey-knockout:1.1.26 everything works as expected
Upgrade to survey-knockout:1.1.27 I see the above error

### Specify your

* browser: Chromium
* browser version: Version 81.0.4044.138 (Official Build) Built on Ubuntu , running on LinuxMint 19.3 (64-bit)
* surveyjs platform: Vue
* surveyjs version: 1.1.26 -> 1.1.27

**Comment by tsv2013** [comment]
SurveyJS versions should be consistent, e.g.
```
    "survey-knockout": "1.1.26",
    "survey-vue": "1.1.26",
    "surveyjs-editor": "1.1.26",
    "surveyjs-widgets": "1.1.26",
```

We can't re-publish package of the previous version due to NPM policy.
We can fix the issue if it exists in the latest version.

Is the issue reproducing with the latest version of SurveyJS?

**Comment by jeffcann** [comment]
@tsv2013 Yes, I get it with every version  >=1.1.27 (to 1.1.33) as well as latest in 1.7.x.

**Comment by tsv2013** [comment]
Can you provide us with the live sample and steps to reproduce on our side?
