### ISSUE TITLE
How renderWidth is it manage

### ISSUE THREAD

**Issue by aloiseau17** [surveyjs/survey-library#2180]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the current behavior?
Questions have a min-width set to 300px directly on element.

### What is the expected behavior?
How can I change this default behavior ? I would like question to adapte responsively because I display the survey inside a narrow panel.

### How would you reproduce the current behavior (if this is a bug)?
Here is an example showing question overflow

#### Provide the test code and the tested page URL (if applicable)

![image](https://user-images.githubusercontent.com/19550407/82348931-c3da6e00-99f9-11ea-9776-01fec5450776.png)

Tested page URL:
https://plnkr.co/edit/zcRS9gc9TOaR7hS7

### Specify your

* browser: Google Chrome
* browser version: 81.0.4044.138
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.7.5

**Comment by tsv2013** [comment]
You can use the "important" to overcode this:
```CSS
.sv_qstn {
  min-width: 0px !important;
}
.sv_row {
    min-width: 0px !important;
}
```

Here is your updated plunker - https://plnkr.co/edit/J7uc9kmOurIgbEac
