### ISSUE TITLE
matrix column-unique validator example?

### ISSUE THREAD

**Issue by andjules** [surveyjs/survey-library#2183]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

New to SurveyJS (fantastic), forgive me if the answer is obvious, but I've searched documentation and issues and not seen much based on column-based matrix-validation expressions.

I'm trying to figure out the simplest way to make a "unique column" validation expression.
Imagine a simple 3 row (apple, orange, banana), 2 column (favourite, 2nd favourite) radio-button matrix for ranking your 2 favourite of 3 fruits (required)
Validation is obviously column-based: if I pick apple as my favourite, then try to pick banana as my favourite, apple should deselect (`onValueChanged` event).
onSubmit validation should really be based on columns (each column must have one selection), not rows/questions.

Wondering if you have an example for this scenario?
This one gets me part way there: https://plnkr.co/edit/Mg8xOA

**Comment by tsv2013** [comment]
Your sample works ok for me. I've adopded it for the latest version of the library - https://plnkr.co/edit/YWHHzmQuZA5cIwbB

It does exactly what you need, doesn't it?
