### ISSUE TITLE
Display row with type check box other (matrixdropdown)

### ISSUE THREAD

**Issue by Huuvinh94** [surveyjs/survey-library#2184]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

I create a question type matrixdropdown and at last rows i have add a properties **hasOther = true**, but it not work. This properties work only in columns "cellType:checkbox"

### What is the expected behavior?

I want to display something like the image below:
It mean at the last row, i want to display a row with type check box other:
![image](https://user-images.githubusercontent.com/18391623/82541061-117de480-9b7a-11ea-9348-dae0f9099509.png)

Please help me
Thanks you!

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
You can use the `columnLayout: "vertical"` option. Here is the live sample - https://plnkr.co/edit/WprzHMgYiuYMWXnC
Does it fit your needs?

**Comment by Huuvinh94** [comment]
I am currently using the way you said, but it not suitable for my case :((
Is there another way?

Thanks you @tsv2013 for your answer!

**Comment by tsv2013** [comment]
There is no other way. What's wrong with it?

**Comment by Huuvinh94** [comment]
It is not at fault.
I had use the `columnLayout: "vertical"` and it work very well.

Thanks you!
