### ISSUE TITLE
choicesByUrl should save raw data

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#2185]
### Are you requesting a feature, reporting a bug or asking a question?

question/feature

### What is the current behavior?

my original need was a way to fetch remote object prop in order to populate other questions after selecting that object from a dropdown. I [managed to do it by a custom asyn func called _getRemoteObjectProperty_](https://plnkr.co/edit/Mqy8ZcATJscOam13opOD?preview) as suggested by [your example](https://surveyjs.io/Examples/Library/?id=questiontype-expression-async&platform=Reactjs&theme=modern#content-result) (which is, by the way, very similar to [Expression Trigger](https://surveyjs.io/Examples/Library/?id=trigger-runexpression&platform=Reactjs&theme=modern#content-result))

However, even if that methodology is very useful in general when I use dropdown with choicesByUrl, the remote service often returns array of objects with all their props. Theoretically there shouldn't be the need to run the second request in order to fetch the desired object and then its prop as SurveyJS already bumped into it while loading choices from remote.

I, actually, also managed to avoid the second request by an hack which I don't really like:

https://plnkr.co/edit/RhW7K4lislPHOFeQ?preview

I don't like the following even if it's clear and works 

```
survey.onLoadChoicesFromServer.add(function(survey,options) {
    options.question.valueObject = options.serverResult
   })
```
Maybe tying valueObject directly to question is wrong. To avoid this I thought about a native solution that will let me access valueObject prop in the ItemValue class as I know you can add custom prop to _itemvalue_ class doing something like :

```
Survey.Serializer.addProperty("itemvalue",
        { name: "alpha3Code" }
      );
```

but this is hardcoded and I was not able to add the whole valueObject prop that will let me simplify the custom function much more: 

https://plnkr.co/edit/SCQaTYKhbYJzfSAW (read the comment at line 14)

Is there a way to attach the whole remote object to the selected item value so that I will enable my users to select which prop insert directly by the json model?

thank you

**Comment by masciugo** [comment]
enhanced version of my hacky solution which work in paneldynamic and matrixdynamic too (serverResult hash is tied to survey object) 

https://plnkr.co/edit/KONfFpFtv5ym3CMA

**Comment by tsv2013** [comment]
Using the `getItemValueCallback` you can extract item value according your needs - use a whole received item object or construct your own one. After that yopu can get properties directly from the question value.

Here is the working sample - https://plnkr.co/edit/YTeioYcdC7Vl96Ot

The only minus is that unnecessary information can be stored as an answer result.

**Comment by masciugo** [comment]
great thank you

**Comment by masciugo** [comment]
@tsv2013 I know understand your last sentence 

> The only minus is that unnecessary information can be stored as an answer result

which is bad ... Because I actually need to keep the default behaviour for the dropdown question (according to the provided choicesByUrl.valueName property). What I do need instead is something internal maybe, a way to reach later the dropdown and get the original raw data the selected ItemValue was built on. That's why I was thinking to a way to keep the raw data into the ItemValue object as a prop

**Comment by tsv2013** [comment]
@masciugo I've added the attachOriginalItems property to the ChoicesRestfull class. It you set it to true, the original item will be attached to the itemValue as the "originalItem" property. For more details check the referenced commit. Does it fit your needs?

**Comment by masciugo** [comment]
many many thanks for this. I waited so long to give a feedback because I did not find the time to try this new feature. However I'll do it as soon as I can. For the moment it sounds good. Thanks again

**Comment by masciugo** [comment]
@tsv2013 I tried to use the new option but It seems to be ignored. 

https://plnkr.co/edit/jPsIlFzBIBY9hPf9

I while debugging I also tried to set allowEmptyResponse = true but it seems to be ignored too. Am I missing something stupid or it a bug?

thank you

**Comment by tsv2013** [comment]
Very weird and unexpected. I'll take a look.

**Comment by tsv2013** [comment]
Yea, it was a serialization issue. I've added unit test and fixed it.

**Comment by masciugo** [comment]
Cannot have it working. Property _ originalItem_ keeps undefined

https://plnkr.co/edit/pHQLO8NCvvzmfRFo

am I wrong?

**Comment by tsv2013** [comment]
You are absolutely right. I'l check it.

**Comment by tsv2013** [comment]
I've found the issue. Items were copied but originalItem was not. I've added unit test and fixed it. Hope this finally makes it work.

**Comment by masciugo** [comment]
hi @tsv2013 I am afraid I did not considered all scenarios.. 
This is the custom function that leverage on the feature you kindly added for me: 
https://plnkr.co/edit/OjMCGuXj9h6OSpt3
It works and it's faster than [my original solution](https://plnkr.co/edit/Mqy8ZcATJscOam13opOD?preview) as expected

But the survey does not get populated when it's in display mode because `targetQuestion.visibleChoices` is always empty.

Do you have any suggestion to solve this problem?

thanks

**Comment by tsv2013** [comment]
@masciugo am I right that in display mode you can't access addiotional parameters for the selected object? As far as i understand in display mode you already have the data you assign to survey. Can you at this moment (probably even on the sever side) obtain the additional parameters you need?

You can use the survey.data in the getSelectedChoiceProp function as data source for the display mode... The first idea :-)
