### ISSUE TITLE
Possible problem/suggestion related with complete and restFull questions

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-library#2186]
Are you requesting a feature, reporting a bug or ask a question?
Question or bug
I will explain a bit a situation, I have a case when I use the survey without rendering it, I'm using it to perform some actions on my survey, the thing is if
1 ) I instantiate my survey (and I have some questions with choices restful option)
2) Set my answers
3) Do a complete
All my restful choice questions are cleaned up, I suppose because the survey don't was completely ready.
there is some event like SurveyReady or any way to avoid this behavior

What is the current behavior?
Clean all my restful questions

What is the expected behavior?
Clean my answers normally if something is wrong

Thanks alot

**Comment by tsv2013** [comment]
Restful choice questions are clean while their choices are not have been loaded.

You can write code similar we're using in survey-pdf module in order to wait survey to be ready to use - https://github.com/surveyjs/survey-pdf/blob/57bc24d56d10f1778ee0cd03991add2ae6a3a3b7/src/survey.ts#L81-L111

**Comment by jmar1998** [comment]
@tsv2013 thanks alot, its working perfectly
