### ISSUE TITLE
Is it possible to configure the timer to display the remaining time to complete the survey ?

### ISSUE THREAD

**Issue by thomas-berthelot** [surveyjs/survey-library#2191]
Is it possible to configure the timer to display the remaining time only ?

### What is the current behavior?
The timer configuration allows to define the maximum time to complete the survey.
And the survey displays the time spent since the beginning.
For instance, I set 3min to finish the survey, I started the survey 2 min ago, then the page displays 2 min

### What is the expected behavior?
I would like to display the remaining time to finish the survey.
For instance, I set 3min to finish the survey, I started the survey 2 min ago, then the page displays 1 min

**Comment by tsv2013** [comment]
Here is the live sample of a quiz - https://www.surveyjs.io/Examples/Library?id=survey-quiz&platform=jQuery&theme=modern

Then you press "Start" the timer is shown on the top. Does it fit your needs?

**Comment by thomas-berthelot** [comment]
Hello,
no sorry that do not fit my needs.

CURRENT BEHAVIOR:
This is the current behavior on your test survey.

First page
You have 10 seconds for every page and 25 seconds for the whole survey of 3 questions.

Next page
You have spent 2 sec of 15 sec on this page and 22 sec of 25 sec in total.

EXPECTED BEHAVIOR:
I am not interested in the time spent, I am interested in the time remaining.
I would like something like:
You have 22 seconds left to complete that survey.
And if possible a progress bar to display the time spent/time remaining.

Thanks a lot.

**Comment by tsv2013** [comment]
You can hide the built-in timer panel using the https://surveyjs.io/Documentation/Library?id=surveymodel#showTimerPanel property and implement your own one. You can update your custom timer panel in the https://surveyjs.io/Documentation/Library?id=surveymodel#onTimer event handler.
