### ISSUE TITLE
Render TextArea in display as div

### ISSUE THREAD

**Issue by ironman1964** [surveyjs/survey-library#2192]
### Are you requesting a feature, reporting a bug or asking a question?
Enhancement

### What is the current behavior?
in the display version of the survey a textarea is just set to readonly. This keeps the scrollbar on the side if there is lots of text.

### What is the expected behavior?
in display version change it to a div and have all the text inside the div

### How would you reproduce the current behavior (if this is a bug)?
Not a bug, but enhancement !
Easier for "printing" a survey

### Specify your
* browser: Chrome
* surveyjs platform: jquery:
* surveyjs version: 1.7.6

**Comment by dmitrykurmanov** [comment]
We've implemented the feature. It will be available in the next minor release.

Usage example:
```js
var survey= new Survey.Model(json);
survey.readOnlyCommentRenderMode = "div";
```
or via json 
```js
var json = {
  readOnlyCommentRenderMode: "div",
  ...
};
var survey= new Survey.Model(json);
```

**Comment by ironman1964** [comment]
Super working perfectly !!

**Comment by aanavaneeth** [comment]
Associated survey creator changes were also made?

**Comment by tsv2013** [comment]
@aanavaneeth Survey creator is not related to this issue.

**Comment by tsv2013** [comment]
Usage example:

Survey.settings.readOnlyCommentRenderMode = "div";

This option can't be set via survey json.

**Comment by ironman1964** [comment]
This is not working correctly. Using v 1.7.24
See the attached print.
It still renders a textarea and in print it is not font color black.
I can't find the css style for the div anywhere.

So please if readonly, render a div and can you tell me the css class you use to style the div.

![Naamloos](https://user-images.githubusercontent.com/688083/89022235-fa9a0200-d321-11ea-9305-6fe9194b6198.png)

**Comment by tsv2013** [comment]
@ironman1964 Can you share a sample illustrating he issue?

**Comment by ironman1964** [comment]
Sorry nope, is secure system. The screenshot above shows what it does ...

Here's the JSON 
[json.txt](https://github.com/surveyjs/survey-library/files/5069750/json.txt)
And here the HTML file I use
[SurveyPDF.txt](https://github.com/surveyjs/survey-library/files/5069757/SurveyPDF.txt)

Hope this works

**Comment by tsv2013** [comment]
I meant a small plunker sample

**Comment by ironman1964** [comment]
never done that, let me try to do ...

**Comment by tsv2013** [comment]
Thanks a lot, such examples save us a lot of time.

You can use this as a starting point - https://surveyjs.io/Examples/Library?id=survey-displaymode&platform=jQuery&theme=modern

Just press the "Edit in Plunker" link and you will get a ready plunker sample to modify

**Comment by ironman1964** [comment]
I hope this one works :-) https://plnkr.co/edit/72o1l7DXxvlxS58t

**Comment by ironman1964** [comment]
@tsv2013  any news ?

**Comment by dmitrykurmanov** [comment]
@ironman1964 we'll check it ASAP thanks

**Comment by dmitrykurmanov** [comment]
@ironman1964 As you mentioned [here ](https://github.com/surveyjs/survey-library/commit/1609e18fd56b8412d83809130175b9fc8aa21810#commitcomment-41299902) it is the bug. Here the new issue with the bug: https://github.com/surveyjs/survey-library/issues/2352

**Comment by dmitrykurmanov** [comment]
We've changed the property scope. Now it is global. Usage example:
```js
Survey.settings.readOnlyCommentRenderMode = "div";
```
