### ISSUE TITLE
Bug on visible if contains operator

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-library#2193]
Im migrating from survey version 1.0.83 to last one 1.7.7 the thing is there is something different with contains operator because on my survey
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "qid1",
     "visibleIf": "[] contains 'C1'",
     "isRequired": true
    }
   ]
  }
 ]
}
This question was invisible on (1.0.83) and now on version 1.7.7, is visible when the array is empty
### Are you requesting a feature, reporting a bug or asking a question?

Bug
### What is the current behavior?
 The question is visible if the visibleif condition is false
 "visibleIf": "[] contains 'C1'", -> visible

### What is the expected behavior?
 The question is invisible if the visibleif condition is false
 "visibleIf": "[] contains 'C1'", -> invisible

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/bg2dUXOxPT64GBpu

### Specify your
* surveyjs version: 1.7.7

**Comment by jmar1998** [comment]
Anything about this? , this is a bug or is a normal behavior now??

**Comment by andrewtelnov** [comment]
@jmar1998 It works just fine to me. Here is [the example](https://plnkr.co/edit/noem2mYMzzAGI85I).
I have just added a [unit test](https://github.com/surveyjs/survey-library/blob/master/tests/expressions/expressionParserTest.ts#L389) for this scenario, but it works without any code change.

Thank you,
Andrew

**Comment by jmar1998** [comment]
@andrewtelnov , hmm maybe im confusing, but I think the question should be invisible because the visibleIf is false 
why this visibleIf is true
[] contains "C" -> true
and this one is false
["dummy-data"] contains "C" -> false
https://plnkr.co/edit/EYaqM0Fm5yHUxIkO

**Comment by andrewtelnov** [comment]
@jmar1998 I have fixed the issue. We will include into [v1.7.10](https://surveyjs.io/WhatsNew#v1.7.10).
The problem was in incorrect expression grammar.

Thank you,
Andrew

**Comment by jmar1998** [comment]
@andrewtelnov thanks alot :+1:
