### ISSUE TITLE
Panel component not showing on condition

### ISSUE THREAD

**Issue by reeg33** [surveyjs/survey-library#2199]
Hello, I think I'm encountering a bug with the "visible if" feature, with panel component, on a quiz I posted below

### What is the current behavior?
When I answer correctly the radiobutton question, the next page should show 2 components : an image, and a panel with a text

### What is the expected behavior?
Except, it shows only the image, leaving the panel invisible. And I put the same condition on both

### How would you reproduce the current behavior (if this is a bug)?
Just run the survey test

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/create-survey#choose-use-creator-online

Test code

```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question1",
     "choices": [
      "item1",
      "item2",
      "item3"
     ]
    }
   ]
  },
  {
   "name": "page2",
   "elements": [
    {
     "type": "image",
     "name": "imageSuccess",
     "visibleIf": "{question1} = 'item1'",
     "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/lion.jpg"
    },
    {
     "type": "panel",
     "name": "panelSUccess",
     "visibleIf": "{question1} = 'item1'",
     "title": "Well done !",
     "description": ":)"
    }
   ]
  }
 ]
}

```

### Specify your

* browser: Chrome
* browser version: Version 83.0.4103.61 (Build officiel) (64 bits)
* surveyjs platform (angular or react or jquery or knockout or vue): web version https://surveyjs.io/create-survey#choose-use-creator-online (but I will use it on angular)
* surveyjs version: 1.7.9

Thanks for your support

**Comment by tsv2013** [comment]
Panel is visible then it contains at least one visible element inside. This the default behaviour for this grouping survey element.

Panel in your sample is not visible because it doesn't contain any elements inside. If you add at least an empty HTML question it will be visible.
```JSON
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question1",
     "choices": [
      "item1",
      "item2",
      "item3"
     ]
    }
   ]
  },
  {
   "name": "page2",
   "elements": [
    {
     "type": "image",
     "name": "imageSuccess",
     "visibleIf": "{question1} = 'item1'",
     "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/lion.jpg"
    },
    {
     "type": "panel",
     "name": "panelSUccess",
     "elements": [
      {
       "type": "html",
       "name": "question2"
      }
     ],
     "visibleIf": "{question1} = 'item1'",
     "title": "Well done !",
     "description": ":)"
    }
   ]
  }
 ]
}
```

**Comment by reeg33** [comment]
My bad I should'nt have used an empty panel. I only wanted to display a conditional text and it seemed the best approach. But an empty html seems better suited for that/

Thanks
