### ISSUE TITLE
Can't checked again column other after enter text to the box. (matrixdropdown)

### ISSUE THREAD

**Issue by Huuvinh94** [surveyjs/survey-library#2200]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

I have a type matrixdropdown, when i add the column has properties **hasOther = true**, i check at column **Other (describe)** and enter value to the box then click focus out this.
=> Can't checked again column other after enter text to the box.

I have a example as below:
https://plnkr.co/edit/BGRiyn9mn64hcziU

### What is the expected behavior?

Is there the bug?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
I've reproduced the issue. We'll work on the fix.

**Comment by tsv2013** [comment]
Fix will be availalble in the nearest minor update.

**Comment by Huuvinh94** [comment]
@tsv2013 
Thanks your answer.

Also the case, i add properties `columnLayout: 'vertical'`, check at column **Other (describe)**, not enter value to the box then click button complete.
=> Error message as shown below:

![image](https://user-images.githubusercontent.com/18391623/83591673-af15e280-a582-11ea-989d-dcb5754829b9.png)

I think the error message only show up in in the last radio?

At the `input with type radio duplicate id`.

![image](https://user-images.githubusercontent.com/18391623/83592522-bd64fe00-a584-11ea-9159-2702f8d56c3d.png)

![image](https://user-images.githubusercontent.com/18391623/83592546-c655cf80-a584-11ea-9d69-2b53ee2fb1b1.png)

Is this the cause of the error?

**Comment by andrewtelnov** [comment]
@Huuvinh94 I have created [a new issue](https://github.com/surveyjs/survey-library/issues/2203) and fixed it.

**Comment by Huuvinh94** [comment]
@andrewtelnov thanks alot
