### ISSUE TITLE
One Time only answered questions but needed through the survey still

### ISSUE THREAD

**Issue by kevinquanblri** [surveyjs/survey-library#2204]
My questionnaire i'm trying to make has questions that should only be answered once for the users. Ex. Date of Birth and Sex because they don't change. The second or more times the user takes the survey, these two questions should never show up anymore.  

I originally plan on saving date of birth and sex values in a place other than the resultjson so I can pull it easily. However, I'm stuck on how I would do this. I tried using the events from the surveymodel class to change and 
visible properties and/or inject values from the server into the survey but that's not working nor and also causing probems to subsequent questions to not show because they have a dependency for conditional visibility on date of birth and/or sex.

IF anyone can provide me inslight or even evaluate if this is something that is out of the capability of surveyjs?

**Comment by andrewtelnov** [comment]
@kevinquanblri survey has functions: `survey.getValue("yourQuestionName");` and `survey.setValue("yourQuestionName", yourQuestionValue);`. You can use them for this task.

Thank you,
Andrew
