### ISSUE TITLE
If I'm creating an App (Apple/Android) then how SurveyJs will help me?

### ISSUE THREAD

**Issue by lalitkhanna** [surveyjs/survey-library#2208]
### Are you requesting a feature, reporting a bug or asking a question?
No
Just checking If I'm creating an App (Apple/Android) then how SurveyJs will help me?

### What is the expected behavior?
If I'm creating an App (Apple/Android) then how SurveyJs will help me?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
SurveyJS is a JavaScript client side library. Probably major part of functionality will work in a WebView component on a device but this wasn't testsed and we're not going to support mobile devives via JS code. We're planning to create a native iOS/Andriod SurveyJS runner, but this is in far perspective and I can't give you any estimations here.

**Comment by lalitkhanna** [comment]
> SurveyJS is a JavaScript client side library. Probably major part of functionality will work in a WebView component on a device but this wasn't testsed and we're not going to support mobile devives via JS code. We're planning to create a native iOS/Andriod SurveyJS runner, but this is in far perspective and I can't give you any estimations here.

Thanks for info.

**Comment by Some-Java-Developer** [comment]
Hello,

We would love to see some evolution on such a functionality, as it is a very realistic scenario to have this in a more device independent implementation.

Today's applications are usually channel independent (not only cross browser, but also cross device).
Working with a webview is not always that easy if information needs to be exchanged between the Webview and the mobile application (security context to name just one example, but there are others).

Best regards

**Comment by kavandersluis** [comment]
Hi @lalitkhanna, what is the current thinking on when you might develop a native iOS/Android runner for SurveyJS surveys? Is this anywhere on the horizon?

Thanks,
Kirstan
