### ISSUE TITLE
Error messages is not updating on locale change

### ISSUE THREAD

**Issue by xxxKOTxxx** [surveyjs/survey-library#2209]
Hi! 

I have a problem with multi language survey. When I change locale almost all localizable strings updating excluding error messages.

Please check [plunker](https://plnkr.co/edit/ZgrLbUyF7PJBsf5o?preview)
Steps to reproduce:
1) click complete button to show required error message
2) click on locale switch button with current locale ('en')
3) To ensure that 'de' error message supports click complete button again
Current result: error message not changing
Expected result: error message changed to german language

**Comment by tsv2013** [comment]
You need to call the `survey.currentPage.hasErrors(true, true);` function. Here is your updated example - https://plnkr.co/edit/VVZHnNdBgo0iV4Zd

**Comment by xxxKOTxxx** [comment]
> You need to call the `survey.currentPage.hasErrors(true, true);` function. Here is your updated example - https://plnkr.co/edit/VVZHnNdBgo0iV4Zd

I fixed this issue using `isCurrentPageHasErrors` method, but this way all errors appears on language change. So I need to check is errors showed with `onValidatedErrorsOnCurrentPage` callback to conditionally fire validation. Possibly there is simpler way to fix it? I think it'll be nice to fix it in library without adding "crutches" to code.
