### ISSUE TITLE
Open file in new tab Question/Feature

### ISSUE THREAD

**Issue by agustinparamio** [surveyjs/survey-library#2210]
### Are you requesting a feature, reporting a bug or asking a question?
QUESTION, FEATURE

### What is the current behavior?
Clicking file link while loading a survey answer open file in current tab

### What is the expected behavior?
open file in new tab

Im using surveyjs on a react app and I cant find any property to set open file in new tab while loading an answer. 
I managed to do this adding a listener to my body and checking if link clicked belongs to the survey but is would be better to have some property on file widget to set this behavior.

I don't know if there is an option to set this that im missing or it would be a nice feature to have.

**Comment by tsv2013** [comment]
You can implement custom file preview panel with the desired behavior. Here is the working sample - https://surveyjs.io/Examples/Library?id=file-custom-preview&platform=jQuery&theme=modern
