### ISSUE TITLE
Extend DynamicPanel - make title of each panel in panel dynamic changeable depends on collapsed/expanded panel state

### ISSUE THREAD

**Issue by vlad-alt** [surveyjs/survey-library#2214]
Hi. I have a question. Is it possible to make the title of each panel in panel dynamic changeable depends on collapsed/expanded panel state? For example, if panel is collapsed, add to title edit/remove buttons and values of all questions inside this panel. When panel is expanded move edit/remove buttons from title to the bottom of panel and hide questions values from title.

### What is the current behavior?
Template title is string

### What is the expected behavior?
Make template title something like panel (push there some expressions to show to end-user questions value)

**Comment by andrewtelnov** [comment]
@vlad-alt We definitely do not have this functionality out of the box and you would have to write some code. Unfortunately, you should write this code in the core of our library. I am not sure what kind of events should we fire to let you change a panel title and render (show/hide) additional buttons.
Could you share with us your design? Why do you need this functionality?

Thank you,
Andrew
