### ISSUE TITLE
Get the complete set of json

### ISSUE THREAD

**Issue by karishmasahu** [surveyjs/survey-library#2216]
Hi,

As per the image attached below, for example if a user answers 2 questions of the survey instead of all.
I want to achieved a json that gives which all questions the user have answered and which are not by rendering the template again.
Any suggestions to achieve this?

![image](https://user-images.githubusercontent.com/33975459/84235326-4e068580-ab13-11ea-846a-38902fe03411.png)

**Comment by andrewtelnov** [comment]
@karishmasahu Could you please provide more information what exactly do you want to do? What is the primary reason? Do you want to allow somebody to review answered/all questions?

Thank you,
Andrew

**Comment by karishmasahu** [comment]
What I want is when the user completed the survey, then the admin wants to review and know which all questions are answered and which are not.

**Comment by andrewtelnov** [comment]
@karishmasahu every question has function `question.isEmpty()`. You can use it to remove/hide a question for your admin. 
Thank you,
Andrew
