### ISSUE TITLE
Go to a question on a page

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/survey-library#2220]
Hi, is there a way to locate a question on a page. For example, the name on the second page is A. How do I get to the question A on the page?

**Comment by tsv2013** [comment]
You can subscribe the https://surveyjs.io/Documentation/Library?id=surveymodel#onAfterRenderQuestionInput event, get the input element of a question, store it somewhere and then use this stored reference to the DOM element to scroll it into view of focus.

**Comment by fengzhihenxs** [comment]
@tsv2013  Okay, thank you. I have achieved
