### ISSUE TITLE
How to reset other description?

### ISSUE THREAD

**Issue by sem1colon** [surveyjs/survey-library#2221]
Is there a option to clear previously entered description while rechecking/re-selecting other?

**Comment by tsv2013** [comment]
Here is the working sample - https://plnkr.co/edit/TMpvnGzewZipgfzs
Does it fir your needs?

**Comment by sem1colon** [comment]
@tsv2013 That doesn't help for checkbox type.

**Comment by tsv2013** [comment]
Here is the updated plunker - https://plnkr.co/edit/vFtZFx7N1v0TYhWB

**Comment by sem1colon** [comment]
This also doesn't work. It will clear other text if you check any other choice after checking others.

**Comment by sem1colon** [comment]
Is there a way?

**Comment by tsv2013** [comment]
The selectbase question type stores previously entered other value in order to restore it on the next "Other" item selecttion.

You can use the obsolete flag - "storeOthersAsComment: false". Here is the plunker - https://plnkr.co/edit/H8voY5GSsfxhuPVE

**Comment by sem1colon** [comment]
This works, but with this a lot of refactoring needs to done in the save logic. Thanks though.

**Comment by sem1colon** [comment]
This also doesn't work. When you check a choice after entering other text, the result json just consists of only *other* not the other value.

**Comment by tsv2013** [comment]
It's a bug. We'll fix it.

**Comment by tsv2013** [comment]
I've fixed the issue via the above commit. Fix will be available in the nearest update, most likely tomorrow.
