### ISSUE TITLE
How to add hover text for Row's 1st column in matrix?

### ISSUE THREAD

**Issue by sem1colon** [surveyjs/survey-library#2222]
Also, how can we add for choices?
I am able to get for the title, but I want to have different tooltips for title, choices/rows' 1st column. Is it possible? or it will override something?

**Comment by tsv2013** [comment]
You can subscribe the https://surveyjs.io/Documentation/Library?id=surveymodel#onAfterRenderQuestion event and patch markup according your needs.

**Comment by sem1colon** [comment]
Do we need to add something like this for getting tooltip for choices/rows?
`Survey.JsonObject.metaData.addProperty("questionbase", "tooltip");`

**Comment by sem1colon** [comment]
Okay, I figured out there are seperate events `onAfterRenderQuestionInput` & `onMatrixAfterCellRender`

**Comment by sem1colon** [comment]
@tsv2013 Still, not able to get the *tooltip* property inside the choices array.

**Comment by sem1colon** [comment]
Is it possible to add tooltip for particular word in question title?

**Comment by tsv2013** [comment]
>Is it possible to add tooltip for particular word in question title?

No
