### ISSUE TITLE
onComplete functionality in custom button

### ISSUE THREAD

**Issue by karishmasahu** [surveyjs/survey-library#2223]
Hi,
on click of complete what all functionality surveyJs provides, I want to implement the same in another custom button.
How can I achieve this?

**Comment by tsv2013** [comment]
You can call the `doComplete` function of the survey - https://github.com/surveyjs/survey-library/blob/master/src/survey.ts#L3127-L3148

**Comment by karishmasahu** [comment]
Yes it worked!!
Thanks

**Comment by karishmasahu** [comment]
The doComplete function doesnot validate form required fields.
Suppose a template has got some mandatory fields, then the complete button validates those mandate fields. But if  we create a custom button and call the doComplete function, then form validation is not happening.
How to achieve this?

**Comment by andrewtelnov** [comment]
@karishmasahu You need to use ``survey.completeLastPage()`` function. It will check errors.

Thank you,
Andrew

**Comment by karishmasahu** [comment]
Superb!! It worked :)
