### ISSUE TITLE
Question answer line layout

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/survey-library#2224]
Hi, I see that the colCount attribute controls the number of columns in the answer, but I don't see the control row. Is there a way to customize the line layout of the question, for example a question of type checkbox, it has 4 answers which are A, B, C and D, I want the layout of the answer to be three lines, A and D are in one line, B On one line, D is on one line. Can it be achieved?

**Comment by tsv2013** [comment]
SurveyJS doesn't have such an option out of the box. But most likely this can be achieved via custom CSS. Or you can patch the markup in the https://surveyjs.io/Documentation/Library?id=surveymodel#onAfterRenderQuestion event handler

**Comment by fengzhihenxs** [comment]
@tsv2013  Thanks, I will try it. By the way, how to get the value of the current page?

**Comment by tsv2013** [comment]
`survey.currentPage`

**Comment by fengzhihenxs** [comment]
@tsv2013 thank you very much
