### ISSUE TITLE
completedHtml translation not saved

### ISSUE THREAD

**Issue by ironman1964** [surveyjs/survey-library#2227]
### Are you requesting a feature, reporting a bug or asking a question?
completedHtml translation is not saved

### What is the current behavior?
completedHtml only in default language in JSON

### What is the expected behavior?
completedHtml in default and other languages in JSON

### How would you reproduce the current behavior (if this is a bug)?
Add language to survey and add completedHtml in survey designer, then go into translation and add translation for completedHtml, save it and restore survey ... 

* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.7.9

**Comment by tsv2013** [comment]
Here is the live sample - https://plnkr.co/edit/zrn7P0GFFviugFN3
It works ok for me. You can modify it to reproduce your issue
