### ISSUE TITLE
Min/ Max Function not working properly when there is zero value

### ISSUE THREAD

**Issue by shekharkc** [surveyjs/survey-library#2229]
### Are you requesting a feature, reporting a bug or asking a question?

Possible bug

### What is the current behaviour?
1. Min/ Max function, when used to compare an 'expression' type question, doesn't yield expected results. Details:
  a.   The min/max function returns the param to be compared with when the 'expression' question is yet to get an initial value (owing to lack of inputs) instead of returning correct [result(screenshot1)](url)
b. When compared with a zero, min/ max function returns the param to be compared with instead of the correct result (screenshot 2)

### What is the expected behaviour?

In 1a, would expect a 'zero' or 'null' or 'undefined' to be returned 
In 1b, the correct result.

### How would you reproduce the current behavior (if this is a bug)?

Pl, see the att code.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code  

```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "question1",
     "title": "Enter Number 1",
     "inputType": "number"
    },
    {
     "type": "text",
     "name": "question2",
     "title": "Enter Number 2",
     "inputType": "number"
    },
    {
     "type": "text",
     "name": "question3",
     "title": "Enter Number 3",
     "inputType": "number"
    },
    {
     "type": "expression",
     "name": "question4",
     "title": "Sum of numbers",
     "expression": "{question1}+ {question2} + {question3}",
     "commentText": "Other (describe)"
    },
    {
     "type": "expression",
     "name": "question5",
     "title": "Max function test",
     "expression": "max({question4}, 200)",
     "displayStyle": "decimal",
     "maximumFractionDigits": 0,
     "minimumFractionDigits": 0,
     "commentText": "Other (describe)"
    },
    {
     "type": "expression",
     "name": "question6",
     "title": "Min function test",
     "expression": "min({question4}, 200)",
     "displayStyle": "decimal",
     "maximumFractionDigits": 0,
     "minimumFractionDigits": 0,
     "commentText": "Other (describe)"
    }
   ]
  }
 ]
}

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

![image](https://user-images.githubusercontent.com/32909897/85097802-4ed79f80-b216-11ea-98f3-633bfdfe78ee.png)

![image](https://user-images.githubusercontent.com/32909897/85097814-5b5bf800-b216-11ea-94b3-7c346b02e093.png)

**Comment by andrewtelnov** [comment]
@shekharkc Indeed, it is a bug. I have added a new unit test and fixed it in the commit above. We will include the fix in [v1.7.13[(https://surveyjs.io/WhatsNew#v1.7.13)
