### ISSUE TITLE
Accessing Individual <select> in matrixdropdown question

### ISSUE THREAD

**Issue by ajax-crypto** [surveyjs/survey-library#2230]
Asking a Question
-------------------------------------------
Given a matrixdropdown question type with multiple rows and columns, where every cell type in a dropdown, I want to access the select elements by (row, col) coordinates. 

Why do I need it?
----------------------------------------------
I need to be able to disable/enable drop down(s) based on the change of option selection in any one drop-down (all within the same matrix question).
Something like 

`if (matrixquestion.dropdown[0][0].value == 1) `
     `     matrixquestion.dropdown[0][2].setEnabled();`

The change of select is accessed in onValueChanged event.

* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version: Latest

**Comment by andrewtelnov** [comment]
@ajax-crypto We do not have enable out of the box, but you can make your items visible/invisible based on value in another column. Here is the [example](https://plnkr.co/edit/RZHND8ws9rKHexet).

Thank you,
Andrew
SurveyJS Team

**Comment by ajax-crypto** [comment]
@andrewtelnov  Thanks for the example, but I am not looking to disable entire column. I want a per drop-down enableIf property (not per row or column, which I am aware of).
i.e. if row1, col1 drop-down has selected option A, disable row2,col2 dropdown (something like that)

**Comment by andrewtelnov** [comment]
@ajax-crypto We can't make them disable, but you can make choices visible/invisible by using choicesVisibleIf property. Here is the updated [example](https://plnkr.co/edit/0RY5o5SLAQnmqoY7).

Thank you,
Andrew

**Comment by ajax-crypto** [comment]
Thank you for the example! I guess I will then have to use the dropdown ID's to do the enable/disable of dropdowns.

**Comment by andrewtelnov** [comment]
@ajax-crypto I have fixed [the following bug](https://github.com/surveyjs/survey-library/issues/2237). From the next minor version that we are going to release in one-two days, you will be able to use choicesEnableIf as you can use choicesVisibleIf.
