### ISSUE TITLE
validate whether Json file able to render the template or not

### ISSUE THREAD

**Issue by karishmasahu** [surveyjs/survey-library#2232]
Suppose there a button to upload a json file.. once the file is uploaded basically it has to display the template whatever provided in the file.
So if we provide any invalid json for which template cannot be rendered then I want to display some message.

So is there any functionality to validate the json in surveyJs?

**Comment by andrewtelnov** [comment]
@karishmasahu on loading invalid JSON [survey.jsonErrors](https://surveyjs.io/Documentation/Library?id=surveymodel#jsonErrors) array property will not be null and empty.

Thank you,
Andrew
