### ISSUE TITLE
SumInArray with nested paneldynamic and matrixdropdown

### ISSUE THREAD

**Issue by shekharkc** [surveyjs/survey-library#2234]
### Are you requesting a feature, reporting a bug or asking a question?

Question or a bug

### What is the current behavior?

sumInArray not working for nested panelDynamic/ matrixdropdown

1. To my understanding, sumInArray function should be able to compute the sum of any referenceable element in an Array. If we have a nested paneldynamic wrapping additional paneldynamic or matrix elements inside - we should be able to sum any referenceable element inside the nested array structure.
2. But, apparently, that is not working or maybe my understanding isn't correct.
3. As an example, if we want to sum all Income received from multiple employers, and the Income has multiple heads, one would want to wrap it in a json structure like the one attached, sum up Income from one Employer and use a function like sumInArray to sum up Income from all employers.

### What is the expected behavior?

I would expect the sumInArray function to return the sum of  all the referenced element in an Array

### How would you reproduce the current behavior (if this is a bug)?

Not sure if it is a bug.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "paneldynamic",
     "name": "income_from_all_employers",
     "indent": 2,
     "title": "Income from Employers",
     "templateElements": [
      {
       "type": "paneldynamic",
       "name": "income_from_employer",
       "title": "Income from Employer",
       "templateElements": [
        {
         "type": "text",
         "name": "Employer Name"
        },
        {
         "type": "matrixdropdown",
         "name": "salary",
         "title": "Salary Details",
         "columns": [
          {
           "name": "amount",
           "title": "Amount",
           "cellType": "text",
           "totalType": "sum",
           "totalFormat": "total salary = {0}",
           "totalDisplayStyle": "decimal"
          }
         ],
         "cellType": "text",
         "rows": [
          {
           "value": "basic_salary",
           "text": "Basic Salary"
          },
          {
           "value": "other_heads_salary",
           "text": "Other heads of Salary "
          }
         ]
        },
        {
         "type": "matrixdropdown",
         "name": "allowances",
         "title": "Details of Allowances",
         "columns": [
          {
           "name": "amount",
           "title": "Amount",
           "cellType": "text",
           "totalType": "sum",
           "totalFormat": "total allowances = {0}",
           "totalDisplayStyle": "decimal",
           "inputType": "number"
          }
         ],
         "cellType": "text",
         "rows": [
          {
           "value": "1",
           "text": "Travel Allowance"
          },
          {
           "value": "2",
           "text": "House Rent Allowance"
          },
          {
           "value": "3",
           "text": "Dearness Allowance"
          },
          {
           "value": "4",
           "text": "Other Allowances (total)"
          }
         ]
        },
        {
         "type": "expression",
         "name": "gross_income",
         "title": "Total Income from Employer",
         "expression": "{panel.salary-total.amount} + {panel.allowances-total.amount}",
         "commentText": "Other (describe)"
        }
       ],
       "allowAddPanel": false,
       "allowRemovePanel": false,
       "panelCount": 1,
       "minPanelCount": 1,
       "maxPanelCount": 1
      },
      {
       "type": "expression",
       "name": "gross_income_all_employers",
       "title": "Gross Income from all Employers",
       "expression": "sumInArray({income_from_all_employers}, 'income_from_employer[0].gross_income')",
       "commentText": "Other (describe)"
      }
     ],
     "panelCount": 1,
     "minPanelCount": 1,
     "renderMode": "progressBottom"
    }
   ]
  }
 ]
}

```

### Specify your

* browser: Chrome
* browser version: Version 83.0.4103.97 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: 1.7.12

**Comment by tsv2013** [comment]
Yes, it doesn't process nested structures because they can be of different types.

You can write your custom function as described in documentation https://surveyjs.io/Documentation/Library?id=LibraryOverview#conditions-functions
