### ISSUE TITLE
How to create Multi-line column header in matrixdropdown question?

### ISSUE THREAD

**Issue by ajax-crypto** [surveyjs/survey-library#2236]
I am trying to create custom header for columns in matrixdropdown question type, where the column text will have two lines, with different font-size. Adding <br> or <font> to title property of columns do not work as intended, and they get displayed as is i.e.

 `columns: [ { title: "Line One <br> <small>Line 2</small>", name:"col1" } ... ]`

This will have no effect and display the tags as well. How can we achieve this?

* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version: Latest

**Comment by andrewtelnov** [comment]
@ajax-crypto You should use a markdown library. Here is [the example](https://surveyjs.io/Examples/Library?id=survey-markdown-matrix).

Thank you,
Andrew

**Comment by ajax-crypto** [comment]
Thank you for the example! It works great.
