### ISSUE TITLE
Matrix Question answered class is not coming while loading the saved data.

### ISSUE THREAD

**Issue by sem1colon** [surveyjs/survey-library#2239]
`sv-question__title--answer` is not loading while loading the survey with the saved data.

**Comment by tsv2013** [comment]
Thank you for the report. We'll work on the fix.

**Comment by dk981234** [comment]
Hello,

We can't reproduce the issue. Here is a [sample](https://surveyjs.io/Examples/Library?id=survey-data&platform=Angular2&theme=modern) and it works fine. Could you please provide us more information (json and some results)?

Thanks,
Dmitry
SurveyJS Team
