### ISSUE TITLE
How can I listen to previous page event?

### ISSUE THREAD

**Issue by kmvbatista** [surveyjs/survey-library#2241]
I'm having to manually handle pagination, how can I listen to the previous page event?

**Comment by andrewtelnov** [comment]
@kmvbatista There two events: [survey.onCurrentPageChanging](https://surveyjs.io/Documentation/Library?id=surveymodel#onCurrentPageChanging) [survey.onCurrentPageChanged](https://surveyjs.io/Documentation/Library?id=surveymodel#onCurrentPageChanged). The are both have a boolean property "option.isPrevPage", it is true if end-user click on Previous button.

Thank you,
Andrew
