### ISSUE TITLE
How can I get DOM representation of question in afterRender method for another question 

### ISSUE THREAD

**Issue by vlad-alt** [surveyjs/survey-library#2253]
Hi. I have a question. I want to create popup window with questions of current page, that marked my custom attribute to true. I have created custom widget for this popup (simple button that open the modal window) and I get all parent questions and check my custom property. When page is loaded I want to hide those questions, when open modal button pressed I want to show them in modal.

#1422 # Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the current behavior?
There is no property in questions with htmlElement (I have found property renderedElement but sometimes it is null, sometimes question don't have this property)

### What is the expected behavior?

In afterRender method of my custom widget I can see parent questions and their DOM representation.

Something like this:

//find sibling questions that should be shown in modal
let parentQuestions = question.parent.questions.filter(q => q.myCustomProperty === true);
//append questions to popup
myCustomWidgetDom.append(questions.map(q.propertyWithQuestionDomRepresentation));

Thanks

**Comment by tsv2013** [comment]
There is no access to DOM elements in survey model. You can collect necessary questions into a new temporary survey created on-the-fly and show this temporary survey in a popup window.

**Comment by vlad-alt** [comment]
Thanks a lot for answer
