### ISSUE TITLE
Custom input attributes

### ISSUE THREAD

**Issue by jheathco** [surveyjs/survey-library#2256]
Is there a way to use custom input attributes?  For example, we'd like our text inputs to be able to support **inputmode** for numerics, and **autocomplete="one-time-code"** for OTP verification.

**Comment by tsv2013** [comment]
You can access and patch the question rendered markup in the https://surveyjs.io/Documentation/Library?id=surveymodel#onAfterRenderQuestionInput or in the https://surveyjs.io/Documentation/Library?id=surveymodel#onAfterRenderQuestion event handlers.

Also you can create a custom question type (custom widgets) like shown in this live samples - 
https://plnkr.co/edit/HdnYE5?p=preview
https://plnkr.co/edit/fUTjd8JcTFLxtr2tkTJf?p=preview&preview
