### ISSUE TITLE
Get values of custom page and panel properties, then make calculations based on them

### ISSUE THREAD

**Issue by 33Piter** [surveyjs/survey-library#2259]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question

### What is the current behavior?

I have custom properties of page, question and panel. These properties will be used to make score calculations.

Ie: 

Page1: weight 3
  Panel1: weight 53
    Question1 (radiogroup)
      A score 100
      B score 70
      C score 20

Result: score = (page weight x panel weight x question weight)

Can't find a way to get the values of page and panel, just the values of the question.

### What is the expected behavior?

Show the calculated score at the result page.

### How would you reproduce the current behavior (if this is a bug)?

Not a bug

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

var json = 
{
  "pages": [
   {
    "name": "Name1",
    "elements": [
     {
      "type": "panel",
      "name": "painel1",
      "elements": [
       {
        "type": "radiogroup",
        "name": "question1",
        "title": "Question 1",
        "number_of_questions": 1,
        "choices": [
         {
          "value": "item1",
          "text": "high",
          "score": 100
         },
         {
          "value": "item2",
          "text": "mid",
          "score": 70
         },
         {
          "value": "item3",
          "text": "low",
          "score": 20
         }
        ]
       }
      ],
      "title": "Panel Title",
      "panel_score": 53
     }
    ],
    "title": "Page Title",
    "page_score": 3
   }
  ]
 };

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
Similar questions were discussed here https://surveyjs.answerdesk.io/ticket/details/t3912/accumulative-score-for-all-questions
and here https://surveyjs.answerdesk.io/ticket/details/t3702/custom-score-property

You need to add the `score` custom property and use the `getPlainData` function or write your own similar one.

**Comment by 33Piter** [comment]
Thank you very much for your response!

I just started on the tool and I still didn't know the getPlainData function.

I did a test showing a raw survey.getPlainData, and it returned the values within the questions. This function will be of great use to me, but I still need help with part of the problem:

**How do I get custom property values for pages and panels?** (in my example, the page_score and panel_score).


My goal is for the user to create a survey using predefined array of weights (in a dropdown) for the Page and Panel elements, and also to set predefined values for the weight of each option in checkbox/radiogroup. I've already managed to create all these features.

An example of calculating the score would be: Page weight * Panel weight * Weight of chosen answer = score (applying this to each question)

What I have in mind for this calculation would be to create a loop between each answer, taking its value + the 2 values above (panel and page), and so doing the calculation.

Am I going the right way? If you can guide me on what functions can be useful in this process, I would be very grateful.


Thanks is advance.

**Comment by 33Piter** [comment]
I had some success using the functions getPageByName, getPanelByName and getQuestionByName!

I used one of the reference calculation functions that you gave me.

Made a Plunker to exemplify: https://plnkr.co/edit/BT9VWJ9B1sZ3jkYr

Now I just need to create a function to call these values automatically, for each element of the survey, without having to specify each name on the code, and so that the calculation accesses the parent values of each question (page_weight and panel_weight).

Any guidance on how to get there?

**Comment by tsv2013** [comment]
I don't understand why do you add the `page_weight` simultaneously to a `page` and to an `itemvalue` objects? And the same with other weights.

```JS
Survey.JsonObject.metaData.addProperty("page", {name: "page_weight"});    
Survey.JsonObject.metaData.addProperty("itemvalue", {name: "page_weight"});
```

My idea is pretty simply. You add the `score` property to each question and choice item. After surveyee answers a survey, you traverse recursively through the survey structure - from survey through all pages, in every page through all panels and questions,  in every panel through all inner panels and questions - and calculate scores for panels and pages. You can combine any output data structure when you will be traverse this tree-like structure of a survey and get any result you want.
