### ISSUE TITLE
add icon inside expression field

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#2266]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

I would like to render expression input field with a small icon on the right. I managed to do it

https://plnkr.co/edit/3RpZ1H49bNn82wb5

but it disappear after expression is run

### What is the expected behavior?

I would like to keep the icon

thank you

**Comment by tsv2013** [comment]
The thing is that element with inputId id re-rendered on calculation.
You can add the icon to the parent element as I do in your forked plunk - https://plnkr.co/edit/syzqJePLiTcOoF9E

**Comment by masciugo** [comment]
thank you. It seems to work without `display: inline-block;` too. I'd add as little code as possible
