### ISSUE TITLE
Is it possible to modify default question`s html ?

### ISSUE THREAD

**Issue by WoodenPC** [surveyjs/survey-library#2271]
Hi. Is it possible to modify default question`s html? For example if i want to edit imagepicker and replace some of inner html parts

**Comment by tsv2013** [comment]
Yes, you can patch rendered markup in the https://surveyjs.io/Documentation/Library?id=surveymodel#onAfterRenderQuestion event handler

Or create a custom widget like in this live sample -  https://plnkr.co/edit/fUTjd8JcTFLxtr2tkTJf?p=preview&preview

**Comment by tsv2013** [comment]
These modifications are not related to SurveyJS Creator functionality

**Comment by WoodenPC** [comment]
Thanks!
