### ISSUE TITLE
Custom widget & goNextPageAutomatic 

### ISSUE THREAD

**Issue by fchris82** [surveyjs/survey-library#2272]
I have made my custom widget that is based on this: https://embed.plnkr.co/plunk/l6uF1U . I would like it to behave like `radiogroup` : if I select 1 value, go forward. How could I solve this?

**Comment by tsv2013** [comment]
If the base question type of a custom widget supports the `goNextPageAutomatic` option, then custom widget will also support it.

Here is the working plunker - https://plnkr.co/edit/hjFyTylUOjRA4bG3
The "textwithbutton" custom widget is based on the "text" question:
```JS
Survey.JsonObject.metaData.addClass("textwithbutton", [], null, "text");
```
so it also supports the `goNextPageAutomatic` option as you can see from this sample.

**Comment by fchris82** [comment]
Ok, I tried to use `radiogroup` parent, because my custom widget is similar, but I added `icon` property to choicable items, and it doesn't work with `radiogroup`. With `text` parent - it seems - solved the problem. `goNextPageAutomatic` works, and my icons works too.
