### ISSUE TITLE
Clear Validation Error On Change

### ISSUE THREAD

**Issue by BryanEuton** [surveyjs/survey-library#2273]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a Question

### What is the current behavior?
When an error message is displayed, the message is only removed after the page is re-submitted.

### What is the expected behavior?
Can we trigger a re-validate on the question after the answer has changed so that the error message is removed?

### How would you reproduce the current behavior (if this is a bug)?
Submit any Survey that has a required field without entering an answer.

* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.7.18

**Comment by andrewtelnov** [comment]
@BryanEuton We have implemented this functionality in v1.7.19. Here is [the related Issue](https://github.com/surveyjs/survey-library/issues/2265).
