### ISSUE TITLE
[Question] - Merging two surveys

### ISSUE THREAD

**Issue by SaraaAwwad** [surveyjs/survey-library#2275]
### Are you requesting a feature, reporting a bug or ask a question?
question

### What is the current behavior?
I have two surveys that i would like to fall under the same one. So, i take the pages only from the latter survey and append them to the first survey. It works fine, however, when a question has the same name as a question from the other survey as expected it creates an error in preview or doesn't show. 

### What is the expected behavior?
So is there any suggestion on how to handle this without actually looping on each question from the second form and changing/appending to its name? because that wouldn't be the best approach because of question dependencies. 

* browser: chrome
* editor version:

**Comment by mohamedHassanee** [comment]
can i add prefix to question name in survey?

**Comment by tsv2013** [comment]
Sure: `question.name = "my_prefix_" + question.name;`

**Comment by mohamedHassanee** [comment]
where should i put this 

> Sure: `question.name = "my_prefix_" + question.name;`

where should id put this line in angular to applied automatically?

**Comment by tsv2013** [comment]
>where should i put this line in angular to applied automatically?
The merge operation is not performed automatically. This code shoud be written in the place where you implement survey merging. (If you are asking your question in context of this thread.) 

Sorry but I don't understand what do you want to achieve. If you explain your scenario in greater details and can give you more appropriate advice.

**Comment by adityadubey1996** [comment]
i am looking to merge 2 survey but the survey js is returning null

**Comment by andrewtelnov** [comment]
@adityadubey1996 You can post here your example in plunker, so we can look.
