### ISSUE TITLE
How to remove the "add column" button for matrixdynamic vertical layout

### ISSUE THREAD

**Issue by mark-wilkinson** [surveyjs/survey-library#2285]
Hello,

I currently have a survey which uses the matrixdynamic type which looks great! However, I find for some of my survey questions it looks better using the vertical layout rather than horizontal. The only problem I have is the "Add Column" button that displays on top of the matrix. I've looked at the documentation and tried every column related property but nothing seems to hide the button. This only displays when switching from horizontal to vertical layout.

Can someone point me in the right direction?

Any help would be appreciated.

Cheers,

**Comment by andrewtelnov** [comment]
@mark-wilkinson Please set ``allowAddRows`` property to ``false``. For matrix dynamic it is still rows.

Thank you,
Andrew

**Comment by mark-wilkinson** [comment]
Hey @andrewtelnov ,

Many thanks for the speedy reply! I've added this to my json but it still showing, here's part of my json:

`{
                    type: "matrixdynamic",
                    name: "houseHoldDetails",
                    title: "   ",
                    minRowCount: 1,
                    allowAddRows: false,
                    columnLayout: "vertical",
                    columns: [
                        {`

**Comment by andrewtelnov** [comment]
@mark-wilkinson It works fine to me. Here is [the example](https://plnkr.co/edit/QeKERxlPulXHB19v).

Thank you,
Andrew

**Comment by mark-wilkinson** [comment]
Hey @andrewtelnov,

I've forked off a sample one, what am I doing wrong in here:
https://plnkr.co/edit/HLmudXdsoebHmnv6

Cheers,
Mark

**Comment by andrewtelnov** [comment]
@mark-wilkinson You are using very old version. Very likely there is no ``allowAddRows`` property in this version.

Thank you,
Andrew

**Comment by mark-wilkinson** [comment]
@andrewtelnov turns out I am using an older version of surveyjs! I've upgraded and now it is working. Thank you :)
