### ISSUE TITLE
Change page title to <h1> triggers exception Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by jbrou015** [surveyjs/survey-library#2286]
#1422 # Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
The page title are h4 and I want them to be h1

### What is the expected behavior?
I can have control on the page title style.

### How would you reproduce the current behavior (if this is a bug)?
.

#### Provide the test code and the tested page URL (if applicable)

The best I came up with is...

```javascript
   survey.onAfterRenderPage.add(function (survey, options) {
        // Change page title to <h1>
        switchPageTitleToH1();
    });

function switchPageTitleToH1() {
    var pagetitle = $("h4.sv_page_title");
    pagetitle.replaceWith(function () {
        return "<h1 class='sv_page_title'><span style='position: static; '><span style='position: static;'>" + $(this).text() + "</span></span></h1>";
    });
}
```

This way is working until I get to the preview page! I get an exception: DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

![image](https://user-images.githubusercontent.com/47859593/87967268-93ac5b80-ca8c-11ea-9481-90653e06e4ac.png)

### Specify your

* browser: any
* browser version: any
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version:v1.7.12

**Comment by tsv2013** [comment]
I've created a live sample for you - https://plnkr.co/edit/e75W5Q6wJGaG1oEG with SurveyJS latest version - 1.7.23
It works ok for me: h4 tags are changed to h1 on the every page and no errors/warnings in console
Do I miss something?

**Comment by jbrou015** [comment]
It works until you reach the preview page. The preview page doesn't show and there is a Vue exception being thrown. 

It looks like when you build the preview page, all Survey Pages becomes Panels, and then somehow, Survey.js is looking for H4.sv_page_title but can't find them so it craps.

**Comment by tsv2013** [comment]
Can you modify this plunker https://plnkr.co/edit/e75W5Q6wJGaG1oEG to show me the issue?

**Comment by jbrou015** [comment]
Your example is fine. Did you try to access the 'Preview' page?

**Comment by tsv2013** [comment]
What is the "Preview" page you are talking about? How to see it?

**Comment by jbrou015** [comment]
The Preview page is at the end of the survey when your are in display mode. You can review your survey before completing it. There is edit buttons that take you directly to the desired question.

[https://surveyjs.io/Documentation/Library?id=surveymodel#showPreviewBeforeComplete]

**Comment by tsv2013** [comment]
I've updated my sample - https://plnkr.co/edit/e75W5Q6wJGaG1oEG
Added the "showPreviewBeforeComplete": "showAllQuestions", option
I've not got any errors in console on the preview page

**Comment by jbrou015** [comment]
In your latest plunker your are using **sv_p_title** instead of **sv_page_title**
```
function switchPageTitleToH1() {
    var pagetitle = $("h4.sv_p_title");
    pagetitle.replaceWith(function () {
        return "<h1 class='sv_p_title'><span style='position: static; '><span style='position: static;'>" + $(this).text() + "</span></span></h1>";
    });
}
```
instead of 
```
function switchPageTitleToH1() {
    var pagetitle = $("h4.sv_page_title");
    pagetitle.replaceWith(function () {
        return "<h1 class='sv_page_title'><span style='position: static; '><span style='position: static;'>" + $(this).text() + "</span></span></h1>";
    });
}
```

**Comment by tsv2013** [comment]
Im the https://plnkr.co/edit/e75W5Q6wJGaG1oEG there is no "h4.sv_page_title" elements on pages. If you comment the `switchPageTitleToH1` function off and check the markup you will see that page header is the "h4.sv_p_title" element

**Comment by jbrou015** [comment]
I am using the defaultStandardCss, I should have mentioned that. I

**Comment by tsv2013** [comment]
Can you provide the sample illustrating the issue?

**Comment by jbrou015** [comment]
```
Survey
    .StylesManager
    .applyTheme("default");

var json = {
  "showPreviewBeforeComplete": "showAllQuestions",
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "name": "name",
          "type": "text",
          "title": "Please enter your name:",
          "placeHolder": "Jon Snow",
          "isRequired": true
        }
      ]
    },
    {
      "name": "page1",
      "elements": [
        {
          "type": "text",
          "name": "email",
          "title": "Thank you for taking our survey. Your survey is almost complete, please enter your email address in the box below if you wish to participate in our drawing, then press the 'Submit' button."
        }
      ]
    }
  ]
}

window.survey = new Survey.Model(json);

 survey
	.onComplete
	.add(function (result) {
		document
			.querySelector('#surveyResult')
			.textContent = "Result JSON:\n" + JSON.stringify(result.data, null, 3);
	});

survey.onAfterRenderPage.add(function (survey, options) {
	// Change page title to <h1>
	switchPageTitleToH1();
});

survey.onCurrentPageChanged.add(function (survey, options) {
	// Change page title to <h1>
	switchPageTitleToH1();
});

function switchPageTitleToH1() {
	var pagetitle = $("h4.sv_page_title");
	pagetitle.replaceWith(function () {
		return "<h1 class='sv_page_title'><span style='position: static; '><span style='position: static;'>" + $(this).text() + "</span></span></h1>";
	});
}
```

**Comment by jbrou015** [comment]
If you can't reproduce then it might be an issue with my code somehow. 
Thanks for your help.

**Comment by tsv2013** [comment]
Can you modify my plunker sample in order to get live example of the issue?

**Comment by jbrou015** [comment]
https://plnkr.co/edit/C6Kv2M3OHBXvxG3s

I also forgot to mention that I do not use any style but my own custom css.
```
Survey.StylesManager.Enabled = false;
```

**Comment by tsv2013** [comment]
Your plunker works ok for me. Probably because there are no page titles in this survey...

**Comment by tsv2013** [comment]
If I missed something please describe the exact steps to reproduce the issue on your plunker.

**Comment by jbrou015** [comment]
I have updated the page title
