### ISSUE TITLE
Survey Called inside web view of Android App fails for some of the controls.

### ISSUE THREAD

**Issue by nikh0001** [surveyjs/survey-library#2289]
I am using the survey created inside the survey creator with some open file dialog controls using the file uploader control in survey js. The open file dialog is working fine inside the web browser of mobile and desktops. 

But when the the survey is loaded inside the web view of an android application it does not work. Button of the choose file dialog gets clicked but nothing happens. I tried adding the permission of storage and internet as well to the android app but still it does not work as expected.

**Comment by tsv2013** [comment]
SurveyJS Libraries are supposed to be used in browsers only.

Yes, some native options can not work in modile devices web view. See the https://surveyjs.answerdesk.io/ticket/details/t3546/choose-file-option-not-working-in-android-device-ionic-4 for more details.

**Comment by nikh0001** [comment]
> SurveyJS Libraries are supposed to be used in browsers only.
> 
> Yes, some native options can not work in modile devices web view. See the https://surveyjs.answerdesk.io/ticket/details/t3546/choose-file-option-not-working-in-android-device-ionic-4 for more details.

The link mentioned above is a private ticket and I am not able to view it.

**Comment by tsv2013** [comment]
@nikh0001 The mentioned link doesn't contain the solution of the problem. It contains description of the issues with file input cointrol inside the Ionic application. SurveyJS Libraries at this moment are pure JavaScript client side solution created to work in web browsers only.
