### ISSUE TITLE
Complete trigger doesn't work

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-library#2290]
Live sample in plunker: https://plnkr.co/edit/FSwG2tDYdy7FyQGc

![image](https://user-images.githubusercontent.com/30930391/88309419-f44ec900-cd16-11ea-899e-c92a99dfc79d.png)

**Comment by andrewtelnov** [comment]
@gologames We process "complete" trigger on pressing "Next" button by default. You can use the following code to change it:
``Survey.settings.executeCompleteTriggerOnValueChanged = true;``

Thank you,
Andrew
