### ISSUE TITLE
Custom question numbering is not working.

### ISSUE THREAD

**Issue by sem1colon** [surveyjs/survey-library#2292]
I have tried with adding `questionTitleTemplate: '{qnum}. {title}'` and `questionStartIndex: 'A'`, this does work with the older versions. But when I tried this in latest version, it's not working. Checkout this example: https://stackblitz.com/edit/js-emv1eh

**Comment by andrewtelnov** [comment]
@sem1colon Yes, we have changed it. You can now modify  questionStartIndex as ``questionStartIndex: 'A)'`` or ``questionStartIndex: 'A.``. Here is [your updated example](https://stackblitz.com/edit/js-yrqb2t).
Instead of questionTitleTemplate, we have "questionTitlePattern" property. Here is [the example](https://surveyjs.io/Examples/Library?id=survey-processtext).

Thank you,
Andrew

**Comment by sem1colon** [comment]
Okay, but how can I have custom numbering? How to set a number property from question object?

**Comment by andrewtelnov** [comment]
@sem1colon Yes, you can. questionStartIndex is doing this. You can have:
``questionStartIndex: '#A.'`` or ``questionStartIndex: '(1)'``.

Thank you,
Andrew

**Comment by sem1colon** [comment]
I want to have custom numbering by making use of a property `num` in question object. I tried setting up with `questionTitlePattern`. But it didn't work. why?

**Comment by andrewtelnov** [comment]
@sem1colon Unless you do not show what do you want to achieve, we can't help you. You are saying that you can't do something, what exactly, please provide the example.

Thank you,
Andrew

**Comment by sem1colon** [comment]
Consider this [example](https://stackblitz.com/edit/js-emv1eh), I have `num` property in question object. I wanted to have this `num` to be my question number. Previously, it was possible.

**Comment by andrewtelnov** [comment]
@sem1colon Unfortunately, we do not have this functionality now. Your questionStartIndex should be "1a", unfortunately, survey library will increase numbers and not letters, so the questions will be: "1a", "2a", "3a", ...
What is the big picture? Do all your questions start from "1a" and then "1b", "1c", ..., what is the logic in numbering?
You can turn off the automatic numbering: ``survey.showQuestionNumbers = "off"`` and use survey.onGetQuestionTitle event:
```js
survey.onGetQuestionTitle.add(function(sender, options) {
  options.title = options.question.num + " " + options.title;
});
```
Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@sem1colon Unfortunately, ``survey.onGetQuestionTitle`` event doesn't work correctly. I have fixed it and updated the unit test. Here is [the related issue](https://github.com/surveyjs/survey-library/issues/2298).
We will include the fix into the next update on the next week.

Thank you,
Andrew

**Comment by sem1colon** [comment]
Thanks for the update. But, why have you stopped supporting `questionTitleTemplate`?
It'd be great if you add support for custom numbering from a property instead of just incrementing.

**Comment by andrewtelnov** [comment]
@sem1colon We made it obsolete. In early versions we have one string that contains: question number, title and requried text. It works perfectly for most developers, but not for designers. They wanted to have red asterics for requried questions and a number inside a fancy cycles.
As result we decided to have three different strings inside spans with different styles: number, title and requried text. A Survey Creator user can change the position of requried text: in the beginning, after number, at the end (default) and it is enought.
``questionStartIndex`` became smarter and you can set not only "1" or  "12", "a" or "C", but also "(C)" or "#1.".
And on onGetQuestionTitle you can do what ever you want if you turn-off question numbering.

Thank you,
Andrew
