### ISSUE TITLE
IsRequired Cells in the matrixdynamic does not auto show asterisk 

### ISSUE THREAD

**Issue by mark-wilkinson** [surveyjs/survey-library#2297]
Hello All,

I've noticed since upgrading to the latest version of SurveyJs that the asterisk no longer shows for any cells that include the isRequired property within the matrixdynamic. The error messages still show but no asterisk. Is there a reason behind this? Can someone point me in the right direction.

Cheers,
Mark

**Comment by andrewtelnov** [comment]
@mark-wilkinson We will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@mark-wilkinson I have fixed the issue. Unfortunately, we will include the fix into v1.7.25 that we will release on the next week and not into today release v1.7.24.

Thank you,
Andrew
