### ISSUE TITLE
About the hasComment attribute

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/survey-library#2299]
Hello, I would like to ask about the hasComment attribute for the text type, but it doesn't seem to work? 
such as ： https://plnkr.co/edit/SZWI0uaTOmiTQSIK

In addition, I want to confirm that all types of questions support the hasComment attribute?

**Comment by andrewtelnov** [comment]
@fengzhihenxs We will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@fengzhihenxs We have the following questions that support comments:
Radiogroup, checkbox, dropdown, image picker, rating and file.
hasComment attribute is hidden for text type and you can't set it in the Survey Creator. It is not serialized into/from JSON for text type as well.

Thank you,
Andrew
