### ISSUE TITLE
always get Latest Vesion 

### ISSUE THREAD

**Issue by ironman1964** [surveyjs/survey-library#2305]
Is there a way to always get the latest version of the JS files ?
Now I need to check the website to see if there is a new version and change the code.

**Comment by dmitrykurmanov** [comment]
you can use npm for example:

```npm i survey-react``` and then changed the version of survey-react to `latest` in package.json

or you can use some cdn based on npm for example unpkg.com:

https://unpkg.com/survey-react/survey.react.js - this link also returns the latest version

**Comment by ironman1964** [comment]
Cool works perfect 

https://unpkg.com/survey-jquery/survey.ko.js
https://unpkg.com/survey-jquery/survey-creator.js
https://unpkg.com/survey-jquery/survey-creator.css

etc :-)
