### ISSUE TITLE
Can we add textUpdateMode to other value in for dropdown questions

### ISSUE THREAD

**Issue by ssbdel97** [surveyjs/survey-library#2310]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question/Requesting a feature.

### What is the current behavior?
Add textUpdateMode to "other" value in dropdown questions.

### What is the expected behavior?
Can we please add textUpdateMode to other value in for dropdown questions

### How would you reproduce the current behavior (if this is a bug)?
I tried this, https://plnkr.co/edit/0F73cRc8zGMYa2Aw, but it is not working.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@ssbdel97 From the next minor version, comments and others will respect ``survey.textUpdateMode`` property.

Thank you,
Andrew
