### ISSUE TITLE
Render TextArea as Div in readonly (was issue #2192)

### ISSUE THREAD

**Issue by ironman1964** [surveyjs/survey-library#2318]
Since issue 2192 is closed I add new one.
It is not rendering a DIV from TextArea in readonly mode, it creates a readonly textarea.

I need this to work since generating a PDF with textarea's does not give me the full textarea. It shows scrollbars in my PDF.
I tried to work with a bit of JQuery but unfortunately all PDF writes use QTWebkit and that can't handle jQuery.
So please please make the 2192 to work !

jsPDF and your exportPDF is not an option, because it needs to be done serverside.

In my code I have:
survey.mode = 'display'; // view only
survey.isSinglePage = true; // one page for export to PDF !
survey.readOnlyCommentRenderMode = "div";

![89022235-fa9a0200-d321-11ea-9305-6fe9194b6198](https://user-images.githubusercontent.com/688083/89708166-05354680-d975-11ea-878c-9e8679bb17ad.png)

**Comment by andrewtelnov** [comment]
@ironman1964 Yes, we make it optional, since some developers wants readonly textarea. It is better for copying text from it. Please call the following code: ``Survey.settings.readOnlyCommentRenderMode = "div"``

Thank you,
Andrew
