### ISSUE TITLE
react: onValueChanging callbacks are called twice after selecting an option in dropdown

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#2321]
### Are you requesting a feature, reporting a bug or asking a question?
question/bug

### What is the current behavior?
In my adoption of surveyJS engine I heavily use onValueChanging event but I don't understand why attached callbacks are called twice after selecting an option

### What is the expected behavior?

callbacks should be called once

### How would you reproduce the current behavior (if this is a bug)?

see console 
https://plnkr.co/edit/81ZISxzNBgls32Ro

* surveyjs platform: react

**Comment by andrewtelnov** [comment]
@masciugo I have fixed the issue.

Thank you,
Andrew
