### ISSUE TITLE
cascade choicesByUrl dropdowns and data

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#2322]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

When I use cascade choicesByUrl dropdowns I noticed a strange behaviors in case of empty response of the second dropdown:

when I select _empty array response_ the **bar** question value does not seems to get updated. It actually gets updated as I can see at submission time but onChangingValue event is not triggered when it changes in the UI. How can I have **bar** value cleared as soon as possible and the onChangingValue event triggered?

thank you
https://plnkr.co/edit/E5QvH1iC01Vw2Nsz

**Comment by masciugo** [comment]
clearIncorrectValues?

**Comment by masciugo** [comment]
By studying clearIncorrectValues function docs it seems that not to clear values automatically in cases like this is expected. However I think that like clearInvisibileValues it should be up to the user choosing whether to keep data you see in UI sync with survey.data or not. Something like `clearIncorrectValues: onHidden` would do.

For the moment I am using this hack to reach my aim:

`question.registerFunctionOnPropertyValueChanged("visibleChoices", () => question.clearIncorrectValues())`

It seems to work but I wonder: is it safe enough?

thank you

**Comment by dmitrykurmanov** [comment]
fixed via the https://github.com/surveyjs/survey-library/issues/2327
