### ISSUE TITLE
None of your Print to PDF example are working

### ISSUE THREAD

**Issue by jbrou015** [surveyjs/survey-library#2325]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?

In you documentation, none of your examples are working.

Try: 

- https://surveyjs.io/Examples/Pdf-Export?id=survey-pdf-saveoptions&platform=Vue&theme=modern#content-result
- https://surveyjs.io/Examples/Pdf-Export?id=survey-pdf-export&platform=Vue&theme=modern

On load we have:
Uncaught TypeError: Cannot read property 'API' of undefined

Then...
ReferenceError: SurveyPDF is not defined

### What is the expected behavior?
Examples are working

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome, edge
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): Vue, jQuery
* surveyjs version:

**Comment by adolfopeccin** [comment]
Most probably its the changes in jsPDF

**Comment by jbrou015** [comment]
Anything I can do to make it work at my end?

**Comment by adolfopeccin** [comment]
You can use the https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js old version before 2.x version released today by jsPDF. It's working.

**Comment by dmitrykurmanov** [comment]
We've updated our site and fixed the problem.

**Comment by jbrou015** [comment]
Your examples are working fine now thank you.

Using jsPDF 1.5.3 is causing those exceptions below in my code. It's coming from jsPDF. Any idea why?

jsPDF PubSub Error this.addFileToVFS is not a function TypeError: this.addFileToVFS is not a function
    at Object.callAddFont (doc_controller.ts:146)
    at PubSub.publish (jspdf.js:78)
    at addFonts (jspdf.js:1028)
    at new jsPDF (jspdf.js:3352)
    at new DocController (doc_controller.ts:131)
    at SurveyPDF.<anonymous> (survey.ts:142)
    at step (helpers.ts:90)
    at Object.next (helpers.ts:71)
    at helpers.ts:64
    at new Promise (<anonymous>)

And...
Uncaught (in promise) TypeError: controller.doc.splitTextToSize is not a function
    at Function.SurveyHelper.createPlainTextFlat (helper_survey.ts:175)
    at Function.<anonymous> (helper_survey.ts:191)
    at step (helpers.ts:90)
    at Object.next (helpers.ts:71)
    at helpers.ts:64
    at new Promise (<anonymous>)
    at Object.__awaiter (helpers.ts:60)
    at Function.SurveyHelper.createTextFlat (helper_survey.ts:189)
    at Function.<anonymous> (helper_survey.ts:354)
    at step (helpers.ts:90)

**Comment by jbrou015** [comment]
I have fixed this one: jsPDF PubSub Error this.addFileToVFS is not a function TypeError: this.addFileToVFS is not a function by adding
```
fontName: 'times',
fontStyle: 'normal',
```
to my options.

However, this one: Uncaught (in promise) TypeError: controller.doc.splitTextToSize is not a function I can't figure out. Anything could help.

Thanks
