### ISSUE TITLE
onValueChanging and onValueChanged behaves differently in cascade dropdowns scenario

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#2327]
### Are you requesting a feature, reporting a bug or asking a question?

question/bug

### What is the current behavior?

when using cascade dropdowns when changing the first one (region in the plunker) onValueChanging and onValueChanged callbacks are regularly called for that question but they are not for the second one (country). Specifically two incoherent things happened:

- onValueChanging show undefined oldValue
- onValueChanged is not even called 

### What is the expected behavior?

I track changes monitoring through onValueChang(ed/ing) callbacks and I would expect the same behavior for question that are not directly changed by the user

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/R5qx6igbm8uBpYeg?preview

**Comment by masciugo** [comment]
the second point (onValueChanged is not even called) is maybe expected. See https://github.com/surveyjs/survey-library/issues/2322

**Comment by andrewtelnov** [comment]
@masciugo Here is [the correct example](https://plnkr.co/edit/5NzJjt7GqFVVdSkA), your example is empty.
Indeed. Here is what happens: the dropdown list becomes empty, as result value becomes incorrect and it sets to undefine.
For some reason we do not fire notification at this moment. We will investigate it. Later, we are setting value to null and it calls onValueChaning event, since null is not underfined in this code (question level). However, the value is not changed and onValueChanged is not called, since survey model decides that underfined and null are the same and returns from setValue function without setting anything.
So the problem that we do not fire events on settings value to underfined on clearing choices.

Thank you,
Andrew

**Comment by masciugo** [comment]
my example plunk is now corrected. thank you

**Comment by andrewtelnov** [comment]
@masciugo I have fixed the issue.

Thank you,
Andrew

**Comment by masciugo** [comment]
thank you @andrewtelnov. Does the fix will affect #2322? 

> Here is what happens: the dropdown list becomes empty, as result value becomes incorrect and it sets to undefine.

I mean, if a dropdown question options list becomes empty, is its value always set to undefined? From docs about clearIncorrectValues I read:

> Call this function to remove values from the current question, that end-user will not be able to enter. For example the value that doesn't exists in a radigroup/dropdown/checkbox choices or matrix rows/columns. 

So it seems that resetting values must be done manually and not a natural consequence of the new emptiness state of the list

**Comment by andrewtelnov** [comment]
@masciugo I do not change the value to undefined if choices becomes empty and ``clearInvisibleValues`` is about visible/invisible questions. You can set ``hideIfChoicesEmpty`` to true for the second question and it will make the question invisible if choices become empty and if ``clearInvisibleValues`` is "onHidden", then it will clear the second question value.

Thank you,
Andrew

**Comment by masciugo** [comment]
ok. I slightly changed my plunk adding a further level of dependency (which is actually my use case)

https://plnkr.co/edit/Y0uGYmc1k8XcWPBk?preview 

If you change the region _foo_ question does not get clear. But if you change the region a second it will. Does the fix will solve this case too? 

Sorry, I would try myself if I were able to setup quickly a dev env :(  
thank you

**Comment by masciugo** [comment]
> Sorry, I would try myself if I were able to setup quickly a dev env

WRONG. It was super easy following the readme instructions and the fix solve the use case too. I'll run a last check after next release

thanks

**Comment by andrewtelnov** [comment]
@masciugo Great!

Thank you,
Andrew
