### ISSUE TITLE
1.7.26 incorrectly executes logic

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#2331]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

Note that this bug breaks surveys that are running, so this is a big issue.

### What is the current behavior?

Logic seems to be executed differently in .26 vs .25, see the attached screen recording.
This is the JSON used.

```
{
 "pages": [
  {
   "name": "page",
   "elements": [
    {
     "type": "multipletext",
     "name": "V007",
     "title": "Question 1",
     "items": [
      {
       "name": "1",
       "title": "Answer 1"
      },
      {
       "name": "2",
       "title": "Answer 2"
      },
      {
       "name": "3",
       "title": "Answer 3"
      }
     ]
    },
    {
     "type": "html",
     "name": "question1",
     "html": "This should show the 3 answers\n<br/>\n{V007.1}<br/>\n{V007.2}<br/>\n{V007.3}<br/>"
    },
    {
     "type": "matrix",
     "name": "V008",
     "title": "This should show a row for each of the given answers",
     "columns": [
      {
       "value": "1",
       "text": "Positief"
      },
      {
       "value": "2",
       "text": "Neutraal"
      },
      {
       "value": "3",
       "text": "Negatief"
      }
     ],
     "rows": [
      {
       "value": "1",
       "text": "{V007.1}",
       "visibleIf": "{V007.1} notempty"
      },
      {
       "value": "2",
       "text": "{V007.2}",
       "visibleIf": "{V007.2} notempty"
      },
      {
       "value": "3",
       "text": "{V007.3}",
       "visibleIf": "{V007.3} notempty"
      }
     ],
     "hideIfRowsEmpty": true
    }
   ]
  }
 ]
}
```
Will attach a video in a sec

**Comment by SamMousa** [comment]
https://sammousa.stackstorage.com/s/L6xUOS65fhWFgLCe

**Comment by SamMousa** [comment]
I think it has to do with some expression evaluation short circuiting that is failing. (https://github.com/surveyjs/survey-library/commit/b5f6143c684f662d44778f2e1921935d49b3ea5a)


Some strange stuff:
![image](https://user-images.githubusercontent.com/547021/90236483-1b368180-de23-11ea-9cec-7d976147e569.png)

I run these commands with about 1 second in between, but in the meantime I have no interaction with the page. So there is something breaking the expression evaluation. This can cause all kind of weird behavior when used in routing

**Comment by andrewtelnov** [comment]
@SamMousa Yes, I made the set of optimization several days ago. I was afraid that I could break something, but hoped on our unit tests, we have them a lot, but unfortunately, still not enough. I will work on the issue.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@SamMousa Indeed the issue was with incorrect getting value from cached path. I have fixed it, by adding one more unit test.

Thank you,
Andrew
