### ISSUE TITLE
Incorrect detection of the requiredInAllRowsError in matrix question

### ISSUE THREAD

**Issue by Kesantielu** [surveyjs/survey-library#2332]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

Incorrect detection of the `requiredInAllRowsError` error in QuestionMatrix when the value of any of the columns is 0 and the `isAllRowRequired` flag is set in the **Vue** version of SurveyJS. If you select a matrix item with a value of 0, then the `requiredInAllRowsError` will appear when the poll ends, as if this item was not selected at all. This behavior is only present in the **Vue** version of SurveyJS, in the others (jQuery, React, Knockout, Angular) everything works as expected.

### How would you reproduce the current behavior (if this is a bug)?

Use Vue version of SurveyJS library and this config:

```json
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "matrix",
     "name": "question",
     "title": "What's up?",
     "isRequired": true,
     "columns": [
      {
       "value": 0,
       "text": "No"
      },
      {
       "value": 1,
       "text": "Maybe"
      },
      {
       "value": 2,
       "text": "Yes"
      }
     ],
     "rows": [
      {
       "value": 1,
       "text": "Question 1"
      },
      {
       "value": 2,
       "text": "Question 2"
      },
      {
       "value": 3,
       "text": "Question 3"
      }
     ],
     "isAllRowRequired": true
    }
   ]
  }
 ]
}
```
Choose any answer options, at least one option "No" and complete the survey.

**Comment by andrewtelnov** [comment]
@Kesantielu I have added a new unit test and fixed it. The issue was in the survey model (platform independent part) and not in the vue version only.
