### ISSUE TITLE
Other option customization

### ISSUE THREAD

**Issue by wrussell96** [surveyjs/survey-library#2333]
Currently in my survey the other option on radio and checkbox questions is always at the bottom and when selected the text is always required.

Is there a way I can set the other text to be optional and set the position of the other option?

* surveyjs platform: react
* surveyjs version: 1.7.17

**Comment by andrewtelnov** [comment]
@wrussell96 Our current implementation is the standard one. You can do not use our implementation and add "other" value as a standard choice value and have the next "comment" question without numbering (``question.hideNumber = true;``) and with visibleIf expression that shows the question when the "other" value is choosen.

Thank you,
Andrew
