### ISSUE TITLE
Css Bug in React.js PanelDynamic Add new Button

### ISSUE THREAD

**Issue by marcziss** [surveyjs/survey-library#2336]
My user was complaining that clicking add new on a dynamic panel was having no effect

What I found was everything seems ok on the first add. Every add after the first, the button gives a problem unless you click the button on the very bottom edge. 
Anywhere else and the user gets the arrow cursor instead of the hand and they can't click.
 
sorry to register this small bug for that is probably a simple fix for a css person, but I couldn't figure out what was causing it. (not being a css person) 

example distilled down
https://plnkr.co/edit/o2vInwNbg4PuOdTp?preview

recreate by trying to click on add new twice and having button receive focus

Seeing the issue on both edge and chrome

**Happens in React.js; however same issue does NOT happen in JQuery**

https://plnkr.co/edit/37AkVqqAJ88zLdgI

**Comment by tsv2013** [comment]
It's a bug indeed. We'll work on the fix

**Comment by marcziss** [comment]
Thanks! I
