### ISSUE TITLE
ImagePicker not working on React after v1.7.24/survey.react.js

### ISSUE THREAD

**Issue by thiagotigaz** [surveyjs/survey-library#2338]
When using imagepicker and surveyjs react components it's not possible to pick the first image available.

![Screen Shot 2020-08-21 at 11 21 06 AM](https://user-images.githubusercontent.com/4993320/90922757-5c89dc80-e3a1-11ea-88b6-71724e525ee2.png)
![Screen Shot 2020-08-21 at 11 20 34 AM](https://user-images.githubusercontent.com/4993320/90922765-601d6380-e3a1-11ea-9dd0-f0a4fee36bcd.png)

### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
It's not possible to select the first image on imagepicker when using any version after 1.7.24

### What is the expected behavior?
We should be able to pick any image

### How would you reproduce the current behavior (if this is a bug)?
Your website is broken, go there to imagepicker, change to react and try picking up the first one. The same problem happens if run locally.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://surveyjs.io/Examples/Library?id=questiontype-imagepicker&platform=Reactjs&theme=bootstrap

### Specify your

* browser: chrome on osx
* browser version: 84.0.4147.105 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.7.25, 1.7.26 and 1.7.27

**Comment by tsv2013** [comment]
I've fixed the issue. Fix will be available in v1.7.28.

**Comment by thiagotigaz** [comment]
Thanks @tsv2013, appreciated! 👍
