### ISSUE TITLE
Conditional default value of a question

### ISSUE THREAD

**Issue by bappajubcse05** [surveyjs/survey-library#2343]
Want to set default value of a question based on some conditions.

Example: The survey is having two questions (Q1 - dropdown and Q2 - test box).
* set default value of Q2 to 100 when Q1's value is 1
* set default value of Q2 to 200 when Q1's value is 2
* set default value of Q2 to 0 when Q1's value > 2

**Comment by andrewtelnov** [comment]
@bappajubcse05 If you are using the default value only, then you should have only one predefined set of default values. If default value of Q1 is 1, then you should set default value of Q2 to 100.
Others you can do in the code or by using expression trigger, that will set the value of a question based on expression.
In other words, I do not see the real user case here and introducing this functionality would make the default Value feature overcomplicated, IMHO.

Thank you,
Andrew
