### ISSUE TITLE
Completion trigger does not work

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/survey-library#2344]
hi, I found that the completion trigger does not work
https://plnkr.co/edit/?p=preview&preview

**Comment by fengzhihenxs** [comment]
This link：  https://plnkr.co/edit/UThxIOs5zkp0ofPI

**Comment by andrewtelnov** [comment]
@fengzhihenxs By default complete trigger performs on clicking "Next" button. To execute it on value change, please change this setting: ``Survey.settings.executeCompleteTriggerOnValueChanged = true;``
Here is [the forked version of your example](https://plnkr.co/edit/uuKZbZuBOc6lMI5G).

Thank you,
Andrew

**Comment by fengzhihenxs** [comment]
Thank you. I understand
