### ISSUE TITLE
Memory Leak in SurveyJS

### ISSUE THREAD

**Issue by hhendrycks** [surveyjs/survey-library#2348]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug/asking a question

### What is the current behavior?

App crashes every hour or so when coding due to heap memory errors.

### What is the expected behavior?

App does not crash.

### How would you reproduce the current behavior (if this is a bug)?

I use webpack-dev-server --hot to rerender the app (without refreshing the page) when the React code is updated. 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
import React from 'react';
import * as Survey from 'survey-react';
import PropTypes from 'prop-types';
import 'survey-react/survey.css';
import '../funnel.css';

function SurveyQuestions(props) {
  const { questions, handleComplete } = props;
  const defaultThemeColors = Survey
    .StylesManager
    .ThemeColors.default;
  defaultThemeColors['$main-color'] = '#286aa6';
  defaultThemeColors['$main-hover-color'] = '#286aa6';
  Survey
    .StylesManager
    .applyTheme();
  const onAnswerSubmission = ({ data }) => {
    if (data) {
      /**
       * TODO: REPLACE WITH CALL TO BACKEND
       */
      console.log({ ...data });
    }
  };
  return (
    <Survey.Survey
      json={questions}
      showCompletedPage={false}
      onComplete={() => handleComplete()}
      onCurrentPageChanged={onAnswerSubmission}
    />
  );
}
SurveyQuestions.propTypes = {
  questions: PropTypes.object.isRequired,
  handleComplete: PropTypes.func.isRequired,
};

export default SurveyQuestions;

```

### Specify your

* browser: Chrome
* browser version: 84.0.4147.135 (Official Build, 64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.7.26

**Comment by tsv2013** [comment]
You sent us an ordinary SurveyJS initialization script.
Could you provide us with the exact steps to reproduce the issue?

**Comment by hhendrycks** [comment]
If I'm adjusting code in my editor with the survey pulled up in my browser, after enough changes the build will crash (perhaps a few minutes of coding). I was wondering if it was due to the app constantly re-rendering with code changes. These re-renders often do not cause the site to reload, potentially causing the memory consumption to keep increasing.

**Comment by tsv2013** [comment]
@hhendrycks  Can you provide us with a live plunker (or other sandbox) sample illustrating the issue? Or provide us with the exact steps to reproduce the issue in our online demos?

**Comment by hhendrycks** [comment]
Thanks for your speedy response! I will be closing the ticket here and opening it on Survey so my team has more access.
