### ISSUE TITLE
Question type File examples not working in Internet Explorer 11

### ISSUE THREAD

**Issue by jbrou015** [surveyjs/survey-library#2349]
### Are you requesting a feature, reporting a bug or asking a question?
Bug on the demo page

### What is the current behavior?
Examples not working

### What is the expected behavior?
To work

#### Provide the test code and the tested page URL (if applicable)
https://surveyjs.io/Examples/Library?id=questiontype-file&platform=jQuery&theme=modern#content-result
https://surveyjs.io/Examples/Library?id=file-custom-preview&platform=Knockoutjs&theme=modern

```

### Specify your

* browser: IE 11
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by dk981234** [comment]
Hello,

We've fixed examples on the site.

Thanks,
Dmitry
SurveyJS Team
