### ISSUE TITLE
Multiple completedHtml messages/screens

### ISSUE THREAD

**Issue by scottmmack** [surveyjs/survey-library#2350]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question. Can't see anywhere in the documentation how this would be achieved.

### What is the current behavior?
My survey finishes on only the one available message screen.

### What is the expected behavior?
I require multiple messages for question routing output. I see triggers are there but these all go to the same end screen.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@scottmmack Please review [this example](https://surveyjs.io/Examples/Library?id=real-nps&platform=jQuery&theme=modern#content-js). You may want to watch the video on youtube. You can find the link in the example.

Thank you,
Andrew

**Comment by scottmmack** [comment]
Awesome, thanks very much Andrew!
