### ISSUE TITLE
Return to the first page of the survey after completion

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/survey-library#2351]
Hello, I have a requirement to use the completion trigger. When it is triggered, the completion page is reached. The completion page has a return button. Click the button to return to the first page of the survey. I am using Angular, and the click event is not recognized when using completedHtml. Is there any other way to achieve this requirement?

![image](https://user-images.githubusercontent.com/37610470/91515372-9ae04800-e91b-11ea-8ca5-149fde4edfba.png)

**Comment by fengzhihenxs** [comment]
In addition, are the onCompleting and onComplete events not executed when the trigger is executed?

**Comment by andrewtelnov** [comment]
@fengzhihenxs We can remove event handler due security reason. I would suggest you to hide the default complete page ``survey.showCompletedPage = false;`` and show your own div with the html markup you need. You can hide survey div ``onComplete`` event and show your div with the button. On your ``clickAgain()`` you can hide your complete div and show survey div again and do ``survey.clear();`` if you want to start the survey again.

Thank you,
Andrew

**Comment by fengzhihenxs** [comment]
@andrewtelnov  I also considered your method, but the onComplete event is not executed when the completion trigger is triggered. I don't know why?

**Comment by andrewtelnov** [comment]
@fengzhihenxs Could you create an example that shows the issue? It works fine [here](https://surveyjs.io/Examples/Library?id=trigger-complete).

Thank you,
Andrew
