### ISSUE TITLE
Comment values are not displayed when storeOthersAsComment=false

### ISSUE THREAD

**Issue by MrKrabat** [surveyjs/survey-library#2353]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
My goal is to preload data into the survey.
When `storeOthersAsComment` is set to `false` saving and loading of `other` is working as expected.
But the `comment` values are not loaded/displayed anymore.

### What is the expected behavior?
Values of `comment` should be displayed when `storeOthersAsComment` is set to `false`.

### How would you reproduce the current behavior (if this is a bug)?
- Open https://plnkr.co/edit/01lPusQYEIFtxpBb
- The comment of question 2 is empty.
- Set `storeOthersAsComment` to `true` and the comment will be displayed

#### Provide the test code and the tested page URL (if applicable)
Tested page URL: https://plnkr.co/edit/01lPusQYEIFtxpBb

### Specify your

* browser: Chrome
* browser version: 84
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: 1.7.26

**Comment by andrewtelnov** [comment]
@MrKrabat I can confirm that it is a bug. We will work on the fix.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@MrKrabat The bug was in survey model. I have added one more unit test and fixed it.
We will include fix into the next update that we will release in few days.

Thank you,
Andrew
