### ISSUE TITLE
Return null/empty string for undefined variables

### ISSUE THREAD

**Issue by steveops** [surveyjs/survey-library#2355]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question

### What is the current behavior?
When you reference an undefined variable in an html question e.g `<div> Hello {missingVariable}, welcome! </div>`, the expression is not interpolated but rendered as is ie `Hello {missingVariable}, welcome!`

### What is the expected behavior?
A blank/empty string should be rendered instead i.e  `Hello , welcome!`

### How would you reproduce the current behavior (if this is a bug)?
- Add an html question to a survey
- Reference a missing/undefined variable in the body of the question
- When the survey is run, the raw expression with curly braces is displayed

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/p1nmtkrUsspRUaXj

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version: 84
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: 1.7.3

**Comment by andrewtelnov** [comment]
@steveops I would love to leave it as it is. Here is the explanation of my decision.
We do not know if the variable is going to exist or not. If we pretend that variable is exists, it will mean that all {nonExistingVariableOrQuestion} should return empty strings.
In the most cases, Creator users set {questionName} for pre-processing. If they mistype a question name, it will be very hard for them to find an error during testing and understand why it doesn't work, in case we will render an empty string.
For your example, all you need to do, is to define your variable, for example: ``survey.setVariable('undefinedVariable', '');`` and it solve your issue.

Thank you,
Andrew

**Comment by steveops** [comment]
@andrewtelnov Thanks for the quick reply. It makes sense that you want users to notice their mistake easily. My scenario is a little different though. The variable in question is actually set correctly, only that it is an empty object in some instances and with nested properties in other instances. I was looking for a way to only render a property if it exist, and in display mode for that matter, and null/empty string otherwise. I've tried a computed property but the behaviour is the same.
How can I go about this?

**Comment by andrewtelnov** [comment]
@steveops You can handle onProcessTextValue event:
```js
survey.onProcessTextValue.add(function(sender, options){
    options.isExists = true;
    if(options.value == undefined) options.value = "";
});
```
Here is [your updated example](https://plnkr.co/edit/p1nmtkrUsspRUaXj?preview).

Thank you,
Andrew

**Comment by steveops** [comment]
Thats solves my issue. Thanks @andrewtelnov. I'll close this now.
