### ISSUE TITLE
Evaluate calculated value with another calculated value

### ISSUE THREAD

**Issue by benirose** [surveyjs/survey-library#2362]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the current behavior?
Value is not calculating. I have two questions, the second is only asked if the value to the first question meets some criteria. However, in my results, I want a single answer for both questions: the value of the second if they answered it, otherwise the value of the first. This is working. However, I also want another calculated value based on this first calculated value.

### What is the expected behavior?
Value calculates

### How would you reproduce the current behavior (if this is a bug)?
Set up two text questions.
Set up a calculated value called "final_answer" with an expression of `iif({question1}, {question1}, {question2})`
Set up another calculated value called "category" with an expression of `iif({final_answer} > 50, "high", "low")`

### Specify your

* browser: Chrome
* browser version: 85
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: survey-creator@1.1.23

**Comment by andrewtelnov** [comment]
@benirose It works fine to me with the latest version. Here is [the example](https://plnkr.co/edit/2lfkHAet3UxrS1hz).

Thank you,
Andrew

**Comment by benirose** [comment]
Thanks Andrew, it seems to be a version issue. Looks like this didn't work in 1.1.23 but works now in 1.8.x, so we will be updating.
