### ISSUE TITLE
send an array or cursor as a group of choices to radio question

### ISSUE THREAD

**Issue by frankwo1** [surveyjs/survey-library#2367]
Hi Andrew,

### Asking a question
I wanted to see how to push an array into the radio question (selections)
I see this one where we can push individual pieces of text into the choice question but do not see how to push an entire array into the question 
https://github.com/surveyjs/survey-library/issues/1326

### What is the current behavior?
I am using javascript

I have tried
Adding an array into the questons

      var       choices = [
              {value:"0", text: "text1"},
              {value:"1", text: "text2"},
              {value:"2", text: "text3"},
              {value:"3", text: "text4"},
            ];
            console.log(choices);

but it does not seem to insert into my question

      {
       type: "radiogroup",
       choices: [{choices}],
       isRequired: true,
       name: "Type",
       title: "SELECT TYPE OF CALL"
}

Thanks for for your help

**Comment by andrewtelnov** [comment]
@frankwo1 It depends what do you want to do.
If you are using JavaScript then the following code will work:
```js
var myChoices = [1, 2, 3, 4];
var json = {
  elements: [
 {
   type: "radiogroup",
   choices: myChoices,
   isRequired: true,
   name: "Type",
   title: "SELECT TYPE OF CALL"
  }
 ]
};
```
It is a pure JavaScript. SurveyJS has nothing to do with it.
If you want to modify it on the fly when survey is already running then you can use the following code:
``survey.getQuestionByName("Type").choices = myChoices;``

Thank you,
Andrew

**Comment by frankwo1** [comment]
Thanks Andrew, works perfectly!
