### ISSUE TITLE
How to override the "Thank you for completing the survey!" functionality?

### ISSUE THREAD

**Issue by chelsumz007** [surveyjs/survey-library#2369]
I want to override the functionality of "Thank you for completing the survey!"

Instead of showing this message, I want to open another matdialog popup. Can you suggest something?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@chelsumz007 You can use survey.onComplete event:
```js
survey.onComplete.add(function(sender, options) {
 //hide survey div
 //show your popup
});
```

Thank you,
Andrew

**Comment by chelsumz007** [comment]
Thank you so much @andrewtelnov 

Also, quick question.. 

![image](https://user-images.githubusercontent.com/52992133/92462551-3e690c80-f1e8-11ea-93fb-e49513794cfd.png)

How do I center align the radio buttons inside the matrix?

Sorry for the noob questions.. just started using surveyjs.. 

Library is great!!
