### ISSUE TITLE
How to center the radio buttons on the matrix

### ISSUE THREAD

**Issue by chelsumz007** [surveyjs/survey-library#2371]
@andrewtelnov 

How do I center the radio buttons. Screenshot below:

![image](https://user-images.githubusercontent.com/52992133/92475609-4c745880-f1fb-11ea-9b7b-6b77020342df.png)

Currently they are left aligned

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version:

**Comment by dmitrykurmanov** [comment]
Hello! We'll take a look. Thanks.

**Comment by dmitrykurmanov** [comment]
We've implemented the enhancement. It will be available in the next minor release.

**Comment by chelsumz007** [comment]
@dmitrykurmanov when would the next minor release be? I needed to implement this in my project.. 

Thanks again!

**Comment by chelsumz007** [comment]
@dmitrykurmanov Thanks!

for now, have over-ridden some of the settings from your git commit. snippet below:

![image](https://user-images.githubusercontent.com/52992133/92696505-9b3f0100-f367-11ea-87be-3b872555f767.png)
