### ISSUE TITLE
unexpected type casting in expression

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#2372]
### Are you requesting a feature, reporting a bug or asking a question?

bug maybe

### What is the current behavior?

if a string question value _seems_ a number it will be casted to number in expression. 

### What is the expected behavior?

it should remain a string

### How would you reproduce the current behavior (if this is a bug)?

This is a very simplified and artificial example. 

https://plnkr.co/edit/jr0ZwkzP6QpTzG9B

Actually I use very complex custom async expression that use question values tu build a url and it needs to fetch values as they are (string _001_ and not number 1)

**Comment by andrewtelnov** [comment]
@masciugo We are trying to convert string into number in expressions. In the most cases, people needs number here. Could you show your code?
In fact, you can pass a value as string and then get it from your function as:
``this.survey.getValue(yourParameterName)``. In this case you will get the string without convertion into number.

Thank you,
Andrew

**Comment by masciugo** [comment]
In this plunk 

https://plnkr.co/edit/Mqy8ZcATJscOam13opOD?preview

if the postId dropdown returned string ids like "001" the custom function getRemoteObjectProperty used in expression would receive it as number 1 and the built path would be wrong..

**Comment by andrewtelnov** [comment]
@masciugo As a workaround, I would suggest to use the following function:
```js
function getSurveyValue(params) {
  if(params.length != 1) return;
  return this.survey.getValue(params[0]);
}
Survey
    .FunctionFactory
    .Instance
    .register("getSurveyValue", getSurveyValue);
```
Here is the [updated plunker](https://plnkr.co/edit/DArVu3K9boIrEySq?preview).
I will think about something that will tell survey about not converting the value into numbrer.

Thank you,
Andrew

**Comment by masciugo** [comment]
thanks for the solution. I did not know you can use multiple custom functions this way, nested. Good to know. 

But, I am afraid, this solution is too complex for my application users as they manage independently the survey json model to build their own survey and they would not understand/memorize the trick (and they should not). 

Another trick, that I already used in other custom functions is to get question values inside the function providing the name of the function as argument instead of the value:

https://plnkr.co/edit/ulVZDgUexuMVap0D

This is maybe easier to understand for my users: use `'postId'` instead of `{postId}`. 
Honestly I don't like this workaround either as it bypass some other default elaborations and facilities like when the target question is inside a paneldynamic o matrixdynamic (panel.postId or row.postId). 

For example in this custom function I needed to implement a parsing to have it working the same way as default expressions do:

```javascript
// function to retrieve property from object already loaded in other dropdown question (targetQuestion)
// with one of the props:
//
// * choicesByUrl (needs property choicesByUrl.attachOriginalItems = true)
// * choicesByQueryingUrl
//
// usage examples:
// getSelectedChoiceProp('country','capital')
// getSelectedChoiceProp('panel.country','capital')
// getSelectedChoiceProp('row.country','capital')

const getSelectedChoiceProp = function(args) {
  let targetQuestionName = args[0],
    prop = args[1],
    targetQuestion

  if (!targetQuestionName || !prop) { return }

  let targetQuestionNameArray = targetQuestionName.split(".")

  if (targetQuestionNameArray.length > 1) { // the targetQuestion is in the same panel or row
    if (this.row) { // it's inside a matrixdynamic cell
      targetQuestion = this.row.cells.map(c=>c.question).find(e=>e.name == targetQuestionNameArray[1])
    } else { // it's inside a paneldynamic panel
      targetQuestion = this.question.parent.getQuestionByName(targetQuestionNameArray[1])
    }
  } else { // the targetQuestion is at root level
    targetQuestion = this.survey.getQuestionByName(targetQuestionName)
  }

  // check targetQuestion requirements
  if (targetQuestion.getType() != "dropdown") return
  if (!targetQuestion.choicesByUrl && !targetQuestion.choicesByQueryingUrl) return

  if (targetQuestion.value) {
    let selectedItem = targetQuestion.visibleChoices.find(c => targetQuestion.value == c.value)
    if (selectedItem && selectedItem.originalItem) {
      return selectedItem.originalItem[prop]
    } 
  }
  return undefined
}
```
This function interact a lot with internals and any surveyJS upgrade may be fatal. If you see big risks please tell me!

**Comment by andrewtelnov** [comment]
@masciugo  From v1.8.2 you will be able to use ``{#postId}``. It will disable the convertion value to numeric and leave string as it is. Here is [the related GitHub issue](https://github.com/surveyjs/survey-library/issues/2376).

Thank you,
Andrew

**Comment by masciugo** [comment]
Fair enough solution. thank you

**Comment by andrewtelnov** [comment]
You are welcome!

Andrew
