### ISSUE TITLE
progressBarType should only count visible questions

### ISSUE THREAD

**Issue by MrKrabat** [surveyjs/survey-library#2375]
### Are you requesting a feature, reporting a bug or asking a question?
Requesting a feature

### What is the current behavior?
- If `progressBarType=pages` the progress bar is calculated using only visible pages of the survey.
- If `progressBarType=questions` the progress bar is calculated using all questions. If the survey contains invisible questions or the user skipped non-required questions, the progress bar shows 7/9 when the user has actually finished the survey.

### What is the expected behavior?
A new option which only uses visible and required questions to calculate the progress bar should be implemented.
1. Count all visible and required questions
2. Count all visible and non-required questions that were answered
3. Add up these numbers. This is the total amount of questions

**Comment by andrewtelnov** [comment]
@MrKrabat Agreed about visible questions and corrected.
I have added "requiredQuestions" options as well. Here is the [related issue](https://github.com/surveyjs/survey-library/issues/2377).

Thank you,
Andrew
