### ISSUE TITLE
Progressbar text is not updating after giving the answers in dynamic panel in the survey

### ISSUE THREAD

**Issue by binicr** [surveyjs/survey-library#2378]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@binicr We do not count questions in dynamic panels and dynamic/dropdown matrices, as well as multiple text question. I believe we should. We will keep this suggestion in mind and hopefully implement it.

Thank you,
Andrew

**Comment by binicr** [comment]
Thanks Andrewtelnov.
But when can I expect this release?
It is really required for our project.

**Comment by andrewtelnov** [comment]
@binicr I can't give you the exact time frame right now. As a work-around you can use [survey.onProgressText](https://surveyjs.io/Documentation/Library?id=surveymodel#onProgressText) event.

Thank you,
Andrew

**Comment by binicr** [comment]
Yes @andrewtelnov  .For time being ,I am using survey.onProgressText.
But for dynamic panel ,this event is not all getting called while entering the answers in the panel

**Comment by andrewtelnov** [comment]
@binicr It has been implemented in v1.8.3 that we released today. Here is [the related issue](https://github.com/surveyjs/survey-library/issues/2390).

Thank you,
Andrew
