### ISSUE TITLE
Not able to count number of elements inside the dynamic panel

### ISSUE THREAD

**Issue by binicr** [surveyjs/survey-library#2381]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@binicr Here is [the example](https://plnkr.co/edit/yhZ9GNVp6PlruqfR).

Thank you,
Andrew

**Comment by binicr** [comment]
Thanks @andrewtelnov  It worked for me.
It is enough for number of questions.
Is there any way to get values from each questions like this

**Comment by andrewtelnov** [comment]
@binicr Question has read/write property value and boolean function isEmpty() 

Thank you,
Andrew

**Comment by binicr** [comment]
Hi @andrewtelnov  ,
I mean 
let x = this.getQuestionsInSurvey(sender);
  x.forEach(item=>{
  
  })

here in x i will all the questions even inside the dynamic panel.
But how to check values (answers) in each questions

**Comment by andrewtelnov** [comment]
item is a question. ``item.value`` or ``item.isEmpty()``

**Comment by binicr** [comment]
yes..Thanks Very much @andrewtelnov 
SurveyJs is awesome...
It works perfectly
