### ISSUE TITLE
Survey creator add property of type validator

### ISSUE THREAD

**Issue by Dibyanshu** [surveyjs/survey-library#2382]
Hello, my awesome surveyjs team,

need a help/example to add a validators type property with my own choices

So the overall feature I am trying to build is ->
#1 - Loading a definition list from ajax (countries, regions, users, etc master records and it's a custom property of type itemvalues)
#2 - Than once select a definition type, say 'countries' than it will load another custom property of type validators. Which should have values like text, order by, row counts, etc. (**in this one I am stuck and need urgent help**)
#3 - Next if you choose to say 'text' then it will load 3 new text box like the validation text selection is doing now(I think I can do this, once I manage to do the **#2**) 
#4 - This setting will filter the list of definition that will be loading in the survey viewer
(the feature we are trying to build is: load any master record as a dropdown list type question also filter on text/order by/row count on top of that) 

(i am following this documentation : [Add Properties to creator doc](https://surveyjs.io/Documentation/Survey-Creator?id=Survey-Creator-Overview#addproperties))
```
SurveyKo.Serializer.addProperty("selectbase", {
      name: 'definitionFilters:validators',
      default: ' ',
      dependsOn: ["definitions", "choiceType"],
      visibleIf: function (obj) {
        var definitions = !!obj ? obj.definitions : null;
        var choiceType = !!obj ? obj.choiceType : null;
        if (definitions !== 'choose' && choiceType === 0) {
          return true;
        }
        else {
          return false;
        }
      },
      // choices: [
      //   { text: "Choose", value: -1 },
      //   { text: "Text", value: 0 },
      //   { text: "Order", value: 1 },
      //   { text: "Top rows {row number}", value: 2 },
      // ],
      category: "New"
    });
```

![definitionFilteringFeature1.png](https://surveyjs.answerdesk.io/attachment/file/6a0b3ca2-524b-4644-8c36-9af93559240d)![definitionFilteringFeature.png](https://surveyjs.answerdesk.io/attachment/file/f9fb3408-ff66-40c8-8c7c-92e7674f23cd)

https://surveyjs.answerdesk.io/ticket/details/t5164/survey-creator-add-property-of-type-validator

**Comment by andrewtelnov** [comment]
@Dibyanshu I doubt that SurveyJS community could help you here. It is a very specific question and it requires to make changes in the library.

Thank you,
Andrew
