### ISSUE TITLE
Edit buttons in preview mode do not redirect to the correct page/question

### ISSUE THREAD

**Issue by jbrou015** [surveyjs/survey-library#2385]
#1813 # Are you requesting a feature, reporting a bug or asking a question?
Probably a bug

### What is the current behavior?
From the preview page (showPreviewBeforeComplete), if you want to edit a question in a survey that have some pages not visible because of some conditions (visibleIf) then your are not redirected to the correct page/question.

### What is the expected behavior?
Being redirected to the right page when clicking 'Edit' from the preview page

### How would you reproduce the current behavior (if this is a bug)?

1. Using the json below in Survey Creator
2. Answer 'No' on page one. This will make the page 'page_not_visible' not visible.
3. Then continue until the preview. 
4. Click preview. So far all is good.
5. Click the edit button of the question 'Question visible' to edit your answer.
6. Problem -> your are not redirected to the right page because page name 'page_not_visible' is not visible.

#### Provide the test code and the tested page URL (if applicable)

Test code

```
{
 "pages": [
  {
   "name": "page_one",
   "elements": [
    {
     "type": "boolean",
     "name": "mybool",
     "title": "Answer this question",
     "isRequired": true
    }
   ],
   "title": "First page"
  },
  {
   "name": "page_not_visible",
   "elements": [
    {
     "type": "text",
     "name": "not_visible",
     "title": "Question NOT visible",
     "isRequired": true
    }
   ],
   "visibleIf": "{mybool}  = true",
   "title": "This page should not be visible"
  },
  {
   "name": "page_visible_always",
   "elements": [
    {
     "type": "text",
     "name": "q_visible",
     "title": "Question visible",
     "isRequired": true
    }
   ],
   "title": "This page should always be visible"
  },
  {
   "name": "page_template",
   "elements": [
    {
     "type": "html",
     "name": "start_info",
     "html": "<p>the end</p>"
    }
   ]
  }
 ],
 "showProgressBar": "bottom",
 "showPreviewBeforeComplete": "showAllQuestions"
}

```

### Specify your

* browser: any
* browser version: any
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: 1.7.28

**Comment by andrewtelnov** [comment]
@jbrou015 We have fixed the issue.

Thank you,
Andrew
