### ISSUE TITLE
onLoadChoicesFromServer event is fired ad-infinitum

### ISSUE THREAD

**Issue by Tri125** [surveyjs/survey-library#2388]
### Are you requesting a feature, reporting a bug or asking a question?

Bug Report

### What is the current behavior?

onLoadChoicesFromServer event is fired ad-infinitum when SurveyModel.data is modified in an event handler, the choicesByUrl url is constructed from the value of another question, and a third question unrelated to those two are modified.

### What is the expected behavior?

``onLoadChoicesFromServer `` should only be fired when the choices are loaded from the server and not when unrelated questions are modified.

### How would you reproduce the current behavior (if this is a bug)?

Minimal repro case: 

https://stackblitz.com/edit/surveyjs-bug-5zdops?file=app/surveyjs.component.ts

There are 4 requirements to reproduce: 

1. Add an event handler to `onLoadChoicesFromServer`
2. The handler must change the SurveyModel.data
3. The dropdown question must use choicesByUrl with a url that is templated from another question. In the repro case, it use the value of another dropdown: `https://pokeapi.co/api/v2/pokemon?limit={q_limit}` where question q_limit define a few numeric values.
4. A question other than these two must be modified and lose focus to trigger a modification. If you modified 'Limit' it won't happen, just reload the tab and only modify the text field in the repro case.

In the repro case, open the project in a new tab (I highly recommend that because otherwise the editor will become unresponsive) and open the console of your browser. Then, write a value in the question "Text field" and click outside the window.

You will see hundred of console logs from the ``onLoadChoicesFromServer`` call. The browser will eventually detect it and terminate the loop but in the case of our more complex application this never stop and create a few important issues.

### Specify your

* browser: Chrome/Firefox
* browser version: Latest
* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version: 1.8.1

**Comment by andrewtelnov** [comment]
@Tri125 I have tried your examples. The `onLoadChoicesFromServer` event was called on changing the "q_limit" question. That is absolutely correctly. After the values cached, all variants of "q_limit" were used, survey stopped calling the event. 
I can see there is an issue when we are setting the "q_limit" to undefined. I will take a look.

Thank you,
Andrew

**Comment by TristanApc** [comment]
Hi @andrewtelnov . Yeah "q_limit" behavior is fine. However, open the example and do not touch the value of "q_limit". Set a value for "Text Field" and click outside of the input. You should see the ``onLoadChoicesFromServer`` event being called non-stop.

If you open the example and change "q_limit" you will no longer be able to reproduce the problem.

**Comment by TristanApc** [comment]
Here's a few gif that should help you understand:

![image](https://user-images.githubusercontent.com/45565804/93090039-3129a300-f66a-11ea-8598-80274f6c3249.png)


https://i.imgur.com/XqjdcN8.gif
![image](https://user-images.githubusercontent.com/45565804/93090072-3c7cce80-f66a-11ea-8013-39825d367e30.png)

**Comment by andrewtelnov** [comment]
@Tri125 I have fixed the issue by the commit above.

Thank you,
Andrew
