### ISSUE TITLE
Matrix Output Data Conversion

### ISSUE THREAD

**Issue by chelsumz007** [surveyjs/survey-library#2391]
Hi,

I need to convert the output of matrix question result to array of objects. is there any such functionality?

Current format:

{I think that I would like to use this system frequently: "Strongly Disagree", I found the system unnecessarily complex: "Strongly Disagree", I though the system was easy to use: "Strongly Disagree", I think I would need the support of a technical person to be able to use this system: "Strongly Disagree", I found the various functions in this system were well integrated: "Strongly Disagree", …}

Required format:
[{"I think that I would like to use this system frequently":"Strongly Disagree"} ,{"I think that I would like to use this system frequently":"Disagree"}, ....... ]

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version:

**Comment by tsv2013** [comment]
There is no such built-in results conversion functionality in SurveyJS Library. You can do it via your custom code in the https://surveyjs.io/Documentation/Library?id=surveymodel#onComplete event handler. Note, that if you want to assign initial data to the question, you need do pass them in the SurveyJS Libary original format.

**Comment by chelsumz007** [comment]
thanks @tsv2013 for quick reply! closing this! :)
