### ISSUE TITLE
Signature pad: duplicate property

### ISSUE THREAD

**Issue by MrKrabat** [surveyjs/survey-library#2396]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Signature pad does have a [property width](https://github.com/surveyjs/survey-library/blob/master/src/question_signaturepad.ts#L196) which overwrites the default [width property](https://github.com/surveyjs/survey-library/blob/master/src/question.ts#L1644) that all questions have.
The values of the two width properties are not compatible. You cannot set the question width of a signature pad, only the width of the canvas.

### What is the expected behavior?
Be able to set the question width of a signature pad.
The signature pad width property should be renamed to inputWidth, drawingAreaWidth or something like this.
Maybe check other question types for duplicate properties too?

### How would you reproduce the current behavior (if this is a bug)?
Just play with the width value of the signature pad in the surveyjs creator.

### Specify your

* browser: Chrome
* browser version: 85
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: 1.8.2

**Comment by tsv2013** [comment]
I know about this inconsistency. But our customers already using the width and height properties to set signature pad canvas size. To be honest I don't want to disappoint them. And you are the first who tell us about the issue over all period of signature pad question existence. I'll think what we could do here.
