### ISSUE TITLE
Highlight unanswered rows in matrix question

### ISSUE THREAD

**Issue by chelsumz007** [surveyjs/survey-library#2402]
Is there a way to highlight unanswered questions in type matrix?

isAllRowRequired just gives an error message but no highlight

**Comment by chelsumz007** [comment]
@andrewtelnov any update on this? thanks!!

**Comment by andrewtelnov** [comment]
@chelsumz007 There is no workaround here. We should implement it on our side.

Thank you,
Andrew

**Comment by chelsumz007** [comment]
@andrewtelnov any idea when would this feature be available?

**Comment by andrewtelnov** [comment]
@chelsumz007 I am working on it right now.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@chelsumz007 It has been implemented.

**Comment by chelsumz007** [comment]
@andrewtelnov how do I implement in my project? just update the package? I'm sorry, new here!

**Comment by andrewtelnov** [comment]
@chelsumz007 You can wait till we relese [v1.8.4](https://surveyjs.io/WhatsNew#v1.8.4) or build library from sources as describe in readme file (located in the root of this repository).

Thank you,
Andrew

**Comment by chelsumz007** [comment]
@andrewtelnov il probably wait! Thanks for the feature :)
