### ISSUE TITLE
Age function in expression is evaluating to true if the date provided is of future

### ISSUE THREAD

**Issue by yarumair** [surveyjs/survey-library#2410]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
If date is provided for the future, the age function in expression is still returning true

### What is the expected behavior?
Age should only be calculated till current date

### How would you reproduce the current behavior (if this is a bug)?
```
{
            "name": "page3",
            "elements": [
                {
                    "type": "text",
                    "inputType": "date",
                    "inputMask": "datetime",
                    "inputFormat": "dd/mm/yyyy",
                    "name": "QBday",
                    "startWithNewLine": false,
                    "title": "What is your birthday?",
                    //"dateFormat": "dd/mm/yy",
                    "isRequired": true,
                    "validators": [
                        {
                         "type": "expression",
                         "text": "You should be atleast 10 years or older",
                         "expression": "age({QBday}) >= 10"
                        }
                       ],
                       "max": "31/12/2999"
                }
            ]
        }
```
and then enter date for the future for example 20/10/2035, the expression will evaluate as true

### Specify your

* browser: Chrome
* browser version:Version 85.0.4183.102 
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version:1.8.3

Check the below screenshot depicting the exact issue in the source code in function age. Check the WATCH panel for the evaluated return statement. A simple if check for negative value will do a fix

![image](https://user-images.githubusercontent.com/41047316/93718806-d925fb80-fb97-11ea-9984-cd3832d4d46f.png)

**Comment by andrewtelnov** [comment]
@yarumair It works for me. Here is [the example](https://plnkr.co/edit/wCz37iIFG3FGEFmR). I have tried your date, December 3, 1954.

Thank you,
Andrew

**Comment by yarumair** [comment]
@andrewtelnov Try with 20th Oct 2035, i.e. a future date, you will notice the issue. The expected behavior is that validation should trigger as this future date means age is zero "0".

**Comment by andrewtelnov** [comment]
@andrewtelnov I will add a test for future date, but your date should work.
Here is the discussion and original code on [stackoverflow](https://stackoverflow.com/questions/4060004/calculate-age-given-the-birth-date-in-the-format-yyyymmdd).

Thank you,
Andrew

**Comment by yarumair** [comment]
Yes saw that. This code is assuming the birthdate will always be in past, whereas in our case user can enter birthdate of the future, in which case there should be an if condition which checks if the value calculated in below statement:

`var ageDate = new Date(ageDifMs);`

Something like

```
if(ageDate < 0)
return 0
```

**Comment by tsv2013** [comment]
@yarumair You can't compare date and an integer (0). You can compare two dates only.

**Comment by yarumair** [comment]
Sorry about that, this what i meant:

```
var ageDifMs = Date.now() - birthday.getTime();
if (ageDifMs < 0)
return 0;
```

**Comment by andrewtelnov** [comment]
@yarumair I have fix it by the commit above and added a unit test. It will return negative value for date in the future.

Thank you,
Andrew
