### ISSUE TITLE
Introduce question.defaultValueExpression and text question.min/maxValueExpression properties

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#2416]
Current we require to use "=" in properties defaultValue and min/max to tell SurveyJS that we are entering the expression.
For example: `defaultValue: "=today(-1)"`, it will set the value by default to yesterday.
Unfortunately, it is hard to create a decent UI for this type of property type, when it can be date or number or expression.
We decided to introduce new properties that will come into Logic category. defaultValueExpression and minValueExpression/maxValueExpression where user can enter the expression in expression property editor.

Old JSON will continue to work, but on loading from JSON other properties will be used. For example `defaultValue: "=today(-1)"` will be converted into `defaultValueExpression: "today(-1)"`.

**Comment by swuecho** [comment]
Does defaultValueExpression support var like '{Q1}', for example defaultValueExpression: 'iif({Q1} < 15, "low", "hight") ?

**Comment by andrewtelnov** [comment]
@swuecho If Q1 question has default value then it will work.

Thank you,
Andrew

**Comment by swuecho** [comment]
verified, Thanks!
