### ISSUE TITLE
I need to validate at panel level

### ISSUE THREAD

**Issue by pchandra2000** [surveyjs/survey-library#2419]
I have a panel with 3 inputs. 

I would like to throw an error if the user does not populate any of the 3 but I cannot seem to do this, I tried putting a validator block at the panel level but it does not work. Not sure how to accomplish this...

{
   "type":"panel",
   "name":"personalStatusInCanadaInformation",
   "elements":[
      {
         "type":"text",
         "name":"socialInsuranceNumber",
         "title":"Social Insurance Number",
         "inputMask":"phone",
         "inputFormat":"###-###-###"
      },
      {
         "type":"text",
         "name":"healthCardNumber",
         "title":"Health Card Number",
         "inputMask":"phone",
         "inputFormat":"####-###-###"
      },
      {
         "type":"text",
         "name":"immigrationFileNumber",
         "title":"Immigration File Number"
      }
   ],
   "validators":[
      {
         "type":"expression",
         "text":"At least one of these numbers is required.",
         "expression":"{socialInsuranceNumber} empty and {healthCardNumber} empty and {immigrationFileNumber} empty"
      }
   ],
   "visibleIf":"{statusInCanada} notempty",
   "title":"Provide at least one of these numbers:"
},
​

**Comment by andrewtelnov** [comment]
@pchandra2000 Panel doesn't have validators. However it has isRequired and requiredErrorText properties that you can use. Here is [the example](https://plnkr.co/edit/K0nY9PkoqyFeAXLr).

Thank you,
Andrew

**Comment by pchandra2000** [comment]
What an excellent solution Andrew! works perfectly! Thank you so much
for your help.

**Comment by pchandra2000** [comment]
Well I might have been too hasty with that comment, it actually works on the plunker, but does not in my code, in order to ensure that its not overtaken by other setting I copied the code from the plunker and pasted it as is into my JSON and it still does not work! I just cannot figure out why.

{
            type: 'panel',
            name: 'personalStatusInCanadaInformation',
            isRequired: true,
            requiredErrorText: "At least one of these numbers is required.",
            elements: [
                {
                    type: 'text',
                    name: 'socialInsuranceNumber',
                    title: 'Social Insurance Number',
                },
                {
                    type: 'text',
                    name: 'healthCardNumber',
                    title: 'Health Card Number',
                },
                {
                    type: 'text',
                    name: 'immigrationFileNumber',
                    title: 'Immigration File Number',
                },
            ],
            title: 'Provide at least one of these numbers:',
        },
