### ISSUE TITLE
Can not add svg icon in "other(describe)" check box in Markdown Radiogroup

### ISSUE THREAD

**Issue by anaskhanstack** [surveyjs/survey-library#2425]
questions: [
        {
            "type": "radiogroup",
            "hasOther": true,
            "isRequired": true,
            "name": "favoritePet",
            "title": "What is your favorite pet ![A parrot](https://surveyjs.io/Content/Images/examples/markdown/image_16x16.svg =16x16) ?",
            "choices": [
                {
                    "value": "dog",
                    "text": "Dog: ![A dog](https://surveyjs.io/Content/Images/examples/markdown/dog.svg =14x14)"
                }, {
                    "value": "cat",
                    "text": "Cat: ![A cat](https://surveyjs.io/Content/Images/examples/markdown/cat.svg =14x14)"
                }, {
                    "value": "parrot",
                    "text": "Parrot ![A parrot](https://surveyjs.io/Content/Images/examples/markdown/parrot.svg =14x14)"
                }
            ]
        }
    ]

**Comment by andrewtelnov** [comment]
@anaskhanstack You have to set otherText property. Here is [the example](https://plnkr.co/edit/cKKMxLj0wMCkZM4V).

Thank you,
Andrew

**Comment by anaskhanstack** [comment]
Thanks, it is now working perfectly
