### ISSUE TITLE
Vue infinite update loop in SurveyMatrix

### ISSUE THREAD

**Issue by talski** [surveyjs/survey-library#2430]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a BUG

### What is the current behavior?
When using Matrix with Vue, when you choose an answer it becomes unresponsive for a few seconds, depending on how long is the matrix, then in console it throws a error
```
vue.js:634 [Vue warn]: You may have an infinite update loop in a component render function.

found in

---> <SurveyMatrix> at src/vue/matrix.vue
```

#### Provide the test code and the tested page URL (if applicable)
https://plnkr.co/edit/9RhKmqvlkSaoqs2k

### Specify your

* browser: Chrome
* browser version: 85.0.4183.121
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: 1.8.6

**Comment by tsv2013** [comment]
We're working on the fix and will update this thread immediately.

**Comment by tsv2013** [comment]
Fix will be available in the nearest update.
