### ISSUE TITLE
Is it possible to use response from previous question as a part of next question

### ISSUE THREAD

**Issue by kunal-mohta** [surveyjs/survey-library#2434]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

For example:
Q1 (question)
(options) a,b,c,d

Q2 Why did you choose option `{response of Q1}`?

Is it possible to have this template-like behavior questions?

### What is the current behavior?
NA

### What is the expected behavior?
NA

### How would you reproduce the current behavior (if this is a bug)?
NA

#### Provide the test code and the tested page URL (if applicable)
NA

**Comment by andrewtelnov** [comment]
@kunal-mohta Your Q2 title should be  "Why did you choose option {Q1}?"
Here is the [example](https://surveyjs.io/Examples/Library?id=survey-processtext)

Thank you,
Andrew

**Comment by kunal-mohta** [comment]
Thanks for replying @andrewtelnov !
Can we achieve a similar behavior directly using the survey creator?

**Comment by andrewtelnov** [comment]
@kunal-mohta What do you mean? You can set the Q2 title in the Property Grid in the SurveyJS Creator. The code you see in this example could be generated in SurveyJS Creator.

Thank you,
Andrew

**Comment by kunal-mohta** [comment]
Got it @andrewtelnov 
Thanks for your assistance.
