### ISSUE TITLE
Adding Image to questions

### ISSUE THREAD

**Issue by kunal-mohta** [surveyjs/survey-library#2437]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

Is it possible to add image (or other multimedia) to the question content of some question (for example, adding image to the question of type radiogroup)?

**Comment by andrewtelnov** [comment]
@kunal-mohta You can do it via code, using the following ``survey.onAfterRenderQuestion`` event and custom properties. Here is [the example](https://surveyjs.io/Examples/Library?id=survey-afterrender). You will have to render image/video instead of buttons.

Thank you,
Andrew

**Comment by kunal-mohta** [comment]
@andrewtelnov Thanks for the response.
The "Show in Survey Creator" link isn't working for the above example. Is there a similar example for the Creator service?

**Comment by andrewtelnov** [comment]
@kunal-mohta Here is [the example](https://surveyjs.io/Examples/Survey-Creator?id=modifysurveys).
Please note, SurveyJS Creator is not under MIT license unlike SurveyJS Library. You can't just use it in your app without getting a developer license.

Thank you,
Andrew

**Comment by kunal-mohta** [comment]
Yes @andrewtelnov I am aware of that. My team is planning on purchasing the commercial license, that is why I am looking into all the required aspects before making a decision.

The example you pointed me to isn't exactly what I was looking for. What I need is to provide the user who is creating the form using the survey creator a way to add image to the question of any type.

**Comment by andrewtelnov** [comment]
@kunal-mohta I wrote before, that it is very close. You can add a custom property imagePath instead of popupDescription and render image instead of button.

Thank you,
Andrew

**Comment by kunal-mohta** [comment]
Understood. Thanks a ton!

**Comment by kunal-mohta** [comment]
@andrewtelnov In the example which you pointed me to ([this one](https://surveyjs.io/Examples/Survey-Creator?id=modifysurveys)), after creating a new question and filling the `popupdescription` property, the **More info** button doesn't render in the designer tab, like it does in the default question ("What OS do you use?").
How can this be resolved?

**Note** - The button starts to appear when I reorder the new question.

**Comment by andrewtelnov** [comment]
@kunal-mohta I have updated [the example in plunker](https://plnkr.co/edit/J5Y6NTreNKhlsKew).

Thank you,
Andrew
