### ISSUE TITLE
Vue: undefined click handler error on clicking checkbox items in modern theme

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#2443]
The original issue came from [SurveyJS support desk](https://surveyjs.answerdesk.io/ticket/details/T5408).
On clicking checkbox items in modern theme vue generates an error

**Comment by simevo** [comment]
Hi ! thanks for the excellent library.

I think there is still something missing in the vue integration of matrixdynamic. I modified your vue example in `src/examples/vue` adding a matrixdynamic question from our survey:
[vue_example.zip](https://github.com/surveyjs/survey-library/files/5505397/vue_example.zip)

Clicking on "add car" has no effect.

I suspect this could be related to the way Vuejs keeps track of array changes: https://vuejs.org/v2/guide/reactivity.html#For-Arrays

**Comment by simevo** [comment]
I tested also the examples provided by you:
13. Matrix Dynamic: "Add subject" works
14. Matrix Dynamic (vertical columns): "Add date" and "Remove" do not work
15. Matrix Dynamic (totals): "Add new item" and "Remove" work

**Comment by andrewtelnov** [comment]
@simevo It works for me. Here is [the example](https://plnkr.co/edit/drBDkcqXfyJkGD4e). Could you please modify it so it doesn't work.

Thank you,
Andrew

**Comment by simevo** [comment]
Hi @andrewtelnov thanks for the quick reply ! I forked your example, here is mine: https://plnkr.co/edit/PlHC94Vg18R9P30o

I can add two rows. After that neither the "add row" or "remove row" button work:
![GIFrecord_2020-11-08_180206](https://user-images.githubusercontent.com/8254819/98471494-0896d300-21ed-11eb-915b-41fd4f4ed07d.gif)

**Comment by andrewtelnov** [comment]
@simevo I have fixed it. Here is [the issue](https://github.com/surveyjs/survey-library/issues/2514) where you can find my commit.

Thank you,
Andrew
