### ISSUE TITLE
The requiredQuestions progress bar works wrong

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-library#2445]
1) Go to https://plnkr.co/edit/Ru1uuCWejE8mJXgT
2) Click choice of required question and get this:
![image](https://user-images.githubusercontent.com/30930391/95482992-61c5d980-0997-11eb-9f67-de4472a63ee8.png)

3) Then click next and get this:
![image](https://user-images.githubusercontent.com/30930391/95483106-81f59880-0997-11eb-8572-9491f72b377f.png)

**Comment by andrewtelnov** [comment]
@gologames Fixed by [this commit](https://github.com/surveyjs/survey-library/commit/ccd44c5fa030733920251ee31fd3750901d85dd5).

Thank you,
Andrew
