### ISSUE TITLE
matrixdynamic total example does not work in vue mode

### ISSUE THREAD

**Issue by swuecho** [surveyjs/survey-library#2447]
### Are you requesting a feature, reporting a bug or asking a question?

click 'add new item'  does not work.

### What is the current behavior?

click 'add new item'  does not work.

### What is the expected behavior?

should work as in jquery mode.

### How would you reproduce the current behavior (if this is a bug)?

go to the example:  https://www.surveyjs.io/Examples/Library?id=questiontype-matrixdynamic-totals&platform=Vue&theme=default

fill the first row, click 'add new item'. 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/ciJchFqHJoMmrOFn

**Comment by andrewtelnov** [comment]
@swuecho We are releasing v1.8.8 today that contains the following [fix](https://github.com/surveyjs/survey-library/issues/2443).
It will solve the issue.

Thank you,
Andrew

**Comment by swuecho** [comment]
Thanks!
