### ISSUE TITLE
typo in example?

### ISSUE THREAD

**Issue by swuecho** [surveyjs/survey-library#2450]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?
in page: https://www.surveyjs.io/Examples/Library?id=questiontype-expression&platform=jQuery&theme=default#content-js

```js
  "expression": "sumInArray({items}, 'quantity'"
           
   "expression": "sumInArray({items}, 'total'",
```

seems missing ')'.

**Comment by andrewtelnov** [comment]
@swuecho I have corrected it. We will update the website on the next week and the fix becomes available.

Thank you,
Andrew

**Comment by swuecho** [comment]
Thanks.  Despite the typo, the example works fine. I guess the expression parser is not strict enough.
