### ISSUE TITLE
TextUpdateMode onTyping 

### ISSUE THREAD

**Issue by swuecho** [surveyjs/survey-library#2452]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

expression update after onBlur not OnTyping. i.e. setting TextUpdateMode = onTyping does not have any effect.

### What is the expected behavior?

after input the number, expression should auto update immediately.

### How would you reproduce the current behavior (if this is a bug)?

type number into text field. expression is not updated.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/Zoa2alQqxv25wtz0

### Specify your

* surveyjs version: 1.8.8

**Comment by andrewtelnov** [comment]
@swuecho Unfortunately html oninput event fires for the following tags:
<input type="password">, <input type="search">, <input type="text"> and <textarea>
Browsers do not support it for input type "number". It fires if you click on arrows increase/decrease value, but not on entering digits.

Thank you,
Andrew

**Comment by swuecho** [comment]
Thanks. for number type, increase/decrease the value indeed works.

However, I change the inputType to 'text' and still can not get expected behavior.

link for updated survey: https://plnkr.co/edit/3n8KIxRA8EduBuCy

**Comment by andrewtelnov** [comment]
@swuecho Hm, in fact it works for both bases. You should use "onTyping" and not "OnTyping". Here is [the forked version](https://plnkr.co/edit/Mkh5iL49Eh4d1wiD).

Thank you,
Andrew

**Comment by swuecho** [comment]
Sorry for the silly typo in my side.  Thanks for your patience.
