### ISSUE TITLE
Locale of progressbar does not change

### ISSUE THREAD

**Issue by MrKrabat** [surveyjs/survey-library#2453]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
If you change the language of the survey, the locale of the progressbar does not change.

### What is the expected behavior?
Progressbar should update too.

### How would you reproduce the current behavior (if this is a bug)?
Change the locale. https://plnkr.co/edit/0o1cxceHuYOFXKyq

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/0o1cxceHuYOFXKyq

### Specify your

* browser: Chrome
* browser version: 86
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: 1.8.8

**Comment by andrewtelnov** [comment]
@MrKrabat Added a unit test and fixed it.

Thank you,
Andrew
