### ISSUE TITLE
React warning with slider component: setState(...):Cannot update during an existing state transition 

### ISSUE THREAD

**Issue by anaskhanstack** [surveyjs/survey-library#2457]
Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.

this warning appears every time when i click next

**Comment by andrewtelnov** [comment]
@anaskhanstack What version do you use and how could we reproduce the issue? Could you please create the plunker example?


Thank you,
Andrew

**Comment by anaskhanstack** [comment]
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.6.4/showdown.min.js"></script>
    <script src="https://surveyjs.azureedge.net/1.8.4/survey.react.js"></script>
    <script src="https://unpkg.com/nouislider@9.2.0/distribute/nouislider.js"></script>
    <link href="https://unpkg.com/nouislider@9.2.0/distribute/nouislider.min.css" rel="stylesheet" />
    <script src="https://unpkg.com/wnumb@1.1.0"></script>
    <script src="https://surveyjs.azureedge.net/1.8.4/surveyjs-widgets.js"></script>

    these are all the version i am using for serveyjs

   in the end only this i am using for react
    ReactDOM.render(<Survey.Survey model={survey} />, document.getElementById("surveyElement"));

**Comment by andrewtelnov** [comment]
@anaskhanstack Please update to the latest version v1.8.9

Thank you,
Andrew

**Comment by anaskhanstack** [comment]
Most of the errors and warning are cleared but only at slider question this warning is appearing again

Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`

Thanks regards 
Anas Khan

**Comment by andrewtelnov** [comment]
@anaskhanstack We know how it works :-) 
I have reproduce the issue with slider.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@anaskhanstack It was fixed during [the following refactoring](https://github.com/surveyjs/survey-library/issues/2468).

Thank you,
Andrew
