### ISSUE TITLE
survey.getProgress() logs weird output on console

### ISSUE THREAD

**Issue by till-tomorrow** [surveyjs/survey-library#2460]
I have some questions that have
visible: "false"
That means they are invisible to users.

I want to track the survey completion progress. So, I have set the following:
"progressBarType":"questions"

Then I have this in the js file:
var surveyProgress = survey.getProgress();
console.log(surveyProgress);

### Are you requesting a feature, reporting a bug or asking a question?
bug

asking question

### What is the current behavior?
survey.getProgress() logs weird output on console. Even when the survey is answered fully then also the progress is not 100 percent.

### What is the expected behavior?
If say 6 out of 23 visible questions are answered then the progress should be 26 percent.

### How would you reproduce the current behavior (if this is a bug)?
survey.getProgress() logs incorrect output on console.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version: 84+
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.8.6

**Comment by andrewtelnov** [comment]
@till-tomorrow Indeed we did not finish with the refactoring after we changed progressText.
I have introduced observable/reactive progressValue property that you can use.

Thank you,
Andrew

**Comment by till-tomorrow** [comment]
Would the observable/reactive progressValue property be available in v1.8.10?

**Comment by andrewtelnov** [comment]
@till-tomorrow Yes they are. 

Thank you,
Andrew
