### ISSUE TITLE
not able to add css class to survey question

### ISSUE THREAD

**Issue by till-tomorrow** [surveyjs/survey-library#2462]
I am trying to highlight the question if there is a particular condition is met. So, I have set the following css class for the question when the condition is met:
_survey.getQuestionByName("questionName").cssClasses.mainRoot = " bq-info";_

But, the question does not get highlighted when the condition is met! Am I doing it a wrong way? Note that the css class "bq-info" is legit.

### Are you requesting a feature, reporting a bug or asking a question?
asking a question

### What is the current behavior?
The question does not get highlighted when the condition is met! Am I doing it a wrong way? Note that the css class "bq-info" is legit.

### What is the expected behavior?
The question's css class should be set to whatever class is provided by the user.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version: 84+
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.8.6

**Comment by andrewtelnov** [comment]
@till-tomorrow It is a calcualted property. Please use `onUpdateQuestionCssClasses` event for this. Here is [the example](https://surveyjs.io/Examples/Library?id=survey-cssclasses).

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@till-tomorrow If you want to update the css for all questions, then review [the following example](https://surveyjs.io/Examples/Library?id=survey-customcss).

**Comment by till-tomorrow** [comment]
Hi Andrew, Thanks for the quick response. 
I see that the first example you provided has the css property changed even before the answer has been recorded. Is there a way to change the css class after the user has answered the question (i.e., on the basis of user's response)?
Also, I don't understand when onUpdateQuestionCssClasses event gets fired. Can you please help me a bit on this piece?

**Comment by andrewtelnov** [comment]
@till-tomorrow I believe you need to set [this empty property](https://github.com/surveyjs/survey-library/blob/master/src/defaultCss/cssmodern.ts#L91) with your css class.

Thank you,
Andrew

**Comment by till-tomorrow** [comment]
I am afraid, this does not seem to work. Am I doing something wrongly?

```
survey.onUpdateQuestionCssClasses.add(function(survey, options) {
    var classes = options.cssClasses;
    options.question.hasError = "";
    if(options.question.description.includes("some text"))
        classes.title = "sq-title";
]);
```

**Comment by andrewtelnov** [comment]
@till-tomorrow Sorry, did not get the question at first. Here is [the working example](https://plnkr.co/edit/AF4VR7sBb31cBoYr).

Thank you,
Andrew
