### ISSUE TITLE
Bug: After server validation, first question with error does not focus

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#2464]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
After server validation, the first question with an error does not focus. This is especially problematic if your survey is relatively long and the user cannot see the error in the view and is wondering why the next page is not loaded.

### What is the expected behavior?
After server validation, first question with error should get focus.

### How would you reproduce the current behavior (if this is a bug)?
Enter a non existing country, see the error and see that the textfield is not focused.

#### Provide the test code and the tested page URL (if applicable)
https://surveyjs.io/Examples/Library?id=validators-server

### Specify your
* browser: Firefox
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: 1.8.9

**Comment by andrewtelnov** [comment]
@Lionqueen94 As a work-around you call call this function on error: `survey.focusQuestion("yourQuestionName");`.
We can't focus a question on server error in all cases. There could be another error that a user is already fixing and focusing to this particular error could confuse him/her. I guess we need to check if there is any error on the page and if there is no any error, then we can focus on this question. The problem that this event is async. We will discuss it.

Thank you,
Andrew

**Comment by Lionqueen94** [comment]
@andrewtelnov Thanks for your quick answer! I have one more question, for certain users I have the `survey.checkErrorsMode = "onComplete"`. When I click Submit and there are required questions not filled in, the survey goes to the right page, but then also does not focus on the first question with an error. This is separate from what I described before, because it happens before sending the data to the server for validation. Hopefully you can also discuss this case. Thanks!

**Comment by andrewtelnov** [comment]
@Lionqueen94 I have fixed the issue by the commit above.
Regarding the second issue. It has been fixed as well. Here is [the link](https://github.com/surveyjs/survey-library/issues/2466) on it.

Thank you,
Andrew

**Comment by Lionqueen94** [comment]
@andrewtelnov Great! Thanks for the work, looking forward to the new version :+1:
