### ISSUE TITLE
When survey checkErrorsMode is "onComplete" then the question with the first error is not focused

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#2466]
Let's say we have the following JSON:
```js
{
      checkErrorsMode: "onComplete",
      pages: [
        {
          elements: [
            { type: "text", name: "q0" },
            { type: "text", name: "q1", isRequired: true },
          ],
        },
        {
          elements: [{ type: "text", name: "q2", isRequired: true }],
        },
        {
          elements: [{ type: "text", name: "q3", isRequired: true }],
        },
      ],
    }
```
If a user click button "Next" and then "Complete" without entering any data, then it should come back into first page and the question "q1", the first question with the error should be focused. Currently it doesn't work correctly, question "q0" is focused.

**Comment by Lionqueen94** [comment]
Hi there, I have just tested version 1.8.10 and the problem is not fully fixed yet. With `checkErrorsMode: "onComplete"` and an error in the servervalidation, the question with the error (including the page with the error) are still not focused.

**Comment by andrewtelnov** [comment]
@Lionqueen94 It works for me if there is only one page. Here is [the example](https://plnkr.co/edit/DbmZY5cIvl3BTnvF).
However, `checkErrorsMode: "onComplete"` and `onServerValidateQuestions` event do not work correctly together. We call `onServerValidateQuestions` event for every page and do not take into account that `checkErrorsMode` is `onComplete`. I will work on the fix for this issue. I was able to reproduce it in a new unit test already.
Are you talking about this problem?

Thank you,
Andrew

**Comment by Lionqueen94** [comment]
> @Lionqueen94 It works for me if there is only one page. Here is [the example](https://plnkr.co/edit/DbmZY5cIvl3BTnvF).
> However, `checkErrorsMode: "onComplete"` and `onServerValidateQuestions` event do not work correctly together. We call `onServerValidateQuestions` event for every page and do not take into account that `checkErrorsMode` is `onComplete`. I will work on the fix for this issue. I was able to reproduce it in a new unit test already.
> Are you talking about this problem?
> 
> Thank you,
> Andrew

Yes, I have 5 or 6 pages indeed, and with an error on an earlier page, nothing happens onComplete. When you go back to the right page, the error is present. So if would be great if that works automatically. Thanks for responding so quickly!

**Comment by andrewtelnov** [comment]
@Lionqueen94 Yes, the issue exists because survejs doesn't change the page. It is fixed [here](https://github.com/surveyjs/survey-library/issues/2478). We will likely release v1.8.11 tomorrow and you will be able to check it.

Thank you,
Andrew
