### ISSUE TITLE
Set/unset single option of checkbox, based on other input

### ISSUE THREAD

**Issue by fabmue** [surveyjs/survey-library#2472]
Hi all!

### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the expected behavior?
Assuming I have a checkbox with options [A, B, C, D]. 
I want to set/unset checkbox option A, in case the user selects checkbox option B. 

Approaches as I understand them:
1. Triggers and setvalue: can only set all options together, but options C and D must not be touched. 
2. onValueChanged hook: As I understand it from the provided example in the docs (https://embed.plnkr.co/plunk/FfYvPB), a custom onValueChanged function can not be bound to a single question / option, but only to the survey object. And inside this function, it is checked (or returned) for the question.name. Meaning all the onValueChanged hooks that are added to the model are called for every user input, no matter which answer was changed by the user. Am I understanding this correct? If so, it seems not to be the right choice. 

3. generally for Triggers (e.g. runexpression): I could not figure out how to add such triggers "in code" when the model is already created in code (https://surveyjs.io/Documentation/Library#objects-createmodel). I managed only to add them in JSON form and creating the model from that JSON object.

Thanks for your help and best!

**Comment by andrewtelnov** [comment]
@fabmue Here is [the example](https://plnkr.co/edit/2dX8ojqoxJkPx9B6) with different ways of doing it.

Thank you,
Andrew

**Comment by fabmue** [comment]
Thanks a lot for the fast answer! I just realized that with triggers it is not possible to implement the radio-box behavior for two choices A and B (mutually exclusive, if A is set then B will be unset and vice versa), unless you add some more state. 
My higher goal is to bulid a nested question with radio-box on the outer level and checkbox on the inner level, similar to https://surveyjs.answerdesk.io/ticket/details/t1537/create-nested-questions, but with mutually exclusive booleans on the outer level. I guess I have to implement it with the onValueChanged function. There is no way of binding an onValueChanged function directly to a question, right?

**Comment by andrewtelnov** [comment]
@fabmue You are right, question doesn't have events. All events are in the root, on survey level.

Thank you,
Andrew

**Comment by fabmue** [comment]
Ok, thanks a lot for the fast response Andrew!

**Comment by JaneSjs** [comment]
Hi @fabmue,
To achieve this goal, enable the `isExclusive` option for a target checkbox item. This option is available with v2.1.1 and newer. For more information, refer to the following release note: https://surveyjs.io/stay-updated/release-notes/v2.1.1#support-for-exclusive-options-in-checkbox-questions.
