### ISSUE TITLE
Want to make choice of type comment with out using hasOther option

### ISSUE THREAD

**Issue by anaskhanstack** [surveyjs/survey-library#2475]
"type": "radiogroup",
 .....                  
 "choices": [
                        {
                            "value": "Lose Weight",
                            "text": "Lose Weight"
                        },
                        {
                            "value": "Happy with current weight",
                            "text": "Happy with current weight"
                        },
                        {
                            "value": "Gain Weight",
                            "text": "Gain Weight",
                            "cellType":"comment"
                        }
                    ],

**Comment by andrewtelnov** [comment]
@anaskhanstack We do not have this type of functionality. You can have a separate comment question with visibleIf equals to `"{yourRadiogroupQuestionName} = 'Gain Weight'"`.

Thank you,
Andrew

**Comment by anaskhanstack** [comment]
Can you please make the sample code in plunker?

**Comment by andrewtelnov** [comment]
Close as duplicated.
