### ISSUE TITLE
onPropertyChanged or onItemValuePropertyChanged callbacks doesn't work with ":multiplevalues" property 

### ISSUE THREAD

**Issue by AndrewIISM** [surveyjs/survey-library#2477]
onPropertyChanged or onItemValuePropertyChanged question callbacks doesn't work when item of ":multiplevalues" property checked/unchecked. For example, it leads to incorrect work of Undo/Redo functionality in Creator.
UPD:
Here is the simple example:
```js
Survey.Serializer.addProperty("carowner", {name: "letters:multiplevalues", choices: ["A", "B", "C", "D", "E", "F"] });
``` 
SurveyJS Creator creates a list of checkboxes from "A", ... ,"F" and the value of the property is an array on letters.

Currently, the SurveyJS Library creates a standard property for this type, while it should create a wrapper for JavaScript array to override push/pop/unshift/splice functions and call property change notification.

**Comment by andrewtelnov** [comment]
@AndrewIISM I have fixed the issue. We will include the fix in [v1.8.11](https://surveyjs.io/WhatsNew#v1.8.11).

Thank you,
Andrew
