### ISSUE TITLE
checkErrorMode equals "onComplete" doesn't work correctly with the server validation

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#2478]
There are two issues there. At first server validation, `survey.onServerValidateQuestions` event, executed on next page, and doesn't take into account that `checkErrorMode` is "onComplete". The second issue, on focusing question it doesn't change the current page and if the question with the error is located on a previous page, not the last one, end-user will not see any error and the last page will be the current one.

**Comment by Lionqueen94** [comment]
@andrewtelnov I currently use `onServerValidateQuestions` to send my data to the server, have it checked for errors, save it and return errors if present. Now I see that I should use `onPartialSend` to send the data to the server (I have `"sendResultOnPageNext": true`). In the case of `"checkErrorMode":"onComplete"`, the onServerValidateQuestions will only be fired on complete, so to save the data for every page Next, I would have to send it to the server `onPartialSend` right? However, with `"checkErrorMode":"onNextPage"` when data gets sent to the server on each page Next, will `OnServerValidateQuestions` be called before `onPartialSend`?

**Comment by andrewtelnov** [comment]
@Lionqueen94 survey will fire `onPartialSend` after `onServerValidateQuestions` executed and there is no any error on the page.
If you have "checkErrorMode":"onComplete" then `onPartialSend` will be fired without any checks.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
By the way, I have fixed the issue by the commit above. There were the third issue, options.data in the event, do not contains all data if `checkErrorMode is "onComplete"`. I have fixed this too.

Thank you,
Andrew
