### ISSUE TITLE
SurveyJS - allow for Authors ?

### ISSUE THREAD

**Issue by kokotko1337** [surveyjs/survey-library#2482]
Is there any way to allow my authors to create new surveys ?
I can create new only with Admin Account.

### What is the current behavior?
Authors can not make new surveys only admins.

### What is the expected behavior?
Authors should make new surveys not only admins.

Tested page URL: not Public

### Specify your

* browser: Chrome 
* browser version: Latest
* surveyjs platform (angular or react or jquery or knockout or vue): Wordpress
* surveyjs version: Latest

**Comment by tsv2013** [comment]
Could you specify - what are your question about? No SurveyJS Library neither SurveyJS Creator or other SurveyJS products have built-in user access management code.

**Comment by kokotko1337** [comment]
I thought this git is about Wordpress Plugin ... im sorry
