### ISSUE TITLE
Prevent scrolling on question change

### ISSUE THREAD

**Issue by jheathco** [surveyjs/survey-library#2494]
### Are you requesting a feature, reporting a bug or ask a question?

Requesting a feature, or asking how to perform a specific behavior

### What is the current behavior?

Oftentimes when going to the next question, the page will scroll

### What is the expected behavior?

Scrolling shouldn't happen

**Comment by andrewtelnov** [comment]
@jheathco Please set [survey.focusFirstQuestionAutomatic](https://surveyjs.io/Documentation/Library?id=surveymodel#focusFirstQuestionAutomatic) property to false.

Thank you,
Andrew

**Comment by SamMousa** [comment]
This one can be closed!

**Comment by tsv2013** [comment]
@SamMousa I guess @jheathco should close it if got the answer
