### ISSUE TITLE
Sharing data between questions in 'panel dynamic' questions

### ISSUE THREAD

**Issue by Nowado** [surveyjs/survey-library#2502]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question.

### What is the current behavior?
Here's where I'm at:
There's a question (name: 'question_panel1') that is a panel dynamic question. Inside it there are two questions: dropdown (name: 'question_dropdown1') and input (name: 'question_input1').
On another page, there's another panel dynamic question (name: 'question_panel2').

### What is the expected behavior?
What I would like to happen:
For each panel in 'question_panel1', create a panel in 'question_panel2'. In specific place in 'question_panel2' display values of 'question_dropdown1' and 'question_input1'.

I've seen both https://surveyjs.io/Examples/Library?id=survey-shareddata and https://github.com/surveyjs/survey-library/issues/1741. It seems to me like I should be able to get it to happen, as both panel dynamic questions use arrays of objects. I want to dig into those objects and pull values of specific questions (say, something like 'question_panel1.panel.question_dropdown1' or if we name value in 'question_dropdown1' 'value1', 'question_panel1.panel.value1') - I'm not sure if I can do it. I tried various combinations of names, 'panel' etc. but I fail to get this specific result.

**Comment by andrewtelnov** [comment]
@Nowado You should use `valueName` property two bind these two questions. Here is the [example](https://plnkr.co/edit/dgHrdumfHmzY8ROu).
Thank you,
Andrew
