### ISSUE TITLE
Implement alternative rendering for the boolean question (switch/checkbox)

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-library#2503]
Some users want different rendering for a boolean question - switch/checkbox
See the https://surveyjs.answerdesk.io/ticket/details/t5476/multiple-choice-questions-using-matrix thread for more details

**Comment by aanavaneeth** [comment]
is this available on survey-creator as well?

**Comment by andrewtelnov** [comment]
@aanavaneeth It is already there. Please go to our SurveyJS Creator, select a question and to property grid. In the general section you will find several switches: "Is visible", "Is required" and "Read Only" and in Layout second one boolean: "Is start with new line?".
Property can have type "switch" and "boolean".

Thank you,
Andrew
