### ISSUE TITLE
Duplicate other fields in checkbox

### ISSUE THREAD

**Issue by AndrewIISM** [surveyjs/survey-library#2509]
When created choice with value "other" in checkbox it work as other choice ("Has other item" property)

![image](https://user-images.githubusercontent.com/42766845/98374271-7908ed00-2051-11eb-9f6c-08566fd2456e.png)

![image](https://user-images.githubusercontent.com/42766845/98374294-81612800-2051-11eb-9548-7588fdff0a4b.png)

**Comment by andrewtelnov** [comment]
@AndrewIISM It is the correctly behavior.
You can change the default other value as:
``survey.getQuestionByName("yourQuestionName).otherItem.value = "newOtherValue";``

Thank you,
Andrew

**Comment by AndrewIISM** [comment]
Okay, thank you!
