### ISSUE TITLE
Panel title is not displayed in Creator on changing the title property value

### ISSUE THREAD

**Issue by AndrewIISM** [surveyjs/survey-library#2510]
For panel title not display. It always is display:none

![image](https://user-images.githubusercontent.com/42766845/98374494-ca18e100-2051-11eb-85b7-e94cce21149a.png)

**Comment by andrewtelnov** [comment]
@AndrewIISM We will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@AndrewIISM I have fixed it by the commit above.

Thank you,
Andrew

**Comment by AndrewIISM** [comment]
@andrewtelnov thank you!
