### ISSUE TITLE
Size param not changing single input

### ISSUE THREAD

**Issue by AndrewIISM** [surveyjs/survey-library#2511]
Maybe I don't understand how it work but when I change size parameter in Single Input nothing happens

![image](https://user-images.githubusercontent.com/42766845/98375067-a6a26600-2052-11eb-816b-651df798af9c.png)

**Comment by andrewtelnov** [comment]
@AndrewIISM It is the ["size" html attribute](https://www.w3schools.com/tags/att_size.asp).  You need to look at width in "Layout" category.

Thank you,
Andrew

**Comment by AndrewIISM** [comment]
@andrewtelnov I get it. Thank you
