### ISSUE TITLE
Warning cause of missing prop matrix.vue

### ISSUE THREAD

**Issue by CaptainCannabis** [surveyjs/survey-library#2513]
in this commit "columnIndex" key in row 9 has been removed resulting in a warning when rendering matrix.vue component.
https://github.com/surveyjs/survey-library/commit/a0ed68dddb22a6c9360b07267c572d800ef97530

`<th v-for="column in question.visibleColumns" :key="columnIndex" :class="question.cssClasses.headerCell">`

should be

`<th v-for="(column, columnIndex) in question.visibleColumns" :key="columnIndex" :class="question.cssClasses.headerCell">`

@gologames

**Comment by CaptainCannabis** [comment]
That was quick - will update my project the other day and confirm & close this.

**Comment by andrewtelnov** [comment]
@CaptainCannabis Thank you for reporting the issue!
Andrew
