### ISSUE TITLE
vue: matrix dynamic doesn't create new rows in some scenarios

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#2514]
Hi @andrewtelnov thanks for the quick reply ! I forked your example, here is mine: https://plnkr.co/edit/PlHC94Vg18R9P30o

I can add two rows. After that neither the "add row" or "remove row" button work:
![GIFrecord_2020-11-08_180206](https://user-images.githubusercontent.com/8254819/98471494-0896d300-21ed-11eb-915b-41fd4f4ed07d.gif)

_Originally posted by @simevo in https://github.com/surveyjs/survey-library/issues/2443#issuecomment-723638099_

**Comment by simevo** [comment]
Hi @andrewtelnov this works ! many thanks. FYI, we have used surveyjs for a CO<sub>2</sub> footprint calculator for a public agency here in Italy. It's here: https://www.arpa.piemonte.it/co2_footprint/#/start
