### ISSUE TITLE
Cannot find welsh translation in survey creator 1.8.13v on localhost

### ISSUE THREAD

**Issue by VolodymyrTrykoz** [surveyjs/survey-library#2518]
### Are you requesting a feature, reporting a bug or asking a question?
I have a question.

### What is the current behavior?
Today you have launched a 1.8.13 release, and I added welsh(camraeg) language to survey-library package in this commit https://github.com/surveyjs/survey-library/commit/86417da7c30f4b67833bc0cbcb8a1b76418e58b5
When I check welsh language on your main page https://surveyjs.io/create-survey, I can see that it was added https://prnt.sc/vgrvix
In my package.json, I use the lates version of surveyjs https://prnt.sc/vgrxtk
I have updated surveyjs on my local machine to 1.8.13 version but still cannot find welsh language in a list of languages in survey-creator https://prnt.sc/vgrzn6
I use react in my project.

What can be the reason for that?
### What is the expected behavior?
I want to see welsh(camraeg) language in a list of all languages

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):react
* surveyjs version:1.8.13

**Comment by andrewtelnov** [comment]
@VolodymyrTrykoz Did you update both survey libraries: react and knockout? We use SurveyJS Library knockout version in our SurveyJS Creator, since we have only knockout version for SurveyJS Creator.

Thank you,
Andrew

**Comment by VolodymyrTrykoz** [comment]
@andrewtelnov Thank you! I have updated survey-knockout as well and I now I see the the welsh language.
