### ISSUE TITLE
Checkboxes allow only a single answer?

### ISSUE THREAD

**Issue by bramevo** [surveyjs/survey-library#2519]
I use the online example where it checks if a checkbox answer is correct by using isAnswerCorrect()
But for some reason, I can only specify one correct answer using correctAnswer for a checkbox question.

    questions: [
                {
                    type: "checkbox",
                    name: "q1",
                    isRequired: true,
                    choicesOrder: "random",
                    title: `Some question.. Choose the three correct answers.`,
                    maxSelectedChoices: 3,
                    choices: [
                        "1|Some answer.",
                        "2|Another one.",
                        "3|Yet another one",
                        "4|Wrong answer.",
                        "5|Worst possible answer"
                    ],
                    correctAnswer: "1"
                }
            ]
        }
    }

The above will return incorrect as more than the correctAnswer value are selected.

Something which would make sense would be rather:

    correctAnswers: ["1", "2", "3"]

Which should require all 3 values to be selected before returning isAnswerCorrect as true.

**Comment by dmitrykurmanov** [comment]
Hello! 

Could you please try to use the array as value for the `correctAnswer` property:
```js
correctAnswer: ["1", "2", "3"]
```

here the example with your json: https://plnkr.co/edit/lUffDHwGTsLSwfIM

**Comment by bramevo** [comment]
This is strange, I wonder why it didn't work during my tests...
Updated it with the result isAnswerCorrect check and it does work: https://plnkr.co/edit/TiI0HF3hu8IVn6HH

@dmitrykurmanov Thx for pointing out that it should work
