### ISSUE TITLE
Request : Any php json builder for surveyjs?

### ISSUE THREAD

**Issue by adib-enc** [surveyjs/survey-library#2528]
We see that json structure can be hardcoded. I'd like to know if there is any php library to build json programmatically. 

For example, in Laravel, this Eloquent code declare how we want to get single row from database:
```
Question::where('id',">",1)->first();
```

What i expect from surveyjs at backend code (at least), especially at builder object (despite initialization from Laravel Facade or not):
reference : - https://surveyjs.io/Documentation/Library?id=Add-Survey-into-your-Web-Page
```
SurveyObject::title("Tell us, what technologies do you use?")
	->pages([
		Page::name("page1")->questions([
			Questions::type("Radiogroup")->choices([ "Yes", "No" ])
		]),
		Page::name("page1")->questions([
			Questions::type("Radiogroup")->choices([ "Yes", "No" ])
		])
	]);
```

Yet, i can't found any library capable of what i'm expecting. Is it good idea to make such library from scratch?

**Comment by tsv2013** [comment]
SurveyJS is a JavaScript client side library. You are asking about the completely different product.
SurveyJS can work with PHP backend. Here is the sample repo - https://github.com/surveyjs/surveyjs-php

**Comment by adib-enc** [comment]
@tsv2013 
this, https://github.com/surveyjs/surveyjs-php, just covers the hardcoded json sample. I think i will try to make the builder from scratch.
