### ISSUE TITLE
Can not make get started  page

### ISSUE THREAD

**Issue by anaskhanstack** [surveyjs/survey-library#2533]
![Untitled](https://user-images.githubusercontent.com/45259204/100053528-0a45d500-2e42-11eb-991e-d321263a6de9.png)
Can we make get started page before starting questionnaire? If yes then is there any example or a way to make that?

**Comment by tsv2013** [comment]
Yes, you can set the https://surveyjs.io/Documentation/Library?id=surveymodel#firstPageIsStarted property to true

**Comment by anaskhanstack** [comment]
Thanks for your support @tsv2013 it works

**Comment by anaskhanstack** [comment]
But can we add the background image to that specific question?
