### ISSUE TITLE
The tooltip get stuck in nouislider

### ISSUE THREAD

**Issue by anaskhanstack** [surveyjs/survey-library#2540]
![Capture](https://user-images.githubusercontent.com/45259204/100316246-ecac7300-2fdb-11eb-9426-4cd2bf32f7ab.PNG)

When i add tooltio in my slider it get stuck the slider does move but the tool does't move 

when i use cdn, it get fixed, but when i use the min.js file, the issue gets appear again

**Comment by anaskhanstack** [comment]
Not added proper file, instead of adding nouislider.js, i have add nouislider.min.js

**Comment by swuecho** [comment]
should not nouislider.js and nouislider.min.js  be equivalent?
