### ISSUE TITLE
firstPageIsStarted appear when i restart and select no option

### ISSUE THREAD

**Issue by anaskhanstack** [surveyjs/survey-library#2541]
Basically the problem is that, when i am in question 10 and restart the page it shows the firstPage again, is there any possibility to hide that page and only show once at start?

**Comment by andrewtelnov** [comment]
@anaskhanstack You have to do it manually by calling the following code: `survey.start();`.

Thank you,
Andrew

**Comment by anaskhanstack** [comment]
It works, Thanks @andrewtelnov :)
