### ISSUE TITLE
Radio in matrix not working with true and false values

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#2544]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

I cannot use value true/false values in matrix columns while I can do it in radiogroup. When choosing one or the other in matrix and look at the console you'll see why: strings "true" and "false" are stored ...

https://plnkr.co/edit/JeAJNJuJ1PAlyT1O

thank you

**Comment by tsv2013** [comment]
You need another question type for this:
```JSON
    {
            name: 'foo',
            rows: ['bar', 'zar'],
            type: 'matrixdropdown',
            columns: [
                {
                    name: "col1",
                    cellType: "radiogroup",
                    showInMultipleColumns: true,
                    choices: [true, false]
                }
            ]
        }
```
It uses the `showInMultipleColumns: true` option

Here is your updated plunker - https://plnkr.co/edit/TqsucQhQS4jEOLMg?preview

**Comment by masciugo** [comment]
Thank you. But does this mean that matrix is only for text and numbers value types?

**Comment by masciugo** [comment]
I just noticed that also numbers are converted to string. So I guess that's for string only value types

**Comment by tsv2013** [comment]
I'm not sure. We need to check it.

**Comment by masciugo** [comment]
@tsv2013 can you confirm that matrix produces string values only?

**Comment by andrewtelnov** [comment]
@masciugo I just understood the issue here. I will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@masciugo I have fixed the issue by the commit above.

Thank you,
Andrew
