### ISSUE TITLE
Bug: onServerValidateQuestions doesn't get called for the last page when showPreviewBeforeComplete is set

### ISSUE THREAD

**Issue by joshcampbell191** [surveyjs/survey-library#2546]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

`onServerValidateQuestions` doesn't get called on the last page if `showPreviewBeforeComplete` is set.

### What is the expected behavior?

`onServerValidateQuestions` should be called on every page.

### How would you reproduce the current behavior (if this is a bug)?

Using the test page provided below, you'll noticed that `page3` is never printed to the console unless you remove  `showPreviewBeforeComplete` from the survey.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/KBfdqN77mlIFxUGB

Test code

```
Survey
    .StylesManager
    .applyTheme("modern");

//assign call to onServerValidateQuestions callback
function surveyValidateQuestion(survey, options) {
    console.log(survey.currentPage.name);
    options.complete();
}

var json = {
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "boolean",
     "name": "question1",
     "isRequired": true
    }
   ]
  },
  {
   "name": "page2",
   "elements": [
    {
     "type": "boolean",
     "name": "question2",
     "isRequired": true
    }
   ]
  },
  {
   "name": "page3",
   "elements": [
    {
     "type": "boolean",
     "name": "question3",
     "isRequired": true
    }
   ]
  }
 ],
 "showPreviewBeforeComplete": "showAllQuestions"
};

window.survey = new Survey.Model(json);

survey
    .onComplete
    .add(function (result) {
        document
            .querySelector('#surveyResult')
            .textContent = "Result JSON:\n" + JSON.stringify(result.data, null, 3);
    });

survey
    .onServerValidateQuestions
    .add(surveyValidateQuestion);
$("#surveyElement").Survey({model: survey});
```

### Specify your

* browser: Microsoft Edge
* browser version: 87.0.664.47
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.8.18

**Comment by andrewtelnov** [comment]
@joshcampbell191 Fixed by the commit above.

Thank you,
Andrew
