### ISSUE TITLE
sum function not working

### ISSUE THREAD

**Issue by MrKrabat** [surveyjs/survey-library#2547]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
The validator 'sum(2, 3) equals 5' returns false.
The validator 'sum(5) equals 5' returns true.

### What is the expected behavior?
The sum(2, 3) should equal 5.

### How would you reproduce the current behavior (if this is a bug)?
Use the survey given below.
- Select 2 and 3 and submit => Failed
- Select 5 and submit => Success

#### Provide the test code and the tested page URL (if applicable)

Test code

```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "checkbox",
     "name": "e1",
     "title": "Select numbers to reach the sum 5",
     "validators": [
      {
       "type": "expression",
       "expression": "sum({e1}) equals 5"
      }
     ],
     "choices": [
      {
       "value": "1",
       "text": "1"
      },
      {
       "value": "2",
       "text": "2"
      },
      {
       "value": "3",
       "text": "3"
      },
      {
       "value": "5",
       "text": "5"
      },
      {
       "value": "8",
       "text": "8"
      },
      {
       "value": "13",
       "text": "13"
      }
     ],
     "colCount": 2
    }
   ]
  }
 ]
}
```

### Specify your

* browser: Chrome
* browser version: 87
* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version: 1.8.18

**Comment by MrKrabat** [comment]
In addition to this, the validator 'avg(1, 3) equal 2' also returns false.

**Comment by andrewtelnov** [comment]
@MrKrabat Here is [the working example](https://plnkr.co/edit/hm35HlPr8EgEuPc1).

Thank you,
Andrew

**Comment by MrKrabat** [comment]
Maybe you could add type conversion if numbers are strings?

Since even the SurveyJS Creator stores numbers as strings, this seems to be necessary.

**Comment by andrewtelnov** [comment]
@MrKrabat OK, it makes sense. I have added this functionality. Here is [the related issue](https://github.com/surveyjs/survey-library/issues/2549).

Thank you,
Andrew

**Comment by MrKrabat** [comment]
Thank you very much! :)
