### ISSUE TITLE
react: checkbox column is editable for readonly matrix if showInMultipleColumns is true

### ISSUE THREAD

**Issue by zhnedyalkow** [surveyjs/survey-library#2560]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug 

### What is the current behavior?

Display mode and readOnly modes did not affect the 'matrixdropdown' type

### What is the expected behavior?

By using 'display' mode in surveyjs implemented in React web app, I am expecting that all different types (checkboxes, radio buttons, single and multi choice matrix) will be disabled respectively.

### How would you reproduce the current behavior (if this is a bug)?

Basically extend the survey json => survey.mode = 'display'; Note that in the surveyjs designer everything seems to be working properly.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/create-survey

Test code

```
const surveyJSON = {"pages":[{"name":"page1","elements":[{"type":"matrixdropdown","name":"2628","title":"Rate your level of agreement with each of the statements below.","defaultValue":{"1832":{"col1":["7","6"]},"1835":{"col1":["7","6"]},"1836":{"col1":["6","7"]},"1844":{"col1":["7","6"]},"1845":{"col1":["7","6"]}},"readOnly":true,"columns":[{"name":"col1","cellType":"checkbox","showInMultipleColumns":true,"choices":[{"value":"10","text":"Disagree"},{"value":"9","text":"Somewhat Disagree"},{"value":"7","text":"Somewhat Agree"},{"value":"6","text":"Agree"}]}],"rows":[{"value":"1836","text":"I know what job/career I want to do when I finish school."},{"value":"1832","text":"I know how to explore and get information about careers I might be interested in."}]}],"title":"Test"}]}

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.7.18

**Comment by andrewtelnov** [comment]
@zhnedyalkow To be on the same page. You are talking about the bug, that you can check/uncheck checkboxes when the question is read-only?
We will fix this one. It happens when column in `showInMultipleColumns` mode.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Here is the [plunker example](https://plnkr.co/edit/0U5NKcmtT9AD8Sup).

**Comment by andrewtelnov** [comment]
@zhnedyalkow Fixed by the commit above.
The problem was in react and only with checkbox column with showInMultipleColumns property set to true.

Thank you,
Andrew

**Comment by zhnedyalkow** [comment]
Hi @andrewtelno,

Thank you for your prompt response.

When the fix will be available to be applied on npm?

Br,
Zhitomir

**Comment by andrewtelnov** [comment]
@zhnedyalkow We are releasing every week, commonly every Tuesday. However we can delay on couple days.
You can check [this page](https://surveyjs.io/WhatsNew) and see our previous releases.

Thank you,
Andrew

**Comment by zhnedyalkow** [comment]
@andrewtelnov thank you, in this case let's keep issue open until release date. 

Br,
Zhitomir

**Comment by zhnedyalkow** [comment]
@andrewtelnov the issue is resolved. You can close this ticket.

Thank you, great support!

Br,
Zhitomir
