### ISSUE TITLE
Add svg to input type button 

### ISSUE THREAD

**Issue by anaskhanstack** [surveyjs/survey-library#2565]
can we add svg to input type button e.g.

pageNextText: "Next![Nails](" + assetsurl + "Group13484.svg =75x75)",
The above statement does not work

![image](https://user-images.githubusercontent.com/45259204/101587750-a822cd80-3a06-11eb-8925-6a6d2c11801d.png)

**Comment by tsv2013** [comment]
I'll create a live sample on our site - https://surveyjs.io/Examples/Library in the "Navigation" section and post the link here

**Comment by tsv2013** [comment]
Here is the example on our site - https://surveyjs.io/Examples/Library?id=navigation-custom&platform=jQuery&theme=modern

You can open in in plunker or CodeSandbox and modify markup/styles according your needs.

**Comment by anaskhanstack** [comment]
Thanks it works
