### ISSUE TITLE
Bug: onValidatedErrorsOnCurrentPage isn't notified of errors set via onServerValidateQuestions

### ISSUE THREAD

**Issue by joshcampbell191** [surveyjs/survey-library#2566]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

The event `onValidatedErrorsOnCurrentPage` isn't notified of errors set via `onServerValidateQuestions`.

### What is the expected behavior?

The event should be triggered again once `options.complete()` is called from `onServerValidateQuestions`.

#### Provide the test code and the tested page URL (if applicable)

In the example provided, `errors: 1` is printed to the console when the field is blank however when an error is set via `onServerValidateQuestions`, it prints `errors: 0` since it runs before the server validation is completed.

Tested page URL: https://plnkr.co/edit/t2HgSyIXfFKBBmIZ

Test code

```
function surveyValidateQuestion(survey, options) {
    options.errors["country"] = "An exception has occurred.";
    options.complete();
}

function surveyValidateErrorsOnCurrentPage(survey, options) {
    console.log(`errors: ${options.errors.length}`);
}

var json = {
    questions: [
        {
            type: "text",
            name: "country",
            title: "Type a country:",
            isRequired: true
        }
    ]
};

window.survey = new Survey.Model(json);

survey
    .onComplete
    .add(function (result) {
        document
            .querySelector('#surveyResult')
            .textContent = "Result JSON:\n" + JSON.stringify(result.data, null, 3);
    });

survey
    .onServerValidateQuestions
    .add(surveyValidateQuestion);

survey
    .onValidatedErrorsOnCurrentPage
    .add(surveyValidateErrorsOnCurrentPage);

$("#surveyElement").Survey({model: survey});
```

### Specify your

* browser: Microsoft Edge
* browser version: 87.0.664.55
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.8.20

**Comment by andrewtelnov** [comment]
@joshcampbell191 Fixed by the commit above.

Thank you,
Andrew
