### ISSUE TITLE
React 17 warnings: "Please update the following components: Survey, SurveyElementErrors, SurveyLocString, SurveyNavigation, SurveyPage, SurveyQuestion, SurveyQuestionCheckbox, SurveyQuestionCheckboxItem, SurveyRow"

### ISSUE THREAD

**Issue by aneilbaboo** [surveyjs/survey-library#2581]
### What is the current behavior?

Warnings when using React 17 (I also tried with version 15)
```shell
  console.warn
    Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
    
    * Move data fetching code or side effects to componentDidUpdate.
    * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
    * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
    
    Please update the following components: Survey, SurveyElementErrors, SurveyLocString, SurveyNavigation, SurveyPage, SurveyQuestion, SurveyQuestionCheckbox, SurveyQuestionCheckboxItem, SurveyRow

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at warn (node_modules/react-dom/cjs/react-dom.development.js:51:5)
      at Object.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings (node_modules/react-dom/cjs/react-dom.development.js:11377:7)
      at flushRenderPhaseStrictModeWarningsInDEV (node_modules/react-dom/cjs/react-dom.development.js:23112:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:22396:3)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
```

### How would you reproduce the current behavior (if this is a bug)?
This repo shows the problem:
https://github.com/aneilbaboo/surveyjs-react17-warnings
```shell
yarn install
yarn test
```

### Specify your

* browser: Chrome / react testing library
* browser version: Version 87.0.4280.88 (Official Build) (x86_64), "@testing-library/react": "^11.2.2",
* surveyjs platform: react
* surveyjs version: "surveyjs": "^3.0.0", "surveyjs-react": "^1.0.1"

**Comment by andrewtelnov** [comment]
@aneilbaboo The current surveyjs-react version is: "1.8.21". Have you tried it?

Thank you,
Andrew

**Comment by aneilbaboo** [comment]
I did a fresh install of surveyjs-react using yarn.

I tried manually updating it in package.json followed by `yarn install`, but I get:

[1/4] 🔍  Resolving packages...
Couldn't find any versions for "surveyjs-react" that matches "^1.8.21"
? Please choose a version of "surveyjs-react" from this list: (Use arrow keys)
❯ 1.0.49 
  1.0.1 
  1.0.0 

I chose 1.0.49. I'm still getting the same error.

**Comment by aneilbaboo** [comment]
@andrewtelnov  I did a fresh install of surveyjs-react using yarn.

I tried manually updating it in package.json followed by `yarn install`, but I get:

[1/4] 🔍  Resolving packages...
Couldn't find any versions for "surveyjs-react" that matches "^1.8.21"
? Please choose a version of "surveyjs-react" from this list: (Use arrow keys)
❯ 1.0.49 
  1.0.1 
  1.0.0 

I chose 1.0.49. I'm still getting the same error.

**Comment by andrewtelnov** [comment]
@aneilbaboo You need [survey-react](https://www.npmjs.com/package/survey-react) package.

Thank you,
Andrew

**Comment by aneilbaboo** [comment]
Thanks!
