### ISSUE TITLE
[Feature] Support questionsOnPageMode at Page level

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#2586]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
Supported at the Survey level, not the Page level.

### What is the expected behavior?
Questions on page mode causes the pages to be remapped, for example, `singlePage` creates 1 page that contains all questions from all pages before executing the survey. Other modes are `questionPerPage` and `standard`. 

Due to the way this is setup, we could very easily support a different mode for a single page.
Instead of either creating 1 page (`singlePage` mode), or creating 1 question per page code flow would look as follows (pseudo code)
```js
let newPages = [];
let allInOnePage = null;
let questionOnPageMode = 'singlePage';
originalPages.apply(page => {
    // Get local questionsonpage mode
    let effectiveMode = (page.questionOnPageMode === 'default') ?  questionOnPageMode : page.questionOnPageMode;
    switch (effectiveMode): 
        case 'singlePage': 
            if (!allInOnePage) {
                allInOnePage = createAllInOnePage(page);
                newPages.push(allInOnePage);
            }
            page.questions.apply(question => {
                allInOnePage.push(question);
            });
        case 'standard':
            allInOnePage = null;
            newPages.push(clone page);
        case 'questionPerPage'
            allInOnePage = null;
            page.questions.apply(question => {
                newPages.push(createPageForQuestion(question, page));
            });
})


```

This rough flow will support combinations of modes and always create a sensible result.

**Comment by andrewtelnov** [comment]
@SamMousa Could you please describe the example of using this functionality? What is the business value of this? Sorry, but I do not see it right now, probably I miss the point.

Thank you,
Andrew

**Comment by SamMousa** [comment]
Suppose I have 20 questions I want to show 1 by 1, but have 5 questions I want to show on 1 page... Now that I think about it more, maybe the panel solution, where you put those 5 in a panel, is good enough.
