### ISSUE TITLE
Ignore logoWidth if logo is empty

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#2587]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
The survey title gets a style like this: `max-width: calc(((100% - 5px) - 2em) - 300px);` 
This (as expected), doesn't work very well with small display sizes, think a survey container of 500px wide...

### What is the expected behavior?
I assume that this calculation was added so that the survey title doesn't overlap the logo. I'd expect if no logo was specified (which is the default) then the `logoWidth` gets ignored and title is allowed to span the whole width.

### How would you reproduce the current behavior (if this is a bug)?
- Go to https://surveyjs.io/create-survey
- Set page title 
- Test survey
- Set it to mobile view

### Workaround
Explicitly setting the logo width to 0 makes it work as expected...

**Comment by dk981234** [comment]
Hello,

We've fixed the issue via the attached commit. The fix will be available with the next minor update.

Thanks,
Dmitry
SurveyJS Team
