### ISSUE TITLE
Feature Request: Add support for datalist

### ISSUE THREAD

**Issue by KevinColemanInc** [surveyjs/survey-library#2596]
### Are you requesting a feature, reporting a bug or asking a question?
Feature request

### What is the current behavior?
There isn't a way to search the choices of the dropdown list. [datalist](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) supports this

**Comment by andrewtelnov** [comment]
@KevinColemanInc We will add this functionality shortly. It is in our TODO list, since it is required for SurveyJS Creator v2. We are using SurveyJS widget as property grid to edit SurveyJS elements in SurveyJS Creator v2 and we need datalist support in the Library out of the box.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@KevinColemanInc The functionality will be available in [v1.8.24](https://surveyjs.io/WhatsNew#v8.24).

Thank you,
Andrew

**Comment by KevinColemanInc** [comment]
wow, that was fast! I am fundamentally looking for a means of having a drop down box with a 300+ options that is searchable. I could even see the need to query a remote api to get even more info. Other ppl may appreciate typeahead feature with remote querying.

I ended up using [react-select](https://react-select.com/home) to ask the question before loading the surveyjs component to show the rest.

**Comment by andrewtelnov** [comment]
@KevinColemanInc Yes, react-select is a better solution. We want to introduce something similar out of the box. Unfortunately, it is in our plans after releasing Creator V2.

Thank you,
Andrew
