### ISSUE TITLE
Vue: Set survey property value break survey navigation after version 1.8.9

### ISSUE THREAD

**Issue by swuecho** [surveyjs/survey-library#2599]
### How would you reproduce the current behavior (if this is a bug)?

1. go to https://9yhjm.csb.app/
2. click nextpage button, goto 2nd page.
3. click prevpage, click does not work any more.

![image](https://user-images.githubusercontent.com/666683/103630061-1d3ce080-4f7c-11eb-9da1-21a092a442bb.png)

PrevPage button does not work. 

### What is the expected behavior?

prevPage button should work.

#### Provide the test code and the tested page URL (if applicable)
works in 1.8.9 https://codesandbox.io/s/surveyjs-vue-forked-wmuzw?file=/src/components/SurveyComponent.vue
fail in 1.8.10 https://codesandbox.io/s/surveyjs-vue-forked-9yhjm

```
    this.survey = new Survey.Model(json);
    // after version  1.8.9, set locale break navigation 
    // How to reproduce:
    // chose a version after 1.8.9. say 1.8.10.
    // click nextpage button, goto 2 page.
    // then click prevpage, click does not work any more.
    this.survey.locale = "ja";
```

I tracked the code and find this change might related to this bug.

https://github.com/surveyjs/survey-library/commit/cc67fbfe766fdb8f83c553e305e14aa5b2e26548

**Comment by andrewtelnov** [comment]
@swuecho Fixed the by commit above. We will include this fix in [v1.8.24](https://surveyjs.io/WhatsNew#v1.8.24).

Thank you,
Andrew

**Comment by swuecho** [comment]
Thanks!

**Comment by swuecho** [comment]
I just tried the 1.8.24. However, still not works as good as in 1.8.9.

try to go Page 2 and then click PrevPage button or NextPage button. does not works well.

besides, my e2e tests related to page nav all fail with surveyjs 1.8.24.

**Comment by swuecho** [comment]
If it's not too much to ask, add a test to prevent regression like this would be great.

**Comment by andrewtelnov** [comment]
@swuecho We do have E2E tests on this. The problem that it works in our enviroment. Here is [the example](https://plnkr.co/edit/UdjrW9JsX4TXAvKi).
It doesn't work on CLI and it works in project I have created locally with my local vue version. I will re-check it later today.

Thank you,
Andrew

**Comment by swuecho** [comment]
@andrewtelnov  I see. Did not know expect the problem is so tricky.

**Comment by andrewtelnov** [comment]
@swuecho I installed v1.8.24 to my local vue CLI project and it doesn't work. I decided to rebuild vue version locally, because my commit  exists in v1.8.24, replace developer javascript with version from npm, restart the cli service and it works. I did not do any changes in my code. It is likely that my commit doesn't do anything.
We will investigate the issue tommorow and come back here. 

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@swuecho Finally fixed it. Unfortunately, the fix will be available in v1.8.26 that we will release on the next week.
You can add locale into json and it work, as a work-around.
`json.locale = "ja";` and then create survey model.

Thank you,
Andrew

**Comment by swuecho** [comment]
Thank you. I will try to cherry pick  the code in place.

**Comment by swuecho** [comment]
all test passed after I add the change to survey.vue.js.  Thanks and looking forward to the next release.

**Comment by andrewtelnov** [comment]
@swuecho Great!

**Comment by MuriloOnYou** [comment]
Hello,
I'm encountering exactly the same problem in my project. Latterly I have updated the survey-vue to 1.8.34 to use the multiple required choices features in checkbox questions and, since that, it's unpossible to use prevPage when I manually set the survey.currentPageNo prop. I have tried utilizing this property directly in the model constructor, but it doesn't suffer any effect.
Our app contains a feature where the backend saves the current page number being edited by user to return at the same point in case he reloads it. Therefore, it's profoundly significant in our software to include the possibility of setting this survey prop.

Heres a piece of the code:
```
this.survey = new SurveyVue.Model({
  title: this.form.title,
  pages: this.form.pages,
  locale: this.form.locale,
  css: myCss,
  showTitle: false,
  showNavigationButtons: false,
  showCompletedPage: false,
  completedHtml
});

this.survey.data = content.data;
this.survey.currentPageNo = currentPageNo;
```

**Comment by andrewtelnov** [comment]
@MuriloOnYou I have just tried it, but I could not reproduce the issue. Here is [the example](https://codesandbox.io/s/surveyjs-vue-forked-fsyjv?file=/src/components/SurveyComponent.vue).

Thank you,
Andrew

**Comment by MuriloOnYou** [comment]
I tried your code and it really worked. But in our case, we run VueJS along with NuxtJS and, then, this simple example doesn't work as expected:
[VueJS + NuxtJS + SurveyJS bug on line 978 (pages/index.vue)](https://codesandbox.io/s/goofy-kepler-z80vl?file=/pages/index.vue)

Comment that line and the form will render with function prevPage working but we need both: 
- to programatically set the current page
- method prevPage working

Thanks,
Murilo R. Montano.

**Comment by swuecho** [comment]
I have `survey:null` set in vue data. Recently I found survey.data will throw error in console. so I change it to `survey: {}` and then the multiple choices symptom will appear.  I revert back to `survey:null` and everything go back to normal. 

might not related. just to post here for reference.

**Comment by andrewtelnov** [comment]
@MuriloOnYou This work-around will solve the issue:
```js
    let survey = new SurveyVue.Model(json);
    survey.data = {
      employeeApproach: ["didntNoticeMe"],
      cordiality: ["kindAndPoliteService"],
      professionalLook: ["goodAppearance"],
      staffBehavior: ["highVolumeTalking"],
    };

    //This line breaks the prevPage function
    survey.currentPageNo = 1;
    this.survey = survey;

```
Thank you,
Andrew

**Comment by MuriloOnYou** [comment]
That worked marvellously. Thank you very much.
