### ISSUE TITLE
Feature request: contextual help text

### ISSUE THREAD

**Issue by ockam** [surveyjs/survey-library#260]
I would like to add help text to my survey. 

Would be great if we could attach help info to any part of a question (global, row, column, answer) and specify if it should render as a dom element or as an attribute (title or other data attribute that would render as a tooltip or popover).

I understand this is complex and has many side effect. 

Meanwhile, is it possible to implement a custom solution with a custom react template? (I have tried but I still can’t wrap my head around the way props are being passed from config to components).

**Comment by andrewtelnov** [comment]
@ockam 
I agree that tooltip/help feature, would be nice to have. I have add this to our TODO list, but I can't promise anything at the current moment. 

At the current moment, there are two options and both are not easy once:
1) [Override the question rendering](http://surveyjs.org/examples/react/survey-customtemplate.html)
2) [Use onAfterRenderQuestion event to correct the DOM](https://github.com/surveyjs/surveyjs/issues/219). Unfortunately we did not have time to make an example yet.

PS: You introduce your own properties: http://editor.surveyjs.io/examples/addproperties.html#code

Thank you,
Andrew

**Comment by ockam** [comment]
Thanks @andrewtelnov 

Regarding the last link (properties), is it normal I can’t see this section when navigating the regular website (surveyjs.org vs editor.surveyjs.io)?

**Comment by andrewtelnov** [comment]
@ockam What do you mean?
Are you talking about his page  http://editor.surveyjs.io/examples/addproperties.html#code?
The Json properties code is in the surveyjs library. Surveyjs library use it to create objects from json. You may need it to make sure the help context related properties are read from Json. Nothing more.

Editor uses Json properties code a lot. The most declaration described in the article used by Editor only. I doubt that you need it.

PS: Here is the main site of the project: http://www.surveyjs.io

Thank you,
Andrew

**Comment by ockam** [comment]
Yes, I meant this page.

At first, I didn’t see the difference (between editor and library).

**Comment by zzal** [comment]
It would be nice to be able to globally override the `renderTitle` method in the `SurveyQuestion` class  (I’m looking at the React version … But I don't know if this easy). That way, we could keep all questions rendering intact, and control globally how all questions are rendered.
Or maybe this should go into `questionTitleTemplate` survey property? But if so, the `textPreProcessor` handling the template should known the custom property the help text is attached to. And also, it should be able to parse HTML (this could allow the help text to be shown only on mouseover)

**Comment by andrewtelnov** [comment]
@zzal Yes, you should use the questionTitleTemplate property:
`survey.questionTitleTemplate = "{no}) {title} {require}:";`
Here is [the demo](http://surveyjs.org/examples/jquery/survey-processtext.html).

PS: Please create a new issue next time, since it is a different topic.

Thank you,
Andrew
