### ISSUE TITLE
Support editing question text dataList property in Survey

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#2605]
The functionality is required for Creator V2. We use Survey as property grid to edit Survey objects.

**Comment by swapnil0545** [comment]
@andrewtelnov I know this is closed. I was able to use this with type text and dataList as property. But I want to show the dropdown values from a restful service. I am not able to use choicebyURL along with this. Any suggestions...

**Comment by andrewtelnov** [comment]
@swapnil0545 Unfortunately, you will have to do it via code. Get values from your service and then assign into dataList property.
You can go futher and add a property dataListByURL and write the code that will work for all text questions in your surveys.

Thank you,
Andrew
