### ISSUE TITLE
Ranking Question

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/survey-library#2612]
### A question for drag and drop ranking. Allows respondents to rank items against each other by placing them in order of preference. Is appropriate for short lists (e.g. 5-7 items).

```js
const json = {
  "questions": [
    {
      "type": "ranking",
      "name": "smartphone-features",
      "title": "Please rank the following smartphone features in order of importance:",
      "isRequired": true,
      "choices": [
        "Battery life",
        "Screen size",
        "Storage space",
        "Camera quality",
        "Durability",
        "Processor power",
        "Price"
      ]
    }
  ]
};

new Survey.Model(json);
```

here the example: https://surveyjs.io/Examples/Library?id=questiontype-ranking

**Comment by aanavaneeth** [comment]
hi. This is cool. I have two points with respect to this. Is it possible to add dynamic options? (not just other but new dynamic choices.) Also, i am not sure how it works on touch screens. have you considered that?

**Comment by dmitrykurmanov** [comment]
@aanavaneeth hello!

As for touch support, it should be ok. We've tested it on mobile devices.

As for dynamic choices could you please describe your scenario? Are you talking about something like [matrix dynamic](https://surveyjs.io/Examples/Library?id=questiontype-matrixdynamic&platform=jQuery&theme=modern) ? We have plans to add drag/drop functionality to matrices.

**Comment by aanavaneeth** [comment]
yes like dynamic matrix/panel.
Having that feature is really useful because that way we can have dynamic option also to be ranked. I dont think drag drop on matrix is a replacement to this.

**Comment by aanavaneeth** [comment]
Recently I extended sortable list widget to achieve dynamic option feature. If you can add this feature to ranking, sortable list itself is not required at all for my requirement.

**Comment by aanavaneeth** [comment]
#2640

**Comment by dmitrykurmanov** [comment]
@aanavaneeth, could you please check our carry forward example https://surveyjs.io/Examples/Library?id=survey-carry-forward&platform=jQuery&theme=modern ? Now it contains ranking. And it is dynamic items in fact.

We have some [problem](https://github.com/surveyjs/survey-library/issues/2645) with carry forward + ranking but we are working on the fix.

Could you also please share the example/screenshot with your extension for the list widget? It will help us to better understand your use case.

**Comment by aanavaneeth** [comment]
dynamic option means users adding new options. not filtering kind of thing.

**Comment by dmitrykurmanov** [comment]
@aanavaneeth we'll discuss it with the team

**Comment by dmitrykurmanov** [comment]
@aanavaneeth we've discussed that idea with the team. And we think that it make sense especially for ranking. We also have the same feature request for the dropdown question (like select2). And we'll add the feature to our "todo". Here the issue:  https://github.com/surveyjs/survey-library/issues/2666. Thanks.
