### ISSUE TITLE
Prevent spamming on complete button?

### ISSUE THREAD

**Issue by demoFuncID1** [surveyjs/survey-library#2616]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?
i have some validation on function onServerValidateQuestions, which is checking some id if exist in database then will prevent  to submit, the issue is if we spamming the complete button while waiting the response, then it will create double entry in the database, is there anyway once I click the complete button I can disable the button ?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:Chrome
* browser version: Version 87.0.4280.141
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.7.26

**Comment by andrewtelnov** [comment]
@demoFuncID1 It works out of the box with the latest versions. Here is [the example](https://plnkr.co/edit/c8K0DF38X2pCm1sg?preview).

Thank you,
Andrew

**Comment by demoFuncID1** [comment]
Hi @andrewtelnov  thank you for your prompt response, I think I found the issue. I use surveyJS script refer from this src `<script src="https://surveyjs.azureedge.net/1.7.26/survey.jquery.js"></script> ` and if I keep spamming the complete button the  there will a multiple submission but  once I change to use the script you provided in the example, as per your comment above it works. so I update the script tag using the one you provided in the example. Thank you for the support
