### ISSUE TITLE
Continue questions from where I left. 

### ISSUE THREAD

**Issue by AWIXOR** [surveyjs/survey-library#2629]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question

### What is the current behavior?

Every time user refreshes the page the survey starts over.

### What is the expected behavior?

Is there any possibility to continue from where he left?

### Specify your

* browser: Chrome
* surveyjs platform: React (Nextjs)

**Comment by andrewtelnov** [comment]
@AWIXOR You can save the question name and then do the following:
`survey.focusQuestion("myPreviouslySavedFocusQuestionName");`

Thank you,
Andrew

**Comment by AWIXOR** [comment]
This is what I ended up doing!

```javascript
  survey.sendResultOnPageNext = true;
  const storageName = "Survey";
  function saveSurveyData(survey) {
    let data = survey.data;
    data.pageNo = survey.currentPageNo;
    window.localStorage.setItem(storageName, JSON.stringify(data));
    console.log(data);
  }
  survey.onPartialSend.add(function (survey) {
    saveSurveyData(survey);
  });
  survey.onComplete.add(function (survey, options) {
    saveSurveyData(survey);
    window.location.href = "/part1/finish";
  });
  const prevData = window.localStorage.getItem(storageName) || null;
  if (prevData) {
    let data = JSON.parse(prevData);
    survey.data = data;
    if (data.pageNo) {
      survey.currentPageNo = data.pageNo;
    }
  }
```
