### ISSUE TITLE
Can not add placeholder to  hasComment: true

### ISSUE THREAD

**Issue by anaskhanstack** [surveyjs/survey-library#2634]
Can not add placeholder to  hasComment: true

 {
      name: "page1",
      elements: [
      {
              value: "other",
              name: "other",
              placeHolder: "Jon Snow",
              text: "Other",
              hasComment: true,
              enableIf: "{QDietPref} notcontains ['None']",
       }]
}       

![image](https://user-images.githubusercontent.com/45259204/106125112-92679400-617d-11eb-9906-fdaae43b2ec1.png)

**Comment by andrewtelnov** [comment]
@anaskhanstack we do not have this functionality yet. We have placeHolder for text and comment questions and we have otherPlaceHolder for radiogroup, checkbox and dropdown questions.
We do not have commentPlaceHolder property.

Thank you,
Andrew

**Comment by anaskhanstack** [comment]
Noted with Thanks

**Comment by JaneSjs** [comment]
Hello @anaskhanstack,
With the current version, you can enable the [question.showCommentArea](https://surveyjs.io/form-library/documentation/api-reference/question#showCommentArea) option to activate a comment section and specify the [question.commentPlaceholder](https://surveyjs.io/form-library/documentation/api-reference/question#commentPlaceholder) property.

![image](https://github.com/surveyjs/survey-library/assets/22372972/eb1f8564-284e-4a48-9071-932def0d2f44)
