### ISSUE TITLE
Angular package (survey-angular) should not have a dependency on knockout

### ISSUE THREAD

**Issue by cbc872** [surveyjs/survey-library#2635]
Regarding Issue: Angular package (survey-angular) has dependency on knockout? ko not defined (https://github.com/surveyjs/surveyjs_angular_cli/issues/33)

It looks like this issue is occurring again in the latest release... Survey JavaScript library v1.8.26. It is requiring knockout. Is there a fix for this on the way?

**Comment by andrewtelnov** [comment]
@cbc872 We are working on the fix and we are going write tests to check links on knockout in types to avoid the issue in the future.

Thank you,
Andrew
