### ISSUE TITLE
How to depollute global scope

### ISSUE THREAD

**Issue by ShaneHudson** [surveyjs/survey-library#2637]
If I have multiple surveys on a React app, I have noticed they share the same instance. How do I ensure each survey uses it's own instance and therefore doesn't have any of the styling or functions of the others?

I've found this easy to replicate when using:
```
    Survey.StylesManager.applyTheme('bootstrap');
```

If that is required in one survey but not another, the one it isn't needed in will work fine until you navigate to the page that has the first one on then back again and the styling will be messed up.

I can fix this by applying a theme directly to the second. 

But I don't feel comfortable with that workaround, as I have no idea how the other functions and everything applied will pollute the other surveys so it seems high risk of at some point introducing bugs without noticing.

How can I ensure each survey uses a fresh instance with no overlap?

**Comment by andrewtelnov** [comment]
@ShaneHudson We make this function static on library level instance by a reason. We believed that developers want to have the same theme for all their surveys, at least on the current page.
Do you have another scenario?

Thank you,
Andrew

**Comment by ShaneHudson** [comment]
So my use-case is essentially I have one older complex form and one newer simple form.

So I want the simple form to not have any of the complexity of the other one. This will help me to over time simplify the complex form too to improve the styling iteratively instead of needing to change the complex form all at once.

Does that make sense? I want to make sure form 2 is a complete fresh instance without any complexity added on form 1.

**Comment by andrewtelnov** [comment]
@ShaneHudson Are they on different browser pages or in the same browser page?

Thank you,
Andrew

**Comment by ShaneHudson** [comment]
They are on different pages but in a SPA currently so uses the same instance.

**Comment by andrewtelnov** [comment]
@ShaneHudson If they are not showing at the same time, then you can set theme every time you are showing the survey. It should not create an issue.

Thank you,
Andrew

**Comment by ShaneHudson** [comment]
That’s true and that’s what I’ve done. But it feels like a workaround... is the styling the only thing done statically? The more complex form has a lot of functions and events on, just want to ensure none of them cause bugs on the simple form without me realising?

**Comment by andrewtelnov** [comment]
@ShaneHudson Since there is no async operations in this code, you are totally fine. It is a simple and working solution. Creating something with several libraries instances will make everything more complicated.

Thank you,
Andrew

**Comment by ShaneHudson** [comment]
Ok. I just want to ensure it is a fresh instance each time. Is it possible to clear existing to make sure I don't bump into any similar issue? Or is styles the only thing that would have the problem? Wouldn't want events triggering on the wrong form.

Is there a function that will reset the instance back to defaults?

**Comment by tsv2013** [comment]
Right now the 
```JS
Survey.StylesManager.applyTheme('bootstrap');
```
code every time it called is creating a new dynamic CSS stylesheet and injects in on your web page.
It can be used to re-generate styles dynamically on-the-fly but when we wrote this code, we didn't keep in mind survey re-styling on the on-the-fly in the end-user application.

If you are talking about the depolluting the global scope from the `Survey` namespace, you can import the `Survey` as a module in your application and it will be scoped inside it and not presented in global (window) scope.

**Comment by ShaneHudson** [comment]
> If you are talking about the depolluting the global scope from the Survey namespace, you can import the Survey as a module in your application and it will be scoped inside it and not presented in global (window) scope.

Thanks @tsv2013, I think I'm doing that already if I understand correctly. Am doing `import * as Survey from 'survey-react';` in each of the pages that hold separate surveys.

If the StylesManager is definitely the only one that shares data between them then that's fine. Just given I've seen one thing do it, nervous about it happening again.
