### ISSUE TITLE
allowCompleteSurveyAutomatic property is not working

### ISSUE THREAD

**Issue by DanielDwyer** [surveyjs/survey-library#2638]
I have found a bug within the `surveyModel`, I have set `goNextPageAutomatic` to true and `allowCompleteSurveyAutomatic` to false.

When the user selects an answer to the final question on the last page of the survey, the survey is automatically completed. 

I expect the user to be automatically navigated forward upon answering each survey question until the user gets to the final question where I expect the user to have to click complete to finish the survey, not be automatically completed upon selecting an answer.

I provided a link that reproduces the behavior.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

https://plnkr.co/edit/ko6YInfDCEneTF5Y

Test code

```
  "goNextPageAutomatic": true,
  "allowCompleteSurveyAutomatic": false

```

* browser: Chrome
* browser version: 88
* surveyjs platform Vue
* surveyjs version: 1.8.6

**Comment by andrewtelnov** [comment]
@DanielDwyer For some reason, we do not have this property serializable and decided that only developer can change it. Please remove it from JSON and set it as: `survey.allowCompleteSurveyAutomatic = false;`.
Here is [the example](https://plnkr.co/edit/tHATrt1c0CNhdkn2).
You can make it serializable as: 
`js
Survey.Serializer.addProperty("survey", {name: "allowCompleteSurveyAutomatic:boolean", category: "logic"});
`
Here is [the example](https://plnkr.co/edit/TJBIC7uMIgiM1e89).

Thank you,
Andrew
