### ISSUE TITLE
(bootstrap theme) Single Questions or Panel in a row -- Flex property still applied to element.style

### ISSUE THREAD

**Issue by mikekidder** [surveyjs/survey-library#2649]
Looks like this is still happening to a single Question on a row.   
Found closed Issue #2559 

![image](https://user-images.githubusercontent.com/41694/106989305-1f3ac080-672f-11eb-8f2c-338aae232740.png)

Should also apply to a single Panel on row as well.

Tested page URL:    https://plnkr.co/edit/7xNd7W1vNeuvg80s

### Specify your

* browser:  **Chrome / Edge** 
* browser version:  **recent**
* surveyjs platform:   **Knockout  / Bootstrap 3.3.7**
* surveyjs version:  **1.8.26  and tested latest with Plunker**

**Comment by mikekidder** [comment]
Workaround:   I have applied this in my own CSS

![image](https://user-images.githubusercontent.com/41694/106989511-8ce6ec80-672f-11eb-8546-c6f6a4c385e4.png)

**Comment by mikekidder** [comment]
SEE ALSO:  

Another issue in Plunker.  
There is a media break around 1556px causing the questions to wrap at smaller widths.
Open the plunker preview in full screen to see difference.

Happy to open a separate Issue

**Comment by dmitrykurmanov** [comment]
@mikekidder, hello!

I've manage to reproduce a problem. It works ok with the modern theme: https://plnkr.co/edit/7xNd7W1vNeuvg80s?preview
But doesn't work in bootstrap: https://plnkr.co/edit/4rRiggjNKwiHsCoT

**Comment by mikekidder** [comment]
Saw the fix.  Thanks!

Shouldn't the Panel (Bootstrap themes) get the same treatment as well?

**Comment by dmitrykurmanov** [comment]
@mikekidder  you are right. I added the fix for panels too
