### ISSUE TITLE
Add base.getSurvey() function

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#2654]
Add 'getSurvey()' function that will return survey model for all `base` classes, like triggers, validators, itemvalues and others.

**Comment by mikekidder** [comment]
Andrew, just curious if there is a movement away from Typescript's get/set?

**Comment by andrewtelnov** [comment]
@mikekidder We need this functionality for Survey Creator V2. I wanted to move `get survey()` into Base class. Unfortunately, it breaks Creator V1 unit tests and to deal with them I would have to make a lot of refactoring in Creator V1. I was afraid to make this large change in Creator V1 that can break something and do not bring any improvements to our current users, so I decided to go with `getSurvey()` function.
