### ISSUE TITLE
"Complete" button appears beforehand the survey is completed

### ISSUE THREAD

**Issue by Elaci0** [surveyjs/survey-library#2664]
### Are you requesting a feature, reporting a bug or asking a question?
Question 

### What is the current behavior?
I have a simple survey with 2 visibile pages and 2 conditionally visible pages.
I am also using the custom navigation [https://surveyjs.io/Examples/Library?id=survey-customnavigation&platform=jQuery&theme=bootstrap](https://surveyjs.io/Examples/Library?id=survey-customnavigation&platform=jQuery&theme=bootstrap)

page1:  simple welcome text
page2:  many booleans with  one required (say bln4)
page3:  simple text, visible if  bln4==True
page4:  simple text  visibile if   bln4 == False

on page1 I have **Next**  button (click)
on page2 I have **Complete** button (but there is at least one page more to see, visibile upon condition)
clicking on  **Complete**  I get error if nothing was selected, as soon as I select  True/false   the button changes to  "**Next**"
but the "**Complete**" link, added by the external navigator, did not change accordly

### What is the expected behavior?
I am expecting that "**Complete**" button appears only once in the last page.  I suspect that the internal counter of the pages, if there is one -visible with  survey.currentPageNo -- is not counting the _not_Visible pages and the second page, in my example, is being considered as __lastPage__ 
If this intended, how can I change the "complete" into the external navigator of that example?
Should I monitor some event and change such link accordly to what was fired?

### How would you reproduce the current behavior (if this is a bug)?
my example is here [https://plnkr.co/edit/Nk7RPSlFWCQrP3yJ](https://plnkr.co/edit/Nk7RPSlFWCQrP3yJ)

**Comment by andrewtelnov** [comment]
@Elaci0 You have to react on [survey.onPageVisibleChanged](https://surveyjs.io/Documentation/Library?id=surveymodel#onPageVisibleChanged) event.
Here is the updated code;
```js
$("#surveyElement").Survey(
{model: survey, 
onCurrentPageChanged: doOnCurrentPageChanged, 
onPageVisibleChanged: doOnCurrentPageChanged}
);
```
Here is the updated [example](https://plnkr.co/edit/kpiUJLTlS2Rri5LG).

Thank you,
Andrew

**Comment by Elaci0** [comment]
Thank you, it works! ..and it is more clean than the code I wrote (using the same onPageVisibleChanged event)
