### ISSUE TITLE
Is it possible to let comment fields grow with the content, especially in display mode?

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#2670]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question/Requesting a feature

### What is the current behavior?
Currently, comment fields with a lot of text do not grow with the content in display mode, making part of the text unreadable.

### What is the expected behavior?
It would be nice if the comment field could automatically grow in size with the content.

### How would you reproduce the current behavior (if this is a bug)?
Add a comment field to a survey, fill in a large amount of text and look at it in display mode.

### Specify your

* browser: Chrome/Firefox
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.8.27

**Comment by andrewtelnov** [comment]
@Lionqueen94 This functionality is in our TODO list, since it has been asked several times, but unfortunately, we have not time to implement it yet.
We are mostly working on SurveyJS Creator v2 at the current moment. We will implement it in the future.

Thank you,
Andrew

**Comment by Lionqueen94** [comment]
This issue can be closed because the feature has been added, thanks again! Maybe it would be good to add it to https://surveyjs.io/WhatsNew for other users.
