### ISSUE TITLE
[Question] access choice value or text 

### ISSUE THREAD

**Issue by swuecho** [surveyjs/survey-library#2675]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

survey 1: 
based on:  https://surveyjs.io/Examples/Library?id=questiontype-dropdownrestfull&platform=jQuery&theme=modern#content-js

```
{ elements: [
  {
    type: "panel",
    name: "panel_countriesByRegion",
    title: "Show countries by region",
    elements: [{
    type: "dropdown",
    name: "region",
    title: "Select the region...",
     choices: ["Africa", "Americas", "Asia", "Europe", "Oceania"]
  }, {
    type: "dropdown",
    name: "reg_country",
    title: "Select the country...",
    isRequired: true,
    choicesByUrl: {
      url: "https://restcountries.eu/rest/v2/region/{region}",
      valueName: "name"
    }
  }]
  }
```

in the survey above,  `region` are evaluated to value in choices.

What if I want the text of choices?

```

{ elements: [
  {
    type: "panel",
    name: "panel_countriesByRegion",
    title: "Show countries by region",
    elements: [{
    type: "dropdown",
    name: "region",
    title: "Select the region...",
    // choices: ["Africa", "Americas", "Asia", "Europe", "Oceania"]
    choices: [
      {
       value: "1",
       text: "Africa"
      },
      {
       value: "2",
       text: "Americas"
      },
      {
       value: "3",
       text: "Asia"
      },
      {
       value: "4",
       text: "Europe"
      },
       {
       value: "5",
       text: "Oceania"
      }
     ]
  }, {
    type: "dropdown",
    name: "reg_country",
    title: "Select the country...",
    isRequired: true,
    choicesByUrl: {
      url: "https://restcountries.eu/rest/v2/region/{region}",
      valueName: "name"
    }
  }]
  }
```
`region` will evaluated to value, which is one of '1,2,3,4,5'. 

something like `region.value`, `region.text` will be great. or `region` is evaluated to value as before and `region.text` evaluated to choice text.

**Comment by swuecho** [comment]
issue related: https://github.com/surveyjs/survey-library/issues/1987

**Comment by andrewtelnov** [comment]
@swuecho I am not sure why should you make this so complicated, but you would have to write some code for this.
At first you will have to introduce a calculatedValue that you can use in `url` text processing.
Then you will need to register a custom function that will set the correct value of this calculatedValue. 
Here is [the example](https://plnkr.co/edit/1s6g9tQYnS2Bb5jd).

Thank you,
Andrew

**Comment by swuecho** [comment]
Thanks.  in our system, the answer is stored as value (int) in postgres, so we want to access the text instead of value in the frontend.

The calculated value works, but still not as easy as 'region.text' or something like that.

**Comment by andrewtelnov** [comment]
@swuecho We have a simple concept : {questionName} replace with question value. We may invent something better in the future, but currently it works this way.

Thank you,
Andrew

**Comment by swuecho** [comment]
Yes. most of the time is value, but for survey below. choice texts is shown instead of choice values.


https://plnkr.co/edit/IICVTaxLldzUHYy1?preview

```
 {
  pages: [
    {
      name: 'page1',
      elements: [
        {
          type: 'checkbox',
          name: 'programsParticipatedIn',
          title:
            'Please choose which of these programs, clubs, activities you have participated in:',
          description: 'Select all that apply.',
          hasOther: true,
          choices: [
            {
              value: '1',
              text: 'text 1',
            },
            {
              value: '2',
              text: 'text 2',
            },
            {
              value: '3',
              text: 'text 3',
            },
            {
              value: '4',
              text: 'text 4',
            },
          ],
        },
        {
          type: 'checkbox',
          name: 'question2',
          title: 'participated in {programsParticipatedIn}',
          choices: ['item1', 'item2', 'item3'],
        },
      ],
    },
  ],
};
```

currently, I think the calculated value approach is enough. Thanks.
