### ISSUE TITLE
How to validate file before uploading to server

### ISSUE THREAD

**Issue by somnath157** [surveyjs/survey-library#2680]
### Are you requesting a feature, reporting a bug or asking a question?
asking a question

### What is the current behavior?
i am trying to validate a file type using validators but the validator is not called after the file upload on server and server return with an error for unsupported file type.

### What is the expected behavior?
I want to validate file type and and show error message to user and API to upload file should not be called in this case.

#### Provide the test code and the tested page URL (if applicable)

JSON 
```
{
			"name": "document",
			"type": "file",
			"title": {
				"zh-cn": "6. 商业登记证",
				"zh-tw": "6. 商業登記證",
				"default": "6. Business registration certificate"
			},
			"maxSize": 10485760,
			"isRequired": true,
			"description": "{   \"type\": \"url\",   \"label\": {     \"default\": \"What does it look like?\",     \"zh-cn\": \"这个文件是什么？\",     \"zh-tw\": \"這個文件是什麼？\"   },   \"value\": \"/assets/images/sample_BR.jpg\" }",
			"acceptedTypes": ".pdf, .jpg, .png",
			"requiredErrorText": {
				"zh-cn": "请上传有效的公司商业登记证",
				"zh-tw": "請上傳有效的公司商業登記證",
				"default": "Please upload valid business registration certificate"
			},
			"allowImagesPreview": false,
			"descriptionLocation": "underInput",
			"validators": [{
				"type": "expression",
				"expression": "isJpgPngOrPdfFile({document}) == true",
				"text": "Invalid file format, please upload your document in png, jpeg or pdf format."
			}]
		}

Javascript code : 

Survey.FunctionFactory.Instance.register('isJpgPngOrPdfFile', this.isJpgPngOrPdfFile);

    isJpgPngOrPdfFile(documents) {
      console.log(typeof documents + ':' + documents);
      if (documents.length < 1) return false;

      var fileValue = documents[0];
      var checkFile = function(file) {
        return (
          !file ||
          !file.name ||
          file.name.toLowerCase().endsWith('.png') ||
          file.name.toLowerCase().endsWith('.jpg') ||
          file.name.toLowerCase().endsWith('.pdf') ||
          file.name.toLowerCase().endsWith('.jpeg')
        );
      };
      if (Array.isArray(fileValue)) {
        return fileValue.every(checkFile);
      }
      return checkFile(fileValue);
    }

async onFileUpload(s, options) {
if (options.files && options.files.length) {
  const file = options.files[0];
  try {
    const data: any = await this.authService.uploadFile(file.name, file, file.type);
    options.callback(
      'success',
      options.files.map((item: File) => {
        return {
          file: item,
          content: data.code
        };
      })
    );
    const aTags = document.querySelectorAll(`[href='${data.code}']`);
    if (aTags.length) {
      (aTags[0] as HTMLAnchorElement).href = data.documentUrl;
      (aTags[0] as HTMLAnchorElement).innerHTML = data.name;
      (aTags[0] as HTMLAnchorElement).target = '_blank';
    }
  } catch (e) {
   
  }
}
}


```

### Specify your

* surveyjs platform : angular
* surveyjs version: 1.1.19

**Comment by tsv2013** [comment]
You can do it in the `onFileUpload` handler:
```JS
function onFileUpload(s, options) {
if (options.files && options.files.length) {
  options.files // check files here
```

`options.files` is an array of https://developer.mozilla.org/en-US/docs/Web/API/File/File objects

You can check file size, type and so on

**Comment by somnath157** [comment]
But i also want to show message to user how can i do that here ?

**Comment by tsv2013** [comment]
You can call the `alert` or `confirm` methods - https://javascript.info/alert-prompt-confirm

**Comment by somnath157** [comment]
No that  is not the requirement I need to show a message on the field saying invalid file uploaded. 
i tried returning 
 ```
options.callback(
      'success',
      options.files.map((item: File) => {
        return {
          file: item,
        };
      })
    );
```
from catch phrase in this i see the error message but file is also saved.

**Comment by tsv2013** [comment]
It's too late to validate files after they have been uploaded

**Comment by tsv2013** [comment]
You can use the [acceptedTypes](https://surveyjs.io/Documentation/Library?id=questionfilemodel#acceptedTypes) property to set what kind of files use can select

**Comment by tsv2013** [comment]
You can validate question content on event as shown in this example - https://surveyjs.io/Examples/Library?id=validators-event&platform=jQuery&theme=modern

**Comment by somnath157** [comment]
Already using acceptedTypes  but getting cases of user still uploading other types. QA

**Comment by somnath157** [comment]
My form is quite big with multiple steps and i want to validate the file while uploading is there any way to do this?

**Comment by tsv2013** [comment]
You can validate in the `onUploadFiles` event handler
```js
survey
    .onUploadFiles
    .add(function (survey, options) {
        var formData = new FormData();

        if(options.files[0].name.indexOf("w") > -1) {
            options.question.addError(new Survey.CustomError("My Error")); // show an error in the question
            options.callback("error");
            return;
        }
        options.callback("success", "uploadResult");

    });
```

**Comment by somnath157** [comment]
Getting error while using  addError method 
` TypeError: Cannot read property 'addError' of undefined`

am i doing anything wrong here

` Survey.SurveyNG.render(this.surveyElement.nativeElement, {
      model: this.survey,
      onValidateQuestion: this.surveyValidateQuestion,
      onUploadFiles: (s, options) => this.onFileUpload(s, options),
      onDownloadFile: (s, options) => this.onFileDownload(s, options)
    });

   async onFileUpload(s, options) {
    if (options.files && options.files.length) {
      const file = options.files[0];
      if(true) {
      options.question.addError(new Survey.CustomError("My Error")); // show an error in the question
      options.callback("error");
      return;
      }
      try {
        const data: any = await this.authService.uploadFile(file.name, file, file.type);
        options.callback(
          'success',
          options.files.map((item: File) => {
            return {
              file: item,
              content: data.code
            };
          })
        );
        const aTags = document.querySelectorAll(`[href='${data.code}']`);
        if (aTags.length) {
          (aTags[0] as HTMLAnchorElement).href = data.documentUrl;
          (aTags[0] as HTMLAnchorElement).innerHTML = data.name;
          (aTags[0] as HTMLAnchorElement).target = '_blank';
        }
      } catch (e) {
        options.question.addError(new Survey.CustomError("My Error")); // show an error in the question
        options.callback("error");
        return;
      }
    }
  }
    `

**Comment by tsv2013** [comment]
Here is the minimal working plunker sample - https://plnkr.co/edit/8DSqU2scJ32DXXGP

**Comment by somnath157** [comment]
Thanks, it worked i upgraded my survey-angular version to 1.8.32
