### ISSUE TITLE
Usage of onCompleting and onComplete events

### ISSUE THREAD

**Issue by doongle** [surveyjs/survey-library#2683]
### Question
I'd like to use onCompleting or onComplete event to save survey to database.
And then depending on the response from the DB, display different completedHtml message.

I tried "completedHtmlOnCondition in surveyJSON like
  ``` 
 "completedHtmlOnCondition": [
    {
     "expression": "{result} = 'ok'",
     "html": "<h1>Thank you</h1>"
    },
    {
     "expression": "{result} != 'ok'",
     "html": "<h1>Error</h1>"
    }
 ]
```
How do I do that?

**Comment by andrewtelnov** [comment]
@doongle You can't use `completedHtmlOnCondition` for this purpose. Please review this [documentation](https://surveyjs.io/Documentation/Library#storeresults-owndatabase). It shows how to deal with your scenario.
If you want to make it completely custom, then I suggest hide survey div `onComple` event and show whatever you want based on result from your server.

Thank you,
Andrew

**Comment by doongle** [comment]
Thank you for your reply.
I chose to hide survey div and use custom html.
I appreciate your help.
