### ISSUE TITLE
[Question] Is it support answer based changeable questions?

### ISSUE THREAD

**Issue by 024N** [surveyjs/survey-library#2689]
Hi,
According to previous question, I want to ask different questions.
I can make structure in the same page but I try to do it in different pages.
Example;
I need 2 question page and first question and first page;
Which country? Germany or France
##############
According to previous answer, second question and second page;
Which Cities?
If Germany is chosen in first page; I only want to show: Berlin or Hamburg
If France is chosen in first page; I only want to show: Paris, Lyon

I tried this structure but I couldn't create logic. Is it support that logic?
pages[
{questions....}
{questions....}
]

**Comment by swuecho** [comment]
https://surveyjs.io/Examples/Library?id=condition-kids&platform=jQuery&theme=modern#content-js

You could split the second question about city to two similar question 

visibleIf: {country} = 'Germany' for question with answer 'Berlin or Hamburg'
visibleIf: {country} = 'France' for question with answer 'Paris, Lyon'

If there are too many choices, you could setup an restapi, use country as input and return the cities. the example is exactly what you are looking for.

https://surveyjs.io/Examples/Library?id=questiontype-dropdownrestfull&platform=jQuery&theme=modern

**Comment by swuecho** [comment]
not sure there are approach to set condition on individual choice. 

something like: 

1. France  visibleIf: {country} = 'France' 

but if this is you are looking for, you could use custom function .

https://plnkr.co/edit/46CXveGYjmISKUlD?preview

**Comment by andrewtelnov** [comment]
@swuecho @024N Please review the following examples: https://surveyjs.io/Examples/Library?id=condition-itemValueVisibleIf and https://surveyjs.io/Examples/Library?id=condition-choicesVisibleIf

Thank you,
Andrew

**Comment by 024N** [comment]
I guess I couldn't explain it.
In one page, I can do that but I am trying to do it on 2 different pages.
After first page is completed, I want to show different question page according to first page answer.
I added basic example desing, Can you check it.
![1](https://user-images.githubusercontent.com/27887007/109708688-c6830a00-7bac-11eb-8a26-b8bcd42244cb.png)

**Comment by andrewtelnov** [comment]
@024N It doesn't matter where the question is located on the same page or on next pages or previous pages. We will update question visibility based on visibleIf expression.

Thank you,
Andrew

**Comment by 024N** [comment]
Yes, you are right. I found problem.
I used checkbox and I did visibleIf: "{Name2} = 'Ford'",
Problem was here, It should be array or visibleIf: "{Name2} contains 'Ford'"
Thank you for help.
