### ISSUE TITLE
[feature] make other value text not required.

### ISSUE THREAD

**Issue by swuecho** [surveyjs/survey-library#2690]
### What is the current behavior?

if 'hasOther:true', other text is required. 

### What is the expected behavior?

add 'otherItemRequired' option and default to 'True'. when value is 'False',  make the other text optional. 

why not add a choice 'other. otherText'  directly and do not set 'hasOther:true'?

when you want to make the choices random, except the 'other' choice should always be the last one.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/4EYh4RiNkdGJjujE

**Comment by andrewtelnov** [comment]
@swuecho The most users needs to have descriptions for other is requried and your case could be easily solved by making "Other a typical value and adding a comment question that visible on selecting "Other" value.
Here is the [example](https://plnkr.co/edit/in5twVht6JRxtYkl).
The only issue - random choices. 
You can still solve this issue by adding a custom code that will make sure that other at the end of the list, by making your own sorting.

Thank you,
Andrew

**Comment by swuecho** [comment]
That works. 

Since order is so important. possible to accept function as choicesOrder parameter?
