### ISSUE TITLE
SurveyJS - Dynamic Matrix logics independent of column value

### ISSUE THREAD

**Issue by Nils-DE** [surveyjs/survey-library#2694]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question / requesting a feature

### What is the current behavior?
When using the dynamic matrix element all kind of logics and conditions are connected to the first column index ([0]), which is then valid for all columns. (See screenshot)
![DynamicMatrixIssue](https://user-images.githubusercontent.com/52461442/109667469-7423f800-7b70-11eb-8215-e036fe7532ab.png)

### What is the expected behavior?
Dynamification of the column index when it comes to visible/enable/required if logics.
The fields "Please provide the name of the legal fact" and "Please provide the effect of the legal fact" in column 2 should only be visible/mandatory, when in column 2 the field "Are Legal Facts involved?" is "Yes", but as the logics' only working when referring to Index 0 ({MX_ResultQuestion3a[0].LegalFact}) it is always fixed for the whole table.

### How would you reproduce the current behavior (if this is a bug)?
1. Fill out all mandatory fields
2. Set "{MX_ResultQuestion3a[0].LegalFact}"=Yes
3. Fill out Last two fields
4. Add column
5. Set {MX_ResultQuestion3a[1].LegalFact} = No
6. Fields in column 2 still mandatory/visible

#### Provide the test code and the tested page URL (if applicable)

Test code

{
       "type": "matrixdynamic",
       "name": "MX_ResultQuestion3a",
       "title": "Please provide the stages of the generalized structure",
       "isRequired": true,
       "columns": [
        {
         "name": "Description",
         "title": "Stage description",
         "cellType": "comment",
         "isRequired": true
        },
        {
         "name": "LegalAct",
         "title": "Point out the involved leagal acts",
         "cellType": "comment",
         "isRequired": true
        },
        {
         "name": "LegalFact",
         "title": "Are Legal Facts involved?",
         "cellType": "dropdown",
         "isRequired": true,
         "choices": [
          {
           "value": "True",
           "text": "Yes"
          },
          {
           "value": "NotTrue",
           "text": "No"
          }
         ]
        },
        {
         "name": "Name",
         "title": "Please provide the name of the legal fact",
         "cellType": "text",
         "isRequired": true,
         **"visibleIf": "{MX_ResultQuestion3a[0].LegalFact} = 'True'"**
        },
        {
         "name": "Effect",
         "title": "Please provide the effect of the legal fact",
         "cellType": "comment",
         "isRequired": true,
         **"visibleIf": "{MX_ResultQuestion3a[0].LegalFact} = 'True'"**
        }
       ],
       "columnLayout": "vertical",
       "rowCount": 1,
       "minRowCount": 1
      },

your_code_here

```

### Specify your

* browser: Chrome
* browser version: Version 88.0.4324.150 (64-Bit)

**Comment by andrewtelnov** [comment]
@Nils-DE I guess you need to use: "visibleIf": "{row.LegalFact} = 'True'", it will get the cell value from the current row.

Thank you,
Andrew

**Comment by Nils-DE** [comment]
@andrewtelnov It worked perfectly, thank you so much!
