### ISSUE TITLE
Simple custom component doesn't work in matrixdynamic

### ISSUE THREAD

**Issue by fullergalway** [surveyjs/survey-library#2695]
A simple custom dropdown component (like country) in matrixdynamic produces no value:

https://plnkr.co/edit/znxEncR0c3bmrjm5?preview

**Comment by fullergalway** [comment]
Works if I add this into my custom component:

```javascript
onLoaded(question) {
      question.questionWrapper.valueChangedCallback = function(){
          question.value = question.questionWrapper.value;
      }
    }
```

**Comment by andrewtelnov** [comment]
@fullergalway I will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@fullergalway I have fixed it by the commit above.

Thank you,
Andrew
