### ISSUE TITLE
Error on build with VueJS: Individual declarations in merged declaration 'ActionBarItem' must be all exported or all local.

### ISSUE THREAD

**Issue by mheers** [surveyjs/survey-library#2701]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Using VueJS 2.6.12 with `yarn serve` or `yarn build` leads to an error (see screenshot).
![Screenshot from 2021-03-05 14-31-04](https://user-images.githubusercontent.com/17021898/110122298-bbec8e80-7dbf-11eb-879a-8b3a57ab9e00.png)

It seems as if `ActionBarItem` is declared twice in the build `node_modules/survey-vue/survey.vue.d.ts`

### What is the expected behavior?
Compile without errors.

### How would you reproduce the current behavior (if this is a bug)?
Starting from v1.8.29 until present v1.8.34 using VueJS 2.6.12 with `yarn serve` or `yarn build`.

### Specify your

* browser: -
* browser version: -
* surveyjs platform (angular or react or jquery or knockout or vue): VueJS 2.6.12
* surveyjs version: v1.8.29 until present v1.8.34 (works with v1.8.28 so I guess it is related to https://github.com/surveyjs/survey-library/commit/68bff049383c39138f65ab380ef73c86e81a2d94 )

**Comment by tsv2013** [comment]
Fix will be available in the nearest minor update.

**Comment by mheers** [comment]
Thank you very much for the fix. I can confirm that it now compiles flawlessly :+1:
