### ISSUE TITLE
Single choice hasNone option

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#2706]
### Are you requesting a feature, reporting a bug or asking a question?

Feature

### What is the current behavior?

Single choice question (dropdown / radio) doesn't have a `none of the above` option. 

### What is the expected behavior?

In market research questions are often mandatory but still want to have an `escape` option to prevent participants just clicking next. Such a `none` should work the same for single choice as it does for multiple choice; always be at the bottom and not randomized.

**Comment by swuecho** [comment]
related https://github.com/surveyjs/survey-library/issues/2690

**Comment by andrewtelnov** [comment]
@SamMousa @swuecho I believe that we need to create an event, that will allow you to control the order of visible choices items.
In this case it will solve the issue with "other", 'none" and maybe other items.
We need to discuss it.

Thank you,
Andrew

**Comment by swuecho** [comment]
That will be terrific!  This feature will solve all the choices order problem.

**Comment by SamMousa** [comment]
I don't think it solves the problem. The proposed thing can already be done in preprocessing.. Just disable randomization and do it yourself with the exceptions..

The issue is we need a non programming option for end users. I'd prefer not to implement special values attached to special behavior..

**Comment by andrewtelnov** [comment]
> I don't think it solves the problem. The proposed thing can already be done in preprocessing.. Just disable randomization and do it yourself with the exceptions..

Well, this is correct. In fact, you can look if there is "none" or "other" value and correct the visible choices on your side. Is it possible? I did not check it yet ;-)
We are library and it is ok to customize it and extend and change the functionality. Our task is to make sure that we implement functionality that needs the most developers out of the box and make it relatively easy for developers to implement what they need.

Andrew

**Comment by SamMousa** [comment]
I agree, this is in my opinion common functionality and it is already in the code base for multiple choice. I created the issue because I think it would be better in the library, not because I can't work around it.
If you change behavior for none option, ever, then my question type will be out of date, essentially I'll be solving a problem you already solved.

**Comment by andrewtelnov** [comment]
@SamMousa Yes, I guess we can move "none" functionality into "selectbase" class. Let me check it later.
It would not solve @swuecho issue in this case.

Thank you,
Andrew

**Comment by swuecho** [comment]
@andrewtelnov  Thanks for considering it. 

A general approach to be able to custom ordering will help a lot. 

for example, a client want to recycle the choices except the first and last one. I could take control the whole question and adjust the order, but too heavy, control the ordering is enough. This is certainly beyond the scope of this issue.

**Comment by andrewtelnov** [comment]
@SamMousa Implemented.

Thank you,
Andrew

**Comment by SamMousa** [comment]
I think this can be closed!
