### ISSUE TITLE
OnprogressText Event callback causing react infinite loop

### ISSUE THREAD

**Issue by khandg** [surveyjs/survey-library#2716]
### Are you requesting a feature, reporting a bug or asking a question?
A Bug

### What is the current behavior?
Callback function causing react infinite loop https://reactjs.org/docs/error-decoder.html/?invariant=185

### What is the expected behavior?
Should work without exception

### How would you reproduce the current behavior (if this is a bug)?
https://ppnutq.digitalgravity.ae/ It is reproducible here.
User: ppnutq
Pass: PPnutq

dist/bundle.js contains the code.
Already output the console logs for further debugging

thanks

**Comment by tsv2013** [comment]
If you share a minimal reproducible sample (https://stackoverflow.com/help/minimal-reproducible-example) we could take a look
