### ISSUE TITLE
[BUG] Vue: Call method on survey break survey navigation after version 1.8.9

### ISSUE THREAD

**Issue by swuecho** [surveyjs/survey-library#2723]
### What is the current behavior?

https://codesandbox.io/s/surveyjs-vue-forked-bdfmx 

select survey-vue 1.8.36

after survey landing, go to next page, then press the 'prev page' button. nothing happens.

![image](https://user-images.githubusercontent.com/666683/111793819-994e8f80-8900-11eb-9639-03c2296d7969.png)
### What is the expected behavior?

in version before 1.8.9. 'prev page' button works, but not after. 

#### Provide the test code and the tested page URL (if applicable)

survey template in `SurveyComponent.vue`

```
<template>
  <div>
    <survey :survey="survey" />
    <div id="QuestionInfo">
      {{ this.survey.getCurrentPageQuestions() }}
    </div>
  </div>
</template>
```

related: https://github.com/surveyjs/survey-library/issues/2599

**Comment by andrewtelnov** [comment]
@swuecho I could not understand what is going on. `this.survey.getCurrentPageQuestions()` requested the currentPage and after that vue stops react on changing "currentPage".
As a work-around, you can do the following:
Modify the template:
```js
<template>
  <div>
    <survey :survey="survey" />
    <div id="QuestionInfo">
      {{ this.questions }}
    </div>
  </div>
</template>
```
Modify the code:
```js
    const survey = new Survey.Model(json);
    this.questions = survey.getCurrentPageQuestions();
    survey.onCurrentPageChanged.add((sender, options) => {
      this.questions = survey.getCurrentPageQuestions();
    });

    return {
      survey: survey,
      questions: this.questions,
    };
```
Thank you,
Andrew

**Comment by swuecho** [comment]
Thanks @andrewtelnov ! This work around works.
