### ISSUE TITLE
breaking change in my custom function after v1.8.26

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#2727]
With my custom function (called _getSelectedChoiceProp_) I can retrieve a property of the originalItem attached to the the selected choice of a target dropdown question ([you help me we this some time ago](https://github.com/surveyjs/survey-library/issues/2185))

https://plnkr.co/edit/k1f0oubNzO6oxqRd 

After [this internal change](https://github.com/surveyjs/survey-library/issues/2615) _getSelectedChoiceProp_ doesn't work anymore with preloaded data because `targetQuestion.visibileChoices` remain undefined even after the `targetQuestion.value` is set. Change survesJS version in the plunker to  v1.8.26 to see the different behaviour.

Is there an alternative way to reach the selected originalItem or to run the custom function when visibileChoices get populated? 
thank you a lot for any help

**Comment by andrewtelnov** [comment]
@masciugo visible choices are not loaded into the first dropdown yet.
Yes a fast fix, you can `return this.question.value` in your `getSelectedChoiceProp` function. Here is [the updated example](https://plnkr.co/edit/QowiOMZZWaXyklZk).

Thank you,
Andrew

**Comment by masciugo** [comment]
OK. So this means, very roughly, that visibileChoices is populated only "if necessary"? thank you

**Comment by andrewtelnov** [comment]
@masciugo It is hard to say. For some reason, `visibleChoices` were ready at the time function access to them and now they are not. I do not remember that we change something in this regard. We introduced [lazy-rendering](https://surveyjs.io/Examples/Library?id=survey-lazy), but it is turn-off by default.

Thank you,
Andrew

**Comment by masciugo** [comment]
no prob. I'll just keep it monitored. Thank a lot
