### ISSUE TITLE
Invalid loops in matrix dynamic/dropdown events

### ISSUE THREAD

**Issue by peteruithoven** [surveyjs/survey-library#2737]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
`getQuestion` functions have invalid for loop conditions. Causing issues where more than available columns are checked and causing errors. 
The condition in the following for loop is just the length of an array (`self.columns.length`), instead of something like `i<self.columns.length`. 
- https://github.com/surveyjs/survey-library/blob/master/src/question_matrixdropdownbase.ts#L3037
- https://github.com/surveyjs/survey-library/blob/master/src/question_matrixdropdownbase.ts#L3072

### What is the expected behavior?
For loops have a valid condition.

### How would you reproduce the current behavior (if this is a bug)?
We noticed this when we created the following situation:
See: https://plnkr.co/edit/PKywNO0UKjHPBVNF
1. Create a matrixdynamic with a dropdown column, with `hasOther`. 
2. Add a `onMatrixCellValueChanged` handler, where you use `options.getCellQuestion`
3. Select Other in dropdown
4. Start typing description in comment field

This triggers a `TypeError: self.columns[i] is undefined` per typed character. 

This because the column name doesn't exist but the for loops keeps running untill it into an error because it requests props from columns that don't exist. 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/PKywNO0UKjHPBVNF

### Specify your

* browser: Firefox / Chrome
* browser version: Firefox: 86.0, Chrome: 89.0.4389.82
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: Above test is using 1.8.20, but the invalid for loops are currently on master.

**Comment by andrewtelnov** [comment]
@peteruithoven Thank you for reporting the issue. I have fixed it.

Thank you,
Andrew
SurveyJS Team

**Comment by peteruithoven** [comment]
Thanks for the quick response
