### ISSUE TITLE
Remove has other item property from ranking's property grid

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-library#2738]
![image](https://user-images.githubusercontent.com/30930391/112147775-225e1300-8bee-11eb-8760-425b9c29aa7e.png)

Also some strange behavior with other item adorner in ranking question:
![image](https://user-images.githubusercontent.com/30930391/112147853-386bd380-8bee-11eb-8e44-31e93b80d331.png)

**Comment by dmitrykurmanov** [comment]
related to https://github.com/surveyjs/survey-library/issues/2799
