### ISSUE TITLE
key duplication errors does not come up in matrix/panel dynamic

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#2742]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

when duplicated keys are present surveyJS correctly does not save the data and focus on the question with the error but the error is not shown

### What is the expected behavior?

see duplicated key errors

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/uOUHnWVU8EalJWnl

**Comment by andrewtelnov** [comment]
@masciugo I have fixed it by the commit above.

Thank you,
Andrew
