### ISSUE TITLE
(Weighted) Random Question Sets

### ISSUE THREAD

**Issue by misamura** [surveyjs/survey-library#275]
Hello all,

surveyjs is a great tool!

I'd like to propose a feature request: "Random Question Sets".

Instead of always showing the same questions in the same order, questions are chosen randomly from a set (or container) of predefined questions.

A subset off all questions within that set is being asked, and each question is weighted, so that a question with a higher weight (probability) is drawn with a higher chance.

Random questions would be an extension of the `pages` element, and each question is extended by a `probability` element.

Something like (just a first draft, really):
```javascript
{
 pages: [
  {
   name: "page1",
   useRandomQuestions: true,  // false: normal behaviour; true: generate a randomized subset of all questions for this page
   numberOfQuestionsToPose: 2,  // just ask a subset of all questions from this page (in this case 2 out of 3 questions)
   questions: [
    {
     type: "comment",
     name: "question1",
     probability: 40
    },
    {
     type: "comment",
     name: "question2",
     probability: 20
    },
    {
     type: "radiogroup",
     probability: 60,
     choices: [
      {
       value: "1",
       text: "first item"
      },
      {
       value: "2",
       text: "second item"
      },
      {
       value: "3",
       text: "third item"
      }
     ],
     name: "question3"
    }
   ]
  }
 ]
}```

What do You think?

All the best,
H.

**Comment by vohrahul** [comment]
@misamura , @andrewtelnov +1 on `numberOfQuestionsToPose` feature. Can we do it with custom properties?

**Comment by andrewtelnov** [comment]
Here is [the example](https://plnkr.co/edit/4wfCUUgnNYRaQoPB) that does what you need.

Thank you,
Andrew
