### ISSUE TITLE
Version 1.8.38 breaks survey-angular package

### ISSUE THREAD

**Issue by MrKrabat** [surveyjs/survey-library#2755]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
```
Error: node_modules/survey-angular/survey.angular.d.ts:9291:26 - error TS2307: Cannot find module 'survey-core' or its corresponding type declarations.

9291     get survey(): import("survey-core").ISurvey;
```

### What is the expected behavior?
No crash.

### How would you reproduce the current behavior (if this is a bug)?
Use survey-angular 1.8.38

### Specify your

* browser: Chrome
* browser version: 89
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: 1.8.38

**Comment by tsv2013** [comment]
I've fixed the issue. Fix will be available in the nearest minor update.
