### ISSUE TITLE
Support Vue 3 in SurveyJS library

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-library#2756]
We need to support Vue 3 in our products. But we need to check whether survey-vue library will be compatible with Vue 2.X\

migrating tool: https://github.com/surveyjs/survey-library/issues/2756#issuecomment-987624404

**Comment by bapaynter** [comment]
This currently does not work with Vue 3.

**Comment by outerstorm** [comment]
@tsv2013 is there any ETA on supporting Vue 3?

**Comment by opiispanen** [comment]
Has anyone tried it with Vue 3.1 and compatibility mode??

**Comment by tsv2013** [comment]
@outerstorm right now - no. the team is busy with SurveyJS Creator V2

**Comment by timritzer** [comment]
This is a big deal to us as well, and we were seriously considering purchasing this product.
Can we at least get some roadmap/timelines? Our app is all vue3 and mixing the two is going to be a mess.

**Comment by moonose** [comment]
Any schedule for this upgrade? Our company is going to purchase this product.

**Comment by outerstorm** [comment]
@moonose - We have yet to hear any details on a schedule and are in the same position - our company will be purchasing the product and implementing in a Vue3 application.  Since we haven't heard anything yet we moved forward with wrapping the Knockout library with a Vue3 wrapper of our own.  Not sure if that approach would work for you, but something to consider.

**Comment by andrewtelnov** [comment]
Hello guys,
Let us to find out, how many changes is required for supporting V3 and is it possible to support V2&V3 at the same time. We will comeback in several days. 

Thank you,
Andrew

**Comment by moonose** [comment]
@outerstorm , thanks for your info. We think SurveyJS is set of awesome products and creator seems works fine under vue3 env. That's why we are planning to purchase this product. But unfortunately, current library does not support vue3. We prefer to get a version supporting vue3 officially. So, I wait for a while to see the progress.

**Comment by dmitrykurmanov** [comment]
I think, that for now, we can't easily change the Vue version from 2 to 3. We are using `vue-class-component` for example and I can't guarantee that it will work in Vue3 and so on.

I think that it is would be reasonable not to have two versions of Vue in the SurveyJS project. As I understand Vue3 is not the default version. It is @next version and even the documentation site opens with Vue2 by default. 

Does anyone have information about Vue3 official release and when it becomes a standard? @bapaynter @outerstorm @opiispanen @timritzer @moonose 

When Vue3 will become a standard I think that we abandon Vue2 support and converted `survey-library` to V3 and then probably implemented creatorV2 for Vue3 too.

**Comment by moonose** [comment]
v3 has already officially released. together with cli, router, vuex, eslint and other core components, v3 has had its own ecosystem now. It is not a new thing (latest version is 3.2.4) and it is mature with clear official documentation (https://v3.vuejs.org/). But I think both v2 and v3 will coexist in a while, because the two are important milestones with different architectures. 

for the new projects,  we have enough reasons to choose v3, but for v2 projects, it is really a hard decision to migrate.
Hope to see a release of v3 for survey.js soon.

**Comment by tsv2013** [comment]
>v3 has already officially released

Since the differences between Vue2 and Vue3 are dramatical and Vue3 package still has the @next tag, we prefer to wait until Vue3 will be the default package installed via the `npm i vue` or similar yarn command.

**Comment by kouhunzhe** [comment]
It is estimated that Vue will not remove the @ next tag in the later stage, because the UI framework based on vue3 has acquiesced vue@next In fact, what I want to see most is the creator of vue3

**Comment by jpgilchrist** [comment]
This is also critical for my company: Testimonial Tree. We are in the midst of building out a product and are the point where we were hoping to use survey js, but this is a bit of a blocker. 

I've read through some various tickets and the priorities are a bit confusing. It seems like you are working on: 
* survey creator (but this is only for react/knockout) is there plans for a vue2/3 instantiation of this?
* surveyjs-library to cleanup and remove code duplication
* adding angular support to I assume surveyjs-library
* then you'll revisit this vue3 situation

I understand your point about vue3 being on the @next branch. However, most "frameworks" and "libraries" are already using vue3 as their default. For instance, we are a use of the https://quasar.dev project and their default command `quasar create` uses vue3. This is also the case with vue-cli and others. All documentation for vue and related ecosystems default to vue3 with an option to look at vue2 if need be. So, I'm not sure that "waiting" till vue3 is not on the @next branch is a good idea. 

I think this should be a higher priority, than it currently is. That being said, I totally understand being limited on human resources. 

I'd appreciate any update and/or thoughts as this hasn't been updated in about a month.

**Comment by andrewtelnov** [comment]
@outerstorm I understand your concern. I wish I can deliver you good news. Unfortunately, I can't. We have 7 developers on board, including me. We are busy with the following tasks right now:
Creator V2 - at the current stage, except working on adaptivity, we are mostly testing, fixing bugs and add e2e tests
Improve our rendering - reuse our own components - remove custom code/rendering, render better html. Add html snapshots tests.

Next tasks in the queue:
Better support for accessibility and add checks for accessibility support into our CI
Angular rendering for SurveyJS Library
Creator V2 angular version
Creator V2 vue2 version
Here we believe we can go with vue3 (library and creator). We will review vue3 situation one more time before working on creator for vue2.

The good news, after finishing with current two tasks, other tasks should be done fast. We have more than 85% of our code as platform independent and less than 15% is rendering, platform specific. We have many e2e tests for Creator and Library and they are running for all platforms. We are working on html snapshot tests, making sure all platforms generate the same html after removing platform specific tags and sorting attributes.  All we need is to write code for angular and vue3 and make sure all tests are running for new platforms as well.

Thank you,
Andrew

**Comment by jpgilchrist** [comment]
@andrewtelnov thanks for the info. 

Just for reference this could help in the short term?


https://www.npmjs.com/package/@vue/compat

**Comment by dougalg** [comment]
A good path to making this work might be to use (Vue-Demi)[https://github.com/vueuse/vue-demi].

**Comment by luukdv** [comment]
> we prefer to wait until Vue3 will be the default package

Update: this will be the case as of February 7.

**Comment by tsv2013** [comment]
@luukdv Good news :-)

**Comment by dmitrykurmanov** [comment]
> A good path to making this work might be to use [Vue-Demi](https://github.com/vueuse/vue-demi). Thanks for the good work.

because we are using so many additional features like `vue-class-component` and typescript I think we can't just use this library for migrating. But we will try. Thanks for sharing

**Comment by dmitrykurmanov** [comment]
https://blog.vuejs.org/posts/vue-3-as-the-new-default.html

**Comment by dougalg** [comment]
> because we are using so many additional features like vue-class-component and typescript I think we can't just use this library for migrating. But we will try.

Vue-demi works well with TS, but class component syntax is strongly discouraged moving forward in Vue last I read, and it is recommended to adopt the standard object syntax or the new composition api.

**Comment by dmitrykurmanov** [comment]
Hello, 
you are right we've made the mvp and it was successful. We proofed the concept. This enhancement is in our todo list.

We are working on native Angular implementation and then we are going to start work for Vue3 support.

Unfortunately, we can't give a concrete estimations. But we are trying to do our best to make it happen as soon as possible.

Thanks,
Dmitry
SurveyJS team

**Comment by jag2kn** [comment]
Hi, excellent news @dmitrykurmanov .

This MVP was uploaded in a commit?

**Comment by uhelliton-megawhat** [comment]
> 



> Reference i

https://github.com/surveyjs/survey-library/issues/2756#issuecomment-1218261339

**Comment by lucavenir** [comment]
Also my team is looking forward for this library being supported by Vue3. This is critical to our open source project.

**Comment by andrewtelnov** [comment]
Hi all,
Vue3 is still on our radar. Our plans regarding JS framework don't change. We have just finished with [Angular rendering](https://github.com/surveyjs/survey-library/tree/master/packages/survey-angular-ui) and started to work on Creator V2 for Angular. After that we are going to work on supporting Vue3 for rendering and then Creator V2 for Vue3.

Thank you,
Andrew

**Comment by lucavenir** [comment]
Hi @andrewtelnov! Thank you for your quick reply.
As a last question: what would be the best workaround this, if I'm using Vue3 and I want to use SurveyJS in any form, somehow?

Thanks in advance,
LV

**Comment by Zoushen6** [comment]
it will be perfect whether suport vue3,please

**Comment by Zoushen6** [comment]
It would be perfect to support vue3.

**Comment by JaneGaid** [comment]
Hello @lucavenir,
For now, you may integrate a knockout Survey Runner to your Vue3 application.  
```
<template>  
  <div id="survey" />
</template>

<script>
import "survey-core/defaultV2.min.css";
import { StylesManager } from "survey-core";
import {Survey} from 'survey-knockout-ui';

StylesManager.applyTheme("defaultV2");

const surveyJson = {
  elements: [{
    name: "FirstName",
    title: "Enter your first name:",
    type: "text"
  }, {
    name: "LastName",
    title: "Enter your last name:",
    type: "text"
  }]
};

export default {
  mounted() {   
    const survey = new Survey(surveyJson);
    survey.render("survey");
  }
};
</script>
```
Check the following example: [SurveyJSKnockoutVue.zip](https://github.com/surveyjs/survey-library/files/9820167/SurveyJSKnockoutVue.zip)

**Comment by Alfredoarnoldo** [comment]
> Hello @lucavenir, For now, you may integrate a knockout Survey Runner to your Vue3 application.
> 
> ```
> <template>  
>   <div id="survey" />
> </template>
> 
> <script>
> import "survey-core/defaultV2.min.css";
> import { StylesManager } from "survey-core";
> import {Survey} from 'survey-knockout-ui';
> 
> StylesManager.applyTheme("defaultV2");
> 
> const surveyJson = {
>   elements: [{
>     name: "FirstName",
>     title: "Enter your first name:",
>     type: "text"
>   }, {
>     name: "LastName",
>     title: "Enter your last name:",
>     type: "text"
>   }]
> };
> 
> export default {
>   mounted() {   
>     const survey = new Survey(surveyJson);
>     survey.render("survey");
>   }
> };
> </script>
> ```
> 
> Check the following example: [SurveyJSKnockoutVue.zip](https://github.com/surveyjs/survey-library/files/9820167/SurveyJSKnockoutVue.zip)

Do you have an example of this kind of workaround with the survey creator & vue 3 please? Thank you.

**Comment by volhaliferovich** [comment]
Do you have any updates on this? Can I create a model using SurveyJS and vue3?

**Comment by T-Zoomer** [comment]
I would really appreciate an update on this or an indication on the timeline. Vue 3 support is all thats holding me back from buying a license.

**Comment by xxxKOTxxx** [comment]
> Do you have any updates on this? Can I create a model using SurveyJS and vue3?

Some update [here](https://github.com/surveyjs/survey-library/issues/3473#issuecomment-1573376723)

**Comment by andrewtelnov** [comment]
@dougalg @jag2kn @outerstorm @opiispanen @bapaynter @timritzer @moonose @jlhejs @jpgilchrist @luukdv @jpgilchrist @xxxKOTxxx @volhaliferovich @SanchezPepe @Alfredoarnoldo @Zoushen6 @lucavenir 
We have released SurveyJS Library for vue3 yesterday. Here is [the npm link](https://www.npmjs.com/package/survey-vue3-ui).
We don't have documentation for it yet and we don't include vue3 into our examples. They will come later.
For now you can check examples on [stackblitz](https://stackblitz.com/edit/vitejs-vite-6yb7se) and [CodeSandbox](https://codesandbox.io/s/quizzical-stallman-st9ljf?file=/src/App.vue).

We added vue3 into our CI. All markup tests, [functional tests](https://dev.azure.com/SurveyJS/SurveyJS%20Integration%20Tests/_build/results?buildId=80288&view=results) and [visual regression](https://dev.azure.com/SurveyJS/SurveyJS%20Integration%20Tests/_build/results?buildId=80289&view=results) tests are running for Vue3 from now.

Thank you,
Andrew
SurveyJS Team

**Comment by shuiqingliu** [comment]
> 
I tried to integrate the CodeSandbox example into a Vue 3 + Vite + TypeScript project, but the survey content is not displayed, and I get an "isCustomElement" error.

**Comment by dmitrykurmanov** [comment]
> > 
> 
> I tried to integrate the CodeSandbox example into a Vue 3 + Vite + TypeScript project, but the survey content is not displayed, and I get an "isCustomElement"(config vue plugin to fix) error.

@shuiqingliu 
CodeSandbox sometimes add additional hidden config to the app. Could you please try [the stackblitz version](https://stackblitz.com/edit/vitejs-vite-6yb7se?file=package.json) instead?

Thank you,
Dmitry
SurveyJS Team

**Comment by dk981234** [comment]
@shuiqingliu 
Hello,

Did you inserted these lines in your main.ts file?
`import {  surveyPlugin } from "survey-vue3-ui"`
`...`
`app.use(surveyPlugin);`
Thanks,
Dmitry
SurveyJS Team

**Comment by shuiqingliu** [comment]
@dk981234 @dmitrykurmanov That's wonderful. It worked. Thank you very much. I am missing the main.ts config:
```typescript
import {  surveyPlugin } from "survey-vue3-ui"
import 'survey-core/defaultV2.css';
```

**Comment by npthao1312** [comment]
This is probably a simple question. But I can't seem to get the form rendering in the lifecycle. This is my code. I have config it properly (it can still render if I just put it outside of the lifecycle hook). 

```
<template>
  <q-layout v-cloak>
    <q-page class="bg-info">
      <div class="row">
        <div v-if="survey">
          <survey :model="survey"></survey>
        </div>
      </div>
    </q-page>
  </q-layout>
</template>

<script setup>
import { reactive, toRefs, onMounted } from "vue";
import { Model } from "survey-core";
import { themeJson } from "../data/survey_theme";
import { SurveyModel } from 'survey-core';
const defaultJson = {}

onMounted(() => {
  const survey = new SurveyModel(defaultJson);
  survey.applyTheme(themeJson);
  survey.onComplete.add((sender, options) => {
    console.log(JSON.stringify(sender.data, null, 3));
  });
  console.log("survey ", survey);
});
</script>
```

**Comment by dk981234** [comment]
@npthao1312
Hello,
I think, you need to define survey variable outside of lifecycle hook:
let survey = undefined;
…
onMounted(()=>{ survey = new SurveyModel(json); }

Thanks,
Dmitry
SurveyJS Team

**Comment by npthao1312** [comment]
@dk981234 Thank you, that took me a bit too long than it's supposed to be. Here is a working version for everybody else.  
```
<template>
  <q-layout v-cloak>
    <q-page class="bg-info">
      <button @click="toggleForm">Toggle Form</button>
      <div class="row">
        <div v-if="showForm">
          <SurveyComponent :model="survey" />
        </div>
      </div>
    </q-page>
  </q-layout>
</template>

<script setup>
import { ref, watch, onMounted } from "vue";
import { Model } from "survey-core";
import { themeJson } from "../data/survey_theme";
import { json } from '../data/defaultWorkflowForm';

let survey = undefined;
// Use a ref to control the visibility of the form
const showForm = ref(false);

// Watch for changes in the `showForm` value and react accordingly
watch(showForm, (newValue) => {
  if (newValue === true) {
    survey = new Model(json);
    survey.applyTheme(themeJson);
    survey.onComplete.add((sender, options) => {
      console.log(JSON.stringify(sender.data, null, 3));
    });

  }
});

// Toggle the visibility of the form
const toggleForm = () => {
  showForm.value = !showForm.value;
};
</script>

```

**Comment by JaneSjs** [comment]
For the record: [SurveyJS Form Library demos](https://surveyjs.io/form-library/examples/implement-conditional-logic-to-change-question-visibility/reactjs) were updated and now include the Vue 3 option. Navigate to a target demo, click Edit in Codesandbox, activate a list of supported frameworks and select Vue3:

The [SurveyJS Form Library demos](https://surveyjs.io/form-library/examples/implement-conditional-logic-to-change-question-visibility/reactjs) have been recently updated and now feature the Vue 3 option as well. To access a specific demo for Vue 3, navigate to atarget demo and click on "Edit in Codesandbox." From the dropdown menu, select Vue 3.
![image](https://github.com/surveyjs/survey-library/assets/22372972/1e4499e8-2826-4284-83e5-6b0e9f5b278c)
