### ISSUE TITLE
Use VIDEO element instead of EMBED

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#2757]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
When an image question uses `contentMode === 'video'`, SurveyJS uses an `<embed>` tag.
In 2021 the video tag is well supported and the `<embed>` tag has been deprecated for a while.

I only noticed this behavior when looking into adding a feature for blocking the survey until a movie has finished playing.

### What is the expected behavior?
I'd expect SurveyJS to use a video tag.

For illustration, this is the template for knockout:
```html
<script type="text/html" id="survey-question-image">
  <div data-bind="css: question.koCss().root">
    <!-- ko if: question.contentMode === "image" -->
    <img data-bind="css: question.koCss().image, attr: { src: $data.imageLink, width: question.imageWidth ? question.imageWidth + 'px' : undefined, height: question.imageHeight ? question.imageHeight + 'px' : undefined, alt: question.text || question.title }, style: { objectFit: question.imageFit }"/>
    <!-- /ko -->
    <!-- ko if: question.contentMode === "video" -->
    <embed data-bind="css: question.koCss().image, attr: { src: $data.imageLink, width: question.imageWidth ? question.imageWidth + 'px' : undefined, height: question.imageHeight ? question.imageHeight + 'px' : undefined }, style: { objectFit: question.imageFit }"/>
    <!-- /ko -->
  </div>
</script>
```

**Comment by SamMousa** [comment]
Would you accept a PR for this?

**Comment by tsv2013** [comment]
We do remember about this request and it's in our plans to implement. But right now we have a lot of work on SurveyJS Creator V2 and this task was postponed a bit. We'll be glad to accept a PR. But I believe you understand that these changes should be done over all supported frameworks (Knockout, React, Vue) and we need to check this behavior in tests.

**Comment by SamMousa** [comment]
Hmm, that's actually quite interesting.
Wouldn't the new APIs you have developed over the last few years allow us to implement these components once in a framework agnostic manner?
Those components should also be testable in a simple framework agnostic manner!

**Comment by tsv2013** [comment]
@SamMousa In the new approach model will be shared, rendering should be implemented in a platform-specific way. Thus you can test a model for all the platforms, but markup should be tested separately for each platform
