### ISSUE TITLE
Bug: Unable to Preview a Matrix Dynamic inside of a Panel Dynamic

### ISSUE THREAD

**Issue by joshcampbell191** [surveyjs/survey-library#2761]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a Bug

### What is the current behavior?
When attempting to preview the survey results, an exception is thrown.

### What is the expected behavior?
The preview should be displayed without any exceptions.

### How would you reproduce the current behavior (if this is a bug)?
1. Add a row in the panel dynamic 
2. Answer the question in the matrix dynamic
3. Preview the results

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/LEnFSZKaORIFc8y5

Test code

```
Survey
    .StylesManager
    .applyTheme("modern");

var json = {
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "paneldynamic",
     "name": "question1",
     "templateElements": [
      {
       "type": "matrixdynamic",
       "name": "question2",
       "columns": [
        {
         "name": "Column 1"
        }
       ],
       "choices": [
        1,
        2,
        3,
        4,
        5
       ],
       "rowCount": 1
      }
     ]
    }
   ]
  }
 ],
 "showPreviewBeforeComplete": "showAnsweredQuestions"
};

window.survey = new Survey.Model(json);

survey
    .onComplete
    .add(function (result) {
        document
            .querySelector('#surveyResult')
            .textContent = "Result JSON:\n" + JSON.stringify(result.data, null, 3);
    });

$("#surveyElement").Survey({model: survey});
```

### Specify your

* browser: Microsoft Edge
* browser version: 89.0.774.63
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery / Vue
* surveyjs version: 1.8.39

**Comment by andrewtelnov** [comment]
@joshcampbell191 It is definitely a bug. We will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@joshcampbell191 Fixed by the commit above.

Thank you,
Andrew
