### ISSUE TITLE
How to create a click event on image picker?

### ISSUE THREAD

**Issue by ivorycoast** [surveyjs/survey-library#2772]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
I am wondering if it is possible to have a click event on an image (image of a body) and depending of the click location (the head, the arm, etc...) redirects the user to a certain page. 

### Specify your
* browser: Firefox
* browser version: 87.0
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.8.39

**Comment by tsv2013** [comment]
You can use the https://surveyjs.io/Documentation/Library?id=surveymodel#onAfterRenderQuestionInput event to access image tag. But I think the imagepicker is not a best choice for the image click map. You can use the image question type for it - https://surveyjs.io/Examples/Library?id=questiontype-image&platform=jQuery&theme=modern.

**Comment by ivorycoast** [comment]
I tried:
```
...
          elements: [
          {
            "type": "image",
            "name": "banner",
            "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/lion.jpg",
            "imageWidth": "500px",
            "imageHeight": "300px"
          }]
...
         survey.onAfterRenderQuestionInput.add(function(sender, options) {
           if (options.question.getType() === "image") {
               options.htmlElement.addEventListener("click", function(evt) {
                  alert(evt); // just for testing purpose
               });
           }
         });
```

It does not work. I tried with "text" type and it works.

**Comment by andrewtelnov** [comment]
@ivorycoast You should find the img element:
```js
survey.onAfterRenderQuestion.add(function (survey, options) {
    if (options.question.getType() !== 'image') return;
    var img = options.htmlElement.querySelector('img');
    img.onclick = () => {alert("I'm here!")}
});
```
[Here is the working example](https://plnkr.co/edit/p2tyT9ScFRazkave).

Thank you,
Andrew

**Comment by ivorycoast** [comment]
Thanks it works. Here is the code is used:

survey.onAfterRenderQuestion.add(function (survey, options) {
    if (options.question.getType() !== 'image') return;
    var img = options.htmlElement.querySelector('img');
    img.onclick = (event) => {
        let bounds = img.getBoundingClientRect();
        var left=bounds.left;
        var top=bounds.top;
        var x = event.pageX - left;
        var y = event.pageY - top;
        var cw=img.clientWidth
        var ch=img.clientHeight
        var iw=img.naturalWidth
        var ih=img.naturalHeight
        var px=x/cw*iw
        var py=y/ch*ih
        if (px >= 50 && px <=70 && py>=60 && py<=100) {
           survey.currentPageNo = 4;
        }
    }
});
