### ISSUE TITLE
Bug on clean answers on complete on choices from web property

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-library#2776]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?
When I use the choices from web property and my question has a previous value that doesn't match with the current data of my API endpoint, the data is not cleaned when I approve (this is cleaned when I have a scenario without choices from web).

### What is the expected behavior?
It works exactly the same as the case without choices from web

### How would you reproduce the current behavior (if this is a bug)?
Case without choices from web: this is a case that has 3 choices, the user select 1 element, and after that, that element was removed - this case is ok
https://plnkr.co/edit/vQ76jGTalxvqFc5I

Case with choices from web
https://plnkr.co/edit/MlnMy5CyGITAwJES

### Specify your

* browser:n/a
* browser version: n/a
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: last

**Comment by andrewtelnov** [comment]
@jmar1998 Please use the following code:
`survey.clearInvisibleValues = "none";` Here is the [documentation for this property](https://surveyjs.io/Documentation/Library?id=surveymodel#clearInvisibleValues).

Thank you,
Andrew

**Comment by jmar1998** [comment]
hello @andrewtelnov, i was expecting to cleaned in both situations , when the choices are loaded from an api or when the choices are static
if you can notice on both plunkers that i send
i got differents behaviors, when are static it works perfectly, when the options are loaded, this clean is ignored

**Comment by andrewtelnov** [comment]
@jmar1998 You complete the survey before you are getting data from the server.
That is the difference and the reason it doesn't work.

Thank you,
Andrew

**Comment by jmar1998** [comment]
hello @andrewtelnov , i do some testing on my side, doing some preparation , to wait for the data be loaded into survey , and i got the same result, no answers cleaned, on choices from web scenario
updated plunker : https://plnkr.co/edit/MlnMy5CyGITAwJES
i add se timeout of 5 secs, to do the complete after

**Comment by andrewtelnov** [comment]
@jmar1998 I have fixed it by the commit above.

Thank you,
Andrew
