### ISSUE TITLE
Bug on visible if (contains operator) if text value is 'False' or 'True'

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-library#2779]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

When i use this kind of visibleif
{question1} contains 'False'
{question1} contains 'FALSE'
{question1} contains 'True'
{question1} contains 'TRUE'

the question never appears
### What is the expected behavior?

This reserved words, should be treated as a word

### How would you reproduce the current behavior (if this is a bug)?
You can use the plunker attached, the test survey tab

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/kJnGrgMdzZToW6Un

* browser: N/A
* editor version: last

**Comment by andrewtelnov** [comment]
@jmar1998 I have fixed the issue. You can use two work-arounds for the current version:
`{#question1} contains 'TRUE'` - # will not convert entered value into numeric or boolean.
or `{question1} contains 'TRUE' or {question1} equals 'TRUE'`, if question1 is true, then it will convert 'TRUE' into boolean on comparing two values.

Thank you,
Andrew
