### ISSUE TITLE
Calculate expression using math, support log10 operator

### ISSUE THREAD

**Issue by cinziasala** [surveyjs/survey-library#2780]
### Are you requesting a feature, reporting a bug or asking a question?

requesting a feature

I am wondering if log10 may be considered an operator of general interest to be added in surveyjs expressions as an alternative to create a specific function.

As an example, it can be used to make complex math expressions like the one for the following medical score:

ALBI = (log10 bilirubin × 0.66) + (albumin × -0.085)

Is it feasible?
Thanks
Cinzia

**Comment by tsv2013** [comment]
You can introduce a custom function to accomplish this task. Please check this doc for more details - https://surveyjs.io/Documentation/Library#conditions-functions

**Comment by cinziasala** [comment]
Thank you, I know that option. I was wondering if log10 could be considered a math operator of general interest and added as a new feature in the expressions. If not, I will introduce a custom function.

Thanks

**Comment by masciugo** [comment]
more or less what happened for #1226. Thank you
