### ISSUE TITLE
matrix cell width

### ISSUE THREAD

**Issue by swuecho** [surveyjs/survey-library#2781]
### Are you requesting a feature, reporting a bug or asking a question?

survey js css adjustment

### What is the current behavior?

<img width="714" alt="Screen Shot 2021-04-08 at 10 34 25 AM" src="https://user-images.githubusercontent.com/666683/113959828-1b720a00-9856-11eb-926e-25901d471fa4.png">

### What is the expected behavior?

all columns should be displayed instead of requiring scroll.

<img width="862" alt="Screen Shot 2021-04-08 at 10 39 44 AM" src="https://user-images.githubusercontent.com/666683/113960247-c8e51d80-9856-11eb-8286-385697a317e4.png">

### How would you reproduce the current behavior (if this is a bug)?

https://surveyjs.io/Examples/Library/?id=questiontype-matrix&platform=jQuery&theme=modern

remove the `min-width: 10em` solve the problem.

**Comment by tsv2013** [comment]
You can use the https://surveyjs.io/Documentation/Library?id=surveymodel#onMatrixAfterCellRender event to customize cell markup
