### ISSUE TITLE
visibleIf does not work on subsequent pages for Vue implementation only.

### ISSUE THREAD

**Issue by JTorres87** [surveyjs/survey-library#2783]
"visibleIf" on a second page causes the page to never work if comparing answer from previous page.

### Are you requesting a feature, reporting a bug or asking a question?
Reporitng a bug

### What is the current behavior?
For other framework/library implementations (such as React or jquery) visibleIf works on other pages.
However on the VueJs implementation, the visibleIf parameter is ignored.
It seems the variables on subsequent pages in VueJs does not have a value.

VueJS version not working:
https://codesandbox.io/s/surveyjs-vue-forked-uyoj5

### What is the expected behavior?
Working React Version
https://codesandbox.io/s/vigorous-lederberg-h99xb

### How would you reproduce the current behavior (if this is a bug)?
Every time, this is a bug.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

These work on subsequent pages:
```visbibleIf: "1=1"```
``` visibleIf: "{introQuestion} = {introQuestion}",```

This does not work on subsequent pages:
 ```visibleIf: "{introQuestion} = 'yes'",```

Working React Version
https://codesandbox.io/s/vigorous-lederberg-h99xb

VueJS version not working:
https://codesandbox.io/s/surveyjs-vue-forked-uyoj5

Both of these examples utilize the same json payload for the survey.

**Comment by JTorres87** [comment]
I forgot to add the json payload by itself for testing.
```
{
      pages: [
        {
          name: "IntroPage",
          elements: [
            {
              type: "radiogroup",
              name: "introQuestion",
              title: "Hi, do you have a name?",
              isRequired: true,
              choices: [
                {
                  value: "yes",
                  text: "Yes"
                },
                {
                  value: "no",
                  text: "No"
                }
              ]
            },
            {
              type: "radiogroup",
              name: "anotherQuestion",
              visibleIf: "{introQuestion} = 'yes'",
              title: "Do you have a last name?",
              isRequired: true,
              choices: [
                {
                  value: "yes",
                  text: "Yes"
                },
                {
                  value: "no",
                  text: "No"
                }
              ]
            },
            {
              type: "html",
              name: "transferToMajorMed",
              visibleIf: "{introQuestion} = 'no'",
              html: "<h2>Sorry You dont Have a Name!!</h2>"
            }
          ]
        },
        {
          name: "SecondPage",
          visibleIf: "{introQuestion} = 'yes'",
          elements: [
            {
              type: "radiogroup",
              name: "nameJohn",
              title: "Is your name John?",
              isRequired: true,
              choices: [
                {
                  value: "yes",
                  text: "Yes"
                },
                {
                  value: "no",
                  text: "No"
                }
              ]
            },
            {
              type: "html",
              name: "transferToMajorMed",
              visibleIf: "{nameJohn} = 'no'",
              html: "<h2>I'm sure you have a great name!</h2>"
            },
            {
              type: "html",
              name: "transferToMajorMed",
              visibleIf: "{nameJohn} = 'yes'",
              html: "<h2>What a great name.</h2>"
            }
          ]
        }
      ]
    };
```

**Comment by andrewtelnov** [comment]
@JTorres87 It is fixed by the commit above.

Thank you,
Andrew
