### ISSUE TITLE
Summary during the survey progression

### ISSUE THREAD

**Issue by ivorycoast** [surveyjs/survey-library#2786]
### Are you requesting a feature, reporting a bug or asking a question?
Feature (or question?)

### What is the current behavior?
I would like to implement a summary of all questions and answers during the progression of the survey.
For example, the summary page will show-up just on the right of the survey.
Something like that:

- First question:
![image](https://user-images.githubusercontent.com/2655756/114179365-294f8a00-993f-11eb-8580-cd7eb1d68a20.png)

- Second question with the summary:
![image](https://user-images.githubusercontent.com/2655756/114180520-9152a000-9940-11eb-8f76-5fded386797b.png)

and so on...

For editing an entry inside the summary, you are redirected to the question. You can change the answer and it will be directly updated inside the summary.

### Specify your

* browser: Firefox
* browser version: 87.0
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.8.39

**Comment by tsv2013** [comment]
You can subscribe the https://surveyjs.io/Documentation/Library?id=surveymodel#onValueChanged event, get the `survey.data` (https://surveyjs.io/Documentation/Library?id=surveymodel#data) or `survey.getPlainData()` (https://surveyjs.io/Documentation/Library?id=surveymodel#getPlainData) data and show answers in your custom markup un the right side of a survey

**Comment by ivorycoast** [comment]
Thanks for your prompt answer!

I was not able to find a way to access survey.data or survey.getPlainData() from onValueChanged. Only:
```
sender - the survey object that fires the event.
options.name - the value name that has been changed.
options.question - a question which question.name equals to the value name. If there are several questions with the same name, the first question is used. If there is no such questions, the options.question is null.
options.value - a new value.
```

Can you explain a little bit please? thanks for your support.

**Comment by swuecho** [comment]
`sender - the survey object that fires the event.`

sender is survey, so you can also call `sender.data`

You could also reference the survey directly, as in
https://github.com/surveyjs/survey-library/issues/2723#issuecomment-803594626

**Comment by ivorycoast** [comment]
Very nice thanks you!
