### ISSUE TITLE
Input number buttons?

### ISSUE THREAD

**Issue by torosushi** [surveyjs/survey-library#2787]
### Are you requesting a feature, reporting a bug or asking a question?
I am asking a question.

### What is the current behavior?
There are no plus minus buttons?
![image](https://user-images.githubusercontent.com/6336672/114284675-e1427b80-9a94-11eb-9cf4-c0619a23fd47.png)

### What is the expected behavior?
How to change field to input with plus minus buttons?
![image](https://user-images.githubusercontent.com/6336672/114284710-3bdbd780-9a95-11eb-9799-001fdf39796e.png)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
SurveyJS doesn't have such a functionality at this moment. You can use the https://surveyjs.io/Documentation/Library?id=surveymodel#onAfterRenderQuestion event to customize markup or implement a custom widget https://github.com/surveyjs/custom-widgets - https://plnkr.co/edit/HdnYE5?p=preview&preview

**Comment by torosushi** [comment]
Thank you.
