### ISSUE TITLE
Move page to a certain position

### ISSUE THREAD

**Issue by ivorycoast** [surveyjs/survey-library#2788]
### Are you requesting a feature, reporting a bug or asking a question?
Question (or feature?)

### What is the expected behavior?
I would like to know if there is a function to move a page to a certain position? (before or after another page)
For example, I have a set of pages, but depending on certain conditions (the answer of one question), I would like to reorder the next pages.

A function like "survey.movePageAfter(pageX,targetPage) / movePageBefore(pageX,targetPage)"

### Specify your

* browser: Firefox
* browser version: 87.0
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.8.39

**Comment by tsv2013** [comment]
You can remove page https://surveyjs.io/Documentation/Library?id=surveymodel#removePage and add it to the certain position https://surveyjs.io/Documentation/Library?id=surveymodel#addPage

**Comment by ivorycoast** [comment]
Super it works!
