### ISSUE TITLE
Vue (radiogroup and checkbox questions):  enableIf in choices property doesn't work correctly

### ISSUE THREAD

**Issue by MuriloOnYou** [surveyjs/survey-library#2807]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
When I set EnableIf prop into the choices of two questions to prevent the user from choosing the same answer on both, the choices at first get correctly disabled but after changing some answer I can select the same answer at the other question.

### What is the expected behavior?
Always disable the other question choice when some answer is selected.

### How would you reproduce the current behavior (if this is a bug)?
Access [the reproduction](https://codesandbox.io/s/surveyjs-enableif-bug-2tczp?file=/pages/index.vue), select some answer at the first question and select some answer at the second question. The corresponding answer into the first question won't be disabled.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codesandbox.io/s/surveyjs-enableif-bug-2tczp?file=/pages/index.vue

### Specify your

* browser: Microsoft Edge
* browser version: 89.0.774.77
* surveyjs platform (angular or react or jquery or knockout or vue): survey-vue
* surveyjs version: 1.8.43

**Comment by andrewtelnov** [comment]
@MuriloOnYou Yes, I can see the issue.

**Comment by andrewtelnov** [comment]
@MuriloOnYou I have fixed it by the commit above.

Thank you,
Andrew

**Comment by MuriloOnYou** [comment]
Thank you so much.

Best regards,
Murilo
