### ISSUE TITLE
Issue on combination between default value on question + single page survey + visibleif on choice

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-library#2816]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

My default value its being cleaned up, because the visible if relation with choice only on singlePage mode

### What is the expected behavior?

The default value must be set after my previous question ends (seems like, the process its running before, and that its why the default value never appears)

### How would you reproduce the current behavior (if this is a bug)?
plunker with single page : https://plnkr.co/edit/Asiw5IchB63JSX6X
plunker with multiple page : https://plnkr.co/edit/YPWEltANZzKNtJJr
You need to select the option 1 and option 2

**Comment by andrewtelnov** [comment]
@jmar1998 Fixed by the commit above.

Thank you,
Andrew
