### ISSUE TITLE
It does not seem to work to assign custom css classes

### ISSUE THREAD

**Issue by reginaochotzki** [surveyjs/survey-library#2821]
Hi Folks,
Could it be that it does not work to assign custom css classes. I'm despairing about this and don't know what else to do.

Here is a codesandbox example:
https://codesandbox.io/s/admiring-clarke-f1m3m?file=/src/Surveyjs.jsx

I would expect the preview button to be purple and the background of the table to be light blue. So that the custom CSS classes for the preview button and for the table are applied.

What am I doing wrong? 

I think I have followed this documentation exactly.
https://surveyjs.io/Examples/Library/?id=survey-customcss&platform=Reactjs&theme=modern#content-js

But somehow it still doesn't seem to work.

**Comment by tsv2013** [comment]
Your codesandbox doesn't work for me:
```
ModuleNotFoundError
Could not find module in path: './test' relative to '/src/index.js'
```

**Comment by reginaochotzki** [comment]
Sorry, here is the correct link
https://codesandbox.io/s/modest-sun-xvwte?file=/src/Surveyjs.jsx

**Comment by reginaochotzki** [comment]
I found out why it didn't work. It was an interaction with emotion. If you have emotion settings in babel.conf, then the css property is always converted to an emotion object. Maybe it would be good to rename the css property to avoid these conflicts in the future. Thanks

**Comment by kevinprakasa** [comment]
For those of you who are still dealing with this issue. I managed to solve it by using survey model `setCss` method. So for my case which I implemented survey.js in React app looks like this.

```
  const survey = new Model(SurveyForm);
  const overrideSurveyCss = {
    root: 'xxx',
    body: 'xxxx,
    ....
  };
  survey.setCss(overrideSurveyCss);
  return <Survey model={survey}/>;

```

Voilla, you'll get the same result as the one above using the CSS prop.
