### ISSUE TITLE
Passing backgroundColor as an option for SignaturePad

### ISSUE THREAD

**Issue by smk1992** [surveyjs/survey-library#2823]
### Are you requesting a feature, reporting a bug or asking a question?
feature

### What is the current behavior?
SignaturePad has hardcoded white background.

### What is the expected behavior?
We should be able to pass backgroundColor as a config for type "signaturepad". The underlying library for signaturepad supports it.

### How would you reproduce the current behavior (if this is a bug)?
This white background is the default behaviour as introduceed by commit  
https://github.com/surveyjs/survey-library/commit/6c1f2fc2e4506c155c77c28f0cb5ad7e11872b06#diff-56fcd01c0c08b1327bf774d29516820047e7a5a410ca987f6446b4c62e5ef679R75

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version: 90
* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: latest

**Comment by tsv2013** [comment]
I've implemented the `backgroundColor` option for the signature pad question:
```JS
      {
        name: "signature",
        type: "signaturepad",
        title: "Sign here",
        penColor: "red",
        backgroundColor: "green"
      },
```

**Comment by smk1992** [comment]
Sweet Thanks
