### ISSUE TITLE
variable substitution not always working

### ISSUE THREAD

**Issue by matthewberryman** [surveyjs/survey-library#2826]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behaviour?

Specifying strings for rows does not result in variable substitution, e.g.
```json
rows: [
  "Are {pronouns[0]} feeling happy?",
  "Are {pronouns[0]} feeling excited?"
]
```
for a matrix Q and where pronouns is from calculatedValues and `pronouns===['you','your','my','mine','You','Your','My','Mine','are','yourself']`
 
results in 
Are {pronouns[0]} feeling happy?
Are {pronouns[0]} feeling excited?

### What is the expected behaviour?

Are you feeling happy?
Are you feeling excited?
...

The same as if I had specified `{"value": "somevalue", "text": "sometext with {pronouns[0]"}` for a row, or title, etc.

### How would you reproduce the current behaviour (if this is a bug)?

Per above.

#### Provide the test code and the tested page URL (if applicable)

Per above.

### Specify your

* browsers & versions: Chrome 91.0.4472.19 (Official Build) beta (x86_64), Firefox 89.0b4 (64-bit), Safari 14.1.1 (16611.2.3)
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.8.44

**Comment by andrewtelnov** [comment]
@matthewberryman Please use text property for text processing. We do not do text processing from values. It would change your data as well.
Here is [the working example](https://plnkr.co/edit/zcKmgf1yT9CvHfpr).

Thank you,
Andrew

**Comment by matthewberryman** [comment]
Ah, I can see now why that would be a problem. I will just keep using the `{"value": ..., "text": ...}` approach I've been using. Thank you for the explanation and for surveyjs more generally.
