### ISSUE TITLE
Markdown not working anymore with 1.8.45 

### ISSUE THREAD

**Issue by MrKrabat** [surveyjs/survey-library#2831]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
With version 1.8.45 markdown does not work anymore. It did work with 1.8.44.

### What is the expected behavior?
Markdown is working.

### How would you reproduce the current behavior (if this is a bug)?
Use markdown.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Examples/Library/?id=survey-markdown-radiogroup&platform=jQuery

### Specify your

* browser: Chrome
* browser version: 90
* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version: 1.8.45

**Comment by andrewtelnov** [comment]
@MrKrabat As a workaround, please set json into survey after adding an event handler. Here is [the example](https://plnkr.co/edit/mywn8OpOXJpWMyTL).
We add a lot of performance optimization for localization strings and for some reason this scenario is missed in our unit tests and E2E. I will add a unit test and fix.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@MrKrabat fixed by the commit above.

Thank you,
Andrew

**Comment by MrKrabat** [comment]
Thank you :)
