### ISSUE TITLE
Expression not updating

### ISSUE THREAD

**Issue by MrKrabat** [surveyjs/survey-library#2846]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Expression does not update.

### What is the expected behavior?
Expression should update.

### How would you reproduce the current behavior (if this is a bug)?
- Use the survey bellow
- Change the value of the first input
- Value of second input does not change

#### Provide the test code and the tested page URL (if applicable)

Test code
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "question1",
     "defaultValue": "Test"
    },
    {
     "type": "text",
     "name": "question2",
     "defaultValueExpression": "{question1}"
    }
   ]
  }
 ]
}

```

### Specify your

* browser: Chrome
* browser version: 90
* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version: 1.8.46

**Comment by andrewtelnov** [comment]
@MrKrabat It works for me. Here is [the working example](https://codesandbox.io/s/surveyjs-angular-forked-r6g22?file=/src/app/components/survey.component.ts).

Thank you,
Andrew

**Comment by MrKrabat** [comment]
Strange, when I change the input of question1, question2 is not updated

**Comment by andrewtelnov** [comment]
@MrKrabat It should not, it is initial value that we change on loading the question.
You can probably are looking for `copyvalue` trigger. Here is [the example](https://surveyjs.io/Examples/Library?id=trigger-copyvalue).

Thank you,
Andrew

**Comment by MrKrabat** [comment]
Thank you for your help :)
