### ISSUE TITLE
Bug with custom widget and error validation in vue

### ISSUE THREAD

**Issue by fcorallini** [surveyjs/survey-library#2848]
### What is the current behavior?

Hi i'm working with survey-vue. I created a simple custom widget, with isRequired true. Triggering the survey validation via JavaScript works well with version 1.8.32 and below. But with version >= 1.8.33 the error red alerts are not displayed in the custom widget:

Example code:
var page = vm.survey.getPage(0)
page.hasErrors()

* browser: Chrome and Firefox

**Comment by andrewtelnov** [comment]
@fcorallini I can confirm the issue in vue.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@fcorallini It is fixed by the commit above.

Thank you,
Andrew
