### ISSUE TITLE
[Question] get question names

### ISSUE THREAD

**Issue by swuecho** [surveyjs/survey-library#2849]
### Are you requesting a feature, reporting a bug or asking a question?

api to get all question names?

I add the following code to survey.ts. Is there a better approach? Thanks.

```js
 public getQuestionNames () {
    let questionNames= Object.keys(
      this.questionHashes.names
    )
    return questionNames
 }
```

**Comment by tsv2013** [comment]
```JS
qNames = survey.getAllQuestions().map(function(question) { return question.name });
```

**Comment by andrewtelnov** [comment]
@swuecho This code is correct if you do it in survey class. The code that @tsv2013 provided is corrected two.
Your code will work faster in several times. Probably in 10 or 100 times. However, even for large surveys with thouthands questions, we are talking about time that less than one millisecond and there is nothing to optimize. `getAllQuestions` uses "depth-first traversal tree" algorythm.

Thank you,
Andrew

**Comment by swuecho** [comment]
@tsv2013  @andrewtelnov Thanks. I was worried about the performance of getAllQuestions, glad to know  it is not a concern. save me some trouble to change in `survey.ts`
