### ISSUE TITLE
How to remove the dots on multi choice questions

### ISSUE THREAD

**Issue by chelsumz007** [surveyjs/survey-library#2850]
How to remove the dots on the multiple choice button in survey

![image](https://user-images.githubusercontent.com/52992133/117106921-56f0ed00-ad9e-11eb-98de-518ba83bd5d9.png)

### Specify your

* browser: chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@chelsumz007 Please check that correct css file is loaded on your page. It looks like css classes are missed.

Thank you,
Andrew

**Comment by chelsumz007** [comment]
Thanks andrew :)
