### ISSUE TITLE
BUG: Dependend choices not working properly in PanelDynamic

### ISSUE THREAD

**Issue by szacchino** [surveyjs/survey-library#2851]
Hi, I report the unattended behavior in the following kind of survey.

1. First put a checkbox field (question1).
2. Secondly a PanelDynamic.
3. In the panel put a dropdown whose choices are taken from selected answer of question 1.

Now let's test the survey.
Select some answers from question1.
Add two or more rows in the paneldynamic.
The first dropdown in the panel works well, the second shows default answers.

The expected behavior is that in every copy of the panel the dropdown should show the selected answers from question1.

If I first create copies of PanelDynamic and THEN choose answers from question1, all the dropdowns shows the correct answers. 

UPD: Minimum [example](https://plnkr.co/edit/CnE5s0Nm1rRl9W3H) to reproduce the issue.

Test code

```js
{
 "completedHtml": "<p><h4>Thank you for sharing this information with us.</h4></p><p>Your name is: <b>{name}</b></p><p>Your email is: <b>{email}</b></p><p>This information is not in the survey data result:<b> {tempvar}</b></p>",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "checkbox",
     "name": "question1",
     "choices": [
      "A",
      "B",
      "C",
      "D",
      "E"
     ],
     "otherText": "item5"
    },
    {
     "type": "paneldynamic",
     "name": "question2",
     "templateElements": [
      {
       "type": "dropdown",
       "name": "question3",
       "choicesFromQuestion": "question1",
       "choicesFromQuestionMode": "selected"
      }
     ]
    }
   ],
   "title": "Customer information"
  }
 ],
 "triggers": [
  {
   "type": "setvalue",
   "setToName": "name",
   "setValue": "Jon Snow"
  },
  {
   "type": "setvalue",
   "setToName": "email",
   "setValue": "jon.snow@nightwatch.com"
  },
  {
   "type": "setvalue",
   "setToName": "tempvar",
   "setValue": "You have decided to use your current information.",
   "isVariable": true
  },
  {
   "type": "setvalue",
   "setToName": "name"
  },
  {
   "type": "setvalue",
   "setToName": "email"
  },
  {
   "type": "setvalue",
   "setToName": "tempvar",
   "setValue": "You have decided not to use your current information.",
   "isVariable": true
  }
 ]
}

```

### Specify your

* browser: Firefox and Chrome
* browser version: firefox 88 and chrome 90.0.4430.93 
* surveyjs platform: vue and jquery
* surveyjs version: 1.8.46

**Comment by andrewtelnov** [comment]
@szacchino It is fixed by the commit above.

Thank you,
Andrew
