### ISSUE TITLE
can we stop the thank you page at end and render some thing of our own.

### ISSUE THREAD

**Issue by AdityaKallur** [surveyjs/survey-library#2852]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@AdityaKallur You can set [survey.showCompletedPage](https://surveyjs.io/Documentation/Library?id=surveymodel#showCompletedPage) to false.
In fact on survey.onCompleted event, you can simply hide div where survey is located and show your own div with your own text.

Thank you,
Andrew

**Comment by AdityaKallur** [comment]
@andrewtelnov This was helpful, thanks
