### ISSUE TITLE
how to visit a quesion's title in an expression validator?

### ISSUE THREAD

**Issue by scil** [surveyjs/survey-library#2860]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

expression can not visit the title `5 + 4 =`

```
      elements: [
        {
          type: 'text',
          name: 'math',
          title: '5 + 4 = ',
          titleLocation: 'left',
          hideNumber: true,
          correctAnswer: 5,
          inputType: 'number',
          isRequired: true,
          validators: [
             {
               type: 'expression',
               text: 'test',
               expression: 'MathExpressionEvaluator({math.title})',
             };

          ],
        },
        
      ]
```

### What is the expected behavior?

expression can parse `{math.title}` to  `5 + 4 =`

**Comment by andrewtelnov** [comment]
@scil You will have to use a custom function to get the question title. I guess "MathExpressionEvaluator" is your custom function. You can create "MathExpressionTitleEvaluator" function and pass there a question name as:
"expression: 'MathExpressionTitleEvaluator("math")'".
In the custom function, you can always access the survey as `this.survey`, so you will be able to get question:
```js
var question = this.survey.getQuestionByName(params[0]);
if(!question) return undefined;
return MathExpressionEvaluator(question.title);
```

Thank you,
Andrew

**Comment by scil** [comment]
Thank you!  And with your code, I found related info in doc:  [Access survey element instances inside a custom function](https://surveyjs.io/Documentation/Library?id=LibraryOverview#custom-functions)
