### ISSUE TITLE
The order of choices questions, can continue column by column ?

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-library#2868]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

When i use the checkbox question and order my choices by asc order and i have my layout as 2 cols, basically my order its like this
AAAA    AAAA 
AAAA    AAAA 
AAAA    AAAA 
CCCC   CCCC
### What is the expected behavior?
its possible to have it like
AAAA    CCCC
AAAA    CCCC
AAAA    DDDD
BBBB
BBBB

Like a continuous order

### Specify your

* browser: last
* editor version: N/A

**Comment by andrewtelnov** [comment]
@jmar1998 Please set the following code before initialization the survey model:
`Survey.settings.showItemsInOrder = "column"`.

```js
  /**
   * By default checkbox and radiogroup items are ordered in rows.
   * Set it "column", and items will be ordered in columns.
   */
  showItemsInOrder: "default",

```

Thank you,
Andrew
