### ISSUE TITLE
Rename the TEMPLATE_RENDERER_COMPONENT_NAME to the pascal case as used in other constants in this project

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-library#2869]

**Comment by gologames** [comment]
[Related commit](https://github.com/surveyjs/survey-library/commit/022b35bd09b3cb1efd9bd1549782c88d54ff0836)

**Comment by gologames** [comment]
Fixed with these pull requests: https://github.com/surveyjs/survey-library/pull/2880 and https://github.com/surveyjs/survey-creator/pull/1212
