### ISSUE TITLE
CalculatedValues stored in LocalStorage wont render on page refresh

### ISSUE THREAD

**Issue by kushv16** [surveyjs/survey-library#2870]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
I am storing the results of my survey into localStorage using the onValueChanged event. Some of the fields in the survey are expression type questions which are getting computed through custom functions being called in the calculatedValues. The computations are functioning as expected and on every valueChange the local storage gets updated.

However If I close Chrome and reopen the survey or on every page refresh, Input fields(Text Type Questions, PanelDynamic Type Questions) are fetched from the local storage and displayed to the user but the expression type questions reset/go blank. 

Is there a way to fetch these values as well and if not then any workaround to compute these values every time the survey is loaded?

### What is the expected behavior?
On refreshing the page the expression type questions should either be computed again based on the input field entries or it should fetch them from the local storage.

This is how the survey should look every time it is rendered or when the data is fetched from the localStorage
![before](https://user-images.githubusercontent.com/59636993/118548394-e1125b80-b777-11eb-9263-4d321a9ad777.jpg)

This is how the survey looks after refresh
![After](https://user-images.githubusercontent.com/59636993/118548504-01dab100-b778-11eb-909d-e03dbf5e67b5.jpg)

### Specify your
* browser: Chrome
* browser version:  90
* surveyjs platform: React
* surveyjs version: 1.8.46

**Comment by tsv2013** [comment]
Can you share a minimal live sample illustrated the issue?

**Comment by andrewtelnov** [comment]
@kushv16 Even if you store data onValueChanged event, it makes sense to store `survey.data` property - survey responses including expression question. Then you can restore the value by settint `survey.data`.
Here is the [help topic](https://surveyjs.io/Documentation/Library?id=LibraryOverview#data-restoreanswers).

Thank you,
Andrew

**Comment by kushv16** [comment]
@andrewtelnov @tsv2013  The localstorage after the onValueChanged event has both the expression type questions as well as the text type questions. However for some reason on page refresh the expression type questions which are computed through calculatedValues are not fetched from the localStorage. 

This is how the code looks like, similar to that given in the surveyJS documentation.
![image](https://user-images.githubusercontent.com/59636993/118605701-2ebcb180-b7d4-11eb-883f-5041ef5fe251.png)

**Comment by andrewtelnov** [comment]
@kushv16 and this code works fine in [our example](https://surveyjs.io/Examples/Library?id=real-patient-history). Please create a minimum reproducible example in plnker and we will take a look.

Thank you,
Andrew

**Comment by kushv16** [comment]
Here is a sample example https://plnkr.co/edit/epMNaFhiJoskMfjX

For the first time when the survey.data is empty all computations and all expression questions are displayed as expected. However, if you refresh the page and then update some user input entry then the question4 computations are not getting updated on the screen. They update themselves only after page refresh.
