### ISSUE TITLE
React build with webpack and typescript

### ISSUE THREAD

**Issue by dcods22** [surveyjs/survey-library#2881]
I am getting an issue when trying to compile our code with adding surveryjs to our React app.  It builds fine before I add it but then I get the error 

ERROR in /Users/daniel.cody/Documents/projects/prospect-ui/node_modules/survey-react/survey.react.d.ts
ERROR in /Users/daniel.cody/Documents/projects/prospect-ui/node_modules/survey-react/survey.react.d.ts(1955,38):
TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.

ERROR in /Users/daniel.cody/Documents/projects/prospect-ui/node_modules/survey-react/survey.react.d.ts
ERROR in /Users/daniel.cody/Documents/projects/prospect-ui/node_modules/survey-react/survey.react.d.ts(1977,52):
TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.

ERROR in /Users/daniel.cody/Documents/projects/prospect-ui/node_modules/survey-react/survey.react.d.ts
ERROR in /Users/daniel.cody/Documents/projects/prospect-ui/node_modules/survey-react/survey.react.d.ts(1984,52):
TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.

ERROR in /Users/daniel.cody/Documents/projects/prospect-ui/node_modules/survey-react/survey.react.d.ts
ERROR in /Users/daniel.cody/Documents/projects/prospect-ui/node_modules/survey-react/survey.react.d.ts(10172,55):
TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.

Dependency versions: 
"survey-react": "^1.8.47",
"react": "^17.0.2",
"typescript": "^4.2.4",
    "webpack": "^4.42.0",

tsconfig:

{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "jsx": "react",
    "lib": ["es6", "dom"],
    "module": "es2020",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noImplicitThis": true,
    "outDir": "./dist/",
    "sourceMap": true,
    "strictNullChecks": true,
    "target": "es5",
    "strict": true
  }
}

**Comment by tsv2013** [comment]
We're using similar typings in another our product - SUrveyJS Creator - and they transpiled ok. Can you share a minimal sample illustrating the issue?

**Comment by dcods22** [comment]
I was missing "skipLibCheck": true, in the tsconfig which allowed for my build to go through
