### ISSUE TITLE
Partial ranking

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#2908]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
Ranking question requires full ordering of every available option

### What is the expected behavior?

It would be great if:
- Choices are initially `unranked` in a separate box
- Ranking choices are moved to a `ranked` box
- There is a minimum and a maximum number of choices one can configure.

**Comment by dmitrykurmanov** [comment]
Hello,

it looks like [sortablejs based custom widget functionality](https://surveyjs.io/Examples/Library?id=custom-widget-sortablejs&platform=jQuery&theme=modern). Could you please check it?

**Comment by JaneSjs** [comment]
Hi @SamMousa,
I believe you may be interested to know that we are currently working on this task: https://github.com/surveyjs/survey-library/issues/5328.

If you'd like to know more, please subscribe to this thread for further notifications.

Should you have any questions or require further assistance, please feel free to reactivate this thread at any time.
