### ISSUE TITLE
'matrixdropdown' type of survey question is not displayed properly in in React Hooks 

### ISSUE THREAD

**Issue by iyamus** [surveyjs/survey-library#2919]
### Are you requesting a feature, reporting a bug or asking a question?
It would be a bug report, otherwise, it's a question. 

### What is the current behavior?
My dev environment is React@^17.0.2 with hooks, and I tried to use the [example](https://surveyjs.io/Examples/Library?id=real-patient-history&platform=Reactjs&theme=default) on the document page. However, I found an issue to display survey contents. Other survey types look fine, but in the case of "matrixdropdown", as you see the image, columns are shown not under the title, but besides one, so it looks weird. Is there any way to remove the space? 
![2021-05-28 12_49_11-LifeWorks](https://user-images.githubusercontent.com/39981992/120031101-8e297700-bfb5-11eb-8e76-faf9923f2e44.jpg)

Even in the [example](https://surveyjs.io/Examples/Library?id=real-patient-history&platform=jQuery&theme=default), it shows spaces in "matrixdropdown" type of survey question. 
![2021-05-28 13_02_37-Patient Past Medical, Social   Family History Survey, Reactjs Survey Library Exa](https://user-images.githubusercontent.com/39981992/120031213-bf09ac00-bfb5-11eb-9471-5f583c8c0901.jpg)

### What is the expected behavior?
The survey question is displayed under the question title, not beside the title, so content is displayed w/o space.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
The JSON file is same as the one in the example.
```
import React, { useEffect } from "react";
import { json} from "../../contents/surveyQuestion";
import * as Survey from "survey-react";
import "survey-react/survey.css";
import * as widgets from "surveyjs-widgets";

Survey.StylesManager.applyTheme("default");

const DisplaySurvey= () => {
  const survey = new Survey.Model(json);

  var storageName = "survey_patient_history";
  var prevData = window.localStorage.getItem(storageName) || null;

  if (prevData) {
    var data = JSON.parse(prevData);
    survey.data = data;
    if (data.pageNo) {
      survey.currentPageNo = data.pageNo;
    }
  }

  const saveSurveyData = (survey) => {
    var data = survey.data;
    data.pageNo = survey.currentPageNo;
    window.localStorage.setItem(storageName, JSON.stringify(data));
  };

  const onComplete = (survey, options) => {
    console.log("Survey results: " + JSON.stringify(survey.data));
  };

  widgets.inputmask(Survey);

  return (
    <div>
      IncentiveData
      <Survey.Survey
        model={survey}
        onComplete={onComplete}
        onPartialSend={saveSurveyData}
        sendResultOnPageNext={true}
      />
    </div>
  );
};

export default DisplaySurvey;

```

### Specify your

* browser: chrome
* browser version: Version 90.0.4430.212 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): ReactJS
* surveyjs version: ^1.8.49

**Comment by dmitrykurmanov** [comment]
Hello,

I guess it is because of [panel.questionTitleLocation](https://surveyjs.io/Documentation/Library?id=panelmodel#questionTitleLocation) property.

```js
var json = {
"pages": [
    {
        "elements": [
            {
                "type": "panel",
                "name": "patienName",
                "elements": [
                  ...
                ],
                "questionTitleLocation": "bottom",
               ...
            }
...
```
Could you please try to change it?

**Comment by dmitrykurmanov** [comment]
also you could try our **"Modern"** theme it might look better:

```
Survey.StylesManager.applyTheme("modern");
```

**Comment by iyamus** [comment]
Thanks for your comment @dmitrykurmanov However, I tried to apply with the property 'questionTitleLocation' as your saying, and found it shows the same layout.
![2021-06-01 13_16_34-LifeWorks](https://user-images.githubusercontent.com/39981992/120378469-b679e400-c2db-11eb-936d-16888acbde05.jpg)

```
            {
              type: "matrixdropdown",
              name: "subsctancesUsing",
              title: "Have you used any of the following substances?",
              questionTitleLocation: "bottom",   <------- adding property
              columns: [
                {
                  name: "current",
                  title: "Currently Use?",
                  choices: ["No", "Yes"],
                  cellType: "radiogroup",
                  isRequired: true,
                },
                {
                  name: "previous",
                  title: "Previously Used?",
                  choices: ["No", "Yes"],
                  cellType: "radiogroup",
                  isRequired: true,
                },
                {
                  name: "amount",
                  title: "Type/Amount/Frequancy",
                  cellType: "text",
                  isRequired: true,
                  visibleIf: "{row.current} = 'Yes' or {row.previous} = 'Yes'",
                },
                {
                  name: "long",
                  title: "How Long? (Years)",
                  cellType: "text",
                  isRequired: true,
                  visibleIf: "{row.current} = 'Yes' or {row.previous} = 'Yes'",
                },
                {
                  name: "stopped",
                  title: "When stopped? (Year)",
                  cellType: "text",
                  isRequired: true,
                  visibleIf: "{row.previous} = 'Yes'",
                },
              ],
              choices: [1, 2, 3, 4, 5],
              rows: [
                "Caffeine: coffee, tea, soda",
                "Tobacco",
                "Alcohol - bear, wine, liquor",
                "Recreational/Street drugs",
              ],
            },
```

Also, I tried to use [the example with 'modern' theme](https://codesandbox.io/s/ivhu0?file=/src/SurveyComponent.jsx:155-341) , it also displays the same layout with having space on the left side of the question set. even though I set up with  ```questionTitleLocation: "bottom"``` between properties. 
![2021-06-01 13_21_05-compassionate-morse-y4w7f - CodeSandbox](https://user-images.githubusercontent.com/39981992/120378907-4750bf80-c2dc-11eb-90ca-772b120c4a6c.jpg)

**Comment by dmitrykurmanov** [comment]
@iyamus I will create a plunker example with your json and check it

**Comment by dmitrykurmanov** [comment]
@iyamus the `questionTitleLocation` is belong to the [Panel](https://surveyjs.io/Documentation/Library?id=panelmodel) not the question(matrixdynamic) itself.

So please try to set the property in the panel or on the whole page. Because [Page ](https://surveyjs.io/Documentation/Library?id=pagemodel) inherited from Panel.

Here the simple example: https://plnkr.co/edit/5uUEOO9NYdondbnS

**Comment by iyamus** [comment]
@dmitrykurmanov Thanks, it works!
