### ISSUE TITLE
Using custom ItemValue properties in CalculatedValues

### ISSUE THREAD

**Issue by JeroenJADS** [surveyjs/survey-library#2925]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

When using CalculatedValues like 
```
{"name": "Scoreq1", "expression": {question1}  }
````

the outcome of this calculatedvalue is automatically the 'value' property of the selected question answer. 

In our setup we have a custom property added to itemvalue called 'Score'. Is it possible to instead of always using the value property in a CalculatedValue use the "Score" property of the answer? 

Using the "value" property wont suffice, since the value property can't be identical between rows in a question, even though the score of the answers could be identical.

### What is the expected behavior?

This could work like 

```
{"name": "Scoreq1", "expression": {question1.score}  }
```

### How would you reproduce the current behavior (if this is a bug)?

.

### Specify your

* browser: Chrome
* browser version: 91.0.4472.77
* surveyjs platform (angular or react or jquery or knockout or vue): Knockout
* surveyjs version: 1.8.49

**Comment by andrewtelnov** [comment]
@JeroenJADS You have to create a custom function, register it in SurveyJS and then you can reuse it in any expression. Please take a look at "getPrice" at [the following example](https://surveyjs.io/Examples/Library/?id=questiontype-matrixdynamic-totals). It is very close to what you are looking for.
You will need to change the following code:
```js
var question = !!this.row ? this.row.getQuestionByColumnName(params[0]) : null;
``` 
to
```js
var question = !!this.row ? this.row.getQuestionByColumnName(params[0]) : this.question;
``` 

Thank you,
Andrew
