### ISSUE TITLE
Error on default values not working when we set data on our survey

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-library#2933]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

When we put default values on the questions, and after that we use
survey.data = {}
survey.data = undefined;
survey.data = {...}
all default values are cleaned up
### What is the expected behavior?
Im expecting to have all the default values always available , except, when i change the question answer by myself

### How would you reproduce the current behavior (if this is a bug)?

Plunker with survey.data : https://plnkr.co/edit/C0KC4DmCbUXY0shZ
Plunker without survey.data : https://plnkr.co/edit/fX79gEVWPVf7i9Yi

### Specify your

* browser: N/A
* browser version: N/A
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: last

**Comment by andrewtelnov** [comment]
@jmar1998 `survey.data = undefined`; or `survey.data = {}`; clears all values and it is correct behavior. There are many unit tests and scenarios based on this behavior.
You are likely looking for [survey.mergeData()](https://surveyjs.io/Documentation/Library?id=surveymodel#mergeData) function. It does what you need.

Thank you,
Andrew

**Comment by jmar1998** [comment]
@andrewtelnov oh ok , got it, thanks alot
