### ISSUE TITLE
Custom complete button text only applied when having multiple pages

### ISSUE THREAD

**Issue by mheers** [surveyjs/survey-library#2934]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Custom complete button text only applied when having multiple pages:

![Screenshot from 2021-06-02 15-42-49](https://user-images.githubusercontent.com/17021898/120491906-eac3d200-c3b9-11eb-824e-fc9a1571f9e4.png)
![Screenshot from 2021-06-02 15-42-58](https://user-images.githubusercontent.com/17021898/120491933-f1524980-c3b9-11eb-80ca-aae88c5a125e.png)

### What is the expected behavior?
Custom complete button text should also be applied when having a single page

### How would you reproduce the current behavior (if this is a bug)?
Create a Survey with the Survey-Creator with a single page and adjust the 'Complete Button Text'

![Screenshot from 2021-06-02 15-48-56](https://user-images.githubusercontent.com/17021898/120493331-29a65780-c3bb-11eb-859c-2a1c0f2fccf6.png)

### Specify your

* browser: chrome
* browser version: 91.0.4472.77 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.8.49

**Comment by andrewtelnov** [comment]
@mheers I could not reproduce the issue on our [web site](https://surveyjs.io/create-survey).
I tried to reproduce it in vue and failed it as well. Here is [the example](https://plnkr.co/edit/n4ISaPiyBzpMioYX).
I tried to set the "completeText" in JSON, before rendering, after rendering. It works fine in all cases.

Thank you,
Andrew

**Comment by mheers** [comment]
@andrewtelnov thank you very much! I can confirm, that there is no issue in survey-js but in my own application instead.

**Comment by andrewtelnov** [comment]
@mheers Do you mean in your vue app? If yes, then I can try to create an app CodeSandbox. For some reason vue has different behavior in CodeSandbox and plunker.

Thank you,
Andrew
