### ISSUE TITLE
Matrix - Custom cell types doesn't work (jQuery, Knockout, Angular)

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/survey-library#2935]
We get the js error in the console: `Cannot read property 'style' of null`

Failed examples: 

- https://surveyjstest.azurewebsites.net/Examples/Library?id=questiontype-matrix-customcelltypes&platform=Knockoutjs&theme=default
- https://surveyjstest.azurewebsites.net/Examples/Survey-Creator?id=matrixcustomcelltypes&theme=modern

**Comment by andrewtelnov** [comment]
It is in the current v1.8.50 (not released), it works fine in v1.8.49.
