### ISSUE TITLE
clearValueOnDisableItems does not clear value

### ISSUE THREAD

**Issue by chen39636** [surveyjs/survey-library#2945]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
setting clearValueOnDisableItems property to true on survey does not clear value on disabled item when using enableIf

### What is the expected behavior?
setting clearValueOnDisableItems to true should clear value on disabled item when using enableIf

### How would you reproduce the current behavior (if this is a bug)?
setting clearValueOnDisableItems to true

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question1",
     "choices": [
      {
       "value": "1",
       "text": "Yes"
      },
      {
       "value": "0",
       "text": "No"
      }
     ]
    },
    {
     "type": "radiogroup",
     "name": "question2",
     "enableIf": "{question1} = 1",
     "choices": [
      {
       "value": "1",
       "text": "Yes"
      },
      {
       "value": "0",
       "text": "No"
      }
     ]
    }
   ]
  }
 ]
}
```
your_code_here
this.surveyjsModel = new Survey.Model(JSON.parse(model.surveyJsonData));
    
this.surveyjsModel.clearValueOnDisableItems = true;
```

### Specify your

* browser: Chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: 1.8.50

**Comment by andrewtelnov** [comment]
@chen39636 this option works on disabling choices and not a question. Here is [the workign example](https://plnkr.co/edit/1jpU3ELc2cDCgHHJ).
Commonly, you want to disable some items and enabled others. Here is [the example](https://plnkr.co/edit/zvLVRu5i551K2Trn) that makes more sense.

Thank you,
Andrew

**Comment by chen39636** [comment]
I understand how it works now. Thank you.
