### ISSUE TITLE
Ratings element broken in 1.8.50

### ISSUE THREAD

**Issue by bbbco** [surveyjs/survey-library#2946]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?

For a basic "rating" page element in version 1.8.50, the survey page renders the rating elements, and _NONE_ of the numbers are selectable by the user. No errors are displayed in the Browser console. The comment box can be filled out but the next button _CANNOT_ be clicked because a number (rating) has not been chosen.

### What is the expected behavior?

The survey page renders the rating elements, and any of the numbers are selectable. The comment box can be filled out and the next button can be clicked. This is the behavior in 1.8.49

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

For the config:

```
{
    "title": "Foo Survey",
    "pages": [{
            "name": "Bar Page",
            "elements": [{
                "type": "rating",
                "name": "Baz Score",
                "title": "Please rate!!!",
                "isRequired": true,
                "hasComment": true,
                "commentText": "Please explain your rating:",
                "rateMin": 0,
                "rateMax": 10,
                "minRateDescription": "Not likely at all",
                "maxRateDescription": "Very likely"
            }],
            "title": "Overall"
        }]
}
```

### Specify your

* browser: chrome
* browser version: 90.0.4430.212
* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: 1.8.50

**Comment by andrewtelnov** [comment]
@bbbco It works for me. Here is [the example](https://plnkr.co/edit/Fc3oq7xcgWMANnJV). 
I have checked [our example](https://surveyjs.io/Examples/Library?id=real-nps&platform=Knockoutjs) in all platforms and themes.

PS: We have several E2E tests on "rating" question.

Thank you,
Andrew

**Comment by bbbco** [comment]
Here's a fork of your example matching what our code looked like when the 1.8.50 release broke ratings:
https://plnkr.co/edit/JnPJgVWgsnCfeBxb

**Comment by bbbco** [comment]
Did a little more looking, and it is now obvious that survey-library 1.8.50 is only compatible with knockout 3.5.x. Anything earlier than that breaks the ratings element.

**Comment by andrewtelnov** [comment]
@bbbco Got it. We moved to knockout 3.5.1 because of SurveyJS Creator some times ago. All our examples and E2E tests using this version.  Could you migrate to v3.5.1?

Thank you,
Andrew

**Comment by bbbco** [comment]
Yes, I was able to migrate to knockout 3.5

Is there some sort of compatibility matrix that needs updated? 


Brian Goad
@bbbco
Creative Analytic Convergence

On June 8, 2021, Pedro Alonso ***@***.***> wrote:
> @bbbco <https://github.com/bbbco> Got it. We moved to knockout 3.5.1
> because of SurveyJS Creator some times ago. All our examples and E2E
> tests using this version. Could you migrate to v3.5.1?
>
> Thank you,
>  Andrew
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/surveyjs/survey-library/issues/2946#issuecomment-
856599241>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAHPWCO2FWJZUVKLIWB7NLTRXM3BANCNFSM46IFJWGA>.

**Comment by andrewtelnov** [comment]
I updated our npm packages and require knockout v3.5.1+

**Comment by bbbco** [comment]
Thank you!

Brian Goad
@bbbco
Creative Analytic Convergence

On June 9, 2021, Pedro Alonso ***@***.***> wrote:
> I updated our npm packages and require knockout v3.5.1+
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/surveyjs/survey-library/issues/2946#issuecomment-
857727967>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAHPWGX3B3AKRUKV73Z76DTR5Y7FANCNFSM46IFJWGA>.
