### ISSUE TITLE
Invisible questions data is not showing?

### ISSUE THREAD

**Issue by nagireddyg** [surveyjs/survey-library#2983]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

 I am few question in the panel and the panel is invisible. I am getting some of the questions data from the panel on completion of the survey, instead of getting all questions data on completion of the survey.

### What is the expected behavior?
I want all the questions data on click of complete button.

### How would you reproduce the current behavior (if this is a bug)?
I am testing in reactjs

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
{
 "title": "Email Testing Survey",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "po_email",
     "title": "PO Email"
    },
    {
     "type": "text",
     "name": "manager_email",
     "title": "Manager Email"
    }
   ]
  },
  {
   "name": "page2",
   "elements": [
    {
     "type": "panel",
     "name": "panel1",
     "elements": [
      {
       "type": "text",
       "name": "to_email",
       "title": "To",
       "hideNumber": true
      },
      {
       "type": "text",
       "name": "bcc_email",
       "title": "BCC",
       "hideNumber": true
      },
      {
       "type": "text",
       "name": "subject_email",
       "title": "Subject",
       "hideNumber": true,
       "defaultValue": "Food and Safety"
      },
      {
       "type": "comment",
       "name": "body_email",
       "title": "Email body",
       "hideNumber": true,
       "defaultValue": "Hi Nagi,\n"
      },
      {
       "type": "boolean",
       "name": "isSendEmail",
       "title": "Send Email?",
       "hideNumber": true,
       "defaultValue": "true",
       "isRequired": true
      }
     ],
     "visible": false,
     "title": "Email Notification",
     "innerIndent": 1
    }
   ]
  }
 ],
 "triggers": [
  {
   "type": "copyvalue",
   "expression": "{po_email} notempty",
   "setToName": "to_email",
   "fromName": "po_email"
  },
  {
   "type": "copyvalue",
   "expression": "{manager_email} notempty",
   "setToName": "bcc_email",
   "fromName": "manager_email"
  }
 ],
 "showProgressBar": "bottom",
 "clearInvisibleValues": "none"
}
```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by nagireddyg** [comment]
<img width="1432" alt="Screenshot 2021-06-16 at 9 43 20 PM" src="https://user-images.githubusercontent.com/23032528/122258345-9149c000-ceee-11eb-8476-faa44a58fe1e.png">

**Comment by nagireddyg** [comment]
<img width="1501" alt="Screenshot 2021-06-16 at 9 46 45 PM" src="https://user-images.githubusercontent.com/23032528/122258457-ae7e8e80-ceee-11eb-8310-ca58bef2ebc6.png">

**Comment by nagireddyg** [comment]
<img width="1518" alt="Screenshot 2021-06-16 at 9 47 08 PM" src="https://user-images.githubusercontent.com/23032528/122258503-ba6a5080-ceee-11eb-8b8b-a7ca52faf670.png">

**Comment by nagireddyg** [comment]
@andrewtelnov I am not getting all the questions data on click of complete button. Where as I am able to see all the questions data in survey creator test tab. You can see above screen shots for your reference. appreciate your help on this. Thank you.

**Comment by nagireddyg** [comment]
<img width="1518" alt="Screenshot 2021-06-16 at 9 47 08 PM" src="https://user-images.githubusercontent.com/23032528/122259809-3022ec00-cef0-11eb-8956-014fd0a129e3.png">

**Comment by nagireddyg** [comment]
<img width="1466" alt="Screenshot 2021-06-16 at 10 13 58 PM" src="https://user-images.githubusercontent.com/23032528/122259897-49c43380-cef0-11eb-80b9-783213e948a4.png">

**Comment by tsv2013** [comment]
You need to set the https://surveyjs.io/Documentation/Library?id=surveymodel#clearInvisibleValues property of your survey to `none`

**Comment by nagireddyg** [comment]
@tsv2013 It is not working as expected because I have assigned null value to **survey.data** . I have removed this null value and then it is working as expected. Thank you.

**Comment by nagireddyg** [comment]
@tsv2013 is it possible to get **only** invisible questions and values on click of complete button?

**Comment by andrewtelnov** [comment]
@nagireddyg You can get all questions as: `survey.getAllQuestions()` every question has read-only boolean property `isVisible`, boolean function `isEmpty()` and read-write property `value`.

Thank you,
Andrew

**Comment by nagireddyg** [comment]
@andrewtelnov Thank you, I have question regarding  **onComplete**,

When I click on complete button, Immediately the page is  showing "Thank you for completing the survey!"  message.

But on click of complete button I am calling post api  and saving the result, but it taking some time to complete the process.

My question is, is there any way we can keep wait the page until we get the response from api and then we can show the Thank you for completing the survey!"  message. And also is it possible to show loading....  show that users can understand something is going on?

**Comment by andrewtelnov** [comment]
@nagireddyg Please read the [following section](https://surveyjs.io/Documentation/Library#storeresults-owndatabase) in docs.

Thank you,
Andrew

**Comment by nagireddyg** [comment]
@andrewtelnov Thank you, it helps.
