### ISSUE TITLE
Totals row not displayed on display mode

### ISSUE THREAD

**Issue by c0nf1ck** [surveyjs/survey-library#2986]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Exporting a matrix with a totals row and **mode** **'display'**, the totals is not displayed

### What is the expected behavior?
Displaying the totals row

### How would you reproduce the current behavior (if this is a bug)?
[https://surveyjs.io/Examples/Library?id=questiontype-matrixdynamic-totals&platform=jQuery&theme=modern](https://surveyjs.io/Examples/Library?id=questiontype-matrixdynamic-totals&platform=jQuery&theme=modern)
Add surveyPDF.mode="display" to the javascript and the exported pdf display total as 0

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by gologames** [comment]
Hello,

We detected that this issue belongs to SurveyLibrary (expressions not calculated in display mode mode). So I carry this issue to corresponding repository

Thanks, Alex
SurveyJS Team

**Comment by andrewtelnov** [comment]
@c0nf1ck @gologames I have fixed the issue. Here is [the related issue](https://github.com/surveyjs/survey-library/issues/2987)

Thank you,
Andrew
