### ISSUE TITLE
Dropdown inconsistent behaviour for dynamic choices

### ISSUE THREAD

**Issue by johnyzv** [surveyjs/survey-library#2994]
We have a scenario in our application where we really need the **dropdown** with _"Choices from web"_ and _"Has other item"_ to behave the same as the static choice **dropdown** when the saved option is not in the list, just to fallback to **Other** option

https://plnkr.co/edit/yW0zr0NIICInDL6a

The main reason for Other is for the pdf export to keep it backwards compatible with old saved surveys

Long version, we migrated some columns for a _matrixdropdown_ from text to dropdown with rest api and obviously there are some old saved surveys where the data is not matched in the new format and I included the _"Has other item"_  for this case, but it's not behaving as we initially tested

![image](https://user-images.githubusercontent.com/1512495/122589432-eb6e9080-d068-11eb-88c6-04a4bb536928.png)

This would be best
![image](https://user-images.githubusercontent.com/1512495/122593761-cc72fd00-d06e-11eb-8411-eeb47c2fafe6.png)

**Comment by andrewtelnov** [comment]
@johnyzv I will take a look. 

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@johnyzv I think we have to ignore the value for the first drodpown. However, it is quite opposite of what you are looking for.
The following code will make the behavior consistent:
```js
var survey = new Survey.Model(json);
survey.storeOthersAsComment= false;
survey.data = { country: "Albania1", country_rest: "Albania1" };
```
If property "storeOthersAsComment" is set to `false`, it means that other comments are stored directly in the value.
If you are fine with this solution than I would love to have the current behavior for a while.

Thank you,
Andrew
SurveyJS Team

**Comment by johnyzv** [comment]
@andrewtelnov Thank you for the help. it works well

One observation is when the api for the second dropdown returns an empty (`[]`) response, this will not work.

https://plnkr.co/edit/ovdoG4HTycN1l5t0

PS: As a workaround we return `[{ name: "N/A" }]` from the api when there are no results

**Comment by andrewtelnov** [comment]
@johnyzv I have fixed the last issue. Here is [the related issue](https://github.com/surveyjs/survey-library/issues/3009).

Thank you,
Andrew

**Comment by johnyzv** [comment]
@andrewtelnov Looks good, Thank you!
