### ISSUE TITLE
passing props not working

### ISSUE THREAD

**Issue by tadiraman** [surveyjs/survey-library#2997]
I use version 1.7.12 and use React.
Here 'optionsCaption' never really works(or not being taken), where as 'completeText' is working when passed any value.
code:
<SurveyJS.Survey
                                ref={el => this.focusFirst(el)}
                                key={appStore.surveySchema.id}
                                model={appStore.surveyModel}
                                completeText={intl.get("MapContainer.submit")}
                                onComplete={this.submitHandler}
                                onValueChanged={this.valueChanged}
                                locale={this.getLang()}
                                optionsCaption={this.getStr()}
                            />}

Am i missing something?

**Comment by andrewtelnov** [comment]
@tadiraman We do not have "optionsCaption" property for Survey model. You can view the list of Survey properties [here](https://surveyjs.io/Documentation/Library?id=surveymodel).

Thank you,
Andrew

**Comment by tadiraman** [comment]
@andrewtelnov thanks for quick reply. That makes sense.
Is there a way we can override the 'optionsCaption'. To give you a little background, i wanted to override this as the language i use (Vietnamese) is not supported in localization. I am super open to add a new localization here by following the steps https://github.com/surveyjs/survey-library/tree/v1.7.12/src/localization

But since there is a bit of urgency, I want to see if a property like 'optionsCaption' can be passed a new value?!

**Comment by andrewtelnov** [comment]
@tadiraman It is better to update the Vietnamese localization and move to the latest version after your changes will be included into master and a new version will be released.
You can do it programmatically, by updating the needed value in localization JSON object, to get the needed string in your version.

Thank you,
Andrew

**Comment by tadiraman** [comment]
@andrewtelnov i have cloned and pushed a change in our account for the vietnamese language. Its not complete though.
https://github.com/sasakiassociates/survey-library

**Comment by andrewtelnov** [comment]
@tadiraman Please make a PR and we will merge it with master. You can make another one later.

Thank you,
Andrew

**Comment by tadiraman** [comment]
thanks a lot! I just did https://github.com/surveyjs/survey-library/pull/3011
let me know once its approved.

**Comment by andrewtelnov** [comment]
@tadiraman Please remove package.json from your PR. I will approved it after you are done.

Thank you,
Andrew

**Comment by tadiraman** [comment]
@andrewtelnov just removed it. thanks!

**Comment by andrewtelnov** [comment]
@tadiraman Sorry, you have removed it completely :-( I mean remove it from PR, please keep it exactly like in our master.
If I merge your PR, our package.json will be removed as well.

Thank you,
Andrew

**Comment by tadiraman** [comment]
@andrewtelnov sorry for the trouble. Here is one without package json https://github.com/surveyjs/survey-library/pull/3012

**Comment by tadiraman** [comment]
@andrewtelnov thanks for merging it! Could you also npm publish? 
I can't really use it unless its published in the npm https://www.npmjs.com/package/survey-react

**Comment by andrewtelnov** [comment]
@tadiraman We are going to release a new version today/tomorrow.

Thank you,
Andrew

**Comment by tadiraman** [comment]
@andrewtelnov that's great, unfortunately its super urgent for us to get this working in few hours.
Let me know if in any another way I can use the latest master?

**Comment by tadiraman** [comment]
thanks for publishing, i can see the latest one now in npm!
