### ISSUE TITLE
onComplete triggered twice or multiple times

### ISSUE THREAD

**Issue by tadiraman** [surveyjs/survey-library#3015]
Here is the react code snippet. Sometimes 'onComplete' gets called twice or multiple times. 
I am using the latest version 1.8.53

<SurveyJS.Survey
                                ref={el => this.focusFirst(el)}
                                key={appStore.surveySchema.id}
                                model={appStore.surveyModel}
                                completeText={intl.get("MapContainer.submit")}
                                onComplete={this.submitHandler}
                                onValueChanged={this.valueChanged}
                                locale={this.getLang()}
                            />

I see this issue happening in the past too
https://github.com/surveyjs/survey-library/issues/679
https://surveyjs.answerdesk.io/ticket/details/t1581/oncomplete-executes-multiple-times

**Comment by andrewtelnov** [comment]
@tadiraman Please change the code as following:
On init survey model
```js
appStore.surveyModel.onComplete.add(this.submitHandler);
```
On render survey
```js
<SurveyJS.Survey
ref={el => this.focusFirst(el)}
key={appStore.surveySchema.id}
model={appStore.surveyModel}
completeText={intl.get("MapContainer.submit")}
onValueChanged={this.valueChanged}
locale={this.getLang()}
/>
```

Thank you,
Andrew

**Comment by tadiraman** [comment]
thanks @andrewtelnov that worked!
Do you know why that issue occurring?

**Comment by andrewtelnov** [comment]
It adds handler to model event on every render.

Thank you,
Andrew

**Comment by tadiraman** [comment]
thanks.
