### ISSUE TITLE
Survey-React: conditional rendering is broken with inline questions

### ISSUE THREAD

**Issue by aanavaneeth** [surveyjs/survey-library#3031]
This particular bug was not there until 1.8.46 but introduced later (may be between 1.8.47 & 1.8.49 and exists in 1.8.53)

If we have two questions in a single line and have have conditional rendering on second question based on first question then that doesn't work. Looks like its happening only on  react library

### Are you requesting a feature, reporting a bug or asking a question?
bug

### What is the current behavior?
not rendering second question

### What is the expected behavior?
rendering second question on selecting 1st/3rd options

### How would you reproduce the current behavior (if this is a bug)?
Add two questions in a single line and have conditional rendering on second question based on first question.  Looks like its happening only on  react library

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/SeXYc4zuRzNf9Uml

### Specify your

* browser: Chrome/Edge
* browser version: Latest
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.8.13

**Comment by aanavaneeth** [comment]
I hope you can fix this in 1.8.54

**Comment by andrewtelnov** [comment]
@aanavaneeth I have added a unit test and e2e test as well on this functionality.

Thank you,
Andrew

**Comment by aanavaneeth** [comment]
is it part of 53? or 54?

**Comment by tsv2013** [comment]
It will be included in 1.8.55

**Comment by tsv2013** [comment]
My bad. It has been included in 1.8.54
