### ISSUE TITLE
Dynamic dropdown with enableIf not displayed correctly

### ISSUE THREAD

**Issue by johnyzv** [surveyjs/survey-library#3039]
This is a complex case in our application, that we solved only by removing the enableIf from matrixdynamic field.

We need to make this matrix add/remove rows open for specific users and also the columns.

For user: "1" displays correctly, for user: "2" does not.

https://plnkr.co/edit/nq4dNpRFoDwhEG13?preview

**Comment by andrewtelnov** [comment]
@johnyzv Sorry, I did not understand what is wrong with the example.
Could you please explain it in more details?

Thank you,
Andrew

**Comment by johnyzv** [comment]
@andrewtelnov Change value for survey data `user: "2"` with `user: "1"`, this is how it is supposed to look

That field value should not interfere with how the dropdown is rendered -> option not selected for both dropdowns

**Comment by andrewtelnov** [comment]
@johnyzv Got it now.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@johnyzv I have fixed it in v1.8.55

Thank you,
Andrew

**Comment by johnyzv** [comment]
@andrewtelnov This is great, when can i test the new version?
Thank you,
Ionut

**Comment by tsv2013** [comment]
Most likely next Tuesday-Wednesday
