### ISSUE TITLE
How to handle the page info (page 1 0f 5) in different languages that are not supported by the library.

### ISSUE THREAD

**Issue by AdityaKallur** [surveyjs/survey-library#3047]
In my case we are supporting Telugu language for one of clients, so I am able to override the PagePrev and other text, but for page info , i am not sure what i can do, as it is a dynamic string,

**Comment by tsv2013** [comment]
This is the localized string - https://github.com/surveyjs/survey-library/blob/master/src/localization/english.ts#L14

**Comment by AdityaKallur** [comment]
yes, I have overridden this string as well, but as this has to function dynamically and library don't support Telugu , the string stays as it is 
![image](https://user-images.githubusercontent.com/83698184/124473314-c7c37e00-ddbc-11eb-8911-2c1ab0c91833.png)

![image](https://user-images.githubusercontent.com/83698184/124473410-eaee2d80-ddbc-11eb-9224-f03fb3ad0328.png)

**Comment by tsv2013** [comment]
>library don't support Telugu

You can add custom localization by this guide https://github.com/surveyjs/survey-library/tree/master/src/localization

**Comment by AdityaKallur** [comment]
You mean to say to add the entire localization for Telugu right, we have few other languages to support , so do we need to add for all those.

**Comment by AdityaKallur** [comment]
But i am using only 6 strings from the localization, 5 of them i have overridden only 1 this page info, even that is also overridden but its not working as expected, so adding the entire  file or overriding the wanted string, is there any difference.?

**Comment by tsv2013** [comment]
Sorry, but I don't understand what's wrong with the following images
![image](https://user-images.githubusercontent.com/3013415/124548280-2da01c00-de36-11eb-81a8-63772ecf14c1.png)
![image](https://user-images.githubusercontent.com/3013415/124548326-3c86ce80-de36-11eb-8938-d568d30e6921.png)

**Comment by AdityaKallur** [comment]
the first number , which should be 2 is not changing, and also observe the below images which is in simplified Chinese.
I know the library supports this language, but as keys were different for library and our application(zn-CH, zn-ch), currently this is also overridden with "第 {​​​​​​​​0}​​​​​​​​ 页 共 {​​​​​​​​1}​​​​​​​​页" , but this doesn't changes as we move to the next page.

![image](https://user-images.githubusercontent.com/83698184/124550804-df4b4700-de4e-11eb-96ff-05a50559a71b.png)

![image](https://user-images.githubusercontent.com/83698184/124550881-fc801580-de4e-11eb-9042-3d83473d2437.png)

**Comment by AdityaKallur** [comment]
For Telugu, it is working now, the closing bracket was missing in the string. once i add that,  it started working, but few languages like Italian, simplified Chinese , they have the proper string with two place holders ({0} {1}), still its not working, i need your help on this to sort it out. Thanks.

**Comment by tsv2013** [comment]
The same code works for the all languages to fill a string with placeholders. If it works for one language it should work for the others. Can you check your string or share a minimal live sample illustrating the issue?

**Comment by AdityaKallur** [comment]
Issue is resolved Thanks
