### ISSUE TITLE
Default / implicit validation rules for closed questions

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#3051]
### Are you requesting a feature, reporting a bug or asking a question?
Feature / question

### What is the current behavior?
Survey validation for a radioquestion does not fail validation if a different value is set via JS.

### What is the expected behavior?
Similar to the `required` attribute I would expect default validation to happen for closed questions based on their configuration; things that come to mind:
1. All choices are valid
2. Number of choices >= min required choices
3. Number of choices <= max required choices

Currently if I want to validate a survey that I load with data I need to resort to something like this:
```json
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question1",
     "isRequired": true,
     "validators": [
      {
       "type": "expression",
       "expression": "{question1} anyof ['item1', 'item2', 'item3']"
      }
     ],
     "choices": [
      "item1",
      "item2",
      "item3"
     ]
    }
   ]
  }
 ]
}
```
Which defeats the purpose of reusing the survey structure to do validation of other data (since now users still have to define obvious validation rules essentially coding their choices twice).

I'm not proposing preventing any setting of data, just that `survey.hasErrors()` should return false if there are questions with invalid data due to their implicit question type.

**Comment by andrewtelnov** [comment]
@SamMousa We have property "maxSelectedChoices" and it doesn't to allow select more then X choices. It doesn't produce any error.
I guess, you are looking for something like in [this example](https://plnkr.co/edit/ir6qxO1ffYTKDyHy).

Thank you,
Andrew

**Comment by SamMousa** [comment]
Yeah exactly! To get an error (visual or in javascript code) we must add a validator explicitly.
But as a user I'd expect some of these validators to be the default. With closed questions, like your example, it's even worse.

The validation will pass if I set data like this: https://plnkr.co/edit/pyMxvpULNr4HadpE

**Comment by andrewtelnov** [comment]
@SamMousa Please use the following function:
[`survey.clearIncorrectValues(true);`](https://surveyjs.io/Documentation/Library?id=surveymodel#clearIncorrectValues)
Here is [your updated example](https://plnkr.co/edit/HB27B5XL27HXHtw4).

Thank you,
Andrew

**Comment by SamMousa** [comment]
Hmm, that'll work. Thanks!
