### ISSUE TITLE
Text validator validates empty string

### ISSUE THREAD

**Issue by mwrouse** [surveyjs/survey-library#3065]
### Are you requesting a feature, reporting a bug or asking a question?
Question? Bug?

### What is the current behavior?
If you have a texfield with validation (minimum length) then when you start the survey, you are able to complete the survey since these values are empty.

However, if you type in the textfield, you can't undo that action after the value has been set. Erasing the contents of the textfield won't allow it to pass validation anymore.

### What is the expected behavior?
I would expect that if a _question is not marked as required, that it should be able to pass validation without having a value set_. 

Even if you set the value, but then later change the value (e.g. a textfield with minimum length validation), it should not hold up the survey unless marked as required.

> It appears that if you have a minimum count on a checkbox then it essentially makes it required. You can't complete the survey until that minimum requirement is met. Even though the question is not marked as required https://jsfiddle.net/mwrouse/qzfw87hL/4/

### How would you reproduce the current behavior (if this is a bug)?
Make a survey with a textfield that has a minimum length > 0

Run the survey, don't set any values and you will be able to complete the survey. 

Run the survey again, type in the textbox field, and click out of the field. Then if you erase the contents you will fail the minimum length validation.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://jsfiddle.net/mwrouse/abo3eLdk/5/

Test code

```javascript

var json = {
 "completedHtml": "<p><h4>Thank you for sharing this information with us.</h4></p><p>Your name is: <b>{name}</b></p><p>Your email is: <b>{email}</b></p><p>This information is not in the survey data result:<b> {tempvar}</b></p>",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "question1",
     "validators": [
      {
       "type": "text",
       "minLength": 500000,
       "maxLength": 0,
       "allowDigits": true
      }
     ]
    }
   ],
   "title": "Type, Click Out, and Erase = Failed Validation"
  }
 ],
 "triggers": [
  {
   "type": "setvalue",
   "setToName": "name",
   "setValue": "Jon Snow"
  },
  {
   "type": "setvalue",
   "setToName": "email",
   "setValue": "jon.snow@nightwatch.com"
  },
  {
   "type": "setvalue",
   "setToName": "tempvar",
   "setValue": "You have decided to use your current information.",
   "isVariable": true
  },
  {
   "type": "setvalue",
   "setToName": "name"
  },
  {
   "type": "setvalue",
   "setToName": "email"
  },
  {
   "type": "setvalue",
   "setToName": "tempvar",
   "setValue": "You have decided not to use your current information.",
   "isVariable": true
  }
 ]
};

window.survey = new Survey.Model(json);
survey.checkErrorsMode = 'onValueChanged';
survey.render("surveyElement");
```

### Specify your

* browser: Chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: 1.8.55

**Comment by mwrouse** [comment]
Just checking this programmatically with the textfield.

Doing `survey.setValue('question1', '')` does nothing to fail the validation. I assume once you erase the textfield then it is equivalent to `''`. 

But if I do: 
```javascript
survey.setValue('question1', 'hey'); // Has minimum length 50000
survey.setValue('question1', '');
```
It will fail validation when the survey is rendered.

**Comment by andrewtelnov** [comment]
@mwrouse We do not validate a question value if it is empty. However, entering the empty string should make the question value empty. I will take a look.

Thank you,
Andrew

**Comment by mwrouse** [comment]
@andrewtelnov I assume that is the case, since erasing the contents of a textbox will result in an empty string. And doing it programmatically shows that.

I also assume this is exists for textfields and such. 


https://jsfiddle.net/mwrouse/qzfw87hL/4/ Shows that at least the checkbox questions are getting validated (on complete) when there is nothing set.

Thanks for your quick help!

**Comment by andrewtelnov** [comment]
@mwrouse I found an old unit case where text validator returns error on checking an empty string.
I have corrected it and added a new unit test.
The fix will be available as well in v1.8.56.

Thank you,
Andrew

**Comment by mwrouse** [comment]
Thanks, I'm glad these are turning out to be rather easy, looks like that one was just a little logic error.

Should I open another bug for this:
> It appears that if you have a minimum count on a checkbox then it essentially makes it required. You can't complete the survey until that minimum requirement is met. Even though the question is not marked as required https://jsfiddle.net/mwrouse/qzfw87hL/4/

Or is that, for some reason, intended behavior?

**Comment by andrewtelnov** [comment]
@mwrouse I am not sure about this one. I am afraid that some people is already used to have the current behavior.
However, I agree, it is not consistent. Do you have an issue with the current behavior?

Thank you,
Andrew

**Comment by mwrouse** [comment]
We produce an enterprise software, on one part of it they have the ability to create custom surveys. It's still in preview and has not been fully released yet.
So yes, I'm sure in the future we will have issues.

There is nothing clear that makes it known that setting a validation requirement like that means that the question becomes required.

It would be a breaking change if introduced, but it would obviously make it more consistent. If you need the question to be answered, you have to mark it as required.

**Comment by andrewtelnov** [comment]
@mwrouse I have checked unit tests and we do not have any unit case that checks answer count validator against an empty array. It means that I could make the changes. Here is [the related issue](https://github.com/surveyjs/survey-library/issues/3069).

Thank you,
Andrew

**Comment by mwrouse** [comment]
@andrewtelnov Just to confirm, but the fix you added will apply to all questions that have any kind of textfield for the input right? Comment and as well as multiple text?
