### ISSUE TITLE
Do not run answer count validator on empty array

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#3069]
We should not check min/max answers on checkbox question if an user doesn't check anything. If the question is not required then we should acceopt an empty value regardless of this validator. Answer count validator should work for non-empty array only.

**Comment by mwrouse** [comment]
Andrew mentioned this in the other issue, but I'll include this link here:
https://jsfiddle.net/mwrouse/qzfw87hL/5/

That link demonstrates that if you have a checkbox question, adding a minimum count validation essentially does the same thing as marking the question as required. 

Complete the survey without selecting anything and you will get a validation error.
