### ISSUE TITLE
Cannot find module 'src/vue/base' or its corresponding type declarations.

### ISSUE THREAD

**Issue by esune** [surveyjs/survey-library#3084]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
Build fails with the following error:
```
#13 30.50 ERROR in /app/node_modules/survey-vue/survey.vue.d.ts(11,25):
#13 30.50 11:25 Cannot find module 'src/vue/base' or its corresponding type declarations.
#13 30.50      9 |
#13 30.50     10 | import Vue from "vue";
#13 30.50   > 11 | import { BaseVue } from "src/vue/base";
#13 30.50        |                         ^
#13 30.50     12 | export { VueSurveyModel as Model };
#13 30.50     13 | export { VueSurveyWindowModel as WindowModel };
#13 30.50     14 |
```

### What is the expected behavior?
Build should succeed without errors. The last version I can complete a build without errors with seems to be `1.8.52`.

### How would you reproduce the current behavior (if this is a bug)?
Add `survey-vue` to your Typescript project dependencies and start a build.

#### Provide the test code and the tested page URL (if applicable)
N.A.

### Specify your

* browser: N.A.
* browser version: N.A.
* surveyjs platform (angular or react or jquery or knockout or vue): `Vue`
* surveyjs version: `1.8.56`

**Comment by dmitrykurmanov** [comment]
I'll check it

**Comment by dmitrykurmanov** [comment]
I've created the [vue-typescript-example](https://github.com/surveyjs/vue-typescript-example) project generated by the standard vue-cli and can't manage to reproduce the problem. This is strange because we really have that wrong import in our code.

Anyway I believe that we've fixed it via the https://github.com/surveyjs/survey-library/commit/260bfdd5756d34b23232a075606e2762078cf97f

**Comment by esune** [comment]
Thank you @dmitrykurmanov 

For reference, [this](https://github.com/bcgov/issuer-kit/blob/master/issuer-web/package.json#L21-L22) is the `package.json` of the app that is breaking with anything greater than `1.8.52`.
