### ISSUE TITLE
When refreshing the page, others isn't cleared

### ISSUE THREAD

**Issue by aammh** [surveyjs/survey-library#3172]
### Are you requesting a feature, reporting a bug or asking a question?
question

### What is the current behavior?
After refreshing the survey (when it is completed) using clear and render, the question that has others selected doesn't get cleared, even though all other questions are cleared. Taking the survey again and also choosing others, the text from before is still there.

### What is the expected behavior?
When others is selected and there is some text, it should be cleared when the survey refreshes (completed).

### Specify your

* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.8.57

**Comment by andrewtelnov** [comment]
@aammh I have fixed it in v1.8.60 by the commit above.

Thank you,
Andrew
