### ISSUE TITLE
Setting properties like `pageNextText` does not rerender buttons

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#3175]
### Are you requesting a feature, reporting a bug or asking a question?
Bug / feature

### What is the current behavior?
Setting button texts during the survey does not rerender the buttons.

### What is the expected behavior?
I'd expect these changes to these properties to be reflected directly, similar to how setting `locale` would rerender the buttons.
Alternatively, if this is not supported I'd expect an error when this is changed while the survey is running.

### How would you reproduce the current behavior (if this is a bug)?
Run this code in your developer tools, assuming the survey instance is stored in`survey`:

`survey.pageNextText = 'Next(13)';`

### Specify your

* browser: n/a
* browser version:  n/a
* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: 1.8.59

**Comment by andrewtelnov** [comment]
@SamMousa I have fixed it in v1.8.60 by the commit above.

Thank you,
Andrew
