### ISSUE TITLE
Set values to other questions on change of dropdown

### ISSUE THREAD

**Issue by nagireddyg** [surveyjs/survey-library#3183]
### Are you requesting a feature, reporting a bug or ask a question?

question

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

  {
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "dropdown",
     "name": "location",
     "isRequired": true,
     "renderAs": "select2",
     "choicesByUrl": {
      "url": "https://api/all",
      "valueName": "location_id",
      "titleName": "location_id"
     },
     "optionsCaption": "Select a location..."
    },
    {
     "type": "text",
     "name": "region"
    },
    {
     "type": "text",
     "name": "group"
    },
    {
     "type": "text",
     "name": "district"
    }
   ]
  }
 ]
}




**API response is below:**
[
  {
    "location_id": "1111",
    "region": "100",
    "group": "102",
    "district": "131"
  },
  {
    "location_id": "2222",
    "region": "222",
    "group": "22",
    "district": "2"
  },
  {
    "location_id": "3333",
    "region": "333",
    "group": "33",
    "district": "3"
  }
]
```

### Specify your

* browser:
* editor version:

**Comment by tsv2013** [comment]
You can use the `setValue` trigger as described in documentation https://surveyjs.io/Documentation/Library?id=LibraryOverview#triggers

**Comment by nagireddyg** [comment]
@tsv2013 
Hi, I don't think so setValue will work here, how can i get region, group, district value on change of the location dropdown with the example I have mentioned above. When I change the dropdown I am getting only location_id values, but I need region, group and district values also.

**Comment by tsv2013** [comment]
You can subscribe the https://surveyjs.io/Documentation/Library?id=surveymodel#onValueChanged event, get the selected value and set several other values depending on it

**Comment by nagireddyg** [comment]
@tsv2013 the selected value has only location_id, how can I get other fields data onValueChanged event?

**Comment by nagireddyg** [comment]
@tsv2013 Can you please help me on this?

**Comment by tsv2013** [comment]
Sorry for delay.

You can use the `attachOriginalItems: true` option and then access all properties from the original item loaded from your service:
```JS
survey
    .onValueChanged
    .add(function (sender, options) {
        debugger;
        if(options.name == "country") {
            var originalItem = Survey.ItemValue.getItemByValue(options.question.visibleChoices, options.value).originalItem;
            survey.getQuestionByName("a2code").value = originalItem.alpha2Code;
            survey.getQuestionByName("a3code").value = originalItem.alpha3Code;
        }
    });
```

Here is the full working sample - https://plnkr.co/edit/vYYNBWb3yoFjT8S4
