### ISSUE TITLE
When and after going to a previous page, the transition between pages is not smooth anymore (react)

### ISSUE THREAD

**Issue by FHourmy** [surveyjs/survey-library#3198]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
On a survey if i answer a question, then go back the content disappear for a brief time, moving the buttons to the top, then the content reappears, this makes some kind of flickering. This effect persist on all page already visited but not on first render

Tthis comportment appeared in version 1.8.57 from what i have tested.

### What is the expected behavior?
When navigating through already answered pages, the transition should stay smooth

### How would you reproduce the current behavior (if this is a bug)?
Start a survey. 
anwser the first question.
press back => flickering
press next => flickering again

#### Provide the test code and the tested page URL (if applicable)

https://codesandbox.io/s/surveyjs-pose-test-forked-vn3z9?file=/src/index.js
Test code

```
const model = new Survey.Model(questions);
const Example = () => <Survey.Survey id="survey" model={model} />;

ReactDOM.render(<Example />, document.getElementById('root'));
```

### Specify your

* browser: chrome
* browser version: 92.0.4515.131
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.60

**Comment by andrewtelnov** [comment]
@FHourmy It is fixed by the commit above
