### ISSUE TITLE
how to set a value from several questions into another one

### ISSUE THREAD

**Issue by Vladqqqqoo** [surveyjs/survey-library#3209]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

How can I implement next solution via JSON config (without adding a code and using different surveyjs events like "onSurveyChange" etc):
I want to be a value of question 3 is combination of question1 and question2.
For example if question1 is "Hello" and questions2 is "World" I want to be question3's value is "Hello World"
And I want to be it dynamically - calculated based on question 1 and question 2 current values.

### What is the current behavior?
I'm trying to use triggers,but the both replace each other's value.

### What is the expected behavior?
Use one trigger and define in "fromName" field several questions or something like this?
OR
Uuse several triggers but result should be a combination of both results?
OR 
Any others solutions which help to implement asked feature.

### How would you reproduce the current behavior (if this is a bug)?
Use attached json via https://surveyjs.io/create-survey and see test results

#### Provide the test code and the tested page URL (if applicable)

Test code

```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "question1"
    },
    {
     "type": "text",
     "name": "question2"
    },
    {
     "type": "text",
     "name": "question3"
    }
   ]
  }
 ],
 "triggers": [
  {
   "type": "copyvalue",
   "expression": "{question1} notempty",
   "fromName": "question1",
   "setToName": "question3"
  },
  {
   "type": "copyvalue",
   "expression": "{question2} notempty",
   "fromName": "question2",
   "setToName": "question3"
  }
 ]
}

```

### Specify your

* browser: Firefox
* browser version: 78.13.9esr(64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: any

**Comment by tsv2013** [comment]
You can use a calculated value (https://surveyjs.io/Documentation/Library#calculatedvalues) as shown in this live sample on our https://surveyjs.io/Examples/Library/?id=survey-calculatedvalues

**Comment by andrewtelnov** [comment]
@Vladqqqqoo You can use run expression trigger.
```js
  {
   "type": "runexpression",
   "expression": "{question1} notempty or {question2} notempty",
   "runExpression": "{question1} + {question2}",
   "setToName": "question3"
  }
```
Here is [the example](https://plnkr.co/edit/uoELbBudNuouDNzZ).

Thank you,
Andrew

**Comment by Vladqqqqoo** [comment]
@andrewtelnov Thank you a lot!
Best regards.
