### ISSUE TITLE
Programmatically create a full response model

### ISSUE THREAD

**Issue by seeker25** [surveyjs/survey-library#3306]
Currently going into Test Survey under the Survey Editor seems to be the only way (that I know of) to create a JSON response (can be non-complete, depending on conditions):

I know for example if some questions are a certain type, or if they are hidden, they aren't included in the response.. 

![image](https://user-images.githubusercontent.com/3484109/132763496-2a5c0ec9-b823-40c0-b164-56fcc999874b.png)

This is being stored as JSON in the database, not breaking it down into some sort of models. This allows for greater flexibility.

**Is it possible to programmatically create a full response that fills in all of the questions with data? That way we could convert this data to a JSON schema or Typescript models?**

If a survey is massive, coming up with the response model is quite time consuming and prone to human error.

**Comment by tsv2013** [comment]
To get responses you can simple use the `data` property of a survey:
```JS
var result = survey.data
```

https://surveyjs.io/Documentation/Library?id=surveymodel#data

**Comment by seeker25** [comment]
`var result = survey.data`

Will not provide a "full" response model. It is conditional based on the questions that are answered, that aren't hidden etc.

**Comment by seeker25** [comment]
I was hoping there was a better way, that could be done at build time. I don't think that's possible considering SurveyJS runs in the browser though.

**Comment by seeker25** [comment]
Apparently it's possible in Node via CLI:

```
import * as Survey from "survey-core";
import { readFileSync } from "fs";
const json = readFileSync(
  "survey-primary.json"
).toString();

//Add custom question components, if they are used by your survey.
const survey = new Survey.SurveyModel(json);

console.log("Generating possible question response types");
survey.getAllQuestions().forEach(function(question) {
  //survey.setValue(question.name, "test"); This is slow, but generates the correct model.
  console.log(`${question.name} - ${question.getType()}`);
});

//console.log(JSON.stringify(survey.data, null, "\t")); Can be used to display survey data.
```
