### ISSUE TITLE
Add properties to customize File Question string constants

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-library#3315]
Based on https://surveyjs.answerdesk.io/ticket/details/t7696/extend-file-upload-to-only-accept-images

**Comment by HenriTroyot** [comment]
It seems that the API members declared using decorators are not added to the pme.json file and do not appear in the docs.  
"@property({ defaultValue: surveyLocalization.getString("confirmRemoveFile") }) confirmRemoveMessage: string;"
