### ISSUE TITLE
Async expression validators don't focus element when false at validation

### ISSUE THREAD

**Issue by FHourmy** [surveyjs/survey-library#3343]
### Are you requesting a feature, reporting a bug or asking a question?
Bug (maybe feature ?)

### What is the current behavior?
In an async expression validator if the expression is false, survey won't scroll to the element on validation

### What is the expected behavior?
On validation, the page should scroll up to the element with the invalid expression validator

### How would you reproduce the current behavior (if this is a bug)?
create a survey with an element with an expression validator calling an async function with this.returnResult(false);,
scroll down the page, press the complete button.

#### Provide the test code and the tested page URL (if applicable)
https://codesandbox.io/s/sparkling-flower-tdkbq?file=/index.js

### Specify your

* browser: chrome / FF
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.8.67

**Comment by andrewtelnov** [comment]
@FHourmy I guess, we do not focus question if errors come from async. I will check and come back.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@FHourmy It is fixed by the commit above.

Thank you,
Andrew
