### ISSUE TITLE
[Question] only show next button in navigation?

### ISSUE THREAD

**Issue by swuecho** [surveyjs/survey-library#3346]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

showNavigationButtons can control the position of navigation buttons. But how to hide the 'Prev' button? 

in some cases, like skiptrigger, hide the Prev button is necessary. 
Actually, in some surveys, client do not want respondent to change their answer.

**Comment by andrewtelnov** [comment]
@swuecho You can set `survey.showPrevButton = false;`

Thank you,
Andrew

**Comment by swuecho** [comment]
awesome! thanks!
