### ISSUE TITLE
Dropdown question type not showing when used in Display mode

### ISSUE THREAD

**Issue by stuttskl** [surveyjs/survey-library#3347]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Dropdown question type not showing in SurveyJS display mode

### What is the expected behavior?
Showing disabled dropdown/select

### How would you reproduce the current behavior (if this is a bug)?
Using SurveyJs creator everything is working as expected

JSON: 
```
{
    "type": "dropdown",
    "name": "_sc803nhle",
    "choices": [
        "A",
        "B",
        "C",
        "D",
    ],
}
```

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/create-survey

Test code

```
import { Survey as SurveyRenderer, SurveyModel } from 'survey-react'
.
.
.
pages = {
    "type": "dropdown",
    "name": "_sc803nhle",
    "choices": [
        "A",
        "B",
        "C",
        "D",
    ],
}

.
.
.
render() {
    return (
         <SurveyRenderer json={pages} mode="display" onAfterRenderQuestion={this.onAfterRenderQuestion} />
    )
}
```

### Specify your

* browser: Chrome
* browser version: Version 93.0.4577.82 (Official Build) (x86_64)
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: "survey-react": "^1.8.64",

**Comment by andrewtelnov** [comment]
@stuttskl Answered in [SurveyJS support forum](https://surveyjs.answerdesk.io/ticket/details/T7761).
Duplicated ticket.

Thank you,
Andrew
