### ISSUE TITLE
text question dataList can return undefined

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#3378]
The following JSON will generate exception on rendering, if survey.locale is not "fr". text question "dataList" property will return undefined instead of empty array.
```js
{
 elements: [  {
     "type": "text",
     "name": "Question1",
     "dataList": {
      "fr": [
       "French DL-1, French DL-2"
      ]
     }
    } ]}
```

**Comment by tsachinn07** [comment]
Hi Andrew,

Can you please also verify that dataList is not getting saved in translation tab when saved from the designer tab, only for the default language.

**Comment by andrewtelnov** [comment]
@tsachinn07 Sorry, I did not get it. What should we check? Please provide the steps.

Thank you,
Andrew

**Comment by tsachinn07** [comment]
Try to enter dataList in any single input on the designer page. And then navigate to the translations Tab. You will see that datalist field is not updated.
It's happening only for the default language.

**Comment by andrewtelnov** [comment]
@tsachinn07 I have fixed it.

Thank you,
Andrew

**Comment by AbhishekKS** [comment]
Hi Andrew,
I was just checking this fix on the test website. Now on the Translation tab, we can have a multi-line for the data list field, which seems fine. But in some scenarios, on the translation tab, when I manipulate these data list fields for different languages, the JSON breaks as below (newline **\n** character gets appended). Because of this on language change on the designer tab, the data list field is not populated for the single input field.

_{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "question1",
     "dataList": {
      **"default": "A\nB\nC\nD\nE",
      "ca": "M\nN\nO\nP\n"**
     }
    }
   ]
  }
 ]
}_


Thanks
Abhishek

**Comment by andrewtelnov** [comment]
@AbhishekKS Could you please help me with this scenarios? I would love to fix them.

Thank you,
Andrew

**Comment by AbhishekKS** [comment]
Hi @andrewtelnov ,

Below are the steps to reproduce this issue:

1) Add a single input question on the designer page on page1.

2) Next move to the translation tab and input the below values or any other values for English and for any other language, say Catala here, in the data list field for Question1.

![image](https://user-images.githubusercontent.com/13827554/135130488-c452ebc9-d942-4d2a-b81f-dca703eaa985.png)

3) Next move to the JSON Editor tab to check the JSON structure. At this point the JSON structure seems properly formed as shown below:
![image](https://user-images.githubusercontent.com/13827554/135130619-263ba3b9-b6bb-4d33-8042-6aec11c1ecf1.png)

3) Now move back again to the translation tab and then again go back to the JSON editor tab. At this point I see the JSON structure has broken as shown below:
![image](https://user-images.githubusercontent.com/13827554/135131114-ed4eeff2-5ce5-4e89-a1e9-83ecb0a36ee3.png)

**Please Note:** If only the data list field for the default language (EN) is filled, this issue does not occur. It's only when I provide data list translations for additional languages alongwith. Also, the JSON seems to get broken only when I revisit the translations tab after providing translations on an earlier visit.

Thanks
Abhishek

**Comment by andrewtelnov** [comment]
@AbhishekKS I have fixed the issue. [Here is the cause of the problem](https://github.com/surveyjs/survey-library/issues/3394).

Thank you,
Andrew
