### ISSUE TITLE
Placeholder of textinput is not getting set properly from json

### ISSUE THREAD

**Issue by tsachinn07** [surveyjs/survey-library#3380]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
From Json placeholder is not localized.

### What is the expected behavior?
From Json placeholder should get localized.

### How would you reproduce the current behavior (if this is a bug)?
https://plnkr.co/edit/Cj8SWC0DhB9CWjLC

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsachinn07** [comment]
Hi,
When I placed the locale key before pages in JSON, then it's working fine. 
It seems an issue, It should work irrespective of the placement of the key in JSON.

Thanks,
Sachin

**Comment by andrewtelnov** [comment]
@tsachinn07 I have fixed the issue in v1.8.69 when fixed [this issue](https://github.com/surveyjs/survey-library/issues/3374).
I have added a new unit test for this case, for regression testing.

Thank you,
Andrew
