### ISSUE TITLE
 User is not able to see the Full answer in submitted surveys or on the preview screen

### ISSUE THREAD

**Issue by tsachinn07** [surveyjs/survey-library#3387]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
The user is not able to see the Full answer in submitted surveys or on the preview screen
This means when questions are in disabled/readonly state.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/16122986/135047700-651be7e0-ef5d-4fe1-b5ff-c20eeadc8d2a.png)

### What is the expected behavior?
User should be able to view his whole answer even in disabled form.

### How would you reproduce the current behavior (if this is a bug)?
View the givens answers in readonly form in mobile.

For this, we can show the answers in spans or div rather than inputs. Here div or span can look like disabled inputs.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by tsv2013** [comment]
The text question is rendered via the `INPUT` HTML which is single line by it's nature

You can use comment question that allow multi line input with conjunction with the `autoGrowComment: true` option as sown in this plunker sample - https://plnkr.co/edit/q3Ai1OCU6gpvkqde

**Comment by tsachinn07** [comment]
Yes, I do understand that a single input act as a single line. But in our case when the user has submitted his survey and wants to check the answers that he has submitted, at that time inputs are in disabled form. In browser, by selecting the text we can the see the answers, but iPhones users are not able to select the text of disabled inputs. Therefore we need a way, where the user can see his whole answer. 

So single input creates a problem at that time. So is there a way, that in the disabled state, instead of single inputs we can show the answers in other HTML tags.

Thanks,
Sachin Tiwari

**Comment by tsachinn07** [comment]
Will it work for single inputs as well?

**Comment by tsachinn07** [comment]
Okay, So are we planning to provide any api for single inputs.

**Comment by tsv2013** [comment]
@tsachinn07 Right now - no. This task is in our queue. Our resources are busy with Creator V2 public beta preparations.

**Comment by Lionqueen94** [comment]
Is it possible to add a css class to the textarea div? I would like to add `white-space: break-spaces` since a text with newlines will become one long paragraph when converted to a div.

**Comment by andrewtelnov** [comment]
@Lionqueen94 Do you mean to add a class to comment question?
You can find several examples in [this section](https://surveyjs.io/Examples/Library?id=survey-cssclasses).

Thank you,
Andrew

**Comment by Lionqueen94** [comment]
> @Lionqueen94 Do you mean to add a class to comment question? You can find several examples in [this section](https://surveyjs.io/Examples/Library?id=survey-cssclasses).
> 
> Thank you, Andrew

@andrewtelnov Hi Andrew, what I mean is that when I try to add a css class to the comment field, it does not seem to show up. Look at this Plunker. I add a class to comment (or at least I'm trying to do that) to make sure that the rendered text in the div actually shows newlines, but I am unsuccessful. https://plnkr.co/edit/GcS9dYkhcFRy8Sz8

**Comment by andrewtelnov** [comment]
@Lionqueen94 I have a strong feeling that we need to add this CSS rule out of the box. @tsv2013 @dk981234 Could you please take a look at it?

Thank you,
Andrew

**Comment by Lionqueen94** [comment]
> @Lionqueen94 I have a strong feeling that we need to add this CSS rule out of the box. @tsv2013 @dk981234 Could you please take a look at it?
> 
> Thank you, Andrew

Is there any update on adding the `white-space: break-spaces` css rule to the divs @tsv2013 @dk981234? Thanks in advance!

**Comment by tsv2013** [comment]
@Lionqueen94 It's in our task list. We'll wotk on it after Creator V2 design issues task.

**Comment by JaneSjs** [comment]
Hello Everyone,
Please be informed that we redesigned the read-only/disabled state rendering for Form Library elements. Now, the text of a read-only single-line text input can be selected. Please refer to the following demo: [Read-Only / Display Mode](https://surveyjs.io/form-library/examples/prevent-form-editing-with-read-only-mode/).

I would recommend that you check to see if the updated read-only mode fits your needs. 

Should you have any further questions, please feel free to submit another GitHub issue.

Thank you
