### ISSUE TITLE
The following question is about sharing values in two 'matrix dynamic' and setting up a 'default value'

### ISSUE THREAD

**Issue by iyamusms** [surveyjs/survey-library#3447]
### Are you requesting a feature, reporting a bug or asking a question?
- Asking questions

### What is the current behavior?
- I'm trying to share the values between each matrix dynamic. On the website, however, examples are given of 'matrix dynamic' and 'panel dynamic' questions. Based on the previous response, in the below codes, only titles selected as 'Yes' on the next page are included.
- In case of 'defaultValue' in first 'matrix dynamic' under 'surveyQuestions ', I am confused as to how to integrate data/objects from API with surveyQuestions JSON. If I grab the data 'initialData' 'from API like this, how do I integrate with 'defualtValue'? 
```
const intialData = [
            {
             title: 'TestTitle3 ',             
             description:
                'This is test value3.',           
            },   
           {
             title: 'TestTitle4',             
             description:
                'This is test value4.',           
            },                  
          ],          
```

Could you please guide me through these questions? 

```
export const surveyQuestions = {
  pages: [
    {
      name: 'Test Matching',
      elements: [       
        {
          type: 'matrixdynamic',
          name: 'matrix_1',
          valueName: 'sharedList',
          defaultValue: [
            {
             title: 'TestTitle1 ',             
             description:
                'This is test value1.',           
            },   
           {
             title: 'TestTitle2',             
             description:
                'This is test value2.',           
            },                  
          ],          
          columns: [
            {
              name: 'title',
              title: Title',
              cellType: 'text',
              readOnly: true,
            },           
            {
              name: 'description',
              title: 'Description',
              cellType: 'comment',
              readOnly: true,
            },    
           {
              name: 'match',
              title: 'Is title match with your title (Y/N)',
              cellType: 'dropdown',
            },      
          ],
          choices: [
            {
              value: 'Yes',
              text: 'Yes',
            },
            {
              value: 'No',
              text: 'No',
            },
          ],
          rowCount: 2,
        },
      ],
    },
    {
      name: 'Shared Input',
      elements: [
        {
          type: 'matrixdynamic',
          name: 'question1',
          valueName: 'sharedList',
          defaultValue:[
          {
              "shared_title": "{sharedList.title}" <-------- this value is shown in the columns
           }
          ],
          columns: [
            {
              name: 'shared_title', // <------------------ Rows with titles matching 'Yes' in sharedList are need to be displayed
              title: 'Title',
              cellType: 'text',
              readOnly: true,
            },           
            {
              name: 'details',
              title: 'Other Details',
              cellType: 'comment',
            },
          ],        
          rowCount: 0,
        },
      ],
      title:
        'Input the detail.',
    },
  ],
  showQuestionNumbers: 'off',
};
```

### What is the expected behavior?
- Sharing values in two 'matrix dynamic'.
- Integrating data with 'surveyQuestions '

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Firefox
* browser version: 92.0.1
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 17.0.2

**Comment by andrewtelnov** [comment]
@iyamusms There are several errors in your code. The main one, you can't use the shared data for your questions, because these questions have different data now. It means you have to stop using same valueName for them. The second, you need to get one question and not the list, survey.getQuestionByName() instead of "getQuestionsByValueName". This function returns the list of questions with valueName. You are setting value property to an array.
Here is the [updated example](https://plnkr.co/edit/JvYX7pWCm817upq1).

Thank you,
Andrew

**Comment by iyamusms** [comment]
Thank you so much! @andrewtelnov  You're a hero!
