### ISSUE TITLE
Cannot find module knockout

### ISSUE THREAD

**Issue by MrKrabat** [surveyjs/survey-library#3461]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Compiler is crashing with survey-angular 1.8.71. The older version 1.8.68 was working fine.
```
Error: node_modules/survey-angular/survey.angular.d.ts:9:21 - error TS2307: Cannot find module 'knockout' or its corresponding type declarations.

9 import * as ko from "knockout";
```

### What is the expected behavior?
Compiler should not crash

### How would you reproduce the current behavior (if this is a bug)?
Use survey-angular and compile your project.

### Specify your

* browser: Chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: 1.8.71

**Comment by Chamithfernando** [comment]
if you are using latest angular versions please use **survey-angular-ui** instead of survey-angular.
