### ISSUE TITLE
Width of column is not applied in matrix dynamic with horizontal scroll

### ISSUE THREAD

**Issue by iyamusms** [surveyjs/survey-library#3487]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question.

### What is the current behavior?
I applied horizontal scroll to 'matrix dynamic'. I applied horizontal scroll to 'matrix dynamic'. Although I set the columns' width, it does not appear. 

### What is the expected behavior?
Columns must display at the width I set, and horizontal scrolling should show all columns at each width.

### How would you reproduce the current behavior (if this is a bug)?
I leave the link to reproduce this.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/3rkMducC7coIY9yV

Test code

```
Survey.StylesManager.applyTheme('modern');

var json = {
    pages: [ 
        {
   "name": "test",
   "elements": [
    {
     "type": "matrixdynamic",
     "name": "test",
     "minWidth": "",
     "maxWidth": "",
     "valueName": "jobList",
     "columns": [
      {
       "name": "column1",
        "cellType": 'text',
       "width": '600',
      },
      {
       "name": "column2",
        "cellType": 'text',
       "width": '400',

      },
      {
       "name": "column3",
       "width": '400',
      },
      {
       "name": "column4",
        "cellType": 'text',
       "width": '400',
      },
      {
       "name": "column5",
       "width": '400',
      },
      {
       "name": "column6",
       "width": '400',
      },
      {
       "name": "column7",
       "width": '400',
      },
      {
       "name": "column8"
      },
      {
       "name": "column9"
      },
      {
       "name": "column10"
      },
      {
       "name": "column11"
      },
      {
       "name": "column12"
      }
     ],
     "horizontalScroll": true,
     "choices": [
      {
       "value": "Yes",
       "text": "Yes"
      },
      {
       "value": "No",
       "text": "No"
      }
     ],
     "allowAddRows": false,
     "allowRemoveRows": false,
     "rowCount": 3
    }
   ]
  },
    ],
    showQuestionNumbers: 'off',
};

const survey = new Survey.Model(json);


survey.onComplete.add(function (sender) {
    document.querySelector('#surveyResult').textContent =
        'Result JSON:\n' + JSON.stringify(sender.data, null, 3);
});

ReactDOM.render(
    <Survey.Survey model={survey} />,
    document.getElementById('surveyElement')
);


```

### Specify your

* browser:firefox
* browser version:93.0
* surveyjs platform (angular or react or jquery or knockout or vue):react
* surveyjs version:^1.8.67

**Comment by andrewtelnov** [comment]
@iyamusms I have updated [your example](https://plnkr.co/edit/ruhHE32upNomcZR2) by changing "width" into "minWidth" and by setting default "columnMinWidth" property. It works as expected.

Thank you,
Andrew
