### ISSUE TITLE
Changing enableIf property with the 'onValueChanged' method.

### ISSUE THREAD

**Issue by iyamusms** [surveyjs/survey-library#3501]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the current behavior?
My intention is to enable or disable other input boxes or select boxes depending on the answer I receive in the select box. `onValueChanged` was my first attempt, but to make the JSON enableif/visibleif is the setting. Can you let me know how to deal with this?

### What is the expected behavior?
Upon selecting 'Yes' on the 'match1 question', the 'match2 question' can be entered. Otherwise, it should be disabled. What if there are more elements in 'matrix_list', how can I control them individually? 

### How would you reproduce the current behavior (if this is a bug)?
I leave the link for the test page.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:https://plnkr.co/edit/5ZzQFeB5aMv057uA

Test code

```
Survey.StylesManager.applyTheme('modern');

var json = {
    pages: [
        {
            name: 'Test Matching',
            elements: [
                {
                    type: 'matrixdynamic',
                    name: 'matrix_list',
                    columns: [
                        {
                            name: 'title',
                            title: 'Title',
                            cellType: 'text',
                            readOnly: true,
                        },
                       
                        {
                            name: 'match1',
                            title: 'match1 question (Y/N)',
                            cellType: 'dropdown',
                            choices: ['Yes', 'No'],
                        },
                         {
                            name: 'match2',
                            title: 'match2 question (Y/N)',
                            enableIf: "{match1}='Yes'",  //<----- It's not working, so tried to use  'onValueChanged'
                            cellType: 'dropdown',
                            choices: ['Yes', 'No'],
                        },
                    ],
                    rowCount: 1,
                },
            ],
        },
        
    ],
    showQuestionNumbers: 'off',
};

const survey = new Survey.Model(json);
survey.data = {
    matrix_list: [
        {
            title: 'TestTitle1 ',
            description: 'This is test value1.',
        },
        {
            title: 'TestTitle2',
            description: 'This is test value2.',
        },
         {
            title: 'TestTitle3',
            description: 'This is test value3.',
        },
         {
            title: 'TestTitle4',
            description: 'This is test value4.',
        },
    ],
};

survey.onComplete.add(function (sender) {
    document.querySelector('#surveyResult').textContent =
        'Result JSON:\n' + JSON.stringify(sender.data, null, 3);
});

ReactDOM.render(
    <Survey.Survey model={survey} />,
    document.getElementById('surveyElement')
);

```

### Specify your

* browser:Fireforx
* browser version: 93.0
* surveyjs platform (angular or react or jquery or knockout or vue):react
* surveyjs version:^1.8.67

**Comment by andrewtelnov** [comment]
@iyamusms For matrices and panel dynamic you need a context. You can't access to a value as "{match1}='Yes'", because there are many instance of your "match1" question.
To get the value in the current row you have to use "{row.match1}='Yes'".

Thank you,
Andrew
