### ISSUE TITLE
Adding custom style to form

### ISSUE THREAD

**Issue by dawie** [surveyjs/survey-library#354]
### Are you requesting a feature, reporting a bug or ask a queation?
Feature Request

### What is the current behavior?
We love the form builder, but we need to style our form better for consumption by users. See screenshot at the bottom.

Is there an API reference to all the API methods that are available?

### What is the expected behavior?

1.	Ability to add class names (especially bootstrap column widths col-md-4) to individual form fields and their parent div’s.

![class names](https://cloud.githubusercontent.com/assets/21646/25327121/890fa546-2905-11e7-8059-f2045e97d097.png)

2.	Ability to remove or override inline styling
3.	Ability to use bootstrap grid system rather than tables
![3](https://cloud.githubusercontent.com/assets/21646/25327147/a0e88a8e-2905-11e7-89f9-062e959cbc3a.png)

#### Provide the test code and the tested page URL (if applicable)

This is what our current form looks like. We need to style it with Bootstrap to make it look good.
![screencapture-file-c-users-desktop-test-html-1493020313054](https://cloud.githubusercontent.com/assets/21646/25327351/60c9d6e6-2906-11e7-88ad-701de1f93bef.png)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version: Lastest VErsion
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.9

**Comment by andrewtelnov** [comment]
@dawie Thank you for your feature request.
At the current moment you can do the following.
1) Add the className property into the question. Here is example and docs: http://editor.surveyjs.io/examples/addproperties.html#code
2) Use survey onAfterRenderQuestion event, 
```
doOnAfterRenderQuestion(survey, options) {
  var className = options.question.className;
  if(className) {
    options.htmlElement.class = className;
  }
}
```
Thank you,
Andrew
