### ISSUE TITLE
Option to skip evaluation for expression parameters or set parameter as constant operand

### ISSUE THREAD

**Issue by seeker25** [surveyjs/survey-library#3557]
Hello I'm trying to write a expression that can be called like this:

```
panelFilterMap([{panel}, IsAlive == 'y' && IsAdult == 'y' && IsCompetent == 'y', Name]) 
```

But unfortunately due to the way the expression runner is setup, it tries to evaluate the middle parameters:
` IsAlive == 'y' && IsAdult == 'y' && IsCompetent == 'y' => false`

I just want this passed in as a string. I've tried with single and double quotes, but it still always gets parsed as a BinaryOperand.

Is there a way to could indicate the string is a Const operand? That way the string can be passed (unmodified) into the panelFilterMap function?

**Comment by andrewtelnov** [comment]
@seeker25 You can call `survey.setVaribable("yourVariable", yourVariableValue);` and then use it in expression as {yourVariable}.

Thank you,
Andrew

**Comment by seeker25** [comment]
Hello Andrew, 

That would involve having to run javascript code. 
That kind of defeats the purpose of writing everything inline in JSON:

EX.
    {
     "type": "expression",
     "name": "participants",
     "expression": "panelFilterMap([{panel}, IsAlive == 'y' && IsAdult == 'y' && IsCompetent == 'y', Name])"
    },

Where someone can easily change the JSON and control the outcome of the expression.

**Comment by andrewtelnov** [comment]
@seeker25 It works for me. Here is [the example](https://plnkr.co/edit/wrJZGLi9BQSIECi8).

Thank you,
Andrew

**Comment by seeker25** [comment]
`'IsAlive == y && IsAdult == y && IsCompetent == y'` evaluates to `IsAlive = y && isAdult = y && isCompetent = y`
when being passed in as a parameter:

![image](https://user-images.githubusercontent.com/3484109/139698373-74bd8f65-16f0-4531-9951-0483f38d55ef.png)


Which isn't going to work if you'd like that expression to be used in a dynamic filter statement. 

One would have to restore the ' character and replace = with ==, at the point they might as well just reparse the expressionValue.

**Comment by andrewtelnov** [comment]
@seeker25 It works correctly in [my example](https://plnkr.co/edit/wrJZGLi9BQSIECi8)  with the latest version at least.

Thank you,
Andrew

**Comment by seeker25** [comment]
'IsAlive == y && IsAdult == y && IsCompetent == y' 
is not equal to 
IsAlive = y && IsAdult = y && IsCompetent = y

**Comment by andrewtelnov** [comment]
@seeker25 I have updated [the example](https://plnkr.co/edit/wrJZGLi9BQSIECi8). I really do not understand what you are trying to do. The second parameter is passed as a string.

Thank you,
Andrew

**Comment by seeker25** [comment]
I think I'm going the wrong way for this anyways. Thanks @andrewtelnov.
