### ISSUE TITLE
Page-level hasErrors behaves inconsistently for pages with dynamic matrix questions

### ISSUE THREAD

**Issue by gitslacker** [surveyjs/survey-library#3575]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug.

### What is the current behavior?
`survey.pages[i].hasErrors(true)` behaves inconsistently for pages that have not yet been visited when using dynamic matrix questions.

When pre-populating some survey data with `survey.data = {data}`, `survey.pages[i].hasErrors(true)` returns `false` for pages containing only dynamic matrix questions until you physically view the page (by navigating to it using the Next button or using `survey.currentPage = i`). If you do not pre-populate any data then it returns `true` for pages with errors as expected. For other fields (e.g. single input) it appears to behave consistently.

### What is the expected behavior?
`survey.pages[i].hasErrors(true)` should indicate whether or not a page has any errors, regardless of question type or if data was preloaded.

### How would you reproduce the current behavior (if this is a bug)?

1. Create a survey configuration with a dynamic matrix question on a second page
2. Preload some data with survey.data = {...}
3. Execute `survey.pages[1].hasErrors(true)`, it will incorrectly return `false`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/ezTsZ0VpoaB2w5Mn

All three pages have errors (missing required fields). Click the "Validate - Click Me" button. Only pages 1 and 3 return `hasErrors == true`, page 2 returns `false`. Note that this behaved consistently in version 1.8.39 and stopped working in 1.8.40. If you fill in a value for question1 and proceed to page 2, clicking the "Validate - Click Me" button will now show page 2 `hasErrors == true` as expected.

### Specify your

* browser: Chrome
* browser version: 95.0.4638.69
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: 1.8.76 (worked in 1.8.39, stopped working in 1.8.40)

**Comment by andrewtelnov** [comment]
@gitslacker I have fixed it by the commit above. It should be merged into master soon and we will include it in v1.8.77.

Thank you,
Andrew
