### ISSUE TITLE
Survey data of questions with valueName in a panel that is hidden during survey editing is not removed

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#3595]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
When a panel with filled in matrixdynamic is hidden, the data does not get removed from the survey data. Unlike when specific fields get hidden, then this does work.

### What is the expected behavior?
Data in matrixdynamic in hidden panel should also be removed.

### How would you reproduce the current behavior (if this is a bug)?
Create a checkbox, add a panel with a matrixdynamic question. Fill in the panel questions. Make the panel hide on checkbox selection. Check that the data still contains the hidden panel questions data.

#### Provide the test code and the tested page URL (if applicable)
https://plnkr.co/edit/Bpcs5SzLpPSzhLmM

Select both target types, fill in a row in each panel. Then deselect one of the target types, submit and see all data still present in the survey_data.

### Specify your

* browser: Firefox
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.8.76

**Comment by andrewtelnov** [comment]
@Lionqueen94 You are probably looking for option: clearInvisibleValues: 'onHiddenContainer'.
We decided to introduce a new option, because in some case, when a panel or page becomes invsible, developers don't want to clear their questions values in case of "onHidden".
Here is [the example](https://plnkr.co/edit/Owl55JPmonILdJpZ).

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@Lionqueen94 However, invsible matrices do not clear their value on complete. That is strange. I will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@Lionqueen94 If you remove valueName from your matrices then it will work correctly. You don't need valueName here, since the question name and valueName are the same. However, I will investigate the issue in more detail and comeback.

Thank you,
Andrew

**Comment by Lionqueen94** [comment]
@andrewtelnov Thanks for having a look at the bug and for responding so quickly!

> @Lionqueen94 You are probably looking for option: clearInvisibleValues: 'onHiddenContainer'. We decided to introduce a new option, because in some case, when a panel or page becomes invsible, developers don't want to clear their questions values in case of "onHidden". Here is [the example](https://plnkr.co/edit/Owl55JPmonILdJpZ).
> 
> Thank you, Andrew

This is indeed the setting I have in my survey json, sorry I forgot to add it to the Plunker. 

> @Lionqueen94 However, invsible matrices do not clear their value on complete. That is strange. I will take a look.
> 
> Thank you, Andrew

But indeed the matrix values still do not get removed even with that setting.

> @Lionqueen94 If you remove valueName from your matrices then it will work correctly. You don't need valueName here, since the question name and valueName are the same. However, I will investigate the issue in more detail and comeback.
> 
> Thank you, Andrew

I will try your suggestion for removing the valueName, but I do have another question on another page that is using the same valueName to add more information to the data. In this case I think I still need to keep valueName in my code right?

**Comment by andrewtelnov** [comment]
@Lionqueen94 I have added a new unit test and fixed it. It will work fine in v1.8.78 that we will release on the next week.

Thank you,
Andrew
