### ISSUE TITLE
expression does not get initialised correctly when survey preloaded with data

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#3620]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

Custom functions in expression seems not to take in account preloaded data.

https://plnkr.co/edit/YZj7LuM6dRDiMYWr

when change q1 or q2 it works but it does not get initialised correctly

thank you

**Comment by andrewtelnov** [comment]
@masciugo It calculates correctly, expression question doesn't display value correctly.
