### ISSUE TITLE
SetValue with HTML Element Does Not Change How The Survey Renders

### ISSUE THREAD

**Issue by mwrouse** [surveyjs/survey-library#3621]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
If you have an HTML element in your survey and want to set a value for it, you would think to use `setValue` but that does not work.

Doing `setValue` for an HTML question does not change the html for the question/element.

**HOWEVER**, it does update the output result of the question, but not what is displayed when the survey is rendered.

### What is the expected behavior?
If you use `setValue` for an HTML question that it would update the content of the element to reflect the HTML you pass in, just like it would update the value of any other question.

### How would you reproduce the current behavior (if this is a bug)?
```javascript

var json = {
 "completedHtml": "HTML Result: {question1}",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "html",
     "name": "question1",
     "html": "<h1>Hey</h1>"
    },
   
   ],
   "title": "Setting HTML Values"
  }
 ],
};

window.survey = new Survey.Model(json);
survey.render("surveyElement");

survey.setValue('question1','<a href="google.com">Google</a>');
```

Running that JS code with Survey JS version 1.8.78 will result in the HTML originally set in the survey being shown, not the html passed in with `setValue`

This will result in the following: 
![image](https://user-images.githubusercontent.com/8886769/142267507-f7fea98c-5444-4ab9-ae76-7cca9d03bcf2.png)
Then when you  hit complete, you get: 
![image](https://user-images.githubusercontent.com/8886769/142267558-6f594c4f-2ad8-49ec-b6f7-9ac52107a34e.png)

So doing `setValue` sets the output value of the HTML question, but doesn't change how it renders.

#### Provide the test code and the tested page URL (if applicable)

https://jsfiddle.net/mwrouse/391hejnd/5/

**Comment by mwrouse** [comment]
I can see why this doesn't currently work, but we allow our users to configure their survey 100% by passing in key-value pairs that get passed to `setValue`. 

By default, an HTML element doesn't have any output value, but doing `setValue` gives it an output value (as expected).
Giving an HTML element an output value of the HTML you set for it might not be ideal.

Adding a different function to modify the HTML content would not great either, since it would then require you to do extra work when setting a bunch of values read from somewhere else. You'd have to check the survey to see if is HTML and then do something different.

**Comment by andrewtelnov** [comment]
@mwrouse html question doesn't support value property. It is a non-value question type.
You can do the following:
```js
    {
     "type": "html",
     "name": "question1",
     "html": "<h1>Hey</h1>{myLink}"
    },
```
and then:
```js
survey.setVariable('myLink','<a href="https://google.com">Google</a>');
```
Here is your [updated example](https://jsfiddle.net/surveyjs/xdsLnmbq/).

Thank you,
Andrew

**Comment by mwrouse** [comment]
Very interesting. Unfortunately, that won't work for our use case. 

We need the content set when creating the survey to be the default value, and can be override sometimes when needed. So having a variable in there like that won't work.

I also tried `setPropertyValue('html', '<a href="https://google.com">Google</a>');` but did not appear to work either.

Is there no set function to be able to change the `html` property on the element?

**Comment by mwrouse** [comment]
Very interesting. Unfortunately, that won't work for our use case. 

We need the content set when creating the survey to be the default value, and can be override sometimes when needed. So having a variable in there like that won't work.

I even tried this but did not appear to work
```javascript
var q = survey.getQuestionByName('question1');
q.setPropertyValue('html','<a href="https://google.com">Google</a>');
```

Is there no set function to be able to change the `html` property on the element?

**Comment by mwrouse** [comment]
For anyone looking in the future, this is how we went about solving this: 

```javascript
let question = survey.getQuestionByName('question1');

if (question.getType() == 'html') {
    question.html = value;
}
```
