### ISSUE TITLE
checkbox question: default value not working with visibleif

### ISSUE THREAD

**Issue by qav-gabriela-castro** [surveyjs/survey-library#3634]
### Are you requesting a feature, reporting a bug or asking a question?
bug

### What is the current behavior?

if a question has a option with visibleif, the default value is checking multiple questions

### What is the expected behavior?
 we could check/uncheck options with default value active

Tested page URL:
https://plnkr.co/edit/etOSdafU7i7GRqmA?preview
Test code

```

### Specify your

* browser:
* browser version:
* surveyjs platform: jquery
* surveyjs version: 1.8

**Comment by andrewtelnov** [comment]
@qav-gabriela-castro I have fixed the issue by commit above. My PR should include into master and the fix will be available in [v1.8.79](https://surveyjs.io/WhatsNew#v1.8.79).

Thank you,
Andrew
