### ISSUE TITLE
Expression validation with 'getDate' and 'today', does not work.

### ISSUE THREAD

**Issue by GleytonLima** [surveyjs/survey-library#3642]
### Are you requesting a feature, reporting a bug or asking a question?

- Possible bug

### What is the current behavior?

The following validation in a expression question return **valid**:

```
{
     "type": "text",
     "name": "date_ok",
     "title": "Date with validation works with less than today",
     "isRequired": true,
     "validators": [
      {
       "type": "expression",
       "expression": "getDate({date_ok})<=today()"
      }
     ],
     "inputType": "date"
}
```
Current date: 2021-11-20
Input: 2021-11-21
Result: **Valid** input

### What is the expected behavior?
```
{
     "type": "text",
     "name": "date_ok",
     "title": "Date with validation works with less than today",
     "isRequired": true,
     "validators": [
      {
       "type": "expression",
       "expression": "getDate({date_ok})<=today()"
      }
     ],
     "inputType": "date"
}
```
Current date: 2021-11-20
Input: 2021-11-21
Result: **Invalid** input

### How would you reproduce the current behavior (if this is a bug)?

Using plnkr.co

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/E2dfm5vFJcQwoy2R

### Specify your

* browser: Google Chrome
* browser version: 96.0.4664.45
* surveyjs platform (angular or react or jquery or knockout or vue): react and agular
* surveyjs version: 1.8.78

**Comment by andrewtelnov** [comment]
@GleytonLima I have fixed the issue by the commit above and add a PR. The fix should be available in [v1.8.79](https://surveyjs.io/WhatsNew#v1.8.79).

Thank you,
Andrew
