### ISSUE TITLE
Vue infinite loop when referencing questions that don't exist

### ISSUE THREAD

**Issue by seeker25** [surveyjs/survey-library#3651]
Are you requesting a feature, reporting a bug or asking a question?
Reporting a BUG

What is the current behavior?
Changing the value of the choice box, when the title references a question that doesn't exist causes an infinite render loop.

vue.js:634 [Vue warn]: You may have an infinite update loop in a component render function.

found in

---> <SurveyElementHeader> at src/vue/elementheader.vue
       <SurveyElement> at src/vue/element.vue
         <SurveyRow> at src/vue/row.vue
           <SurveyPage> at src/vue/page.vue
             <Survey> at src/vue/survey.vue
               <Root>

Test URL:
https://plnkr.co/edit/L1DW8eT9lrxPPppe

Specify your
browser: Chrome
browser version:  96.0.4664.45
surveyjs platform (angular or react or jquery or knockout or vue): Vue
surveyjs version: 1.8.71

**Note:**
I've seen other infinite update loops happen when a question is referenced, but doesn't exist.  This locks up the survey entirely on production mode and freezes the browser.

**Comment by seeker25** [comment]
Another way to recreate this would be to create a survey expression, and have it return ""
Reference that question another question in the title and you also get a Vue infinite render loop. 
Example coming up.

**Comment by tsv2013** [comment]
We've fixed the issue via the commit above. Fix will be available in the nearest update.

**Comment by seeker25** [comment]
Thank you! The problem seems to be fixed.
