### ISSUE TITLE
Boolean defaultValue does not work with custom ValueTrue and valueFalse

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#3653]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
When you set your own valueTrue ("yes") and valueFalse ("no") on a boolean and set the defaultValue to "yes", the boolean is not set. When you set the defaultValue to true, it does work. However the creator shows defaultValue: "yes" when you set the boolean with a default value

### What is the expected behavior?
defaultValue: "yes" should work in case you set custom valueTrue and valueFalse.

### How would you reproduce the current behavior (if this is a bug)?
See this Plunker: https://plnkr.co/edit/8L6tAyRYcxkTJrGu

### Specify your

* browser: Firefox
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.8.78

**Comment by dmitrykurmanov** [comment]
It is the bug we will investigate and fix it.

As a workaround you could preset the data:

```js
survey.data = {
    "boolean1": "yes",
    "boolean2": "no"
};
```
it works as expected. Here is the updated example: https://plnkr.co/edit/1piSGMXkn1Cqhpzf?preview

**Comment by dmitrykurmanov** [comment]
Fixed. Fix will be available in the next minor release
