### ISSUE TITLE
Do not send notification about adding questions on randomizing existing questions on a page

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#3672]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
I originally found this because I had some issues with infinite recursion in the event handler for the `currentPageChange` event.

If I try to read something like `survey.currentPageNo` I might trigger an infinite recursion:
```js
public get currentPageNo(): number {
    return this.visiblePages.indexOf(this.currentPage);
  }

public get currentPage(): any {
    if (this.currentPageValue != null) {
      if (!this.isPageInVisibleList(this.currentPageValue) || this.pages.indexOf(this.currentPageValue) < 0) {
        if (
          !this.onContainsPageCallback ||
          !this.onContainsPageCallback(this.currentPageValue)
        ) {
          this.currentPage = null;
        }
      }
    }
    if (this.currentPageValue == null && !!this.firstVisiblePage) {
      this.currentPage = this.firstVisiblePage;
    }
    return this.currentPageValue;
  }
```

The issue here is that calling a getter in some circumstances also calls the getter, which then executes the `onCurrentPageChanging` callback again.

Doing some more research in the stack traces leads me to believe that this is possible regardless of 

### What is the expected behavior?
Never 

### How would you reproduce the current behavior (if this is a bug)?
Unclear; I know that on some larger surveys it is `null` and if the move is allowed the survey resets from the start.

Okay, bear with me, this is going to be hard to fathom.
- We have a panel with randomized questions inside, from these questions a subset is visible (this is done using a condition, but this doesn't change after initial load).
```ts
randomizeElements(isRandom: boolean): void {
    if (!this.canRandomize(isRandom) || this.isRandomizing) return;
    this.isRandomizing = true;
    var oldElements = [];
    var elements = this.elements;
    for (var i = 0; i < elements.length; i++) {
      oldElements.push(elements[i]);
    }
    var newElements = Helpers.randomizeArray<IElement>(oldElements);
    this.elements.splice(0, this.elements.length);
    for (var i = 0; i < newElements.length; i++) {
      this.elements.push(newElements[i]);
    }
    this.isRandomizing = false;
  }
```
This randomization function has some nasty side effects.
First of all, it clears the questions inside the panel. This means the panel becomes invisible and so does the page it is contained in (the panel is the only question on the page).

Then `questionAdded` is triggered for every element (this is very inefficient, I think you could in this case, since you're just reordering, do a single assign without that event).

The `questionAdded` code updates the visible page indexes; so now the current page at a moment in time becomes not visible.

Then code later on that tries to check if the prev button should be shown (here we have entered knockout specific territory, this is triggered from some observable). `isShowPrevButton()` calls `get state()`, which in turn calls `get currentPage()`.

At this point the logic in there checks if the current page is visible, which it is not, and thus it resets the current page to the first visible page.

This restarts the loop with a different page, which might also have a randomized panel inside...

I've spend a couple of hours on debugging this; I'll try to get some simple reproduction example another time.

**Comment by andrewtelnov** [comment]
@SamMousa We have another code right now. This part was completely rewritten several days ago. Here is [get currentPage property code](https://github.com/surveyjs/survey-library/blob/master/src/survey.ts#L2580).

Thank you,
Andrew

**Comment by SamMousa** [comment]
That looks a lot more efficient, and while it'll resolve this case I think some other improvements to the randomization are warranted.

The `onQuestionAdded` is expected to fire only when a new question is added to a survey, I think that firing it for every question in a randomized panel is more of an accident than intentional; what do you think?

**Comment by SamMousa** [comment]
This loop: https://github.com/surveyjs/survey-library/blob/master/src/panel.ts#L393

Since this only reorders we can be sure that after it's done the survey contains the exact same questions as before it was called... so firing those events seems to be mostly wasting CPU cycles in a best case scenario.

**Comment by andrewtelnov** [comment]
@SamMousa Yes, I will take a look.

Thank you,
Andrew
