### ISSUE TITLE
Formatting required for question title text (add support for markdown?)

### ISSUE THREAD

**Issue by m-hinds** [surveyjs/survey-library#3673]
### Are you requesting a feature, reporting a bug or ask a question?
New Feature

### What is the current behavior?
All the characters in question titles must be formatted identically (i.e. it isn't possible to bold, underline or  italicize).

### What is the expected behavior?
Question titles ought to have sections bolded, underlined or italicized text to draw respondents attention to a particular aspect of the question which may be easily misunderstood or sensitive.
Markdown or a raw HTML option might be a good way to achieve this.

Thanks!

**Comment by tsv2013** [comment]
Sorry for missing this. It was in created wrong repo.

SurveyJS Library supports markdown in texts. Here is the example on our site - https://surveyjs.io/Examples/Library?id=survey-markdown-radiogroup&platform=jQuery&theme=modern
