### ISSUE TITLE
Implement angular survey component in SurveyJS Library

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-library#3681]
Check whether we can use SurveyJS reactivity approach with latest Angular versions

**Comment by tsv2013** [comment]
I've implemented Ng native reactivity for survey model, introduced `survey-angular-ui` library and `angular-ui` example project.

At this moment something wrong in generated typings when angular modules are in the main `node_modules` folder. I'll ned @andrewtelnov help here, but a bit later.

**Comment by tsv2013** [comment]
First of all

- [ ] actions
- [ ] popup
- [ ] responsivity manager
- [ ] question title
- [ ] checkbox question

**Comment by OlgaLarina** [comment]
Dima
- [ ] text
- [ ] html

Olga
- [ ] dropdown, 
- [ ] image

Duet
- [ ] boolean 
- [ ] checkbox, 
- [ ] radiogroup, 
- [ ] rating

- [ ] Survey Layout

**Comment by dk981234** [comment]
- [ ] https://github.com/surveyjs/survey-library/issues/4525
