### ISSUE TITLE
Add Flemish language

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#3682]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
Flemish is not available, in most cases Dutch is close enough. However when a single survey requires both a Dutch and Flemish translation it becomes troublesome.

My proposal would be to add Flemish, and initialize it as a copy (or an alias) of the Dutch language.
While the survey engine might use the same texts, the questionnaire will then be able to use separate texts for those languages.

PS. I'm happy to make a PR for these kinds of issues, if that saves you some work. Just tell me or add a label like: `would accept a pr for this`

**Comment by andrewtelnov** [comment]
@SamMousa Sure, we will accept your PR.

Thank you,
Andrew

**Comment by SamMousa** [comment]
This is included in v1.9.1

**Comment by SamMousa** [comment]
I'm not familiar with webpack. 
If it supports wildcards, it might be better to change this file: 
https://github.com/surveyjs/survey-library/blob/master/src/entries/chunks/localization.ts

To use a wildcard; alternatively the `nl-BE` file should be added to this file.

**Comment by SamMousa** [comment]
Fixed in #3776
