### ISSUE TITLE
Window auto scrolls to surveyJS on load and focusing first question

### ISSUE THREAD

**Issue by gregpawlowski** [surveyjs/survey-library#3701]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Window scrolls to survey JS on load, first question is auto focused by default.

### What is the expected behavior?
The page should not auto scroll to the survey. This causes weird behavior, scrolling my page to the bottom.
According to https://github.com/surveyjs/survey-library/commit/2410bab8db5da0218f32355130367d924026f403 this was supposed to be fixed. 

I have tried using focusFirstQuestionAutomatic property  but that only ensures the question isn't focused upon click "next".

It looks like the problem is with the API, using the API and setting 
survey.focusFirstQuestionAutomatic = false; in JavaScript will produce the error.
However if the option is set in the surveyjson focusFirstQuestionAutomatic : false then the page does not scroll or focus.

### How would you reproduce the current behavior (if this is a bug)?
Easily tested, add content before the survey div. When the div loads, page will scroll to the survey and focus on first question.

Adding focusFirstQuestionAutomatic  into the serializable ensures the first page /first questions is not focused. Adding it to the API in javascript will produce an error. 

### Specify your

* browser: Chrome
* browser version: 92.0
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version:

**Comment by tsv2013** [comment]
You need to set the [`focusFirstQuestionAutomatic`](https://surveyjs.io/Documentation/Library?id=surveymodel#focusFirstQuestionAutomatic) property of your survey to `false`.

**Comment by andrewtelnov** [comment]
@gregpawlowski Here is [the example](https://plnkr.co/edit/tIJshkRowBdLG8s9) and it works as expected.

Thank you,
Andrew

**Comment by gregpawlowski** [comment]
@andrewtelnov I have tried your plunker example and it does not work properly in chrome for me.

When I load your example in full preview mode in plunker it focuses on the q1 input.

1. Load your example
2. Expand live preview
3. Refresh
Focus shows on q1 every time the window is refreshed.
Same result is happening in Edge. Not sure why refresh causes it to load on the question

**Comment by andrewtelnov** [comment]
@gregpawlowski You are right. We scroll&focus afer JSON loading and it is too late to set the property. Here is the code that fix the issue:
```js
const survey = new Survey.Model();
survey.focusFirstQuestionAutomatic = false;
survey.fromJSON(json);
```
and [updated example](https://plnkr.co/edit/ofW5z3R2wWN81cMl)

Thank you,
Andrew

**Comment by gregpawlowski** [comment]
Thank you for the quick response and finding the problem. This workaround works from me. I still think that all properties should be settable prior to the call of rendering $('#surveyElement').Survey({ model: survey }), this would be my assumption. Not sure if you would like to address this or close. I'm ok either way as long as this is documented as it shows inconstancy between the API and SurveyJson properties, thank you again.

**Comment by andrewtelnov** [comment]
@gregpawlowski Yes, I was thinking about it as well.
We will discuss it. 

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@gregpawlowski I have fixed by the commit above. Functional tests for all cases have been added.

Thank you,
Andrew
