### ISSUE TITLE
Implement placeholder for an empty matrix dynamic

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-library#3717]
For Creator V2 property grid - implement placeholder for an empty collection

https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=2100%3A7986

**Comment by dk981234** [comment]
Also implement design for matrixdynamic placeholder in DefaultV2 theme:
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=11493%3A94981
