### ISSUE TITLE
remove frames from image/html questions in defaultV2 theme, stretch image in image question to 100% width

### ISSUE THREAD

**Issue by dk981234** [surveyjs/survey-library#3734]
it is decorative element and should be treated not like questions/panels

**Comment by ST-1580** [comment]
- [ ] Remove frames from image questions
- [ ] Remove frames from html questions
- [ ] Change `max-width` to 100%
- [ ] Rename `sv-image-image` class
- [ ] Make round border around image

**Comment by ST-1580** [comment]
Implementation of a round corners was converted to [the issue](https://github.com/surveyjs/survey-library/issues/3755)
