### ISSUE TITLE
Image Picker "Responsive" mode

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/survey-library#3754]
the concept `isResponsive` property:

- **false**: our current behavior with the `imageWidth`, `imageHeight` and `imageFit` props
- **true**:  the responsive mode. Images has `min/max Width/Height` props and `colCount` one. They are stretched according to allowed space without proportion changes (crop)

the links:

- [the design](https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=9296%3A50559)
- [the design 2 (resizable)](https://www.figma.com/file/lcpGtVUw2Hk6YpTZsNF8Pn/Shared?node-id=1%3A461)
- example of the [responsive tiles](https://demos.devexpress.com/Dashboard/?mode=viewer&dashboardId=SalesDetails&dashboardState=%7B%22Items%22%3A%7B%22listBoxState%22%3A%7B%22MasterFilterValues%22%3A%5B%5D%7D%7D%7D)

**Comment by dk981234** [comment]
Closed via https://github.com/surveyjs/survey-library/pull/4199
