### ISSUE TITLE
Not all data is submitted in payload on submit.

### ISSUE THREAD

**Issue by lore-burek** [surveyjs/survey-library#3758]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug.  (PS, I tried to submit a ticket on the website, but the authenticate with github didn't work right, there was a vicious circle with 'registering my githib with your site' (which I had already done). 

### What is the current behavior?
I have 1 key-value pair missing from my survey results on submission

### What is the expected behavior?
That I receive all data associated with my survey in the JSON payload. 

### How would you reproduce the current behavior (if this is a bug)?
Using your UI, plug in my sample JSON (attached) into the JSON editor.  It displays 3 dropdowns: State, City, Location but city and location questions are only visible based on the parent question. 
[Test Survey]
[complete]
Observe results are missing the location key/value pair.

#### Provide the test code and the tested page URL (if applicable)

Screen recording URL: https://share.getcloudapp.com/wbuYj0Pg

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version: Version 96.0.4664.93 (Official Build) (arm64)
[TEST-JSON.txt](https://github.com/surveyjs/survey-library/files/7715357/TEST-JSON.txt)

* surveyjs platform (angular or react or jquery or knockout or vue): No need, it's on your site that it's not working too. 
* surveyjs version:

**Comment by SamMousa** [comment]
Your questions should have unique names. You have 4 questions all named `location`.
Give them unique names and use the `valueName` property if you want to store them in the same field.
