### ISSUE TITLE
react: 'Other' textarea always visible

### ISSUE THREAD

**Issue by dszewczyk1** [surveyjs/survey-library#3762]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

'Other' textarea is always visible for radiogroup, no matter if radio button associated with it is selected or not.

### What is the expected behavior?

'Other' textarea should be only presented, when 'Other' radio option is selected.

### How would you reproduce the current behavior (if this is a bug)?

Just enable 'other' for radiogroup (hasOther: true)

#### Provide the test code and the tested page URL (if applicable)
Currently visible on examples page as well.
Tested page URL: https://surveyjs.io/Examples/Library?id=questiontype-radiogroup&platform=Reactjs&theme=modern

Test code

```
{
    type: "radiogroup",
    name: "gender",
    isRequired: true,
    hasOther: true
}

```

### Specify your

* browser: Chrome
* browser version: 96.0.4664.93
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.9.2

**Comment by andrewtelnov** [comment]
@dszewczyk1 Indeed, we do check that "other" textarea is invisible in our e2e tests. I have added this check.

Thank you,
Andrew
