### ISSUE TITLE
Change of placeHolder in comment from "OtherPlaceholder" to "commentPlaceholder"

### ISSUE THREAD

**Issue by Sarfraz-droid** [surveyjs/survey-library#3763]
OtherPlaceholder sounds very vague. it took me a while to find out this. changing it to "commentPlaceholder" sounds better.
Should I change it to commentPlaceholder?

**Comment by dmitrykurmanov** [comment]
we have some mess with the `hasComment`, `hasOther`, and with the `otherPlaceHolder` properties. I will create an example to illustrate it and then we will discuss it with the team.

**Comment by dmitrykurmanov** [comment]
here the example: https://plnkr.co/edit/SKAFZEA9ogyypTor

**Comment by dmitrykurmanov** [comment]
#3774 now we have the `commentPlaceHolder ` property as well:

  var json = {
    questions: [
      {
        type: "rating",
        name: "satisfaction",
        "hasComment": true,
        "commentPlaceHolder": "placeholder text",
      }
    ]
  };
