### ISSUE TITLE
String values passed into Matrix can throw error when total properties are set.

### ISSUE THREAD

**Issue by mikekidder** [surveyjs/survey-library#3766]
For Matrix questions (choices/dynamic), there are occasions where the total calculations can receive a string value causing a javascript error.

Ran into this issue - see plunker:  https://plnkr.co/edit/FVf5RrsbUJVeaE0J

Matrix (choices) - 3 Rows | CellType: 'Single Input' -> Column | Edit => "ColumnC" 
  Properties: Total:  'sum',  InputMask: 'Currency'

You see errors in console when entering values in ColumnC.

ColumnA - Single Input, InputType: 'Number', InputMask: 'None'
ColumnB - Single Input, InputType: 'Number', InputMask: 'Currency'
ColumnC - Default (CellType: 'text'), InputType not set, InputMask: 'Currency'

ColumnB:  Allows the calculations, but the InputType is interferring with InputMask
    - Don't see placeholder text
    - Currency value display:  45.00 -> 45, 12.50 -> 12.5

Reason for ColumnC:  
    - InputMask works with text to show placeholder value $0.00
    - Retains the currency value:  $12.20 -> $12.20

Proposed update:  https://github.com/mikekidder/survey-library/commit/7c9344ccda061b0219ffc98e5cadf976a218c227
Happy to submit a PR

It also fixes an important hydration issue we have as well.

Our form data results are stored in database as XML.  
Due to the conversion back to JSON, all values are strings.
String values passed in into the Matrix questions has same issues above.

**Comment by andrewtelnov** [comment]
@mikekidder I have added one more unit test and fixed it by the commit above.

Thank you,
Andrew

**Comment by mikekidder** [comment]
Thanks for the quick turnaround!  
I thought you'd want to add a little more polish versus my proposed update.  LOL

**Comment by andrewtelnov** [comment]
@mikekidder You are welcome!
Unfortuantely, at the current stage of the product, when a lot of developers rely on its quality, we can't fix/change anything without unit tests (model), functional (e2e) tests (library behavior model+frameworks), markup tests (rendering by frameworks) and visual regression (image comparing, checking css rules) tests.

Thank you,
Andrew
