### ISSUE TITLE
Add support for default strings for custom localizable properties

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#3771]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
Currently builtin properties support loading localized default properties from localizations.
This is realized by these lines in `survey.ts`:
```js
this.createLocalizableString("pageNextText", this, false, true);
```
The 4th argument tells the localizable string that it should try to load data from the localization if not specified in survey config.

When creating custom properties you can set `isLocalizable` to `true`, this enables localization support. 
It would be great if these custom properties also support loading defaults from localizations.

Concrete example: we're adding a property `closeWindowText` to our surveys. We want this to be customizable just like all other button texts, but we also want to provide localized defaults just like builtin button texts.

### Workarounds
Since `createLocalizableStrings` is `protected` we can't (or shouldn't) call this from outside, which would be a dirty hack anyway.

One other option is to manually set the `localizationName` public property on the LocalizableString object.
```js
survey.getLocalizableString("closeWindowText").localizationName = 'closeWindowText';
```

### Expected behavior
I think it makes sense to add support for loading defaults from localization by default for custom properties. Since they won't be set in most cases unless the user adds them explicitly it won't impact users not using it.

**Comment by andrewtelnov** [comment]
@SamMousa Added support by the commit above.

Thank you,
Andrew
