### ISSUE TITLE
checkbox: default value not working for initially invisible items

### ISSUE THREAD

**Issue by qav-gabriela-castro** [surveyjs/survey-library#3781]
### Are you requesting a feature, reporting a bug or asking a question?
bug

### What is the current behavior?
the checkbox triggers a question which has a default value and it's not been checked

### What is the expected behavior?
when  i check an option of the checkbox, the next question would appear with the default value checked

#### Provide the test code and the tested page URL (if applicable)
https://plnkr.co/edit/8D1x9WKWDwRVXBm1?preview

**Comment by andrewtelnov** [comment]
@qav-gabriela-castro I have fixed by the commit above. The fix will be available in [v1.9.3](https://surveyjs.io/WhatsNew#v1.9.3).

Thank you,
Andrew
