### ISSUE TITLE
Bug: undefined error when typing in checkbox other comment with `"textUpdateMode": "onTyping"

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#3808]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
When you type in the other comment field of a checkbox, there is an error happening in the console:
```
Uncaught TypeError: e.target is undefined                                   survey.jquery.min.js:11:374205
```

### What is the expected behavior?
No errors should happen when you type a comment.

### How would you reproduce the current behavior (if this is a bug)?
Add a checkbox with `hasOther=true` and add `"textUpdateMode": "onTyping"` setting to a survey.

#### Provide the test code and the tested page URL (if applicable)
https://plnkr.co/edit/py4ZMSkvbXuBJbTz

### Specify your

* browser: Firefox
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.9.1 and 1.9.3 for sure

**Comment by andrewtelnov** [comment]
@Lionqueen94 I have added the functional test and fixed it by the commit above.

Thank you,
Andrew
