### ISSUE TITLE
Introduce clearIfInvisible on question level to override survey clearInvisibleValues behavior

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#3811]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
The `clearInvisibleValues` setting is global. 

### What is the expected behavior?
Ideally it should be possible to override this for specific questions. Reasoning:
- I want to remove values from questions that are no longer relevant (and thus hidden via `visibleIf`).
- I'm injecting some data at the start of the survey, for example an email address
- If the email address is not present in the injected data I want to show a question asking for it, if it is present I hide the question using `visibleIf`.

### Proposed solution
Add a `boolean` setting **Never clear values** to the base question model. When checked this means any clearing behavior will be skipped for this specific question.

**Comment by andrewtelnov** [comment]
@SamMousa It is a survey property with defaultValue equals to "onComplete".
You can simply override the default value using the following code:
`Survey.Serializer.findProperty("survey", "clearInvisibleValues").defaultValue = "onHidden";`
Please note, that after that "onHidden" will be treat as default value. Serializer will not serialize this value into JSON.

You can use this approach with the most serializable properties.

Thank you,
Andrew

**Comment by SamMousa** [comment]
That won't solve the problem.

I have to clear invisible values, except for some questions which should never be cleared.
Currently there is no way to configure that in the survey.

The reasoning is that sometimes if questions become irrelevant you want to clear them:

1. Do you have a car? Yes / no
2. What colour is it?

Here it a user goes back and changes his answer you want to clear the second question. It is no longer relevant.


In other situations like prefilling an email address from the database:


What is your email?

I want to hide this question, but the data is still relevant, thus the data must not be cleared.

Hope that clarifies the idea
