### ISSUE TITLE
Implement dropDown widget

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-library#3840]
- [x] implement custom popup
- [x] [change invisible items](https://github.com/surveyjs/survey-creator/issues/2896)
- [ ] #4265
- [ ] implement hover and pressed state for dropdown button [figma](https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SJS-Creator?node-id=8085%3A48258)
- [x] keyboard "arrow down" should move from search to list
- [x] scroll up in Safari can hide the dropdown popup (ask @novikov82 )

**Comment by novikov82** [comment]
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=266%3A2770

**Comment by tsv2013** [comment]
Support additional cases:

- [ ] custom item template (users can show images, hints, descriptions in dropdown item)
- [ ] items grouping - like `optgroup` as described in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup
- [ ] implement clear button
- [ ] support RTL
- [ ] support placeholder
- [ ] check accessibility

**Comment by tsv2013** [comment]
We need to take in account this case - https://github.com/surveyjs/survey-library/issues/4277
