### ISSUE TITLE
How to trigger onUploadFiles event after survey data restore?

### ISSUE THREAD

**Issue by digital88** [surveyjs/survey-library#3841]
### Are you requesting a feature, reporting a bug or asking a question?
question

### What is the current behavior?
When I restore survey answers with survey.data = someData; onUploadFiles do not trigger. Is there any way to manually trigger this event? I have set storeDataAsText property to false on file questions before restoring survey data, it did not help.

### What is the expected behavior?
-

### How would you reproduce the current behavior (if this is a bug)?
-

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version: 96
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.8.71

**Comment by tsv2013** [comment]
>When I restore survey answers with survey.data = someData;
>

In this case you needn't upload files again - they are already uploaded

**Comment by digital88** [comment]
I need to convert dataurl in base64 back to javascript File object. I figured it out, I just for some reason expected surveyjs to do this for me automagically :)
Thanks for answer.
