### ISSUE TITLE
DefaultValue should be an array.

### ISSUE THREAD

**Issue by nervusdm** [surveyjs/survey-library#3842]
I believe we can call this as a feature improvement.

### What is the current behavior?
  "type": "matrix",
     "name": "test",
     "title": "test,
     "description": "I test :",
     "defaultValue": {
      "One": "Oui",
      "Two": "Oui",
      "Three":"Oui",
}
..

### What is the expected behavior?
defaultValue should be an array.
It's all about json_encode.
For recording the survey js on the server, ( back office php for example) if we use a usual json_encode, defaultvalue order may change.

**Comment by nervusdm** [comment]
Here is a basic php helper who may help, if someone has a problem with json_encode and this.

`static function defaultValueProblem($x)
{


            foreach($x->pages as $xz )
            {
            foreach($xz->elements as $kx=>$vx)
            {
                if (isset($vx->defaultValue))
                {
                    $tmp=null;
                    foreach($vx->defaultValue as $k=>$v)
                    {
                        $tmp[$k]=$v;
                    }
                    $tmp_defaultValue=new stdClass();
                    foreach($vx->rows as $k=>$v)
                    {
                        if (isset($tmp[$v]))
                        {
                            $tmp_defaultValue->$v=$tmp[$v];
                        }
                    }
                    $vx->defaultValue=$tmp_defaultValue;
                }
            }
            }
return $x ;
}`

**Comment by tsv2013** [comment]
SurveyJS products are the client-side JavaScript libraries. What issue do you want to resolve via a server-side code?

**Comment by nervusdm** [comment]
> SurveyJS products are the client-side JavaScript libraries. What issue do you want to resolve via a server-side code?

I am not  saying this is an issue. It's a bad pattern. Rows are array. DefaultValue are not.

Since i Know no one cares, I close this.
