### ISSUE TITLE
VueJS: Imagepicker: Duplicate value prop in imagepicker.vue's generated render function

### ISSUE THREAD

**Issue by a-d-c** [surveyjs/survey-library#3902]
BUG: Refactoring of several question types occurred between R1.8.79 and R1.9.0, including modifications to the Image Picker question. One of these changes has caused the render function for the image picker to contain a duplicate "value" property which yields errors in certain browsers.

### What is the current behavior?

When using survey-vue library in an application and loading that application in IE11 you will receive a: "Multiple definitions of a property not allowed in strict mode" in the console.

Tracked this down to the following line in survey-vue.js:
`domProps: { value: item.value, value: _vm.question.value },`

this appears on line 13038 in R1.9.0 and 13168 in R1.9.5

Seems likely that this was related to the image-picker refactoring [here](https://github.com/surveyjs/survey-library/commit/bbb111668e362b0d53dbdea4ca637a38999d4301)

### What is the expected behavior?

Non-duplicate value prop in domProps / no IE11 console errors

* browser: IE11
* browser version: 1809
* surveyjs platform: vue
* surveyjs version: 1.9.0+

**Comment by dmitrykurmanov** [comment]
we will investigate the problem and return back asap

**Comment by tsv2013** [comment]
The ":value" binding is used to set the "value" attribute of HTML INPUT tag inside the imagepicker question type:
```HTML
<input name="choosepicture_sq_100" id="sq_100i_0" aria-required="false" aria-label="What animal would you like to see first ?" aria-invalid="false" type="radio" class="sv-imagepicker__control" value="lion" style="display: none;">
```
The `value="lion"` in the above case. User input is proceeded via the "v-model" binding.

**Comment by tsv2013** [comment]
You can check the live sample on our site - https://surveyjs.io/Examples/Library?id=questiontype-imagepicker&platform=Vue&theme=modern

**Comment by a-d-c** [comment]
Hi @tsv2013,

The problem is that I am _not actually using an image picker question at all_. This issue is occurring as soon as we attempt to load the survey-vue module itself - before we've even assigned survey structure & data. I understand that the :value prop  vs v-model difference in the template, but the issue is that the process that has transformed that template into the render function is generating an invalid object (at least in "strict mode" as far as IE11 is concerned).

In fact - the live sample you posted above does not work in IE11 (screenshot below). 

Therefore - if it is the case that as of V1.9.0 Survey JS does not support IE11, then I understand and will have to continue using 1.8.79 indefinitely. Believe me, I would love nothing more than to be able to say that our application will not support IE11, but unfortunately in our industry - I am stuck supporting it for the foreseeable future.


![Screen Shot 2022-01-21 at 8 47 49 AM](https://user-images.githubusercontent.com/8865531/150538488-88352185-0eff-4bff-bb7b-fd7ca5b1f4d9.png)

**Comment by tsv2013** [comment]
How do you get that "Multiple definitions of a property ..." is related to the imagepicker question markup?

**Comment by a-d-c** [comment]
No - you don't even need to be in the image picker sample. Opening ANY of the samples in IE11 will cause the issue since the problem is in the generated code of the npm package itself.

Here is another example - if you navigate to this sample for the basic "Text" question via IE11 you will see the same errors: [https://surveyjs.io/Examples/Library?id=questiontype-text&platform=Vue&theme=modern](https://surveyjs.io/Examples/Library?id=questiontype-text&platform=Vue&theme=modern)
![Screen Shot 2022-01-21 at 9 14 07 AM](https://user-images.githubusercontent.com/8865531/150541785-15b7c79d-10f5-4967-b91d-df2d1b70003b.png)

**Comment by tsv2013** [comment]
Yes, I see. The issue is related to inputType branching logic in VueJS implementation. The thing is that imagepicker question returns inputType checkbox or radio only and even shouldn't go in the third branch with `domProps: { value: item.value, value: _vm.question.value },`

We'll discuss this issue and update this thread
