### ISSUE TITLE
choicesByUrl url is not correctly encoded when using interpolation

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#3908]
It seems that only parameters get encoded. 

In the following example user provided url is not encoded 

https://plnkr.co/edit/Ki3rQ0vOsRL1X7Ll 

thank you

**Comment by tsv2013** [comment]
I've checked the network browser dev tool for the plunker you've provided and it shows that URL is do encoded:
![image](https://user-images.githubusercontent.com/3013415/151130730-319fcbd8-ec2d-4c6d-86fb-2e364b48ce9e.png)

I've also added a unit test - and it works ok.

**Comment by masciugo** [comment]
Sorry there was a misunderstanding. For "parameters" I intended url parameters. The ones after `?` in the url. However I better define my problem in [another issue](https://github.com/surveyjs/survey-library/issues/3950). Forget about this and thanks
