### ISSUE TITLE
Avoid "The request returned empty data or the 'path' property is incorrect" message

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#3943]
### Are you requesting a feature, reporting a bug or asking a question?

question/feature

### What is the current behavior?

dropdown with choicesByUrl causes the alert "The request returned empty data or the 'path' property is incorrect" to come up  when no choices are returned by the server. This is perfectly possible and frequent in my use case, it's not an error. I would simply show an empty choices list. 

### What is the expected behavior?

Simply avoid that message or avoiding to treat is as an error. Maybe adding an option to choicesByUrl will do:

`allowEmptyResult: true`

thank you

**Comment by andrewtelnov** [comment]
@masciugo There is "allowEmptyResponse" property in "Choices From Web" object. You can set it in Creator.

Thank you,
Andrew

**Comment by masciugo** [comment]
ok it seemed strange to me that it wasn't there. thank you
However is there any way to set it globally? I have many questions like that. Maybe something on Survey.ChoicesRestfull ...

**Comment by andrewtelnov** [comment]
@masciugo After my PR will be in the master and we release it, you will be able to add the following code:
``Survey.Serializer.findProperty("choicesByUrl", "allowEmptyResponse").defaultValue = true;``

Thank you,
Andrew
