### ISSUE TITLE
choicesByUrl url does not encode char %  to %25

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#3950]
### Are you requesting a feature, reporting a bug or asking a question?

question/bug

### What is the current behavior?

Currently url parameters get encoded but the special char `%` is not. See inspector in the following example

https://plnkr.co/edit/JB3SDPYgLfLgMKuj

### What is the expected behavior?

`%` should be encoded (%25) as any other special chars. This is done by encodeURI:

![image](https://user-images.githubusercontent.com/454321/151782669-0d307bdb-e94b-435b-8492-afdc4f6eb345.png)

thanks

**Comment by novikov82** [comment]
@masciugo 
We do not control symbol encoding out of parameter scopes. Currently symbols are encoded by XMLHttpRequest
But % is a special symbol and XMLHttpRequest does not encode it.

For your case the simpliest solution is encode % as %25 in choicesByUrl.
Or create additional value and use it as a parameter:
https://plnkr.co/edit/KuQcvc1v7HGvmHFG

**Comment by masciugo** [comment]
I see. thank you for the explanation
