### ISSUE TITLE
"showPreview = false" in File questions hides all information about files

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-library#4000]
this issue better to take after [#](https://github.com/surveyjs/survey-library/pull/4010) merge

**Comment by tsv2013** [comment]
Yes, it's used for custom preview drawing as shwon in this example - https://surveyjs.io/Examples/Library?id=file-custom-preview

**Comment by novikov82** [comment]
Oh, I was confused with this property name that was not clear enough for me.
