### ISSUE TITLE
Survey progress bar styling

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-library#4001]
![image](https://user-images.githubusercontent.com/29385489/150189798-3cef47ed-f55b-4e30-af83-2bc00e25aba2.png)
![image](https://user-images.githubusercontent.com/29385489/150189936-5572bcac-a32b-4ca5-98c4-456fd24a18aa.png)

(transfer issue to SurveyLibrary if needed)

https://surveyjs.io/Examples/Library?id=navigation-buttons&platform=Knockoutjs&theme=modern

**Comment by dk981234** [comment]
Will be resolved with for #4113

**Comment by novikov82** [comment]
design is ready - https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=13098%3A102005
