### ISSUE TITLE
Number Spinner not working with checkErrorsMode = 'onValueChanged' and textUpdateMode = 'onTyping'

### ISSUE THREAD

**Issue by joaobrunoah** [surveyjs/survey-library#4057]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Create a survey Model configured with:
* checkErrorsMode = 'onValueChanged'
* textUpdateMode = 'onTyping'

If you create a question of type "Single Input", and configure this Single Input to accept only numbers,  the number spinner (up and down arrows) does not work properly (After each click to go up, the cursor of the mouse becomes a text cursor and the up button is not hovered anymore)

### What is the expected behavior?
I can click as much as I want in the up arrow of a number spinner, without losing hover property

### How would you reproduce the current behavior (if this is a bug)?
1. Create a survey Model configured with:
* checkErrorsMode = 'onValueChanged'
* textUpdateMode = 'onTyping'
2. Create a question of type "Single Input", and restrict this to numbers
3. Answer the survey, changing the number value using the input spinners

### Specify your

* browser: Chrome
* browser version:  98.0.4758.102
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.9.3

**Comment by andrewtelnov** [comment]
@joaobrunoah Could you please help us to reproduce the issue by forking [the current example](https://plnkr.co/edit/R6abEdSEyC6yMFmQ) modify the code if needed and provide steps to reproduce the issue.

Thank you,
Anddrew

**Comment by pablorosalesps** [comment]
I haven't been able to reproduce this yet, so we can mark this as closed. We'll check with the latest SurveyJS version and try to reproduce it, if we can do that, we'll open a ticket again.

cc: @joaobrunoah

**Comment by joaobrunoah** [comment]
Sorry, I lost track of this issue and I can't help solving it anymore, so I just closed it.
