### ISSUE TITLE
V2: Implement custom number editor

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-library#4065]
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=2341%3A99230

![image](https://user-images.githubusercontent.com/3013415/155528377-ed2209d9-8218-485a-9097-63411ccae8b5.png)

**Comment by andrewtelnov** [comment]
@tsv2013 I beleive we have implemented it as well.

Thank you,
Andrew
