### ISSUE TITLE
V2: matrix row titles

### ISSUE THREAD

**Issue by dk981234** [surveyjs/survey-library#4074]
Check this behavior: 
![image](https://user-images.githubusercontent.com/21283706/155677172-8e7ea30b-e248-42c7-ad29-15c3179ecdb6.png)

**Comment by novikov82** [comment]
currently it works this way. also we have `rowTitleWidth` property and can adjust the row header width


![Image](https://github.com/surveyjs/survey-library/assets/29385489/8261dc41-6440-4381-8626-0b8607a74bb2)
