### ISSUE TITLE
Allow to create an alternative expression executor

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#4094]
Allow to override our default expression executor

**Comment by masciugo** [comment]
Hi @andrewtelnov is this new feature documented somewhere? I am curious but not able to understand its goal
thank you

**Comment by andrewtelnov** [comment]
@masciugo It was created for a company that has it's own expression engine. They wanted integrated our SurveyJS Library, including SurveyJS Creator, into their application and they want to have the same expression engine they have already.
Basically you have to implement expression parser and then execution. 

Thank you,
Andrew
