### ISSUE TITLE
The choicesByUrl with a expression in url within a dropdown breaks in a paneldynamic

### ISSUE THREAD

**Issue by isangines** [surveyjs/survey-library#4116]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug.

### What is the current behavior?

Given a dropdown with a choicesByUrl property inside a paneldynamic is not calling the restful API. 

### What is the expected behavior?

Expecting the same behaviour as the panel in the sample: https://surveyjs.io/Examples/Library/?id=questiontype-dropdownrestfull

### How would you reproduce the current behavior (if this is a bug)?

To repro the issue, I've tweaked the sample you have from a panel to a paneldynamic here https://plnkr.co/edit/WRaZyXhEn6cXb5KR

You need to clicke "Add new" and select a region, the region should be populated same as the sample of the above section. 

### Specify your

* browser: Microsoft Edge Chromium
* browser version: 99.0.1150.36 
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.9.19

Thanks!

**Comment by andrewtelnov** [comment]
@isangines It should be:
`"url": "https://surveyjs.io/api/CountriesExample?region={panel.region}",`
panel.region - means the question region from the current panel. 

Thank you,
Andrew

**Comment by isangines** [comment]
Many thanks Andrew for your quick response! Yes, that solved the issue 😊

Thanks,
Ivan
