### ISSUE TITLE
A11Y: radiogroup redundant labelling (VoiceOver)

### ISSUE THREAD

**Issue by saltdotac** [surveyjs/survey-library#4121]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug.

### What is the current behavior?
Screenreaders read redundant information when selecting radio inputs. For example, 

### What is the expected behavior?
Each choice would be read once. If the label contains text content there's no need for an `aria-label` on the `<label>`

### How would you reproduce the current behavior (if this is a bug)?
1. Open Voiceover
2. Navigate to the [radio sample page](https://surveyjs.io/Examples/LibrarySinglePage?id=questiontype-radiogroup&platform=Reactjs&theme=modern)
3. tab to a choice and see it read twice

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Examples/LibrarySinglePage?id=questiontype-radiogroup&platform=Reactjs&theme=modern

### Specify your

* browser: Firefox
* browser version: 99.0b3
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.9.19

**Comment by saltdotac** [comment]
The ARIA example works fine in Voiceover, with no issues of duplication. It also does not duplicate the text content of the radio in an aria-label, as described in the issue.

**Comment by dmitrykurmanov** [comment]
@saltdotac in that case it looks like a bug I will investigate the issue and write back asap

**Comment by dmitrykurmanov** [comment]
We've done some investigations and can't find fast way to fix the problem. We decided to add this ticket to our backlog for a while and we will return to it a bit later.

**Comment by dmitrykurmanov** [comment]
closed in favor of https://github.com/surveyjs/survey-library/issues/6859
