### ISSUE TITLE
Typescript types for survey-knockout are incorrect as of 1.9.20

### ISSUE THREAD

**Issue by JosephBrooksbank** [surveyjs/survey-library#4125]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
`property 'choices' does not exist on type 'Question'`
`property 'itemValue' does not exist on type 'ItemValue'`

### What is the expected behavior?
'choices' should be recognized as a valid field on type 'Question' and 'itemValue' should be recognized as a valid field on type 'ItemValue'.

### How would you reproduce the current behavior (if this is a bug)?
Update survey-knockout from `1.8.63` to `1.9.20` (supposed to be [BACKWARDS COMPATIBLE](https://semver.org/)) 
Observe linter giving errors that cause no behavioral issues when suppressed with `ts-ignore`.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
const getAnswerNames = ( question: Question ) => question.choices.map( ( itemValue: ItemValue ) => itemValue.text );

```

### Specify your

* browser: NA
* browser version: NA
* surveyjs platform (angular or react or jquery or knockout or vue): knockout (creator)
* surveyjs version: 1.9.20

**Comment by andrewtelnov** [comment]
@JosephBrooksbank Question doesn't have "choices" property indeed. You have to cast to "QuestionSelectBase" class where this property is introduced.
and ItemValue doesn't have public property itemvalue.
We started to use our own type script generator. All others failed on our libraries and we decided to go with our own.

Thank you,
Andrew

**Comment by JosephBrooksbank** [comment]
Thanks, that makes sense about casting. I was actually accessing the 'text' field on `ItemValue`, not sure why I was getting a typing error before- that has gone away. Thanks for the explanation!
