### ISSUE TITLE
Angular : Navigation title locales in the progressbar of a survey

### ISSUE THREAD

**Issue by Nicolasprrt** [surveyjs/survey-library#4144]
### Are you requesting a feature, reporting a bug or asking a question?
reporting a Bug

### What is the current behavior?
When I'm filling a multilingual survey
The locales of the progress bar (type : 'buttons') do not display properly (only  opened and current pages navigation titles are in the correct language, the others are still in  'default'

### What is the expected behavior?
We expect that all the navigation titles in the progress bar (type:'buttons') have all the correct language when the survey is displayed.

### How would you reproduce the current behavior (if this is a bug)?
Create a multilingual survey , enable the progressbarType 'buttons' , change the language of your app. 

### Specify your

* browser: Chrome
* browser version: 99.0.4844.82
* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version: 1.9.20

**Comment by andrewtelnov** [comment]
@Nicolasprrt It has been fixed in [v1.9.21](https://surveyjs.io/WhatsNew#v1.9.21).

Thank you,
Andrew
