### ISSUE TITLE
File names are overlapping

### ISSUE THREAD

**Issue by rendaforstmane** [surveyjs/survey-library#4148]
Long file names are overlapping in the preview on mobiles
Question type  - file, multiple

<img width="304" alt="Screenshot 2022-03-24 at 18 10 15" src="https://user-images.githubusercontent.com/84146240/159961420-77127d2f-a047-4757-acb9-2f1b606444e1.png">

**Comment by novikov82** [comment]
@rendaforstmane 
Can you test the last release? 
It works correctly on narrow screens:
https://plnkr.co/edit/8Me3gnUbwdCrz5z6
![image](https://user-images.githubusercontent.com/29385489/160398919-769e47e9-48be-42ae-8049-15fed02abfb2.png)

**Comment by rendaforstmane** [comment]
Arrows are something you implemented and are not yet available in the latest release(1.9.21.)? we use the latest one, but I can't see them on mobiles. 
But I still got issues with long names in files.
![Screenshot 2022-03-28 at 16 23 54](https://user-images.githubusercontent.com/84146240/160408003-d9e2af90-1524-4863-a2cf-99ead3f941a3.png)
On mobile in your example looks good :) 
![Screenshot 2022-03-28 at 16 24 31](https://user-images.githubusercontent.com/84146240/160408089-1f6e9fa5-1680-4528-b062-dc2f7203bed4.png)

**Comment by novikov82** [comment]
You can see in my plunker sample that I used version 1.9.21. There arrows appeared in mobile mode (when the container is 600px or less).
For the long names in desktop mode - you are right, there is still a bug. We gonna work on it in nearest time.
