### ISSUE TITLE
How do I hide the ‘Edit’ button when I manually enter preview mode

### ISSUE THREAD

**Issue by ZengJun-cloud** [surveyjs/survey-library#4167]
### Are you requesting a feature, reporting a bug or asking a question?
question

### What is the current behavior?
I manually enter preview mode, and also see the 'Edit' button

### What is the expected behavior?
I manually enter preview mode, don`t see the 'Edit' button

### How would you reproduce the current behavior (if this is a bug)?
I manually enter preview mode.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
     // res is api response values
      for (const key in res) {
        if (res[key]) {
          this.survey.getQuestionByName(key).value = res[key];
        }
      }
      this.survey.showPreview()
```

### Specify your

* browser:  Google Chrome
* browser version: 99.0.4844.82
* surveyjs platform (angular or react or jquery or knockout or vue): "survey-react": "1.9.20",
* surveyjs version: "survey-core": "^1.8.64",

**Comment by andrewtelnov** [comment]
@ZengJun-cloud In this case you do not need to go into preview mode, but go into display mode:
`survey.mode = "display";`

Thank you,
Andrew

**Comment by ZengJun-cloud** [comment]
> 

I want to see all questions

**Comment by andrewtelnov** [comment]
You can set [survey.questionsOnPageMode](https://surveyjs.io/Documentation/Library?id=surveymodel#questionsOnPageMode) to "singlePage" to get all questions on one page.

Thank you,
Andrew

**Comment by ZengJun-cloud** [comment]
> You can set [survey.questionsOnPageMode](https://surveyjs.io/Documentation/Library?id=surveymodel#questionsOnPageMode) to "singlePage" to get all questions on one page.
> 
> Thank you, Andrew
