### ISSUE TITLE
Survey property `renderedElement` disappeared since v1.9.13

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#4176]
### Are you requesting a feature, reporting a bug or asking a question?
Question, I think.

### What is the current behavior?
It seems the property `renderedElement` on the `Survey` model disappeared. You used to be able to do `survey.renderedElement` to obtain the render root used.

### What is the expected behavior?
I expected the `renderedElement` to be available. But after inspecting the code (knockout) it turns out this property has been private for a very long time, so maybe it was never meant to be available.

This works in v1.9.12 but no longer works in v1.9.13

I reckon it has to do with the overhaul of `kosurvey.ts`.

https://github.com/surveyjs/survey-library/compare/v1.9.12...v1.9.13

**Comment by andrewtelnov** [comment]
@SamMousa Sorry for being late on this issue.
We killed platform specific Survey Models and keep only one model that works for all platforms: knockout, vue, react. It helps us to remove a lot of code in Creator V2 and make code cleaner.
As result of this refactoring we remove this private field.

Thank you,
Andrew
