### ISSUE TITLE
OnDownloadFile not triggered when programmatically setting survey data.

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#4179]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
When loading survey for a file question programmatically, when viewing the file question, `OnDownloadFile` is not triggered.
Instead the value of the `content` field in the question's value is used as the source for an image tag.

### What is the expected behavior?
It should trigger the `OnDownloadFile` event so that we can use the content (which in our case is a UUID) to generate a URL and download the file.

### How would you reproduce the current behavior (if this is a bug)?
Not sure, how to reproduce it easily in a system that does not have some built-in way to preload survey data. I could demo  it in our environment.

### Specify your

* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: v1.9.5

FYI: I'm on 1.9.5 because we have some other problems introduced in v1.9.13 which prevent us from moving to the latest version.

**Comment by tsv2013** [comment]
File content is actually need for preview only. Do you see file preview?

**Comment by SamMousa** [comment]
I see a broken preview. Because the uuid I'm storing in content is not a valid URL. Instead, if the event is called with that uuid in the content it will construct the URL and call the callback with a data URI for the preview (as per examples in the docs)

**Comment by tsv2013** [comment]
Can you share a live example here - it looks like I don't understand the case right now

**Comment by SamMousa** [comment]
Hmm, found the issue! Turns out the downloading of files happens before survey rendering. I happened to load the old data before registering upload & download handlers so the default dummy handler was called.

Thanks for the responses, I'll close this although my points on documentation still stands I think :)
