### ISSUE TITLE
choicesByUrl.run() is not fetching data from rest api in dynamic panel

### ISSUE THREAD

**Issue by paragkulkarni** [surveyjs/survey-library#4193]
const dyanamicPanel = Survey.getQuestionByName('InterestedPartiesPanel') as Survey.QuestionPanelDynamic;
    const templatePanel = dyanamicPanel.template as PanelModel;
    const question:any = templatePanel.getQuestionByName("AddressCountry")
    question.choicesByUrl.url = "restAPI url"
    question.choicesByUrl.run();   --->> ######################**Not working**#################

Is it any solution for fetching rest api in dynamic panel

**Comment by andrewtelnov** [comment]
@paragkulkarni Replied [here](https://surveyjs.answerdesk.io/ticket/details/T9161).

Thank you,
Andrew
