### ISSUE TITLE
React: chaning question comment in code doesn't update comment text area

### ISSUE THREAD

**Issue by iaminvictus1993** [surveyjs/survey-library#4205]
A  checkbox type question, I can't clear it's comment value by clearValue/setComment

### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

click clear comment button should clear its comment value, but not

### What is the expected behavior?

click clear comment button can clear its comment value

### How would you reproduce the current behavior (if this is a bug)?
1. input some value in the other/comment box
2. click  clear comment
3. the comment value should be removed
#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codesandbox.io/s/xenodochial-chebyshev-4kbwle

Test code

```
            this.survey.setComment("car", null);
            this.survey.clearValue("car");

```

### Specify your

* browser: chrome
* browser version: 99.0.4844.84 (Official Build) (64-bit) (cohort: Stable) 
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version:  1.9.22

**Comment by andrewtelnov** [comment]
@iaminvictus1993 Fixed by the commit above.

Thank you,
Andrew
