### ISSUE TITLE
choicesFromQuestion when targeting generic array value question

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#4209]
### Are you requesting a feature, reporting a bug or asking a question?

feature/bug

### What is the current behavior?

I'd like to to populate dropdown question choices by collecting paneldynamic/matrixdynamic specific question value.
I am trying to do that by leveraging choicesFromQuestion prop and custom function. The target question from which I'd like to fetch choices from with choicesFromQuestion is an expression that produce an array as value (like checkbox questions do)

https://plnkr.co/edit/ht0cOqmY4eRnNw1O?preview

How can I reach my goal?

thank a lot

**Comment by cinziasala** [comment]
Hi all,
Any chance to have it implemented?
Thanks a lot

**Comment by andrewtelnov** [comment]
@masciugo You have a pretty specific case, I would suggest to handle survey.onValueChanged event and update your dropdown questions in the panel dynamic in the code.

Thank you,
Andrew

**Comment by masciugo** [comment]
[implemented](https://github.com/surveyjs/survey-library/pull/6684). thank you
