### ISSUE TITLE
Move all project from nodejs 14 to latest stable

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-library#4230]
For now our projects required node 14 we need to support npm run build on latest stable nodejs (16)

how to reproduced: install latest stable nodejs. go to the library. npm run build_prod

**Comment by tsv2013** [comment]
I've fixed peer dependency via the
```JSON
  "overrides": {
    "karma-webpack": {
      "webpack": "^4.43.0"
    }
  },
```
config.

See the https://github.com/surveyjs/survey-library/actions NodeJS XX.x build actions

We need to migrate to Webpack 5 and fix all dependencies. But it will be another task.
