### ISSUE TITLE
knockout: dropdown is not updated options on changing survey locale

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#4261]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

When creating a matrix multiple choice question you can override the choices for a column by settings the cell type to `dropdown` instead of `default`. 
Then using the translation tab you can translate these choices.

### What is the expected behavior?

I expected the translations for the column specific choices to be used, but they are not.
Note that even the primary choices are not translated (tested via the preview tab)

### How would you reproduce the current behavior (if this is a bug)?
```
{
 "logoPosition": "right",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "question1",
     "columns": [
      {
       "name": "Column 1",
       "cellType": "dropdown",
       "choices": [
        {
         "value": "item1",
         "text": {
          "default": "A",
          "nl": "A1"
         }
        },
        {
         "value": "item2",
         "text": {
          "default": "B",
          "nl": "B2"
         }
        },
        {
         "value": "item3",
         "text": {
          "default": "C",
          "nl": "C2"
         }
        }
       ]
      },
      {
       "name": "Column 2"
      },
      {
       "name": "Column 3"
      }
     ],
     "choices": [
      {
       "value": 1,
       "text": {
        "default": "E1",
        "nl": "D1"
       }
      },
      {
       "value": 2,
       "text": {
        "default": "E2",
        "nl": "D2"
       }
      },
      {
       "value": 3,
       "text": {
        "default": "E3",
        "nl": "D3"
       }
      },
      {
       "value": 4,
       "text": {
        "default": "E4",
        "nl": "D4"
       }
      },
      {
       "value": 5,
       "text": {
        "default": "E5",
        "nl": "D5"
       }
      }
     ],
     "rows": [
      "Row 1",
      "Row 2"
     ]
    }
   ]
  }
 ]
}
```

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/create-survey

### Specify your

* browser: Brave
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: latest

**Comment by andrewtelnov** [comment]
@SamMousa I go to our SurveyJS Creator, drop matrix dynamic question, select a column, change cellType to "dropdown", then go to choices and add new choices, then go to translation tab, add a "Deutsch" and translate them, then go to JSON and everything were correct.
What should I do differently to reproduce it?

Thank you,
Andrew

**Comment by SamMousa** [comment]
This is a screenrecording of the default case, using the question choices not column specific ones.

https://user-images.githubusercontent.com/547021/164467194-03b223aa-5786-4b77-be42-8873df8d520c.mp4
