### ISSUE TITLE
Question: Select2 tagbox AJAX vs choicesByUrl

### ISSUE THREAD

**Issue by isangines** [surveyjs/survey-library#4277]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

Hi Survey JS team, 

We have different dropdowns depending on others, take those 2 samples:

Dropdown 1

```
 {
  "type": "dropdown",
  "name": "filterBy",
  "startWithNewLine": false,
  "renderAs": "select2",
  "title": "Filter by",
  "titleLocation": "hidden",
  "choicesByUrl": {
    "url": "Columns?group={panel.group}",
    "valueName": "value",
    "titleName": "name"
}
```
Dropdown 2:
 ```
{
  "type": "tagbox",
  "renderAs": "select2",
  "name": "limiterDropdown",
  "startWithNewLine": false,
  "title": "Limiter",
  "titleLocation": "hidden",
  "visible": false,
  "choicesByUrl": {
      "url": "Data?columnName={panel.filterBy}",
      "valueName": "value",
      "titleName": "name"
  },
}
```
They are working perfectly fine, however, there are times that the second dropdown above can have +1000 items and the type tagbox doesn't handle well that (the dropdown freezes and takes long time (+1 min) to load the results to the user) so we want to add pagination via AJAX to the select2 component.  When adding the AJAX config within the `select2Config` option and having the URL similar to:

```
ajax: {
           url: 'Data?columnName={panel.filterBy}'
...
```

The URL is not being resolved when doing the call to the endpoint (i.e. it's not picking the value from the previous dropdown same as the choicesByUrl)

So our questions are:

1. Is there a better way to handle the performance of the type tagbox instead of pagination (without tagbox. the dropdown van cope with +1000 items)?
2. if we need to use AJAX for pagination, how we can control the URL given a dependent value?

Thanks for you help!

### Specify your

* browser: Microsoft Edge Chromium
* browser version: 99.0.1150.36
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.9.19

**Comment by tsv2013** [comment]
Here we have intersection between built-in functionality (choices by url) and select2 options (AJAX).  We don't want to support select2 in the future - we want to implement all necessary functionality out of the box. Right now we're working on the dropdown enhancements in this thread - https://github.com/surveyjs/survey-library/issues/3840
We'll take in account this case.

Is it a crucial issue for you? In this case we could try to find a workaround for you.

**Comment by isangines** [comment]
Thank you @tsv2013 @OlgaLarina  looking forward to seeing that implemented in new versions!

For my scenario, it'd be great if you can please provide a workaround, as it's for a customer.

I've managed to get the pagination working on client-side using this workaround found in SO https://stackoverflow.com/a/57468425 however as it's inside a panel when adding a new row and trying to edit the dropdown from the previous row, the select has the values of the new dropdown. i.e. Imagine 2 dropdowns per row and the user selects countries, then the 2nd dropdown with pagination will display countries, then the user adds a new row and instead of countries, they select continents so the second dropdown displays continents. If the user goes back to the countries dropdown, then the dropdown displays continents instead of countries. Ideally, each dropdown should have its own values.

Thanks for your help!

**Comment by JaneGaid** [comment]
Hello @isangines,
For the record: we decided to create a separate issue and collect customer inquiries in one place: [Dropdown, Tagbox - Improve performance when working with large data sets](https://github.com/surveyjs/survey-library/issues/4780).
