### ISSUE TITLE
Bug: onShowingPreview doesn't get called if onServerValidateQuestions is set

### ISSUE THREAD

**Issue by StephBrouil** [surveyjs/survey-library#4290]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug.

### What is the current behavior?

`onShowingPreview` doesn't get called when `onServerValidateQuestions` is set.

### What is the expected behavior?

`onShowingPreview` should be called even if `onServerValidateQuestions` is set.

### How would you reproduce the current behavior (if this is a bug)?

Using the test page provided below, you'll notice that `onShowingPreview` is never printed unless you remove the assignment of the `onServerValidateQuestions` event on the survey.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/6Sy4Rx5lK9rjA9eD

Test code

```
Survey
    .StylesManager
    .applyTheme("modern");

//assign call to onServerValidateQuestions callback
function surveyValidateQuestion(survey, options) {
    options.complete();
}

//assign call to onShowingPreview callback
function showingPreview(survey, options){
    console.log("onShowingPreview");
}

var json = {
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "boolean",
     "name": "question1",
     "isRequired": true
    }
   ]
  },
  {
   "name": "page2",
   "elements": [
    {
     "type": "boolean",
     "name": "question2",
     "isRequired": true
    }
   ]
  }
 ],
 "showPreviewBeforeComplete": "showAllQuestions"
};

window.survey = new Survey.Model(json);

survey
    .onComplete
    .add(function (sender) {
        document
            .querySelector('#surveyResult')
            .textContent = "Result JSON:\n" + JSON.stringify(sender.data, null, 3);
    });

survey
    .onShowingPreview
    .add(showingPreview);

survey
    .onServerValidateQuestions
    .add(surveyValidateQuestion);

$("#surveyElement").Survey({model: survey});

```

### Specify your

* browser: Microsoft Edge
* browser version: 100.0.1185.50
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.9.20

**Comment by andrewtelnov** [comment]
@StephBrouil I have fixed the issue by the commit above. My collegues should prove my PR and merge it. The fix should be availalble in [v1.9.28](https://surveyjs.io/WhatsNew#v1.9.28).

Thank you,
Andrew
