### ISSUE TITLE
survey-vue-ui doesn't work with Typescript: no declaration for type Survey

### ISSUE THREAD

**Issue by metaturso** [surveyjs/survey-library#4326]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a possible bug with `survey-vue-ui` and the [VueJS getting started project](https://github.com/surveyjs/code-examples/tree/main/get-started-vue).

This report is vaguely similar to #4036, albeit it can't be patched by using a fully qualified type.

### What is the current behavior?

This code taken from the example:
```ts

<template>
  <Survey :survey="survey" />
</template>

<script>
import 'survey-core/modern.min.css';
import { StylesManager, Model } from 'survey-core';
import { Survey } from 'survey-vue-ui'; 
// NOTE: The text in the get-started-vue example is missing the closing apostrophe. I added it for the sake of a mcve.
// The documentation refers to GitHub as GutHub. Don't forget to feed your developers :)

StylesManager.applyTheme("modern");

const surveyJson = {
  elements: [{
    name: "FirstName",
    title: "Enter your first name:",
    type: "text"
  }, {
    name: "LastName",
    title: "Enter your last name:",
    type: "text"
  }]
};

export default {
  name: 'MyFirstSurvey',
  components: {
    Survey
  },
  data() {
    const survey = new Model(surveyJson);
    return {
      survey
    }
  },
}
</script>
```

Produces the following error:
```
TS2305: Module '"node_modules/survey-vue-ui/survey-vue-ui"' has no exported member 'Survey'.
```

I've installed packages as suggested by the documentation, i.e.:

```bash
npm install survey-vue-ui --save
```

### What is the expected behavior?

- The code from the get-started-vue project works with surveyjs and Typescript.
- The documentation is updated to reflect changes in the `survey-core` API 1.19.28

### How would you reproduce the current behavior (if this is a bug)?

1. Create a blank project
2. Follow this guide https://surveyjs.io/Documentation/Library?id=get-started-vue
3. Use Typescript components by adding `lang="ts"` to the `<script>` tag in the Vue SFC
4. The IDE or Typescript compiler reports the problem importing the `Survey` component from `survey-vue-ui`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```ts
import { Model } from 'survey-core';
import { SurveyModel } from 'survey-vue-ui';
```

### Specify your

* browser: N/A.
* browser version: N/A.
* typescript version: 4.1.3
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.9.28
* survey-vue-ui version: 1.9.28

**Comment by andrewtelnov** [comment]
@RomanTsukanov Please take a look.

Thank you,
Andrew

**Comment by RomanTsukanov** [comment]
Hi @metaturso,

I fixed the issues in the docs: https://github.com/surveyjs/survey-library/pull/4328. Thanks for bringing them to our attention.

As for the TS issues, @andrewtelnov will look into them a bit later.

**Comment by andrewtelnov** [comment]
@metaturso @RomanTsukanov I have fixed our d.ts generator. Indeed it did not generate vue d.ts correctly after we change our webpack entries for vue, it stopped work. It will be fine in v1.9.30.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@metaturso It is better to use v1.9.31, since there were some issues with react typing in v1.9.30 :) that is why we made v1.9.31 on the next day after releasing 1.9.30.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@metaturso I have installed "npm i survey-vue-ui" and in file "survey-vue-ui.d.ts" I have the following class on one line: 341
```ts
export declare class Survey extends BaseVue {
  constructor();
  survey: SurveyModel;
  model: SurveyModel;
  processedCompletedHtmlValue: string;
  updater: number;
  get pageId(): string;
  get navId(): string;
  protected getModel(): Base;
  get vueSurvey(): SurveyModel;
  onPropertyChanged(value: string, oldValue: string): void;
  forceUpdate(): void;
  protected onMounted(): void;
  beforeDestroy(): void;
  get hasTitle(): boolean;
  get hasCompletedPage(): boolean;
  get css(): any;
  getProcessedCompletedHtml(): string;
  getCompletedStateClasses(): any;
  start(): void;
  doTrySaveAgain(): void;
}
```

Thank you,
Andrew
