### ISSUE TITLE
csp policy with survey-angular

### ISSUE THREAD

**Issue by gawielgo** [surveyjs/survey-library#4331]
I cloned the library developed in native angular, everything works perfectly, the only problem is that adding the following csp policy:

meta http-equiv="Content-Security-Policy" content="script-src 'strict-dynamic' 'nonce-rAnd0m123' 'unsafe-inline' http: https:;
    object-src 'none';base-uri 'none';"

as google's csp evaluator recommends, but I encounter the problem shown in the figure:

![Cattura](https://user-images.githubusercontent.com/42548156/167628692-ef2a8125-ad24-458f-9713-9ec3e0b3e87d.PNG)

### Are you requesting a feature, reporting a bug or asking a question? 
a bug

### What is the current behavior?
the error shown in the figure

### What is the expected behavior? 
no errors with the csp policy

### How would you reproduce the current behavior (if this is a bug)? 
deploying an angular project in which the survey-angular library has been installed and where the recommended csp policy tag has been inserted

### Specify your

* browser: chrome
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: 1.9.28

**Comment by andrewtelnov** [comment]
@gawielgo We are using knockout for rendering in Angular widget. We are working on Angular rendering right now and, it is probably, in couple months we will have Angular rendering and "survey-angular-ui" package that will not have this issue.
Knockout templates are parsed by using `eval` function.
So, it is in our plans to have Angular rendering for SurveyJS Library and later for Survey Creator, as we do it for react.
In fact, we are already working on it.

Thank you,
Andrew

**Comment by rizzaccio87** [comment]
@andrewtelnov are there any news about it? 
I installed the "survey-angular-ui" library (v 1.9.53) and I tried to use it: the CSP issue `unsafe-eval` doesn't seem to be anymore.
I tried to use a component of the new library, but I did not find documentation about: where could I find it?
When will a stable version of the "survey-angular-ui" library and survey creator?
Thanks

**Comment by tsv2013** [comment]
@rizzaccio87 We've released "survey-angular-ui" library several months ago and right now are preparing for the "survey-creator-angular" release. It's planned to be released in the month or so. You can track our social networks https://twitter.com/surveyjs and https://www.facebook.com/SurveyJS

**Comment by rizzaccio87** [comment]
@tsv2013 the [documentation ](https://surveyjs.io/form-library/documentation ) refers to survey-angular npm package and not to the new library. Where could I find API documentation and examples of use for survey-angular-ui library? Thanks

**Comment by tsv2013** [comment]
@rizzaccio87 I thought it's ready. But looks like it's under development for while. It will be available on the official Angular CreatorV2 release.
