### ISSUE TITLE
Official timeline for React 18 support?

### ISSUE THREAD

**Issue by AntonOfTheWoods** [surveyjs/survey-library#4350]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
No official React 18 support

### What is the expected behavior?
Official React 18 support

### How would you reproduce the current behavior (if this is a bug)?
Install with React 18

I couldn't find a ticket on official React 18 support so thought it would be nice for the community to have some visibility on this.

**Comment by andrewtelnov** [comment]
@AntonOfTheWoods Our libraries works for react 18. 

Thank you,
Andrew

**Comment by AntonOfTheWoods** [comment]
Thanks @andrewtelnov , I agree they appear to work, I am talking about being able to install without npm errors 

https://github.com/surveyjs/survey-library/blob/master/build-scripts/survey-react/package.json

```
  "peerDependencies": {
    "react": "^16.5.0 || ^17.0.1",
    "react-dom": "^16.5.0 || ^17.0.1"
  }
```

**Comment by andrewtelnov** [comment]
@AntonOfTheWoods  Indeed, we will need to change it. Let us discuss it today in the team.

Thank you,
Andrew

**Comment by tsv2013** [comment]
I've fixed dependencies
