### ISSUE TITLE
Вопрос про логику перехода в вопросах.

### ISSUE THREAD

**Issue by stevenKirill** [surveyjs/survey-library#4374]
Привет. Хотел узнать если можно плз как ты реализовал логику перехода между вопросами вперед назад? По глобальному индексу типо i +1 на следующую страницу или i - 1 на предыдущую или есть какое то более умное решение? Делаю такую штуку для банка одного приложение и хотел узнать совет. Буду благодарен очень!

**Comment by stevenKirill** [comment]
Я не нашел как можно пометить label question мой вопрос к сожалению(

**Comment by andrewtelnov** [comment]
@stevenKirill Are you looking for [survey.currentPageNo](https://surveyjs.io/Documentation/Library?id=surveymodel#currentPageNo) or [survey.nextPage()](https://surveyjs.io/Documentation/Library?id=surveymodel#nextPage), [survey.prevPage()](https://surveyjs.io/Documentation/Library?id=surveymodel#prevPage) functions?

Thank you,
Andrew

**Comment by stevenKirill** [comment]
Yes, I want to ask how did you make logic to navigate next and prev page in quiz ?

**Comment by andrewtelnov** [comment]
@stevenKirill Were you looking for these functions? Do you need more help on this?

Thank you,
Andrew

**Comment by stevenKirill** [comment]
I mean how does it wotk under the hood ?

**Comment by dmitrykurmanov** [comment]
@stevenKirill SurveyJS Library is totally open source. So you could find any code here in the repo or you could clone it locally. For example, [nextPage function](https://github.com/surveyjs/survey-library/blob/5d8eee2ea9cd6c215d0012d7f2e2e7c1c386a3a4/src/survey.ts#L3229)
