### ISSUE TITLE
direction RTL not supported

### ISSUE THREAD

**Issue by DevAhmad7** [surveyjs/survey-library#4401]
### Is it possible to support the direction of the page from right to left?

![Screenshot (191)](https://user-images.githubusercontent.com/55281583/171467216-b819b49b-6897-48f9-a1f6-14e165140d3e.png)

![Screenshot (190)](https://user-images.githubusercontent.com/55281583/171467211-ce5c9bba-50d1-4412-aa07-e40e9c8e82c5.png)

**Comment by tsv2013** [comment]
Closed as duplicate for https://github.com/surveyjs/survey-creator/issues/3071
