### ISSUE TITLE
Ranking option disappears on mobile.

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#4417]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Sometimes a ranking question option disappears; I tested this survey

### What is the expected behavior?
Options should never disappear from screen

### How would you reproduce the current behavior (if this is a bug)?
- Open the link below on a mobile phone
- Zoom in so the 3 options don't fully fit on your screen
- Pick up option and reorder them several times

#### Provide the test code and the tested page URL (if applicable)
Tested page URL: https://surveyjs.io/published?id=aa17f177-c849-42a9-b273-3f085aaa2fff

Test code

```json
{
 logoPosition: "right",
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "ranking",
     name: "question1",
     choices: [
      "item1",
      "item2",
      "item3"
     ]
    }
   ]
  }
 ]
}

```

### Specify your

* browser: Brave (Chrome 102) on Android
* browser version: 102
* surveyjs platform (angular or react or jquery or knockout or vue):  knockout
* surveyjs version: v1.9.26 AND v1.9.34

**Comment by andrewtelnov** [comment]
@SamMousa Are you talking about drag&drop issues or it disappeard completely?

Thank you,
Andrew

**Comment by SamMousa** [comment]
Disappeared completely

**Comment by andrewtelnov** [comment]
@dmitrykurmanov Please take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@SamMousa FYI: We have another user that has the same issue. @dmitrykurmanov  is working on it.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
@SamMousa as Andrew said it was already a known problem but in some other cases. Anyway, I believe it was fixed via the https://github.com/surveyjs/survey-library/commit/cd94ec42d38529b7e2c54e492133de7ce7aa4e99 and will be available in the next minor update.
