### ISSUE TITLE
Add animation features to Library out of the box

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-library#4442]
Current state of Survey animation is here:
https://surveyjs.io/Examples/Library?id=survey-animation&platform=Reactjs&theme=defaultV2#content-result

Maybe we need some more impressive solutions.

**Comment by tsv2013** [comment]
See also the following issues:
https://github.com/surveyjs/survey-library/issues/1770
https://github.com/surveyjs/survey-library/issues/2588
https://github.com/surveyjs/survey-library/issues/4907

**Comment by tsv2013** [comment]
https://github.com/surveyjs/survey-library/issues/1385
