### ISSUE TITLE
Triggers: enable question and skip to the question do not work at once.

### ISSUE THREAD

**Issue by Matvey1308** [surveyjs/survey-library#4455]
**Are you requesting a feature, reporting a bug or asking a question?** 
Bug

**What is the current behavior?**
Triggers. There's a radiobutton question (question1) with 3 items and question13 (default text input. It is disabled initially). There is a condition:

{question1} == 'item2') or ({question1} == 'item3' => Make question {question13} enable Survey skip to the question {question13}

When I clicked 'item2' for the first time, It did not skip me to question13, but it becomes enabled, but when I click 'item3', it skips me to question13, because it is already enabled.

The main issue is that currently this setup of triggers (enable + skip) does not work.

**What is the expected behavior?**
After clicking 'item2' or 'item3', it should enable question13 and skip me to question13 at once.

**How would you reproduce the current behavior (if this is a bug)?**
1. Create radiobutton question (question1) and disabled text input (question2).
2. Create a condition: {question1} == 'item2') or ({question1} == 'item3' => Make question {question2} enable Survey skip to the question {question2}
3. Go to survey.
4. Click item2.
5. It should only enable question2.

**Provide the test code and the tested page URL (if applicable)**
Tested page URL: https://plnkr.co/edit/NX7E6BxCVkVs9gAV

Test code

var json = {
"title": "SimultaneousEnableAndSkip",
"pages": [
{
"name": "page1",
"elements": [
{
"type": "radiogroup",
"name": "question1",
"id": 2759,
"choices": [
{
"value": "item1",
"id": 38117
},
{
"value": "item2",
"id": 38118
},
{
"value": "item3",
"id": 38119
}
]
},
{
"type": "text",
"name": "question2",
"id": 2760
},
{
"type": "text",
"name": "question3",
"id": 2761
},
{
"type": "text",
"name": "question4",
"id": 2762
},
{
"type": "text",
"name": "question5",
"id": 2763
},
{
"type": "text",
"name": "question6",
"id": 2764
},
{
"type": "text",
"name": "question7",
"id": 2765
},
{
"type": "text",
"name": "question8",
"id": 2766
},
{
"type": "text",
"name": "question9",
"id": 2767
},
{
"type": "text",
"name": "question10",
"id": 2768
},
{
"type": "text",
"name": "question11",
"id": 2769
},
{
"type": "text",
"name": "question12",
"id": 2770
},
{
"type": "text",
"name": "question13",
"enableIf": "{question1} = 'item2' or {question1} = 'item3'",
"readOnly": true,
"id": 2771
}
],
"navigationButtonsVisibility": "show",
"id": 358
}
],
"triggers": [
{
"type": "skip",
"expression": "{question1} = 'item1'",
"gotoName": "question2"
},
{
"type": "skip",
"expression": "{question1} = 'item2' or {question1} = 'item3'",
"gotoName": "question13"
}
],
"name": "SimultaneousEnableAndSkip",
"id": 164
};

Specify your
browser: Chrome 102
browser version: 102
surveyjs platform (angular or react or jquery or knockout or vue): React
surveyjs version: v1.9.26 AND v1.9.35

**Comment by andrewtelnov** [comment]
@Matvey1308 Indeed, I can confirm the issue.
We will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@Matvey1308 It is fixed by the commit above.

Thank you,
Andrew
