### ISSUE TITLE
Allow edit panel dynamic empty text in Creator

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-library#4466]
![image](https://user-images.githubusercontent.com/29385489/174729808-356a72bb-5241-47c6-be58-956be707cba9.png)

**Comment by novikov82** [comment]
@mikeamelin 
we can edit the texts using Property Grid:
![image](https://user-images.githubusercontent.com/29385489/177990062-ecc47744-a5a0-4606-9624-8b315dd45e98.png)
This texts are never shown on design surface. To edit them there we need some redesign.

**Comment by mikeamelin** [comment]
Looks like this is the issue, that Andrew fixed some time ago.
