### ISSUE TITLE
Show Message based on previous selected item

### ISSUE THREAD

**Issue by go-sudo** [surveyjs/survey-library#4492]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

I'm using smarty to show date of the selected item only (checkbox or dropdown) 

but the messages display the information of all item, even those are not selected

### What is the expected behavior?

I would like to display the information for only the selected item

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

https://i.im.ge/2022/06/23/uXGcBW.gif
```

{literal}
        <script type="text/javascript">Survey
    .StylesManager
    .applyTheme("defaultV2");

var json = {
  "pages": [
    {
      "locale": "fr",
      "name": "page1",
      "elements": [
              {
         "type": "radiogroup",
          "name": "Commandes",
         "isRequired": true,
         "title": "Merci de choisir la commande",
          "colCount": 3,
          "choicesOrder": "asc",
          "choices": [ {/literal}  {foreach from=$orders item=order}
            "{$order.details.reference}",
        
          {/foreach}{literal}  ]
        },{
             
     "type": "html",
     "name": "DétailsCommande",
       "isRequired": false,
        "visibleIf": "{Commandes.length} > 1",
        "title": " ",
        "choicesFromQuestion": "Commandes",
         "choicesFromQuestionMode": "selected",
<!--it should shows the order date of the selected   "name": "Commandes"-->
     "html": "{/literal}  {foreach from=$orders item=order} {$order.details.order_date}{/foreach}{literal}"
    },
```

### Specify your

* browser:Chrome
* browser version:Version 102.0.5005.115 (Official Build) (64-bit)
* surveyjs platform jquery
* surveyjs version:1.9.2

**Comment by andrewtelnov** [comment]
@go-sudo Could you please provide the JSON or plunker with the real data?

Thank you,
Andrew

**Comment by go-sudo** [comment]
Hello @andrewtelnov 

I can not post real data with smarty, I get a suggestion from a good friend, but I do not know how to implent it with survey

https://plnkr.co/edit/oRSKRQ9Cx8yU3aDv
<script>
var my_date_aray = [];{/literal}
	{foreach from=$orders item=order}
		my_date_aray["{$order.details.reference}"] = "{$order.details.order_date}";		
	{/foreach}
	{literal}
</script>

the issue that when I select on the dropdown an order, the html show the expiration date for all orders available on the dropdown (unsellected) and not the only the selected one

Regards

**Comment by andrewtelnov** [comment]
@go-sudo Unfortunately, your example doesn't work. We need the real data to see the issue.

Thank you,
Andrew

**Comment by go-sudo** [comment]
Hello @andrewtelnov 

Please do not close this issue, I will make a html example for your

I let you know that it works when i change the type from html to checkbox but I need to display the information as text or html 
https://watch.screencastify.com/v/bVMqeguvdwrvwx977Tml
```
pages": [
    {
      "locale": "fr",
      "name": "page1",
      "elements": [
              {
         "type": "radiogroup",
          "name": "Commandes",
         "isRequired": true,
         "title": "Merci de choisir la commande",
          "colCount": 3,
          "choicesOrder": "asc",
          "choices": [ {/literal}  {foreach from=$orders item=order}
            "{$order.details.reference}",
        
          {/foreach}{literal}  ]
        },{
"type": "checkbox",
"name": "fin",
 "isRequired": false,
"visibleIf": "{Commandes.length} > 0",
//"choicesVisibleIf":"{Typologie} contains {item}",
"choices": [
 {/literal}  {foreach from=$orders item=order}
{ "value": "{$order.details.reference}", "text": "{$order.details.order_date}"},{/foreach}{literal}

],
  "choicesVisibleIf": "{Commandes} contains {item}"
},
```

**Comment by go-sudo** [comment]
Hi @andrewtelnov 

here is a demo based on html https://plnkr.co/edit/hV6XK8V6A9v78cFz

regards

**Comment by andrewtelnov** [comment]
@go-sudo opSystem should be "checkbox". Here is the [updated example](https://plnkr.co/edit/TcCqInnO3qvJ5T7z)
You are requested opSystem value to be an array.

Thank you,
Andrew

**Comment by go-sudo** [comment]
hi @andrewtelnov 

like this one https://github.com/surveyjs/survey-library/issues/1046 but instead of dropdown i need to show text please

**Comment by go-sudo** [comment]
Hi @andrewtelnov 

Thanks to you, I Found a solution to my issue, I appreciate your help
