### ISSUE TITLE
MatrixDynamic trimming bug in text and comment questions

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#4509]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
Text/comment question value is not fully trimmed in matrixdynamic.

### What is the expected behavior?
Text/comment question value is fully trimmed in matrixdynamic.

### How would you reproduce the current behavior (if this is a bug)?
When you enter values with whitespace(s) before or after the text one whitespace remains instead of all whitespace getting trimmed.

#### Provide the test code and the tested page URL (if applicable)
See this Plunker: https://plnkr.co/edit/cngMaS5c2TZpBp3p

### Specify your

* browser: Firefox/Chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): jquery (and react)
* surveyjs version: 1.9.37 and before

**Comment by Lionqueen94** [comment]
@andrewtelnov What I need is the resulting answers to be fully trimmed, and they are not, see:
`Result JSON: { "teachersRate": [ { "subject": " Maths ", "explains": 1, "improvements": " Nothing " } ] }`
There is still a space in front and behind the string and these need to be trimmed off.

**Comment by andrewtelnov** [comment]
@Lionqueen94 You can use the following code:
```js
function trimValue(options) {
  if(!!options.value && typeof options.value === "string") {
    options.value = options.value.trim();
  }
}
survey.onValueChanging.add((sender, options) => {
  trimValue(options);
});
survey.onMatrixCellValueChanging.add((sender, options) => {
  trimValue(options);
});
```
Here is the [updated example](https://plnkr.co/edit/Okg689rEc5XLAmhw).

Thank you,
Andrew

**Comment by Lionqueen94** [comment]
@andrewtelnov Thanks a lot!
```
function trimValue(options) {
  if(!!options.value && typeof options.value === "string") {
    options.value = options.value.trim();
  }
}
survey.onMatrixCellValueChanging.add((sender, options) => {
  trimValue(options);
});
```
works perfectly!
