### ISSUE TITLE
Auto select item when dropdown has 1 value

### ISSUE THREAD

**Issue by go-sudo** [surveyjs/survey-library#4515]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

dropdown asks to choose from list 

### What is the expected behavior?

Autoselect the item when has one value

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:https://plnkr.co/edit/WV7LTPKCiEZbnlkj

 {
"type": "dropdown",
"name": "ManagerGID",
"choices": [
{ "value": "item1", "text": "laim"},
{ "value": "item2", "text": "baoe"},
{ "value": "item2", "text": "lij"},
{ "value": "item2", "text": "t74104"},
{ "value": "item3", "text": "wangch"},
{ "value": "item2", "text": "z41928"}
]
},  {
      "type": "dropdown",
      "name": "EmployeeGID",
      "title": "GID",
      "choices": [
      { "value": "item1", "text": "xur"},
      {"value": "item2", "text": "q73500"},
      { "value": "item2", "text": "p41145"}, 
      { "value": "item3", "text": "j27411"},
      { "value": "item3", "text": "d00307"}
      ],
       "choicesVisibleIf": "{ManagerGID} contains {item}",
         "visibleIf": "{ManagerGID.length} > 0",
      
    }

```

### Specify your

browser:Chrome
browser version:Version 102.0.5005.115 (Official Build) (64-bit)
surveyjs platform jquery
surveyjs version:1.9.2

**Comment by andrewtelnov** [comment]
@go-sudo values in choices should be unique.

Thank you,
Andrew

**Comment by go-sudo** [comment]
@andrewtelnov not necessary
let's say that I choose a ManagerGID and this manager has only one EmployeeGID 
so I would like that the dropdown of EmployeeGID  select automatically this   Employee,

 and even it will be nice that the dropdown not be editable in this case 
because we have only one Employee

**Comment by go-sudo** [comment]
@andrewtelnov 

any example please, because I do not understand, or surveyjs does not support this option
you think I should add some JavaScript condition ?

**Comment by andrewtelnov** [comment]
You should have a unique value for every item. Otherwise, there is no way we can distinguish one item from another. User should select an item, save the repsonse into JSON and then on setting this JSON response again, we should show the same selected item.
If items are not unique, we will not be able to do it.

Thank you,
Andrew

**Comment by go-sudo** [comment]
I think I do explain bad ,

I do not want to show the same item in the 2 dropdown
{
"type": "dropdown",
"name": "FathersList",
"choices": [
{ "value": "father1", "text": "andrew"},
{ "value": "father3", "text": "Philipe"},
]
}, {
"type": "dropdown",
"name": "Sonslist",
"title": "GID",
"choices": [
{ "value": "father1", "text": "xur"},
{"value": "father1", "text": "Philippe"},
{ "value": "father1", "text": "Lisa"},
{ "value": "father1", "text": "Natasha"},
{ "value": "father3", "text": "Zara"}
],
"choicesVisibleIf": "{ManagerGID} contains {item}",
"visibleIf": "{ManagerGID.length} > 0",

father3 has one son, when I select this father the sonlist's dropdown should  auto-select the value of  'ZARA'  dropdown using jQuery or condition surveyjs

**Comment by andrewtelnov** [comment]
@go-sudo You can add a new property into "itemvalue" "father" and then create a custom function that you can use in chociesVisbileIf.

Please review adding a [new property](https://surveyjs.io/Documentation/Survey-Creator?id=property-grid) and [custom functions](https://surveyjs.io/Documentation/Library#custom-functions) topics.
You can find [maxtrix total example](https://surveyjs.io/Examples/Library?id=questiontype-matrixdynamic-totals&platform=Reactjs&theme=defaultV2#content-js) useful. It adds a property into itemvalue class and use it in a custom function.

Thank you,
Andrew

**Comment by go-sudo** [comment]
Hi @andrewtelnov 

I appreciate your help, any idea how to remove the button (add new line) from this panel please
![image](https://user-images.githubusercontent.com/11594433/176671844-544e2a43-9952-4e9d-a920-429e69fed36d.png)
