### ISSUE TITLE
how to make a multilingue surveyjs

### ISSUE THREAD

**Issue by go-sudo** [surveyjs/survey-library#4524]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

survey with default language

### What is the expected behavior?

survey  in multilanguage

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Examples/Survey-Creator/?id=multiplelanguages&platform=jQueryV2#content-result

Test code
  Survey.surveyLocalization.supportedLocales = ["en", "de", "es", "fr"];
const options = {
  showTranslationTab: true
};
var json = {
```
your_code_here

```

### Specify your

browser:Chrome
browser version:Version 102.0.5005.115 (Official Build) (64-bit)
surveyjs platform jquery
surveyjs version:1.9.2

**Comment by andrewtelnov** [comment]
@go-sudo Are you asking about creating the correct survey JSON or about SurveyJS Creator widget?
What is the question?

Thank you,
Andrew

**Comment by tsv2013** [comment]
Here is the multi lingual survey live example - https://surveyjs.io/Examples/Library?id=survey-multilanguages&platform=Reactjs&theme=defaultV2

**Comment by go-sudo** [comment]
hi @andrewtelnov 

there is no menu to select language 

https://plnkr.co/edit/hgpZ1lrLNxjUyjZa
![image](https://user-images.githubusercontent.com/11594433/176883410-0721c3a4-225c-42d8-bd5e-24744effed05.png)

**Comment by andrewtelnov** [comment]
@go-sudo It is UI that doesn't belongs to survey. Commonly language selector is located on the top right corner of the web app.
You can always set it as: `survey.locale = yourValue;`

Thank you,
Andrew

**Comment by go-sudo** [comment]
Hi @andrewtelnov 

When I add this line to the page, I get a blank page. I see no language selector in the top right corner of the web app, 
any real example please. 

![image](https://user-images.githubusercontent.com/11594433/176888908-da3b6e1d-a1b4-4c9a-93d1-251fae18a19b.png)

**Comment by andrewtelnov** [comment]
:-)
1) `yourValue` it could be "de" or "fr" and so on
2) As I wrote, languages selector UI should be implemented by you.
SurveyJS Library, widget has to be integrated into a web application. It should not have it's own language selector UI.

Thank you,
Andrew

**Comment by go-sudo** [comment]
:) Thank you very much, it works!
