### ISSUE TITLE
Multiple server validation not working as expected

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#4531]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
When the first event handler for `onServerValidateQuestions` succeeds the survey is immediately completed.

### What is the expected behavior?
In the context of a validation event which supports registering of multiple handlers, I'd expect them all to be called. The library should then wait for them all to complete before continuing.

### How would you reproduce the current behavior (if this is a bug)?
https://plnkr.co/edit/UNHpTceGwmd5fG8F

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/UNHpTceGwmd5fG8F
 
Test code

```js
Survey.StylesManager.applyTheme("defaultV2");
var json = {
  "elements": [
    {
      "type": "text",
      "name": "country",
      "title": "Type a country:"
    }
  ]
};
window.survey = new Survey.Model(json);
survey.onComplete.add((sender) => {
  document.querySelector('#surveyResult').textContent = "THIS SHOULD NOT HAPPEN";
});
survey.onServerValidateQuestions.add((survey, options) => {
 // This validation succeeds without errors
 options.complete();
});
survey.onServerValidateQuestions.add((survey, options) => {
  options.errors["country"] = "error";
 // This validation fails with errors
 options.complete();
});

survey.render("surveyElement");

```

### Specify your

* surveyjs platform (angular or react or jquery or knockout or vue):  knockout
* surveyjs version: 1.9.38

**Comment by andrewtelnov** [comment]
@SamMousa Yes, we are waiting for the first reply. We have to wait for replies from all events.

Thank you,
Andrew
