### ISSUE TITLE
Minimum and maximum rate value descriptions on rating questions dropdown layout

### ISSUE THREAD

**Issue by MuriloOnYou** [surveyjs/survey-library#4572]
### Are you requesting a feature, reporting a bug or asking a question?
Requesting a feature

### What is the current behavior?
The minimum and maximum rate value descriptions are not showed on the dropdown layout of the rating questions
![image](https://user-images.githubusercontent.com/80476785/177990016-9889cba1-404c-497e-8567-1b56b2e8f5cf.png)
![image](https://user-images.githubusercontent.com/80476785/177990034-1ea26f3e-6a62-48e0-b51c-561451e32175.png)

### What is the expected behavior?
Show the minimum and maximum rate value descriptions within the dropdown
![image](https://user-images.githubusercontent.com/80476785/177993095-5075ff92-f1df-4bc1-82ae-76386112a25f.png)

### How would you reproduce the current behavior (if this is a bug)?
Using a mobile device to answer a question of the type rating

### Specify your

* browser: Microsoft Edge
* browser version: 103.0.1264.44
* surveyjs platform (angular or react or jquery or knockout or vue): Nuxt
* surveyjs version: 1.9.21

**Comment by tsv2013** [comment]
The 1 and 5 in your case are the actually minimum and maximum rate values. I think it should be obvious for the surveyee. I've added this to our backlog.
