### ISSUE TITLE
Hide "Next" button and show "Complete" if a complete trigger is going to be executed

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#4635]
When a user choose a question value that will trigger a complete trigger then "Next" button should be hidden and "Complete" button should be shown. Here is the JSON example:
```js
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question1",
     "choices": [
      "item1",
      "item2",
      "item3"
     ]
    }
   ]
  },
  {
   "name": "page2",
   "elements": [
    {
     "type": "text",
     "name": "question2"
    }
   ]
  }
 ],
 "triggers": [
  {
   "type": "complete",
   "expression": "{question1} = 'item1'"
  }
 ]
}
```
When a user choose "item1" for the first question then "Complete" button should be shown instead of "Next" button. When the value is cleared or another value is choosen then "Complete" button should be hidden and "Next" button should be shown.

**Comment by SamMousa** [comment]
This was release in v1.9.42 btw.

Is there a way to disable this behavior? 
In market research there are screenouts where you don't want the user to know he's being screened out.

**Comment by SamMousa** [comment]
Hmm just found out this broke my custom trigger which extended the complete trigger class.
Fixed it by not doing anything unless it's a real execution.

**Comment by andrewtelnov** [comment]
@SamMousa `Survey.settings.changeNavigationButtonsOnCompleteTrigger = false;` will do the job after releasing v1.9.51.

Thank you,
Andrew
