### ISSUE TITLE
Bug: Dropdown search bar is visible when "searchEnabled" is set to false

### ISSUE THREAD

**Issue by StephBrouil** [surveyjs/survey-library#4664]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

The dropdown search bar is visible when `searchEnabled` is set to `false` (with more than 10 choices).

### What is the expected behavior?

The dropdown shouldn't display the search bar when `searchEnabled` is set to `false`.

### How would you reproduce the current behavior (if this is a bug)?

Using the test page provided below, you'll notice that the search bar in the dropdown is visible even though `searchEnabled` is set to false in the survey json.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

https://plnkr.co/edit/nFz6LbiR0UflYpnD

Test code

```
Survey.StylesManager.applyTheme("defaultV2");
var json = {
  "elements": [
    {
      "type": "dropdown",
      "name": "car",
      "choices": [
        "Ford",
        "Vauxhall",
        "Volkswagen",
        "Nissan",
        "Audi",
        "Mercedes-Benz",
        "BMW",
        "Peugeot",
        "Toyota",
        "Citroen",
        "Honda",
      ],
      "searchEnabled": false  
    }
  ]
};
window.survey = new Survey.Model(json);
survey.onComplete.add(function (sender) {
  document.querySelector('#surveyResult').textContent = "Result JSON:\n" + JSON.stringify(sender.data, null, 3);
});
var app = new Vue({
  el: '#surveyElement',
  data: {
    survey: survey
  }
});

```

### Specify your

* browser: Edge
* browser version: 103.0.1264.71
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.9.42

**Comment by schlick** [comment]
I've just come across this issue too. Good to know it's not me doing something wrong 😄

**Comment by OlgaLarina** [comment]
The issue was fixed by the [pull request](https://github.com/surveyjs/survey-library/pull/4695). Fix will be available in the nearest minor update.
