### ISSUE TITLE
Share data between questions example for valuePropertyName fails under Angular, jQuery and Knockout

### ISSUE THREAD

**Issue by schlick** [surveyjs/survey-library#4667]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

Using the _Share data between questions_ example on the SurveyJS website with Angular, jQuery or Knockout, clicking once on an unselected checkbox item on Page 2 (What car do you own?) does not check it (kinda need 2 or 3 clicks) and even when checked, the selected item is not displayed in the title of the subsequent question (Please describe your car), specifically "templateTitle": "Car: {panel.carProducer}" does not work.

React and Vue doe not exhibit this issue.

### What is the expected behavior?

Clicking the checkbox item checks it and that item name displayed in the title of the panel.

### How would you reproduce the current behavior (if this is a bug)?

Using the provided SurveyJS example, Page 2 using Angular, jQuery or Knockout.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Examples/Library?id=survey-shareddata

https://user-images.githubusercontent.com/18456/182078321-815ce5e1-8993-4dc4-9dc4-d89c80dc50d2.mov

### Specify your

* browser: Chrome and Safari
* browser version: Chrome v103, Safari v15.6 (Mac OS X)
* surveyjs platform (angular or react or jquery or knockout or vue): Angular, jQuery and Knockout exhibit the bug; React and Vue do not.
* surveyjs version: latest (1.9.42)

**Comment by andrewtelnov** [comment]
@schlick Indeed. There is a bug in knockout. Our current angular version is using knockout inside, the same with jQuery.
We are working on angular rendering right now, so it will be a different platform soon.
We will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@schlick Fixed by the commit above. I hope it will be included into next minor. My PR should be green and approved.

Thank you,
Andrew
