### ISSUE TITLE
Resizeobserver loop completed with undelivered notifications

### ISSUE THREAD

**Issue by dk981234** [surveyjs/survey-library#4692]
When resizing survey this error occurs in safari.

[T10244 - ResizeObserver loop completed with undelivered notifications](https://surveyjs.answerdesk.io/internal/ticket/details/T10244)

**Comment by JaneSjs** [comment]
+1 [T11846 - Errors in "survey-angular-ui" package](https://surveyjs.answerdesk.io/internal/ticket/details/T11846)
