### ISSUE TITLE
Panels with high nesting level look bad

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-library#4696]
![image](https://user-images.githubusercontent.com/18551316/183411678-86dfe329-e976-4f74-997b-f83a0f245d62.png)
![image](https://user-images.githubusercontent.com/18551316/183411698-94be400e-bb5f-4915-9890-3054e8748eb1.png)

You can reproduce the issue in this plunk: https://plnkr.co/edit/k3VFs4C3NBcUdBHW
Select "Married", then select "Yes" and "Other types of employment" for both you and your partner.

**Comment by dk981234** [comment]
- [ ] Fix for desktop
- [ ] Fix for small screens
