### ISSUE TITLE
[REACT] Issue on re-rendering

### ISSUE THREAD

**Issue by miky9585** [surveyjs/survey-library#4700]
Using react library and onCurrentPageChanging / onEverithingelse
with a change state internally
during page re-rendering, survey start with first question (so never go to the next one)

Example https://codesandbox.io/s/upbeat-fire-yd58s8

**Comment by andrewtelnov** [comment]
@miky9585 You are recreating the survey model "onCurrentPageChanging" event and your starting rendering a brand new model all the time. I have updated [your example](https://codesandbox.io/s/reverent-gauss-fqho45?file=/src/App.js).

Thank you,
Andrew

**Comment by miky9585** [comment]
solved using 
const [model, setModel] = useState(null)
and 
useEffect( () => {


        const _model = new Model(_SURVEY);
...etc...
        setModel(_model)
}, [])
