### ISSUE TITLE
The Survey.settings property is not documented

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-library#4731]
Survey [Library/Runner documentation](https://surveyjs.io/Documentation/Library?id=surveymodel) contains no info about the following property: [Survey.settings.executeCompleteTriggerOnValueChanged](https://github.com/surveyjs/survey-library/issues/2121).

**Comment by RomanTsukanov** [comment]
The `settings` object will be available at this link: https://surveyjs.io/Documentation/Library?id=settings
