### ISSUE TITLE
"First page is a start page" breaks navigation in survey with conditionally shown pages

### ISSUE THREAD

**Issue by ivasilyev-servicetitan-com** [surveyjs/survey-library#4737]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
1.9.45

### What is the expected behavior?
Page (a first one) should be shown

### How would you reproduce the current behavior (if this is a bug)?
Create a survey:
1. with 2 pages: p1 and p2
2. with 2 questions on the first page: q1 and q2
3. have a rule: if q1=yes, then show q2
4. have a rule: if q2=yes, then show p2
5. (important) set `firstPageIsStarted: true`
6. run surveys
ERROR: it says "There is no visible page or question in the survey."
EXPECTED: p1 with q1 should be shown (there is nothing preventing them from showing)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/published?id=078a2c6e-1125-4b6f-a82f-bed3d067cb3b

Test code

```
{
 logoPosition: "right",
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "radiogroup",
     name: "question1",
     choices: [
      {
       value: "1",
       text: "Yes"
      },
      {
       value: "0",
       text: "No"
      }
     ]
    },
    {
     type: "radiogroup",
     name: "question2",
     visibleIf: "{question1} = 1",
     title: "question2",
     choices: [
      {
       value: "1",
       text: "Yes"
      },
      {
       value: "0",
       text: "No"
      }
     ]
    }
   ]
  },
  {
   name: "page2",
   elements: [
    {
     type: "text",
     name: "question3"
    }
   ],
   visibleIf: "{question2} = 1"
  },
  {
   name: "page3"
  }
 ],
 clearInvisibleValues: "onHiddenContainer",
 firstPageIsStarted: true
}
```

### Specify your

* browser: Opera
* browser version: 89.0.4447.83
* surveyjs platform (angular or react or jquery or knockout or vue): ReactJS, but it doesn't matter
* surveyjs version: 1.9.45

**Comment by andrewtelnov** [comment]
@ivasilyev-servicetitan-com I have reproduce it. We will look at it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@ivasilyev-servicetitan-com It was fixed by the commit above.

Thank you,
Andrew
