### ISSUE TITLE
visibleIf based on selection of checkbox with valuePropertyName

### ISSUE THREAD

**Issue by schlick** [surveyjs/survey-library#4742]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question

### What is the current behavior?

When starting with a checkbox type question, I can have another question that is displayed conditionally on the value selected in the checkbox question.

When I add the `valuePropertyName` property to the checkbox question, it switches the selected values to a collection of objects as expected. However, now my original visibleIf condition no longer works which makes sense but I wonder whether there is a way to still have the conditional behaviour.

### What is the expected behavior?

Being able to show/hide another question based on the selected value in the checkbox question while using `valuePropertyName`.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/b3LbhMw5ogtRos6K

Test code

```

{
      "type": "checkbox",
      "name": "cars",
      "title": "What cars are you driving?",
      "choices": [
        "Ford",
        "BMW",
        "Toyota",
      ]
    },
    {
      "type": "text",
      "name": "specific_details",
      "title": "Tell us about your BMW car",
      "visibleIf": "{cars} = ['BMW']"
    },

```

Now add into the checkbox question:

```
"valuePropertyName": "car_name",
```

### Specify your

* browser: Chrome
* browser version: 104
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.9.45

**Comment by andrewtelnov** [comment]
@schlick Indeed, We did not test this case. We look and see how we can make both scenarios working.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@schlick I have reviewed the issue. We can't make it works as: "{cars} contains 'BMW'". You can do it by using a custom function.
Here is [the example](https://plnkr.co/edit/i4jBPmgJQVjfXBsM).
We could change the question value on the fly for condition check, but for a generic case the array can have many other attributes and a developer may want to check them as well.

Thank you,
Andrew

**Comment by schlick** [comment]
Thanks again for your advice @andrewtelnov. The custom function approach works.
