### ISSUE TITLE
Checkbox - The `hasComment` option

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#4764]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
Multiple choice question configuration happens on 2 "levels". There's the definition of choices and then there are modifiers that also add choices: `hasOther` and `hasNone`.
While these modifiers work they are limited.

### What is the expected behavior?
My idea would be to move the configuration to a single level, that of the choices.
Each choice could then get additional options:
- `isExclusive`
- `hasComment`
- `fixedPosition`

#### `isExclusive`
This option would implement logic similar to the option added by `hasNone` (and could replace its functionality). There are use cases for multiple exclusive options and this also allows the user to program the value for the option.

#### `hasComment`
This option would implement logic similar to the option add by `hasOther`, but to specific items. When such an item is checked a text area shows up.

#### `isFixedPosition`
When randomizing answer order it is sometimes desirable to have some control over the choices. Checking this box would fix the position of this item in the list.
Randomization happens by taking the spots and randomizing over them; this is relatively simple to implemented and I have done so in other use cases:
1. Choices look like this, where `F` means fixed: `x F x x F x x`
2. Copy the choices that need to be randomized (5 elements) to an array
3. Loop over the original choices array and for each index check if it is fixed, if not, replace it with a random element from 2
4. Remove the inserted element from 3 from the array
5. Repeat until array from 2 is empty

Ideally when adding this one would phase out `hasNone`, `hasOther` and `hasComment`. `hasComment` could be implemented as a default value for the individual `hasComment` setting on a choice.

**Comment by JaneGaid** [comment]
Hello @SamMousa,
Thank you for your valuable suggestions.

Regarding adding the `hasComment` option to a Checkbox item configuration: this would require significant changes in survey logic. We noted down this idea for further consideration.

Regarding two other suggestions: I decided to extract them to separate issues:
* [Checkbox - Fix specific item position and exclude it from randomizing](https://github.com/surveyjs/survey-library/issues/4777)
* [Checkbox - The isExlusive property](https://github.com/surveyjs/survey-library/issues/4778)

Please refer to them for further details.

**Comment by SamMousa** [comment]
Thanks for the feedback @JaneGaid, I'm aware of the workaround (s), just posted this here for improvement in the lib!

**Comment by andrewtelnov** [comment]
@SamMousa We have introduce a new functionality that is related to this issue. You can find it in v1.9.117: [Reorder "None", "Other", and "Select All" in Select-Based Questions.](https://surveyjs.io/stay-updated/release-notes/v1.9.117#reorder-none-other-and-select-all-in-select-based-questions).

Thank you,
Andrew

**Comment by JaneSjs** [comment]
Hi @SamMousa,
Please be informed that we introduced the `isExclusive` option for a choice item: [View Demo](https://plnkr.co/edit/QEjnlyMx6qI2MKGg).

https://github.com/user-attachments/assets/36f505a0-4c71-4c5b-aeee-fed1c9093f61

For more information, refer to the following release note: [Support for Exclusive Options in Checkbox Questions](https://surveyjs.io/stay-updated/release-notes/v2.1.1#support-for-exclusive-options-in-checkbox-questions).

We’d be happy to hear from you if you have any questions or feedback.
