### ISSUE TITLE
Expression properties added to Survey don't work

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#4769]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Custom properties of type `condition` or `expression` do not have their `onExecuteExpression` called when they are attached to the survey.

### What is the expected behavior?
It should either work, or fail during setup.

### How would you reproduce the current behavior (if this is a bug)?
I've created a plunker that adds a property to questions and to survey.

It shows that it is working for questions (try changing the rating value). But the exact same code is not working for the property added to the survey.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/EijsTFbFTZD9jC8B

### Specify your

* browser: N/A
* browser version: N/A
* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: latest

**Comment by andrewtelnov** [comment]
@SamMousa The issue has been fixed.

Thank you,
Andrew
