### ISSUE TITLE
checkAndSetPropertyValue and setPropertyValue methods seem to duplicate functionality

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-library#4802]
The [`checkAndSetPropertyValue`](https://surveyjs.io/form-library/documentation/base#checkAndSetPropertyValue) description says that the only difference between this and the `setPropertyValue` method is the `onSettingValue` function execution, and when this function is not specified, both methods work identically. However, `onSettingValue` isn't specified by default in most questions, which means that it is never executed when it is unneeded, and this means that there's no need to have two methods: we can keep the `checkAndSetPropertyValue` method only (and rename it to `setPropertyValue`).

**Comment by andrewtelnov** [comment]
@RomanTsukanov I have removed this function.

Thank you,
Andrew
