### ISSUE TITLE
React-Native support & using surveyjs without front end libraries.

### ISSUE THREAD

**Issue by safaiyeh** [surveyjs/survey-library#484]
Are there plans to support React Native? I have a need for mobile surveys; however, surveyjs service seems to have a dependency on the front end.

Is there a way to request the survey json via https without the frontend library?

**Comment by andrewtelnov** [comment]
@JSafaiyeh We have discussed react Native support and everybody agree that we have to implement it. Unfortunately, there are some other tasks that we believe are more urgent at the current moment. For example, move all information/libraries/services into one web site: surveyjs.io, so you would be able to find this link without any help: http://api.dxsurvey.com/Help/Api/GET-api-Survey-getSurvey_surveyId :)
We did a good job to hide it from you and others :)

PS: Somebody have said me he started a public project on GitHub: surveyjs for react native. However, I could not find it now.

Thank you,
Andrew

**Comment by JSafaiyeh** [comment]
Thanks for the response. I will be investigating creating react-native support.

**Comment by abolger** [comment]
@JSafaiyeh, I am also dying for React Native support, however in the mean time I have implemented react support in a React Native Webview component and got it working. It took a bit of finagling, but it is possible. Is there enough interest that I should create a skeleton react native project showing how I did this?

**Comment by ppatel890** [comment]
I am also trying to get react native support. Webview works, but not all that well, especially with file upload/file picker. @andrewtelnov, were you able to find anything out about the public project someone started? Thank you!

**Comment by ppatel890** [comment]
@andrewtelnov Do you have any pointers on where to get started if trying to create a react native implementation of surveyjs library? Would rewriting each question component within the reactjs implementation as React Native components and using the core surveyjs logic for survey flow be enough? Or would there have to be more changes to the core surveyjs logic?

**Comment by andrewtelnov** [comment]
@ppatel890 Unfortunately I did not write a single line of code myself on react-native platform :-(

Thank you,
Andrew

**Comment by bhavinpankanis** [comment]
@ppatel890 @abolger Could you please provide pointers to render Survey.js in webview. I am too looking for a react-native support but I guess for the time being, I will have to go with webview solution in order to meet my requirement.

**Comment by abolger** [comment]
Here's a sample app so no one else had to set up the nonsense I did to make this work. https://github.com/abolger/surveyjs-inside-react-native-webview

**Comment by bhavinpankanis** [comment]
@abolger The project works perfectly well. Just 2 queries as of now
1. When I click on submit, the screen gets blank - Can I override this behaviour?
2. I would like to show native controls like date-time pickers, etc. Can that be achieved using the existing bridging?. If yes, Could you please provide pointers for that?

**Comment by abolger** [comment]
1) It's an open source project on the MIT license, you can change the
handler do whatever you want on submit- reload the screen, navigate to your
company website, literally anything.

2) The bridge implementation I used and the project provided can send
messages back and forth, so I see no technical reason why you couldn't code
up a 'datepicker' message and send the data back and forth to a webview
over the bridge. However, the whole point (for me anyways) was to use
SurveyJS as they've coded it- once you start building all the react native
stuff you're talking about a considerable extension to the initial 'port'.
But if you do that, I'd love to see it.

**Comment by naoey** [comment]
@andrewtelnov considering there was initial interest from the SurveyJS team implementing a react native version, has there been any updates on the idea since this issue was last discussed?

**Comment by andrewtelnov** [comment]
@naoey We are working on this [issue](https://github.com/surveyjs/surveyjs/issues/1361). After that we may try react native. We are defaintely interested in it.

Thank you,
Andrew

**Comment by kostiantyn-solianyk** [comment]
What is the status of this issue? It would be awesome if the surveyjs worked with react-native! Did you start, maybe we can help with something?

**Comment by andrewtelnov** [comment]
@kostiantyn-solianyk @amphithere We are going to start working on it in several weeks, likely on December. At least give a try. Right now, we are working on making all UI dependent properties reactive. It makes the code for react version clean and should help with react native implementation.

Thank you,
Andrew

**Comment by socialsuiteDan** [comment]
Is there any update on the React Native plans? We would also be willing to help, as we need to implement survey functionality across both web and react native.

**Comment by andrewtelnov** [comment]
@socialsuiteDan Unfortunately, there is no update since then. There are always something more urgernt.
The good news, we have got two new devs in our team in March. Likely we will get one more this or in next month. It means that we double our team. New guys need couple months to cach-up and hopefully, React-Native card will move from TODO list into "In Progress" :).

To all others, who read this issue. If you are interesting in React-Native, please drop a line, to let us know that more people need it.

Thank you,
Andrew

**Comment by pephumin** [comment]
I am interested too, and hence it is why I subscribed to this discussion for a while. It would be great to have a rexacr native version of surveys.

**Comment by pornprasit** [comment]
i need it, thanks.

**Comment by kostiantyn-solianyk** [comment]
@andrewtelnov, thanks for being interested. Personally I need surveyjs in react-native too. It would be great to have this support.

**Comment by frogburger** [comment]
@andrewtelnov, it will be very useful for our project

**Comment by mharis161** [comment]
Is there any update on the React Native plans? We would also be willing to help, as we need to implement survey functionality in react native.

**Comment by mharis161** [comment]
> Here's a sample app so no one else had to set up the nonsense I did to make this work. https://github.com/abolger/surveyjs-inside-react-native-webview

@abolger  i have used this code

i have faced some issue 
Reacord audio widget not working 
file picker also not working 

how to record voice with surveyjs in react-native

**Comment by mharis161** [comment]
@andrewtelnov  i am also interested in react-native survey js app.

**Comment by Aequitas737** [comment]
@andrewtelnov We would also love RN support. Also willing to help out to accomplish it.

**Comment by ginoburrr** [comment]
@andrewtelnov We would also like React Native support.

**Comment by alecdiaz1** [comment]
@andrewtelnov RN support would be great!

**Comment by safaiyeh** [comment]
Man, it has been a while since I been here.

For anyone that wants a way to move forward. I made my own implementation by parsing the raw data and creating our own views for it. It was not too difficult and helps to maintain your app's current design.

**Comment by andrewtelnov** [comment]
Hi all,
Sorry for not reporting our progress here. The reason is simple. Nobody wants to bring the bad news.

We have created a prototype, survey with the text question type and limited functionality, and found out that there is no way we will be able to create a quality React Native library on JavaScript, that works great on Android and iOS. 
I know, it may sound disappointed, but the truth, that we must go native to get a quality library.
Based on what we have learned, the right way of doing it – write the core code on C++, then reuse it for Android and iOS by creating native libraries for them and finally write wrappers around them for react native and Xamarin and so on. Unfortunately, that is the only way to have the quality libraries and unfortunately it is resource consuming task.
It doesn’t mean that we will not work on it. The fact is, that it is a big commitment for us, and we will have to hire at least two experience developers for this task.

**Comment by quicksilverr** [comment]
Hey @andrewtelnov Love the project and work you guys are doing. Is there any news on the native libs and wrappers?

**Comment by slycadelic** [comment]
> Hi all, Sorry for not reporting our progress here. The reason is simple. Nobody wants to bring the bad news.
> 
> We have created a prototype, survey with the text question type and limited functionality, and found out that there is no way we will be able to create a quality React Native library on JavaScript, that works great on Android and iOS. I know, it may sound disappointed, but the truth, that we must go native to get a quality library. Based on what we have learned, the right way of doing it – write the core code on C++, then reuse it for Android and iOS by creating native libraries for them and finally write wrappers around them for React Native, Xamarin and so on. Unfortunately, that is the only way to have the quality libraries and unfortunately it is resource consuming task. It doesn’t mean that we will not work on it. The fact is, that it is a big commitment for us, and we will have to hire at least two experience developers for this task.

I am working on a project where a team has built a web platform for some company and they are using this library to handle forms (creating, filling and storing responses). Now they have asked me to create a mobile app for the same company where users can go and fill forms. Creating forms can only be done by admin from the web-platform. That saves me a lot of work.

Hence, I was looking to see if there is support for react-native or flutter. Coudn't find any but if there is any update I would love to know. In the mean time, I am consuming their api and making some react-native components that can display the questions and store answers. Starting with the simple stuff. Will update on how it goes.

**Comment by andrewtelnov** [comment]
@slycadelic We have not started to work on this and very unlikely we will start working on it this year. We will need to enlarge our team to go native and we are still not sure about the market here. How many developers need it and how much they are ready to pay for it.

Thank you,
Andrew

**Comment by synth** [comment]
We would love to see React Native support! :)

**Comment by brianwachira** [comment]
> I am also trying to get react native support. Webview works, but not all that well, especially with file upload/file picker. @andrewtelnov, were you able to find anything out about the public project someone started? Thank you!

How do I run it on a webview?

**Comment by brianwachira** [comment]
> > Hi all, Sorry for not reporting our progress here. The reason is simple. Nobody wants to bring the bad news.
> > We have created a prototype, survey with the text question type and limited functionality, and found out that there is no way we will be able to create a quality React Native library on JavaScript, that works great on Android and iOS. I know, it may sound disappointed, but the truth, that we must go native to get a quality library. Based on what we have learned, the right way of doing it – write the core code on C++, then reuse it for Android and iOS by creating native libraries for them and finally write wrappers around them for React Native, Xamarin and so on. Unfortunately, that is the only way to have the quality libraries and unfortunately it is resource consuming task. It doesn’t mean that we will not work on it. The fact is, that it is a big commitment for us, and we will have to hire at least two experience developers for this task.
> 
> I am working on a project where a team has built a web platform for some company and they are using this library to handle forms (creating, filling and storing responses). Now they have asked me to create a mobile app for the same company where users can go and fill forms. Creating forms can only be done by admin from the web-platform. That saves me a lot of work.
> 
> Hence, I was looking to see if there is support for react-native or flutter. Coudn't find any but if there is any update I would love to know. In the mean time, I am consuming their api and making some react-native components that can display the questions and store answers. Starting with the simple stuff. Will update on how it goes.

Same thing here. Is it possible to run surveyjs on a webview? I am thinking of doing that instead of building components from scratch

**Comment by brianwachira** [comment]
> I am also trying to get react native support. Webview works, but not all that well, especially with file upload/file picker. @andrewtelnov, were you able to find anything out about the public project someone started? Thank you!

Hi, I also made it run on webview. Did you manage to fix the file picker issue? can't get the files on react native

**Comment by prasunsrivastava** [comment]
> Man, it has been a while since I been here.
> 
> For anyone that wants a way to move forward. I made my own implementation by parsing the raw data and creating our own views for it. It was not too difficult and helps to maintain your app's current design.

Do you have a reference implementation for this? It would be really helpful to see how it was done and use that as an inspiration.

**Comment by coyksdev** [comment]
This is easy now with expo dom

![Screenshot 2025-01-04 at 11 36 59 pm](https://github.com/user-attachments/assets/881fd1a9-03c0-4d3a-a8cc-3eb9ffdafbb4)

**Comment by ShumGG** [comment]
> This is easy now with expo dom
> 
> ![Screenshot 2025-01-04 at 11 36 59 pm](https://github.com/user-attachments/assets/881fd1a9-03c0-4d3a-a8cc-3eb9ffdafbb4)

doing this way but when lauching updates with eas it crashes for a reason, if i dont use 'use dom' in the component it works, its with 'use dom' that the update doesnt apply and crash

**Comment by ibnsultan** [comment]
I don't know if this is going to help anyone, But I have implemented a custom parser for surveyJS forms in my application (it's open), while there's some minor parts that directly depends on the app, with a few tweeks you should have it running with no issues. 

The project is [surveyr Collect](https://github.com/friendlylabs/collect/), The parser files
- [surveyParser](https://github.com/friendlylabs/collect/blob/main/utils/surveyParser.ts)
- [surveyRender](https://github.com/friendlylabs/collect/blob/main/components/NativeSurveyRenderer.tsx)
- [surveyRendererComponents](https://github.com/friendlylabs/collect/tree/main/components/survey)

The catch
---
- This is not a standalone parser, so you'll have to extract the files and works with them per your requirements.
- The handling of remote assets i.e choiceByUrl in dropdown question is a little bit different as I was aiming for oofline first approach, so you'll have to modify that to match you needs

Edit: if i find time maybe, i'll try to make a standalone version of it.
