### ISSUE TITLE
Rename some `has*` properties

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-library#4846]
We have two types of `has*` properties:

1. Properties that indicate presence of something (`hasTitle`, `hasDescription`, `hasInput`).
2. Properties that change something (`hasComment` displays a comment area, `hasOther` displays the Other item)

We need to split these two types apart by means of naming. Let's keep properties of type 1 as they are and rename properties of type 2 as follows:

`hasComment` -> `showCommentArea`
`hasOther` -> `showOtherItem`
`hasNone` -> `showNoneItem`
`hasSelectAll` -> `showSelectAllItem`

**Comment by SamMousa** [comment]
I see this issue as a label API, is there a changelog for these kinds of changes?
We parse the generated JSON and I just randomly noticed this renaming.
