### ISSUE TITLE
Dropdown Question closes the popup when tapping a search box in iOS devices

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-library#4856]
From [T10625 - Auto scroll to input on focus breaks dropdown search on ios](https://surveyjs.answerdesk.io/internal/ticket/details/T10625)

> iOS always tries to vertically center a text input on focus.
So if you've scrolled down a bit and tap the dropdown, then tap the search box, it will always close the dropdown because iOS automatically tries to scroll it to the center of the screen.

**Comment by OlgaLarina** [comment]
Hello, 

I've fixed the issue via [the pull request](https://github.com/surveyjs/survey-library/pull/4875). Fix will be available in the nearest minor update.

Olga,
SurveyJS Team
