### ISSUE TITLE
Survey form

### ISSUE THREAD

**Issue by beryl454** [surveyjs/survey-library#4869]
https://1drv.ms/u/s!AhwL4AVeAg15hRvWZDdRs-OSNExX

**Comment by andrewtelnov** [comment]
@beryl454 Could you please add a comment to your post?
IMHO: Your link probably is not related to SurveyJS.

Thank you,
Andrew

**Comment by beryl454** [comment]
> @beryl454 Could you please add a comment to your post?
> IMHO: Your link probably is not related to SurveyJS.
> 
> Thank you,
> Andrew

Hey Andrew 
I'm a beginner and still trying to figure out how this works. Pardon me for that. 
I'm working on it.
Thanks 
Beryl
