### ISSUE TITLE
Property to specify the Boolean question mode 

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#4899]
A Boolean question may be rendered differently depending on the available width: as a slider and radio buttons. Implement an option to enforce a specific method (for example, `useRadio: never | always | auto`).

Source ticket: [T10713 - Boolean Question Render mode (slider or radio)](https://surveyjs.answerdesk.io/internal/ticket/details/T10713)

**Comment by novikov82** [comment]
we can use renderAs property:
https://surveyjs.io/form-library/examples/yes-no-question/reactjs#content-code
