### ISSUE TITLE
The survey.onAfterRenderHeader event is not raised (+ validate the description)

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#4906]
I expect the [`survey.onAfterRenderHeader`](https://github.com/surveyjs/survey-library/blob/9b62a4b849aba6ee94eb77c15695051c8e038551/src/survey.ts#L602) event to be raised after the survey header rendering completes. However, it isn't raised (see this [Example](https://plnkr.co/edit/MGYPz2T3VEtDUQkd)). Also, please verify the doc description.

**Comment by theriddler** [comment]
This still seems to be an issue in 1.9.48. Will it be fixed soon or should I find another workaround?

**Comment by JaneSjs** [comment]
Hello @theriddler,
I verified and confirmed that the `survey.onAfterRenderHeader` function is raised when a survey header rendering is complete.
[View Demo](https://plnkr.co/edit/iVA5uTZzg8HgsXl0)

Within this event, use the `options.htmlElement` property to obtain a header HTML element and update it, if needed.
