### ISSUE TITLE
Replace the `otherPlaceholder` and `commentPlaceholder` properties with a single property

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-library#4925]
Both these properties can be used to specify a placeholder for the comment area when `hasComment` or `hasOther` is enabled. We should replace them with a single property. Proposed name: `commentAreaPlaceholder`.

**Comment by andrewtelnov** [comment]
@RomanTsukanov We will have the ability to show other and comments arias soon. It means that it is better to keep them as they are now.

Thank you,
Andrew
