### ISSUE TITLE
Multiple Text Question - The Notempty Item Validator doesn't work

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-library#4950]
I want to ensure that a Multiple Text Question item is not left unanswered. So, I setup the following item validator and set the `survey.checkErrorsMode` property to `onValueChanged`. 
```
"validators": [
        {
         "type": "expression",
         "text": "Please enter the Text!",
         "expression": "{multipleTextQuestion.item1} notempty"
        }
]
```
However, no validation message appears if leave a value empty and move the focus outside the editor:
![image](https://user-images.githubusercontent.com/22372972/193752066-4804ac59-c777-420c-a17a-06a9a7875845.png)

[Example](https://plnkr.co/edit/x3upsZQBXzpWt3wh)

**Comment by andrewtelnov** [comment]
@andrewtelnov It works corectly. Here is [the example](https://plnkr.co/edit/WeJyqG3E1FJIKq7K).
It doesn't work if `survey.checkErrorsMode` property is to onValueChanging. In this case `question1.item1` value is not set yet.

Thank you,
Andrew
