### ISSUE TITLE
Dynamic Panel - Add custom buttons to individual panels (e.g., the Remove button) and to the top-level area (e.g., Add button)

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#4953]
An option for the Panel Dynamic question to add custom buttons to individual panels (like the Remove button) and to the top-level question area (like the Add button).

**Usage scenario**
A custom Duplicate button which duplicates the current panel with input values:
![image](https://user-images.githubusercontent.com/22372972/193789413-c132ddae-ea32-465d-8e7f-2156a5c3916b.png)

Original issue: [T10818 - Add a custom button to a Dynamic Panel](https://surveyjs.answerdesk.io/internal/ticket/details/T10818).

**Comment by masciugo** [comment]
very interesting. So it's not just for duplication, is it?

**Comment by masciugo** [comment]
Hi, is there any doc/demo available about this new feature. Thanks a lot for adding it!

**Comment by dk981234** [comment]
Hello,
You can add, delete, or modify actions in the panel footer using a new [survey.onGetPanelFooterActions](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onGetPanelFooterActions) event. I created the following example to demonstrate how to customize panel actions: https://plnkr.co/edit/3RRo1mqs26eP0YTH.

Please take your time testing this functionality. As always, you're welcome to contact us if you have any questions or require further assistance.
