### ISSUE TITLE
File question with `showPreview`: `false` does not display anything after upload

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-library#4990]
https://plnkr.co/edit/F5m3XTqTQ321XdBm

The result is below:

![image](https://user-images.githubusercontent.com/18551316/194511062-a6091c79-9633-4ad4-b6bd-3ebb2fa015e6.png)

As I see it, `showPreview` should disable the display of file contents. File icons and names must remain.

UPD: There's also the [`allowImagesPreview`](https://surveyjs.io/form-library/documentation/questionfilemodel#allowImagesPreview) property. I see no point in keeping them both because without file icons and names the question looks buggy.

**Comment by tsv2013** [comment]
This option disables images in preview:
      "allowImagesPreview": false,
This option completely turns preview off
      "showPreview": false
And customers can render custom preview - https://surveyjs.io/form-library/examples/file-custom-preview/reactjs
