### ISSUE TITLE
QuestionFileModel: Rename the `onStateChanged` property

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-library#4993]
We already have a [`state`](https://surveyjs.io/form-library/documentation/questionfilemodel#state) property that defines the expand state. However, the [`onStateChanged`](https://surveyjs.io/form-library/documentation/questionfilemodel#onStateChanged) property works with the upload state. So, to distinguish between these states, I suggest renaming the `onStateChanged` proeprty to `onUploadStateChanged`.

**Comment by tsv2013** [comment]
It also loaded for files preview download. Should it be different states?
