### ISSUE TITLE
prevent expression questions from running calculation when they're based on invalid questions

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#5020]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

the expression questions always run, even if they are based on some invalid questions

### What is the expected behavior?

I just wonder if it makes sense stop calculation if questions used as operands have invalid values

thank you

**Comment by JaneGaid** [comment]
Hello @masciugo,
The survey evaluates expressions for the first time when the survey begins, and then re-evaluates again each time any of the question values change.
For example, if an expression contains invalid question names, the expression would simply return `false`. 

Would you please clarify whether you encounter any issues on this matter?  

Thank you

**Comment by masciugo** [comment]
thank you @JaneGaid. I meant when the expression contains invalid questions value (not invalid question names). For example:

https://plnkr.co/edit/YoUzeYM1e7anMAJF

the expression in calculated even if the other questions are invalid

**Comment by JaneSjs** [comment]
Hello @masciugo,
Please accept my apologies for the delayed reply. 
I appreciate your clarification. Expressions are actually calculated, however, a survey doesn't allow submission without fixing validation issues first. So, the resultant expression value will be calculated over valid values once a user corrects these values.

To ensure that a value entered doesn't go beyond the specified limits, consider using a numeric input mask. 
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "tenderJointCount",
     "validators": [
      {
       "type": "numeric",
       "minValue": 0,
       "maxValue": 28
      }
     ],
     "maskType": "numeric",
     "maskSettings": {
      "precision": 0,
      "min": 0,
      "max": 28
     }
    },
    {
     "type": "text",
     "name": "swollenJointCount",
     "startWithNewLine": false,
     "validators": [
      {
       "type": "numeric",
       "minValue": 0,
       "maxValue": 28
      }
     ],
     "maskType": "numeric",
     "maskSettings": {
      "precision": 0,
      "min": 0,
      "max": 28
     }
    },
    {
     "type": "expression",
     "name": "DAS28ESR",
     "expression": "(0.56*{tenderJointCount}^0.5)+(0.28*{swollenJointCount}^0.5)"
    }
   ]
  }
 ]
}
```
Consider the updated demo: [View Plunker](https://plnkr.co/edit/kgzM6Oty2z2iV9Ff). Let me know if you have further questions.
