### ISSUE TITLE
Do not call copy and setvalue triggers on page changed event

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-library#5027]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
Data in a panel dynamic gets removed when a trigger happens.

### What is the expected behavior?
Data should not get deleted.

### How would you reproduce the current behavior (if this is a bug)?
See this Plunker: https://plnkr.co/edit/HBRDYcu40rLccRsu
- Set the SurveyJS version to 1.9.41 and the survey submits correctly.
- Set the SurveyJS version to anything newer and the data in the second panel dynamic gets removed.

Another case where data is removed:
- Set the trigger boolean to "yes". 
- Add a second report recipient, submit the survey and see that the second recipient is removed.

#### Provide the test code and the tested page URL (if applicable)
See this Plunker: https://plnkr.co/edit/HBRDYcu40rLccRsu

### Specify your
* browser: firefox/chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.9.42 and higher

**Comment by andrewtelnov** [comment]
@Lionqueen94 The bug has been fixed by the commit above. The fix will be availabe in the next minor that we will release next week.

Thank you,
Andrew

**Comment by Lionqueen94** [comment]
@andrewtelnov Thanks a lot for the quick response! Looking forward to testing the fix after the next release.
