### ISSUE TITLE
(un)registerPropertyChangedHandlers should accept an array of property names as the third argument

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-library#5032]
Recently, we've [modified the first paramter of the (un)registerPropertyChangedHandlers methods](https://github.com/surveyjs/survey-library/issues/4805). They now accept an array of property names. We should do the same with the third parameter.

**Comment by andrewtelnov** [comment]
@RomanTsukanov It should not. propertyName and key pair is unique. You can add several handlers for a property if key is undefined or different. You can have only one key in these functions.
