### ISSUE TITLE
Inconsistency of the survey JSON results for comments

### ISSUE THREAD

**Issue by zagadeka** [surveyjs/survey-library#5047]
### Are you requesting a feature, reporting a bug or asking a question?

It's a bug.

### What is the current behavior?

If one defines the survey as follows:
`
{
 "logoPosition": "right",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question",
     "title": "What is your favourite fruit?",
     "choices": [
      {
       "value": "item1",
       "text": "Apple"
      },
      {
       "value": "item2",
       "text": "Lemon"
      },
      {
       "value": "item3",
       "text": "Orange"
      }
     ],
     "hasOther": true
    },
    {
     "type": "text",
     "name": "question-Comment",
     "title": "Would you like to leave a comment?"
    }
   ]
  }
 ]
}
`
chooses last option "other (describe)" with the text field and answers the second question, JSON does not contain both answers:
`
{
    "question": "other",
    "question-Comment": "I don't like fruits."
}
`

### What is the expected behavior?

I'm not sure. Using an array could be a solution:
`
{
    "question": ["other", "Tomato"],
    "question-Comment": "I don't like fruits."
}
`

**Comment by andrewtelnov** [comment]
@zagadeka It is a radiogroup, it can have only one choice and the value can't be array.
You can use checkbox for your task or radiogroup + Comment question.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@zagadeka It can't be "Tomato" and "other". It should be only one value "Tomato" or "other".
However, you can modify the json before you sent it into your database. Here is [the example](https://plnkr.co/edit/HnCPZbdB9ip4n18c).

Thank you,
Andrew

**Comment by zagadeka** [comment]
@andrewtelnov Thank you for your commitment. I am not sure if it is clear what the problem is. My user controls the entire process of defining the survey. When creating the customized survey he can define radio group with the name `x` and input with the name `x-Comment`. In this case SurveyJS JSON result is defective. It's not the bug in the library. It's about result JSON design. If my suggestions above are not good enough, would it even be possible to fix this somehow?

**Comment by JaneGaid** [comment]
Hello @zagadeka,

Thank you for the clarification. Questions which support the Other option by default store the Other value under the `questionName-Comment` name. In your survey, you actually create a separate question with the same value name. That is why the resulting JSON doesn't contain both answers.

Please try either of the following options.

**Option #1**
Specify another name for your separate question, for example, `questionComment`:
```
var json = { 
  "logoPosition": "right", 
  "pages": [ 
    { "name": "page1", 
    "elements": [ 
      { 
      "type": "radiogroup", 
      "name": "question", 
      "title": "What is your favourite fruit?", 
      "choices": [ 
        { "value": "item1", "text": "Apple" }, 
        { "value": "item2", "text": "Lemon" },
        { "value": "item3", "text": "Orange" } 
        ], 
        "hasOther": true }, 
        { 
          "type": "text", 
          "name": "questionComment",
          "title": "Would you like to leave a comment?" 
          } 
        ] 
      }
    ]
}
```
The resulting JSON appears as follows:
```
Result JSON: { "question": "other", "question-Comment": "Mango", "questionComment": "Enjoy your meal!" }
```
[Example](https://plnkr.co/edit/gjkwhbOg2y8UXB4O).

**Option #2**
Disable the [survey.storeOthersAsComment ](https://surveyjs.io/form-library/documentation/surveymodel#storeOthersAsComment) option. 
```
var json = { 
  "logoPosition": "right", 
  "pages": [ 
    { "name": "page1", 
    "elements": [ 
      { 
      "type": "radiogroup", 
      "name": "question", 
      "title": "What is your favourite fruit?", 
      "choices": [ 
        { "value": "item1", "text": "Apple" }, 
        { "value": "item2", "text": "Lemon" },
        { "value": "item3", "text": "Orange" } 
        ], 
        "hasOther": true }, 
        { 
          "type": "text", 
          "name": "question-Comment", 
          "title": "Would you like to leave a comment?" } 
        ] 
      }
    ],
    "storeOthersAsComment": "false"
}
```
Now, the Other option text will be stored under a Radiogroup question name:
```
Result JSON: { "question": "Mango", "question-Comment": "Enjoy your meal!" }
```
[Example](https://plnkr.co/edit/uohjidUJV17yYkK3).

Drop us a line if any questions remain.

Thank you

**Comment by JaneGaid** [comment]
A follow-up: I would generally recommend that you give your questions unique names. If you would simply name your first question as `question1`, this would resolve the issue:
```
var json = { 
  "logoPosition": "right", 
  "pages": [ 
    { "name": "page1", 
    "elements": [ 
      { 
      "type": "radiogroup", 
      "name": "question1", 
      "title": "What is your favourite fruit?", 
      "choices": [ 
        { "value": "item1", "text": "Apple" }, 
        { "value": "item2", "text": "Lemon" },
        { "value": "item3", "text": "Orange" } 
        ], 
        "hasOther": true }, 
        { 
          "type": "text", 
          "name": "question-Comment", 
          "title": "Would you like to leave a comment?" } 
        ] 
      }
    ]
}
```

Thank you

**Comment by zagadeka** [comment]
@JaneGaid Thank you for your suggestions. `storeOthersAsComment` is quite tempting although the user may give an answer which will be the name of another option (`{ "question": "item2", "question-Comment": "Enjoy your meal!" }`). This would be confusing. Requiring uniqueness of names including the `-Comment` suffix is probably the best way.

**Comment by JaneGaid** [comment]
You're welcome, @zagadeka. Correct - unique names for survey questions ensure correct output. 

Should you have further questions, let us know.
