### ISSUE TITLE
Error in cssRoot getter for Page class

### ISSUE THREAD

**Issue by BrevAlessio** [surveyjs/survey-library#5097]
My Vue application receives an error coming from this getter. The error states that it cannot read property 'root' of undefined, meaning this.cssClasses.page is undefined.

From `page.ts` file:
```
  public get cssRoot(): string {
    return new CssClassBuilder()
      .append(this.cssClasses.page.root)
      .append(this.cssClasses.page.emptyHeaderRoot, !(<any>this.survey).renderedHasHeader &&
        !((<any>this.survey).isShowProgressBarOnTop && !(<any>this.survey).isStaring))
      .toString();
  }

```

## Reproduction (Edit)
I could reproduce the bug in a standalone [codepen](https://codesandbox.io/s/surveyjs-creator-vue-forked-7b7s1d)
It happens when both `survey-vue-ui` and `survey-creator` are imported in an application, even in different files.
Navigate between the 2 pages and check the console for the specific error reported above.

### Specify your

* browser: Opera
* browser version: 91.0.4516.65
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.9.55

**Comment by JaneGaid** [comment]
Hello @BrevAlessio,
Thank you for sharing the example. We will research this issue and get back once we have any news to share.

**Comment by BrevAlessio** [comment]
This solved only the immediate console.log error, didn't address the root problem, I opened #5176 for a further investigation

**Comment by JaneGaid** [comment]
Hello @BrevAlessio,
Thank you for the update. We'll continue researching this issue. Please refer to https://github.com/surveyjs/survey-library/issues/5176 for further information.
