### ISSUE TITLE
Error message doesn't look good if titleLocation is left

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-library#5128]
I created a composite component and enabled the isRequired field for each question. The composite layout appears as follows when validation fails for items: [example](https://plnkr.co/edit/ppsNrpkxjqu125pH).
![image](https://user-images.githubusercontent.com/22372972/198632818-1f7b6829-3548-43e8-a5f4-81b6145003d0.png)

Validation message should basically appear at the top or bottom of individual questions.

**Comment by andrewtelnov** [comment]
@JaneGaid The issue with our design for error messages if title location is "left". Here is the example.

Thank you,
Andrew
