### ISSUE TITLE
Add support for images in Ranking question type

### ISSUE THREAD

**Issue by vasilyz** [surveyjs/survey-library#5134]
Hello! It would be nice to support for images in Ranking question type. Something like a union of Ranking and Image picker question types.

**Comment by JaneSjs** [comment]
Hi @vasilyz,
Please be informed that the SurveyJS v1.9.86 release introducs new rating scale types for SurveyJS Rating Scale question: stars and smileys. 

![Clipboard-File-2.png](/internal/attachment/file/a1f6fc02-a7dd-414b-8920-09abf9dda523)

For more information, refer to [SurveyJS v1.9.86 Release Notes](https://surveyjs.io/stay-updated/release-notes/2023-05-03).

Thanks
