### ISSUE TITLE
"Other text" editor is too small

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-library#516]
### Are you requesting a feature, reporting a bug or ask a question?
Feature

### What is the current behavior?
![image](https://user-images.githubusercontent.com/3013415/28525657-a01e96aa-708d-11e7-9c67-a6e2a583d260.png)

### What is the expected behavior?
At least
![image](https://user-images.githubusercontent.com/3013415/28525700-bbc237b8-708d-11e7-85df-4256d1959b51.png)

Probably multiline editor.

**Comment by andrewtelnov** [comment]
It was fixed.
