### ISSUE TITLE
Ranking: Answer count validator doesn't work.

### ISSUE THREAD

**Issue by ArclightMat** [surveyjs/survey-library#5160]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug over a widget validator.

### What is the current behavior?
When adding an "answer count" validator to the ranking, instead of limiting the choices, it adds them anyway and then blocks progress due to auto-ordering increasing the answer count over the limit.
![rankingvalidatorerror](https://user-images.githubusercontent.com/4731163/199341321-11d94f4b-6fb5-40be-874a-e2791b4b2ad3.png)

### What is the expected behavior?
The  "answer count" is respected, and the selection is limited to the min/max limit set.

### How would you reproduce the current behavior (if this is a bug)?
Add a "Ranking" question with a X number of choices, and then a "answer count" validator with its max count set to "X-1".

#### Provide the test code and the tested page URL (if applicable)

Test code

```
{
	"survey": {
		"pages": [
			{
				"name": "page1",
				"elements": [
					{
						"name": "question3",
						"type": "ranking",
						"title": "Please rank your 5 favorite fruits (where 1 = Most favorite and 5 = least favorite)",
						"choices": [
							{
								"text": "Banana",
								"value": "item8"
							},
							{
								"text": "Apple",
								"value": "item9"
							},
							{
								"text": "Pineapple",
								"value": "item10"
							},
							{
								"text": "Mango",
								"value": "item11"
							},
							{
								"text": "Passionfruit",
								"value": "item12"
							},
							{
								"text": "Tomato",
								"value": "item13"
							},
							{
								"text": "Pear",
								"value": "item14"
							},
							{
								"text": "Star fruit",
								"value": "item15"
							}
						],
						"validators": [
							{
								"type": "answercount",
								"maxCount": 5
							}
						]
					}
				]
			}
		]
	}
}
```

### Specify your

* browser: Mozilla Firefox 
* browser version: 106.0.3
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.9.54

**Comment by JaneSjs** [comment]
Hello @ArclightMat,
A Ranking question doesn't currently have an option to limit the number of items to rank. We are currently evaluating this option. You can track our progress at https://github.com/surveyjs/survey-library/issues/5328.
