### ISSUE TITLE
Dropdown 

### ISSUE THREAD

**Issue by jefftudorbenbria** [surveyjs/survey-library#5191]
### Are you requesting a feature, reporting a bug or asking a question?
Bug.

### What is the current behavior?
Once our survey resets, the dropdown questions exhibit odd behaviour. On select, the selected item displays its value rather than displayValue/text. After a blur event (click somewhere on the page other than the dropdown) then the selected item changes its display from its value to its displayValue/text.

### What is the expected behavior?
The dropdown selected item should always display displayValue/text.

### How would you reproduce the current behavior (if this is a bug)?
1. Add a dropdown question to your survey which has value and test/displayValue.
2. Have some logic in your survey which on complete clears the survey aka "survey.clear()";
3. Interact with the dropdown and select an item. 
You should notice at this point that the selected item displays the item value until you click away.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by JaneGaid** [comment]
Hello @jefftudorbenbria,
Thank you for contacting us. I followed your explanation and created the following example: https://plnkr.co/edit/L42Af15OZsty78bm. 
```
var json = {
 "logoPosition": "right",
 "completedHtml": "<h3>Thank you for completing the survey</h3>",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "dropdown",
     "name": "question1",
     "choices": [
      {
       "value": "item1",
       "text": "Test Item 1"
      },
      {
       "value": "item2",
       "text": "Test Item 2"
      },
      {
       "value": "item3",
       "text": "Test Item 3"
      }
     ]
    }
   ]
  }
 ],
 "showQuestionNumbers": "off"
};
window.survey = new Survey.Model(json);
survey.onComplete.add(function (sender) {
  survey.clear();
});
```
I see that the Dropdown correctly displays an item text value:

https://user-images.githubusercontent.com/22372972/200346913-e01ee377-6b45-429f-89d9-d9961d1387b1.mp4


Would you please clarify how to reproduce the issue?

**Comment by jefftudorbenbria** [comment]
Thank you for getting back to me so quickly!

Yes you are correct, it seems that the clear() was not causing the issue.
Immediately after calling survey.clear() we call survey.render(), which seems to be the culprit.

**Comment by JaneGaid** [comment]
Hello @jefftudorbenbria,
Would you please clarify at which point you call `survey.render`? Could you please share an example which reproduces the issue? I believe this would allow us to communicate more efficiently and research the issue faster. 

Thank you

**Comment by jefftudorbenbria** [comment]
It seems after uprev-ing survey js the issue is no longer present. Thanks for your help!
