### ISSUE TITLE
`checkErrorsMode` for `OnPageNext` doesn't work correctly when a question value is changed

### ISSUE THREAD

**Issue by joshcampbell191** [surveyjs/survey-library#5194]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
 `checkErrorsMode` for `OnPageNext` isn't respected when a question with an error is changed. This causes `onValidatedErrorsOnCurrentPage` to be triggered unexpectedly.

The line in question appears to be the following: https://github.com/surveyjs/survey-library/blob/1a05580a7a4aa94ec191c46884190736f9ccc65b/src/survey.ts#L5028

### What is the expected behavior?
`onValidatedErrorsOnCurrentPage` should only be triggered when the conditions for `checkErrorsMode` are met.

### How would you reproduce the current behavior (if this is a bug)?
1. Cause an error on a question (e.g. not filling a required field)
2. Try completing the survey
3. Fix the error

After step 3, the `onValidatedErrorsOnCurrentPage` was called 2 times: once for the initial error (expected because default behavior for `checkErrorsMode` of `OnNextPage`) and a second time after the error was fixed (without trying to complete the survey).

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/709CgYRKRJjrsvtb

Test code

```js
var json = {
  "elements": [
    {
      "name": "name",
      "type": "text",
      "title": "Please enter your name:",
      "placeHolder": "Jon Snow",
      "isRequired": true
    },
  ]
};
window.survey = new Survey.Model(json);
survey.onValidatedErrorsOnCurrentPage.add(function (sender, options) {
  console.log("validation was called");
});
```

### Specify your

* browser: Microsoft Edge
* browser version: 107.0.1418.35
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.9.56

**Comment by JaneGaid** [comment]
Hello @joshcampbell191,
Thank you for reporting this issue. We will research this issue and get back to you shortly.
