### ISSUE TITLE
Validation: Error message is displayed twice and differs from the one that is specified

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-library#5195]
https://plnkr.co/edit/bKv6ftiWfwI6ibhV

1. Enter an invalid value.
2. Click Complete.

Expected result: The question displays one of the error messages specified in the `validators` array.
Actual result: The question displays a default error message twice.

**Comment by andrewtelnov** [comment]
@RomanTsukanov I have upldated [the plunker](https://plnkr.co/edit/NWWzoGkGv9G2ouNL). The numeric validator checks if the value is a numeric first. You don't need the first validator.

**Comment by RomanTsukanov** [comment]
Okay, thanks! Case closed ;)
