### ISSUE TITLE
Custom widgets not working anymore (renderAs: 'prettycheckbox')

### ISSUE THREAD

**Issue by dasboe** [surveyjs/survey-library#5198]
In the newest versions of SurveyJs (> 1.9.54) custom widgets are not working anymore. Everything is working fine in Version 1.9.54.
In my tests the `isFit` function is not called anymore.

### Are you requesting a feature, reporting a bug or asking a question?
Bug, Regression

### What is the current behavior?
Custom Widgets not working 

### What is the expected behavior?
Custom Widgets working 

### How would you reproduce the current behavior (if this is a bug)?
Change Version of SurveyJs from Version 1.9.54 to Version > 1.9.54

#### Provide the test code and the tested page URL (if applicable)

CustomWidgetCollection.Instance.addCustomWidget({
  ...
  name: 'my-widget',
  title: 'SurveyJs Creator',
  isFit: question => {
    // This is not called!!!!
  }
  ...
}, "customtype")

**Comment by stsiushkevich** [comment]
> Hello @dasboe, Thank you for reaching out to us. I created this demo (https://codesandbox.io/s/bold-phoebe-t1h3f3?file=/src/SurveyCreatorComponent.jsx) and confirmed that a custom widget got registered and the `isFit` function is triggered.
> 
> Please clarify how to reproduce the issue.

I confirm that prettycheckbox is not working anymore. You can wisit your page: https://surveyjs.io/form-library/examples/custom-widget-pretty-checkbox/reactjs

**Comment by JaneSjs** [comment]
Hi @stsiushkevich,
Thank you for sharing the demo. We will research this issue and let you know our results.
