### ISSUE TITLE
Multiple Text doesn't pass validation when checkErrorsMode is set to onValueChanging

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-library#5201]
Run [this example](https://plnkr.co/edit/EdqZwiyOoqfoxPCx). Enter the min value: the error appears and remains even if you enter a correct max value.
![image](https://user-images.githubusercontent.com/22372972/200612350-20af855a-3d9d-4f17-a0de-1c7037c1e8d2.png)

If works with the default `checkErrorsMode`: https://plnkr.co/edit/eflMNWhpQMRvgibq.

**Comment by RomanTsukanov** [comment]
Duplicate of #5190

**Comment by JaneGaid** [comment]
Dup: https://github.com/surveyjs/survey-library/issues/5190
