### ISSUE TITLE
"none" and "other" options not displaying on dropdown options in react

### ISSUE THREAD

**Issue by zulalnb** [surveyjs/survey-library#5202]
### Are you requesting a feature, reporting a bug or asking a question?
question

### What is the current behavior?

I checked "allow the other" option and "allow the none" option boxes creating dropdown survey on surveyjs. Both of options display on surveyjs.io but not on react js app. 

### What is the expected behavior?

None and other options displaying on reactjs

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
import 'survey-core/modern.min.css';
import { StylesManager, Model } from 'survey-core';
import { Survey } from 'survey-react-ui';

StylesManager.applyTheme("modern");

export function App() {

   const json = {
        surveyId: 'fff11111',
        resultId: 'aaaaa11111',
        postId:'11111bbbb',
      };
  
   const survey = new Model(json);
   return (<Survey model={survey} />)

}

```

preview on react app local machine
![img](https://user-images.githubusercontent.com/33003721/200782654-a487ec82-bde2-40dc-95d1-ce23f8bd9865.png)

options i checked
![img](https://user-images.githubusercontent.com/33003721/200780381-1a3006e7-fd23-49ba-a320-597d7f80a933.png)
![img](https://user-images.githubusercontent.com/33003721/200780494-07de1d4b-f536-46e1-bcc1-8119a0036285.png)

json editor
![img](https://user-images.githubusercontent.com/33003721/200780583-40e38221-a921-45b3-b858-084fd82fc602.png)

preview on surveyjs.io
![img](https://user-images.githubusercontent.com/33003721/200782360-a5bf55c4-bad6-45c2-8b0e-e1d8d199914f.png)

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.9.33

**Comment by JaneSjs** [comment]
Hello @zulalnb,
I believe you may use an outdated version of SurveyJS libraries. We've recently renamed options which enable the Other and None items: [Rename some has* properties](https://github.com/surveyjs/survey-library/issues/4846).

So, I recommend that you upgrade your SurveyJS libraries to the recent version and check to see it this resolves the issue.

If upgrade is not an option at the moment, you may update your survey JSON and change the `showOtherItem` and `showNoneItem` property names to `hasOther` and `hasNone`.

Please let me know your results.

**Comment by zulalnb** [comment]
Hello @JaneSjs, 

Thanks.

How to update survey JSON using code? I tried to rename showOtherItem and showNoneItem property names from JSON editor on surveyjs.io but it returns default values when i refresh the site.

**Comment by JaneSjs** [comment]
Hi @zulalnb,
Unfortunately, it is impossible to specify legacy property names using the Survey Creator at MySurveys. Properties will be always renamed to use their actual names.
Please consider upgrading your survey runner libraries.

**Comment by zulalnb** [comment]
Thanks @JaneSjs it works after upgraded the survey libraries.

**Comment by PurpleKaz81** [comment]
All y'all have no idea the life-savers you are having had this convo. Thank you! 🙂

**Comment by isophel** [comment]
Unhandled Runtime Error
TypeError: Cannot set properties of undefined (setting 'renderCallback')

Call Stack
./src/react/reactSurvey.tsx.Survey.setSurveyEvents
node_modules\survey-react-ui\survey-react-ui.js (14682:0)
./src/react/reactSurvey.tsx.Survey.createSurvey
node_modules\survey-react-ui\survey-react-ui.js (14642:0)
