### ISSUE TITLE
descriptionLocation 'underInput' not working with survey-angular-ui

### ISSUE THREAD

**Issue by philstraub** [surveyjs/survey-library#5239]
Descriptions with `descriptionLocation: 'underInput'` do not get rendered when using angular.

To reproduce:

- go to https://surveyjs.io/form-library/documentation/get-started-angular
- replace surveyJson with:
```
const surveyJson = {
  elements: [
    {
      name: "FirstName",
      title: "Enter your first name:",
      type: "text",
      description: 'a description',
      descriptionLocation: 'underTitle'
    },
    {
      name: "LastName",
      title: "Enter your last name:",
      type: "text"
      description: 'a description',
      descriptionLocation: 'underInput'
    }
  ]
};
```
- Result: The first description renders under title. The second description does not get rendered at all (but it should be rendered under the text input field).

**Comment by JaneSjs** [comment]
Hello @philstraub,
Thank you for reporting this issue. We'll research it and post updates once we have any news to share.
- Problematic Demo ([Angular sample](https://codesandbox.io/s/surveyjs-angular-forked-pjh7i3?file=/src/app/components/json.ts)).
- Working Demo ([React sample](https://plnkr.co/edit/loiI754mL8tHFvLQ?preview)).
