### ISSUE TITLE
Setting answer for custom widgets

### ISSUE THREAD

**Issue by jefftudorbenbria** [surveyjs/survey-library#5272]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

My question is regarding custom survey questions.

What is the best practice for setting the value of a question?

On input change we currently do the following:
       question.value = value;

This properly sets the answer for the question and our submit works, however the auto navigate feature is not working.
I figure this is because there is something we are missing when we set the answer.

Thank you!

* surveyjs platform: jquery
* surveyjs version: 1.9.54

**Comment by JaneSjs** [comment]
Hello @jefftudorbenbria,
You can set an answer using the `question.value` property. Also, you can call the [survey/.setValue(questionName, newValue)](https://surveyjs.io/form-library/documentation/design-survey-predefine-answers) function to set a question value. For more information on how to preset question answers, refer to [Populate Form Fields](https://surveyjs.io/form-library/documentation/design-survey-predefine-answers).

Regarding the issue: could you please send me a reproducible sample?
