### ISSUE TITLE
Survey Description and Logo do not appear in a jQuery app when a survey is loaded from a service

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5277]
I load a survey from MyService. In a jQuery app, the description & logo do not appear: [example](https://plnkr.co/edit/DRE2bTjBShfCSCpT).
It works in a React app ([sample](https://plnkr.co/edit/qZ4V0k2eCcEeddMv)). It also works if I use a static JSON ([example](https://plnkr.co/edit/WdtY1PRBGhVjovUk)). 

Original issue: [T11342 - Title and Logo do not appear in a jQuery sample when a survey is loaded from MyService](https://surveyjs.answerdesk.io/internal/ticket/details/T11342).

**Comment by andrewtelnov** [comment]
[Additional example](https://plnkr.co/edit/F9d6PPczN2vc21e9).
