### ISSUE TITLE
Text Question - The Range inputType doesn't display a range / slider control

### ISSUE THREAD

**Issue by dk981234** [surveyjs/survey-library#5293]
Current behavior:
[Example](https://plnkr.co/edit/5N9zuf4fhG1K2bdR).
![image](https://user-images.githubusercontent.com/22372972/205615259-095ef3e9-cba1-4f26-a35f-71ae4b4fc3fe.png)

Expected behavior: the range / slider component.
![image](https://user-images.githubusercontent.com/22372972/205615968-9ef157bc-c590-4908-8fdf-d6e1a747b8d4.png)

**Comment by dk981234** [comment]
https://plnkr.co/edit/OciJiAdFYtgoArMP?preview

**Comment by JaneSjs** [comment]
v1.9.134
https://plnkr.co/edit/hW0pdNc9IjZGuzMl
![image](https://github.com/surveyjs/survey-library/assets/22372972/8705d160-deb5-4b6c-8d82-eaef9c48f96c)
