### ISSUE TITLE
Custom CSS for a row with a customer property 

### ISSUE THREAD

**Issue by hamodey** [surveyjs/survey-library#5305]
### Can I add custom CSS for (some) rows on my Matrix 
To explain what I mean. I have added a custom boolean property which is of "partTwo" the use case for this doesn't matter, but the boolean will change eventually. But, I want my rows to be highlighted in **GREEN** when the boolean of `partTwo === true`. 

I have tried using the method of:

```javascript
    model.onUpdateQuestionCssClasses.add(function (survey, options) {
      const optionsClasses = options.cssClasses;

      options.question.rows.forEach((row) => {
        if (row.partTwo) {
          optionsClasses.row = 'part-two-survey-row';
        }
      });
    });
```

This method from what I have seen changes the css for ALL rows, but of course I would like it for only the rows that have partTwo. 

Is there another method you would recommend or any other variations of the above to go ahead with that?

Thanks

ps. I have added an image to support the visualisation 

![image](https://user-images.githubusercontent.com/26579110/205940771-0596abdb-d889-4b7d-b3c4-5a9c40fe4af7.png)

### Specify your

* browser: Chrome
* browser version: Latest
* surveyjs platform (angular or react or jquery or knockout or vue): React 
* surveyjs version: 1.9.41 React

**Comment by JaneSjs** [comment]
Hello @hamodey,
Let's continue discussing this issue in the following thread: [T11443 - Custom CSS for a row with a customer property #5305](https://surveyjs.answerdesk.io/internal/ticket/details/T11443).
