### ISSUE TITLE
defaultValue in dropdown (with choicesByUrl) changes preloaded data in survey

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#5309]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

It seem that the defaltValue is applied even if the survey has data already set only when using choicesByUrl

### What is the expected behavior?

to keep the original data

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/Tw5k87FZ849BxvJO

**Comment by scicco** [comment]
Hello, any update on this? 

Thank you

**Comment by masciugo** [comment]
I tried again with 1.9.79. The same behaviour persists even if is slightly different: The field is populates with the saved data (italy) but it turn back to the default value as soon as I click outside the field

**Comment by masciugo** [comment]
@andrewtelnov sorry to question you directly. I tried with 1.9.86 and the problem still persists I think this is serious bug. Could you please confirm that? thank you

**Comment by masciugo** [comment]
Hi @JaneSjs. Am I doing something wrong maybe? Please, could you tell me if this is the expected behaviour? thanks a lot

**Comment by masciugo** [comment]
not experiencing anymore in 1.9.91
