### ISSUE TITLE
Freeze progress bar in survey

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-library#5337]

**Comment by ElenaGorbatkova** [comment]
@OlgaLarina https://surveyjs.io/service/editsurvey/e0702e8e-1f5a-4efa-9414-d4e33ba7809f

**Comment by OlgaLarina** [comment]
https://github.com/surveyjs/survey-library/issues/5360

**Comment by OlgaLarina** [comment]
https://surveyjs.io/form-library/examples/product-feedback-survey-template/reactjs

**Comment by mikeamelin** [comment]
Just freeze progress bar on the top, and let's see how it works.

Btw — can user change height of the progress bar? I don't want to make it huge by default, but I suppose someone wants to make it more visible (see image).


![Image](https://user-images.githubusercontent.com/17025812/208943703-0081969b-74bf-4e36-b984-5ec3270deaa7.png)
