### ISSUE TITLE
Boolean Question ignores valueTrue and valueFalse in Mobile (Radio Button) Mode

### ISSUE THREAD

**Issue by PixelDonut** [surveyjs/survey-library#5343]
### Are you requesting a feature, reporting a bug or asking a question?
I'm reporting a Bug

### What is the current behavior?
The boolean ignores the valueTrue and valueFalse when in mobile view and just saves it as true or false. Because of this the second question doesn't become visible

### What is the expected behavior?
The valueTrue and valueFalse is used when in mobile view. Thus the second question becomes visible

### How would you reproduce the current behavior (if this is a bug)?
Make the browser window smaller, so it shows the boolean as two radio buttons instead of the slider. Then answer the first question. The second question does not pop up

#### Provide the test code and the tested page URL (if applicable)

Test code

```
"elements": [{
            "type": "boolean",
            "name": "*question",
            "isRequired": true,
            "title": "title",
            "labelTrue": "Yes",
            "labelFalse": "No" ,
            "valueTrue": 2,
            "valueFalse": 0
        },{
            "type": "boolean",
            "name": "question1",
            "isRequired": true,
            "visibleIf": "{*question} = 2",
            "title": "title2",
            "labelTrue": "Yes",
            "labelFalse": "No",
            "valueTrue": 3,
            "valueFalse": 2
        }]
```

* browser: Google Chrome
* browser version: 108.0.5359.98
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.9.64

**Comment by JaneSjs** [comment]
Hello @PixelDonut,
Thank you for reporting this issue. I tested this and confirmed that the second question does not appear when Boolean questions are rendered as radio buttons. 
```
const json = {
  "elements": [
    {
            "type": "boolean",
            "name": "*question",
            "isRequired": true,
            "title": "title",
            "labelTrue": "Yes",
            "labelFalse": "No" ,
            "valueTrue": 2,
            "valueFalse": 0,
            "renderAs": "radio"
        },{
            "type": "boolean",
            "name": "question1",
            "isRequired": true,
            "visibleIf": "{*question} = 2",
            "title": "title2",
            "labelTrue": "Yes",
            "labelFalse": "No",
            "valueTrue": 3,
            "valueFalse": 2,
             "renderAs": "radio"
        }]
};
```
[Example](https://plnkr.co/edit/PdLsdh2AlL738ZnM).
We'll research this issue and get back shortly.

**Comment by PixelDonut** [comment]
@JaneSjs Boolean is misspelled, is that intentional?
