### ISSUE TITLE
Survey is not scrolled to a focused question

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5346]
I use the survey.focusQuestiuon functino to focus a question. The question gets focused, however, the survey is not scrolled and the focused question though focused remains invisible: [example](https://plnkr.co/edit/vqjeBL2c9bWm8V8u?open=lib%2Fscript.js).

Current behavior:
![image](https://user-images.githubusercontent.com/22372972/208049214-e820535a-532c-46d7-a08c-7f05185cde46.png)

Expected behavior: the survey is scrolled to a focused question:
![image](https://user-images.githubusercontent.com/22372972/208049344-24b3c9f2-04ef-458a-8d02-40af45d7a46e.png)

Original Issue: [T11528 - FocusQuestion not scrolling](https://surveyjs.answerdesk.io/internal/ticket/details/T11528)

**Comment by tsv2013** [comment]
The thing is that addressed question is on the second page. And question markup is not been rendered yet. Thus survey is need to render target page first and then focus the question.

Rendering in modern frameworks like react usually delayed. And this is why question has not been focused during the linear code execution.

Here is the temporary workaround:
```JS
survey.currentPage = JSON.parse(responseJson).pageNo - 1;
// survey.focusQuestion('question66_2');
setTimeout(() => {
  debugger
  survey.focusQuestion('question66_2');
}, 1);
```
