### ISSUE TITLE
SurveyModel: Rename parameters in the `onCurrentPageChanging` and `onCurrentPageChanged` event handlers

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-library#5355]
`onCurrentPageChanging`:

- `options.allowChanging` -> `options.allow` (for consistency)

`onCurrentPageChanging` and `onCurrentPageChanged`:

- `options.isNextPage` and `options.isPrevPage` - replace with `options.isGoingBackwards`

**Comment by andrewtelnov** [comment]
@RomanTsukanov `isGoingBackwards !== isPrevPage`. `isPrevPage` when a user press a previous button or goes exactly on a page before the current. `isGoingBackwards` should be true when a user goes to any page before the current.
The same story with the `isGoingForwards`.
I have added these two properties. 'allow' is already here.

Thank you,
Andrew
