### ISSUE TITLE
Change none item value to another value

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#5363]
Add `Survey.settings.selectNoneItemValue` property (default 'none'). To change the none item value to another value you can use the following code: `Survey.settings.selectNoneItemValue = "n/a";` 

### Are you requesting a feature, reporting a bug or asking a question?

Question/feature 

### What is the current behavior?

I cannot set the hasNone value in dropdown questions. I mean something different than 'none'

### What is the expected behavior?

Have a hasNoneValue option to customize none value

Or can you please provide an alternative way to customize the default behavior?

Thanks a lot

**Comment by andrewtelnov** [comment]
@masciugo Why can't you add any other item in dropdown choices and consider it as a 'none'?

Thank you,
Andrew

**Comment by masciugo** [comment]
Because I load the choices from internet using choicesByUrl and I was asked to return "NA" as vaule. I already tried a workaround by leveraging on value changing event but then I thought that would beuch more elegant and of general interest if it could be set at model definiton level like all other similar settings. Thanks in any case

**Comment by masciugo** [comment]
great man! thank you

**Comment by RomanTsukanov** [comment]
@masciugo 
We have implemented the requested functionality, but slightly changed the API that you suggested. Starting with v1.9.65, you can set a default None item value as follows:

```js
Survey.settings.noneItemValue = "n/a";
```

**Comment by masciugo** [comment]
thanks @RomanTsukanov but it seems that last change does not work with v1.9.65

https://plnkr.co/edit/Av35khR3isLLisJV

Apart from this maybe I was unclear about my need. I opened this issue while I was trying to hack surveyJS someway so that I came across `Survey.settings.selectNoneItemValue` general setting. But [later](https://github.com/surveyjs/survey-library/issues/5363#issuecomment-1356223171) I imagine something settable by users: 

>  ...I thought that would be much more elegant and of general interest if it could be set at model definiton level like all other similar settings

I mean something settable at survey level by a property exposed to users or, even better, by a property at question level: from an API point of view I would just add a new `noneValue` question prop flank the other _none_ props:
![image](https://user-images.githubusercontent.com/454321/209203437-ba9b0e71-3e88-42fb-b3d3-e2153a6d01cf.png)

If this is not possible or you don't like it I can add the `noneValue` prop as a custom prop for my users. But then, can you suggest a snippet to apply it?

thanks again

**Comment by masciugo** [comment]
Moreover.. it seems from the docs that the intention to change then None choice item si/was considered. But the this is a readOnly prop. Thank you
![image](https://user-images.githubusercontent.com/454321/209303970-f5799825-7e15-4a9f-8b90-3cb00f3b07d9.png)

**Comment by RomanTsukanov** [comment]
@masciugo 
We are investigating into why the `noneItemValue` property wasn't included into the latest release. Thanks for bringing this to our attention. In the meantime, could you please clarify why your users might need to change the value produced by the None item? I assume that they design their surveys using Survey Creator. In this case, it shouldn't matter to them how the None item is processed and stored in your database, because they never deal with your backend.

As for the `noneItem` property, here's an example of how you can use it to change the None value for an individual survey question in code:

https://plnkr.co/edit/crXryf17gpd9SQXu

**Comment by masciugo** [comment]
@RomanTsukanov thank you for your interest. My application is basically a workspace for researchers where they collect and extract data in a collaborative way for their studies (it's an [EDC](https://en.wikipedia.org/wiki/Electronic_data_capture)) **The application is not vertical on a specific research study i.e., it is independent of the type of data collected, which are decided on a study-by-study basis by the researchers**. So users creates their forms on their own providing the raw json model (I hope we'll add the creator in the mid future) and later export the relative collected data. As they use the exported data for feeding their analysis tools sometimes they need some specific formats like 'NA' or 'N/A' but in general I can't predict it. 

Thanks for the example which, to be honest, I had already tried without success in my context so it was because of it. But it will help, I need to investigate

**Comment by masciugo** [comment]
@RomanTsukanov by extending your example to a more basic dropdown with hard coded choices it doesn't work.

https://plnkr.co/edit/N1p5c7EadInvZi4S

it should, doesn't it?

I know that, in this case, I can add manually the none option but I would like to provide to my app users the same interface to manage none item for all multiple-choice questions

**Comment by RomanTsukanov** [comment]
@masciugo Looks like a bug. I created a separate issue: https://github.com/surveyjs/survey-library/issues/5424. Please track it to be notified about any progress.
