### ISSUE TITLE
TypeError: this.element.clickTitleFunction is not a function

### ISSUE THREAD

**Issue by vinod-amt** [surveyjs/survey-library#5380]
![image](https://user-images.githubusercontent.com/95850031/208679799-cb1b43e4-8895-426c-ba12-dbb1e5f85d3e.png)

the package "survey-angular-ui" is giving error when you click on some place. that place you can get from below surveyjs json.

```json
{
 "title": "Bla bla bla",
 "description": "A real-world bla bla bla....",
 "logoPosition": "right",
 "completedHtml": "<h3>We appreciate you . Thank you</h3>",
 "completedHtmlOnCondition": [
  {
   "expression": "({question6} = 'No') or ({question7} = 'No')",
   "html": "<h3>Sorry, bla bla</h3>"
  }
 ],
 "pages": [
  {
   "name": "Patient Registration",
   "elements": [
    {
     "type": "panel",
     "name": "patient_registration",
     "elements": [
      {
       "type": "text",
       "name": "uhid",
       "maxWidth": "32%",
       "title": "some question",
       "isRequired": true
      }
     ],
     "title": "Click here for Error",
     "minWidth": "300px"
    }
   ],
   "title": "page title",
   "description": "bla bla blaa......"
  }
 ],
 "triggers": [
  {
   "type": "complete",
   "expression": "({question6} != 'Yes') or ({question7} != 'Yes')"
  }
 ],
 "sendResultOnPageNext": true,
 "navigateToUrlOnCondition": [
  {}
 ],
 "showPageNumbers": true,
 "showProgressBar": "top",
 "progressBarType": "buttons",
 "checkErrorsMode": "onValueChanged",
 "textUpdateMode": "onTyping",
 "showPreviewBeforeComplete": "showAllQuestions",
 "widthMode": "responsive"
}
```

All you need to do is to click on "Click here for Error" text. 
Again remainding you , this error is happening with "survey-angular-ui" package only and you can use your "surveyjs_angular_cli" 
boilerplate repo only to recreate this bug.

### Are you requesting a feature, reporting a bug or asking a question?
reporting a bug.

### What is the current behavior?
error happening when you click at certain place.

### What is the expected behavior?
no error should happen.

### How would you reproduce the current behavior (if this is a bug)?
mentioned in above details.

#### Provide the test code and the tested page URL (if applicable)
you can use your "surveyjs_angular_cli" repo with the provided survey json.

Tested page URL:
NA

Test code

```
NA

```

### Specify your

* browser: chrome
* browser version: latest to this date.
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: 1.9.64

**Comment by JaneSjs** [comment]
Hello @vinod-amt,
Thank you for sharing the sample. I created [this sample](https://codesandbox.io/s/surveyjs-angular-forked-hpm1xj?file=/src/app/components/json.ts) and reproduced the following exception:
```
ERROR TypeError: this.element.clickTitleFunction is not a function
    at ElementHeaderComponent.click (survey-angular-ui.mjs? [sm]:885:22)
    at ElementHeaderComponent_click_HostBindingHandler (ɵcmp.js:0:0)
    at executeListenerWithErrorHandling (core.mjs? [sm]:15780:16)
    at wrapListenerIn_markDirtyAndPreventDefault (core.mjs? [sm]:15815:22)
    at HTMLDivElement.eval (platform-browser.mjs? [sm]:459:38)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs? [sm]:26367:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
    at invokeTask (zone.js:1661:18)
    at globalCallback (zone.js:1692:29)
    at HTMLDivElement.globalZoneAwareCallback (zone.js:1725:16)
```
We will investigate the issue and let you know our results.
