### ISSUE TITLE
Expession: No errors should be thrown even if an expression cannot be parsed

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-library#5384]
if expression is wrong it returns empty string
if expression refers question with unknown name it returns 0
if question refers to unregistered function it returns...

We do not raise any exception in that cases. It is ok.
But we need to show some warning in console.

**Comment by JaneSjs** [comment]
+1 [T11797 - Error in Expression or Calculated Value (e.replace is not a function)](https://surveyjs.answerdesk.io/internal/ticket/details/T11797)
