### ISSUE TITLE
Right answer

### ISSUE THREAD

**Issue by bsde1234** [surveyjs/survey-library#5387]
### Are you requesting a feature, reporting a bug or ask a question?
Do you have right answer option to convert poll to quiz?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by JaneSjs** [comment]
Hello @bsde1234,
Yes - we have a [correctAnswer](https://surveyjs.io/form-library/documentation/api-reference/question#correctAnswer) option for a question. You can specify correct answers to create a quiz. For more information, please refer to:
* Demo: [Make a Quiz](https://surveyjs.io/form-library/examples/make-quiz-javascript/reactjs)
* Documentation: [Make a Quiz](https://surveyjs.io/form-library/documentation/design-survey/create-a-quiz)

Please let us know if you have any questions or require further assistance.

**Comment by bsde1234** [comment]
Is there any option to show correct answer at end of each question for at
least 2 seconds. Also a background music also would be nice. It can be used
as quiz master tv shows

**Comment by JaneSjs** [comment]
Please refer to the following demo to learn how to review quiz results: https://surveyjs.io/form-library/examples/survey-quiz-results/reactjs.

Regarding the music: unfortunately, the survey doesn't have such an option. I may suggest that you use a third-party library to play a music while a respondents fills in survey questions. 

Should you have any questions or require further assistance, we are here to help.

**Comment by bsde1234** [comment]
The purpose is to create a video by screen recording not to give quizzes to
users. Means after 5 seconds answer should come  and then next question. I
think you get it

**Comment by JaneSjs** [comment]
Hello @bsde1234,
Please let me make sure I clearly understand your usage scenario. Do you wish to create a quiz which users can fill in on a web site? After user inactivity, do you wish to show a correct answer?

Please clarify your task to let me consider the best option. Feel free to share some mockup images/screenshots/videos to illustrate your task.

**Comment by bsde1234** [comment]
Please view this video https://youtu.be/e5zR7bNpb8s

**Comment by JaneSjs** [comment]
Thank you for the update. Let me make sure I got it right: you wish to check an option, and immediately display a correct answer?

**Comment by bsde1234** [comment]
No, it doesn't. It's purely for video purposes only. Nobody will attend
quiz. Question with option should come after a specific time answer also
should display for specific time. A background music (a difference for
question and answer would be nice) also good.

**Comment by JaneSjs** [comment]
Hi,
Thank you for the clarification. If you wish to display a correct answer, you can use a Markdown feature and render a correct option, as demonstrated by the `renderCorrectAnswer` function in the [Review Quiz results](https://surveyjs.io/form-library/examples/survey-quiz-results/reactjs) demo.

**Comment by bsde1234** [comment]
Hi, That looks fine. Can you please tell me how to apply `renderCorrectAnswer` in https://surveyjs.io/form-library/examples/make-quiz-javascript/jquery#content-code
There each question have 10 seconds time. I need to show correct answer for 3 seconds after each question.

Thanks.

**Comment by bsde1234** [comment]
@JaneSjs @andrewtelnov please give a code

**Comment by andrewtelnov** [comment]
@bsde1234 To trigger onTextMarkdown event for all elements on the current page you can call:
`survey.currentPage.locStrsChanged();`
You can call this function on your time event.

Thank you,
Andrew

**Comment by bsde1234** [comment]
Hi @andrewtelnov I am not a coder. Can you please give full code by adding your solution in https://surveyjs.io/form-library/examples/make-quiz-javascript/jquery#content-code

**Comment by JaneSjs** [comment]
Hi @bsde1234,
Please accept my apologies for the delayed reply. The following demo shows how to:
* Automatically switch a survey to the next page each 10 seconds;
* Automatically display the CORRECT/INCORRECT label after 3 seconds on each page.
This routine is done by the following code:
```
setInterval(() => {
    if (survey.isLastPage) {
      survey.doComplete();
      return;
    }
    survey.nextPage();
  }, 10000);
  setInterval(() => {
    changeTitle(survey.currentPage.questions[0]);
    }, 3000);
```
