### ISSUE TITLE
Ranking Issues and Enchancements

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#5392]
- [x] no drag indicator (Safary only)
![Image](https://user-images.githubusercontent.com/17025812/208933807-68d668ac-ea6f-430a-9dc6-3d291fb86ab3.png)
- [x] circle size
- [x] floating item size
- [x] editing mode - creator editing border:
![Image](https://user-images.githubusercontent.com/17025812/208938617-43d17299-01e0-4bb6-b2dd-3b5cfd78c618.png)
- [x] indicator position (mobile) :
![Image](https://user-images.githubusercontent.com/17025812/215264579-a0df1c55-b452-495d-8c57-7f73539bd6a2.jpeg)

See original design — https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SJS-Creator?node-id=9397%3A48582&t=loNh6Fq16DtZwLxq-4

and for the mobile - https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=10034%3A78153&t=kL5yFGm88ST1tKem-4

**Comment by dmitrykurmanov** [comment]
- [ ] 
![image](https://user-images.githubusercontent.com/22315929/219587442-56afaaf9-f65d-4afe-9e38-3b15a4637261.png)

- [ ] 
![image](https://user-images.githubusercontent.com/22315929/219587503-8c006fd8-3fbd-432c-8a72-7c636792c776.png)

- [ ] change "-" to icon: 
![image](https://user-images.githubusercontent.com/22315929/219588417-b9d74a41-4fdc-4b92-b5a4-f8a68d5d1fd5.png)
