### ISSUE TITLE
RunExpression Trigger only calculating for Matrix values when the first row is updated

### ISSUE THREAD

**Issue by tylers** [surveyjs/survey-library#5407]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

For a runexpression definition based on values from a matrix question, if the expression value returns true, runexpression is only calculating when the first row is updated. 

### What is the expected behavior?

runexpression should calculate when the related expression returns true and any of the referenced values are updated.

### How would you reproduce the current behavior (if this is a bug)?

For plnkr example below:

The defined expression for the runexpression trigger requires all rows to have a value before calculating. Once every row has a selection, the 'Expression Total' and 'Run Expression Total' elements should display the same value.

1. Select a value for Row A: 'Expression Total' will update, 'Run Expression Total' will not
2. Select a value for Row B: 'Expression Total' will update, 'Run Expression Total' will not.
3. Select a value for Row C: 'Expression Total' will update, 'Run Expression Total' will not. (Errant behavior)
4. Select a new value for Row A: 'Expression Total' will update, 'Run Expression Total' will update.
5. Select a new value for Row B: 'Expression Total' will update, 'Run Expression Total' will not.  (Errant behavior)
6. Select a new value for Row A: 'Expression Total' will update, 'Run Expression Total' will update.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/BOj8nHYlpEeYx9eV

Test code

```
{
  "title": "Run Expression trigger for Matrix Questions",
  "completedHtml": "<h3>Thank you for completing the survey</h3>",
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "matrix",
          "name": "MatrixQuestion",
          "title": "Matrix Question",
          "columns": [
            "0", "1", "2"
          ],
          "rows": [
            {
              "value": "RowA",
              "text": "Row A"
            },
            {
              "value": "RowB",
              "text": "Row B"
            },
            {
              "value": "RowC",
              "text": "Row C"
            }
          ]
        },
        {
          "type": "expression",
          "name": "ExpressionTotal",
          "title": "Expression",
          "expression": "{MatrixQuestion.RowA} + {MatrixQuestion.RowB} + {MatrixQuestion.RowC}"
        },
        {
          "type": "text",
          "name": "RunExpressionTotal",
          "title": "Run Expression",
          "readOnly": true
        }
      ]
    }
  ],
  "triggers": [
    {
      "type": "runexpression",
      "expression": "{MatrixQuestion.RowA} notempty and {MatrixQuestion.RowB} notempty and {MatrixQuestion.RowC} notempty",
      "runExpression": "{MatrixQuestion.RowA} + {MatrixQuestion.RowB} + {MatrixQuestion.RowC}",
      "setToName": "RunExpressionTotal"
    },
  ]
}

```

### Specify your

* browser: Chrome
* browser version: 108.0.5359.124
* surveyjs platform: tested on angular (non-ui) locally, angular-ui and knockout on codesandbox
* surveyjs version: 1.9.65

**Comment by andrewtelnov** [comment]
@tylers You can't use triggers for matrices.
Your expression column should be the following:
```json
 {
          "type": "expression",
          "name": "ExpressionTotal",
          "title": "Expression",
          "expression": "{row.RowA} + {row.RowB} + {row.RowC}"
 }
```

Thank you,
Andrew

**Comment by tylers** [comment]
> @tylers You can't use triggers for matrices. Your expression column should be the following:
> 
> ```json
>  {
>           "type": "expression",
>           "name": "ExpressionTotal",
>           "title": "Expression",
>           "expression": "{row.RowA} + {row.RowB} + {row.RowC}"
>  }
> ```
> 
> Thank you, Andrew

@andrewtelnov  Why would I change `MatrixQuestion.RowA` to `row.RowA`? If you click on my [plnkr link](https://plnkr.co/edit/BOj8nHYlpEeYx9eV?preview) in my original description above and edit the ExpressionTotal expression to `row.` prefixes, it breaks it even further.

**Comment by tylers** [comment]
_I didn't want to close ticket with my comment but github forced it._

> You can't use triggers for matrices.

Is this by design or because there is a bug?

**Comment by andrewtelnov** [comment]
@tylers You can't use triggers for matrix dynamic. Trigger should work for this matrix. I will need to take a look.
For some reason, [the following example](https://plnkr.co/edit/9Smz9wbUxxyx2Dnw?preview) with defaultValueExpression doesn't work as well.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@tylers I have started to write unit tests and found that I wrote incorrect code for "iff" function. Here is the correct defaultValueExpression property and [the updated example](https://plnkr.co/edit/ZFQ3bEOmWEL7xWBK).
```js
"defaultValueExpression": "iif({MatrixQuestion.RowA} > 0 and {MatrixQuestion.RowB} > 0 and {MatrixQuestion.RowC} > 0,{MatrixQuestion.RowA} + {MatrixQuestion.RowB} + {MatrixQuestion.RowC}, 0)",
```
Regarding trigger. I will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@tylers I have fixed the issue by the PR above.

Thank you,
Andrew
