### ISSUE TITLE
Missing minRateDescription and maxRateDescription in mobile view

### ISSUE THREAD

**Issue by DavidViolet18** [surveyjs/survey-library#5409]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
Actually when we use the rating question with rate description,  the ends are replaced by the min rate and max rate description in desktop mode. On mobile, only numbers appear.

### What is the expected behavior?
I would like on mobile the min rate and max rate description appear instead of the numbers.

### How would you reproduce the current behavior (if this is a bug)?
I can reproduce the bug on the website https://surveyjs.io/create-free-survey

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
{
 "locale": "fr",
 "logoFit": "none",
 "logoPosition": "right",
 "pages": [
  {
   "name": "personal_info",
   "elements": [
    {
     "type": "rating",
     "name": "varied_nutrition",
     "title": {
      "fr": "Avez-vous une alimentation variée ?"
     },
     "isRequired": true,
     "rateMax": 10,
     "minRateDescription": {
      "fr": "gras - sucré - salé"
     },
     "maxRateDescription": {
      "fr": "sain et équilibré"
     },
     "displayRateDescriptionsAsExtremeItems": true
    }
   ]
  }
 ],
 "sendResultOnPageNext": true,
 "showTitle": false,
 "showPageTitles": false,
 "questionDescriptionLocation": "underInput",
 "showProgressBar": "top",
 "completeText": {
  "fr": "Découvrez votre routine beauté !"
 },
 "questionsOnPageMode": "questionPerPage",
 "widthMode": "responsive"
}
```

![image](https://user-images.githubusercontent.com/13423682/209294286-c3418efe-52d1-4ed3-9b3c-5ae6d1b9aa18.png)
![image](https://user-images.githubusercontent.com/13423682/209294364-c51d121d-3d9f-4115-80fd-36703f8fef79.png)

### Specify your

* browser: Chrome
* browser version:  109.0.5414.46
* surveyjs platform (angular or react or jquery or knockout or vue): angular 1.9.59
* surveyjs version: 1.9.59

**Comment by JaneSjs** [comment]
Hello @DavidViolet18,
In smaller screens, a Rating question adaptively changes its view mode. So, instead of buttons, Rating displays rate values in a drop-down list. In this mode, min and max labels are no longer displayed.

**Comment by DavidViolet18** [comment]
Hi @JaneSjs, 
Is there a way to display these descriptions in the drop-down list ? 
Since on smaller screens, the user does not know what the values ​​1 and 10 correspond to and therefore cannot make decisions to select the correct answer.

**Comment by JaneSjs** [comment]
Hello @DavidViolet18,
Please accept my apologies for the delayed reply. Unfortunately, we haven't considered displaying min/max rate value descriptions  in a mobile/dropdown Rating mode. As an option, you may consider using the buttons render mode. With this option, a Rating question will use buttons to display rate items. On mobile, these items will be wrapped to the next line.
![image](https://github.com/surveyjs/survey-library/assets/22372972/58e4cb84-dafd-491d-ace8-523c5c355206)
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "rating",
     "name": "question1",
     "minRateDescription": "The minimum value",
     "maxRateDescription": "The maximum value",
     "displayMode": "buttons"
    }
   ]
  }
 ]
}
```

**Comment by mikeamelin** [comment]
Prototype to discuss — https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Library-Preview?type=design&node-id=1734-94728&mode=design

**Comment by mikeamelin** [comment]
Popup prototype — https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Library-Preview?type=design&node-id=1738-159932&mode=design&t=0ekAtAViznF5bbBa-4
