### ISSUE TITLE
Allow set survey background image using JSON and Creator

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-library#5410]

**Comment by AndOne1974** [comment]
That would be a cool feature!

**Comment by JaneSjs** [comment]
+1 [T11777 -  How to change the  color, font and background color of the survey ? While creating survey there is no option](https://surveyjs.answerdesk.io/internal/ticket/details/T11777)

We want to have background image on the survey body

**Comment by JaneSjs** [comment]
Found one more issue requesting a similar functionality: [Ability to add background color/image on pages. ](https://github.com/surveyjs/survey-library/issues/394)

**Comment by JaneSjs** [comment]
+1
https://surveyjs.answerdesk.io/internal/ticket/details/T12107

load a background image per question or per page
