### ISSUE TITLE
Third party Angular component integration: clarification needed

### ISSUE THREAD

**Issue by thomaux** [surveyjs/survey-library#5414]
I am developing custom widget types as standalone Angular applications (comparable to the principle of micro-frontends) and currently have a working solution, where I bootstrap the Angular module in the custom widget's `afterRender` hook:

```typescript
import { CustomWidgetCollection } from 'survey-core';

const type = 'my-custom-type';

@Component{... }
class Widget { ... }

const json = {
  name: type,
  title: type,
  widgetIsLoaded: () => true,
  isFit: (question: Question) => question.getType() === type,
  htmlTemplate: '<div></div>',
  afterRender: async (question: Question, el: HTMLDivElement) => {
    /**
     * Create a new module on the fly to allow us to bootstrap to the root element (div) of the template of this custom question
     */
    @NgModule({
      imports: [BrowserModule, HttpClientModule, ...],
      providers: [...],
    })
    class CustomQuestionModule implements DoBootstrap {
      ngDoBootstrap(appRef: ApplicationRef): void {
        appRef.bootstrap(Widget, el);
      }
    }

    await platformBrowserDynamic().bootstrapModule(CustomQuestionModule);
  },
};

CustomWidgetCollection.Instance.add(json, 'customtype');
```

My approach is based on the [official documentation on creating custom question widgets](https://surveyjs.io/survey-creator/documentation/create-custom-widget#add-new-question-using-custom-widget).

I had to amend my solution however, as bootstrapping multiple Angular applications on a single page results in an error due to the same Angular platform being created multiple times.

I have a workaround where both the custom widgets and my application request the Angular platform as a singleton, but I would like to provide a cleaner solution. I asked this as a general [question on StackOverflow](https://stackoverflow.com/questions/74786813/bootstrap-the-same-angular-standalone-component-multiple-times-on-one-page/74822484#74822484) and got a response from a SurveyJS team member (thanks for that!). The response indicated I should switch to the new survey-angular-ui library to resolve my problem.

As this library provides native Angular components and no longer relies on Knockout, I decided to make the jump. However I seem to be unable to figure out how to use the `AngularComponentFactory` to register my custom Angular widget questions. In the code below I simply swapped out the functionality of the after render function and replaced that by registering the component instead directly to the AngularComponentFactory, but alas this does not seem to yield a result:

```typescript
import { AngularComponentFactory } from 'survey-angular-ui';

const type = 'my-custom-type';

@Component{... }
class Widget { ... }

AngularComponentFactory.Instance.registerComponent(type, Widget)
```

Browsing through the docs, I found a [tutorial on how to integrate third party widgets using React](https://surveyjs.io/survey-creator/documentation/third-party-component-integration-react) and I am wondering if the docs could be updated to include an Angular example as well?

Many thanks in advance for your time and effort.

**Comment by thomaux** [comment]
Andrew was able to answer my SO question with a [working example](https://codesandbox.io/s/surveyjs-angular-forked-96o0np?file=/src/app/app.module.ts:333-386). I believe adding a dedicated page on how to integrate third party libs in Angular, similar to the React page, would help a lot of users.

**Comment by tsv2013** [comment]
Please check the live example - https://codesandbox.io/s/7d9zjs
