### ISSUE TITLE
Inner Panel Dynamic panels are not expanded when validation errors occur

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5431]
Run [this example](https://plnkr.co/edit/KbgHNyT0sQbneJKg). Navigate to the second page and click Complete. Validation errors occur and empty fields are highlighted asking a user to enter values. 
![image](https://user-images.githubusercontent.com/22372972/209792283-2bf6d9c3-4e2a-45d3-9656-2bb43003a250.png)

Enter some values.
![image](https://user-images.githubusercontent.com/22372972/209792337-fec1643c-ae5c-4194-9117-78af50fda4f6.png)

Try to sumbit the form again. Nothing happens. It is because inner panel dynamic questions also have validation errors. However, panels are not expanded when validation errors occur.
Expected behavior: nested elements are also expanded to allow users address validation errors:
![image](https://user-images.githubusercontent.com/22372972/209792509-bca32233-85f7-44e6-97b5-1bd3e58e9529.png)

Original issue: [T11613 - Show error in paneldynamic](https://surveyjs.answerdesk.io/internal/ticket/details/T11613).

**Comment by andrewtelnov** [comment]
The [minimum example](https://plnkr.co/edit/ih4NckMaOyTx3oEp) that shows the issue.
