### ISSUE TITLE
Display Current/Maximum Allowed Characters when a maximum length is defined for input fields

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5436]
Usage scenario: Text input fields (e.g., Text, Comment questions) define the `maxLength` property:
```
{ 
   "elements": [
    {
     "type": "text",
     "name": "question1",
     "maxLength": 5
    }
   ] 
}
```
Display the Current/Max allowed characters for input fields.
![image](https://user-images.githubusercontent.com/22372972/209923800-385da9c4-a0bf-460e-bd6d-c18874ff7ced.png)

**Comment by mikeamelin** [comment]
Design — https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SJS-Creator?node-id=15561%3A133259
