### ISSUE TITLE
Fix design for overlay popup in dropdown question

### ISSUE THREAD

**Issue by dk981234** [surveyjs/survey-library#5437]

**Comment by mikeamelin** [comment]
Multi-select — https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SJS-Creator?node-id=15611%3A127493&t=a4Wrl8EjI0eBCbaU-4

Drop-down — https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SJS-Creator?node-id=15611%3A131147&t=a4Wrl8EjI0eBCbaU-4
