### ISSUE TITLE
Dropdown Question: Wordpress: Issue

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/survey-library#5441]
The question has problems with modern theme and wordpress:

![image](https://user-images.githubusercontent.com/22315929/210073012-dbc9dcf1-de7c-4b39-a9e6-fda29d10e7ff.png)

**Comment by olivertwist0404** [comment]
Update your WordPress to the latest version 9.0 which was released recently. My client is also facing this error while posting in their [court of kern](https://thecourtdirect.com/superior-court-of-kern-detailed). The New version is awesome must try it.

**Comment by JaneSjs** [comment]
Hello @olivertwist0404,
Thank you for your input. The original issue posted in this thread doesn't relate to the WordPress version. An issue occurs in our Form Library. We are currently working on it. After that, we will update the SurveyJS version for the WordPress Plugin. With the update, the issue will be resolved.

Regarding the WordPress version update: unfortunately, we don't plan such an update at the moment. Updating a WordPress version may require significant changes in SurveyJS WordPress plugin. However, SurveyJS Team resources are not focused on other tasks: for more information, check our [Roadmap](https://medium.com/@surveyjs/surveyjs-2022-year-end-recap-a1d581694381).

**Comment by JaneSjs** [comment]
@olivertwist0404, I decided to extract your inquiry to a separate thread: https://github.com/surveyjs/survey-library/issues/5511. We will consider updating WordPress version for SurveyJS Word Press Plugin.

Thank you
