### ISSUE TITLE
Render survey into some div not using the <survey> component

### ISSUE THREAD

**Issue by Ich1goSan** [surveyjs/survey-library#5451]
Method of Model class _render_ is not working

My example below:

```
export class TestComponent implements OnInit {
  public survey: Model;
  public json = {
    "elements": [{
      "name": "username",
      "type": "text",
      "title": "Username"
    }]
  };
  ngOnInit(): void {
    this.survey = new Model(this.json);
    this.survey.render("testing");
    // Also tried
    this.survey.render(document.querySelector('div#testing'));
  }

}
```
Html:
```
<div id="testing"></div>
```
I need to render survey directly into the div like in a previous version of library (SurveyNG.render("testing", { model: this.survey });) 
I can't use this approach <survey [model]="survey"></survey>

* surveyjs platform (angular or react or jquery or knockout or vue): angular with "survey-angular-ui": "1.9.55", "survey-core": "1.9.55",
* surveyjs version: 1.9.55

Could you help me to resolve this issue? Thank you!

**Comment by andrewtelnov** [comment]
@Ich1goSan You can use a knockout or jquery version in this case. "survey-angular-ui" is a package that uses Angular rendering. It works as any other Angular Component.

Thank you,
Andrew
