### ISSUE TITLE
None option is not part of question 

### ISSUE THREAD

**Issue by AndriiSiuta** [surveyjs/survey-library#5459]
### Are you requesting a feature, reporting a bug or asking a question?
Asking question: why do none value do not push into question JSON?
Bug or ?

### What is the current behavior?
Current behaviour: when we add none inside survey it goes for hasNone = true, and noneText and do not add into question array

### What is the expected behavior?

Expected behavior none is present in question array as should be logical for developers

### How would you reproduce the current behavior (if this is a bug)?
Create checkbox question add few options and add none.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
![photo_2023-01-06_11-21-40](https://user-images.githubusercontent.com/21024727/210970857-adbec8dd-ec77-4a49-85f0-1d137c00382b.jpg)

```
Surveycreator.text

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:
  "survey-angular": "1.8.41",
    "survey-creator": "1.8.41",
    "survey-knockout": "1.8.41",
    "surveyjs-widgets": "1.8.41",

**Comment by andrewtelnov** [comment]
@AndriiSiuta We believe that None item value should be setup by a developer. End-user should not worry about none item value. In latest version of SurveyJS you can change it in Survey settings as the following:
`Survey.settings.noneItemValue = "super_none";`

Thank you,
Andrew

**Comment by AndriiSiuta** [comment]
It's not about user, it's logical interface, when you add any external option it should be part of this interface. You can add a lot of custom things, but this thing is inside choice

**Comment by andrewtelnov** [comment]
@AndriiSiuta You can change the behavior of SurveyJS on different levels. I strongly believe that end-user should not worry about none item value and it should be the same for all questions.
As a developer you can change it via settings as I show above.
However, SurveyJS is a flexible framework you can define noneValue property and it will solve your task.
The [example](https://plnkr.co/edit/eVqx5V7t2bN6fsif) and the code snip.
```js
Survey.Serializer.addProperty('selectbase', {
  name: 'noneValue',
  dependsOn: 'showNoneItem',
  visibleIf: (obj) => {
    return obj.hasNone;
  },
  nextToProperty: "showNoneItem",
  onGetValue: (obj) => { return !!obj && !!obj.noneItem ? obj.noneItem.value : "none"; },
  onSetValue: (obj, val) => { obj.noneItem.value = val; }
});
```

Thank you,
Andrew
