### ISSUE TITLE
Add IsRequiredIf like VisibleIf

### ISSUE THREAD

**Issue by luca76** [surveyjs/survey-library#546]
Hi, 

it would be useful to add an IsRequiredIf like VisibleIf.

For example, I have a combo box for cadastral type that with specified values makes some or none further fields required.

**Comment by andrewtelnov** [comment]
@luca76 Do you have many of those fields? I understand your scenario, I just want to know how often you need it. You may use onValueChange event for now.

Thank you,
Andrew

**Comment by luca76** [comment]
Ah, ok, onValueChange can be useful :-) Thank you!

**Comment by andrewtelnov** [comment]
@luca76 We have question.ifRequired now. It was introduced about a year ago.

Thank you,
Andrew
