### ISSUE TITLE
Boolean in radio mode not selected when having a custom True and False value

### ISSUE THREAD

**Issue by PixelDonut** [surveyjs/survey-library#5471]
### Are you requesting a feature, reporting a bug or asking a question?
Bug report

### What is the current behavior?
When de element type boolean is radio mode (when the screen is to small to show the slider) it doesn't show whether it is selected when you have a custom valueTrue and valueFalse

<img width="235" alt="image" src="https://user-images.githubusercontent.com/49429676/211508600-b89d461a-0edb-4335-9236-11865d5df2fd.png">

### What is the expected behavior?
That the selected item shows that it is selected:

<img width="235" alt="image" src="https://user-images.githubusercontent.com/49429676/211508803-015a05f6-3c27-44c5-a3e4-50fcd3a6c597.png">

### How would you reproduce the current behavior (if this is a bug)?

By setting a custom value in the boolean element and having it shown as a radio group.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://plnkr.co/edit/vUSUNS6NfheubYuM

Test code

```
"elements": [
        {
            "type": "boolean",
            "title": "Boolean as radio",
            "labelTrue": "Yes",
            "labelFalse": "No" ,
            "valueTrue": 1,
            "valueFalse": 0,
            "renderAs": "radio"
        },{
            "type": "radiogroup",
            "name": "Radiogroup",
            "choices": [
              "No",
              "Yes"
            ]
          }]
```

### Specify your

* browser: Chrome
* browser version: 108.0.5359.124
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.9.67

**Comment by JaneSjs** [comment]
Hello @PixelDonut,
Thank you for reporting this issue. We'll handle it shortly.

**Comment by JaneSjs** [comment]
Hi @PixelDonut,
As an immediate solution, you can use string literals as `valueTrue` and `valueFalse` values (https://plnkr.co/edit/mxCR5yJWNFg9Puh4).
```
{
   "type": "boolean",
    "title": "Boolean as radio",
    "labelTrue": "Yes",
    "labelFalse": "No" ,
    "valueTrue": "1",
    "valueFalse": "0",
    "renderAs": "radio"
}
```

**Comment by PixelDonut** [comment]
Thank you, I'll have a look if this will work for our application.
