### ISSUE TITLE
Responsiveness not working in simple surveys

### ISSUE THREAD

**Issue by nico-hernandez** [surveyjs/survey-library#5473]
Dear community I come to you looking for tips in order to improve responsiveness of simple surveys, may be I forgot containers? Thanks.

### Are you requesting a feature, reporting a bug or asking a question?
Asking a question.

### What is the current behavior?
Trying some of the examples listed on the SurveyJS website, I found they aren't responsive at all (any display size).

### What is the expected behavior?
On mobile devices I'd expect responsive survey.

### How would you reproduce the current behavior (if this is a bug)?
Not a bug, but I attach the link to HTML and JS scripts of the examples

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
[https://surveyjs.io/form-library/examples/condition-cascade/jquery](url)

<img width="164" alt="surveyjs-screenshot" src="https://user-images.githubusercontent.com/62685164/211549384-3d907c3d-78a7-4d55-8d16-4b33da44c9ed.PNG">

### Specify your

* browser: Chrome 
* browser version: 108.0.5359.125 (Build oficial) (64 bits)
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: v1.9.67

**Comment by JaneSjs** [comment]
Hello @nico-hernandez,
Thank you for contacting us. I tested the demo you've shared: https://surveyjs.io/form-library/examples/condition-cascade/jquery. First, I opened it in a creator and switched to the Preview tab. I selected a mobile device and got the following result:
![image](https://user-images.githubusercontent.com/22372972/211618769-494c1ff9-8aee-4e1d-90d0-43ab734c6ce8.png)

The survey works just fine. Also, I tested it on my cellphone and also didn't notice any issue on a smaller screen.

Would you please elaborate on the issue? If possible, share a problematic survey JSON for research.

**Comment by JaneSjs** [comment]
For the record: the following screenshot was taken from my cellphone:
![Screenshot_20230110_201722_Chrome](https://user-images.githubusercontent.com/22372972/211619052-d3615796-8419-46f7-b112-d6086e1f7864.jpg)

**Comment by nico-hernandez** [comment]
After struggling I realized this line was missing in my HTML code <meta name="viewport" content="width=device-width"/>
That's all, now is responsive, thanks @JaneSjs
