### ISSUE TITLE
("ClearInvisibleValues":"onHiddenContainer") Survey data is not removed when questions are hidden. This happens in Survey-jQuery version 1.9.67.

### ISSUE THREAD

**Issue by NicolasKolumbic** [surveyjs/survey-library#5474]
### Are you requesting a feature, reporting a bug or asking a question?

I am reporting a bug, I see the problem carried over from "Survey-jquery 1.9.65".

### What is the current behavior?

When trying to submit a form, I notice that it keeps the fields that were previously filled in, but were later hidden.

### What is the expected behavior?

You should remove those values from "survey.data" when the fields are hidden by "visibleIf".

### Specify your

* browser: chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.9.67

**Comment by JaneSjs** [comment]
Hello @NicolasKolumbic,
I created an example and confirmed, that survey results (`survey.data`) doesn't contain a Boolean value, which is located on a hidden panel. Please check my results below.

Survey JSON:
```
export const json = {
  logoPosition: "right",
  pages: [
    {
      name: "page1",
      elements: [
        {
          type: "boolean",
          name: "pnlVisibilityFlag",
          title: "Hide Panel",
          defaultValue: "false"
        },
        {
          type: "panel",
          name: "panel1",
          elements: [
            {
              type: "boolean",
              name: "question1",
              defaultValue: "true"
            }
          ],
          visibleIf: "{pnlVisibilityFlag} = false"
        },
        {
          type: "text",
          name: "question2",
          defaultValue: "Test"
        }
      ]
    }
  ],
  clearInvisibleValues: "onHiddenContainer"
};
```
[Example](https://codesandbox.io/s/distracted-ramanujan-r24vr1?file=/src/json.js)

Test Results:
* A panel is visible:  
![image](https://user-images.githubusercontent.com/22372972/211599316-f8af481e-e682-4d3c-9948-c92b24bbad39.png)

Survey results contain three question answers:
   ```
{"pnlVisibilityFlag":false,"question2":"Test","question1":true}
```
* The panel is hidden:
![image](https://user-images.githubusercontent.com/22372972/211599439-43ba27ab-5f88-4702-ab02-cd7e891ef6ee.png)

Survey results contain two answers:
```
{"pnlVisibilityFlag":true,"question2":"Test"}
```
Would you please share a problematic survey JSON / example for investigation?
