### ISSUE TITLE
Comments: the showCommentArea property doesn't work for Boolean & matrices questions

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5479]
The `showCommentArea` should activate the Comment box. 
![image](https://user-images.githubusercontent.com/22372972/211794173-523f2cac-e900-4725-a94b-745e73bc87c1.png)
However, this doesn't work for Boolean questions: [example](https://codesandbox.io/s/sharp-hill-7yjb92).
![image](https://user-images.githubusercontent.com/22372972/211794047-930a3044-ce69-475b-90f3-129aed47d908.png)

**Comment by andrewtelnov** [comment]
@JaneSjs It doesn't work for boolean, matrices and panel dynamic question. I am going to fix the issue and add unit and e2e tests.

Thank you,
Andrew

**Comment by R-D-Vie** [comment]
As of 25.04.2023 I am still having similar issues to the above - the comment area is not showing up with the boolean question type:

![image](https://user-images.githubusercontent.com/76235546/236178464-90dc7a24-22b2-4436-8f12-1aeb83f35e14.png)
![image](https://user-images.githubusercontent.com/76235546/236178521-c9c3eea6-3bf5-4496-8ef7-88e3ab56b698.png)
