### ISSUE TITLE
A Radiogroup Question doesn't have a default value when the survey.data is preset

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5483]
[Example](https://plnkr.co/edit/hQWJRE0WaQhESQZ4).
A survey has the preconfigured data:
```
survey.data = {
        "question1": "No",
        "question2": "No"
}
```
Also, `question3` has the `visibleIf` expression and `defaultValue`:
```
{
     "type": "radiogroup",
     "name": "question3",
     "visibleIf": "({question1} = 'Yes') and ({question2} = 'Yes')",
     "startWithNewLine": false,
     "title": "Eligible",
     "defaultValue": "Item 1",
     "readOnly": true,
     "choices": [
      {
       "value": "Item 1",
       "text": "Yes"
      },
      {
       "value": "Item 2",
       "text": "No"
      }
     ]
}
```
To reproduce the issue, select Yes for question1 and question2. The question3 item appears, but it doesn't have a default value.
![image](https://user-images.githubusercontent.com/22372972/211991174-a35470eb-c534-47b6-8a1d-33a7f442feee.png)

Source ticket: [T11715 - Variable Logic](https://surveyjs.answerdesk.io/internal/ticket/details/T11715).

**Comment by andrewtelnov** [comment]
[survey.mergeData](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#mergeData) function should be used, instead of survey.data.

Thank you,
Andrew

**Comment by vinod-amt** [comment]
> [survey.mergeData](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#mergeData) function should be used, instead of survey.data.
> 
> Thank you, Andrew

so , u r saying we should mergeData even though it is first time assignment of data. and in the given plunkr example, if we replace "survey.data" with "survey.mergeData" it is not even working.
