### ISSUE TITLE
TagBox Issues

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#5487]
- [ ] font must be bold

![Image](https://user-images.githubusercontent.com/17025812/211831621-dd2792fa-93ac-4ee4-9119-657f5650bad8.png)

- [ ] surveyjs/survey-creator#3782

![Image](https://user-images.githubusercontent.com/17025812/211831639-ff456697-7f56-4484-9615-160130e16dbd.png)

**Comment by OlgaLarina** [comment]
The second point is https://github.com/surveyjs/survey-creator/issues/3781

**Comment by novikov82** [comment]
It is not released yet and should work on test site.

С уважением,
Алексей Новиков



чт, 26 янв. 2023 г. в 19:25, mikeamelin ***@***.***>:
