### ISSUE TITLE
How hide buttons in certain pages in the progress bar

### ISSUE THREAD

**Issue by nediazc** [surveyjs/survey-library#5493]
Hello

it's possible not show the buttons in all the pages in the progress bar.
The idea is not overwhelm the user, because I have 15 pages in the survey
I just want show the button in certain pages(like sections in the survey).
If the user press button, just go to the page where the navigationTitle was placed
I guess another person had the same concern than me in this issue: https://github.com/surveyjs/survey-library/issues/443
but not sure

Regards

**Comment by andrewtelnov** [comment]
@nediazc We are going to implement TOC (table of content) navigation on the left/right. At first as example and later include it into the library. We are starting to work on it. It should solve your issue.

Thank you,
Andrew

**Comment by nediazc** [comment]
> TOC (table of co

Thanks @andrewtelnov

**Comment by tsv2013** [comment]
We've implemented TOC navigation out-of-the box. You can turn it on via the "showTOC" survey property or survey configuration option. It will be available in the nearest minor updates (most likely this next week).
