### ISSUE TITLE
Ranking - Add an option to drag and drop items using a container icon (six dot icon) only

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5501]
Original Issue: [T11678 - Ranking Drag And Drop](https://surveyjs.answerdesk.io/internal/ticket/details/T11678).

Currently, it is possible to drag and drop Rakning items by clicking an item area:
![2023-01-16_9-33-16](https://user-images.githubusercontent.com/22372972/212612983-d094f207-45b8-45d5-b11d-52fc494aec8e.gif)

If items have links, clicking a ranking item for reordering may activate a link.

Suggestion: add another drag and drop mode and allow users to select an item by using an item container button only:
![image](https://user-images.githubusercontent.com/22372972/212613267-faace22e-69bf-4dd1-b32b-2678d333574f.png)

**Comment by andrewtelnov** [comment]
@dmitrykurmanov Please add an option into survey settings
