### ISSUE TITLE
Image Picker Issues

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#5504]
- [ ] last item's name editing  –> enter

![Image](https://user-images.githubusercontent.com/17025812/212629130-8b3426d1-8f32-4b9f-9e66-663c5715165a.png)

- [ ] logic. Impossible to select item (milty-select)

![Image](https://user-images.githubusercontent.com/17025812/212629348-c103855e-36fc-4c0a-b752-33e8a4326711.png)

- [ ] double click doesn't work to select text

![Image](https://user-images.githubusercontent.com/17025812/212629459-7a9c9a50-603c-42da-b30c-58cf26dc4e1a.png)

- [ ] default image name remains after new image's loaded

![Image](https://user-images.githubusercontent.com/17025812/212629807-bf01c2c2-ded0-4d76-b853-1ae4dd3037fb.png)

**Comment by novikov82** [comment]
1-3 can not be reproduced
4 transformed to https://github.com/surveyjs/survey-creator/issues/3814
