### ISSUE TITLE
The 'Cannot read properties of undefined (reading 'add')' error is thrown on an attempt to add a callback function for the survey.onQuestionVisibleChanged event

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5513]
A compiler throws the following error on an attempt to subscribe to the [survey.onQuestionVisibleChanged](https://github.com/surveyjs/survey-library/blob/master/src/survey.ts#L329) event:

**Cannot read properties of undefined (reading 'add')**

```
survey.onQuestionVisibleChanged.add(function (sender, options) {
  //...
});
```
[Example](https://codesandbox.io/s/long-wind-qek6x1?file=/src/SurveyComponent.jsx:315-488).

Source ticket: [T11761 - "Clear values on hidden" is not working on dynamic panel](https://surveyjs.answerdesk.io/internal/ticket/details/T11761).

**Comment by andrewtelnov** [comment]
@JaneSjs The event is not in the released version yet. It will be available in v1.9.69. Here is [the related issue](https://github.com/surveyjs/survey-library/issues/5381).

Thank you,
Andrew
