### ISSUE TITLE
SurveyBootstrapMaterial is not defined

### ISSUE THREAD

**Issue by jerome-lemaire** [surveyjs/survey-library#5517]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### How would you reproduce the current behavior (if this is a bug)?
Go to the page https://surveyjs.io/form-library/examples/bootstrap-material-theme/jquery and click "Edit in CodeSandbox" button

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codesandbox.io/s/gfullq

Test code

```
SurveyBootstrapMaterial.defaultCss.navigationButton = "btn btn-green";
SurveyBootstrapMaterial.defaultCss.rating.item = "btn btn-default my-rating";
```

### Specify your

* browser: edge
* browser version: 108.0.1462.76
* surveyjs platform: jquery
* surveyjs version: latest

**Comment by andrewtelnov** [comment]
@OlgaLarina "defaultCss" is not found in "survey-jquery/plugins/...". I tried it in v1.9.70
