### ISSUE TITLE
`choicesFromQuestion` in composite question

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#5519]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
`choicesFromQuestion` seems not to work in a composite question. The goal is to have 1 composite question with 2 elements. 
The first question in the composite is multiple choice and the second question is a single choices with options from the first.

### What is the expected behavior?
`choicesFromQuestion` should work with the notation `composite.abc`.

### How would you reproduce the current behavior (if this is a bug)?
```js
Survey.ComponentCollection.Instance.add({
    iconName: 'icon-language',
    name: 'platformlanguagepicker',
    title: 'Platform language picker',
    elementsJSON: [
        {
          name: 'languages',
          type: 'checkbox',
          title: 'Languages for this project',
          choices: localeChoices
        },
        {
          name: 'defaultlanguage',
          type: 'dropdown',
          title: 'Primary language for this project',
          choicesFromQuestion: 'composite.languages',
          choicesFromQuestionMode: "selected"
        }
    ],
    onInit () {
      console.log('oninit');
      // debugger;
    },

  });
```

### Workaround
Duplicate choices for both questions, use `choicesVisibleIf` to hide unselected choices.

**Comment by SamMousa** [comment]
Please don't rush an implementation on my account. (in my opinion) We should decide some syntax on placeholders first instead of my proposes `composite.xyz`, since `composite` is also a perfectly valid question name.

See #5522

**Comment by andrewtelnov** [comment]
@SamMousa It has been implemented in [this issue](https://github.com/surveyjs/survey-library/issues/5547),
I decided do not add any prefix like "composite.". We don't have it for now. You can use the question name directly. If it could find in the content panel, then it will look in the survey.
You JSON will be: `choicesFromQuestion: 'languages',`.

Thank you,
Andrew
