### ISSUE TITLE
Proper question name validation

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#5522]
### Are you requesting a feature, reporting a bug or asking a question?
Currently any string is a valid value for a question name, however in https://github.com/surveyjs/survey-library/issues/4918 a sort of fix was applied to remove the '#' if it was the start of a question name.

First of all this fix doesn't really work, it removes the first character, however entering a name like `###abc` still creates such a bad question name.

### What is the current behavior?
- No real documentation on what is valid

### What is the expected behavior?
Question names should be treated like variable names; they are used in expressions in multiple places and having a clear syntax for them helps survey creators create better surveys.

I propose picking a standard variable naming convention like:
- Names can contain letters, digits, underscores and unicode characters
- Names must not begin with a digit
- Names are case sensitive

This is a break in backwards compatibility, but it probably (no reference data on this, just a feeling) won't affect many users.

Advantage of such a syntax is that we can easily validate it using a regex instead of magically fixing it like was done in #4918.

Regex for proposed syntax: `^[a-zA-Z][\w\d_]*$`.

### Advantages
- Makes the JSON result object easier to read
- Makes expressions easier to parse
- Reduces chance for weird conversions when going between languages: 

```php
echo json_encode(json_decode('{"0": "a"}', true));
// ["a"]
```
- Allows for clean implementation of custom syntax, like `#` for suppressing type jungling #4918 
- Or `$` for identifying the result object root (#5521)
- Or `.` for identifying a subkey.

**Comment by JaneSjs** [comment]
Hello @SamMousa,
Thank you for your input. We'll review your suggestions and get back shortly.

**Comment by SamMousa** [comment]
I think you misunderstood; this is more about the library validating its own configuration and imposing some sane defaults.
Take for example the issue I mentioned in the original post regarding question names starting with a `#`. 
It is inclear what are allowed characters for question names; the library will happily run this survey JSON:
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "rating",
     "name": "#rating"
    },
    {
     "type": "expression",
     "name": "question1",
     "expression": "{#rating}+10\n"
    }
   ]
  }
 ]
}
```
But it will not work due to #4918. The issue is in the way the bug has been "fixed": it just fixes one way of editing the survey JSON.

I propose instead defining from the project the valid names for variables used inside surveys. That is the only way to properly handle reserved names.

Take this example https://surveyjs.io/form-library/examples/condition-matrixdropdownvisibleif/reactjs#content-code.
It contains this logic: 
```js
{
      "rowsVisibleIf": "{car} contains {item}",
}
```
Clearly, `{item}` refers to a reserved name for a matrixdropdown question. What would happens if I have another question actually named `item`? 
If I copy the JSON from the example linked above and go into the question editor and change the name of the `car` question to `item`, it will also update the condition to read: `{item} contains {item}`. Not unexpectedly, this won't work very well...

So what I'm proposing is fixing a bug in the library, I'm aware of how I can work around it, that's not the point; why should you not want to fix this in the library itself?

**Comment by SamMousa** [comment]
Make name valid is not validation. If i load Json that is invalid I expect an exception not a silently altered data model and no obvious way to detect the break.

Why not throw an error in the survey model constructor if the given Json is in fact not a valid survey structure? (Or at the very least provide a validate function so Devs can call that manually)

**Comment by andrewtelnov** [comment]
@SamMousa We can't throw error, we can write a message into console log.

Thank you,
Andrew

**Comment by SamMousa** [comment]
What about introducing a validation function then? Writing in a console log doesn't help for forms that are created while in production. .

**Comment by andrewtelnov** [comment]
@SamMousa I can add a callback function into settings. It is not empty, it will pass a original value, corrected value (it can be equal to original value) and you will have to return the value that will be applied.

Thank you,
Andrew

**Comment by SamMousa** [comment]
This means we'll have to alter the JSON to inject our callback. Also the survey then is no longer JSON, but javascript.
```js
Survey
    .StylesManager
    .applyTheme("defaultV2");

// This is supplied by a user, it may or may not be valid.
const surveyJson = {
    elements: [{
        name: "FirstName",
        title: "Enter your first name:",
        type: "text"
    }, {
        name: "LastName",
        title: "Enter your last name:",
        type: "text"
    }]
};

// I expect an exception here, I'm not sure why you wouldn't want an exception if something is invalid...
const survey = new Survey.Model(surveyJson);

// If you insist on not changing the existing code what about just introducing a new constructor instead of tacking on extra options / parameters?
const survey2 = new LiteralSurvey.Model(surveyJson);

// This way consuming code can deal with unexpected errors cleanly.


```

In general it is currently very unclear how error handling is done, or what errors are magically fixed. For example when using an undefined question type it is silently ignored, again leaving no way for the calling code to detect something (big) is wrong.

Rather than fix this specific case, I'd like a more documented point of view from you detailing how consuming code is supposed to verify that given configuration is valid.

It feels like currently the only way to "hack" it together is to call the constructor and save it to JSON and then compare that to the original JSON. If that is really the way to do to it, then I can accept that...
But then it should be documented (and become part of the backward compatibility promise, which currently it doesn't need to be). 
I imagine things like the recently renamed fields (like `hasOther`) will also cause the above method to detect errors to detect false positives, because here in fact both field names are valid...

**Comment by andrewtelnov** [comment]
@SamMousa you can use [survey.jsonErrors](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#jsonErrors)
Regarding callback function, I was talking about the following code:
```js
Survey.settings.onQuestionNameValidation = (name, correctedName) => {
  if(name !== correctedName) {
   //the name has been changed, do something
  }
  //You can change the name here.
  return correctedName;
};
```

Thank you,
Andrew

**Comment by SamMousa** [comment]
Hmm, `jsonErrors` will work when fulling loading the survey JSON. Thanks!

Regarding the question name validation I think we're still not solving the same problem. I'm not looking to add specific fixes or constraints there.
I'm just trying to get the SurveyJS core to be clear about existing constraints that are not explicitly enforced.
Like:
- Do not start a question name with `#` (it is half-fixed in the editor which automatically removes it, sometimes)
- Do not call a question `item` since it will collide with `rowsVisibleIf` logic


The idea here is that since question names are used as variables they should follow some naming convention (again i'm not looking to impose one of my own, but looking for a stance from SurveyJS core).

Additional constraints that you might want to adopt to enforce good clean code in your survey JSON could be things like:
- Question names must start with a letter



The only real question name validation that is currently done is the duplicate:
![image](https://user-images.githubusercontent.com/547021/231455629-319adae5-99eb-4cb7-953b-6aed0254ae8d.png)

In my opinion all validation should happen like that:
- _Name must not start with #_
- _item is not a valid name_

That is a way cleaner approach then fixing things magically while someone is typing.

**Comment by andrewtelnov** [comment]
@SamMousa I don't disagree that it would be nice. Let me think. I will comeback to you.

Thank you,
Andrew
