### ISSUE TITLE
Modern Theme - Radiogroup items are displayed in a single column regardless of the colCount property value

### ISSUE THREAD

**Issue by oliverboorman1** [surveyjs/survey-library#5524]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
Between SurveyJS v1.9.65 and v1.9.66, the CSS styling that is used to display radio buttons inline appears to have broken for the modern theme. Since v1.9.66, the radio buttons of a radio group with colCount = 2 are displayed vertically, not in columns.

### What is the expected behavior?
The radio buttons of a radio group with colCount >1  are displayed horizontally in columns. This was working as expected in v1.9.65.

### How would you reproduce the current behavior (if this is a bug)?
See https://codesandbox.io/s/trusting-bash-mg5j5h for a minimal example.

Despite the radiogroup being configured to have colCount = 2, the radio button are displayed vertically, not in two horizontal columns.

### Specify your

* browser: Chrome
* browser version: 109
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: v1.9.66 onwards

**Comment by JaneSjs** [comment]
Hello @oliverboorman1,
Thank you for reporting this issue. We will research it and let you know our results.
