### ISSUE TITLE
standard-version is deprecated

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#5528]
### Are you requesting a feature, reporting a bug or asking a question?
Bug?

![image](https://user-images.githubusercontent.com/547021/213183135-6204f4ae-d61b-4eba-8cab-ffe76438b7db.png)

https://www.npmjs.com/package/standard-version

Edit: part of #5316

**Comment by tsv2013** [comment]
We need to take in account these threads:
https://github.com/conventional-changelog/standard-version/pull/907
https://github.com/conventional-changelog/standard-version/issues/919

We'll try to switch to https://github.com/absolute-version/commit-and-tag-version
