### ISSUE TITLE
Generate JSON Schema- Survey Model 

### ISSUE THREAD

**Issue by nehemiah-tzur** [surveyjs/survey-library#5544]
### Are you requesting a feature, reporting a bug or asking a question?

Feature request

### What is the current behavior?

There is no way to currently get the JSON schema for a survey,

### What is the expected behavior?

It would be nice if there was a method for generating a JSON schema for a survey model. This way you can validate schema's on the backend that might have been tampered with.

### How would you reproduce the current behavior (if this is a bug)?

n/a.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

none

Test code

### Specify your

* browser: any
* browser version: any
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: any
any

**Comment by andrewtelnov** [comment]
@nehemiah-tzur In fact, we have this code. I will include JSON scheme generation together with our docs documentation.

Thank you,
Andrew

**Comment by nehemiah-tzur** [comment]
I actually meant a JSON schema for the results not the survey code.

**Comment by andrewtelnov** [comment]
@nehemiah-tzur Here is [the doc](https://surveyjs.io/form-library/documentation/handle-survey-results-access#access-full-survey-results) for it.

Thank you,
Andrew
