### ISSUE TITLE
Implement TOC navigation

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-library#5551]
Survey navigation/Table Of Contents panel helps survey respondents go through a survey and directly access a required questionnaire item. It is especially useful for large surveys: when there are a lot of questions in a questionnaire. With a navigation bar, respondents can easier access questions and have greater control over the flow.

Currently, SurveyJS has the following navigation options: 
* Button navigation (for small surveys)
https://surveyjs.io/form-library/examples/navigation-buttons/reactjs
* Custom navigation: an example on how to implement a drop-down menu with a question list for easier navigation (for example, for large surveys).
https://surveyjs.io/form-library/examples/survey-customnavigation/reactjs

**Suggestion**: implement a left-side panel / a sidebar navigation.
***
Customer requests:
* The Left-Side Navigation Panel 
   - [T10046 - Navigation Placement](https://surveyjs.answerdesk.io/internal/ticket/details/T10046)
_design the navigation on left in surveyjs?_
   - [T11738 - Need to show survey in Preview mode only](https://surveyjs.answerdesk.io/internal/ticket/details/T11738)
   _page navigation buttons_
* An External Page Selector to Navigate to a Specific Page
   - [T10404 - How to setup an external PageSelector for a Multi-page Survey](https://surveyjs.answerdesk.io/internal/ticket/details/T10404)
   - [T386 - Is there a way to jump directly to a survey page?](https://surveyjs.answerdesk.io/internal/ticket/details/t386)
* In PDF - Question Titles in the Header, clicking a title navigates to the question.
   - [Table of Contents for easier navigation](https://github.com/surveyjs/survey-pdf/issues/147)
_having the question titles in the header and when you click on the title it takes you to the individual question in the pdf (with a large number of questions it would make it easier to check the pdf)_
***

Third-party alternatives
* A Sidebar

https://www.qualtrics.com/support/survey-platform/survey-module/survey-flow/advanced-elements/table-of-contents/

![Image](https://user-images.githubusercontent.com/22372972/209665788-dc7a49e2-1d7a-4149-81e3-a2ce0a86a792.png)

See also the internal issue - https://github.com/surveyjs/service/issues/702

**Comment by JaneSjs** [comment]
Consider supporting TOC out of the box: currently, no support on small screens.
Customer feedback from [T10404 - How to setup an external PageSelector for a Multi-page Survey](https://surveyjs.answerdesk.io/internal/ticket/details/T10404).
![image](https://user-images.githubusercontent.com/22372972/214849569-4a46599b-5fc5-4f8f-9d80-23171c0045b0.png)

**Comment by tsv2013** [comment]
Adaptivity design -
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=15839%3A137655&t=mSumhDwpJhmebUFc-4
