### ISSUE TITLE
Dropdown: The drop-down menu should have the same width as the input field

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-library#5555]
https://surveyjs.io/form-library/examples/create-dropdown-menu-in-javascript/reactjs

![image](https://user-images.githubusercontent.com/18551316/214240959-a62f9195-f3cb-4ba5-9d19-ff1645d4ed29.png)

**Comment by novikov82** [comment]
fixed with https://github.com/surveyjs/service/commit/e230a808100da12a1e7e37976c37d5ca597c227b
