### ISSUE TITLE
Customize data saving feedback

### ISSUE THREAD

**Issue by tillsanders** [surveyjs/survey-library#5556]
### Feature

Currently, when using the hooks `showDataSaving(), `showDataSavingError()` and `showDataSavingSuccess()`, there is no easy way to customize the appearance of these messages. I would like to have a class or ID to target these elements using CSS.

### What is the current behavior?

Currently, the HTML output when using these functions looks somewhat like this:

```html
<div data-bind="visible: completedState != '', css: css.saveData.root" style="">
  <div data-bind="css: completedStateCss">
    <span data-bind="text:completedStateText">CUSTOM TEXT</span>
    <input type="button" data-bind="visible: completedState == 'error', value: getLocalizationString('saveAgainButton'), click: doComplete, css: css.saveData.saveAgainButton" value="CUSTOM TEXT" style="">
  </div>
</div>
```

As you can see, there is not a single class or ID we can use to customize the appearance. This is crucial however, since an error message at this stage needs to be highlighted in some way or the users will miss it.

**Comment by JaneSjs** [comment]
Hello @tillsanders,
Thank you for contacting us. We've handled this issue in the scope of the following thread: https://github.com/surveyjs/survey-library/issues/5357. In particular, we've added the `sv-save-data_error`, and `sv-save-data_success` CSS classes. You can review a list of newly added CSS classes [here](https://github.com/surveyjs/survey-library/pull/5530/files#diff-2a79723519e19ad6cc3d5a94379a12f8bb17c8e022cc285e30ce49174aa62831R1).
New classes will be available with the next minor update. It is scheduled for a day or so.

Please feel free to test this functionality and let us know if you have any questions.

Thanks
