### ISSUE TITLE
Is it necessary to buy license if only needs to create forms without any other service ?

### ISSUE THREAD

**Issue by Fred-QS** [surveyjs/survey-library#5588]
The bottom banner after html integration tells to buy license for use Survey in my app, but I can't see any information in documentation about integrating any API key or else to unlock my integration.
I only need the creator without any other service.
Do I need to buy a license ?
If yes, how to declare it in my integration code ?
![Capture d’écran 2023-01-29 à 21 25 00](https://user-images.githubusercontent.com/66546741/215353926-5fd19052-429b-4962-9763-47b2f75acbf4.png)

**Comment by andrewtelnov** [comment]
@Fred-QS SurveyJS Library, a JavaScript form library, is under MIT license and you can do with it whatever you want.
You are showing SurveyJS Creator. It is another library. It allows to build surveys/forms visually for non-developers. You need a developer license to use it in your applications. I believe our [price page](https://surveyjs.io/pricing) shows it.
Please let us know if you have other questions.

Thank you,
Andrew
