### ISSUE TITLE
No enough room for title (matrix)

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#5590]
![Image](https://user-images.githubusercontent.com/17025812/215513301-1c6ea6a1-4739-4484-b5b8-f93ae1581d24.png)

**Comment by JaneSjs** [comment]
Source ticket: [T11885 - Custom UI Questionnaire](https://surveyjs.answerdesk.io/internal/ticket/details/T11885)

**Comment by novikov82** [comment]
https://github.com/surveyjs/survey-library/pull/4644/files#diff-f1a7fd029df5a83eb015f8b3bf500361a458b5764b5cc3b51b418515615543d5

**Comment by novikov82** [comment]
@mikeamelin can you check if it is fixed already?

**Comment by mikeamelin** [comment]
I'm not sure about fixed. But I just don't know how it was. I've tried and don't see the issue for now... with default settings.

![Screenshot 2023-11-24 at 10 08 31](https://github.com/surveyjs/survey-library/assets/17025812/06fc130c-d61a-4851-939b-2cdadd47cb95)
