### ISSUE TITLE
Safary only: Matrix dynamic doesn't work correctly on iPad with allowRowsDragAndDrop option

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#5592]
The following JSON doesn't work well on iPad:
```js
{
     "type": "matrixdynamic",
     "name": "question",
     "columns": [
      {
       "name": "col1",
       "cellType": "comment"
      }
     ],
     "allowRemoveRows": false,
     "rowCount": 3,
     "allowRowsDragAndDrop": true
}
```
[Source ticket](https://surveyjs.answerdesk.io/internal/ticket/details/T11894).

**Comment by dmitrykurmanov** [comment]
demo CodeSandbox: https://codesandbox.io/s/vibrant-microservice-75phht?file=/src/json.js
demo Plunker: https://plnkr.co/edit/stbEXfLqQ4hmO4El

**Comment by dmitrykurmanov** [comment]
can't reproduced on Ipad with IOS 16.2

**Comment by dmitrykurmanov** [comment]
after the investigation, I've realized that we need to implement the `longTap` functionality for matrices like in the ranking questions
