### ISSUE TITLE
Copy choices not bringing "Other" text

### ISSUE THREAD

**Issue by rudyp321** [surveyjs/survey-library#5611]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
When you have a check box group whose choices are loaded from the choices selected on a previous question, if the user selects the "Other" option and enters text, that text is not copied over to the new question.

### What is the expected behavior?
The text that was entered when "Other" was selected should be displayed among the list of options.

### How would you reproduce the current behavior (if this is a bug)?

1. Define a question of type "checkbox" with the Other option available.  
2. Define another question of type checkbox whose choices will come from the selected choices in the first question.  
3. Start survey
4. Select "Other" and enter some text for the first checkbox question
5. Proceed to the next checkbox question

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@rudyp321 Please review [the following example](https://plnkr.co/edit/v7xkBbnJUFti4EKe). It works as expected.

Thank you,
Andrew

**Comment by rudyp321** [comment]
It seems to work when the second question is of type ranking and not
checkbox.

**Comment by JaneSjs** [comment]
Hello @rudyp321,
I updated that sample and used the Checkbox question as a second question: https://plnkr.co/edit/idx1Kmj6q4qQZMET.
It works as expected.
https://user-images.githubusercontent.com/22372972/218430799-c7f17a5f-f26d-4d29-a643-f734e3b88648.mp4

Please check how it works on your side. 

If you have any questions or require further assistance, please feel free to reactivate this thread.

**Comment by rudyp321** [comment]
Hello @JaneSjs , 

You did not select "Other".  If you select "Other" and enter text, that text does not carry over to the second question. That's the issue I'm reporting.  It works otherwise, and also seems to work if the second question is of type "ranking".  See video below.

[Recording-20230213_082128.webm](https://user-images.githubusercontent.com/2546816/218470216-d87537ca-aad7-42bc-97de-709716c37b04.webm)

**Comment by andrewtelnov** [comment]
@rudyp321 The issue has been fixed by the PR above.

Thank you,
Andrew

**Comment by rudyp321** [comment]
Thank you very much, @andrewtelnov .  Any idea when this fix will be part of a release?

**Comment by andrewtelnov** [comment]
@rudyp321 PR is green. Somebody should merge it. I beleive the fix will be avaiable in the next release.

Thank you,
Andrew
