### ISSUE TITLE
Render "select" element for dropdown lists instead of "input" + popup

### ISSUE THREAD

**Issue by daveylad** [surveyjs/survey-library#5627]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
Default rendering for a dropdown list is "input/text" with a popup for list items 

### What is the ~~expected~~ DESIRED behavior?
Render the dropdown as a traditional "select" element with "options"

Are there any options/settings/work arounds to prevent the default behaviour and revert to the "select" element for dropdown lists?

### Specify your

* browser: All
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version: jquery 1.9.71

**Comment by JaneSjs** [comment]
Hi @daveylad,
If wish to replace the built-in [Dropdown Menu question](https://surveyjs.io/form-library/examples/create-dropdown-menu-in-javascript/reactjs) with an HTML <select> tag, set the Dropdown's `renderAs` property to `select`.
```json{7}
{
      "type": "dropdown",
      "name": "car",
      "title": "Which is the brand of your car?",
      "isRequired": true,
      "showNoneItem": true,
      "showOtherItem": true,
      "renderAs": "select",
      "choices": [ "Ford", "Vauxhall", "Volkswagen", "Nissan", "Audi", "Mercedes-Benz", "BMW", "Peugeot", "Toyota", "Citroen" ]
}
```
[Example](https://plnkr.co/edit/uOucV2hwthiP4HUq).

Please feel free to reactivate this thread if you have any questions or require further assistance.
