### ISSUE TITLE
survey-angular.d.ts Error

### ISSUE THREAD

**Issue by Neeraja-Reddy-1** [surveyjs/survey-library#5628]
Getting survey-angular.d.ts file error.
![image](https://user-images.githubusercontent.com/93314191/217524431-3ec86957-6187-45c7-a3f9-58ea53422e93.png)

Here is the tsconfig.json file
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "resolveJsonModule": true,
    "importHelpers": true,
    "types": []
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  // "exclude": [
  //   "node_modules/**/*.d.ts"
  // ],
  "include": [
    "src/**/*.d.ts",
    "node_modules"
  ],
  "exclude": [
    "node_modules/**/*.d.ts",
    "node_modules/**/*.ts",
    "node_modules/survey-angular/survey.angular.d.ts"
  ] ,
  "jsx": "react"
}

**Comment by JaneSjs** [comment]
Hi @Neeraja-Reddy-1,
Thank you for contacting us. In a recent question, we've updated typings in our survey-angular library. Now, you may require to upgrade your TypeScript version to v4.4.4 or newer. For the record: we are currently researching ways to support an older TypeScript versions as well and help customers to easily migrate to a new SurveyJS Angular version. You may wish to subscribe to the following thread to receive further notifications in this regard: https://github.com/surveyjs/survey-library/issues/5636.

Drop me a line if you have any questions.

**Comment by JaneSjs** [comment]
Hello @Neeraja-Reddy-1,
With the most recent version (v1.9.74), the survey-angular library should perform well with Angular 10.

Our developers fixed the issue: [Angular - Build errors in survey-angular library](https://github.com/surveyjs/survey-library/issues/5636). I've just tested the survey-angular library with Angular 8 and TypeScript 3.5.3 and confirmed that everything runs correctly.

Please upgrade the SurveyJS library to the latest version v1.9.74 and test how the survey-angular performs in your Angular 10 application.

Should you have any questions or require further assistance, we are here to help.
