### ISSUE TITLE
Github Tag 1.9.72 missing 

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/survey-library#5642]
> According to the Whatsnew Page is a new Version "released" 1.9.72. It seems that the Tag 1.9.72 for the survey library branch is missing. Pls add the Tag when you are ready for the release of this version, thx!

based on https://surveyjs.answerdesk.io/ticket/details/T12008

**Comment by tsv2013** [comment]
Fixed via the https://github.com/surveyjs/service/commit/651b1cc7dcd74405fe9684f9269d37f6f0f84f47 commit
