### ISSUE TITLE
When questions use the same valueName, the question.setNewValue function doesn't update values of another question

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5650]
I have a Panel Dynamic and a custom question which have the same `valueName: "Codes"`. The `question.setNewValue(result)` function successfully initializes values for the Panel Dynamic question, however, it doesn't _reset_ values on subsequent calls.

An example is available in the following ticket: [T12027 - Dynamic panel values not updating](https://surveyjs.answerdesk.io/internal/ticket/details/T12027)

**Comment by andrewtelnov** [comment]
It works with the following code:
```js
question.clearValue();
question.value = result;
```

Thank you,
Andrew
