### ISSUE TITLE
core.js:6014 ERROR TypeError: Unable to process binding "template: function(){return { name:'survey-content'}" Message: Cannot read properties of undefined (reading 'fire')     at SurveyLiveTester.koEventAfterRender

### ISSUE THREAD

**Issue by xokaer** [surveyjs/survey-library#5652]
I dragged the date question and got the date properties on the right side. But when I click on preview, it throws me error. 

![Image](https://user-images.githubusercontent.com/105218396/218423392-0835ab4a-8881-48df-8b81-72b5b40c9ba1.png)

**Comment by JaneSjs** [comment]
Hello @xokaer,
Please clarify which date question you're talking about and the SurveyJS Library Version. If possible, share a problematic example reproducing the issue.

**Comment by xokaer** [comment]
I Added Amharic Calander date picker library in angular surveyjseditor on angular 8 and start to serve the project and the form is displayed on form builder and drag the amharic date picker quastion but if I test the review or previews it is not display survey complete form fill

**Comment by JaneSjs** [comment]
Hello @xokaer,
Please accept my apologies for the delayed reply. It appears that you use an outdated version of SurveyJS Form Library. Please upgrade to the most recent SurveyJS Form Library v1.11.2. An Angular integration guide is available at [Angular Form Library](https://surveyjs.io/form-library/documentation/get-started-angular).

Should you have any further questions, please feel free to submit another GitHub issue.

Thanks
