### ISSUE TITLE
surveyjs-widgets is not working anymore since 1.9.67 version

### ISSUE THREAD

**Issue by stsiushkevich** [surveyjs/survey-library#5654]
A noticed after updating to 1.9.72, that my prettycheckbox widgets are broken. After experimenting with various versions I discovered that there is an issue in survey-react sinse 1.9.67. The verstion 1.9.66 works fine. You can test it in any sandbox, please note that in HTML markup no any "pretty" CSS class anymore.

**Comment by stsiushkevich** [comment]
Select is broken too

**Comment by JaneSjs** [comment]
Thank you for reporting this issue, @stsiushkevich. We will check it and let you know our results.

**Comment by andrewtelnov** [comment]
@stsiushkevich It is fixed in [this issue](https://github.com/surveyjs/survey-library/issues/5198).

Thank you,
Andrew
