### ISSUE TITLE
servey-widgets prettycheckbox is broken in Matrix

### ISSUE THREAD

**Issue by stsiushkevich** [surveyjs/survey-library#5656]
When I updated from 1.9.26 to newer version I noticed, that my matrix styles are broken:

Before (1.9.26):
![image](https://user-images.githubusercontent.com/12151060/218458085-b40d030c-afe5-4559-8011-724e2969f553.png)
Markup:
![image](https://user-images.githubusercontent.com/12151060/218458221-f661adca-c9a3-4a25-9999-0efa318bfb80.png)
After update:
![image](https://user-images.githubusercontent.com/12151060/218458402-a7e5112e-e229-4d36-8c77-9edb1e632627.png)
Murkup:
![image](https://user-images.githubusercontent.com/12151060/218458637-627e55ce-ffde-416e-b6a2-4755187a29eb.png)

prettycheckbox is not working anymore. I discovered that an issue started from 1.9.28 to latest version. You can test it on any sandbox.

**Comment by andrewtelnov** [comment]
@stsiushkevich Yes, we removed this spans. I checked the code for pretty checkbox and I could not find code related with matrix.
What JavaScript platform do you use? You can likely achieve your task without using pretty checkbox at all. You can override a radiogroup rendering directly now. Here is [the example](https://surveyjs.io/form-library/examples/add-custom-items-to-radio-button-group/reactjs).

Thank you,
Andrew
