### ISSUE TITLE
After completing the survey how to restart the survey again

### ISSUE THREAD

**Issue by OshaniSilva** [surveyjs/survey-library#5658]
### What is the current behavior?

Currently I'm having a complex survey with multiple pages. Once it has been completed I cannot restart the survey unless I refresh the page. Image is given below.

![image](https://user-images.githubusercontent.com/26425777/218464103-10c718c0-eb22-4f5b-8f36-9af901600f90.png)

### What is the expected behavior?

Is there a way to add a restart survey button or have another solution for this? Could you please provide an example.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by JaneSjs** [comment]
Hello @OshaniSilva,
To restart a survey, call the [survey.clear](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#clear) function. The function clears survey data and state. If the survey has a completed state, it will be started again.

If you wish to restart a survey once it's completed, subscribe to the `survey.onComplete` function and run the following code.
```
survey.onComplete.add(function (sender) {
  // Access survey results from `sender.data`
  //  Send survey results to your server (https://surveyjs.io/form-library/documentation/handle-survey-results-store)
  // Clear survey results and state to restart the survey
  sender.clear();
});
```
I hope this helps. Please feel free to reactivate this thread if you have any questions or require further assistance.
