### ISSUE TITLE
Accessing data and questions asked after survey completion

### ISSUE THREAD

**Issue by OshaniSilva** [surveyjs/survey-library#5661]
### What is the current behavior?

After completing the survey when accessing the data provided by the user I get it in the format below. With the name provided in the json with the answer given. Also I'm having an html element with a paragraph tag as shown below which is not getting included to the below dataset.

{
   "deviceOwner": "Employee",
   "dataSeparation": "Yes",
   "email": "test@gmail.com",
   "information": "feature1",
   "feedback": "feedback test"
}

![image](https://user-images.githubusercontent.com/26425777/218636983-6304170a-bc2a-483d-bf1b-ebce98d1ca60.png)

### What is the expected behavior?

I need to get the data with the question which I asked which is in the title tag of the json also I need to access the data provided to the user inside the html elements.  Could you please show me a way to achieve this. A sample of my json is given below.

export const json = {
  showQuestionNumbers: 'off',
  pages: [
    {
      elements: [
        {
          type: 'dropdown',
          name: 'deviceOwner',
          title: 'Who owns the device?',
          isRequired: true,
          choices: ['Employee', 'Employer'],
        },
      ],
    },
    {
      elements: [
        {
          type: 'dropdown',
          name: 'dataSeparation',
          title: 'Data separation needed?',
          visibleIf: "{deviceOwner}='Employee'",
          isRequired: true,
          choices: ['Yes', 'No'],
        },
      ],
    },
    {
      elements: [
        {
          type: 'html',
          name: 'info',
          html:
            '<p>We do not recommend.</p>',
          visibleIf: "{dataSeparation}='Yes' && {deviceOwner}='Employee'",
        },
      ],
    },
    {
      elements: [
        {
          type: 'dropdown',
          name: 'notDlp',
          title: 'Mode used?',
          visibleIf: "{dataSeparation}='No' && {deviceOwner}='Employee'",
          isRequired: true,
          choices: ['Yes', 'No'],
        },
      ],
    },
    {
      elements: [
        {
          type: 'html',
          name: 'info',
          html:
            '<p>Test info 345</p>',
          visibleIf:
            "{notDlp}='Yes' && {dataSeparation}='No' && {deviceOwner}='Employee'",
        },
      ],
    },
    {
      elements: [
        {
          type: 'html',
          name: 'info',
          html:
            '<p>Testing 123</p>',
          visibleIf:
            "{notDlp}='No' && {dataSeparation}='No' && {deviceOwner}='Employee'",
        },
      ],
    },
    {
      elements: [
        {
          type: 'text',
          name: 'email',
          title: 'PLease enter your email',
          isRequired: true,
          validators: [{ type: 'email' }],
        },
        {
          type: 'text',
          name: 'feedback',
          title: 'Please provide your feedback',
        },
      ],
    },
  ],
  completedHtml: '<p>Thank You For Providing us the information.</p>',
};

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by JaneSjs** [comment]
Hi @OshaniSilva,
HTML questions are read-only questions. HTML content is not included in survey data. If you wish to include read-only data in survey results, consider the following option. 

Subscribe to the [survey.onComplete](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onComplete) function and call the [survey.getPlainData](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#getPlainData) to get a list of all survey questions including read-only ones. You can retrieve question values and read-only HTML content and send this data to a server. For more information, refer to [Access Full Survey Results](https://surveyjs.io/form-library/documentation/handle-survey-results-access#access-full-survey-results).

I hope this helps. Please feel free to reopen this thread if you have any questions or require further assistance.

**Comment by OshaniSilva** [comment]
Hi @JaneSjs,
When using survey.getPlainData function this logs all the data in the json file. However in my survey depending on the users input I'm showing a customized message in a html tag which needs to be sent to the back end. Can I please know how I can do this?

**Comment by JaneSjs** [comment]
Hi @OshaniSilva,
THank you for the update. HTML questions contain read-only values. They are not included in survey results.
You can consider the following options:
* In the [survey.onComplete](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onComplete) function, get an HTML question using the [survey.getQuestionByName](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#getQuestionByName) function. Obtain HTML content using the [question.html](https://surveyjs.io/form-library/documentation/api-reference/add-custom-html-to-survey#html) property.
* Use calculated values or variables to store custom values in survey results. For more information, refer to our documentation: [Variables & Calculated Values](https://surveyjs.io/form-library/documentation/design-survey/conditional-logic#variables).

Please drop me a line if you have further questions.
