### ISSUE TITLE
Cannot add a text-area

### ISSUE THREAD

**Issue by OshaniSilva** [surveyjs/survey-library#5681]
### What is the current behavior?

I have a survey which needs a textarea.  The text type which I use now is not sufficient as more space is needed. Is there another component which I can use for this?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by JaneSjs** [comment]
Hello @OshaniSilva,
You can use a [Comment question](https://surveyjs.io/form-library/examples/questiontype-comment/reactjs) to add a text area field to your survey. Use the comment question's [rows](https://surveyjs.io/form-library/documentation/api-reference/comment-field-model#rows) property to enlarge the text input area.

I hope this helps. Please feel free to reopen this thread if you have any questions or require further assistance.
