### ISSUE TITLE
The onSetValue function is not raised for a custom property

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5682]
I registered a custom Dropdown property and handled the `onSetValue` function. However, this function is not raised when changing a selected value. For more details, refer to the [original thread](https://surveyjs.answerdesk.io/internal/ticket/details/T12058).

**Comment by andrewtelnov** [comment]
Here is the [working example](https://codesandbox.io/s/aged-tdd-974p2y?file=/src/creator.jsx).
There is a trick with a custom property. It can be added by using Serializer.addProperty only. If you add properties via addClass, then Serializer assumes that the class and the property is actually exists in JavaScript object and behavior differently.
We wanted to make it more obvious, but unfortunately, could not able to find out the way to do it without breaking the existing code of our customers.

Thank you,
Andrew
