### ISSUE TITLE
Add a new feature to display information which is also included in the survey result

### ISSUE THREAD

**Issue by OshaniSilva** [surveyjs/survey-library#5704]
### Are you requesting a feature, reporting a bug or asking a question?

Requesting a feature

### What is the current behavior?

Currently I'm using a html tags (EX.. h3, p ..) to display some information. However there is no way to get this information with the survey result data once the survey has been completed. Is it possible to add a component for displaying information which would include in the survey result as well.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by JaneSjs** [comment]
Hello @OshaniSilva,
I have discussed this suggestion with the team. Unfortunately, we are not considering such an option. HTML questions are read-only questions which don't actually have a _value_. Survey results include user responses, and we do not plan to include `html` property contentin survey results.

Please consider an alternavite option. For example, try calculated fields, as it was suggested in the following thread: https://github.com/surveyjs/survey-library/issues/5705#issuecomment-1445827589.
