### ISSUE TITLE
Display some information in a page and retrieve that data once survey is completed

### ISSUE THREAD

**Issue by OshaniSilva** [surveyjs/survey-library#5705]
### What is the current behavior?
Is there a way to display some information and once survey has been completed retrieve that data with the other survey results?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by JaneSjs** [comment]
Hi @OshaniSilva,
On survey completion (survey.onComplete), you can get survey data using the following API:
* [survey.data](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#data) returns survey results in the following format: `questionName: value`. 
```
{
  question1Name: question1Value,
  question2Name: question2Value,
  // ...
}
```
* [survey.getPlainData()](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#getPlainData) returns detailed information about survey questions (e.g., name, title, etc.) and their answers.

For more information on how to access survey results, check out our documentaiton: https://surveyjs.io/form-library/documentation/handle-survey-results-access.

Please let me know if this information helps.

**Comment by OshaniSilva** [comment]
Hi @JaneSjs,

I have tried above but I'm still unable to fix the issue. For example I have a a json as given below which would display a different information based on the users input.

So once the survey has been completed how can I retrieve information shown to the user along with the users input as I need both the particular information shown to the user and the users input to be sent to the backend.

Scenario

For example if the User chooses 'Employee' then  Test 1 will be shown to them in the next page. Once the user completes the survey I need to send the users input to the 1st question ( Employee ) and the content of the p tag ( Test 1 ) to the backend.

EX:

export const json = {
  pages: [
    {
      elements: [
        {
          type: 'dropdown',
          name: 'deviceOwner',
          title: 'Who owns the device?',
          isRequired: true,
          choices: ['Employee', 'Employer'],
        },
      ],
    },
    {
      elements: [
        {
          type: 'html',
          key: 'info',
          name: 'info',
          html:
            '<p>Test 1</p>',
          visibleIf: "{deviceOwner}='Employee'",
        },
      ],
    }, {
      elements: [
        {
          type: 'html',
          key: 'info',
          name: 'info',
          html:
            '<p>Test 2</p>',
          visibleIf: "{deviceOwner}='Employer'",
        },
      ],
    },
]
}

**Comment by OshaniSilva** [comment]
Hi @JaneSjs,

Could I please get an example for the above scenario?

**Comment by OshaniSilva** [comment]
Hi @JaneSjs ,

Is there an update on this?

**Comment by JaneSjs** [comment]
Hello @OshaniSilva,
Thank you for the update. 

HTML values are not saved to `survey.data`. With the above survey JSON definition, I believe it is better to consider an alternative.

If you wish to preserve a specific value to survey results, you can create a calculated field:
```
"calculatedValues": [
 {
   "name": "var1",
   "expression": "iif({deviceOwner}='Employee', 'Test 1' , 'Test 2')",
   "includeIntoResult": true
  }
 ]
```
Now, survey data contains the `var1` field depending on the `{deviceOwner}='Employee'` expression evaluation result.
Please test the following example: https://plnkr.co/edit/pFo8ObeC9dWHr3Qb.

Let me know if this works for you.
