### ISSUE TITLE
Save data notifications vanish too quickly

### ISSUE THREAD

**Issue by tillsanders** [surveyjs/survey-library#5725]
### Usability bug

Recently, #5530 improved the saving notifications. This is already a lot better than before. The messages are disappearing too quickly, however.

### What is the current behavior?

When completing a survey, I have access to the callbacks `showDataSaving()`, `showDataSavingSuccess()` and `showDataSavingError()`, like this:

```javascript
survey.onComplete.add(function ({ data }, { showDataSaving, showDataSavingError, showDataSavingSuccess }) {
    showDataSaving();
    if (!doingStuff()) {
        showDataSavingError();
        return;
    }
    showDataSavingSuccess();
});
```

This will display notifications accordingly, at the bottom of the screen. The notifications disappear after about three seconds. The error notification contains a button that can retry sending the survey.

### What is the expected behavior?

- The notifications should stay longer.
- The error notification **should not disappear automatically at all** since it is the only way to re-submit the survey!

### Specify your

* browser: Chrome (macOS)
* browser version: 110
* surveyjs platform: jquery
* surveyjs version: 1.9.76

**Comment by JaneSjs** [comment]
Hello,
Thank you for input. Your suggestions definitely make sense.
I tested this usage scenario and also noticed some additional issues. Let me list them below.

### The Saving Success notification
- [ ] The 'saving success' notification should stay longer.
- [ ] The notification looks like a button. However, it seems that clicking the button does nothing. What's the point applying a button style to it?
![image](https://user-images.githubusercontent.com/22372972/222692017-5de33994-97f5-49b5-85c1-3fc8fc1c6b5b.png)

### The Saving Error notification
![image](https://user-images.githubusercontent.com/22372972/222693757-e9ef0b32-4b19-477b-b6b6-df5515000393.png)

- [ ] The error notification should not disappear at all.
The error notification should not disappear: it contains the Try Again button, which users can click;
- [ ] As it name implies, the **Try Again** button should allow users to re-submit a survey. However, this button (the `save-again` action) seems to just call the `doComplete` function: https://github.com/surveyjs/survey-library/blob/master/src/survey.ts#L1458. I believe this button should clear the survey to re-run it:
```
 this.notifier.addAction(<IAction>{
      id: "save-again",
      title: this.getLocalizationString("saveAgainButton"),
      action: () => { 
           this.clear();       
      }
    }, "error");
```

I will discuss the above issues with the team and get back to you shortly.

**Comment by JaneSjs** [comment]
Hello @tillsanders,
Thank you for your patience. I discussed this with the team.

* The notifications should stay longer.

You can specify the [Survey.settings.notifications.lifetime](https://surveyjs.io/form-library/documentation/api-reference/settings#notifications) property to increase the notification delay. By default, it is set [to 2 seconds](https://github.com/surveyjs/survey-library/blob/864b6296bcc1701faa4c80f049b58363d0c027b3/src/settings.ts#L309). For example, you can set to to 10 seconds using the following code:
```
Survey.settings.notifications.lifetime = 10000;
```

* The error notification should not disappear automatically at all since it is the only way to re-submit the survey!

We agreed that error notification should not disappear, because it contains a user action. I created a separate issue in this regard. 
https://github.com/surveyjs/survey-library/issues/5768

Thank you

**Comment by CmdrBeavis** [comment]
Oh what I wouldn't give right now for the documentation of that `onComplete.add()` function / method! I've searched all over the place, and still no joy. : (

My linter is DEMANDING to know the Type of the options argument. Currently I just get "`'options' is of type 'unknown'`"

**Comment by andrewtelnov** [comment]
@CmdrBeavis What framework do you use?
[onComplete](https://github.com/surveyjs/survey-library/blob/master/src/survey.ts#L152) event has options with [CompleteEvent](https://github.com/surveyjs/survey-library/blob/master/src/survey-events-api.ts#L110) type.
Here is [survey.onComplete](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onComplete) event documentation.

Thank you,
Andrew

**Comment by CmdrBeavis** [comment]
Angular (15)


Thanks and best regards,
Scott K. Fraley

**Comment by CmdrBeavis** [comment]
Not sure how to find it, so I'll ask; is there a way to control the display and behavior of that "`Try Again`" button you get when you call the `showDataSavingError()` options function?
