### ISSUE TITLE
Matrix Dynamic Custom Cell Types - File Question file placeholder text is broken when multiple tagbox items are selected (DefaultV2)

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5757]
* Run the following demo in defaultV2 theme: https://surveyjs.io/form-library/examples/questiontype-matrix-customcelltypes/reactjs.
* Select multiple items in a tagbox.
* A file question's placeholder text goes beyond the available area:
![image](https://user-images.githubusercontent.com/22372972/224132212-c5c90a7f-ca50-4011-9af6-ac86657a3d09.png)

**Comment by andrewtelnov** [comment]
@JaneSjs We need to discuss it. Probably we have to introduce min width for a column based on cell question type. In this case, it will work out of the box.

Thank you,
Andrew

**Comment by JaneSjs** [comment]
The issue was fixed by setting the `minWidth` option for a matrix column. 

The updated demo is available at https://surveyjs.io/form-library/examples/questiontype-matrix-customcelltypes/reactjs.
