### ISSUE TITLE
Knockout/jQuery - completedHtmlOnCondition doesn't work when specifying survey values (survey.setValue) in the onComplete function

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5762]
Please run the following demo for Knockout: https://surveyjs.io/form-library/examples/create-a-scored-quiz/reactjs

For jQuery: https://plnkr.co/edit/TTSKdYRMpIIAJQYY

The completedHtmlOnCondition doesn't show expected output.

**Comment by andrewtelnov** [comment]
@JaneSjs Please use onCompleting.

Thank you,
Andrew
