### ISSUE TITLE
Typo json schema 'allOff' should be 'allOf'

### ISSUE THREAD

**Issue by goxiaoy** [surveyjs/survey-library#5767]
### Are you requesting a feature, reporting a bug or asking a question?
bug 

### What is the current behavior?
'allOff'

### What is the expected behavior?
'allOf'

### How would you reproduce the current behavior (if this is a bug)?

https://github.com/surveyjs/survey-library/blob/master/docs/surveyjs_definition.json

#### Provide the test code and the tested page URL (if applicable)

https://github.com/surveyjs/survey-library/blob/d343e57ed871bb80a0d65fd4a72f0a04b597417e/docs/surveyjs_definition.json#L408

And  all of following `allOff`
### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by JaneSjs** [comment]
Hello @goxiaoy,
Thank you for reporting this issue. We will handle it shortly.
