### ISSUE TITLE
Range slider with displaying actual min and max value

### ISSUE THREAD

**Issue by geourjoa-tetras** [surveyjs/survey-library#5774]
Hello,

I'm trying to use range from Survey js.

I would like have a range input displaying actual value, min and maximal possible value. Something like that.

![Screenshot from 2023-03-14 17-32-25](https://user-images.githubusercontent.com/122985699/225074809-337bceba-e5f5-4953-b9da-41933be0aaa3.png)

I don't find any example of this in the documentation. I'm new on the lib. 
Is it possible to do something like this in survey js ? I assume yes, it's a common question I think.

Can anyone give me the correct json to do this ?

My current sample range 

```
{
  "name": "thermalPerformance",
  "title": "Isolation (m².K/W)",
  "type": "text",
  "inputType": "range",
  "min": 1,
  "max": 6.5,
  "step": 0.1,
  "defaultValue": 3.25,
},
```

Thanks in advance for your help and this awesome lib for complex form.

Geourjoa

### Specify your

* browser: Firefox Linux
* browser version: 110.0.1
* surveyjs platform (angular or react or jquery or knockout or vue): JQuery
* surveyjs version: 1.9

**Comment by JaneSjs** [comment]
Hello @geourjoa-tetras,
Thank you for reaching out to us. 
I see that you use the inputType: "range" for a `text` question.
The `inputType` property value is passed on to the [type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#input_types) attribute of the underlying <input> HTML element. 
You can review the MDN topic for the [input type="range"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range) and review possible settings: unfortunately, I don't see any option to display the selected value.

Instead, you may wish to try using a third-party NoUISlider: [Demo](https://surveyjs.io/form-library/examples/custom-widget-nouislider/reactjs).
![image](https://user-images.githubusercontent.com/22372972/225266165-48c4f08b-51a8-4b1d-b754-fa7f2465cd78.png)

Please select your JavaScript framework and click Edit in Plunker/Sandbox to review the code.

Should you have any questions or require further assistance, feel free to reactivate this thread.

**Comment by geourjoa-tetras** [comment]
Thanks for the answers, exactly what I want !
