### ISSUE TITLE
TOC Issues

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#5786]
- [x] useless indent above TOC
- [x] we have to use some min-width (may be 256 px)
- [ ] TOC must fit to height of page

![Image](https://user-images.githubusercontent.com/17025812/225631592-61e0ce11-d642-498a-afca-bba109dd9bb2.png)

- [x] hover must have rounded corners

![Image](https://user-images.githubusercontent.com/17025812/225631735-d6eb8988-111f-4bfe-b6c7-f5ee05a53d70.png)

- [x] selected must be higher

![Image](https://user-images.githubusercontent.com/17025812/225631851-9888ef28-d2a9-4931-bf5c-52a72a6deb38.png)

- [ ] no mobile mode
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=16476-271406

![Image](https://user-images.githubusercontent.com/17025812/225631971-c42b7480-ea68-4726-9792-29617876c81b.png)

**Comment by tsv2013** [comment]
I've extracted mobile mode into a separate issue - TOC: mobile layout #5877

**Comment by tsv2013** [comment]
As for full page height - TOC actually has the survey height
In this case survey is not fit the whole preview page - this is related to SurveyJS Creator

Indeed we have another issue now - Survey has unnesessary bottom margin #5878
