### ISSUE TITLE
storeOthersAsComment at question level

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#5788]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

I'd like to control storeOthersAsComment prop at question level and it actually works. But looking at the docs it seems you can do that at survey level only. 
[By looking the codebase, also seems to confirm the fact that it can be used at question level](https://github.com/surveyjs/survey-library/blob/97d553037764ab33066a0d502fb232a26f367319/src/question_baseselect.ts#L688)

Can you confirm that? If so maybe that prop is missing in the question baseselect docs 

thank you

**Comment by JaneSjs** [comment]
Hello @masciugo,
Please accept my apologies for the delayed reply. It appears that I missed this issue. Yes, it is actually possible to specify the `storeOthersAsComment` property at the question's level. Consider this example:
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "checkbox",
     "name": "question1",
     "choices": [
      "Item 1",
      "Item 2",
      "Item 3"
     ],
     "showOtherItem": true,
     "storeOthersAsComment": false
    },
    {
     "type": "checkbox",
     "name": "question2",
     "choices": [
      "Item 1",
      "Item 2",
      "Item 3"
     ],
     "showOtherItem": true,
     "storeOthersAsComment": true
    }
   ]
  }
 ]
}
```
We will check to see if we can better hightlight this in our documentation.

Thank you

**Comment by JaneSjs** [comment]
Hello @masciugo,
I reviewed this thread (https://github.com/surveyjs/survey-library/issues/1635) and it appears that we intentionally marked the `question.storeOthersAsComment` property internal to avoid ambiguity when specifying both a survey's and question's `storeOthersAsComment` option. 
Therefore, we recommed that you specify the `survey.storeOthersAsComment` property at the survey level.
Would you please clarify what is the usage scenario behing specifyign a different `storeOthersAsComment` value for survey questions?

I look forward to your reply.

Thanks

**Comment by masciugo** [comment]
Hi, I need to control `storeOthersAsComment` at question level when I need to apply my custom widget. Specifically I need to set storeOthersAsComment to false because the comment way is not compatible with with my custom widget. So it's not set by the user who build the survey model but forced, behind the scenes, by my custom widget code

**Comment by JaneSjs** [comment]
Hello @masciugo,
Thank you for the clarification. You can actually override the `storeOthersAsComment` property at the level of an individual question instance. 

Please let us know if you have further questions.
