### ISSUE TITLE
Wrong other item rendering in case of survey with preloaded data

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#5800]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

when using option `storeOthersAsComment: false` the other element rendering is wrong 

### How would you reproduce the current behavior (if this is a bug)?

https://codesandbox.io/s/hopeful-cdn-2jo002?file=/src/json.js

**Comment by JaneSjs** [comment]
Current behavior:
![image](https://user-images.githubusercontent.com/22372972/226301377-20105d58-5bb4-4270-ab8d-2303363a5ddf.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/22372972/226301836-772267fe-9772-4337-a416-b6ba960fdfac.png)
