### ISSUE TITLE
The maximum length indicator doesn't appear when using the Text validator

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5811]
[Example](https://plnkr.co/edit/HpiMdtd9YkrP376M)
```
 {
     "type": "comment",
     "name": "service_improvements",
     "title": "How can we improve our service?",
     "validators": [
      {
       "type": "text",
       "minLength": 10,
       "maxLength": 20
      }
     ]
}
```
![image](https://user-images.githubusercontent.com/22372972/226204394-4872dd7d-da0c-4c5b-bc5f-0765c603ba8d.png)

**Comment by andrewtelnov** [comment]
@JaneSjs We need to use maxLength to show the indicator. Validator can show the error only. 
I would not consider this as a bug.

Thank you,
Andrew
