### ISSUE TITLE
Create a webpage using SurveyJS in React

### ISSUE THREAD

**Issue by skverma771** [surveyjs/survey-library#5815]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by skverma771** [comment]
Can we create a webpage using SurveyJS in React, and if we need to create multiple SurveyJS for a single page and based on them, we want to create a search functionality, then how can we do it?

**Comment by JaneSjs** [comment]
Hello @skverma771,
To create a webpage using SurveyJS for React, please follow this tutorial: [Add a Survey to a React Application](https://surveyjs.io/form-library/documentation/get-started-react). You can create multiple surveys in a single page. Each survey is located in a container div HTML element; so to create multiple surveys, create multiple div elements for each survey.

Regarding the search functionality: please elaborate on it.
