### ISSUE TITLE
Panel Dynamic: add a tab (button) mode to renderMode property

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#5829]
Create a new mode that will show tabs/buttons in panel dynamic.
[Here is the related ticket on SurveyJS support forum](https://surveyjs.answerdesk.io/ticket/details/T12431).

**Comment by mikeamelin** [comment]
Design — https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=16686-360911&t=wKJo4a1KhVFc5RjN-4
