### ISSUE TITLE
Cannot enable the Single Matrix | Require answer for all rows property by default

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5851]
[Original issue](https://surveyjs.answerdesk.io/internal/ticket/details/T12458)
[Example](https://codesandbox.io/s/billowing-fast-r43wts?file=/src/SurveyCreatorComponent.jsx)

**Comment by andrewtelnov** [comment]
The issue is fixed by this [PR](https://github.com/surveyjs/survey-library/pull/5849).

Thank you,
Andrew
