### ISSUE TITLE
Can client-side & server-side validation run at different times?

### ISSUE THREAD

**Issue by socialsuiteDan** [surveyjs/survey-library#5872]
### Are you requesting a feature, reporting a bug or asking a question?
I have a question:

Is there a way to apply client-side validation on every page navigation, but then only run server-side validation via onServerValidateQuestions when the survey is submitted?

More background:
My scenario requires server-side validation on a subset of the questions in a user-generated survey, which all need to be complete before the validation can run. However, those inputs may not all be on the first page, so I've had to set checkErrorsMode to 'onComplete' as that's the only point I can be sure it will work. The server call is also pretty slow, so i don't really want to have to run it more than once per survey. 

However, this means that even simple mandatory field validation doesn't get applied until submission, there might be 8-10 pages or more so it's not great for users to only get that feedback right at the end. What i'd like is to be able to have the client side validation run on each page navigation, but then the server-side validation only kick in on submission of the survey. Is there some way to implement that using the existing functionality?

**Comment by andrewtelnov** [comment]
@socialsuiteDan You can handle [survey.onCompleting](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onCompleting) event.
You review [the folowing issue](https://github.com/surveyjs/survey-library/issues/1242#issuecomment-1472247921). It shows how to wait for async server request on this event.

Thank you,
Andrew

**Comment by socialsuiteDan** [comment]
Hi @andrewtelnov, thanks for the quick response. I looked at survey.onCompleting when I was initially trying to figure this out, but it doesn't give me access to the errors parameter to assign individual question error messages so that's why i was trying to use onServerValidateQuestions.

I've been testing the suggested way of using the onCompleting event to do the server call, and then i was trying to make the results available to the onServerValidateQuestions event handler so that I can assign the question level errors, but the timing doesn't seem to work, the validation runs before the onCompleting handler and if I try calling survey.validate() in the async callback it doesn't seem to do anything. Calling doComplete() like in the example works, but that doesn't re-validate before hitting the onCompleting event again. Is there some other way to assign question level errors that would work from within the callback?

**Comment by andrewtelnov** [comment]
@socialsuiteDan You can always add a new error into a question as: `question.addError([string |](error: SurveyError | string);`
You can go to the question with the first error as: `question.focus();`.
I hope this helps.

Thank you,
Andrew

**Comment by socialsuiteDan** [comment]
@andrewtelnov thanks, that approach works. Final question - is there some way to disable the complete button and/or show a spinner while the server validation runs? The only option i've found so far is to change the text on the button, i.e. survey.completeText = 'Validating . . .' but the button is still clickable even if it doesn't do anything.

**Comment by andrewtelnov** [comment]
@socialsuiteDan The complete button is an action on navigation bar. You can access to as the following:
```js
        const completeButton = survey.navigationBar.getActionById("sv-nav-complete");
        completeButton.enabled = !completeButton.enabled;
```
Here is [the example](https://plnkr.co/edit/spiJmdGJfzS4XYCd).

Thank you,
Andrew

**Comment by socialsuiteDan** [comment]
Thanks, that's really helpful.
