### ISSUE TITLE
TOC: mobile layout

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-library#5877]
We need to implement mobile layout for TOC

- [ ] no mobile mode
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=16476-271406
![image](https://user-images.githubusercontent.com/3013415/227926802-b24d9270-a563-4b26-ae70-a8d3ca2c4f86.png)

See the original issue - https://github.com/surveyjs/survey-library/issues/5786

**Comment by nicolaslopez1000** [comment]
Is this in active development?

**Comment by JaneSjs** [comment]
Hi @nicolaslopez1000,
Yes, this task is in our list. Please wait for our updates.
