### ISSUE TITLE
How can I change the colors of each element of a choice, try this way but it remains the same.

### ISSUE THREAD

**Issue by JesusCristobal97** [surveyjs/survey-library#5902]
How can I change the colors of each element of a choice, try this way but it remains the same.

![image](https://user-images.githubusercontent.com/39527292/228828916-d5bc78a6-a017-44e0-b772-f01a64cb4030.png)

I tried to place the styles linearly but it didn't work

![image](https://user-images.githubusercontent.com/39527292/228828976-31b6476e-3a39-404e-9547-ed0c2b4a3ebc.png)

**Comment by andrewtelnov** [comment]
@JesusCristobal97 Please use [onTextMarkdown](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onTextMarkdown) event. Here is [the example](https://surveyjs.io/form-library/examples/survey-markdown-radiogroup) for radiogroup.

Thank you,
Andrew

**Comment by JaneSjs** [comment]
@JesusCristobal97, please feel free to reactivate this thread if you have any questions or require further assistance.

Thanks
