### ISSUE TITLE
Recheck all colors in the palette.

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#5914]
Some colors and effects (shadows) have been changed.

/* Color styles */
--default---general---backcolor: rgba(255, 255, 255, 1);
--default---general---backcolor--dark: rgba(248, 248, 248, 1);
--default---general---forecolor: rgba(0, 0, 0, 0.91);
--default---general---forecolor--light: rgba(0, 0, 0, 0.45);
--default---general---dim--backcolor: rgba(243, 243, 243, 1);
--default---general---dim--forecolor: rgba(0, 0, 0, 0.91);
--default---general---dim--forecolor--light: rgba(0, 0, 0, 0.45);
--default---general---dim--backcolor--light: rgba(249, 249, 249, 1);
--default---general---dim--backcolor--dark: rgba(243, 243, 243, 1);
--default---general---haze--background: rgba(144, 144, 144, 0.5);
--default---borders---default--border: rgba(0, 0, 0, 0.16);
--default---borders---light--border: rgba(0, 0, 0, 0.09);
--default---borders---inside--border: rgba(0, 0, 0, 0.16);
--default---primary---backcolor: rgba(25, 179, 148, 1);
--default---primary---backcolor--light: rgba(25, 179, 148, 0.1);
--default---primary---backcolor--dark: rgba(20, 164, 139, 1);
--default---primary---forecolor: rgba(255, 255, 255, 1);
--default---primary---forecolor--light: rgba(255, 255, 255, 0.25);
--default---secondary---backcolor: rgba(255, 152, 20, 1);
--default---secondary---backcolor--semi--light: rgba(255, 152, 20, 0.25);
--default---secondary---backcolor--light: rgba(255, 152, 20, 0.1);
--default---secondary---forecolor: rgba(255, 255, 255, 1);
--default---secondary---forecolor--light: rgba(255, 255, 255, 0.25);
--default---special---red: rgba(229, 10, 62, 1);
--default---special---red--light: rgba(229, 10, 62, 0.1);
--default---special---red--forecolor: rgba(255, 255, 255, 1);
--default---special---green: rgba(25, 179, 148, 1);
--default---special---green--light: rgba(25, 179, 148, 0.1);
--default---special---green--forecolor: rgba(255, 255, 255, 1);
--default---special---blue: rgba(67, 127, 217, 1);
--default---special---blue--light: rgba(67, 127, 217, 0.1);
--default---special---blue--forecolor: rgba(255, 255, 255, 1);
--default---special---yellow: rgba(255, 152, 20, 1);
--default---special---yellow--light: rgba(255, 152, 20, 0.1);
--default---special---yellow--forecolor: rgba(255, 255, 255, 1);

/* Effect styles */
--default---shadow---small:  0px 1px 2px rgba(0, 0, 0, 0.15);
--default---shadow---medium:  0px 2px 6px rgba(0, 0, 0, 0.1);
--default---shadow---large:  0px 8px 16px rgba(0, 0, 0, 0.1);
--default---shadow---inner: inset 0px 1px 2px rgba(0, 0, 0, 0.15);

**Comment by OlgaLarina** [comment]
https://github.com/surveyjs/private-tasks/issues/225
