### ISSUE TITLE
How to get specific result value from dxservice api GET request?

### ISSUE THREAD

**Issue by vanBersie** [surveyjs/survey-library#592]
**Question**

When using this request:
```
$.ajax({
	type: 'GET',
	url: 'https://dxsurvey.com/api/MySurveys/getSurveyResults/<id>?accessKey=<accessKey>',
	dataType: 'json',
	success: function(res){
		console.log(res);
	}
});
```
I get all the results. Is it possible to access only a specific value? In this example [https://surveyjs.io/Examples/Library/?id=service-result&platform=jQuery](https://surveyjs.io/Examples/Library/?id=service-result&platform=jQuery) without using the api you could access it with `survey.getResult('<id>', '<name of the form element>');` but how to pass that to the api? Unfortunately I couldn't find anything within the documentation. I tried to pass the parameter "&name=<my_form_element_name>" but that didn't work. Is it possible?

Thanks in advance!

**Comment by andrewtelnov** [comment]
@vanBersie Have you found public api? This method probably is what you need: http://api.dxsurvey.com/Help/Api/GET-api-Survey-getResult_resultId_name

PS: We will make it more discoverable after moving this service into surveyjs.io

Thank you,
Andrew

**Comment by vanBersie** [comment]
Yes, in the meanwhile I could create a almost working survey with it. I didn't use it at first because I couldn't find all the IDs that are needed because they were kind of hidden in that dropdown under "My surveys" :D 

Before that I could only use the API because the only ID I knew so far was the one that was in the URL on the result page ;)

**Comment by andrewtelnov** [comment]
@vanBersie Yes, the usability of the current version dxsurvey.com is really bad. We will work on it.

Thank you,
Andrew
