### ISSUE TITLE
Panel Dynamic: if renderMode is a tab, show some display text for tabs

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-library#5949]
![image](https://user-images.githubusercontent.com/14936841/230022179-f5a5e8af-b6f6-487c-95ac-7777c271a4fa.png)

**Comment by JaneSjs** [comment]
The feature was requested at T12706 - Dynamic Panel - Tab Render Mode
https://surveyjs.answerdesk.io/internal/ticket/details/T12706
