### ISSUE TITLE
Disable multiple locales support for properties with isLocalizable equals to false

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5962]
Original issue: T12627 - How to disable logo localization?
https://surveyjs.answerdesk.io/internal/ticket/details/T12627

[Example](https://plnkr.co/edit/Ioy3ABmTghlLEANo)

Task: keep the same survey logo regardless of a survey locale.
Unfortunately, `isLocalizable = false` doesn't prevent users from specifying another Logo base64 string from Property Grid or from uploading another logo from a design surface.

**Comment by andrewtelnov** [comment]
We need to disable multiple locales for properties sith isLocalizable equals to 'false'.

Thank you,
Andrew
