### ISSUE TITLE
Panel - The Required Validation message doesn't use the default validation error appearance

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5975]
To reproduce the issue, add a panel with questions, and enable the [panel.isRequired](https://surveyjs.io/form-library/documentation/api-reference/panel-model#isRequired) option. The validation message appears as follows:
![image](https://user-images.githubusercontent.com/22372972/230878645-76441dbb-2cd0-4d84-b261-e948fafba933.png)

[Example](https://codesandbox.io/s/reverent-glade-bmbbj4?file=/src/SurveyComponent.jsx)

Expected behavior: the validation message appears as follows.
![image](https://user-images.githubusercontent.com/22372972/230880721-a67c2f9e-9410-4982-a78b-f54affa0970a.png)

**Comment by mikeamelin** [comment]
Current state — https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=17159-393618

**Comment by JaneSjs** [comment]
Unfortunately, a panel doesn't have a required validation mode which requires that all fields must be answered. So the following option is unavailable for now.
![image](https://user-images.githubusercontent.com/22372972/230894751-13485505-5913-462e-a1ef-7368f0869fa5.png)

Forwarded to the team for further consideration: https://github.com/surveyjs/survey-library/issues/5976
