### ISSUE TITLE
Tabbed Dynamic Panel Issues

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#5994]
- [ ] wrong distance

![Image](https://user-images.githubusercontent.com/17025812/231219796-595fc37e-a5e7-43ff-9bf1-4f9553cbee7e.png)

**Comment by mikeamelin** [comment]
- [ ] tabs is not centred



![Image](https://user-images.githubusercontent.com/17025812/231219942-4e6a4c20-34e5-4055-8371-258380466140.png)

**Comment by mikeamelin** [comment]
- [ ] tab must have hover

https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=16686-361271&t=KzejMkATknPWTTlp-4

**Comment by mikeamelin** [comment]
- [ ] there must not be indent



![Image](https://user-images.githubusercontent.com/17025812/231220244-e9701409-0127-45ca-b3bd-a3237911c5c8.png)

**Comment by mikeamelin** [comment]
- [ ] changing position doesn't affect the tabs on the surface



![Image](https://user-images.githubusercontent.com/17025812/231220660-6cd34388-b374-4ab2-9326-2e640880f9c1.png)

**Comment by mikeamelin** [comment]
- [ ] wrong distance in case with no title



![Image](https://user-images.githubusercontent.com/17025812/231220950-d0927002-531b-4428-bb7e-5ee45187c52a.png)

**Comment by OlgaLarina** [comment]
- [ ] Hide bottom navigation panel
