### ISSUE TITLE
TOC and animation bug when used together

### ISSUE THREAD

**Issue by NicholasStambaugh** [surveyjs/survey-library#5997]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
TOC bugs when used in combination with page change animation. Search bar disappears and navigation breaks. It only allows you to move one page forward, backwards navigation still works though. Animation taken from [](https://surveyjs.io/form-library/examples/survey-animation/reactjs#content-code)

### What is the expected behavior?
animation and TOC both work together properly.

### How would you reproduce the current behavior (if this is a bug)?
Apply TOC and page change animation in same survey

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
var doAnimantion = true;
// This component renders the survey.
function SurveyComponent() {
    const survey = new Model(sourcing);
    survey.onComplete.add((sender, options) => {
        console.log(JSON.stringify(sender.data, null, 3));

    });
// This function animates the survey element 
// by adding or removing the "expandable" and "expandable_show" classes. 
// This creates a 'scrolling' effect on page change and  
function animate(show) {
    const element = document.getElementById("surveyElement");
    if (!!element) {
        const list = element.classList;
        if (!list.contains("expandable")) {
            list.add("expandable");
        }
        if (show) {
            list.add("expandable_show");
        } else {
            list.remove("expandable_show");
        }
    }
};
    // This function prevents page changes during animations 
    // and triggers an animation after the page changes.
    survey.onCurrentPageChanging.add(function (sender, options) {
        if (!doAnimantion) return;
        options.allowChanging = false;
        setTimeout(function () {
            doAnimantion = false;
            sender.currentPage = options.newCurrentPage;
            doAnimantion = true;
        }, 500);
        animate(false);
    });
    // This function triggers an animation when the current page of the survey changes
    survey.onCurrentPageChanged.add(function (sender) {
        animate(true);
    });
    // This function prevents survey completion during 
    // animations and triggers an animation after the survey is completed.
    survey.onCompleting.add(function (sender, options) {
        if (!doAnimantion) return;
        options.allowComplete = false;
        setTimeout(function () {
            doAnimantion = false;
            sender.doComplete();
            doAnimantion = true;
        }, 500);
        animate(false);
    });
    // This function triggers an animation after the survey is rendered.
    survey.onAfterRenderSurvey.add((sender, options) => {
        animate(true);
    });
    // // Render the survey using the SurveyJS React component.
    return (<Survey model={survey} />);
}

export default SurveyComponent;

```

### Specify your

* browser: Chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: latest

**Comment by JaneSjs** [comment]
Hello,
Thank you for reporting this issue. I will discuss it with the developers. Please look forward to updates.

[Example](https://codesandbox.io/s/dark-frost-lzpofp?file=/src/json.js)

**Comment by NicholasStambaugh** [comment]
Thank you, let me know if I can be of any assistance.

**Comment by tsv2013** [comment]
You need to change the HTML element will being animated. Use CSS selector for a page content:
```JS
    const element = document.querySelectorAll("#surveyElement .sd-page.sd-body__page")[0];
```
and it will animate page content only.

Here is the updated live example - https://codesandbox.io/s/competent-curie-6gcb2q

**Comment by NicholasStambaugh** [comment]
Ah, this makes sense. Will be testing soon, thank you so much! :)
