### ISSUE TITLE
Survey Validation occurs even if non-mandatory fields are unspecified

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#6011]
Original issue: T12707 - Multiple text box validation
https://surveyjs.answerdesk.io/ticket/details/T12707
***
Test this sample: https://plnkr.co/edit/8S0YuKjOnw8zCkAV.
A Multiple text question is not required and has the following validation:
```
{
     "type": "multipletext",
     "name": "question1",  
     "validators": [
      {
       "type": "expression",
       "expression": "{question1.text1} > {question1.text2}"
      }
     ],   
     "items": [
      {
       "name": "text1",
       "inputType": "number",       
      },
      {
       "name": "text2",
       "inputType": "number",       
      }
     ]
    }
```
However, it is impossible to complete the survey without entering values.
![image](https://user-images.githubusercontent.com/22372972/231744115-44bd47a4-13ec-408a-9fed-43100cce2599.png)

Expected behavior: it is possible to leave fields unspecified and complete the survey.

**Comment by andrewtelnov** [comment]
@JaneSjs Please use the following expression:
"{question1.text2} empty or {question1.text1} > {question1.text2}"

Thank you,
Andrew
