### ISSUE TITLE
Progress bar has wrong design.

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#6018]
The green line must be only one.

![Image](https://user-images.githubusercontent.com/17025812/231992943-4762c160-8604-48b7-b18d-193af92b949b.png)

**Comment by OlgaLarina** [comment]
https://private-user-images.githubusercontent.com/17025812/244409262-0539a312-8185-4d6e-8968-02363e175070.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJrZXkxIiwiZXhwIjoxNjg3OTYyNTIxLCJuYmYiOjE2ODc5NjIyMjEsInBhdGgiOiIvMTcwMjU4MTIvMjQ0NDA5MjYyLTA1MzlhMzEyLTgxODUtNGQ2ZS04OTY4LTAyMzYzZTE3NTA3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMwNjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMDYyOFQxNDIzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDVjZjFjMjViOWIwNTg1YTdkNTUzMmZlZTNmZmUwODhmMzdhNGE3MTFhYWQxNDQ3ZjA2ZDI1Y2NjZDMzZWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z6lDB9C2Z7kHCzlsU2Wie9egqFQopV73stoKj1udrBk
