### ISSUE TITLE
Custom Percentage Progress Component - The 'Can't create component with name: sv-progress-percent and default: undefined' error is thrown on an attempt to run a survey with a custom component

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#6038]
Original issue: T12658 - progressbar-percentage Bug (Angular)
https://surveyjs.answerdesk.io/internal/ticket/details/T12658

![image](https://user-images.githubusercontent.com/22372972/232453997-f6b529c2-02ca-42b7-b718-da36297926f1.png)

Run the following sample to reproduce the issue.
[progress-percentage-component-issue.zip](https://github.com/surveyjs/survey-library/files/11248857/progress-percentage-component-issue.zip)

**Comment by dk981234** [comment]
Please add these lines:
`export class AppModule {
  static declaration = [ProgressPercentComponent]
}`
to fix the issue.
