### ISSUE TITLE
completedBeforeHtml not working with cookieName

### ISSUE THREAD

**Issue by Maxime-J** [surveyjs/survey-library#6060]
### What is the current behavior?
When `cookieName` is set and the survey has already been submitted once,
`completedHtml` is shown if user returns on the survey.

### What is the expected behavior?
According to the docs, `completedBeforeHtml` should be shown.

> cookieName property
> --
> A cookie name used to save information about survey completion.
When this property has a value, the survey creates a cookie with the specified name on completion. This cookie helps ensure that users do not pass the same survey twice. On the second run, they will see the Completed Before page.

### How would you reproduce the current behavior (if this is a bug)?

Can be easily reproduced using the example:
https://surveyjs.io/form-library/examples/survey-cookie/reactjs

### Specify your

* surveyjs platform (angular or react or jquery or knockout or vue): all
* surveyjs version: 1.9.84

**Comment by andrewtelnov** [comment]
@Maxime-J Thank you for the fix.

Andrew
SurveyJS Team
