### ISSUE TITLE
The page.addNewQuestion function doesn't create a new question for a custom widget type

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#6075]
Original issue: T12791 - A third-party Camera question: 
https://surveyjs.answerdesk.io/internal/ticket/details/T12791
***
The [page.addNewQuestion](https://surveyjs.io/form-library/documentation/api-reference/page-model#addNewQuestion) function fails to add a new question of a custom-defined type.

An example with a Datepicker: https://plnkr.co/edit/ob9bwQHUNGZm76hX

**Comment by andrewtelnov** [comment]
The issue is reopened since the PR is revert. It cause numerous errors in Creator functional tests in V1 and V2.

Thank you,
Andrew
