### ISSUE TITLE
options squeeze together if too much 

### ISSUE THREAD

**Issue by AkaHanshan** [surveyjs/survey-library#6093]
In the popup,when when selecting the condition,if there are to many options, will squeeze together and can't scroll the select list
so add a min-height,it works well

**Comment by AkaHanshan** [comment]
And this problem seems  caused if have two version of creator core in one project, I found the webpack have two version sv-list.scss,the Survey/src/modern/blocks/sv-list.scss have a flex caused this problem,so add the min-height to prevent the missing style of page elements from not supporting the height of the outer box.

**Comment by OlgaLarina** [comment]
You are writing about the modern theme CSS (src/modern/blocks/sv-list.scss) but your fix is related to the defaultV2 theme (src/defaultV2-theme/blocks/sd-list.scss). Coud you please illustrate the issue with a screenshot and share the exact steps to reproduce it in our online demos or share a minimal live sample of the issue?
