### ISSUE TITLE
Colorize the rating

### ISSUE THREAD

**Issue by JoopStringer** [surveyjs/survey-library#6114]
Is there a way to colorize the rating element like this ?
Maybe via CSS ?
<img width="627" alt="Scherm­afbeelding 2023-05-02 om 08 55 27" src="https://user-images.githubusercontent.com/688083/235599787-a1683a18-a847-4476-8bff-f9f7adbeb042.png">

**Comment by JaneSjs** [comment]
Hi @JoopStringer,
Yes, it is possible to apply different colors to rate items using the [:nth-child()](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) CSS preudo-class. For instance:
```
var json = {
  questions: [
    {
      type: "rating",
      name: "satisfaction",
      title: "How satisfied are you with the Product?",   
      "rateMin": 0,
      "rateMax": 10,
      "displayMode": "buttons"
    }
  ]
};

.sd-rating__item:nth-child(-n+9)  {
  background-color: red;
}
.sd-rating__item:nth-last-child(-n+4)  {
  background-color: yellow;
}
.sd-rating__item:nth-last-child(-n+2)  {
  background-color: darkgreen;
}
```
![image](https://user-images.githubusercontent.com/22372972/235622112-91a47f49-3522-43b7-a6aa-db638ece3c61.png)

[Example](https://plnkr.co/edit/NWetkADiCJDIf2p4)

I hope this helps.

Please feel free to reactivate this thread if you have further questions.

**Comment by JoopStringer** [comment]
Cool, works perfectly. Added a bit for the text colors
	.sd-rating__item:nth-child(-n+9)  {
	  color: white;
	  background-color: red;
	}
	
	.sd-rating__item:nth-last-child(-n+5)  {
	  color: black;	
	  background-color: yellow;
	}

	.sd-rating__item:nth-last-child(-n+3)  {
	  background-color: darkgreen;
	  color: white;
	}
		
Would be nice to be able to add this in the designer as well !

**Comment by JaneSjs** [comment]
Hi @JoopStringer,
You're always welcome.
I noted down this inquiry and forwarded to our developers for further consideration.
https://github.com/surveyjs/survey-library/issues/6135

Thank you

If you wish to allow users to define colors for rate items in Survey Creator, you can register a custom property for an `itemvalue` object and handle the `survey.onAfterRender` questions to apply colors to individual rate items.
```js
survey.onAfterRenderQuestion.add((sender, options) => {  
  if(options.question.getType() === 'rating'){
    let rateItemsFieldset = options.htmlElement.getElementsByTagName('fieldset')[0];
      for (var i = 1; i < rateItemsFieldset.children.length; i++) {    
        let item = rateItemsFieldset.children[i];  
        item.style.backgroundColor = options.question.rateValues[i-1].color;
    }
  } 
});
```
I created the following demo to show how to create a custom Color property for Rate Items and use a [React Color](https://surveyjs.io/survey-creator/examples/custom-colorpicker-property-editor/reactjs#) widget to edit colors: [CodeSandbox demo](https://codesandbox.io/s/winter-browser-4wbqis?file=/src/SurveyCreatorComponent.jsx).

I hope this helps. Please feel free to reactivate this thread if you have any questions or require further assistance.

Thanks

**Comment by JoopStringer** [comment]
Sweet !

> Op 4 mei 2023, om 08:12 heeft Jane ***@***.***> het volgende geschreven:
> 
> llowing demo to show how to create a custom

**Comment by JaneSjs** [comment]
Hello @JoopStringer,
I created an example demonstrating how to override rendering for Rating items and add a `color` property for an individual rate item. 
# [Survey JSON Model](#tab/tab1)
```json
export const json = {
  elements: [
    {
      type: "rating-colored",
      name: "satisfaction-numeric",
      title: "How satisfied are you with our product?",
      rateValues: [
        { value: 0, text: "0", color: "#EA3532" },
        { value: 1, text: "1", color: "#F74445" },
        { value: 2, text: "2", color: "#FF6443" },
        { value: 3, text: "3", color: "#EDB188" },
        { value: 4, text: "4", color: "#FFA62B" },
        { value: 5, text: "5", color: "#FFC001" },
        { value: 6, text: "6", color: "#E3C301" },
        { value: 7, text: "7", color: "#C0CA00" },
        { value: 8, text: "8", color: "#9CCC02" },
        { value: 9, text: "9", color: "#79CA03" },
        { value: 10, text: "10", color: "#31B000" }
      ]
    }
  ],
  showQuestionNumbers: "off"
};
```
# [Custom Rating Scale question](#tab/tab2)
```js
import React, { createElement } from "react";
import { QuestionRatingModel, ElementFactory, Serializer } from "survey-core";
import {
  ReactElementFactory,
  RatingItem,
  SurveyQuestionRating,
  ReactQuestionFactory
} from "survey-react-ui";

Serializer.addProperty("itemvalue", {
  name: "color",
  isLocalible: true
});
class ColoredRatingItem extends RatingItem {
  get question() {
    return this.props.question;
  }
  get item() {
    return this.props.item;
  }
  get index() {
    return this.props.index;
  }
  get color() {
    return this.item.locText.owner.color;
  }
  getStateElement() {
    return this.item;
  }
  render() {
    var itemText = this.renderLocString(this.item.locText);
    var mycolor = this.color;
    return (
      <label
        className="sd-rating__item sd-rating__item--allowhover sd-rating__item--fixed-size"
        style={{ "background-color": mycolor }}
      >
        <input
          type="radio"
          className="sv-visuallyhidden"
          name={this.question.name}
          id={this.question.getInputId(this.index)}
          value={this.item.value}
          disabled={this.isDisplayMode}
          checked={this.question.value == this.item.value}
          onClick={this.props.handleOnClick}
          onChange={() => {}}
          aria-label={this.question.ariaLabel}
          aria-describedby={this.question.ariaDescribedBy}
        />
        <span className="sd-rating__item-text">{itemText}</span>
      </label>
    );
  }
}
ReactElementFactory.Instance.registerElement("colored-item", (props) => {
  return React.createElement(ColoredRatingItem, props);
});

const customType = "rating-colored";

class CustomRatingModel extends QuestionRatingModel {
  getType() {
    return customType;
  }
  get itemComponentName() {
    return "colored-item";
  }
}

Serializer.addClass(
  customType,
  [],
  function () {
    return new CustomRatingModel("");
  },
  "rating"
);
export function registerColoredRating() {
  ElementFactory.Instance.registerElement(customType, (name) => {
    return new CustomRatingModel(name);
  });
  ReactQuestionFactory.Instance.registerQuestion(customType, (props) => {
    return createElement(SurveyQuestionRating, props);
  });
}
```
# [index.css](#tab/tab3)
```css
.sd-question__content fieldset {
  display: flex;
  flex-direction: row;
  border: none;
  flex-wrap: wrap;
}
.svc-rating-question-content .sd-question__content {
  padding-left: 48px;
}
```
***
![image](https://github.com/surveyjs/survey-library/assets/22372972/ee998223-e465-455d-bcd1-a5ceebdd0551)

Please refer to the following demos:
* [View Demo: SurveyJS Form Library - Colorize Rating Scale](https://codesandbox.io/s/vigilant-maxwell-9irxn5?file=/src/SurveyComponent.jsx)
* [View Demo: Colorize Rating Scale Items Demo in Survey Creator](https://codesandbox.io/s/relaxed-bhaskara-xzt2me?file=/src/SurveyCreatorComponent.jsx)

In Survey Creator, users can define individual rating item colors using the Property Grid editor:
![image](https://github.com/surveyjs/survey-library/assets/22372972/a4342bc8-de78-4667-b27f-ebe45eadc6d0)

I hope these examples help. Should you have any questions or require further assistance, please let me know.

**Comment by JoopStringer** [comment]
Super cool ... 
However I use survey.jquery.js v1.9.39 (no React), so how to implement it there ?

**Comment by JaneSjs** [comment]
Hi @JoopStringer,
I'll check to see if I can apply this code to a Survey Creator for Knockout. I'll update this thread once I have any news to share.

Thank you
