### ISSUE TITLE
Radio Button Group Issue

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#6116]

**Comment by ashish-khankari** [comment]
Hey, I would like to contribute to your project and could be please provide description

**Comment by JaneSjs** [comment]
Dear @ashish-khankari,

Thank you for showing interest in our project. We appreciate your willingness to help and contribute to SurveyJS. We would be more than happy to work with you.

Please note that SurveyJS is an open source project, which means anyone who is willing to work with us and contribute to our project can fork the repository and make a pull request. 

We will review the pull request and work together to improve our project. Thank you for your cooperation and we look forward to working with you.

Best regards,
Jane

**Comment by ashish-khankari** [comment]
please provide description for bug

**Comment by JaneSjs** [comment]
@ashish-khankari,
Thank you for the update. I discussed this issue with the team and the issue appears to be irrelevant. I'm closing it for now. 

Thank you
