### ISSUE TITLE
Preview. Read-only states need to be improved.

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#6123]
A couple of issues...
— survey must not use a panel as a background
— questions' read-only states

![Image](https://user-images.githubusercontent.com/17025812/235694082-4eecddc3-16a5-4b9b-ab1b-2c11869efa75.png)

**Comment by mikeamelin** [comment]
Design — https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?type=design&node-id=17937-388133&t=5HQr5k5iq6rhKN5x-4

**Comment by JaneSjs** [comment]
+1 T15955 - Better read only display
https://surveyjs.answerdesk.io/internal/ticket/details/T15955
