### ISSUE TITLE
custom widget :expression property

### ISSUE THREAD

**Issue by npltr62** [surveyjs/survey-library#6133]
In my customwidget.js , I add property like this code
`Survey.JsonObject.metaData.addProperties("textwithunit", [
          { name: "unitText", type: "expression" }
      ]);`
the purpose is to use my custom function inside.
thank's

**Comment by JaneSjs** [comment]
Hello,
You can add a custom property of an `expression` type if you wish to create a non-Boolean expressions for this property.
If you with to create a property which accepts [Boolean expressions](https://surveyjs.io/Documentation/Library?id=design-survey-conditional-logic#conditional-visibility) similar to [visibleIf](https://surveyjs.io/Documentation/Library?id=Question#visibleIf) or [enableIf](https://surveyjs.io/Documentation/Library?id=Question#enableIf), set a custom property's type to `condition`.
For more information on available property types, refer to https://surveyjs.io/survey-creator/documentation/property-grid#type.

Please let me know if you have additional questions.
