### ISSUE TITLE
Rating Scale in Matrices: Introduce an option to decrease the Rate item size in Matrices

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#6139]
To reproduce this, run [the demo](https://surveyjs.io/form-library/examples/change-visibility-of-rows-in-matrix-table/reactjs) and select all cars. A matrix appears as follows:
![image](https://user-images.githubusercontent.com/22372972/236142315-142edbd6-3a55-44c4-9552-614679b4811f.png)

Suggestion: add an option to decrease the size of rate items in matrices. For instance: a global `Survey.setting.rateItemSizeMode: small | normal`.

**Comment by novikov82** [comment]
stars: https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=17298-440451&t=4hwf3dmUQP2dKW6z-4
