### ISSUE TITLE
A complete trigger is not executed after updating a Matrix row value

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#6152]
Original issue: T12974 - complete trigger issue with matrix question
https://surveyjs.answerdesk.io/internal/ticket/details/T12974

[Example](https://codesandbox.io/s/happy-sun-x5iij7?file=/src/survey_json.js)
Task: to activate a complete trigger when a Single-Choice Matrix has any of the listed options selected for a specific row:
```
triggers: [
    {
      type: "complete",
      expression:
        "{question2.PGA Tour} anyof ['I do not follow this sport at all', 'I look at this sport when it\\'s in the news or on my timeline, but don’t really keep up with it consistently', 'I keep up with this sport when I can and follow some events']"
    }
]
```
If you select a target value, the Complete button is activated:
![image](https://user-images.githubusercontent.com/22372972/236436749-f4f0f00d-4589-4fdd-b267-74d99cf0a995.png)

Click another row, and notice that a Complete button disappears:
![image](https://user-images.githubusercontent.com/22372972/236436900-8f840902-5220-408e-ba6b-46d9187b7d3c.png)

**Comment by andrewtelnov** [comment]
[Here](https://plnkr.co/edit/FogLVJeSj4kdnpSp) is a simple example.

Thank you,
Andrew
