### ISSUE TITLE
Set "disabled" property for individual items

### ISSUE THREAD

**Issue by mstaselis** [surveyjs/survey-library#616]
### Are you requesting a feature, reporting a bug or ask a question?

feature

### What is the current behavior?

There is no possibility to disable certain answers in "radiogroup" and "checkbox" type questions. Maybe a boolean value could be introduced in a "ItemValue" level that indicates a "disabled" property should be set for individual item.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@mstaselis It is definitely makes sense. I'm adding it into our TODO list. 
Unfortunately, I can't make any estimate on implementing this functionality at the current moment.

Thank you,
Andrew

**Comment by TWKDreamState** [comment]
This would be very useful for me too. I was literally going to post a similar message today!

**Comment by andrewtelnov** [comment]
TO EVERYBODY:
The more people will post here, that they need this functionality, then the most likely we will implement it.
The only question I have, how do you want to disabled/enabled the item? I do not think you want to have it disable all the time. In this case you may just remove it.
What are scenarios when you need this functionality. That would help us as well.

Thank you,
Andrew

**Comment by TWKDreamState** [comment]
For me personally, I would like to be able to offer a series of options to specific questions. Like a ranking for example. And if a ranking is chosen for one of the questions, it becomes unavailable (but greyed out) for the rest of the questions. Hope that makes sense? So, rate the following...

Accomodation 1 2 3 4 5 6 7 8 9 10 -> 5 gets chosen
Price 1 2 3 4 <5> 6 7 8 9 10 -> 5 is now unavailable

This is just an example question - the aim is to get the questions rated in order of preference.

**Comment by mstaselis** [comment]
Hi,
For me, this option is needed to disable certain answers based on previous selections. Meaning, customer can select "Yes" or "No" option in first question. Second question contains available products listed as checkboxes. If customer chooses "No" in first question, second question needs to have certain products disabled. I have a custom trigger set on first question that will disable products on second. Hope this clarifies my use case

**Comment by obitohub** [comment]
Hi,

this functionality is extremely important to us at the moment. What is the status of implementation ? And it's not possible to make a workaround.
Simple situation:
one question e.g. has 3 options to choose from (radiogroup). If some option is chosen then other questions radiogroups some answers should be disabled not to be able to select them. So other question could have e.g. 5 options to choose from but 2 of those will be disabled.

**Comment by andrewtelnov** [comment]
@obitohub To be honest I would love to postponed this functionality for a while. We are working on the first version. The main task - rewrite the way we are working with the custom widgets. The most questions are about them.
I agree it would be cool to have the ability to disabled radio button and checkboxes, but to be honest it not high demand function from one side and it is costy in developement from another side.
We have to rewrite the way we are working with our ItemValue object. We should have a successor class, ItemValueEx for checkbox and radiogroup questions. It will have additionally enabled and enabledIf properties. 
We have to re-write the condition processor. Rght now if there is non empty visibleIf/enableIf properties, the condition processor runs all of them for any value change. Adding enableIf for choices, will definately kill the performance for large surveys. Condition processor should know on which value changes it should react and on which it should do nothing. That is alone a complex task, that we want to implement in anyway.
There are some other small issues that has to be solved.

The dirty workaround - is the following:
1) add enabled (or disabled) property into ItemValue
2) create a custom widget based on Checkbox/Radigroup and react on disabled property
3) onValueChanged event update the disabled property
It is doable, but it will take time

Another dirty workaround - change the choices onValueChanged event and just removed disable items. This will take several lines of code.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@mstaselis @TWKDreamState We do not have enable/disable functionality yet, but we have implemented the ability to change the visibilty. information is [here](https://github.com/surveyjs/surveyjs/issues/1079)

Thank you,
Andrew

**Comment by benkiefer** [comment]
We are currently leveraging the visibility toggle and would love to see enabled/disabled as an alternative. Right now, a user who selects a "none of the above" type option loses all of the other options in the list, and can no longer tell what the other options are.

**Comment by andrewtelnov** [comment]
@benkiefer Could you please explain the issue with "none of the above" in more details? I could not get it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@benkiefer Thank you for sharing the example with us. We will discuss one more time this functionality.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@benkiefer FYI: We will start with [this issue](https://github.com/surveyjs/surveyjs/issues/1442)

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@benkiefer We have made a good progress [here](https://github.com/surveyjs/surveyjs/issues/1447). I am looking for a good general scenario to show case this functionality. Do you have a world-real show case, so we can use for demos?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@benkiefer Yes, the functionality is implemented. Here is [the example](https://next.plnkr.co/edit/VtqzB4p1IsulbNca).
I am looking for a user case to show it in a demo.

Thank you,
Andrew
