### ISSUE TITLE
How to specify a certain name about the i18n lang for the default field in the output JSON

### ISSUE THREAD

**Issue by AkaHanshan** [surveyjs/survey-library#6160]
I want to specify a certain name for the default field in the output JSON for multilingual content, instead of using "default"
such as 
```
     "title": {
      "fr": "3213213",
      "en": "321321"
     }
```
instead of
```
     "title": {
      "fr": "3213213",
      "default": "321321"
     }
```
How can I achieve this?

**Comment by JaneSjs** [comment]
Hi,
Would you please clarify the overall usage scenario? Do you wish to use the En locale as a default, but use the `en` key in the survey JSON model?

**Comment by AkaHanshan** [comment]
Hi @JaneSjs ,Yes, I am not sure if surveyjs can support this JSON format because I want to collaborate with the RN app side. Therefore, I need to specifically specify the key "en" instead of "default". 
However, if it is too complicated, we can also agree that "default" defaults to "en".

**Comment by JaneSjs** [comment]
Hello @AkaHanshan,
Thank you for the update. The `en` is used as a default survey language. It is defined by the [Survey.settings.defaultLocaleName](https://surveyjs.io/form-library/documentation/api-reference/settings#defaultLocaleName) property.

So, if you wish to explicitly define the `en` as a survey language, you can override the default survey locale and set it to another value. For this, modify the [Survey.settings.defaultLocaleName](https://surveyjs.io/form-library/documentation/api-reference/settings#defaultLocaleName) property.
```
import { settings } from "survey-core";

settings.defaultLocaleName = "de";
```
Now, you can define texts for survey elements using the `en` key. To apply the English locale, you need to explicitly set a survey's `locale` property.
```
export const json = {
  logoPosition: "right",
  locale: "en",
  title: {
    default: "Sample Survey",
    fr: "3213213",
    en: "321321"
  },
  pages: [
    {
      name: "page1",
      elements: [
        {
          type: "text",
          name: "question1"
        }
      ]
    }
  ]
};

```
[View Demo](https://codesandbox.io/s/white-leftpad-rgzp9j?file=/src/json.js:0-294)

For more information on survey localization, refer to the following guide:

Please feel free to reactivate this thread if you have any questions or require further assistance.

Thanks
