### ISSUE TITLE
BUG: jquery modern.css not working

### ISSUE THREAD

**Issue by xbln** [surveyjs/survey-library#6163]
<!DOCTYPE html>
<html>
<head>
    <title>My First Survey</title>
    <meta charset="utf-8">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    
    <link href="https://unpkg.com/survey-jquery/modern.min.css" type="text/css" rel="stylesheet">

    
    

    <script type="text/javascript" src="https://unpkg.com/survey-jquery/survey.jquery.min.js"></script>
    <script type="text/javascript" src="index.js"></script>
</head>
<body>
    <div id="surveyContainer"></div>
</body>
</html>

### Are you requesting a feature, reporting a bug or asking a question?
bug

### What is the current behavior?
no css formating

### What is the expected behavior?
css formating "modern.css"

### How would you reproduce the current behavior (if this is a bug)?
use example provided at surveyjs homepage, change index.html line 9 from "defaultV2.min.css" to "modern.min.css" or comment-out line 9 and re-activate line 12

### Specify your

* browser: chrome, edge
* browser version: newest
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: newest

resulted output:

![bug](https://github.com/surveyjs/survey-library/assets/27554937/87573671-1860-47f4-a485-66f04361cf7b)

**Comment by JaneSjs** [comment]
Hi @xbln,
I created the following CodeSandbox demo and confirmed that the 'modern' theme is applied correctly: https://codesandbox.io/s/unruffled-http-8ry4iu.

Please review the demo and let me know if it helps.

**Comment by JaneSjs** [comment]
Hi @xbln,
I created the following demo and imported the modern theme: `https://unpkg.com/survey-jquery/modern.min.css`.
[Code Sandbox jQuery Demo](https://codesandbox.io/s/elegant-hypatia-vr0rrh?file=/index.html)

index.html
```
<!DOCTYPE html>
<html>
  <head>
    <script src="https://unpkg.com/jquery"></script>
    <script src="https://unpkg.com/survey-jquery@1.9.88/survey.jquery.min.js"></script>
    <link
      href="https://unpkg.com/survey-jquery/modern.min.css"
      type="text/css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="./index.css" />
  </head>
  <body>
    <div id="surveyElement"></div>
    <script src="./json.js"></script>
    <script src="./index.js"></script>
  </body>
</html>
```

Everything works fine.
![image](https://github.com/surveyjs/survey-library/assets/22372972/477350af-01a1-45de-ac3e-266172ca5d6b)


Please share a problematic demo for research.

**Comment by moroswitie** [comment]
I can confirm the original problem.

The problem ocurs when you put the loading of the form inside of the head tags.
please see example: https://codesandbox.io/s/interesting-einstein-nnwdkc?file=/index.html

**Comment by JaneSjs** [comment]
Hi @moroswitie,
Thank you for the update. When you load an index.js in the `head` section, the code tries to render a survey within the `surveyElement` element container. However, as the `surveyElement` is not yet rendered, the survey doesn't appear.

If you wish to link an index.js and json in the head section, you need to ensure that the DOM content is loaded before rendering the survey. For this, wrap your JavaScript code in a document ready function provided by jQuery. This function ensures that the code inside it is executed only after the DOM has finished loading. Here's an updated version of your index.js file:
```
$(document).ready(function () {
  const survey = new Survey.Model(json);
  survey.onComplete.add((sender, options) => {
    console.log(JSON.stringify(sender.data, null, 3));
  });

  $("#surveyElement").Survey({ model: survey });
});
```

The updated sample is available at https://codesandbox.io/s/competent-smoke-txswm2?file=/index.js.

I hope this helps. Please feel free to reactivate this thread if you have further questions.
