### ISSUE TITLE
An exception occurs when calling `survey.mergeData()` to define a File question value

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#6166]
Task: preload files to a survey File question.

In v1.9.66, the `survey.mergeData` works correctly and the file appears on survey start: https://codesandbox.io/s/dry-water-fnxrex?file=/src/SurveyComponent.jsx
```
 survey.mergeData({
    files: [
      {
        name: "maxresdefault.jpg",
        type: "image/jpeg",
        content:
          "https://api.surveyjs.io/private/Surveys/getTempFile?name=89c8b259-9e2a-4b18-83e4-3c70f019c962.jpg"
      }
    ]
  });
```
In v1.9.86, the following exception appears: https://codesandbox.io/s/confident-fire-rd9ppk?file=/package.json.
```
file.content.substring is not a function
```

**Comment by andrewtelnov** [comment]
@JaneSjs I beleive I have fixed the issue by this [PR](https://github.com/surveyjs/survey-library/pull/6162/files).

Thank you,
Andrew

**Comment by JaneSjs** [comment]
I confirm that: https://codesandbox.io/s/confident-fire-rd9ppk?file=/package.json.
