### ISSUE TITLE
Dropdown with Lazy Loading: A previously selected item appears instead of the actually selected item

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#6182]
To reproduce the issue, refer to https://surveyjs.io/form-library/examples/lazy-loading-dropdown/reactjs and start typing a country name. Click the PgDn keyboard arrow to select an item. Click Enter - the previous item appears.

https://github.com/surveyjs/survey-library/assets/22372972/657eae60-0467-40e9-aa1e-75b76c4efdd9

**Comment by JaneSjs** [comment]
The issue remains in v1.9.91: https://surveyjs.io/form-library/examples/lazy-loading-dropdown/reactjs.

A customer reported about it at T13435 - Value not assigned when typing on lazy-loaded dropdowns
https://surveyjs.answerdesk.io/internal/ticket/details/T13435.


https://github.com/surveyjs/survey-library/assets/22372972/4c7a786b-f6f1-49a7-b759-e67aacedab76

**Comment by JaneSjs** [comment]
The issue remains in v1.9.96. Reproducible in our online demo: https://surveyjs.io/form-library/examples/lazy-loading-dropdown/reactjs.

**Comment by dongosiddik** [comment]
Hello team,

I am currently retrieving the complete list of countries from a RESTful Web service. My own API returns a very large dataset that takes too much time to load.

I've seen that it's necessary to use "Lazy Loading," but I'm having trouble incorporating it into this JSON. Please correct me.

Additionally, I would like to know what the differences are between version v1 and v2.

Best regards.

`{
          "type": "dropdown",
          "name": "country",
          "title": "Select a country",
          "description": "Une liste complète des pays est interrogée à partir d'un service Web RESTful.",
          "choicesByUrl": {
            "url": "https://surveyjs.io/api/CountriesExample",
            "valueName": "identifier"
          },
          "defaultValue": "FRA",
          "choicesLazyLoadEnabled": true,
          "choicesLazyLoadPageSize": 40

        },`
