### ISSUE TITLE
defaultValues in paneldynamic elements are applied even when the survey is preloaded with data

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#6228]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

defaultValues in paneldynamic elements are applied even when the survey is preloaded with data

### What is the expected behavior?

defaultValues in paneldynamic elements should be applied only when the panel is added

### How would you reproduce the current behavior (if this is a bug)?

In the following example default values are correctly applied for root questions (q4) but wrongly applied for questions inside the paneldynamic (q3,q5)

https://plnkr.co/edit/O58XPAzXQwa0PiH5

### Specify your

* browser: Chrome
* browser version: Version 113.0.5672.92 (Official Build) (arm64)
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.9.88

**Comment by Itagliaf** [comment]
I am experiencing the same problem. Why are some defaultValues applied and some are not?  Is this expected? thank you
