### ISSUE TITLE
Comment Question - The size grip remains when the autoGrow option is enabled

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#6232]
Issue: when the Comment question's [autoGrow](https://surveyjs.io/form-library/documentation/api-reference/comment-field-model#autoGrow) optoin is enabled, the size grip remains available. As a result, customers can resize the visible comment area.
[Example ](https://plnkr.co/edit/eZJwokA6h6vDs0uc)

https://github.com/surveyjs/survey-library/assets/22372972/ce91c191-525c-4773-9d4e-8c90025e5c01

Expected behavior: the `autoGrow` setting behaves as the [survey.autoGrowComment](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#autoGrowComment) property. That is, when the `autoGrow` option is enabled, the size grip is not available and users cannot resize the visible comment area.

https://github.com/surveyjs/survey-library/assets/22372972/57745f81-5591-41a1-b97a-811bf1eaf8e4

**Comment by RomanTsukanov** [comment]
`Comment.autoGrow` and `survey.autoGrowComment` must work identically. To control the resize grip, we can introduce two new properties: `Comment.allowResize` and `survey.allowResizeComment`.

In Survey Creator, use the following captions:

- `Comment.allowResize` - Allow resizing
- `survey.allowResizeComment` - Allow users to resize text areas
