### ISSUE TITLE
Can we use 3rd party component in free version of surveyJS

### ISSUE THREAD

**Issue by HarisMughal** [surveyjs/survey-library#6261]
I was looking at SurveyJS from library docs and in the section Integrate Third-Party Components,
I saw that in order to integrate a 3rd party component you have to use survey-creator which is a paid library.
So I am confused about whether we are allowed to use this or not. If this is a paid feature, it should be in  survey-creator section.

I apologize for asking this question here as I did not find any other place to ask.

**Comment by tsv2013** [comment]
Here is the demo - https://surveyjs.io/form-library/examples/add-custom-question-type-to-form-builder/reactjs
It shows how a 3-rd party component can be used in survey library

**Comment by JaneSjs** [comment]
Hello @HarisMughal,
Thank you for contacting us. You can integrate third-party components to a SurveyJS Form Library. Please refer to the example posted above. In addition, I would recommend that you refer to the corresponding guide depending on your JavaScript platform: 
* [Integrate Third-Party Angular Components](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-angular)
* [Integrate Third-Party React Components](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-react)

Should you have any questions or require further assistance, please feel free to contact us and reopen this thread.

Thanks
