### ISSUE TITLE
Build Error on react js

### ISSUE THREAD

**Issue by Rodgerkilzone** [surveyjs/survey-library#6266]
I have included survey js in my project but it cant build for production when survey library is included, Please assist

Failed to compile.

Parse error on line 1: 
1 * var(--sjs-font-size, calc(2 * var(--base-unit, 8px)))
--------------------------------------------------------^
Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "RPAREN"
CompileError: Begins at CSS selector undefined

**Comment by JaneSjs** [comment]
Hello @Rodgerkilzone,
Thank you for your input. We'll research this issue and post updates at https://github.com/surveyjs/survey-library/issues/6270.

Thank you
