### ISSUE TITLE
correctAnswer as function?

### ISSUE THREAD

**Issue by richarddmorey** [surveyjs/survey-library#6269]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question, and perhaps requesting a feature.

### What is the current behavior?

I believe that the current behaviour is that a `correctAnswer` must be a fixed value.

### What is the expected behavior?

Consider the following quiz:

```
{
    elements: [{
        name: "Q1",
        title: "What is 1 divided by 3?",
        type: "text",
        correctAnswer: 1/3
    }]
}
```

If I test the quiz, it requires the correct answer "0.3333333333333333". What I'd like to do is to provide an function as `correctAnswer` that returns `true` if the answer is correct, and `false` if not; this would let me create quizzes with numerical tolerance, to use regular expressions, or to provide several possible correct answers. For instance:

```
{
    elements: [{
        name: "Q1",
        title: "What is 1 divided by 3?",
        type: "text",
        correctAnswer: x => { x = Number(x); return x>.32 && x<.34; }
    }, {
        name: "Q2",
        title: "Say 'cat' or 'dog'.",
        type: "text",
        correctAnswer: x => { x = String(x).toLowerCase(); return x === 'dog' || x === 'cat'; }
    }, {
        name: "Q3",
        title: "Say 'cat' or 'dog' again.",
        type: "text",
        correctAnswer: x => { return /dog|cat/.test(String(x));}
    }]
}
```

I believe this could be accomplished by changing the following line:

https://github.com/surveyjs/survey-library/blob/907fef84533ab294b915573d1bf7c51f55752cf2/src/question.ts#LL1503C7-L1503C7

to

```
    const isEqual = typeof this.correctAnswer === "function" ? !!this.correctAnswer(this.value) : this.isTwoValueEquals(this.value, this.correctAnswer, !settings.comparator.caseSensitive, true);
```

and analogous changes in `question_matrix.ts` and `question_ranking.ts`.

**Comment by JaneSjs** [comment]
Hello @richarddmorey,
Thank you for your suggestion. You can use the [survey.onIsAnswerCorrect](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onIsAnswerCorrect) function and programmatically calculate whether or not `options.question.value` is correct.

I hope this function can help you. Please feel free to reopen this thread if you have additional questions or require further assistance.

**Comment by richarddmorey** [comment]
Thanks for this. Do you have an example where `survey.onIsAnswerCorrect` is used in this way?

**Comment by richarddmorey** [comment]
I've had a go at this. I did not use `survey.onIsAnswerCorrect` because that seems to not fire when I need it (only when the score is tallied?). Instead, I modified the "Quiz with instant answers" example. 

Plunker: https://plnkr.co/edit/2CMGAmEGXwhLGMIG

The key bit in the survey model is to define some question's correctAnswer as an object, e.g.:

```
{
  "type": "text",
  "name": "q1",
  "title": "Type something that includes the word 'green'.",
  "correctAnswer": {"type": "string", "regex": "green","flags":"i"},
  "enableIf": "{q1} empty"
 }
```

Then, in the code that checks the correct answers, to have some code handling objects (in `index.js`):

```
    if(typeof correctAnswer === "object"){
        if(correctAnswer?.type === "string" && correctAnswer.regex){
            correctAnswer.flags = correctAnswer.flags || '';
            re = new RegExp(correctAnswer.regex, correctAnswer.flags);
            return re.test(givenAnswer);
        }else if(correctAnswer?.type === "number" && (correctAnswer.min || correctAnswer.max)){
            correctAnswer.min = correctAnswer.min || Number.NEGATIVE_INFINITY;
            correctAnswer.max = correctAnswer.max || Number.POSITIVE_INFINITY;
            return givenAnswer <= correctAnswer.max && givenAnswer >= correctAnswer.min ? true : false;    
        }else{
            throw new Error(`Bad object as correctAnswer in question ${q.name}: ${correctAnswer}.`);
        }
    }
```

This seems to work, and I can potentially add more "types".

I have several questions/issues. 

1. There seems to be a bug where if you define a correctAnswer as an object with a key `type: "text"` the correctAnswer comes through as `undefined`. So for instance, this question in the survey model:
```
{
  "type": "text",
  "name": "q1",
  "title": "Type something that includes the word 'green'.",
  "correctAnswer": {"type": "text"},
  "enableIf": "{q1} empty"
 }
```
means that `question.correctAnswer===undefined`. So I just used `type: "string"` but this seems like a bug.

2. Do you see any potential pitfalls/breakages with this approach? Will using objects as correctAnswers break anything?

3. Does this break correct answer tallying, and if so, is there any way to fix it?

**Comment by JaneSjs** [comment]
Hello @richarddmorey,
Please accept my apologies for the delayed response. I reviewed your demo and would like to suggest an alternavite.

The correct answer feature mainly targets quizzes and scored surveys. That is why the `correctAnswer` property receives a value of a question rather than a custom object. Overall, the correct answer option doesn't mean to _validate_ a question value against a specified condition.

To validate a question value, for instance, using regular expressions, please configure validators. Consider this simple survey:
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "q1",
     "title": "Type something that includes the word 'green'.",
     "validators": [
      {
       "type": "regex",
       "text": "Please use the 'green' word ",
       "regex": ".*green.*"
      }
     ]
    }
   ]
  }
 ]
}
```
[View Demo](https://plnkr.co/edit/JJTvPFf0bpYUfoMj)
The 'regex' validator checks if a question value contains the 'green' word. Otherwise, a user cannot submit a value and the validation error occurs. By default, a survey validates answers when a user switches to the next page. If you wish to validate an answer immediately after a user leaves a question, set the [checkErrorsMode](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#checkErrorsMode) property to `onValueChanged`.

You can also configure numeric validators. For more information, please refer to the following demo: [Input Validation](https://surveyjs.io/form-library/examples/javascript-form-validation/reactjs).

Please let me know if this validation option works for you.

**Comment by richarddmorey** [comment]
@JaneSjs - Indeed, I want to use correctAnswer for scored quizzes. I'd like to add the possibility for a range of possible answers. For instance, in numeric answers, they should accept "rounding" error (e.g. any value within .001 of the stated correct answer might be considered correct); for string answers, a regular expression might determine the correct answers (e.g. if the correct answer is the person John Jones Smith, you might accept "Smith", "JJ Smith", "John J. Smith", etc).

These questions will often be generated randomly, with "correct" answers like (say) 0.04858393548454532, so any reasonable quiz will accept rounded answers.

**Comment by JaneSjs** [comment]
Hello @richarddmorey,
Thank you for the update. I believe that the [survey.onIsAnswerCorrect](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onIsAnswerCorrect) function may help. Please consider the following demo.

**Survey JSON**
```
export const json = {
  title: "Sample Quiz",
  completedHtml:
    "<h4>You got <b>{correctAnswers}</b> out of <b>{questionCount}</b> correct answers.</h4>",
  completedHtmlOnCondition: [
    {
      expression: "{correctAnswers} == 0",
      html:
        "<h4>Unfortunately, none of your answers is correct. Please try again.</h4>"
    },
    {
      expression: "{correctAnswers} == {questionCount}",
      html:
        "<h4>Congratulations! You answered all the questions correctly!</h4>"
    }
  ],
  pages: [
    {
      name: "page2",
      elements: [
        {
          type: "text",
          name: "question1",
          title: "Your Name",
          correctAnswer: "John"
        }
      ]
    }
  ],
  showProgressBar: "bottom",
  startSurveyText: "Start Quiz",
  maxTimeToFinish: 25,
  maxTimeToFinishPage: 10,
  showTimerPanel: "top"
};
```
The `onIsAnswerCorrect` function:
```
function checkString(input) {
    const correctValues = ["Smith", "JJ Smith", "John J. Smith"];

    // Check if the input matches any of the specified values
    if (correctValues.includes(input)) {
      return true;
    }

    // Check if the input contains any of the specified values
    for (const value of correctValues) {
      if (input.includes(value)) {
        return true;
      }
    }

    // If none of the checks pass, return false
    return false;
  }
  survey.onIsAnswerCorrect.add((sender, options) => {    
    if (options.question.name !== "question1") return;
    let userAnswer = options.question.value;    
    options.result = checkString(userAnswer);
  });
```
[View Demo](https://codesandbox.io/s/thirsty-hawking-gl9c4r?file=/src/SurveyComponent.jsx)

Please let me know if this option helps.
