### ISSUE TITLE
Custom widget content cleared between page turns

### ISSUE THREAD

**Issue by richarddmorey** [surveyjs/survey-library#6281]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug (I think)

### What is the current behavior?

When I turn a page, the content of my custom widget (a quill.js editor box) is cleared. The contents of `survey.data` remain.

### What is the expected behavior?

I expect the contents of the editor to remain.

### How would you reproduce the current behavior (if this is a bug)?

Please see the following plunker: https://plnkr.co/edit/wT6IYwOeNV7bkrU3

1. Go to page 2,
2. Type in the box
3. Click the "Show data in console" button to ensure data is saved to `survey.data`
4. Go to page 1
5. Click the "Show data in console" button to ensure data is still saved to `survey.data`
6. Go to page 2 - note that box is now empty
7. Click the "Show data in console" button to ensure data is still saved to `survey.data`
8. Type in the box again
9. Click the "Show data in console" button to ensure new data is saved to `survey.data`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  https://plnkr.co/edit/wT6IYwOeNV7bkrU3

### Specify your

* browser: Firefox
* browser version: 113.0.2
* surveyjs platform jquery
* surveyjs version: 1.9.89

**Comment by JaneSjs** [comment]
Hello @richarddmorey,
Please accept my apologies for the delayed reply. I reproduced the issue on your demo. I may need additional time to check why the text is reset in a Quill editor. Please look forward to updates.

**Comment by JaneSjs** [comment]
In the afterRender function, you do not pass a question.value to the Quill editor. To resolve the issue, invoke the `valueChangedCallback` to update an editor's value. Please update your code as follows:
```
afterRender: function(question, element) {
    ...
    let updateValueHandler = function () {
      if (changingValue) return;
      changingValue = true;
      console.log('Setting quill.setContents')
      const v = question.value ? JSON.parse(question.value) : {ops:[]};
      quill.setContents(v);
      changingValue = false;
    };
    question.valueChangedCallback = updateValueHandler;
    updateValueHandler();
    ...
 }
```
The updated demo is available at https://plnkr.co/edit/ZrzhMq96SGz29HrY.

I hope this helps. You may also want to check the following tutorial for more information on how to integrate jQuery widgets to a SurveyJS Form Library: [Create Custom Widget](https://surveyjs.io/form-library/documentation/customize-question-types/create-custom-widgets).
