### ISSUE TITLE
Signature Pad - The signature area overlaps the question area

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#6304]
When a question's max width is set to `100px`, the signature area overlaps the question area.

[View Demo](https://plnkr.co/edit/DQdF1IkzWJKsNuCB)

```
{
 "pages": [
  {
   "name": "add_page_title",
   "elements": [
    {
     "type": "signaturepad",
     "name": "question1",
     "maxWidth": "100px"
    }
   ]
  }
 ]
}
```

![image](https://github.com/surveyjs/survey-library/assets/22372972/d02dd00d-5706-4f56-8ad9-d9f3e86d8cd7)

It is required to automatically adjust the `signatureWidth` setting to fit the question's area. For instance, the following layout produces a valid output:

[View Demo](https://plnkr.co/edit/9awst6EcKBGNmPY1)

```
{
 "pages": [
  {
   "name": "add_page_title",
   "elements": [
    {
     "type": "signaturepad",
     "name": "question1",
     "maxWidth": "100px",
     "signatureWidth": 220
    }
   ]
  }
 ]
}
```
![image](https://github.com/surveyjs/survey-library/assets/22372972/13524543-1dec-4117-bacf-17731c2e7300)

**Comment by novikov82** [comment]
When shrinking the widest option to the narrowest one, it is necessary to calculate the width of the already drawn signature. As long as it fits on the screen - just reduce the area. As soon as it stops decreasing, we begin zoom.
![Image](https://github.com/surveyjs/survey-library/assets/29385489/74b22db0-f24a-4c6d-89f3-70665cfb58f0)

**Comment by novikov82** [comment]
Fixed


![Image](https://github.com/surveyjs/survey-library/assets/29385489/f36163c2-00c9-4014-aeac-4bb2d24e1c7a)
