### ISSUE TITLE
Width of description for boolean

### ISSUE THREAD

**Issue by SwampD0nkey** [surveyjs/survey-library#6317]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
When using a boolean with a question on the left and the swtich on the right, the description can either be under the question text or under the switch.  It cannot be spread across the full width of the question without having the switch on a separate line to the question text. 

### What is the expected behavior?
A third option would be better where the description text can be underneath the question text and displayed across the full width of both the question text and the switch.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version: 113.0.5672.127
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.9.88

**Comment by JaneSjs** [comment]
Hello @SwampD0nkey,
Thank you for your input. Survey questions currently support two options of displaying a description: under the question (title) or under the input. 
![image](https://github.com/surveyjs/survey-library/assets/22372972/a0640417-589e-42a4-b22d-c36d032873e1)

From what I gather, you are requesting an option to display the description under the title and input, as follows:
![image](https://github.com/surveyjs/survey-library/assets/22372972/f7bc30b6-f8b5-4514-baf7-999ed3bd933a)

I forwarded this inquiry to the team for further consideration.

We appreciate your cooperation.

In the meantime, I may suggest that you override question rendering and display a description at a required position. The following demo shows how to override renering for a Radiogroup question: [Custom Question Renderer
](https://surveyjs.io/form-library/examples/create-custom-question-renderer/reactjs).

**Comment by SwampD0nkey** [comment]
Yes, that's exactly what I am suggesting.  I hope the team approves the enhancement.

**Comment by JaneSjs** [comment]
Hello @SwampD0nkey,
Please accept my apologies for the delayed reply.

I discussed this task with our developers. It appears that supporting the desired description layout option, significant changes may be required. Moreover, we though about introducing new description location options. We noted down this inquiry and may consider it in the future.

In the meantime, we recommend that you create a composite question to achieve the desired functionality. Use a panel to combine a Boolean question and a read-only Expression or HTML question. Consider the following example:
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "panel",
     "name": "panel1",
     "elements": [
      {
       "type": "boolean",
       "name": "question1",
       "title": "Are You 21 or Older?",
       "titleLocation": "left",
       "hideNumber": true
      },
      {
       "type": "html",
       "name": "question3",
       "html": "<span class=\"sd-description\">Please select Yes or No to indicate if you are 21 years of age or older.</span>"
      }
     ]
    }
   ]
  }
 ]
}
```
[View Demo](https://plnkr.co/edit/j4hK7YVz1xs0RWBa)

The above configuration produces the following output:
![image](https://github.com/surveyjs/survey-library/assets/22372972/63a354f3-8034-4b5d-be74-586d693d5cb4)

You may also wish to register a custom [composite component](https://surveyjs.io/form-library/documentation/customize-question-types/create-composite-question-types). to use multiple survey elements as a single survey question.
```
Survey.ComponentCollection.Instance.add({  
  name: "booleanwithdescription",   
  title: "Boolean 21 Year",   
  elementsJSON: [
   {
       "type": "boolean",
       "name": "question1",
       "title": "Are You 21 or Older?",
       "titleLocation": "left",
       "hideNumber": true
      },
      {
       "type": "html",
       "name": "question3",
       "html": "<span class=\"sd-description\">Please select Yes or No to indicate if you are 21 years of age or older.</span>"
      }
  ]
});

```
Now, you can use a custom component as a survey question:
```
const json = {  
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "booleanwithdescription",
     "name": "q1"   
    }
   ]
  }
 ]
}
```
[View Demo](https://plnkr.co/edit/7yi0PpL6pKdJNHfm)

I hope either of these alternavites can help you. Should you have any questions or require further assistance, we are here to help.
