### ISSUE TITLE
How to show thank you message after storing response on the server

### ISSUE THREAD

**Issue by thenakliman** [surveyjs/survey-library#6320]
We have a usecase where we want to save user response on the backend and then show thank you page. We have explored onComplete/onCompleting etc; as they are the events and  async, so even if save response is not completed by the server, it show thank you page to the user.

### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the current behavior?
Thank you page is shown even before completing the save at the server.

### What is the expected behavior?
Show thank you page only if backend save is successful.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
    const survey = new Model(json);
    survey.onComplete.add((sender, options) => {
        console.log(JSON.stringify(sender.data, null, 3));
    });
```

### Specify your

* browser: chrome
* browser version: latest 
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: latest

**Comment by JaneSjs** [comment]
Hi @thenakliman,
To display a 'Thank you' page only after data is successfully saved to a database, you can handle the [survey.onComplete](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onComplete) function. Within this function, call the `options.showDataSavingSuccess(text)` function if the data was successfully saved. For more information and a code example, please refer to [Store Survey Results in Your Own Database](https://surveyjs.io/form-library/documentation/handle-survey-results-store#store-survey-results-in-your-own-database).

Should you have any questions or require further assistance, please feel free to reactivate this thread.
