### ISSUE TITLE
Questions that use choicesFromQuestion do not get populated with preloaded data

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#6328]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

questions using choicesFromQuestion (where the dependent question is a checkbox or tagbox) does not get populated with preloaded data (Albania in linked plunk preferredCountries question)

https://plnkr.co/edit/6wvYy4K2sJ7GX3a5?preview

many thanks for your support

**Comment by andrewtelnov** [comment]
Note: It stopped working in v1.9.85. It works in v1.9.84.
