### ISSUE TITLE
Dynamic Panel - A File question value is not cleared regardless of the clearIfInvisible: "onHidden" setting

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#6336]
User Issue: T13428 - Fileupload control not clearing value when inside panel
https://surveyjs.answerdesk.io/internal/ticket/details/T13428
***
[Demo](https://codesandbox.io/s/surveyjs-angular-forked-njr7jp?file=/src/app/components/json.ts:252-282)

To reproduce the issue, set the Boolean question to Yes and upload files to a File question inside a Dynamic Panel.
![image](https://github.com/surveyjs/survey-library/assets/22372972/70d82e67-0665-43b2-a4eb-8e398572b3bb)

Set the Boolean question to No to hide the File question.
![image](https://github.com/surveyjs/survey-library/assets/22372972/189fb4e2-b34d-4a3c-aa55-21eb8e027bc8)

Set the Boolean question to Yes to bring up the File question and notice that the File question inside the Dynamic Panel preserves its value:
![image](https://github.com/surveyjs/survey-library/assets/22372972/e058f098-15b4-4392-a9c4-01ce4f7fd638)

**Comment by andrewtelnov** [comment]
@JaneSjs The user will need to use "onHiddenContainer". We don't have it on question level. Here is [the related issue](https://github.com/surveyjs/survey-library/issues/6381) that adds this new option.

Thank you,
Andrew
