### ISSUE TITLE
Implement a proprietary confirmation dialog

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#6362]
Currently, a survey displays the standard JavaScript [Window confirm](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm) dialog.

[View Demo](https://plnkr.co/edit/AWefjPy7zYDWwwKa)
![image](https://github.com/surveyjs/survey-library/assets/22372972/c7671f8f-0f74-4828-99ef-7ae6625a176f)

It is actually possible to register a custom confirmation dialog. For this, assign a callback function to the [Survey.settings.confirmActionFunc](https://surveyjs.io/form-library/documentation/api-reference/settings#confirmActionFunc). The custom func should display a confirmation dialog and return `true` to confirm deletion and `false` to cancel it.
```
Survey.settings.confirmActionFunc = (message) => {
       return confirm(message); // Activate a custom confirmation dialog
};
```

Suggestion: Consider implementing a confirmation dialog that adheres to the visual style of other survey elements.

**Comment by mikeamelin** [comment]
https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?type=design&node-id=101-15&mode=design

**Comment by dmitrykurmanov** [comment]
see https://www.w3schools.com/tags/tag_dialog.asp

**Comment by dmitrykurmanov** [comment]
creator popup: https://www.figma.com/file/i6Lpc7zkjHtso2oXZV97fo/SurveyJS-Libraries?type=design&mode=design&t=ob7rPqLmS4l6yBLC-0

**Comment by dmitrykurmanov** [comment]
- [ ] need new doc `onApply, onCancel`:
  confirmActionFunc: function (message: string, onApply:()=>{}, onCancel:()=>{}): void {
    showConfirmDialog(message, onApply, onCancel);
  },

**Comment by dmitrykurmanov** [comment]
- [ ]  UI remarks: https://github.com/surveyjs/private-tasks/issues/300
