### ISSUE TITLE
Is Internet Explorer 11 (IE 11) still supported?

### ISSUE THREAD

**Issue by sjanjua** [surveyjs/survey-library#6379]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question

### What is the current behavior?

Is IE 11 still supported with the latest version of the library?

It's not clear in the documentation if IE 11 is still supported. I've seen posts from 4-5 years ago asking this question, and they were told that yes it is supported. However, I've noticed that certain components, such as the Select element, do not work in IE11. Is there a certain version that stopped supporting it?

Having a Supported Browsers page would be helpful, along with which versions of the library work for each browser type. 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Internet Explorer
* browser version: 11
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.9.91

**Comment by andrewtelnov** [comment]
@sjanjua MS stoped supports IE11 a year ago. I tried to run our website in IE11 and then plunker to run our example and it doesn't work. Why do you need it?

Thank you,
Andrew

**Comment by sjanjua** [comment]
@andrewtelnov thanks for the reply. I'm aware that MS support for IE11 has stopped, but my company still needs to support IE11 because some of the hospitals that we write our apps for still use it. We've decided to go a different route since Survey.js will not be able to accommodate some of our needs because of this.

Thanks.
