### ISSUE TITLE
Ranking option disappears on mobile. (2023/06/18)

### ISSUE THREAD

**Issue by jangminhyeok** [surveyjs/survey-library#6380]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

when I drag and drop the ranking option to below question, ranking option disappears

### What is the expected behavior?

It should not be disappeared.

### How would you reproduce the current behavior (if this is a bug)?

Video is attached.

[google_screen_recording_2023-06-18T12-58_19.645Z.webm](https://github.com/surveyjs/survey-library/assets/52376170/2c90812b-8aba-4be6-9f0e-a26f96f65318)

**Comment by JaneSjs** [comment]
Hello @jangminhyeok,
Thank you for contacting us. I tested our online [Ranking demo](https://surveyjs.io/form-library/examples/add-ranking-question-to-form/reactjs) on my cell phone and confirmed that an item doesn't disappear when it is being dragged outside the Ranking question's area.

https://github.com/surveyjs/survey-library/assets/22372972/52de5c53-c93b-4c1d-b8ff-094157fa82a8

If you haven't yet updated your SurveyJS Library version, I would definitely recommend doing so. If the issue persists after the upgrade, please share a reproducible demo with me.
