### ISSUE TITLE
SurveyModel: Rename matrix-related APIs

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-library#6383]
- [x] onMatrixBeforeRowAdded -> onMatrixRowAdding, options.canAddRow -> options.allow
- [x] onMatrixAllowRemoveRow -> onMatrixRenderRemoveButton
- [x] onMatrixAfterCellRender -> onAfterRenderMatrixCell
- [x] Use `options.cellQuestion` and `options.column` instead of `options.getCellQuestion` and `options.columnName`
- [x] Make the `options.row` parameter strongly-typed

**Comment by andrewtelnov** [comment]
@RomanTsukanov  
onMatrixAllowRemoveRow and onGetMatrixRowActions are absolutely different.
onGetMatrixRowActions allows to add/remove actions. onMatrixAllowRemoveRow tells what row can/can't be removed.

We have onAfterQuestionRender, onAfterPageRender, ... I don't want to change onMatrixAfterCellRender.
They are different: onMatrixBeforeRowAdded -> onMatrixRowAdding. onMatrixBeforeRowAdded allows to change cell type and so on. onMatrixRowAdding enable/disable adding.

Thank you,
Andrew
