### ISSUE TITLE
Calling `startTimer` on a start page breaks the timer

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-library#6408]
https://plnkr.co/edit/ixucLpLImd8YLPP3

![image](https://github.com/surveyjs/survey-library/assets/18551316/1723bc57-ca45-46f9-bea7-bc5a3693d48b)

**Comment by andrewtelnov** [comment]
@RomanTsukanov You should not call it. `startTimer();` function will be called automatlically when the start page will be passed.
In your case timer is starting working, but the first page is not showing yet.
You can call startTimer() if the start page is passed or it doesn't exist.

Thank you,
Andrew
