### ISSUE TITLE
text input of type number not working in Firefox and Safari

### ISSUE THREAD

**Issue by BinoDino** [surveyjs/survey-library#6411]
### Hi SurveyJS Team,

I think I found a **bug** on questions of type `text` with input type `number` on the browsers Safari and Firefox. If this was already fixed lately I am sorry for the duplication. But I looked through the changelog before writing and could not find it.

### What is the current behavior?

<ins>Here is an example: </ins>

```json 
{
   "type": "text",
    "name": "number-between",
    "title": {
       "de": "Geben Sie eine Zahl zwischen 1 und 10 ein.",
       "en": "Enter a number between 1 and 10."
     },
    "inputType": "number"
 }
```

<ins>Behaviour in Safari and Firefox:</ins>

![Bildschirmfoto 2023-06-22 um 11 41 26](https://github.com/surveyjs/survey-library/assets/80482900/94b5d2ed-1826-4081-b3f1-ee46bd50be3b)

**Input is moreover not marked as invalid.**

### What is the expected behavior?

It should not be possible to insert text into a field with input type `number`.

### Specify your

* browser: Safari / Firefox
* browser version: 16.5 (Safari) / 95.0 (64-Bit) (Firefox)
* surveyjs platform: angular
* surveyjs version: 1.9.89

**Comment by andrewtelnov** [comment]
@BinoDino These browsers give us an empty value. You can make this question a required and the issue will go away.
Here is [the example](https://plnkr.co/edit/wB8zcShN7fLeNKTU).

Thank you,
Andrew

**Comment by BinoDino** [comment]
Hi @andrewtelnov , 
Thank you very much for you fast reply. Sorry my answer is late. I had to wrap my mind around how I can achieve what I want. 

I just wrote a custom validation function to solve it  following your instructions [here](https://surveyjs.io/form-library/examples/add-custom-input-validation/angular#content-code ).

In case anyone else ever needs it: 

<ins>The survey JSON</ins>

```json
{
    "type": "text",
    "name": "number-between",
    "title": {
        "de": "Geben Sie eine Zahl zwischen 1 und 10 ein.",
        "en": "Enter a number between 1 and 10."
     },
    "validators": [
       {
         "type": "expression",
          "expression": "isValidNumber({number-between})",
          "text": {
             "de": "Die Eingabe ist ungültig.",
             "en": "The input is invalid."
          }
       }
   ]
}
```

<ins>The function</ins>

```typescript
export function isValidNumber([ input ]: string[]) {
  if (!input) return true;
  const regex = /^0(\.[0-9]+)?$|^\-?[1-9][0-9]*$|^\-?[1-9][0-9]*\.[0-9]+$/
  return regex.test(input)
}

FunctionFactory.Instance.register("isValidNumber", isValidNumber);

```

**Comment by andrewtelnov** [comment]
@BinoDino Yes, it could work as well. Thank you for sharing the code wiht us.

Andrew
