### ISSUE TITLE
Survey in Display Mode - A file upload button remains, and the selected Rate option is rendered with a Primary color

### ISSUE THREAD

**Issue by vitexikora** [surveyjs/survey-library#6425]
### Are you requesting a feature, reporting a bug or asking a question?
Buig

### What is the current behavior?
File & Rating input elements are not correctly rendered

### What is the expected behavior?
File input has file-picker icon rendered, that does nothing:
![file](https://github.com/surveyjs/survey-library/assets/14636323/a29387dc-bbd5-427d-9969-9f3391b825cb)

Rating, as the only disabled input, is rendered with primary color:
![rating](https://github.com/surveyjs/survey-library/assets/14636323/57a90da4-a221-4432-ab3b-7d2dcd7a8bc3)

### How would you reproduce the current behavior (if this is a bug)?
Render filled survey in display mode with file & rating inputs

### Specify your

* browser: Firefox
* browser version: 114.0
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.9.79 & 1.9.93 (happens on both)

**Comment by JaneSjs** [comment]
Hello,
Thank you for reporting this issue. However, I require additional clarification from your side. I created the following demo: https://plnkr.co/edit/b9wuY3pgNYnsRxGX.

In read-only mode (`mode: "display"`), the File and Rating questions appear as follows:
![image](https://github.com/surveyjs/survey-library/assets/22372972/4ebe2e22-39c2-4acf-bd44-bfadfceb8bec)

By looking at your screenshot, I suppose you've using custom CSS styles. Would you please share a demo reproducing the issue?

**Comment by vitexikora** [comment]
Hello,

as I said and is notable from the screenshot, it is happening for a **filled-in** survey.
See modified plunker: https://plnkr.co/edit/7gFqOFr7c8RYFyyk?preview

**Comment by JaneSjs** [comment]
Hello @vitexikora,
Please accept my apologies for the delayed reply. Thank you for sharing the demo. I reproduced the issue. 

We will research this issue and update this thread once we have any news to share.
