### ISSUE TITLE
chrome calls my origin page twice (while Firefox do not) since version 1.9.81

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#6438]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

when I try to load the page with the survey my server is called twice when I use chrome. This does not happen in firefox. Does anybody know why? Of course if I remove the survey from the page both browsers run only one request, as expected

See the example https://plnkr.co/edit/lvMq6zfkFukK3wpc?preview and open preview in a pop up window

<img width="1159" alt="image" src="https://github.com/surveyjs/survey-library/assets/454321/b003b417-0a30-4fc6-b6a6-9cf35fd8bb89">
<img width="1344" alt="image" src="https://github.com/surveyjs/survey-library/assets/454321/31f748ca-c2da-4031-8e61-fb4c7287baa1">

thank you

**Comment by masciugo** [comment]
maybe this could be useful https://dev.to/paulcalvano/investigating-duplicate-html-requests-on-a-page-load-2eog

**Comment by masciugo** [comment]
I've just found out that this behaviour was introduced by version 1.9.82. With 1.9.81 was ok: the second text/html request does not get run

https://plnkr.co/edit/lvMq6zfkFukK3wpc

this could be a performance problem for servers that build page dynamically. 

Thank you

**Comment by andrewtelnov** [comment]
@masciugo It is a strange issue. We will take a look.

Thank you,
Andrew

**Comment by masciugo** [comment]
cool. thank you

**Comment by andrewtelnov** [comment]
@masciugo It has been fixed.

Thank you for reporting it!
Andrew
