### ISSUE TITLE
How to actually USE the 'built-in' SVG Icons [in SyrveyJs]?

### ISSUE THREAD

**Issue by CmdrBeavis** [surveyjs/survey-library#6456]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

Not sure as I haven't been able to find any examples showing how to use said icons.

### What is the expected behavior?

n/a

### How would you reproduce the current behavior (if this is a bug)?

Well, since I'm not sure where else my question fits into this template, I'll just ask it here.

I've Googled, I've tried to read the docs, but I can't find any actual "reference" docs anywhere, etc.

I'm just trying to add an icon-checkbox into an html element in my survey json model.. with some text after it. e.g. [√] Thanks for completing this questionnaire!

I was trying to use an Angular Material icon, but if SurveyJs has some built-in, all the better. But again, I can't find any actual usage examples.

TIA! :D

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
Ostensibly it would go into the below HTML. But again, I have no idea what this would / should even look like.

    completedHtml:
        "<p><h4>Thank you!&nbsp;&nbsp;Your response has been submitted.&nbsp;&nbsp;Please allow 20 business days for screening.&nbsp;<br />You will receive an email once your application has been processed.</h4></p>"

```

### Specify your

* browser: Microsoft Edge
* browser version: 114.0.1823.58 (Official build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): Angular 15
* surveyjs version: Can't seem to figure out what my currently-in-use version. :( 
  ( I tried `npm v survey-core`, which gave me LOTS of information, but only shows the CURRENT version, not the one sitting right in my `node_modules` folder! I mean, I'm sure I'm missing something here, but I cannot find the proper command to get the `being used` version of a given package to save my life. )

**Comment by JaneSjs** [comment]
Hello @CmdrBeavis,
If you wish to use built-in icons, you can include them to HTML content as follows: `<svg><use href="#icon-name"></use></svg>`. 

```
<svg><use href="#icon-v2check_24x24"></use></svg>
```

For instance, the following code references the [V2Check_24x24](https://github.com/surveyjs/survey-library/blob/0be44aef43c62f5790bd0c7d56e63b57aa780687/src/images/V2Check_24x24.svg) icon in a `completedHtml` property:
```
export const json = {
  completedHtml:
    '<svg><use href="#icon-v2check_24x24"></use></svg><p><h4>Thank you!&nbsp;&nbsp;Your response has been submitted.&nbsp;&nbsp;Please allow 20 business days for screening.&nbsp;<br />You will receive an email once your application has been processed.</h4></p>',
  elements: [
    ...
  ]
};
```
![image](https://github.com/surveyjs/survey-library/assets/22372972/f19e31d6-89ec-4350-aae2-e18ddd02a0a0)

Built-in cons are available as a part of the currently applied theme. For instance, icons available with the Default V2 theme are placed in the following folder: https://github.com/surveyjs/survey-library/tree/0be44aef43c62f5790bd0c7d56e63b57aa780687/src/images.

You can also review how icons are referenced in [defaultV2Css.ts](https://github.com/surveyjs/survey-library/blob/0be44aef43c62f5790bd0c7d56e63b57aa780687/src/defaultCss/defaultV2Css.ts#L538).

You can also use custom icons.
To register a custom SVG icon and use it in a survey, use the `SvgRegistry.registerIconFromSvg` method. For instance, the following code registers a custom SVG icon with the `icon-test` id.
```
import { SvgRegistry } from "survey-core";

var svg =
  '<svg viewBox="0 0 12 12" xmlns="http://www.w3.org/2000/svg"><path d="M11.35 1.34999L10.65 0.649994L6.05002 5.24999L1.35002 0.649994L0.650024 1.34999L5.25002 6.04999L0.650024 10.65L1.35002 11.35L6.05002 6.74999L10.65 11.35L11.35 10.65L6.75002 6.04999L11.35 1.34999Z"/></svg>';

SvgRegistry.registerIconFromSvg("icon-test", svg);
```
[View Demo](https://codesandbox.io/s/bitter-wind-9g87qf?file=/src/SurveyComponent.jsx)

I hope this information helps. Please let me know if you have any questions or require further assistance.

**Comment by CmdrBeavis** [comment]
Wow, thanks!

Unfortunately I'm now off that contract. That said, this is great info. and if all else fails, will hopefully help others using your library.
