### ISSUE TITLE
duplicated rows in changelog page

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#6458]
### Are you requesting a feature, reporting a bug or asking a question?

bug?

### What is the current behavior?

duplicated rows in changelog

![image](https://github.com/surveyjs/survey-library/assets/454321/afc721e7-f9a0-49a4-ad7b-65d11607caec)

thankyou

**Comment by JaneSjs** [comment]
Hello,
Thank you for bringing our attention to this issue. We've already fix it. Now, a Changelog page appears correctly: https://surveyjs.io/changelog.

Please feel free to contact us if you have any questions or require further assistance.
