### ISSUE TITLE
The File question - A wrong file is removed when the survey.onDownloadFile callback is used

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#6459]
User Issue: T13706 - Upload file deletes wrong file (angular)
https://surveyjs.answerdesk.io/internal/ticket/details/T13706.
*** 
Issue: when the `survey.onDownloadFile` is used, a wrong file appears after deleting a file.

Without the onDownloadFile callback - Works correctly ([View Demo](https://codesandbox.io/s/surveyjs-angular-forked-28nv43?file=/src/app/components/survey.component.ts)).
![image](https://github.com/surveyjs/survey-library/assets/22372972/1c709d52-0fe8-42f8-a2c4-4a02c33a2859)

If you store an image identifier as a file's content, and handle the `survey.onDownloadFile` to display a file preview, a wrong file is removed: [View Demo](https://codesandbox.io/s/surveyjs-angular-forked-f4vhvn?file=/src/app/components/survey.component.ts).
![image](https://github.com/surveyjs/survey-library/assets/22372972/51170678-ef3a-4f5c-a813-866b888d4b7a)

Test Images:
![capibara1](https://github.com/surveyjs/survey-library/assets/22372972/12e1265e-bd59-444e-acf5-db7ea8e36b09)
![capibara2](https://github.com/surveyjs/survey-library/assets/22372972/a4b43bea-53d8-48be-9642-361d6af85a94)
![capibara3](https://github.com/surveyjs/survey-library/assets/22372972/288c3ecc-673c-4e50-8ae9-cce70bca1320)

**Comment by MattPil29** [comment]
thanks for fixing so quickly.
