### ISSUE TITLE
Dynamic Panel's Panel Count Binding Fails to Set at First Run

### ISSUE THREAD

**Issue by PerikiyoXD** [surveyjs/survey-library#6473]
### Are you requesting a feature, reporting a bug or asking a question?
This is a bug report

### What is the current behavior?
When you bind the "Panel count" binding to an expression, on the first run it'll show nothing. 
You have to trigger the dynamic panel once to make it work, which is not an expected behaviour.

Started test (value = nothing)
![Screenshot 2023-07-04 at 14-11-30 Create a Survey Quiz or Poll without Registration Free Survey Tool](https://github.com/surveyjs/survey-library/assets/3116368/d45deb32-7449-46ec-918a-6a75f6e14985)
Add a panel to the dynamic panel (value = 1)
![Screenshot 2023-07-04 at 14-11-43 Create a Survey Quiz or Poll without Registration Free Survey Tool](https://github.com/surveyjs/survey-library/assets/3116368/83fae135-443a-416e-bae7-12c9f7e9874e)
Remove the panel (value = 0)
![Screenshot 2023-07-04 at 14-12-34 Create a Survey Quiz or Poll without Registration Free Survey Tool](https://github.com/surveyjs/survey-library/assets/3116368/984be013-61d0-4908-a7bb-b3301e17be21)

### What is the expected behavior?
When you bind the "Panel count" binding to an expression, on the first run it'll show 0.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://surveyjs.io/create-free-survey
Test code
```json
{
 "logoPosition": "right",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "panel",
     "name": "panel_productos_fito",
     "elements": [
      {
       "type": "expression",
       "name": "product_count"
      },
      {
       "type": "paneldynamic",
       "name": "product_dynpanel",
       "state": "expanded",
       
       "bindings": {
        "panelCount": "product_count"
       },
       "templateElements": [
        {
         "type": "panel",
         "name": "product_panel",
         "elements": [
          {
           "type": "text",
           "name": "product_name"
          }
         ],
         
         "state": "expanded"
        }
       ]
      }
     ]
    }
   ],
   "title": "Dynamic panel's panel count binding doesn't set at first - Bug test"
  }
 ]
}
```

### Specify your

* browser: Firefox
* browser version: 114.0.2 (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: v1.9.96

**Comment by PerikiyoXD** [comment]
Any comments on the status would be appreciated

**Comment by andrewtelnov** [comment]
@PerikiyoXD I will take a look tomorrow/after tomorrow on it and comeback.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@PerikiyoXD It works as expected the expression "product_count" question value is `undefined`. It converts to 0. As result panelCount is 0.
There is no any reason to bind panelCount to expression question. It makes sence to set it to numeric question or dropdown question where choices are numbers.
If you need to show the number of panels in expression, then please use the following JSON: 
```json
      {
       "type": "expression",
       "name": "product_count",
       "expression": "{product_dynpanel.length}"
      },
```
You need to remove the binding.
[Here is the example](https://plnkr.co/edit/P5Lp2tuaHviaAnMv).

Thank you,
Andrew

**Comment by PerikiyoXD** [comment]
Shouldn't the default value of the "product_dynpanel.length" be 0 on initialization? So I just bind the value directly and avoid adding the expression? That's how I interpret the binding.

**Comment by PerikiyoXD** [comment]
Otherwise I just understand that the binding itself is a redundancy that's not working properly.

**Comment by andrewtelnov** [comment]
@PerikiyoXD Binding is needed to bind, for example, a numeric question value and panel count.
The typical scenario: panel dynamic "add"/"remove" panels buttons are hidden. A user setup a number of panels in one question and then fill the data in panels.

Thank you,
Andrew

**Comment by PerikiyoXD** [comment]
Makes sense now, so if I placed a numeric question and I set it to 9 it'll initialize the panel count to 9.

Thank you! I'll close this issue.
