### ISSUE TITLE
Dropdown popup behaves differently when in modal/portal component (v1.9.93 ➡️ v1.9.94)

### ISSUE THREAD

**Issue by Johoseph** [surveyjs/survey-library#6477]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

In v1.9.94, when opening a dropdown question in a Survey that lives within a modal (Reakit Dialog component in this case), the popup position does not align with the dropdown field.

![image](https://github.com/surveyjs/survey-library/assets/49534136/6495050c-d2a8-497b-9bb8-59753d3c1c8d)

### What is the expected behavior?

In v1.9.93, when performing the same action as above, the popup position is correct.

![image](https://github.com/surveyjs/survey-library/assets/49534136/c6757415-62b4-47e4-b9aa-21dcb780afa0)

I am unsure if this behaviour is specifically related to the interaction with the Reakit Dialog component I am using, or generally to all React portal components. I am curious what has changed between patch versions to cause this.

### How would you reproduce the current behavior (if this is a bug)?

Using the below test sandbox, click 'open' to open a Survey in a Reakit Dialog component. Open the dropdown question to see the list popup misaligned with the question.

In `package.json`, decrement the SurveyJS version to `1.9.93` and repeat the above - the popup is correctly aligned with the question.

#### Provide the test code and the tested page URL (if applicable)

Test code/page URL: https://codesandbox.io/s/priceless-jasper-y49kdf

### Specify your

* browser: Chrome
* browser version: 114.0.5735.199
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.9.94

**Comment by andrewtelnov** [comment]
@Johoseph Thank you for providing the reproduciable example. We will work on the fix.
We render popup in survey div instead of root body in the latest versions. We need it for Theme support.

Thank you,
Andrew
