### ISSUE TITLE
Panel css style

### ISSUE THREAD

**Issue by obitohub** [surveyjs/survey-library#648]
### Are you requesting a feature, reporting a bug or ask a question?
question

### What is the current behavior?
Currently you can't style panel with its elements inside with some css.

### What is the expected behavior?
If question type is panel I expect to use css for it ("type": "panel"). E.g. panel could be with grey background, added border and so on.
I tried to implement custom widget for it but panel is not a question so adding "renderAs": "productPanel" to panel and when trying to override css this statement is not executed:
    let classes = options.cssClasses;
    if ( options.question.renderAs === "productPanel" ) {
        classes.root = 'productPanel';
    }

Maybe there is some easier way to achieve this ? In browsers html I see that for panel there are two lines generated:
<div. style="vertical-align: top; display: inline-block; width: 100%;"><div. style="padding-left: 20px;">

Maybe in second div there could be "class" tag added to define css ?

**Comment by andrewtelnov** [comment]
Here is the styles that you can override for panel right now:
```js
  panel: {
    title: "sv-title sv-panel__title",
    titleExpandable: "sv-panel__title--expandable",
    titleOnError: "sv-panel__title--error",
    description: "sv-description sv-panel__description",
    container: "sv-panel sv-row__panel",
    content: "sv-panel__content",
    icon: "sv-panel__icon",
    iconExpanded: "sv-panel__icon--expanded",
    footer: "sv-panel__footer",
    requiredText: "sv-panel__required-text",
    number: "sv-question__num",
  },
```

Thank you,
Andrew
