### ISSUE TITLE
The "+" in numbers starting with "+" will be ignored in custom function expression

### ISSUE THREAD

**Issue by AkaHanshan** [surveyjs/survey-library#6505]
In dropdown in paneldynamic, the "+" in the value of choices will be ignored, for example, "+852" becomes 852 in expression
here is an example:
https://codesandbox.io/s/boring-david-6p65gq?file=/src/SurveyComponent.jsx

**Comment by andrewtelnov** [comment]
@AkaHanshan To avoid conversion, please use the '#' before the value. Here is the updated expression:
"regionPhoneValidate({#question1[0].countryCode},{question1[0].mobileNumber})"

Thank you,
Andrew

**Comment by AkaHanshan** [comment]
@andrewtelnov  Thanks for your reply 😁
