### ISSUE TITLE
Locale doesn't update for `editText`

### ISSUE THREAD

**Issue by Sandarr95** [surveyjs/survey-library#6523]
### Are you requesting a feature, reporting a bug or asking a question?
Bug report

### What is the current behavior?
`editText` does not update locale on locale change while being rendered.

![](https://github.com/surveyjs/survey-library/assets/6546993/9af62487-223e-40de-aa65-e08f47102163)

### What is the expected behavior?
`editText` should update locale on locale change while being rendered.
In the image above this should have resulted in the text "Bewerk" being shown, not "Edit".

### How would you reproduce the current behavior (if this is a bug)?
* Go to https://surveyjs.io/service/mysurveys
* Create a new survey
* In the JSON-editor, paste:
```json
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "question1"
    }
   ]
  }
 ],
 "previewText": {
  "nl": "Voorbeeld",
  "en": "Preview"
 },
 "showPreviewBeforeComplete": "showAnsweredQuestions"
}
```
* Click on the preview tab
* Answer question1 with something
* Click on Preview
* Change the language to Dutch

Now the send button changes languages as expected, the edit text does not.

### Specify your

* browser: Firefox
* browser version: 115
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.9.79 (locally, I don't know which version runs on surveyjs.io)

**Comment by andrewtelnov** [comment]
@Sandarr95 It is fixed by the commit above.

Thank you,
Andrew
