### ISSUE TITLE
Let dropdown search-on-type match characters ignoring typographical marks (A when using Á, Ä...)

### ISSUE THREAD

**Issue by PerikiyoXD** [surveyjs/survey-library#6525]
### Are you requesting a feature, reporting a bug or asking a question?
A feature

### What is the current behavior?
It will perfect-match the string

### What is the expected behavior?
It will match a non typographic mark version of the string
'Álava' -> 'Alava'

### How would you reproduce the current behavior (if this is a bug)?
N/A

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://surveyjs.io/create-free-survey

Test code
```
{
 "locale": "es",
 "title": {
  "es": "typographic marks test"
 },
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "dropdown",
     "name": "question1",
     "choices": [
      {
       "value": "Item 2",
       "text": {
        "es": "Álava"
       }
      },
      {
       "value": "Item 3",
       "text": {
        "es": "Mérida"
       }
      },
      {
       "value": "Item 4",
       "text": {
        "es": "Cáceres"
       }
      }
     ]
    }
   ]
  }
 ],
 "showQuestionNumbers": "off"
}
```

### Specify your

* browser: Firefox
* browser version: 114.0.2 (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: v1.9.97

**Comment by PerikiyoXD** [comment]
Any feedback is much appreciated

**Comment by PerikiyoXD** [comment]
I've made some simple JS function that does what I want

```js
function removeDiacritics(text) {
  if (typeof text !== 'string') {
    throw new Error('Input should be a string.');
  }
  
  return text.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}

console.log(removeDiacritics('Ávila')); // Output: Avila
console.log(removeDiacritics('Cáceres')); // Output: Caceres
console.log(removeDiacritics('Tórrido del Zujar')); // Output: Torrido del Zujar

```

**Comment by PerikiyoXD** [comment]
I hope we can make this into a PR with proper code placement, this impacts latin-derived diacritic-featured languages. Thank you for your time!

**Comment by andrewtelnov** [comment]
@PerikiyoXD Did you make a PR? We are going to discuss it on our sprint planning next week.

Thank you,
Andrew

**Comment by PerikiyoXD** [comment]
I haven't yet, I will investigate the codebase and then create a basic overview of where, what and how to place the code.

Thank you for showing interest of adding this feature request!

**Comment by PerikiyoXD** [comment]
I've found a proper location and made a quick fix. This seems to fix the issue.

Inserted `.normalize("NFD").replace(/[\u0300-\u036f]/g, "")` on `src/list.ts@hasText`

**Comment by PerikiyoXD** [comment]
Opened a PR.

**Comment by PerikiyoXD** [comment]
Thank you!

How may I configure the callback for the SurveyJS Creator? This means, if I want to use the callback, how may I access it?
I can't seem to find the right way to configure it.

**Comment by PerikiyoXD** [comment]
@andrewtelnov ?
