### ISSUE TITLE
Custom message on completedBefore survey is not showing on loading Survey from the service

### ISSUE THREAD

**Issue by SteBantoa** [surveyjs/survey-library#6552]
Hi all,
I found a bug which won't display custom `completedBefore` message on a submitted survey page loaded.

I've created a CodeSandBox build to test it out:
https://codesandbox.io/s/gracious-aryabhata-tpxz3v

Shown message is:
"I nostri records mostrano che hai già completato questo questionario."

even if on the survey edit field "Markup to show if the user already filled out this survey" I set a custom message.

* browser: Chrome
* browser version: 114.0.5735.198 (x86_64)
* surveyjs platform: jQuery
* surveyjs version: 1.9.98

**Comment by andrewtelnov** [comment]
@SteBantoa I see the issue. The completedBeforeHtml shows before the Survey JSON data is loaded from the server.
We will take a look and comeback to you.

Thank you,
Andrew
