### ISSUE TITLE
Page paddings (in different modes)

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#6578]
- [ ] padding below title

![Image](https://github.com/surveyjs/survey-library/assets/17025812/415d3fd3-4563-44c7-adbb-19dfb69a9f00)

- [ ] padding above button

![Image](https://github.com/surveyjs/survey-library/assets/17025812/67bd0a89-b5a8-4c6f-b089-8b5d9dced2f4)

**Comment by mikeamelin** [comment]
Additional comments...

— title's padding depends on Survey Structure — they should be the same
— need to check padding for title and button for both appearance — default and panelless

Here is prototype — https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?type=design&node-id=175-235683&mode=design

**Comment by tsv2013** [comment]
Additional design link - https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?node-id=263%3A487260&mode=dev
Check navigation buttons top margin for pages with single question
