### ISSUE TITLE
FireFox unable to validate date input with 5 digit year against a maximum value

### ISSUE THREAD

**Issue by TheJayMann** [surveyjs/survey-library#6633]
### Are you requesting a feature, reporting a bug or asking a question?

This is a bug report.

### What is the current behavior?

On FireFox (LibreWolf v109, also tested with FireFox 116), when adding a single line input with type of date, and setting a max date, when (accidentally) typing in a five digit year, validation passes even though the year is larger than the set max date value. e.g., setting max date value of 2023-12-31 and submitting a value of 20205-10-10 will pass validation and allow the survey to be submitted.

### What is the expected behavior?

In the example above, given that 20205-10-10 is a later date than the declared maximum date of 2023-12-31, a validation error message should be displayed, preventing the survey from being submitted.

### How would you reproduce the current behavior (if this is a bug)?

See example above, as well as test code below.

#### Provide the test code and the tested page URL (if applicable)

Test code

```json
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "question36",
     "title": "What day is today?",
     "inputType": "date",
     "min": "2023-01-01",
     "max": "2023-12-31"
    }
   ]
  }
 ]
}
```

### Specify your

* browser: LibreWolf and FireFox
* browser version: 109 and 116
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: 1.9.101

### Other notes

The issue appears to be the custom validation logic provided by SurveyJS, as default validation logic provided by FireFox appears to work properly.  When the custom validation is attempting to compare the date value entered against the declared max valid date, the text versions of these values are attempted to be parsed as a Date object, and it appears that FireFox, when parsing a date value with a year having more than 4 digits returns "Invalid date," and this appears to allow the validation to succeed.

This does not appear to be an issue with Chromium browsers, as the date input does not allow entering a year value larger than 4 digits; when a fifth digit is added, the first digit is removed.  Also, if a five digit year were possible, parsing the value as a Date object appears to work in Chromium browsers, with the Date object having a 5 digit year.

**Comment by JaneSjs** [comment]
Hello @TheJayMann,
Thank you for sharing a sample. A single-line input question uses the standard HTML `input` element. The `inputType` Text question's property value is assigned to the `type` property of the underlying `<input>` element. However, it appears that the `input type="date"` allows manually setting a greater value regardless of the specified `max` attribute when being used on a Firefox browser.

To validate this, you can proceed to the following MDN article: [Setting maximum and minimum dates]
(https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#setting_maximum_and_minimum_dates). 
![image](https://github.com/surveyjs/survey-library/assets/22372972/430cc47c-72b4-40e4-9376-7d10fcd78e2c)

As an option, you can register the [Inputmask widget](https://surveyjs.io/form-library/examples/control-data-entry-formats-with-input-masks/reactjs#content-code).
```
{
  elements: [
    {
      name: "date",
      type: "text",
      title: "Date:",
      inputMask: "datetime",
      inputFormat: "yyyy-mm-dd",
      min: "2023-01-01",
      max: "2023-12-31"
    }
  ],
  showQuestionNumbers: false,
  questionTitleLocation: "left"
}
```
[View Demo](https://codesandbox.io/s/heuristic-jepsen-zkltpk?file=/src/json.js)

It will format user input following the `inputFormat` pattern and display an error message if a supplied value goes beyond the min/max values.

I hope this helps. Please feel free to reactivate this thread if you have additional questions.

**Comment by TheJayMann** [comment]
The inputmask widget will most likely work, but I believe it will not be desirable, especially given that it appears to be required to display as year-month-day, rather than the user's preferred date display.  This appears to remove the built in date picker as well.  Also, the previous analysis is not entirely correct; while the MDN sample you tried allows typing in a year date larger than specified, if you attempt to submit the data with the submit button, FireFox will prevent the submission.  Meanwhile, the custom validation logic in Survey JS itself will attempt to parse the text value as a date and FireFox javascript engine will fail to parse the date.  I did noticed that the `valueAsDate` property will get the date value without issue.

**Comment by TheJayMann** [comment]
After looking into this a while, I managed to forge a solution/workaround.
```javascript
/**
 * @param {Survey.SurveyModel} sender
 * @param {object} options
 * @param {Survey.Question} options.question
 * @param {string} options.error
 * @param {any} options.value
 * @param {string} options.name
 */
function addMaxValidation(sender, options) {
  if (options.question instanceof Survey.QuestionTextModel) {
    if (options.question.inputType === "date" || options.question.inputType === "datetime-local") {
      if (isNaN(new Date(options.value))) {
        var input = document.getElementById(options.question.inputId);
        if (input instanceof HTMLInputElement && input.validity.rangeOverflow) {
          var maxValue = new Date(input.max);
          if (isNaN(maxValue)) {
            maxValue = input.max;
          }
          options.error = options.question.maxErrorText.replace("{0}", maxValue);
        }
      }
    }
  }
}

...

survey.onValidateQuestion.add(addMaxValidation)
```

Essentially, this adds an extra layer of validation for `date` and `datetime-local` (I skipped `datetime` as most browsers no longer support this type), check if the built in browser validation says the value is too large, and, if so, display the assigned max error text.  In my minor testing, this appears to work.
