### ISSUE TITLE
Question: Signature Pad Widget

### ISSUE THREAD

**Issue by BinoDino** [surveyjs/survey-library#6643]
Hi SurveyJS team, 
I would like to know if the signature pad widget is supported on tablets (e.g. iPad) in a way that allows users to sign with a pen (e.g. Apple Pencil).

Thank you very much in advance.

**Comment by JaneSjs** [comment]
Hello @BinoDino,
Yes, the Signature Pad widget is supported on tablets, and you can use it on an iPad device with an Apple Pencil. To ensure correct operation of the Signature Pad widget, please use the most recent version of SurveyJS libraries ([v1.9.101](https://surveyjs.io/stay-updated/release-notes)).

Should you have any questions or require further assistance, we are here to help.
