### ISSUE TITLE
Question title has wrong location if descriptionLocation is "underInput"

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-library#6661]
{
            name: "q1",
            type: "text",
            title: "title & description underInput",
            titleLocation: "bottom",
            description: "question-description",
            descriptionLocation: "underInput",
          },

https://www.figma.com/file/i6Lpc7zkjHtso2oXZV97fo/SurveyJS-Libraries?type=design&node-id=19407-576465&mode=design&t=GwwWkoM3b4lxRMhW-4

![image](https://github.com/surveyjs/survey-library/assets/14936841/17be4577-11f7-45f8-989b-1edb10895bd5)

**Comment by novikov82** [comment]
it is not a bug
