### ISSUE TITLE
hasOther has different behavior in dropdown question than dropdown cell in matrixdynamic 

### ISSUE THREAD

**Issue by madceb** [surveyjs/survey-library#670]
Hello,

if a dropdown question has the hasOther option activated when submitted the value in the result Json is as: 
- questionname=Other 
- questionname-comment=text in other

But a dropdown cell in a matrixdynamic question the result it is as:
- questionnamecell=text in other

Is this an issue?

Regards,

**Comment by andrewtelnov** [comment]
@madceb We set the property storeOthersAsComment to false (true by default) for radiogroup/checkbox/dropdown questions. Do you have a problem with that?

Thank you,
Andrew

**Comment by madceb** [comment]
Hello @andrewtelnov 

I prefer to have it as in the first option that it is the default behavior:
- questionname=Other
- questionname-comment=text in other

but in the cellType, with storeOthersAsComment to true or false, it still get the same with no second property with the comment.

Regards

**Comment by andrewtelnov** [comment]
We have implemented support for ``survey.storeOthersAsComment`` property in [dynamic/dropdown matrices](https://github.com/surveyjs/survey-library/issues/2401). It will be available from [v1.8.4](https://surveyjs.io/WhatsNew#v1.8.4).

Thank you,
Andrew
