### ISSUE TITLE
Add preview images to the Themes & Styles help topic

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-library#6702]
It would be great if the topic contained a preview of all 40 themes with their names.

**Comment by mikeamelin** [comment]
Prototype — https://www.figma.com/file/BxElnWdlOzSNiFZjNqOWRO/Documentation?type=design&node-id=302-135694&mode=design&t=0xhvSR9yF3Kks9e9-0

**Comment by novikov82** [comment]
@mikeamelin we need the design to show all 40 themes

**Comment by mikeamelin** [comment]
A new prototype — https://www.figma.com/file/BxElnWdlOzSNiFZjNqOWRO/Documentation?type=design&node-id=302-135694&mode=design

... and preview —

[Panelless.zip](https://github.com/surveyjs/survey-library/files/12700066/Panelless.zip)
[Default.zip](https://github.com/surveyjs/survey-library/files/12700067/Default.zip)
