### ISSUE TITLE
confirmActionFunc is not supporting a compromised async function

### ISSUE THREAD

**Issue by jiyuan12354** [surveyjs/survey-library#6736]
Our company is bought surveyjs Pro, and we use the surveyjs to render a questionare form. surveyjs is powerful，but I want to post a issue here which other team may also interested in. 

surveyjs did provide a property named `confirmActionFunc` , attempt to provide a customized feature for users to overwrite the default window.comfirm, but I checked the source code, surveyjs don't accept any promised/async confirmActionFunc in this case...and you may know user can't provide a sync function to get confirm result immediately， so the case is confirmActionFunc is not work for the real case

### This is requesting a feature

I am requesting a feature, related to `confirmActionFunc`, I'd like overwrite the default `confirmAction` function with a promised customized `confirmAction`

### What is the current behavior?

panel will be removed no matter my promised confirmActionFunc execute result, becasue surveyjs will regard the confirmActionFunc as a sync function which return true/false immediately

### What is the expected behavior?

I’d like to see that surveyjs supporting the async confirmActionFunc, so that I can render my own customized confirm modal as I want

**Comment by andrewtelnov** [comment]
@jiyuan12354 Please review [this PR](https://github.com/surveyjs/survey-library/pull/6739).

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Here is the example of using
```js
//Example of using
Survey.settings.confirmActionAsyncFunc = (message, resCallback) => {
  settimeout(() => {
    if(confirm(message)) resCallback(true);
  }, 300)
return true; //should return true
};
```

**Comment by jiyuan12354** [comment]
Thanks @andrewtelnov  maybe I am not the expert. could you tell, based on this branch `features/6736-confirmActionAsync` how could I package the survey-core in my local env, I want to test it the pr in my local env

**Comment by jiyuan12354** [comment]
I ran `yarn build_prod` and copy the build/survey-core to my projects node_modules, seems work fine.
Thanks @andrewtelnov  again, please let me know if you release the new package to npmjs.com

**Comment by andrewtelnov** [comment]
@jiyuan12354 Great! We release every week. This PR should be merged with master today or on Monday. We commonly release every Tuesday/Wednesday.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@jiyuan12354 We are goint to release new version today. I have just renamed confirmActionAsyncFunc into confirmActionAsync. Please take it into account. Here is [my commit](https://github.com/surveyjs/survey-library/commit/444e0d8b09ceafbbe10118f487bde9d6843b74da).

Thank you,
Andrew
