### ISSUE TITLE
No space appears for a Progress Bar and the last question on a page

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#6738]
T14281 - Bug - Progress bar
https://surveyjs.answerdesk.io/internal/ticket/details/T14281
***
v1.9.102 [View Demo](https://codesandbox.io/s/quizzical-lake-s3n69h?file=/package.json)
![image](https://github.com/surveyjs/survey-library/assets/22372972/d6eb9cf9-4939-45d3-b7b7-e86e64c8760b)

v1.9.103 [View Demo](https://codesandbox.io/s/crazy-jones-8wgrnw?file=/package.json)
![image](https://github.com/surveyjs/survey-library/assets/22372972/bf7cb865-e7f7-47a3-be44-d5b3ca5c8cfe)

**Comment by mikeamelin** [comment]
Bottom progress bar — https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?type=design&node-id=774-182287&mode=design
