### ISSUE TITLE
It is impossible to change a default value of the ChoicesRestful.path property

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#6766]
### Are you requesting a feature, reporting a bug or asking a question?

bug/question

### What is the current behavior?

In the following plunk I was able to customize `allowEmptyResponse` property defaultValue (as you can see I do not get any error in q1). But I was not able to do the same for the `path` property (q2 should return an empty list)

https://plnkr.co/edit/vwNYDij400GUSQyy

thank you

**Comment by JaneSjs** [comment]
Hello @masciugo,
From what I gather, you wish to programmatically specify the default value for the [ChoicesRestful.path](https://surveyjs.io/form-library/documentation/api-reference/choicesrestful#path) property.
However, the following code doesn't work:
```
Survey.Serializer.getProperty("choicesByUrl", "path").defaultValue = "list"
```

With the `defaultValue` set to `list`, you expect the second question to display an empty list of items, as if the `list` value is specified at the level of the `choicesByUrl` setting:
![image](https://github.com/surveyjs/survey-library/assets/22372972/32a782c1-d139-4972-b25d-8f40dcac9e35)

We will research this issue and update you shortly.

Thanks

**Comment by masciugo** [comment]
Hi guys. I tried but it does not seems fixed to me

https://codesandbox.io/s/great-solomon-yvnwvc?file=/src/SurveyComponent.jsx

q2 should not provide any choices as 'list' path does not exists in the service response

(I switched to codesandbox because plunker seems not very responsive)

**Comment by andrewtelnov** [comment]
@masciugo I found the reason. We did not clear properties correctly. I have added unit test and fix it. Here is [the PR](https://github.com/surveyjs/survey-library/pull/7070). We will include the fix into the version we will release next week.

Thank you,
Andrew
