### ISSUE TITLE
Read-only and Preview Mode: Redesign: Root Issue

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-library#6776]
We need to distinguish the disabled and read-only (display) mode of survey questions.
@mikeamelin created design for this states:
- [ ] Preview. Read-only states need to be improved. #6123
- [ ] Correct inactive (disabled or read-only) states for all questions. #6262

Details — https://docs.google.com/document/d/1xE_qzePrSRulQa7VS9ambu8JdXJsFBwDt1eg2Ue8ZFM/edit?usp=sharing
Design — https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?type=design&node-id=101-7&mode=dev

### Dev TODO

- [x] radio-group
- [x] single-input
- [x] rating
- [x] rating-stars ( @novikov82  )
- [x] rating-smileys ( @novikov82  )
- [x] checkbox-group ( @dmitry-kurmanov )
- [x] dropdown ( @novikov82  )
- [x] tag-box ( @novikov82  )
- [x] yes/no (boolean) ( @dmitry-kurmanov )
- [x] boolean:radio ( @dmitry-kurmanov )
- [x] boolean:checkbox ( @dmitry-kurmanov )
- [x] file-upload ( @dmitry-kurmanov )
- [x] image-picker ( @dmitry-kurmanov )
- [x] ranking ( @dmitry-kurmanov )
- [x] comment ( @novikov82  )
- [x] multiple-text ( @novikov82  )
- [x] ~signature~ can not implement ( @novikov82  )
- [x] matrix single choice ( @novikov82  )
- [x] ~matrix multiple choice~ need to do nothing
- [x] #8026
- [x] support old themes (modern, ... etc)

**Comment by JaneSjs** [comment]
+1 T15483 - Make boolean question appear with color in read-only mode
https://surveyjs.answerdesk.io/internal/ticket/details/T15483

**Comment by JaneSjs** [comment]
+1 T14754 - Override checked icon when in survey read only mode
https://surveyjs.answerdesk.io/internal/ticket/details/T14754

**Comment by JaneSjs** [comment]
+1 T15955 - Better read only display
https://surveyjs.answerdesk.io/internal/ticket/details/T15955

**Comment by JaneSjs** [comment]
+1 
T16282 - in display mode the yes/no not clear
https://surveyjs.answerdesk.io/internal/ticket/details/T16282

**Comment by JaneSjs** [comment]
T17346 - Make font color of readonly values darker?
https://surveyjs.answerdesk.io/internal/ticket/details/T17346

**Comment by mikeamelin** [comment]
**READ-ONLY**

- [ ] the border should be inside
![Screenshot 2024-04-02 at 09 18 02](https://github.com/surveyjs/survey-library/assets/17025812/1554cc44-90b0-4972-9ab1-f4872bfecc7c)

- [ ] title is missed
- [ ] looks like unnecessary pixels are on the bottom
![Screenshot 2024-04-02 at 09 19 07](https://github.com/surveyjs/survey-library/assets/17025812/214c8bb6-bfe8-4edf-9ea0-154d5d5d1f65)

**PREVIEW**

- [ ] there shouldn't be any pixels 
![Screenshot 2024-04-02 at 09 23 27](https://github.com/surveyjs/survey-library/assets/17025812/debb3bc9-c48e-4317-8684-b3eddbcdad03)

- [ ] unselected image should be semi-transparent
![Screenshot 2024-04-02 at 09 23 56](https://github.com/surveyjs/survey-library/assets/17025812/373f184c-701e-4d54-85e1-af1f2e3f7fb6)

**Comment by mikeamelin** [comment]
- [ ] colorful smiley rating — wrong color/opacity for inactive items

![Screenshot 2024-04-04 at 09 58 08](https://github.com/surveyjs/survey-library/assets/17025812/20445f6a-010c-431a-92bd-0605f498a44d)

- [ ] matrix with alt rows

![Screenshot 2024-04-04 at 10 01 53](https://github.com/surveyjs/survey-library/assets/17025812/929a1755-56f3-41f3-a951-9599d5757ab9)

- [ ] dynamic matrix

![Screenshot 2024-04-04 at 10 02 18](https://github.com/surveyjs/survey-library/assets/17025812/83681199-1fe4-414d-8350-626ecc025ef5)

- [ ] no button is necessary at all

![Screenshot 2024-04-04 at 10 30 56](https://github.com/surveyjs/survey-library/assets/17025812/d9cf4568-10b4-4a2a-aa3c-96999989bb15)

- [ ] i think we should use same way as for File Upload

![Screenshot 2024-04-04 at 10 31 23](https://github.com/surveyjs/survey-library/assets/17025812/449e5707-1a86-4d5d-ab38-e77e9bbf2abd)

- [ ] dynamic panel. Let's hide footer for one record
![Screenshot 2024-04-04 at 10 33 15](https://github.com/surveyjs/survey-library/assets/17025812/194d970f-454f-4402-9179-b10553e67202)

**Comment by mikeamelin** [comment]
**PREVIEW**

- [ ] colorful smiley rating

![Screenshot 2024-04-04 at 10 52 17](https://github.com/surveyjs/survey-library/assets/17025812/e7961975-3f1d-4f12-9de0-9d2370ceeb0f)

- [ ] text color
- [ ] no button

![Screenshot 2024-04-04 at 10 52 37](https://github.com/surveyjs/survey-library/assets/17025812/455fce31-0d7f-4f33-aad9-45b0536ba54a)

- [ ] no border
- [ ] text color
- [ ] text — some thing like No signature

![Screenshot 2024-04-04 at 10 53 53](https://github.com/surveyjs/survey-library/assets/17025812/07435bbd-bb36-4c6f-8fdf-a9c15c4802cc)

- [ ] radiobutton appearance 
![Screenshot 2024-04-04 at 10 54 17](https://github.com/surveyjs/survey-library/assets/17025812/28aee01e-f1ea-4773-b882-64cea36ea139)

- [ ] dynamic matrix
![Screenshot 2024-04-04 at 10 54 31](https://github.com/surveyjs/survey-library/assets/17025812/2377c338-dc60-4ba1-977d-456e5988908a)

- [ ] nested panel
![Screenshot 2024-04-04 at 10 56 19](https://github.com/surveyjs/survey-library/assets/17025812/5152cbeb-3c34-4db8-b4ec-dcc7508f9812)

- [ ] dynamic matrix. No records — text color

![Screenshot 2024-04-04 at 11 01 03](https://github.com/surveyjs/survey-library/assets/17025812/4b3313af-f822-4c09-94be-fef784634ed1)

**Comment by JaneSjs** [comment]
+1 https://github.com/surveyjs/survey-library/issues/8055

**Comment by mikeamelin** [comment]
- [ ] there we should use another background color for read-only 


https://www.figma.com/file/i6Lpc7zkjHtso2oXZV97fo/*-Components?type=design&node-id=19925-1262932&mode=design&t=kUI5IeJ7yhJgoE6N-4
![Image](https://github.com/surveyjs/survey-library/assets/17025812/1ce69717-400e-4c24-bcd9-78998c59736e)

https://www.figma.com/file/i6Lpc7zkjHtso2oXZV97fo/*-Components?type=design&node-id=19925-1258280&mode=design&t=kUI5IeJ7yhJgoE6N-4
![Image](https://github.com/surveyjs/survey-library/assets/17025812/9bbfdf3d-49e2-420c-9e60-02b116515250)


https://www.figma.com/file/i6Lpc7zkjHtso2oXZV97fo/*-Components?type=design&node-id=18229-396599&mode=design&t=kUI5IeJ7yhJgoE6N-4
![Image](https://github.com/surveyjs/survey-library/assets/17025812/2dc69f70-5528-47f8-908c-2abdc09ec28a)

- [ ] let's change background color for alt row everywhere

https://www.figma.com/file/i6Lpc7zkjHtso2oXZV97fo/*-Components?type=design&node-id=19925-1340814&mode=design&t=kUI5IeJ7yhJgoE6N-4
![Image](https://github.com/surveyjs/survey-library/assets/17025812/ccc2130e-8a4f-4e77-ab76-3f2708cae27e)
