### ISSUE TITLE
Knockout&jQuery: Validator text containing an expression doesn't update properly on value change

### ISSUE THREAD

**Issue by FHourmy** [surveyjs/survey-library#6790]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### Specify your

* surveyjs platform (angular or react or jquery or knockout or vue): jquery 
* surveyjs version: 1.9.104

### What is the current behavior?
Validator text containing an expression doesn't update properly on value change (version 1.9.104). 
It used to work (tested on 1.8.71)

### What is the expected behavior?
Validator text containing an expression should update when the value changes

### How would you reproduce the current behavior (if this is a bug)?
reproduced on sandbox : https://codesandbox.io/s/winter-voice-vjcypc
enter a value, see the error text not updating

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codesandbox.io/s/winter-voice-vjcypc

**Comment by JaneSjs** [comment]
Hi @FHourmy,
Thank you for sharing the demo. I tested it on my end and confirms that expressions and validation work as expected. For instance, enter `30` within the first input field. The 'leftover' expression receives the `70` value and the error message appears as expected:
![image](https://github.com/surveyjs/survey-library/assets/22372972/3ea51f0e-e249-4256-a435-018488902aae)

Now, enter `120` for the first field. The `leftover` expression is now set to `-20` which is less than 0. The validation expression evaluates to `true` and the error message disappears.
![image](https://github.com/surveyjs/survey-library/assets/22372972/f2d0c725-bf6b-4aad-90ae-0a6ef88638b1)

Please let me know if you are expecting different behavior.

**Comment by FHourmy** [comment]
Hi @JaneSjs 

For the Bug to happen here is the step by step : 
- initial state : correct value, no error
![image](https://github.com/surveyjs/survey-library/assets/34136072/3ac4c993-ccbb-4ac9-8696-d77ddd8f7bdf)
- you enter a wrong value => the error is triggered with the correct text
![image](https://github.com/surveyjs/survey-library/assets/34136072/50e3cedd-59f0-4761-9395-ae37df60c1a4)
- you enter another wrong value => the text error is not updated
- 
![image](https://github.com/surveyjs/survey-library/assets/34136072/3b879857-d835-49fd-a714-21306d025119)

**Comment by andrewtelnov** [comment]
@FHourmy The issue has been fixed by [this PR](https://github.com/surveyjs/survey-library/pull/6808).

Thank you,
Andrew
