### ISSUE TITLE
progress bar as percentage

### ISSUE THREAD

**Issue by rsands2801** [surveyjs/survey-library#68]
I envisage a better method of user feedback is to have a progressbar that has a percentage instead of page 1 or, etc.

It is a percentage of total questions completed and total questions (not pages) left to go that are visible.

The percentage starts at 0% when survey begins (will need to change progress bar text color to black to be seen) and as the survey is completed it increases percentage and changes font color to white or whatever color user chooses.

**Comment by andrewtelnov** [comment]
I am afraid it will be tricky to do with the colors.
In fact, I should have at least two colors: progressStartColor and progressEndColor. The color will be changed from start to end.
I may probably will need progressTextStartColor and progressTextEndColor.
Currently, I am consider to postpone this feature for a while. There are many things, they I would love to include into the library, editor and service.
This one is cool, but it is something fancy for the current stage.

Thank you,
Andrew

**Comment by garybond** [comment]
+1 for showing progress as percentage instead of Page 1 of X.
The color changing is not something we need.

**Comment by andrewtelnov** [comment]
@garybond There are already several similar requests. I am adding it into our TODO list, percentage based on questions count: 
((answered questions on the current page and next pages + all questions on previous pages) * 100 / total visible questions)  %.

Thank you,
Andrew

**Comment by amehlen** [comment]
How is the current state of this issue?

Best regards,
Allan

**Comment by andrewtelnov** [comment]
@amehlen We have not chance to introduce this behavior yet out of the box, but we will keep it in mind.

Thank you,
Andrew

**Comment by vovkind** [comment]
What can we do with mobile? The text is just not visible.

![image](https://user-images.githubusercontent.com/9039260/42510503-c9b55678-8457-11e8-8639-4c20eba84211.png)

+1 for changing to percentage

**Comment by vovkind** [comment]
Some updates, please?

**Comment by dmitrykurmanov** [comment]
We are working on other features and I can't give you any estimate. But you can try to create custom navigation. Here is the example https://surveyjs.io/Examples/Library/?id=survey-customnavigation&platform=jQuery&theme=default

**Comment by iuliuscaesar92** [comment]
@dmitrykurmanov  It would be helpful to have an example of percent based progress bar based on survey-customnavigation article

**Comment by paddotk** [comment]
You can use an HSL color scheme for this: https://www.w3schools.com/colors/colors_hsl.asp

E.g.
 - from black to white: `hsl(0, 0%, 0%)` - `hsl(0, 0%, 100%)`
 - from red to green: `hsl(0, 100%, 50%)` - `hsl(115, 100%, 50%)`

**Comment by TonisOrmisson** [comment]
I propose skip the colors and just give the option to display progress as % instead of the text `Answered x/x questions`. 

I propose to add something like Survey: `progressBarDisplayType` percentage/text. 

Percentage as progress is:
- simpler
- more intuitive
- more standard

**Comment by hoechenberger** [comment]
I would also like to chime in and state that displaying percentage completed instead of pages completed is a hard requirement for an upcoming survey of mine. Would be great to see this feature added. I don't care about the colors :)

**Comment by andrewtelnov** [comment]
We have [survey.progressBarType](https://surveyjs.io/Documentation/Library?id=surveymodel#progressBarType) property and I have just added [survey.onProgressText event](https://github.com/surveyjs/survey-library/issues/2370) that allow to render any text you want into progress bar.

Thank you,
Andrew
