### ISSUE TITLE
Incorrect smartphone paddings

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-library#6849]
![Image](https://user-images.githubusercontent.com/29385489/265045954-f172d2bf-fd36-4b0c-85a3-53eb338d704b.png)

**Comment by aditya-garg-09-01-2002** [comment]
How can I reproduce this bug as in which page has this, and further if you can guide me through source code that would be great.
(p.s. I used surveyjs for the first time so can't go through a lot at once)
thanks in advance

**Comment by novikov82** [comment]
The bug can be reproduced here https://surveyjs.io/form-library/examples/s/text-entry-question/reactjs/default

I believe I will be fixed in nearest release next wеек.

**Comment by aditya-garg-09-01-2002** [comment]
ok I will taking that as no more work is to be done on this issue then.
Thanks
