### ISSUE TITLE
Mobile: Multiple text renders incorrectly

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#6875]
We don't need to render table for multiple text on mobile
![image](https://github.com/surveyjs/survey-library/assets/5655108/a13c20bc-90ac-4342-a91c-5085614efd7a)

**Comment by mikeamelin** [comment]
+ wrong placeholder rendering in Library



![Image](https://github.com/surveyjs/survey-library/assets/17025812/c2fc1df3-98b3-4da9-a269-b73bbc55e74b)
