### ISSUE TITLE
Mobile: There are multiple issues with matrices

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#6876]
We need a different/better design for matrices on mobile.

**Comment by mikeamelin** [comment]
No problem to use panel/dynamic panel for matrix responsivity. But we have to synchronize CSS...



![Image](https://github.com/surveyjs/survey-library/assets/17025812/497d3426-42a6-45ed-a060-1dc59d100239)
![Image](https://github.com/surveyjs/survey-library/assets/17025812/1d97cbf3-e731-425f-b433-23092ac67608)




Here is a prototype for details — 

https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?type=design&node-id=1065-107295&mode=design

**Comment by mikeamelin** [comment]
This property shouldn't be applied.



![Image](https://github.com/surveyjs/survey-library/assets/17025812/307c9c25-6cf8-4283-996b-2c982533c118)
