### ISSUE TITLE
Creator, autogenerated choices aren't translated via my custom locale(swe)

### ISSUE THREAD

**Issue by EliasHolmerTietoevry** [surveyjs/survey-library#6885]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

When adding a new question(multichoice or radiogroup for example.) the automatically added options text is english however when i remove them all and add them back the swedish translation appears.

### What is the expected behavior?

When creating a new question the options should correspond to the locale configured in the code.

### How would you reproduce the current behavior (if this is a bug)?

Configure the surveyJS creator as below with a json containing translations such as my "customLocale" file. I am using Angular and typescript. Create a new question that has automatically named options that are in english, remove all the options and add new ones. After this the new options should corespond to the customLocale file.

    this.creator = new SurveyCreatorModel(creatorOptions);
    this.creator.locale = 'customlocale';

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

export class SurveyCreatorComponent implements OnInit {
  creator!: SurveyCreatorModel;


  constructor() {}

  ngOnInit() {
    this.creator = new SurveyCreatorModel(creatorOptions);
    this.creator.locale = 'customlocale';
  }

```

### Specify your

* browser: chrome
* browser version: 116.0.5845.140
* surveyjs platform (angular or react or jquery or knockout or vue): angular 
* surveyjs version: 1.9.91

https://github.com/surveyjs/survey-library/assets/114986465/fe81977f-ab6f-4cf1-8a47-425983c15c4b

**Comment by JaneSjs** [comment]
Hello @EliasHolmerTietoevry,
Those choices which appear when a user adds a new question are preconfigured within the Survey Creator's `settings.toolbox.defaultJSON`. Choices texts are hardcoded in English. You can check how it's done in our source code: [defaultJSON](https://github.com/surveyjs/survey-creator/blob/0310ce67364b6b88a2200327e9962e4d61af6a1e/packages/survey-creator-core/src/creator-settings.ts#L97-L140).

If you translate a Survey Creator UI, please additionally override these texts using the settings.defaultJSON definition. For instance:
```
import { settings } from "survey-creator-core";

settings.toolbox.defaultJSON = {
  dropdown: {
    choices: ["Artikel 1", "Artikel 2", "Artikel 3"]
  },
  tagbox: {
    choices: ["Artikel 1", "Artikel 2", "Artikel 3"]
  },
  radiogroup: {
    choices: ["Artikel 1", "Artikel 2", "Artikel 3"]
  },
  checkbox: {
    choices: ["Artikel 1", "Artikel 2", "Artikel 3"]
  },
  ranking: {
    choices: ["Artikel 1", "Artikel 2", "Artikel 3"]
  }
};
```
This issue has already been discussed in the following thread: https://github.com/surveyjs/survey-creator/issues/4444.
