### ISSUE TITLE
Checkboxes Question: Choices selected are not reflected in another field using Default Value Expression Property

### ISSUE THREAD

**Issue by gitikakhanna** [surveyjs/survey-library#6886]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

The selected choices (in checkboxes question) are not reflected in another field when trying to access the answer using Default Value Expression

### What is the expected behavior?

Selected choices should be accessible and rendered in another field using Default Value Expression.

### How would you reproduce the current behavior (if this is a bug)?

Step 1: Create a Checkbox question with multiple choices (question1)

Step 2: Create a Single-Input Field (question2) and the default value expression should be set as **{question1}**

Step 3: In the Preview tab, select multiple choices in Question 1. The value reflected in question 2 will be only the first choice that was selected in question 1. It does not reflect all the selected options separated by a comma. 

Step 4: Unselect all choices in question1 and the question2 will still be reflecting the very first choice selected in question1.

In the below example, I selected multiple options in Question 1 (Favourite Sports) and the answer reflected in the text field didn't contain all the selected options. When I unselected all options, even then the value in second field did not change. 

https://github.com/surveyjs/survey-library/assets/31077845/5e20b13d-aec0-4cdc-bbf0-c5e145f15d5f

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
The bug is reproducible in the following codesandbox

Test code
https://codesandbox.io/s/checkbox-question-bug-28xq84?file=/src/json.js

### Specify your

* browser: Chrome
* browser version: 112.0.5615.49
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.9.81

**Comment by JaneSjs** [comment]
Hello @gitikakhanna,
I appreciate your detailed explanation, and a demo. I reproduced the issue using the latest SurveyJS Form Library version. We'll research this issue and update you as soon as we get any news to share.

Thanks

```
{
 "logoPosition": "right",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "checkbox",
     "name": "question1",
     "choices": [
      "Item 1",
      "Item 2",
      "Item 3"
     ]
    },
    {
     "type": "text",
     "name": "question2",
     "defaultValueExpression": "{question1}"
    }
   ]
  }
 ]
}
```
![image](https://github.com/surveyjs/survey-library/assets/22372972/d64feac0-0c75-4059-a3e7-91b35b7d68b7)

**Comment by gitikakhanna** [comment]
> Hello @gitikakhanna, I appreciate your detailed explanation, and a demo. I reproduced the issue using the latest SurveyJS Form Library version. We'll research this issue and update you as soon as we get any news to share.
> 
> Thanks
> 
> ```
> {
>  "logoPosition": "right",
>  "pages": [
>   {
>    "name": "page1",
>    "elements": [
>     {
>      "type": "checkbox",
>      "name": "question1",
>      "choices": [
>       "Item 1",
>       "Item 2",
>       "Item 3"
>      ]
>     },
>     {
>      "type": "text",
>      "name": "question2",
>      "defaultValueExpression": "{question1}"
>     }
>    ]
>   }
>  ]
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/22372972/266978836-d64feac0-0c75-4059-a3e7-91b35b7d68b7.png)

Thank you @JaneSjs
