### ISSUE TITLE
Capture file question value from built-in camera

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#6908]
We need a new mode property: "file" (default), "webcam" and "both" to allow get picture from webcame if it is exists.
If there is no camera on a device then "file" mode will be used.

**Comment by mikeamelin** [comment]
Prototype — https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?type=design&node-id=1141-166723&mode=design
