### ISSUE TITLE
Dropdown - A dropdown remains open

### ISSUE THREAD

**Issue by Giusort** [surveyjs/survey-library#6918]
Hi,

   using survey-angular-ui:

    "survey-angular-ui": "^1.9.106",
    "survey-core": "^1.9.106",
    "surveyjs-widgets": "^1.9.106",

we have exactly the same issue as in #6444 and in this [demo](https://plnkr.co/edit/uzMr2TKoG3F47CDi).

Thank you

**Comment by JaneSjs** [comment]
Hi @Giusort,
I created the following demo using the `survey-angular-ui` package v1.9.106: [View Demo](https://codesandbox.io/s/surveyjs-angular-forked-jyqcl3?file=/package.json).

I can confirm that a drop-down is correctly collapsed when scrolling a form. Would you please test the demo on your side and let me know if it works for you?

**Comment by Giusort** [comment]
Thank you Jane,

  thanks to your demo we explored the question in depth:
  
  if in our project we use a popup
  
"<popup-survey [model]="surveyModel" [isExpanded]="true"></popup-survey>"
  
  the behavior is as expected, the drop down closes on the external scroll but if we use just the survey the dropdown remains open
  
"<survey [model]="surveyModel"></survey>"
  
  
  We noticed that in the survey-angular-ui documentation there is the same wrong behavior:
  
  https://surveyjs.io/form-library/examples/create-dropdown-menu-in-javascript/angular#
  
  
![image](https://github.com/surveyjs/survey-library/assets/49234435/e2ec12df-bb23-4a4f-a08f-60f4792a643d)

but it's ok in the example sandbox:

https://codesandbox.io/s/whvhgc



This is our configuration:

Angular CLI: 15.2.9
Node: 18.10.0
Package Manager: npm 9.8.0
OS: win32 x64

Angular: 15.2.9
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.9
@angular-devkit/build-angular   15.2.9
@angular-devkit/core            15.2.9
@angular-devkit/schematics      15.2.9
@schematics/angular             15.2.9
ng-packagr                      15.2.2
rxjs                            6.6.7
typescript                      4.9.5

**Comment by JaneSjs** [comment]
Hello @Giusort,
Thank you for the quick update. I reproduced this issue on our [Dropdown demo](https://surveyjs.io/form-library/examples/create-dropdown-menu-in-javascript/angular#).
https://github.com/surveyjs/survey-library/assets/22372972/d83e086e-eb68-4400-9dc8-94eb17cd2914

We'll research this issue and update you once we have any news to share.

Thank you

**Comment by JaneSjs** [comment]
Hello @Giusort,
I quickly discussed this issue with our developers. It appears that a Dropdown doesn't close a popup because in the prodivded HTML configuration, it doesn't track a parent container scrolling. To resolve the issue, it is necessary to enable the `survey.fitToContainer` option. 
```
{
  "fitToContainer":  true,
  "elements": [
    {
      "type": "dropdown",
      "name": "car",
      "title": "Which is the brand of your car?",
      "isRequired": true,
      "showNoneItem": true,
      "showOtherItem": true,
      "choices": [ "Ford", "Vauxhall", "Volkswagen", "Nissan", "Audi", "Mercedes-Benz", "BMW", "Peugeot", "Toyota", "Citroen" ]
    }
  ],
  "showQuestionNumbers": false
}
```
We'll continue investigating this issue. Thank you

**Comment by JaneSjs** [comment]
Hello @Giusort,
Thank you for sharing a demo. I enabled the `fitToContainer` option within your demo and confirmed it works as expected. Please test the updated sample: https://codesandbox.io/s/surveyjs-angular-forked-9mggty?file=/src/app/components/json.ts.

https://github.com/surveyjs/survey-library/assets/22372972/691028c4-3183-4b38-bf32-4c4a16ab67ed

Let me know if it woks.

**Comment by Giusort** [comment]
Hi @JaneSjs, thank you.

   I updated your last working example (with the fitToContainer option) adding a div with a vertical scroller:
   
   https://codesandbox.io/s/surveyjs-angular-forked-tcfx5f?file=/src/app/components/survey.component.html

   As you can see, if you open the dropdown and scroll on the "Lorem ipsum" frame, the drop down still remains open; if you scroll where the dropdown is, it closes.
   Without "fitToContainer: true" the dropdown remains always open, regardless of where you scroll.
   
![image](https://github.com/surveyjs/survey-library/assets/49234435/36fac0ef-8c0e-44e0-9edb-1ae7c8e99f6a)

**Comment by JaneSjs** [comment]
Hello @Giusort,
Please accept my apologies for the delayed reply. Thank you for the update. I'll discuss this issue with our developers and update you shortly.

**Comment by JaneSjs** [comment]
Hello @Giusort,
I discussed this issue with our developers. It appears that we do detect scroll events of outer survey containers. To close a survey popup when the outer container is being scrolled, handle all scroll events and programmatically hide a popup. 
* Subscribe to the [survey.onPopupVisibleChanged](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onPopupVisibleChanged) event to access a popup instance.
* Subscribe to the `onScroll` event and enable the `useCapture` option. With this option, the `onScroll` event will fire on all elements within a page.
```
export class SurveyComponent implements OnInit {
  model: Model;
  popup;

  ngOnInit() {
    const survey = new Model(json);

    survey.onPopupVisibleChanged.add((sender, options) => {
      this.popup = options.popup;
    });
    window.addEventListener(
      "scroll",
      () => {
        if (this.popup) {
          this.popup.isVisible = false;
        }
      },
      true
    );
    ...
    this.model = survey;
  }
}
```
[View Demo](https://codesandbox.io/s/surveyjs-angular-forked-2z5mmx?file=/src/app/components/survey.component.ts:409-978)

Should you have any further question, please feel free to reactivate this thread.

**Comment by Giusort** [comment]
Thank you @JaneSjs!
