### ISSUE TITLE
defaultValueExpression should be ignored in case of preloaded data (1.9.107 regression)

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#6941]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

defaultValueExpression should be ignored in case of preloaded data. It use to work with 1.9.106

https://plnkr.co/edit/dMVEJIGZbhP6DSjm

thank you

**Comment by andrewtelnov** [comment]
@masciugo I have fixed it by the comment above.

Thank you,
Andrwe
