### ISSUE TITLE
enable tagbox with hasOther to store more than one custom choice

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#6964]
### Are you requesting a feature, reporting a bug or asking a question?

feature

### What is the current behavior?

At moment using hasOther with tagbox let you add ONE custom choice. The possibility to add only one choice make much sense in a context of a dropdown (single choice). But when dealing with a multiple choices widget you may need to build your array of selected choices by adding more than one custom choice. Which is basically what select2 let you do with the _tags: true_ option when used with multiple choices. 

In my projects I would like to switch to the native solutions but I can't do it now because it would not be back compatible with my data as I have some saved array (built with select2 custom widget) like:

`['opt1', 'opt3', 'myCustomOpt1', 'myCustomOpt2']`

Instead, no backward compatiblity problems for all dropdowns.

Does it make any sense to you guys? 

thankyou

**Comment by andrewtelnov** [comment]
@masciugo Do you mean a select2 functionality that allows to enter new values into the list?

Thank you,
Andrew

**Comment by masciugo** [comment]
Yes [I was recommended](https://github.com/surveyjs/survey-library/issues/5689#issuecomment-1437067572) to use built-in questions of third-party ones but I miss that feature

**Comment by andrewtelnov** [comment]
Got it. We will discuss it on our weekly planning. I am doubt that we will do it this month, since we have a lot of functionality in our list to implement, but I agree that it is nice to have features. We have already discussed several times.

Thank you,
Andrew

**Comment by JaneSjs** [comment]
Hello Everyone, 
Thank you for your ideas. Unfortunately, we don't currently plan to support user input choices for a Dropdpwn/Tag Box. We have the corresponding ticket in our list and may consider this enhancement in future updates of a SurveyJS Form Library. In the meantime, you may consider using a third-party Select2 component: [View Demo](https://plnkr.co/edit/zjhI6ztuUaEGJljg).

Select2 allows you to add new options to a list. Enable the `allowAddNewTag` option to let users add new tags to a Tag Box Select2 widget.

Should you have any questions or require further assistance, please feel free to reactivate this thread.
