### ISSUE TITLE
Pre-processing translation strings stop working in v1.9.106/107

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#6967]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
We discovered this with custom properties, but reproduced it with built in properties.
Doing something like this: `Survey.surveyLocalization.locales.en.startSurveyText = "{n}";`
Will break the survey model constructor.

### What is the expected behavior?
This is a regression.

### How would you reproduce the current behavior (if this is a bug)?
```js
Survey.surveyLocalization.locales.en.startSurveyText = "{n}";
new Survey.Model();
```

#### Provide the test code and the tested page URL (if applicable)

Check the developer console to see the error!

Tested page URL: https://plnkr.co/edit/7srGU5BPMpf66E90

### Specify your

* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: 107

## Important 
While the given example can be fixed by moving up the initialization of `this.textPreProcessor` in the `Survey` constructor, this will not fix the issue for custom properties.

Custom properties are added in the `super()` call by a parent class.
The issue is caused by a circular reference in `base.ts`:
```ts
public createCustomLocalizableObj(name: string) {
    var locStr = this.getLocalizableString(name);
    if (locStr) return;
    this.createLocalizableString(name, <ILocalizableOwner>(<any>this), false, true);
  }
```
This localizable string is passed the survey class as an implementor of `ILocalizableOwner`. But at this moment it cannot yet fully satisfy this interface since it has not been fully initialized...

The design flaw becomes obvious when you look at the typecasting needed to silence typescript.
I'm not sure what the best solution to untangle this is...

One possible solution that might work, without fixing the design, is to simply initialize the field in the declaration, not in the constructor:
```ts
private textPreProcessor: TextPreProcessor = new TextPreProcessor();
```

**Comment by andrewtelnov** [comment]
@SamMousa It is fixed by the commit above. I created the instance on the first request.

Thank you,
Andrew

**Comment by SamMousa** [comment]
That'll work as well! Why did you prefer it above initialisation at the point of declaration? You use that method for other properties

**Comment by andrewtelnov** [comment]
@SamMousa I need to setup this class instance. It is not a constructor call only.

Thank you,
Andrew

**Comment by SamMousa** [comment]
Please reopen this, in v1.9.113 it's back in a different form.

```ts
  public getVariable(name: string): any {
    if (!name) return null;
    name = name.toLowerCase();
    var res = this.variablesHash[name];
    if (!this.isValueEmpty(res)) return res;
    if (name.indexOf(".") > -1 || name.indexOf("[") > -1) {
      if (new ProcessValue().hasValue(name, this.variablesHash))
        return new ProcessValue().getValue(name, this.variablesHash);
    }
    return res;
  }
```
Specifically `this.variablesHash` is access before being initialized.
![image](https://github.com/surveyjs/survey-library/assets/547021/72f8e399-fc17-40c5-bf2d-d9ae2631f7cd)


It's trying to resolve the variable but failing to do so because the survey object is not fully initialized.
I think it's easier / more logical to handle translations after all initialization has been done.
