### ISSUE TITLE
Question: Possible to integrate third party code with Vue3?

### ISSUE THREAD

**Issue by piscis** [surveyjs/survey-library#6977]
I would like to know if its possible to integrate third party components or your own vue components as custom question type when using vue3. 

If possible could you provide a minimalistic example similar to the react one I found here: https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-react

### Are you requesting a feature, reporting a bug or asking a question?

question

**Comment by JaneSjs** [comment]
Hi @piscis,
Yes, you can integrate a third-party Vue 3 component to a SurveyJS Form Library and use it as a custom question type.

Please refer to the following example: [View Demo](https://stackblitz.com/edit/vitejs-vite-az9p9y?file=src%2Fmain.ts). This example shows how to integrate a [vue-color](https://github.com/ckpack/vue-color) widget to a Vue 3 SurveyJS Form Library application.

* Install the [survey-vue3-ui](https://www.npmjs.com/package/survey-vue3-ui) and [@ckpack/vue-color](https://www.npmjs.com/package/@ckpack/vue-color) npm packages. 
* Implement a QuestionColorPickerModel on top of a base Question type.
```
<template>
  <div ref="root">
    <Sketch
      v-if="question.colorPickerType === 'Sketch'"
      :model-value="color"
      @update:model-value="updateValue"
    ></Sketch>
    <Compact
      v-if="question.colorPickerType === 'Compact'"
      :model-value="color"
      @update:model-value="updateValue"
    ></Compact>
    <Slider
      v-if="question.colorPickerType === 'Slider'"
      :model-value="color"
      @update:model-value="updateValue"
    ></Slider>
  </div>
</template>
<script lang="ts" setup>
import { Sketch, Slider, Compact, type Payload } from '@ckpack/vue-color';
import { useQuestion } from 'survey-vue3-ui';
const props = defineProps<{ question: QuestionColorPickerModel }>();
const root = ref(null);
useQuestion(props, root);
const color = computed(() => props.question.value || "");
const updateValue = (data: Payload) => {
    const question = props.question;
    question.value = data.hex;
}
</script>
<script lang="ts">
import { Question, ElementFactory, Serializer } from 'survey-core';
import { computed, ref } from 'vue';

const CUSTOM_TYPE = 'color-picker';

export class QuestionColorPickerModel extends Question {
  getType() {
    return CUSTOM_TYPE;
  }
  get colorPickerType() {
    return this.getPropertyValue('colorPickerType');
  }
  set colorPickerType(val) {
    this.setPropertyValue('colorPickerType', val);
  }

  get disableAlpha() {
    return this.getPropertyValue('disableAlpha');
  }
  set disableAlpha(val) {
    this.setPropertyValue('disableAlpha', val);
  }
}

export function registerColorPicker() {
  ElementFactory.Instance.registerElement(CUSTOM_TYPE, (name) => {
    return new QuestionColorPickerModel(name);
  });
}
Serializer.addClass(
  CUSTOM_TYPE,
  [
    {
      name: 'colorPickerType',
      default: 'Slider',
      choices: ['Slider', 'Sketch', 'Compact'],
      category: 'general',
      visibleIndex: 2, // Place after the Name and Title
    },
  ],
  function () {
    return new QuestionColorPickerModel('');
  },
  'question'
);
</script>
```
* Within the **main.ts** file, register `surveyPlugin` and add the custom `ColorQuestion` component to the Vue application.
```
import { createApp } from 'vue';
import { surveyPlugin } from 'survey-vue3-ui';
import 'survey-core/defaultV2.css';
import App from './App.vue';
import ColorQuestion from './Color.vue';

createApp(App)
  .use(surveyPlugin)
  .component('survey-color-picker', ColorQuestion)
  .mount('#app');
```
Now, you can create a survey model and use the custom `color-picker` question type.

```
const model = new SurveyModel({
  elements: [
    {
      type: 'color-picker',
      name: 'question1',
      title: 'Color picker type = Slider',
    },
...
```
We hope this example can help. Should you have any further questions, we are here to help.

**Comment by piscis** [comment]
Thanks  @JaneSjs I'm going to give it a try.

**Comment by nathan-cv** [comment]
Thank you @JaneSjs - I was about to throw my hands up and abort my approach until I stubbled across your comment.  Absolute gold - this opens up so many possibilities for us. Major props to everyone working on the survey-vue3-ui package.

It would be super helpful to have this documented next to the other [3rd party articles](https://surveyjs.io/form-library/documentation/customize-question-types/create-specialized-question-types).
