### ISSUE TITLE
confirmDelete = true doesn't work with matrixdynamic

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/survey-library#6999]
```js
       {
        "confirmDelete": true,
        "type": "matrixdynamic",
...
      }
```
`paneldynamic` is ok

**Comment by andrewtelnov** [comment]
@dmitrykurmanov We do not ask for confirm delete if there is no value in the row. There is unit test on it.
Please set any value into any cell and you will see the confirmation dialog.

Thank you,
Andrew
