### ISSUE TITLE
clearInvisibleValues onHiddenContainer breaks defaultValueExpression for text input

### ISSUE THREAD

**Issue by fabiocody** [surveyjs/survey-library#7010]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug.

### What is the current behavior?
If clearInvisibleValues is set to onHiddenContainer, I don't get the result of defaultValueExpression in the text input when questions that appear in the expression change, as happens when clearInvisibleValues is set to onHidden or is not set.

### What is the expected behavior?
defaultValueExpression should correctly set the value of the text input, even if clearInvisibleValues is set to onHiddenContainer.

### How would you reproduce the current behavior (if this is a bug)?
```json
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question1",
     "choices": [
      "A",
      "B"
     ]
    },
    {
     "type": "panel",
     "name": "panel1",
     "elements": [
      {
       "type": "text",
       "name": "question2",
       "defaultValueExpression": "iif({question1} = 'A', 42, iif({question1} = 'B', 24, 0))"
      }
     ],
     "visibleIf": "{question1} anyof ['other', 'A', 'B']"
    }
   ]
  }
 ],
 "clearInvisibleValues": "onHiddenContainer"
}
```
This config can be used to reproduce the bug: if you select one of the first options and then change it, the value does not reflect the defaultValueExpression result.

### Specify your

* browser: Google Chrome
* browser version: 116.0.5845.187
* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version: 1.9.109

**Comment by andrewtelnov** [comment]
@fabiocody The PR above fixes the issue.

Thank you,
Andrew
