### ISSUE TITLE
Vue3: Load data into tagbox/dropdown in dynamic matrix with RESTful API choices produce Vue warnings

### ISSUE THREAD

**Issue by zvn2060** [surveyjs/survey-library#7025]
### Are you requesting a feature, reporting a bug or asking a question?
BUG

### What is the current behavior?
When use tagbox or dropdown in dynamic matrix, and set these two question use data from RESTful API as choices
* If no survey data load, it is fine
* But if I load previously submitted into the survey, these two element will show below in debug mode and crash in production mode
 > [Vue warn]: Maximum recursive updates exceeded in component <Dropdown>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function

### What is the expected behavior?
Shouldn't cause page crash

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

CodeSandbox: https://codesandbox.io/p/sandbox/vue-recursive-update-tagbox-vmodel-when-choice-from-api-d3vggf

### Specify your

* browser: Edge / Chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): vue 3
* surveyjs version: v1.9.109

**Comment by andrewtelnov** [comment]
@zvn2060 I have just checked and it works fine to me. What should I do to reproduce the issue?

Thank you,
Andrew

**Comment by zvn2060** [comment]
@andrewtelnov 
I mean, if I use the tagbox and dropdown in dynamic matrix
and **the data is fetch from API**

although the project seems working fine, but DevTool show these warning
![image](https://github.com/surveyjs/survey-library/assets/45450852/9490f2db-ad6f-4897-b63f-daef8ac9ca94)

and If this project in **production mode, it will cause the whole page crash and unusable.**

**Comment by andrewtelnov** [comment]
@dk981234 Could you please check this warnings?

Thank you,
Andrew
