### ISSUE TITLE
Cookie Messanging - Display a notification to inform users that a survey is taken only once

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7035]
User Issue: T14800 - Cookie messaging to survey users
https://surveyjs.answerdesk.io/internal/ticket/details/T14800

User idea: When a survey contains a `cookieName`, display a notification to inform users that a survey cannot be retaken. 
A notification may look like one of a standard SurveyJS notifiers:
![image](https://github.com/surveyjs/survey-library/assets/22372972/75241ec9-7841-4a0b-8b59-4ab5f3e5e6e4)

**Comment by RomanTsukanov** [comment]
Notification type: "error" differs from the other two types in width and height. @dk981234 is going to look into it.

![image](https://github.com/surveyjs/survey-library/assets/18551316/4e340de4-c5fd-44ea-b5f2-db8387e2c398)

**Comment by dk981234** [comment]
https://github.com/surveyjs/survey-library/pull/7384
