### ISSUE TITLE
Error in render: "TypeError: Cannot read properties of undefined (reading 'description')"

### ISSUE THREAD

**Issue by olivier-calvo** [surveyjs/survey-library#7044]
Hello,

I try to use form-library along with survey-creator on the same page.
I first want to display the preview of my survey and propose a "edit" button that then displays the creator.

When I import SurveyCreator, form-library no longer appears and generates the following error in the console:

![image](https://github.com/surveyjs/survey-library/assets/27730627/5f59a7e5-729c-4280-b623-3aa33278a1bd)

package.json
```json
{
  "name": "test svjs",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview --port 4173"
  },
  "dependencies": {
    "survey-creator-knockout": "^1.9.110",
    "survey-vue-ui": "^1.9.110",
    "vue": "^2.7.7"
  },
  "devDependencies": {
    "@vitejs/plugin-legacy": "^2.0.0",
    "@vitejs/plugin-vue2": "^1.1.2",
    "terser": "^5.14.2",
    "vite": "^3.0.2"
  }
}
```

App.vue (without "edit" button)
```vue
<script setup>
import { SurveyCreator } from "survey-creator-knockout";
import "survey-core/defaultV2.min.css";
import "survey-creator-core/survey-creator-core.min.css";
import { Model } from 'survey-core';
import { Survey } from 'survey-vue-ui';
import { onMounted } from "vue";

const defaultJson = {
  pages: [{
    name: "Name",
    elements: [{
      name: "FirstName",
      title: "Enter your first name:",
      type: "text"
    }, {
      name: "LastName",
      title: "Enter your last name:",
      type: "text"
    }]
  }]
};

const survey = new Model(defaultJson);

const creator = new SurveyCreator({
  showLogicTab: true,
  isAutoSave: true
});

creator.JSON = defaultJson

onMounted(() => creator.render("surveyCreator"));

</script>

<template>
  <div id="app">
    <div id="surveyCreator" />
    <hr />
    <Survey :survey="survey" />
  </div>
</template>
```

### Environment

* browser : Google Chrome
* browser version : 117.0.5938.92
* surveyjs platform : Vue 2
* surveyjs version : 1.9.110

**Comment by JaneSjs** [comment]
Hello @olivier-calvo,
To ensure compatibility when using a SurveyJS Form Library and Survey Creator in a single Vue application, you need to use the `survey-knockout-ui` package to render a survey. Please follow this guide for integration steps: [Add a Survey to a Knockout Application](https://surveyjs.io/form-library/documentation/get-started-knockout).

Please update your project to use the Knockout integration for a Form Library and let me know if this resolves the issue.

**Comment by JaneSjs** [comment]
Hello @olivier-calvo,
Please accept my apologies for the delayed reply. Please follow the [Knockout Form Library](https://surveyjs.io/form-library/documentation/get-started-knockout) integration guide to embed a survey within your Survey Creator Vue 2 component. 

Consider the updated code.

**SurveyCreatorComponent.vue**
```
<template>
  <div id="app">
    <div id="creatorElement" />
    <hr />
    <survey params="survey: model"></survey>
  </div>
</template>
<script>
import Vue from "vue";
import { SurveyCreator } from "survey-creator-knockout";
import { Model } from "survey-core";
import "survey-core/survey.i18n.js";
import "survey-creator-core/survey-creator-core.i18n.js";
import { surveyJSON } from "./survey_json";
import "survey-core/defaultV2.css";
import "survey-creator-core/survey-creator-core.css";
import "./index.css";
import * as ko from "knockout";

export default Vue.component("surveyjs-creator-component", {
  name: "surveyjs-creator-component",
  mounted() {
    const survey = new Model(surveyJSON);
    ko.applyBindings({
      model: survey,
    });
    const options = {
      showLogicTab: true,
    };
    const creator = new SurveyCreator(options);
    creator.JSON = surveyJSON;

    creator.render("creatorElement");
  },
});
</script>
```
[View CodeSandbox](https://codesandbox.io/p/sandbox/surveyjs-creator-vue-n77ng9)

Let me know if you have further questions.
