### ISSUE TITLE
showPreviewAfterComplete property support

### ISSUE THREAD

**Issue by sovetski** [surveyjs/survey-library#7056]
We have the property "showPreviewBeforeComplete" which is very cool, but havind "showPreviewAfterComplete" will also perfect!

Imagine that we have a quizz page, that the user can not go back, and at the end of the quizz, all result will be send to the server and the user will see the result

**Comment by JaneSjs** [comment]
Hello @sovetski,
Thank you for reaching out. Such an option already exists. It is called a survey display mode, and it enables you to display a survey in review mode. To enable the review mode, [specify question answers ](https://surveyjs.io/form-library/documentation/design-survey/pre-populate-form-fields) and set the [survey.mode ](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#mode) property to display.

Please refer to the following demo: [Review Quiz results](https://surveyjs.io/form-library/examples/survey-quiz-results/reactjs).

I hope this option may help you. Should you have any further questions, we are always here to help.
