### ISSUE TITLE
How do users clear the value of Single-line input with Date type quickly?

### ISSUE THREAD

**Issue by WillIDC** [surveyjs/survey-library#7061]
Hi
I have a Single-line input of Date type. How the user can quickly clear the value to set a empty value. Otherwise the user has to clear the year, month , day...which is inconvenient

Thanks.

**Comment by JaneSjs** [comment]
Hi,
To clear [a DateTime value](https://surveyjs.io/form-library/examples/datetime-entry-question/reactjs), activate a popup and click the Clear button:
![image](https://github.com/surveyjs/survey-library/assets/22372972/c18e246a-13c8-4efa-8cc8-4c969df998d5)

Please let me know if you have any further questions.

**Comment by WillIDC** [comment]
OMG, I accidentally ignored that button. Thank you very much.
