### ISSUE TITLE
File Question - Rendering a custom file preview within the onAfterRenderQuestion callback stops working with v1.9.110

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7063]
User Issue: T14859 - Custom preview for file upload question - not working after updating version
https://surveyjs.answerdesk.io/internal/ticket/details/T14859
***
https://surveyjs.io/form-library/examples/custom-file-previews/

No file appears:
![image](https://github.com/surveyjs/survey-library/assets/22372972/12382849-3235-4dfd-8a6b-8e696e69cd39)

**Comment by jithureddy** [comment]
@JaneSjs - When `showPreview:false`, `onUploadFiles` call back is not triggered as well, because need to show the custom preview after uploadFiles custom API endpoint

**Comment by JaneSjs** [comment]
Hi @jithureddy,
I followed up with you in the following thread: https://github.com/surveyjs/survey-library/issues/7065. Please check my answer.

Thanks
