### ISSUE TITLE
Edit an existing question.

### ISSUE THREAD

**Issue by usamaSaddiq** [surveyjs/survey-library#708]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?

Can't find any helper methods.

### What is the expected behavior?

Hey I am implementing my own editor for a school project and just wondering if there is a way to edit existing questions on the survey.

I am using survey.pages[0].addNewQuestion(Type, Text) method and just wanted to select an already exisiting question and customize the json.

Test code

Something like editQuestion or anything that might be of any help.

* browser: Chrome
* browser version: 29.0.
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@usamaSaddiq To insert an already existing question/element you have to use [addElement function](https://surveyjs.io/Documentation/Library/?id=pagemodel#addElement). To edit the question/element, actually change the element properties is simple as:
```
ver question = survey.getQuestionByName("myQuestionName");
question.title = "My new title";
question.choices = ["My new Item 1",  "My new Item 2" ]; 
```
We have created to repos with examples of creating your own Survey Management System:
https://github.com/surveyjs/surveyjs-php
https://github.com/surveyjs/surveyjs-aspnet-mvc
Hopefully they will help you as well.

Thank you,
Andrew

**Comment by usamaSaddiq** [comment]
Okay great I will look into this repository for sure.

And any chance I might be able to get an HTML of a question object.

onAfterQuestionRendered return all questions so it's abit harder like that any easy helper methods?

Cheers

**Comment by usamaSaddiq** [comment]
Plus I have tried the addElement function at it edits the question and adds another question with same values in the survey, here is the fiddle

https://jsfiddle.net/r5kczfdw/1/

**Comment by andrewtelnov** [comment]
@usamaSaddiq Updated your example: https://jsfiddle.net/r5kczfdw/2/

about cssType. There are different css classes for different cssType. sv_row/sv_q is for default cssType. You may modify them. Here is the source files: https://github.com/surveyjs/surveyjs/tree/master/src/defaultCss
And here is the demo: https://surveyjs.io/Examples/Library/?id=survey-customcss

Thank you,
Andrew

**Comment by usamaSaddiq** [comment]
@andrewtelnov  Thanks alot.

One last thing any way to get the type of the question? 

Text Question have the InputType parameter but I guess that's for input, I can determine the type but just wondering if there is any helper method or property.

Cheers

**Comment by tsv2013** [comment]
Each question has the
`question.getType()`
function which returns string with question type name.
Text question has 'question.inputType()' function - https://surveyjs.io/Documentation/Library/?id=questiontextmodel#inputType.

**Comment by usamaSaddiq** [comment]
Thanks heaps @tsv2013
