### ISSUE TITLE
No way to set a custom placeholder for File Upload

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#7089]

**Comment by JaneSjs** [comment]
Usage Scenario: T15132 - How to Dynamically Set File Drag Placeholder Text for Multiple File Inputs?
https://surveyjs.answerdesk.io/internal/ticket/details/T15132

Multiple File Uploads are available within a form. Each file upload allows uploading files of different types. It is necessary to specify different placeholders for File questions.
