### ISSUE TITLE
Cover description uses wrong property for settings.

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#7137]
![Image](https://github.com/surveyjs/survey-creator/assets/17025812/8d02e0d6-ae03-41fe-83ca-47e1458d1989)

**Comment by mikeamelin** [comment]
Prototype — https://www.figma.com/file/Tj1RJZn2jVbL5ZE4W2OWAB/Property-Grid-Preview?type=design&node-id=44-29273&mode=design&t=ajpz33KCc74x8cpm-4

**Comment by OlgaLarina** [comment]
https://github.com/surveyjs/survey-creator/pull/4791
