### ISSUE TITLE
Change the default value for survey focusFirstQuestionAutomatic to false

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#7155]
This turn-on functionality can break a page flow with an embeded survey. It is better to turn it on manually, when it is needed.

**Comment by OlgaLarina** [comment]
https://github.com/surveyjs/survey-creator/issues/3998
https://github.com/surveyjs/survey-library/issues/6023
https://github.com/surveyjs/survey-library/issues/4571
