### ISSUE TITLE
Render icon registry in correct document

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#7164]
### Are you requesting a feature, reporting a bug or asking a question?
Bug / feature

### Context
I'm implementing a preview function in a new window, without using server side code.
These are my steps:
- I get a reference to the new window
- I insert an element into it
- I call the survey's `render` function with a the element that lives in a different document.

I realize this is an edge case, but bear with me.

### What is the current behavior?
Currently the survey calls `renderIcons()` on the `SvgRegistry`.
The function works like this:
```ts
public renderIcons() {
    const containerId = "sv-icon-holder-global-container";
    if(!!settings.environment && !settings.environment.root.getElementById(containerId)) {
      let iconsDiv = document.createElement("div");
      iconsDiv.id = containerId;
      iconsDiv.innerHTML = "<svg>" + this.iconsRenderedHtml() + "</svg>";
      iconsDiv.style.display = "none";

      getElement(settings.environment.svgMountContainer).appendChild(iconsDiv);
    }
  }
```

### What is the expected behavior?
I don't see the need for having a document global icon registry.
The few cases where you'll have multiple surveys on a page the overhead from duplicated icon definitions is minimal. 
Instead render the icons a survey need inplace, or in a per survey registry.

### How would you reproduce the current behavior (if this is a bug)?
Call `survey.render(target)` with a `target` from a different document.

I'm willing to work on a PR to improve this behavior while at the same time cleaning up a bit of code by reducing the usage of global variables. I understand this is an edge case but think that this would improve code cleanliness as well as resolve my issue!

**Comment by JaneSjs** [comment]
Hello @SamMousa,
Thank you for contacting us. I would recommend that you use our special [survey settings](https://github.com/surveyjs/survey-library/blob/master/src/settings.ts#L12C1-L32) to override the SVG icon container: `settings.environment.svgMountContainer`. You can set it to a target HTML element which would render icons.

Should you have any further questions, please let me know.
