### ISSUE TITLE
Knockout: fromJSON breaks rendered survey - Question Titles disappear

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#7168]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Calling `fromJSON` on a rendered survey sometimes clears out question texts.

### What is the expected behavior?
Rendering should be intact

### How would you reproduce the current behavior (if this is a bug)?
Go to the code sandbox in the URL below.
Click the button to see that question texts disappear after calling `fromJSON`. Also note that they re-appear when picking a value in one of the questions.

https://codesandbox.io/s/distracted-dew-ktd4rj?file=/src/index.js

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codesandbox.io/s/distracted-dew-ktd4rj?file=/src/index.js

### Specify your

* browser: Chromium & Firefox
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: latest

Edit: 
Also created the same code in Vue: https://codesandbox.io/s/surveyjs-library-vue3-forked-6n3y6r?file=/src/App.vue
In Vue it works, which leads me to believe it is a knockout rendering / binding issue.

**Comment by JaneSjs** [comment]
Hello @SamMousa,
Please accept my apologies for the delayed response.

I see that question titles disappear when calling the `survey.fromJSON` function:

https://github.com/surveyjs/survey-library/assets/22372972/ac502606-15d9-4e04-a1b5-6f04b8e166cd

We'll research this issue and update you as soon as we get any information.

Thanks

**Comment by SamMousa** [comment]
This also happens when you change the `questionsOnPageMode` property. 
I think it is an issue in the reactivity used on survey JS objects, sometimes it seems not to trigger a proper rerender.

**Comment by SamMousa** [comment]
Demo for the second issue here: https://codesandbox.io/s/elegant-turing-k9rpj3?file=/src/index.js

(Change the question on page mode using the dropdown and you'll see questions disappear)

I feel these are all caused by the same underlying issue.
What is needed to get more eyes on this?
