### ISSUE TITLE
Create Specialized Question Types - Add an example on how to Copy a Base Question and customize its settings

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7172]
* https://surveyjs.answerdesk.io/internal/ticket/details/T14784#9b949bc5-1c28-4934-8adf-0b2b45cf0449
* https://surveyjs.answerdesk.io/internal/ticket/details/T14574
* https://surveyjs.answerdesk.io/internal/ticket/details/T13121#5c866a04-c57a-480e-83f5-41f4683202b6
* https://surveyjs.answerdesk.io/internal/ticket/details/T15114#90a4b406-6a11-4c05-b7ff-1db771bdce69
* https://surveyjs.answerdesk.io/internal/ticket/details/T15325
***
We need to update the [Create Specialized Question Types](https://surveyjs.io/form-library/documentation/customize-question-types/create-specialized-question-types) help topic and clearly highlight the following usage scenario: 'Create one more component which will look the same as a standard question (e.g., Rating, Dropdown), but with some customized properties.

An example:
```
creator.toolbox.addItem({
    name: "csat",
    title: "CSAT",
    iconName: "icon-rating",
    isCopied: true,
    id: "csatQuestion",
    category: "General",
    json: {
      type: "rating",
      title: "How satisfied are you with your in-store experience today?",
      rateType: "stars"
    }
});
```
[View Demo](https://codesandbox.io/s/flamboyant-zeh-473ytc?file=/src/SurveyCreatorComponent.jsx:450-757)

BTW: in docs, there is no `addItem` function.
[addCopiedItem](https://surveyjs.io/survey-creator/documentation/api-reference/questiontoolbox#addCopiedItem)

**Comment by JaneSjs** [comment]
+1 https://github.com/surveyjs/survey-creator/issues/4661

**Comment by RomanTsukanov** [comment]
Waiting for https://github.com/surveyjs/survey-library/issues/7661

**Comment by RomanTsukanov** [comment]
Fixed in https://github.com/surveyjs/survey-library/pull/7727
