### ISSUE TITLE
[Vue3] - Error when using `onAfterRenderQuestionInput` with checkbox questions, and sometimes `htmlElement` is null when using `onAfterRenderQuestion`

### ISSUE THREAD

**Issue by aazvf** [surveyjs/survey-library#7173]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

Survey fails when using `onAfterRenderQuestionInput` with a checkbox question
I also believe there is a problem with `onAfterRenderQuestion`, it is sometimes returning null for `options.htmlElement`. I can create another issue if required but I suspect it is a similar bug.

### What is the expected behavior?

No console errors, and that `options.htmlElement` resolves to a real element on the page when using `onAfterRenderQuestion` and `onAfterRenderQuestionInput` for any question type. Thanks

### How would you reproduce the current behavior (if this is a bug)?

- Use `survey-vue3-ui`
- Use a checkbox question in the survey
- Use the onAfterRenderQuestionInput callback [api docs](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onAfterRenderQuestionInput)
- See `vue.global.js:1694 Uncaught TypeError: Cannot read properties of null (reading 'id')` in the console

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codepen.io/aaioa/pen/QWzXZdG

Test code

```
const json = {
  
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
                    "type": "checkbox",
                    "name": "safeguarding_method",
                    "title": "This is a checkbox question. It fails when using onAfterRenderQuestionInput",
                    "isRequired": true,
                    "choices": [
                        "Choice one",
                        "Choice two",
                        "Choice three",
                        "Choice four",
                        "Choice five"
                    ]
                },
       
      ]
    }
  ],
  "showPrevButton": false,
  "showQuestionNumbers": "off",
  "widthMode": "static",
  "width": "1000px"
 };
const App = {
  template: '<SurveyComponent :model="survey" />',
  setup() {
    const survey = new Survey.Model(json);
    survey.onAfterRenderQuestionInput.add((survey, options) => {
      console.log('onAfterRenderQuestionInput', options);
    });
    return { survey };
  }
};
Vue.createApp(App)
    .use(SurveyVue.surveyPlugin)
    .mount("#app");

```

### Specify your

* browser: Chrome, chromium, firefox
* browser version: latest
* surveyjs platform : Vue3
* surveyjs version: 1.9.112

**Comment by aazvf** [comment]
Hi @dk981234 

Thank you.

I have made this new codepen [https://codepen.io/aaioa/pen/gOZVGvO](https://codepen.io/aaioa/pen/gOZVGvO)

It took a minute to get this to trigger on codepen but here are some of my findings:

- `settings.lazyRender.enabled` must be `true` [docs](https://surveyjs.io/form-library/documentation/api-reference/settings#lazyRender)
- A question must be hidden using `visibleIf`
- There must be another question using `visibleIf` for some reason (I think)
- There must be a checkbox question in the survey. For some reason if i remove the checkbox question the bug does not trigger

To be honest I don't know exactly what triggers the bug but that's what I did to reproduce it on codepen


### Here is the code from codepen:

The `onAfterRenderQuestion` callback is trying to just set a style of `background:green` on every question.

If you look in the console you'll see htmlElement logging as null.
If an error happens inside `onAfterRenderQuestion` (like using `options.htmlElement.setAttribute` without first checking that `options.htmlElement` is not null) then it breaks further, try it by removing the if statement.

```
const json = {
    "title": "Testing onAfterRenderQuestion",
    "logoPosition": "right",
    "widthMode": "responsive",
    "pages": [
        {
            "name": "page1",
            "title": "page one",
            "elements": [
                {
                  "title": "Select 'a' to show the hidden question",
                    "type": "checkbox",
                    "name": "first",
                    "choices": [
                        "a",
                        "b",
                        "c",
                    ],
                    "colCount": 5
                },

                {
                    "type": "text",
                    "visible": false,
                    "visibleIf": "{first} anyof ['a']",
                    "name": "first_text",
                    "title": "This is a hidden",
                    "isRequired": true,
                    "maxLength": 400,
                },

                {
                    "type": "text",
                    "visible": false,
                    "visibleIf": "{first_text} = 'a'",
                    "name": "second_text",
                    "title": "This hidden question is even deeper",
                    "isRequired": true,
                    "maxLength": 400
                },
                {
                    "type": "checkbox",
                    "name": "checkbox_question",
                    "title": "This is a checkbox question. it should be coloured green like the rest",
                    "isRequired": true,
                    "choices": [
                        "Choice one",
                        "Choice two",
                        "Choice three",
                        "Choice four",
                        "Choice five"
                    ]
                },
                

            ]
        },
        
    ],

    "width": "1000px"
};
Survey.settings.lazyRowsRendering = true; // This is triggering the bug, but only under certain circumstances
const App = {
    template: '<SurveyComponent :model="survey" />',
    setup() {
        const survey = new Survey.Model(json);

        survey.onAfterRenderQuestion.add((survey, options) => {
          console.log('onAfterRenderQuestion ',options.question.title, options.htmlElement);
          if (options.htmlElement) {
             options.htmlElement.setAttribute('style', 'background:green');
          }
           
           
        });
        return {survey};
    }
};
Vue.createApp(App)
    .use(SurveyVue.surveyPlugin)
    .mount("#app");
```


Thanks, I hope this is helpful, I think it's something to do with the lazy loading setting combined with 'visibleIf'

**Comment by dk981234** [comment]
Hello,

Thanks for your investigation. Now I see the problem in the implementation of the question component.
We will try to fix the issue with the `onAfterRenderQuestion` event in the next minor update.
