### ISSUE TITLE
Unit tests related to Signaturepad failing

### ISSUE THREAD

**Issue by Ahmad-anility** [surveyjs/survey-library#7174]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting failing unit test

### What is the current behavior?
Currently when I run unit test 2 unit test fails. Both of them are related to `signaturepad`. 

```
Chrome Headless 118.0.5993.70 (Mac OS 10.15.7) question signaturepad Check signaturepad signauteWidth/Height properties FAILED
.
.
Chrome Headless 118.0.5993.70 (Mac OS 10.15.7) question signaturepad Check signaturepad signauteWidth/Height properties FAILED

.
.
Chrome Headless 118.0.5993.70 (Mac OS 10.15.7): Executed 2672 of 2673 (2 FAILED) 
```

tested on master branch current commit is `51bade9243e44c1741b274e97408381195155d16`

**Comment by andrewtelnov** [comment]
@Ahmad-anility We run then on Ubuntu. Probably there is a difference. Could you check your signuturepad version?
Here is [the link](https://dev.azure.com/SurveyJS/SurveyJS%20Integration%20Tests/_build?definitionId=56) on our CI. It is green.

Thank you,
Andrew

**Comment by Ahmad-anility** [comment]
@andrewtelnov , the version in the package.json is `^4.1.5` . But the latest is `4.1.6` therefore in my package-lock it is `4.1.6` I even tried the exact version `4.1.5` and it is still the same. 

Cheers

**Comment by tsv2013** [comment]
I have similar issue on macOS. We can add the <any> cast in our code.
