### ISSUE TITLE
Dropdown - Accessibility Issue - The Clear button's caption is read twice by NVDA

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7260]
User Issue: T15286 - Accessibility test
https://surveyjs.answerdesk.io/internal/ticket/details/T15286
***
To reproduce the issue, run NVDA and hover over the Clear button. It is announces as 'Clear Clear':
![image](https://github.com/surveyjs/survey-library/assets/22372972/8f04f9db-557b-4892-a725-ddd9de840f9d)

**Comment by dmitrykurmanov** [comment]
closed in favor of https://github.com/surveyjs/survey-library/issues/7259
