### ISSUE TITLE
Nouislider Start option

### ISSUE THREAD

**Issue by CodeCurosity** [surveyjs/survey-library#7348]
for Nouislider start option surveyjs is using defaultValue but it only accepts one start option, how can we have a range option with multiple handles e.g     start: [4000, 8000],

**Comment by JaneSjs** [comment]
Hello @CodeCurosity,
SurveyJS uses a third-party NoUISlider library. You can extend the default NoUISlider implementation ([nouislider.js](https://github.com/surveyjs/custom-widgets/blob/master/src/nouislider.js)) and add a [start range](https://refreshless.com/nouislider/slider-options/#section-start) for the NoUISlider widged.

Thanks
