### ISSUE TITLE
Problem to use Lazy Loading

### ISSUE THREAD

**Issue by dongosiddik** [surveyjs/survey-library#7354]
Hello team,
I am currently retrieving the complete list of countries from a RESTful Web service. My own API returns a very large dataset that takes too much time to load.
I've seen that it's necessary to use "Lazy Loading" but I'm having trouble incorporating it into this JSON. Please correct me.
Additionally, I would like to know what the differences are between version v1 and v2.
Best regards

`{
          "type": "dropdown",
          "name": "country",
          "title": "Select a country",
          "description": "Une liste complète des pays est interrogée à partir d'un service Web RESTful.",
          "choicesByUrl": {
            "url": "https://surveyjs.io/api/CountriesExample",
            "valueName": "identifier"
          },
          "defaultValue": "FRA",
          "choicesLazyLoadEnabled": true,
          "choicesLazyLoadPageSize": 40

        },`

**Comment by andrewtelnov** [comment]
@dongosiddik We don't have the second version for our SurveyJS Library. It is still v1.x.
You have to implement event handlers to make lazy loading work. Please review [this example](https://surveyjs.io/form-library/examples/lazy-loading-dropdown/reactjs#content-docs).

Thank you,
Andrew
