### ISSUE TITLE
[Ranking] Option to override default placeholder text

### ISSUE THREAD

**Issue by GER-Jani** [surveyjs/survey-library#7357]
### Are you requesting a feature, reporting a bug or asking a question?
Feature

### What is the current behavior?
There is no option to adapt placeholder text (_"Drag and drop choices here to rank them"_)

### What is the expected behavior?
A field in the SurveyJS designer or accepted property in JSON format to override the default placeholder text (e. g. override to _"Drag and drop intuitively"_)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/published?id=d7dc829d-2128-474d-89fd-92081c5453e2

Test code

```
{
 "logoPosition": "right",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "ranking",
     "name": "question1",
     "title": "How would you deal with situation xyz?",
     "description": "I would most likely deal with situation xyz as follows ...",
     "hideNumber": true,
     "isRequired": true,
     "choices": [
      {
       "value": "Item 1",
       "text": "This is a very long description to deal with situation xyz in case of A."
      },
      {
       "value": "Item 2",
       "text": "This is a very long description to deal with situation xyz in case of B."
      },
      {
       "value": "Item 3",
       "text": "This is a very long description to deal with situation xyz in case of C."
      },
      {
       "value": "Item 4",
       "text": "Another very long description to deal with situation xyz in case of D."
      }
     ],
     "selectToRankEnabled": true,
     "selectToRankAreasLayout": "vertical"
    }
   ]
  }
 ]
}
```

### Specify your

* browser: Google Chrome
* browser version: Version 119.0.6045.124
* surveyjs platform (angular or react or jquery or knockout or vue): Website
* surveyjs version: Current

**Comment by andrewtelnov** [comment]
@GER-Jani Please use "selectToRankEmptyUnrankedAreaText" and "selectToRankEmptyRankedAreaText" properties to setup these strings.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@RomanTsukanov please add documentation for these properties. We missed them.
@dmitrykurmanov We need to make them serializable.

Thank you,
Andrew

**Comment by RomanTsukanov** [comment]
I think we need to create a category for "select to rank"-related properties.
