### ISSUE TITLE
Dropdown - A search placeholder doesn't display while spaces within a long caption

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7369]
User Issue: T15583 - native dropdown with obsolete bootstrap theme
https://surveyjs.answerdesk.io/internal/ticket/details/T15583
***
To reproduce the issue, paste the following JSON to https://surveyjs.io/create-free-survey:
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "dropdown",
     "name": "question4",
     "choices": [
      "Item 1",
      "Item 2",
      {
       "value": "Item 3",
       "text": "very very very long text"
      },
      {
       "value": "Item 4",
       "text": "very very very very very long text1"
      }
     ]
    }
   ]
  }
 ]
}
```
As you start typing, the space disappears:
![image](https://github.com/surveyjs/survey-library/assets/22372972/45e4cac8-24ca-40d8-9c13-69eb7fbcddf4)

https://github.com/surveyjs/survey-library/assets/22372972/01fd4249-8c71-457c-911a-a9a2f616d3ed

**Comment by novikov82** [comment]
We found that the root of the issue on our site is 
```css
body { 
    word-spacing: -1px;
}
```

We are going to remove it.
If ones really need for word-spacing then add the same word-spacing to the inputs, something like:
```css
body input { 
    word-spacing: -1px;
}
```
