### ISSUE TITLE
using {field-name} as defaultValue?

### ISSUE THREAD

**Issue by CodeCurosity** [surveyjs/survey-library#7371]
I would like to use variable e.g {field-name} or custom variable {anyvar} inside defaultValue attribute, why it doesn't work?

**Comment by andrewtelnov** [comment]
@CodeCurosity "defaltValue" is a constant, Please use `defaultValueExpression` property.

Thank you,
Andrew

**Comment by CodeCurosity** [comment]
Fantastic, thank you.
