### ISSUE TITLE
Create a hidden question with defaultValue without showing it to user?

### ISSUE THREAD

**Issue by CodeCurosity** [surveyjs/survey-library#7372]
I can't seem to find any documentation to create hidden input e.g i want to collect data of which browser user is using in a hidden field that is sent to post data but without user seeing it, visible : false doesn't send the data.

**Comment by andrewtelnov** [comment]
@CodeCurosity Please set [clearIfInvisible ](https://surveyjs.io/form-library/documentation/api-reference/question#clearIfInvisible) question property to "none".

Thank you,
Andrew
