### ISSUE TITLE
The survey.onValueChanged function is raised with an empty array [] as a Dynamic Panel value

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7378]
T15604 - Paneldynamic trigger onValueChanged Event
https://surveyjs.answerdesk.io/internal/ticket/details/T15604
***
Usage scenario: a Panel Dynamic is made visible when a Boolean value is true. When a Boolean value is false, the Dynamic Panel question is invisible and its value is not included in survey data. However, the `survey.onValueChanged` event is raised and the `options.value` parameter returns an empty array `[]`.

Expected behavior: the `survey.onValueChanged` event is not raised because no value is actually changed.

**Comment by andrewtelnov** [comment]
@JaneSjs It works correctly. It replace the array with one empty object with undefined on survey complete.

Thank you,
Andrew
