### ISSUE TITLE
sumInArray doesn't work for checkbox values in expression?

### ISSUE THREAD

**Issue by CodeCurosity** [surveyjs/survey-library#7380]
I have a checkbox with multiple options, why i can't sum the values using sumInArray in expression?

**Comment by CodeCurosity** [comment]
I created a custom function to make it work, i am surprised why this isn't available by default.

`    function sumArrayValues(params) {
        if (!params || params.length === 0) return 0;
      
        var arrayValues = params[0];
        var sum = 0;
      
        for (var i = 0; i < arrayValues.length; i++) {
          // Check if the value is numeric before adding to the sum
          var numericValue = parseFloat(arrayValues[i]);
          
          if (!isNaN(numericValue)) {
            sum += numericValue;
          }
        }
      
        return sum;
      }
      
      Survey.FunctionFactory.Instance.register("sumArrayValues", sumArrayValues);`

**Comment by JaneSjs** [comment]
Hello,
The [sumInArray](https://surveyjs.io/form-library/documentation/design-survey/conditional-logic#suminarray) function should be used to calculate the summary over an array of values. This function should be used to summaries field values of questions which value is an array: [Dynamic Panel](https://surveyjs.io/form-library/examples/duplicate-group-of-fields-in-form/) and [matrix](https://surveyjs.io/form-library/examples/single-selection-matrix-table-question/) question types.

A Checkbox question's value is not an array. Therefore, you can use the [sum](https://surveyjs.io/form-library/documentation/design-survey/conditional-logic#sum) function to calculate a summary of selected checkbox items. Please consider this simple survey:
```json
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "checkbox",
     "name": "question1",
     "choices": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5"
     ]
    },
    {
     "type": "expression",
     "name": "question2",
     "expression": "sum({question1})"
    }
   ]
  }
 ],
 "calculatedValues": [
  {
   "name": "score"
  }
 ]
}
```
Let me know if you have any further questions.

Thanks
