### ISSUE TITLE
Rating question. Wrong item's border.

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#7391]
Patient Registration demo's theme.
There was no plan to draw white outside border.

![Image](https://github.com/surveyjs/survey-library/assets/17025812/abb73347-5ed2-490f-9e6f-7b36a5b316a5)

**Comment by novikov82** [comment]
this border is transparent
and the background of item is white
you use here inner shadow, that is drawn inside the border

what about using outside shadow?
![Image](https://github.com/surveyjs/survey-library/assets/29385489/6de4bb33-c4eb-4262-99b0-cf5aab04c6c6)
