### ISSUE TITLE
Unique column/answer totals and single select answer choices per row

### ISSUE THREAD

**Issue by ilaplain15115** [surveyjs/survey-library#7395]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

Table one: 
Calculates total for each column/ answer choice. However, there is the ability to select multiple answers per row/ question
Table two:
Only able to select one answer per row. The total columns are not unique to each individual answer choice.

### What is the expected behavior?

I want to find the best way to calculate a total count for columns/ answer choices. I want to only be able to select one answer choice per row/ question. What is the best way to do this or is this possible?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
{
 "title": "Github 2",
 "logoPosition": "right",
 "pages": [
  {
   "name": "page4",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "question1-10",
     "title": "Questions 1- 10",
     "hideNumber": true,
     "questionCategory": "surveyquestion",
     "columns": [
      {
       "name": "PC.answer.yes",
       "title": "Answer",
       "cellType": "radiogroup",
       "totalType": "count",
       "choices": [
        "Yes"
       ],
       "storeOthersAsComment": true
      },
      {
       "name": "PC.answer.N/A",
       "title": "Answer",
       "cellType": "radiogroup",
       "choices": [
        "N/A"
       ],
       "storeOthersAsComment": true
      },
      {
       "name": "PC.answer.no",
       "title": "Answer",
       "cellType": "radiogroup",
       "colCount": 0,
       "totalType": "count",
       "choices": [
        "No"
       ],
       "otherText": "No (Please describe)",
       "storeOthersAsComment": true
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      "1.",
      "2.",
      "3.",
      "4.",
      "5.",
      "6.",
      "7.",
      "8.",
      "9.",
      "10."
     ]
    },
    {
     "type": "matrixdropdown",
     "name": "question1",
     "title": "Questions 1- 10",
     "hideNumber": true,
     "questionCategory": "surveyquestion",
     "columns": [
      {
       "name": "PC.answer.yes",
       "title": "Answer",
       "cellType": "radiogroup",
       "colCount": 0,
       "showInMultipleColumns": true,
       "totalType": "count",
       "choices": [
        {
         "value": "Yes",
         "text": "Highly Effective"
        },
        {
         "value": "No",
         "text": "Effective"
        },
        {
         "value": "Item 1",
         "text": "Partial"
        }
       ],
       "showOtherItem": true,
       "otherText": "Needs improvement",
       "storeOthersAsComment": true
      }
     ],
     "choices": [
      1,
      2,
      3,
      4
     ],
     "rows": [
      "1.",
      "2.",
      "3.",
      "4.",
      "5.",
      "6.",
      "7.",
      "8.",
      "9.",
      "10."
     ]
    }
   ],
   "title": "Practice"
  }
 ]
}

```

### Specify your

* browser: Chrome
* browser version: 119.0.6045.160
* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version: 1.9.112

**Comment by JaneSjs** [comment]
Hello @ilaplain15115,
Please accept my apologies for the delayed reply.

From what I gather, you wish to complete the following tasks:
* Allow users to select a single option per row.
* Calculate the total count of column answers.

Please refer to the following ticket where I shared a solution to achieve this task: [Single Select Matrix - Display totals under columns](https://surveyjs.answerdesk.io/internal/ticket/details/T14259#09a360a9-8485-4f52-83ac-05b69c62984a).

Feel free to reactivate this thread if you have any further questions.

Thanks
