### ISSUE TITLE
CV2: Order grid component align in KnockoutJS

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-library#7410]
https://surveyjstest.azurewebsites.net/Examples/Survey-Creator?id=component-ordertable&platform=KnockoutjsV2&theme=modern
![Screenshot 2021-10-20 100217-order](https://user-images.githubusercontent.com/29385489/138065409-219a7b0e-4cf3-470f-beaa-d76213b9e0f4.png)

**Comment by andrewtelnov** [comment]
@novikov82 It has been fixed while working on [this issue](https://github.com/surveyjs/survey-library/issues/7338).

Thank you,
Andrew
