### ISSUE TITLE
Background image loading method.

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#7419]
Can we make something more attractive?

![Image](https://github.com/surveyjs/survey-library/assets/17025812/5a80aa67-5cf4-40c3-ad71-cc14a14902f4)

**Comment by OlgaLarina** [comment]
For this effect, you can use the progressive JPEG format. You can convert your image to progressive format using Adobe Photoshop. How to do this is indicated in this article.
https://medium.com/hd-pro/jpeg-formats-progressive-vs-baseline-73b3938c2339
