### ISSUE TITLE
feature - add event editing on paneldynamics tabs buttons

### ISSUE THREAD

**Issue by macone** [surveyjs/survey-library#7437]
### Are you requesting a feature, reporting a bug or asking a question?

FEATURE

in paneldynamics tabs we should be able to modify a event on clicking "Previous", "Next", "Add New", "Remove".
I was ask for making scroll to the top of a paneldynamic element on clicking "add new" button on PanelDynamic tab 
i was not able do it in surveyjs so I need to catch in that button in plain javascript and add that event

### What is the current behavior?

We can not edit the event in surveyjs of  "Previous", "Next", "Add New", "Remove" in paneldynamicsTab

### What is the expected behavior?

We should be able to edit events of those (add)

### How would you reproduce the current behavior (if this is a bug)?

its on every 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: 
https://plnkr.co/edit/IHfMtPtwzi9U90VE?preview

**Comment by JaneSjs** [comment]
Hi @macone,
Thank you for sharing a demo. From what I gather, you wish to scroll a form to the top when a user adds a new panel. I would recommend that you handle the [survey.onDynamicPanelAdded](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onDynamicPanelAdded) function. Within this function, call the [survey.focusFirstQuestion()](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#focusFirstQuestion) function to focus the Dynamic Panel question, which is the first question on the current page.
```
survey.onDynamicPanelAdded.add((sender, options) => {
       sender.focusFirstQuestion();
})
```
[View Plunker](https://plnkr.co/edit/pjknLJ2Y8sx6RnLZ)
If you have multiple questions, you can use the [survey.focusQuestion('questionName')](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#focusQuestion) function to focus a specified question.

I hope this API helps. Please let us know if you have any further questions.

Thanks
