### ISSUE TITLE
Progress bar remains pages as selected.

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#7462]
![Image](https://github.com/surveyjs/survey-library/assets/17025812/afd9dcf9-ac69-46bd-a15a-b44578013462)

**Comment by tsv2013** [comment]
We're using here the passed property of a page:
```
  public get passed(): boolean {
    return this.getPropertyValue("passed", false);
  }
  public set passed(val: boolean) {
    this.setPropertyValue("passed", val);
  }
```
to style progress bar. That's why it behaves so.
