### ISSUE TITLE
Custom Properties - Clarification on creating custom properties of a expression/condition type - the 'onExecuteExpression' function is needed

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7490]
Usage Scenario: https://surveyjs.answerdesk.io/internal/ticket/details/T15667#df020e69-8347-40b3-92e3-544e5a0f55bf

When you implement a custom property of the expression or condition type, it is mandatory to implement the [onExecuteExpression](https://surveyjs.io/survey-creator/documentation/property-grid-customization#onexecuteexpression) function and store a function evaluation result.

**Comment by RomanTsukanov** [comment]
We'll add docs for this use case to the following demo in future releases: [Implement a Custom Expression Property](https://surveyjs.io/form-library/examples/add-custom-expression-property/).
