### ISSUE TITLE
Popup Survey - The minimize and close button order is incorrect

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7506]
T16038 - Popup Icons wrong order
https://surveyjs.answerdesk.io/internal/ticket/details/T16038

[View Plunker](https://plnkr.co/edit/wkRAAi0ZwV5ysWgA)
It is suggested to change the order or buttons of a PopupSurvey. Currently, the close button goes before the minimize button.
![image](https://github.com/surveyjs/survey-library/assets/22372972/a8003d9a-6972-4bb6-ac98-e64dff09ccba)

The Minimize button should be displayed before Close.

**Comment by AndOne1974** [comment]
And i would suggest to have a "full screen" button too!

**Comment by JaneSjs** [comment]
Hi @AndOne1974,
Thank you for your idea. We agree that it would be a nice addition to our Popup Survey. I created a separate issue in this regard: https://github.com/surveyjs/survey-library/issues/7518.

Thanks

**Comment by JaneSjs** [comment]
Regarding the original task: we are currently working on redesigning our PopupSurvey. The minimize and close buttons will be reordered once the following task is closed: https://github.com/surveyjs/service/issues/1668.
