### ISSUE TITLE
focusFirstQuestionAutomatic not working

### ISSUE THREAD

**Issue by jumper572** [surveyjs/survey-library#7512]
Hello.
When I open a page it automatically scrolls to the bottom survey, how can I turn this off (disable page scroll)?

Demo code:
`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>TEST</title>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script type="text/javascript" src="https://unpkg.com/survey-jquery/survey.jquery.min.js"></script>
</head>

<body>

TEST 

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

	<div id="surveyContainer_6"></div>

	<script>
	const surveyJson = {
	"focusFirstQuestionAutomatic": false,
	"focusOnFirstError": false,
	"goNextPageAutomatic": true,
		"pages": [{"name":"page_1","title":"","elements":{"type":"radiogroup","name":"question_id_43","title":"\u0427\u0442\u043e \u0442\u0430\u043a\u043e\u0435 email-\u043c\u0430\u0440\u043a\u0435\u0442\u0438\u043d\u0433?","colCount":"1","isRequired":"true","choices":[{"answer_id":"149","value":"\u041f\u0440\u043e\u0434\u0430\u0436\u0430 \u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u044b\u0445 \u043f\u0438\u0441\u0435\u043c"},{"answer_id":"150","value":"\u041f\u0440\u043e\u0434\u0432\u0438\u0436\u0435\u043d\u0438\u0435 \u0431\u0438\u0437\u043d\u0435\u0441\u0430 \u0447\u0435\u0440\u0435\u0437 \u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u0443\u044e \u043f\u043e\u0447\u0442\u0443"},{"answer_id":"151","value":"\u041e\u0442\u043f\u0440\u0430\u0432\u043a\u0430 \u0430\u043a\u0446\u0438\u043e\u043d\u043d\u044b\u0445 SMS-\u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0439"},{"answer_id":"152","value":"\u041c\u0430\u0440\u043a\u0435\u0442\u0438\u043d\u0433\u043e\u0432\u044b\u0435 \u0438\u0441\u0441\u043b\u0435\u0434\u043e\u0432\u0430\u043d\u0438\u044f \u043f\u043e \u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u043e\u0439 \u043f\u043e\u0447\u0442\u0435"}]}}]
	};

	const survey = new Survey.Model(surveyJson);
	$("#surveyContainer_6").Survey({ model: survey });

	</script>

</body>
</html>`

**Comment by jumper572** [comment]
![2023-12-15_18-16-17](https://github.com/surveyjs/survey-library/assets/29145733/387b822a-8e88-4f39-a08c-8de54c33af16)

**Comment by andrewtelnov** [comment]
@jumper572 The issue has been introduced in v1.9.121. It has been fixed by [this PR](https://github.com/surveyjs/survey-library/pull/7501).
You can use the following work-around:
```js
survey.onScrollingElementToTop.add((sender, options) => {
 options.cancel = true;
});
```
Thank you,
Andrew

**Comment by jumper572** [comment]
Thank you very much, problem solved!
