### ISSUE TITLE
Popup Survey - Introduce a "full screen" mode

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7518]
And i would suggest to have a "full screen" button too!

_Originally posted by @AndOne1974 in https://github.com/surveyjs/survey-library/issues/7506#issuecomment-1857827750_

- [x] https://github.com/surveyjs/survey-library/issues/7762

**Comment by mikeamelin** [comment]
Prototype — https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Library-Preview?type=design&node-id=1870-151181&mode=design

**Comment by mikeamelin** [comment]
- [ ] the icon should be changed
![Screenshot 2024-01-25 at 15 33 51](https://github.com/surveyjs/survey-library/assets/17025812/7ccaeb64-0669-45f8-afe3-64583f1a0bcc)

- [ ] after opening from collapsed state
![Screenshot 2024-01-25 at 15 34 20](https://github.com/surveyjs/survey-library/assets/17025812/915e678c-f9a2-4f7b-9675-225285e16b7e)

- [ ] background should be fitted to the height

![Screenshot 2024-01-25 at 15 36 48](https://github.com/surveyjs/survey-library/assets/17025812/9b4a7290-be17-45d0-b087-1a3995bc4cb7)

- [ ] the popup should be collapsed in this case



https://github.com/surveyjs/survey-library/assets/17025812/75990d0e-a8ce-47ce-9283-de799ab28eb2

**Comment by mikeamelin** [comment]
- [ ] it is weird that scrollbars are different (macOS) for two mode — popup and fullscreen. Popup has native scrollbar, fullscreen — static

- [ ] button should be shifted for scrollbar size 

![Screenshot 2024-01-31 at 12 27 06](https://github.com/surveyjs/survey-library/assets/17025812/e7695e43-7c3d-4ebe-9dee-2fde4b7ce827)

- [ ] buttons shouldn't be disappeared during the scrolling
![Screenshot 2024-01-31 at 12 26 37](https://github.com/surveyjs/survey-library/assets/17025812/d6aed15f-b4d8-4f3c-9cce-b0f197dbde7e)

**Comment by mikeamelin** [comment]
- [ ] indent should be the same as right padding in the case with no scrollbar

![Screenshot 2024-02-02 at 12 04 43](https://github.com/surveyjs/survey-library/assets/17025812/9535b16c-f89f-4fc7-befc-2f343fc3b6a4)

- [ ] popup's bottom is cutted
![Screenshot 2024-02-02 at 12 05 15](https://github.com/surveyjs/survey-library/assets/17025812/aa678c58-6716-41ff-ad12-fe37b1501a95)

**Comment by mikeamelin** [comment]
- [ ] старая проблема с артефактами

MacOS, Safari/Chrome

Есть ощущение, что опрос, лежащий внутри попапа, имеет закругленные уголки, вровень с закруглениями попапа. Это может быть причиной следующих проблем... 

Какие-то стремные пиксели в заголовке — 
![Screenshot 2024-02-05 at 12 30 20](https://github.com/surveyjs/survey-library/assets/17025812/0b4827c2-39af-42ba-b09d-6e1c9a291113)

Именно вот этот момент говорит о том, что контент закругляется —
![Screenshot 2024-02-05 at 12 31 12](https://github.com/surveyjs/survey-library/assets/17025812/7da497ee-d70a-42fe-9dd6-0e68d226a326)

Закругление уголка и какой-то зазор (плавающий) — 
![Screenshot 2024-02-05 at 12 31 34](https://github.com/surveyjs/survey-library/assets/17025812/84fc9339-87fe-4df4-aae3-bd39840b1318)

Еще одни стремные зеленые пиксели — 
![Screenshot 2024-02-05 at 12 31 56](https://github.com/surveyjs/survey-library/assets/17025812/0220bdbe-0c19-470c-b3ba-47f2ad42011e)

**Comment by mikeamelin** [comment]
- [ ] скролбару лучше быть в цвет фона опроса

![Screenshot 2024-02-05 at 12 32 24](https://github.com/surveyjs/survey-library/assets/17025812/8bdbf573-8878-4b30-8430-2b7ac1fea9f5)
