### ISSUE TITLE
Add an event for setting authentication headers in a GET request made by `choiceByUrl`

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7528]
User issues
* T16070 - Set headers Authentication in ChoiceByUrl
https://surveyjs.answerdesk.io/internal/ticket/details/T16070
* T14803 - How could we consume different private APIs (Authenticated APIs) for dropdown.
https://surveyjs.answerdesk.io/internal/ticket/details/T14803
* T15766 - Survey PDF- How to get variable values in form?
https://surveyjs.answerdesk.io/internal/ticket/details/T15766
...and more
***

https://github.com/surveyjs/survey-library/blob/38bf35cd7667f16e0567bfe7081bb4d017dba5fc/src/choicesRestful.ts#L106C17-L106C36

**Comment by RomanTsukanov** [comment]
`settings.web.onBeforeRequestChoices`
