### ISSUE TITLE
How can I add ItemValue custom property in a matrix to the results output of a survey?

### ISSUE THREAD

**Issue by DworrallRC** [surveyjs/survey-library#7534]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question

### What is the current behavior?

Custom properties added to ItemValue (rows) in a Single-Select Matrix are not appearing in the results output (survey.data) of the survey.

![image](https://github.com/surveyjs/survey-library/assets/103633363/9d0a80d2-5589-4c20-a252-8ebee4ca862c)

### What is the expected behavior?

When using survey.data or Survey.getPlainData, I would have expected the additional properties to be included in the json for the matrix results.

I have added the properties to matrix when running the survey.

![image](https://github.com/surveyjs/survey-library/assets/103633363/e0fa908b-c77c-4877-9c8e-5248f1c3e471)

### How would you reproduce the current behavior (if this is a bug)?

[survejs matrix custom property output code.txt](https://github.com/surveyjs/survey-library/files/13725182/survejs.matrix.custom.property.output.code.txt)

### Specify your

* browser: Chrome
* browser version: Latest
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version:

**Comment by DworrallRC** [comment]
To try and clarify a little, when you call **survey.getQuestionByName('question2').rows** the properties are visible and have values for the ItemValue rows in the matrix:

![image](https://github.com/surveyjs/survey-library/assets/103633363/a5c1d31e-72b4-49c6-95c0-8ba878ea8869)

I am trying to get the abbreviation (or any other property) to accompany the selected answer in the results json.

**Comment by andrewtelnov** [comment]
@DworrallRC It should not be in the data since we store there question name (valueName) and question value.
How do you want to get the result? What format are you looking for?
Right now it is: ItemValue.value (where ItemValue is a row) and a row.value {rowName: rowValue}.

Thank you,
Andrew

**Comment by DworrallRC** [comment]
@andrewtelnov I'm looking for a mechanism to be able to include the associated properties for each row with the answers selected. The properties have been sucessfully configured - they are available in the definition. But these properties are then required in the results to categorise and enhance the selected answer. There needs to be a way to access the properties for each row alongside it's selected value.

In the meantime, I am transforming my own results output by combining the answers from plainData with the extra properties from definition:

` for (const row in question.rows) {
     var row_data = question.rows[row];
     var plainData = question.getPlainData();
     const row_item = {
         id: row_data.id,    // this is the FFM Question ID for matrix rows
         value: row_data.value,
         text: row_data.text,
         abbreviation: row_data.abbreviation,
         score: plainData.value[row_data.value],
         scoreTransformOption: row_data.scoreTransformOption        
     }                

     if (row_item != null && !!row_item && row_item.id != null) { 
         matrixRows.push(row_item);
     }
 }`

**Comment by JaneSjs** [comment]
Hello @DworrallRC,
Please accept my apologies for the delayed reply. In a Single-Select Matrix, the data array returns an array of objects which store column properties rather than row properties. Therefore, you would be able to include custom properties to column definitions and obtain them using the `survey.getPlainData` function passing the `calculations` object as it's demonstrated in the following demo: [Scored Survey](https://surveyjs.io/form-library/examples/create-a-scored-survey/reactjs#content-code).

However, if you wish to attach custom properties to rows, you may need to iterate through [QuestionMatrixModel.visibleRows](https://surveyjs.io/form-library/documentation/api-reference/matrix-table-question-model#visibleRows) array and generate a new response object. Consider the following demo: [View Plunker](https://plnkr.co/edit/8kHzoYXyQKp9UNjh).
```
 survey.onComplete.add((sender, options) => {
        console.log(JSON.stringify(sender.data, null, 3));
        const matrix = sender.getQuestionByName('question1');
        const res = [];
        matrix.visibleRows.forEach(row => {
            let rowObject = {
                [row.item.value]: row.value,
                abbreviation: row.item.abbreviation,
                scoreTransformOption: row.item.scoreTransformOption
            }
            res.push(rowObject);
});
```
Please let us know if you have further questions.
