### ISSUE TITLE
Choice options are not updated with changed choicesbyurl

### ISSUE THREAD

**Issue by satyam-saxen** [surveyjs/survey-library#7535]
### Are you requesting a feature, reporting a bug or asking a question?

It's a question mainly. But could be bug as well.

### What is the current behavior?
I have upgraded the survey version to latest 1.9.121 and it starts breaking the drop-down questions behaviour. In my case I'm using choices by url property and updating the url of this on page change. It is fetching the choice options based on updated url but there is one more fetch call which is using the initial choices url and resetting the options to the initial ones. Previously I was on version 1.9.25.

### What is the expected behavior?

On page change if the url is updated then the choices should be reflected in the drop-down questions according to the updated url.

### How would you reproduce the current behavior (if this is a bug)?

It's for matrix dynamic cell which is of type drop-down. I have a list of questions with the name of matrix dynamic questions and their cell which is used for this drop-down so that we can directly get those drop-down questions to update the choices which was working fine before upgrading.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
const question= survey.getQuestionByName('matrixdynamicquestion');
const column = question.getColumnByName('dropdownQuestionName');
column.choicesByUrl.url = updated url;
column.choicesByUrl.run();

I have also defined the path, titleName and valueName. And verifier it with survey.toJSON() that it has the updated choices url.

```

### Specify your

* browser:Google chrome
* browser version:latest 
* surveyjs platform (angular or react or jquery or knockout or vue):react
* surveyjs version:1.9.121

**Comment by andrewtelnov** [comment]
@satyam-saxen Please try to use the following code:
`column.templateQuestion..choicesByUrl.url = "updated url";`.
You don't need to call run for a column/templateQuestion, it has to be done for all cell questions in the column. However, it should work out of the box.
If the code I gave doesn't work, please let us know.

Thank you,
Andrew
