### ISSUE TITLE
How to integrate numberMask third party api into survay form 

### ISSUE THREAD

**Issue by shahbaazaliSatschel** [surveyjs/survey-library#7538]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@shahbaazaliSatschel Here is [the example](https://surveyjs.io/form-library/examples/control-data-entry-formats-with-input-masks). We will have our own mask implementation out of the box in several weeks.

Thank you,
Andrew
