### ISSUE TITLE
Animation: Ranking: Smooth height change after item removal

### ISSUE THREAD

**Issue by dmitry-kurmanov** [surveyjs/survey-library#7547]
![image](https://github.com/surveyjs/survey-library/assets/22315929/03e2b332-0903-4626-8e4b-2f98efaa58c2)

**Comment by mikeamelin** [comment]
- [ ] it's better to use animation step-by-step
![Screenshot 2024-02-23 at 17 24 16](https://github.com/surveyjs/survey-library/assets/17025812/e100db2e-a936-4d31-bd2f-c1fd70b70f40)

- [ ] looks like there is no animation for appearing

![Screenshot 2024-02-23 at 17 24 55](https://github.com/surveyjs/survey-library/assets/17025812/4e824285-916d-45b7-bf6d-63e23e73b6dd)

- [ ] and here
![Screenshot 2024-02-23 at 17 25 20](https://github.com/surveyjs/survey-library/assets/17025812/bd6b1732-ec43-4847-845d-882933cb5a18)

- [ ] and here when item is dropped back
![Screenshot 2024-02-23 at 17 29 00](https://github.com/surveyjs/survey-library/assets/17025812/bfcffbfe-8c2b-4bc3-8675-be38a25fd51f)

Also there is a couple of issues...

- [ ] the item on the right (#2) twitches

https://github.com/surveyjs/survey-library/assets/17025812/8335d81e-f1b4-4b64-8514-b7ad9c3d8537

- [ ] looks like there we have to turn height sizing animation off


https://github.com/surveyjs/survey-library/assets/17025812/e2b89acd-3885-412d-8bbd-0130e9f4b8ba
