### ISSUE TITLE
How to change html table text color based on value?

### ISSUE THREAD

**Issue by Juuso1** [surveyjs/survey-library#7567]
### Are you requesting a feature, reporting a bug or asking a question?
This is question how to change html table text color based on value in Surveyjs form?
Custom function or expression?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by JaneSjs** [comment]
Hello @Juuso1,
You can use [question values](https://surveyjs.io/form-library/documentation/design-survey/conditional-logic#question-values) in HTML question content. To use values, wrap a question or calculated value's name with curly braces. 

Please consider this demo:
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "dropdown",
     "name": "question1",
     "defaultValue": "red",
     "choices": [
      {
       "value": "red",
       "text": "Red"
      },
      {
       "value": "orange",
       "text": "Orange"
      },
      {
       "value": "blue",
       "text": "Blue"
      }
     ]
    },
    {
     "type": "html",
     "name": "question2",
     "html": "<span style='color:{question1}'><b>Hello World</b></span>"
    }
   ]
  }
 ]
}
```
Let me know if you have any further questions.

Thanks
