### ISSUE TITLE
popupsurvey not showing description

### ISSUE THREAD

**Issue by truezjz** [surveyjs/survey-library#7568]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

popupsurvey not showing description

### What is the expected behavior?

popupsurvey show show description on top of the popup window

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version: any version
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.9.122

**Comment by truezjz** [comment]
thanks Jane,  I know the popup survey can display the title,  but it does NOT display the description property of the survey, in the regular survey like this example : https://surveyjs.io/stay-updated/blog/survey-branding-in-creator, it can display the description,  is that supposed to be?

**Comment by JaneSjs** [comment]
Hello @truezjz,
Thank you for the update. To let us consider the best option, would you please clarify where you expect a description to appear? You can share a demo image for reference.

Thanks

**Comment by JaneSjs** [comment]
@truezjz,
I discussed this issue with our developers. We are currently redesigining our Pop-Up Survey. With a new design, a survey description will be available within a popu-up form. If you wish to subscribe to further updates regarding this task, please visit https://github.com/surveyjs/service/issues/1668.

Thanks
