### ISSUE TITLE
Dropdown list data displays incorrectly 

### ISSUE THREAD

**Issue by Minhvu17ctt7** [surveyjs/survey-library#7577]
Are you requesting a feature, reporting a bug or asking a question?

 What is the current behavior?
1. Set survey mode is "display" and set all questions is read-only
2. Click on dropdown question (1, 3, 5, 7,.... times)
3. Click the edit button (set survey mode is "edit" and set all questions read-only mode is false)
4. observer =>  Dropdown list option display incorrectly position (left corner)

What is the expected behavior?
4. Dropdown list option display incorrectly position (below dropdown question)

https://github.com/surveyjs/survey-library/assets/38001765/2d495967-576b-4fba-97eb-2f2c3c263b5b

**Comment by JaneSjs** [comment]
To resolve the issue, upgrade a SurveyJS library version to the latest one: v1.9.123.

Thanks
