### ISSUE TITLE
Ranking: Carry Forward: Support Unarranged behavior

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/survey-library#7583]
based on the https://surveyjs.answerdesk.io/internal/ticket/details/T16166

**Comment by JaneSjs** [comment]
It appears that the [Select Items To Rank](https://surveyjs.io/form-library/examples/select-items-to-rank/reactjs) mode may be used instead.

**Comment by dmitrykurmanov** [comment]
> It appears that the [Select Items To Rank](https://surveyjs.io/form-library/examples/select-items-to-rank/reactjs) mode may be used instead.

I created draft just in case. If we decide to support this feature we will need @RomanTsukanov for API
