### ISSUE TITLE
Does there exist a published JSON spec that outlines surveyJS? 

### ISSUE THREAD

**Issue by jpgilchrist** [surveyjs/survey-library#7619]
Do you have an existing JSON specification? I.e., a JSON validator that we can adhere to. I'm trying to convert a home grown survey system and structured referential db structure to SurveyJS and I'm trying to find the easiest way to convert said system to your json structure. I see there's various documentation, but I don't see a specific set of docs that just communicate the JSON structure itself. 

Thanks in advance.

### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
n/a

### What is the expected behavior?
n/a

### How would you reproduce the current behavior (if this is a bug)?
n/a

#### Provide the test code and the tested page URL (if applicable)
n/a

### Specify your
n/a

**Comment by SamMousa** [comment]
You can ask the serializer to create a schema for you. See #2523

**Comment by jpgilchrist** [comment]
@SamMousa thanks.
