### ISSUE TITLE
Regex validator not validating when using case-insensitive flag

### ISSUE THREAD

**Issue by gregpawlowski** [surveyjs/survey-library#7620]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Regex validator doesn't validate for case insensitive flag

### What is the expected behavior?
Should validate

### How would you reproduce the current behavior (if this is a bug)?
Enter the following validator in suvejs json:
```
     "validators": [
      {
       "type": "regex",
       "text": "Please enter a valid something.com email",
       "regex": "/.+@something.com/i"
      }
     ],
     "inputType": "email",
```

When entering a test such as "test@SOMETHING.COM" the validator fails. I have tried using // instead of one /.  It does not appear that case insensitive match is working. 

### Specify your
* browser: Chrome
* browser version:119.0.6045.200
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* Fails in survey creator https://surveyjs.io/create-free-survey

**Comment by andrewtelnov** [comment]
@gregpawlowski Interesting. I was not able to make it works either.
Our code is pretty simple: `new RegExp(this.regex);` and then `re.test(value)`.
We will take a look.

Thank you,
Andrew

**Comment by gregpawlowski** [comment]
Thank you. 

The problem appear to be anytime / is used to specify a regex value. It's not just because of the case insensitive flag but anytime / is used in the regex expression in the beginning and end.

Is there maybe some get/set on the value that sanitized/encodes it?

**Comment by gregpawlowski** [comment]
Thank You @andrewtelnov ,
The problem is when using / in the valus. 

 RegExp constructor will sanitize string, flags are passed as second argument. Onlu using regex literal in javscript allows for // and passing flags at the end. 

From console:
new RegExp("/.*@something.com/i")
returns: /\/.*@something.com\/i/

However passing the i as a second argument
new RegExp(".*@something.com", "i")
return /.*@something.com/i

Only regex literal syntax allows for passing in flags /.

Maybe a check can be made on the value? Check if beginning and end have / and pass in flags or use regex literal syntax?

**Comment by andrewtelnov** [comment]
@gregpawlowski I decided to implement the easiest possible solution for now. We may need a better code if more flags something wish to set. However, at the current moment "i" is the only flag that can be used here.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@gregpawlowski At the end, we decided to add a boolean property "insensitive".

Thank you,
Andrew

**Comment by yanhuiyi** [comment]
Hi @andrewtelnov,
I got the same issue, how can I add literal value in regexp? For example, I would check if an email ending with .edu domain. It should be case insensitive. Thanks!
