### ISSUE TITLE
Vue.js - Survey model cannot be a computed property

### ISSUE THREAD

**Issue by morphet81** [surveyjs/survey-library#763]
### What is the current behavior?
If the survey model is set as a computed property, the first page is displayed correctly but navigation buttons in the survey do not work.

### What is the expected behavior?
It should be possible to set the model as a computed poperty or to mention clearly it cannot.

### How would you reproduce the current behavior (if this is a bug)?
Set the model as a computed property

### Specify your

* browser: Firefox
* browser version: 56.0.2 (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 0.95.0

**Comment by tsv2013** [comment]
@morphet81 Could share the plunker (or another sandbox/application) example, illustrating the problem, to check it on our side?

**Comment by neilhosey** [comment]
This is also a problem for me.  Using it in data() works fine but as a computed property it doest, it shows, but the Complete button or choosing any answers on raido button questions does not work.

**Comment by tsv2013** [comment]
@neilhosey Could share the plunker (or another sandbox/application) example, illustrating the problem, to check it on our side?
