### ISSUE TITLE
TagBox with the enabled hideSelectedItems option - The popup window height is not decreased when selecting items 

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7631]
[View Demo](https://plnkr.co/edit/hyh38EMYdom3Xjum)
In earlier versions, the popup window's height was decreased as soon as you select items:
![image](https://github.com/surveyjs/survey-library/assets/22372972/20058793-519a-40b7-a2f5-1b7216dbe56c)

In v1.9.124, the popup window height remains as soon as items are selected:
![image](https://github.com/surveyjs/survey-library/assets/22372972/65b31438-d754-432c-b99e-677a11b1b61b)
![image](https://github.com/surveyjs/survey-library/assets/22372972/570acd6e-a914-47bd-880b-5e43e4c208af)

**Comment by OlgaLarina** [comment]
https://github.com/surveyjs/survey-library/issues/6205
