### ISSUE TITLE
survey.onCurrentPageChanged event can be fired multiple times on clicking TOC or progress bar button

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#7633]
We have code duplication in TOC and progress button classes and they doesn't work correctly.
The code should not navigate from the current selected page into new selected page by changing pages one by one.
It should validate through all pages and stay in a page if there is an error on it. If there is no error on the page, then survey should not make a page current, but proceed to another page immediately.

Introduce `survey.tryNavigateToPage(page: PageModel): boolean;' function.

**Comment by SamMousa** [comment]
This new flow breaks the `validationEnabled` setting since it is validating pages without checking the setting. See #7705.
