### ISSUE TITLE
Can't install survey-angular-ui with Angular version 15.2.5

### ISSUE THREAD

**Issue by xiaohanInvictiq** [surveyjs/survey-library#7639]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question, am not sure if it is a bug or just you didn't update your official website

### What is the current behavior?
I'm trying to run "npm install survey-angular-ui --save" and my program has an Angular version 15.2.5, but got the error message:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: audit@0.0.0
npm ERR! Found: @angular/common@15.2.10
npm ERR! node_modules/@angular/common
npm ERR!   dev @angular/common@"^15.2.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^17.0.0 || ^18.0.0" from @angular/cdk@17.0.4
npm ERR! node_modules/@angular/cdk
npm ERR!   peer @angular/cdk@"*" from survey-angular-ui@1.9.124
npm ERR!   node_modules/survey-angular-ui
npm ERR!     survey-angular-ui@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### What is the expected behavior?

According to the description on your official website: "SurveyJS for Angular requires Angular v12.0.0 or newer and depends on the @angular/cdk package. " Ideally it should be installed successfully with Angular 15, isn't it?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version:

**Comment by andrewtelnov** [comment]
@xiaohanInvictiq Will seting package and version to @angular/cdk in your package.json solve the issue?
We don't put any restriction here.

Thank you,
Andrew

**Comment by xiaohanInvictiq** [comment]
> @xiaohanInvictiq Will seting package and version to @angular/cdk in your package.json solve the issue? We don't put any restriction here.
> 
> Thank you, Andrew

Oh! Yes, adding the version for @angular/cdk works, thank you!
