### ISSUE TITLE
A survey model is generated long time for a Multi-Page Survey with TOC

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7659]
Issue: a survey model initialization takes 13 seconds on a customer's machine.
A demo are available at [T16308 - Survey page lazyload](https://surveyjs.answerdesk.io/internal/ticket/details/T16308).

**Comment by andrewtelnov** [comment]
It should work faster in 5 times and more, after we merge PR for [this issue](https://github.com/surveyjs/survey-library/issues/7662).

Thank you,
Andrew
