### ISSUE TITLE
Force surveyjs to recalculate after function registration

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#7694]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
Say I have a function `toUpper` that changes a string to upper case.
I create the survey model but only after it has been created the function `toUpper` is registered.

Can I tell the survey model to re-evaluate all calculations? 
Notes:
- This is all happening before the survey is rendered for the first time
- I do not control the function registration, while I can detect when it happens called I cannot control when it happens

### What is the expected behavior?
Ideally surveyJS should detect any function registration and update the relevant expressions automatically.

Alternatively there should be a clean way to notify SurveyJS that something has changed. For calculated values specifically I can work around it by doing this:
```js
survey.calculatedValues[0].setOwner(survey.calculatedValues[0].data);
```
But this is not feasible for things like `visibleIf`, I'd have to iterate recursively over every element and check every expression again.
Instead the proper solution is to add the function definition as a dependency and recalculate when the dependency is changed.

### How would you reproduce the current behavior (if this is a bug)?
I don't think it's a bug but you can see demo sandbox below.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codesandbox.io/p/sandbox/stupefied-cartwright-zdyrqt
**NOTE**
Due to the way knockout and the sandbox work, make sure you do an actual reload when testing changes.
![image](https://github.com/surveyjs/survey-library/assets/547021/3a738374-2b25-42d5-8550-7e0440c0a455)

### Specify your

* browser: chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: latest

**Comment by SamMousa** [comment]
Workaround for now: `survey.setVariable('__someRandomName', 1)` recalculates everything.

**Comment by andrewtelnov** [comment]
@SamMousa We have added `survey.runExpressios()` function that you can call.

Thank you,
Andrew
