### ISSUE TITLE
How can I integrate the surver.js license key with angular?

### ISSUE THREAD

**Issue by Nikunjwdv0106** [surveyjs/survey-library#7698]
I have the buy the surver.js license key. However, I need help finding documentation for integrating the license key with angular.
My Survey.js Version like below:
```
"survey-angular-ui": "^1.9.126",
"survey-core": "^1.9.126",
```
Can anyone please suggest how I can integrate the license key?

**Comment by andrewtelnov** [comment]
@Nikunjwdv0106 Please go on [this page](https://surveyjs.io/remove-alert-banner) and follow the instructions.

Thank you,
Andrew

**Comment by kartikwatwani** [comment]
I am using setLicenseKey function but still the message is being shown.

`<span class="svc-creator__non-commercial-text">To use our library, a <a href="https://surveyjs.io/licensing">developer license</a> is required. If you have an active license, <a href="https://surveyjs.io/remove-alert-banner">set up your license key</a> and ensure you're using the latest version.</span>`

**Comment by andrewtelnov** [comment]
@kartikwatwani Please use our technical support at https://surveyjs.answerdesk.io/ to solve the issue.

Thank you,
Andrew
