### ISSUE TITLE
Navigation from the TOC not allowed

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#7705]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
When navigation from the TOC navigation is not allowed if there are invalid questions, even though I've set `validationEnabled` to `false`.

### What is the expected behavior?
If I can navigate to the next page using the **Next** button I should also be able to navigate using the TOC. In other words, disabling validation should allow free navigation using the TOC.

### How would you reproduce the current behavior (if this is a bug)?
1. Create a survey with multiple pages
2. Add a required question on the first page
3. Enable the table of contents
4. Disable validation by setting `survey.validationEnabled = false;`
5. Attempt to navigate via the TOC, confirm it doesn't work.
6. Attempt to navigate via the **next**, confirm it does work.

### Specify your

* browser: chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: 125

**Comment by andrewtelnov** [comment]
@SamMousa We have fixed this issue in [this PR](https://github.com/surveyjs/survey-library/pull/7684).

Thank you,
Andrew
