### ISSUE TITLE
No result when copying an answer to an invisible question

### ISSUE THREAD

**Issue by zagadeka** [surveyjs/survey-library#7708]
Having an invisible question with the logic of copying an answer from another question, the answer is missing from the resulting JSON.

### Are you requesting a feature, reporting a bug or asking a question?

I wonder if this is a feature or a bug.

### What is the current behavior?

There is no answer to the invisible question in the result JSON.

### What is the expected behavior?

The resulting JSON file contains the copied answer to the invisible question.

### Provide the test code and the tested page URL (if applicable)

Survey template:
`{
 "title": "NPS Survey Question",
 "completedHtml": "<h3>Thank you for your feedback</h3>",
 "completedHtmlOnCondition": [
  {
   "html": "<h3>Thank you for your feedback</h3> <h4>We are glad that you love our product. Your ideas and suggestions will help us make it even better.</h4>"
  },
  {
   "html": "<h3>Thank you for your feedback</h3> <h4>We are glad that you shared your ideas with us. They will help us make our product better.</h4>"
  }
 ],
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "checkbox",
     "name": "question1",
     "isRequired": true,
     "choices": [
      "Item 1",
      "Item 2",
      "Item 3"
     ]
    },
    {
     "type": "checkbox",
     "name": "question2",
     "visible": false,
     "isRequired": true,
     "choices": [
      "Item 1",
      "Item 2",
      "Item 3"
     ]
    }
   ]
  }
 ],
 "triggers": [
  {
   "type": "copyvalue",
   "expression": "{question1} notempty",
   "fromName": "question1",
   "setToName": "question2"
  }
 ],
 "showQuestionNumbers": "off"
}`

JSON result:
`{
    "question1": [
        "Item 2"
    ]
}`

SurveyJS version: v1.9.77, v1.9.126

**Comment by andrewtelnov** [comment]
@zagadeka You can set the [survey.clearInvisibleValues](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#clearInvisibleValues) to "none".
You can set it on a question level by using [question.clearIfInvisible](https://surveyjs.io/form-library/documentation/api-reference/text-entry-question-model#clearIfInvisible) property by setting it to "none".

Thank you,
Andrew

**Comment by zagadeka** [comment]
@andrewtelnov Thank you very much! That solves the problem.
