### ISSUE TITLE
A custom Checkbox Item's event is invoked only for precreated Matrix rows

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7717]
User issue and Demo: T16454 - Custom item component is not rendering for Dynamic Matrix
https://surveyjs.answerdesk.io/internal/ticket/details/T16454

To reproduce the issue, run the customer's demo. Change the checked state of the cities column. The  `CustomCheckboxItemTemplateComponent.onChanged` event will be invoked and the following console messages appear. However, if you add more rows and check their `cities` values, the `onChanged` event won't be invoked and no messages appear.

![image](https://github.com/surveyjs/survey-library/assets/22372972/c8c660ac-01e5-4f7e-beba-6de410b598be)

**Comment by andrewtelnov** [comment]
@JaneSjs  
I have checked this functionality for React and Angular and it works for me.
Here are examples: [React](https://plnkr.co/edit/aUZobOoDWJy3jB3V) and [Angular](https://codesandbox.io/p/sandbox/surveyjs-angular-forked-jgvkmn?file=%2Fsrc%2Fapp%2Fcomponents%2Fjson.ts%3A36%2C1).

Thank you,
Andrew
