### ISSUE TITLE
[Vue] HTML markup in question titles and descriptions does not apply

### ISSUE THREAD

**Issue by ngekoding** [surveyjs/survey-library#7722]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
The question title keeping showing HTML markup.

Actually it is the same issue with https://github.com/surveyjs/survey-library/issues/6209 in Angular version.

### What is the expected behavior?
The question title must showing the result of the HTML markup, like <u> for underline, etc.

### How would you reproduce the current behavior (if this is a bug)?
Just add HTML tag to the question title.

#### Provide the test code and the tested page URL (if applicable)
https://codesandbox.io/p/sandbox/surveyjs-html-markup-in-question-title-vue-2tcc2j?file=%2Fsrc%2Fcomponents%2FMyFirstSurvey.vue

![Surveyjs Vue](https://github.com/surveyjs/survey-library/assets/11625690/88e9897c-3a66-4958-a8be-5b4b0a3d4154)

### Specify your

* browser: Chrome
* browser version: Version 120.0.6099.234 (Official Build) (x86_64)
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: Latest

**Comment by JaneSjs** [comment]
Hi @ngekoding,
To format Markdown text as HTML, register a Markdown processing library and implement the survey.onTextMarkdown function to convert Markdown to HTML. For more information, visit [Convert Markdown to HTML with Showdown](https://surveyjs.io/form-library/examples/edit-survey-questions-markdown/vue3js#content-code).
