### ISSUE TITLE
Dynamic Matrix: `alternateRows` doesn't work

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-library#7746]
https://plnkr.co/edit/nZzzIScanjWHSUoh

**Comment by novikov82** [comment]
We can just add class name definition to devaultV2Css.ts
```js
matrixdynamic: {
    //...
    rootAlternateRows: "sd-table--alternate-rows",
    //...
}
```
But as the result we will have

![Image](https://github.com/surveyjs/survey-library/assets/29385489/c1bca464-0b6b-4cfb-b707-abfd0f75d992)

Maybe better solution is to hide `alternateRows` property from matrix dynamic.

**Comment by novikov82** [comment]
Results of quick solution


![Image](https://github.com/surveyjs/survey-library/assets/29385489/15cba07e-7b31-4298-80e7-3d50ec7b6ffa)
