### ISSUE TITLE
Add refuse and don't know items into select base (checkobox, dropdown, radiogroup and tagbox)

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#7754]
We need an optional two more items that will work similar to none: showRefuseItem and showDonotKnowItem. These properties should be invisible by default.
To enable this functionality in Creator you will need to make this properties visible as the following:
```js
import { Serializer } from "survey-core";

Serializer.findProperty("selectbase", "showRefuseItem");
Serializer.findProperty("selectbase", "showDontKnowItem");

```

**Comment by SamMousa** [comment]
Really nice that this feature landed.
I'm a bit stumped that you didn't go for a generic solution that I've already proposed years ago: https://github.com/surveyjs/survey-library/issues/4778

While a great improvement, this approach of having 1000s of options vs a few generic ones seems bad for everyone: more work for you, fewer use cases for us! Anyway, cheers for adding this!
