### ISSUE TITLE
Popup Survey in Full Screen Mode - A scrollbar doesn't appear

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7762]
To reproduce the issue, run the demo and activate the full screen mode. A scrollbar doesn't appear.
![image](https://github.com/surveyjs/survey-library/assets/22372972/d6430d6f-88b4-45fd-b41b-6dea73edf952)

[PopupSurveyFullScreen.zip](https://github.com/surveyjs/survey-library/files/14095888/PopupSurveyFullScreen.zip)

**Comment by dmitry-kurmanov** [comment]
fixed in https://github.com/surveyjs/survey-library/issues/7518
