### ISSUE TITLE
Knockout-ui: ReferenceError: survey is not defined

### ISSUE THREAD

**Issue by cami-espinozaq** [surveyjs/survey-library#7801]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug in the last release

### What is the current behavior?

When loading a survey with the new Progress Bar UI, the `knockout-latest-js` package fails to load it, rising the following error:

```
knockout-latest.js:16 Uncaught ReferenceError: Unable to process binding "css: function(){return survey.css.progressButtonsContainer }"
Message: survey is not defined
    at css (eval at parseBindingsString (knockout-latest.js:74:172), <anonymous>:3:56)
    at update (knockout-latest.js:99:258)
    at a.$.l (knockout-latest.js:79:379)
    at Function.yd (knockout-latest.js:55:359)
    at Function.zd (knockout-latest.js:55:45)
    at Function.ha (knockout-latest.js:54:384)
    at a.o.a.$ (knockout-latest.js:52:147)
    at knockout-latest.js:79:366
    at Object.D (knockout-latest.js:11:52)
    at p2 (knockout-latest.js:78:408)
```

### What is the expected behavior?

To render the new Progress Bar without any errors.

### How would you reproduce the current behavior (if this is a bug)?

One can visit an example with the Progress Bar (like https://surveyjs.io/form-library/examples/configure-form-navigation-with-progress-indicators/) and try edit it with CodeSandbox > Knockout. It just renders the error.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

https://codesandbox.io/p/sandbox/white-butterfly-4kpyqv

### Specify your

* browser: Google Chrome
* browser version: Version 114
* surveyjs platform (angular or react or jquery or knockout or vue): Knockout
* surveyjs version: `1.9128`

**Comment by tsv2013** [comment]
It's a known and fixed (upcoming release) issue - New Progress bar UI is not working for Knockout #5141
