### ISSUE TITLE
Progress Bar Issues

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#7810]
- [ ] hover — https://www.figma.com/file/i6Lpc7zkjHtso2oXZV97fo/*-Components?type=design&node-id=20213-132926&mode=design&t=pjMwIorInVSzYqJt-4

- [ ] fit-to-survey mode — https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Library-Preview?type=design&node-id=1852-111846&mode=design&t=I3tXxTp3bGz11GDG-4

- [ ] option to switch progress bar's view (old or new) in the property grid

- [ ] theming issues — looks like wrong color's variables for this element 

![Image](https://github.com/surveyjs/survey-library/assets/17025812/ad3440b7-92d4-4630-8c6d-e7b5cae25c7d)

**Comment by tsv2013** [comment]
Fixed:
- hover
- fit to survey mode
Decided not to implement
- option to switch progress bar's old view
