### ISSUE TITLE
How can we take HTML response from html using survey creator?

### ISSUE THREAD

**Issue by chaklasiyanikunj** [surveyjs/survey-library#7862]
How can we receive the result?
here is my html which is i used using survey creator.

```
<body>
<form>
  <input class="sd-input" type="text" id="inputBox" name="inputBox"><br>
  <input class="sd-input" type="submit" value="Submit">
</form>
</body>
```

But when I show the preview It's shows fine. But when I click on complete It's not showing on result.
Can you pleas suggest how can we receive response from html field?

**Comment by JaneSjs** [comment]
Hello,
HTML questions are read-only survey elements. If you wish to capture user input and include it within survey results, consider using a [Text Entry](https://surveyjs.io/form-library/examples/text-entry-question/reactjs)/[Comment](https://surveyjs.io/form-library/examples/add-open-ended-question-to-a-form/reactjs) fields.

Please feel free to reactivate this thread if you have any further questions.
