### ISSUE TITLE
How to remove complete button

### ISSUE THREAD

**Issue by Bashar-Alziq** [surveyjs/survey-library#7870]

**Comment by andrewtelnov** [comment]
Please set [survey.showCompleteButton](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#showCompleteButton) property to false.

Thank you,
Andrew

**Comment by Bashar-Alziq** [comment]
showCompleteButton property is not exist on survey

> Thank you, Andrew

**Comment by JaneSjs** [comment]
Hello @Bashar-Alziq,
Please refer to the following demo: [View Plunker](https://plnkr.co/edit/FNEpyFQYDb83tzhd).
```
survey.showCompleteButton = false;
```
A complete button disappears as needed:
![image](https://github.com/surveyjs/survey-library/assets/22372972/89036403-7255-4211-8df6-d3b2f7d3bf50)

Please drop us a line if you have any further questions.
