### ISSUE TITLE
How can I update my code from StylesManager.applyTheme to survey.aplpyTheme

### ISSUE THREAD

**Issue by Hidend** [surveyjs/survey-library#7883]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
Once back, I applied this theme:
Survey.StylesManager.applyTheme("winterstone");
Now I updated SurveyJS and I'm not sure how to keep using that theme since colours changed to a green one instead of orange, I have read the docs and it says that StylesManager is deprecated, so how can I use that orange theme?.

### What is the expected behavior?
That I can keep using that theme with updated surveyJS, I guess it changed from StylesManager to survey.applyTheme(SurveyTheme.LayeredDarkPanelless);
But how can I use the winterstone theme?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
Not applicable

### Specify your

* browser: Chrome
* browser version: 121.0.6167.184/185
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.9.129

**Comment by JaneSjs** [comment]
Hello @Hidend,
We may need additional time to research this issue. Please stay tuned.

**Comment by JaneSjs** [comment]
Hi @Hidend,
To apply a Winterstone theme, follow these steps.
* Import the `survey.css` style sheet.
```
```
* Call the `StylesManager.applyTheme("winterstone")` function after a `SurveyModel` initialization.
```
StylesManager.applyTheme("winterstone"); 
```
[View Demo](https://plnkr.co/edit/VjRjF26YLfe5aStt)

Please let me know if you have further questions.
