### ISSUE TITLE
Rating Scale with stars: Support half points

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-library#7885]
It's not unusual for surveys to have a rating scale that allows selecting half a point, so that users could leave ratings like 3.5/5, 8.5/10, etc.

**Comment by novikov82** [comment]
https://plnkr.co/edit/aQLcLoX7KNtcZjCN
It requires some special disign decisions.
I dont think that this feature is useful in survey mode.


![Image](https://github.com/surveyjs/survey-library/assets/29385489/4b6760b3-811f-485e-b693-2703fa054035)
