### ISSUE TITLE
Function isValueEqual return false for equals arrays

### ISSUE THREAD

**Issue by FHourmy** [surveyjs/survey-library#7886]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
function isValueEqual returns false when comparing arrays

### What is the expected behavior?
function isValueEqual  should return true for arrays when elements are the same (or at least when reference is the same)

#### Provide the test code and the tested page URL (if applicable)
repro : https://codesandbox.io/s/pensive-babbage-nq43rr
you can see in the console the comparison results when clicking a checkbox (see function added to onValueChanged)

### Specify your

* surveyjs platform (angular or react or jquery or knockout or vue): jquery 
* surveyjs version: 1.9.127

**Comment by andrewtelnov** [comment]
@FHourmy survey.isValueEqual is a private function that except one name (question name) and a value. You don't need to use it.
You can use Helpers.isTwoValueEquals() function.
It has value1 and value2 as two first parameters and 3 optional parameters:
```js
    x: any,
    y: any,
    ignoreOrder: boolean = false,
    caseSensitive?: boolean,
    trimStrings? : boolean
```
The class is located in `survey-core` in your case you can use it as:
`Survey.Helpers.isTwoValueEquals([1, 2], [1, 2]);`.

Thank you,
Andrew
SurveyJS Team
