### ISSUE TITLE
Is there any example available for adding a custom button using a custom widget?

### ISSUE THREAD

**Issue by chaklasiyanikunj** [surveyjs/survey-library#7910]
I hope you guys are doing well.
I checked your custom widget documentation [here](https://surveyjs.io/form-library/documentation/customize-question-types/create-custom-widgets). However, in that documentation, I did not find any proper details for how I could add any custom control using the custom widget.
Is there any example or proper documentation available for adding a custom button or anchor tag in survey JS?

**Comment by JaneSjs** [comment]
Hi @chaklasiyanikunj,
If you wish to add a custom button to survey questions, you may consider the following options.
* Register a custom button which appears within a question's title area. For more information on this option, refer to [Context Actions in Element Titles](https://surveyjs.io/form-library/examples/modify-titles-of-survey-elements/reactjs).
* Depending on your development platform, implement a custom [React](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-react)/[Angular](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-angular)/[Vue 3](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-vue) component and register it as a separate survey element. 

Should you have any further questions, please feel free to reactivate this thread.
