### ISSUE TITLE
File Upload - The upload file button remains highlighted and clickble in read-only mode

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7927]
T17111 - File Upload Question in display mode: button still highlighted and clickable
https://surveyjs.answerdesk.io/internal/ticket/details/T17111
***
[View Demo](https://plnkr.co/edit/HNgpenqA0GvlvUN0)

https://github.com/surveyjs/survey-library/assets/22372972/734119ce-f0a1-4ca2-a550-63aaf713c559

**Comment by Grubiopa** [comment]
Hi, I have another issue connected to upload files. Could be connected?
https://github.com/surveyjs/survey-library/issues/7907
