### ISSUE TITLE
Group results inside panel

### ISSUE THREAD

**Issue by marvin-wtt** [surveyjs/survey-library#7928]
### Are you requesting a feature, reporting a bug or asking a question?

Feature 

### What is the current behavior?

Questions inside a panel are not grouped by their panel valueName.

### What is the expected behavior?

It would be nice if there was an option to group the questions in a panel by their valueName or an additional property. 
Example scenario:
The form contains an address of the user and the guardian. Instead of having a flat JSON with fields like `guardian_zip_code`, `guardian_city`... It would be nice to group them into objects with identical keys, like `guardian: { zipCode: "", city: "" }`

I offer to create a PR for this feature, but I'd like to collect some thoughts on what would be the best option first.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

```json
"pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "panel",
     "name": "question1",
     "elements": [
      {
       "type": "text",
       "name": "question2"
      }
     ]
    }
   ]
  }
```
Result
```json
{
  "question1": {
    "question2:": "value-here"
  }
}
```

### Specify your

* browser: /
* browser version: / 
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by JaneSjs** [comment]
Hello @marvin-wtt,
Thank you for reaching out to us. By default, a [survey.data](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#data) object has the following structure:
```js
{
   'questionName': 'questionValue'
}
```
If you wish to get survey results and preserve the structure of a survey with page names as nodes, you can call the [survey.getStructuredData](https://github.com/surveyjs/survey-library/blob/master/src/survey.ts#L2560C39-L2574) function on survey completion (the [survey.onComplete](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onComplete) event handler).
```
survey.onComplete.add((sender, options) => {
      let data = sender.getStructuredData();
      // Save data to your storage
});
```
For more information on how to store survey results, you may also wish to review the following topic: [Store Survey Results](https://surveyjs.io/form-library/documentation/handle-survey-results-store).

Please let me know if you have any questions or require further assistance.

**Comment by marvin-wtt** [comment]
Hello @JaneSjs, 

Using `getStructuredData` does not seem to work as it only structures by pages, not by panels, and also does not allow for identical `valueName` properties within different nodes.

I'd like to structure the data within panels, as this feels like the most natural way. Dynamic panels already nest their data similarly. It would be nice to have the same behavior as a custom question, just directly within the editor. 

My proposal would be to use the existing `valueName` property on pages and panels. Another option would be to introduce a new property to opt-in nesting to not introduce a breaking change compared to the current behavior.

This would require some changes, as changes in questions with the same`valueName` must only propagate within the same node.

As already mentioned, I offer to create a PR, but I'd like your opinion first to not was my time.

**Comment by JaneSjs** [comment]
Hello @marvin-wtt,
Please accept my apologies for the delayed reply. If you wish to group answers under a common key, consider creating a composite component: [View Demo](https://surveyjs.io/survey-creator/examples/add-address-to-form-template/).
I'm afraid we may not consider modifying the structure of a survey response. If you wish to group repeated panels under the same key, consider using a Dynamic Panel. As for the identical `valueName`: it is used to combine answers from multiple fields within the same object.

Drop me a line if you have more questions.
