### ISSUE TITLE
defaultValue may work incorrectly for one question per page mode

### ISSUE THREAD

**Issue by letitechera** [surveyjs/survey-library#7932]
**Reporting a bug**

I recently updated surveyjs from v1.9.116 to v1.9.132 and the behavior for some of my panel questions broke.

The expected behavior should be that the first question in my panel, which is a radiogroup question, should have a defaultValue, if that value is selected then I show the text input from the next question in the panel. Since it's the default value, the input should be shown on survey load by default. But now it is not!
I have to choose another option and then select that option again for the text input to show.

This was working in v1.9.116 as expected. But it broke after updating to v1.9.132.
(It is impacting the business of the company I work for).

Here is a codesandbox with the example to reproduce the error: [codesandbox](https://codesandbox.io/p/sandbox/sweet-bouman-f9x89x?file=%2Fpackage.json%3A6%2C31&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltegzhfb0007356kpb79a8sc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltegzhfb0003356kv623b517%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltegzhfb0004356k50smesve%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltegzhfb0006356k7vef8mij%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltegzhfb0003356kv623b517%2522%253A%257B%2522id%2522%253A%2522cltegzhfb0003356kv623b517%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltg3dacu0002356j0w0xjevp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A55%252C%2522startColumn%2522%253A10%252C%2522endLineNumber%2522%253A55%252C%2522endColumn%2522%253A10%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fjson.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cltg483f10002356jjejqhiq9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A31%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A31%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltg483f10002356jjejqhiq9%2522%257D%252C%2522cltegzhfb0006356k7vef8mij%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltegzhfb0005356k6vnsami8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltegzhfb0006356k7vef8mij%2522%252C%2522activeTabId%2522%253A%2522cltegzhfb0005356k6vnsami8%2522%257D%252C%2522cltegzhfb0004356k50smesve%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltegzhfb0004356k50smesve%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
(I added multiple panel questions to show it, because sometimes it doesn't happen to the first one)

* Browser: Google Chrome

**Comment by andrewtelnov** [comment]
@letitechera Your code sandbox is likely private.

Thank you,
Andrew

**Comment by letitechera** [comment]
@andrewtelnov Sorry about that, just made it public, try accessing the link again

**Comment by andrewtelnov** [comment]
@letitechera Here is the [small reproduciable example](https://plnkr.co/edit/GIRpTAYoUeOudsrP).
As a current work-around, you can comment `questionsOnPageMode: "questionPerPage"` in JSON and set this property after loading model.
We will take a look and comeback to you.
