### ISSUE TITLE
[New Feature] Description for every rating item instead of min and max only

### ISSUE THREAD

**Issue by HenryWu01** [surveyjs/survey-library#7937]
### Are you requesting a feature, reporting a bug or asking a question?

Feature Request

### What is the current behavior?

We can only set the description for min value and max value.

![brave_WksOxWboJY](https://github.com/surveyjs/survey-library/assets/99880210/a578b17c-e88e-44d5-9000-25999cd2afa1)

### What is the expected behavior?

We can set the description for every rating value.

![brave_SffPtjAtNg](https://github.com/surveyjs/survey-library/assets/99880210/4ca36fc9-f0be-4d28-b4e3-50e758a2fe28)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Brave
* browser version: 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit) 
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.9.128

**Comment by JaneSjs** [comment]
Hello @HenryWu01,
Thank you for your inquiry.
By default, Rating Scale displays item captions in a tooltip. If you wish to display an item's text underneath the item, you can implement a custom item template for a Rating question and display the value under the rate item. An example is available at [Rating Scale: Custom Item Component Support](https://surveyjs.io/stay-updated/release-notes/v1.9.113#rating-scale-custom-item-component-support).

You can implement a custom rate item component on top of a default template and display a value label under the rate item. 

Consider the following demo: [View Stackblitz](https://stackblitz.com/edit/react-ioyjur?file=src%2Fjson.js).

**App.js**
```
import React from 'react';
import './style.css';
import { Model } from 'survey-core';
import { Survey } from 'survey-react-ui';
import 'survey-core/defaultV2.min.css';
import { json } from './json';
import { SvgRegistry } from 'survey-core';
import {
  ReactElementFactory,
  SurveyElementBase,
  SvgIcon,
} from 'survey-react-ui';

class CustomChoiceItem extends SurveyElementBase {
  renderElement() {
    const question = this.props.question;
    const item = this.props.item;

    const isDisplayMode = this.isDisplayMode;
    const handleOnClick = this.props.handleOnClick;
    const handleOnMouseDown = this.props.handleOnMouseDown;
    const index = this.props.index;
    return (
      <label
        onMouseDown={handleOnMouseDown}
        className={`${question.getItemClass(item.itemValue)} outer-label`}
        onMouseOver={(e) => question.onItemMouseIn(item)}
        onMouseOut={(e) => question.onItemMouseOut(item)}
      >
        <input
          type="radio"
          className="sv-visuallyhidden"
          name={question.name}
          id={question.getInputId(index)}
          value={item.value}
          disabled={isDisplayMode}
          checked={question.value == item.value}
          onClick={handleOnClick}
          onChange={() => {}}
          aria-required={question.ariaRequired}
          aria-label={question.ariaLabel}
          aria-invalid={question.ariaInvalid}
          aria-describedby={question.ariaDescribedBy}
        />
        <SvgIcon
          className={'sv-star'}
          size={'auto'}
          iconName={question.itemStarIcon}
          title={item.text}
        ></SvgIcon>
        <SvgIcon
          className={'sv-star-2'}
          size={'auto'}
          iconName={question.itemStarIconAlt}
          title={item.text}
        ></SvgIcon>
        <label className={'caption'}>{item.text}</label>
      </label>
    );
  }
}
ReactElementFactory.Instance.registerElement('custom-rate-item', (props) => {
  return React.createElement(CustomChoiceItem, props);
});

export default function App() {
  const survey = new Model(json);
  survey.onComplete.add((sender, options) => {
    console.log(JSON.stringify(sender.data, null, 3));
  });
  return <Survey model={survey} />;
}
```
**style.css**
```
.caption {
  margin-top: 50px;
}
.outer-label {
  display: flex;
  flex-direction: column;
  align-items: center;
}
```
**json.js**
```
export const json = {
  elements: [
    {
      type: 'rating',
      name: 'satisfaction-smileys-colored',
      title: 'How satisfied are you with our product?',
      description: 'Smiley rating with colored scale',
      rateType: 'stars',
      scaleColorMode: 'colored',
      autoGenerate: false,
      rateValues: [
        {
          value: 1,
          text: 'Terrible',
        },
        {
          value: 2,
          text: 'Poor',
        },
        {
          value: 3,
          text: 'Average',
        },
        {
          value: 4,
          text: 'Good',
        },
        {
          value: 5,
          text: 'Perfect',
        },
      ],
      displayMode: 'buttons',
      itemComponent: 'custom-rate-item',
    },
  ],
  showQuestionNumbers: false,
};

```
![image](https://github.com/surveyjs/survey-library/assets/22372972/11f40863-4eec-45cf-bac5-2c5c5fc920b0)
Please drop me a line if you have further questions.
***
A similar issue was also discussed at https://surveyjs.answerdesk.io/ticket/details/T15178.

**Comment by HenryWu01** [comment]
> Hello @HenryWu01, Thank you for your inquiry. By default, Rating Scale displays item captions in a tooltip. If you wish to display an item's text underneath the item, you can implement a custom item template for a Rating question and display the value under the rate item. An example is available at [Rating Scale: Custom Item Component Support](https://surveyjs.io/stay-updated/release-notes/v1.9.113#rating-scale-custom-item-component-support).
> 
> You can implement a custom rate item component on top of a default template and display a value label under the rate item.
> 
> Consider the following demo: [View Stackblitz](https://stackblitz.com/edit/react-ioyjur?file=src%2Fjson.js).
> 
> **App.js**
> 
> ```
> import React from 'react';
> import './style.css';
> import { Model } from 'survey-core';
> import { Survey } from 'survey-react-ui';
> import 'survey-core/defaultV2.min.css';
> import { json } from './json';
> import { SvgRegistry } from 'survey-core';
> import {
>   ReactElementFactory,
>   SurveyElementBase,
>   SvgIcon,
> } from 'survey-react-ui';
> 
> class CustomChoiceItem extends SurveyElementBase {
>   renderElement() {
>     const question = this.props.question;
>     const item = this.props.item;
> 
>     const isDisplayMode = this.isDisplayMode;
>     const handleOnClick = this.props.handleOnClick;
>     const handleOnMouseDown = this.props.handleOnMouseDown;
>     const index = this.props.index;
>     return (
>       <label
>         onMouseDown={handleOnMouseDown}
>         className={`${question.getItemClass(item.itemValue)} outer-label`}
>         onMouseOver={(e) => question.onItemMouseIn(item)}
>         onMouseOut={(e) => question.onItemMouseOut(item)}
>       >
>         <input
>           type="radio"
>           className="sv-visuallyhidden"
>           name={question.name}
>           id={question.getInputId(index)}
>           value={item.value}
>           disabled={isDisplayMode}
>           checked={question.value == item.value}
>           onClick={handleOnClick}
>           onChange={() => {}}
>           aria-required={question.ariaRequired}
>           aria-label={question.ariaLabel}
>           aria-invalid={question.ariaInvalid}
>           aria-describedby={question.ariaDescribedBy}
>         />
>         <SvgIcon
>           className={'sv-star'}
>           size={'auto'}
>           iconName={question.itemStarIcon}
>           title={item.text}
>         ></SvgIcon>
>         <SvgIcon
>           className={'sv-star-2'}
>           size={'auto'}
>           iconName={question.itemStarIconAlt}
>           title={item.text}
>         ></SvgIcon>
>         <label className={'caption'}>{item.text}</label>
>       </label>
>     );
>   }
> }
> ReactElementFactory.Instance.registerElement('custom-rate-item', (props) => {
>   return React.createElement(CustomChoiceItem, props);
> });
> 
> export default function App() {
>   const survey = new Model(json);
>   survey.onComplete.add((sender, options) => {
>     console.log(JSON.stringify(sender.data, null, 3));
>   });
>   return <Survey model={survey} />;
> }
> ```
> 
> **style.css**
> 
> ```
> .caption {
>   margin-top: 50px;
> }
> .outer-label {
>   display: flex;
>   flex-direction: column;
>   align-items: center;
> }
> ```
> 
> **json.js**
> 
> ```
> export const json = {
>   elements: [
>     {
>       type: 'rating',
>       name: 'satisfaction-smileys-colored',
>       title: 'How satisfied are you with our product?',
>       description: 'Smiley rating with colored scale',
>       rateType: 'stars',
>       scaleColorMode: 'colored',
>       autoGenerate: false,
>       rateValues: [
>         {
>           value: 1,
>           text: 'Terrible',
>         },
>         {
>           value: 2,
>           text: 'Poor',
>         },
>         {
>           value: 3,
>           text: 'Average',
>         },
>         {
>           value: 4,
>           text: 'Good',
>         },
>         {
>           value: 5,
>           text: 'Perfect',
>         },
>       ],
>       displayMode: 'buttons',
>       itemComponent: 'custom-rate-item',
>     },
>   ],
>   showQuestionNumbers: false,
> };
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/22372972/314051909-11f40863-4eec-45cf-bac5-2c5c5fc920b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTA2NjcsIm5iZiI6MTcxMTAxMDM2NywicGF0aCI6Ii8yMjM3Mjk3Mi8zMTQwNTE5MDktMTFmNDA4NjMtNGVlYy00NWNmLWJhYzUtMmM1YzVmYzkyMGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA4MzkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYTRkNWIyOTdkMWNhMzk4ODE5MzIzZDkyOGEyNmFjOWNiOGViNTMwNjY2ODA0ODg2NGFlOGM3MmI0MzYxNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tG4imHjz9c5UetplxcGyDr9OrEhFvOtbT1EK0Q9FcJ4) Please drop me a line if you have further questions.
> 
> A similar issue was also discussed at https://surveyjs.answerdesk.io/ticket/details/T15178.

Thank you for the quick response. May I ask that how does the ``margin-top: 50px;`` calculated from? Can we wrap the ``SvgIcon`` and ``input`` inside a ``div``?

**Comment by JaneSjs** [comment]
Hello @HenryWu01,
> May I ask that how does the margin-top: 50px; calculated from?

This value is hardcoded within CSS. You may wish to calculate this value depending on a survey's base unit. With this option, a top margin will be adjusted depending on the `--sjs-base-unit` value defined within a survcey theme. I updated the demo: [View Stackblitz](https://stackblitz.com/edit/react-tt4yja?file=src%2FApp.js,src%2Fstyle.css,src%2Fsurvey_theme.js,package.json).

> Can we wrap the SvgIcon and input inside a div?

You can update a custom item component as needed as long as the custom template produces the target output. 

Please feel free to reopen this thread if you have any further questions.
