### ISSUE TITLE
[Bug] Rating scale display vertically instead of horizontally

### ISSUE THREAD

**Issue by HenryWu01** [surveyjs/survey-library#7939]
### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

![chrome_WL5YXEP2au](https://github.com/surveyjs/survey-library/assets/99880210/a87e77be-42ed-416a-b938-9ba6e4d87121)

### What is the expected behavior?

![brave_NJNUAgl66D](https://github.com/surveyjs/survey-library/assets/99880210/2b4ca439-ee55-4227-8d5f-3c6a10be0269)

### How would you reproduce the current behavior (if this is a bug)?

On older browsers, Chrome 76 or below. Chrome 83+ seems fine.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/create-free-survey

Test code

```
Using Chrome 76, go to survey creator and create a rating question. Then the error is appeared.
```

### Specify your

* browser: Chrome
* browser version: Chrome 76.0.3809.100
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.9.128

**Comment by JaneSjs** [comment]
Hello @HenryWu01,
It appears that the issue occurs on an older Chrome version. I didn't manage to reproduce the issue on my end (using Chrome Version 122.0.6261.112 (Official Build) (64-bit)).
![image](https://github.com/surveyjs/survey-library/assets/22372972/7f8e5ef4-29bc-4fc7-92b4-e99c27f54bdd)

Please upgrade your Chrome version.
