### ISSUE TITLE
Cant use question name when using join variable (formerly known as valueName)

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#7944]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
Documentation (https://surveyjs.io/form-library/documentation/design-survey/conditional-logic#question-values) states: 
> To use a question value as a placeholder, specify the question's [name](https://surveyjs.io/Documentation/Library?id=Question#name) in curly brackets. The name will be replaced with the question value.

### What is the expected behavior?
That it works as explained in the docs.

### How would you reproduce the current behavior (if this is a bug)?

Go to the page below. It might just be a documentation bug.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/wAxQTPXyExGTFiXU

```
const json = {
  "elements": [
    {
      "type": "panel",
      "name": "contactinfo",
      "elements": [
        {
          "type": "text",
          "name": "email",
          "title": "E-mail address",
          "inputType": "email",
          "autocomplete": "email",
          "valueName": "different"
        },
        {
          "type": "text",
          "name": "phone",
          "title": "Phone number",
          "inputType": "tel",
          "autocomplete": "tel"
        },
        {
          "type": "text",
          "name": "telegram",
          "title": "Telegram"
      }
      ],
      "title": "Contact Information",
      "isRequired": true
    },
    {
      "type": "checkbox",
      "name": "contactby",
      "visible": false,
      "visibleIf": "{email} notempty or {phone} notempty or {telegram} notempty",
      "title": "How we may contact you?",
      "isRequired": true,
      "choices": [
        {
          "value": "email",
          "text": "By e-mail: {email}",
          "visibleIf": "{email} notempty"
        },
        {
          "value": "phonecall",
          "text": "By a phone call: {phone}",
          "visibleIf": "{phone} notempty"
        },
        {
          "value": "sms",
          "text": "By SMS: {phone}",
          "visibleIf": "{phone} notempty"
        },
        {
          "value": "telegram",
          "text": "By Telegram: {telegram}",
          "visibleIf": "{telegram} notempty"
        },
        {
          "value": "dontcontact",
          "text": "I don't want to be contacted"
        }
      ]
    }
  ],
  "showQuestionNumbers": false
 };

```

### Specify your

* browser: N/A
* browser version: N/A
* surveyjs platform (angular or react or jquery or knockout or vue): N/A
* surveyjs version: .133

**Comment by JaneSjs** [comment]
Hi @SamMousa,
I apologies for the delayed response. 
The [`question.valueName`](https://surveyjs.io/form-library/documentation/api-reference/question#valueName) setting has a higher priority than [`question.name`](https://surveyjs.io/form-library/documentation/api-reference/question#name). Therefore, if you specify `valueName`, you need to use it within question placeholders. Consider the updated JSON:
```
{
  "elements": [
    {
      "type": "panel",
      "name": "contactinfo",
      "elements": [
        {
          "type": "text",
          "name": "email",
          "title": "E-mail address",
          "inputType": "email",
          "autocomplete": "email",
          "valueName": "different"
        },
        {
          "type": "text",
          "name": "phone",
          "title": "Phone number",
          "inputType": "tel",
          "autocomplete": "tel"
        },
        {
          "type": "text",
          "name": "telegram",
          "title": "Telegram"
      }
      ],
      "title": "Contact Information",
      "isRequired": true
    },
    {
      "type": "checkbox",
      "name": "contactby",
      "visible": false,
      "visibleIf": "{email} notempty or {phone} notempty or {telegram} notempty",
      "title": "How we may contact you?",
      "isRequired": true,
      "choices": [
        {
          "value": "email",
          "text": "By e-mail: {different}",
          "visibleIf": "{different} notempty"
        },
        {
          "value": "phonecall",
          "text": "By a phone call: {phone}",
          "visibleIf": "{phone} notempty"
        },
        {
          "value": "sms",
          "text": "By SMS: {phone}",
          "visibleIf": "{phone} notempty"
        },
        {
          "value": "telegram",
          "text": "By Telegram: {telegram}",
          "visibleIf": "{telegram} notempty"
        },
        {
          "value": "dontcontact",
          "text": "I don't want to be contacted"
        }
      ]
    }
  ],
  "showQuestionNumbers": false
 }
```
[View Demo](https://plnkr.co/edit/b5WAadPI6DJoWM15)

![image](https://github.com/surveyjs/survey-library/assets/22372972/ff3abfce-55cb-42ff-b1f9-2f4b1e18206b)

We'll update our documentation to mention this specific. Thank you for pointing it out.

**Comment by JaneSjs** [comment]
@RomanTsukanov please add a note regarding the `valueName` usage at [Question Values](https://surveyjs.io/form-library/documentation/design-survey/conditional-logic#question-values).

**Comment by RomanTsukanov** [comment]
I've added the following note to the aforementioned help topic:

> For questions with a specified [`valueName`](https://surveyjs.io/form-library/documentation/api-reference/question#valueName) property, use its value instead of the `name` value.

The new version of this document will be available with the next update of our website.
