### ISSUE TITLE
Master/detail (parent-child) form?

### ISSUE THREAD

**Issue by catamaican** [surveyjs/survey-library#7951]
Is it possible to create a master/detail (parent/child) forms? (e.g. class/students or order/items-on-order). If yes, could you, please, provide a demo?

Thank you!

**Comment by andrewtelnov** [comment]
@catamaican You can use [panel dynamic](https://surveyjs.io/form-library/examples/duplicate-group-of-fields-in-form) vs panel dynamic inside or [matrix dynamic](https://surveyjs.io/form-library/examples/add-expandable-details-section-under-matrix-rows) with detail panel and with matrix dynamic or panel dynamic inside this detail panel.

Thank you,
Andrew
