### ISSUE TITLE
Drag-and-drop doesn't work with shadow DOM

### ISSUE THREAD

**Issue by dmitry-kurmanov** [surveyjs/survey-library#7965]
My primary issue is that taliwind css mutates some base styles that conflict with SurvyeJS.

To solve this I was attempting to place SurveyJS in the Shadow DOM to separate tailwind and SurveyJS stylings. That worked with the new settings API described in the PR above. However, it seems that when drag&drop is used, it pulls the Shadow DOM root, and then get's the host property which is where it appends the dragged element. However, in that context the Survey JS CSS is not applied resulting in the element not appearing on screen.
```
|_ Host Element
   |_ Shadow DOM
   |_ Dragged Element 
```
IMO, the tree should look like this to pickup on the CSS...

```
|_ Host Element
   |_ Shadow DOM
      |_ Dragged Element <-- Indentation, styles applied.
``` 
What did I miss?

Edit: I'm working in React, incase that has implications, though I don't believe so.

_Originally posted by @cworsley4 in https://github.com/surveyjs/survey-library/issues/5703#issuecomment-1992132190_

**Comment by cworsley4** [comment]
Thank you @dmitry-kurmanov I appreciate you escalating this

**Comment by iwnow** [comment]
@dmitry-kurmanov why it was reverted?

**Comment by dmitry-kurmanov** [comment]
> @dmitry-kurmanov why it was reverted?

we faced with a problem with one integration test for vue3 and reverted it for a while. I believe that we will include the fix in the next release
