### ISSUE TITLE
Thank You message is invisible in Contrast Dark Theme

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7977]
[View Demo](https://plnkr.co/edit/uOY1A4bRAoj3BeiM)

![image](https://github.com/surveyjs/survey-library/assets/22372972/fa1bf9fe-1b65-4d94-8edf-2d9bb2f57e1f)

**Comment by OlgaLarina** [comment]
https://github.com/surveyjs/survey-library/pull/7985
