### ISSUE TITLE
How to customize multiple select UI when click to select field in mobile view 

### ISSUE THREAD

**Issue by shahbaazaliSatschel** [surveyjs/survey-library#8002]
![Screenshot_20240320_005850](https://github.com/surveyjs/survey-library/assets/130356273/2aa0edb5-cd87-41fe-a56f-646f1d3bdb16)

It's like this and it little bit confusing for the user.

Or Is there any other solution like adding custom multiple select component?
Please help 
Thanks

**Comment by JaneSjs** [comment]
Hello,
If you wish to render two items only (Yes and No), and the user may choose both, I may recommend that you consider an alternative question type. For instance, try [Checkboxes](https://surveyjs.io/form-library/examples/create-checkboxes-question-in-javascript/reactjs).

If you wish to use a multi-choice drop-down, consider using the [Multi-choice Dropdown/TagBox](https://surveyjs.io/form-library/examples/how-to-create-multiselect-tag-box/reactjs) question type.

Unfortunately, TagBox doesn't support other rendering mode. You may consider implementing a custom question type: [Integrate Third-Party React Components](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-react).

By the way, I would appreciate it if you clarify how exactly you would like the TagBox to appear on a mobile?
