### ISSUE TITLE
Bug: showPreviewBeforeComplete causes duplicate questions to appear in creator preview results screen

### ISSUE THREAD

**Issue by mgoetz-nerdery** [surveyjs/survey-library#8005]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug

### What is the current behavior?

If you are using a Specialized question type with the `showPreviewBeforeComplete: "showAllQuestions"` setting in creator mode, the preview survey will incorrectly show duplicate questions with the wrong name on the results page.  This seems to happen only when the question is named "question1" or something similar.

### What is the expected behavior?

The preview survey should only show the questions that are in the survey itself.

### How would you reproduce the current behavior (if this is a bug)?

1. Visit the test case URL: https://codesandbox.io/p/sandbox/vibrant-sun-sr6ncq
2. Switch to the Preview tab
3. Enter a value for "question1", then click preview
4. Click Complete
5. Notice that the Survey Results page shows results for "question1" and "question11", even though "question11" does not exist.
![Screenshot 2024-03-20 at 10 07 53 AM](https://github.com/surveyjs/survey-creator/assets/32200555/8572d9fc-b235-4019-b1ad-9f89dc57288c)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codesandbox.io/p/sandbox/vibrant-sun-sr6ncq

### Specify your

* browser: Chrome (122)
* editor version: 1.9.135

**Comment by mgoetz-nerdery** [comment]
Hi, I saw that this bug was referenced as fixed in the new version 1.9.136, but I don't know was actually resolved.  I've updated my test case to 1.9.136 and I am still seeing the same behavior:  https://codesandbox.io/p/sandbox/vibrant-sun-sr6ncq

**Comment by andrewtelnov** [comment]
@mgoetz-nerdery I [have forked your example](https://codesandbox.io/p/sandbox/vibrant-sun-forked-vhwmdf?file=%2Fpackage.json%3A21%2C26) and it works fine to me.

Thank you,
Andrew
