### ISSUE TITLE
Passing custom data to results?

### ISSUE THREAD

**Issue by CodeCurosity** [surveyjs/survey-library#8023]
I want to send a simple form id with the result to my backend but i couldn't find any easy way to do that?

**Comment by CodeCurosity** [comment]
Found the solution 

result.setValue("newproperty", propertyval);

**Comment by JaneSjs** [comment]
Hello,
Thank you for the update. You can programmatically set [question values](https://surveyjs.io/form-library/documentation/design-survey/conditional-logic#question-values) and variables
