### ISSUE TITLE
On the mobile end, parsing rich text titles in matrix dropdown question types failed 

### ISSUE THREAD

**Issue by momaekwudi** [surveyjs/survey-library#8038]
* browser: mobile H5
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: V1.9.136

![44251711951976_ pic](https://github.com/surveyjs/survey-library/assets/19163778/a7ccff35-f13c-4dac-a3eb-f9f1149a7fa9)
![44271711952000_ pic](https://github.com/surveyjs/survey-library/assets/19163778/e62626ef-5720-403b-90e8-8f64d2d981da)

**Comment by JaneSjs** [comment]
Hello,
We are researching this issue in another thread: https://github.com/surveyjs/survey-library/issues/8318. Please follow it for further information.

Thanks
