### ISSUE TITLE
Dropdown - A gap appears in a popup window when a drop-down question is located at the bottom of a form

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8047]
The issue is reproducible in a SurveyJS Creator's Preview.
[View Demo](https://plnkr.co/edit/LOMnAZ23IFrc9pqY)

![image](https://github.com/surveyjs/survey-library/assets/22372972/6009fc7d-103d-447f-af66-fc97d062ac63)

**Comment by OlgaLarina** [comment]
https://github.com/surveyjs/survey-creator/pull/5416
