### ISSUE TITLE
Blazor Server / Blazor WASM Integration Demo and Tutorials

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8052]
* T17558 - Assistance Needed: Integrating SurveyJS with Blazor Server .NET 8
https://surveyjs.answerdesk.io/internal/ticket/details/T17558

Please provide concise guidance, code samples, or tutorials for successfully incorporating SurveyJS components into a Blazor Server environment?

* T11237 - SurveyJS in Blazor WASM app
https://surveyjs.answerdesk.io/internal/ticket/details/T11237

**Comment by tsv2013** [comment]
I've prepated the demo project in this repo - https://github.com/surveyjs/surveyjs-blazor
