### ISSUE TITLE
When the radio is readOnly, the value selected or default doesn't appear

### ISSUE THREAD

**Issue by FilipiRafael** [surveyjs/survey-library#8055]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
When the radio is readOnly, the value selected or default doesn't appear

### What is the expected behavior?
The value should appear as the other fields, comment for example, appear the value even if it's readOnly

### How would you reproduce the current behavior (if this is a bug)?
```
{
  "elements": [
    {
      "name": "411",
      "type": "panel",
      "title": "Structural Engineering",
      "keyName": "name",
      "elements": [
        {
          "name": "documents_uploaded_2687",
          "type": "radiogroup",
          "title": "Documents Uploaded",
          "choices": [
            "No",
            "Yes"
          ],
          "colCount": 4,
          "visibleIf": true,
          "isRequired": true,
          "defaultValue": "No",
          "requiredErrorText": "Value cannot be empty"
        },
        {
          "name": "comment_3275",
          "type": "comment",
          "title": "Comment",
          "maxLength": 200,
          "visibleIf": true,
          "isRequired": false,
          "defaultValue": "",
          "requiredErrorText": "Value cannot be empty"
        }
      ],
      "description": "Structural Engineering",
      "showQuestionNumbers": "off"
    }
  ],
  "showQuestionNumbers": "off",
  "questionErrorLocation": "bottom"
}
```
The above json is what I was using to generate the follow form:
<img width="725" alt="Screenshot 2024-04-04 at 11 41 38" src="https://github.com/surveyjs/survey-library/assets/61629642/91f689a5-4929-4db1-88fa-fdceeac6e43f">
As you can see I can't see the value of the radio field, but if I remove the **readOnly** prop, it shows normally.
<img width="745" alt="Screenshot 2024-04-04 at 11 43 04" src="https://github.com/surveyjs/survey-library/assets/61629642/d947e9b9-a8c8-436e-9840-7ef17fa6a3d7">

Then I created with the survey creator the same radio readOnly form to see if there's something different, I got the form working well, but the json form is the same and it doesn't worked for me. 

Form and json returned by survey creator:
<img width="1144" alt="Screenshot 2024-04-04 at 10 35 18" src="https://github.com/surveyjs/survey-library/assets/61629642/0196c69b-ffb7-44c0-9e9a-4963629156a9">
<img width="1020" alt="Screenshot 2024-04-04 at 11 45 28" src="https://github.com/surveyjs/survey-library/assets/61629642/55efae2a-2aae-4db3-bf47-974114fa10f5">
<img width="1209" alt="Screenshot 2024-04-04 at 11 45 34" src="https://github.com/surveyjs/survey-library/assets/61629642/90918512-e0cf-4050-9761-328576f34a27">
```
{
 "logoPosition": "right",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question1",
     "title": "question",
     "defaultValue": "Item 1",
     "isRequired": true,
     "readOnly": true,
     "choices": [
      "Item 1",
      "Item 2",
      "Item 3"
     ]
    }
   ]
  }
 ]
}
```

By the way, I also tried that prop **clearValueOnDisableItems** but it also didn't work. FYI, the way we're showing the form is by saving the JSON in the database and then showing it in the front end.

Let me show an example:
<img width="906" alt="Screenshot 2024-04-04 at 10 34 36" src="https://github.com/surveyjs/survey-library/assets/61629642/848c5913-07de-452c-8732-5b11b3b77870">

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version: 123.0.6312.106 (Official Build) (arm64)
* surveyjs platform (angular or react or jquery or knockout or vue): JQuery
* surveyjs version: <link href="https://unpkg.com/survey-jquery/defaultV2.min.css" type="text/css" rel="stylesheet">

**Comment by JaneSjs** [comment]
Hello @FilipiRafael,
Thank you for the comprehensive explanation and sharing the relevant code and screenshots. I created the following demo to confirm that Radiogroup correctly displays a default value: [View Plunker](https://plnkr.co/edit/2LpAua0Srj9clmsu).
If you programmatically assign a new response object to the [`survey.data`](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#data) property, note that the new response will override default question values.
If you need to programmatically assign user responses and keep default question values, use the [`survey.mergeData(newResponseObj)`](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#mergeData) function.

Please let me know if this helps. Additionally, please ensure that your SurveyJS Form Library is up-to-date.

I look forward to your reply.

**Comment by FilipiRafael** [comment]
Hello @JaneSjs 
Thanks for your quick reply.
The data we are using in the survey.data  in this case, is coming from our database. As I showed above, when the form is not readonly the answer is displayed. When we set the form to read-only the answers for radio control are cleared. We need to have the answer showing like text box, for example.

**Comment by FilipiRafael** [comment]
Hey @JaneSjs, another question is about design. When those fields are readOnly, can we remove that opacity? I didn't find any prop to do that, thanks. I just want normal design fields, but readOnly, not editable, you know?

<img width="693" alt="Screenshot 2024-04-04 at 20 04 23" src="https://github.com/surveyjs/survey-library/assets/61629642/b7b89a7e-fd91-45e2-8c79-8646f7b21ffa">

**Comment by FilipiRafael** [comment]
Still about the first question, the same problem as occurs with radio fields, occurs with select and checkbox, but as you can see in the following screenshot, it's not happening with normal text fields.

<img width="794" alt="Screenshot 2024-04-04 at 20 09 25" src="https://github.com/surveyjs/survey-library/assets/61629642/6757db33-2422-48f0-b1a1-94ecd079e2fe">

**Comment by FilipiRafael** [comment]
Hey @JaneSjs, sorry to ask, but did you find out something? Thanks :)

**Comment by JaneSjs** [comment]
Hello @FilipiRafael,
Please accept my apologies for the delayed reply. 

Regarding the first question: unfortunately, I couldn't reproduce it on my end. I created the following demo for your reference: [View Plunker](https://plnkr.co/edit/KzvTyTThUP02b22p).

I would recommend that you ensure that you're using the latest version of SurveyJS libraries. If you require further assistance, please share a problematic demo for research.

Regarding the read-only item appearance: we are currently working on this task.
https://github.com/surveyjs/survey-library/issues/6776

In the meantime, you can disable the opacity using CSS. Check the following demo: [View Demo](https://plnkr.co/edit/GLX3ibtiDfYVxoCA).

I look forward to your reply.

**Comment by FilipiRafael** [comment]
Hey @JaneSjs, thank you very much for the answer and all the resources and issues that you sent to me :), but I solved it all only using CSS now, I realize that when the checkbox and radio fields, for example, are read-only, they don't show the checked value, because of the CSS class used ` .sd-item--disabled.sd-item--checked .sd-item__decorator {`. If you wanna know more please let me know, but you can now close this issue, thanks 🥇

**Comment by FilipiRafael** [comment]
Hey @JaneSjs, thank you very much for the answer and all the resources and issues that you sent to me :), but I solved it all only using CSS now, I realize that when the checkbox and radio fields, for example, are read-only, they don't show the checked value, because of the CSS class used ` .sd-item--disabled.sd-item--checked .sd-item__decorator {`. If you wanna know more please let me know, but you can now close this issue, thanks 🥇
