### ISSUE TITLE
[feature request] Resize/convert image before upload

### ISSUE THREAD

**Issue by mschfh** [surveyjs/survey-library#8069]
### Are you requesting a feature, reporting a bug or asking a question?
Feature Request

### What is the current behavior?
not implemented

### What is the expected behavior?
The File Upload question should support client-side resizing/converting of images (e.g. using HTML5 Canvas) before uploading it.

**Comment by JaneSjs** [comment]
Hello @mschfh,
Thank you for sharing your ideas. 

Unfortunately, File Upload doesn't provide any UI option for modifying images before upolading. Once a user selects an image using the file chooser, the image is immediately uploaded to a specified storage without any editing capability.

If you need to resize or rotate images, you would need to perform these actions before initiating the file chooser dialog or before uploading them to a survey.

Feel free to reach out if you have any further questions.

Thanks
