### ISSUE TITLE
how to do calculations by using input fields

### ISSUE THREAD

**Issue by gowrisankarvoltuswave** [surveyjs/survey-library#8109]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@gowrisankarvoltuswave You can use [setValueExpression property](https://surveyjs.io/form-library/documentation/api-reference/text-entry-question-model#setValueExpression).

Thank you,
Andrew
