### ISSUE TITLE
Change position of file delete button in the file question

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#8121]
The request comes from [SurveyJS technical forum](https://surveyjs.answerdesk.io/ticket/details/t17716/adjusting-the-position-of-the-delete-icon-for-non-image-file-uploads).

> I am reaching out to inquire about the possibility of adjusting the position of the "delete" icon in SurveyJS for non-image file uploads, such as PDFs.

> Currently, the "delete" icon is centrally located on the file icon, which has been causing some confusion. Users frequently attempt to click on the file icon to open the file but end up hitting the "delete" button instead. Is there a way to either move the "delete" icon to a different position or remove it altogether for these types of uploads?

**Comment by mikeamelin** [comment]
https://www.figma.com/design/jcuAUsN02n2yJerx39mqf9/LBR--%3E-Library-Preview?node-id=2418-20451
