### ISSUE TITLE
Broken alignment on the Preview.

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#8124]
![Image](https://github.com/surveyjs/survey-library/assets/17025812/3cd53a67-b26e-48cf-8de3-0d1a47c6c0c5)

[survey.json](https://github.com/surveyjs/survey-library/files/14998489/survey.json)

**Comment by novikov82** [comment]
panelless
![image](https://github.com/surveyjs/survey-library/assets/29385489/43c9e337-2805-46d3-a4a9-dfa0d0883dcd)
