### ISSUE TITLE
Wrap questions titles and show title actions in full instead of "..."

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#8144]
Here is the related issue on [SurveyJS technical forum](https://surveyjs.answerdesk.io/ticket/details/t17745/title-action-is-getting-converted-to-the-meatballs-menu).
User wants to show actions fully and wrap the question titles in several lines.

**Comment by OlgaLarina** [comment]
Example - https://plnkr.co/edit/pPCXmoCSTyI8rlQI

CSS
.fix-toolbar-width {
&emsp; flex: 0 0 auto;
}

JS
survey.getAllQuestions(false).forEach(q => {
&emsp;let questionToolbar = q.getTitleToolbar();
&emsp;if(q.name === "os") {
&emsp;&emsp;questionToolbar.isResponsivenessDisabled = true ;
&emsp;&emsp;questionToolbar.cssClasses.root += " fix-toolbar-width"
&emsp;}
});
