### ISSUE TITLE
Surveys are not rendered properly starting from version 1.9.137 of survey-vue3-ui

### ISSUE THREAD

**Issue by pomma89** [surveyjs/survey-library#8171]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug.

### What is the current behavior?

Starting from version `1.9.137` of `survey-vue3-ui`, surveys are rendered with an empty content:

![image](https://github.com/surveyjs/survey-library/assets/4697032/82f7c109-6a5f-45e5-89b3-ba2c5c7de401)

### What is the expected behavior?

Before version `1.9.137` of `survey-vue3-ui`, surveys are rendered properly:

![image](https://github.com/surveyjs/survey-library/assets/4697032/d13806f9-bb88-4d4d-86e9-a6b084556930)

### How would you reproduce the current behavior (if this is a bug)?

I forked Survey.js `code-examples` repo and set the version of that package in this example, so that it shows an empty survey:

https://github.com/pomma89/survey-code-examples/tree/empty-vue3-survey-repro/get-started-library/vue3

#### Provide the test code and the tested page URL (if applicable)

Please see above.

### Specify your

* browser: Firefox 125.0.1, Chrome 124.0.6367.61
* browser version: please see above
* surveyjs platform (angular or react or jquery or knockout or vue): Vue (3)
* surveyjs version: 1.9.137 or later

Please let me know if you need further information.

Thank you very much,
Goodbye,
Alessio

**Comment by dk981234** [comment]
Hello,

We've tested your example and it seems to work fine.

![image](https://github.com/surveyjs/survey-library/assets/21283706/e748ed1b-f248-40e9-ab10-24c512ace4d8)

Please, check that 'survey-core' and 'survey-vue3-ui' have the same version.

Thanks,
Dmitry
SurveyJS Team

**Comment by pomma89** [comment]
Thank you, @dk981234: setting both packages to the same version made it work.

Thanks again for your quick reply,
Goodbye,
Alessio
