### ISSUE TITLE
Accessibility: header structure

### ISSUE THREAD

**Issue by pierretl** [surveyjs/survey-library#8183]
It is important to be consistent when using headings and subheadings.
A SurveyJs form can be included in pages with different structures from one site to another or even on the same site, it would be better not to use a semantic tag.
Another possibility is to allow their customization by modifying the tag or using the pair of attributes ```role="heading" aria-level="[level]"```
![firefox_SHyCYD7py0](https://github.com/surveyjs/survey-library/assets/13539389/5020b638-c888-442f-ae1b-dbe446024e17)

**Comment by tsv2013** [comment]
SurveyJS allows to customize heading tags used in survey structure. Here is the live example on our site - https://surveyjs.io/form-library/examples/change-heading-levels/jquery
Does it fit your case?
