### ISSUE TITLE
File Upload bug

### ISSUE THREAD

**Issue by CodeCurosity** [surveyjs/survey-library#8184]
I am using this example code for File Upload for jQuery

https://surveyjs.io/form-library/examples/file-upload/jquery#content-code

i tried everything, data is returned properly, response is valid, file name and url is returning just fine but the file upload spinner keeps spinning and when i try submitting form it says "Your file is uploading. Please wait several seconds and try again.
", file is uploaded to the proper folder and is returning url and file name but it doesn't show any preview and doesn't let me submit, what am i missing?

**Comment by andrewtelnov** [comment]
@CodeCurosity Do you call `options.callback` function in survey.onUploadFiles event?
This call should hide the spinning and show the file(s) preview.

Thank you,
Andrew

**Comment by CodeCurosity** [comment]
Yes i did and somehow that callback function doesn't seem to work, here is my code

```
const uploadFileUrl = oformsData.ajaxurl + '?action=upload_file';

survey.onComplete.add(function(result) {
    var dataToSend = JSON.stringify(result.data);
    
    jQuery.ajax({
        type: "POST",
        url: oformsData.ajaxurl, // WordPress AJAX URL
        data: {
            action: 'of_send_mail',
            surveyData: dataToSend
        },
        success: function(response) {
            console.log(result.data);
            // Handle the response (e.g., show a success message to the user)
            // alert(response);
            // document.location = "https://surveyjs.io";
        },
        error: function(error) {
            // Handle errors if any
            alert('Form Error');
        }
    });
});
survey.onUploadFiles.add((_, options) => {
    
    const formData = new FormData();

    options.files.forEach((file) => {
        formData.append(file.name, file);
    });

    fetch(uploadFileUrl, {
        method: "POST",
        body: formData
    })
    .then((response) => response.json())
                        .then((data) => {
                            options.callback(
                                options.files.map((file) => {
                                    return {
                                        file: file,
                                        content: data[file.name]
                                    };
                                })
                            );
                        })
    .catch((error) => {
        console.error('Error during file upload:', error);
        options.callback([], ['An error occurred during file upload.']);
    });
});

```

**Comment by CodeCurosity** [comment]
I have a deadline @andrewtelnov , can you help?

**Comment by andrewtelnov** [comment]
@CodeCurosity It is hard to help without debugging. Please check the console for errors. Probably there is an error in your console.

Thank you,
Andrew

**Comment by CodeCurosity** [comment]
That is the issue, i have tried everything there are no errors, formdata and response is valid yet it does that, anyways neve rmind.
