### ISSUE TITLE
Allow to revert the rating scale order

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#8192]
It will be nice to allow to revert the rating scale order.
The request was reported in [SurveyJS technical forum](https://surveyjs.answerdesk.io/internal/ticket/details/T17913).

**Comment by tsv2013** [comment]
This can be achieved via the following custom CSS rule:

CSS
.sd-rating fieldset {
  flex-direction: row-reverse;
}
Here is the working plunker example - https://plnkr.co/edit/HRMZ8vMdw5oEewIP
