### ISSUE TITLE
JQuery library does not scale correctly for mobile

### ISSUE THREAD

**Issue by SmallPepperZ** [surveyjs/survey-library#8198]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

The mobile view shows a zoomed-out version of the survey

<img src="https://github.com/surveyjs/survey-library/assets/69822582/9943e9f5-84b7-44e9-8e92-fdf848b5935e" height=500>

### What is the expected behavior?

The text and ui scales to allow the user to see the survey

<img src="https://github.com/surveyjs/survey-library/assets/69822582/f6e506c6-a1f1-41b5-b292-1c6ababc5826" height=500>

### How would you reproduce the current behavior (if this is a bug)?

1. Visit any surveyjs page using jquery or knockout on a mobile device, or use your browser's developer tools to simulate a small screen
2. Observe how the UI does not adjust itself for a mobile device screen size.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://github.com/surveyjs/code-examples/tree/main/get-started-library/jquery

### Specify your

* browser: Safari
* browser version: 17.4
* surveyjs platform (angular or react or jquery or knockout or vue): jquery, knockout
* surveyjs version: 1.10.1 (latest)

**Comment by andrewtelnov** [comment]
@SmallPepperZ Please set `<meta name="viewport" content="width=device-width, initial-scale=1">` in your html hearder.
Here is [the example](https://plnkr.co/edit/wkpMiXKhi0PdE6sv?preview).

Thank you,
Andrew

**Comment by SmallPepperZ** [comment]
Thanks!
