### ISSUE TITLE
Enhancement: Add Notes panel (contains one RTE) in the survey 

### ISSUE THREAD

**Issue by CJSoftLabs** [surveyjs/survey-library#8201]
### Are you requesting a feature, reporting a bug or asking a question?
Request for new Feature

### What is the current behavior?
There is no notes section avaliable in the survey.

### What is the expected behavior?
1) The survey should have a panel similar to property panel in the right side (for LTR languages and in left for RTL language).
2) The panel should contain a RTE control to capture thenotes data.
3) The visibility of the panel is defined by a property named showNotes.
4) The data captured in the Notes RTE needs to be avaliable in the surveyNotes property of the survey data.

### Specify your

* browser: Google Chrome/Microsoft Edge
* browser version: 124
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.9.139

**Comment by andrewtelnov** [comment]
@CJSoftLabs I guess you are looking for [this example](https://surveyjs.io/form-library/examples/survey-review-mode). You can add a custom boolean property to a question type and based on it generate or do not generate the comment.
You can add any other logic you need. We do not do it out of the box, because there are different similar scenarios with different logic that you can easily implement and out of the box solution would limit developers.

Thank you,
Andrew

**Comment by CJSoftLabs** [comment]
Hi @andrewtelnov,
Thanks for the link. I've already had a look at this and Unfortunately, it does not fit my usecase (car sales agent will have an unstructured meeting with the potential customer and fill up the survey. Anything which is not available in the survey will be captured as Notes at survey level) for the following reasons.
1) The notes data is required at survey level as a summary - question level notes is an overkill.
2) As a work around if the comments section for a question is used, comments are not available for text based fields.

**Comment by andrewtelnov** [comment]
@andrewtelnov It is your code and it is your rules. This code will enable the comment area to the comment question.
`Survey.Serializer.getProperty("comment", "showCommentArea").visible = true;`.
And you can setup the adding comment question in the Review example in the way you need it. Again it is your code, it is your rules.

Thank you,
Andrew
