### ISSUE TITLE
Preview layout broken in v1.9.139 / v1.10.1

### ISSUE THREAD

**Issue by mschfh** [surveyjs/survey-library#8202]
### Are you requesting a feature, reporting a bug or asking a question?
Bug / Regression

### What is the current behavior?
Starting with v1.9.139 (including v1.10.1), the Preview layout changed.
![Write a short text that describes your company in 2-3 Paragraphs](https://github.com/surveyjs/survey-library/assets/37435502/cec84889-9e19-47cf-aca3-511a1b7b6a6a)

### What is the expected behavior?
The same design <= v1.9.138
![Pasted Graphic 2](https://github.com/surveyjs/survey-library/assets/37435502/47c2824b-cbfa-4b94-9eea-497a83eb3f65)

### How would you reproduce the current behavior (if this is a bug)?
https://surveyjs.io/published?id=84641fdb-d745-48c3-95ec-14bedcfb2986
```

### Specify your

* browser: Chrome
* browser version: 124
* surveyjs platform (angular or react or jquery or knockout or vue): jquery / knockout / React
* surveyjs version: v1.9.139 / v1.10.1

**Comment by andrewtelnov** [comment]
@mschfh We made this change on purpose. Here is the link in [our release notes](https://surveyjs.io/stay-updated/release-notes/v1.9.139#new-design-for-read-only-and-preview-modes).
We got a lot of complains about the previous styles from our customers and we carefully review our read-only and preview styles and make the more readable.

Thank you,
Andrew
