### ISSUE TITLE
Result shows wrong order of questions

### ISSUE THREAD

**Issue by CodeCurosity** [surveyjs/survey-library#8236]
This is the order of my form

Full Name
E-mail
Dropdown
Range Slider
Range Slider
Expression

but when i log the result.data it shows in wrong order, this is the output i get
Range Slider
Range Slider
Expression
Full Name
E-mail
Dropdown

How do i fix this so they output in the same order as they are submitted?

**Comment by andrewtelnov** [comment]
@CodeCurosity survey.data is a hash table where the key is a question name (valueName) and the value is the question value. On entering a value we modify this hash table and as result keys in the order how end-user enters the data in your survey.
If you want to get the data by the questions order then just use the following code:
```js
const data = {};
survey.getAllQuestions(true).forEach(q => {
  if(!q.isEmpty()) data[q.getValueName()] = q.value;
});
```

Thank yuo,
Andrew

**Comment by CodeCurosity** [comment]
Doesn't seem to work, still the same order, range slider value is entered 3rd last but both range slider values are always first, with your code, no changes.

**Comment by andrewtelnov** [comment]
@CodeCurosity do you use `data` variable instead of `survey.data` property?

Thank you,
Andrew

**Comment by CodeCurosity** [comment]
I don't quite understand, i am using your example code

```
survey.onComplete.add(function(result) {
        const data = {};
        survey.getAllQuestions(true).forEach(q => {
          if(!q.isEmpty()) data[q.getValueName()] = q.value;
        });
    
    var dataToSend = JSON.stringify(result.data);
```

**Comment by andrewtelnov** [comment]
It should be `var dataToSend = JSON.stringify(data);`. 

Thank you,
Andrew

**Comment by CodeCurosity** [comment]
So what happens to result we are calling here ?     survey.onComplete.add(function(result) { and i want to set variables so i set it to data?

**Comment by CodeCurosity** [comment]
thank you.
