### ISSUE TITLE
Ranking - Support the `itemComponent` setting and allow developers to create a custom item template

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8284]
T17758 - Ranking Images
https://surveyjs.answerdesk.io/internal/ticket/details/T17758
***
Support the `itemComponent` setting for a Ranking question to allow developers to implement a [custom item component](https://surveyjs.io/form-library/examples/dropdown-box-with-custom-items/reactjs). For instance, to display images and allow respondents rank them.

**Comment by dmitry-kurmanov** [comment]
https://github.com/surveyjs/survey-library/commit/368100d537cb6ce0f265415e7b08e8b3fb4f9096
