### ISSUE TITLE
[Enhancement] Geospatial Survey Questions

### ISSUE THREAD

**Issue by sancarn** [surveyjs/survey-library#8296]
### Are you requesting a feature, reporting a bug or ask a question?

Requesting a feature - Geospatial questions:

![image](https://github.com/surveyjs/survey-creator/assets/7938900/a89e0b37-eddc-4add-b88f-feef214d5db6)

### Description

* Place a point on a map - Outputs geojson point
* Draw features on a map - Outputs geojson feature collection
* Select an existing feature from a map - Outputs selected polygon (including metadata)

### Output of control: 

* [GeoJSON](https://geojson.org/)

### Resources: 

* https://geojson.io/#map=2/0/20 - geojson editor
* https://leafletjs.com/ - open source map control for the web

**Comment by JaneSjs** [comment]
Hello @sancarn,
Thank you for your ideas. Unfortunately, we do not have immediate plans to implement such a widget.

You can integrate a required web control within a SurveyJS Form Library and Creator by extending a built-in question model. Consider the following demo (for React)[View CodeSandbox](https://codesandbox.io/p/sandbox/clever-wave-mfd66p?file=%2Fsrc%2Fjson.js%3A5%2C29&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu9hzhqz0007356i039avf9f%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu9hzhqz0003356if92wohoi%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu9hzhqz0004356i6rna4qn4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu9hzhqz0006356imb2wh36v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu9hzhqz0003356if92wohoi%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu9hzhqz0002356ijps2ym02%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A29%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A29%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fjson.js%2522%257D%255D%252C%2522id%2522%253A%2522clu9hzhqz0003356if92wohoi%2522%252C%2522activeTabId%2522%253A%2522clu9hzhqz0002356ijps2ym02%2522%257D%252C%2522clu9hzhqz0006356imb2wh36v%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu9hzhqz0005356iprk26i23%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu9hzhqz0006356imb2wh36v%2522%252C%2522activeTabId%2522%253A%2522clu9hzhqz0005356iprk26i23%2522%257D%252C%2522clu9hzhqz0004356i6rna4qn4%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu9hzhqz0004356i6rna4qn4%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D). 

Please follow the tutorial which corresponds to your JavaScript platform:
* [Integrate Third-Party Angular Components](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-angular)
* [Integrate Third-Party React Components](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-react)
* [Integrate Third-Party Vue 3 Components](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-vue)

Should you have any further questions, please let us know.

**Comment by JaneSjs** [comment]
+https://surveyjs.answerdesk.io/internal/ticket/details/T17450
