### ISSUE TITLE
Can you add survey.questionDescriptionLocation

### ISSUE THREAD

**Issue by irynmare** [surveyjs/survey-library#830]
### Are you requesting a feature, reporting a bug or ask a question?

requesting a feature

### What is the current behavior?

Description of the questions is shown under question title

### What is the expected behavior?

Can you add survey.questionDescriptionLocation to be able to show description in bottom of the question as it was done for errors with survey.questionErrorLocation?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@irynmare There is already titleLocation property. Description is rendered under the title.
It has "top", "bottom" and "left" options.
Does it work for you?

Thank you,
Andrew

**Comment by irynmare** [comment]
Not really. I need title to be in top and description under input. Added picture of how it should look.
![f9d57fa](https://user-images.githubusercontent.com/34510857/33944345-8d0d9cf8-e024-11e7-933d-458cb7e97d47.PNG)

**Comment by andrewtelnov** [comment]
@irynmare It looks good and yes, we do not have an option for this right now.
I'm adding this into our TODO list...

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@irynmare Sorry, We have missed this request, but we have finally implemented it. Here is the related [issue]( https://github.com/surveyjs/survey-library/issues/1328).
`survey.questionDescriptionLocation = "underInput";`
This code will work from next minor version that we will release on the next week.

Thank you,
Andrew
