### ISSUE TITLE
Use en-gb instead of en-UK for English UK

### ISSUE THREAD

**Issue by Niveshkrishna** [surveyjs/survey-library#8311]
### Are you requesting a feature, reporting a bug or asking a question?
bug

### What is the current behavior?
en-uk is the wrong locale code for the English UK

### What is the expected behavior?
It should use en-gb as per iso https://www.andiamo.co.uk/resources/iso-language-codes/

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@Niveshkrishna I could not find any code related to "en-uk" in our code except our unit tests. I have corrected the tests.
Probably I missed something. Could you point me where did you find the issue?

Thank you,
Andrew
