### ISSUE TITLE
Dynamic Panel with Tabbed UI: An untitled panel displays a weird element within an empty panel title area

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8327]
When Dynamic Panel enables the tabbed UI and a newly created panel doesn't yet contain a title, the following UI element appears:
[View Demo](https://plnkr.co/edit/iHopN4Mi8ZdxiKia)

https://github.com/surveyjs/survey-library/assets/22372972/0db55088-6efa-4075-856d-0e1788937fc0

**Comment by RomanTsukanov** [comment]
We could add a `tabTitlePlaceholder` property, which would apply when `templateTabTitle` evaluates to undefined/null.

**Comment by RomanTsukanov** [comment]
@andrewtelnov 
We need to change the default value to "New Panel"
