### ISSUE TITLE
Add a note: checkErrorsMode: "onValueChanged" doesn't work for date input fields

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8329]
* T12662 - Date validation issue
https://surveyjs.answerdesk.io/internal/ticket/details/T12662#6d3c1d4f-578e-41d2-8106-44362c42d43a
* T18376 - Date type inputs validation
https://surveyjs.answerdesk.io/internal/ticket/details/T18376

**Comment by RomanTsukanov** [comment]
We can validate data input fields when they lose focus, but this seems a constly solution. I've added a note about the current behavior to the docs: [API Reference](https://github.com/surveyjs/survey-library/pull/8455) | [Data Validation help topic](https://github.com/surveyjs/service/pull/2297).

**Comment by JaneSjs** [comment]
We handled this issue. Now, date fields are validated on value change: [Date Input Fields: Support for Immediate Validation](https://surveyjs.io/stay-updated/release-notes/v1.12.6#date-input-fields-support-for-immediate-validation).
