### ISSUE TITLE
Yes/No Component show yes/yes when swap option is on.

### ISSUE THREAD

**Issue by missakation** [surveyjs/survey-library#8346]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
When I have a boolean component and the option "Swap the order of yes and no" is set to yes, it shows yes/yes when I select yes.

### What is the expected behavior?
It should show yes/no

![Screenshot 2024-05-31 at 8 15 03 PM](https://github.com/surveyjs/survey-library/assets/10357213/87910c8e-a261-4586-acff-674410357f00)

**Comment by andrewtelnov** [comment]
@missakation Please provide your boolean question json.

Thank you,
Andrew

**Comment by missakation** [comment]
> @missakation Please provide your boolean question json.
> 
> Thank you, Andrew

`
                {
                  type: "boolean",
                  name: "is_enabled",
                  minWidth: "100px",
                  startWithNewLine: false,
                  title: "Is Enabled",
                  hideNumber: true,
                  defaultValue: "true",
                },
`

**Comment by andrewtelnov** [comment]
@missakation [It works fine](https://plnkr.co/edit/eyKC0sLpeovWtLPC) to me.

Thank you,
Andrew

**Comment by missakation** [comment]
> @missakation [It works fine](https://plnkr.co/edit/eyKC0sLpeovWtLPC) to me.
> 
> Thank you, Andrew

Oh sorry try this:

      {
       "type": "boolean",
       "name": "is_enabled",
       "minWidth": "100px",
       "startWithNewLine": false,
       "title": "Is Enabled",
       "hideNumber": true,
       "defaultValue": "true",
       "swapOrder": true
      },
      
      The swap option should be on

**Comment by andrewtelnov** [comment]
@missakation Yes, there is the issue [here](https://plnkr.co/edit/MCxJk4KkHc8C8AJi).

Thank you,
Andrew
