### ISSUE TITLE
'Freeze the progress bar' option or make it a default behavior.

### ISSUE THREAD

**Issue by ElenaGorbatkova** [surveyjs/survey-library#8356]
### Are you requesting a feature, reporting a bug or asking a question?

Requesting a feature

### What is the current behavior?

Progress bar is static

### What is the expected behavior?

I would like the progress bar to freeze when a user scrolls down a page with questions, so it's always visible

### How would you reproduce the current behavior (if this is a bug)?

it's a default behavior at the moment

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: 

https://github.com/surveyjs/survey-library/assets/102306951/e0c23a80-0adc-401c-9d1b-283531af60b1

![image](https://github.com/surveyjs/survey-library/assets/102306951/26e678e2-c6a2-42db-b5dc-b9cc6bb7bd77)

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by mikeamelin** [comment]
Here are some prototypes and throughs (read comments) — https://www.figma.com/design/jcuAUsN02n2yJerx39mqf9/LBR--%3E-Library-Preview?node-id=2443-31648

**Comment by mikeamelin** [comment]
- [ ] here reduced paddings are used in the original prototype 
![Screenshot 2024-06-19 at 11 32 04](https://github.com/surveyjs/survey-library/assets/17025812/00ae53c6-05d9-4c16-8968-fc6817786739)

- [ ] no shadow is needed for this view
![Screenshot 2024-06-19 at 11 33 57](https://github.com/surveyjs/survey-library/assets/17025812/b33a00a6-5dc6-4433-8a2b-62bc9660d037)

- [ ] here I changed a bit margins to align static and floating labels each other
![Screenshot 2024-06-19 at 11 36 28](https://github.com/surveyjs/survey-library/assets/17025812/724fafc4-b9c1-4138-9b25-73d7aba58640)
![Screenshot 2024-06-19 at 11 36 59](https://github.com/surveyjs/survey-library/assets/17025812/5c9a6d2e-efd9-4711-b308-1395d6f05790)

- [ ] wrong text color for the floating label
![Screenshot 2024-06-19 at 11 37 29](https://github.com/surveyjs/survey-library/assets/17025812/77e5735b-f86b-4bc2-9782-31aaf111dda4)
