### ISSUE TITLE
Numeric Input Mask - When using a comma as a decimal separator, the focus accidentally jumps before the decimal symbol

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8362]
Expected behavior when using a default decimal separator.

https://github.com/surveyjs/survey-library/assets/22372972/12fbaa16-34ac-42d1-a356-4ceab0f51743

The problematic behavior when using the `,` decimal separator.

https://github.com/surveyjs/survey-library/assets/22372972/10e581a2-10b8-438a-a0cb-dda9add5af02

[View Demo](https://plnkr.co/edit/YgFkoUApKIxryclB)

**Comment by OlgaLarina** [comment]
The default thousands separator value is ",".
If you set decimalSeparator to “,”, you need to change the “thousandsSeparator” too.

`  
     "maskSettings": {
      "decimalSeparator": ",",
      "thousandsSeparator": ".",
      "precision": 1,
      "max": 100
     }`

**Comment by JaneSjs** [comment]
@OlgaLarina, thank you. I wish to reset the thouthand separator. I updated mask settings as follows.
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "qX",
     "title": "X",
     "maskType": "numeric",
     "maskSettings": {
      "decimalSeparator": ",",
      "thousandsSeparator": " ",
      "precision": 1,
      "max": 100
     }
    }
   ]
  }
 ]
}
```
https://plnkr.co/edit/C8KahIe49Ydc3h3B

**Comment by rajeshn95** [comment]
Wow, finally found it, Thanks
I was trying to set the masksetting for the BRL currency, and haven't found what all values maskSetting takes, I tried finding it in the document but couldn't found it. I think its better to put somewhere in the documentation.
BTW thanks🙏
