### ISSUE TITLE
Nuxt Build Error

### ISSUE THREAD

**Issue by charlimxm** [surveyjs/survey-library#8376]
Hello! Am trying to use survey-vue3-ui library with Nuxt 3 app. Works in dev but error occurs when I try to build app for production

/plugins/survey.js
```
import { defineNuxtPlugin } from '#app'
import { surveyPlugin } from 'survey-vue3-ui';

export default defineNuxtPlugin(nuxtApp => {
  nuxtApp.vueApp.use(surveyPlugin)
})
```
App works on nuxt dev.

Error occurs when I run nuxt build.
![Screenshot 2024-06-06 at 6 14 18 PM](https://github.com/surveyjs/survey-library/assets/31029245/aa7b59d1-16f4-4739-8217-6529117db141)

How should I use the survey library with nuxt 3? 

### Specify your
* browser: any
* browser version: latest
* surveyjs platform: vue 3 on nuxt3
* surveyjs version: ^1.9.129

**Comment by JaneSjs** [comment]
Hello @charlimxm,
Thank you for sharing this code. Please ensure that your Nuxt configuration includes the plugin and CSS

**nuxt.config.ts**
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  css: ['survey-core/defaultV2.min.css'],
  plugins: ['~/plugins/survey-plugin.ts'],
});
```
I created the following demo for your reference: 
* [View Stackblitz](https://stackblitz.com/edit/github-m32zze?file=nuxt.config.ts).
* Download zip archive at [github-m32zze.zip](https://github.com/user-attachments/files/15743142/github-m32zze.zip).

I confirm that the SurveyJS form appears correctly. 
![image](https://github.com/surveyjs/survey-library/assets/22372972/9ffcd2b4-e469-46bf-bf6c-f2c2952aa279)

Also, ran this demo locally and confirmed that the `nuxt dev` and `nuxt build` commands completes successfully.
Here is the `nuxt build` commant output.
![image](https://github.com/surveyjs/survey-library/assets/22372972/db9ff4b8-3265-44e3-8057-36ef1f7deaea)

Please let me know if this information helps.
