### ISSUE TITLE
Matrix question configured with visible if condition and 'Hide the question if it has no rows"= True

### ISSUE THREAD

**Issue by phuongvannguyen** [surveyjs/survey-library#8393]
### Are you requesting a feature, reporting a bug or asking a question?
I'm requesting a feature

### What is the current behavior?

When I set a matrix Q3 with 'Hide the question if it has no rows"= True, row visible if Q2 = 'abc' and Q3 is visible if Q1 = yes then when I choose Q1 = No and input 'abc' for Q2--> Q3 is shown despite of the condition Q3 is visible if Q1 = yes.

### What is the expected behavior?

The expectation in this case is Q3 is not shown. Q3 is shown only if when Q1 = Yes and it has rows

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by JaneSjs** [comment]
Hello,
I followed your explanation and created the following form:
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "boolean",
     "name": "Q1"
    },
    {
     "type": "dropdown",
     "name": "Q2",
     "choices": [
      {
       "value": "abc",
       "text": "ABC"
      },
      "Item 2",
      "Item 3"
     ]
    },
    {
     "type": "matrixdropdown",
     "name": "Q3",
     "visibleIf": "{Q1} = true",
     "columns": [
      {
       "name": "Column 1"
      },
      {
       "name": "Column 2"
      },
      {
       "name": "Column 3"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      "Row 1",
      "Row 2"
     ],
     "hideIfRowsEmpty": true
    }
   ]
  }
 ]
}
```
![image](https://github.com/surveyjs/survey-library/assets/22372972/08395035-1eb5-42c7-b8f3-8505ca4bb5be)
The logic works correctly and a matrix appears only when setting Q1 to Yes. I tested this survey in our [online demo](https://surveyjs.io/create-free-survey).

Please clarify how to reproduce the issue.

Thanks

**Comment by phuongvannguyen** [comment]
Hi, 

Below is my test on online demo
{
 "logoPosition": "right",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "boolean",
     "name": "question1",
     "title": "Q1"
    },
    {
     "type": "text",
     "name": "question2",
     "title": "Q2"
    },
    {
     "type": "matrix",
     "name": "question3",
     "visibleIf": "{question1} = true",
     "title": "Q3",
     "columns": [
      "Column 1",
      "Column 2",
      "Column 3"
     ],
     "rows": [
      {
       "value": "Row 1",
       "visibleIf": "{question2} = 'abc'"
      },
      "Row 2"
     ],
     "hideIfRowsEmpty": true
    }
   ]
  }
 ]
}
![image](https://github.com/surveyjs/survey-library/assets/44052163/555a6f0e-4f7a-4d46-8cd9-6e9b80ade8aa)
