### ISSUE TITLE
Ranking Custom Item Component for Angular

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8405]
[View Demo](https://codesandbox.io/p/sandbox/surveyjs-angular-jkgt32)

![image](https://github.com/surveyjs/survey-library/assets/22372972/1d8deb9f-3bf8-4925-a7ef-ac7ab83f3a67)

**Comment by dmitry-kurmanov** [comment]
https://codesandbox.io/p/sandbox/ng-ranking-custom-item-component-35zwrl?file=%2Fsrc%2Fapp%2Fcomponents%2Fsurvey.component.ts%3A46%2C1

**Comment by JaneSjs** [comment]
Ranking Question with Items which use Images (the `img` tag): https://codesandbox.io/p/sandbox/rank-ng-custom-forked-7wyy6r?file=%2Fsrc%2Fapp%2Fcomponents%2Fsurvey.component.css%3A10%2C1.
