### ISSUE TITLE
showProgresssBar: "aboveHeader" is broken

### ISSUE THREAD

**Issue by DominiqueMakowski** [surveyjs/survey-library#8418]
As can be seen in the [demo](https://surveyjs.io/form-library/examples/configure-form-navigation-with-progress-indicators/reactjs), changing the `showProgresssBar` argument from "belowHeader" or "aboveHeader" does not make a difference (it stays below the header).

![image](https://github.com/surveyjs/survey-library/assets/8875533/fa4f44b9-b91b-4187-bed5-25aa4d4be186)

(linking https://github.com/jspsych/jsPsych/issues/3320)

**Comment by JaneSjs** [comment]
Hello @DominiqueMakowski,
Thank you for reporting this issue. I forwraded it to our developers for further investigation. We'll update you shortly.

**Comment by JaneSjs** [comment]
Hello @DominiqueMakowski,
I discussed this issue with our developers. It appears that the Above Header progress bar display mode is available with the Advanced Header mode. The advance header allow you to control the overall appearance of a survey header including a background color, header size and text alignment. 
Please refer to the following demo: [View Plunker](https://plnkr.co/edit/4wndhZTkX8K0ugfz).
![image](https://github.com/surveyjs/survey-library/assets/22372972/c1af4cea-1bc9-4055-9070-e5997221027d)

We'll update our demo accordingly.

Thank you
