### ISSUE TITLE
Custom widgets in Ionic app

### ISSUE THREAD

**Issue by rooswelt** [surveyjs/survey-library#842]
### Are you requesting a feature, reporting a bug or ask a question?
Ask a question

### Question
Is it possible to use custom widgets on Ionic (v.3) apps? Are there any tutorials/examples?

**Comment by tsv2013** [comment]
Unfortunately we have not tested SurveyJS with Ionic. We cann't give any recomendations here.
Custom widgets are ordinary HTML/JS/CSS objects. I do not see any objections. But problems can be in case of rendering into specific native controls.

**Comment by rooswelt** [comment]
I'm trying to insert a ImagePicker in my survey.  But I see nothing.
This is my code:

**component.ts**
```
...
 @Input()
  set json(surveyJSON) {
    Survey.Survey.cssType = "bootstrap";
    let surveyModel = new Survey.ReactSurveyModel(surveyJSON);
    if (surveyModel.jsonErrors) {
      console.error("Error in json survey", surveyModel.jsonErrors);
    }
    surveyModel.locale = "it";
    surveyModel.onComplete.add(survey => {
      this.surveyCompleted.emit(survey.data);
    });
    Survey.defaultBootstrapCss.navigationButton = "btn btn-primary";
    Survey.SurveyNG.render("surveyElement", { model: surveyModel });
  }
...
```
 **index.html**
```
<head>
....
  <script src="https://unpkg.com/jquery"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/image-picker/0.3.0/image-picker.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/image-picker/0.3.0/image-picker.css" />
  <script src="https://unpkg.com/surveyjs-widgets"></script>
....
</head>
```

**JSON survey content**
```
...
"elements": [
        {"type": "imagepicker",
            "name": "choosepicture",
            "title": "What animal would you like to see first ?",
            "choices": [
                {
                    "value": "lion",
                    "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/lion.jpg"
                }, {
                    "value": "giraffe",
                    "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/giraffe.jpg"
                }, {
                    "value": "panda",
                    "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/panda.jpg"
                }, {
                    "value": "camel",
                    "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/camel.jpg"
                }
            ]},
....
```

I see other elements but no image picker. In console 
I have this error:
![schermata 2017-12-21 alle 17 15 03](https://user-images.githubusercontent.com/1296566/34264237-83fa7510-e672-11e7-8da1-fdb6dcbe3fbb.png)

I'm kinda stuck. Any advice?

**Comment by andrewtelnov** [comment]
@rooswelt You may have this error, if the "imagepicker" was not registered for some reason.
It means that following code: https://github.com/surveyjs/widgets/blob/master/src/image-picker.js was not executed at the moment the survey starts parsing the json.
I can't see where do you inlude "survey.jquery.js" script? It should be included before "surveyjs-widgets"

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
Hello! You could check this project https://github.com/abritopach/ionic-surveyjs. It may help.

**Comment by nikhilkenge** [comment]
Hi @dmitrykurmanov ,

We are working on a project, and we are stuck while using the sortable widget.
The sortable widget is not appearing in the survey and we are not able to trace what is wrong in it.

It would be really grateful, if you could please check the below codebase and let us know what went wrong in that.

Repo: https://github.com/nikhilkenge/ionicSortableJs.git

Thanks in advance.

**Comment by dmitrykurmanov** [comment]
@nikhilkenge, hello! We have fixed your example, please check the pull request https://github.com/nikhilkenge/ionicSortableJs/compare/master...dmitrykurmanov:patch-1 . There are two moments: 

-  we copy and past our sortable widget code  (https://github.com/surveyjs/widgets/blob/master/src/sortablejs.js)
- and we have changed call order and params for `addCustomWidget` function. It must be called before creation of survey instance (because of _custom type_)

PS In this repo (https://github.com/surveyjs/surveyjs_angular_cli) we are demonstrating the recommended way of using **surveyjs-widgets** in an angular app.
