### ISSUE TITLE
Dynamic Panel (Tab) wrongly switch panel when some panels are hidden

### ISSUE THREAD

**Issue by zvn2060** [surveyjs/survey-library#8430]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?
When dynamic panel render as tab `{ "renderMode": "tab" }`
and some of its panel was hidden by `templateVisibleIf`

click the tabs which are after hidden tab, doesn't jump to correct tab.

Like, the logic still consider all panels are visible.

### What is the expected behavior?

It should jump to correct panel

### How would you reproduce the current behavior (if this is a bug)?

In below repro size, the survey is filled with answer, where the `question2: 2` was config to hidden
and click tab (value: 3), it will jump to value: 4 tab

```javascript
{
  question1: [
    { question2: 1 },
    { question2: 2 },
    { question2: 3 },
    { question2: 4 },
  ],
}
```

[CodeSandbox](https://codesandbox.io/p/devbox/vue-recursive-update-tagbox-vmodel-when-choice-from-api-d3vggf?file=%2Fsrc%2FApp.vue&embed=1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cln2dyjud00083n6fdrs8qu2t%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cln2dyjuc00033n6frdcx8hoe%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cln2dyjud00053n6f6qqh1p4o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cln2dyjud00073n6fbynhzy7w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cln2dyjuc00033n6frdcx8hoe%2522%253A%257B%2522id%2522%253A%2522cln2dyjuc00033n6frdcx8hoe%2522%252C%2522activeTabId%2522%253A%2522clxk0owht00l53j6j02hrweca%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cln2dyjuc00023n6fkzwt5xzq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxk0fxgl00023j6j8w8488j1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A41%252C%2522endColumn%2522%253A2%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FMyFirstSurvey.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clxk0owht00l53j6j02hrweca%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cln2dyjud00073n6fbynhzy7w%2522%253A%257B%2522id%2522%253A%2522cln2dyjud00073n6fbynhzy7w%2522%252C%2522activeTabId%2522%253A%2522cln2dyjud00063n6fgiufnuwa%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cln2dyjud00063n6fgiufnuwa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522isCloud%2522%253Atrue%252C%2522id%2522%253A%2522clxk0rzqr00tk3j6j8umxi5sj%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cln2dyjud00053n6f6qqh1p4o%2522%253A%257B%2522id%2522%253A%2522cln2dyjud00053n6f6qqh1p4o%2522%252C%2522activeTabId%2522%253A%2522clxk0qi6800q33j6jnoduo5dl%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clxk0qi6800q33j6jnoduo5dl%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15.144404332129966%257D)

### Specify your Environment

* browser: Edge
* browser version: 126.0.2592.56 64bit
* surveyjs platform (angular or react or jquery or knockout or vue): Vue 3
* surveyjs version: 1.11.2

**Comment by JaneSjs** [comment]
Hello,
Thank you for reporting this issue. I reproduced it using the provided demo.

https://github.com/surveyjs/survey-library/assets/22372972/9db9c646-7dd5-400b-95c9-ec6f8e3b5d12


We will research this issue and update you shortly. Please stay tuned.
