### ISSUE TITLE
The survey.onUpdateChoiceItemCss function is not fired for a Dropdown question

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8446]
T18645 - Curious as to why onUpdateChoiceItemCss is not firing for dropdown options.
https://surveyjs.answerdesk.io/internal/ticket/details/T18645
***
The [`survey.onUpdateChoiceItemCss`](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onUpdateChoiceItemCss) function is not fired for a Dropdown question. 
[View Demo](https://plnkr.co/edit/W9A7OhF5Ms4Q0y3s)

**Comment by JaneSjs** [comment]
I discussed this issue with our developers. It appears that the [survey.onUpdateChoiceItemCss](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onUpdateChoiceItemCss) function is not raised for Dropdown list items.
To customize drop-down items, we suggest that you create a custom item component and attach required CSS classes/apply styling at the level of a custom item template. For more information, please visit [Custom Item Template](https://surveyjs.io/Library/examples/dropdown-box-with-custom-items/reactjs).

@RomanTsukanov please update the documentation: [survey.onUpdateChoiceItemCss](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onUpdateChoiceItemCss).

**Comment by RomanTsukanov** [comment]
@JaneSjs 
Done: https://github.com/surveyjs/survey-library/commit/4d97e7e0abadcd287f8a8eecd9bc050edc545d3a
