### ISSUE TITLE
Add custom CSS styling to particular element (color buttons of rating scale)

### ISSUE THREAD

**Issue by DominiqueMakowski** [surveyjs/survey-library#8482]
I struggle to find a way of modifying the CSS styling for one particular element of a page, a rating scale:

![image](https://github.com/surveyjs/survey-library/assets/8875533/b58dca55-aa86-46ce-8f43-d60a2078414e)

For which I would like to color the buttons background (with a reds -> greens gradient). Is that something that this possible using SurveyJS? Thanks!

**Comment by JaneSjs** [comment]
Hello @DominiqueMakowski,
You can colorize a rating scale items using a [custom CSS](https://surveyjs.io/form-library/documentation/manage-default-themes-and-styles#apply-custom-css-classes) or by creating a custom rating item template.

For instance, apply the following CSS to define Red and Green background for Rating Scale items:
```
.sd-rating__item:nth-child(-n+4)  {
  background-color: red;
}
.sd-rating__item:nth-last-child(-n+7)  {
  background-color: greenyellow;
}
```
[View Plunker](https://plnkr.co/edit/nGrapvXqXEWJDXmz)
![image](https://github.com/surveyjs/survey-library/assets/22372972/bb3cbf5c-9f30-4a0b-9ebf-9a5f7b6be553)

If you wish to implement a custom rating item template, please visit [Rating Scale: Custom Item Component Support](https://surveyjs.io/stay-updated/release-notes/v1.9.113#rating-scale-custom-item-component-support).

Please feel free to reactivate this thread if you require further assistance.
