### ISSUE TITLE
Rating Scale is Converted to Dropdown on Smaller Screens or when a survey mode is Static and the width is not enough to display buttons

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8492]
A Rating Scale adaptively changes its layout and switches from the button to dropdown mode when there is not enough room to entirely display all buttons: [View Demo](https://surveyjs.io/form-library/examples/ui-adaptation-modes-for-rating-scale/reactjs). However, users consider this option as an issue rather than a adaptivity feature. 

Here are related issues:

* T18813 - Issue with Rating Question Display on Mobile Devices
https://surveyjs.answerdesk.io/internal/ticket/details/T18813
* T18368 - rating gets converted to dropdown when rateMax is used
https://surveyjs.answerdesk.io/internal/ticket/details/T18368
* T16222 - Rating and NPS question type become dropdown 
https://surveyjs.answerdesk.io/internal/ticket/details/T16222
* T15945 - Rating scale min/max description rendering bug
https://surveyjs.answerdesk.io/internal/ticket/details/T15945
* T14724 - Rating Scale
https://surveyjs.answerdesk.io/internal/ticket/details/T14724
* T14027 - Rating Scale as a Multiple-Choice Matrix column - Rating values are cut off in small browser windows or the mobile views
https://surveyjs.answerdesk.io/internal/ticket/details/T14027
* T14213 - Rating Question on mobile and large screen 
https://surveyjs.answerdesk.io/internal/ticket/details/T14213
* T13934 - Rating - Stars display as dropdown 
https://surveyjs.answerdesk.io/internal/ticket/details/T13934
* T11889 - Keep “Rating” type question as button in mobile view
https://surveyjs.answerdesk.io/internal/ticket/details/T11889

Perhaps, we can decrease the size of rating scale buttons to display buttons on smaller screens.

**Comment by lander854** [comment]
there is an issue with this, when converting rating with custom values to dropdown, dropdown uses value to display its options, instead of text.

**Comment by JaneSjs** [comment]
Regarding the initial issue: you can fix the Rating display mode using the [displayMode](https://surveyjs.io/form-library/documentation/api-reference/rating-scale-question-model#displayMode) option. To always display buttons, set this option to `"buttons"`.

@lander854, thank you for a follow-up. We already fixed this issue at https://github.com/surveyjs/survey-library/issues/8953. Please upgrade your SurveyJS Form Library.
