### ISSUE TITLE
[Angular] Users can change a dropdown value by clicking a read-only Dropdown field

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8493]
T18827 - For dropdown, mode "display" is allowing to select the options
https://surveyjs.answerdesk.io/internal/ticket/details/T18827
***

https://github.com/surveyjs/survey-library/assets/22372972/ff29270e-a350-4cf5-9948-cbd941e42094

To reproduce the issue, insert the following JSON within a creator at https://surveyjs.io/survey-creator/examples/free-nps-survey-template/angular#.
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "dropdown",
     "name": "question1",
     "defaultValue": "Item 2",
     "choices": [
      "Item 1",
      "Item 2",
      "Item 3"
     ]
    }
   ]
  }
 ],
 "mode": "display"
}
```

**Comment by dmitry-kurmanov** [comment]
related to https://github.com/surveyjs/survey-library/issues/8394
