### ISSUE TITLE
Ranking question response isn't showing when survey property "questionsOnPageMode" set to 'singlePage'.

### ISSUE THREAD

**Issue by zenricatlasopen** [surveyjs/survey-library#8500]
### Updated 
Here is [the reproduciable example](https://plnkr.co/edit/g0nnnNSTwDt6P7Dz).

Ranking question response isn't showing when survey property "questionsOnPageMode" set to 'singlePage'. Same happens inside survey js pdf.

### package versions:
![image](https://github.com/surveyjs/survey-library/assets/137736697/2d48ee29-1dc3-4baa-819e-cc96f0970d71)

### Here's the code:
![image](https://github.com/surveyjs/survey-library/assets/137736697/bd5dd92a-47d7-4ca3-b73e-b2f9aec219a9)

### Result:
![image](https://github.com/surveyjs/survey-library/assets/137736697/d321aee2-58ba-4edc-aaa9-b9f8fcb6da21)

the order should be: 'Item 3', 'value 2', 'text1'

**Comment by zenricatlasopen** [comment]
@andrewtelnov is there a way we can apply that fix in our application without changing our survey js version?

**Comment by andrewtelnov** [comment]
@zenricatlasopen 
You can look at my commit. You need to [override a function and add one line of code](https://github.com/surveyjs/survey-library/commit/169629eb2152cb3aac05df43478c7c1f64459d40#diff-2a4bf52e08ed5d622d52e22e5509d90f5b1f832715042aade6f9b390ae110ed7R148).

What version you are and why can't you use to the latest one?

Thank you,
Andrew

**Comment by zenricatlasopen** [comment]
@andrewtelnov  thank you for respondeing

Do you know how to add that line of code to our app?
![image](https://github.com/surveyjs/survey-library/assets/137736697/173e235e-d2eb-408c-b594-04c8cb6e2649)

**Comment by andrewtelnov** [comment]
@zenricatlasopen I can see you are using Creator and other our libraries in your project. Please write to our [technical support](https://surveyjs.answerdesk.io/) forum, provide your developer license info and the version of SurveyJS Library you are using. We will try to find a solution.

Thank you,
Andrew
