### ISSUE TITLE
Progress Bar counts invisible questions when calculating the total progress value

### ISSUE THREAD

**Issue by MrSatyam77** [surveyjs/survey-library#8514]
Survey JS Customs progress bar documentation [link](https://surveyjs.io/form-library/examples/progress-bar-with-percentage/angular).

My Progress Bar Not Completed 100% even all answer is fillable. Code [link](https://codesandbox.io/p/sandbox/surveyjs-angular-forked-ryc43s?file=%2Fsrc%2Fapp%2Fcomponents%2Fsurvey.component.ts).

**Description:**
I am adding one dynamic matrix in Survey Form.
I added the field dynamically with SurveyJS.
If I select the Yes then my second column value visible. 
If I select the No then my second column value not visible.
When All Column value is Yes then It's working fine.
But when I select two field NO and second field value not hide and progress count is not display correctly

Can anyone please address that how can i ignore the value If it's not visible in matrix?

**Comment by JaneSjs** [comment]
Hello @MrSatyam77,
A custom progress bar uses the default [`survey.progressValue`](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#progressValue) property value. However, the `survey.progressValue` counts invisible questions to calculate the total number of questions.

[View Demo with a standard Progress bar](https://plnkr.co/edit/2ppvKHLjHXk5FIrO)
![image](https://github.com/surveyjs/survey-library/assets/22372972/cc741936-b075-4c80-b98c-6e0247ffaa9a)

I will reach out to our developers regarding the possible option to exclude invisible questions from the total progress number.

**Comment by MrSatyam77** [comment]
@andrewtelnov this issued is not resolved which version (survey-core, survey-angular-ui) it's resolve ?

https://codesandbox.io/p/sandbox/surveyjs-angular-forked-ryc43s?file=%2Fpackage.json%3A14%2C35
