### ISSUE TITLE
goNextPageAutomatic is not working when using custom UI elements.

### ISSUE THREAD

**Issue by mariano-ramonda** [surveyjs/survey-library#8527]
When using a custom UI component for rendering question's elements, as seen here https://surveyjs.io/form-library/examples/add-custom-items-to-single-and-multi-select-questions/reactjs#content-code
`goNextPageAutomatic = true` does not work (while using the default UI, it works).

### Are you requesting a feature, reporting a bug or asking a question?
This is a bug; the behavior should be the same regardless of the UI being rendered.

* surveyjs version:
```
    "survey-core": "^1.11.4",
    "survey-react-ui": "^1.11.4",
```

**Comment by JaneSjs** [comment]
Hello @mariano-ramonda,
Thank you for reporting this issue. We will research it and update you shortly.
https://plnkr.co/edit/ixmntFP03udVGind

**Comment by andrewtelnov** [comment]
@mariano-ramonda Here is [the working example](https://plnkr.co/edit/jxbeJuwZOF1Cj2e6).
You need to handle onMouseDown event as shown in the example.

Thank you,
Andrew

**Comment by mariano-ramonda** [comment]
Thank you, @andrewtelnov.
I highly recommend you to add this to the documentation about rendering custom UI and using go to next page automatically.
