### ISSUE TITLE
Rating Scale in Dropdown Mode - The popup is immediately closed and it's impossible to select a rate item if a question has a large title text

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8538]
T18947 - Issue blink on rating question type at small screen
https://surveyjs.answerdesk.io/internal/ticket/details/T18947

**Comment by joaquinnunez** [comment]
i was hunting this bug today, thanks for the update ❤️

**Comment by joaquinnunez** [comment]
Question, was this added to the 2.5.35 version? I upgraded it, it worked, and then it did not, maybe I tested it incorrectly. With the cursor instead of a tap. But it seems to me that it is still failing in 2.5.35

**Comment by JaneSjs** [comment]
Hi @joaquinnunez,
Yes, this fix is included to v2.5.25. To process your inquiry in the most efficient manner, I created a separate issue on your behalf: https://github.com/surveyjs/survey-library/issues/11622. Please refer to it for further details.
