### ISSUE TITLE
Ratings with buttons: how to avoid the collapsing of the buttons over 2 lines? minWidth has no effect

### ISSUE THREAD

**Issue by DominiqueMakowski** [surveyjs/survey-library#8544]
Using the following minimal example:

```js
{
 "title": "NPS Survey Question",
 "completedHtml": "<h3>Thank you for your feedback</h3>",
 "completedHtmlOnCondition": [
  {
   "expression": "{nps_score} >= 9",
   "html": "<h3>Thank you for your feedback</h3> <h4>We are glad that you love our product. Your ideas and suggestions will help us make it even better.</h4>"
  },
  {
   "expression": "{nps_score} >= 6  and {nps_score} <= 8",
   "html": "<h3>Thank you for your feedback</h3> <h4>We are glad that you shared your ideas with us. They will help us make our product better.</h4>"
  }
 ],
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "rating",
     "name": "a",
     "minWidth": "1000px",
     "maxWidth": "200%",
     "title": "Question 1",
     "rateCount": 9,
     "rateMax": 9,
     "displayMode": "buttons"
    },
    {
     "type": "rating",
     "name": "b",
     "minWidth": "300x",
     "title": "Question 2",
     "rateCount": 9,
     "rateMax": 9,
     "displayMode": "buttons"
    },
    {
     "type": "rating",
     "name": "c",
     "width": "200%",
     "title": "Question 3",
     "rateCount": 9,
     "rateMax": 9,
     "displayMode": "buttons"
    }
   ]
  }
 ],
 "showQuestionNumbers": "off"
}
```

I tried to play with `minWidth`, `width`, `maxWidth` parameters so that the buttons don't collapse on 2 lines for narrow screens:

![image](https://github.com/surveyjs/survey-library/assets/8875533/fc3c67b1-e3ed-423a-b787-867eacbc82d9)

I didn't manage to do it, is there a solution to that?

**Comment by JaneSjs** [comment]
Hello,
You can [apply a custom CSS class](https://surveyjs.io/form-library/documentation/manage-default-themes-and-styles#apply-custom-css-classes) and decrease the size of rating scale buttons to allow them fit within a row.
Consider the following demo: [View Plunker](https://plnkr.co/edit/XY4jIUjLRKImAhpl).
```
.smaller-rating__item {
  min-width: calc(2*(var(--sjs-base-unit, var(--base-unit, 8px))));
   width: calc(5*(var(--sjs-base-unit, var(--base-unit, 8px))));
   height: calc(5*(var(--sjs-base-unit, var(--base-unit, 8px))));
}
survey.onUpdateQuestionCssClasses.add((sender, options) => {
        if(options.question.getType() === "rating"){
           options.cssClasses.item += " smaller-rating__item";
        }
});
```
Alternatively, create a [custom theme](https://surveyjs.io/form-library/documentation/manage-default-themes-and-styles#create-a-custom-theme) and decrease the Scale factor to make all survey elements appear in a more compact way.

Let me know if you have further questions.

**Comment by DominiqueMakowski** [comment]
Thanks! Is it possible to set thhe button size to be expressed dynamically as a function of the window size (i.e., in % screen?)
