### ISSUE TITLE
Auto populate today's month 

### ISSUE THREAD

**Issue by ilaplain15115** [surveyjs/survey-library#8552]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question

### What is the current behavior?

Currently I do not know how to get a single line input question to automatically generate today's date. I want to use the date to trigger question visibility

### What is the expected behavior?

I want the current month question to automatically generate todays month. I want question 2 'Seasonal Question' to only be visible if the month is current month question is July. 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
{
 "title": "Github4",
 "logoPosition": "right",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "question1",
     "title": "Current date",
     "questionCategory": "surveyquestion",
     "inputType": "month"
    },
    {
     "type": "paneldynamic",
     "name": "question3",
     "questionCategory": "surveyquestion",
     "templateElements": [
      {
       "type": "matrixdropdown",
       "name": "question2",
       "questionCategory": "surveyquestion",
       "columns": [
        {
         "name": "Column 1",
         "cellType": "boolean"
        }
       ],
       "choices": [
        1,
        2,
        3,
        4,
        5
       ],
       "rows": [
        "Regular question",
        {
         "value": "Seasonal question",
         "visibleIf": "{question1} = '2024-07'"
        }
       ]
      }
     ]
    }
   ]
  }
 ]
}

```

### Specify your
browser: Chrome 

browser version: 119.0.6045.160 

surveyjs platform (angular or react or jquery or knockout or vue): Angular 

surveyjs version: 1.9.112

**Comment by JaneSjs** [comment]
Hello @ilaplain15115,
The [`today()`](https://surveyjs.io/form-library/documentation/design-survey/conditional-logic#today) function should be used to set a today's date as a default question value. 
```
 {
   "type": "text",
   "name": "question1",
   "title": "Current date",
   "defaultValueExpression": "today()",
  "inputType": "month"
}
```
However, the `month` entry field cannot currently parse the supplied default value in UTC format and convert it to a month input format. I'll forward this issue to our developers for further investigation. We'll update you as soon as we get any news to share.
