### ISSUE TITLE
Multi-line question titles aren't aligned vertically when `titleLocation: "left"`

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-library#8554]
https://surveyjs.io/published?id=b08b07f2-f126-43bd-9781-f484abbd340f

![image](https://github.com/user-attachments/assets/e3b7fbf2-ac28-4cec-853f-cfb5591fd15c)

**Comment by JaneSjs** [comment]
https://surveyjs.io/pdf-generator/examples/add-markup-to-customize-pdf-forms/reactjs

**Comment by mikeamelin** [comment]
Modified demo —

[survey.json](https://github.com/user-attachments/files/16235743/survey.json)
