### ISSUE TITLE
Library Only: Dynamic matrix's row drag-n-drop.

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-library#8596]
Same way as for Ranking.

![Image](https://github.com/user-attachments/assets/b7be2049-b2ee-4719-a7db-e30e5ce7f8c9)

**Comment by dmitry-kurmanov** [comment]
- [ ] library / preview
- [ ] design surface
- [ ] property grid

**Comment by mikeamelin** [comment]
**Design-time**

- [ ] 1 — a row (the left editor) should be aligned with a question's title
- [ ] 2 — the icon should be in the middle of the row
- [ ] 3 — looks like the icon is smaller than should be




<img width="746" alt="Screenshot 2024-11-21 at 12 51 08" src="https://github.com/user-attachments/assets/76b5a2d6-1024-4121-873d-6433685f98bb">


**Run-time**

- [ ] 1 — a row (the left editor) should be aligned with a question's title
- [ ] 2 — paddings (depends on (1))
<img width="262" alt="Screenshot 2024-11-21 at 12 52 19" src="https://github.com/user-attachments/assets/33e15361-d88a-49c6-9c00-582520b2db7c">
