### ISSUE TITLE
The 'Could not find a declaration file for module 'survey-core/themes/borderless-light'' TypeScript error occurs on an attempt to load a SurveyJS theme

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8598]
T19095 - Changing the default theme
https://surveyjs.answerdesk.io/internal/ticket/details/T19095
***
The following compilation error appears when [trying to load a SurveyJS Theme](https://surveyjs.io/form-library/documentation/manage-default-themes-and-styles#apply-a-predefined-theme):
```
import { BorderlessLight } from 'survey-core/themes/borderless-light';

creator.theme = BorderlessLight;
```
```
Error: src/app/survey-creator/survey-creator.component.ts:3:33 - error TS7016: Could not find a declaration file for module 'survey-core/themes/borderless-light'. 'D:/SurveyJS/code-examples/get-started-creator/angular/node_modules/survey-core/themes/borderless-light.js' implicitly has an 'any' type.
  If the 'survey-core' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module 'survey-core/themes/borderless-light';`

3 import { BorderlessLight } from 'survey-core/themes/borderless-light';
```
***
A predefined theme can be applied as follows:
```
import { LayeredDarkPanelless  } from 'survey-core/themes';

creator.theme = LayeredDarkPanelless;
```

**Comment by OlgaLarina** [comment]
Hello, @JaneSjs !
Themes can be imported in several ways. The documentation should be corrected.

import { BorderlessLight } from 'survey-core/themes';  
import BorderlessDark from 'survey-core/themes/borderless-dark';

**Comment by RomanTsukanov** [comment]
Fixed in https://github.com/surveyjs/service/pull/2376
