### ISSUE TITLE
Cannot reorder items on Ranking on a mobile

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8604]
T19123 - error when drag the option ranking 
https://surveyjs.answerdesk.io/internal/ticket/details/T19123
***
I tested [Ranking](https://surveyjs.io/form-library/examples/s/add-ranking-question-to-form/) on my Android device, however, didn't manage to drag an item by holding the drag icon/the entire item.

https://github.com/user-attachments/assets/6fd7ac13-4980-48b5-9ef8-72b2ffe0701a

**Comment by dmitry-kurmanov** [comment]
probably caused by https://github.com/surveyjs/survey-library/pull/8441

**Comment by JaneSjs** [comment]
+ a Dropdown appears as follows:
![image](https://github.com/user-attachments/assets/799dd4a7-4e26-4d14-bfdb-d13bf4f7c8b7)
