### ISSUE TITLE
Dropdown - Display a popup regardless of a device screen dimension

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8610]
* [T19133 - Remove popup modal from Dropdown](https://surveyjs.answerdesk.io/internal/ticket/details/T19133)
* [T18500 - Drop Down Shows Pop Up Modal](https://surveyjs.answerdesk.io/internal/ticket/details/T18500)
* _Is there a way to disable the fancy dropdown in survey js?_
[T18194 - Use native select dropdown](https://surveyjs.answerdesk.io/internal/ticket/details/T18194)
* _on mobile the rendering is displayed in a modal, which I don't like._
[T17056 - Render dropdown on mobile](https://surveyjs.answerdesk.io/internal/ticket/details/T17056)
* [T15974 - dropdown popover](https://surveyjs.answerdesk.io/internal/ticket/details/T15974)
***
Depending on a device screen size, a Dropdown is displayed as a regular drop-down (desktop), a popup (tablet), or an overlay /popover on a mobile. Customers ask to display a 'normal' popup on all devices: desktop, tablet, mobile.

**Comment by RomanTsukanov** [comment]
If I get it right, and we're going to let programmers select the menu type dynamically based on the screen size and/or current question, then here's the API:

```js
survey.onOpenDropdownMenu.add((_, options) => {
  options.menuType: "dropdown" | "popup" | "overlay",
  options.screenHeight: number,
  options.screenWidth: number,
  options.question: Question
});
```

**Comment by dk981234** [comment]
Probably, isTouchDevice flag should be available in the options

**Comment by andrewtelnov** [comment]
I would add mobile/table/desktop proeprty into the options.
