### ISSUE TITLE
Form Submission loading symbol

### ISSUE THREAD

**Issue by stephenstroud** [surveyjs/survey-library#8630]
When completing a survey is it possible to show a loading symbol on the button and have a debouncing feature?

Thanks

**Comment by andrewtelnov** [comment]
@stephenstroud You can use some [survey.onComplete](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onComplete) event and call `options.showSaveInProgress()`, then based on your result of your saving call `options.showSaveSuccess()` or `options.showSaveError()`.

Thank you,
Andrew

**Comment by stephenstroud** [comment]
> @stephenstroud You can use some [survey.onComplete](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onComplete) event and call `options.showSaveInProgress()`, then based on your result of your saving call `options.showSaveSuccess()` or `options.showSaveError()`.
> 
> Thank you, Andrew

Thank you for this, I updated my code but found it jumps straight to the completed page the API request has even finished. I'm matched to your sample code and used the flag "surveyShowDataSaving": true. Any ideas? thanks

```
        survey.onComplete.add((survey: { data: any }, options) => {
          options.showSaveInProgress();
          
               this.api.saveSurveyResult(requestModel).subscribe({
            next: (response) => {
              options.showSaveSuccess();
              console.log(response);
            },
            error: () => {
              options.showSaveError();
            },

```

**Comment by stephenstroud** [comment]
> @stephenstroud You can use some [survey.onComplete](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onComplete) event and call `options.showSaveInProgress()`, then based on your result of your saving call `options.showSaveSuccess()` or `options.showSaveError()`.
> 
> Thank you, Andrew

I just read the small print, and it saves on the complete page.. it is working, However, now I'm wondering what happens if there is an error due to their input and they need to go back and correct this. How is then achieved if we are at the complete page?

**Comment by andrewtelnov** [comment]
@stephenstroud Yes, it is the valid behavior. It will go to the complete page. If there is an error, there is button to re-submit it again.

Thank you,
Andrew

**Comment by stephenstroud** [comment]
@andrewtelnov  Great I have tested and working as you say. Thank you!
