### ISSUE TITLE
Question - .NET Schema server side validation

### ISSUE THREAD

**Issue by stephenstroud** [surveyjs/survey-library#8639]
Hi, I wanted to validate the survey schema once received through my .NET API I've copied the reference code below. Is there a .NET flavour for this, if not I will create one. 

```// Server-side code for a NodeJS backend
import { Model } from "survey-core";

const surveyJson = { ... };
const survey = new Model(surveyJson);

survey.data = initialSurveyResultJson;
survey.clearIncorrectValues(true);

const correctSurveyResultJson = survey.data;
```

**Comment by andrewtelnov** [comment]
@stephenstroud It would take several lines of code to do it in NodeJS and would require some coding for .Net (C#).
I would do the following.
Together with saving JSON definition that you get from Creator, I would store the data validation JSON with the following format:
`{ questionName/questionValueName : { type: "string"/"number"/"date"/"Array"/..., isRequired: boolean }`
So you will need to run through all your questions:
```js
function getQuestionCodeType(q) {
 if(q.getType() === "text") {
   if(q.inputType === "number") return "number";
   if(q.inputType === "date") return "date";
  }
//Put more logic here
 return "string";
}

const dataValidationJSON = {}
creator.survey.getAllQuestions().forEach( q => {
 dataValidationJSON[q.getValueName] = { type: getQuestionCodeType(q), isRequired: q.isRequired }
});
```
Having this JSON on the server, you will be able to validate user responses .

You need it if you create a service where non authorized client can send the data to your service or from any client.

Thank you,
Andrew
