### ISSUE TITLE
React-ui vs React

### ISSUE THREAD

**Issue by RahulRanjan2806** [surveyjs/survey-library#8645]
In the `build-scripts` folder, there are subdirectories like `react-ui` and `react`, same for other frameworks. What is the difference between these directories, and which one should be used for integrating SurveyJS with React?

**Comment by andrewtelnov** [comment]
@RahulRanjan2806 We will make obsolete survey-react soon. Please use survey-react-ui

Thank you,
Andrew

**Comment by RahulRanjan2806** [comment]
Thanks @andrewtelnov for your assistance. Could you please clarify the difference between the `react-ui` and `react` directories in the current code structure? I’m a bit confused about that. Your help would be greatly appreciated.

**Comment by RahulRanjan2806** [comment]
Thanks @andrewtelnov, really it was helpful.
