### ISSUE TITLE
Is it possible to pre-populate `fieldB`/or run a trigger if `fieldA.<property>` is a certain value?

### ISSUE THREAD

**Issue by doelgonzo** [surveyjs/survey-library#8667]
### Are you requesting a feature, reporting a bug or asking a question?
Question.

### What is the current behavior?

First of all, super awesome lib... There's a usecase we're trying to figure out, and that is if we're able to use the expression engine or basically have triggers respond to changes in the value of a **property** in different field. For example, our survey has a field (Field A) that has a custom property (customProp) that can be value A, B, or C... Field B should be:
- Visible if Field A's customProp is set to A
- Hidden if Field A's customProp is set to B
- Read-only and prepopulated with "X" if Field A's **custom property** is set to A.

How would we achieve this? I was thinking we could reference it like {fieldA.customProp} but it doesn't seem this works.
Is there a different way I should be thinking about this? Thanks in advance!

**Comment by andrewtelnov** [comment]
@doelgonzo You can use `propertyValue` function in the expression:
`"propertyValue('questionA', 'propertyNameA') = 'A' & {questionA} = 1"`.

Thank you,
Andrew

**Comment by doelgonzo** [comment]
@andrewtelnov I tried this:
```
import { useCallback } from "react";

import "survey-core/defaultV2.min.css";
import { Model, Serializer } from "survey-core";
import { Survey } from "survey-react-ui";

Serializer.addProperty("text", {
  name: "customProp",
  type: "dropdown",
  choices: ["val1", "val2", "val3"],
  category: "general",
  visibleIndex: 0
});

const surveyJson = {
  triggers: [
    {
      type: "setvalue",
      expression:
        "propertyValue('questionA', 'customProp') = 'val3' & {questionA} = 1",
      setToName: "questionB",
      setValue: "SUCCESS"
    }
  ],
  elements: [
    {
      type: "text",
      name: "questionA",
      title: "Field with customProp",
      customProp: "val3"
    },
    {
      type: "text",
      name: "questionB",
      title:
        "If questionA = 1, and customProp is val3, this should be set to SUCCESS"
    }
  ]
};

function App() {
  const survey = new Model(surveyJson);
  survey.focusFirstQuestionAutomatic = false;

  const alertResults = useCallback((sender) => {
    const results = JSON.stringify(sender.data);
    console.log(results);
  }, []);

  survey.onComplete.add(alertResults);

  return <Survey model={survey} />;
}

export default App;
```

But when I set questionA to 1, even though it has `customProp` set to *val3*, it doesn't execute the trigger. Maybe I set something up wrong?

See: https://codesandbox.io/s/surveyjs-add-a-survey-to-a-react-application-forked-gp6dpd?file=/src/App.js

**Comment by andrewtelnov** [comment]
@doelgonzo It should be:
"propertyValue('question0', 'customProp') = 'val3' and {question0} = 1"
We don't have `&` it should be 'and'.

Thank you,
Andrew

**Comment by JaneSjs** [comment]
@doelgonzo,
I updated your survey definition following Andrew's recommendation: [View Plunker](https://plnkr.co/edit/HWmpvrH5DW3MMwuw).
```
{
  triggers: [
    {
      type: "setvalue",
      expression:
        "propertyValue('questionA', 'customProp') = 'val3' and {questionA} = 1",
      setToName: "questionB",
      setValue: "SUCCESS"
    }
  ],
  elements: [
    {
      type: "text",
      name: "questionA",
      title: "Field with customProp",
      customProp: "val3"
    },
    {
      type: "text",
      name: "questionB",
      title:
        "If questionA = 1, and customProp is val3, this should be set to SUCCESS"
    }
  ]
}
```
For the record: to conditionallly set a question value, you can use the [`setValueIf`](https://surveyjs.io/form-library/documentation/api-reference/question#setValueIf) and [`setValueExpression`](https://surveyjs.io/form-library/documentation/api-reference/question#setValueExpression) question settings instead of the `setValue` trigger. Consider the updated survey definition: [View Demo](https://plnkr.co/edit/WPn2tZc5kkDEZDrT).
```
{
  elements: [
    {
      type: "text",
      name: "questionA",
      title: "Field with customProp",
      customProp: "val3"
    },
    {
      type: "text",
      name: "questionB",
      title:
        "If questionA = 1, and customProp is val3, this should be set to SUCCESS",
      setValueIf: "propertyValue('questionA', 'customProp') = 'val3' and {questionA} = 1",
      setValueExpression: "SUCCESS"
    }
  ]
}
```
Also, take note that with v1.9.114 and newer, the [`survey.focusFirstQuestionAutomatic`](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#focusFirstQuestionAutomatic) option is set to `false` by default.

Feel free to reach out to us if you require further assistance.
