### ISSUE TITLE
Impossible to override "Bootstrap" theme colors using StylesManager.ThemeColors

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8678]
T19356 - Surveyjs 1.9.96 - boostrap theme and color customization
https://surveyjs.answerdesk.io/internal/ticket/details/T19356
***
The following code doesn't override theme colors.
[View Demo](https://plnkr.co/edit/TMtdUQoNyUba78Zd)
```
Survey.StylesManager.ThemeColors["bootstrap"]['$main-color'] = 'var(--primary)';
Survey.StylesManager.ThemeColors["bootstrap"]['$progress-buttons-color'] = '#5b7489';
Survey.StylesManager.ThemeColors["bootstrap"]['$slider-color'] = 'var(--primary)';
```

**Comment by tsv2013** [comment]
We're going to drop (even in plugins form) BS and BSM soon (in v2.0)
Many new question types (like signaturepad, image picker, dropdown, ranking) even doen't support bootstrap styling.
We can suggest everyone who use BS to move to our new "defaulltV2" theme or use various workarounds.
