### ISSUE TITLE
Progress bar not showing navigation title after surveyjs update

### ISSUE THREAD

**Issue by kravex911** [surveyjs/survey-library#8679]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question 

### What is the current behavior?
I have a couple surveys on my application and while was on version 1.10.3 the progress bar was showing this:
<img width="1135" alt="image" src="https://github.com/user-attachments/assets/67ed2af2-72ce-42d6-b4e7-7d2a895b72e0">

And the arrows allowed me to scroll through the progress bar and it let users know which page to click on if they wanted to get to something quickly. But after updating my surveyjs package, the progress bar now shows this:
<img width="1135" alt="image" src="https://github.com/user-attachments/assets/1948315a-441b-447b-89a7-05e980f5f514">

I was just wondering if maybe I am doing something wrong and that is why the progress bar has changed? in my JSON object I am using:
`"progressBarType": "buttons",
    "showProgressBar": "top"`
    
What I also don' understand is that on my other surveys, they remain the same like so:
<img width="1135" alt="image" src="https://github.com/user-attachments/assets/a65834df-1086-4290-b2f2-8539cee0e114">

Please any help will be highly appreciated

### What is the expected behavior?
I would like the progress bar to have the nav title under each button and arrows letting me scroll along the progress bar

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Firefox MacOS
* browser version: 128.0.3 (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): react 
* surveyjs version: 1.11.10

**Comment by JaneSjs** [comment]
Hello @kravex911,
I created the following demo using v1.10.3. However, I didn't get any arrows for scrolling through a navigation bar: [View Demo (v1.10.3)](https://plnkr.co/edit/pnmdLhq5LjUhkhtv)
![image](https://github.com/user-attachments/assets/46f90fee-431d-4bd4-a28c-30529c953711)

We actually made slignt changes in our button navigation bar. In v1.11.11, it appears as follows: [View Demo (v1.11.11)](https://plnkr.co/edit/r9Fyx3yE7H85LIjI).
![image](https://github.com/user-attachments/assets/d9c57d3e-bdfc-49f7-9d63-9e4464e9d00a)

For multi-page forms with many pages, we generally recommend considering a compact navigator mode: [View Demo](https://plnkr.co/edit/ERHkxfvI5oZBe5M2).
```
const json = {
  "showProgressBar": "aboveHeader",
  "progressBarType": "pages",
  "progressBarShowPageNumbers": false,
  "progressBarShowPageTitles": false,
   //...
}
```
![image](https://github.com/user-attachments/assets/c76a1d87-08be-43de-bd8d-4a44656bb1cd)

To allow users quickly navigate to pages, you may wish to additionally enable a [table of contents](https://surveyjs.io/form-library/examples/table-of-contents/): [View Demo](https://plnkr.co/edit/I8o8APLaYfyavl16).
```
const json = {
  "showProgressBar": "aboveHeader",
  "progressBarType": "pages",
  "progressBarShowPageNumbers": false,
  "progressBarShowPageTitles": false,
   "showTOC": true,
   //...
}
```
![image](https://github.com/user-attachments/assets/72682076-1532-4b44-a880-76b84da1e6c2)

Please let me know if this information helps.
