### ISSUE TITLE
Ranking Items Wrap Issues

### ISSUE THREAD

**Issue by dmitry-kurmanov** [surveyjs/survey-library#8680]
- [x] avoid word breaks (like in radiogroup)
- [x] use wrap in creator's design time

see https://github.com/surveyjs/survey-library/issues/7358

**Comment by mikeamelin** [comment]
- [ ] looks like something is trying to be cutted :)
<img width="740" alt="Screenshot 2024-08-14 at 14 56 23" src="https://github.com/user-attachments/assets/9c94860e-5cb1-4606-8a1b-3a33783f0b80">

- [ ] need to cut
<img width="1382" alt="Screenshot 2024-08-14 at 14 56 52" src="https://github.com/user-attachments/assets/32382cb0-0f4f-427e-a09b-05e866e58939">

- [ ] overlapping
<img width="705" alt="Screenshot 2024-08-14 at 14 57 19" src="https://github.com/user-attachments/assets/46ce3430-3653-4ee8-ac5e-cc38cda4a34d">


**JSON** 
[survey.json](https://github.com/user-attachments/files/16613671/survey.json)
