### ISSUE TITLE
Multi-Select Matrix - A Radiogroup column has -1 in a Column Count property dropdown list

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8685]
In SurveyJS Form Builder, a Radiogroup column contains the `-1` value within a column count setting dropdown. The [`colCount`](https://surveyjs.io/form-library/documentation/api-reference/radio-button-question-model#colCount) property accepts positive integer values.
![image](https://github.com/user-attachments/assets/0b95085c-5a88-49d3-b87f-ef3b6fc2fc6c)

**Comment by andrewtelnov** [comment]
@RomanTsukanov @JaneSjs If -1 then value is taken from `matrix.columnColCount` property.
We need to update the property description.

Thank you,
Andrew
