### ISSUE TITLE
CodeSandbox Issue - Could not find dependency: 'jquery' relative to '/node_modules/survey-js-ui/survey-js-ui.js

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8717]
[View CodeSandbox](https://codesandbox.io/p/sandbox/pensive-bush-t47tk7?file=%2Fpackage.json)
The following message appears on the application startup:
```
Could not find dependency: 'jquery' relative to '/node_modules/survey-js-ui/survey-js-ui.js
```
Expected behavior: as the jquery is not required, a code sandbox should not suggest to install this library.

**Comment by dmitry-kurmanov** [comment]
related to https://github.com/surveyjs/survey-library/pull/8695

**Comment by dmitry-kurmanov** [comment]
### Demos
vanila module - https://codesandbox.io/p/sandbox/vanilla-module-66cmrg?file=%2Fsrc%2Findex.js%3A13%2C1
jquery module - https://codesandbox.io/p/sandbox/unruffled-carson-xhvxkz?workspaceId=edee766e-0cde-4353-8fbc-f772c90e21cb
