### ISSUE TITLE
The survey.validate() function returns false and survey.hasErrors is not empty when a Complete trigger activates and allows users to submit a form without entering required values

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8721]
T19465 - hasErrors() with triggers
https://surveyjs.answerdesk.io/internal/ticket/details/T19465
***
**Current behavior:** if a complete trigger is activated and a user can submit a form leaving required fields empty on subsequent pages, survey validation fails (the `survey.validate()` returns `false` and `survey.hasErrors` is not empty). 
**Expected behavior:** if a complete trigger is activated and a user submits a form leaving required fields unspecified on subsequent pages (which are actually skipped), the survey validation should be passed successfully.

**Comment by andrewtelnov** [comment]
The default behavior could be changed by using the following code:
```js
    survey.onCompleting.add((sender, options) => {
        if(options.isCompleteOnTrigger) {
            options.allow = survey.validate(true, true);
        }
    });
```
Here is [the example](https://plnkr.co/edit/8MoAPYpdYpBqGhwI).

Thank you,
Andrew
