### ISSUE TITLE
Matrix rows do not properly support RTL languages

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#8726]
### Are you requesting a feature, reporting a bug or asking a question?
Bug, follow up from #8335

### What is the current behavior?
Text in matrix rows is not correctly aligned when using a RTL language.

### What is the expected behavior?
It should "just work"

### How would you reproduce the current behavior (if this is a bug)?
https://codesandbox.io/p/sandbox/weathered-violet-fwn6q5?file=%2Fsrc%2Fjson.js

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codesandbox.io/p/sandbox/weathered-violet-fwn6q5?file=%2Fsrc%2Fjson.js

Test code

```js
export const json = {
  pages: [
    {
      name: "page1",
      elements: [
        {
          type: "matrix",
          name: "promoter-features",
          title: {
            default: "Which of the following features do you value the most?",
            ar: "أي من الميزات التالية تقدرها أكثر؟",
          },
          description: {
            default: "Please select no more than three features.",
            ar: "الرجاء تحديد ما لا يزيد عن ثلاث ميزات.",
          },
          isRequired: true,
          columns: ["a", "b", "c"],
          rows: ["الرجاء تحديد ما لا يزيد", "الرجاء تحديد ما لا يزيد"],
        },
      ],
    },
  ],
  showPrevButton: false,
  showQuestionNumbers: "off",
  widthMode: "static",
  width: "1000px",
  locale: "ar",
};
```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by JaneSjs** [comment]
Hello @SamMousa,
Thank you for sharing a demo. Let me confirm that you expect that the row titles are aligned to the right of a parent container?
![image](https://github.com/user-attachments/assets/34ac3e21-dad9-41ef-980e-5cc876144708)

**Comment by SamMousa** [comment]
Yes, I think that is expected for a RTL text right? Hmm, or is it currently right aligned for a LTR text and therefore consistent*-) good question, i dont know the answer!
