### ISSUE TITLE
Matrix Layout in Mobile devices - Introduce an option to render a matrix as a table or list regardless of the screen size

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8728]
Render a matrix on a laptop using the 'mobile' list mode:
* T19444 - Force matrix to use the mobile-size on all screens
https://surveyjs.answerdesk.io/internal/ticket/details/T19444

Render a matrix as table on mobile devices:
* T16565 - Matrix Columns only displayed in "mobile" layout
https://surveyjs.answerdesk.io/internal/ticket/details/T16565
* T15471 - Dynamic matrix mobile view
https://surveyjs.answerdesk.io/internal/ticket/details/T15471

**Comment by JaneSjs** [comment]
+1 user request

T19553 - Force questions to be unresponsive (do not adjust on mobile devices)
https://surveyjs.answerdesk.io/internal/ticket/details/T19553

**Comment by iotashan** [comment]
It looks like these are two separate but related requests. One wants it at the Survey level, and mine wants it at the Question level.
