### ISSUE TITLE
validateValueCallback return type should be optional

### ISSUE THREAD

**Issue by BarkerCreations** [surveyjs/survey-library#8729]
### Are you requesting a feature, reporting a bug or asking a question?
`Bug`

### What is the current behavior?
Typing in the `survey-angular-ui` package requires `validateValueCallback` to return a SurveyError or descendant.

### What is the expected behavior?
If the value is valid I should be able to return null

#### Provide the test code and the tested page URL (if applicable)

Test code (in my custom widget)

```typescript
const onValidateQuestion = (): SurveyError => {
    // Invalid if there is no answer object
    if (question.isRequired && (!question.value || Object.keys(question.value).length === 0)) {
        return new AnswerRequiredError();
    }

    // Yes I know
    // @ts-ignore
    return null;
};

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): `Angular`
* surveyjs version: `survey-angular-ui @ 1.11.12`

**Comment by JaneSjs** [comment]
Hello @BarkerCreations,
The [`survey.onValidateQuestion`](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onValidateQuestion) function doesn't actually expect any return value. If a value is invalid, please specify the `options.error` parameter to display a validation error message to a user.

Let me know what you think.
