### ISSUE TITLE
Progress bar renders very slowly when there are many pages

### ISSUE THREAD

**Issue by leemiadsk** [surveyjs/survey-library#8731]
### Are you requesting a feature, reporting a bug or asking a question?
bug

### What is the current behavior?
page hangs momentarily when moving to the next page

### What is the expected behavior?
instantly move to the next page

### How would you reproduce the current behavior (if this is a bug)?
Clicking next causes the page to hang momentarily. This does not occur when the progress bar is hidden

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://j4wh29.csb.app

Test code
https://codesandbox.io/p/sandbox/staging-https-j4wh29

### Specify your

* browser: Chrome
* browser version: 127.0.6533.120
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.11.12

**Comment by cityisempty** [comment]
Same issure, When I set "showProgressBar": "off",  It renders become fast.

**Comment by JaneSjs** [comment]
Hello Everyone,

Using a progress bar may not be ideal for large forms. The spacing between points is calculated programmatically, so with a high number of pages, these calculations can take time. Additionally, on large forms, the progress bar displays dots without the page titles or indexes. This makes it difficult to navigate to a specific page..

Is it a real usage scenario to have a form with 500 pages?

**Comment by andrewtelnov** [comment]
@leemiadsk @cityisempty You can show the progress as a text and you can show a custom text. Here is [the example](https://plnkr.co/edit/1SHZLyOyJQlVWkjI). It will work fast for you 500 pages and it will be more informative.

Thank you,
Andrew
