### ISSUE TITLE
Tagbox with Lazy Loading - The new selected value is always replaced with the the first selected value while searching

### ISSUE THREAD

**Issue by nhrrsn** [surveyjs/survey-library#8751]
### Are you requesting a feature, reporting a bug or asking a question?

Bug report.

### What is the current behavior?

When using a tagbox with lazy loading, when searching for an item in the tagbox the first item that is selected is rememebered. When that item is deleted and another item is selected, the new value gets overwritten with the first value.

This seems to be related to onGetChoiceDisplayValue only being called once to set the display value of the tagbox. 

The bug does not occur when the search functionality is not used. If the tagbox is opened and and item from the default list is selected, then the tagbox works as expected. 

### What is the expected behavior?

The first selected item should not overwrite subsequent selections. 

### How would you reproduce the current behavior (if this is a bug)?

I have reproduced the bug on codepen here: https://codepen.io/Ian-Harrison/pen/eYwKLJm

This codepen example is forked from the lazy loaded multiselect jQuery example in the documentation.

To reproduce the bug:
1. Search for a country e.g. "france".
2. Select the country.
3. Delete the selected item
4. Search for another country e.g. "germany"
5. When the item is selected, the selected text appears as "France" even though "Germany" should be selected.

#### Provide the test code and the tested page URL (if applicable)

https://codepen.io/Ian-Harrison/pen/eYwKLJm

```
const json = {
  "elements": [
    {
      "type": "tagbox",
      "name": "country",
      "title": "Select a country",
      "isRequired": true,
      "choicesLazyLoadEnabled": true,
      "choicesLazyLoadPageSize": 40
    }
  ],
  "showQuestionNumbers": false
};
const survey = new Survey.Model(json);
survey.applyTheme(SurveyTheme.Default);
survey.onComplete.add((sender, options) => {
    console.log(JSON.stringify(sender.data, null, 3));
});
survey.onChoicesLazyLoad.add((_, options) => {
  if (options.question.getType() === "tagbox" && options.question.name === "country") {
    const url = `https://surveyjs.io/api/CountriesExamplePagination?skip=${options.skip}&take=${options.take}&filter=${options.filter}`;
    sendRequest(url, (data) => { options.setItems(data.countries, data.total); });
  }
});

survey.onGetChoiceDisplayValue.add((_, options) => {
  console.log("onGetChoiceDisplayValue ", options)
  if (options.question.getType() === "tagbox" && options.question.name === "country") {
    const valuesStr = options.values.map(value => "values=" + value).join("&");
    const url = 'https://surveyjs.io/api/GetCountryNames?' + valuesStr;
    sendRequest(url, (data) => { options.setItems(data.countryNames); });
  }
});

function sendRequest(url, onloadSuccessCallback) {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
  xhr.onload = () => {
    if (xhr.status === 200) {
      onloadSuccessCallback(JSON.parse(xhr.response));
    }
  };
  xhr.send();
}

$("#surveyElement").Survey({ model: survey });
```

### Specify your

* browser: Chrome/Firefox
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular & jquery
* surveyjs version: 1.11.6

**Comment by JaneSjs** [comment]
Hello @nhrrsn,
Thank you for reporting this issue. I reproduced it on my end using the latest SurveyJS library version: [View Plunker](https://plnkr.co/edit/Q5w26b9k3cqciYlh).

https://github.com/user-attachments/assets/1ed87972-a02a-4125-9fa5-e41b54925a82


We'll research this issue and update you as soon as we get any news to share. Please stay tuned.
