### ISSUE TITLE
Dynamic Panel - Introduce an onDynamicPanelItemValueChanging event handler

### ISSUE THREAD

**Issue by amitm2f** [surveyjs/survey-library#8755]
Hey, It would be nice to know if you have any plans on implementing a onDynamicPanelItemValueChanging handler that gets triggered before the event and contains the old value of the ItemValue that was changed.

**Comment by JaneSjs** [comment]
Hello @amitm2f,
Please use the [`survey.onDynamicPanelItemValueChanged`](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onDynamicPanelItemValueChanged) function to listen to a dynamic panel's element value change.

Let me know if this function works for you.
