### ISSUE TITLE
The status parameter within the survey.downloadFile function returns "skipped" instead of "success"

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8765]
T19645 - downloadFile callback returns 'skipped' status instead of 'success' or 'error'
https://surveyjs.answerdesk.io/internal/ticket/details/T19645
***
[View Demo](https://plnkr.co/edit/Uao3VSX71udlujhw)
The `survey.downloadFile` function is used to download the fist file uploaded to a File Upload question. However, despite the fact that the `data` parameter returns a base64 encoded file, the `status` returns `skipped`. Previously, it returned `success`.
```
survey.downloadFile(
                question,
                question.name,
                question.value[0],
                (status, data) => {
                    if (status === "success") {
                        alert('success');
                    }
                    if (status === "error") {
                        alert('error');
                    }
});
```
![image](https://github.com/user-attachments/assets/dc5b846d-b136-4b34-a2d7-56003a1edd85)

**Comment by tsv2013** [comment]
One is need to handle the `onDownloadFile` event to use this internal method:
```
            survey.onDownloadFile.add((s, o) => {
                o.callback("success", o.content);
            });
```

https://plnkr.co/edit/rqfFDPvdzUEbZ9aL

**Comment by JaneSjs** [comment]
Thanks, @tsv2013. I created another issue to update the survey.downloadFile function description: https://github.com/surveyjs/survey-library/issues/8768.
