### ISSUE TITLE
Content Security Police compatibility broken

### ISSUE THREAD

**Issue by MrKrabat** [surveyjs/survey-library#877]
### Are you requesting a feature, reporting a bug or ask a question?
The newest release 1.0.2 broke the compatibility with Content Security Police (CSP) which forbids the use of inline Javascript and the use of "eval()" function.

### What is the current behavior?
Browser refuses to execute Javascript. Survey is not showing up at all.
![unbenannt](https://user-images.githubusercontent.com/8700513/35109631-3043e724-fc77-11e7-9033-a776fff34df5.PNG)

### What is the expected behavior?
Everything works as it was with 1.0.1.

### How would you reproduce the current behavior (if this is a bug)?
Inject a CSP for testing purpose. Add to HTML Head:
`<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; font-src 'self';">`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
Press F12 to open your javascript console!
SurveyJS 1.0.2 (broken): https://iq4s-2.hci.uni-hannover.de/tmp/index.php?id=4ff93b77
SurveyJS 1.0.1 (working): https://iq4s-2.hci.uni-hannover.de/master/index.php?id=4ff93b77

Test code not needed.

### Specify your

* browser: Google Chrome
* browser version: 63
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.2

**Comment by tsv2013** [comment]
Thank you for the valueable feedback, @MrKrabat!
This issue is related to the thing that we started to using in the Angular and jQuery libraries the Knockout core instead of React+preact. If you need the CSP compatibility, you can use the "survey-react" library as a workaround for now.
We will discuss this issue with the team and update this thread as soon as we'll find a solution.

**Comment by tsv2013** [comment]
@MrKrabat Could you please describe your requirements in greater details, if it possible - what the real world application are you developing - a web site, an electron app, a chrome extension, chrome app or something else?

**Comment by MrKrabat** [comment]
Thanks, we are developing a web site which allows employees of the institue to create surveys. We use SurveyJS to render a preview in our editor and to display the online surveys.

In general we have no special security requirements, but being CSP compatible and disable of inline-javascript and eval() should be standard for new applications today.

**Comment by tsv2013** [comment]
@MrKrabat Thank you for the information you provided. We understand CSP compatibility importance and we've included this feature in our task list. We'll update this thread as soon as we'll have some results.

**Comment by ngquoccuong** [comment]
I have same issue for SurveyJS 1.0.74 Angular. Do we have any improvement on this? Thanks,

**Comment by ozatski** [comment]
Having the same issue with v1.0.60.

**Comment by tsv2013** [comment]
@ozatski  Yes, we've not changed this behavior.

**Comment by Lionqueen94** [comment]
How high is making SurveyJS compatible with CSP on the task list at the moment? And is there a version of SurveyJS that is CSP compatible (in a comment it was stated that the react version was, but is this still the case)? I'm using the jquery version at the moment.

**Comment by tsv2013** [comment]
@Lionqueen94 No we've postponed this task at this moment

**Comment by tsv2013** [comment]
@Lionqueen94 But react version should still be SCP compatible.

**Comment by sabaansari86** [comment]
Hi any updates on this issue? Is there a fix yet? I am facing the same issue.

**Comment by tsv2013** [comment]
@sabaansari86 You can use the survey-react library as I wrote earlier.

**Comment by sabaansari86** [comment]
The problem is we are using the custom widgets from survey js taht have the knockout dependency. Also surveyjs itself has a dependency on knockout.

**Comment by tsv2013** [comment]
@sabaansari86 You can use the `survey-react` library as I wrote earlier. The `survey-react` library doesn't have knockoutjs dependency. Custom widgets are also doesn't use knockoutjs.

If it doesn't so please provide a live sample illustrating the issue.

**Comment by mattdeacon** [comment]
The survey-react library still uses stylemanager and uses inline styles ... this really should not be closed until it is resolved surely!

**Comment by tsv2013** [comment]
@mattdeacon What's the problem with the inline styles and the styles manager?

**Comment by gawielgo** [comment]
hi guys, is there any possibility that the survey-angular will also be adapted?

**Comment by gawielgo** [comment]
hi @tsv2013 , sorry if I ask you again...when you plan to release that version? if it's possible to know...

**Comment by tsv2013** [comment]
Our roadmap for the nearest future was announced by @andrewtelnov here - https://github.com/surveyjs/survey-library/issues/2756#issuecomment-967461460

After SurveyJS Creator V2 we plan to start work on native Angular implementation (latest Angular). Unfortunately we can't promise you the exact timeframe.

**Comment by tsv2013** [comment]
@gawielgo We started to work on it in this branch - https://github.com/surveyjs/survey-library/tree/feature/3681-native-ng
