### ISSUE TITLE
Frontend snippet to view results from single survey?

### ISSUE THREAD

**Issue by dwjp** [surveyjs/survey-library#8775]
I'd like to compactly render the data (questions, answers, images/uploads, etc) from a single survey response. It feels like this would be a common use case alongside the summary/table view in the Dashboard product.

I think I know how to do this using [getPlainData()](https://surveyjs.io/Documentation/Library?id=surveymodel#getPlainData), with handlers for each data type, but it feels like a boilerplate task that must have been solved many times before?

Is there a feature I'm missing here, or an existing code snippet to achieve this?

**Comment by JaneSjs** [comment]
Hello @dwjp,
You can visualize a user response by opening the same form with existing user answers. Please refer to the following demo: [Read-Only / Display Mode](https://surveyjs.io/form-library/examples/prevent-form-editing-with-read-only-mode/reactjs).
Also, you can visualize a response using a [Tabulator](https://surveyjs.io/dashboard/examples/export-survey-results-to-csv-files/). 
If these options do not fit your needs, you can [obtain survey data](https://surveyjs.io/form-library/documentation/access-and-modify-survey-results) and implement a custom response view.

Let me know if you have further questions.
