### ISSUE TITLE
Custom Questions - Describe how to register a property of the `itemvalues` type using the this.createItemValues function

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8780]
* T19644 - Custom Widget choices not updated
https://surveyjs.answerdesk.io/internal/ticket/details/T19644
* T18061 - Item value property
https://surveyjs.answerdesk.io/internal/ticket/details/T18061
* T15912 - Columns and Rows do not appear on first load 
https://surveyjs.answerdesk.io/internal/ticket/details/T15912
* T19207 - Custom Component Array Editor Help
https://surveyjs.answerdesk.io/internal/ticket/details/T19207
***
Please update the custom question tutorials and clarify how to register custom properties of `itemvalues` type (e.g., choices, rows, columns). An important note: it is necessary to call the `this.createItemValues("propName")` function within a question model constructor.
```
constructor(name) {
    super(name);
    this.createItemValues("mychoices");
}
```

**Comment by RomanTsukanov** [comment]
Fixed in https://github.com/surveyjs/service/commit/3613e7456340101b862a36e6368a82ce0446943d
