### ISSUE TITLE
Surveyjs.io appears to be down with a 503 Service Unavailable

### ISSUE THREAD

**Issue by yogat3ch** [surveyjs/survey-library#8788]
Just an outage report that the website https://surveyjs.io/ seems to be down:
![image](https://github.com/user-attachments/assets/f7339f74-4bb8-4328-987e-66565bdd793a)

**Comment by andrewtelnov** [comment]
@yogat3ch Azure died on slot swapping (we were updating the website). It happens time to time. It is fine now.

Thank you,
Andrew
