### ISSUE TITLE
A Trash Bin icon and an empty space persist when a Dynamic Matrix row is hidden by a condition

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8789]
T19709 - Hide dynamic matrix row
https://surveyjs.answerdesk.io/internal/ticket/details/T19709
***
[View Demo](https://plnkr.co/edit/6oCBuTjYElrI1LZj)
A row is hidden by a condition. However, the empty space an a trash bin icon persist.

![image](https://github.com/user-attachments/assets/84a310f8-cd67-4cbe-af7e-012618576cc1)

***
A usage scenario:
_Yes, this functionality should act like filter._

**Comment by andrewtelnov** [comment]
Fixed by supporting rowsVisibleIf property. Here is [the related issue](https://github.com/surveyjs/survey-library/issues/8809).

Thank you,
Andrew
