### ISSUE TITLE
[Question] Hi, there. I want to make survey form readonly.

### ISSUE THREAD

**Issue by MinWook6457** [surveyjs/survey-library#8808]
Hi, there. I want to make survey form readonly.

```
 survey: {
                _surveyModel: new Survey.Model($("#rsrchModelJson").val()),
                init: function() {
                    this.surveyModel.data = JSON.parse($("#rsrchResultJson").val());
                    this.surveyModel.applyTheme({ isPanelless: true });


                    $("#surveyContainer").Survey({ model: this.surveyModel });
                },
                get surveyModel() {
                    return this._surveyModel;
                },
                set surveyModel(value) {
                    this._surveyModel = value;
                },
            },
```
I want to take a read-only option in an already created survey form.
What additional options do I need to add to enable read-only? 

* browser: Chrome
* surveyjs platform (angular or react or jquery or knockout or vue): jquery

**Comment by JaneSjs** [comment]
Hello @MinWook6457,
To enable the read-only mode, set the [`survey.mode`](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#mode) property to `"display"`. A demo is also available at [Read-Only / Display Mode](https://surveyjs.io/form-library/examples/prevent-form-editing-with-read-only-mode/).

Please feel free to reactivate this thread if you require further assistance.

**Comment by MinWook6457** [comment]
Hello @JaneSjs 
Thank you for your reply.

How can I apply read-only option in the code rather than in the mode when creating a survey?

I want to make read-only on the code.
