### ISSUE TITLE
Panels and nested questions are numbered incorrectly

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8813]
https://surveyjs.answerdesk.io/internal/ticket/details/T19784
***
Consider the following survey:
```
{
    elements: [
      {
        type: "panel", name: "panel1", title: "Panel 1",
        showNumber: true, questionStartIndex: "1.1", showQuestionNumbers: "onpanel",
        elements: [
          { type: "text", name: "q1" },
          { type: "text", name: "q2" }
        ]
      },
      {
        type: "panel", name: "panel2", title: "Panel 2",
        showNumber: true, questionStartIndex: "1.1", showQuestionNumbers: "onpanel",
        elements: [
          { type: "text", name: "q3" },
          { type: "text", name: "q4" }
        ]
      }
    ]
  }
```
The second panel has the `4` number. However, I would expect that the panel has the `2` number since the numbering for inner panel questions is reset within each panel.
![image](https://github.com/user-attachments/assets/c1c26ab7-af23-4d67-a05b-0b37c46b2251)

**Comment by JaneSjs** [comment]
@andrewtelnov, a user also requested for the following numbering schema.
```
Is there a numbering schema supported in surveyjs that allows such an example.

Code
1. panel
    1.1 question in panel
    1.2 question in panel but another one
    1.3 some other one
    1.4 some other other one
    1.5 some other new one

2. some question without panel

3. another panel
    3.1 some different question in panel
    3.2 some even more different question in panel
```

**Comment by kindy91** [comment]
I managed to get it running like the example mentioned by JaneSjs. However, the interaction between designer and preview is quite different.
### Question JSON
`
{
  "logoPosition": "right",
  "showNavigationButtons": "none",
  "showPrevButton": false,
  "maxTextLength": 10000,
  "maxOthersLength": 10000,
  "autoGrowComment": true,
  "elements": [
    {
      "type": "panel",
      "name": "panel1",
      "showNumber": true,
      "showQuestionNumbers": "onpanel",
      "questionStartIndex": "1.1",
      "elements": [
        {
          "type": "text",
          "name": "question1",
          "title": "question"
        },
        {
          "type": "text",
          "name": "question2",
          "title": "question"
        },
        {
          "type": "text",
          "name": "question5",
          "title": "question"
        }
      ]
    },
    {
      "type": "panel",
      "name": "panel2",
      "showNumber": true,
      "showQuestionNumbers": "onpanel",
      "questionStartIndex": "2.1",
      "elements": [
        {
          "type": "text",
          "name": "question3",
          "title": "question"
        },
        {
          "type": "text",
          "name": "question4",
          "title": "question"
        },
        {
          "type": "text",
          "name": "question6",
          "title": "question"
        }
      ]
    },
    {
      "type": "text",
      "name": "question7",
      "title": "question"
    },
    {
      "type": "text",
      "name": "question8",
      "title": "question"
    }
  ]
}
`
### Designer tab
![image](https://github.com/user-attachments/assets/b178c9b9-62fe-430f-bce1-33050e132883)

### Preview tab
![image](https://github.com/user-attachments/assets/df5b209c-b056-4bd6-b3a1-3086700c1822)

**Comment by JaneSjs** [comment]
Hello @kindy91,
Thank you for the update. I reproduced this issue in v1.12.2.
[View Demo](https://plnkr.co/edit/s1Ch5dhtOAHe6ubS)
![image](https://github.com/user-attachments/assets/09f68db3-a29f-433e-ab5e-a2ed284c7f5c)

@andrewtelnov, would you please take a look?

**Comment by andrewtelnov** [comment]
@kindy91 I have fixed the issue. The following JSON will work in v1.12.3 version:
It will be:
1. Panel1
  1.1 question1
  1.2 question 2
2. Panel 2
 2.1 question 3
 2.2 question 4

```js
{
    elements: [
      {
        type: "panel", name: "panel1", title: "Panel 1",
        showNumber: true, questionStartIndex: "1.1", showQuestionNumbers: "onpanel",
        elements: [
          { type: "text", name: "q1" },
          { type: "text", name: "q2" }
        ]
      },
      {
        type: "panel", name: "panel2", title: "Panel 2",
        showNumber: true, questionStartIndex: "1.1", showQuestionNumbers: "onpanel",
        elements: [
          { type: "text", name: "q3" },
          { type: "text", name: "q4" }
        ]
      }
    ]
  }
```
Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@kindy91 @JaneSjs I have added two more unit tests and fixed them in the PR above. It should work fine after this fix.

Thank you,
Andrew

**Comment by JaneSjs** [comment]
@andrewtelnov Andrew, unfortunately, the second panel shows 3.1, 3.2, 3.3 whereas we expect 2.1, 2.2, 2.3. Please refer to [this demo for v1.12.4](https://plnkr.co/edit/mMtquAkkiG7FC02E).
![image](https://github.com/user-attachments/assets/2399fe13-d4ee-4f4a-8276-4728d73be0fc)

**Comment by andrewtelnov** [comment]
@JaneSjs It should be `"questionStartIndex": "1.1"`. You can set it to `"questionStartIndex": "2.1"`, if you want to start from 2 instead of 1. If you set it to: `"questionStartIndex": "10.1"`then the questions in the second panel will start from `11.1`
It can be `"questionStartIndex": "A.a"`, for example.

Thank you,
Andrew
