### ISSUE TITLE
feature: implement a captcha widget (question) out-of-the-box

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/survey-library#882]

**Comment by cdalexndr** [comment]
Captcha would prevent automatic responses that pollute the results.

I've tried to use an external captcha but I've failed to integrate it with surveyjs. 
I've resolved to using custom captcha with plain html forms + some javascript instead.

**Comment by tsv2013** [comment]
Captcha need server-side code, SurveyJS is a client-side library
