### ISSUE TITLE
Allow remove row based on the row index in a matrix question

### ISSUE THREAD

**Issue by amitm2f** [surveyjs/survey-library#8825]
Hey, It would be nice to have an option to add a simple expression to determine if the Remove button should be rendered in a specific row based on its index. Something like:
`"removeRowIf": "{rowIndex} > 5"`

**Comment by JaneSjs** [comment]
Hello,
You can specify the minimum number of rows using the [`minRowCount`](https://surveyjs.io/form-library/documentation/api-reference/dynamic-matrix-table-question-model#minRowCount) property. With this option, a matrix will display a Remove row button only when the number of rows exceeds the minimum row number. Consider the following survey JSON:
```json
{
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "matrixdynamic",
          "name": "question1",
          "columns": [
            {
              "name": "Column 1"
            },
            {
              "name": "Column 2"
            },
            {
              "name": "Column 3"
            }
          ],
          "choices": [
            1,
            2,
            3,
            4,
            5
          ],
          "rowCount": 5,
          "minRowCount": 5
        }
      ]
    }
  ]
}
```
![image](https://github.com/user-attachments/assets/17fe38ae-e411-4afc-9fe9-9ab95c10b454)
![image](https://github.com/user-attachments/assets/ad99130a-8168-4c6e-9d12-08e54e8627a2)

Let me know if this option suits you.
