### ISSUE TITLE
Dropdown item labels are misaligned in RTL

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8827]
T19902 - A drop-down menu with choices shows the options in LTR
https://surveyjs.answerdesk.io/internal/ticket/details/T19902
***
[View Demo](https://plnkr.co/edit/7pbXouZdMTnruor2)
The item texts should be right-aligned.
![image](https://github.com/user-attachments/assets/563134b5-97e2-41be-8def-317d8a17f851)

**Comment by miguellords** [comment]
I think this will help you.
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive
