### ISSUE TITLE
Custom Error is not focus.

### ISSUE THREAD

**Issue by kmmamta** [surveyjs/survey-library#884]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@kmmamta Could you please post here an example to produce the issue.
If you, in [this example](https://surveyjs.io/Examples/Library/?id=validators-event) set the  "least amount" to 1000 and "most amount" to 100 then you get an error in the first input and it will be focused.

Thank you,
Andrew
