### ISSUE TITLE
Multi-Select Matrix - A disabled checkbox is focusable

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8850]
T19986 - Matrix checkbox focusable when disabled
https://surveyjs.answerdesk.io/internal/ticket/details/T19986
***
Consider the following survey:
```
{
  "title": "NPS Survey Question",
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "matrixdropdown",
          "name": "matrix",
          "columns": [
            {
              "name": "col1",
              "cellType": "checkbox",
              "readOnly": true,
              "choices": [
                "1",
                "2"
              ]
            }
          ],
          "rows": [
            "row1",
            "row1"
          ]
        }
      ]
    }
  ],
  "showQuestionNumbers": "off"
}
```
A disabled checkbox can be clicked/selected.

https://github.com/user-attachments/assets/fea0be62-36ee-44cb-b144-efb42c3ba24c

Expected behavior: a disabled checkbox is not selectable.

https://github.com/user-attachments/assets/3afcc081-ef76-4537-aef2-cf39b738c437

**Comment by dmitry-kurmanov** [comment]
https://plnkr.co/edit/TTlIA9EAaLdnMfFo
