### ISSUE TITLE
[question] New survey-ui-js library

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#8855]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
I just noticed the new `survey-ui-js` library. What does it use under the hood for rendering? Is it a knockoutjs wrapper or does it use a self built rendering system? Or something else entirely?

**Comment by JaneSjs** [comment]
Hi @SamMousa,
The [`survey-js-ui`](https://www.npmjs.com/package/survey-js-ui) and [`survey-creator-js`](https://www.npmjs.com/package/survey-creator-js) bundles use the [Preact](https://preactjs.com/) library. These bundles are universal, framework-agnostic, Knockout-free UI rendering bundles which can be used in any JavaScript application or integrated into any framework that SurveyJS doesn't support yet (e.g., Svelte).

Please follow these instructions if you wish to migrate from `survey-knockout-ui` and `survey-creator-knockout` packages: [Knockout-Free UI Rendering Bundles](https://surveyjs.io/stay-updated/release-notes/v1.11.12#knockout-free-ui-rendering-bundles).

Should you have any further questions, please let us know.
