### ISSUE TITLE
Remove default  "choose" option from "matrixdropdown" Dropdown . 

### ISSUE THREAD

**Issue by kmmamta** [surveyjs/survey-library#891]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
@kmmamta There is no such an option now in the SureyJS. We'll discuss this enchancement with the team and update this thread immediately.

**Comment by andrewtelnov** [comment]
We have a boolean [question.showOptionsCaption](https://surveyjs.io/Documentation/Library?id=questiondropdownmodel#showOptionsCaption) property now.

Thank you,
Andrew
