### ISSUE TITLE
Text question with inputType 'range' should contain "min",  "max" and "step" attributes

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/survey-library#892]

**Comment by innoforce-dev** [comment]
Wanted to +1 this issue. We'd need the range input. But without the properties min/max/step it's useless. 

When is that implemented? Issue is already almost 2 yrs. old now.

**Comment by tsv2013** [comment]
@innoforce-dev You are the only who asked for in in this two years.
As a workaround you can use noUIslider - https://surveyjs.io/Examples/Library/?id=custom-widget-nouislider&platform=jQuery&theme=modern or boorstrap slider - https://surveyjs.io/Examples/Library/?id=custom-widget-bootstrapslider&platform=jQuery&theme=modern

**Comment by innoforce-dev** [comment]
I see. noUiSlider seems to play all the tricks. 

Anyway it would be good to add the missing properties for the inputType range - or remove it from the list of inputType options, as it's kind of useless at the moment.

**Comment by andrewtelnov** [comment]
We have these properties now.
