### ISSUE TITLE
[Question] Hi Survey Team. I want to make survey modal using result data.

### ISSUE THREAD

**Issue by MinWook6457** [surveyjs/survey-library#8925]
### Are you requesting a feature, reporting a bug or asking a question?

First, I recieved JSON data below code
```
$.ajax({
        url: "<c:url value='/adm/dashboard/readOnlyRsrchData.json'/>",
        type: "POST" , data : JSON.stringify({rsrchId: id , dataTy : dataTy}),
        contentType: "application/json;charset=utf-8",
        success : function (response) {
            const surveyData = response.data.rsrchModelJson;
            const surveyResult = response.data.rsrchResultJson;

            showDynamicSurveyModal(surveyData, surveyResult);
        }
      })
```
Second, I make to survey form using result json data.
```
 const surveyModel = new Survey.Model(rsrchModelJson);
      surveyModel.data = JSON.parse(rsrchResultJson);

      surveyModel.mode = "display";
      surveyModel.questionsOnPageMode = "singlePage";
      surveyModel.applyTheme({ isPanelless: true });

      $("#surveyContainer").empty();

      $("#surveyContainer").Survey({ model: surveyModel });

      const $modal = $("#commonModal");
      $modal.modal('show');
```

Error : Uncaught TypeError: $(...).Survey is not a function

I imported both jquery and survey using cdn.

How to make survey form in madal...?

**Comment by JaneSjs** [comment]
Hello,
If you wish to integrate a SurveyJS Form Library to a jQuery application, use the [survey-js-ui](https://www.npmjs.com/package/survey-js-ui) package:
* [View Demo](https://plnkr.co/edit/hQfmzn3KNuPzRgSd)
* [View Integration Tutorial](https://surveyjs.io/form-library/documentation/get-started-html-css-javascript)

If you wish to show a popup survey, use the `SurveyUI.renderPopupSurvey` function: [View Demo](https://surveyjs.io/form-library/examples/popup-survey/vanillajs#).

Let me know if you have any further questions.
