### ISSUE TITLE
react warning when prepopulate survey with matrixdynamic with some data

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#894]
### Are you requesting a feature, reporting a bug or ask a question?

bug (minor)

### What is the current behavior?

matrixdynamic generates a warning **only if data is preloaded** :
> Warning: Failed form propType: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`. Check the render method of `SurveyQuestionDropdown`.

### What is the expected behavior?

no warning

### How would you reproduce the current behavior (if this is a bug)?

go https://plnkr.co/edit/5XjVUSsI0gKg6KgHJZt0?p=preview and see console

There are actually 2 warnings. The other one was pointed out in #893

**Comment by andrewtelnov** [comment]
@masciugo I believe the issue has been fixed. Here is [the example](https://plnkr.co/edit/Nt6N2Qb5Zp2u8ykZE3uI?p=preview).

Thank you,
Andrew
