### ISSUE TITLE
Signature Pad - No cookies are included in a request when a signature pad downloads a signature image by URL

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8956]
T20367 - No cookies included in request when signaturepad downloads image
https://surveyjs.answerdesk.io/internal/ticket/details/t20367

**Comment by tsv2013** [comment]
One can use the `survey.onDownloadFile` event to implement custom loading options
See https://github.com/surveyjs/survey-library/issues/8575 for more details
