### ISSUE TITLE
Mark a question as important in addition to isRequired.

### ISSUE THREAD

**Issue by ajay-shenoy** [surveyjs/survey-library#8963]
Other than **isRequired** flag, is there a provision in Survey creator to mark few questions as **important**. And then later store that information in the database for highlighting the important questions within a survey.

**Comment by JaneSjs** [comment]
Hello @ajay-shenoy,
You can mark a question required by enabling the [isRequired](https://surveyjs.io/form-library/documentation/api-reference/question#isRequired) option. With this option, a question will display a red mark and respondents won't be able to leave a question unanswered.

Please let me know if this option works for you.
