### ISSUE TITLE
Identify question of type imagepicker from Survey Response

### ISSUE THREAD

**Issue by ajay-shenoy** [surveyjs/survey-library#8981]
Is there a way to identify that the response or answer is for a question of type imagepicker in the submitted Survey response.

**Comment by JaneSjs** [comment]
Hello @ajay-shenoy,
A response returned by [`survey.data`](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#data) doesn't contain information about a question type. If you wish to save a question type in a survey response, use the [`survey.getPlainData`](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#getPlainData) function.

Let me know if it works for you.

**Comment by ajay-shenoy** [comment]
Tried getPlaindata method on the survey response object however it gives questionname, question title, answer value, answer display value. Didn't get question type in it.

Can you help with an example if possible.

**Comment by ajay-shenoy** [comment]
Tried getPlaindata method on the survey response object however it gives questionname, question title, answer value, answer display value. Didn't get question type in it.

Can you help with an example if possible.

**Comment by JaneSjs** [comment]
Hello,
You can obtain a question using the [`survey.getQuestionByName(questionName)`](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#getQuestionByName) function and check its type using the [`question.getType()`](https://surveyjs.io/form-library/documentation/api-reference/question#getType) function.

Thank you
