### ISSUE TITLE
Text questions display comments

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/survey-library#8986]
**Describe the bug**
Hello, when my project originally used version 1.1.6, the text type issue showed comments via 'hasComment'. Now after updating to the latest version, 'showCommentArea' is used instead, but now the text type does not support displaying comments. Why is this happening? Text type issues, is it possible to customize the implementation to display comments on rendering? Or how do I go about it?

Looking forward to your reply, thank you.

**Expected behavior**
![image](https://github.com/user-attachments/assets/21a145ed-ff53-4de2-bc07-30dc95e7e6c8)

![image](https://github.com/user-attachments/assets/3f259e08-ff90-4bf8-b16f-11fa11453922)

**Comment by JaneSjs** [comment]
Hello,
The Comment option is not available for Text and Comment questions by default. If you wish to enable comments for single-line text input fields, register a custom `showCommentArea` property as follows:
```js
import { Serializer } from "survey-core";

Serializer.addProperty("text", { name: "showCommentArea:switch", layout: "row", visible: true, category: "general" });

let surveyJson = { ...
  {
    "name": "username",
    "type": "text",
    "title": "Username",
    "showCommentArea": true,
    "commentText": "Additional info"
  }
...
}
```
[Example](https://plnkr.co/edit/5rnsZzbSDnB4XCv8)
![image](https://github.com/user-attachments/assets/deaf1587-5578-42a5-b46f-f3f5849bfce2)

**Comment by fengzhihenxs** [comment]
Thank you very much for your support.
