### ISSUE TITLE
Duplicate Error Messages During Async Validation

### ISSUE THREAD

**Issue by ocobble** [surveyjs/survey-library#8993]
**Describe the bug**
I'm trying to create a form that validates multiple questions using async calls to a server. My code is very similar to [this example](https://surveyjs.io/form-library/examples/javascript-async-form-validation/reactjs#) that I found on the SurveyJS website. 

There's one minor issue. If multiple questions fail the validation and then any question is edited, duplicate error messages appear above each question.

**Steps to reproduce**

I've created an example survey [here](https://embed.plnkr.co/plunk/X4tFLHLlYYGhbQMf) to demonstrate the issue.

1. Submit the survey with several invalid answers.
2. After submitting, the error messages will display as normal above the questions that are invalid.
3. Edit any of the questions. Once you finish editing, the error messages will duplicate above the other incorrect questions.

**Expected behavior**
The error messages should only display once.

**Screenshots**

Example of how my example survey looks after submitting: 

<img width="458" alt="SurveyJS Bug 3" src="https://github.com/user-attachments/assets/d20ad87c-34d4-40c8-b020-5ed23a2eddba">

This is what happens after I correct the misspelling in question 2. I only clicked out of the textbox. I didn't hit submit.

<img width="465" alt="SurveyJS Bug 4" src="https://github.com/user-attachments/assets/3cb3c5b4-c1ac-419d-8594-3d0a80019848">

- Browser: Chrome
- Browser version: 130.0.6723.70
- JS framework/library: First discovered this in React, but my plunker is in vanilla javascript.
- SurveyJS version: 1.12.1
- Device: PC

**Comment by JaneSjs** [comment]
Hello,
Thank you for sharing the demo. However, let me note that it doesn't use SurveyJS vanilla JS libraries. Instead, it uses an outdated `survey-jquery` library and a legacy Modern theme. To fix the issue, upgrade your application to use the latest v1.12.8 and use the [`survey-js-ui`](https://surveyjs.io/form-library/documentation/get-started-html-css-javascript) package and a default theme: [View Demo](https://plnkr.co/edit/16ET2V2KjIPBwMIU).

Please feel free to reactivate this thread if you require further assistance.

**Comment by ocobble** [comment]
Thank you for responding. In your demo that you linked, I still get the same error.

<img width="789" alt="Survey JS Error" src="https://github.com/user-attachments/assets/796a6532-f528-4a73-a397-3033f695b2e4">


 My React application uses `survey-core` and `survey-react-ui` version 1.12.1 and has the same issue as well.

**Comment by ocobble** [comment]
@JaneSjs Sorry for the tag, but I just wanted to make sure that you saw my comment from a month ago. The solution that you provided in the demo didn't work.

**Comment by JaneSjs** [comment]
Hello @ocobble,
Please accept my apologies for missing this issue.
Thank you for reporting this problem. We will investigate it and update you as soon as we get any news to share.
***
The similar issue was also reported at Help Desk: [T21166 - Multiple validations are happening simultaneously](https://surveyjs.answerdesk.io/internal/ticket/details/T21166).
