### ISSUE TITLE
Angular uses bootstrap-datetimepicker

### ISSUE THREAD

**Issue by fengzhihenxs** [surveyjs/survey-library#8996]
Hello, I use surveyjs form-library in angular17. I see that there are some third-party widgets built into the official, but I need to use bootstrap-datetimepicker to implement the input format as "10/30/2024 4:20 PM". How do I do that? Hope it inspires me.

Looking forward to your reply, thank you.

**Comment by JaneSjs** [comment]
You can integrate a Bootstrap datepicker using a custom widger option: [View Demo](https://surveyjs.io/form-library/examples/custom-widget-bootstrapdatepicker/angular).
If you wish to proceed with a modern component-based approach, consider creating a custom question model and a custom question renderer which would integrate an [Angular Bootstrap DatePicker](https://ng-bootstrap.github.io/#/components/datepicker/examples). For more information on how to integrate third-party Angular components, please visit [Integrate Third-Party Angular Components](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-angular).

**Comment by fengzhihenxs** [comment]
@JaneSjs  Thank. I'll give it a try.
