### ISSUE TITLE
Dropdown with Lazy Loading - A drop-down list appears empty when re-opening a popup

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#9013]
T20594 - Specify as many forms as i need whit its corresponding form question name
https://surveyjs.answerdesk.io/internal/ticket/details/T20594
***
Please consider the following demo: [View CodeSandbox](https://codesandbox.io/p/sandbox/dazzling-browser-yknls8?file=%2Fsrc%2FSurveyComponent.jsx%3A32%2C16&workspaceId=c1318f77-19a4-463d-b58a-86fcfde8c6c4). To reproduce the issue, select dropdown 1, dropdown 2. Re-open dropdown 2: a list appears empty even though the `options.setItems(selectedItem.values, selectedItem.values.length)` function seems to be invoked with a correct item value array.

![image](https://github.com/user-attachments/assets/9bc0e043-6f59-4ad4-a77f-a9e5ca585278)

**Comment by OlgaLarina** [comment]
Shouldn't pass an Array\<ItemValue> into method setItems. Try the following code.

```
  survey.onChoicesLazyLoad.add((_, options) => {
    if (options.question.name === "dropdown1") {
      const dropdownItems = dropdown1Values.map((item) => {
        const newItem = {
          value: item.id,
          text: item.title,
          values: item.values,
        };
        return newItem;
      });
      options.setItems(dropdownItems, dropdownItems.length);
    }
    if (options.question.name === "dropdown2") {
      debugger;
      const dropdown1 = options.question.parent.getQuestionByName("dropdown1");
      const selectedItem = dropdown1.selectedItem;
      if (!!selectedItem) {
        const dropdownItems2 = selectedItem.values.map((item) => {
          const newItem = {
            value: item.id,
            text: item.text,
          };
          return newItem;
        });
        options.setItems(dropdownItems2, dropdownItems2.length);
      }
    }
  });
```

**Comment by JaneSjs** [comment]
I got a reply from @OlgaLarina. The [`survey.onChoicesLazyLoad`](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onChoicesLazyLoad) event's `options.setItems` callback function should either accept an array of strings or of the `{ value: XXX, text: YYY }` objects. Therefore, it is necessary to update the code as follows: [View Demo](https://codesandbox.io/p/sandbox/stoic-leaf-sc4yx9?file=%2Fsrc%2FSurveyComponent.jsx%3A33%2C28&workspaceId=c1318f77-19a4-463d-b58a-86fcfde8c6c4).
```js{16-20}
survey.onChoicesLazyLoad.add((_, options) => {
    if (options.question.name === "dropdown1") {
      const dropdownItems = dropdown1Values.map((item) => {
        return {
          value: item.id,
          text: item.title,
          values: item.values,
        };
      });
      options.setItems(dropdownItems, dropdownItems.length);
    }
    if (options.question.name === "dropdown2") {
      const dropdown1 = options.question.parent.getQuestionByName("dropdown1");
      const selectedItem = dropdown1.selectedItem;
      if (!!selectedItem) {
        const dropdown2Choices = dropdown1.selectedItem.values.map((item) => {
          return { value: item.value, text: item.text };
        });
        options.setItems(dropdown2Choices, dropdown2Choices.length);
      }
    }
});
```
