### ISSUE TITLE
Selected dropdown value won't change with survey.locale

### ISSUE THREAD

**Issue by jzju** [surveyjs/survey-library#9034]
**Steps to reproduce**

```
<SurveyComponent :model="survey"/>
import { Model } from "survey-core";
const survey = new Model({});

function onChange() {
  survey.locale = lang.value;
}

{
  "choices": [
      {
          "text": {
              "default": "english",
              "ne": "notenglish"
          },
          "value": "one"
      }
  ],
  "name": "q1",
  "title": {
      "default": "english",
      "ne": "notenglish"
  },
  "type": "dropdown"
}
```
Start with survey.locale = "ne", select option one, change survey.locale to "en", everything becomes english except the selected value in dropdown.

**Expected behavior**
The dropdown should say english.

**Screenshots**
![Screenshot_20241111_171748](https://github.com/user-attachments/assets/5dda8020-a4e2-4309-a635-bf869d036a87)

**Please complete the following information:**
- Browser: brave
- JS framework/library: vue3
- SurveyJS version: 1.11.13
- Device: Ubuntu

**Comment by JaneSjs** [comment]
Hi @jzju,
Please upgrade your SurveyJS Form Library to the latest v1.12.9. I tested the following demo and confirmed that a selected Dropdown value is updated correctly.
[View CodeSandbox](https://codesandbox.io/p/sandbox/surveyjs-library-vue3-forked-yd3v6p?file=%2Fsrc%2FApp.vue%3A27%2C1)

Let me know if this helps.

**Comment by jzju** [comment]
Found a workaround to this and and another bug where rating where lacking text. Call survey.fromJSON after changing language.

```
survey.locale = lang.value;
  survey.fromJSON({
    elements: sj,
  });
```

**Comment by JaneSjs** [comment]
Hello,
> Did you select the option before changein language?

I tested the demo in various ways but did not reproduce any issues with improper translation. For me to move forward, I need to reproduce the issue on my end. Please share exact steps to reproduce the issue using [the demo I shared earlier](https://codesandbox.io/p/sandbox/surveyjs-library-vue3-forked-yd3v6p?file=%2Fsrc%2FApp.vue%3A27%2C1).

Thank you

> and another bug where rating where lacking text. Call survey.fromJSON after changing language.

```
survey.locale = lang.value;
survey.fromJSON(yourjson);
```

I would also appreciate if you elaborate on this additional issue. Please share a relevant code/demo for research.

Thank you

**Comment by jzju** [comment]
This is from using your CodeSandbox

https://github.com/user-attachments/assets/98dd021d-189f-4d2e-bdbc-ff12ce114362
