### ISSUE TITLE
Adding Loading Effect to Custom "Print" Button in SurveyJS

### ISSUE THREAD

**Issue by mustaphazeroual04** [surveyjs/survey-library#9035]
Hello SurveyJS Support Team,

I have added a custom navigation button labeled "Print" to my survey, intending to handle an asynchronous process when this button is clicked. I would like to add a loading indicator to the button to improve the user experience while the asynchronous treatment completes.
Here is the code snippet I used for adding the custom "Print" button:

```
survey.addNavigationItem({
  id: "survey_print_btn",
  locTitleName: "printBtn",
  visibleIndex: 49, // "Complete" button has the visibleIndex 50.
  action: () => {
    this.printEvent.emit();
  },
  location: 'end',
  mode: 'small',
  css: 'p-0',
  innerCss: "sd-btn sv-btn sv-footer__complete-btn p-button p-button-sm text-base border-round-lg w-full pt-1 pb-2 font-semibold printBtn"
});
```
Could you please guide me on how to implement a loading effect while the asynchronous action is being processed? Any suggestions or code examples would be highly appreciated.
Thank you for your assistance.
Best regards,
Mustapha ZEROUAL

**Comment by JaneSjs** [comment]
Hello @mustaphazeroual04,
If you wish to implement a custom button which would display some loading indicator during a long-lasting operation, you may consider implementing a custom component and assign it as an action's [component](https://surveyjs.io/form-library/documentation/api-reference/iaction#component).

To learn how to implement a custom component and register it within SurveyJS Form Library, refer to a tutorial which corresponds to your JavaScript platform: [Angular](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-angular) / [React](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-react) / [Vue 3](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-vue).

Thanks
