### ISSUE TITLE
Unable to use markdown "click" on panel titles or descriptions.

### ISSUE THREAD

**Issue by gregpawlowski** [surveyjs/survey-library#9046]
**Describe the bug**
I'm using markdown to add links in my survey. In the title I added a description with a link using markdown as suggested in documentation. The link shows up but does not nothing when clicked.

Markdown links work in questions but not in panel titles or descriptions. When clicking in the panel description int appears that an event handler attached has stopPropagation preventing the link to fire. I think this event is preventing the click.

```
<div data-bind="css: question.cssHeader, click: function(m, e) { if(question.clickTitleFunction) return question.clickTitleFunction(e); }"</div>
```

**Steps to reproduce**
1. Set up Survey Like this:
```
{
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "panel",
          "name": "rphFraudRxPanel",
          "title": "Fraudulent Prescription Questions",
          "description": "[Click Me](http://www.google.com)",
          "elements": [
            {
              "type": "text",
              "name": "question1",
              "title": "Test"
            }
          ]
        }
      ]
    }
  ]
}
```
2. Make sure to add markdown library

**Expected behavior**
Click to work and link to fire.

**Screenshots**

**Please complete the following information:**
- Browser: chrome
- JS framework/library: JQuery
- SurveyJS version: 1.9.122

**Comment by JaneSjs** [comment]
Hi @gregpawlowski,
I created the following demo and confirmed that your Markdown works correctly. 
Please run [this demo](https://plnkr.co/edit/CbXlaIniDuvx4Zri), open a preview in a separate tab and test these links. You'll be correctly navigated to a given URL.

https://github.com/user-attachments/assets/8c19cc56-9698-456a-98c4-976df706ec1a
