### ISSUE TITLE
A custom expression property doesn't work for 'multipletextitem'

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#9056]
A usage scenario: update Multiple Textboxes' placeholders based on another question's value.
[T20719 - Can I adjust multiple textboxes settings according to dropdown selection?](https://surveyjs.answerdesk.io/internal/ticket/details/T20719)
***
[View Demo](https://plnkr.co/edit/8BYEZ0iRBxQ2w4Cg)
```js
Survey.Serializer.addProperty('multipletextitem', {
    name: "placeholderExpression",
    type: "expression",
    onExecuteExpression: (obj, res) => {
        debugger
        obj.placeholer = res;
    }
});
```
The `onExecuteExpression` function is not raised when selecting another `question1` item.

**Comment by andrewtelnov** [comment]
@JaneSjs Here is [the working example](https://plnkr.co/edit/nOOtVNKwX5b9pTeG) and code:

```js
Survey.Serializer.addProperty('text', {
    name: "placeholderExpression",
    type: "expression",
    onExecuteExpression: (obj, res) => {
        obj.placeholder = res;
    }
});
Survey.Serializer.addProperty('multipletextitem', {
    name: "placeholderExpression",
    type: "expression",
    onGetValue: (obj) => { return obj.placeholderExpression; },
    onSetValue: (obj, val) => { 
        obj.placeholderExpression = val; }
});

```
Thank you,
Andrew
