### ISSUE TITLE
Composite Elements - Custom Mask Settings (DateTime) are reset

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#9057]
T20721 - Composite question
https://surveyjs.answerdesk.io/internal/ticket/details/T20721
***
[View Demo](https://codesandbox.io/p/sandbox/exciting-andras-w733f4?file=%2Fsrc%2FSurveyCreatorComponent.jsx&workspaceId=c1318f77-19a4-463d-b58a-86fcfde8c6c4)

You can reproduce the following issues:
- [ ] If you close a property grid, an input field's mask disappears on a design surface.
- [ ] If you select a Boolean question value in preview, the mask disappears.

https://github.com/user-attachments/assets/f9a3e35d-2d42-4b0c-81e4-1396abb71993

**Comment by andrewtelnov** [comment]
@JaneSjs You need to create different mask objects for different mask type. That is why you are having a problems with loading. You can use `onSetValue` & `onGetValue` callback functions to implement this.

Please use the following code to register your properties:
```js
function getCompositeInput(question) {
  return question.contentPanel.getQuestionByName("q1");
}
```

```js
  onInit() {
    Serializer.addProperties("myComposite", [
      {
        name: "maskType",
        category: "mask",
        default: "none",
        visibleIndex: 0,
        choices: ["none", "pattern", "datetime", "numeric", "currency"],
        onSetValue: function (obj, value) {
          obj.setPropertyValue("maskType", value);
          const q = getCompositeInput(obj);
          if (q) q.maskType = value;
        },
      },
      {
        name: "maskSettings:masksettings",
        category: "mask",
        visibleIndex: 1,
        dependsOn: ["maskType"],
        onGetValue: function (obj) {
          const q = getCompositeInput(obj);
          return q ? q.maskSettings : {};
        },
        onSetValue: function (obj, value) {
          const q = getCompositeInput(obj);
          if (q) {
            q.maskSettings.setData(value);
          }
        },
      },
    ]);
  },

```
Here is [the example](https://codesandbox.io/p/sandbox/admiring-maxwell-yxpm9z?file=%2Fsrc%2FSurveyCreatorComponent.jsx).

Thank you,
Andrew
