### ISSUE TITLE
Add don't know to matrix questions

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#9079]
**Is your feature request related to a problem? Please describe.**
A matrix is a shorthand for multiple individual radiogroup questions. However radiogroups support all kinds of special values, don't know, refuse to answer etc...

In a `matrixdropdown` question you can use this by adding a column of the radiogroup type, but this is a workaround.
A standard matrix question should support these special options by default. (One could argue that the whole `matrix` question type is redundant since it can always be emulated via `matrixdropdown`).

**Describe the solution you'd like**
Make the options for columns in the matrix question type the similar to choices in a radiogroup.
This means adding: 
![image](https://github.com/user-attachments/assets/0a67aaf9-9bc1-4a33-b91f-f9d0d2707995)

**Describe alternatives you've considered**
Several workarounds exist for end users:
1. Use a special value to mean _Don't know_, this allows them to use a normal `matrix` question but doesn't clearly communicate the intention and is prone to errors in analysis.
2. Use a `matrixdropdown` question with 1 radiogroup column

**Comment by JaneSjs** [comment]
Hi @SamMousa,
We appreciate you sharing your ideas.

A Single-Select Matrix was not designed to display special choices such as None, Other, Don't Know, Refuse to Answer. In fact, you can easily add more columns to replicate the `None`, `Don't Know`, and `Refuse to Answer` options.
```
{
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "matrix",
          "name": "question1",
          "columns": [
            "Column 1",
            "Column 2",
            "Column 3",
            {
              "value": "none",
              "text": "None"
            },
            {
              "value": "dontKnow",
              "text": "Don't Know"
            },
            {
              "value": "refuse",
              "text": "Refuse to Answer"
            }
          ],
          "rows": [
            "Row 1",
            "Row 2"
          ]
        }
      ]
    }
  ]
}
```
![Image](https://github.com/user-attachments/assets/e173ba50-2dd6-4330-8971-a546c1cf0cde)

If you additionally wish to display the Other option which would display an additional input field, consider using a Multi-Select Matrix and a Radiogroup column:
```
{
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "matrixdropdown",
          "name": "question1",
          "columns": [
            {
              "name": "Column 1",
              "cellType": "radiogroup",
              "showInMultipleColumns": true,
              "choices": [
                {
                  "value": "item1",
                  "text": "Item 1"
                },
                {
                  "value": "item2",
                  "text": "Item 2"
                },
                {
                  "value": "item3",
                  "text": "Item 3"
                }
              ],
              "showOtherItem": true,
              "showNoneItem": true,
              "showRefuseItem": true,
              "showDontKnowItem": true
            }
          ],
          "choices": [
            1,
            2,
            3,
            4,
            5
          ],
          "rows": [
            "Row 1",
            "Row 2"
          ]
        }
      ]
    }
  ]
}
```
![Image](https://github.com/user-attachments/assets/11467548-5dea-4310-b6ed-bba30ca99a4f)

Let us know if you have further questions.

**Comment by SamMousa** [comment]
The solutions you propose are workarounds, I said this literally in my issue. 
I'm aware of the workaround, but why does the matrix question exist? Matrix dropdown can do all the things it can.
I'll tell you why, it exists because it gives easier access to a common use case.
So I'm creating a feature request to improve the common case of a matrix with special option values.

This is not completed, either it should be reopened or closed as won't fix. But you did not add anything in your reply that was not already in my issue description.
