### ISSUE TITLE
Matrix question radio button has no inner circle when focused

### ISSUE THREAD

**Issue by jatoko** [surveyjs/survey-library#9086]
**Describe the bug**
When selecting an option in an altenate row in a matrix question, the radio button has no inner circle (see screenshot).

**Steps to reproduce**

1. Go to https://surveyjs.io/form-library/examples/single-selection-matrix-table-question/reactjs#
2. Click on any response for an alternate row (i.e., a row with gray background)
3. The focused radio button has no inner circle, only an outer circle.

**Expected behavior**
The focused radio button should have an inner circle, too.

**Screenshots**
![image](https://github.com/user-attachments/assets/58f960ec-feb9-488a-a3aa-fd554b323040)

**Please complete the following information:**
- Browser: Chrome, Firefox
- Browser version: 131.0.6778.70/ 132
- JS framework/library: React
- SurveyJS version: latest on surveyjs website
- Device: Desktop

**Additional context**
no

**Comment by dipak-kumawat** [comment]
attempt #9086

**Comment by jatoko** [comment]
> attempt #9086

Just to make sure: Is there another issue that should have been linked (e.g., a fix), or is it correct that the reply links back to this issue ("9086")?

**Comment by JaneSjs** [comment]
Hello @jatoko,
Thank you for reporting this issue. I reproduced it and forwarded to our developers. We'll update this thread as soon as we get any news to share.

https://github.com/user-attachments/assets/2a0ca2d4-a42d-4615-8487-7f7a39b5302a

Please stay tuned.
