### ISSUE TITLE
Date input type locale

### ISSUE THREAD

**Issue by stormbinary** [surveyjs/survey-library#9100]
Hello,
I have looked at the code example with inputType  as date. 
Is there any code snippets for setting the date locale,on the date picker, to other than English, for example Chinese or Hebrew?
Thank you

**Comment by JaneSjs** [comment]
Hello @stormbinary,
A [Text question with inputType: "date"](https://surveyjs.io/form-library/examples/datetime-entry-question/) uses a standard HTML [<input type="date">](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) element. As stated [at MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date), the displayed date is formatted based on the locale of the user's browser. Therefore, if you wish to change the locale of your date input field, you need to change the browser locale.

Let us know if you have any further questions.
