### ISSUE TITLE
dropdown depend on two other question

### ISSUE THREAD

**Issue by hapiKzm** [surveyjs/survey-library#9128]
hi i have drop down that use webservice to get data the url is something like this 
```
question.type = 'dropdown'
question.choicesByUrl = {
   url: '/search/list?key=dropdown&firstQName={firstQName}&secondQName={secondQName}',
   valueName: 'id',
   titleName: 'name',
```
The problem is that both the first and second questions currently require a value for the request to be triggered. However, I want the request to be triggered when either the firstQuestion or secondQuestion has a value, or when neither of them has a value.

**Comment by JaneSjs** [comment]
Hello @hapiKzm,
To achieve your goal, enable the lazy loading feature and programmatically send a fetch request using the [onChoicesLazyLoad](https://surveyjs.io/form-library/documentation/surveymodel#onChoicesLazyLoad) event. Within this event, obtain values of target survey fields using the `survey.getValue('firstQName')` / `survey.getValue('secondQName')` function. For more information, please refer to: [Lazy Loading](https://surveyjs.io/form-library/examples/lazy-loading-dropdown/).

Please feel free to reactivate this thread if you require further assistance.
