### ISSUE TITLE
use value of ranking question in expression

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#9129]
**Describe the bug**
I cannot use the value of a ranking question (or any other array for that matter) in a condition.

**Steps to reproduce**

1. Create a ranking question with options X, Y, Z
2. Create a follow up question that is only visible if the highest ranked item from the ranking question is item X

**Expected behavior**
This should be possible, I'd expect (and thought I even remembered this working in the past) any array value to be accessible using bracket notation.

**Additional context**
https://surveyjs.answerdesk.io/ticket/details/t20949/can-t-use-ranking-question-in-conditions-or-dynamic-texts

**Comment by JaneSjs** [comment]
Hi @SamMousa,
Would you please share a sample survey JSON which reproduces the issue?

I created this sample and confirmed that a question appears when a Ranking question contains a specified item sequence: `"visibleIf": "{question1} = ['x', 'z', 'y']"`
```
{
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "ranking",
          "name": "question1",
          "commentText": "Your Comments",
          "choices": [
            {
              "value": "x",
              "text": "X"
            },
            {
              "value": "y",
              "text": "Y"
            },
            {
              "value": "z",
              "text": "Z"
            }
          ]
        },
        {
          "type": "text",
          "name": "question2",
          "visibleIf": "{question1} = ['x', 'z', 'y']"
        }
      ]
    }
  ]
}
```
![image](https://github.com/user-attachments/assets/03cd0960-150c-480f-a99b-357de552c36a)

I look forward to your reply.

**Comment by SamMousa** [comment]
Your example checks and exact ordering, but i only want to order based on the highest ranked element.

So imagine the survey like this:

Q1, ranking: Rank the colors based on your preference for a car.
- Red
- Yellow
- Black

Q2, text: Why do you like **black** cars the most?

I want to replace the bold black with the first chosen from the ranking. Alternatively I want to make multiple versions of Q2, one for each color and only show the correct one.

**Comment by JaneSjs** [comment]
Hi @SamMousa,
Thank you for the update. You can implement a [custom function](https://surveyjs.io/form-library/documentation/design-survey/conditional-logic#implement-a-custom-function) and retrieve the display text of a top ranked value programmatically. 
```
function getTopRankedItem(params){
    const rankValue = params[0];
    if(!!rankValue && rankValue.length > 0) {        
        const topItem = rankValue[0];
        const rankingQuestion = this.survey.getQuestionByName('rankCars');
        const topChoice = Survey.ItemValue.getItemByValue(rankingQuestion.choices, topItem);
        return topChoice.text;    
    }
}
Survey.FunctionFactory.Instance.register('getTopRankedItem', getTopRankedItem);
```
Consider the following demo: [View Plunker](https://plnkr.co/edit/vhngK0MNfxcGoTOY).

https://github.com/user-attachments/assets/e27029ea-9cc6-412d-a3e8-48919cf38b2c

Let me know what you think.

**Comment by JaneSjs** [comment]
Hi @SamMousa,
You can actually obtain an item by an index in survey expressions. If you wish to display a specific item in a question's title, create a [calculated field](https://surveyjs.io/form-library/documentation/design-survey/conditional-logic#calculated-values) and embed it in a question's title text. Consider the following JSON:
```
{
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "ranking",
          "name": "cars",
          "title": "Rank cars by preference from most to least favorite",
          "commentText": "Your Comments",
          "choices": [
            "Audi",
            "BMW",
            "Mercedes Ben"
          ]
        },
        {
          "type": "text",
          "name": "question3",
          "visibleIf": "{cars} notempty",
          "title": "Why do you like {topRankedItem} cars the most?"
        }
      ]
    }
  ],
  "calculatedValues": [
    {
      "name": "topRankedItem",
      "expression": " {cars[0]}"
    }
  ]
}
```
![Image](https://github.com/user-attachments/assets/eca638c7-39bf-4836-9f0a-f069616e9ebb)

Let me know if you have more questions.

**Comment by SamMousa** [comment]
Thank you! That is a proper solution!
