### ISSUE TITLE
How to edit / use function when using hostedJS solution?

### ISSUE THREAD

**Issue by gamingchange113** [surveyjs/survey-library#9140]
I am trying to launch my survey using the hostedJS function, vs hosting independently, but I need to be able to generate a random, 6-digit number at the end of the survey for respondents to verify completion. I found several JavaScript functions that could do this - in particular the math.random function, but I don't know how to push that function to the hosted SurveyJS solution. The survey editor only allows editing of the JSON, not the Javascript code / driver shell... So for the life of me I can't figure out how to actually utilize the math.random function in this hosted solution. 

Can someone help???

**Comment by gamingchange113** [comment]
Note that I have also tried creating a calculated value (custom variable) to generate a random number, but haven't found an expression that the JSON will recognize. Very much open to that solution, if there is an expression that works within JSON for this purpose.

**Comment by JaneSjs** [comment]
Hello,
If you wish to run and execute a custom function when you run a SurveyJS Form, you can register a custom function and use it in survey expressions. For more information on how to register custom JS functions and use it within SurveyJS Forms, please visit [Custom Functions](https://surveyjs.io/form-library/documentation/design-survey/conditional-logic#custom-functions).

Let me know if this is what you need.

**Comment by gamingchange113** [comment]
Hi Jane. I don't believe this addresses my issue. I don't _believe_ I need to create a custom function (e.g., I found reference to a function that would serve my purpose, below, in the previous helpdesk ticket linked below). I'm struggling with where to input a function, given that I'm publishing with the hosted SurveyJS solution. (I don't see any wrapper code to enter such a function.) Is there a way to implement a function, e.g., math.random, within the JSON? I hope this question makes sense, as I have now spent two days trying to solve this issue, unsuccessfully (and am now several days behind my deadline!). Thank you. 

function random_func(params: any[]): any {
 return Math.random();
}
// The function is registered for use in SurveyJS expressions.
FunctionFactory.Instance.register("random", random_func);

Ticket link: https://surveyjs.answerdesk.io/ticket/details/t7218/random-number

**Comment by tsv2013** [comment]
@gamingchange113 If under the "hostedJS function" you mean the https://surveyjs.io/service/mysurveys page or another page on the https://surveyjs.io site, then the answer is no - you can't write any custom JS code on our site. In order to use it you need to implement a self-hosted solutiuon.

**Comment by tsv2013** [comment]
> I would not be able to use a function like math.random via a the surveyjs site? 

exactly
