### ISSUE TITLE
Ability to sum values in a single select matrix

### ISSUE THREAD

**Issue by digiscapeuk** [surveyjs/survey-library#9150]
Not sure if I'm just missing something in the documentation but it seems like you can't easily sum the values across single select matrix questions.

Consider a scenario where you have a large number of questions all with the common answer style of Low/Medium/High where the responses map to the scores 1/2/3.  If you want to have an expression that scores all sub question(rows) in the matrix you need to manually build an expression and refer to each row individually.

I'd like a function to just get the sum of the values across all rows that have a selection but can't see a way of doing it without writing a manual expression across each of the rows.

**Comment by JaneSjs** [comment]
Hi @digiscapeuk,
You can use a Multi-Select Matrix and calculate values over matrixes using the corresponding ~inArray function. For instance, consider the [`countInArray`](https://surveyjs.io/form-library/documentation/design-survey/conditional-logic#countinarray) function.
```
{
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "matrixdropdown",
          "name": "question1",
          "columns": [
            {
              "name": "options",
              "title": "options",
              "cellType": "radiogroup",
              "showInMultipleColumns": true,
              "choices": [
                {
                  "value": 1,
                  "text": "Low"
                },
                {
                  "value": 2,
                  "text": "Medium"
                },
                {
                  "value": 3,
                  "text": "High"
                }
              ]
            }
          ],
          "rows": [
            "Row 1",
            "Row 2",
            "Row 3",
            "Row 4",
            "Row 5"
          ]
        },
        {
          "type": "expression",
          "name": "question2",
          "title": "Low Count",
          "expression": "countInArray({question1}, 'options', {options} = 1)"
        },
        {
          "type": "expression",
          "name": "question3",
          "startWithNewLine": false,
          "title": "Medium Count",
          "expression": "countInArray({question1}, 'options', {options} = 2)"
        },
        {
          "type": "expression",
          "name": "question4",
          "startWithNewLine": false,
          "title": "High Count",
          "expression": "countInArray({question1}, 'options', {options} = 3)"
        }
      ]
    }
  ]
}
```
![image](https://github.com/user-attachments/assets/c0080991-472a-44d2-82ba-2db28a8862a5)
