### ISSUE TITLE
Currency Input Mask - The expression result is calculated incorrectly when a form starts

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#9155]
T21058 - Arithmetic operations with Input masking are not working as expected
https://surveyjs.answerdesk.io/internal/ticket/details/T21058
***
[View Demo](https://plnkr.co/edit/0EdHc2EulxZAhSUM)

When a form starts, the expression result is incorrect:
![image](https://github.com/user-attachments/assets/9d7369ae-4bc4-498c-b160-5299c5a86d73)

If you click an existing value, the result is recalculated and appears correctly:
![image](https://github.com/user-attachments/assets/791eb53e-a53a-4967-9075-00f405c7cac9)

**Comment by OlgaLarina** [comment]
@JaneSjs , if you set "saveMaskedValue" is true, then the default value should be masked too - "defaultValue": "500,000".
