### ISSUE TITLE
Request: ability to add a class name to a question

### ISSUE THREAD

**Issue by murrah** [surveyjs/survey-library#917]
### Are you requesting a feature, reporting a bug or ask a question?
Feature

### What is the current behavior?
I am currently exploring SurveyJS and generating a few test surveys using the online survey designer. There are some CSS changes I woud like to make "standard" for me (see below). At present I need to assign class names via event listeners on a survey.

### What is the expected behavior?
I would like to be able to assign a class name (string) to a question in the Survey Designer / JSON. That way, I can easily put the css in one stylesheet I use for multiple surveys and not have to bother with event listeners etc. 

#### Provide the test code and the tested page URL (if applicable)
Eg. this is generic CSS I use to make ALL table questions equal widths. Ideally, if I could use a class name instead of the surveyjs class selector I could selectively apply this css. I think there are lots of places this could be useful.

	/* Generic table formatting */
	.table {
		table-layout: fixed;
	}
	.table th,td { text-align:center; }

Thanks for a fantastic product!

**Comment by tsv2013** [comment]
You can add cusom CSS classes using 2 approaches:
 - static - to all questions of givben type - https://surveyjs.io/Examples/Library/?id=survey-customcss&platform=Knockoutjs&theme=default
 - dynamic - customize classes on event (onUpdateQuestionCssClasses) - https://surveyjs.io/Examples/Library/?id=survey-cssclasses&platform=jQuery&theme=default

Does it fit your needs?

**Comment by andrewtelnov** [comment]
It can be done by adding a custom property and by using [survey.onUpdateQuestionCssClasses](https://surveyjs.io/Documentation/Library?id=surveymodel#onUpdateQuestionCssClasses) event.

Thank you,
Andrew
