### ISSUE TITLE
Multipletext numeric validator allows letter e

### ISSUE THREAD

**Issue by yogat3ch** [surveyjs/survey-library#9190]
**Describe the bug**
I'm running the Wordpress SurveyJS plugin Version 1.12.4.
I'm using a `multipletext` question type with the following JSON:
```json
 {
      
          "type": "multipletext",
          "name": "NY_fee_suggest_spring",
          "visibleIf": "{NY_fee_change_spring} = true",
          "title": "What is a reasonable Spring season vending fee that includes additional funding for promotional efforts (considering that the current vendor fee is $200 for the season or $20 per week)?",
          "items": [
            {
              "name": "Per season",
              "inputType": "number",
              "title": "Per season ($)",
              "validators": [
                {
                  "type": "numeric",
                  "text": "Value must be a number greater than 0",
                  "minValue": 0
                }
              ]
            },
            {
              "name": "Per week",
              "inputType": "number",
              "title": "Per week ($)",
              "validators": [
                {
                  "type": "numeric",
                  "text": "Value must be a number greater than 0",
                  "minValue": 0
                }
              ]
            }
          ]
        
        }
```
Each of the multipletext items has a numeric validator. 
Because the field is a "number" field, I can't enter any of the letters of the alphabet when I try, except for the letter e. This letter e also seems to be missed by the validator. Here's a [short video](https://www.loom.com/share/cef4118c4eb64e55917f60ff4d20e528?sid=4cef8f91-3ca5-423b-964e-640f96836c51) demonstrating what happens in Preview mode.

**Steps to reproduce**

1. Go to the [Survey](https://themindful.life/harmony-crossing-survey/)
2. Click at least one month checkbox in the first question
3. Type 2 or greater for the second question, and hit next.
4. Scroll to Q11, answer yes, a question will reveal
5. enter `e` for one of the fields
6. Hit next

**Expected behavior**
Entering the letter `e` should show the error message "Value must be a number greater than 0" when clicking the next button and prevent further progress.

**Screenshots**
See video

**Please complete the following information:**
- Browser: Chrome
- Browser version: 131.0.6778.140
- JS framework/library: Wordpress plugin
- SurveyJS version: 1.12.4
- Device: Apple M1 Pro running Sonoma 14.6.1 (23G93)

Thanks for the exceptional plugin. The straightforward implementation of complex survey logic is surprisingly easy with the sleek interface!

**Comment by JaneSjs** [comment]
Hello @yogat3ch,
`e` represents exponents, therefore, it is available for numeric input types. A similar issue was already discussed in another thread: https://surveyjs.answerdesk.io/ticket/details/t3576/input-type-number-allows-e-letter-to-type.

 If you wish to prevent users from entering the `e` letter, you can enable [a Numeric input mask](https://surveyjs.io/form-library/documentation/api-reference/inputmasknumeric) for your Multiple Text items. Consider the updated JSON:
```
{
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "multipletext",
          "name": "NY_fee_suggest_spring",
          "title": "What is a reasonable Spring season vending fee that includes additional funding for promotional efforts (considering that the current vendor fee is $200 for the season or $20 per week)?",
          "items": [
            {
              "name": "Per season",
              "maskType": "numeric",
              "title": "Per season ($)",
              "validators": [
                {
                  "type": "numeric",
                  "text": "Value must be a number greater than 0",
                  "minValue": 0
                }
              ]
            },
            {
              "name": "Per week",
              "maskType": "numeric",
              "maskSettings": {
                "precision": 0,
                "min": 0
              },
              "title": "Per week ($)",
              "validators": [
                {
                  "type": "numeric",
                  "text": "Value must be a number greater than 0",
                  "minValue": 0
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```
Let me know if you have any questions.

**Comment by yogat3ch** [comment]
Hi @JaneSjs, thanks for clarifying why the `e` is valid input, that makes sense! Thanks for linking the post, I did not find that post when I searched for the possible reason behind why the `e` was being allowed.

Appreciative of the help!
