### ISSUE TITLE
SurveyModel: renamings onDragDropAllow 

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-library#9211]
onDragDropAllow -> onAllowDragDrop
   - options.target -> options.draggedElement
   - options.source -> options.fromElement
   - options.parent -> options.toElement
   - options.insertBefore -> options.insertBeforeElement
   - options.insertAfter -> options.insertAfterElement

**Comment by novikov82** [comment]
already done https://github.com/surveyjs/survey-library/pull/7370/files
no need to rename event
