### ISSUE TITLE
[Request] Render question titles in <label> instead of <h5>

### ISSUE THREAD

**Issue by kaphert** [surveyjs/survey-library#928]
### Are you requesting a feature, reporting a bug or ask a question?
Feature

### What is the current behavior?
The titles of form fields are rendered within a `<h5>` and `<span>` tag. 

Taken from Vue version:
```
<h5><span style="position: static;"><span style="position: static;">Phone</span></span></h5>
```

### What is the expected behavior?
For screen readers and usability it would be better if this could be rendered in a `<label for="{fieldId}">` tag. 

```
<label for="phone_field_id">Phone</label>
```

* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: v1.0.7

**Comment by tsv2013** [comment]
You can modifiy rendered markup in the handler of the onAfterRenderQuestion event, described here - https://surveyjs.io/Documentation/Library/?id=surveymodel#onAfterRenderQuestion

**Comment by kaphert** [comment]
Thank you that would be a solution for me. But my request was more to add it as a default to the library because that would make more sense to me. 

But I can imagine that changing this would have some impact on existing surveys.

**Comment by tsv2013** [comment]
Yes, it can affect surveys, customized via css

**Comment by kaphert** [comment]
For the one who is interested. The following event listener will do the trick by replacing the `h5` tag with a `label` tag. 
```
survey.onAfterRenderQuestion.add(function (sender, options) {
    let el = options.htmlElement;
    let title = el.getElementsByTagName('H5')[0];
    if (title) {
        title.outerHTML = '<label for="'+ options.question.inputId +'" class="'+ title.className +'">'+ title.innerHTML +'</label>';
    }
});
```

**Comment by kaphert** [comment]
Above solution is not working because of: https://github.com/surveyjs/surveyjs/issues/930
