### ISSUE TITLE
requiredErrorText not displaying for multipletext items

### ISSUE THREAD

**Issue by murrah** [surveyjs/survey-library#937]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
requiredErrorText not displaying for multipletext items. See code snippet.

### What is the expected behavior?
requiredErrorText should display for each item if set. If not set, display default.

#### Provide the test code and the tested page URL (if applicable)

    {
        "type": "multipletext",
        "name": "contactreq",
        "visible": false,
        "visibleIf": "{sendresults}=true",
        "title": "If you would like to stay in touch ( no spam or pressure! ) please leave your details below.",
        "isRequired": true,
        "requiredErrorText":"Please enter contact details",          // Displays "Please enter contact details"
        "items": [
        {
            "name": "firstname",
            "isRequired": true,
            "requiredErrorText":"Please enter your first name",      // Displays "Please answer the question"  
            "title": "First name"
        },
        {
            "name": "lastname",
            "title": "Last name"
        },
        {
            "name": "email",
            "inputType": "email",
            "title": "Email",
            "validators": [
            {
                "type": "email"
            }]
        }]
    }

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.9

**Comment by andrewtelnov** [comment]
@murrah We do not have requiredErrorText in Multiple text item yet.
We have a task a in our TODO list "Change text item into QuestionText". It would solve some issues and additionally it solves your issue as well.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@murrah I would recommend to use Panel and three text questions inside it. It does everything you need and more :)

Thank you,
Andrew

**Comment by boxbrosg2** [comment]
I was looking for this functionality and it seems it was on your TODO list but hasn't been addressed yet. Any chance this can bubble up again after a year?

Using a panel is nice but it treats each question as a new one with a question number and value and we would prefer to collect multiple pieces of data at once.

**Comment by andrewtelnov** [comment]
@boxbrosg2 I have added the needed changes via two commits above. This property will be available from the next minor update on the next week.

Thank you,
Andrew
SurveyJS Team

**Comment by boxbrosg2** [comment]
Thanks Andrew! I see the property within the Mutlitext items now. It looks like the error text is ignoring the survey QuestionErrorLocaiton. Not sure if that was an unintentional change or not but the error is always appearing above the question even when the survey is set to below.

**Comment by boxbrosg2** [comment]
Just following up to see if you noticed my error text location issue. Appreciate all the help!

**Comment by andrewtelnov** [comment]
@boxbrosg2 I have implemented this functionality via the commit above.

Thank you,
Andrew
