### ISSUE TITLE
Could not find RTL support [Question]

### ISSUE THREAD

**Issue by Mulli** [surveyjs/survey-library#945]
I could not find any mention in relation with Right to Left languages.
Is it supported & Documented? or a new feature request?
Thanks!

**Comment by dmitrykurmanov** [comment]
Hello! RTL should be supported on the browser level. If something doesn't work with our widgets on your browser with RTL settings, we would consider this as a bug and it will be fixed. Just let us know about the issue.
I've checked it with one of our examples:
![image](https://user-images.githubusercontent.com/22315929/36481075-b4035b7c-171f-11e8-8a8f-2c356c75fc26.png)

**Comment by Mulli** [comment]
Great! Thanks for the quick reply. I shall update soon.

**Comment by sashad2003** [comment]
Добрый день Дмитри,
У меня возникла та же проблема с поддержкой RTL.
На странице прописано dir="rtl" и вся страница отображается правильно но это не срабатывает на все элементы. К примеру "titleLocation". В настройках у меня есть возможность выбрать отображение с лева но на Иврите и на Арабском оно должно быть с права. Все float, margin, padding, text-align и тд которые были left должны превратиться в right и на оборот. На снимке экрана что вы показали видно что текст все равно приравнивается к левой стороне и кнопки 1,2,3,4,5 в не правильном порядке потому что при RTL  они должны отображаться в зеркальном порядке 5,4,3,2,1.
Можете пожалуйста это исправить?
Заранее огромное СПС!

**Comment by jestintab** [comment]
Hi,
To display contents  like the screenshot above from right to left, using some properties like `isRTL: true.`
Please help. Thank you.

**Comment by tsv2013** [comment]
@jestintab You can simply add to body tag the
```CSS
    direction: rtl;
```
CSS style

**Comment by tsv2013** [comment]
@sashad2003 We are sorry that we lost your comment since the issue was closed. I've reopened the issue. We'll keep your suggestions on our radar. Any community contribution in SurveyJS library is also welcome.
