### ISSUE TITLE
How to add odd/even question background highlightling?

### ISSUE THREAD

**Issue by halexiev-hedgeserv** [surveyjs/survey-library#948]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the question?

How to add odd/even background highlighting for questions?

### What is the expected behavior?

An event handler for question number change or equivalent where one can update the css classes of the questions.

### How would you reproduce the current behavior (if this is a bug)?

It seems like there are always edge cases that pop up and adjacent questions with same highlight as there is no appropriate place or event handler for this type of logic.

Turns out that css alone is not enough as questions might be inside and outside of panels on the same page and therefore the css selectors cannot handle this correctly.

### Specify your

* browser: chrome
* browser version: 63
* surveyjs platform (angular or react or jquery or knockout or vue): angular cli 
* surveyjs version: 1.0.10

**Comment by tsv2013** [comment]
This is already implemented in our default theme:
https://surveyjs.io/Examples/Library?id=real-productfeedback&platform=jQuery&theme=default

You can check

https://github.com/surveyjs/surveyjs/blob/c2ad3c2cac79a6380d9cd7549228321c5637a0da/src/main.scss#L155-L166

**Comment by halexiev-hedgeserv** [comment]
@tsv2013 Just add `survey.isSinglePage = true;` and see what happens:

https://plnkr.co/edit/BLnX7cWcXEKYSeSeRfpy?p=preview

Not doable in css only imho - it would be best if there is an event handler just **before** the survey/page/panel/question gets rendered so there are not multiple dom updates. 

Otherwise this is what seems to work for us at the moment:

```
this.survey.onVisibleChanged.add((survey, options) => {
    let even = true;

    survey.getAllQuestions(true).forEach(question => {
      const questionBase = question as Survey.QuestionBase;
      if (questionBase.visibleIndex !== -1) {
        const questionElement = this.elementById(questionBase.id);
        this.toggleClass(questionElement, 'even', even = !even);
      }
    });
}); 
```

This way no matter how many nested panels questions are in they are properly labeled odd/even in the context of the whole survey.

**Comment by tsv2013** [comment]
@halexiev-hedgeserv By the way - what is your main scenario? Why are you using `survey.isSinglePage = true;` mode? You can just put all questions on one page - and all should work out-of-the-box...

**Comment by halexiev-hedgeserv** [comment]
@tsv2013 We have a very big survey with lots of different questions, including html ones which have no number and in our case do not need to be odd/even highlighted (the `questionBase.visibleIndex !== -1` check above).

As for isSinglePage - in our case we need all questions shown right from the start. Since the survey is very large we group questions in panels and within these root panels there are other child panels.
Once you have this hierarchy css alone cannot do it because in the context of the entire survey you might have, for example, a panel with 3 questions (1, 2, 3) and another adjacent panel with few more - css will not make the first question of the second panel even highlighted because it's first child.

**Comment by dmitrykurmanov** [comment]
I think we need to fix odd/even css background for the `isSinglePage ` mode. May be in this mode we need to add additional `single-mode` css class to the root.

**Comment by halexiev-hedgeserv** [comment]
@dmitrykurmanov Not sure the issue is with the page mode though - you could have nested panels in both modes so css would still not work because, for example, nth-child selector works for immediate parents, but not for parents few levels up the dom tree.

In our case  we want the odd/even scheme to be applied in the context of all questions, so no matter how many nested panels a particular question is in it needs to be highlighted if its question number is even. 

The code snippet above works regardless of the page mode and it's all good for us - I just wish there was maybe a more appropriate listener which we can use ... maybe before question is actually (re)rendered so we do not perform more dom updates than necessary. 

Would it be possible to have listeners like afterRender, but only this time - beforeRender?

**Comment by andrewtelnov** [comment]
We have it in our modern theme by default now.

Thank you,
Andrew

**Comment by d-mance** [comment]
Hello,
how can I disable this feature? I want all the rows the same white color.
Thanks
