### ISSUE TITLE
Remove Duplication in ChoicesByUrl

### ISSUE THREAD

**Issue by LA95** [surveyjs/survey-library#951]
### Are you requesting a feature, reporting a bug or ask a question?
Requesting a feature

### What is the current behavior?
Using choicesByUrl, if there is duplication of data from the restURL, the duplicates get displayed.

### What is the expected behavior?
Option to remove duplication in the above mentioned scenario. Something like a distinct?

**Comment by tsv2013** [comment]
Whether it will be suitable if we add a callback "onItemsProcess" with array of items that (array) can by modified as one needs before assigned to choices?
