### ISSUE TITLE
Programmatically toggle readOnly option for fields inside a panelDynamic

### ISSUE THREAD

**Issue by ajien** [surveyjs/survey-library#959]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

I'd like to be able to programmatically toggle readOnly option for some of the fields inside a panelDynamic. When using onValueChange, I am only able to use getQuestionByName() to get the panelDynamic, but not the questions inside the panel. It would be really neat if getQuestionByName() also works for nested questions, as in the case of panelDynamic's inner questions. What would be the alternatives to make it work?

**Comment by andrewtelnov** [comment]
@ajien I guess `dynamicPanelQuestion.template.getQuestionByName() ` is what you need.

Thank you,
Andrew

**Comment by ajien** [comment]
Hi, Andrew.

Here's what I did trying to set the readOnly property of several fields in a panel dynamic based on a selected value in one field:

        if(options.value[0].edit_project === 'no') {
            const q = options.question.template.questions;
                q.forEach(function(i) {
                    i.setPropertyValue('readOnly', true);
                });
        }

I can see from console that the readOnly values would change to true, but the fields do not actually refresh and render in readonly mode. What do you think should I do here?

**Comment by andrewtelnov** [comment]
@ajien You have to set it manually for all panels: options.question.panels (array of panels).
You are setting the readOnly into template and panels have been already generated based on this template.

Thank you,
Andrew
