### ISSUE TITLE
Feature Request - Add 'goToPage()' method

### ISSUE THREAD

**Issue by kaphert** [surveyjs/survey-library#976]
### Are you requesting a feature, reporting a bug or ask a question?
feature

### What is the current behavior?
I am adding a survey page step overview. I list all the pages and pages are clickable when they were shown which means: you can go back to a page a user already visited but you can't go to the last page instantly

To prevent odd behavior with being able to skip validation I've added the checks that are done in the `nextPage()` validation myself. Which means: you can only switch pages if the current page does not have errors, do server validation, checkOnPageTriggers. This all works fine but it feels hacky and unnecessary. If some internal logic is added or changed my steps won't work as expected. 

### What is the expected behavior?

My suggestion would be to implement a method: `goToPage(page)` which does all the `nextPage` logic. The current `nextPage` method could than internally use `goToPage()`. 

### Specify your

* surveyjs version: v1.0.11

**Comment by andrewtelnov** [comment]
@kaphert I would sugest to use page.visibleIf property. The page is visible only when the certain expression returns true. survey.visiblePages property returns all curent visible pages.
In this case, if page is invisible, you could not go this page. 
Will it work for your scenario?

Thank you,
Andrew

**Comment by kaphert** [comment]
@andrewtelnov no my request has nothing to do with visibility of the page or I do not understand your response. 

I have on the top of my survey a list of all the pages. 

Lets say: 
1. Enter your name (1 required question: name)
2. Enter your address (1 required question: address)
3. Confirm (overview of the survey) 

A user is only able to click on one of the pages if he saw this page before (wasShown = true). 

If we start the first page (enter your name) is active, page 2 and 3 are not active and `wasShown = false`. So the user can't click on page 2 or 3. 

The user filled in his name and clicks on 'Next' so he ends up at page 2. Because he is now at page 2 he is able to visit page 1 by clicking on the top navigation of page 1. But he is still not able to click on page 3 because he didn't saw this page yet. 

Ok, now the user clicks on 'Page 1' in the top navigation. The user is going back to page 1 and page 1 is now active. The user clears the input of the question on page 1 and now clicks on 'Page 2' in the navigation. If a developer does not handle this manually he is able to go to step 2 without performing all the validation and callbacks. I solved this with my custom code shown below but I think it would be nice if this all would be added to a method called `goToPage()` in surveyjs itself so you can reuse it. 

*Vue example code*
```
<ul>
   <li v-for="(page, index) in survey.visiblePages"
       :key="page.id"
       :class="{active: page.isActive, shown: page.wasShown, disabled: (loading || success)}"
        @click="goToPage(page)"
    >
        <span class="step">{{ (index) + 1 }}.</span>
        <span class="name">{{ page.title }}</span>
    </li>
</ul>
```

and my self made goToPage looks like:
```
goToPage: function(page) {
    // copied from logic of survey.nextPage()
    if (this.survey.isEditMode &&  this.survey.isCurrentPageHasErrors) {
        return;
    }

    if (this.survey.doServerValidation()) {
        return;
    }

    if (page.wasShown && !this.loading && !this.success) {
        this.survey.checkOnPageTriggers();

        this.survey.currentPage = page;
    }
},
```

**Comment by andrewtelnov** [comment]
@kaphert Then I would suggest the following.
Use [page.hasErrors function](https://surveyjs.io/Documentation/Library/?id=pagemodel#hasErrors)
and the code would be:
```
gotToPage: function(page) {
 var pages = this.survey.visiblePages;
  var visibleIndex = pages.indexOf(page);
  var currentIndex = pages.indexOf(this.survey.currentPage);
  if(visibleIndex < 0 || currentIndex < 0) return;
  //go to the previous page, we do need to do any check
  if(currentIndex <= visibleIndex) {
    this.survey.currentPage = page;
  }
  //The current page has an error(s), show it/them
  if(this.survey.currentPage.hasErrors(true, true)) return;
  for(var i = currentIndex + 1; i < visibleIndex; i ++) {
   //check if there is any error in next pages in silent mode
   //do not show any error or focus a question with an error
   if(pages[i].hasErrors(false, false)) return false; //there is an error, can't do anything.
  }
  //There is no error, do next page, send the data and so on.
  this.survey.nextPage();
  //go to the needed page
  this.survey.currentPage = page;
}
```
I have not tested the code above, but you should understand the idea, if there is a typo or something wrong.

Thank you,
Andrew

**Comment by kaphert** [comment]
Thank you for your cooperation. My suggestion is to add such a method to surveyjs instead of every developer have to implement this ourself. The risk of implementing this myself is that as soon as something new is added to surveyjs that does something on a page change or some logic is changed in a release there I also need to update this in my own script.

**Comment by andrewtelnov** [comment]
We have the skiptrigger now. It has "expression" and "gotoName" properties. If expression becomes true, then survey focus the "gotoName" question. If the question is located on another page, then this page becomes current.

Thank you,
Andrew
