### ISSUE TITLE
'Select all' option for checkbox questions

### ISSUE THREAD

**Issue by Lynn42** [surveyjs/survey-library#979]
### Are you requesting a feature, reporting a bug or ask a question?

Requesting a feature

(Possibly this was requested before, sorry if this is the case)

### What is the current behavior?

Right now if you use a checkbox question in your survey, when a user wants to check all answer options, he needs to do so manually. When there are a lot of answer options, this is a lot of work.

### What is the expected behavior?

It would be really nice if a functionality was added to allow you to add a Select All functionality to checkbox questions when building your survey in the surveyJs Editor (similar to adding a 'Has other item' option to a specific question). When this functionality is set to true, the question show an additional checkbox option 'select all' which, when checked, automatically checks all the actual answer options, and when unchecked again, unchecks all answer options.

I would imagine this field to show not in the list of actual answer options, but slightly seperated from it (i.e. above the answer options?) so the user notices it easily.

Ideally, you want to be able to change the text of this option to another than the default 'select all'.

When a user does still manually checks all answer options, you would expect the select all box to be checked automatically to reflect this.

**Comment by bappajubcse05** [comment]
@andrewtelnov Could you please confirm whether it is already released? I am also looking for the same feature.

**Comment by andrewtelnov** [comment]
@bappajubcse05 We don't have this functionality yet. And thank you for posting your request. We may add this task in one of our next week iterations.

Thank you,
Andrew

**Comment by bappajubcse05** [comment]
Hello @andrewtelnov - could you please let me know whether it is already available?

**Comment by andrewtelnov** [comment]
@bappajubcse05 Unfortunately not. It would have a "Implemented" label in this case.
It is in our TODO list, but we did not pick it up yet for the next week iteration.
If more people add a comment here, that they need it, more likely we will do it in the nearest time.

Thank you,
Andrew

**Comment by burlof** [comment]
Hello!
I am trying to change the value of the selectAll but I do not find the way.
I just found this thread and it's just what I need.
Is there any way currently to change the Select All value for a text of your own?
Has that functionality been implemented ???

Thank you.
Greetings!

**Comment by andrewtelnov** [comment]
@burlof @Lynn42 @bappajubcse05 Yes, we have implemented it sometimes ago.
Please look at [this example](https://next.plnkr.co/edit/lxYqwaVixllQ2GYI).

Thank you,
Andrew

**Comment by burlof** [comment]
@andrewtelnov Ok, thank you very much for the solution and especially for the speed of the response :)
