### ISSUE TITLE
enableIf does not work in React

### ISSUE THREAD

**Issue by ajien** [surveyjs/survey-library#981]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

enableIf does not work in React. When the field where the condition relies upon is changed, the field that must be enabled stays in readonly/disabled/display mode.

### What is the expected behavior?

The target field should re-render and update to an editable field.

### Specify your

* browser: Chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version:

**Comment by andrewtelnov** [comment]
@ajien Could you please provide us with an example that reproduce the issue?
Here is the working example: https://plnkr.co/edit/KjvRtM4wIsVlUerfMJks?p=preview

Thank you,
Andrew

**Comment by ajien** [comment]
Thanks, Andrew. It seems to work in Plunker, but could not figure out why
it does not work in my app. I even used the exact codes that I have in my
app component in Plunker and everything works fine.

**Comment by ajien** [comment]
Hi, Dimitri. The error I am seeing related to this issue is this: Warning:
Failed prop type: You provided a `value` prop to a form field without an
`onChange` handler. This will render a read-only field. If the field should
be mutable use `defaultValue`. Otherwise, set either `onChange` or
`readOnly`.

**Comment by andrewtelnov** [comment]
I believe it was fixed.

Thank you,
Andrew
