### ISSUE TITLE
New Question Types

### ISSUE THREAD

**Issue by eferrervaughn** [surveyjs/survey-library#998]
### Are you requesting a feature, reporting a bug or ask a question?

- Asking a Question

### What is the current behavior?

- SurveyJS doesn't have all the question types I want

### What is the expected behavior?

- I want to create a plotting question (place a dot on a matrix). What are the steps to creating a completely new question type? What areas of the code do I have to update?

**Comment by andrewtelnov** [comment]
@eferrervaughn I would suggest look at custom widgets.
Here are [demos](https://surveyjs.io/Examples/Library/?id=custom-widget-select2-tagbox)
Here is [the repo](https://github.com/surveyjs/widgets)
Here is [the demo](https://surveyjs.io/Examples/Builder/?id=customwidgets) for Survey Builder.
For example microfon widget has been added by a guy from Open Source Community, here is [his commit](https://github.com/surveyjs/widgets/commit/7bcf56385486de63ce7993ea8ac07f0edee0a3b0)

Thank you,
Andrew

**Comment by eferrervaughn** [comment]
Thanks Andrew, are there any docs that explain what each property does in the Survey constructor / Widget object? I see:

Settings,
Name,
activatedBy
widgetISLoaded
htmlTemplate
isFit
activatedByChange
isDefaultRender
afterRender
willUnmount

I can infer a good amount of these but I want to make sure I am putting the expected behavior.

**Comment by eferrervaughn** [comment]
I took a stab at commenting the functionality.  If someone could help explain the ones I am not sure about or got might have gotten wrong.
`import noUiSlider from "nouislider";

function init(Survey) {
  var widget = {
    // Reference Name
    name: "nouislider",
    // Name you put in Survey JSON that will show in UI
    title: "noUiSlider",
    // Not sure
    iconName: "icon-nouislider",
    // Has the library loading (optional only if you have external dependencies)
    widgetIsLoaded: function() {
      return typeof noUiSlider != "undefined";
    },
    // Not Sure
    isFit: function(question) {
      return question.getType() === "nouislider";
    },
    // Not sure but I guess its the parent element that houses this question
    htmlTemplate: "<div></div>",
    // how you initiate it in the Survey JSON
    activatedByChanged: function(activatedBy) {
      Survey.JsonObject.metaData.addClass("nouislider", [], null, "empty");
      Survey.JsonObject.metaData.addProperties("nouislider", [
        {
          name: "step:number",
          default: 1
        },
        {
          name: "rangeMin:number",
          default: 0
        },
        {
          name: "rangeMax:number",
          default: 100
        }
      ]);
    },
    // Rendering the actual UI component & handles storing the response values
    afterRender: function(question, el) {
      question.value = (question.rangeMin+question.rangeMax)/2;

      el.style.marginBottom = "50px";
      var slider = noUiSlider.create(el, {
        start: question.value,
        connect: [true, false],
        step: question.step,
        tooltips: true,
        pips: {
          mode: "positions",
          values: [0,25,50,75,100],
          density: 5
        },
        range: {
          min: question.rangeMin,
          max: question.rangeMax
        }
      });
      slider.on("set", function() {
        question.value = slider.get();
      });
      var updateValueHandler = function() {
        slider.set(question.value);
      };
      question.noUiSlider = slider;
      question.valueChangedCallback = updateValueHandler;
    },
    // what to do when removing from DOM
    willUnmount: function(question, el) {
      question.noUiSlider.destroy();
      question.noUiSlider = null;
    }
  };
  // Adds Custom Widget
  Survey.CustomWidgetCollection.Instance.addCustomWidget(widget, "customtype");
}

if (typeof Survey !== "undefined") {
  init(Survey);
}

export default init;`

**Comment by andrewtelnov** [comment]
@eferrervaughn 
You got everything right. Here is some additional information.
// The name of the icon, you may leave it empty or do not define at all
iconName: "icon-nouislider"
//This function is called for every question and nested questions in the survey. 
//If it returns the true, then the custom widget is used for the question.
//In this example. for question with type "nouislider" used this custom widget
//You may use widget for type: "text" and inputType: "date" for example
isFit: function(question) {
return question.getType() === "nouislider";
},
// It is usefull when you create a custom widget based on a generic question, 
//you may define the default html that will be rendered for question input
//For example:
```
    htmlTemplate:
      "<textarea rows='10' cols='80' style: {width:'100%'}></textarea>",

```
htmlTemplate: "",

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@eferrervaughn I have created an [example with comments](https://plnkr.co/edit/HdnYE5?p=preview), please review customwidget.js file

Thank you,
Andrew

**Comment by masciugo** [comment]
@andrewtelnov thanks for the example. I tried to build a custom widget for json text input field. I want just to prettify the content. [Here my attempt](https://plnkr.co/edit/zRFSpr?p=preview). It seems ok but I cannot have it working under react in my app. To be more precise I cannot edit the content. Is possible to have a plunker like the previous you posted but in a React context? The only example I found is [this](https://stackblitz.com/edit/surveyjs-widgets-react) but it use the official library

**Comment by masciugo** [comment]
[I managed to reproduce the behaviour](https://plnkr.co/edit/0YORz4PUolV4sR5ejjc6?p=preview). What's wrong with it? thank you

**Comment by andrewtelnov** [comment]
@eferrervaughn You were using el.value on onValueChangedCallback instead of question.value and you do not setup the correctly json initially. Here is the [corrected fork](https://plnkr.co/edit/blzaM8?p=preview)

Thank you,
Andrew

**Comment by masciugo** [comment]
@andrewtelnov thank you for your help but you probably missed my last update where I reproduced the strange behaviour **with react**. Please have a look if you can. https://plnkr.co/edit/0YORz4PUolV4sR5ejjc6?p=preview

**Comment by eferrervaughn** [comment]
I ended up building one from scratch. Thanks for your help!

**Comment by masciugo** [comment]
@andrewtelnov Sorry if I bother you but can you help me with my last plunk?

**Comment by andrewtelnov** [comment]
Finally added a [documentation](https://surveyjs.io/Documentation/Survey-Creator?id=Create-Custom-Widget).

Thank you,
Andrew
